### PR TITLE
BL-5358 Prevent extra line inserted before pasted text

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2024)

### CODE REVIEW

**Comment by StephenMcConnel** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 113 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2024#-L0RYDM7BGFNCfLP6rwb:-L0RYDM83pfV15QvvyX6:b-naoycp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/eb951363f2081218a3b1316a6e0bb7e49e638424/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L113)):*
> ```XML
>                 endMkr += "<p class='removeMe'></p>"
>             }
>             event.data.dataValue = event.data.dataValue.replace("<p>", "").replace("</p>", endMkr);
> ```

Shouldn't this line be inside the if (paras.length == 1) block?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2024)*

**Comment by StephenMcConnel** [comment]
Looks like a messy problem.  One question, but otherwise probably okay for a fix.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2024#-:-L0RYam4FpX9xAMhDNvf:b-8up1zy)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 113 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2024#-L0RYDM7BGFNCfLP6rwb:-L0dkVLrmV6nMBuaJsam:b80ex4p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/eb951363f2081218a3b1316a6e0bb7e49e638424/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L113)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Shouldn't this line be inside the if (paras.length == 1) block?
</blockquote></details>

No. We always want to remove the <p>...</p> wrapper AROUND the first paragraph content, if any.  What's different in the only-one-paragraph case is inserting the empty paragraph where the end of the original one was (and removing it later).
(Note that replace, in JS, and with the first argument just a string not an RE, only replaces the first occurrence.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2024)*

**Comment by StephenMcConnel** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2024#-:-L0jWfgjUUaNxEhnka7S:bnfp4nl)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2024)*

**Pull request merged**
