### PR TITLE
Change UI language in Collection Chooser (BL-4307)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1542)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Basically good; couple of questions and optional suggestions

---

Reviewed 1 of 5 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs, line 91 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542#-KeL7xbzTO782yuIvmiQ:-KeL7xbzTO782yuIvmiR:biguq3q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1d853d534add5d0e9ba76ab2f09a7daa254aa33b/src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs#L91)):*
> ```Smalltalk
> 					control.Visible = Settings.Default.ShowSendReceive;
> 			}
> 			// We've pulled label1 out into _topRightPanel; do the same check
> ```

Surely for this one specific control we know whether it's tagged sendreceive or not?

---

*[src/BloomExe/CollectionChoosing/OpenCreateCloneControl.designer.cs, line 39 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542#-KeL7lK4h4db7j3E7E7H:-KeL7lK4h4db7j3E7E7I:bfu0oqa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1d853d534add5d0e9ba76ab2f09a7daa254aa33b/src/BloomExe/CollectionChoosing/OpenCreateCloneControl.designer.cs#L39)):*
> ```Smalltalk
> 			this.button9 = new System.Windows.Forms.Button();
> 			this._templateButton = new System.Windows.Forms.Button();
> 			this.button8 = new System.Windows.Forms.Button();
> ```

I haven't checked all this! I assume it's mostly from VS deciding to re-arrange the file...

---

*[src/BloomExe/Workspace/WorkspaceView.cs, line 319 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542#-KeL3QIdrwEj3-06qF1t:-KeL3QIdrwEj3-06qF1u:byyyme9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1d853d534add5d0e9ba76ab2f09a7daa254aa33b/src/BloomExe/Workspace/WorkspaceView.cs#L319)):*
> ```Smalltalk
> 				item.Tag = lang;
> 				item.Click += (sender, args) => UiLanguageMenuItemClickHandler(uiMenuControl, sender as ToolStripItem, finishClickAction);
> 				if (lang.IetfLanguageTag == Settings.Default.UserInterfaceLanguage)
> ```

This is not new, but I'd love to see a comment explaining why we want to do this, both here and in the click handler, where (not very obviously) we do the same thing for the newly chosen language. I guess the thought is that if someone has actually chosen a language, presumably he knows which it is and doesn't need (Korean) or something like that after it, taking up space in the UI? Would it be worth pulling out a common method, something like UpdateMenuTextToShorterNameOfSelection(menu, selectedLang)?
I'd also prefer to see a single line outside the loop, setting the text from the current language, rather than doing it inside the loop only if the current item is the selected one.
(Not a new problem, but always nice to improve things.)

---

*[src/BloomExe/Workspace/WorkspaceView.cs, line 342 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542#-KeL3-npgqroCAIqE3-C:-KeL3-npgqroCAIqE3-D:b-azl1pu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1d853d534add5d0e9ba76ab2f09a7daa254aa33b/src/BloomExe/Workspace/WorkspaceView.cs#L342)):*
> ```Smalltalk
> 		{
> 			// these lines deal with having a smaller workspace window and minimizing the button texts for smaller windows
> 			SaveOriginalButtonTexts();
> ```

If this is a problem it's not new, but this feels like the wrong time to save the original text. A previous invocation of this click action may already have altered the original.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542#-:-KeL8F2VsKPRjZLDXVco:b-4kdtaj)*

**Comment by hatton** [comment]
I think sometimes code reviewers can triple the cost of a feature, just... because.

**Comment by andrew-polk** [comment]
I'm very hesitant to make changes to the original code since we are targeting 3.7. I actually went out of my way to try to ensure I wasn't changing the original code.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs, line 91 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542#-KeL7xbzTO782yuIvmiQ:-KeZ2GLtynaaTxAOjzPl:b8vlly5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1d853d534add5d0e9ba76ab2f09a7daa254aa33b/src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs#L91)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Surely for this one specific control we know whether it's tagged sendreceive or not?
</blockquote></details>

Good point. Not sure why it was done this way. I can change it.

---

*[src/BloomExe/CollectionChoosing/OpenCreateCloneControl.designer.cs, line 39 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542#-KeL7lK4h4db7j3E7E7H:-KeZ1t86-T-AZ7FZIZv6:brd9w2h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1d853d534add5d0e9ba76ab2f09a7daa254aa33b/src/BloomExe/CollectionChoosing/OpenCreateCloneControl.designer.cs#L39)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I haven't checked all this! I assume it's mostly from VS deciding to re-arrange the file...
</blockquote></details>

Yes, VS revamped the file for some reason. (I haven't checked it either.)

---

*[src/BloomExe/Workspace/WorkspaceView.cs, line 319 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542#-KeL3QIdrwEj3-06qF1t:-KeZ2MRAbvHf5jst0J1Y:bdrpqz9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1d853d534add5d0e9ba76ab2f09a7daa254aa33b/src/BloomExe/Workspace/WorkspaceView.cs#L319)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This is not new, but I'd love to see a comment explaining why we want to do this, both here and in the click handler, where (not very obviously) we do the same thing for the newly chosen language. I guess the thought is that if someone has actually chosen a language, presumably he knows which it is and doesn't need (Korean) or something like that after it, taking up space in the UI? Would it be worth pulling out a common method, something like UpdateMenuTextToShorterNameOfSelection(menu, selectedLang)?
I'd also prefer to see a single line outside the loop, setting the text from the current language, rather than doing it inside the loop only if the current item is the selected one.
(Not a new problem, but always nice to improve things.)
</blockquote></details>

For the comment: Isn't this just setting the text of the selected language to display when the dropdown is closed?

For the suggested code change: See 3.7 comment on PR. 

---

*[src/BloomExe/Workspace/WorkspaceView.cs, line 342 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542#-KeL3-npgqroCAIqE3-C:-KeZ2OklNya0ng5OnKgG:bh7yq98) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1d853d534add5d0e9ba76ab2f09a7daa254aa33b/src/BloomExe/Workspace/WorkspaceView.cs#L342)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

If this is a problem it's not new, but this feels like the wrong time to save the original text. A previous invocation of this click action may already have altered the original.
</blockquote></details>

See 3.7 comment on PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542#-:-KeZ2DIcdwfEHjJDM8hi:b-p4ku53)*

**Comment by andrew-polk** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs, line 91 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542#-KeL7xbzTO782yuIvmiQ:-KeZxxUYFmsw--Q0wxu4:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1d853d534add5d0e9ba76ab2f09a7daa254aa33b/src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs#L91)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Good point. Not sure why it was done this way. I can change it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542)*

**Comment by JohnThomson** [comment]
Sorry if I'm dragging things out. I'm willing to go with Andrews judgement whether any of these things are safe enough to do in 3.7 and, if not, whether any of them are worth doing separately in 3.9

---

Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/Workspace/WorkspaceView.cs, line 319 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542#-KeL3QIdrwEj3-06qF1t:-Ke_W15KflV8oqcomngu:b-jcsm0j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1d853d534add5d0e9ba76ab2f09a7daa254aa33b/src/BloomExe/Workspace/WorkspaceView.cs#L319)):*
> Isn't this just setting the text of the selected language to display when the dropdown is closed?
Yes, and it's very unusual to set it to something other than the text of the selected item, as happens automatically when you select it. An unusual thing that has to be done consistently in two places without even a comment linking them feels to me like asking for trouble. But we are trying to keep the change minimal and simple....sigh...is it worth doing a better job in 3.9??

Agreed, minimal change to 3.7 is good, so I guess the weirdness of checking every iteration of a loop to see whether the current one is the one thing we want to change can stand.

---

*[src/BloomExe/Workspace/WorkspaceView.cs, line 342 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542#-KeL3-npgqroCAIqE3-C:-Ke_X0PlEx8XcIUUAyp2:b-8dcsro) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1d853d534add5d0e9ba76ab2f09a7daa254aa33b/src/BloomExe/Workspace/WorkspaceView.cs#L342)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

See 3.7 comment on PR
</blockquote></details>

Preserving an actual discovered bug for fear of creating a new problem might be taking that idea too far, but no one has reported the problem I'm predicting (and I haven't even confirmed it), so maybe you're right to leave it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542#-:-Ke_YAYRGsMJmjKK50_W:bidokk4)*

**Comment by andrew-polk** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/Workspace/WorkspaceView.cs, line 319 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542#-KeL3QIdrwEj3-06qF1t:-KedZij2tz3X932G2vJh:bk81n1y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1d853d534add5d0e9ba76ab2f09a7daa254aa33b/src/BloomExe/Workspace/WorkspaceView.cs#L319)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

> Isn't this just setting the text of the selected language to display when the dropdown is closed?
Yes, and it's very unusual to set it to something other than the text of the selected item, as happens automatically when you select it. An unusual thing that has to be done consistently in two places without even a comment linking them feels to me like asking for trouble. But we are trying to keep the change minimal and simple....sigh...is it worth doing a better job in 3.9??

Agreed, minimal change to 3.7 is good, so I guess the weirdness of checking every iteration of a loop to see whether the current one is the one thing we want to change can stand.
</blockquote></details>

I've pulled out the code into a common method. 

But I don't think I understand what you're asking for as far as pulling the logic out of the loop. Either way, we have to iterate over the CultureInfo objects to find the correct one since Settings.Default.UserInterfaceLanguage is an attribute of the CultureInfo object. Or I am just missing what you're saying?

---

*[src/BloomExe/Workspace/WorkspaceView.cs, line 342 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542#-KeL3-npgqroCAIqE3-C:-Ke_a8G8jfTUWXm743H4:bm4vq9f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1d853d534add5d0e9ba76ab2f09a7daa254aa33b/src/BloomExe/Workspace/WorkspaceView.cs#L342)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Preserving an actual discovered bug for fear of creating a new problem might be taking that idea too far, but no one has reported the problem I'm predicting (and I haven't even confirmed it), so maybe you're right to leave it.
</blockquote></details>

This is why I think you're better at code reviews than I am! Discovering potential bugs in unmodified code... I don't think I would ever do that.
But as you say, this is a predicted bug and I would rather be safe not changing code I don't fully understand.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542)*

**Comment by JohnThomson** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/Workspace/WorkspaceView.cs, line 319 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542#-KeL3QIdrwEj3-06qF1t:-KedgwVyXbo87ld-78eb:b-ts73r8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1d853d534add5d0e9ba76ab2f09a7daa254aa33b/src/BloomExe/Workspace/WorkspaceView.cs#L319)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I've pulled out the code into a common method. 

But I don't think I understand what you're asking for as far as pulling the logic out of the loop. Either way, we have to iterate over the CultureInfo objects to find the correct one since Settings.Default.UserInterfaceLanguage is an attribute of the CultureInfo object. Or I am just missing what you're saying?
</blockquote></details>

I think it would be equivalent (and make the intent clearer) to have a line after the loop, (once we've selected the right item)  saying uiMenuControl.Text = ((CultureInfo)uiMenuControl.SelectedItem.Tag).NativeName. And I think that would also work in the ClickHandler method below. But it may well be too risky a change for 3.7. And as I look closer, it seems the current code is (bizarrely) being done INSTEAD of selecting the appropriate current item in the menu. So my idea probably wouldn't work. Let's leave it as is. Sorry.

---

*[src/BloomExe/Workspace/WorkspaceView.cs, line 342 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542#-KeL3-npgqroCAIqE3-C:-KedhZUg3NhlIT9ozZQp:b-8rr3zp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1d853d534add5d0e9ba76ab2f09a7daa254aa33b/src/BloomExe/Workspace/WorkspaceView.cs#L342)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This is why I think you're better at code reviews than I am! Discovering potential bugs in unmodified code... I don't think I would ever do that.
But as you say, this is a predicted bug and I would rather be safe not changing code I don't fully understand.
</blockquote></details>

I will try to remember to test it and make a card if there's a real bug :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542)*

**Comment by JohnThomson** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/CollectionChoosing/OpenCreateCloneControl.designer.cs, line 39 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542#-KeL7lK4h4db7j3E7E7H:-KedinRYEgCFlncGIR0W:bb6ywmx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1d853d534add5d0e9ba76ab2f09a7daa254aa33b/src/BloomExe/CollectionChoosing/OpenCreateCloneControl.designer.cs#L39)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Yes, VS revamped the file for some reason. (I haven't checked it either.)
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542)*

**Comment by andrew-polk** [comment]
Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Workspace/WorkspaceView.cs, line 342 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542#-KeL3-npgqroCAIqE3-C:-KedjEGsrrpfaVET60ot:b-rx17zi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1d853d534add5d0e9ba76ab2f09a7daa254aa33b/src/BloomExe/Workspace/WorkspaceView.cs#L342)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I will try to remember to test it and make a card if there's a real bug :-)
</blockquote></details>

Thanks. That is appreciated!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542)*

**Comment by JohnThomson** [comment]
Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Workspace/WorkspaceView.cs, line 342 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542#-KeL3-npgqroCAIqE3-C:-KedpWSql6os_ypWCrZ-:b-yt1iiv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1d853d534add5d0e9ba76ab2f09a7daa254aa33b/src/BloomExe/Workspace/WorkspaceView.cs#L342)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Thanks. That is appreciated!
</blockquote></details>

I can't produce a problem. Seems we're not really saving the 'original' button texts, but the current localization, and that has just been updated...so this is right, even though it doesn't look it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1542)*

**Pull request merged**
