### PR TITLE
BL-6296 Don't save page while loading it

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2654)

### CODE REVIEW

**Review by JohnThomson — COMMENTED** [review]
Two issues to think about here:
1. Is this safe? Is there any case you can think of where we need to save a page we are in the process of loading still? Is it possible we might miss a notification and leave a page in the 'don't bother saving" state? Should we also have some timeout for resetting PageMightBeDirty?
2. Is this OK architecturally? I'm using a mechanism made for something else; but it seems a waste to add a second mechanism for notifying C# that a page is loaded.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2654#-:-LIwD6NvDGcoWURGfSS1:b-60xsy5)* status: 0 of 2 files reviewed, all discussions resolved

**Comment by hatton** [comment]
Added some thoughts in the Youtrack issue.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2654)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Edit/EditingView.cs, line 472 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2654#-LJEa-MmBxZOU84HXEGl:-LJEa-MmBxZOU84HXEGm:b-x2svia) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7026948a73541f0d63d02be418d9119c688618a7/src/BloomExe/Edit/EditingView.cs#L472)):*
> ```Smalltalk
> 				_model.SetupServerWithCurrentPageIframeContents();
> 				HtmlDom domForCurrentPage = _model.GetXmlDocumentForCurrentPage();
> 				// A page can't be 'dirty' in the interval between when we start to navigate to it and when it's visible.
> ```

Could you address here what happens if a navigation leads to an OnBlur() event fire that modifies the page somehow?
___
*[src/BloomExe/Edit/EditingView.cs, line 475 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2654#-LJE_XfE-jodtgBtwNMZ:-LJE_XfE-jodtgBtwNM_:b-p3lnqr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7026948a73541f0d63d02be418d9119c688618a7/src/BloomExe/Edit/EditingView.cs#L475)):*
> ```Smalltalk
> 				// So we don't want anything trying to save it during that time. Apart from wasting time, such a save
> 				// might fail (BL-2634, BL-6296) if the new page is not yet loaded enough to have the right ID.
> 				// To detect that the page IS loaded, we're re-purposing some code originally made for timing
> ```

Is this the best way to do it, is it solid? Then just do it. Is it a hack and you can't figure out a better way? Well that's ok to say so too. But as is, this comment just leaves one feeling uneasy.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2654)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Edit/EditingModel.cs, line 960 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2654#-LJEacWO1Nj_vwRmLqSJ:-LJEacWO1Nj_vwRmLqSK:b-ho0xta) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7026948a73541f0d63d02be418d9119c688618a7/src/BloomExe/Edit/EditingModel.cs#L960)):*
> ```Smalltalk
> 		// page and when it is loaded. This prevents trying to save when things are in an unstable state
> 		// (e.g., BL-2634, BL-6296). It may also prevent some wasted Saves and thus improve performance.
> 		public bool PageMightBeDirty = true;
> ```

I think the name here promises more sophistication than we have.  All we have is a concept like NavigatingSoSuspendSaving.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2654)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Edit/EditingView.cs, line 479 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2654#-LJF7O-5AcCs9OIvPLQe:-LJF7O-5AcCs9OIvPLQf:be6929e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7026948a73541f0d63d02be418d9119c688618a7/src/BloomExe/Edit/EditingView.cs#L479)):*
> ```Smalltalk
> 				// to set it up again each time we load a page. It's important to set it up before we start
> 				// navigation; otherwise, we might miss the event and never enable saving for this page.
> 				Browser.RequestTimingNotification("editPagePainted", () => _model.PageMightBeDirty = true);
> ```

John & I decided it would make sense to add a new method to the Browser which just conveys what we want, and not how to get it, e.g. ``OnReallyDoneNavigating( Action )``

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2654)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/Edit/EditingModel.cs, line 960 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2654#-LJEacWO1Nj_vwRmLqSJ:-LJK28-lE7G1tm2VEZUh:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7026948a73541f0d63d02be418d9119c688618a7/src/BloomExe/Edit/EditingModel.cs#L960)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think the name here promises more sophistication than we have.  All we have is a concept like NavigatingSoSuspendSaving.
</blockquote></details>

Done.
___
*[src/BloomExe/Edit/EditingView.cs, line 472 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2654#-LJEa-MmBxZOU84HXEGl:-LJJZN-n5OkHsLLR1o9S:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7026948a73541f0d63d02be418d9119c688618a7/src/BloomExe/Edit/EditingView.cs#L472)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Could you address here what happens if a navigation leads to an OnBlur() event fire that modifies the page somehow?
</blockquote></details>

Done.
___
*[src/BloomExe/Edit/EditingView.cs, line 475 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2654#-LJE_XfE-jodtgBtwNMZ:-LJK0lr319aN6mrMiSYb:bczzsui) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7026948a73541f0d63d02be418d9119c688618a7/src/BloomExe/Edit/EditingView.cs#L475)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is this the best way to do it, is it solid? Then just do it. Is it a hack and you can't figure out a better way? Well that's ok to say so too. But as is, this comment just leaves one feeling uneasy.
</blockquote></details>

It's the best thing I can find. I've done some renaming to make it clear that this sort of notification is not limited to timing notifications, and adjusted the comment.
___
*[src/BloomExe/Edit/EditingView.cs, line 479 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2654#-LJF7O-5AcCs9OIvPLQe:-LJK0cZ-3nOdoTUeGV_5:bn9c8c3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7026948a73541f0d63d02be418d9119c688618a7/src/BloomExe/Edit/EditingView.cs#L479)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

John & I decided it would make sense to add a new method to the Browser which just conveys what we want, and not how to get it, e.g. ``OnReallyDoneNavigating( Action )``
</blockquote></details>

This turned out to be wrong. What's going on here is specific to editable pages, not generic like OnReallyDoneNavigating.

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2654)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/Edit/EditingModel.cs, line 960 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2654#-LJEacWO1Nj_vwRmLqSJ:-LJKAe6TECRFL0Rn-w3E:b-usdmq6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7026948a73541f0d63d02be418d9119c688618a7/src/BloomExe/Edit/EditingModel.cs#L960)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still think the reverse polarity would be more accurate and clear, but I won't harp on it.
___
*[src/BloomExe/Edit/EditingView.cs, line 472 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2654#-LJEa-MmBxZOU84HXEGl:-LJKAyOo25nbTg6QVSiU:b-3o5er0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7026948a73541f0d63d02be418d9119c688618a7/src/BloomExe/Edit/EditingView.cs#L472)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see that you address my request, but not a huge deal.

**Pull request merged**
