### PR TITLE
Adjust (localized) origami toggle switch to display nicely (BL-13129)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6329)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6329)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

*[a discussion](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6329#-NsPllRjDGYXqZrXf7qd:-NsPllRjDGYXqZrXf7qe:b-f67tqd) (no related file):*
I don't think this is the whole answer. It's definitely a step in the right direction to make measurements after localizing, but even in English, as the issue screenshot shows, the parts of the origami control can wrap, which produces undesirable ugliness, if the window is made narrower than the page.
It would help to apply CSS white-space:nowrap. Then, however wide the window is to begin with, you will measure the full width needed. And it will get clipped, instead of wrapping in an ugly way, if the user later makes the window smaller.
Since we have all that empty space to the left, it feels like it would be better still to keep the control visible, even if the page isn't entirely. One way:
- wrap another div around the .origami-toggle.
- give it width: 100% (so it will match the page-scaling-container, unless otherwise constrained)
- have the javascript set its max-width to the width of the page. (So it won't be wider than that, however big the window)
- set the .origami-toggle to be right:19px.
If I'm right, that will keep the origami control as far right as will make it visible, but not beyond the width of the page. And even without the white-space rule, it won't wrap unless it really runs out of space.
Another advantage is, the Javascript only has to know the page width, so you don't have to wait for localization.
I'm not sure whether @hatton would prefer the control to stay in place relative to the page and get clipped with it, or stay visible as the page gets clipped. If we used the extra div AND white-space:nowrap, then in a very narrow window the label would get clipped on the left, but you could still see the actual control, and it would never overlap the page. That would get my vote.

___

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6329)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @hatton and @JohnThomson)

*[a discussion](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6329#-NsPllRjDGYXqZrXf7qd:-NsQGxt07mCN-OGBeA9j:b-804e76) (no related file):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't think this is the whole answer. It's definitely a step in the right direction to make measurements after localizing, but even in English, as the issue screenshot shows, the parts of the origami control can wrap, which produces undesirable ugliness, if the window is made narrower than the page.
It would help to apply CSS white-space:nowrap. Then, however wide the window is to begin with, you will measure the full width needed. And it will get clipped, instead of wrapping in an ugly way, if the user later makes the window smaller.
Since we have all that empty space to the left, it feels like it would be better still to keep the control visible, even if the page isn't entirely. One way:
- wrap another div around the .origami-toggle.
- give it width: 100% (so it will match the page-scaling-container, unless otherwise constrained)
- have the javascript set its max-width to the width of the page. (So it won't be wider than that, however big the window)
- set the .origami-toggle to be right:19px.
If I'm right, that will keep the origami control as far right as will make it visible, but not beyond the width of the page. And even without the white-space rule, it won't wrap unless it really runs out of space.
Another advantage is, the Javascript only has to know the page width, so you don't have to wait for localization.
I'm not sure whether @hatton would prefer the control to stay in place relative to the page and get clipped with it, or stay visible as the page gets clipped. If we used the extra div AND white-space:nowrap, then in a very narrow window the label would get clipped on the left, but you could still see the actual control, and it would never overlap the page. That would get my vote.
</blockquote></details>

I think my original javascript code worked better than you thought, but following your suggested approach gives a better solution that doesn't require waiting for localization to finish.  With my changes (and possibly with my original code), the control now displays fine on windows as small as 800x600, which I think is all we could possibly want.

___

**Review by JohnThomson — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6329)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Review by JohnThomson — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6329)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
