### PR TITLE
[5.4] BL-12712 Ace by Daisy catastrophic failure

### PR DESCRIPTION
**Pull request by gmartin7**
* I apparently don't have AbD installed. I thought I did.
   But now Bloom correctly tells me it can't find it.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6130)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6130)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomExe/web/controllers/AccessibilityCheckApi.cs` line 331 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6130#-NfrSSI_5WobrmreX9D-:-NfrSSIaDs9iRkZtpwf0:bpw28sa) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54384e26a3089c93e56eefa166f1108d583eeed3/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L331)):*
> ```Smalltalk
> 			}
> 			// Adding Volta created a situation where there can be more than one location for npm.cmd.
> 			// If we get more than one result, we need the last non-empty one. (non-Volta)
> ```

I think we need to say more.
Why doesn't the volta one work?
Why is it safe to always pick the last one?
It seems that they would probably be in the order the system would use them, so using the first one would be most natural.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6130)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/web/controllers/AccessibilityCheckApi.cs` line 331 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6130#-NfrSSI_5WobrmreX9D-:-Nfvm3472hzuzc56QKZW:bs2xcey) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54384e26a3089c93e56eefa166f1108d583eeed3/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L331)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think we need to say more.
Why doesn't the volta one work?
Why is it safe to always pick the last one?
It seems that they would probably be in the order the system would use them, so using the first one would be most natural.
</blockquote></details>

As noted in the comments, the Volta version does the spawning of 1000s of processes. I added back in the Encoding and it seems to be working fine, despite many tries on the `where` command above coming back with a timeout error before today!
Today's testing:
* successfully finds Ace by Daisy and uses it to analyze the ePUB file.
* if I delete Ace by Daisy, Bloom successfully determines it isn't available and says so.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6130)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomExe/web/controllers/AccessibilityCheckApi.cs` line 331 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6130#-NfrSSI_5WobrmreX9D-:-NfvqITGBMAFcPNNgtIB:bkad2gd) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54384e26a3089c93e56eefa166f1108d583eeed3/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L331)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

As noted in the comments, the Volta version does the spawning of 1000s of processes. I added back in the Encoding and it seems to be working fine, despite many tries on the `where` command above coming back with a timeout error before today!
Today's testing:
* successfully finds Ace by Daisy and uses it to analyze the ePUB file.
* if I delete Ace by Daisy, Bloom successfully determines it isn't available and says so.
</blockquote></details>

If we really need to code for not-the-Volta-one, isn't that different than just taking the last one?
I'm not sure this is correct, either, but wouldn't it be better to get the first one which isn't *volta*?

**Comment by andrew-polk** [comment]
*[`src/BloomExe/web/controllers/AccessibilityCheckApi.cs` line 331 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6130#-NfrSSI_5WobrmreX9D-:-NfvqfBhEeTe3wmNmwSu:bay3y3s) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54384e26a3089c93e56eefa166f1108d583eeed3/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L331)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If we really need to code for not-the-Volta-one, isn't that different than just taking the last one?
I'm not sure this is correct, either, but wouldn't it be better to get the first one which isn't *volta*?
</blockquote></details>

I meant to say where the path doesn't include "volta"

**Comment by andrew-polk** [comment]
*[`src/BloomExe/web/controllers/AccessibilityCheckApi.cs` line 331 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6130#-NfrSSI_5WobrmreX9D-:-NfvvD2k1RRkT2XRpZ9r:b-tedet9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54384e26a3089c93e56eefa166f1108d583eeed3/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L331)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I meant to say where the path doesn't include "volta"
</blockquote></details>

Looking at the code a little more, if the problem is with the "root -g" params, what can we do to move away from that?

As I understand, all we're trying to do here is verify that npm is available?
How about `npm --version`?

**Comment by andrew-polk** [comment]
*[`src/BloomExe/web/controllers/AccessibilityCheckApi.cs` line 331 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6130#-NfrSSI_5WobrmreX9D-:-NfvvoNyALpzVCfUtg-i:bjbzqj5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54384e26a3089c93e56eefa166f1108d583eeed3/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L331)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looking at the code a little more, if the problem is with the "root -g" params, what can we do to move away from that?

As I understand, all we're trying to do here is verify that npm is available?
How about `npm --version`?
</blockquote></details>

Oh, no. I see we actually need to find the global node_modules directory.

**Comment by andrew-polk** [comment]
*[`src/BloomExe/web/controllers/AccessibilityCheckApi.cs` line 331 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6130#-NfrSSI_5WobrmreX9D-:-Nfvwi39DL0pVu4X2Gtl:bre0gdp) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54384e26a3089c93e56eefa166f1108d583eeed3/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L331)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Oh, no. I see we actually need to find the global node_modules directory.
</blockquote></details>

When I run `"C:\Program Files\Volta\npm.cmd"` root -g from the command line, I don't see a memory leak or spawning of extra processes.
Definitely seems we need to understand this more.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6130)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/web/controllers/AccessibilityCheckApi.cs` line 331 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6130#-NfrSSI_5WobrmreX9D-:-NfvyDLzBoz6T63fobqc:b-d3779g) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54384e26a3089c93e56eefa166f1108d583eeed3/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L331)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

When I run `"C:\Program Files\Volta\npm.cmd"` root -g from the command line, I don't see a memory leak or spawning of extra processes.
Definitely seems we need to understand this more.
</blockquote></details>

I do... if you start in the Volta directory. And the Command Line Runner takes a start directory that would default to Volta, if you're using that version of npm.cmd.

**Comment by andrew-polk** [comment]
*[`src/BloomExe/web/controllers/AccessibilityCheckApi.cs` line 331 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6130#-NfrSSI_5WobrmreX9D-:-Nfvzt_vDQUEEhoWhBC0:b-7opfv4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54384e26a3089c93e56eefa166f1108d583eeed3/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L331)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I do... if you start in the Volta directory. And the Command Line Runner takes a start directory that would default to Volta, if you're using that version of npm.cmd.
</blockquote></details>

Ah. I see that now, yes. Good catch.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6130)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/web/controllers/AccessibilityCheckApi.cs` line 331 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6130#-NfrSSI_5WobrmreX9D-:-Nfw0uTU1tddx2zgfOgd:b435p17) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54384e26a3089c93e56eefa166f1108d583eeed3/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L331)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I find that even running `npm.cmd --version` causes the same problem **if** run in the volta directory.

Let's weigh the pros and cons of your solution (excluding volta) vs. not running the volta directory:
```
var result = CommandLineRunnerExtra.RunWithInvariantCulture(fullNpmPath, "root -g", Encoding.ASCII, "", 10,
				new NullProgress());
```
Probably worth a team discussion, either in person on on Zulip.
</blockquote></details>

Wouldn't I still need to find the other location, just to get the directory we DO want to run from?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6130)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/web/controllers/AccessibilityCheckApi.cs` line 331 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6130#-NfrSSI_5WobrmreX9D-:-NfwHBIr29SjNlNjw4PJ:b-eesk76) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54384e26a3089c93e56eefa166f1108d583eeed3/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L331)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Wouldn't I still need to find the other location, just to get the directory we DO want to run from?
</blockquote></details>

And it's only a problem on developer machines. Nobody else will have Volta.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6130)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
