### PR TITLE
Uzbekistan XMatter and supporting changes (BL-12047)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 20 of 23 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734)* status: 23 of 24 files reviewed, 7 unresolved discussions (waiting on @JohnThomson)

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734#-NRnH5uq38-y37dEk7dc):*
Looks like this is still outstanding



_Code quote:_
```
(TODO: unit test)
```
___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 53 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734#-NRnHAxb4r6RPpDz0N4h:-NRnHAxb4r6RPpDz0N4i:b-bdpuwu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/03fb0c277599974e78630f758eaa0241ecf7aa62/src/BloomBrowserUI/bookEdit/css/editMode.less#L53)):*
> ```Less
>     /* This works with a transform:scale style added in Javascript to allow zooming just the main page*/
>     transition: transform 20ms;
>     /* This works around a bug in Gecko29 and should be removed when we upgrade. It prevents redraw errors during crtl-wheel zooming*/
> ```

Unfortunately prettier (I assume) moved these comments below what they refer to, so they are somewhat disconnected now.
I guess we need to move them above.
___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 134 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734#-NRnHax847Ey4p69K6sv:-NRnHax847Ey4p69K6sw:bok5t8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/03fb0c277599974e78630f758eaa0241ecf7aa62/src/BloomBrowserUI/bookEdit/css/editMode.less#L134)):*
> ```Less
> 
>     >.imageButton,
>     >.miniButton {
> ```

I'm not convinced the removal of these spaces is innocuous. (Or is it a purposeful change to fix a bug?)
___
*[`src/BloomExe/Book/XMatterHelper.cs` line 213 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734#-NRnIQCQ3L5RHflD4zTc:-NRnIQCQ3L5RHflD4zTd:b-twxedk) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/03fb0c277599974e78630f758eaa0241ecf7aa62/src/BloomExe/Book/XMatterHelper.cs#L213)):*
> ```Smalltalk
> 		/// (This allows us to define default formatting for xmatter elements using "user-defined"
> 		/// styles that the user can modify later. We must not re-insert them after the user has
> 		/// done so, so we limit the insertion to styles that are not already present.)
> ```

I guess it isn't a problem that nothing ever removes them if the user then switches to a new xmatter, right?
It would just be as if they had added the styles manually, I think.
___
*[`src/BloomExe/Book/XMatterHelper.cs` line 227 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734#-NRnId8C2PYYPVJC20xo:-NRnId8C2PYYPVJC20xp:b4x2jtc) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/03fb0c277599974e78630f758eaa0241ecf7aa62/src/BloomExe/Book/XMatterHelper.cs#L227)):*
> ```Smalltalk
> 				// 2) it should do it whenever we update the xmatter. But it does need to preserve
> 				// the existing styles in case they have been customized, even at the expense of
> 				// losing some new default improvement.
> ```

Sorry; I can't tell if this TODO is meant to live on past the merge of this PR.
Also, it seems like it is implemented.

So I guess if it is supposed to remain, it needs more clarity.
1. Why is ok to keep as is for now?
2. How, specifically, is the implementation below different than what is called for?
___
*[`src/content/.yarnrc.yml` line 1 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734#-NRnEdMR51rW0eAyI8Qu:-NRnEdMR51rW0eAyI8Qv:b6hfct5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/03fb0c277599974e78630f758eaa0241ecf7aa62/src/content/.yarnrc.yml#L1)):*
> ```YAML
> yarnPath: .yarn/releases/yarn-1.22.19.cjs
> ```

I'm pretty sure when this file got checked in previously, we had build issues.
Of course, I think that was probably because the file didn't exist. This PR is trying to add the file. But we don't want that, either, do we? Even if this is something we may want in place moving forward, it doesn't seem like Version5.4 branch is where we want to first add it. In fact, master has `src/BloomBrowserUI/.yarn/` in .gitignore.
___
*[`src/content/templates/xMatter/project-specific/Uzbekistan2023-XMatter/Uzbekistan2023-XMatter.pug` line 26 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734#-NRnGbd7-edjPrXEeK4P:-NRnGbd7-edjPrXEeK4Q:b6efbxp) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/03fb0c277599974e78630f758eaa0241ecf7aa62/src/content/templates/xMatter/project-specific/Uzbekistan2023-XMatter/Uzbekistan2023-XMatter.pug#L26)):*
> ```Pug
> 			+field-prototypeDeclaredExplicity("V").foobar
> 				label.bubble Not clear what this is yet
> 				//- TODO !!!!!!!!!!!!!!!!!!!!!!!! change both "foobar"s to something semantic once we figure out what this field is.
> ```

This is outstanding.



_Code quote:_
```Pug
//- TODO !!!!!!!!!!!!!!!!!!!!!!!! change both "foobar"s to something semantic once we figure out what this field is.
```

**Review by JohnThomson — COMMENTED** [review]
Glad I had you check.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734#-:-NRo4Oyf7Lb8Hjq7_Dzg:butffnq)* status: 20 of 25 files reviewed, 7 unresolved discussions (waiting on @andrew-polk)

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734#-NRnH5uq38-y37dEk7dc):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like this is still outstanding
</blockquote></details>

Done. (But I don't know any way to remove it from the commit history.)
___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 53 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734#-NRnHAxb4r6RPpDz0N4h:-NRnwOcz-c-D9QH3C7n_:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/03fb0c277599974e78630f758eaa0241ecf7aa62/src/BloomBrowserUI/bookEdit/css/editMode.less#L53)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Unfortunately prettier (I assume) moved these comments below what they refer to, so they are somewhat disconnected now.
I guess we need to move them above.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 134 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734#-NRnHax847Ey4p69K6sv:-NRny55B3vF70DTFgUPX:b-4k8mix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/03fb0c277599974e78630f758eaa0241ecf7aa62/src/BloomBrowserUI/bookEdit/css/editMode.less#L134)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not convinced the removal of these spaces is innocuous. (Or is it a purposeful change to fix a bug?)
</blockquote></details>

It is innocuous; see https://stackoverflow.com/questions/23581885/css-vs/23583078#23583078. Whitespace matters between two simple selectors (.x.y) but not around a combinator like >. This is part of John's changes, probably by prettier. I'm inclined to leave it.
___
*[`src/BloomExe/Book/XMatterHelper.cs` line 213 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734#-NRnIQCQ3L5RHflD4zTc:-NRnyQzg5KPbA1kbuX9w:b462ool) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/03fb0c277599974e78630f758eaa0241ecf7aa62/src/BloomExe/Book/XMatterHelper.cs#L213)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I guess it isn't a problem that nothing ever removes them if the user then switches to a new xmatter, right?
It would just be as if they had added the styles manually, I think.
</blockquote></details>

I believe so. (Of course they will probably no longer work, since any other xmatter probably applies a different style to these elements.)
___
*[`src/BloomExe/Book/XMatterHelper.cs` line 227 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734#-NRnId8C2PYYPVJC20xo:-NRnyeDk5OM3sjTQAbH_:bhyuxhm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/03fb0c277599974e78630f758eaa0241ecf7aa62/src/BloomExe/Book/XMatterHelper.cs#L227)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; I can't tell if this TODO is meant to live on past the merge of this PR.
Also, it seems like it is implemented.

So I guess if it is supposed to remain, it needs more clarity.
1. Why is ok to keep as is for now?
2. How, specifically, is the implementation below different than what is called for?
</blockquote></details>

I just forgot to remove it. Sorry.
___
*[`src/content/.yarnrc.yml` line 1 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734#-NRnEdMR51rW0eAyI8Qu:-NRo1osB4u9GcmIV1J4G:ba3dfob) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/03fb0c277599974e78630f758eaa0241ecf7aa62/src/content/.yarnrc.yml#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm pretty sure when this file got checked in previously, we had build issues.
Of course, I think that was probably because the file didn't exist. This PR is trying to add the file. But we don't want that, either, do we? Even if this is something we may want in place moving forward, it doesn't seem like Version5.4 branch is where we want to first add it. In fact, master has `src/BloomBrowserUI/.yarn/` in .gitignore.
</blockquote></details>

Removed
___
*[`src/content/templates/xMatter/project-specific/Uzbekistan2023-XMatter/Uzbekistan2023-XMatter.pug` line 26 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734#-NRnGbd7-edjPrXEeK4P:-NRo1sbT2dT7DjQDeG4i:b-6gticq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/03fb0c277599974e78630f758eaa0241ecf7aa62/src/content/templates/xMatter/project-specific/Uzbekistan2023-XMatter/Uzbekistan2023-XMatter.pug#L26)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This is outstanding.
</blockquote></details>

Yep. We're waiting for Chris to give us the answer. John wants us to put it to internal beta with it left as foobar but to make sure to fix it before we actually release.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 134 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734#-NRnHax847Ey4p69K6sv:-NRoAyQPAO1YEaiYM4AD:b-g3kveh) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/03fb0c277599974e78630f758eaa0241ecf7aa62/src/BloomBrowserUI/bookEdit/css/editMode.less#L134)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It is innocuous; see https://stackoverflow.com/questions/23581885/css-vs/23583078#23583078. Whitespace matters between two simple selectors (.x.y) but not around a combinator like >. This is part of John's changes, probably by prettier. I'm inclined to leave it.
</blockquote></details>

Ok, but apparently you saving the file changed it back! Along with several other changes. 
This isn't good... we need to get on the same page with prettier changes.
___
*[`src/content/.yarnrc.yml` line 1 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734#-NRnEdMR51rW0eAyI8Qu:-NRoBQdv2c9dn9vdXpRd:b-4mz2e5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/03fb0c277599974e78630f758eaa0241ecf7aa62/src/content/.yarnrc.yml#L1)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Removed
</blockquote></details>

I see you removed the other file but not this one.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734)* status: 23 of 25 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 134 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734#-NRnHax847Ey4p69K6sv:-NRoDUfr6PiPTkrJCtHS:bcb42b7) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/03fb0c277599974e78630f758eaa0241ecf7aa62/src/BloomBrowserUI/bookEdit/css/editMode.less#L134)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Ok, but apparently you saving the file changed it back! Along with several other changes. 
This isn't good... we need to get on the same page with prettier changes.
</blockquote></details>

Grrrr...reverted the other changes
___
*[`src/content/.yarnrc.yml` line 1 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734#-NRnEdMR51rW0eAyI8Qu:-NRoDSMy9uBX5U9gD7BV:b-ljo57k) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/03fb0c277599974e78630f758eaa0241ecf7aa62/src/content/.yarnrc.yml#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I see you removed the other file but not this one.
</blockquote></details>

Sorry, done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5734)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
