### PR TITLE
Let book Readmes include images, update TemplateStarter Readme

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1578)

### CODE REVIEW

**Comment by andrew-polk** [comment]
:lgtm: 
I assume you verified the ReadMeImages directory is not copied when creating a book from the template?

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1578#-:-Kffw5q7fNiFNhTwGuLp:b-cq6gb)*

**Comment by hatton** [comment]
Thanks for catching that. New commit added.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1578#-:-KfgnGAU6ul-x91bA9OT:b9n4bji)*

**Comment by andrew-polk** [comment]
Looks like the new commit went on the wrong branch (the one for BloomField.ts)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1578#-:-Kfgq2ZZ52xKqsbtpVMf:b-4koyh6)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1578#-:-KfhKjm_PE5KBk0Sby5I:bnfp4nl)*

**Pull request merged**
