### PR TITLE
Minor refactorings and fixes in preparation for actual change (BL-9920)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx, line 68 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-MaAWevOAT-uhrs7PFJy:-MaAWevOAT-uhrs7PFJz:b-he07aq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a424298bbf92bde58cd0fc4009a98c212dfabb3/src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx#L68)):*
> ```XML
>         props.collectionName,
>         undefined,
>         true
> ```

This unrelated change just prevents the missing l10n warning by setting temporarilyDisableI18nWarning to true.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/web/controllers/CommonApi.cs, line 158 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-MaA_SLGAcNR2QQBvvdt:-MaA_SLGAcNR2QQBvvdu:btli0cq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a424298bbf92bde58cd0fc4009a98c212dfabb3/src/BloomExe/web/controllers/CommonApi.cs#L158)):*
> ```Smalltalk
> 			// api to do it. We just need a way to close a c#-opened dialog from javascript (e.g. the Close button of the dialog).
> 			// This version of the handler sets requiresSync to false to ensure we don't get into deadlock situations like BL-9920.
> 			apiHandler.RegisterEndpointHandler("common/closeReactDialogImmediately", request =>
> ```

The "immediately" part makes sense in the mind of you while you're coding this, but it doesn't from an api consumer point of view. It leads to "wait, why would I *not* want it to close immediately"?  The answer seems to be "we don't know". But if that's true, why have both api calls?  In other words, it seems like either the fix here should just be the `requiresSync: false`, or else more comments to help me understand why we might need the `true` version.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/web/controllers/CommonApi.cs, line 158 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-MaA_SLGAcNR2QQBvvdt:-MaAcjIh74ebK2UFYppO:b-fwxjt0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a424298bbf92bde58cd0fc4009a98c212dfabb3/src/BloomExe/web/controllers/CommonApi.cs#L158)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

The "immediately" part makes sense in the mind of you while you're coding this, but it doesn't from an api consumer point of view. It leads to "wait, why would I *not* want it to close immediately"?  The answer seems to be "we don't know". But if that's true, why have both api calls?  In other words, it seems like either the fix here should just be the `requiresSync: false`, or else more comments to help me understand why we might need the `true` version.
</blockquote></details>

Yeah, I definitely see your point.
I was attempting to provide both in part so that a developer would think about which one might be the right thing to do for each call...
But I admit I don't have a full enough understanding to add comments which would help said developer make the decision.
I discovered (by much pain and misery) that if we are going to have two different calls, one cannot start with the text of the other (like `closeReactDialog` and `closeReactDialogThreadsafe`).
But I can definitely see the argument to saying, since we don't know of a use case for `requiresSync: true`, just provide the one and put a word of warning in the comment.

I'll head that way.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/web/controllers/CommonApi.cs, line 158 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-MaA_SLGAcNR2QQBvvdt:-MaAgYb6518KDi_LyCe8:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a424298bbf92bde58cd0fc4009a98c212dfabb3/src/BloomExe/web/controllers/CommonApi.cs#L158)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Yeah, I definitely see your point.
I was attempting to provide both in part so that a developer would think about which one might be the right thing to do for each call...
But I admit I don't have a full enough understanding to add comments which would help said developer make the decision.
I discovered (by much pain and misery) that if we are going to have two different calls, one cannot start with the text of the other (like `closeReactDialog` and `closeReactDialogThreadsafe`).
But I can definitely see the argument to saying, since we don't know of a use case for `requiresSync: true`, just provide the one and put a word of warning in the comment.

I'll head that way.
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 360 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-MaVaL7V4D0A5_XXlg3X:-MaVaL7V4D0A5_XXlg3Y:bqmw2v8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3f626d9f76ef9c88fa6f469398089eb422d8de04/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L360)):*
> ```XML
>                         )}
>                     </div>
>                 )}
> ```

All these sign language changes are a result of testing out the pathological case of ffmpeg not existing or not working correctly and realizing that that code path was broken.
___
*[src/BloomExe/web/controllers/CommonApi.cs, line 500 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-MaVa__-73NhO3b4d7Lb:-MaVa__-73NhO3b4d7Lc:b-6fjs4v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3f626d9f76ef9c88fa6f469398089eb422d8de04/src/BloomExe/web/controllers/CommonApi.cs#L500)):*
> ```Smalltalk
> 
> 			Application.Idle += HandleAction;
> 		}
> ```

I'm not excited about this solution.
1. There is nothing to help us know we need to use this when writing future code.
2. CommonApi was just a place to put it because I couldn't think of a better place.
3. I'm not sure I like the method name.

Definitely open to any and all suggestions.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 63 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-MaVktpu4-eReKK7v3l7:-MaVktpu4-eReKK7v3l8:b-y4h0j4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3f626d9f76ef9c88fa6f469398089eb422d8de04/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L63)):*
> ```Smalltalk
> 		private void HandleShowCreateTeamCollectionDialog(ApiRequest request)
> 		{
> 			CommonApi.CreateDialogOnIdle(() =>
> ```

Unless I'm missing someting (for the 10th time today!), this want to be a static on ReactDialog instead of CommonAi.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 63 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-MaVktpu4-eReKK7v3l7:-MaZibBo3ZjcD2Or2R9H:bws2ru8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3f626d9f76ef9c88fa6f469398089eb422d8de04/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L63)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Unless I'm missing someting (for the 10th time today!), this want to be a static on ReactDialog instead of CommonAi.
</blockquote></details>

Yeah... difficult to say. Most calls are actually to ErrorReport.NotifyUserOfProblem currently.
Perhaps a BaseApi might have been an ok place? But that doesn't exist.
Anyway, I went with what you suggested.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 63 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-MaVktpu4-eReKK7v3l7:-Ma_5CjICp7-tndDPwhO:b-upu09u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3f626d9f76ef9c88fa6f469398089eb422d8de04/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L63)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Yeah... difficult to say. Most calls are actually to ErrorReport.NotifyUserOfProblem currently.
Perhaps a BaseApi might have been an ok place? But that doesn't exist.
Anyway, I went with what you suggested.
</blockquote></details>

Oh, sorry, I didn't convey what I meant.  What I was meaning is that we can get a clean method to open dialogs with just the minimum information:

```c#
private void HandleShowCreateTeamCollectionDialog(ApiRequest request)
{
	ReactDialog.Show(reactComponent: "CreateTeamCollectionDialog",
		props: new { defaultRepoFolder = DropboxUtils.GetDropboxFolderPath() },
		width: 600,
		height: 580
	);

	request.PostSucceeded();
}
```
,
and then in `ReactDialog.cs`, the CreateDialogOnIdle can be `private` (unless someone needs it) and add

```c#
public static void Show(string reactComponent, object props, int width, int height)
{
	ReactDialog.CreateDialogOnIdle(() =>
	{
		using (var dlg = new ReactDialog(reactComponent, props))
		{
			dlg.Width = width;
			dlg.Height = height;
			dlg.ShowDialog();
		}
	});
}
```

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 63 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-MaVktpu4-eReKK7v3l7:-Ma_9nhp8oIDK9AvL3Eg:b-4lx5t9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3f626d9f76ef9c88fa6f469398089eb422d8de04/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L63)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Oh, sorry, I didn't convey what I meant.  What I was meaning is that we can get a clean method to open dialogs with just the minimum information:

```c#
private void HandleShowCreateTeamCollectionDialog(ApiRequest request)
{
	ReactDialog.Show(reactComponent: "CreateTeamCollectionDialog",
		props: new { defaultRepoFolder = DropboxUtils.GetDropboxFolderPath() },
		width: 600,
		height: 580
	);

	request.PostSucceeded();
}
```
,
and then in `ReactDialog.cs`, the CreateDialogOnIdle can be `private` (unless someone needs it) and add

```c#
public static void Show(string reactComponent, object props, int width, int height)
{
	ReactDialog.CreateDialogOnIdle(() =>
	{
		using (var dlg = new ReactDialog(reactComponent, props))
		{
			dlg.Width = width;
			dlg.Height = height;
			dlg.ShowDialog();
		}
	});
}
```

</blockquote></details>

I was thinking it may not be safe/right to have such a general method on ReactDialog which would always wait until Idle to launch. I'll have to think more about that.

And then I still have to have a method somewhere (I guess back in CommonApi?) to wrap calls to ErrorReport.Notify*.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 63 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-MaVktpu4-eReKK7v3l7:-Ma_Hk155lnc8_9U8Um9:b-fsqotn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3f626d9f76ef9c88fa6f469398089eb422d8de04/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L63)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I was thinking it may not be safe/right to have such a general method on ReactDialog which would always wait until Idle to launch. I'll have to think more about that.

And then I still have to have a method somewhere (I guess back in CommonApi?) to wrap calls to ErrorReport.Notify*.
</blockquote></details>

? It seems like we've come full circle. I thought we agreed that it isn't safe/right is to leave it to each developer to have to think about such issues, and we agreed that onidle is the universal way to do these.

For ErrorReport.Notify*, that now calls us back. Wherever that callback leads to opening a ReactDialog, it should call this `Show`.

BTW I can't for the life of me figure out why `	class ReactDialogFactory: IReactDialogFactory` exists.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 63 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-MaVktpu4-eReKK7v3l7:-Ma_Iq5N8EXlYwPtUt4F:b-uuzpzt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3f626d9f76ef9c88fa6f469398089eb422d8de04/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L63)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

? It seems like we've come full circle. I thought we agreed that it isn't safe/right is to leave it to each developer to have to think about such issues, and we agreed that onidle is the universal way to do these.

For ErrorReport.Notify*, that now calls us back. Wherever that callback leads to opening a ReactDialog, it should call this `Show`.

BTW I can't for the life of me figure out why `	class ReactDialogFactory: IReactDialogFactory` exists.
</blockquote></details>

And while you're working around here... if you see an opportunity, remove the urQueryString. That's a footgun that won't work in pure browser land, anyways. We should be using props.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473)* status: 0 of 23 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 63 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-MaVktpu4-eReKK7v3l7:-Mb8M_kNE0wFwPA6E3UL:b-8z00o2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3f626d9f76ef9c88fa6f469398089eb422d8de04/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L63)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

And while you're working around here... if you see an opportunity, remove the urQueryString. That's a footgun that won't work in pure browser land, anyways. We should be using props.
</blockquote></details>

I've gotten rid of urlQueryString. Allowed for some nice simplifications.

But for this PR I've backed out attempts to fix the actual problem.
I need to pair or hand off that part. It has gotten really hairy.
A simple do-on-idle doesn't work inside the guts of the Notify stuff because we need to know the DialogResult. Still working out the best way forward...

btw, apparently IReactDialogFactory exists for unit testing HtmlErrorReporter.
___
*[src/BloomExe/web/controllers/CommonApi.cs, line 500 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-MaVa__-73NhO3b4d7Lb:-Mb8ML-L2eMrItLk8Mo7:bb21adi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3f626d9f76ef9c88fa6f469398089eb422d8de04/src/BloomExe/web/controllers/CommonApi.cs#L500)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not excited about this solution.
1. There is nothing to help us know we need to use this when writing future code.
2. CommonApi was just a place to put it because I couldn't think of a better place.
3. I'm not sure I like the method name.

Definitely open to any and all suggestions.
</blockquote></details>

This PR is only handling some tangential issues. The actual fix will be handled subsequently. So this comment is obsolete.

**Review by gmartin7 — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 5 of 9 files at r2, 17 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton)

**Review by JohnThomson — CHANGES_REQUESTED** [review]
looks basically good. Minor suggestions and questions.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-:-MbN-QyfAQxvFeirMSQQ:b-8fr5mo)* status: all files reviewed, 5 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomBrowserUI/bookPreview/BookPreviewPanel.tsx, line 11 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-MbMvk6p9SuPIu0ma3lW:-MbMvk6p9SuPIu0ma3lX:b-lxjjx9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f621c664439d2482a9686991d767b8f8c5ce2b79/src/BloomBrowserUI/bookPreview/BookPreviewPanel.tsx#L11)):*
> ```XML
> 
> export const BookPreviewPanel: React.FunctionComponent<{
>     urlPreview: string;
> ```

It's awkward that the same bit of information is coming to this control both as a prop and through a webSocket. The similar-but-backwards names urlPreview and previewUrl don't very well convey the significant difference. How about calling this one "initialPreviewUrl"? Or even, "initialBookPreviewUrl" and "currentBookPreviewUrl"?
___
*[src/BloomBrowserUI/problemDialog/ProblemDialog.tsx, line 17 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-MbMx2i27kFfwHHtfcSf:-MbMx2i27kFfwHHtfcSg:b-4b81ku) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f621c664439d2482a9686991d767b8f8c5ce2b79/src/BloomBrowserUI/problemDialog/ProblemDialog.tsx#L17)):*
> ```XML
>     level: ProblemKind;
>     message: string; // The localized message to notify the user about.
>     reportLabel?: string; // The localized text that goes on the Report button. Omit or pass "" to disable Report button.
> ```

This might interact with my current PR, which makes DialogReportButton's text configurable but treats a falsy text as "Use the default text".https://github.com/BloomBooks/BloomDesktop/pull/4534.
___
*[src/BloomBrowserUI/problemDialog/ProblemDialog.tsx, line 23 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-MbMxg2J4D6cI-ZTaDdJ:-MbMxg2J4D6cI-ZTaDdK:b-46wlo3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f621c664439d2482a9686991d767b8f8c5ce2b79/src/BloomBrowserUI/problemDialog/ProblemDialog.tsx#L23)):*
> ```XML
>         return <NotifyDialog {...props} />;
>     } else {
>         return <ReportDialog kind={props.level} />;
> ```

This is not a change, but it's very surprising to me that ReportDialog doesn't need at least the message.
___
*[src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx, line 68 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-MaAWevOAT-uhrs7PFJy:-MbMyYlq-rj_40T_u_sr:b-6gjt9b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a424298bbf92bde58cd0fc4009a98c212dfabb3/src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx#L68)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This unrelated change just prevents the missing l10n warning by setting temporarilyDisableI18nWarning to true.
</blockquote></details>

I think you should comment // temporarilyDisableI18nWarning. One day we're going to want to search for all occurrences of that.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473)* status: 20 of 23 files reviewed, 5 unresolved discussions (waiting on @gmartin7, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/bookPreview/BookPreviewPanel.tsx, line 11 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-MbMvk6p9SuPIu0ma3lW:-MbNCMaS8IJqb2WVCgvX:bd3w38g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f621c664439d2482a9686991d767b8f8c5ce2b79/src/BloomBrowserUI/bookPreview/BookPreviewPanel.tsx#L11)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's awkward that the same bit of information is coming to this control both as a prop and through a webSocket. The similar-but-backwards names urlPreview and previewUrl don't very well convey the significant difference. How about calling this one "initialPreviewUrl"? Or even, "initialBookPreviewUrl" and "currentBookPreviewUrl"?
</blockquote></details>

Good point. I hadn't even noticed there were two.
___
*[src/BloomBrowserUI/problemDialog/ProblemDialog.tsx, line 17 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-MbMx2i27kFfwHHtfcSf:-MbNFtOQ4MKYYNMPxkDR:b-57nc83) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f621c664439d2482a9686991d767b8f8c5ce2b79/src/BloomBrowserUI/problemDialog/ProblemDialog.tsx#L17)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This might interact with my current PR, which makes DialogReportButton's text configurable but treats a falsy text as "Use the default text".https://github.com/BloomBooks/BloomDesktop/pull/4534.
</blockquote></details>

I'm not changing behavior. Just passing props instead of url param.
Looks like your changes don't relate to ProblemDialog, though. It is a totally separate dialog from what I'm seeing.
___
*[src/BloomBrowserUI/problemDialog/ProblemDialog.tsx, line 23 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-MbMxg2J4D6cI-ZTaDdJ:-MbNFQKw7k8yt73BMhmP:b2rocw6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f621c664439d2482a9686991d767b8f8c5ce2b79/src/BloomBrowserUI/problemDialog/ProblemDialog.tsx#L23)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This is not a change, but it's very surprising to me that ReportDialog doesn't need at least the message.
</blockquote></details>

ReportDialog gets all its info separately through the api. I retested this to make sure.
___
*[src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx, line 68 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473#-MaAWevOAT-uhrs7PFJy:-MbNCQFu6rWRHbvWR8D7:bo2baeq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a424298bbf92bde58cd0fc4009a98c212dfabb3/src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx#L68)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think you should comment // temporarilyDisableI18nWarning. One day we're going to want to search for all occurrences of that.
</blockquote></details>

Good point. Unfortunately, we have this many other places, too. I considered doing the same everywhere else, but the same process I would use to find them is the one we will use in the future to find them, so wasted effort...

**Review by JohnThomson — APPROVED** [review]
> Reviewed 2 of 9 files at r2, 15 of 17 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton)

**Review by andrew-polk — COMMENTED** [review]
> Dismissed @hatton from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
