### PR TITLE
BL-5347 Improve Image Credit punctuation

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2026)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/web/controllers/ImageApi.cs, line 132 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2026#-L0BMBhput8bv_5YLDxS:-L0BMBhput8bv_5YLDxT:b-at31ie) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/30036804e6606d7760b581f5676acb1e936c98f0/src/BloomExe/web/controllers/ImageApi.cs#L132)):*
> ```Smalltalk
> 			// Generate a formatted credit string like:
> 			//   Image on page 2 by John Doe, Copyright John Doe, 2016, CC-BY-NC. or
> 			//   Images on pages 1, 3, 4 by Art of Reading, Copyright SIL International 2017, CC-BY-SA.
> ```

Seems rather silly to be reviewing something this simple at all, but...why drop the 'and'?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2026)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/web/controllers/ImageApi.cs, line 132 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2026#-L0BMBhput8bv_5YLDxS:-L0BMp0wBleFAkUeTWAE:bjt1v9a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/30036804e6606d7760b581f5676acb1e936c98f0/src/BloomExe/web/controllers/ImageApi.cs#L132)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Seems rather silly to be reviewing something this simple at all, but...why drop the 'and'?
</blockquote></details>

OK, I see why from the issue. Now I have a much more fundamental question: all you changed is a C# comment. How can that change anything in the actual program behavior?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2026)*

**Comment by gmartin7** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/web/controllers/ImageApi.cs, line 132 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2026#-L0BMBhput8bv_5YLDxS:-L0BWAajnM9GKwUxUekW:b-gpib76) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/30036804e6606d7760b581f5676acb1e936c98f0/src/BloomExe/web/controllers/ImageApi.cs#L132)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

OK, I see why from the issue. Now I have a much more fundamental question: all you changed is a C# comment. How can that change anything in the actual program behavior?
</blockquote></details>

There are 2 revisions of the PR; you need to "widen your gaze" a bit. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2026)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2026#-:-L0BgvC30jwu4VXxVVzj:bnfp4nl)*

**Pull request merged**
