### PR TITLE
Allow a settings.json to define some defaults for a brand (BL-3868)

### PR DESCRIPTION
**Pull request by hatton**
Settings.json can contain copyright, license url, and rights statement (license notes)

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1233)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[DistFiles/branding/GRN-REACH/settings.json, line 3 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1233#-KTjG9tINhdOPd3YmjfH:-KTjG9tINhdOPd3YmjfI:b-lj0gmv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/021e77b7add15f685dfcfeeed32ce067039d5d23/DistFiles/branding/GRN-REACH/settings.json#L3)):*
> ```JSON
> {
>     "LicenseUrl":"http://creativecommons.org/licenses/by/3.0/igo/",
>     "LicenseRightsStatement": "Translationsâ€”If you create a translation of this work, please add the following disclaimer along with the attribution: This translation was not created by USAID and should not be considered an official USAID translation. USAID shall not be liable for any content or error in this translation.
> ```

I assume the â€ character after "Translations shows up correctly in the app, so this is probably a problem with Reviewable's rendering?

---

*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 72 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1233#-KTjIGQpx2pxeVUBz3eE:-KTjIGQpx2pxeVUBz3eF:byb2he2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/021e77b7add15f685dfcfeeed32ce067039d5d23/src/BloomExe/Book/BookCopyrightAndLicense.cs#L72)):*
> ```Smalltalk
> 		}
> 
> 		private static Metadata SetToDefaultCopyrightAndLicense(string brandingNameOrPath)
> ```

Seems like the method name should be something like GetMetadataWithDefaultCopyrightAndLicense

---

*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 78 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1233#-KTjIQP33ZcJGGU972IZ:-KTjIQP33ZcJGGU972I_:bm53nel) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/021e77b7add15f685dfcfeeed32ce067039d5d23/src/BloomExe/Book/BookCopyrightAndLicense.cs#L78)):*
> ```Smalltalk
> 			metadata.License = new CreativeCommonsLicense(true, true, CreativeCommonsLicense.DerivativeRules.Derivatives);
> 
> 			//OK, that's all we need, the reset is blank. That is, unless we are we are working with a brand
> ```

reset => rest

---

*[src/BloomExe/web/controllers/BrandingApi.cs, line 30 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1233#-KTjIfpxL6Fo3VBwFbSY:-KTjIfpxL6Fo3VBwFbSZ:b-iq015s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/021e77b7add15f685dfcfeeed32ce067039d5d23/src/BloomExe/web/controllers/BrandingApi.cs#L30)):*
> ```Smalltalk
> 				{
> 					request.Failed("");
> 						// the HTML will need to be able to handle this invisibly... see http://stackoverflow.com/questions/22051573/how-to-hide-image-broken-icon-using-only-css-html-without-js
> ```

extra tab

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1233)*

**Comment by hatton** [comment]
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 72 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1233#-KTjIGQpx2pxeVUBz3eE:-KTjWLzrwwxtfSxAAx1v:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/021e77b7add15f685dfcfeeed32ce067039d5d23/src/BloomExe/Book/BookCopyrightAndLicense.cs#L72)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Seems like the method name should be something like GetMetadataWithDefaultCopyrightAndLicense
</details>
Done.

---

*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 78 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1233#-KTjIQP33ZcJGGU972IZ:-KTjWPjzjlpWOE8PK_0m:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/021e77b7add15f685dfcfeeed32ce067039d5d23/src/BloomExe/Book/BookCopyrightAndLicense.cs#L78)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> reset => rest
</details>
Done.

---

*[src/BloomExe/web/controllers/BrandingApi.cs, line 30 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1233#-KTjIfpxL6Fo3VBwFbSY:-KTjWPC9413JmM-z52Do:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/021e77b7add15f685dfcfeeed32ce067039d5d23/src/BloomExe/web/controllers/BrandingApi.cs#L30)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> extra tab
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1233)*

**Comment by hatton** [comment]
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[DistFiles/branding/GRN-REACH/settings.json, line 3 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1233#-KTjG9tINhdOPd3YmjfH:-KTjWh7hvtm-JlcVEuiz:b2nign6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/021e77b7add15f685dfcfeeed32ce067039d5d23/DistFiles/branding/GRN-REACH/settings.json#L3)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> I assume the â€ character after "Translations shows up correctly in the app, so this is probably a problem with Reviewable's rendering?
</details>
yes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1233)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1233#-:-KTjew8xPV1DYTI2gQBY:bnfp4nl)*

**Pull request merged**
