### PR TITLE
BL-6085 Remove old Epub publish view and clean up code

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458)

### CODE REVIEW

**Comment by andrew-polk** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-:-LEKobLQCA7r3umMajWJ:bnfp4nl)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKgD8140uKkdMcnYrG:-LEKqYxOA9cSBw_-az3g:b-rkcvwv) (no related file):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

May be helpful to review the three commits separately. Note however that epubVisibility.less, which was removed in the first, comes back (unchanged except for location) in the third, after I found it was still needed.
</blockquote></details>

Did some reviewing, some still to come.

---

*[src/BloomExe/Publish/PublishModel.cs, line 312 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKq8a67fg6Ua1dAXwA:-LEKq8a67fg6Ua1dAXwB:btqcby8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91ad5f79a5c5abd33c4170b83ac831bfbf2e5966/src/BloomExe/Publish/PublishModel.cs#L312)):*
> ```Smalltalk
> 			}
> 		}
> ```

Though named "internal"  this is actually effectively public (bloom is not a library). So it wants the same comment as any non-obvious public property.

---

*[src/BloomExe/Publish/PublishModel.cs, line 313 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKpccMBUI9MeYVOdeY:-LEKpccMBUI9MeYVOdeZ:b-44vb7r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91ad5f79a5c5abd33c4170b83ac831bfbf2e5966/src/BloomExe/Publish/PublishModel.cs#L313)):*
> ```Smalltalk
> 		}
> 
> 		internal string LastDirectory
> ```

Can this use the same syntax as the properties on line 540 and following?

---

*[src/BloomExe/Publish/PublishModel.cs, line 540 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKpPWyE-MtsnGhQ-pZ:-LEKpPWyE-MtsnGhQ-p_:b-mvx4g1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91ad5f79a5c5abd33c4170b83ac831bfbf2e5966/src/BloomExe/Publish/PublishModel.cs#L540)):*
> ```Smalltalk
> 		}
> 
> 		internal BookThumbNailer ThumbNailer => _thumbNailer;
> ```

I don't know yet where these are used, but if it's to avoid some other class getting them via autofac... maybe a comment is in order explaining that.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/BloomBrowserUI/publish/epub/epubVisibility.less, line 3 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKsFWnBF68Ee22Arkr:-LEKsFWnBF68Ee22Arks:b-17pslr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91ad5f79a5c5abd33c4170b83ac831bfbf2e5966/src/BloomBrowserUI/publish/epub/epubVisibility.less#L3)):*
> ```Less
> // Items hidden only in epubs are defined here.
> // One might think they should be defined in baseEPUB.less.
> // But baseEPUB.less is actually shipped with epubs whereas basePage.less is used at the
> ```

I think baseEPUB.less doesn't exist anymore?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/BloomExe/Publish/EpubPublishPanel.cs, line 6 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKtcir2Amb-DBeFUCc:-LEKtcir2Amb-DBeFUCd:b-8n4j55) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91ad5f79a5c5abd33c4170b83ac831bfbf2e5966/src/BloomExe/Publish/EpubPublishPanel.cs#L6)):*
> ```Smalltalk
> using System.Diagnostics;
> using System.IO;
> using System.Linq;
> ```

Several of these are unneeded

---

*[src/BloomExe/Publish/EpubPublishPanel.cs, line 22 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKskmFEwNiGmFIQfrK:-LEKskmFEwNiGmFIQfrL:b-as2rbf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91ad5f79a5c5abd33c4170b83ac831bfbf2e5966/src/BloomExe/Publish/EpubPublishPanel.cs#L22)):*
> provides backend support

But I suspect this is not what this class actually does, because it inherits from HtmlPublishPanel... then this *is* UI (which is the polar opposite of "backend").

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/BloomExe/Publish/EpubPublishPanel.cs, line 22 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKskmFEwNiGmFIQfrK:-LEKu3m_EYT3Ep2G_L92:b-4zqq1j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91ad5f79a5c5abd33c4170b83ac831bfbf2e5966/src/BloomExe/Publish/EpubPublishPanel.cs#L22)):*
And if it actually mixes the two and that's how you want it to be, that you don't want to have our standard View vs. Model classes, the comment could say that. 

> the React component epubPublishUI.tsx,

 A major strategy of reducing complexity is separation of concerns/knowledge.  So I think it's better for c#  comments to not tell the reader what component framework the front-end was implemented in at the time.... only give us what we need to understand *this class*.

---

*[src/BloomExe/Publish/EpubPublishPanel.cs, line 31 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKvH1CAc4c8KQBa12T:-LEKvH1CAc4c8KQBa12U:b-a8aqbe) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91ad5f79a5c5abd33c4170b83ac831bfbf2e5966/src/BloomExe/Publish/EpubPublishPanel.cs#L31)):*
> ```Smalltalk
> 	/// them directly.) Unfortunately the model's lastDirectory is supposed to be updated as well as read.
> 	/// If we got serious about testing this, and wanted better isolation,
> 	/// we could make an interface for reading and writing the last directory,
> ```

I haven't even figured out what in the world "lastDirectory" is.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458)*

**Comment by andrew-polk** [comment]
*[src/BloomExe/Publish/EpubPublishPanel.cs, line 55 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKvi6s8cRcu0nqFsOR:-LEKvi6s8cRcu0nqFsOS:b-fwq0h4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91ad5f79a5c5abd33c4170b83ac831bfbf2e5966/src/BloomExe/Publish/EpubPublishPanel.cs#L55)):*
> ```Smalltalk
> 
> 		public EpubPublishPanel(string pathToHtmlFile, PublishModel model,
> 			BookThumbNailer thumbNailer, BookServer bookServer) : base(NavigationIsolator._sTheOneNavigationIsolator, pathToHtmlFile)
> ```

I'm sure you didn't do this, but it seems odd that we would pass a singleton.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKgD8140uKkdMcnYrG:-LEL47ez5xX8i37Q2Zfd:b-arcrq4) (no related file):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Did some reviewing, some still to come.
</blockquote></details>

As you can tell from other comments, I'm not very happy with this myself...I just can't see what better to do.

---

*[src/BloomExe/Publish/EpubPublishPanel.cs, line 6 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKtcir2Amb-DBeFUCc:-LEKx9qk0wobQPO6evPz:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91ad5f79a5c5abd33c4170b83ac831bfbf2e5966/src/BloomExe/Publish/EpubPublishPanel.cs#L6)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Several of these are unneeded
</blockquote></details>

Done.

---

*[src/BloomExe/Publish/EpubPublishPanel.cs, line 22 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKskmFEwNiGmFIQfrK:-LEKxf6k1gxhsQ7vlPj3:bvfr4aq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91ad5f79a5c5abd33c4170b83ac831bfbf2e5966/src/BloomExe/Publish/EpubPublishPanel.cs#L22)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

And if it actually mixes the two and that's how you want it to be, that you don't want to have our standard View vs. Model classes, the comment could say that. 

> the React component epubPublishUI.tsx,

 A major strategy of reducing complexity is separation of concerns/knowledge.  So I think it's better for c#  comments to not tell the reader what component framework the front-end was implemented in at the time.... only give us what we need to understand *this class*.

</blockquote></details>

I dunno. The operations invoked by the api calls do things like saving a file, which involves asking for a file name, so the back end is doing UI. Initializing the view involves starting a process to create a preview and then notifying the front end when it is ready. Then the api may be told that a setting has changed which triggers a new preview. Progress messages are sent at various points. I was not able to disentangle everything into back end, view and view model. I was just trying to get epub-specific stuff into a place separate from the overall publish view/model. Maybe I just don't understand how the view/model thing applies to a component like this; what is the model that this view is editing? A model of the state of the UI?

---

*[src/BloomExe/Publish/EpubPublishPanel.cs, line 31 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKvH1CAc4c8KQBa12T:-LEKxZ-_5s31TwH_7ki8:bgqvti0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91ad5f79a5c5abd33c4170b83ac831bfbf2e5966/src/BloomExe/Publish/EpubPublishPanel.cs#L31)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I haven't even figured out what in the world "lastDirectory" is.
</blockquote></details>

EditingModel keeps track of the most recent directory where the user saved something.

---

*[src/BloomExe/Publish/EpubPublishPanel.cs, line 55 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKvi6s8cRcu0nqFsOR:-LEL1K7f8upnko2QbXQ2:bbf0q1m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91ad5f79a5c5abd33c4170b83ac831bfbf2e5966/src/BloomExe/Publish/EpubPublishPanel.cs#L55)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm sure you didn't do this, but it seems odd that we would pass a singleton.
</blockquote></details>

There is a work in progress to hide all knowledge of the isolator, so only the Browser class itself knows about the one-and-only isolator. I didn't want my new class to add to the problem.

---

*[src/BloomExe/Publish/PublishModel.cs, line 312 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKq8a67fg6Ua1dAXwA:-LEL1tOy8pB4SMX78EhC:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91ad5f79a5c5abd33c4170b83ac831bfbf2e5966/src/BloomExe/Publish/PublishModel.cs#L312)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Though named "internal"  this is actually effectively public (bloom is not a library). So it wants the same comment as any non-obvious public property.
</blockquote></details>

Done.

---

*[src/BloomExe/Publish/PublishModel.cs, line 313 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKpccMBUI9MeYVOdeY:-LEL1yTR2PeJouPXy3Wy:bqzmmmf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91ad5f79a5c5abd33c4170b83ac831bfbf2e5966/src/BloomExe/Publish/PublishModel.cs#L313)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Can this use the same syntax as the properties on line 540 and following?
</blockquote></details>

AFAIK that only works for read-only properties.

---

*[src/BloomExe/Publish/PublishModel.cs, line 540 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKpPWyE-MtsnGhQ-pZ:-LEL2GYw30r87lq_kuC7:bf40qp3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91ad5f79a5c5abd33c4170b83ac831bfbf2e5966/src/BloomExe/Publish/PublishModel.cs#L540)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I don't know yet where these are used, but if it's to avoid some other class getting them via autofac... maybe a comment is in order explaining that.
</blockquote></details>

Maybe EpubPublishPanel could be created by AutoFac? Or maybe EpubPublishPanel is a mistake?

---

*[src/BloomBrowserUI/publish/epub/epubVisibility.less, line 3 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKsFWnBF68Ee22Arkr:-LEKwpYJ-cjF21tsPj1C:bhgji9r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91ad5f79a5c5abd33c4170b83ac831bfbf2e5966/src/BloomBrowserUI/publish/epub/epubVisibility.less#L3)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think baseEPUB.less doesn't exist anymore?
</blockquote></details>

Still needed, so I moved it to the new folder.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458)*

**Comment by JohnThomson** [comment]
Review status: 8 of 16 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/BloomExe/Publish/PublishModel.cs, line 540 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKpPWyE-MtsnGhQ-pZ:-LELxfqAEN8AKvUztHJA:b-tb5apf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91ad5f79a5c5abd33c4170b83ac831bfbf2e5966/src/BloomExe/Publish/PublishModel.cs#L540)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Maybe EpubPublishPanel could be created by AutoFac? Or maybe EpubPublishPanel is a mistake?
</blockquote></details>

EpubPublishPanel is now gone, along with these props.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458)*

**Comment by hatton** [comment]
Reviewed 2 of 8 files at r2, 1 of 6 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/BloomBrowserUI/publish/epub/epubPublishUI.tsx, line 45 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEQ4I4lBZu_CzpOWJMZ:-LEQ4I4lBZu_CzpOWJM_:bohgex2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f42aa99bd67cf0fb27fd8a4352fb06e5cc109673/src/BloomBrowserUI/publish/epub/epubPublishUI.tsx#L45)):*
> ```XML
>             // This is a way of kicking off the request for a preview. We need the forcePreview
>             // parameter to make it happen even though we aren't actually changing the settings.
>             axios.post("/bloom/api/publish/epub/epubSettings?forcePreview=true", result.data);
> ```

This is a Frankenstien of a url, grafting a verb to make a preview on something called settings. Looking in the api code, I think it doesn't even read this, so this is a trick. Why not just have and endpoint named something like ```api/publish/epub/updatePreview```

---

*[src/BloomExe/Publish/PublishModel.cs, line 314 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEQ9sLY4BMOKBCjnfSA:-LEQ9sLY4BMOKBCjnfSB:bqptcgw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f42aa99bd67cf0fb27fd8a4352fb06e5cc109673/src/BloomExe/Publish/PublishModel.cs#L314)):*
> ```Smalltalk
> 
> 		/// <summary>
> 		/// The most recent directory where the user saved something.
> ```

It's not clear to me that we want to show the same directory for each thing, but if that's what we currently do, then that would be a new card. At the point where we decide to persist this in user settings, then it becomes more obvious that you don't want your PDF save location to mess up your epub save location.

So for now it's a question of, since we don't really want the "feature" of confusing various locations (pdf, epub, etc), is it better to encapsulate this location in the publishing code for each one, rather than in PublishModel.

(this is not a big deal, can be ignored for now)

---

*[src/BloomExe/Publish/PublishModel.cs, line 316 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEQ5Mk96NPkZVTjnpZN:-LEQ5Mk96NPkZVTjnpZO:b-f0trou) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f42aa99bd67cf0fb27fd8a4352fb06e5cc109673/src/BloomExe/Publish/PublishModel.cs#L316)):*
> ```Smalltalk
> 		/// The most recent directory where the user saved something.
> 		/// </summary>
> 		internal string LastDirectory
> ```

Outside of libraries, I think wrapping class variables in trivial properties is just noise.  So

    public string LastSavedDirectory; 

is better. In a library,

    public string LastSavedDirectory {get;set;}

might be preferred.

---

*[src/BloomExe/Publish/PublishView.cs, line 506 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEQErgh77ifxVp16b-8:-LEQErgh77ifxVp16b-9:bhy2wft) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f42aa99bd67cf0fb27fd8a4352fb06e5cc109673/src/BloomExe/Publish/PublishView.cs#L506)):*
> ```Smalltalk
> 					// This works as long as we only have one PublishView. If we one day support multiple windows, we'll need to do something
> 					// to tell it the current one whenever we switch active publish views.
> 					_publishEpubApi.CurrentView = this;
> ```

I hope we get rid of both _publishEpubApi and these back-links to here, and to the model... maybe we can chat about that.

---

*[src/BloomExe/Publish/Epub/PublishEpubApi.cs, line 113 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEQBT_y9mw8i7hjjJiR:-LEQBT_y9mw8i7hjjJiS:b-9aumgp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/932e6bed9e1e090450ff33bbff1dc5bfaa9742ce/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L113)):*
> ```Smalltalk
> 				if (request.HttpMethod == HttpMethods.Get)
> 				{
> 					request.ReplyWithJson(CurrentView.GetEpubState());
> ```

Would be good to use same name for "State" vs.  "Settings".

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKgD8140uKkdMcnYrG:-LERJ5QpDWWSd1RTxlTN:b-tzr2my) (no related file):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

As you can tell from other comments, I'm not very happy with this myself...I just can't see what better to do.
</blockquote></details>

Think we're in good shape now.

---

*[src/BloomBrowserUI/publish/epub/epubPublishUI.tsx, line 45 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEQ4I4lBZu_CzpOWJMZ:-LERIvei2jUHkzwIU2e7:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f42aa99bd67cf0fb27fd8a4352fb06e5cc109673/src/BloomBrowserUI/publish/epub/epubPublishUI.tsx#L45)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This is a Frankenstien of a url, grafting a verb to make a preview on something called settings. Looking in the api code, I think it doesn't even read this, so this is a trick. Why not just have and endpoint named something like ```api/publish/epub/updatePreview```
</blockquote></details>

Done.

---

*[src/BloomExe/Publish/PublishModel.cs, line 314 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEQ9sLY4BMOKBCjnfSA:-LERIzOK2DEaUvlZG2ga:b9ixo0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f42aa99bd67cf0fb27fd8a4352fb06e5cc109673/src/BloomExe/Publish/PublishModel.cs#L314)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

It's not clear to me that we want to show the same directory for each thing, but if that's what we currently do, then that would be a new card. At the point where we decide to persist this in user settings, then it becomes more obvious that you don't want your PDF save location to mess up your epub save location.

So for now it's a question of, since we don't really want the "feature" of confusing various locations (pdf, epub, etc), is it better to encapsulate this location in the publishing code for each one, rather than in PublishModel.

(this is not a big deal, can be ignored for now)
</blockquote></details>

No longer sharing directory, which simplifies many things

---

*[src/BloomExe/Publish/PublishModel.cs, line 316 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEQ5Mk96NPkZVTjnpZN:-LER59-C7aKUo7MSfJN8:bq8e4i2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f42aa99bd67cf0fb27fd8a4352fb06e5cc109673/src/BloomExe/Publish/PublishModel.cs#L316)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Outside of libraries, I think wrapping class variables in trivial properties is just noise.  So

    public string LastSavedDirectory; 

is better. In a library,

    public string LastSavedDirectory {get;set;}

might be preferred.
</blockquote></details>

Gone away

---

*[src/BloomExe/Publish/PublishView.cs, line 506 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEQErgh77ifxVp16b-8:-LERJ26S9tPuKAThf65a:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f42aa99bd67cf0fb27fd8a4352fb06e5cc109673/src/BloomExe/Publish/PublishView.cs#L506)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I hope we get rid of both _publishEpubApi and these back-links to here, and to the model... maybe we can chat about that.
</blockquote></details>

Done.

---

*[src/BloomExe/Publish/Epub/PublishEpubApi.cs, line 113 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEQBT_y9mw8i7hjjJiR:-LER5Z5c1pwCYTSh7FYH:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/932e6bed9e1e090450ff33bbff1dc5bfaa9742ce/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L113)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Would be good to use same name for "State" vs.  "Settings".
</blockquote></details>

Done.

---

*[src/BloomExe/Publish/EpubPublishPanel.cs, line 22 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKskmFEwNiGmFIQfrK:-LER5bBs1T8-uo_fG8Aa:b-ix5q55) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91ad5f79a5c5abd33c4170b83ac831bfbf2e5966/src/BloomExe/Publish/EpubPublishPanel.cs#L22)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I dunno. The operations invoked by the api calls do things like saving a file, which involves asking for a file name, so the back end is doing UI. Initializing the view involves starting a process to create a preview and then notifying the front end when it is ready. Then the api may be told that a setting has changed which triggers a new preview. Progress messages are sent at various points. I was not able to disentangle everything into back end, view and view model. I was just trying to get epub-specific stuff into a place separate from the overall publish view/model. Maybe I just don't understand how the view/model thing applies to a component like this; what is the model that this view is editing? A model of the state of the UI?
</blockquote></details>

EpubPublishPanel is gone.

---

*[src/BloomExe/Publish/EpubPublishPanel.cs, line 31 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458#-LEKvH1CAc4c8KQBa12T:-LER5fq460YrFdLp_dk_:b-wv7b25) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91ad5f79a5c5abd33c4170b83ac831bfbf2e5966/src/BloomExe/Publish/EpubPublishPanel.cs#L31)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

EditingModel keeps track of the most recent directory where the user saved something.
</blockquote></details>

PublishEpubApi now has its own, so this entanglement is gone

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2458)*

**Pull request merged**
