### PR TITLE
Allow Format dialog after backspace in empty text (BL-4423)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1570)

### CODE REVIEW

**Comment by hatton** [comment]
What's happening that current is null in the circumstances of BL-4423?

**Comment by StephenMcConnel** [comment]
I assume that backspacing at the beginning of the text box erases the styles associated with it.  I do know that 9 lines above the change is existing code that checks for current not being null before accessing it.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1570#-:-KfMWXlfBYMhVppzo44z:b-v5ahn6)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1570#-:-KfMZaGkDrFRo4qdZnsQ:bnfp4nl)*

**Comment by hatton** [comment]
I think we need to attempt to understand this error. It's like visiting a doctor... "Doc, it hurts when I do this". "Then don't do that". OK, maybe that's where we end up, but let's start with "What is actually happening? Might we fix that? If not, might it cause some other bug"? E.g,  what happens in the HTML when this backspace happens?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1570#-:-KfMj0cWHNyeMQSHVdy3:b-tjsodn)*

**Comment by StephenMcConnel** [comment]
What has happened is that the delete operation has removed all paragraph boxes from the text box.  So when the StyleEditor method getFormatValues() tries to retrieve the paragraph box, it returns an empty jquery, which then starts returning undefined values for the paragraph formatting values.  The actual call to populateSelect() is for "para-spaciing-select" with an undefined current value.  I'm not sure what the best fix is, or where the code lies that deletes the only paragraph from the text box.

If we do come up with a better fix, I would prefer either to leave the new check for current in place, or else remove the existing check a few lines above in the code.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1570#-:-KfNjKW_AR3iMIp0o_lT:b-otgpt8)*

**Comment by JohnThomson** [comment]
It's likely that deleting the paragraph when it's empty is a Mozilla behavior that has been around for a long time. It wasn't a problem before in this context because the style dialog initialization wasn't looking for paragraphs. Now that we have paragraph-level properties we look for to initialize in the dialog, it has become a problem. It's fairly easy to have the style dialog re-insert the missing paragraph. But, are there other things that may be messed up by the paragraphs being missing? And, are there formattable divs which shouldn't have paragraph elements? I vaguely recall they were optional at one point.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1570#-:-KfNuyxwbVoCgbFASRUJ:bqz3hpk)*

**Comment by hatton** [comment]
We did a fix in #1580

**Pull request closed without merging**
