### PR TITLE
Retain TemplateStarter betweeen 3.9 to 3.8 and back (BL-4491)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1628)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/Book.cs, line 146 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1628#-KgVkBmah-Flr__DSlnG:-KgVkBmah-Flr__DSlnH:b3kqzf2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f95e4e39dddc8d542975f246f048f8eed0714ccc/src/BloomExe/Book/Book.cs#L146)):*
> ```Smalltalk
> 			//{
> 			//	_storage.Dom.RemoveMetaElement("xmatter");
> 			//}
> ```

I don't think this is good enough. See my comment in the issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1628)*

**Comment by andrew-polk** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/BloomExe/Book/HtmlDom.cs, line 126 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1628#-Kgo5I6zVpHk_f6ITYhJ:-Kgo5I7-lKbAMX840Ugj:b-taqrwo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/03c5d082c8f8a42af205136b6486d51e4a9108ad/src/BloomExe/Book/HtmlDom.cs#L126)):*
> ```Smalltalk
> 		public void FixAnyAddedCustomPages()
> 		{
> 			foreach (XmlElement node in _dom.SafeSelectNodes("/html/body/div[contains(@class,'bloom-page') and contains(@class,'customPage')and @data-page='']"))
> ```

I think this is probably very similar to existing code elsewhere, but, technically, this is not future-proof for adding new classes such as bloom-page-hidden or bloom-page-do-not-modify-in-any-way, etc.
Perhaps it isn't worth is, since, as I say, we already have this problem elsewhere, but these contains really *ought* to be contains(concat(' ', normalize-space(@class), ' '), ' className ')

---

*[src/BloomExe/Book/HtmlDom.cs, line 129 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1628#-Kgo6ktFO6HHRAKKTVI9:-Kgo6ktFO6HHRAKKTVIA:bs61zqv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/03c5d082c8f8a42af205136b6486d51e4a9108ad/src/BloomExe/Book/HtmlDom.cs#L129)):*
> ```Smalltalk
> 			{
> 				node.SetAttribute("data-page", "extra");
> 				foreach (XmlElement label in node.SafeSelectNodes("div[@class='pageLabel']"))
> ```

Similar to above comment, this is not future-proof for the addition of more classes to labels.
(Assuming we want to make the change for any label which has that class rather than _only_ that class...)

---

*[src/BloomExe/Book/HtmlDom.cs, line 134 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1628#-Kgo6sI1uX3Va8zLmZy0:-Kgo6sI1uX3Va8zLmZy1:b-c1hzp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/03c5d082c8f8a42af205136b6486d51e4a9108ad/src/BloomExe/Book/HtmlDom.cs#L134)):*
> ```Smalltalk
> 					break;
> 				}
> 				foreach (XmlElement description in node.SafeSelectNodes("div[@class='pageDescription']"))
> ```

Same as above comment.

---

*[src/BloomExe/Book/HtmlDom.cs, line 136 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1628#-Kgo81FxAvRuvvpPxVAb:-Kgo81FxAvRuvvpPxVAc:b-210zng) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/03c5d082c8f8a42af205136b6486d51e4a9108ad/src/BloomExe/Book/HtmlDom.cs#L136)):*
> ```Smalltalk
> 				foreach (XmlElement description in node.SafeSelectNodes("div[@class='pageDescription']"))
> 				{
> 					description.InnerText = String.Empty;
> ```

While I am sure this works currently, I wonder if there is any way to better link the changes needed here to the actual differences between pages for templates. It just seems a little fragile. For example, if the code which generates templates starts doing something else different which could cause a break in this scenario, there is nothing alerting us that this code needs to be changed.
I don't have any good ideas (other than commenting...), but it is something to think about.

---

*[src/BloomExe/Book/HtmlDom.cs, line 1371 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1628#-Kgo3RASuWeBdTeLKuC3:-Kgo3RASuWeBdTeLKuC4:bq19w0x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/03c5d082c8f8a42af205136b6486d51e4a9108ad/src/BloomExe/Book/HtmlDom.cs#L1371)):*
> ```Smalltalk
> 		{
> 			var generator = GetMetaValue("Generator", "");
> 			var match = Regex.Match(generator, "[0-9]+(\\.[0-9]+)+");
> ```

I realize this isn't a result of your change, but this regex will not find, for example, "1" or "2". Are we confident that Bloom always included at least the major/minor?
The other thing, again not new with your change, which I find troubling about this implementation is that the meta tag actually allows for things other than "Bloom Version x.x.x", such as "PhotoStoryConverter 1.0". @Hatton, do we need to provide a strategy for this now? Since the converter is currently using the hydrator, I believe it ends up with "Bloom Version x.x.x", but that could change, or we could potentially have other tools used to generate Bloom books in the future.

Anyway, those shouldn't hold up this PR, but we may want to create (a) new card(s).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1628)*

**Comment by StephenMcConnel** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/BloomExe/Book/Book.cs, line 146 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1628#-KgVkBmah-Flr__DSlnG:-KgoSIbhXIj9dnkOASg7:b589qq2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f95e4e39dddc8d542975f246f048f8eed0714ccc/src/BloomExe/Book/Book.cs#L146)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't think this is good enough. See my comment in the issue.
</blockquote></details>

This has been restored, and rewritten to add a check for whether it's a template book.

---

*[src/BloomExe/Book/HtmlDom.cs, line 126 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1628#-Kgo5I6zVpHk_f6ITYhJ:-KgoTCt1dCzGGk1KQn8q:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/03c5d082c8f8a42af205136b6486d51e4a9108ad/src/BloomExe/Book/HtmlDom.cs#L126)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this is probably very similar to existing code elsewhere, but, technically, this is not future-proof for adding new classes such as bloom-page-hidden or bloom-page-do-not-modify-in-any-way, etc.
Perhaps it isn't worth is, since, as I say, we already have this problem elsewhere, but these contains really *ought* to be contains(concat(' ', normalize-space(@class), ' '), ' className ')
</blockquote></details>

Done.

---

*[src/BloomExe/Book/HtmlDom.cs, line 129 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1628#-Kgo6ktFO6HHRAKKTVI9:-KgoTwBO9Da_b_le76zZ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/03c5d082c8f8a42af205136b6486d51e4a9108ad/src/BloomExe/Book/HtmlDom.cs#L129)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Similar to above comment, this is not future-proof for the addition of more classes to labels.
(Assuming we want to make the change for any label which has that class rather than _only_ that class...)
</blockquote></details>

Done.

---

*[src/BloomExe/Book/HtmlDom.cs, line 134 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1628#-Kgo6sI1uX3Va8zLmZy0:-KgoTvbPc0gLYgKOP5CP:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/03c5d082c8f8a42af205136b6486d51e4a9108ad/src/BloomExe/Book/HtmlDom.cs#L134)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Same as above comment.
</blockquote></details>

Done.

---

*[src/BloomExe/Book/HtmlDom.cs, line 136 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1628#-Kgo81FxAvRuvvpPxVAb:-KgoUfrJ6iGKcgZBlgtL:b-gccu17) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/03c5d082c8f8a42af205136b6486d51e4a9108ad/src/BloomExe/Book/HtmlDom.cs#L136)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

While I am sure this works currently, I wonder if there is any way to better link the changes needed here to the actual differences between pages for templates. It just seems a little fragile. For example, if the code which generates templates starts doing something else different which could cause a break in this scenario, there is nothing alerting us that this code needs to be changed.
I don't have any good ideas (other than commenting...), but it is something to think about.
</blockquote></details>

Done.  Added a comment.

---

*[src/BloomExe/Book/HtmlDom.cs, line 1371 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1628#-Kgo3RASuWeBdTeLKuC3:-KgoaGA62fBXmnwvFSFx:b-ft0lkg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/03c5d082c8f8a42af205136b6486d51e4a9108ad/src/BloomExe/Book/HtmlDom.cs#L1371)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I realize this isn't a result of your change, but this regex will not find, for example, "1" or "2". Are we confident that Bloom always included at least the major/minor?
The other thing, again not new with your change, which I find troubling about this implementation is that the meta tag actually allows for things other than "Bloom Version x.x.x", such as "PhotoStoryConverter 1.0". @Hatton, do we need to provide a strategy for this now? Since the converter is currently using the hydrator, I believe it ends up with "Bloom Version x.x.x", but that could change, or we could potentially have other tools used to generate Bloom books in the future.

Anyway, those shouldn't hold up this PR, but we may want to create (a) new card(s).
</blockquote></details>

I created a new issue: http://issues.bloomlibrary.org/youtrack/issue/BL-4544.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1628)*

**Comment by hatton** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/BloomExe/Book/HtmlDom.cs, line 126 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1628#-Kgo5I6zVpHk_f6ITYhJ:-KgogriXcbEgNiq0sSvm:b62eq2y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/03c5d082c8f8a42af205136b6486d51e4a9108ad/src/BloomExe/Book/HtmlDom.cs#L126)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Doesn't that query assume the class is both preceded and followed by another class (or at least a space)? Maybe I'm reading it wrong.

---

*[src/BloomExe/Book/HtmlDom.cs, line 1371 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1628#-Kgo3RASuWeBdTeLKuC3:-KgohRXhCEHHOiOhj2dF:buquas1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/03c5d082c8f8a42af205136b6486d51e4a9108ad/src/BloomExe/Book/HtmlDom.cs#L1371)):*
> Are we confident that Bloom always included at least the major/minor?

Yes of course.

> "PhotoStoryConverter 1.0"

Yeah I don't know what to do about that. Probably wait for it to be a problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1628)*

**Comment by StephenMcConnel** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/BloomExe/Book/HtmlDom.cs, line 126 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1628#-Kgo5I6zVpHk_f6ITYhJ:-Kgoo0imfaOrK5pLbI6T:b1m5iwz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/03c5d082c8f8a42af205136b6486d51e4a9108ad/src/BloomExe/Book/HtmlDom.cs#L126)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Doesn't that query assume the class is both preceded and followed by another class (or at least a space)? Maybe I'm reading it wrong.
</blockquote></details>

The concat operation places a space at the beginning and the ending of the original class string so that the specific class with a space at each end will only match exactly, and will match anywhere in the list of (space separated) classes which now has spaces at the two ends as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1628)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1628#-:-KgotyD0jsQeQr9ockNw:bnfp4nl)*

**Pull request merged**
