### PR TITLE
BL-4556 Get Original Contributors copied

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1655)

### CODE REVIEW

**Comment by StephenMcConnel** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/BookData.cs, line 869 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655#-KhUAnuRotetJNBD84Zg:-KhUAnuRotetJNBD84Zh:byvgh5i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f879339c4d5e3b4f12f678a0e1c26e0e6d21a732/src/BloomExe/Book/BookData.cs#L869)):*
> ```Smalltalk
> 			// review: I want to do xmlNode.InnerText, but I have only a string that might not even be xml
> 			// is there a better way?
> 			return s.Replace("<p>", string.Empty).Replace("</p>", string.Empty).Replace("<p />", string.Empty) == string.Empty;
> ```

Are you absolutely sure we never have to replace "<p/>" (without the space inside)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655)*

**Comment by gmartin7** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/BookData.cs, line 869 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655#-KhUAnuRotetJNBD84Zg:-KhUCZF3Lm_I4sk9Uj2K:bqk9gv2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f879339c4d5e3b4f12f678a0e1c26e0e6d21a732/src/BloomExe/Book/BookData.cs#L869)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Are you absolutely sure we never have to replace "<p/>" (without the space inside)?
</blockquote></details>

Something didn't come through right in your comment. I don't understand what you're asking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655)*

**Comment by gmartin7** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/BookData.cs, line 869 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655#-KhUAnuRotetJNBD84Zg:-KhUCk8MBmqrZZO438hh:by9beb3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f879339c4d5e3b4f12f678a0e1c26e0e6d21a732/src/BloomExe/Book/BookData.cs#L869)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Something didn't come through right in your comment. I don't understand what you're asking.
</blockquote></details>

Oh. You mean the self-closing p tag with no space? I haven't seen one yet. I suppose that doesn't mean there couldn't be one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655)*

**Comment by StephenMcConnel** [comment]
:lgtm: but I'd happy for someone else to glance over this as well.  :-)

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/BookData.cs, line 869 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655#-KhUAnuRotetJNBD84Zg:-KhXziNobB300276GlmB:b-uo77rf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f879339c4d5e3b4f12f678a0e1c26e0e6d21a732/src/BloomExe/Book/BookData.cs#L869)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Oh. You mean the self-closing p tag with no space? I haven't seen one yet. I suppose that doesn't mean there couldn't be one.
</blockquote></details>

I guess the authors of this web interface think we want to do raw HTML formatting more than we want to discuss HTML elements directly.  :-)  How does &lt;p/&gt; look?  You did guess right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655#-:-KhY-wWnYuhqTLzfF_Yd:bfbzgh9)*

**Comment by JohnThomson** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/Book/BookData.cs, line 869 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655#-KhUAnuRotetJNBD84Zg:-KhY8FeHmUt8K0BBpg3l:bt1rtyh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f879339c4d5e3b4f12f678a0e1c26e0e6d21a732/src/BloomExe/Book/BookData.cs#L869)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I guess the authors of this web interface think we want to do raw HTML formatting more than we want to discuss HTML elements directly.  :-)  How does &lt;p/&gt; look?  You did guess right.
</blockquote></details>

Thoughts:
- `<br></br>/<br />/<br/>`? (Older Bloom's produced a lot of these)
- anything else 'invisible' you can think of? For example, I have vague recollections of cases where we stick in special space characters..ZWBS? ZWNBS? Next fix might deal with that.
@hatton, I have vague recollections of cases where an edit div could contain an image or label. Are those further things we should filter here?

---

*[src/BloomExe/Book/BookData.cs, line 860 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655#-KhYBBdBX_OJo1mR4UKT:-KhYBBdBX_OJo1mR4UKU:bni931v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1731130cc87cafcddac5aac6026c6eac4b2802e3/src/BloomExe/Book/BookData.cs#L860)):*
> ```Smalltalk
> 			}
> 		}
> ```

I see some modified examples will test this somewhat but I wonder if it's worth making it internal so you can make some direct test cases for it? Would be a good candidate for usin [Testcase] to make a bunch of tests with about one line of code...given various strings it should produce the right booleans.

---

*[src/BloomExe/Book/BookData.cs, line 869 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655#-KhY8ajUXnx9SskJhl3E:-KhY8ajUXnx9SskJhl3F:b-rc4byd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1731130cc87cafcddac5aac6026c6eac4b2802e3/src/BloomExe/Book/BookData.cs#L869)):*
> ```Smalltalk
> 			var strippedString =
> 				s.Replace("<p>", string.Empty).Replace("</p>", string.Empty).Replace("<p />", string.Empty).Replace("<p/>", string.Empty);
> 			return strippedString == string.Empty;
> ```

String.IsNullOrWhiteSpace(strippedString)? Could easily be various indent and newlines in between or inside empty paragraphs

---

*[src/BloomTests/Book/BookDataTests.cs, line 886 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655#-KhYAXh7t8DgsFHIhZGG:-KhYAXh7t8DgsFHIhZGH:b-s70ypn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1731130cc87cafcddac5aac6026c6eac4b2802e3/src/BloomTests/Book/BookDataTests.cs#L886)):*
> ```Smalltalk
> 		#endregion
> 
> 		private static string GetXpathContributorsForLang(string lang)
> ```

Name led me up the garden path...I was expecting it to return things that contributed to the XPath. Maybe GetXpathForContributionsInLang?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/Book/BookData.cs, line 869 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655#-KhUAnuRotetJNBD84Zg:-KhXMV1W85M4puCFylxn:b-wmmex0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f879339c4d5e3b4f12f678a0e1c26e0e6d21a732/src/BloomExe/Book/BookData.cs#L869)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Thoughts:
- `<br></br>/<br />/<br/>`? (Older Bloom's produced a lot of these)
- anything else 'invisible' you can think of? For example, I have vague recollections of cases where we stick in special space characters..ZWBS? ZWNBS? Next fix might deal with that.
@hatton, I have vague recollections of cases where an edit div could contain an image or label. Are those further things we should filter here?
</blockquote></details>

Sounds like what you really want is a proper regex that strips out tags and whitspace.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655)*

**Comment by gmartin7** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/Book/BookData.cs, line 869 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655#-KhUAnuRotetJNBD84Zg:-KhYI05u9LztPTP3a5xA:bhu0g1p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f879339c4d5e3b4f12f678a0e1c26e0e6d21a732/src/BloomExe/Book/BookData.cs#L869)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Sounds like what you really want is a proper regex that strips out tags and whitspace.
</blockquote></details>

StackOverflow says: Using a regular expression to parse HTML is fraught with pitfalls. HTML is not a regular language and hence can't be 100% correctly parsed with a regex.

I've made a test that checks all the br and p element possibilities. It fails on a zwnbs (xFEFF) testcase, but perhaps those would only be used where the user actually enters something?

---

*[src/BloomExe/Book/BookData.cs, line 860 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655#-KhYBBdBX_OJo1mR4UKT:-KhYVOdQV6wh5DeqoLAO:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1731130cc87cafcddac5aac6026c6eac4b2802e3/src/BloomExe/Book/BookData.cs#L860)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I see some modified examples will test this somewhat but I wonder if it's worth making it internal so you can make some direct test cases for it? Would be a good candidate for usin [Testcase] to make a bunch of tests with about one line of code...given various strings it should produce the right booleans.
</blockquote></details>

Done.

---

*[src/BloomExe/Book/BookData.cs, line 869 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655#-KhY8ajUXnx9SskJhl3E:-KhYSIvvkfraHIJ_P5I7:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1731130cc87cafcddac5aac6026c6eac4b2802e3/src/BloomExe/Book/BookData.cs#L869)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

String.IsNullOrWhiteSpace(strippedString)? Could easily be various indent and newlines in between or inside empty paragraphs
</blockquote></details>

Done.

---

*[src/BloomTests/Book/BookDataTests.cs, line 886 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655#-KhYAXh7t8DgsFHIhZGG:-KhYj-tHCtimWqb-V-ac:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1731130cc87cafcddac5aac6026c6eac4b2802e3/src/BloomTests/Book/BookDataTests.cs#L886)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Name led me up the garden path...I was expecting it to return things that contributed to the XPath. Maybe GetXpathForContributionsInLang?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655)*

**Comment by JohnThomson** [comment]
:lgtm: with one additional test suggested...feel free to merge, I don't need to see it again.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/BloomTests/Book/BookDataTests.cs, line 1042 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655#-Khc6txrmxTkdnyxO_bc:-Khc6txrmxTkdnyxO_bd:b-th26tj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2d835c76e960d888902ec10f9137c721da4043db/src/BloomTests/Book/BookDataTests.cs#L1042)):*
> ```Smalltalk
> 		[TestCase("<br></br>", ExpectedResult = true)]
> 		[TestCase("<br/>Bob", ExpectedResult = false)]
> 		[TestCase("<br />", ExpectedResult = true)]
> ```

Much improved. I would like to see at least one test case  where white space must be ignored AFTER removing some markup, and also check newlines, e.g., "/n <p>  /n</p>/n".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655#-:-Khc7Oo2ZTtXqWZdBajv:btv82jy)*

**Comment by gmartin7** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/BloomTests/Book/BookDataTests.cs, line 1042 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655#-Khc6txrmxTkdnyxO_bc:-KhcD-NnRZDAtDwe-CpG:b-sn2qmh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2d835c76e960d888902ec10f9137c721da4043db/src/BloomTests/Book/BookDataTests.cs#L1042)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Much improved. I would like to see at least one test case  where white space must be ignored AFTER removing some markup, and also check newlines, e.g., "/n <p>  /n</p>/n".
</blockquote></details>

OK, did that. The newline one I implemented with Environment.NewLine which required its own test, since the input string has to be a constant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1655)*

**Pull request merged**
