### PR TITLE
BL-5102 Comprehension Questions

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1937)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Let's not merge this until we see whether any tweaks are needed to make the BloomReader side of things easier.

**Comment by andrew-polk** [comment]
Reviewed 2 of 8 files at r1.
Review status: 2 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[DistFiles/localization/en/Bloom.xlf, line 713 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1937#-KyGu-hII8gQcPa2XyN8:-KyGu-hII8gQcPa2XyN9:bk3gaom) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a73d9b5674997c4bcf1e46c78024cf9d82ab6f93/DistFiles/localization/en/Bloom.xlf#L713)):*
> ```XML
>         <note>ID: EditTab.AddPageDialog.ChooseLayoutWillLoseData</note>
>       </trans-unit>
>       <trans-unit id="EditTab.AddPageDialog.EnterpriseCustomers" sil:dynamic="true">
> ```

Whitespace changes here are inconsistent.

---

*[src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.pug, line 29 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1937#-KyGuPLErWNPrcofQdtj:-KyGuPLErWNPrcofQdtk:b-epam6l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a73d9b5674997c4bcf1e46c78024cf9d82ab6f93/src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.pug#L29)):*
> CCs

What are CCs? I keep thinking creative commons.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1937)*

**Comment by JohnThomson** [comment]
Review status: 2 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.pug, line 29 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1937#-KyGuPLErWNPrcofQdtj:-KyHe5olWrzyQ7UHePWd:b-pa0lid) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a73d9b5674997c4bcf1e46c78024cf9d82ab6f93/src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.pug#L29)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> CCs

What are CCs? I keep thinking creative commons.
</blockquote></details>

Comprehension Questions. Should obviously be CQ, but somehow I got CC out of the similar initial sounds, I think. Will fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1937)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 8 files at r1, 5 of 8 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[DistFiles/localization/en/Bloom.xlf, line 713 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1937#-KyGu-hII8gQcPa2XyN8:-KyQnKpw1SdRyv2QpE_7:b-x9v781) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a73d9b5674997c4bcf1e46c78024cf9d82ab6f93/DistFiles/localization/en/Bloom.xlf#L713)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Whitespace changes here are inconsistent.
</blockquote></details>

Likely not a big deal, but the line below this still ended up with an unintended whitespace change.

---

*[src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.less, line 118 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1937#-KyQnXjNCxkGL-QGFR7a:-KyQnXjNCxkGL-QGFR7b:b-h91sb7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4b7097816589c8cbd0f7d63ef056778e8c63a6a4/src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.less#L118)):*
> ccLabel

quizLabel?

---

*[src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.pug, line 15 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1937#-KyQnZlRnXx6rDrb2Oge:-KyQnZlRnXx6rDrb2Ogf:bmqkqjf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4b7097816589c8cbd0f7d63ef056778e8c63a6a4/src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.pug#L15)):*
> cc-style

quiz-style?

---

*[src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.pug, line 22 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1937#-KyQnqlcUghCBm_-2ik1:-KyQnqlcUghCBm_-2ik2:b-1hlpxo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4b7097816589c8cbd0f7d63ef056778e8c63a6a4/src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.pug#L22)):*
> ```Pug
> 
> 		+include-standard-pages
> 		// note that these pages are NOT numbered.
> ```

Should all these comments be //- so they don't get transpiled into html?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1937)*

**Comment by JohnThomson** [comment]
Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[DistFiles/localization/en/Bloom.xlf, line 713 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1937#-KyGu-hII8gQcPa2XyN8:-KySroe0wR8gMhNb8mG7:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a73d9b5674997c4bcf1e46c78024cf9d82ab6f93/DistFiles/localization/en/Bloom.xlf#L713)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Likely not a big deal, but the line below this still ended up with an unintended whitespace change.
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.less, line 118 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1937#-KyQnXjNCxkGL-QGFR7a:-KySpfhR4DS-yoSNIs25:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4b7097816589c8cbd0f7d63ef056778e8c63a6a4/src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.less#L118)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ccLabel

quizLabel?
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.pug, line 15 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1937#-KyQnZlRnXx6rDrb2Oge:-KySqFNgRk8yeQNJ_5Ch:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4b7097816589c8cbd0f7d63ef056778e8c63a6a4/src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.pug#L15)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> cc-style

quiz-style?
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.pug, line 22 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1937#-KyQnqlcUghCBm_-2ik1:-KySqFByNX2PrllxZbrg:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4b7097816589c8cbd0f7d63ef056778e8c63a6a4/src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.pug#L22)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should all these comments be //- so they don't get transpiled into html?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1937)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1937#-:-KyWEaqVk-IVBWYV3VuR:bnfp4nl)*

**Pull request merged**
