### PR TITLE
BL5542 remove JQuery from music tsx

### PR DESCRIPTION
**Pull request by JohnThomson**
(Except for one interface implementation)

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2133)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx, line 135 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2133#-L4HkZZ2DwbDztBkzBF3:-L4HkZZ3iPJlFzVi9ETj:b64r5ne) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b686df3c8db7b21703d3cdae8e4c85e8d5cdc686/src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx#L135)):*
> ```XML
>             return;
>         }
>         this.getPlayer();
> ```

Don't care for relying on a side effect of something called get. The caching is ok, but... 

---

*[src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx, line 143 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2133#-L4HkdhL_N37YeeHb_A7:-L4HkdhL_N37YeeHb_A8:buiad1l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b686df3c8db7b21703d3cdae8e4c85e8d5cdc686/src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx#L143)):*
> ```XML
>         // src is a different URL, so the player treats it as a new sound to play.
>         // Without this it may not play if it hasn't changed.
>         this.player.setAttribute("src", musicUrl + "?nocache=" + new Date().getTime());
> ```

... how about just call getPlayer() everywhere?, or up above doing a 

    const player = this.getPlayer();

and then using that.

---

*[src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx, line 257 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2133#-L4HlBM2TD4bYG-Gagai:-L4HlBM2TD4bYG-Gagaj:b8b5xz7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b686df3c8db7b21703d3cdae8e4c85e8d5cdc686/src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx#L257)):*
> ```XML
>     makeRootElement(): HTMLDivElement {
>         const root = document.createElement("div");
>         root.setAttribute("class", "musicBody");
> ```

Probably I'm reading the jquery wrong, but I read it to as just a query, whereas this new thing seems to create a div and then set the class. Set me straight!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2133)*

**Comment by JohnThomson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx, line 135 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2133#-L4HkZZ2DwbDztBkzBF3:-L4HyxEGJoAUQ5iCIK5L:b-in0gdh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b686df3c8db7b21703d3cdae8e4c85e8d5cdc686/src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx#L135)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Don't care for relying on a side effect of something called get. The caching is ok, but... 
</blockquote></details>

I guess you're right. The trick is to get the event listener added only once, since raw JavaScript has no nice equivalent of .off() that I can find...you have to remember the function you previously added. I'll give it some more thought.

---

*[src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx, line 257 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2133#-L4HlBM2TD4bYG-Gagai:-L4HyIoeou0vERuJUQ_g:b7jci0z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b686df3c8db7b21703d3cdae8e4c85e8d5cdc686/src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx#L257)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Probably I'm reading the jquery wrong, but I read it to as just a query, whereas this new thing seems to create a div and then set the class. Set me straight!
</blockquote></details>

$("html") creates an element matching the HTML. Beats me how they can reliably distinguish a query asking to find an existing element from source code to make into a new one, but somehow the possible strings must be mutually exclusive. There doesn't seem to be a close equivalent outside jquery. But I believe the old and new code do the same thing. It seems to work, anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2133)*

**Comment by JohnThomson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx, line 135 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2133#-L4HkZZ2DwbDztBkzBF3:-L4I-lstDWcQkZX9p3gH:b-9x6uee) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b686df3c8db7b21703d3cdae8e4c85e8d5cdc686/src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx#L135)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I guess you're right. The trick is to get the event listener added only once, since raw JavaScript has no nice equivalent of .off() that I can find...you have to remember the function you previously added. I'll give it some more thought.
</blockquote></details>

OK, I think I found a better way. Fortunately only the one user of the element cares about the listener.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2133)*

**Comment by hatton** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx, line 131 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2133#-L4I7shiCEPxnoX5yBGU:-L4I7shiCEPxnoX5yBGV:b2q2kct) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d3cb46b4f5ff9bea7158a4759ba85270827b0a1a/src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx#L131)):*
> ```XML
>             return;
>         }
>         var player = this.getPlayer();
> ```

All of these ``var`` s should be const. I'm surprised tslint isn't squaking? But I'll merge this because you're waiting on it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2133)*

**Pull request merged**
