### PR TITLE
BL-5953 Start New Epub Screen

### PR DESCRIPTION
**Pull request by hatton**
Note: the change in BloomButton is hard to read because of formatting (sorry); I just fixed the className property handling so that it doens't throw away incoming classNames.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Looks like a promising start. A few niggles.

---

Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/BloomBrowserUI/publish/sectionScreen.less, line 46 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC4Ru6YBUNiR0rxmAc3:-LC4Ru6YBUNiR0rxmAc4:b-xdkk49) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aee5fef41f55ff95b22849c1354402cd3cd6a4e5/src/BloomBrowserUI/publish/sectionScreen.less#L46)):*
> ```Less
>         height: calc(
>             100% - (@verticalFudgeHack + @header-height + @screen-padding)
>         ); // enhance: is there a way to just fill to bottom?
> ```

Display:flex and use a weight(?) on the component that you want to stretch?

---

*[src/BloomBrowserUI/publish/epub/epubPublishUI.tsx, line 23 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC4SJVx3SV5Y4xP11rB:-LC4SJVx3SV5Y4xP11rC:bm4yk82) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aee5fef41f55ff95b22849c1354402cd3cd6a4e5/src/BloomBrowserUI/publish/epub/epubPublishUI.tsx#L23)):*
> ```XML
> const kWebSocketLifetime = "publish-epub";
> 
> interface IComponentState {}
> ```

You told me off for creating a state class before I had anything to put in it :-).  I'm sure you're going to have, but anyway, it should have a more specific name, like IPublishUIState.

---

*[src/BloomBrowserUI/publish/epub/epubPublishUI.tsx, line 66 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC4T59cEc6jJr--ytew:-LC4T59cEc6jJr--ytex:b-74pgbc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aee5fef41f55ff95b22849c1354402cd3cd6a4e5/src/BloomBrowserUI/publish/epub/epubPublishUI.tsx#L66)):*
> ```XML
>                     <H1 l10nKey="PublishTab.epub.Title">Create an Epub book</H1>
>                 </header>
>                 <div className={"sections"}>
> ```

Why does this need braces? Nothing is being computed. (Also elsewhere.)

---

*[src/BloomBrowserUI/publish/epub/epubPublishUI.tsx, line 131 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC4TzhZ7KacVndZ71F-:-LC4TzhZ7KacVndZ71F0:ba3wyp6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aee5fef41f55ff95b22849c1354402cd3cd6a4e5/src/BloomBrowserUI/publish/epub/epubPublishUI.tsx#L131)):*
> ```XML
> // get any not-in-a-class code called, including ours. But it only makes sense to get wired up
> // if that html has the root page we need.
> if (document.getElementById("EpubPublishUI")) {
> ```

Does this need to be wrapped in document.Ready or similar? Could the EpubPublishUIelement exist but not be loaded yet?

---

*[src/BloomBrowserUI/react_components/bloomButton.tsx, line 58 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC4UPnh8OSep8WR-c6u:-LC4UPnh8OSep8WR-c6v:b-rkk4od) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aee5fef41f55ff95b22849c1354402cd3cd6a4e5/src/BloomBrowserUI/react_components/bloomButton.tsx#L58)):*
> ```XML
>                     this.props.className +
>                     " " +
>                     (this.props.hidden ? "hidden" : "")
> ```

In similar contexts I like to put the space as " hidden" since we don't need it with the empty string. But maybe this way makes it less likely to get forgotten?

---

*[src/BloomExe/Publish/PublishView.cs, line 445 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC4V0wM3H4TEjkSQQes:-LC4V0wM3H4TEjkSQQet:b-ljwwj8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aee5fef41f55ff95b22849c1354402cd3cd6a4e5/src/BloomExe/Publish/PublishView.cs#L445)):*
> ```Smalltalk
> 			}
> 			if (displayMode != PublishModel.DisplayModes.Upload && displayMode != PublishModel.DisplayModes.EPUB && displayMode != PublishModel.DisplayModes.Android)
> 				if (displayMode != PublishModel.DisplayModes.Upload && displayMode != PublishModel.DisplayModes.EPUB && displayMode != PublishModel.DisplayModes.Android)
> ```

This line seems to have gotten in twice?

---

*[src/BloomExe/Publish/Epub2/EpubView2.cs, line 24 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC4VkrO0baxgzYf8cjg:-LC4VkrO0baxgzYf8cjh:bv7pfcq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aee5fef41f55ff95b22849c1354402cd3cd6a4e5/src/BloomExe/Publish/Epub2/EpubView2.cs#L24)):*
> ```Smalltalk
> 			// Has to be in front of the panel docked top for Fill to work.
> 			_browser.BringToFront();
> 			BloomFileLocator.GetBrowserFile(false, "gulpfile.js"); // WHAT???
> ```

I agree: WHAT? does something go wrong if you remove this line?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-:-LC4ccTDDqyR0tvB4Xxf:bi3cwqz)*

**Comment by andrew-polk** [comment]
Is the idea here to temporarily have two epub tabs and the old one will go away at some point?

---

Reviewed 14 of 20 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/BloomBrowserUI/publish/epub/EpubPreview.tsx, line 6 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC3wN-3DjfUQmvniCqt:-LC3wN-401rarmL1luKX:b-sjuwsp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aee5fef41f55ff95b22849c1354402cd3cd6a4e5/src/BloomBrowserUI/publish/epub/EpubPreview.tsx#L6)):*
> ```XML
> 
> interface IComponentState {}
> // This is a screen of controls that gives the user instructions and controls
> ```

This comment is not correct, is it?

---

*[src/BloomExe/Publish/Epub2/EpubView2.cs, line 24 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC4bJdCDLYdt79yacuz:-LC4bJdCDLYdt79yacv-:bc772nf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aee5fef41f55ff95b22849c1354402cd3cd6a4e5/src/BloomExe/Publish/Epub2/EpubView2.cs#L24)):*
> WHAT???

I agree. What is this??

---

*[src/BloomExe/Publish/Epub2/EpubView2.cs, line 31 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC4bkql6Zc37UbdE_Of:-LC4bkql6Zc37UbdE_Og:b-hrj88x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aee5fef41f55ff95b22849c1354402cd3cd6a4e5/src/BloomExe/Publish/Epub2/EpubView2.cs#L31)):*
> ```Smalltalk
> 		}
> 
> 		private string GetUrlParams()
> ```

Seems like we want a base class that AndroidView, EpubView2, and future views can implement so stuff like this can go there.

---

*[src/BloomExe/Publish/Epub2/EpubView2.Designer.cs, line 37 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC4axb_CtG7pSRYbUj9:-LC4axb_CtG7pSRYbUjA:bw03reb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aee5fef41f55ff95b22849c1354402cd3cd6a4e5/src/BloomExe/Publish/Epub2/EpubView2.Designer.cs#L37)):*
> ```Smalltalk
> 			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
> 			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
> 			this.Name = "AndroidView";
> ```

Copy/paste holdover. Or is it a Klingon?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-:-LC4c1UG737rhi4ru5Km:bbld8xh)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 6 files at r2.
Review status: 16 of 20 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/BloomBrowserUI/publish/epub/EpubPreview.tsx, line 6 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC3wN-3DjfUQmvniCqt:-LC5_uybCOPnhDb99Zy_:b-ddnqe9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aee5fef41f55ff95b22849c1354402cd3cd6a4e5/src/BloomBrowserUI/publish/epub/EpubPreview.tsx#L6)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

It's not great, but how is it incorrect?
</blockquote></details>

Isn't this just the preview itself (i.e. the picture of the device with content)? I don't think there are any instructions or controls there.

---

*[src/BloomExe/Publish/Epub2/EpubView2.cs, line 31 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC4bkql6Zc37UbdE_Of:-LC5a7IUBDcNeh66hxie:b-g8yu4x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aee5fef41f55ff95b22849c1354402cd3cd6a4e5/src/BloomExe/Publish/Epub2/EpubView2.cs#L31)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Gonna remove this, don't need it (and I think I would have just made an API call for it). We're going to re-do the Android screen to match the new epub one, that would be a good time to see what can be combined.
</blockquote></details>

I don't see why it is better to do it then as opposed to now. We know there are common things already (without looking, I would guess all but one line).

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386)*

**Comment by andrew-polk** [comment]
Reviewed 3 of 6 files at r2.
Review status: 19 of 20 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/BloomExe/Publish/PublishView.cs, line 551 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC5b0qi3RolQpDWa6M-:-LC5b0qi3RolQpDWa6M0:b-34lvoq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/60581ee1176522de9bc63b86827173a1d2e32903/src/BloomExe/Publish/PublishView.cs#L551)):*
> ```Smalltalk
> 					break;
> 				}
> 				case PublishModel.DisplayModes.EPUB2:
> ```

This case is identical to PublishModel.DisplayModes.Android except for one line.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386)*

**Comment by JohnThomson** [comment]
Review status: 19 of 20 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/BloomBrowserUI/publish/epub/epubPublishUI.tsx, line 66 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC4T59cEc6jJr--ytew:-LC5eLZwCTrdnYFjQoaY:b4xww0g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aee5fef41f55ff95b22849c1354402cd3cd6a4e5/src/BloomBrowserUI/publish/epub/epubPublishUI.tsx#L66)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Drat, somehow I got the idea that it was needed. Does appear to be needed for boolean properties, but not strings.
</blockquote></details>

You need it for computations, like {"sections" + (this.state.disabled ? " disabled" : ""} but not for simple strings. I wouldn't expect just true or false to work because they aren't valid HTML...to be that they'd have to be either quoted or braced.

---

*[src/BloomBrowserUI/publish/epub/epubPublishUI.tsx, line 131 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC4TzhZ7KacVndZ71F-:-LC5fAxW43plbxIxXM1G:bcfqw4e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aee5fef41f55ff95b22849c1354402cd3cd6a4e5/src/BloomBrowserUI/publish/epub/epubPublishUI.tsx#L131)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Conceivable (remember this is just a copy of the Android thing we've been shipping for a while)... spent 15 minute googling, could not find evidence that anyone is doing that. Did learn about script tags having a "defer"... but that and everything else I read was concerned about the script loading slowing down the initial page display.
</blockquote></details>

My understanding is that it would be OK as long as the element comes before the JS. Taking a closer look than I did the first time, it seems this one is, so it should be OK...but might break if someone decided to put the <script> tags in the root HTML document in the header. I might add a comment in the HTML to say not to do that.

---

*[src/BloomBrowserUI/react_components/bloomButton.tsx, line 58 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC4UPnh8OSep8WR-c6u:-LC5gQsx1GCbGtc_ZDDc:bn0nlvc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aee5fef41f55ff95b22849c1354402cd3cd6a4e5/src/BloomBrowserUI/react_components/bloomButton.tsx#L58)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Done. But resentful of having to figure out what you mean, for such an irrelevant difference :-)
</blockquote></details>

Sorry, wasn't trying to be obscure.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386)*

**Comment by hatton** [comment]
Review status: 19 of 20 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/BloomExe/Publish/PublishView.cs, line 551 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC5b0qi3RolQpDWa6M-:-LC6mse13fZ3TondBHAJ:btqv2mf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/60581ee1176522de9bc63b86827173a1d2e32903/src/BloomExe/Publish/PublishView.cs#L551)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This case is identical to PublishModel.DisplayModes.Android except for one line.
</blockquote></details>

Yes, like I said, I wanted to refactor soon when I'd have time to do a proper job. The code in this class is obscenely verbose for how little it does. But I've come up with a small simplification for now.

---

*[src/BloomExe/Publish/Epub2/EpubView2.cs, line 31 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC4bkql6Zc37UbdE_Of:-LC6nWme3dEVYmjOdZY1:b-jrtw58) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aee5fef41f55ff95b22849c1354402cd3cd6a4e5/src/BloomExe/Publish/Epub2/EpubView2.cs#L31)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't see why it is better to do it then as opposed to now. We know there are common things already (without looking, I would guess all but one line).
</blockquote></details>

In the rare times when I think I can get away from PM'ing & UX'ing and do some foundational coding to head off the constant growth of spagetti, I have to keep the scope small or my project becomes a hold up for others. But  fine, I've come up with something for now.  Baseclass was not the right solution.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386)*

**Comment by JohnThomson** [comment]
Looks basically good. Couple of minor suggestions.

---

Reviewed 2 of 8 files at r2, 19 of 26 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/HtmlPublishPanel.cs, line 8 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC9g5TU7g46jIV9lFlI:-LC9g5TU7g46jIV9lFlJ:bhak781) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8963384dd193098860d1d20b8a52aa13d25f25ae/src/BloomExe/Publish/HtmlPublishPanel.cs#L8)):*
> ```Smalltalk
> {
> 	/// <summary>
> 	/// This class implements a panel that appears in the Publish tab, for which the UI is an html component.
> ```

I think I finally figured out that the idea is that this is shared (or inherited from?) by all the publish tabs that are implemented in HTML. Maybe, 
"This class implements all the Publish tab panels that are done as HTML pages, typically containing React controls, such as the Android and Epub ones. Which tab it implements is determined by the root HTML file path passed to its constructor."
If I'm wrong and it's only for Epub, the name is too generic.

---

*[src/BloomExe/Publish/HtmlPublishPanel.cs, line 14 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC9igfo4CvzS3XmFlkS:-LC9igfo4CvzS3XmFlkT:b-a1zv0v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8963384dd193098860d1d20b8a52aa13d25f25ae/src/BloomExe/Publish/HtmlPublishPanel.cs#L14)):*
> ```Smalltalk
> 		private Browser _browser;
> 
> 		public HtmlPublishPanel(NavigationIsolator isolator, string path)
> ```

path deserves a more descriptive name in view of its central role in the class...maybe "pathToRootHtmlFile"?
It might also be useful for debugging to save it in a member variable (e.g., to help tell which HtmlPublishPanel I am looking at, or that the file locator found the wrong version...)

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-:-LC9jYhz-r9FBsZ0E0lC:b-lf0mb7)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/publish/epub/EpubPreview.tsx, line 6 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC3wN-3DjfUQmvniCqt:-LC9qIeN6aEKJ5zMkJ8u:b-gutk1e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aee5fef41f55ff95b22849c1354402cd3cd6a4e5/src/BloomBrowserUI/publish/epub/EpubPreview.tsx#L6)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Isn't this just the preview itself (i.e. the picture of the device with content)? I don't think there are any instructions or controls there.
</blockquote></details>

Ick, sorry, I both was in the wrong place when I added it, and in the wrong place (in my mind) when I read you comment.

---

*[src/BloomExe/Publish/HtmlPublishPanel.cs, line 8 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC9g5TU7g46jIV9lFlI:-LC9qWyNBCSjAXPTsgNk:b-qnyt36) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8963384dd193098860d1d20b8a52aa13d25f25ae/src/BloomExe/Publish/HtmlPublishPanel.cs#L8)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think I finally figured out that the idea is that this is shared (or inherited from?) by all the publish tabs that are implemented in HTML. Maybe, 
"This class implements all the Publish tab panels that are done as HTML pages, typically containing React controls, such as the Android and Epub ones. Which tab it implements is determined by the root HTML file path passed to its constructor."
If I'm wrong and it's only for Epub, the name is too generic.
</blockquote></details>

I do not like comments like that, speculating on what might be in the html you write, what the implementations are at the moment, etc. E.g.,  once the path parameter has a better name as you mention below (pathToRootHtmlFile) if a programmer reads that and still needs to be told "Which tab it implements is determined by the root HTML file path passed to its constructor" then I don't think we want them in the code base.

---

*[src/BloomExe/Publish/HtmlPublishPanel.cs, line 14 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC9igfo4CvzS3XmFlkS:-LC9s8b2BhNyHOS3zy5M:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8963384dd193098860d1d20b8a52aa13d25f25ae/src/BloomExe/Publish/HtmlPublishPanel.cs#L14)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

path deserves a more descriptive name in view of its central role in the class...maybe "pathToRootHtmlFile"?
It might also be useful for debugging to save it in a member variable (e.g., to help tell which HtmlPublishPanel I am looking at, or that the file locator found the wrong version...)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 3 of 23 files at r1, 1 of 8 files at r2, 2 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-:-LC9smzu41a18EeWNMLw:bnfp4nl)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/HtmlPublishPanel.cs, line 8 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC9g5TU7g46jIV9lFlI:-LC9wR179uxdCVq36NgQ:brzxeaa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8963384dd193098860d1d20b8a52aa13d25f25ae/src/BloomExe/Publish/HtmlPublishPanel.cs#L8)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I do not like comments like that, speculating on what might be in the html you write, what the implementations are at the moment, etc. E.g.,  once the path parameter has a better name as you mention below (pathToRootHtmlFile) if a programmer reads that and still needs to be told "Which tab it implements is determined by the root HTML file path passed to its constructor" then I don't think we want them in the code base.
</blockquote></details>

It feels to me that I spend an inordinate amount of my time (and much more when I was new to Bloom) trying to find the code that is actually responsible for the screen area I want to change, and even when I've found it, it's often hard to be sure I have. So I'm very keen on class comments that make this clear. When I first read this comment about a class that implements "a panel" I want to shout "WHICH ONE??!" Of course the answer that eventually emerges is, several (and likely to increase). How about, "This configurable class provides a C# wrapper for several of the publish option panels that appear in the Publish tab, for which the UI is an html component"?
If that or something like it doesn't feel like an improvement go ahead and merge. It's not that important.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386)*

**Comment by hatton** [comment]
Review status: 29 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/HtmlPublishPanel.cs, line 8 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386#-LC9g5TU7g46jIV9lFlI:-LCA0Z13BXfbGqw_tXY6:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8963384dd193098860d1d20b8a52aa13d25f25ae/src/BloomExe/Publish/HtmlPublishPanel.cs#L8)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It feels to me that I spend an inordinate amount of my time (and much more when I was new to Bloom) trying to find the code that is actually responsible for the screen area I want to change, and even when I've found it, it's often hard to be sure I have. So I'm very keen on class comments that make this clear. When I first read this comment about a class that implements "a panel" I want to shout "WHICH ONE??!" Of course the answer that eventually emerges is, several (and likely to increase). How about, "This configurable class provides a C# wrapper for several of the publish option panels that appear in the Publish tab, for which the UI is an html component"?
If that or something like it doesn't feel like an improvement go ahead and merge. It's not that important.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2386)*

**Comment by JohnThomson** [comment]
Nice work getting rid of redundant code rather than adding more!

**Pull request merged**
