### PR TITLE
BookInfoIndicator does not show theme if none determined (BL-13006)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6279)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6279)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6279#-NpVgJ6j8JHm7jlaa5ON):*
Should the commit message be something like,
"Hide theme name in BookInfoIndicator if none determined"
?
___
*[`src/BloomExe/Book/AppearanceSettings.cs` line 158 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6279#-NpVgXXJ1swIn9ESabda:-NpVgXXJ1swIn9ESabdb:bu0ezw8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/58b9f1f102714041394592c0f2ec86e3e0bd2225/src/BloomExe/Book/AppearanceSettings.cs#L158)):*
> ThemNameForBookInfo

ThemeNameForBookInfo


Is `ThemeNameForDisplay` better?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6279)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6279#-NpVgJ6j8JHm7jlaa5ON):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should the commit message be something like,
"Hide theme name in BookInfoIndicator if none determined"
?
</blockquote></details>

I don't find it any clearer, but it's at least as good, so I went ahead and changed it.
___
*[`src/BloomExe/Book/AppearanceSettings.cs` line 158 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6279#-NpVgXXJ1swIn9ESabda:-NpW02mf7L1cCox03rym:b-y10era) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/58b9f1f102714041394592c0f2ec86e3e0bd2225/src/BloomExe/Book/AppearanceSettings.cs#L158)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ThemNameForBookInfo

ThemeNameForBookInfo


Is `ThemeNameForDisplay` better?
</blockquote></details>

I don't think so. "ForDisplay" suggests to me localization or some other way of prettifying the name to make it more readable. This function doesn't do that, it just has a special case for the situation where we don't have a definite theme name in the json. As far as I can predict, it will only ever be used for this one purpose. I added "Indicator" and a comment to hopefully make things clearer.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6279)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Book/AppearanceSettings.cs` line 158 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6279#-NpVgXXJ1swIn9ESabda:-NpW3KD6BfcX6zvUVmEb:b-d6ri3z) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/58b9f1f102714041394592c0f2ec86e3e0bd2225/src/BloomExe/Book/AppearanceSettings.cs#L158)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't think so. "ForDisplay" suggests to me localization or some other way of prettifying the name to make it more readable. This function doesn't do that, it just has a special case for the situation where we don't have a definite theme name in the json. As far as I can predict, it will only ever be used for this one purpose. I added "Indicator" and a comment to hopefully make things clearer.
</blockquote></details>

`ThemeNameForDisplay` Sounds right to me, too

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6279)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Book/AppearanceSettings.cs` line 158 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6279#-NpVgXXJ1swIn9ESabda:-NpWJ3KJ5Tabp6N_5Bon:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/58b9f1f102714041394592c0f2ec86e3e0bd2225/src/BloomExe/Book/AppearanceSettings.cs#L158)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

`ThemeNameForDisplay` Sounds right to me, too
</blockquote></details>

Done.

**Comment by andrew-polk** [comment]
*[`src/BloomExe/Book/AppearanceSettings.cs` line 158 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6279#-NpVgXXJ1swIn9ESabda:-NpWL10PAFMCu33J95Kb:bs8pz6m) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/58b9f1f102714041394592c0f2ec86e3e0bd2225/src/BloomExe/Book/AppearanceSettings.cs#L158)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still missed the final "e" in Theme.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6279)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6279)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/Book/AppearanceSettings.cs` line 158 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6279#-NpVgXXJ1swIn9ESabda:-NpWQ9Iy9yKUFaZH01RS:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/58b9f1f102714041394592c0f2ec86e3e0bd2225/src/BloomExe/Book/AppearanceSettings.cs#L158)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Still missed the final "e" in Theme.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6279)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
