### PR TITLE
Add palette enum to ColorPickerDialog (BL-11433)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This includes persisting custom color choices by users in the collection
settings.

- - -
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348)* status: all files reviewed, 6 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/react_components/colorPickerDialog.tsx` line 32 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348#-N9mLw096yHiWBL_Lskj:-N9mLw096yHiWBL_Lskk:btwt1az) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d1b0581b1d039a561d3da04823a9af770c2e6bf9/src/BloomBrowserUI/react_components/colorPickerDialog.tsx#L32)):*
> ```XML
>     Text = "text",
>     CoverBackground = "cover-background",
>     BloomReaderBookshelf = "BloomReader-bookshelf",
> ```

My preference would be `bloom-reader-bookshelf`



_Code quote:_
```XML
BloomReader-bookshelf
```

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348)* status: all files reviewed, 7 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/react_components/colorPickerDialog.tsx` line 34 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348#-N9mM3je90if_C2UDxvI:-N9mM3je90if_C2UDxvJ:b-n99u1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d1b0581b1d039a561d3da04823a9af770c2e6bf9/src/BloomBrowserUI/react_components/colorPickerDialog.tsx#L34)):*
> ```XML
>     BloomReaderBookshelf = "BloomReader-bookshelf",
>     OverlayText = "overlay-text",
>     OverlayBackground = "overlay-background"
> ```

I wonder if we should go ahead and make this more generic. Something like `text-background`?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348)* status: all files reviewed, 7 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomBrowserUI/react_components/colorPickerDialog.tsx` line 32 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348#-N9mLw096yHiWBL_Lskj:-N9mWQQG4gPKSUw-iBI3:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d1b0581b1d039a561d3da04823a9af770c2e6bf9/src/BloomBrowserUI/react_components/colorPickerDialog.tsx#L32)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

My preference would be `bloom-reader-bookshelf`
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/react_components/colorPickerDialog.tsx` line 33 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348#-N9mIJW1ELwH9PtCisJo:-N9mWdWA3klX8aoD7sH6:b-efbg6q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d1b0581b1d039a561d3da04823a9af770c2e6bf9/src/BloomBrowserUI/react_components/colorPickerDialog.tsx#L33)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The two text ones have be merged somehow. In other words, the overlay tool must use the default `text` pallete.
</blockquote></details>

I'm not convinced that the standard palettes and overlay palettes are the same.  We've been using the 4-level grayscale palette as the base for overlay text color choosing since the beginning.  For the default palette that @hatton came up with recently, he dropped the two gray colors and added 15 new colors for the base palette of choosing text colors in the normal text boxes.  I'd want to hear from @hatton before merging the text and background palettes as you suggest.
___
*[`src/BloomBrowserUI/react_components/colorPickerDialog.tsx` line 34 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348#-N9mM3je90if_C2UDxvI:-N9mYQME3wkfbCAyi596:b-5k1emq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d1b0581b1d039a561d3da04823a9af770c2e6bf9/src/BloomBrowserUI/react_components/colorPickerDialog.tsx#L34)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I wonder if we should go ahead and make this more generic. Something like `text-background`?
</blockquote></details>

As I said, I'm not sure that the standard palettes and the overlay palettes are the same.
Note that there may be other palettes added later.  These are just the ones I saw lying around in the code already used in color choosing.  (plus one that @hatton provided for the recent color dialog work.)
___
*[`src/BloomBrowserUI/react_components/colorPickerDialog.tsx` line 103 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348#-N9mHuB1DGciBuckLyO9:-N9mYNVS7PmKtrEcim_1:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d1b0581b1d039a561d3da04823a9af770c2e6bf9/src/BloomBrowserUI/react_components/colorPickerDialog.tsx#L103)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Can this switch be replaced with something like
```
let getColorsApiCall: string = "editView/getBookColors";
if (props.pallette) {
  getColorsApiCall = `settings/getCustomPaletteColors?palette=${props.pallete.toString()}`
}
```
?
(and similar for the add color call?)
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/react_components/colorPickerDialog.tsx` line 104 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348#-N9mJvq-9ItJoRuFvAHV:-N9mVuK08nkvTCRXX36c:baccsaq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d1b0581b1d039a561d3da04823a9af770c2e6bf9/src/BloomBrowserUI/react_components/colorPickerDialog.tsx#L104)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Did you consider the pros/cons of having the default and custom color lists provided from the server rather than merging them here?
One obvious advantage of what you have is that you already have it. : )
</blockquote></details>

If everything came from the server, we'd have to re-implement the merge code in C#.  At the moment, I'd much rather keep to what we've been using.
___
*[`src/BloomBrowserUI/react_components/colorPickerDialog.tsx` line 427 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348#-N9mJHQT1zgBOD7SR2dp:-N9mg1JZ2D1F9_9AjL0D:b-cy55g3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d1b0581b1d039a561d3da04823a9af770c2e6bf9/src/BloomBrowserUI/react_components/colorPickerDialog.tsx#L427)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not excited about all these being copied here.
Should we either 
1. Wait until we can retire the other ones
2. Make the other code reference these here now so the other lists can be removed

?
</blockquote></details>

overlayToolColorHelper.ts is a skeleton of its former self, but further refactoring can wait for converting the overlay tool all the way to using palettes, which I think may go beyond the scope of this issue.  At least for an initial merge that gets palettes implemented.
___
*[`src/BloomExe/Collection/CollectionSettings.cs` line 855 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348#-N9mL2oS8-SKirGThUnK:-N9mk5kR04wEQcsFjXJ7:b-uzbmso) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d1b0581b1d039a561d3da04823a9af770c2e6bf9/src/BloomExe/Collection/CollectionSettings.cs#L855)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

These methods probably need some unit tests.
</blockquote></details>

Could be.  I don't have time today with harvester issues.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348)* status: 3 of 7 files reviewed, 7 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomExe/Collection/CollectionSettings.cs` line 855 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348#-N9mL2oS8-SKirGThUnK:-N9n03Z_A_h_JgoMU3fH:bc6yqhe) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d1b0581b1d039a561d3da04823a9af770c2e6bf9/src/BloomExe/Collection/CollectionSettings.cs#L855)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Could be.  I don't have time today with harvester issues.
</blockquote></details>

I've added a unit that exercises both of these methods.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348)* status: 3 of 7 files reviewed, 7 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomExe/Collection/CollectionSettings.cs` line 855 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348#-N9mL2oS8-SKirGThUnK:-N9n0OfN-Kd6lqHKZ8mo:bnysk31) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d1b0581b1d039a561d3da04823a9af770c2e6bf9/src/BloomExe/Collection/CollectionSettings.cs#L855)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I've added a unit that exercises both of these methods.
</blockquote></details>

unit test  :-)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[`src/BloomBrowserUI/react_components/colorPickerDialog.tsx` line 464 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348#-N9n7H8J-ttrs-KvGtr3:-N9n7H8J-ttrs-KvGtr4:b-h2q9zj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7cf6ca9428b0c4ce4eb1c0b5097b3eb1eadc710e/src/BloomBrowserUI/react_components/colorPickerDialog.tsx#L464)):*
> ```XML
> // Handles all types of color strings: special-named, hex, rgb(), or rgba().
> // If BubbleSpec entails opacity, this string should be of the form "rgba(r, g, b, a)".
> export const getSwatchFromBubbleSpecColor = (
> ```

If I understand correctly, this is more like getSwatchFromColorString now (not specific to bubbles).

But then I'm confused because this method calls something called getSwatchFromColorSpec

**Review by gmartin7 — APPROVED** [review]
> Reviewed 2 of 7 files at r4, 3 of 4 files at r6, 12 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton)

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/react_components/colorPickerDialog.tsx` line 33 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348#-N9mIJW1ELwH9PtCisJo:-NAKrXe-2voO8vy4ECu2:b6qdtq7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d1b0581b1d039a561d3da04823a9af770c2e6bf9/src/BloomBrowserUI/react_components/colorPickerDialog.tsx#L33)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I'm not convinced that the standard palettes and overlay palettes are the same.  We've been using the 4-level grayscale palette as the base for overlay text color choosing since the beginning.  For the default palette that @hatton came up with recently, he dropped the two gray colors and added 15 new colors for the base palette of choosing text colors in the normal text boxes.  I'd want to hear from @hatton before merging the text and background palettes as you suggest.
</blockquote></details>

We decided that @hatton will come along behind me after this is merged and make all the palette choices.
___
*[`src/BloomBrowserUI/react_components/colorPickerDialog.tsx` line 34 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5348#-N9mM3je90if_C2UDxvI:-NAKrc3h18oMnAknO2B2:b6qdtq7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d1b0581b1d039a561d3da04823a9af770c2e6bf9/src/BloomBrowserUI/react_components/colorPickerDialog.tsx#L34)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

As I said, I'm not sure that the standard palettes and the overlay palettes are the same.
Note that there may be other palettes added later.  These are just the ones I saw lying around in the code already used in color choosing.  (plus one that @hatton provided for the recent color dialog work.)
</blockquote></details>

We decided that @hatton will come along behind me after this is merged and make all the palette choices.

**Pull request merged**
