### PR TITLE
Use collection ID to detect books from other collections (BL-9705)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300)

### CODE REVIEW

**Review by hatton — COMMENTED** [review]
> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300)* status: 2 of 11 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 741 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300#-MWWJwVIBFabGYE_tXze:-MWWJwVIBFabGYE_tXzf:b6nvheg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/66c017c27fff6ceec2369f61547605c305f3588d/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L741)):*
> ```Smalltalk
> 			if (collectionId != null)
> 			{
> 				children.Add(new XElement("Id", new XText(collectionId)));
> ```

Not a big deal by any stretch, but normally this would be an attribute?

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300)* status: 2 of 11 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 63 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300#-MWWKHLs3UN82mrqdIQv:-MWWKHLs3UN82mrqdIQw:b6s32qm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/66c017c27fff6ceec2369f61547605c305f3588d/src/BloomExe/TeamCollection/TeamCollection.cs#L63)):*
> ```Smalltalk
> 		}
> 
> 		public string CollectionId {
> ```

Correct me if I'm wrong, but unless you're publishing this as a library that has an api you don't want to change, this doesn't buy you anything more than

`public string CollectionId;`
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 337 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300#-MWWKeDu78oLf7PlBw_9:-MWWKeDu78oLf7PlBw_A:b-vekf6n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/66c017c27fff6ceec2369f61547605c305f3588d/src/BloomExe/TeamCollection/TeamCollection.cs#L337)):*
> ```Smalltalk
> 		public void WriteBookStatus(string bookName, BookStatus status)
> 		{
> 			// No reason to take up space in the repo with a collection ID that is purely local.
> ```

I don't understand  this comment. What does "purely local" mean? Is there a decision being made here that I don't see?

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300)* status: 2 of 11 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 141 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300#-MWWLUeeBfPGemTgDsrD:-MWWLUeeBfPGemTgDsrE:bv3pscy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/66c017c27fff6ceec2369f61547605c305f3588d/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L141)):*
> ```Smalltalk
> 					if (Directory.Exists(repoFolderPath))
> 					{
> 						var newCollectionId = string.IsNullOrEmpty(collectionId);
> ```

Sorry to do this to you again, but I tripped later on because this reads as either "The id of a new collection" or "a new collection id".  But what you mean is "needsACollectionId". 

I would pretty strongly recommend not adding migration code like this at this point. It's a trivial matter to just delete all existing Team Collections until we get the file formats done.

**Review by hatton — COMMENTED** [review]
> Reviewed 6 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300)* status: 8 of 11 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300)* status: 7 of 11 files reviewed, 4 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 741 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300#-MWWJwVIBFabGYE_tXze:-MWZS3Yc9AGooI0CEkDk:b-x9l8xt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/66c017c27fff6ceec2369f61547605c305f3588d/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L741)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Not a big deal by any stretch, but normally this would be an attribute?
</blockquote></details>

Yes, commonly ID is an attribute used to find some element within the file. But in this case, it is one of the (currently only two) main pieces of information stored in the file; it is not the ID of some XmlElement but of the collection that the whole XML file describes. We certainly could choose to make both the ID and the repo path attributes of the root element, or replace the whole file with JSON, or CSV...there is so little to choose that I can hardly make a case one way or the other. But nor do I see any case for changing what is done.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 63 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300#-MWWKHLs3UN82mrqdIQv:-MWZS07C4cktNaE-XXee:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/66c017c27fff6ceec2369f61547605c305f3588d/src/BloomExe/TeamCollection/TeamCollection.cs#L63)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Correct me if I'm wrong, but unless you're publishing this as a library that has an api you don't want to change, this doesn't buy you anything more than

`public string CollectionId;`
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 337 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300#-MWWKeDu78oLf7PlBw_9:-MWZTo6x4zF_U03_RwJT:bwhcyvh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/66c017c27fff6ceec2369f61547605c305f3588d/src/BloomExe/TeamCollection/TeamCollection.cs#L337)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I don't understand  this comment. What does "purely local" mean? Is there a decision being made here that I don't see?
</blockquote></details>

I've tried to clarify.
___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 141 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300#-MWWLUeeBfPGemTgDsrD:-MWZXk2XD75jIEpUNOBQ:ba3dfob) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/66c017c27fff6ceec2369f61547605c305f3588d/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L141)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Sorry to do this to you again, but I tripped later on because this reads as either "The id of a new collection" or "a new collection id".  But what you mean is "needsACollectionId". 

I would pretty strongly recommend not adding migration code like this at this point. It's a trivial matter to just delete all existing Team Collections until we get the file formats done.
</blockquote></details>

Removed

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300)* status: 7 of 11 files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 337 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300#-MWWKeDu78oLf7PlBw_9:-MW_-XL10DS43hruvs_9:b-1vps93) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/66c017c27fff6ceec2369f61547605c305f3588d/src/BloomExe/TeamCollection/TeamCollection.cs#L337)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I've tried to clarify.
</blockquote></details>

JT is going to see if, were we to put this id in the CollectionSettings, it the TeamCollection would still be able to get at it when starting up. Then this would be truly a collection id, shared by all team members.

Failing that, we could fall back to call it "LocalCollectionId" or some such, though that's still awkward.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300)* status: 3 of 14 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 337 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300#-MWWKeDu78oLf7PlBw_9:-MW_8nFv75Jc6VdpdrIF:bjvfbzz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/66c017c27fff6ceec2369f61547605c305f3588d/src/BloomExe/TeamCollection/TeamCollection.cs#L337)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

JT is going to see if, were we to put this id in the CollectionSettings, it the TeamCollection would still be able to get at it when starting up. Then this would be truly a collection id, shared by all team members.

Failing that, we could fall back to call it "LocalCollectionId" or some such, though that's still awkward.
</blockquote></details>

OK, CollectionId now belongs to CollectionSettings. It's slightly awkward to get it to the TC before it is needed, but I think less of a problem than a CollectionId that isn't common to all copies of the collection.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300)* status: 2 of 13 files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/Collection/CollectionSettings.cs, line 298 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300#-MWa6Zp-9d1-xLI0m7Kf:-MWa6Zp-9d1-xLI0m7Kg:b-pnupiq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ceaec55bf9e8b149d4adf4c9649ae3c25a6e4d9b/src/BloomExe/Collection/CollectionSettings.cs#L298)):*
> ```Smalltalk
> 			XElement xml = new XElement("Collection");
> 			xml.Add(new XAttribute("version", "0.2"));
> 			xml.Add(new XElement("CollectionId", CollectionId));
> ```

Why an element instead of a `id` attribute?

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300)* status: 2 of 13 files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/Collection/CollectionSettings.cs, line 298 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300#-MWa6Zp-9d1-xLI0m7Kf:-MWa793YBagcXPOpHvJc:b7nygt8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ceaec55bf9e8b149d4adf4c9649ae3c25a6e4d9b/src/BloomExe/Collection/CollectionSettings.cs#L298)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Why an element instead of a `id` attribute?
</blockquote></details>

It's fine though, if you like it. I suppose reasonable people could have different preferences.

**Review by hatton — COMMENTED** [review]
> Reviewed 11 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/Collection/CollectionSettings.cs, line 298 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300#-MWa6Zp-9d1-xLI0m7Kf:-MWa8KWo0u61pxiPjz9X:bor00tr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ceaec55bf9e8b149d4adf4c9649ae3c25a6e4d9b/src/BloomExe/Collection/CollectionSettings.cs#L298)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

It's fine though, if you like it. I suppose reasonable people could have different preferences.
</blockquote></details>

It was a bit arbitrary in TeamCollection.xml, but here, EVERY other bit of data about the collection is saved as an element (except the version attribute on the root Collection element, which is more a property of the XML than the collection).
<CollectionId>ab08bd62-3f24-420b-bb51-dd5d144913d4</CollectionId>
  <Language1Name>English</Language1Name>
  <Language1IsCustomName>false</Language1IsCustomName>
  <Language1Iso639Code>en</Language1Iso639Code>
  <DefaultLanguage1FontName>Andika New Basic</DefaultLanguage1FontName>
  <IsLanguage1Rtl>false</IsLanguage1Rtl>
  <Language1LineHeight>0</Language1LineHeight>
...etc

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/Collection/CollectionSettings.cs, line 298 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4300#-MWa6Zp-9d1-xLI0m7Kf:-MWa9lEaCAH-9jpZ-aw0:b-bbzfw5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ceaec55bf9e8b149d4adf4c9649ae3c25a6e4d9b/src/BloomExe/Collection/CollectionSettings.cs#L298)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It was a bit arbitrary in TeamCollection.xml, but here, EVERY other bit of data about the collection is saved as an element (except the version attribute on the root Collection element, which is more a property of the XML than the collection).
<CollectionId>ab08bd62-3f24-420b-bb51-dd5d144913d4</CollectionId>
  <Language1Name>English</Language1Name>
  <Language1IsCustomName>false</Language1IsCustomName>
  <Language1Iso639Code>en</Language1Iso639Code>
  <DefaultLanguage1FontName>Andika New Basic</DefaultLanguage1FontName>
  <IsLanguage1Rtl>false</IsLanguage1Rtl>
  <Language1LineHeight>0</Language1LineHeight>
...etc
</blockquote></details>

Grrrr.
```
  <CollectionId>ab08bd62-3f24-420b-bb51-dd5d144913d4</CollectionId>
  <Language1Name>English</Language1Name>
  <Language1IsCustomName>false</Language1IsCustomName>
  <Language1Iso639Code>en</Language1Iso639Code>
  <DefaultLanguage1FontName>Andika New Basic</DefaultLanguage1FontName>
  <IsLanguage1Rtl>false</IsLanguage1Rtl>
  <Language1LineHeight>0</Language1LineHeight>
  ...
```

**Pull request merged**
