### PR TITLE
[5.0] BL-10329 Rename Comic to Overlay Tool

### PR DESCRIPTION
**Pull request by gmartin7**
* changes 'comic' folder to 'overlay' and moves all files
* renames several files

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687)

### CODE REVIEW

**Review by JohnThomson — COMMENTED** [review]
> Reviewed 10 of 12 files at r1, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687)* status: all files reviewed, 9 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug, line 26 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687#-MiNOSv78RYaG_JRHiw7:-MiNOSv78RYaG_JRHiw8:b-t986nl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a7c1989a646980452d24019db603022bf9bbfc7/src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug#L26)):*
> ```Pug
> 				.checkbox-label(data-i18n='EditTab.Toolbox.MusicTool') Music Tool
> 			.checkbox-and-label
> 				.checkbox.clear#comicCheck(data-tool='overlayTool', onclick='FrameExports.showOrHideTool_click(this);')
> ```

I think this wants a comment..."not changed to overlay because the control name occurs in meta.json and the modified name would not be recognized by older Bloom's"?
___
*[src/BloomExe/Book/Book.cs, line 2098 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687#-MiNOkU1EZ7sq0XE4tb6:-MiNOkU1EZ7sq0XE4tb7:bos3drx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a7c1989a646980452d24019db603022bf9bbfc7/src/BloomExe/Book/Book.cs#L2098)):*
> ```Smalltalk
> 		{
> 			var result = AllLanguages(includeLangsOccurringOnlyInXmatter);
> 			// For comical books, we only publish a single language. It's not currently feasible to
> ```

Books with overlays?
___
*[src/BloomExe/Book/Book.cs, line 3845 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687#-MiNPNuz3IwaBtTrSdgm:-MiNPNuz3IwaBtTrSdgn:blkl6za) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a7c1989a646980452d24019db603022bf9bbfc7/src/BloomExe/Book/Book.cs#L3845)):*
> ```Smalltalk
> 
> 		// Although the Toolbox tool is renamed to Overlay, we aren't currently changing the Feature names.
> 		public bool HasComicPages => HtmlDom.HasComicFeature(OurHtmlDom.Body);
> ```

This property could be renamed, I think...it happens to be implemented by checking the comic feature, but it won't break anything if this property uses the new name? Then you probably don't need the comment.
___
*[src/BloomExe/Book/BookInfo.cs, line 1264 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687#-MiNPj7Q6iYq98FE6mMG:-MiNPj7Q6iYq98FE6mMH:b91iknb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a7c1989a646980452d24019db603022bf9bbfc7/src/BloomExe/Book/BookInfo.cs#L1264)):*
> ```Smalltalk
> 		[JsonIgnore]
> 		public bool Feature_Quiz { get; set; }
> 		// Feature code is unchanged despite the toolbox tool rename to Overlay Tool.
> ```

Feature NAME is unchanged despite the toolbox tool rename to Overlay Tool, because they are stored in the parse database and used from there by Bloom Library, and because older versions of Bloom would not recognize a feature 'overlay'.
___
*[src/BloomExe/Book/HtmlDom.cs, line 2203 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687#-MiNQOEd-a9PMat2bPbO:-MiNQOEd-a9PMat2bPbP:b-mb3riu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a7c1989a646980452d24019db603022bf9bbfc7/src/BloomExe/Book/HtmlDom.cs#L2203)):*
> ```Smalltalk
> 
> 		/// <summary>
> 		/// The Comic Tool is renamed Overlay, but we retain the old Feature name for backward compatibility.
> ```

...compatibility with older versions of Bloom, the Parse database, and Bloom Library.
___
*[src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, line 116 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687#-MiNQZuS329XUKDi7sWh:-MiNQZuS329XUKDi7sWi:bliiue5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a7c1989a646980452d24019db603022bf9bbfc7/src/BloomExe/Publish/Android/BloomReaderFileMaker.cs#L116)):*
> ```Smalltalk
> 			{
> 				// This indicates that we are harvesting a book with comic speech bubbles or other overlays (Overlay Tool).
> 				// For comical books, we only publish a single language. It's not currently feasible to
> ```

books with overlays?
___
*[src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx, line 446 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687#-MiNOAhK6oh1l28CwSVG:-MiNOAhK6oh1l28CwSVH:bkeijwa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a7c1989a646980452d24019db603022bf9bbfc7/src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx#L446)):*
> ```XML
>             >
>                 <Div
>                     l10nKey="EditTab.Toolbox.ComicTool.DragInstructions"
> ```

should this have been updated?
___
*[src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx, line 462 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687#-MiNOG0702Zd7vqPSs3f:-MiNOG0702Zd7vqPSs3g:b-oqjph4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a7c1989a646980452d24019db603022bf9bbfc7/src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx#L462)):*
> ```XML
>                     <Span
>                         id="shapeChooserTextBlock"
>                         l10nKey="EditTab.Toolbox.ComicTool.TextBlock"
> ```

this too?
___
*[src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx, line 474 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687#-MiNOH_s6Isj4eqcCO0Q:-MiNOH_s6Isj4eqcCO0R:b-yjg231) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a7c1989a646980452d24019db603022bf9bbfc7/src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx#L474)):*
> ```XML
>                     <Span
>                         id="shapeChooserCaption"
>                         l10nKey="EditTab.Toolbox.ComicTool.Options.Style.Caption"
> ```

and this?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687)* status: 13 of 21 files reviewed, 9 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug, line 26 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687#-MiNOSv78RYaG_JRHiw7:-MiNiF5XEwPvfAcOkqkM:b-v5qyl7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a7c1989a646980452d24019db603022bf9bbfc7/src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug#L26)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think this wants a comment..."not changed to overlay because the control name occurs in meta.json and the modified name would not be recognized by older Bloom's"?
</blockquote></details>

Changed. I don't think this html `id` is stored anywhere. The `data-tool` attribute (which I already changed) is what showOrHideTool_click() references.
___
*[src/BloomExe/Book/Book.cs, line 2098 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687#-MiNOkU1EZ7sq0XE4tb6:-MiNjP-38L62EbDNI--7:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a7c1989a646980452d24019db603022bf9bbfc7/src/BloomExe/Book/Book.cs#L2098)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Books with overlays?
</blockquote></details>

Done.
___
*[src/BloomExe/Book/Book.cs, line 3845 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687#-MiNPNuz3IwaBtTrSdgm:-MiNjosKC8ZO8g4dBdnW:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a7c1989a646980452d24019db603022bf9bbfc7/src/BloomExe/Book/Book.cs#L3845)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This property could be renamed, I think...it happens to be implemented by checking the comic feature, but it won't break anything if this property uses the new name? Then you probably don't need the comment.
</blockquote></details>

Done.
___
*[src/BloomExe/Book/BookInfo.cs, line 1264 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687#-MiNPj7Q6iYq98FE6mMG:-MiNkDVH0fYZ3F_2ZVak:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a7c1989a646980452d24019db603022bf9bbfc7/src/BloomExe/Book/BookInfo.cs#L1264)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Feature NAME is unchanged despite the toolbox tool rename to Overlay Tool, because they are stored in the parse database and used from there by Bloom Library, and because older versions of Bloom would not recognize a feature 'overlay'.
</blockquote></details>

Done.
___
*[src/BloomExe/Book/HtmlDom.cs, line 2203 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687#-MiNQOEd-a9PMat2bPbO:-MiNm8r6DME2rBTZN5z9:b-4sfk7i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a7c1989a646980452d24019db603022bf9bbfc7/src/BloomExe/Book/HtmlDom.cs#L2203)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

...compatibility with older versions of Bloom, the Parse database, and Bloom Library.
</blockquote></details>

I was actually able to rename this property too, but I added a comment.
___
*[src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, line 116 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687#-MiNQZuS329XUKDi7sWh:-MiNmJrHEMr7FhenyI0m:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a7c1989a646980452d24019db603022bf9bbfc7/src/BloomExe/Publish/Android/BloomReaderFileMaker.cs#L116)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

books with overlays?
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx, line 446 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687#-MiNOAhK6oh1l28CwSVG:-MiNghkF2IBrQ1dvezdZ:b2cxxur) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a7c1989a646980452d24019db603022bf9bbfc7/src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx#L446)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

should this have been updated?
</blockquote></details>

Intentional. See new comment above.
___
*[src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx, line 462 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687#-MiNOG0702Zd7vqPSs3f:-MiNgqv80-eD0Y9VpZbZ:b6wbt0c) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a7c1989a646980452d24019db603022bf9bbfc7/src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx#L462)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

this too?
</blockquote></details>

Intentional.
___
*[src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx, line 474 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687#-MiNOH_s6Isj4eqcCO0Q:-MiNgtsD-IrfloEKzzpi:b6wbt0c) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a7c1989a646980452d24019db603022bf9bbfc7/src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx#L474)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

and this?
</blockquote></details>

Intentional.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687)* status: 13 of 21 files reviewed, 10 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Book/Book.cs, line 3988 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687#-MiNq3vv10_n4H9tMxfa:-MiNq3vw1iFrOvAmbupQ:blm9evf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/66091aec487f82a5807536904c5ca75156cd5c7b/src/BloomExe/Book/Book.cs#L3988)):*
> ```Smalltalk
> 		/// These are now created with the Overlay Tool, but the feature retains the old name.
> 		/// </summary>
> 		private void UpdateComicFeature()
> ```

I thought about changing the name of this method too... but "Comic" is still the name of the feature, so I decided to leave it.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomExe/Book/Book.cs, line 3988 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4687#-MiNq3vv10_n4H9tMxfa:-MiRTaUnBiXOME6HypeY:b-j2fohf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/66091aec487f82a5807536904c5ca75156cd5c7b/src/BloomExe/Book/Book.cs#L3988)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I thought about changing the name of this method too... but "Comic" is still the name of the feature, so I decided to leave it.
</blockquote></details>

I think you're right.

**Pull request merged**
