### PR TITLE
Support video and widgets in spreadsheet (BL-11542)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 17 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700)* status: 17 of 19 files reviewed, 7 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Extensions.cs` line 183 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700#-NR4KxKk5vjwsDvpv4PE:-NR4KxKk5vjwsDvpv4PF:b-prmx44) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bc532a75f8e2db3cb194ab7de0a8dca27d205a67/src/BloomExe/Extensions.cs#L183)):*
> ```Smalltalk
> 		/// into items that need it.
> 		/// </summary>
> 		public static IEnumerable<T[]> MapUnevenLists<T>(List<T>[] inputs)
> ```

Is it worth testing this explicitly?
I'm ok with the answer being "no" if it is sufficiently tested through the SS tests and we don't have a reasonable expectation of it being reused.
___
*[`src/BloomExe/Book/HtmlDom.cs` line 1321 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700#-NR4OUqp3J_4vEMabNIk:-NR4OUqp3J_4vEMabNIl:b-fm43ym) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bc532a75f8e2db3cb194ab7de0a8dca27d205a67/src/BloomExe/Book/HtmlDom.cs#L1321)):*
> ```Smalltalk
> 		}
> 
> 		internal static string GetUserModifiableStylesUsedOnPage(XmlElement head, XmlElement contentToSearch)
> ```

This is a good cleanup.
Looking at the existing code, it appears we can stop modifying the dom here because the only caller (in Book) has a subsequent call which does basically the same thing. Is that accurate?
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 1100 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700#-NR4Ur0n14AF5B3klvOG:-NR4Ur0n14AF5B3klvOH:b-xmt6c1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bc532a75f8e2db3cb194ab7de0a8dca27d205a67/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L1100)):*
> ```Smalltalk
> 		private Dictionary<BlockTypes, string> _pagesToInsert;
> 
> 		Dictionary<BlockTypes, string> PageToInsert()
> ```

A bigger picture question...

What happens when user creates Basic Text and Picture page, uses origami to add another image, then exports?
Do we still call it Basic Text and Picture even though we know the content slots don't fit?
If we do, that seems inherently wrong.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 1105 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700#-NR4UlTi-XbIkFNLxVZH:-NR4UlTi-XbIkFNLxVZI:bvmtuph) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bc532a75f8e2db3cb194ab7de0a8dca27d205a67/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L1105)):*
> ```Smalltalk
> 			{
> 				_pagesToInsert = new Dictionary<BlockTypes, string>();
> 				_pagesToInsert[BlockTypes.Image] = "adcd48df-e9ab-4a07-afd4-6a24d0398385"; // just an image
> ```

Seems like we would benefit to make these guids constants somewhere.
___
*[`src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs` line 328 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700#-NR4Tbfp2j0jDxQDigco:-NR4Tbfp2j0jDxQDigcp:bktrkf4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bc532a75f8e2db3cb194ab7de0a8dca27d205a67/src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs#L328)):*
> ```Smalltalk
> 		{
> 			return String.Format(
> 				@"<div class=""bloom-videoContainer bloom-noVideoSelected bloom-leadingElement bloom-selected"" id=""vc{0}"">
> ```

I'm sure it wouldn't affect the test either way, but we don't ever have `bloom-noVideoSelected` with a `source`, do we?



_Code quote:_
```Smalltalk
bloom-noVideoSelected
```
___
*[`src/BloomTests/Spreadsheet/SpreadsheetPageTypeImportTests.cs` line 23 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700#-NR4R3owBUTYAZ5bk2AW:-NR4R3owBUTYAZ5bk2AX:b-ms42lq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bc532a75f8e2db3cb194ab7de0a8dca27d205a67/src/BloomTests/Spreadsheet/SpreadsheetPageTypeImportTests.cs#L23)):*
> ```Smalltalk
> 	/// This also covers (along with SpreadsheetImageAndTextImportTests) various cases of how to
> 	/// import when page type is specified.
> 	/// The following is a list I made at the start of interesting cases. I didn't quite end up implementing all of them,
> ```

Is it worth being explicit about which ones you covered? Or at least the ones you didn't?
Otherwise, I'm not sure I see a lot of value in keeping the comment.



_Code quote:_
```Smalltalk
	/// The following is a list I made at the start of interesting cases. I didn't quite end up implementing all of them,
	/// but I thought it was worth keeping. The ones I did seem to capture all the important paths through the code.
```
___
*[`src/BloomTests/Spreadsheet/SpreadsheetPageTypeImportTests.cs` line 231 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700#-NR4SXEY004gGcBQZUuC:-NR4SXEY004gGcBQZUuD:bkjqpge) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bc532a75f8e2db3cb194ab7de0a8dca27d205a67/src/BloomTests/Spreadsheet/SpreadsheetPageTypeImportTests.cs#L231)):*
> ```Smalltalk
> 			_progressSpy = new ProgressSpy();
> 
> 			// Not sure we need this. Todo: try removing it when otherwise done.
> ```

Still want to do this?



_Code quote:_
```Smalltalk
Todo: try removing it when otherwise done.
```

**Review by andrew-polk — COMMENTED** [review]
I've made a pass through everything but the two biggies... SpreadsheetExporter and SpreadsheetImporter. Maybe best to do those interactive?
Let me know if you want to do it before or after looking at the comments I've already added.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700#-:-NR4VQiKDIdFX2jscsRH:bvxwuvi)* status: 17 of 19 files reviewed, 7 unresolved discussions (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700)* status: 17 of 19 files reviewed, 7 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Extensions.cs` line 183 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700#-NR4KxKk5vjwsDvpv4PE:-NRh_9WN4QSbvfXPK77S:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bc532a75f8e2db3cb194ab7de0a8dca27d205a67/src/BloomExe/Extensions.cs#L183)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is it worth testing this explicitly?
I'm ok with the answer being "no" if it is sufficiently tested through the SS tests and we don't have a reasonable expectation of it being reused.
</blockquote></details>

Done.
___
*[`src/BloomExe/Book/HtmlDom.cs` line 1321 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700#-NR4OUqp3J_4vEMabNIk:-NRhaHeK3OKyN0fbKZjL:bb831pg) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bc532a75f8e2db3cb194ab7de0a8dca27d205a67/src/BloomExe/Book/HtmlDom.cs#L1321)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This is a good cleanup.
Looking at the existing code, it appears we can stop modifying the dom here because the only caller (in Book) has a subsequent call which does basically the same thing. Is that accurate?
</blockquote></details>

It's been a long time. I don't recall why I removed the DOM updating, except for the obvious consideration that it's obnoxious for a Get method to have side effects. But indeed both callers do their own saving of the new stylesheet (after merging with what this returns).
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 1100 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700#-NR4Ur0n14AF5B3klvOG:-NRhawSt3Loh45OFFQmk:bk7obgt) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bc532a75f8e2db3cb194ab7de0a8dca27d205a67/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L1100)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

A bigger picture question...

What happens when user creates Basic Text and Picture page, uses origami to add another image, then exports?
Do we still call it Basic Text and Picture even though we know the content slots don't fit?
If we do, that seems inherently wrong.
</blockquote></details>

The only time the name of the page matters is if we are importing into a document and the spreadsheet says it needs a page with a given name (or of course if the user is making a new template, but then it's up to them to make an appropriate name). The situation you're describing will be OK when re-importing into the same document because the spreadsheet rows that expect a 3-slot Basic Text and Picture will align with the page that has exactly that.
But it might make sense to generate a modified name...I'm just not sure what it should be. I suppose it would be something to just change it to "Basic Text & Picture modified" or we could actually indicate the number of slots..."Basic Text & Picture (1T,2P,0V,0W)" so you'd only get a match for something modified to have the expected number of each slot. Something to discuss with JohnH?
If we want to, feels like a plausible distinct card ("Update page name when changing slots") rather than making this PR even bigger.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 1105 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700#-NR4UlTi-XbIkFNLxVZH:-NRhzpwB4p0wMDzO8Cqu:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bc532a75f8e2db3cb194ab7de0a8dca27d205a67/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L1105)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems like we would benefit to make these guids constants somewhere.
</blockquote></details>

Done.
___
*[`src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs` line 328 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700#-NR4Tbfp2j0jDxQDigco:-NRi-3pk6ebVWHYaaRGi:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bc532a75f8e2db3cb194ab7de0a8dca27d205a67/src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs#L328)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm sure it wouldn't affect the test either way, but we don't ever have `bloom-noVideoSelected` with a `source`, do we?
</blockquote></details>

Done.
___
*[`src/BloomTests/Spreadsheet/SpreadsheetPageTypeImportTests.cs` line 23 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700#-NR4R3owBUTYAZ5bk2AW:-NRi-K7F78PsEzYoPcl5:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bc532a75f8e2db3cb194ab7de0a8dca27d205a67/src/BloomTests/Spreadsheet/SpreadsheetPageTypeImportTests.cs#L23)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is it worth being explicit about which ones you covered? Or at least the ones you didn't?
Otherwise, I'm not sure I see a lot of value in keeping the comment.
</blockquote></details>

Done.
___
*[`src/BloomTests/Spreadsheet/SpreadsheetPageTypeImportTests.cs` line 231 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700#-NR4SXEY004gGcBQZUuC:-NRi45Qb8HmB6YbdDmkQ:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bc532a75f8e2db3cb194ab7de0a8dca27d205a67/src/BloomTests/Spreadsheet/SpreadsheetPageTypeImportTests.cs#L231)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Still want to do this?
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 19 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 1100 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700#-NR4Ur0n14AF5B3klvOG:-NRiOZh5Do9DDB6TyrTj:b-71v3sc) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bc532a75f8e2db3cb194ab7de0a8dca27d205a67/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L1100)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

The only time the name of the page matters is if we are importing into a document and the spreadsheet says it needs a page with a given name (or of course if the user is making a new template, but then it's up to them to make an appropriate name). The situation you're describing will be OK when re-importing into the same document because the spreadsheet rows that expect a 3-slot Basic Text and Picture will align with the page that has exactly that.
But it might make sense to generate a modified name...I'm just not sure what it should be. I suppose it would be something to just change it to "Basic Text & Picture modified" or we could actually indicate the number of slots..."Basic Text & Picture (1T,2P,0V,0W)" so you'd only get a match for something modified to have the expected number of each slot. Something to discuss with JohnH?
If we want to, feels like a plausible distinct card ("Update page name when changing slots") rather than making this PR even bigger.
</blockquote></details>

Ok, we agreed for now to just point out the scenario to Colin so he can make sure it does something reasonable.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Spreadsheet/SpreadsheetExporter.cs` line 210 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700#-NRjI3LB2uAoIs34hNRt:-NRjI3LB2uAoIs34hNRu:b-aswb2k) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8d160a6b01d2af81723a8cd71127d8d33c2c842d/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L210)):*
> ```Smalltalk
> 				{
> 					_progress.MessageWithParams("Spreadsheet.TroubleCopyingFolder", "",
> 						"Bloom had trouble copying the folder {0} to the activities folder: " +
> ```

The space at the end of the string should not be part of the i18n. Sorry I didn't catch this before.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetExporter.cs` line 236 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700#-NRjI9K75oQtNZIB7Qpi:-NRjI9K75oQtNZIB7Qpj:b-aswb2k) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8d160a6b01d2af81723a8cd71127d8d33c2c842d/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L236)):*
> ```Smalltalk
> 				{
> 					_progress.MessageWithParams("SpreadsheetTroubleCopying", "",
> 						"Bloom had trouble copying the file {0} to the video folder: " +
> ```

The space at the end of the string should not be part of the i18n. Sorry I didn't catch this before.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 512 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700#-NRjHIT4C1seWbwtYZNo:-NRjHIT4C1seWbwtYZNp:bobs4ev) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8d160a6b01d2af81723a8cd71127d8d33c2c842d/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L512)):*
> ```Smalltalk
> 		/// and enough cycles will cause the name to overflow. So, if the name looks like
> 		/// an output (ends in hyphen-number), just increment the number.</remarks>>
> 		public static string GetNextFileName(string input)
> ```

I don't like introducing a third one of these.
(We already have ImageUtils.GetUnusedFilename() and BookStorage.GetUniqueFileName().)
Maybe ImageUtils.GetUnusedFilename() can be reused (maybe extracted first)?
If not, should we at least move this to a common place and document why it needs to be different than the other two?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700)* status: 12 of 22 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Spreadsheet/SpreadsheetExporter.cs` line 210 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700#-NRjI3LB2uAoIs34hNRt:-NRjKg_N10oYRegwkJPb:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8d160a6b01d2af81723a8cd71127d8d33c2c842d/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L210)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The space at the end of the string should not be part of the i18n. Sorry I didn't catch this before.
</blockquote></details>

Done.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetExporter.cs` line 236 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700#-NRjI9K75oQtNZIB7Qpi:-NRjKguv6GxcbKhyX3MH:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8d160a6b01d2af81723a8cd71127d8d33c2c842d/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L236)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The space at the end of the string should not be part of the i18n. Sorry I didn't catch this before.
</blockquote></details>

Done.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 512 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700#-NRjHIT4C1seWbwtYZNo:-NRjOD9J3hTDxza0uBSi:b-z951su) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8d160a6b01d2af81723a8cd71127d8d33c2c842d/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L512)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't like introducing a third one of these.
(We already have ImageUtils.GetUnusedFilename() and BookStorage.GetUniqueFileName().)
Maybe ImageUtils.GetUnusedFilename() can be reused (maybe extracted first)?
If not, should we at least move this to a common place and document why it needs to be different than the other two?
</blockquote></details>

I removed it and used the ImageUtils one.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5700)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
