### PR TITLE
BL-6055 Save Epub UI settings to meta.json

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2490)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @gmartin7)

---

*[src/BloomBrowserUI/publish/epub/epubPublishUI.tsx, line 68 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2490#-LEqEMp33kha-BM3vKqr:-LEqEMp33kha-BM3vKqs:b-nl71c) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7055214b30d274719e14da6d3aaf4668d5f56918/src/BloomBrowserUI/publish/epub/epubPublishUI.tsx#L68)):*
> ```XML
>         //     WebSocketManager.closeSocket(kWebSocketLifetime);
>         // });
>     }
> ```

In Louisiana we call these freebie improvements *lagniappe* :-)

---

*[src/BloomExe/Book/BookInfo.cs, line 331 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2490#-LEqEjwZ1J7NiFQnhpMG:-LEqEjwZ1J7NiFQnhpMH:bjs2edn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c6b4abe8427271fe3f2a4619a14308d2dbdced1f/src/BloomExe/Book/BookInfo.cs#L331)):*
> ```Smalltalk
> 		}
> 
> 		public string PublishImageDescriptionsInEpub
> ```

these are ok, this is the pattern in this file, but I'm really annoyed by this pattern. If you are annoyed by it too, you could do as I did recently and just reach into bookinfo.metadata._____ and skip this boilerplate.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2490)*

**Comment by gmartin7** [comment]
Much better, I think. One thing I'm curious about: At one point the preview started over automatically when I clicked one of the checkboxes, now I've had to add a updatePreview POST to get it to do that. If anyone can spot what I did that messed that up, I'd be grateful.

---

Review status: 0 of 15 files reviewed, 3 unresolved discussions (waiting on @hatton)

---

*[src/BloomBrowserUI/publish/epub/epubPublishUI.tsx, line 68 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2490#-LEqEMp33kha-BM3vKqr:-LEuy9il8n8rGLGajxLD:b32w0x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7055214b30d274719e14da6d3aaf4668d5f56918/src/BloomBrowserUI/publish/epub/epubPublishUI.tsx#L68)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

In Louisiana we call these freebie improvements *lagniappe* :-)
</blockquote></details>

OK

---

*[src/BloomExe/Book/BookInfo.cs, line 331 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2490#-LEqEjwZ1J7NiFQnhpMG:-LEuyP_RAS1xNOKoCxST:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c6b4abe8427271fe3f2a4619a14308d2dbdced1f/src/BloomExe/Book/BookInfo.cs#L331)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

these are ok, this is the pattern in this file, but I'm really annoyed by this pattern. If you are annoyed by it too, you could do as I did recently and just reach into bookinfo.metadata._____ and skip this boilerplate.
</blockquote></details>

Done.

---

*[src/BloomExe/Publish/Epub/PublishEpubApi.cs, line 301 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2490#-LEqHGuQ1vOkp2w9d2UE:-LEv5q0xCh24XyXQdfuz:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c6b4abe8427271fe3f2a4619a14308d2dbdced1f/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L301)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

please add a comment explaining what's going on here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2490#-:-LEv9Zag8uqNix2JGDq7:b-lhak25)*

**Comment by gmartin7** [comment]
Method of updating the preview isn't quite the same as JH's Accessibility Checker one, but pretty good, I think.

---

Review status: 0 of 20 files reviewed, 3 unresolved discussions (waiting on @hatton)

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2490#-:-LF4DCfB9z10fxX4Wlwq:b-u7uwh2)*

**Comment by gmartin7** [comment]
Review status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @hatton)

---

*[src/BloomExe/Publish/Epub/PublishEpubApi.cs, line 301 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2490#-LEqHGuQ1vOkp2w9d2UE:-LFNdwni1RK0LLqUo2n1:b2w2e2y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c6b4abe8427271fe3f2a4619a14308d2dbdced1f/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L301)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This might actually have been changed in a PR I have out, too. What it is is that the epub maker requires geckofx to render the page, in order to figur out what is actually visible. This requires being on the UI thread. It fails when we debug because Bloom itself is not front-most.
</blockquote></details>

rebased on JH's change to use his

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2490)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 4 files at r1, 7 of 15 files at r2, 7 of 11 files at r3, 8 of 9 files at r4.
Review status: all files reviewed, 3 unresolved discussions (waiting on @hatton and @gmartin7)

---

*[src/BloomExe/Book/Book.cs, line 62 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/2490#-LFO01Kn6g5Ugnx3iS5Y:-LFO01Ko1mi4k_DA6sui:bj81d62) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98d5da8b20f02ba4a41f84cbb673e19cab281c89/src/BloomExe/Book/Book.cs#L62)):*
> ```Smalltalk
> 		public Book(BookInfo info = null)
> 		{
> 			BookInfo = info; // only for testing!
> ```

Worth adding a check (at least a debug assert?) to ensure we are running unit tests when calling this constructor?
Pretty sure we have a way to check if we are running unit tests.

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 102 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/2490#-LFO1ujHEbCVRZKYX5DL:-LFO1ujI6p4rCTkSmreE:b-7vz74f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98d5da8b20f02ba4a41f84cbb673e19cab281c89/src/BloomExe/web/EnhancedImageServer.cs#L102)):*
> ```Smalltalk
> 		/// Handle enum reads/writes
> 		/// </summary>
> 		public void RegisterEnumEndpointHandler<T>(string pattern, Func<ApiRequest, T> readAction, Action<ApiRequest, T> writeAction,
> ```

Does this belong in EnhancedImageServer?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2490)*

**Comment by gmartin7** [comment]
Review status: 17 of 19 files reviewed, 3 unresolved discussions (waiting on @andrew-polk, @hatton, and @gmartin7)

---

*[src/BloomExe/Book/Book.cs, line 62 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/2490#-LFO01Kn6g5Ugnx3iS5Y:-LFO9N_oD8b6ecnqZoiW:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98d5da8b20f02ba4a41f84cbb673e19cab281c89/src/BloomExe/Book/Book.cs#L62)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Worth adding a check (at least a debug assert?) to ensure we are running unit tests when calling this constructor?
Pretty sure we have a way to check if we are running unit tests.
</blockquote></details>

Done.

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 102 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/2490#-LFO1ujHEbCVRZKYX5DL:-LFO6-Bn2sO0i8qEPsiA:b-bmfjb0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98d5da8b20f02ba4a41f84cbb673e19cab281c89/src/BloomExe/web/EnhancedImageServer.cs#L102)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Does this belong in EnhancedImageServer?
</blockquote></details>

I believe so. This is where RegisterEndpointHandler and RegisterBooleanEndpointHandler already live.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2490)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 102 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/2490#-LFO1ujHEbCVRZKYX5DL:-LFOAGHl7UYQ9jp14im-:bby5tvb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98d5da8b20f02ba4a41f84cbb673e19cab281c89/src/BloomExe/web/EnhancedImageServer.cs#L102)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I believe so. This is where RegisterEndpointHandler and RegisterBooleanEndpointHandler already live.
</blockquote></details>

Still feels wrong to me. But not for this PR, I guess.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2490#-:-LFOAKhe0Y-hhZc48A76:bnfp4nl)*

**Pull request merged**
