### PR TITLE
BL-9961 Enable multi-paragraph paste from Notepad

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5139)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5139)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts` line 153 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5139#-N1eyX-r7l16q7PV5xB_:-N1eyX-r7l16q7PV5xBa:b-j4xpsq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0bba18c4d6dc5cb36dc8ced0f501c1050dde4a7e/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L153)):*
> ```XML
>             }
> 
>             let paras = event.data.dataValue.match(/<p>/g);
> ```

Probably due to some intermediate state you had while working on this, but you've changed const to let unnecessarily.



_Code quote:_
```XML
let
```
___
*[`src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts` line 175 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5139#-N1eyBgU76_QyqNDUyCW:-N1eyBgV02X9SqXfEHKY:b-h5xj8y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0bba18c4d6dc5cb36dc8ced0f501c1050dde4a7e/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L175)):*
> ```XML
>                     );
>                 // Reset dataValue
>                 event.data.dataValue = reconstitutedTextWithParas;
> ```

If we do this, won't we lose any changes made to `event.data.dataValue` above (such as `convertStandardFormatVerseMarkersToSuperscript`, etc.)?

Can/should you do the replacement before the rest of this handler runs?
___
*[`src/BloomBrowserUI/bookEdit/js/bloomEditing.ts` line 317 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5139#-N1eylsx3AoXBdu5YacI:-N1eylsx3AoXBdu5YacJ:b-71kmno) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/96b0d409abe8699847bb057bb7f8e676e9dd1990/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L317)):*
> ```XML
>         .replace(/&#39;/g, "'")
>         .replace(/&#169;/g, "©");
> }
> ```

(for next time)
It is generally helpful to add a comment in reviewable when making a change for which the reason is not obvious like this.
(I verified this is not used myself by looking at code.)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5139)* status: all files reviewed, 4 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts` line 211 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5139#-N1j-jrk9V4vTHGJawYK:-N1j-jrk9V4vTHGJawYL:bb4y6pg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78a140fecc41fe472f256a31de42b5347f8da017/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L211)):*
> ```XML
>     }
> 
>     // Return value will reset 'event.data.dataValue'
> ```

That is only true for the one place this is currently called, but there could be other callers later.

I think it would be better to write a comment explaining what this method does and returns.
i.e. if no paras but does have line breaks, returns blah blah...



_Code quote:_
```XML
// Return value will reset 'event.data.dataValue'
```
___
*[`src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts` line 212 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5139#-N1j-a_dCoZq4uiL4CMH:-N1j-a_dCoZq4uiL4CMI:bb7phvt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78a140fecc41fe472f256a31de42b5347f8da017/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L212)):*
> ```XML
> 
>     // Return value will reset 'event.data.dataValue'
>     static reconstitueParagraphsOnPlainTextPaste(eventData: any): any {
> ```

typo



_Code quote:_
```XML
reconstitue
```
___
*[`src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts` line 215 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5139#-N1j-9rSBEnhxFNC5zfF:-N1j-9rSBEnhxFNC5zfG:b4gjnaz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78a140fecc41fe472f256a31de42b5347f8da017/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L215)):*
> ```XML
>         if (!eventData.dataValue.match(/<p>/g)) {
>             // BL-9961 If we're inserting plain text from Notepad, we will arrive here because
>             // 'dataValue' doesn't have paragraphs, but we actually want them.
> ```

I think this comment is now incorrect (or at least misleading?).
We only want paragraphs if there are line breaks, right?



_Code quote:_
```XML
            // BL-9961 If we're inserting plain text from Notepad, we will arrive here because
            // 'dataValue' doesn't have paragraphs, but we actually want them.
```
___
*[`src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts` line 216 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5139#-N1j-JM4Bfg26IZcKNKc:-N1j-JM4Bfg26IZcKNKd:b32838a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78a140fecc41fe472f256a31de42b5347f8da017/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L216)):*
> ```XML
>             // BL-9961 If we're inserting plain text from Notepad, we will arrive here because
>             // 'dataValue' doesn't have paragraphs, but we actually want them.
>             // Finding where the original string with its paragraphs was passed inside the
> ```

Can't you just pass in event.data.dataValue to this method now and use that instead?



_Code quote:_
```XML
            // Finding where the original string with its paragraphs was passed inside the
            // dataTransfer object was a bit tricky.
            const textWithReturns: string = eventData.dataTransfer._.data.Text;
```

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5139)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts` line 211 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5139#-N1j-jrk9V4vTHGJawYK:-N1jd7HPCgzmhQpSaRLn:b-fsijxj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78a140fecc41fe472f256a31de42b5347f8da017/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L211)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

That is only true for the one place this is currently called, but there could be other callers later.

I think it would be better to write a comment explaining what this method does and returns.
i.e. if no paras but does have line breaks, returns blah blah...
</blockquote></details>

Comment updated.
___
*[`src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts` line 215 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5139#-N1j-9rSBEnhxFNC5zfF:-N1jdkep45IcUXS409IL:baw1xrg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78a140fecc41fe472f256a31de42b5347f8da017/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L215)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this comment is now incorrect (or at least misleading?).
We only want paragraphs if there are line breaks, right?
</blockquote></details>

Updated all the comments. Should be clearer now.
___
*[`src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts` line 216 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5139#-N1j-JM4Bfg26IZcKNKc:-N1j6LlAATtgHpowL7JL:b-txy56c) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78a140fecc41fe472f256a31de42b5347f8da017/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L216)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Can't you just pass in event.data.dataValue to this method now and use that instead?
</blockquote></details>

That's kinda the whole point! The `dataValue` at this point has NO line breaks. Just all the lines squashed together in one line! e.g.: `One.Two.Three`, where the `dataTransfer._.data.Text` has the original `One.\nTwo.\nThree.\n`.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5139)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts` line 216 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5139#-N1j-JM4Bfg26IZcKNKc:-N1jhJnQ9O7STB0pRr2Q:b-nctsom) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78a140fecc41fe472f256a31de42b5347f8da017/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L216)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

That's kinda the whole point! The `dataValue` at this point has NO line breaks. Just all the lines squashed together in one line! e.g.: `One.Two.Three`, where the `dataTransfer._.data.Text` has the original `One.\nTwo.\nThree.\n`.
</blockquote></details>

Ah, I see. I made the mistake of assuming that it was there in `event.data.dataValue` but had been altered by the time we got to this point in the code originally.

**Pull request merged**
