### PR TITLE
BL-6054 try harder to find where global node_modules might live

### PR DESCRIPTION
**Pull request by hatton**
And also handle ace-by-daisy failures robustly.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2489)

### CODE REVIEW

**Comment by JohnThomson** [comment]
:lgtm: with one question and a minor suggestion.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @hatton)

---

*[src/BloomExe/web/controllers/AccessibilityCheckApi.cs, line 114 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2489#-LEtt_5H08cQw3yRMw90:-LEtt_5H08cQw3yRMw91:bfja53e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5ba580a60fc8894357cc54f6958ab1e1c39da5c2/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L114)):*
> ```Smalltalk
> 				var reportDirectory = Path.Combine(reportRootDirectory, "report" + i);
> 				// This call is ok if the directory does not exist at all.
> 				SIL.IO.RobustIO.DeleteDirectoryAndContents(reportDirectory);
> ```

If each iteration takes over 2s to fail, 20 tries is going to feel like a freeze. Well, maybe not, we're doing a long-running process, if 60s is a typical timeout for the main task. By the time THAT fails 20 times, possibly taking several seconds each try, there could be a really long delay before the user sees the final error message result. Any way we can give some indication of what it going on (besides the error message on first failure, which is good)?

---

*[src/BloomExe/web/controllers/AccessibilityCheckApi.cs, line 195 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2489#-LEtvmYO5MAH5TJuIJnu:-LEtvmYPCqX-t7raDDLv:b-q9v7qp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5ba580a60fc8894357cc54f6958ab1e1c39da5c2/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L195)):*
> ```Smalltalk
> 			{
> 				request.ReplyWithHtml(
> 					$"Could could not find global node_modules directory at {nodeModulesDirectory}. {instructionsHtml}");
> ```

A newline here would be consistent with similar messages.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2489#-:-LEtw-Br4bvXtq6dyTiU:b-bgg5z2)*

**Comment by hatton** [comment]
Review status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @JohnThomson and @hatton)

---

*[src/BloomExe/web/controllers/AccessibilityCheckApi.cs, line 114 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2489#-LEtt_5H08cQw3yRMw90:-LEzC-og6YQRyHqe5t2w:b-yif2uv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5ba580a60fc8894357cc54f6958ab1e1c39da5c2/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L114)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

If each iteration takes over 2s to fail, 20 tries is going to feel like a freeze. Well, maybe not, we're doing a long-running process, if 60s is a typical timeout for the main task. By the time THAT fails 20 times, possibly taking several seconds each try, there could be a really long delay before the user sees the final error message result. Any way we can give some indication of what it going on (besides the error message on first failure, which is good)?
</blockquote></details>

Of course you're right. I've re-written it to just use guids for names, but still within a named folder, so that we can automatically cleanup whatever is willing to be cleaned up with each run.

---

*[src/BloomExe/web/controllers/AccessibilityCheckApi.cs, line 195 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2489#-LEtvmYO5MAH5TJuIJnu:-LEz9ROg0jQu_B8FJd-S:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5ba580a60fc8894357cc54f6958ab1e1c39da5c2/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L195)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

A newline here would be consistent with similar messages.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2489)*

**Comment by gmartin7** [comment]
:lgtm: with one minor question. JT should probably still have a look

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

---

*[src/BloomExe/web/controllers/AccessibilityCheckApi.cs, line 195 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2489#-LEtvmYO5MAH5TJuIJnu:-LEzNvyr30jhe1QzZW4l:b-yl25sl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5ba580a60fc8894357cc54f6958ab1e1c39da5c2/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L195)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What happened to using {Environment.NewLine}? Any particular reason you chose a br tag instead here?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2489#-:-LEzOUdgCNECqg56wZbV:b6hzbcw)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

---

*[src/BloomExe/web/controllers/AccessibilityCheckApi.cs, line 114 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2489#-LEtt_5H08cQw3yRMw90:-LEzTojiAZZ-JbeW0XGK:b-wqmpll) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5ba580a60fc8894357cc54f6958ab1e1c39da5c2/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L114)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Of course you're right. I've re-written it to just use guids for names, but still within a named folder, so that we can automatically cleanup whatever is willing to be cleaned up with each run.
</blockquote></details>

So this wipes out the 2s delays from trying to delete directories. But we're still trying 20 times. I have no idea how long one failed try might be, but a 60s timeout suggests even one try might take a while. I'm not seeing the calling context but is there something...even a wait cursor...to indicate the system is busy working on this? Or is it not busy...the user can do other things while this churns along?
Also: I don't actually see any code to "cleanup whatever is willing to be cleaned up"

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2489)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

---

*[src/BloomExe/web/controllers/AccessibilityCheckApi.cs, line 195 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2489#-LEtvmYO5MAH5TJuIJnu:-LEzVwKAAUCoioKXa4Ym:b-pyvapf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5ba580a60fc8894357cc54f6958ab1e1c39da5c2/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L195)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

What happened to using {Environment.NewLine}? Any particular reason you chose a br tag instead here?
</blockquote></details>

These messages are html. I'm guessing the original newline code wasn't doing anything (since html displays all whitespace as a single space).

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2489)*

**Comment by hatton** [comment]
Review status: all files reviewed, 4 unresolved discussions (waiting on @hatton and @JohnThomson)

---

*[src/BloomExe/web/controllers/AccessibilityCheckApi.cs, line 114 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2489#-LEtt_5H08cQw3yRMw90:-LEzcxHu03QPPdh3rLor:b-j7cac8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5ba580a60fc8894357cc54f6958ab1e1c39da5c2/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L114)):*
I think you might have been commenting on the old version?

It's true that we are giving Ace lots of times to fail, but there are no more directory deleting delays.

> I don't actually see any code to "cleanup whatever is willing to be cleaned up"

see 

    // This call is ok if the directory does not exist at all.
    Directory.CreateDirectory(reportRootDirectory);

---

*[src/BloomExe/web/controllers/AccessibilityCheckApi.cs, line 101 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2489#-LEzd96S2NVoxVma5C1B:-LEzd96S2NVoxVma5C1C:b-wtg3pm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0ff90815b79c5721274cee86c6cd36393ebf34b9/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L101)):*
> ```
> irectory.CreateDirectory(reportRootDirectory);
> ```

---

*[src/BloomExe/web/controllers/AccessibilityCheckApi.cs, line 102 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2489#-LEzd8N2-CWrKiK7opjc:-LEzd8N2-CWrKiK7opjd:b-3rj4lp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0ff90815b79c5721274cee86c6cd36393ebf34b9/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L102)):*
> ```
> l exists
> ```

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2489)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

---

*[src/BloomExe/web/controllers/AccessibilityCheckApi.cs, line 114 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2489#-LEtt_5H08cQw3yRMw90:-LF-ITfv2YRXblC2xQz0:b6altmm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5ba580a60fc8894357cc54f6958ab1e1c39da5c2/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L114)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think you might have been commenting on the old version?

It's true that we are giving Ace lots of times to fail, but there are no more directory deleting delays.

> I don't actually see any code to "cleanup whatever is willing to be cleaned up"

see 

    // This call is ok if the directory does not exist at all.
    Directory.CreateDirectory(reportRootDirectory);
</blockquote></details>

No, just not looking far enough back in the unchanged code. (But I would have understood your comment much faster if you'd referred me to RobustIO.DeleteDirectoryAndContents(reportRootDirectory);

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2489#-:-LF-JC-Z4ShIAx9M2VpF:bnfp4nl)*

**Pull request merged**
