### PR TITLE
BL-11257 Tweak to Publish to Video screen

### PR DESCRIPTION
**Pull request by gmartin7**
* standardize spacing and background color as per other
   Publish pages

- - -
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5474)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5474)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/publish/commonPublish/PublishScreenBaseComponents.tsx` line 48 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5474#-NEgr6G0EXmwlFbpZzqV:-NEgr6G0EXmwlFbpZzqW:b-x4ebpn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fdfd1d1c3c6e32afcb61896f8967449f39288a29/src/BloomBrowserUI/publish/commonPublish/PublishScreenBaseComponents.tsx#L48)):*
> ```XML
>                 padding-left: ${leftPad}px;
>                 padding-top: ${topBottomPad}px;
>                 padding-bottom: ${topBottomPad}px;
> ```

Let's figure out how to do this without the prop.

Should the thing under previews be a new subcomponent which adds the padding but is a child of PublishPanel?

The publish modes with previews will become the minority once PDF and Web use this template.
___
*[`src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx` line 330 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5474#-NEgthzxEwI_ydnY9AYd:-NEgthzxEwI_ydnY9AYe:bbe8574) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fdfd1d1c3c6e32afcb61896f8967449f39288a29/src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx#L330)):*
> ```XML
>                     }
>                     padding: 0 !important;
>                     background-color: ${kMainPanelBackgroundColor} !important;
> ```

I discussed this with JH. He wants all the publish backgrounds to be white rather than the slight gray.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5474)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/publish/commonPublish/PublishScreenBaseComponents.tsx` line 48 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5474#-NEgr6G0EXmwlFbpZzqV:-NEhE4Zy0AGFadGNhxOh:b3yyupd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fdfd1d1c3c6e32afcb61896f8967449f39288a29/src/BloomBrowserUI/publish/commonPublish/PublishScreenBaseComponents.tsx#L48)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's figure out how to do this without the prop.

Should the thing under previews be a new subcomponent which adds the padding but is a child of PublishPanel?

The publish modes with previews will become the minority once PDF and Web use this template.
</blockquote></details>

Done. That worked!
___
*[`src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx` line 330 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5474#-NEgthzxEwI_ydnY9AYd:-NEh-5rp-RsW3oO-Dxdz:b-ol6svy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fdfd1d1c3c6e32afcb61896f8967449f39288a29/src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx#L330)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I discussed this with JH. He wants all the publish backgrounds to be white rather than the slight gray.
</blockquote></details>

... the advantage of re-used constants. Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5474)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx` line 311 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5474#-NEhL4Ak86v8OkvRkLuO:-NEhL4Ak86v8OkvRkLuP:bo6n0v4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1d2bb90a7792d22028e455a836ce7bb2365173c9/src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx#L311)):*
> ```XML
>     color: grey;`;
>     // Usually PublishPanel is the bottom section of a mainPanel component. Here it IS the mainPanel,
>     // so we don't need its built-in padding.
> ```

This comment is now obsolete. Then go ahead and merge.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5474)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx` line 311 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5474#-NEhL4Ak86v8OkvRkLuO:-NEkswJU0TRfejVAzXgP:b-udixpo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1d2bb90a7792d22028e455a836ce7bb2365173c9/src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx#L311)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This comment is now obsolete. Then go ahead and merge.
</blockquote></details>

Done. And removed the background color part of the next one for the same reason.

**Pull request merged**
