### PR TITLE
Implement dialog for creating a TC and improve settings panel (BL-9552)

### PR DESCRIPTION
**Pull request by JohnThomson**
Also parts of BL-9542

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 3 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208)* status: 3 of 13 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/teamCollection/CreateTeamCollection.html, line 1 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTqwtqp71DpIL6r1on1:-MTqwtqq5oKNh2WhACOL:bzabwlm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomBrowserUI/teamCollection/CreateTeamCollection.html#L1)):*
> ```HTML
> <!DOCTYPE html>
> ```

I think things would be simpler if this was a dialog that lives within the screen that launches it.  Should fit easily:


___
*[src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx, line 29 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTqy4cc2mGte7tkw9Ph:-MTqy4cc2mGte7tkw9Pi:btr3krf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx#L29)):*
> ```XML
>                 setProblemReport(e.problem);
>             }
>         };
> ```

This name is unclear: `teamCollectionCreate`. Sounds like some kind of imperative command, but maybe it is an event, like `TeamCollectionLocationChosen`?
___
*[src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx, line 30 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTqxe6h0x4tNIfbR9dX:-MTqxe6h0x4tNIfbR9dY:b-cmdo0p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx#L30)):*
> ```XML
>             }
>         };
>         WebSocketManager.addListener("teamCollectionCreate", listener);
> ```

Took me a bit to figure out the need for async here. Possible comment, if this is why?

`// We have to wait for the user to chose a destination, so we can't just do an http get. We have to get this callback from c#`
___
*[src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx, line 30 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTqy4Fh2O0DtN6HVXnI:-MTqy4Fh2O0DtN6HVXnJ:bbd0lm4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx#L30)):*
> ```
> teamCollectionCreate
> ```

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208)* status: 4 of 13 files reviewed, 8 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx, line 135 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTqyauu3QUDSZCc6mcX:-MTqyauu3QUDSZCc6mcY:bip7qkj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx#L135)):*
> ```XML
> // to get the ReactDOM.render call applied even though we can't do React inside
> // a local script element.
> (window as any).connectCreateTeamCollectionScreen = element => {
> ```

Can go away by making this screen a modal dialog of the parent screen
___
*[src/BloomBrowserUI/teamCollection/teamCollectionSettings.tsx, line 1 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTqzBtl8t2UCTw4mSnk:-MTqzBtl8t2UCTw4mSnl:boqjev2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomBrowserUI/teamCollection/teamCollectionSettings.tsx#L1)):*
> ```XML
> import * as React from "react";
> ```

Given this file name, I expected to see a file of properties, perhaps with persistence. Turns out it is a UI component. How about `TeamCollectSettingsPanel`?
___
*[src/BloomBrowserUI/teamCollection/teamCollectionSettings.tsx, line 22 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTqyz8qDXAutoXvNKbV:-MTqyz8qDXAutoXvNKbW:b5a5orc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomBrowserUI/teamCollection/teamCollectionSettings.tsx#L22)):*
> ```XML
> 
> // The contents of the Team Collection panel of the Settings dialog.
> // Currently based on an early mock-up, now superceded.
> ```

Are these comments out of date?
___
*[src/BloomBrowserUI/teamCollection/teamCollectionSettings.tsx, line 25 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTqz22I6fuIw6atNbGb:-MTqz22I6fuIw6atNbGc:befeqo0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomBrowserUI/teamCollection/teamCollectionSettings.tsx#L25)):*
> ```XML
> 
> export const TeamCollectionSettings: React.FunctionComponent = props => {
>     const urlParams = new URLSearchParams(window.location.search);
> ```

Maybe a comment on why we are getting props from a window url instead of props?

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208)* status: 4 of 13 files reviewed, 9 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Browser.cs, line 1405 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTqzmGWE8ks0126XXQD:-MTqzmGX86hIDV6XxnYs:b-q5ok7x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomExe/Browser.cs#L1405)):*
> ```Smalltalk
> 				return;
> 			}
> ```

I'm curious why this is implemented here. Wouldn't it be more natural to have an API with an endpoint called `ShowInFileExplorer`?

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208)* status: 4 of 13 files reviewed, 11 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 129 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTr-KU39iLPJ2Wc1bo9:-MTr-KU39iLPJ2Wc1boA:ba8n6qd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomExe/Collection/CollectionSettingsDialog.cs#L129)):*
> ```Smalltalk
> 				_sharingTab.Controls.Add(_sharingBrowser);
> 			};
> 			_sharingBrowser.OnBrowserClick += delegate(object sender, EventArgs args)
> ```

Please remove `sharing`.
___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 135 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTr-SSk4LyTnz4k238j:-MTr-SSk4LyTnz4k238k:baiv80l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomExe/Collection/CollectionSettingsDialog.cs#L135)):*
> ```Smalltalk
> 				var anchor = target as Gecko.DOM.GeckoAnchorElement;
> 				var anchorHref = Browser.GetAnchorHref(args);
> 				if (anchorHref != "" && anchorHref != "#")
> ```

I don't know what all this is all about, but it feels... retro and complicated.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208)* status: 4 of 13 files reviewed, 11 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/teamCollection/CreateTeamCollection.html, line 1 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTqwtqp71DpIL6r1on1:-MTr2z3x9Dcl3XJG9t0V:b-u03ht2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomBrowserUI/teamCollection/CreateTeamCollection.html#L1)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think things would be simpler if this was a dialog that lives within the screen that launches it.  Should fit easily:



</blockquote></details>

I've used various forms of this pattern for modals:

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208)* status: 4 of 13 files reviewed, 11 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/teamCollection/CreateTeamCollection.html, line 1 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTqwtqp71DpIL6r1on1:-MTr4OHq4MGS7BqLXzVj:b-m2fqkq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomBrowserUI/teamCollection/CreateTeamCollection.html#L1)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I've used various forms of this pattern for modals:



</blockquote></details>

Bit more:

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208)* status: 3 of 12 files reviewed, 11 unresolved discussions (waiting on @hatton)

___
*[src/BloomBrowserUI/teamCollection/CreateTeamCollection.html, line 1 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTqwtqp71DpIL6r1on1:-MTrOP18469bnA_qOFqy:bsskcb1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomBrowserUI/teamCollection/CreateTeamCollection.html#L1)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Bit more:


</blockquote></details>

I think we have a standard React way of doing it now, with a MaterialUI Dialog class. Done.
___
*[src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx, line 29 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTqy4cc2mGte7tkw9Ph:-MTrP5A42v4EB1ZCzWGE:bb7gzl0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx#L29)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This name is unclear: `teamCollectionCreate`. Sounds like some kind of imperative command, but maybe it is an event, like `TeamCollectionLocationChosen`?
</blockquote></details>

gone
___
*[src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx, line 30 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTqxe6h0x4tNIfbR9dX:-MTrP6aP7xJLbIfyWHAL:bb7gzl0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx#L30)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Took me a bit to figure out the need for async here. Possible comment, if this is why?

`// We have to wait for the user to chose a destination, so we can't just do an http get. We have to get this callback from c#`
</blockquote></details>

gone
___
*[src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx, line 30 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTqy4Fh2O0DtN6HVXnI:-MTrP99q8jbjtFKGPcrX:bb7gzl0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx#L30)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

> ```
> teamCollectionCreate
> ```

</blockquote></details>

gone
___
*[src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx, line 135 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTqyauu3QUDSZCc6mcX:-MTrPBnh1QpZJKj8Qqyu:bb7f2mf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx#L135)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Can go away by making this screen a modal dialog of the parent screen
</blockquote></details>

done
___
*[src/BloomBrowserUI/teamCollection/teamCollectionSettings.tsx, line 1 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTqzBtl8t2UCTw4mSnk:-MTrQd_N5HdiwfCUyA3S:btn5xw7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomBrowserUI/teamCollection/teamCollectionSettings.tsx#L1)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Given this file name, I expected to see a file of properties, perhaps with persistence. Turns out it is a UI component. How about `TeamCollectSettingsPanel`?
</blockquote></details>

Let's make this a separate commit, right after this is merged. This is an existing file, and making large changes to it in the same commit as it is renamed tends to confuse Git.
___
*[src/BloomBrowserUI/teamCollection/teamCollectionSettings.tsx, line 22 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTqyz8qDXAutoXvNKbV:-MTrPKbx2GtFjEgOPXS3:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomBrowserUI/teamCollection/teamCollectionSettings.tsx#L22)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Are these comments out of date?
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/teamCollection/teamCollectionSettings.tsx, line 25 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTqz22I6fuIw6atNbGb:-MTrPmhyCXh9nQdgdCcB:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomBrowserUI/teamCollection/teamCollectionSettings.tsx#L25)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Maybe a comment on why we are getting props from a window url instead of props? 
</blockquote></details>

Done.
___
*[src/BloomExe/Browser.cs, line 1405 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTqzmGWE8ks0126XXQD:-MTrPpUN4nf8L_dmnEQM:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomExe/Browser.cs#L1405)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I'm curious why this is implemented here. Wouldn't it be more natural to have an API with an endpoint called `ShowInFileExplorer`?
</blockquote></details>

Done.
___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 129 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTr-KU39iLPJ2Wc1bo9:-MTrQYqk0KRe54Yp9ZiY:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomExe/Collection/CollectionSettingsDialog.cs#L129)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Please remove `sharing`.
</blockquote></details>

Done.
___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 135 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTr-SSk4LyTnz4k238j:-MTrQZpP-OtyZMOfnDjs:bb7gzl0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98315e3e4be16a25ee8695b5dae9ce5d0bb1eee6/src/BloomExe/Collection/CollectionSettingsDialog.cs#L135)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I don't know what all this is all about, but it feels... retro and complicated.
</blockquote></details>

gone

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208)* status: 4 of 12 files reviewed, 9 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx, line 61 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTreHgqCx3es1ydQ7zf:-MTreHgr2ZhwZTBX6w7X:bss2z6t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f90e0e91376f52d016fcfcfdb00effd1c86c5bef/src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx#L61)):*
> ```XML
>                             temporarilyDisableI18nWarning={true}
>                             onClick={() =>
>                                 BloomApi.get(
> ```

Won't this `get` time out if you don't choose a folder quickly enough?  If not, somehow, can you add a comment explaining that?

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208)* status: 5 of 12 files reviewed, 9 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomBrowserUI/teamCollection/teamCollectionSettings.tsx, line 27 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTrexg06nLM108rfAC6:-MTrexg06nLM108rfAC7:bneb14j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f90e0e91376f52d016fcfcfdb00effd1c86c5bef/src/BloomBrowserUI/teamCollection/teamCollectionSettings.tsx#L27)):*
> ```XML
>     // provide any props. We instead use a url param to communicate from C# to this whether we are showing settings
>     // for a collection that is already part of a team collection (and if so, to provide the collection path).
>     const urlParams = new URLSearchParams(window.location.search);
> ```

This is fine, but I think at our next opportunity, let's make a standard c# control, `ReactComponent`, which
* provides a browser
* takes these parameters:
  * the name of the bundle
  *  the name of a component
  * an `object` which is the props

That last isn't actually needed, as the component could just use the API to get its props. Not needed in this case either?

**Review by hatton — COMMENTED** [review]
> Reviewed 7 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208)* status: 11 of 12 files reviewed, 4 unresolved discussions (waiting on @hatton and @JohnThomson)

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208)* status: 11 of 12 files reviewed, 4 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomBrowserUI/teamCollection/teamCollectionSettings.tsx, line 27 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTrexg06nLM108rfAC6:-MTrmZ4V0ZmYbzbL8Oug:b-xh82ub) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f90e0e91376f52d016fcfcfdb00effd1c86c5bef/src/BloomBrowserUI/teamCollection/teamCollectionSettings.tsx#L27)):*
> make a standard c# control, ReactComponent, which

I've written this up as `BL-9579 Simplify Conversion of CollectionSettings panel to react.` I would really like browser code removed from CollectionSettingsDialog, and the path to increased use of react paved instead of hacked through the jungle each time :-)

**Review by hatton — COMMENTED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton and @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx, line 61 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTreHgqCx3es1ydQ7zf:-MTv3McR8vwR1UWfJZV3:bdmn40l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f90e0e91376f52d016fcfcfdb00effd1c86c5bef/src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx#L61)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Won't this `get` time out if you don't choose a folder quickly enough?  If not, somehow, can you add a comment explaining that?
</blockquote></details>

One site says FF times out after 90s. I switched it back to using WebSocket and added comments.
___
*[src/BloomBrowserUI/teamCollection/teamCollectionSettings.tsx, line 27 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTrexg06nLM108rfAC6:-MTv3Ums8tLQ7_c03W62:b-vur305) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f90e0e91376f52d016fcfcfdb00effd1c86c5bef/src/BloomBrowserUI/teamCollection/teamCollectionSettings.tsx#L27)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

> make a standard c# control, ReactComponent, which

I've written this up as `BL-9579 Simplify Conversion of CollectionSettings panel to react.` I would really like browser code removed from CollectionSettingsDialog, and the path to increased use of react paved instead of hacked through the jungle each time :-)
</blockquote></details>

Good idea. Nothing to do for this PR, then?

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208)* status: 10 of 12 files reviewed, 5 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx, line 28 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTv5hCYA7iyqXUEMQTV:-MTv5hCYA7iyqXUEMQTW:b-lu7va6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e90177269d02daffcb890bee94842badcf78ea86/src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx#L28)):*
> ```XML
>     // and then selects a folder. We use a listener rather than having the API request return the
>     // results to guard against a browser timeout on the request.
>     React.useEffect(() => {
> ```

WOuld make a good reusable hook, probably in WebSocketManager. Would help those who implement something similar in the future.
___
*[src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx, line 30 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTv5bjk5Ma5vk94-Ret:-MTv5bjk5Ma5vk94-Reu:bqakxeq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e90177269d02daffcb890bee94842badcf78ea86/src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx#L30)):*
> ```XML
>     React.useEffect(() => {
>         const listener = e => {
>             if (e.id === "shared-folder-path") {
> ```

Some left over "shared" nomenclature we should remove?
___
*[src/BloomBrowserUI/teamCollection/teamCollectionSettings.tsx, line 27 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTrexg06nLM108rfAC6:-MTv50cUBZGGcY-pWUvD:b-7jzv7t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f90e0e91376f52d016fcfcfdb00effd1c86c5bef/src/BloomBrowserUI/teamCollection/teamCollectionSettings.tsx#L27)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Good idea. Nothing to do for this PR, then?
</blockquote></details>

right

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208)* status: 10 of 12 files reviewed, 6 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx, line 72 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTv607p5WUrW_nm_v-l:-MTv607p5WUrW_nm_v-m:b-2mg3as) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e90177269d02daffcb890bee94842badcf78ea86/src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx#L72)):*
> ```XML
>                             variant="text"
>                             temporarilyDisableI18nWarning={true}
>                             // This will eventually timeout if the user doesn't choose a folder or cancel
> ```

Better to not timeout. Just have the api return immediately?

**Review by gmartin7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208)* status: 10 of 12 files reviewed, 7 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[DistFiles/localization/en/Bloom.xlf, line 4811 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTv6kpvBCyk0rmbH_ie:-MTv6kpvBCyk0rmbH_if:b-e2eikg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e90177269d02daffcb890bee94842badcf78ea86/DistFiles/localization/en/Bloom.xlf#L4811)):*
> ```XML
>       <trans-unit id="TeamCollection.Intro" sil:dynamic="true">
>         <source xml:lang="en">Bloom's Team Collection system helps your team collaborate as you create, translate, and edit books. Find out [how it
>                 works(text)]({0}) and [how it works (video)]({1}).</source>
> ```

This seems like it might be difficult to translate in some languages. Colin and I asked @hatton for permission to change the UI to: 
"Read about how it works `here`, or view this `video`. where `here` is a hyperlink, and `video` is a hyperlink.
He approved the change.
___
*[src/BloomBrowserUI/react_components/link.tsx, line 22 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTv7SQx9N029okMOY2t:-MTv7SQx9N029okMOY2u:br53drj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e90177269d02daffcb890bee94842badcf78ea86/src/BloomBrowserUI/react_components/link.tsx#L22)):*
> ```XML
> // A link element that is localizable.
> // Note: if you find yourself looking for a way to make one of these with the text forced to
> // upper case, you may be really wanting a BloomButton with variant={text}
> ```

Helpful! Thanks.

**Review by gmartin7 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208)* status: all files reviewed, 7 unresolved discussions (waiting on @hatton and @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208)* status: 10 of 13 files reviewed, 7 unresolved discussions (waiting on @gmartin7, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx, line 28 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTv5hCYA7iyqXUEMQTV:-MTvDbVE89KqAEVNkOED:bhrhdbu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e90177269d02daffcb890bee94842badcf78ea86/src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx#L28)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

WOuld make a good reusable hook, probably in WebSocketManager. Would help those who implement something similar in the future.
</blockquote></details>

Already existed, more or less...now using.
___
*[src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx, line 30 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208#-MTv5bjk5Ma5vk94-Ret:-MTvDaqL0DKI4SqrO_af:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e90177269d02daffcb890bee94842badcf78ea86/src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx#L30)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Some left over "shared" nomenclature we should remove?
</blockquote></details>

Done.

**Review by gmartin7 — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208)* status: all files reviewed, 7 unresolved discussions (waiting on @hatton and @JohnThomson)

**Review by hatton — COMMENTED** [review]
> Reviewed 1 of 3 files at r4, 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4208)* status: all files reviewed, 4 unresolved discussions (waiting on @hatton and @JohnThomson)

**Pull request merged**
