### PR TITLE
Stop ePUB paragraphs from showing in columns (BL-4320)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1521)

### CODE REVIEW

**Comment by hatton** [comment]
Pretty sure this would break other things.

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookLayout/languageDisplay.less, line 8 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1521#-KdnAsticfn6wyPrybVa:-KdnAsticfn6wyPrybVb:b-535iym) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e7991266bef36d88e0f7863fe737d7d005a1348b/src/BloomBrowserUI/bookLayout/languageDisplay.less#L8)):*
> ```Less
>     // possible vertical alignment.
>     // But display:flex causes multiple paragraphs to each show in its own column.  (BL-4320)
>     display: block;
> ```

I think JT just changed this to flex recently to make vertical alignment work. Same below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1521)*

**Comment by StephenMcConnel** [comment]
I changed this to have ePUBs not include bookLayout/languageDisplay.css as per our discussion during the hangout.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookLayout/languageDisplay.less, line 8 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1521#-KdnAsticfn6wyPrybVa:-Ke0HAuPx5JA7q3tRhp8:b6pll2k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e7991266bef36d88e0f7863fe737d7d005a1348b/src/BloomBrowserUI/bookLayout/languageDisplay.less#L8)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think JT just changed this to flex recently to make vertical alignment work. Same below.
</blockquote></details>

JT says that display:block is still appropriate for ePUBs where we have much less control over the display anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1521#-:-Ke0GzEc5_4nweMmqc5O:b-8hx3mh)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/ePUB/baseEPUB.less, line 36 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1521#-Ke0UzeZ1WsAdlJqhjOO:-Ke0UzeZ1WsAdlJqhjOP:b-n754l4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2202c4add816f391a9b63278ab96fc69ddb6b9f2/src/BloomBrowserUI/ePUB/baseEPUB.less#L36)):*
> ```Less
> div.bloom-editable {
>     margin-bottom: 0.6em;
>     display: block;
> ```

I'm totally speculating here, but it seems this could make some things visible which shouldn't be.
The only specific example I can think of to check would be a book with multiple languages. But you probably tested that.

The other thing I am wondering about... are we saying that if a user vertically aligns some text at the bottom of a page, we are okay ignoring that in their epub?

---

*[src/BloomExe/Publish/EpubMaker.cs, line 791 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1521#-Ke0VnWTsySpuWJZNr-D:-Ke0VnWTsySpuWJZNr-E:b8iqa06) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2202c4add816f391a9b63278ab96fc69ddb6b9f2/src/BloomExe/Publish/EpubMaker.cs#L791)):*
> pages

Not just pages, right? Any element?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1521)*

**Comment by StephenMcConnel** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/ePUB/baseEPUB.less, line 36 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1521#-Ke0UzeZ1WsAdlJqhjOO:-Ke0r3sk-lZeIUNzMdrW:b-t7nauo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2202c4add816f391a9b63278ab96fc69ddb6b9f2/src/BloomBrowserUI/ePUB/baseEPUB.less#L36)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm totally speculating here, but it seems this could make some things visible which shouldn't be.
The only specific example I can think of to check would be a book with multiple languages. But you probably tested that.

The other thing I am wondering about... are we saying that if a user vertically aligns some text at the bottom of a page, we are okay ignoring that in their epub?
</blockquote></details>

The premise I've been going on is that JohnT says that everything we don't want to display is removed from the ePUB so that we don't ship unnecessary bytes to take up more space than needed on phones.  There's also the fact that not all readers do a good job of handling display:none, so we can't rely on it.
The less/css for epubs is so much simpler than that for the editing/PDF publishing path that a lot of work would need to be done to really handle all the fancy formatting we're doing in the latter case.  This issue is trying to fix an obvious breakage in ePUBs.  If you think the right fix is to bring the formatting of ePUBs up to par with printed books, 1) I'm the wrong person to do it, and 2) that's not the feedback I've been getting from others on the team.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 791 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1521#-Ke0VnWTsySpuWJZNr-D:-Ke0rnVe-CGATUn7AgyD:b9rbe12) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2202c4add816f391a9b63278ab96fc69ddb6b9f2/src/BloomExe/Publish/EpubMaker.cs#L791)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> pages

Not just pages, right? Any element?
</blockquote></details>

I suppose it would be any div in the case of the visibility marking.  I have absolutely no idea what granularity the (or how) user can assign invisibility, but I can adjust the comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1521)*

**Comment by andrew-polk** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/ePUB/baseEPUB.less, line 36 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1521#-Ke0UzeZ1WsAdlJqhjOO:-Ke3u-uyzH63RjYQqCdx:b22yprx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2202c4add816f391a9b63278ab96fc69ddb6b9f2/src/BloomBrowserUI/ePUB/baseEPUB.less#L36)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

The premise I've been going on is that JohnT says that everything we don't want to display is removed from the ePUB so that we don't ship unnecessary bytes to take up more space than needed on phones.  There's also the fact that not all readers do a good job of handling display:none, so we can't rely on it.
The less/css for epubs is so much simpler than that for the editing/PDF publishing path that a lot of work would need to be done to really handle all the fancy formatting we're doing in the latter case.  This issue is trying to fix an obvious breakage in ePUBs.  If you think the right fix is to bring the formatting of ePUBs up to par with printed books, 1) I'm the wrong person to do it, and 2) that's not the feedback I've been getting from others on the team.
</blockquote></details>

Sounds like maybe this is a PR @JohnThomson would be better handling, then.

I think my original point is still worth considering. We remove elements based on if the browser is displaying them. If we make a change which errantly causes the browser to display something, it will not be properly removed before publication. It seems to me that this change could cause such an error. If you have considered that already and decided it is not true, great. I just want to make sure it is considered.

On the issue of epubs displaying differently than printed books, I agree this is not the place to make those changes. But I am surprised to understand that is our intent. And if it isn't our intent, we would be better off not going further down that road.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1521)*

**Comment by JohnThomson** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/ePUB/baseEPUB.less, line 36 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1521#-Ke0UzeZ1WsAdlJqhjOO:-Ke48jk-5F8iH18aEfi6:b-7wiaun) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2202c4add816f391a9b63278ab96fc69ddb6b9f2/src/BloomBrowserUI/ePUB/baseEPUB.less#L36)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sounds like maybe this is a PR @JohnThomson would be better handling, then.

I think my original point is still worth considering. We remove elements based on if the browser is displaying them. If we make a change which errantly causes the browser to display something, it will not be properly removed before publication. It seems to me that this change could cause such an error. If you have considered that already and decided it is not true, great. I just want to make sure it is considered.

On the issue of epubs displaying differently than printed books, I agree this is not the place to make those changes. But I am surprised to understand that is our intent. And if it isn't our intent, we would be better off not going further down that road.
</blockquote></details>

It is very possible that it is not practicable at all to make epubs look the same as a printed book. Even if we succeeded in completely fixing the layout, many books would probably be too small to read on some devices. But we don't even have full control over the layout...readers are highly varied in how they interpret things. Even with our simplified layout, I don't think any two of the ten or so readers I have renders a given book exactly the same. We decided early in the epub effort to limit our initial efforts to laying out the material we have in a basically sequential, vertical arrangement. Anything that is side-by-side on paper will be one-above-the-other in an epub. No doubt it's possible to do better than this, especially when we have our own reader, but it will still be quite a hard problem. Our thought was to postpone that effort until we see whether there is significant take-up of Bloom epubs, and if so, what users most want improved.
IIRC, the xmatter code decides what to delete based on actually laying out the pages (using paper stylesheets) and asking the browser what is visible. For content pages, I think we tried (probably prematurely) to optimize and emulate the effect. We probably should switch to the xmatter strategy for everything, especially now we've given template makers control over what languages are visible in content. But that's another PR. Here, we're just trying to clean up the consequences of the fact that switching from display:block to display:flex for the purpose of overriding display:none caused problems for epubs whose readers don't seem to handle flex well.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 791 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1521#-Ke0VnWTsySpuWJZNr-D:-Ke4BuckbVd6zxsQ3ZY2:bu8ymws) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2202c4add816f391a9b63278ab96fc69ddb6b9f2/src/BloomExe/Publish/EpubMaker.cs#L791)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I suppose it would be any div in the case of the visibility marking.  I have absolutely no idea what granularity the (or how) user can assign invisibility, but I can adjust the comment.
</blockquote></details>

The visibility we're talking about here is the hiding of blocks of text in languages not of current interest. Since the new origami formatting gives the user more control over what languages are visible in a given block, probably the epub's decision-making is broken. I need to test that and make a card.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1521)*

**Comment by JohnThomson** [comment]
@hatton did not like some side effects of this fix

**Comment by StephenMcConnel** [comment]
John closed this accidently -- he meant to close another PR.

**Comment by StephenMcConnel** [comment]
This works okay with the recent change to allow borders in ePUBs.

**Comment by JohnThomson** [comment]
I think it's time to merge this. If we need to do more we can, but this fixes the problem of horizontal paragraph sequences and I don't think it harms anything.

---

Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 791 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1521#-Ke0VnWTsySpuWJZNr-D:-Ke570J87ROWr_f6g8FJ:bxlxqfi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2202c4add816f391a9b63278ab96fc69ddb6b9f2/src/BloomExe/Publish/EpubMaker.cs#L791)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

The visibility we're talking about here is the hiding of blocks of text in languages not of current interest. Since the new origami formatting gives the user more control over what languages are visible in a given block, probably the epub's decision-making is broken. I need to test that and make a card.
</blockquote></details>

I think that last comment was wrong. This some new sort of user control of visibility.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1521#-:-Ke577PxOwJb66p79VkZ:b-sxfdlw)*

**Pull request merged**
