### PR TITLE
[3.8]BL-4605 Change message for websocket port problem

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1673)

### CODE REVIEW

**Comment by hatton** [comment]
Looks like these want to be unified into one call or variable?

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/web/BloomWebSocketServer.cs, line 63 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1673#-KjyH9EARyxyyOfXIE9i:-KjyH9EARyxyyOfXIE9j:bhufx4p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/23bab1170e77a149cf8f2b1cb8e9576cf072f786/src/BloomExe/web/BloomWebSocketServer.cs#L63)):*
> antivirus

I'm thinking we should say "anti-malware" or "antivirus" in both places.

---

*[src/BloomExe/web/CommandAvailabilityPublisher.cs, line 60 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1673#-KjyHKD9GuzTpXhi2FLs:-KjyHKD9GuzTpXhi2FLt:b-ubi9w0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/23bab1170e77a149cf8f2b1cb8e9576cf072f786/src/BloomExe/web/CommandAvailabilityPublisher.cs#L60)):*
> ```Smalltalk
> 			{
> 				ErrorReport.NotifyUserOfProblem(ex,
> 					"Bloom cannot start properly, because something prevented it from opening port {1},{0}" +
> ```

Aren't these the same message? Let's reuse it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1673)*

**Comment by hatton** [comment]
hmmm, technically I guess anti-malware is the ubmrella term. Just seems a long ways from easy English...

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1673#-:-KkCOiPLIVF9yyyw-RC_:bnfp4nl)*

**Pull request merged**
