### PR TITLE
BL-9169 Try again to solve gap in page list after deletes

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4104)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4104)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx, line 222 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4104#-MNyMmQDCdrNqvaJc3Cj:-MNyMmQDCdrNqvaJc3Ck:bkq4w1n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0882aef74563c43459189f51c29f15729fac5b02/src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx#L222)):*
> ```XML
>                         scrollContainer="#pageGridWrapper"
>                         resize={true} // expand lazy elements as needed when container resizes
>                         offset={200} // give the component a better chance of noticing pages we need to show
> ```

This comment doesn't seem to fit with my understanding of offset.
Since offset is a distance in pixels, how does that help the loader "notice" pages?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4104)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx, line 222 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4104#-MNyMmQDCdrNqvaJc3Cj:-MNySc4dDxwi9eIffHxp:b-icehzd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0882aef74563c43459189f51c29f15729fac5b02/src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx#L222)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This comment doesn't seem to fit with my understanding of offset.
Since offset is a distance in pixels, how does that help the loader "notice" pages?
</blockquote></details>

I'm not actually sure it makes a difference.
From the api docs: to preload a component even if it's 100px below the viewport (or 200 here).
I was thinking it might be more likely to render it, it the area where it should render it was larger.

**Comment by andrew-polk** [comment]
___
*[src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx, line 193 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4104#-MNyX3U1E_VPcrSonO88:-MNyX3U1E_VPcrSonO89:b-1vhfpm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0882aef74563c43459189f51c29f15729fac5b02/src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx#L193)):*
> ```XML
>         // https://stackoverflow.com/questions/61191496/why-is-my-react-lazyload-component-not-working)
>         forceCheck();
>     }, [realPageList]);
> ```

Based on the comment before this useEffect and my (possibly wrong) understanding of how arrays work when they are the trigger of a useEffect, it seems this is only called once per book.

Is it called when the contents of realPageList change? Or are we creating a new array if the contents change?
Or should we have another useEffect which just triggers on the length of realPageList?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4104)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx, line 193 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4104#-MNyX3U1E_VPcrSonO88:-MNyXiiQD1xYjuBEgiX4:bra4vhq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0882aef74563c43459189f51c29f15729fac5b02/src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx#L193)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Based on the comment before this useEffect and my (possibly wrong) understanding of how arrays work when they are the trigger of a useEffect, it seems this is only called once per book.

Is it called when the contents of realPageList change? Or are we creating a new array if the contents change?
Or should we have another useEffect which just triggers on the length of realPageList?
</blockquote></details>

I checked with a `console.log()` just after the `forceCheck()` here. It was triggered every time I deleted a page. ;) Yeah, I was wondering about the same things until I tested it.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4104)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx, line 193 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4104#-MNyX3U1E_VPcrSonO88:-MNyYUx52SE9CV69H4Jy:b32wtd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0882aef74563c43459189f51c29f15729fac5b02/src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx#L193)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I checked with a `console.log()` just after the `forceCheck()` here. It was triggered every time I deleted a page. ;) Yeah, I was wondering about the same things until I tested it.
</blockquote></details>

ok

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4104)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx, line 222 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4104#-MNyMmQDCdrNqvaJc3Cj:-MNy_BDL1Ep5-R3al7s3:b-j26x8z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0882aef74563c43459189f51c29f15729fac5b02/src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx#L222)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I'm not actually sure it makes a difference.
From the api docs: to preload a component even if it's 100px below the viewport (or 200 here).
I was thinking it might be more likely to render it, it the area where it should render it was larger.
</blockquote></details>

The `offset` prop didn't seem to affect the behavior at all. Removed.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4104)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
