### PR TITLE
Require user to be admin to edit settings in TC (BL-9869)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4419)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4419)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetupDialog.ts, line 70 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4419#-MZZkwzuEfmyDwVnIHL3:-MZZkwzuEfmyDwVnIHL4:bhfagl0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d711d1c3a8377a22eac8434bbee1cb61c24a55a4/src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetupDialog.ts#L70)):*
> ```XML
>             getTheOneReaderToolsModel().setupType = showWhat;
> 
>             BloomApi.get("readers/io/readerSettingsEditForbidden", result => {
> ```

I can't really make sense of this jquery stuff. I assume there was no reasonable way to avoid further jquery work? Like, you couldn't just avoid opening this thing if the user doesn't have permissions? 
___
*[src/BloomExe/Collection/CollectionSettings.cs, line 209 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4419#-MZZicUAEIgHfIlCYlpg:-MZZicUAEIgHfIlCYlph:b-ungagp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d711d1c3a8377a22eac8434bbee1cb61c24a55a4/src/BloomExe/Collection/CollectionSettings.cs#L209)):*
> ```Smalltalk
> 		}
> 
> 		public static string MustBeAdminMessage => LocalizationManager.GetString("TeamCollection.MustBeAdmin",
> ```

It would be better if we could keep UI out of the this data structure class. I understand that it's used in multiple places, so you want some common place. Just pick a place that is on the UI level. Maybe even create a new Permissions class and group this and various api calls there?
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 44 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4419#-MZZkOdJ5Ejn2FWOkW8K:-MZZkOdJ5Ejn2FWOkW8L:b-y8ydmo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d711d1c3a8377a22eac8434bbee1cb61c24a55a4/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L44)):*
> ```Smalltalk
> 
> 		// intended for use only by TeamCollectionManager, see comment in OkToEditCollectionSettings
> 		internal CollectionSettings Settings => _settings;
> ```

Let's not have this here. I'll address what I'm guessing is the root reason it's here over in that TCM code.
___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 84 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4419#-MZZkhXr175YdmMNZ4yz:-MZZkhXs-yF9pwY10uks:bpe7l1i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d711d1c3a8377a22eac8434bbee1cb61c24a55a4/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L84)):*
> ```Smalltalk
> 		// before the CS is loaded. So we need another way to get it when needed
> 		// later. This is the least kludgy I've found.
> 		private CollectionSettings Settings => TeamCollectionApi.TheOneInstance.Settings;
> ```

How about just have the ProjectContext set it. E.g. it does

`ToolboxView.SetupToolboxForCollection(Settings);`

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4419)* status: 0 of 10 files reviewed, 4 unresolved discussions (waiting on @hatton)

___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetupDialog.ts, line 70 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4419#-MZZkwzuEfmyDwVnIHL3:-M_LQpWo7C-gQjW-ldD7:b2obl7p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d711d1c3a8377a22eac8434bbee1cb61c24a55a4/src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetupDialog.ts#L70)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I can't really make sense of this jquery stuff. I assume there was no reasonable way to avoid further jquery work? Like, you couldn't just avoid opening this thing if the user doesn't have permissions? 
</blockquote></details>

There are always options. This showSetupDialog() function is called from two places and the dialog has to come up in a different iframe from the code that launches it, so that's already a bit tricky. At some point, there has to be a BloomApi.get() to find out whether we are allowed to do settings. It seemed better to have that in the common method rather than duplicate it in both callers. And we already figured out the trickiness of bringing up a dialog in a different iframe from the code launching it, so I preferred not to duplicate that. Git doesn't make this very clear, but all I really did was replace the normal dialog content with the message if we're not allowed to do it, and hide buttons other than Cancel.
___
*[src/BloomExe/Collection/CollectionSettings.cs, line 209 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4419#-MZZicUAEIgHfIlCYlpg:-M_LN6OR8VgM7Js_mdww:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d711d1c3a8377a22eac8434bbee1cb61c24a55a4/src/BloomExe/Collection/CollectionSettings.cs#L209)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

It would be better if we could keep UI out of the this data structure class. I understand that it's used in multiple places, so you want some common place. Just pick a place that is on the UI level. Maybe even create a new Permissions class and group this and various api calls there?
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 44 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4419#-MZZkOdJ5Ejn2FWOkW8K:-M_LOiiq9SZgbWoZcJRG:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d711d1c3a8377a22eac8434bbee1cb61c24a55a4/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L44)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Let's not have this here. I'll address what I'm guessing is the root reason it's here over in that TCM code.
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 84 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4419#-MZZkhXr175YdmMNZ4yz:-M_LOiKD-HuhzeT08IoM:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d711d1c3a8377a22eac8434bbee1cb61c24a55a4/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L84)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

How about just have the ProjectContext set it. E.g. it does

`ToolboxView.SetupToolboxForCollection(Settings);`
</blockquote></details>

Done.

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 4 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4419)* status: 5 of 10 files reviewed, 3 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/Workspace/WorkspaceView.cs, line 837 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4419#-M_MkjTPEZJXHc-FzMeh:-M_MkjTPEZJXHc-FzMei:b6dcu79) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b596887b3d36246d188c805428848eb9cc99675f/src/BloomExe/Workspace/WorkspaceView.cs#L837)):*
> ```Smalltalk
> 			using (var dlg = new ShowReleaseNotesDialog(Resources.BloomIcon, path))
> 			{
> 				// Try to make the dialog big enough to show the embedded images without horizontal
> ```

Did this sneak in from another PR? Steve was working on this.
___
*[src/BloomExe/Workspace/WorkspaceView.Designer.cs, line 511 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4419#-M_Ml3BwCgwE-qZ3ZvUn:-M_Ml3BwCgwE-qZ3ZvUo:bewazq2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b596887b3d36246d188c805428848eb9cc99675f/src/BloomExe/Workspace/WorkspaceView.Designer.cs#L511)):*
> ```Smalltalk
> 		private ToolStripMenuItem _askAQuestionMenuItem;
> 
> 		public static string MustBeAdminMessage => LocalizationManager.GetString("TeamCollection.MustBeAdmin",
> ```

Really surprised to find this coded added to *Designer.cs* code. What's the story?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4419)* status: 5 of 10 files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/Workspace/WorkspaceView.cs, line 837 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4419#-M_MkjTPEZJXHc-FzMeh:-M_MuNZP3Xx9u04-_MR1:b-ce049a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b596887b3d36246d188c805428848eb9cc99675f/src/BloomExe/Workspace/WorkspaceView.cs#L837)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Did this sneak in from another PR? Steve was working on this.
</blockquote></details>

Not seeing what you mean. The only change I see here is that some prettifier decided to remove some redundant namespace prefixes.
___
*[src/BloomExe/Workspace/WorkspaceView.Designer.cs, line 511 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4419#-M_Ml3BwCgwE-qZ3ZvUn:-M_Mu_HZ5YnhNMrKZRHX:b-fzbx9t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b596887b3d36246d188c805428848eb9cc99675f/src/BloomExe/Workspace/WorkspaceView.Designer.cs#L511)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Really surprised to find this coded added to *Designer.cs* code. What's the story?
</blockquote></details>

Grrrr. I told refactor to move it from one class to another, and apparently this is what it picked. Fixed.

**Review by hatton — APPROVED** [review]
> Reviewed 3 of 9 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4419)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/Workspace/WorkspaceView.cs, line 837 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4419#-M_MkjTPEZJXHc-FzMeh:-M_MxAGyBKvt9rteWFzQ:byqevex) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b596887b3d36246d188c805428848eb9cc99675f/src/BloomExe/Workspace/WorkspaceView.cs#L837)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Not seeing what you mean. The only change I see here is that some prettifier decided to remove some redundant namespace prefixes.
</blockquote></details>

This whole section was shown as new (green) when I wrote the comment, but not now.

**Pull request merged**
