### PR TITLE
Don't let harvester break font synthesis (BL-12594)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6036)

### CODE REVIEW

**Comment by andrew-polk** [comment]
*[`src/BloomExe/Book/Book.cs` line 1629 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6036#-NawYo6n95-1ODvDqttq:-NawYo6n95-1ODvDqttr:b-rh878t) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/95c03951f1e08dc56156020d59ae04c31550af8a/src/BloomExe/Book/Book.cs#L1629)):*
> ```Smalltalk
> 					CollectionSettings.Language1Tag,
> 					CollectionSettings.Language2Tag
> 				};
> ```

This is just a simplification which doesn't change the logic.

**Review by StephenMcConnel — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6036)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/Book/Book.cs` line 1674 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6036#-NaxLJ_s2sxwnB7vzwmd:-NaxLJ_s2sxwnB7vzwme:b2agteu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/95c03951f1e08dc56156020d59ae04c31550af8a/src/BloomExe/Book/Book.cs#L1674)):*
> ```Smalltalk
> 		{
> 			var contents = RobustFile.ReadAllText(path);
> 			contents = Regex.Replace(contents, "^@font-face.*$\n", "", RegexOptions.Multiline);
> ```

I've only ever seen using $ to match the end of line to also have the $ as the last item in the match.  I think I understand you to want to remove the line altogether and not leave a blank line where the font-face declaration was.  Does this code really work?  If so, I'm happy with it.
(I'd also be happy with leaving blank lines in the file since I don't think they hurt anything.)

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6036)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Book/Book.cs` line 1674 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6036#-NaxLJ_s2sxwnB7vzwmd:-Nb0bqKO4SqrP2pBiK8K:bkwy75p) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/95c03951f1e08dc56156020d59ae04c31550af8a/src/BloomExe/Book/Book.cs#L1674)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I've only ever seen using $ to match the end of line to also have the $ as the last item in the match.  I think I understand you to want to remove the line altogether and not leave a blank line where the font-face declaration was.  Does this code really work?  If so, I'm happy with it.
(I'd also be happy with leaving blank lines in the file since I don't think they hurt anything.)
	
</blockquote></details>

Yep, it works.
I also was unsure before I tried it the first time.

Yes, the goal is to not leave blank lines.

I added a test.

**Review by StephenMcConnel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6036#-:-NbRM14i0v25f0PJlWuv:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Review by StephenMcConnel — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6036)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
