### PR TITLE
Show Status pane for Team Collection dialog when disconnected (BL-12021)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5707)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5707)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/teamCollection/TeamCollectionDialog.tsx` line 75 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5707#-NQfWCtP8QzKadfoMpwY:-NQfWCtP8QzKadfoMpwZ:b-z7jiv9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e5ad403dc4c8fd8fba6e7eeb9ec3fc0992353a69/src/BloomBrowserUI/teamCollection/TeamCollectionDialog.tsx#L75)):*
> ```XML
>     // we're in this waiting state and shouldn't display the Tabs at all. When we get the
>     // value from the API, we set defaultTabIndex to either 0 or 1 and the Tabs element is
>     // rendered for the first time with the correct defaultIndex.
> ```

This isn't due to your change, but the comment here is inaccurate. It states the initial state is -1.
___
*[`src/BloomBrowserUI/teamCollection/TeamCollectionDialog.tsx` line 82 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5707#-NQfW4Ji-sEf_8Vfaj3A:-NQfW4Ji-sEf_8Vfaj3B:bw8mu7r) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e5ad403dc4c8fd8fba6e7eeb9ec3fc0992353a69/src/BloomBrowserUI/teamCollection/TeamCollectionDialog.tsx#L82)):*
> ```XML
>     useEffect(() => {
>         BloomApi.getBoolean("teamCollection/logImportant", logImportant => {
>             setDefaultTabIndex(logImportant ? 0 : 1);
> ```

Seems like the fix for this should be to just have logImportant return true for this case. 
Is that not feasible for some reason?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5707)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/teamCollection/TeamCollectionDialog.tsx` line 75 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5707#-NQfWCtP8QzKadfoMpwY:-NQfX6U43Re1pQUgGf8I:bmgqizb) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e5ad403dc4c8fd8fba6e7eeb9ec3fc0992353a69/src/BloomBrowserUI/teamCollection/TeamCollectionDialog.tsx#L75)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This isn't due to your change, but the comment here is inaccurate. It states the initial state is -1.
</blockquote></details>

Actually, looking at the history here, I would bet that this is supposed to be -1 and then the tabs hidden while it is -1.
I bet a bad merge caused it to be lost.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5707)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5707)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/teamCollection/TeamCollectionDialog.tsx` line 82 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5707#-NQfW4Ji-sEf_8Vfaj3A:-NQzuI1T3mZP7ENrE_LJ:b-ewx8jq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e5ad403dc4c8fd8fba6e7eeb9ec3fc0992353a69/src/BloomBrowserUI/teamCollection/TeamCollectionDialog.tsx#L82)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems like the fix for this should be to just have logImportant return true for this case. 
Is that not feasible for some reason?
</blockquote></details>

I guess your reversion of the other changes means all we had to do was restore the defaultTabIndex to -1 to fix the original issue. Great!

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5707)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`src/BloomBrowserUI/teamCollection/TeamCollectionDialog.tsx` line 75 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5707#-NQfWCtP8QzKadfoMpwY:-NQgdj58BcUYSho8fqcX:b-tkd7lx) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e5ad403dc4c8fd8fba6e7eeb9ec3fc0992353a69/src/BloomBrowserUI/teamCollection/TeamCollectionDialog.tsx#L75)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Actually, looking at the history here, I would bet that this is supposed to be -1 and then the tabs hidden while it is -1.
I bet a bad merge caused it to be lost.
</blockquote></details>

Rereading the comment made me realize that not only did a previous merge change the -1 to a 1, but it also removed the mechanism to make things work by *not displaying* the BloomTabs element until defaultTabIndex was set properly.  Restoring that simplified everything.  The comment is entirely accurate for what should be happening, and what is now happening with my latest changes.
___
*[`src/BloomBrowserUI/teamCollection/TeamCollectionDialog.tsx` line 82 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5707#-NQfW4Ji-sEf_8Vfaj3A:-NQge-QO5X-YEcc6zxAZ:b-wrq1te) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e5ad403dc4c8fd8fba6e7eeb9ec3fc0992353a69/src/BloomBrowserUI/teamCollection/TeamCollectionDialog.tsx#L82)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems like the fix for this should be to just have logImportant return true for this case. 
Is that not feasible for some reason?
</blockquote></details>

Things are working fine once code prevents displaying the BloomTabs element until setDefaultTabIndex is called the first time  Nothing needs to be changed here (or in the C# code).

**Pull request merged**
