### PR TITLE
BL-9091 Auto Order Xmatter

### PR DESCRIPTION
**Pull request by hatton**
If we know we're going to a device, automatically put all pages that aren't the cover to the back.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3971)

### CODE REVIEW

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3971)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3971)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/Book/Book.cs, line 1414 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3971#-MIVvhETAKEKhDXBZqsv:-MIVvhETAKEKhDXBZqsw:b5kzex9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b21b1e91e9b760d8ea769e3e3aa5c9794bd0f67d/src/BloomExe/Book/Book.cs#L1414)):*
> ```Smalltalk
> 			// still requiring it to be a valid layout.
> 			layout = Layout.FromDomAndChoices(bookDOM, layout, fileLocator);
> 			helper.InjectXMatter(_bookData.GetWritingSystemCodes(), layout, CollectionSettings.BrandingProjectKey, Storage.FolderPath, BookInfo.UseDeviceXMatter);
> ```

Is BookInfo.UseDeviceXMatter true for custom device xmatters which may have multiple front matter pages?

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3971)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Book/Book.cs, line 1414 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3971#-MIVvhETAKEKhDXBZqsv:-MIW-oSaC8ZVIkb5Di7p:bb7y47q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b21b1e91e9b760d8ea769e3e3aa5c9794bd0f67d/src/BloomExe/Book/Book.cs#L1414)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is BookInfo.UseDeviceXMatter true for custom device xmatters which may have multiple front matter pages?
</blockquote></details>

Yeah that would take more work. Do we have such a beast already?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3971)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/Book/Book.cs, line 1414 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3971#-MIVvhETAKEKhDXBZqsv:-MIW9b-YA3mGLtjs6hkQ:bwm48sv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b21b1e91e9b760d8ea769e3e3aa5c9794bd0f67d/src/BloomExe/Book/Book.cs#L1414)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Yeah that would take more work. Do we have such a beast already?
</blockquote></details>

Yes, Dari and Pashto as you already discovered.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3971)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
