### PR TITLE
Make SendBook a background operation (BL-4812)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1794)

### CODE REVIEW

**Comment by JohnThomson** [comment]
I'm not quite clear why we want it in the background. I don't see any change to the "exactly one device connected" logic so I gather the idea is not to be able to send to multiple devices at the same time. That seems to leave allowing the user to go on with something else while the transfer completes. But to allow that I think we need to be more prepared for possibilities like finding that _progress has been disposed before we try to send it the completion notice, or getting a failure notice after the user has moved away from the publish tab altogether.
I'm still rather confused about what state we're supposed to be in with what event handlers active after the transfer completes (see previous PR).

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Publish/BloomReaderPublisher.cs, line 154 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1794#-KrXfRKFPRcepZZlr-5-:-KrXfRKFPRcepZZlr-50:b-kpjy8x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c25934bb9234ee89094fa2a2fffa686f11034dd6/src/BloomExe/Publish/BloomReaderPublisher.cs#L154)):*
> ```Smalltalk
> 		{
> 			var bookTitle = book.Title;
> 			_progress.WriteMessage(String.Format(LocalizationManager.GetString(
> ```

Does WriteMessage handle being called from non-UI thread?

---

*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 109 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1794#-KrXiCvbkHHCIYITtaon:-KrXiCvbkHHCIYITtaoo:bxsbd32) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c25934bb9234ee89094fa2a2fffa686f11034dd6/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L109)):*
> ```Smalltalk
> 		private void OnConnectionFailed(object sender, EventArgs args)
> 		{
> 			ResolveConnect("ReadyToConnect");
> ```

If this is supposed to put us into the "ready to connect" state, why does the method remove the OnConnected event handler?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1794#-:-KrXiX2yIc41uJhasVOH:b-42rpf7)*

**Comment by JohnThomson** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1794)*

**Comment by hatton** [comment]
> That seems to leave allowing the user to go on with something else while the transfer completes.

I don't know what prompted this change, but that for sure is not a goal. In fact we should consider what it would take to lock you in this screen until the state is no longer "sending".

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1794#-:-Kr_vWwqjUSxt89GTZIG:b-v96gpo)*

**Comment by andrew-polk** [comment]
It is very possible I made these changes without thinking clearly and there is a better way to accomplish what I did. But before the change, clicking Send Book would lock up the UI and the progress box would not update until the operation was complete. After the change, the UI becomes enabled (I understand your concerns that we may prefer that some of it not be usable, but ideally help links and scrolling the progress box would) and the progress is updated in real time.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Publish/BloomReaderPublisher.cs, line 154 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1794#-KrXfRKFPRcepZZlr-5-:-Krb5CYQ5HB5G3JhdG6y:b-63u3ll) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c25934bb9234ee89094fa2a2fffa686f11034dd6/src/BloomExe/Publish/BloomReaderPublisher.cs#L154)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Does WriteMessage handle being called from non-UI thread?
</blockquote></details>

I didn't notice an issue while testing.

---

*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 109 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1794#-KrXiCvbkHHCIYITtaon:-Krb5G8b7AsbgHkVtGPT:bhzejap) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c25934bb9234ee89094fa2a2fffa686f11034dd6/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L109)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

If this is supposed to put us into the "ready to connect" state, why does the method remove the OnConnected event handler?
</blockquote></details>

In this case, "ready to connect" state means ready to push the connect button, i.e. the Connect button is enabled and the Send Book button is disabled.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1794#-:-Krb4c7ePAkmY4UeqARV:by8yiho)*

**Comment by hatton** [comment]
sounds good to me

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1794#-:-Krb_hD129YifMNcIfk0:b-joddjj)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1794#-:-Krbli9WnodqeZCvhZ7f:bnfp4nl)*

**Pull request merged**
