### PR TITLE
BL-3330, update display when sample words change

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1029)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 70 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KFyqtYQ6lzCu-1Nyw22:-KFyqtYQ6lzCu-1Nyw23:-569695827) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/85b42c189dc34dfab178c109334ab79fd4966ed7/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L70)):*
This code moved into the RefreshSettingsExceptSampleWords method

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 947 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KFyrWDS08iPyuyAi5ii:-KFyrWDS08iPyuyAi5ij:1600492200) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/85b42c189dc34dfab178c109334ab79fd4966ed7/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L947)):*
This bit of complexity...skipping file types we don't handle...got moved into a filter for the list of texts we retain at all a the start of beginSetTextsList. The simulation of a loop using recursion with promises seemed like plenty of complexity for one method, so I'm trying to keep everything else out of it.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 970 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KFyrFofarwI4EoBWFnZ:-KFyrFofarwI4EoBWFn_:-1583838869) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/85b42c189dc34dfab178c109334ab79fd4966ed7/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L970)):*
This line was here to keep the recursion loop going in getNextSamplefiles...seems much more natural in the looping method (now beginGetAllSampleFiles)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029)*

**Comment by JohnThomson** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/libSynphony/synphony_lib.js, line 265 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KFysAeCjhWuA8Fr-oVl:-KFysAeCjhWuA8Fr-oVm:1870864770) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/libSynphony/synphony_lib.js#L265)):*
This change turned out not to be necessary...nothing ended up calling the new method. But I thought it made the code enough more readable to be worth retaining.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029)*

**Comment by hatton** [comment]
Reviewed 4 of 8 files at r1.
Review status: 4 of 8 files reviewed at latest revision, 15 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 225 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCuZrwgV4KeZy9ywFC:-KGCuZrwgV4KeZy9ywFD:1598802497) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L225)):*
I note that beginRefresh returns a promise, but that is lost here. Probably doesn't mater in this implementation, but is it dangerous to "lose" the fact that this is async, both by the name (the wrapper here doesn't have the begin-  prefix and doesn't have a promise signature.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 262 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCmQ1iErORMBZxCGaN:-KGCmQ1iErORMBZxCGaO:-603285432) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L262)):*
I know this isn't actually part of this commit, but I got tripped up here: Normally, one would say

    var synphony = new Syn...
    synphony.loadSettings(settings);
    RTM.model.setSynphony(synphony)

So I assumed that this was done the other way around because  setSynphony  does something to synphony? But i looked it up and it isn't doing anything, just assigns the member variable.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 268 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCo3OzuM56zJjMAV17:-KGCo3OzuM56zJjMAV18:552173627) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L268)):*
So, you're introducing Deferred because you want to keep the signature as a jquery promise, rather than a plain 'ol ES6 Promise that axios uses. Took me a while to figure that out, so comment would help. But can we just switch to ES6 Promise so that you can just say

    return axios.post(....

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 273 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCsqwu4ocEQdQtEY19:-KGCsqwvzUqN-gnqVMnZ:-393441960) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L273)):*
Same, can we use the [ES6 Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)?

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 291 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCvsPBoc1rFASRE5HH:-KGCvsPC1l198lH1plnD:1973783987) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L291)):*
I think this can be written more simply like this:

    var promise = axios post....
    return promise.then(....

I'm not sure, but the current way might be the "broken-chain" [anti-pattern](http://taoofcode.net/promise-anti-patterns/).
    

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 23 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCtGNteS-xduJtkX6q:-KGCtGNteS-xduJtkX6r:637539021) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L23)):*
Can't see where axiosxhr is used

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 919 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCxU9hCC2IsGjfL_xe:-KGCxU9hCC2IsGjfL_xf:93182310) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L919)):*
simplify as

    return RTM.model.begin...

?

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 923 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCwhD-m2kNruNixLkp:-KGCwhD-m2kNruNixLkq:1377248224) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L923)):*
Not part of this commit, but let's fix this while we're in here. There is no "other thread" in javascript unless one employees [web workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers). SetTimeout just means "later".

Worse, SetTimeout is not the "javascript equivalent"  though you might use that for the same purpose. Anyhow it's bad form to put comments in our JS code referring to c# concepts. ANyone working in JS should just learn the JS concepts.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 949 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCyxbom9BLjI3DslRd:-KGCyxbom9BLjI3DslRe:2033319470) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L949)):*
>  I don't know how to return a pre-resolved one when we get down to none left.

You need something different than

    return new Promise( (resolve, reject )=> resolve());

On the broader approach here, would be simpler to spawn an async call for each instead of doing recursion? E.g., using [promise.all](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all)?

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 966 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCznZeOOXairz8LUyQ:-KGCznZeOOXairz8LUyR:1973144882) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L966)):*
We seem to loose the string of promises here... we call begin but don't wait for it to finish.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/libSynphony/bloom_lib.js, line 19 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGD05aUNDOwZdMhSFWh:-KGD05aUNDOwZdMhSFWi:527762342) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/libSynphony/bloom_lib.js#L19)):*
While we're in here, can we rename this in some way that marks it obviously as a global static?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029)*

**Comment by JohnThomson** [comment]
Review status: 4 of 8 files reviewed at latest revision, 15 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 225 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCuZrwgV4KeZy9ywFC:-KGDI1emSeNXz1ALU_zG:-1809103271) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L225)):*
So what's the right way to terminate a promise chain, when the intent is just to let the incomplete stuff happen quietly in the background? Or does every caller of a beginX method always have to become one itself and continue the chain?

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 262 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCmQ1iErORMBZxCGaN:-KGDLtPbAVWuhIEz8RPb:1360730167) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L262)):*
I'm nervous that somewhere something that loadSettings calls may assume there is only one instance of synphony and access it through the RTM.model.synphony...which would not yet be set. Could try to trace through all the code...or try your way and hope to notice if anything breaks...the earliest version of this code assigned the synphony variable at its declaration, so it was once safe to assume it was always there...

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 268 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCo3OzuM56zJjMAV17:-KGDIwmbNXqWF9edtgwz:408566330) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L268)):*
I tried hard to do it with axios promises, but somewhere in the mess (may go away with promise.all) I actually have to create a promise myself...at least to cover the case where there are no sample files and I need to return an already-resolved promise (and currently this is also used at the end of the recursive chain, and in one place where one branch does something deferred and another doesn't). I'll try again.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 273 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCsqwu4ocEQdQtEY19:-KGDJeQdTjezyEjg9FJE:550562425) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L273)):*
Same problem, IIRC...all these methods call each other. I'll try.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 291 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCvsPBoc1rFASRE5HH:-KGDK60x0zGYbVRQW3gU:-153364896) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L291)):*
How do I come up with an axios-type promise (already resolved) for the 'else' case?

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 23 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCtGNteS-xduJtkX6q:-KGDKJCMYP-E1xmKHYyM:872883375) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L23)):*
May have been from an unsuccessful experiment. I'll see if it works without it.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 919 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCxU9hCC2IsGjfL_xe:-KGDLOGRJoUpAwFliePs:340342831) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L919)):*
All the comments are making it hard to figure out whether anything happens after the 'then'. If not, and if I can get all the promise types consistent, that would work.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 923 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCwhD-m2kNruNixLkp:-KGDKqZqf59MDUbNe9jn:577398283) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L923)):*
Do you just mean to fix the comment, or is there something better to do than the setTimeout?

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 949 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCyxbom9BLjI3DslRd:-KGDGun7RnGnHqYVSKu2:-1229305137) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L949)):*
I wondered about that...worried about multithreading issues...I think JavaScript isn't supposed to have that problem, is that true even with promises?

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 966 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCznZeOOXairz8LUyQ:-KGDHTFIYF9i38SRIJ0Q:-1458644517) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L966)):*
There's only one promise for the whole chain of recursive calls. That's why we pass it to the next iteration. The outermost non-recursive caller (that doesn't pass a promise in) does the waiting.
If I can switch it to promise.all this will all go away.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/libSynphony/bloom_lib.js, line 19 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGD05aUNDOwZdMhSFWh:-KGDKz1kBiGg6eNjt2eJ:160383661) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/libSynphony/bloom_lib.js#L19)):*
OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029)*

**Comment by JohnThomson** [comment]
Review status: 2 of 8 files reviewed at latest revision, 15 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 225 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCuZrwgV4KeZy9ywFC:-KGNcPdJZIbPqA8WBr-N:1661206169) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L225)):*
Following verbal discussion, decided this doesn't need changing

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 262 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCmQ1iErORMBZxCGaN:-KGNPvGpDSjSMBOP5-P4:955073042) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L262)):*
Seems to work your way, so I went ahead and changed it.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 268 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCo3OzuM56zJjMAV17:-KGNQ-cJuf7LYp4atScZ:1567146967) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L268)):*
OK, done

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 273 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCsqwu4ocEQdQtEY19:-KGNcN9Pnbt_F4zloUuM:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L273)):*
Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 291 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCvsPBoc1rFASRE5HH:-KGNcA_Rw7_AzykoZ8NH:243026305) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L291)):*
Works to just return null...actually the other branch, returning a promise from then, is a more unusual case

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 23 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCtGNteS-xduJtkX6q:-KGNc8uitzCM43u2yuif:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L23)):*
Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 919 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCxU9hCC2IsGjfL_xe:-KGNbxkIKmQiWewgHbYy:677588487) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L919)):*
done

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 923 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCwhD-m2kNruNixLkp:-KGNQf2Hu06Ee1qdo6ei:-1776512108) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L923)):*
I think I improved the comment, anyway

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 949 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCyxbom9BLjI3DslRd:-KGNbpT_4B9C4j-c3GEB:-909257002) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L949)):*
Seems fine...haven't tested with large number of sample files...

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 966 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGCznZeOOXairz8LUyQ:-KGNbkXQ2ZMevfkVFwL5:-916468470) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L966)):*
This whole mess went away using Promise.all

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/libSynphony/bloom_lib.js, line 19 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGD05aUNDOwZdMhSFWh:-KGNRHmMlgu9Ctqurkzf:224654319) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a22746391333d252a49d7c4964c2562d4bafce71/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/libSynphony/bloom_lib.js#L19)):*
changed to theOneWordCache

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029)*

**Comment by hatton** [comment]
Review status: 2 of 8 files reviewed at latest revision, 16 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 937 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGXjEXiBgkouh_k6VaT:-KGXjEXiBgkouh_k6VaU:-390376592) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/338d306a2d739269d6e25cb8369904b6cbd28e5c/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L937)):*
This comment wants updating now that it isn't recursive.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029)*

**Comment by hatton** [comment]
Just needs one comment update, then we can merge.

**Comment by JohnThomson** [comment]
Review status: 2 of 8 files reviewed at latest revision, 16 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 937 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029#-KGXjEXiBgkouh_k6VaT:-KGXr9uyHB7FQ5zEVK-z:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/338d306a2d739269d6e25cb8369904b6cbd28e5c/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L937)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1029)*

**Pull request merged**
