### PR TITLE
Forget changes menu item and dialog and imp (BL-10013)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564)* status: all files reviewed, 7 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/teamCollection/ForgetChangesDialog.tsx, line 86 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564#-McpnB9v8KR2E_ux70Bw:-McpnB9v8KR2E_ux70Bx:b-q0mt20) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4428661eeeb384269d2fe1147e7747735875b4e/src/BloomBrowserUI/teamCollection/ForgetChangesDialog.tsx#L86)):*
> ```XML
>                 >
>                     Cancel
>                 </BloomButton>
> ```

I think you can use DialogCancelButton here
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 147 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564#-McptVQJ7CrQGI5Z2Gfh:-McptVQJ7CrQGI5Z2Gfi:bhjxggu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4428661eeeb384269d2fe1147e7747735875b4e/src/BloomExe/TeamCollection/TeamCollection.cs#L147)):*
> ```Smalltalk
> 			{
> 				
> 				finalBookName = status.oldName;
> ```

Maybe I'm trying too hard... but I'm just verifying... 
does this oldName always match the repo even if the book was renamed several times?
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 158 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564#-McpsJdY7G4JDarHNyQN:-McpsJdY7G4JDarHNyQO:b-yu9ech) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4428661eeeb384269d2fe1147e7747735875b4e/src/BloomExe/TeamCollection/TeamCollection.cs#L158)):*
> ```
> if (File.Exists(extraBookPath))
> ```
I'm sure I'm just missing something, but I can't figure out what is going on here.

If the idea is simply that we now have all the files in right place but we want to sync the htm file name to the directory name, won't this always exist? Maybe this is just a safety check? But if it fails, didn't something very bad happen?

Should this logic of moving a book to a new folder with a unique name live in BookStorage?
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 168 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564#-Mcprip11adHUEQGMtZ7:-Mcprip283qLJlmKuuwA:b-d7ys2k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4428661eeeb384269d2fe1147e7747735875b4e/src/BloomExe/TeamCollection/TeamCollection.cs#L168)):*
> ```
> Todo
> ```
I guess this is the same todo as the one in TeamCollectionApi?
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 53 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564#-McppY2i76SOf7dcfaPN:-McppY2i76SOf7dcfaPO:b-9co0sa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4428661eeeb384269d2fe1147e7747735875b4e/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L53)):*
> ```
> forgetChanges
> ```
For clarity and to continue the pattern of other endpoints, I think should be something like
`forgetChangesInCurrentBook`
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 283 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564#-Mcpouot4j41YVX6pM81:-Mcpouot4j41YVX6pM82:b1dkj80) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4428661eeeb384269d2fe1147e7747735875b4e/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L283)):*
> ```
> Todo before 5.1
> ```
I'm not sure what this means.
Before it goes to beta?
Is this in a card? How will we not lose it?
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 305 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564#-McppQMqBfgj62a8y4eO:-McppQMqBfgj62a8y4eP:b-wf26ac) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4428661eeeb384269d2fe1147e7747735875b4e/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L305)):*
> ```
> 				NonFatalProblem.Report(ModalIf.All, PassiveIf.All, $"Something went wrong forgetting changes",
> 					_bookSelection?.CurrentSelection?.FolderPath, ex);
> 				request.Failed("forget changes failed");
> ```
This will result in the user being notified twice in addition to the error in the log.
Seems like since we have the error log, we don't want NonFataProblem.Report at all and we should tell the client the api call was successful?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564)* status: 4 of 8 files reviewed, 7 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/teamCollection/ForgetChangesDialog.tsx, line 86 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564#-McpnB9v8KR2E_ux70Bw:-McuGVWvAi1dR2yxdruu:b-103iyp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4428661eeeb384269d2fe1147e7747735875b4e/src/BloomBrowserUI/teamCollection/ForgetChangesDialog.tsx#L86)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think you can use DialogCancelButton here
</blockquote></details>

Well, I could after fixing a bug in it :-)
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 147 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564#-McptVQJ7CrQGI5Z2Gfh:-McuGauAB2nCQBZscS_G:b-3cxcjs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4428661eeeb384269d2fe1147e7747735875b4e/src/BloomExe/TeamCollection/TeamCollection.cs#L147)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Maybe I'm trying too hard... but I'm just verifying... 
does this oldName always match the repo even if the book was renamed several times?
</blockquote></details>

Yes. Unless something is badly wrong. It's specifically kept for the purpose of finding the corresponding repo item. (Well, if you check in, of course, the repo thing gets renamed too, and then oldName is null.)
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 158 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564#-McpsJdY7G4JDarHNyQN:-McuK1hR-dSQLD7VJU2Z:bn2pd4y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4428661eeeb384269d2fe1147e7747735875b4e/src/BloomExe/TeamCollection/TeamCollection.cs#L158)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> if (File.Exists(extraBookPath))
> ```
I'm sure I'm just missing something, but I can't figure out what is going on here.

If the idea is simply that we now have all the files in right place but we want to sync the htm file name to the directory name, won't this always exist? Maybe this is just a safety check? But if it fails, didn't something very bad happen?

Should this logic of moving a book to a new folder with a unique name live in BookStorage?
</blockquote></details>

I added a long comment which may help. This block is not about undoing the rename, but removing an unexpected obstacle in the place we should be moving it TO as we undo the rename.
We could make a method in BookStorage, but there's only one other caller of GetUniqueFolderPath, and it doesn't do a simple rename like this, so the function would only be used once. I'm not sure it's worth it.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 168 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564#-Mcprip11adHUEQGMtZ7:-McuKRjlDLUMFuLApltJ:bb77ufg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4428661eeeb384269d2fe1147e7747735875b4e/src/BloomExe/TeamCollection/TeamCollection.cs#L168)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Todo
> ```
I guess this is the same todo as the one in TeamCollectionApi?
</blockquote></details>

Yes.
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 53 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564#-McppY2i76SOf7dcfaPN:-McuKpSkBtfCVZgAmHLP:b-80h340) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4428661eeeb384269d2fe1147e7747735875b4e/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L53)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> forgetChanges
> ```
For clarity and to continue the pattern of other endpoints, I think should be something like
`forgetChangesInCurrentBook`
</blockquote></details>

Done...except John and I decided SelectedBook is clearer than CurrentBook and are in the process of switching over. So I made the new one follow that pattern.
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 283 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564#-Mcpouot4j41YVX6pM81:-McuLiT6B_EkPSX7MrbH:b-vf4x8s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4428661eeeb384269d2fe1147e7747735875b4e/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L283)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Todo before 5.1
> ```
I'm not sure what this means.
Before it goes to beta?
Is this in a card? How will we not lose it?
</blockquote></details>

John has been working on a new Collection Tab in React, which he says is a necessary part of 5.1. I'm in the process of taking it over. Seemed a waste to try to handle these updates in the code that is going away. The new ReactCollectionTab has its own Todo list, for now separate from YouTrack. I captured this there.
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 305 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564#-McppQMqBfgj62a8y4eO:-McuMnuyCboHU0X2800H:bn8ibj1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4428661eeeb384269d2fe1147e7747735875b4e/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L305)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> 				NonFatalProblem.Report(ModalIf.All, PassiveIf.All, $"Something went wrong forgetting changes",
> 					_bookSelection?.CurrentSelection?.FolderPath, ex);
> 				request.Failed("forget changes failed");
> ```
This will result in the user being notified twice in addition to the error in the log.
Seems like since we have the error log, we don't want NonFataProblem.Report at all and we should tell the client the api call was successful?
</blockquote></details>

The user won't usually see the log. Seems like we need something to let him know something went wrong, even though it's hard to see what could.
I don't much like pretending something worked if it didn't, so I kept the Failed, but handled it in the post() call so we won't get another error from JS.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 158 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564#-McpsJdY7G4JDarHNyQN:-Md3Oj6J0bw-bV4oPJKr:bsvjil6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4428661eeeb384269d2fe1147e7747735875b4e/src/BloomExe/TeamCollection/TeamCollection.cs#L158)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I added a long comment which may help. This block is not about undoing the rename, but removing an unexpected obstacle in the place we should be moving it TO as we undo the rename.
We could make a method in BookStorage, but there's only one other caller of GetUniqueFolderPath, and it doesn't do a simple rename like this, so the function would only be used once. I'm not sure it's worth it.
</blockquote></details>

Yeah, I understood the overall logic. Just not this one line I commented on (checking if the htm file exists).
We should probably discuss.

And it does seem worth it to me to move the logic. That would keep GetUniqueFolderPath private and provides the logic -- which is the type of thing BookStorage should know how to do, not TeamCollection, nor even necessarily FolderTeamCollection -- in a reusable form for the future.

But this also makes me realize we need to move all this file IO stuff to FolderTC if possible.
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 305 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564#-McppQMqBfgj62a8y4eO:-Md3NYGJAQmnbyEiHfkn:bg6hunm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4428661eeeb384269d2fe1147e7747735875b4e/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L305)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

The user won't usually see the log. Seems like we need something to let him know something went wrong, even though it's hard to see what could.
I don't much like pretending something worked if it didn't, so I kept the Failed, but handled it in the post() call so we won't get another error from JS.
</blockquote></details>

Why won't the user see the error in the log? I'm referring to the TC log:
`log.WriteMessage(MessageAndMilestoneType.Error, msgId, msgEnglish, _bookSelection?.CurrentSelection?.FolderPath, ex.Message);`

I suppose adding a NonFatalProblem.Report to that could be beneficial... Hard to say. But I guess if they submit the error we might be able to investigate and fix.

**Review by JohnThomson — COMMENTED** [review]
While making other fixes, found I had not handled the case of a new local book, which John and I agreed should result in the command being disabled.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564#-:-Md3nFWe2TIlETX6lChC:b6dpfiw)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 158 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564#-McpsJdY7G4JDarHNyQN:-Md3n5gWC8_WVb1dK-NL:b-y2qe23) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4428661eeeb384269d2fe1147e7747735875b4e/src/BloomExe/TeamCollection/TeamCollection.cs#L158)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Yeah, I understood the overall logic. Just not this one line I commented on (checking if the htm file exists).
We should probably discuss.

And it does seem worth it to me to move the logic. That would keep GetUniqueFolderPath private and provides the logic -- which is the type of thing BookStorage should know how to do, not TeamCollection, nor even necessarily FolderTeamCollection -- in a reusable form for the future.

But this also makes me realize we need to move all this file IO stuff to FolderTC if possible.
</blockquote></details>

OK, I moved the logic, and added a comment about checking that the HTM file is where we expect.
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 305 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564#-McppQMqBfgj62a8y4eO:-Md3_CNwD7lyYCPan2ru:b-g57gq0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4428661eeeb384269d2fe1147e7747735875b4e/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L305)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Why won't the user see the error in the log? I'm referring to the TC log:
`log.WriteMessage(MessageAndMilestoneType.Error, msgId, msgEnglish, _bookSelection?.CurrentSelection?.FolderPath, ex.Message);`

I suppose adding a NonFatalProblem.Report to that could be beneficial... Hard to say. But I guess if they submit the error we might be able to investigate and fix.
</blockquote></details>

You're absolutely right. Somehow I was only looking at the previous line of low-level logging.
I'm not sure that anything here will cause the TC dialog to come up...probably just the TC icon changes state. That might not be enough. However, I don't much expect this ever to happen.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 158 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564#-McpsJdY7G4JDarHNyQN:-Md3wD07D8F_uHKukOsB:bextgao) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4428661eeeb384269d2fe1147e7747735875b4e/src/BloomExe/TeamCollection/TeamCollection.cs#L158)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

OK, I moved the logic, and added a comment about checking that the HTM file is where we expect.
</blockquote></details>

Sorry for making complex, multi-part comments.

I think you missed the bit about moving the general IO from here to FolderTeamCollection.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 158 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564#-McpsJdY7G4JDarHNyQN:-MdHk_kqBdstG6qY-Uc7:b-hhlp2a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4428661eeeb384269d2fe1147e7747735875b4e/src/BloomExe/TeamCollection/TeamCollection.cs#L158)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry for making complex, multi-part comments.

I think you missed the bit about moving the general IO from here to FolderTeamCollection.
</blockquote></details>

Responded to that bit on Flowdock. I don't think we want to. FolderTeamCollection is not supposed to capture all the File IO, it's supposed to capture all the IO to the REPO. File IO to the local collection folder belongs in TeamCollection, since it won't change if we someday have another way to store the repo data.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 158 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4564#-McpsJdY7G4JDarHNyQN:-MdI671pEjiWgkDcvG8u:b-f683vv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4428661eeeb384269d2fe1147e7747735875b4e/src/BloomExe/TeamCollection/TeamCollection.cs#L158)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Responded to that bit on Flowdock. I don't think we want to. FolderTeamCollection is not supposed to capture all the File IO, it's supposed to capture all the IO to the REPO. File IO to the local collection folder belongs in TeamCollection, since it won't change if we someday have another way to store the repo data.
</blockquote></details>

Yeah, sorry; I feel like I may have made that mistake before.

**Pull request merged**
