### PR TITLE
Don't center text in overflowing bubble text boxes (BL-13606)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This bug is similar to one fixed earlier for normal text boxes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6674)

### CODE REVIEW

**Comment by StephenMcConnel** [comment]
This fix may be safe for cherry-picking back to 6.0.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6674)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/content/bookLayout/bubble.less` line 254 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6674#-O7ZQJNa9RhSvU1yaTVs:-O7ZQJNa9RhSvU1yaTVt:b-39xkou) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f69052f401ced6e6f8d61454f06f500b1ec146b8/src/content/bookLayout/bubble.less#L254)):*
> ```Less
>     // (Of course, there could be other ways of specifying transparent. But AFIK Bloom has never used them.)
>     // (Thus, if it has backgroundColors and isn't explicitly transparent the centering applies.)
>     .bloom-textOverPicture[data-bubble]:not([data-bubble*="`style`:`none`"]):not(:has(.overflow)),
> ```

Since there's a fairly detailed comment here, it might be helpful to include an explanation of why we don't want to do it for overflowing boxes.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6674)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/content/bookLayout/bubble.less` line 254 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6674#-O7ZQJNa9RhSvU1yaTVs:-O7Za82p6E0x61g3PDX0:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f69052f401ced6e6f8d61454f06f500b1ec146b8/src/content/bookLayout/bubble.less#L254)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Since there's a fairly detailed comment here, it might be helpful to include an explanation of why we don't want to do it for overflowing boxes.
</blockquote></details>

Done.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6674)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
