### PR TITLE
BL-9800 Fix crash when clicking Report

### PR DESCRIPTION
**Pull request by gmartin7**
* Report button in TC Activity sync progress dialog

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4368)

### CODE REVIEW

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4368)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 444 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4368#-MYLp0PA1X88WpTG5EI1:-MYLp0PA1X88WpTG5EI2:bek841f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a9c0c3ca308277184d689321cbbdd995b9b757a6/src/BloomExe/web/controllers/ProblemReportApi.cs#L444)):*
> ```Smalltalk
> 				try
> 				{
> 					StartupScreenManager.CloseSplashScreen(); // we have one of these above, do we need this one?
> ```

JT says this one inside of the SafeInvoke is better than the other one, because this has to be run on the UI thread... So I left them both for now.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4368)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 415 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4368#-MYM4CaJ970zYS7tlSvm:-MYM4CaJ970zYS7tlSvn:b-hu832h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a9c0c3ca308277184d689321cbbdd995b9b757a6/src/BloomExe/web/controllers/ProblemReportApi.cs#L415)):*
> ```Smalltalk
> 			if (ReactDialog.CurrentOpenModal != null)
> 			{
> 				ReactDialog.CloseCurrentModal();
> ```

This one limitation seems to have no end of bugs. @johnthomson, could CurrenOpen somehow  become a stack of dialogs, instead of a single variable?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4368)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 444 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4368#-MYLp0PA1X88WpTG5EI1:-MYMDeZo9ePxgY8QMH2X:b62k581) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a9c0c3ca308277184d689321cbbdd995b9b757a6/src/BloomExe/web/controllers/ProblemReportApi.cs#L444)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

JT says this one inside of the SafeInvoke is better than the other one, because this has to be run on the UI thread... So I left them both for now.
</blockquote></details>

Let's remove or modify the new comment appropriately, please.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4368)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 415 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4368#-MYM4CaJ970zYS7tlSvm:-MYMIks--23XnzWLGWBw:b-em27rg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a9c0c3ca308277184d689321cbbdd995b9b757a6/src/BloomExe/web/controllers/ProblemReportApi.cs#L415)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This one limitation seems to have no end of bugs. @johnthomson, could CurrenOpen somehow  become a stack of dialogs, instead of a single variable?
</blockquote></details>

I could work toward that if we wish...
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 444 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4368#-MYLp0PA1X88WpTG5EI1:-MYMIPwC2TTvsPDuuME7:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a9c0c3ca308277184d689321cbbdd995b9b757a6/src/BloomExe/web/controllers/ProblemReportApi.cs#L444)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's remove or modify the new comment appropriately, please.
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4368)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4368)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 415 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4368#-MYM4CaJ970zYS7tlSvm:-MYQpc177q38Boc5UBgy:bmqa0rs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a9c0c3ca308277184d689321cbbdd995b9b757a6/src/BloomExe/web/controllers/ProblemReportApi.cs#L415)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I could work toward that if we wish...
</blockquote></details>

Done. And this way is much simpler too.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4368)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by andrew-polk — APPROVED** [review]
> Dismissed @hatton from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4368)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Comment by hatton** [comment]
The only actual user of `CurrentOpenModal` is `HandleReloadCollection`. It would seem to me that the current use is wrong; that method is interested in closing *all* dialogs, I think? If so, `CurrentOpenModal` should go away entirely and a public method for closing all dialogs added.

**Review by JohnThomson — COMMENTED** [review]
CurrentOpenModal could become private with such a method, but it is used internally.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4368#-:-MYRK9RA42YyI-xaKY-8:b-yp8hja)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by hatton** [comment]
It is literally used, obviously. But I see zero purpose in it.

**Pull request merged**
