### PR TITLE
BL-12779 Minimal Check In All

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6163)

### CODE REVIEW

**Review by StephenMcConnel — APPROVED** [review]
:lgtm: although maybe Andrew should scan over it as well.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6163#-:-NhTlIEI3KeFLiABzd2Y:b-yb375r)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/BloomExe/TeamCollection/TeamCollectionApi.cs` line 690 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6163#-NhTjzbu5SPZ1nuXe_Gl:-NhTjzbu5SPZ1nuXe_Gm:b-e97el1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/32b1609971cf4872e29f005cde8ee54f64c6fbc9/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L690)):*
> ```Smalltalk
>                     // comment, and NOT see the pending comment as if it was their own if they check out.
> 
>                     var book = _collectionModel.GetBookFromBookInfo(bookInfo);
> ```

This is out of scope for this issue, but could BookHistory be rewritten to use BookInfo objects instead of Book objects?  A quick scan shows that book.ID, book.FolderPath, and book.NameBestForUserDisplay are the only items used from the Book object, and the first two should be available in the BookInfo object.  I suppose it depends on how vital the exact book name string is.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6163)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[`src/BloomExe/TeamCollection/TeamCollectionApi.cs` line 85 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6163#-NhTq0WuCV-RavuGYLDz:-NhTq0Wv01CfABZkcVmH:b-6x5l99) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/32b1609971cf4872e29f005cde8ee54f64c6fbc9/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L85)):*
> ```Smalltalk
> 
> 		private bool HandleLogImportant(ApiRequest arg)
>         {
> ```

Somehow a bunch (but not all) of the tabs in this file got changed to spaces.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6163)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @StephenMcConnel)

___
*[`src/BloomExe/TeamCollection/TeamCollectionApi.cs` line 85 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6163#-NhTq0WuCV-RavuGYLDz:-NhYbzTt-xG0_LCh_-uD:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/32b1609971cf4872e29f005cde8ee54f64c6fbc9/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L85)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Somehow a bunch (but not all) of the tabs in this file got changed to spaces.
</blockquote></details>

Done.
___
*[`src/BloomExe/TeamCollection/TeamCollectionApi.cs` line 690 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6163#-NhTjzbu5SPZ1nuXe_Gl:-NhYc4o_EukgMjczEw19:btg6qj0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/32b1609971cf4872e29f005cde8ee54f64c6fbc9/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L690)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

This is out of scope for this issue, but could BookHistory be rewritten to use BookInfo objects instead of Book objects?  A quick scan shows that book.ID, book.FolderPath, and book.NameBestForUserDisplay are the only items used from the Book object, and the first two should be available in the BookInfo object.  I suppose it depends on how vital the exact book name string is.
</blockquote></details>

Right, I'm actually compromising ux a bit here by not getting the `NameBestForUserDisplay`, and didn't want to make the normal case also do that.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6163)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Pull request merged**
