### PR TITLE
BL-5404 Music Toolbox panel

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2068)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/backgroundAudio/backgroundAudio.less, line 1 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2068#-L3-TQ3kbO8i2aIs9q0Y:-L3-TQ3kbO8i2aIs9q0Z:b-qzjwhu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/745317764afdfffbe037cc60ce7d108e9ff1aafa/src/BloomBrowserUI/bookEdit/toolbox/backgroundAudio/backgroundAudio.less#L1)):*
> ```Less
> @import "../../../templates/common-mixins.less";
> ```

The indentation in this file seems inconsistent.

---

*[src/BloomBrowserUI/bookEdit/toolbox/backgroundAudio/backgroundAudio.ts, line 33 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2068#-L3-Tv-O7vkprKUBQHx3:-L3-Tv-O7vkprKUBQHx4:bw6m4jz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/745317764afdfffbe037cc60ce7d108e9ff1aafa/src/BloomBrowserUI/bookEdit/toolbox/backgroundAudio/backgroundAudio.ts#L33)):*
> ```XML
>     }
>     updateMarkup() {
>         // This isn't exactly updating the markup, but it needs to happen when we switch pages,
> ```

Is this going to get called whenever the user types a key?

---

*[src/BloomBrowserUI/bookEdit/toolbox/backgroundAudio/backgroundAudio.ts, line 56 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2068#-L3-UDTcJ8Av4zkkTP7x:-L3-UDTcJ8Av4zkkTP7y:b-yk2x6z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/745317764afdfffbe037cc60ce7d108e9ff1aafa/src/BloomBrowserUI/bookEdit/toolbox/backgroundAudio/backgroundAudio.ts#L56)):*
> continueMusic

Everywhere else, you refer to it as background audio. Is there a reason to change here? (Also several other instances below...)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2068)*

**Comment by JohnThomson** [comment]
Review status: 15 of 17 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/backgroundAudio/backgroundAudio.less, line 1 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2068#-L3-TQ3kbO8i2aIs9q0Y:-L3-iq_3xWR9dYdSq29P:bkkd4c4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/745317764afdfffbe037cc60ce7d108e9ff1aafa/src/BloomBrowserUI/bookEdit/toolbox/backgroundAudio/backgroundAudio.less#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The indentation in this file seems inconsistent.
</blockquote></details>

Fixed, I believe.

---

*[src/BloomBrowserUI/bookEdit/toolbox/backgroundAudio/backgroundAudio.ts, line 33 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2068#-L3-Tv-O7vkprKUBQHx3:-L3-l3ggSOUSzKERYcoB:b-aq0bmp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/745317764afdfffbe037cc60ce7d108e9ff1aafa/src/BloomBrowserUI/bookEdit/toolbox/backgroundAudio/backgroundAudio.ts#L33)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is this going to get called whenever the user types a key?
</blockquote></details>

Technically, whenever they pause while typing. I added a comment. We don't have a "startup plus switching pages" hook, probably because when we developed the toolbox, we still reloaded everything on page switch, so anything like that could just go in showTool().

---

*[src/BloomBrowserUI/bookEdit/toolbox/backgroundAudio/backgroundAudio.ts, line 56 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2068#-L3-UDTcJ8Av4zkkTP7x:-L3-hnqL4SGjmpqdiwgN:bcdkiuw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/745317764afdfffbe037cc60ce7d108e9ff1aafa/src/BloomBrowserUI/bookEdit/toolbox/backgroundAudio/backgroundAudio.ts#L56)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> continueMusic

Everywhere else, you refer to it as background audio. Is there a reason to change here? (Also several other instances below...)
</blockquote></details>

I think of the feature as background audio and mostly use that terminology. However, per JohnH's design, the actual radio buttons are labeled "No music", "Continue music" and "New music". It struck me as confusing to give a button with text "continue music" a value "continueBgAudio", but of course, if I don't, there has to be a name change somewhere. My compromise was to use 'music' only for things most directly connected to one of the three buttons that actually mentions music. I'm open to changing it, but will wait to see if you think this rationale makes sense (and if I did it consistently).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2068)*

**Comment by hatton** [comment]
Review status: 15 of 17 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/backgroundAudio/backgroundAudio.ts, line 56 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2068#-L3-UDTcJ8Av4zkkTP7x:-L3-vSYOyk3zBvpQS6qC:bduxusg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/745317764afdfffbe037cc60ce7d108e9ff1aafa/src/BloomBrowserUI/bookEdit/toolbox/backgroundAudio/backgroundAudio.ts#L56)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think of the feature as background audio and mostly use that terminology. However, per JohnH's design, the actual radio buttons are labeled "No music", "Continue music" and "New music". It struck me as confusing to give a button with text "continue music" a value "continueBgAudio", but of course, if I don't, there has to be a name change somewhere. My compromise was to use 'music' only for things most directly connected to one of the three buttons that actually mentions music. I'm open to changing it, but will wait to see if you think this rationale makes sense (and if I did it consistently).
</blockquote></details>

How about Music throughout, including file names?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2068)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/toolbox/backgroundAudio/backgroundAudio.ts, line 56 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2068#-L3-UDTcJ8Av4zkkTP7x:-L3-yvkEKa-ydWo9dONH:bfyva6e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/745317764afdfffbe037cc60ce7d108e9ff1aafa/src/BloomBrowserUI/bookEdit/toolbox/backgroundAudio/backgroundAudio.ts#L56)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

How about Music throughout, including file names?
</blockquote></details>

I don't care enough to dictate an opinion on naming. But I will point out that IMS uses this for sound effects, too, such as the lions roaring in the story of Daniel.
I didn't realize the UI was using "Music." I'm okay with it as is.
And since I hear a lot of this is getting reworked into React, it probably isn't worth changing now (except maybe that json id?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2068#-:-L3-zNxJRUSiZDvbtg1J:bnfp4nl)*

**Comment by JohnThomson** [comment]
Review status: 1 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/toolbox/music/music.ts, line 56 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2068#-L3-UDTcJ8Av4zkkTP7x:-L34kspDxAeNXfZHfh96:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/745317764afdfffbe037cc60ce7d108e9ff1aafa/src/BloomBrowserUI/bookEdit/toolbox/music/music.ts#L56)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't care enough to dictate an opinion on naming. But I will point out that IMS uses this for sound effects, too, such as the lions roaring in the story of Daniel.
I didn't realize the UI was using "Music." I'm okay with it as is.
And since I hear a lot of this is getting reworked into React, it probably isn't worth changing now (except maybe that json id?)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2068)*

**Pull request merged**
