### PR TITLE
BL-6612 Clean up CkEditor markup on save page

### PR DESCRIPTION
**Pull request by JohnThomson**
Also in one sample shell

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2874)

### CODE REVIEW

**Review by StephenMcConnel — CHANGES_REQUESTED** [review]
:lgtm:  with one totally optional suggestion.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2874#-:-LQePiqa45eq8Le7SrJr:b77hoqk)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomTests/Book/HtmlDomTests.cs, line 56 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2874#-LQeOq2L9eT_ggFu07Oj:-LQeOq2L9eT_ggFu07Ok:bjs05l5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/60de88c4a50394fdc3f83096e43107d7e6e670d3/src/BloomTests/Book/HtmlDomTests.cs#L56)):*
> ```Smalltalk
> 			assertThatResult.HasSpecifiedNumberOfMatchesForXpath("//div[@id='whole' and @class='']", 1);
> 			assertThatResult.HasSpecifiedNumberOfMatchesForXpath("//div[@id='none' and @class='bloom-content1']", 1);
> 		}
> ```

What about one final test for counting matches of "//div[contains(@class, 'cke_')]" (if that xpath works), possibly with testing before and after the relevant method call.  But what you have does demonstrate that the method works.  (I just had to make some comment on your code...)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2874)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomTests/Book/HtmlDomTests.cs, line 56 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2874#-LQeOq2L9eT_ggFu07Oj:-LQfKQZO-dVbehbK7lWF:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/60de88c4a50394fdc3f83096e43107d7e6e670d3/src/BloomTests/Book/HtmlDomTests.cs#L56)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

What about one final test for counting matches of "//div[contains(@class, 'cke_')]" (if that xpath works), possibly with testing before and after the relevant method call.  But what you have does demonstrate that the method works.  (I just had to make some comment on your code...)
</blockquote></details>

Done.

**Review by StephenMcConnel — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2874)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by StephenMcConnel — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2874#-:-LQgAsEw4NgfF_hvc-fJ:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
