### PR TITLE
Add Border Style and Background color to text box properties (BL-4238)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1485)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Couple of things to think about, probably not very important.
In the spirit of our discussion this morning...any reason routines like changeBorder and initializeBoderStyle can't have unit tests?

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 194 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1485#-Kd2iYOVk-q7YTqTUMvd:-Kd2iYOVk-q7YTqTUMve:b-ax4djv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/450b68f79ed6b988850887d0484979070e04fdb4/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L194)):*
> ```XML
>     }
> 
>     initializeBorderStyle() {
> ```

There's a chunk of deleted code in a4e38d34b0076a0b7bb32264bc3fb8668df25db1 (3 Feb 2017) that attempted to choose one of these options based on current style values. I'm not sure whether it's better than this or not. It's less dependent on the current state of things being EXACTLY one of the options changeBorderStyle creates. Whether that's really useful I'm not sure. It might, for example, make a better guess if what's actually in the book is some other option from a later Bloom. Or if it's something set up by a really smart user using a custom CSS file. But those are way-out edge cases. (Similarly, that code interprets any background other than transparent as 'grey' :-).)

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 241 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1485#-Kd2lPdzUnT-xl2ub5UC:-Kd2lPdzUnT-xl2ub5UD:bjn3w5b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/450b68f79ed6b988850887d0484979070e04fdb4/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L241)):*
> ```XML
>             style = style + 'border-radius:10px;';
>             style = style + 'box-sizing:border-box;';
>         }
> ```

The old code forces it to no border if that button is selected. That was useful for a non-normal style which might need to override a border specified by normal on an outer div. It probably isn't here. (Similarly I think the old code will force no background for that option.) But I thought it was worth asking about. Can you imagine a case where something has an inherited border and the user tries to turn it off with this and is annoyed to fail?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1485#-:-Kd2ljuhXcMw7uqomdUy:b-9id3ou)*

**Comment by JohnThomson** [comment]
Given that another PR depends on it, it MIGHT make sense to attach the unit-test task to BL-4269. I already did that with one PR I thought urgent.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1485#-:-Kd2mPVdvVm80CVyZGHj:b28txjl)*

**Comment by andrew-polk** [comment]
I'm actually thinking now that the next change is so intertwined with this one that they really should be reviewed together. I will try to make some improvements based on your comments, then push the next feature in.

Would you rather I keep this PR open and add to it? Or create a new one? There are up- and down-sides for each, I think.

---

Review status: 11 of 15 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1485#-:-Kd6AzSa1YLcjc7RP5oA:bi32e06)*

**Comment by JohnThomson** [comment]
Whatever you think is clearer. Will it make more sense to look at the new commit separately, or to look at the complete change from the current code?

---

Review status: 11 of 15 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1485#-:-Kd6WDM2bX7TFT6u-4if:b9szzjj)*

**Comment by andrew-polk** [comment]
It looks like things are already a bit confused on this one after rebasing on your changes. Plus, I made some significant changes, so I'm going to close this PR and create another one. 
Sorry that means re-reviewing some parts.

---

Review status: 11 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 194 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1485#-Kd2iYOVk-q7YTqTUMvd:-Kd7ft8hymLz9DYw_Vfa:bnbjr6i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/450b68f79ed6b988850887d0484979070e04fdb4/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L194)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

There's a chunk of deleted code in a4e38d34b0076a0b7bb32264bc3fb8668df25db1 (3 Feb 2017) that attempted to choose one of these options based on current style values. I'm not sure whether it's better than this or not. It's less dependent on the current state of things being EXACTLY one of the options changeBorderStyle creates. Whether that's really useful I'm not sure. It might, for example, make a better guess if what's actually in the book is some other option from a later Bloom. Or if it's something set up by a really smart user using a custom CSS file. But those are way-out edge cases. (Similarly, that code interprets any background other than transparent as 'grey' :-).)
</blockquote></details>

I decided to make it all class-based. So we either have the class we added or we don't.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 241 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1485#-Kd2lPdzUnT-xl2ub5UC:-Kd7gIUlXojJI_0ai0Yl:b-fh9hgt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/450b68f79ed6b988850887d0484979070e04fdb4/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L241)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

The old code forces it to no border if that button is selected. That was useful for a non-normal style which might need to override a border specified by normal on an outer div. It probably isn't here. (Similarly I think the old code will force no background for that option.) But I thought it was worth asking about. Can you imagine a case where something has an inherited border and the user tries to turn it off with this and is annoyed to fail?
</blockquote></details>

With the class system I implemented in the new code, we could always add !important if we discover that becomes necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1485#-:-Kd7fdC_fObbkgi-a1Ok:b-4idknu)*

**Comment by andrew-polk** [comment]
Going to close this in favor of a clean PR which will address both BL-4238 and BL-4239

**Comment by JohnThomson** [comment]
Review status: 11 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 194 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1485#-Kd2iYOVk-q7YTqTUMvd:-KdBHyYqHM5q1JZdpeYj:bbx1mw8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/450b68f79ed6b988850887d0484979070e04fdb4/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L194)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I decided to make it all class-based. So we either have the class we added or we don't.
</blockquote></details>

That's a neat solution. Wouldn't work in the other dialog, since these properties are supposed to become part of the definition of a style, but for this case I think it does.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 241 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1485#-Kd2lPdzUnT-xl2ub5UC:-KdBIKJY5bAioO9knE3x:b-75e900) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/450b68f79ed6b988850887d0484979070e04fdb4/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L241)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

With the class system I implemented in the new code, we could always add !important if we discover that becomes necessary.
</blockquote></details>

It's not so much having it be important, as the difference between border: none and just saying nothing about borders.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1485)*

**Comment by andrew-polk** [comment]
Review status: 11 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 241 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1485#-Kd2lPdzUnT-xl2ub5UC:-KdBKmw6MYfSP98RE_CV:bu6i1k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/450b68f79ed6b988850887d0484979070e04fdb4/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L241)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's not so much having it be important, as the difference between border: none and just saying nothing about borders.
</blockquote></details>

I do set each side of the border to none if there is no border, so we do have that now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1485)*

**Pull request closed without merging**
