### PR TITLE
Clean up CompressBookForDevice (BL-4809)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1784)

### CODE REVIEW

**Comment by JohnThomson** [comment]
:lgtm: as long as the one question I raised doesn't turn out to be a problem.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/BookCompressor.cs, line 31 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1784#-Kr1819tGjQs6_GUC1CT:-Kr1819tGjQs6_GUC1CU:bm6e585) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e89b8dc977f47b0f9d521d939eab4e91f404b0a6/src/BloomExe/Book/BookCompressor.cs#L31)):*
> ```Smalltalk
> 			{
> 				// In case we have any new settings since the last time we were in the Edit tab (BL-3881)
> 				book.BringBookUpToDate(new NullProgress());
> ```

The other thing this MIGHT accomplish is inserting current xmatter and therefore dealing with branding images. I _think_ this is done when you select a book, but it's worth checking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1784#-:-Kr18IHFCgBOGhPiVAQ3:b-liqyrw)*

**Comment by andrew-polk** [comment]
*[src/BloomExe/Book/BookCompressor.cs, line 31 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1784#-Kr1819tGjQs6_GUC1CT:-Kr1PLcvEQzdH_HH4Wbf:b-skjmmz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e89b8dc977f47b0f9d521d939eab4e91f404b0a6/src/BloomExe/Book/BookCompressor.cs#L31)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

The other thing this MIGHT accomplish is inserting current xmatter and therefore dealing with branding images. I _think_ this is done when you select a book, but it's worth checking.
</blockquote></details>

Good thought. We do still need to ensure BringBookUpToDate is called, but PublishModel.DoAnyNeededAudioCompression() calls it if needed, and that is called before loading the AndroidView. I enhanced the comment in PublishView to reflect this.
Do you think that is sufficient? I suppose some future caller could call this method without going through that path...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1784)*

**Comment by andrew-polk** [comment]
Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomTests/Book/BookCompressorTests.cs, line 45 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1784#-Kr1ZjW2Kh3ElbhCZT0H:-Kr1ZjW2Kh3ElbhCZT0I:b23artg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e89b8dc977f47b0f9d521d939eab4e91f404b0a6/src/BloomTests/Book/BookCompressorTests.cs#L45)):*
> ```Smalltalk
> 			var expectedFiles = Directory.GetFiles(testBook.FolderPath).ToList();
> 			expectedFiles.Add("license.png"); // Something in the compression process adds this.
> 			expectedFiles.Add("back-cover-outside.svg"); // Something in the compression process adds this.
> ```

These are now *really* added by calling BringBookUpToDate on the test book.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1784)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/BookCompressor.cs, line 31 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1784#-Kr1819tGjQs6_GUC1CT:-Kr1_lildCOLQBFoINjG:bgcj82r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e89b8dc977f47b0f9d521d939eab4e91f404b0a6/src/BloomExe/Book/BookCompressor.cs#L31)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Good thought. We do still need to ensure BringBookUpToDate is called, but PublishModel.DoAnyNeededAudioCompression() calls it if needed, and that is called before loading the AndroidView. I enhanced the comment in PublishView to reflect this.
Do you think that is sufficient? I suppose some future caller could call this method without going through that path...
</blockquote></details>

I think that's sufficient. (Especially since I'm pretty sure it's already being done also by just selecting the book.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1784#-:-Kr1a3hworRjhRXkiIvJ:bnfp4nl)*

**Pull request merged**
