### PR TITLE
BL-6208 Make Daisy share main epubmaker

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2569)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Please do NOT merge this yet...there's still a bug, where sometimes things freeze up in the BL-6208 scenario.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
I think this lgtm (other than a few comments/questions), but I would be more comfortable if @hatton had a chance to look.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2569#-:-LH3zFbu35wEgwN2kBgS:bxiczt5)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Publish/Epub/PublishEpubApi.cs, line 31 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2569#-LH3xa3H9VV_fB2UBqIU:-LH3xa3H9VV_fB2UBqIV:bixxe2z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/adcb292d24239246bcb2d89a9272bac4a3fe3874/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L31)):*
> ```Smalltalk
> 		private CollectionSettings _collectionSettings;
> 		private BloomWebSocketServer _webSocketServer;
> 		private readonly WebSocketProgress _standardProgress;
> ```

These two WebSocketProgress members either need better names or comment explaining them.
___
*[src/BloomExe/web/controllers/AccessibilityCheckApi.cs, line 115 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2569#-LH3wbZOA-NkmyGYxAjo:-LH3wbZOA-NkmyGYxAjp:b-1h42bi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/684f102d2bfbccf4bbbcd0ffe10bc8c5f435afc5/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L115)):*
> ```Smalltalk
> 				true // <-- ui thread needed to make epub for some reason.
> 					 // This messes with our ability to make progress show up.
> 					 // Card for fixing the epub maker is BL-6122 
> ```

Does this handle BL-6122 completely? We'll need to do something on that card (at least a comment) when this is merged, right?
___
*[src/BloomExe/web/controllers/AccessibilityCheckApi.cs, line 116 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2569#-LH3wHK-7ZzrHk7i1F35:-LH3wHK-7ZzrHk7i1F36:b-3uz7pk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/adcb292d24239246bcb2d89a9272bac4a3fe3874/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L116)):*
> ```Smalltalk
> 			//enhance: this might have to become async to work on large books on slow computers
> 			server.RegisterEndpointHandler(kApiUrlPart + "aceByDaisyReportUrl", request => { MakeAceByDaisyReport(request); },
> 				false 
> ```

trailing space here (if you're making other changes)

**Review by JohnThomson — COMMENTED** [review]
It's now ready to merge AFAIK, but I agree, JohnH's input would be welcome.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2569#-:-LH40vd5DKIkhp_ztXG9:bwbblzr)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomExe/Publish/Epub/PublishEpubApi.cs, line 31 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2569#-LH3xa3H9VV_fB2UBqIU:-LH4-cGl8on9f9shsMxv:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/adcb292d24239246bcb2d89a9272bac4a3fe3874/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L31)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

These two WebSocketProgress members either need better names or comment explaining them.
</blockquote></details>

Done.
___
*[src/BloomExe/web/controllers/AccessibilityCheckApi.cs, line 115 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2569#-LH3wbZOA-NkmyGYxAjo:-LH40G0yECqnYAzXNHAr:ba8k1ua) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/684f102d2bfbccf4bbbcd0ffe10bc8c5f435afc5/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L115)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Does this handle BL-6122 completely? We'll need to do something on that card (at least a comment) when this is merged, right?
</blockquote></details>

I don't think so. It was an error initially to require this whole task to run on the UI thread; EpubMaker is already coded to use Invoke for those parts of itself that need to be, and that's what BL-6122 is about: making that unnecessary. So this change does NOT solve it, not even partially, that I can see.
___
*[src/BloomExe/web/controllers/AccessibilityCheckApi.cs, line 116 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2569#-LH3wHK-7ZzrHk7i1F35:-LH4-sre-vmncvoU4mUT:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/adcb292d24239246bcb2d89a9272bac4a3fe3874/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L116)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

trailing space here (if you're making other changes)
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2569)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/BloomExe/web/controllers/AccessibilityCheckApi.cs, line 116 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2569#-LH3wHK-7ZzrHk7i1F35:-LH42sKz5B5I6C4EiULI:bs63j24) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/adcb292d24239246bcb2d89a9272bac4a3fe3874/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L116)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Somehow, this change didn't make it. No big deal, but if you're inclined, you could fix this and the typo in the new comment at the top of PublishEpubApi at the same time (socked => socket).

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2569)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @andrew-polk)

___
*[src/BloomExe/web/controllers/AccessibilityCheckApi.cs, line 116 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2569#-LH3wHK-7ZzrHk7i1F35:-LH45vR50akS0dN_vRG6:bb6un1j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/adcb292d24239246bcb2d89a9272bac4a3fe3874/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L116)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Somehow, this change didn't make it. No big deal, but if you're inclined, you could fix this and the typo in the new comment at the top of PublishEpubApi at the same time (socked => socket).
</blockquote></details>

Done

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2569)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/BloomExe/web/controllers/AccessibilityCheckApi.cs, line 116 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2569#-LH3wHK-7ZzrHk7i1F35:-LH463F39LnUD6w05rJM:b-ucfkn4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/adcb292d24239246bcb2d89a9272bac4a3fe3874/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L116)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Thanks.

**Review by andrew-polk — APPROVED** [review]

**Pull request merged**
