### PR TITLE
Several small improvements

### PR DESCRIPTION
**Pull request by JohnThomson**
May be helpful to look at individual commits separately

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6572)

### CODE REVIEW

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6572)* status: 0 of 17 files reviewed, 2 unresolved discussions

___
*[`src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityRuntime.ts` line 904 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6572#-O2-s-Zq3rm8ljTV2_t6:-O2-s-Zq3rm8ljTV2_t7:b-13faug) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/362b434efa66f585f071c3d01c215c189154c4bb/src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityRuntime.ts#L904)):*
> ```XML
> }
> 
> export const doShowAnswersInTargets = (showNow: boolean, page: HTMLElement) => {
> ```

This group of functions was moved from dragActivityTool, not changed significantly.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityRuntime.ts` line 959 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6572#-O2-sAWr2LN3ZKvPihbv:-O2-sAWr2LN3ZKvPihbw:b-fqv5vv) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/362b434efa66f585f071c3d01c215c189154c4bb/src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityRuntime.ts#L959)):*
> ```XML
>         return undefined;
>     }
>     return draggable.ownerDocument.querySelector(
> ```

The one change moving here was to use draggable.ownerDocument instead of getPage()

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6572)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 111 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6572#-O20CjjA96VGZldcjVeD:-O20CjjA96VGZldcjVeE:b-9ja3j2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/362b434efa66f585f071c3d01c215c189154c4bb/DistFiles/localization/en/BloomMediumPriority.xlf#L111)):*
> ```XML
>       </trans-unit>
>       <trans-unit id="EditTab.Toolbox.DragActivity.PartOfRightAnswerDisabled" translate="no">
>         <source xml:lang="en">Disabled…nothing that could be part of the answer is selected</source>
> ```

There is no space between the elipsis and "nothing".
Here and in the code.
___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 151 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6572#-O20EHAv-Q5fpnTp2y6X:-O20EHAv-Q5fpnTp2y6Y:b-8rlqr8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8c6a2f8ebc20ce5dcd78ec7c865f6a9abbbf32a3/DistFiles/localization/en/BloomMediumPriority.xlf#L151)):*
> ```XML
>         <source xml:lang="en">Show answer in each drag target. Use this to make the activity easier.</source>
>         <note>ID: EditTab.Toolbox.DragActivity.ShowAnswer</note>
>       </trans-unit>
> ```

You removed this string, but I don't see a corresponding change in the code. Was this already obsolete?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6572)* status: 16 of 17 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 111 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6572#-O20CjjA96VGZldcjVeD:-O20TRXO3l5vlpg12pGf:b-bilco3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/362b434efa66f585f071c3d01c215c189154c4bb/DistFiles/localization/en/BloomMediumPriority.xlf#L111)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

There is no space between the elipsis and "nothing".
Here and in the code.
</blockquote></details>

We decided to reword.
___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 151 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6572#-O20EHAv-Q5fpnTp2y6X:-O20IpvmDM5myv-W6WyK:b-7ateh5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8c6a2f8ebc20ce5dcd78ec7c865f6a9abbbf32a3/DistFiles/localization/en/BloomMediumPriority.xlf#L151)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

You removed this string, but I don't see a corresponding change in the code. Was this already obsolete?
</blockquote></details>

Apparently so. I could find nothing that uses it. Probably an earlier version of ShowAnswersInTargets.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6572)* status: all files reviewed, 2 unresolved discussions

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6572)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
