### PR TITLE
Properly strip image metadata when needed (BL-13618)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6560)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6560)* status: 0 of 3 files reviewed, all discussions resolved

___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 1367 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6560#-O-wetck02GuWooftb22:-O-wetck02GuWooftb23:b-nksu8r) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bfc9569586a78b956b0dc600b55f63240d62ed07/src/BloomExe/ImageProcessing/ImageUtils.cs#L1367)):*
> ```Smalltalk
>                     );
>                 if (!String.IsNullOrEmpty(options.ProfilesToStrip))
>                     argsBldr.AppendFormat(" +profile \"{0}\"", options.ProfilesToStrip);
> ```

The `-strip` option removes all profiles and does not take a parameter. 
So when we were calling it, we were getting an error as it was trying to interpret the value of `options.ProfilesToStrip` as a file name.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6560)* status: 0 of 3 files reviewed, all discussions resolved

___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 1367 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6560#-O-wetck02GuWooftb22:-O-wgjKH9ECSUA9Y0g3u:b-yidqsi) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bfc9569586a78b956b0dc600b55f63240d62ed07/src/BloomExe/ImageProcessing/ImageUtils.cs#L1367)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The `-strip` option removes all profiles and does not take a parameter. 
So when we were calling it, we were getting an error as it was trying to interpret the value of `options.ProfilesToStrip` as a file name.
</blockquote></details>

What is there isn't understandable either, and wants a comment. I.e., it's really unclear why saying `+profile {options.ProfilesToStrip}` should mean "strip these profiles".

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6560)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @hatton)

___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 1367 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6560#-O-wetck02GuWooftb22:-O-wj6iT3mDNn0eLrzeF:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bfc9569586a78b956b0dc600b55f63240d62ed07/src/BloomExe/ImageProcessing/ImageUtils.cs#L1367)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

What is there isn't understandable either, and wants a comment. I.e., it's really unclear why saying `+profile {options.ProfilesToStrip}` should mean "strip these profiles".
</blockquote></details>

Done.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6560)* status: 0 of 3 files reviewed, all discussions resolved

___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 1367 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6560#-O-wetck02GuWooftb22:-O-wnfeeBuaMGfmRhGum:bbdo9qg) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bfc9569586a78b956b0dc600b55f63240d62ed07/src/BloomExe/ImageProcessing/ImageUtils.cs#L1367)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK so the problem is pre-existing. `profilesToStrip` is actually be `profiles to keep`!

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6560)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @hatton)

___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 1367 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6560#-O-wetck02GuWooftb22:-O-wuDaxDoZX6R4_Rl2z:bp0snl) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bfc9569586a78b956b0dc600b55f63240d62ed07/src/BloomExe/ImageProcessing/ImageUtils.cs#L1367)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

OK so the problem is pre-existing. `profilesToStrip` is actually be `profiles to keep`!
</blockquote></details>

No, this code path just never worked at all. 
See my first comment in this thread.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6560)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @hatton)

___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 1367 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6560#-O-wetck02GuWooftb22:-O-wyRDX0p3p-f4CRQYd:bjjxskj) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bfc9569586a78b956b0dc600b55f63240d62ed07/src/BloomExe/ImageProcessing/ImageUtils.cs#L1367)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

No, this code path just never worked at all. 
See my first comment in this thread.
</blockquote></details>

I think I understand your question better now.
You're asking if the name "ProfilesToStrip" is correct.
I think it is. The bang in front of icm tells it to strip everything (*) except (!) icm.

But you can see in the comment from the doc, the thing you pass to `+profile` is the profiles you want to strip.

So on another code path we pass in "iptc" because that's the profile we want to strip.

**Review by StephenMcConnel — APPROVED** [review]
:lgtm:  Good catch for a bug I most likely introduced.

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6560#-:-O09ktVd0nuL0NP3ScUw:b4wj1yy)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
