### PR TITLE
Use Icu to translate language names (BL-5128)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
Also ensure that China (the country name) does not display for zh-CN in language menu.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1936)

### CODE REVIEW

**Comment by andrew-polk** [comment]
:lgtm:
But it feels like too big a change to put in before the beta goes live.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomTests/Book/BookTests.cs, line 245 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1936#-KyGsZ_50GEYbTLTs6x1:-KyGsZ_50GEYbTLTs6x2:b-b6tp6d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c8277196e2a7711f189efaf5e14f16115fd47a5d/src/BloomTests/Book/BookTests.cs#L245)):*
> espagnol

Is this a typo? Or some magical incantation which causes the ñ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1936#-:-KyGt7mOenfgCztl4Sab:bxq4d6x)*

**Comment by StephenMcConnel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomTests/Book/BookTests.cs, line 245 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1936#-KyGsZ_50GEYbTLTs6x1:-KyGxRWpBzY84VQyko0n:b22ml81) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c8277196e2a7711f189efaf5e14f16115fd47a5d/src/BloomTests/Book/BookTests.cs#L245)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> espagnol

Is this a typo? Or some magical incantation which causes the ñ?
</blockquote></details>

It's the French name for Spanish.  The C# code uses Language2 (national language) to display the language2 (national) and language3 (regional) language names.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1936)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomTests/Book/BookTests.cs, line 245 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1936#-KyGsZ_50GEYbTLTs6x1:-KyH6DyNPFQiR-lK3xPS:b-w4z4z8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c8277196e2a7711f189efaf5e14f16115fd47a5d/src/BloomTests/Book/BookTests.cs#L245)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

It's the French name for Spanish.  The C# code uses Language2 (national language) to display the language2 (national) and language3 (regional) language names.
</blockquote></details>

Ah. I guess I got confused because Thai appears to be English.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1936)*

**Comment by StephenMcConnel** [comment]
ICU is too big to add to the Windows installer.

**Pull request closed without merging**
