### PR TITLE
BL-6679 Refactor sign language tool avoiding Dom manipulation in C#

### PR DESCRIPTION
**Pull request by JohnThomson**
Also removes traces of old commands Edit Outside Bloom and Restore Original

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2909)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2909)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson and @hatton)

___
*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 193 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2909#-LSGArlG5vSUiBfVS8L3:-LSGArlG5vSUiBfVS8L4:bhpax8s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d6ae0353fdb19f78bf4e4d6db363c32de7c32a29/src/BloomExe/web/controllers/SignLanguageApi.cs#L193)):*
> ```Smalltalk
> 				var newVideoPath = Path.Combine(BookStorage.GetVideoDirectoryAndEnsureExistence(CurrentBook.FolderPath), GetNewVideoFileName()); // Use a new name to defeat caching.
> 				RobustFile.Copy(path, newVideoPath);
> 				var relativePath = BookStorage.GetVideoFolderName + Path.GetFileName(newVideoPath);
> ```

Perhaps not worth it, but these two lines could be reused in a method. (if you make other changes)

**Review by andrew-polk — COMMENTED** [review]
@hatton, do you want a look before this is merged? :lgtm: with one optional comment.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2909#-:-LSGO4Ey8d6TVQLohq42:b-ed7w0i)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson and @hatton)

**Review by hatton — APPROVED** [review]
Looked at it. Nice to see all the pink lines so outnumbering the green ones!

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2909#-:-LSGnYOi8gi5D_-HYUCV:bnx6es6)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson and @hatton)

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2909)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
