### PR TITLE
Remove optipng from Bloom installation (BL-9378)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4983)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Looks like there are still a couple places in .cs files which need to be addressed.
ImageUpdater
BloomIntegrityDialog

**Review by andrew-polk — CHANGES_REQUESTED** [review]
see above

**Review by StephenMcConnel — COMMENTED** [review]
I've removed every mention of optipng (and CompressImage), even those found in comments.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4983#-:-Mw8bu5a1Ah8UJCdmapm:bkyyszy)* status: 0 of 6 files reviewed, all discussions resolved

**Review by andrew-polk — APPROVED** [review]
Sorry if my "see above" seemed like nagging. I was reviewing directly from github and it forced me to add a comment (which I had already done).

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4983#-:-Mw8iZrA-zwxoKPBFQ-w:b11yc58)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
