### PR TITLE
Rename a couple of classes

### PR DESCRIPTION
**Pull request by gmartin7**
* migrate nonprinting class to bloom-nonprinting

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2383)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/BloomExe/Book/Book.cs, line 978 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2383#-LCUmeQW0KdHK2Rw821-:-LCUmeQW0KdHK2Rw8210:b2ze08) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1219bc8cdcff6c9adc8bbe382ca207cbc8a17ac6/src/BloomExe/Book/Book.cs#L978)):*
> ```Smalltalk
> 		/// tool on these pages embedded tons of span elements which messed up BR display. New question pages have classes
> 		/// that keep them from being recorded. Here we fix up any existing question pages from the old code.
> 		/// Also, the older nonprinting class will be updated here to bloom-nonprinting.
> ```

Help me understand why this is the best place to do this migration.
It feels wrong, but if this is the only feature which currently uses nonprinting, I might be convincible.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2383)*

**Comment by gmartin7** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/Book.cs, line 978 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2383#-LCUmeQW0KdHK2Rw821-:-LCUyDRGBHZBpduzrblA:bps61ht) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1219bc8cdcff6c9adc8bbe382ca207cbc8a17ac6/src/BloomExe/Book/Book.cs#L978)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Help me understand why this is the best place to do this migration.
It feels wrong, but if this is the only feature which currently uses nonprinting, I might be convincible.

</blockquote></details>

There are now two pages in the "Special" section of Add Page dialog that use nonprinting that we are changing to bloom-nonprinting. Only the Question page was in the "wild". The TranslationInstruction page now uses the modified class (which is one reason I wanted this merged sooner, rather than later, so it doesn't get used with the old classname).
This is the area of the code where we update class names that change and bring old books up-to-date.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2383)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/Book.cs, line 978 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2383#-LCUmeQW0KdHK2Rw821-:-LCUzRBI7U3axqvC2ewT:b4u87kh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1219bc8cdcff6c9adc8bbe382ca207cbc8a17ac6/src/BloomExe/Book/Book.cs#L978)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

There are now two pages in the "Special" section of Add Page dialog that use nonprinting that we are changing to bloom-nonprinting. Only the Question page was in the "wild". The TranslationInstruction page now uses the modified class (which is one reason I wanted this merged sooner, rather than later, so it doesn't get used with the old classname).
This is the area of the code where we update class names that change and bring old books up-to-date.
</blockquote></details>

To clarify, by "this...place" I meant this method.
Seems like it would be better to give it its own method. Though your foreach labels the divs as `quizPages`, you are searching for and migrating all `nonprinting` divs.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2383)*

**Comment by gmartin7** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/Book.cs, line 978 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2383#-LCUmeQW0KdHK2Rw821-:-LCVB3V58uhJgaJDLlMV:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1219bc8cdcff6c9adc8bbe382ca207cbc8a17ac6/src/BloomExe/Book/Book.cs#L978)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

To clarify, by "this...place" I meant this method.
Seems like it would be better to give it its own method. Though your foreach labels the divs as `quizPages`, you are searching for and migrating all `nonprinting` divs.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2383)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2383#-:-LCVC45mCZO2YBUVJRjc:bnfp4nl)*

**Pull request merged**
