### PR TITLE
BL-11159 React Topic Chooser

### PR DESCRIPTION
**Pull request by gmartin7**
* get basic framework setup
* clicking Choose Topic... link activates new dialog
* get storybook hooked up and working
* give storybook "reasonable" data
* display topics
* adjust various sizes and spacings
* move api to EditingViewApi
* get "No Topic" to work properly
* remove old .ts and .less versions
* fixed regression: clicking the topic itself again brings up
   the topic dialog
* deleted some unused code in editablePage.ts

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5316)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5316)* status: all files reviewed, 6 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts` line 452 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5316#-N8Yy5aH2_g7o5BegzrA:-N8Yy5aH2_g7o5BegzrB:b-xw8xgm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b721145cde0c6239e893c4dcb8a9cf1b4153a926/src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts#L452)):*
> ```XML
>                     functionCall = "clickWasAlreadyHandled";
>                     onClick =
>                         "onClick='(window.parent || window).editTabBundle.showEditViewTopicChooserDialog();'";
> ```

Can we simplify this case, the one above, and the C# code by just putting the onClick strings into the source.data so that we end up with a javascript: href and neither end has to mess with "clickWasAlreadyHandled" and we never have an onClick?
___
*[`src/BloomBrowserUI/bookEdit/TopicChooser/TopicChooserDialog.tsx` line 101 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5316#-N8Yoxh2-fVgdeTqnWka:-N8Yoxh2-fVgdeTqnWkb:b-z2o1ze) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b721145cde0c6239e893c4dcb8a9cf1b4153a926/src/BloomBrowserUI/bookEdit/TopicChooser/TopicChooserDialog.tsx#L101)):*
> ```XML
>             <FormControlLabel
>                 css={css`
>                     span:first-child {
> ```

Can't we just put this on the Radio element itself?
___
*[`src/BloomBrowserUI/bookEdit/TopicChooser/TopicChooserDialog.tsx` line 121 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5316#-N8Yp7bO2ZGetS0-3fdu:-N8Yp7bO2ZGetS0-3fdv:bxhybs3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b721145cde0c6239e893c4dcb8a9cf1b4153a926/src/BloomBrowserUI/bookEdit/TopicChooser/TopicChooserDialog.tsx#L121)):*
> ```XML
>                             : choice.englishKey}
>                     </Typography>
>                 }
> ```

Does/should clicking on the label activate that choice? (Surprises me that only the Radio itself has the onChange action, but maybe the FormControlLabel handles this?
___
*[`src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx` line 166 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5316#-N8YqPQ2AnWIY1DlMTwb:-N8YqPQ2AnWIY1DlMTwc:b-pe84k0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b721145cde0c6239e893c4dcb8a9cf1b4153a926/src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx#L166)):*
> ```XML
>     const background = props.backgroundColor || "transparent";
>     const cursor = props.disableDragging ? "unset" : "move";
>     const fontSize = props.fontSize || "16px";
> ```

There may be a backwards-compatibility reason to use px, but our CSS course recommends font sizes in rems. Of course, it may not matter much since I don't think the user has any control over how big a REM is in GeckoFx.
___
*[`src/BloomExe/Edit/EditingView.cs` line 677 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5316#-N8YzT9rC_AfSk7gzhkj:-N8YzT9rC_AfSk7gzhkk:bda3tjg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b721145cde0c6239e893c4dcb8a9cf1b4153a926/src/BloomExe/Edit/EditingView.cs#L677)):*
> ```Smalltalk
> 				// Let Gecko handle hrefs that are explicitly tagged "javascript"
> 				// Used to be tied to, for example, data-functionOnHintClick="ShowTopicChooser()".
> 				// Now we do straight React, so that click is now in the above "clickWasAlreadyHandled" category.
> ```

I don't think the two new lines help. Better, if we still need clickWasAlreadyHandled, to note above one or two examples that use it, and here one or two that use this.
___
*[`src/BloomExe/web/controllers/EditingViewApi.cs` line 221 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5316#-N8Z-4PLBl9o-FQwE9Kq:-N8Z-4PLBl9o-FQwE9Kr:b54opuh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b721145cde0c6239e893c4dcb8a9cf1b4153a926/src/BloomExe/web/controllers/EditingViewApi.cs#L221)):*
> ```Smalltalk
> 			var data = $"[{{\"englishKey\":\"No Topic\",\"translated\":\"{localizedNoTopic}\"}}, {pairs}]";
> 
> 			request.ReplyWithJson(data);
> ```

I'm not sure this is worth changing at this point, but for future reference, if the client always wants the list and current choice together, both could be returned in a single JSON, which reduces round trips and complexity at the other end.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5316)* status: 11 of 17 files reviewed, 6 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts` line 452 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5316#-N8Yy5aH2_g7o5BegzrA:-N8eRTr6DExlS8H6wepX:brr4ra) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b721145cde0c6239e893c4dcb8a9cf1b4153a926/src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts#L452)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Can we simplify this case, the one above, and the C# code by just putting the onClick strings into the source.data so that we end up with a javascript: href and neither end has to mess with "clickWasAlreadyHandled" and we never have an onClick?
</blockquote></details>

I'd be concerned about backwards compatibility, since all the books out there so far have 
```
<div class="coverBottomBookTopic bloom-userCannotModifyStyles bloom-alwaysShowBubble Cover-Default-style" data-derived="topic" data-functiononhintclick="ShowTopicChooser()" data-hint="Click to choose topic"></div>
```
It may well be that I just don't understand what you mean too. More explanations are welcome.
___
*[`src/BloomBrowserUI/bookEdit/TopicChooser/TopicChooserDialog.tsx` line 101 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5316#-N8Yoxh2-fVgdeTqnWka:-N8eYaSs9_uqY-XoZp6V:bw8tgi1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b721145cde0c6239e893c4dcb8a9cf1b4153a926/src/BloomBrowserUI/bookEdit/TopicChooser/TopicChooserDialog.tsx#L101)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Can't we just put this on the Radio element itself?
</blockquote></details>

Done. Took some figuring out, since there's not an actual <radio> element in the output.
___
*[`src/BloomBrowserUI/bookEdit/TopicChooser/TopicChooserDialog.tsx` line 121 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5316#-N8Yp7bO2ZGetS0-3fdu:-N8eYpygBRWwexMoy6Nx:b-vwhxt9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b721145cde0c6239e893c4dcb8a9cf1b4153a926/src/BloomBrowserUI/bookEdit/TopicChooser/TopicChooserDialog.tsx#L121)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Does/should clicking on the label activate that choice? (Surprises me that only the Radio itself has the onChange action, but maybe the FormControlLabel handles this?
</blockquote></details>

Yep. That's apparently how it works.
___
*[`src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx` line 166 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5316#-N8YqPQ2AnWIY1DlMTwb:-N8eZ_o79cJKF28dybJf:b7eh4wi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b721145cde0c6239e893c4dcb8a9cf1b4153a926/src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx#L166)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

There may be a backwards-compatibility reason to use px, but our CSS course recommends font sizes in rems. Of course, it may not matter much since I don't think the user has any control over how big a REM is in GeckoFx.
</blockquote></details>

I've reverted the changes to DialogTitle, as I'm no longer using them. rems might be a good idea someday... but maybe not today.
___
*[`src/BloomExe/Edit/EditingView.cs` line 677 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5316#-N8YzT9rC_AfSk7gzhkj:-N8izgVPCI2wBqv8sW_A:b-hcw1uv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b721145cde0c6239e893c4dcb8a9cf1b4153a926/src/BloomExe/Edit/EditingView.cs#L677)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't think the two new lines help. Better, if we still need clickWasAlreadyHandled, to note above one or two examples that use it, and here one or two that use this.
</blockquote></details>

I removed the comments. I'm not sure where these might be used now.
___
*[`src/BloomExe/web/controllers/EditingViewApi.cs` line 221 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5316#-N8Z-4PLBl9o-FQwE9Kq:-N8izxHq9JuNSuZyUZgH:b-a6l2yr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b721145cde0c6239e893c4dcb8a9cf1b4153a926/src/BloomExe/web/controllers/EditingViewApi.cs#L221)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm not sure this is worth changing at this point, but for future reference, if the client always wants the list and current choice together, both could be returned in a single JSON, which reduces round trips and complexity at the other end.
</blockquote></details>

Done. This took a bit to figure out. I had a good example (elsewhere in this file) of using ExpandoObject, but this case was slightly different because one of the parts of the result was an array. I'm not sure I did the most efficient thing, but it works now.

**Review by JohnThomson — APPROVED** [review]
Looks good now...just my response about the click action to consider. I don't think it's essential to make this change, but I think it would be in the spirit of leaving the code better than we found it.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5316#-:-N93pak7CprEMQhx4w_M:b-9mqnwh)* status: 11 of 17 files reviewed, 1 unresolved discussion (waiting on @gmartin7 and @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts` line 452 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5316#-N8Yy5aH2_g7o5BegzrA:-N93nsXJAPGM0-_ZvaJ7:b-6l38s2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b721145cde0c6239e893c4dcb8a9cf1b4153a926/src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts#L452)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I'd be concerned about backwards compatibility, since all the books out there so far have 
```
<div class="coverBottomBookTopic bloom-userCannotModifyStyles bloom-alwaysShowBubble Cover-Default-style" data-derived="topic" data-functiononhintclick="ShowTopicChooser()" data-hint="Click to choose topic"></div>
```
It may well be that I just don't understand what you mean too. More explanations are welcome.
</blockquote></details>

You'd need to check, but I believe data-functiononhintclick="ShowTopicChooser()" is part of the xmatter shell that is automatically updated whenever a book is opened for editing (at least). Very likely you can fix it everywhere by updating the topic mixin somewhere in xmatter. So if we want to just have a single mechanism for special click actions, I don't think backwards compatibility would be a problem.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5316)* status: 11 of 21 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts` line 452 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5316#-N8Yy5aH2_g7o5BegzrA:-N9IXKdv1ebjHkKP25Z8:b-5nly8g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b721145cde0c6239e893c4dcb8a9cf1b4153a926/src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts#L452)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

You'd need to check, but I believe data-functiononhintclick="ShowTopicChooser()" is part of the xmatter shell that is automatically updated whenever a book is opened for editing (at least). Very likely you can fix it everywhere by updating the topic mixin somewhere in xmatter. So if we want to just have a single mechanism for special click actions, I don't think backwards compatibility would be a problem.
</blockquote></details>

I'm not sure I did it the way you intended or not...
And probably confused things with some html and js refactoring...
The 2nd commit has the changes.

**Review by JohnThomson — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5316#-:-N9YXo4-5qy7MuQZecA0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
