### PR TITLE
BL-11257 New Publish screen template

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5262)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
Looks basically good; a few minor things I think you can improve, hopefully easily!

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5262#-:-N5acZIa1x90kRycexyL:bxjyrxy)* status: 0 of 21 files reviewed, 7 unresolved discussions (waiting on @gmartin7 and @JohnThomson)

___
*[`src/BloomBrowserUI/publish/commonPublish/PublishScreenBanner.tsx` line 24 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5262#-N5aXPwR92vSTzP_i5HU:-N5aXPwR92vSTzP_i5HV:b-t2c374) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a59b078878c67812a42bcfcaafcf766bc9076545/src/BloomBrowserUI/publish/commonPublish/PublishScreenBanner.tsx#L24)):*
> ```XML
>                 flex-direction: row;
>                 justify-content: space-between;
>                 background-color: #ebebeb;
> ```

Is this color not already in BloomUI? If not, should it be?
___
*[`src/BloomBrowserUI/publish/commonPublish/PublishScreenBanner.tsx` line 54 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5262#-N5aZ0DT5HessEor69nQ:-N5aZ0DT5HessEor69nR:b7ktdtc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a59b078878c67812a42bcfcaafcf766bc9076545/src/BloomBrowserUI/publish/commonPublish/PublishScreenBanner.tsx#L54)):*
> ```XML
>                         l10nKey={props.descriptionL10nId}
>                     >
>                         {props.descriptionMarkdown}
> ```

If this indeed might be Markdown, don't we need a wrapper to interpret it?
___
*[`src/BloomBrowserUI/publish/commonPublish/PublishScreenBaseComponents.tsx` line 10 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5262#-N5aZMExCdbIyzugIC0P:-N5aZMExCdbIyzugIC0Q:b-3xhi11) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a59b078878c67812a42bcfcaafcf766bc9076545/src/BloomBrowserUI/publish/commonPublish/PublishScreenBaseComponents.tsx#L10)):*
> ```XML
> 
> export const PreviewPanel: React.FunctionComponent = props => {
>     return <section className={"preview"}>{props.children}</section>;
> ```

As long as we're making new components, can we switch to Emotion and put whatever rules "preview" is supposed to do inline? Or are those rules used elsewhere? (Likewise for other classnames here...I think it should be possible to get rid of the new less file.
___
*[`src/BloomBrowserUI/publish/commonPublish/PublishScreenTemplate.tsx` line 56 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5262#-N5a_tDs06vxP_jhlsIK:-N5a_tDt3Ao5F_8KaogT:bqge3xp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a59b078878c67812a42bcfcaafcf766bc9076545/src/BloomBrowserUI/publish/commonPublish/PublishScreenTemplate.tsx#L56)):*
> ```XML
>             flex: 5; // The MainPanel fills out the rest of the width not taken by the OptionPanel.
>             display: flex;
>             background-color: #fafafa;
> ```

BloomUI?
___
*[`src/BloomBrowserUI/publish/ePUBPublish/ePUBPublish.less` line 31 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5262#-N5aaDn7EQ70wavExSRb:-N5aaDn7EQ70wavExSRc:b-d4s4jn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a59b078878c67812a42bcfcaafcf766bc9076545/src/BloomBrowserUI/publish/ePUBPublish/ePUBPublish.less#L31)):*
> ```Less
> }
> 
> // In the new PublishScreenTemplate, settingsGroup is no longer part of the main screen.
> ```

A rule starting with .settingsGroup won't care. "section." just makes it a bit more specific, and you haven't explained why that's needed.
Can we move this rule to Emotion?
___
*[`src/BloomBrowserUI/publish/ReaderPublish/MethodChooser.tsx` line 53 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5262#-N5abqlPBesPvFtA4UoB:-N5abqlPBesPvFtA4UoC:bzqst0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a59b078878c67812a42bcfcaafcf766bc9076545/src/BloomBrowserUI/publish/ReaderPublish/MethodChooser.tsx#L53)):*
> ```XML
>                     // explicitly set.  See https://issues.bloomlibrary.org/youtrack/issue/BL-7506.
>                     padding-top: 10px;
>                     .column1 {
> ```

Since you're migrating to Emotion, why not just put these rules on the appropriate child element instead of class column1? Usually we only want to do this sort of embedded rules when the element we want to target is created by code we don't control, like an inner component of some MUI thing.
___
*[`src/BloomBrowserUI/publish/ReaderPublish/ReaderPublish.less` line 3 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5262#-N5abczaE3GeJjc1lolk:-N5abczaE3GeJjc1loll:b-mb8i1j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a59b078878c67812a42bcfcaafcf766bc9076545/src/BloomBrowserUI/publish/ReaderPublish/ReaderPublish.less#L3)):*
> ```Less
> @import "../../bloomUI.less";
> 
> .ReaderPublishScreen {
> ```

Can we move the last two fragments to Emotion and scrap this file?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5262)* status: 0 of 23 files reviewed, 7 unresolved discussions (waiting on @gmartin7 and @JohnThomson)

___
*[`src/BloomBrowserUI/publish/commonPublish/PublishScreenBanner.tsx` line 24 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5262#-N5aXPwR92vSTzP_i5HU:-N5anGNEE8YrA11BFc8p:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a59b078878c67812a42bcfcaafcf766bc9076545/src/BloomBrowserUI/publish/commonPublish/PublishScreenBanner.tsx#L24)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is this color not already in BloomUI? If not, should it be?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/commonPublish/PublishScreenBanner.tsx` line 54 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5262#-N5aZ0DT5HessEor69nQ:-N5ai83F-nPM9lbAUboB:b-bd7vkw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a59b078878c67812a42bcfcaafcf766bc9076545/src/BloomBrowserUI/publish/commonPublish/PublishScreenBanner.tsx#L54)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

If this indeed might be Markdown, don't we need a wrapper to interpret it?
</blockquote></details>

Actually, `DIV` runs through l10n code that DOES interpret a limited subset of markdown, including bolding, and basic links. I was surprised to discover that myself! The method `getLocalizedContentAndClass()` in `l10nComponents.tsx` calls `processSimpleMarkdown()`.
___
*[`src/BloomBrowserUI/publish/commonPublish/PublishScreenBaseComponents.tsx` line 10 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5262#-N5aZMExCdbIyzugIC0P:-N5ajG2rAokr2NMo-obN:b-41zevx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a59b078878c67812a42bcfcaafcf766bc9076545/src/BloomBrowserUI/publish/commonPublish/PublishScreenBaseComponents.tsx#L10)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

As long as we're making new components, can we switch to Emotion and put whatever rules "preview" is supposed to do inline? Or are those rules used elsewhere? (Likewise for other classnames here...I think it should be possible to get rid of the new less file.
</blockquote></details>

I certainly agree in principle. To be clear, this is actually a rename. It used to be `BasePublishScreen.tsx` w/equivalent `.less` file. Anyway, I'm moving as many rules as I can to emotion without "upsetting the apple cart". I've managed to eliminate the ePUB-specific `.less` file. Some of the rules that apply to this file are more basic than I want to fiddle with in this PR (html, app, screenroot sort of things).
___
*[`src/BloomBrowserUI/publish/commonPublish/PublishScreenTemplate.tsx` line 56 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5262#-N5a_tDs06vxP_jhlsIK:-N5amxpqBBAPmKfQlYSQ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a59b078878c67812a42bcfcaafcf766bc9076545/src/BloomBrowserUI/publish/commonPublish/PublishScreenTemplate.tsx#L56)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

BloomUI?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/ePUBPublish/ePUBPublish.less` line 31 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5262#-N5aaDn7EQ70wavExSRb:-N5anfBC8wniVsui3mOg:bmywauc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a59b078878c67812a42bcfcaafcf766bc9076545/src/BloomBrowserUI/publish/ePUBPublish/ePUBPublish.less#L31)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

A rule starting with .settingsGroup won't care. "section." just makes it a bit more specific, and you haven't explained why that's needed.
Can we move this rule to Emotion?
</blockquote></details>

The rules above are "under" `.ePUBPublishScreen`. SettingsGroup is now no longer part of the main screen so I moved it out. It took a lot of work to figure out how to get all these rules into emotion, but I finally got it working. Eliminating this file...



_Code quote:_
```Less
.ePUBPublishScreen
```
___
*[`src/BloomBrowserUI/publish/ReaderPublish/MethodChooser.tsx` line 53 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5262#-N5abqlPBesPvFtA4UoB:-N5bBbFpCrXjtaSztefP:bugn6yt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a59b078878c67812a42bcfcaafcf766bc9076545/src/BloomBrowserUI/publish/ReaderPublish/MethodChooser.tsx#L53)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Since you're migrating to Emotion, why not just put these rules on the appropriate child element instead of class column1? Usually we only want to do this sort of embedded rules when the element we want to target is created by code we don't control, like an inner component of some MUI thing.
</blockquote></details>

Done. Found places to put all these rules, eventually.
___
*[`src/BloomBrowserUI/publish/ReaderPublish/ReaderPublish.less` line 3 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5262#-N5abczaE3GeJjc1lolk:-N5bGNBy8Ii2gy1j_7vv:b-v5dv8a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a59b078878c67812a42bcfcaafcf766bc9076545/src/BloomBrowserUI/publish/ReaderPublish/ReaderPublish.less#L3)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Can we move the last two fragments to Emotion and scrap this file?
</blockquote></details>

working on it.... Got it! Done.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5262)* status: 0 of 23 files reviewed, 7 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/publish/ReaderPublish/ReaderPublish.less` line 3 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5262#-N5abczaE3GeJjc1lolk:-N5gGVH-30b8v5smJU8p:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a59b078878c67812a42bcfcaafcf766bc9076545/src/BloomBrowserUI/publish/ReaderPublish/ReaderPublish.less#L3)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

working on it.... Got it! Done.
</blockquote></details>

Done.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 9 of 21 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5262)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/publish/ReaderPublish/MethodChooser.tsx` line 53 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5262#-N5abqlPBesPvFtA4UoB:-N5jqDkF8UXQQ2n6LhIs:b-ap11yd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a59b078878c67812a42bcfcaafcf766bc9076545/src/BloomBrowserUI/publish/ReaderPublish/MethodChooser.tsx#L53)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Done. Found places to put all these rules, eventually.
</blockquote></details>

Sorry it was so much work, but I think we'll be glad in the long run.

**Pull request merged**
