### PR TITLE
RunJavascriptAsync (BL-11919)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714)* status: 0 of 34 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/IBrowser.cs` line 448 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NR0HKzk-4yEo8fqqDVh:-NR0HKzk-4yEo8fqqDVi:b-5wt98d) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/583c737bf5fbe588e7ca3177cff38114b8c1b00e/src/BloomExe/IBrowser.cs#L448)):*
> ```Smalltalk
> 		public abstract string RunJavaScript(string script);
> 
> 		public abstract Task<string> RunJavaScriptAsync(string script);
> ```

Shouldn't this be an `async` method?
(maybe you can't have `abstract async`?)
___
*[`src/BloomExe/WebView2Browser.cs` line 321 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NR0HpI274nhJt5CWrC7:-NR0HmOu44O5UQaYgPm0:bvaz8iq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/583c737bf5fbe588e7ca3177cff38114b8c1b00e/src/BloomExe/WebView2Browser.cs#L321)):*
> ```Smalltalk
> 		}
> 
> 		public override Task<string> RunJavaScriptAsync(string script)
> ```

Shouldn't this be an `async` method?

Why do we have this and the following method? (And why does the following method start with a lower-case r?
I think the comment on the following method needs to be updated, right?

**Review by andrew-polk — COMMENTED** [review]
Just did a cursory look, but noticed a couple things I had questions about.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-:-NR0IAhcDjW138BEsdPq:bomfsc)* status: 0 of 34 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714)* status: 0 of 34 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/GeckoFxBrowser.cs` line 830 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NR3nEllBM6fMc60Jf8w:-NR3nEllBM6fMc60Jf8x:b-qturw4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/583c737bf5fbe588e7ca3177cff38114b8c1b00e/src/BloomExe/GeckoFxBrowser.cs#L830)):*
> ```Smalltalk
> 		}
> 
> 		public static string RunJavaScriptOn(GeckoWebBrowser geckoWebBrowser, string script)
> ```

I don't suppose anyone could accidentally use this now...
But let's go ahead and make it private.

**Review by jsubloom — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714)* status: 3 of 34 files reviewed, 7 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[`src/BloomExe/Edit/ConfigurationDialog.cs` line 57 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NR3rt8fCegeCVF0L4P8:-NR3rt8fCegeCVF0L4P9:b-bnug3y) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/583c737bf5fbe588e7ca3177cff38114b8c1b00e/src/BloomExe/Edit/ConfigurationDialog.cs#L57)):*
> ```Smalltalk
> 		}
> 
> 		async private void  _okButton_Click(object sender, EventArgs e)
> ```

I think "private async" is more idiomatic than "async private". For example, see the official docs: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/async, which use "private async"
___
*[`src/BloomExe/Publish/PDF/PdfViewer.cs` line 202 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NR3sp-78VPQut3PAW_9:-NR3sp-78VPQut3PAW_A:bec5b14) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/583c737bf5fbe588e7ca3177cff38114b8c1b00e/src/BloomExe/Publish/PDF/PdfViewer.cs#L202)):*
> ```Smalltalk
> 			{
> 				var wv2 = _pdfViewerControl as WebView2Browser;
> 				wv2.RunJavaScriptAsync("window.print()");
> ```

I'm not so sure about this. Is this intentional? Did you mean to make Print async, or are we intentionally trying to fire-and-forget the async operation?
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 169 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NR3uNbw5Bn0X161OrqU:-NR3uNbw5Bn0X161OrqV:bglxgl3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/583c737bf5fbe588e7ca3177cff38114b8c1b00e/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L169)):*
> ```Smalltalk
> 				_browser.Navigate(rootPage, false);
> 				// This extra check that spreadsheetBundle actually exists might not be necessary.
> 				var task = _browser.RunJavaScriptAsync($"spreadsheetBundle");
> ```

I'm not sure what the point of converting to RunJavascriptAsync was here. It didn't seem to make our life any better.  Can you explain what's going on? 

Actually, what I think should happen overall in this file is:
1) An InitializeAsync() method or similar should be added.
2) InitializeAsync() should take charge of loading up the browser / spreadsheet bundle.
3) GetBrowser() can synchronously return the previously loaded browser. I guess you can optioanlly throw an exception if GetBrowser() is called before InitializeAsync() completes by utilizing a isLoaded member variable or something like that.
4) Any callers to GetBrowser() such as GetSentenceFragments() can synchronously return without needing to await anything.

Does that make sense?
___
*[`src/BloomExe/ToPalaso/ProgressDialogForeground.cs` line 35 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NR3wlbiEyVE7Q2OvJtm:-NR3wlbj4rbKV4rZ31bF:b-mgpr20) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/583c737bf5fbe588e7ca3177cff38114b8c1b00e/src/BloomExe/ToPalaso/ProgressDialogForeground.cs#L35)):*
> ```Smalltalk
> 		}
> 
> 		public void ShowAndDoWork(Func<IProgress, Task> work)
> ```

Add a comment saying that work can be an async method.
___
*[`src/BloomExe/ToPalaso/ProgressDialogForeground.cs` line 61 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NR3yYq4024XCeS8DWqB:-NR3yYq59QgH6j0Vp7Z6:b-ntopte) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/583c737bf5fbe588e7ca3177cff38114b8c1b00e/src/BloomExe/ToPalaso/ProgressDialogForeground.cs#L61)):*
> ```Smalltalk
> 		{
> 			Application.Idle -= new EventHandler(StartWorking);
> 			if (_work != null)
> ```

I think this works, but I think it could be more straightforward as follows:

1) StartWorking becomes an async method.  (async Task StartWorkingAsync)..  Not 1,000% sure, but as far as I know, there's no problem with Application.Idle receiving an async event handler, right? 
2) I guess you can still have two overloads of ShowAndDoWork. But I'd have the first overload which takes the Action just wrap the action so that it is of type Func<IProgress, Task> and pass it to the 2nd overload. 
3) Now we just need one member variable instead of two, so get rid of the extraneous one.
4) The old StartWorking code can be simplified to:
Application.Idle -= ...
await _asyncWork(Progress)
Close();

I like that this avoids having two mutually exclusive member variables to store the work, which I wasn't a huge fan of. I think having one member variable is more understandable.

What do you think?

**Review by jsubloom — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714)* status: 3 of 34 files reviewed, 7 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 169 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NR3uNbw5Bn0X161OrqU:-NR4-IIv3UA9konA64rK:b-szzigp) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/583c737bf5fbe588e7ca3177cff38114b8c1b00e/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L169)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

I'm not sure what the point of converting to RunJavascriptAsync was here. It didn't seem to make our life any better.  Can you explain what's going on? 

Actually, what I think should happen overall in this file is:
1) An InitializeAsync() method or similar should be added.
2) InitializeAsync() should take charge of loading up the browser / spreadsheet bundle.
3) GetBrowser() can synchronously return the previously loaded browser. I guess you can optioanlly throw an exception if GetBrowser() is called before InitializeAsync() completes by utilizing a isLoaded member variable or something like that.
4) Any callers to GetBrowser() such as GetSentenceFragments() can synchronously return without needing to await anything.

Does that make sense?
</blockquote></details>

or, if it's too burdensome to make initalizeAsync async... I think I'd prefer having the cludgy code that synchronously waits for the async stuff to be done in the initialize method instead?

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714)* status: 2 of 35 files reviewed, 6 unresolved discussions (waiting on @JohnThomson and @jsubloom)

**Review by jsubloom — CHANGES_REQUESTED** [review]
> Reviewed 16 of 27 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, 7 of 7 files at r6, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714)* status: 34 of 35 files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[`src/BloomExe/MiscUI/BrowserProgressDialog.cs` line 121 at r7](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NRKU3hcBE_1DYDA2o8_:-NRKU3hcBE_1DYDA2o8a:b-spae8j) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c779013103bba71db0e7ddc5b564b16e9f77f219/src/BloomExe/MiscUI/BrowserProgressDialog.cs#L121)):*
> ```Smalltalk
> 		private static Action _doWhenProgressDialogCloses;
> 
> 		public static async Task DoWorkWithProgressDialog(IBloomWebSocketServer socketServer,
> ```

In C# it's usually idiomatic to append "Async" to the method names for async methods. (Although Javascript is less of a fan of that practice). Any reason we shouldn't do that here?

Similar question to many other places.
Wouldn't it make it easier to spot which methods ought to be awaited or not?
___
*[`src/BloomExe/Publish/PublishView.cs` line 774 at r7](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NRKUFZn4V4AXnkvTU07:-NRKUFZn4V4AXnkvTU08:bq7crq4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c779013103bba71db0e7ddc5b564b16e9f77f219/src/BloomExe/Publish/PublishView.cs#L774)):*
> ```Smalltalk
> 		}
> 
> 		private async void OnPrint_Click(object sender, EventArgs e)
> ```

I think the return type should be Task<void> or Task instead.

Optionally - maybe Async should be appended to method name.
___
*[`src/BloomExe/ToPalaso/ProgressDialogForeground.cs` line 38 at r7](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NRKYLeVC_JS7bGA7X81:-NRKYLeVC_JS7bGA7X82:bi3xpwe) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c779013103bba71db0e7ddc5b564b16e9f77f219/src/BloomExe/ToPalaso/ProgressDialogForeground.cs#L38)):*
> ```Smalltalk
> 		}
> 
> 		// Typically work is an async function that conceptually returns void,
> ```

The parameter name "work" is now "asyncWork"



_Code quote:_
```Smalltalk
work
```

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714)* status: 13 of 41 files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @jsubloom)

___
*[`src/BloomExe/GeckoFxBrowser.cs` line 830 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NR3nEllBM6fMc60Jf8w:-NRJH5vPC-ckPrIvWHpD:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/583c737bf5fbe588e7ca3177cff38114b8c1b00e/src/BloomExe/GeckoFxBrowser.cs#L830)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't suppose anyone could accidentally use this now...
But let's go ahead and make it private.
</blockquote></details>

Done.
___
*[`src/BloomExe/IBrowser.cs` line 448 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NR0HKzk-4yEo8fqqDVh:-NR3Q9lc8svK1busVlo3:b-ob6sdf) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/583c737bf5fbe588e7ca3177cff38114b8c1b00e/src/BloomExe/IBrowser.cs#L448)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Shouldn't this be an `async` method?
(maybe you can't have `abstract async`?)
</blockquote></details>

Right, abstract methods can't be async. Seems silly since users of the interface need to know. But the fact that it returns a Task tells the compiler that it can be awaited, and all the async really does is tell the compiler that the body of the method is allowed to use await. But an abstract method has no body!
___
*[`src/BloomExe/WebView2Browser.cs` line 321 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NR0HpI274nhJt5CWrC7:-NR3Qm5-3wzp7-JkK8Ix:b5j96jc) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/583c737bf5fbe588e7ca3177cff38114b8c1b00e/src/BloomExe/WebView2Browser.cs#L321)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Shouldn't this be an `async` method?

Why do we have this and the following method? (And why does the following method start with a lower-case r?
I think the comment on the following method needs to be updated, right?
</blockquote></details>

I think I got away with it because it doesn't actually use await. It just returns the task returned by the async method below. But you are right, there's no reason to have both. I merged them.
___
*[`src/BloomExe/Edit/ConfigurationDialog.cs` line 57 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NR3rt8fCegeCVF0L4P8:-NRJHHcf7tG9fjwENt6Z:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/583c737bf5fbe588e7ca3177cff38114b8c1b00e/src/BloomExe/Edit/ConfigurationDialog.cs#L57)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

I think "private async" is more idiomatic than "async private". For example, see the official docs: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/async, which use "private async"
</blockquote></details>

Done.
___
*[`src/BloomExe/MiscUI/BrowserProgressDialog.cs` line 121 at r7](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NRKU3hcBE_1DYDA2o8_:-NRYdkCr36beHCepbVC2:bq3j1ie) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c779013103bba71db0e7ddc5b564b16e9f77f219/src/BloomExe/MiscUI/BrowserProgressDialog.cs#L121)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

In C# it's usually idiomatic to append "Async" to the method names for async methods. (Although Javascript is less of a fan of that practice). Any reason we shouldn't do that here?

Similar question to many other places.
Wouldn't it make it easier to spot which methods ought to be awaited or not?
</blockquote></details>

I think I have done this systematically through our code base, except that it did not seem useful to rename Test methods that are only ever called by NUnit. (IBrowser.UpdateDisplay is another exception, which I have commented.)
___
*[`src/BloomExe/Publish/PublishView.cs` line 774 at r7](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NRKUFZn4V4AXnkvTU07:-NRKl7-90n1huax8TQ_n:bu94sdm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c779013103bba71db0e7ddc5b564b16e9f77f219/src/BloomExe/Publish/PublishView.cs#L774)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

I think the return type should be Task<void> or Task instead.

Optionally - maybe Async should be appended to method name.
</blockquote></details>

It can't be. The return type of an event handler is required to be void. If it is actually invoked by the event being raised, the assumption is that it doesn't matter that some of the work ends up getting put back in the queue and something else might happen in the meantime. I think that's true in this case. When it does matter, you're in trouble. I think even if you make another async method and await the result, the code after the await might still get executed in another event loop cycle and other things might happen in between.
(If something else wants to call the event handler and await it, you can of course put the relevant code into another method which the event handler also calls, and have that return Task. But that's not the case here.)
___
*[`src/BloomExe/Publish/PDF/PdfViewer.cs` line 202 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NR3sp-78VPQut3PAW_9:-NRJCgVC9ksEwZjyu0hV:b-n321o4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/583c737bf5fbe588e7ca3177cff38114b8c1b00e/src/BloomExe/Publish/PDF/PdfViewer.cs#L202)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

I'm not so sure about this. Is this intentional? Did you mean to make Print async, or are we intentionally trying to fire-and-forget the async operation?
</blockquote></details>

I don't think any of the things we do after calling this depend on it having completed...it just puts the UI in a state where the user can print. But that could change, and it turned out to be easy to make two more methods async, so I did.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 169 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NR3uNbw5Bn0X161OrqU:-NRJJ0f59yB7bwDrS7AE:b-qne1aj) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/583c737bf5fbe588e7ca3177cff38114b8c1b00e/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L169)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

or, if it's too burdensome to make initalizeAsync async... I think I'd prefer having the cludgy code that synchronously waits for the async stuff to be done in the initialize method instead?
</blockquote></details>

In general, the point of converting to RunJavascriptAsync is to eventually get rid of the kludgy code in WebView2Browser.RunJavascript that tries to convert the async call to sync without causing a deadlock. I'm not confident that code can be trusted, or that it will continue to work with future versions of WebView2Browser, or that it will continue to work when we eventually abandon Windows.Forms.
We'd have to do a similar kludge to be sure that InitializeAsync has actually finished all its delayed tasks before calling anything that assumes GetBrowser is OK, so that kind of defeats the purpose. (You can't await anything in a constructor.)
But your comment did motivate me to try to get rid of the kludge here, and I did! Making GetBrowser async and using that to handle waiting for Navigate as well as for RunJavascript makes things much cleaner. (It also led to converting one more RunJavaScript to async, as a bonus.)
___
*[`src/BloomExe/ToPalaso/ProgressDialogForeground.cs` line 35 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NR3wlbiEyVE7Q2OvJtm:-NRJEg_J8ELWf5ZsRi81:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/583c737bf5fbe588e7ca3177cff38114b8c1b00e/src/BloomExe/ToPalaso/ProgressDialogForeground.cs#L35)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

Add a comment saying that work can be an async method.
</blockquote></details>

Done.
___
*[`src/BloomExe/ToPalaso/ProgressDialogForeground.cs` line 61 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NR3yYq4024XCeS8DWqB:-NRJGuzWEawBl9H3ZWAV:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/583c737bf5fbe588e7ca3177cff38114b8c1b00e/src/BloomExe/ToPalaso/ProgressDialogForeground.cs#L61)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

I think this works, but I think it could be more straightforward as follows:

1) StartWorking becomes an async method.  (async Task StartWorkingAsync)..  Not 1,000% sure, but as far as I know, there's no problem with Application.Idle receiving an async event handler, right? 
2) I guess you can still have two overloads of ShowAndDoWork. But I'd have the first overload which takes the Action just wrap the action so that it is of type Func<IProgress, Task> and pass it to the 2nd overload. 
3) Now we just need one member variable instead of two, so get rid of the extraneous one.
4) The old StartWorking code can be simplified to:
Application.Idle -= ...
await _asyncWork(Progress)
Close();

I like that this avoids having two mutually exclusive member variables to store the work, which I wasn't a huge fan of. I think having one member variable is more understandable.

What do you think?
</blockquote></details>

Done.
___
*[`src/BloomExe/ToPalaso/ProgressDialogForeground.cs` line 38 at r7](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NRKYLeVC_JS7bGA7X81:-NRKmXLmDW11VjKmP7QI:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c779013103bba71db0e7ddc5b564b16e9f77f219/src/BloomExe/ToPalaso/ProgressDialogForeground.cs#L38)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

The parameter name "work" is now "asyncWork"
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714)* status: 14 of 41 files reviewed, 3 unresolved discussions (waiting on @jsubloom)

**Review by jsubloom — APPROVED** [review]
:lgtm:

> Reviewed 27 of 27 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-:-NRYoTWj9oJB-qiM_HLg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

___
*[`src/BloomExe/MiscUI/BrowserProgressDialog.cs` line 121 at r7](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NRKU3hcBE_1DYDA2o8_:-NRYnId5DWQYmJTENjsJ:b-a4plpw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c779013103bba71db0e7ddc5b564b16e9f77f219/src/BloomExe/MiscUI/BrowserProgressDialog.cs#L121)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think I have done this systematically through our code base, except that it did not seem useful to rename Test methods that are only ever called by NUnit. (IBrowser.UpdateDisplay is another exception, which I have commented.)
</blockquote></details>

Thanks for all the changes
___
*[`src/BloomExe/Publish/PublishView.cs` line 774 at r7](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5714#-NRKUFZn4V4AXnkvTU07:-NRYnSKZEu23qLTGqAfY:b-eke7k9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c779013103bba71db0e7ddc5b564b16e9f77f219/src/BloomExe/Publish/PublishView.cs#L774)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It can't be. The return type of an event handler is required to be void. If it is actually invoked by the event being raised, the assumption is that it doesn't matter that some of the work ends up getting put back in the queue and something else might happen in the meantime. I think that's true in this case. When it does matter, you're in trouble. I think even if you make another async method and await the result, the code after the await might still get executed in another event loop cycle and other things might happen in between.
(If something else wants to call the event handler and await it, you can of course put the relevant code into another method which the event handler also calls, and have that return Task. But that's not the case here.)
</blockquote></details>

Gotcha, thanks for explaining that.

**Pull request merged**
