### PR TITLE
BL-4237 Handle vertical alignment in text boxes

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1479)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.less, line 3 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479#-KcUp0vyULVSjUYotMxi:-KcUp0vyULVSjUYotMxj:b-6zfkyf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32da9aa73a69182cd8c5da2b96e06e693b3670e4/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.less#L3)):*
> ```Less
> #text-properties-dialog {
>     .tab-page {
>         div {
> ```

A rule hitting all divs was messing up my buttons.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 34 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479#-KcUp8qKuJVqX782bGU0:-KcUp8qKuJVqX782bGU1:bematcu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac2e1b4771e0a211f9f1c460146b4c74c70c9e18/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L34)):*
> ```XML
>         // Why do we use .off and .on? See comment in a nearly identical location in StyleEditor.ts
>         $(targetBox).off('click.formatButton');
>         $(targetBox).on('click.formatButton', '.formatButton', () => {
> ```

This change isn't strictly necessary, but I prefer using => so I don't have to keep track of changes to the meaning of 'this'

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 139 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479#-KcUpJZYfSzfk46LsMf8:-KcUpJZYfSzfk46LsMf9:b-tb328x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac2e1b4771e0a211f9f1c460146b4c74c70c9e18/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L139)):*
> ```XML
>         }
>         // Now make it so
>         if (id.startsWith('align')) {
> ```

This test isn't really necessary yet...anticipating other possible buttons.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 168 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479#-KcUpsbsgatNcRFu_Gag:-KcUpsbtu8x615VSRGXo:b-vkjfgl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac2e1b4771e0a211f9f1c460146b4c74c70c9e18/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L168)):*
> ```XML
>     }
> 
>     changeAlignment() {
> ```

This is highly dependent on bloom-translationGroup having display:flex, flex-direction: column, and height: (something like 100%, currently 100% - 2px). These are set in basePage.less so I _think_ it is safe to assume.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 171 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479#-KcUpY7g4ZYzSK_67hc_:-KcUpY7g4ZYzSK_67hca:b2hj3js) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac2e1b4771e0a211f9f1c460146b4c74c70c9e18/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L171)):*
> ```XML
>         var targetGroup = $(this.getAffectedTranslationGroup(this.boxBeingEdited));
>         if (targetGroup) {
>             var style = (targetGroup.attr('style') || '')
> ```

Is there any reason to do this with classes? I'm assuming we do NOT want all pages created from the same template page or by duplicating pages to change together.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479)*

**Comment by JohnThomson** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 99 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479#-KcUqlJbyzGz78sV1UWM:-KcUqlJc-BTcPQHW19br:b-6848wx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac2e1b4771e0a211f9f1c460146b4c74c70c9e18/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L99)):*
> ```XML
>     }
> 
>     removeButtonSelection() {
> ```

Is there a better place to put several routines like this that could be shared with StyleEditor.ts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479)*

**Comment by andrew-polk** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug, line 30 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479#-KcY3Wd07TqNGv8tTWqB:-KcY3Wd07TqNGv8tTWqC:b-gpgt2l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac2e1b4771e0a211f9f1c460146b4c74c70c9e18/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug#L30)):*
> {0}

I'm not familiar with this in pug. How does it work?

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 99 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479#-KcUqlJbyzGz78sV1UWM:-KcY28swJHs-9tmpDgQf:bcl06sm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac2e1b4771e0a211f9f1c460146b4c74c70c9e18/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L99)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is there a better place to put several routines like this that could be shared with StyleEditor.ts?
</blockquote></details>

Not yet that I know of. I had started, at one point, to make a base class which both implemented (but the decision to use pug made it less useful for what I was doing). Now would certainly be a good time to do it.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 168 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479#-KcUpsbsgatNcRFu_Gag:-KcY2zF1KiAOkG1KBe3B:b-fhgybc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac2e1b4771e0a211f9f1c460146b4c74c70c9e18/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L168)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This is highly dependent on bloom-translationGroup having display:flex, flex-direction: column, and height: (something like 100%, currently 100% - 2px). These are set in basePage.less so I _think_ it is safe to assume.
</blockquote></details>

Any way to write a js test which verifies those remain the values needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug, line 30 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479#-KcY3Wd07TqNGv8tTWqB:-KcYKSwVzKWBaqsPSPPR:b-vi7fjt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac2e1b4771e0a211f9f1c460146b4c74c70c9e18/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug#L30)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> {0}

I'm not familiar with this in pug. How does it work?
</blockquote></details>

I have no idea! My intent was to write some JavaScript which would do a simple replace of {0} with the necessary leading path, but I forgot, and somehow our image server is smart enough to make it work! Probably I can simplify it to just the file name.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 99 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479#-KcUqlJbyzGz78sV1UWM:-KcYZumA_SRneKT50aPE:bwpskl8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac2e1b4771e0a211f9f1c460146b4c74c70c9e18/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L99)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Not yet that I know of. I had started, at one point, to make a base class which both implemented (but the decision to use pug made it less useful for what I was doing). Now would certainly be a good time to do it.
</blockquote></details>

We decided you would make a card to remind us to pull out common code to a new (maybe not base?) class.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 168 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479#-KcUpsbsgatNcRFu_Gag:-KcY_4zomnCKt4OVCN_N:b-v9h8sj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac2e1b4771e0a211f9f1c460146b4c74c70c9e18/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L168)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Any way to write a js test which verifies those remain the values needed?
</blockquote></details>

A C# test would probably be easier...I'll give it some thought. Maybe a separate PR, since you're somewhat waiting on this one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug, line 30 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479#-KcY3Wd07TqNGv8tTWqB:-KcYd70cc88zVeA4j_mE:bwdudyr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac2e1b4771e0a211f9f1c460146b4c74c70c9e18/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug#L30)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I have no idea! My intent was to write some JavaScript which would do a simple replace of {0} with the necessary leading path, but I forgot, and somehow our image server is smart enough to make it work! Probably I can simplify it to just the file name.
</blockquote></details>

Ok, for StyleEditor.pug, I just hard-coded the /bloom/bookEdit/ part in a mixin, so if you find a better way, I can change it.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 99 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479#-KcUqlJbyzGz78sV1UWM:-KcYdFaeO_sVTi2vlWhx:b-993k5d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac2e1b4771e0a211f9f1c460146b4c74c70c9e18/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L99)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We decided you would make a card to remind us to pull out common code to a new (maybe not base?) class.
</blockquote></details>

Right. Doing that now.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 168 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479#-KcUpsbsgatNcRFu_Gag:-KcYdKWtElUkz93MGySI:b-t9ns8f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac2e1b4771e0a211f9f1c460146b4c74c70c9e18/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L168)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

A C# test would probably be easier...I'll give it some thought. Maybe a separate PR, since you're somewhat waiting on this one?
</blockquote></details>

That's fine. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479)*

**Comment by JohnThomson** [comment]
Review status: 5 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug, line 30 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479#-KcY3Wd07TqNGv8tTWqB:-KcYaorPmrUtyzfR1tRC:bfyhtff) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac2e1b4771e0a211f9f1c460146b4c74c70c9e18/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug#L30)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I have no idea! My intent was to write some JavaScript which would do a simple replace of {0} with the necessary leading path, but I forgot, and somehow our image server is smart enough to make it work! Probably I can simplify it to just the file name.
</blockquote></details>

Works fine with plain file names, so I've switched to that.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 168 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479#-KcUpsbsgatNcRFu_Gag:-KcYfBp92y2NaI-LvPGX:b-r5z5ow) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac2e1b4771e0a211f9f1c460146b4c74c70c9e18/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L168)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

That's fine. Thanks.
</blockquote></details>

I can't think of a good way to do it in either place (see question in flowdock). I think for now I'll merge without it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1479)*

**Pull request merged**
