### PR TITLE
Change enterprise tab message for download-for-edit (BL-13287)

### PR DESCRIPTION
**Pull request by JohnThomson**
Also fixes issues with expired and otherwise invalid subscriptions.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6424)

### CODE REVIEW

**Comment by andrew-polk** [comment]
*[`DistFiles/localization/en/Bloom.xlf` line 5281 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6424#-Nvn0pHw7y7qv2n6fmor:-Nvn0pHw7y7qv2n6fmos:b-rhjo7s) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/db7c2f3843d296d872b27959b35a8a695672643a/DistFiles/localization/en/Bloom.xlf#L5281)):*
> ```XML
>         <source xml:lang="en">This collection is in "Download for Edit" mode. The book has the same Bloom Enterprise branding as when it was last uploaded.</source>
>         <note>ID: Settings.Enterprise.DownloadForEdit</note>
>       </trans-unit>
> ```

(Maybe we're close enough now? But...)
I would set this to translate="no" and wait to remove that for all the 5.7 strings at once.

**Review by andrew-polk — COMMENTED** [review]
I need to work on a PD email, so I haven't finished but published one thing so far.

> Reviewed 1 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6424#-:-Nvn4Ds19P8AFVLrWz0i:bx5f1qk)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6424)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/Bloom.xlf` line 5281 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6424#-Nvn0pHw7y7qv2n6fmor:-NvnMEp4-tWdhiiomtiL:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/db7c2f3843d296d872b27959b35a8a695672643a/DistFiles/localization/en/Bloom.xlf#L5281)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

(Maybe we're close enough now? But...)
I would set this to translate="no" and wait to remove that for all the 5.7 strings at once.
</blockquote></details>

Done.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6424)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[`src/BloomBrowserUI/collection/enterpriseSettings.tsx` line 161 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6424#-Nvr-wRh3iR9LmXoU48i:-Nvr-wRh3iR9LmXoU48j:b-6afn6r) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ba317c3e540ceae93a838f2810bc26ed8f975729/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L161)):*
> ```XML
>                         )}
>                         {this.state.controlState === "SubscriptionDownload" && (
>                             <Markdown
> ```

Apologies if I'm just missing something, but does this message require markdown and 2 parameters?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6424)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomBrowserUI/collection/enterpriseSettings.tsx` line 161 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6424#-Nvr-wRh3iR9LmXoU48i:-Nvr3ebmBhgulqOlykzC:btk6ebl) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ba317c3e540ceae93a838f2810bc26ed8f975729/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L161)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Apologies if I'm just missing something, but does this message require markdown and 2 parameters?
</blockquote></details>

No (though I'm surprised John didn't want to mention the actual branding name). Fixed.

**Pull request merged**
