### PR TITLE
BL-12367 Help Menu Tweaks

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5925)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5925)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[`DistFiles/localization/en/Bloom.xlf` line 3010 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5925#-NXqt6uuE7mDuL0DpCM2:-NXqt6uuE7mDuL0DpCM3:b-z3mtmi) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f3d69d0e64e9daf0147da3dd13d787e8fc1a1960/DistFiles/localization/en/Bloom.xlf#L3010)):*
> ```XML
>       </trans-unit>
>       <trans-unit id="HelpMenu.DocumentationMenuItem">
>         <source xml:lang="en">Help...</source>
> ```

I really wish this wasn't true, but if we modify the source like this, all existing translations go away when we sync back from Crowdin to code (unless the translators re-translate/approve between those two actions).

Options:
1. Manually modify strings in Crowdin after the change. I don't think that's an option here since it is not obvious what the new translations should be. (Of course, we could just keep anything as is.)
2. Introduce a new ID and mark this one obsolete, to be removed in a couple versions.
___
*[`src/BloomExe/Workspace/WorkspaceView.cs` line 1026 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5925#-NXqtuSQ8rbrMnkprXx0:-NXqtuSQ8rbrMnkprXx1:b1c695t) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/46a88ad8078d40e2a98aa8465f1fb3c3641a0fd8/src/BloomExe/Workspace/WorkspaceView.cs#L1026)):*
> ```Smalltalk
> 				dlg.Width = Math.Min(1024, screenSize.Width);
> 				dlg.Height = Math.Min(768, screenSize.Height);
> 				var uriCss = new Uri(FileLocationUtilities.GetFileDistributedWithApplication("ReleaseNotes.css"));
> ```

I think we can delete the ReleaseNotes.css file now.
(Better make a quick check to ensure we didn't hijack and reuse it for Training Videos or something.)
___
*[`src/BloomExe/Workspace/WorkspaceView.Designer.cs` line 341 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5925#-NXqu6C8Cskh0y5gzwxg:-NXqu6C8Cskh0y5gzwxh:b-r5zxv3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f3d69d0e64e9daf0147da3dd13d787e8fc1a1960/src/BloomExe/Workspace/WorkspaceView.Designer.cs#L341)):*
> ```Smalltalk
> 			this._releaseNotesMenuItem.Name = "_releaseNotesMenuItem";
>             this._releaseNotesMenuItem.Size = new System.Drawing.Size(321, 34);
>             this._releaseNotesMenuItem.Text = "Release Notes (Web)";
> ```

This text change needs l10n changes, too.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5925)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/Bloom.xlf` line 3010 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5925#-NXqt6uuE7mDuL0DpCM2:-N_AhR_o-6GQyLof2c6T:bz9wyf0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f3d69d0e64e9daf0147da3dd13d787e8fc1a1960/DistFiles/localization/en/Bloom.xlf#L3010)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I really wish this wasn't true, but if we modify the source like this, all existing translations go away when we sync back from Crowdin to code (unless the translators re-translate/approve between those two actions).

Options:
1. Manually modify strings in Crowdin after the change. I don't think that's an option here since it is not obvious what the new translations should be. (Of course, we could just keep anything as is.)
2. Introduce a new ID and mark this one obsolete, to be removed in a couple versions.
</blockquote></details>

It's fine to improve English without having everything else improve. What does "modify strings" mean? If it means we have to to a re-translate, I think that's easy enough.

OK, I've just changed the string in 5.4 and then in Crowdin directly, and  Crowdin had a choice of to Keep Translations, we'll see if it all just works out.
___
*[`src/BloomExe/Workspace/WorkspaceView.cs` line 1026 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5925#-NXqtuSQ8rbrMnkprXx0:-N_AyiL92zkXTcCZeanw:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/46a88ad8078d40e2a98aa8465f1fb3c3641a0fd8/src/BloomExe/Workspace/WorkspaceView.cs#L1026)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think we can delete the ReleaseNotes.css file now.
(Better make a quick check to ensure we didn't hijack and reuse it for Training Videos or something.)
</blockquote></details>

Done.
___
*[`src/BloomExe/Workspace/WorkspaceView.Designer.cs` line 341 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5925#-NXqu6C8Cskh0y5gzwxg:-N_Aygw_4z2CRdB2Lq8U:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f3d69d0e64e9daf0147da3dd13d787e8fc1a1960/src/BloomExe/Workspace/WorkspaceView.Designer.cs#L341)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This text change needs l10n changes, too.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5925)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hatton)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5925)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hatton)

**Pull request merged**
