### PR TITLE
BL-4955 Add analytics for publish to Android

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1836)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Android/PublishToAndroidApi.cs, line 118 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1836#-KtIp_5lGs7gXBITi7pi:-KtIp_5lGs7gXBITi7pj:b-j5l06c) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a887331bf69ab90383b388096889a3006c605310/src/BloomExe/Publish/Android/PublishToAndroidApi.cs#L118)):*
> ```Smalltalk
> 		public static void ReportAnalytics(string mode, Book.Book book)
> 		{
> 			Analytics.Track("Publish Android", new Dictionary<string, string>() {{"mode", mode}, {"title", book.Title}, {"country", book.CollectionSettings.Country}});
> ```

I notice that "Save ePUB" and "Print PDF" report:
```
{"BookId", BookSelection.CurrentSelection.ID},
{"Country", _collectionSettings.Country}
```
Is the bookId preferrable? Should we keep the key capitalization consistent?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1836)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Android/PublishToAndroidApi.cs, line 118 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1836#-KtIp_5lGs7gXBITi7pi:-KtIrD3M_uxipFil8Vjv:bbf906z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a887331bf69ab90383b388096889a3006c605310/src/BloomExe/Publish/Android/PublishToAndroidApi.cs#L118)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I notice that "Save ePUB" and "Print PDF" report:
```
{"BookId", BookSelection.CurrentSelection.ID},
{"Country", _collectionSettings.Country}
```
Is the bookId preferrable? Should we keep the key capitalization consistent?
</blockquote></details>

How would you use the bookId?  FOr that matter, how would we use book title? 

I can however see liking to see the languages.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1836)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Android/PublishToAndroidApi.cs, line 118 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1836#-KtIp_5lGs7gXBITi7pi:-KtIu9n0Kmgf8018Y3HP:baj1s3x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a887331bf69ab90383b388096889a3006c605310/src/BloomExe/Publish/Android/PublishToAndroidApi.cs#L118)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

How would you use the bookId?  FOr that matter, how would we use book title? 

I can however see liking to see the languages.
</blockquote></details>

Yes, and uploading to BL tracks URL and title.
I can imagine someone like ACR being very interested in which books got loaded into readers and how often. Whether we identify that by Title or BookID, I don't know, but one or the other seems potentially useful. Title is a lot more legible. But you're right that BookId has consistency in its favor.
Unless I hear otherwise, I'll change it to BookId and Country.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1836)*

**Comment by JohnThomson** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Android/PublishToAndroidApi.cs, line 118 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1836#-KtIp_5lGs7gXBITi7pi:-KtMtV6Ic1fur27cgMew:b-3g3ais) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a887331bf69ab90383b388096889a3006c605310/src/BloomExe/Publish/Android/PublishToAndroidApi.cs#L118)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Yes, and uploading to BL tracks URL and title.
I can imagine someone like ACR being very interested in which books got loaded into readers and how often. Whether we identify that by Title or BookID, I don't know, but one or the other seems potentially useful. Title is a lot more legible. But you're right that BookId has consistency in its favor.
Unless I hear otherwise, I'll change it to BookId and Country.
</blockquote></details>

OK, now pushing BookId, Country, and Language

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1836)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1836#-:-KtNJY9Lxnu20eoRIZS6:bnfp4nl)*

**Pull request merged**
