### PR TITLE
Fix pageChooser error if path to Bloom has punctuation in it (BL-9109)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3989)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3989)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[src/BloomBrowserUI/pageChooser/page-chooser.ts, line 713 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3989#-MItuNdkBJIV1fnO8GXA:-MItuNdl3A_zNs0FZMaL:boqikiy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/58b0cd4b8e957e39335fd2bde8fcb0d7f63a8577/src/BloomBrowserUI/pageChooser/page-chooser.ts#L713)):*
> ```XML
>             encodeURIComponent(templateBookFolderUrl) +
>             "/template/" +
>             encodeURIComponent(label) +
> ```

This is not strictly required, it wasn't causing an error even without encoding, but it seemed ideal to encode a string that is allowed to have punctuation it.

**Review by JohnThomson — APPROVED** [review]
Seems that if we are adding code to encode something, we should need code somewhere to decode it.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3989#-:-MItxCDo8rSls-CQ_uxY:b60agrc)* status: all files reviewed, 1 unresolved discussion

**Review by sujeffreyl — COMMENTED** [review]
Actually, the error is caused because BloomServer decodes an unencoded string.  Bloom.Api.RequestInfo already has the decoding logic.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3989#-:-MItxbpXC9jMj9c-TOi9:b-mijgz6)* status: all files reviewed, 1 unresolved discussion

**Review by JohnThomson — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3989)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
