### PR TITLE
Bl 2960 Move Talking Book controls to toolbox

### PR DESCRIPTION
**Pull request by JohnThomson**
There are several changes here, including bug fixes to earlier work and implementation of new features ('listen' to whole page, Clear unwanted recording). May be easier to review one commit at a time. I've tried to only do one main thing in each commit, but some include minor bug fixes also.

[Review on Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/899)

### CODE REVIEW

**Comment by hatton** [comment]
Reviewed 39 of 44 files at r1.
Review status: 39 of 44 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 767 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/899#-K5g_HgOywPkMbunzwxo:-K5g_HgOywPkMbunzwxp:-218376105) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/11d685e5789270d26a6caade92516342be1080be/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L767)):*
I assume libsynphony is being used to detect sentence boundaries?

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.less, line 54 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/899#-K5gajTSnzZVkGOfUkl7:-K5gajTSnzZVkGOfUkl8:580435115) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/11d685e5789270d26a6caade92516342be1080be/src/BloomBrowserUI/bookEdit/toolbox/toolbox.less#L54)):*
Can we have each tool have its own stylesheet?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/899)*

**Comment by hatton** [comment]
Reviewed 4 of 44 files at r1.
Review status: 43 of 44 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Edit/EditingModel.cs, line 852 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/899#-K5gbEOGIalZMBCi6XM4:-K5gbEOGIalZMBCi6XM5:1398081932) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/11d685e5789270d26a6caade92516342be1080be/src/BloomExe/Edit/EditingModel.cs#L852)):*
I don't know about this case, but it's common to find that a file is already gone; would this tell the user that it had a problem deleting if it was just missing?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/899)*

**Comment by hatton** [comment]
I saw several places where things are considerably cleaner now. Thanks!

---

Reviewed 1 of 44 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/899#-:-K5gd03yL4VSVEdBgM0u:376648194)*

**Comment by hatton** [comment]
I'm going to merge this now, but please look at my comments an add new cards to the "ready for work" for any that you want to address.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/899#-:-K5gdO4BNGA8lzqQnuW5:260427104)*

**Comment by JohnThomson** [comment]
I don't think any definitely need attention. We could try to split readerTools.less (and many other things) into separate components for decodable and leveled readers.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 767 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/899#-K5g_HgOywPkMbunzwxo:-K5ge3au9brxyLiaG8RH:266713857) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/11d685e5789270d26a6caade92516342be1080be/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L767)):*
Right. We probably want to substitute something better at some point, but it would probably be less confusing to change it for both tools at once.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.less, line 54 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/899#-K5gajTSnzZVkGOfUkl7:-K5gePkp9wRaeUz6Cqq-:1137213815) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/11d685e5789270d26a6caade92516342be1080be/src/BloomBrowserUI/bookEdit/toolbox/toolbox.less#L54)):*
We have audioRecording.less for the talking book stuff, and readerTools.less for the other two. This file is (in my intention, at least) for things that affect the whole toolbox, like icons that are always visible. Stuff in toobox.less is (or should be...I haven't carefully checked) styles we would  need to load whatever tool is open.

---

*[src/BloomExe/Edit/EditingModel.cs, line 852 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/899#-K5gbEOGIalZMBCi6XM4:-K5gfb05Cuobz6Kgm5Vk:2064853303) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/11d685e5789270d26a6caade92516342be1080be/src/BloomExe/Edit/EditingModel.cs#L852)):*
No. Expanding two lines up will show that we don't even attempt to delete unless the file exists.
It's actually quite likely that it doesn't in this case. I haven't tried to enable or disable this button based on whether there is a recording.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/899#-:-K5gfwxjbh2KPRbqMkZq:2102511418)*

**Pull request merged**
