### PR TITLE
[5.5] BL-12249 Make All BloomPUBs dialog

### PR DESCRIPTION
**Pull request by gmartin7**
* fix scrolling of dialog
* fix layout of ConditionallyEnabledBlock

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5884)

### CODE REVIEW

**Review by gmartin7 — COMMENTED** [review]
In UI Review

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5884#-:-NWOVJQ_52r254pUnLTu:bafp69a)* status: 0 of 1 files reviewed, all discussions resolved

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5884)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/publish/ReaderPublish/BulkBloomPub/BulkBloomPubDialog.tsx` line 113 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5884#-NWsyBdv3LUcpPTSrync:-NWsyBdv3LUcpPTSrynd:b-dnefb0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d5929249343a6ced8875e74b3da29c7daa3a5658/src/BloomBrowserUI/publish/ReaderPublish/BulkBloomPub/BulkBloomPubDialog.tsx#L113)):*
> ```XML
>                     <div
>                         css={css`
>                             // don't let this get a scrollbar
> ```

Can you say a little more? Does adding padding somehow make a scrollbar less likely? Or are you reducing some default padding?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5884)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/publish/ReaderPublish/BulkBloomPub/BulkBloomPubDialog.tsx` line 113 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5884#-NWsyBdv3LUcpPTSrync:-NWxCJ3g6sylFmcIOKIu:bbq04vu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d5929249343a6ced8875e74b3da29c7daa3a5658/src/BloomBrowserUI/publish/ReaderPublish/BulkBloomPub/BulkBloomPubDialog.tsx#L113)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Can you say a little more? Does adding padding somehow make a scrollbar less likely? Or are you reducing some default padding?
</blockquote></details>

Thanks for pushing back on this. The actual problem was the `WhatsThisBlock` component, which had too much vertical padding. This padding is coming from some MUI component that was used in creating the `BloomButton`. As commented in the fixed code, reducing the vertical padding by 1px top and bottom on the `BloomButton` component in the `WhatsThisBlock` was enough to fix the issue.

There was another option of increasing the `top: 0;` rule on the button to something like `top: 6px;` and then setting padding-top and -bottom to 0, but then the hover button background looked really skinny vertically. The advantage of the 2nd option was that the `What's This?` label wasn't above the element it referred to so much... Oh well. I think the first option is better.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5884)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
