### PR TITLE
Fix digitally published back cover for Kyrgyz (BL-10053)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4538)

### CODE REVIEW

**Review by hatton — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4538)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Review by JohnThomson — APPROVED** [review]
lgtm with one minor suggestion

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4538#-:-MbcaHZfAwPvIqGBVM1Z:b-3xej0k)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookLayout/basePage-sharedRules.less, line 15 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4538#-Mbc_Up78vuSLi35nVob:-Mbc_Up78vuSLi35nVoc:b-z9v01v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/213503c105765bd7c0bc50cec89bdf03f3b195cd/src/BloomBrowserUI/bookLayout/basePage-sharedRules.less#L15)):*
> ```Less
>     // visible .bloom-editables are made display:flex rather than display:none
>     // to allow for possible vertical alignment options. Once using display:flex,
>     // the direction must be column, or paragraphs arrange in a row.
> ```

Worth adding something like, "We try not to use display:flex in epubs, because some readers don't handle it. But it can easily sneak into custom xmatter and similar things, and then without this rule we get an unexpected row behavior in readers that DO handle it."

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4538)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @hatton and @JohnThomson)

___
*[src/BloomBrowserUI/bookLayout/basePage-sharedRules.less, line 15 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4538#-Mbc_Up78vuSLi35nVob:-Mbce5H89epQ_Pf1MzS-:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/213503c105765bd7c0bc50cec89bdf03f3b195cd/src/BloomBrowserUI/bookLayout/basePage-sharedRules.less#L15)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Worth adding something like, "We try not to use display:flex in epubs, because some readers don't handle it. But it can easily sneak into custom xmatter and similar things, and then without this rule we get an unexpected row behavior in readers that DO handle it."
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
> Dismissed @JohnThomson from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4538)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @hatton and @JohnThomson)

**Pull request merged**
