### PR TITLE
Check connection on each TC operation (BL-9748)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4336)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4336)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 252 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4336#-MXdKTrNB4tEwcrF4IaP:-MXdKTrNB4tEwcrF4IaQ:b-7n6zc9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6b25ce9a252d13921ca4b0989a2d7a85c561da14/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L252)):*
> ```Smalltalk
> 
> 			return true;
> 		}
> ```

I'm not sure what the right answer is...
And I know most of this logic was already here previous to this PR...
But it seems we keep inching away from keeping the specific folder stuff in FolderTeamCollection.
Anything we can do about that?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4336)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 252 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4336#-MXdKTrNB4tEwcrF4IaP:-MXgVcZvC-fP5BwjZ5sD:b8pg11y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6b25ce9a252d13921ca4b0989a2d7a85c561da14/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L252)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not sure what the right answer is...
And I know most of this logic was already here previous to this PR...
But it seems we keep inching away from keeping the specific folder stuff in FolderTeamCollection.
Anything we can do about that?
</blockquote></details>

I found a way

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4336)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 793 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4336#-MXgtlQx3PxgqJCodq7U:-MXgtlQyCUmoBSPcPGkQ:b-tnhewb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/84cfc01bbfba55e1a8ad250deacd7e0adca5ef74/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L793)):*
> ```
> �Join this Team Collection�.
> ```
Somehow, when these got copied to their new location, they became replacement characters. Perhaps it is just Reviewable doing something strange, but it shows them correctly in the removed code in TCManager.
Anyway... maybe we just want straight double quotes for safety?
___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 252 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4336#-MXdKTrNB4tEwcrF4IaP:-MXguVYOAEOvDMnUA_VC:b-1el1uf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6b25ce9a252d13921ca4b0989a2d7a85c561da14/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L252)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I found a way
</blockquote></details>

Thanks. Nicely done!

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4336)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 793 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4336#-MXgtlQx3PxgqJCodq7U:-MXhGMjI-NgHmhVXZVWl:b-6mw5ul) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/84cfc01bbfba55e1a8ad250deacd7e0adca5ef74/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L793)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> �Join this Team Collection�.
> ```
Somehow, when these got copied to their new location, they became replacement characters. Perhaps it is just Reviewable doing something strange, but it shows them correctly in the removed code in TCManager.
Anyway... maybe we just want straight double quotes for safety?
</blockquote></details>

Done. (They showed up as smart double quotes in Visual Studio...but I agree, simple ones are safer.)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4336)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
