### PR TITLE
BL-9585 Bloomds of Templates should stick with the template xmatter

### PR DESCRIPTION
**Pull request by hatton**
This looks like a lot of changes, but all it is is plumbing of one bit through a bunch of methods.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4213)

### CODE REVIEW

**Review by StephenMcConnel — CHANGES_REQUESTED** [review]
One question, which could be answered "no".  :-)  Otherwise, it all looks okay.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4213#-:-MTvM0IwEjch_EXU1SDI:bn7cggq)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomTests/Publish/BloomReaderPublishTests.cs, line 1328 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4213#-MTvLkCy0SjGNMs2QCxY:-MTvLkCy0SjGNMs2QCxZ:b-v7cwij) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/629a9c1c841ea08cb786a06a1e554d2988a73503/src/BloomTests/Publish/BloomReaderPublishTests.cs#L1328)):*
> ```Smalltalk
> 			{
> 				BloomReaderFileMaker.CreateBloomDigitalBook(bloomdTempFile.Path, testBook.FolderPath, _bookServer, Color.Azure, new NullWebSocketProgress(),
> 					isTemplateBook: false, creator: creator, 
> ```

Would a unit test with isTemplateBook: true be worthwhile?

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4213)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomTests/Publish/BloomReaderPublishTests.cs, line 1328 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4213#-MTvLkCy0SjGNMs2QCxY:-MTvOiEx0H_f5AVtdWbn:b-ccdv4g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/629a9c1c841ea08cb786a06a1e554d2988a73503/src/BloomTests/Publish/BloomReaderPublishTests.cs#L1328)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Would a unit test with isTemplateBook: true be worthwhile?
</blockquote></details>

Fair question. I decided it's not worth it to test a one-bit thing because if we break it, it will be easy to see and the cost is negligible. As the reviewer, you have every right to say "Go do it", though :-)

**Review by StephenMcConnel — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4213#-:-MTvvXhu3xBuWB9kTx8_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by StephenMcConnel — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4213)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hatton)

**Pull request merged**
