### PR TITLE
Fix BL-3078 Bubbles in simple front/back matter lost after 1st use

### PR DESCRIPTION
**Pull request by hatton**
[Review on Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/953)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Book/BookData.cs, line 756 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/953#-KBIfM9NBdwqlVAZbkFk:-KBIfM9NBdwqlVAZbkFl:1567800229) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ec9f8c5ab2699f5fd16eb162a697514a89453097/src/BloomExe/Book/BookData.cs#L756)):*
the->they

---

*[src/BloomExe/Book/BookData.cs, line 767 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/953#-KBIfaY5E3OSuvUWve6X:-KBIfaY5E3OSuvUWve6Y:-523389427) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ec9f8c5ab2699f5fd16eb162a697514a89453097/src/BloomExe/Book/BookData.cs#L767)):*
I suppose it's always right for the label if any to come at the end?

---

*[src/BloomTests/Book/BookDataTests.cs, line 1038 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/953#-KBIfrqgJ3zeUMmN4Um7:-KBIfrqgJ3zeUMmN4Um8:747321329) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ec9f8c5ab2699f5fd16eb162a697514a89453097/src/BloomTests/Book/BookDataTests.cs#L1038)):*
It's not clear from the comment on the main method whether we need to preserve the content of the label, or just the fact that it's present. But the test begins with a non-empty label, so if the intent is to keep the content, seems it would be worth verifying that.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/953)*

**Comment by hatton** [comment]
Stuff like this is maybe why other people don't write unit tests as often as I do... if reviews then talk about how the test could be even better!

**Comment by hatton** [comment]
OK, added test for contents of the label.

**Comment by hatton** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Book/BookData.cs, line 767 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/953#-KBIfaY5E3OSuvUWve6X:-KBIrPiHSNMj2OvheWCX:1270130335) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ec9f8c5ab2699f5fd16eb162a697514a89453097/src/BloomExe/Book/BookData.cs#L767)):*
it's allright

---

*[src/BloomTests/Book/BookDataTests.cs, line 1038 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/953#-KBIfrqgJ3zeUMmN4Um7:-KBIrUGVw3zMXkgumFtc:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ec9f8c5ab2699f5fd16eb162a697514a89453097/src/BloomTests/Book/BookDataTests.cs#L1038)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/953)*

**Pull request merged**
