### PR TITLE
Bulk Upload: dry-run as a flag instead of a destination

### PR DESCRIPTION
**Pull request by jsubloom**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5626)

### CODE REVIEW

**Review by jsubloom — COMMENTED** [review]
I didn't realize it when I made my initial fix, but then a thought struck me: Why was DryRun a destination? Isn't it normally an extra flag? And if it were a flag, JH's initial version of the check would've worked perfectly fine without  me making the check more complicated.

So i tried making it a flag.
Old Command:
Bloom.exe upload "[path]" --user [userEmail] --destination dry-run

New Command:
Bloom.exe upload "[path]" --user [userEmail] --destination dev --dry-run

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5626#-:-NNrJuqF1hc1xcQ5qugL:bmng6h3)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @andrew-polk and @StephenMcConnel)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5626)* status: all files reviewed, 1 unresolved discussion (waiting on @jsubloom and @StephenMcConnel)

___
*[`src/BloomExe/CLI/UploadCommand.cs` line 122 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5626#-NNrKfG52Qc0H9M4AZLU:-NNrKfG52Qc0H9M4AZLV:b-onz540) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2925a8338a0fa1572c26ac675c6b0336ce4f2246/src/BloomExe/CLI/UploadCommand.cs#L122)):*
> ```Smalltalk
> 
> 	[Option("dry-run", Default=false, HelpText = "If present, performs a dry-run (will just print out what would happen).", Required = false)]
> 	public bool DryRun { get; set; }
> ```

It scares me a bit to go from dry run being the default to not.
I guess you've evaluated the places we run this to ensure there are no surprises?

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5626)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @StephenMcConnel)

___
*[`src/BloomExe/CLI/UploadCommand.cs` line 122 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5626#-NNrKfG52Qc0H9M4AZLU:-NNrLDSOBpBjl-50E_A9:b-mvkg96) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2925a8338a0fa1572c26ac675c6b0336ce4f2246/src/BloomExe/CLI/UploadCommand.cs#L122)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

It scares me a bit to go from dry run being the default to not.
I guess you've evaluated the places we run this to ensure there are no surprises?
</blockquote></details>

Yeah... it's an interesting question.
Well, apparently for 2+ years nobody ran it in the default mode!!!  (unless they figured out how to get the old code to run in dry-run mode better than me)  They probably explicitly specified the destination

For the CLI, the default goes to Dev now. That mitigates some of the risk

For the BookUpload class: while in terms of the CLI, the default if you don't specify it is false... if you neglect to tell BookUpload at all, the default is true.
Actually, I probably broke some tests that expect it to be false...

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5626)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @StephenMcConnel)

___
*[`src/BloomExe/CLI/UploadCommand.cs` line 122 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5626#-NNrKfG52Qc0H9M4AZLU:-NNrQ0Ys7oZHTMvQzhiW:b-dg6f23) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2925a8338a0fa1572c26ac675c6b0336ce4f2246/src/BloomExe/CLI/UploadCommand.cs#L122)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

Yeah... it's an interesting question.
Well, apparently for 2+ years nobody ran it in the default mode!!!  (unless they figured out how to get the old code to run in dry-run mode better than me)  They probably explicitly specified the destination

For the CLI, the default goes to Dev now. That mitigates some of the risk

For the BookUpload class: while in terms of the CLI, the default if you don't specify it is false... if you neglect to tell BookUpload at all, the default is true.
Actually, I probably broke some tests that expect it to be false...
</blockquote></details>

fixed the unit tests

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5626)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
