### PR TITLE
BL-4197 Catch HRESULT E_FAIL

### PR DESCRIPTION
**Pull request by gmartin7**
Advice on how to write a test for this is welcome. I couldn't figure out how to do it.

This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1759)

### CODE REVIEW

**Comment by JohnThomson** [comment]
ErrorReport probably already has framework for verifying expected errors in testing? If so, can't you test by just making a selection for a nonexistent file?
LGTM so far.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1759#-:-Kpoly3cDh22qWRm753-:blh0jks)*

**Comment by gmartin7** [comment]
So it does. I tried to do without one of the methods, but I needed to be able to set the path to something that existed to test the right thing.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1759#-:-Kpp_l4IQ2O2uPO_VxlP:byb83ys)*

**Comment by hatton** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/CollectionTab/LibraryModel.cs, line 196 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1759#-KpphwtV48nn005sv-XE:-KpphwtV48nn005sv-XF:bw5hcj5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/64e6b491da053b5516f5ac462cd9a78133ad5528/src/BloomExe/CollectionTab/LibraryModel.cs#L196)):*
> ```Smalltalk
> 			{
> 				SIL.Reporting.ErrorReport.NotifyUserOfProblem(e,
> 					"Bloom ran into an error while trying to open that book. (Sorry!) We suggest closing and reopening Bloom.");
> ```

At this point, Bloom is *not* opening the book. It is talking to Windows Explorer.  How about "Bloom had a problem asking you operating system to show that folder."  --- no advice needed, since we don't really know what cause it or how to fix it.

---

*[src/BloomTests/CollectionTab/LibraryModelTests.cs, line 211 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1759#-KppiWPDrJtnCUiuKMgy:-KppiWPDrJtnCUiuKMgz:b-z80jul) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/64e6b491da053b5516f5ac462cd9a78133ad5528/src/BloomTests/CollectionTab/LibraryModelTests.cs#L211)):*
> ```Smalltalk
> 
> 		[Test]
> 		public void OpenFolderOnDisk_CatchCOMError()
> ```

I think these tests are don't add any value. Appreciate the willingness to write tests though!

---

*[src/BloomTests/CollectionTab/TestLibraryModel.cs, line 12 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1759#-Kppi_Mn77kLDG2zh9pB:-Kppi_Mn77kLDG2zh9pC:b-unv6my) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/64e6b491da053b5516f5ac462cd9a78133ad5528/src/BloomTests/CollectionTab/TestLibraryModel.cs#L12)):*
> ```Smalltalk
> 	{
> 		public readonly string TestFolderPath;
> 		public bool ThrowCOMError { private get; set; }
> ```

I think this doesn't add any value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1759)*

**Comment by gmartin7** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/CollectionTab/LibraryModel.cs, line 196 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1759#-KpphwtV48nn005sv-XE:-Kppniqh7pz6RD4OpxzN:b-h64nxg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/64e6b491da053b5516f5ac462cd9a78133ad5528/src/BloomExe/CollectionTab/LibraryModel.cs#L196)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

At this point, Bloom is *not* opening the book. It is talking to Windows Explorer.  How about "Bloom had a problem asking you operating system to show that folder."  --- no advice needed, since we don't really know what cause it or how to fix it.
</blockquote></details>

You told the user that closing and reopening Bloom helped you when you had the problem once.

---

*[src/BloomTests/CollectionTab/LibraryModelTests.cs, line 211 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1759#-KppiWPDrJtnCUiuKMgy:-KppnYNF2FJYcVtXhOqC:b-81taoq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/64e6b491da053b5516f5ac462cd9a78133ad5528/src/BloomTests/CollectionTab/LibraryModelTests.cs#L211)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think these tests are don't add any value. Appreciate the willingness to write tests though!
</blockquote></details>

reverted.

---

*[src/BloomTests/CollectionTab/TestLibraryModel.cs, line 12 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1759#-Kppi_Mn77kLDG2zh9pB:-Kppn_J8PCsZeuF-h3wk:b-81taoq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/64e6b491da053b5516f5ac462cd9a78133ad5528/src/BloomTests/CollectionTab/TestLibraryModel.cs#L12)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think this doesn't add any value.
</blockquote></details>

reverted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1759)*

**Comment by gmartin7** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/CollectionTab/LibraryModel.cs, line 196 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1759#-KpphwtV48nn005sv-XE:-KpqEVV6Y8cBgnhNv5On:bqa9i99) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/64e6b491da053b5516f5ac462cd9a78133ad5528/src/BloomExe/CollectionTab/LibraryModel.cs#L196)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

You told the user that closing and reopening Bloom helped you when you had the problem once.
</blockquote></details>

Your comment on the issue was: Let's catch this error and tell people to restart their computer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1759)*

**Pull request merged**
