### PR TITLE
Change upload API - client sends files and hashes (BL-12568)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Draft because it must be coordinated with the azure function side (https://github.com/BloomBooks/bloom-azure-functions/pull/72).

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252)* status: 0 of 7 files reviewed, 2 unresolved discussions

___
*[`src/BloomExe/WebLibraryIntegration/BloomS3Client.cs` line 473 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-NoNGRAP-IUS7lVIlkfP:-NoNGRAQ2ARO20Lf4phr:b-q8v28j) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e4cd18819af374fe0418855ee311e9bbea919d1/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L473)):*
> ```Smalltalk
>                 Path.GetExtension(localFilePath).ToLowerInvariant()
>             );
>         }
> ```

These were already not needed since we implemented the white list (BookFileFilter).

But it was handling one thing kinda by accident. It was still actively preventing meta.bak from being uploaded. See changes in `RemoveUnwantedLanguageData` and `BookInfo.cs` which now handle this.
___
*[`src/BloomExe/WebLibraryIntegration/BookUpload.cs` line 300 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-NoNHepDEH5Ubamul1OM:-NoNHepDEH5Ubamul1ON:bpnakog) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/edaa6773add27c04d505300f784f8a4733fcc514/src/BloomExe/WebLibraryIntegration/BookUpload.cs#L300)):*
> ```Smalltalk
>                         List<FilePathAndHash> existingBookFiles = null;
>                         if (!isNewBook)
>                             existingBookFiles = GetStagedFiles(stagingDirectory);
> ```

I struggled with this.

For new books, we could just follow the pattern of existing books. We would send the list of all book files, and the API would return that same exact list. That seems like a waste of bandwidth.

On the other hand, we like the idea of having the azure function be the controller. And the only way to let that happen is to send this list back and forth.
I think we even discussed the possibility that the function could become smart enough to restart a failed upload. If that failed upload was for a new book, the only way to achieve that would be for the file list to get sent/received even for new books.

Please give any thoughts or suggestions.
___
*[`src/BloomExe/WebLibraryIntegration/BookUpload.cs` line 493 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-NoNHEuI4VxhJcE3o9QI:-NoNHEuJ-tlJklX6WoE0:b-yredv0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/edaa6773add27c04d505300f784f8a4733fcc514/src/BloomExe/WebLibraryIntegration/BookUpload.cs#L493)):*
> ```Smalltalk
> 
>         // Copy the needed files to the staging directory and make any modifications needed before upload.
>         private string SetUpStaging(
> ```

This method is essentially the old BloomS3Client.UploadBook with the following changes:
1. The parent creates the staging temp folder and passes in the path.
2. At the end, we simply return the staged book dir rather than call SyncBookFiles.
___
*[`src/BloomExe/WebLibraryIntegration/BookUpload.cs` line 543 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-NoNH0641VSOZ6uZ80zf:-NoNH0641VSOZ6uZ80zg:b-g166bv) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/edaa6773add27c04d505300f784f8a4733fcc514/src/BloomExe/WebLibraryIntegration/BookUpload.cs#L543)):*
> ```Smalltalk
>         }
> 
>         private void ProcessVideosInTempDirectory(string destDirName)
> ```

This method was moved from BloomS3Client unchanged.
___
*[`src/BloomExe/WebLibraryIntegration/BookUpload.cs` line 566 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-NoNH3bd0iJLlcyzaEnL:-NoNH3bd0iJLlcyzaEnM:b-g166bv) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/edaa6773add27c04d505300f784f8a4733fcc514/src/BloomExe/WebLibraryIntegration/BookUpload.cs#L566)):*
> ```Smalltalk
>         /// See BL-12583.
>         /// </remarks>
>         private static void CopyCollectionSettingsToTempDirectory(
> ```

This method was moved from BloomS3Client unchanged.
___
*[`src/BloomExe/WebLibraryIntegration/BookUpload.cs` line 586 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-NoNH5HKDtRFyeUmaNdx:-NoNH5HKDtRFyeUmaNdy:bybak91) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/edaa6773add27c04d505300f784f8a4733fcc514/src/BloomExe/WebLibraryIntegration/BookUpload.cs#L586)):*
> ```Smalltalk
>         }
> 
>         private void RemoveUnwantedLanguageData(
> ```

This method was moved from BloomS3Client with one change:
on the last line, I added the `makeBackup:false` parameter to `WriteToFolder`.

**Review by hatton — COMMENTED** [review]
> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs` line 171 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-NoODlMO3cVOYz3VCdmB:-NoODlMO3cVOYz3VCdmC:b-rkrbb9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/edaa6773add27c04d505300f784f8a4733fcc514/src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs#L171)):*
> ```Smalltalk
>                 request.AddQueryParameter("existing-book-object-id", existingBookObjectId);
>                 // If uploading an existing book, we give the server a list of files and their hashes.
>                 // Format is `files: [{ "path": "abc", "hash": "123" }, ...]`
> ```

If you want you could update this to include this `files-prefix` but it's not a big deal
___
*[`src/BloomExe/WebLibraryIntegration/BloomS3Client.cs` line 284 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-NoOFI534yUCnIBUQRYK:-NoOFI534yUCnIBUQRYL:b-a940ji) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/edaa6773add27c04d505300f784f8a4733fcc514/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L284)):*
> ```Smalltalk
>         }
> 
>         public static string GetEtag(string filePath)
> ```

worth a comment maybe pointing to how we know these are just md5's of the whole file?  [This blog](https://teppen.io/2018/06/23/aws_s3_etags/) makes it seem more complicated

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/WebLibraryIntegration/BookUpload.cs` line 300 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-NoNHepDEH5Ubamul1OM:-NoOGIg3EYBdgigOQMk0:b-x9y9qo) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/edaa6773add27c04d505300f784f8a4733fcc514/src/BloomExe/WebLibraryIntegration/BookUpload.cs#L300)):*
> That seems like a waste of bandwidth.

I would think it is so small that whatever is easier to code/maintain/reason about is preferred.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/WebLibraryIntegration/BookUpload.cs` line 278 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-NoOGTxHCxk3xOVhBkFV:-NoOGTxHCxk3xOVhBkFW:b-c0fjmz) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/edaa6773add27c04d505300f784f8a4733fcc514/src/BloomExe/WebLibraryIntegration/BookUpload.cs#L278)):*
> ```Smalltalk
> 
>                     // This currently (unfortunately) enforces a single upload at a time.
>                     // We considered modifying it now, but decided we would discover the problem
> ```

I'm not following this comment: we would discover *what* problem?

**Review by JohnThomson — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252)* status: all files reviewed, 6 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomExe/WebLibraryIntegration/BookUpload.cs` line 278 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-NoOGTxHCxk3xOVhBkFV:-NoOUFmG3kHgWdGSH7tY:b-oqk6o3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/edaa6773add27c04d505300f784f8a4733fcc514/src/BloomExe/WebLibraryIntegration/BookUpload.cs#L278)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I'm not following this comment: we would discover *what* problem?
</blockquote></details>

That they are all trying to use the same staging directory.
___
*[`src/BloomExe/WebLibraryIntegration/BookUpload.cs` line 300 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-NoNHepDEH5Ubamul1OM:-NoO8LfL3vxyLpMcJ8bG:b-55wcg9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/edaa6773add27c04d505300f784f8a4733fcc514/src/BloomExe/WebLibraryIntegration/BookUpload.cs#L300)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

> That seems like a waste of bandwidth.

I would think it is so small that whatever is easier to code/maintain/reason about is preferred.
</blockquote></details>

It could be a useful optimization to not have to compute checksums and send them back and forth for new books. I don't know how often books get re-uploaded, but it would not surprise me if first-time uploads are a majority, perhaps even by a good margin. Any idea how long it takes to compute this sort of checksum for a large book full of files?

If we one day implement restartable, I would expect things to begin with a call rather like the one that currently asks "is this an existing book". It would have a three-way answer, new, existing, or incomplete. Existing or incomplete would both result in sending the list of files and checksums and getting back a list of what to upload. (I think 'incomplete' should only be used for new books. Bloom probably needs to know that it is attempting to upload an existing book. If there has already been an incomplete attempt to upload an existing book, the server function can just quietly take advantage of any files already successfully copied or uploaded to shrink the list of things to upload this time. Elegantly, since we're sending the checksums, we can continue an incomplete upload even if the book has been edited. We just need the server to checksum any files in the staging area.)

OTOH, it would definitely be simpler if this code didn't even have to think about whether the book is new and/or being retried. It just tells the server, I want the book to consist of these files with these checksums. And the server tells it what needs uploading. Quite possibly the client doesn't have to change at all to make it restartable. It would be nice to be able to ship restartability any time, without having to wait for a new client to make it to release.

So I think I'm voting for "always send the list" unless we have evidence that the cost of computing the checksums and sending the extra data is likely to be a significant part of the upload time (say, more than 5%? 10%?)
___
*[`src/BloomTests/WebLibraryIntegration/BloomS3StandardUpDownloadTests.cs` line 89 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-NoOTB-1D6wztSWvTqrj:-NoOTB-1D6wztSWvTqrk:bjh1qjt) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e4cd18819af374fe0418855ee311e9bbea919d1/src/BloomTests/WebLibraryIntegration/BloomS3StandardUpDownloadTests.cs#L89)):*
> ```Smalltalk
>             File.WriteAllText(Path.Combine(bookFolder, "one.css"), @"test");
>             File.WriteAllText(Path.Combine(bookFolder, "preview.pdf"), @"test pdf file");
>             File.WriteAllText(Path.Combine(bookFolder, "extra.pdf"), @"unwanted pdf file");
> ```

I'm not clear why we no longer need to test that unwanted stuff is not getting sent. Maybe you're just satisfied with testing of the file filter elsewhere? Or maybe I missed some equivalent new test?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252)* status: all files reviewed, 5 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`src/BloomExe/WebLibraryIntegration/BloomS3Client.cs` line 284 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-NoOFI534yUCnIBUQRYK:-NoOY0gjEu_Hw_6cp3UP:b-bpbrrt) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/edaa6773add27c04d505300f784f8a4733fcc514/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L284)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

worth a comment maybe pointing to how we know these are just md5's of the whole file?  [This blog](https://teppen.io/2018/06/23/aws_s3_etags/) makes it seem more complicated
</blockquote></details>

Does that help?
___
*[`src/BloomExe/WebLibraryIntegration/BookUpload.cs` line 278 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-NoOGTxHCxk3xOVhBkFV:-NoORmYv2gaUNKCewwpe:bxqjm44) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/edaa6773add27c04d505300f784f8a4733fcc514/src/BloomExe/WebLibraryIntegration/BookUpload.cs#L278)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

That they are all trying to use the same staging directory.
</blockquote></details>

I just copied the comment; but I *did* write it originally... : )
The idea was just that if we ever wanted to call this method in parallel for multiple books, it wouldn't work because they would all be staged in the same place.
I tried to clean up the comment.
___
*[`src/BloomExe/WebLibraryIntegration/BookUpload.cs` line 300 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-NoNHepDEH5Ubamul1OM:-NoObVoa5aGJyclQcJNU:bgyrv8v) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/edaa6773add27c04d505300f784f8a4733fcc514/src/BloomExe/WebLibraryIntegration/BookUpload.cs#L300)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It could be a useful optimization to not have to compute checksums and send them back and forth for new books. I don't know how often books get re-uploaded, but it would not surprise me if first-time uploads are a majority, perhaps even by a good margin. Any idea how long it takes to compute this sort of checksum for a large book full of files?

If we one day implement restartable, I would expect things to begin with a call rather like the one that currently asks "is this an existing book". It would have a three-way answer, new, existing, or incomplete. Existing or incomplete would both result in sending the list of files and checksums and getting back a list of what to upload. (I think 'incomplete' should only be used for new books. Bloom probably needs to know that it is attempting to upload an existing book. If there has already been an incomplete attempt to upload an existing book, the server function can just quietly take advantage of any files already successfully copied or uploaded to shrink the list of things to upload this time. Elegantly, since we're sending the checksums, we can continue an incomplete upload even if the book has been edited. We just need the server to checksum any files in the staging area.)

OTOH, it would definitely be simpler if this code didn't even have to think about whether the book is new and/or being retried. It just tells the server, I want the book to consist of these files with these checksums. And the server tells it what needs uploading. Quite possibly the client doesn't have to change at all to make it restartable. It would be nice to be able to ship restartability any time, without having to wait for a new client to make it to release.

So I think I'm voting for "always send the list" unless we have evidence that the cost of computing the checksums and sending the extra data is likely to be a significant part of the upload time (say, more than 5%? 10%?)
</blockquote></details>

On my machine, calculating the hashes of 444 files (mostly images, no audio or video) took 1.2 seconds.

So I'm planning to change things to simplify on the singular path of sending all files and hashes to the function so it can be the controller.
___
*[`src/BloomTests/WebLibraryIntegration/BloomS3StandardUpDownloadTests.cs` line 89 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-NoOTB-1D6wztSWvTqrj:-NoOYvEQCPTZdXpSBjuO:b8wkpa4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e4cd18819af374fe0418855ee311e9bbea919d1/src/BloomTests/WebLibraryIntegration/BloomS3StandardUpDownloadTests.cs#L89)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm not clear why we no longer need to test that unwanted stuff is not getting sent. Maybe you're just satisfied with testing of the file filter elsewhere? Or maybe I missed some equivalent new test?
</blockquote></details>

Yeah, we were already using BookFileFilter to create the staging directory. So that logic is already (in theory) tested there.
I just removed the redundant (except meta.bak which was handled differently) logic to blacklist certain files.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252)* status: 1 of 10 files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs` line 171 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-NoODlMO3cVOYz3VCdmB:-NoYxtJ6Dy9K9L1eT0c0:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/edaa6773add27c04d505300f784f8a4733fcc514/src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs#L171)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

If you want you could update this to include this `files-prefix` but it's not a big deal
</blockquote></details>

Done.

**Review by JohnThomson — COMMENTED** [review]
LGTM, with one thing I noticed about some comments after the name changes.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-:-NonaHCNCPE2Hvj0FX6e:b7sohkm)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @hatton)

___
*[`src/BloomExe/WebLibraryIntegration/BloomS3Client.cs` line 677 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-NonZWQUAY9tjuc9lVfC:-NonZWQUAY9tjuc9lVfD:b-7amw2b) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d3973e6b356d0088a5dbd2b41d03f1c6564e7f30/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L677)):*
> ```Smalltalk
>         // baseUrl looks like https://s3.amazonaws.com/BloomLibraryBooks/5b4b4b4b%2f1234567890%2fBook+Title%2f
>         // We want the part after the bucket name, without encoding, like 5b4b4b4b/1234567890/Book Title
>         public static string GetPrefixFromBaseUrl(string baseUrl)
> ```

Something is funny here. Comparing this and the previous method...
---both say they are getting a prefix, but they get different things
---one says it takes a url and the other says it takes a baseUrl, but the comments indicate both are expected to be passed more-or-less the same thing.
It's not obvious why a typically URL has so many components. In real life, 5b4b4b4b would typically be an email address, and 1234567890 is a book ID, right?
Looks like the real difference is encoding...
But it would be nicer still if the names and/or comments indicated more of why the part at the END of the URL is called a Prefix, and what it's good for...
Of course the comments are not new (may even be mine!) but the name change drew attention to the problem :-)

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @hatton and @JohnThomson)

___
*[`src/BloomExe/WebLibraryIntegration/BloomS3Client.cs` line 677 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-NonZWQUAY9tjuc9lVfC:-Norc3tz1-2DYXA1qEop:bsv3v4h) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d3973e6b356d0088a5dbd2b41d03f1c6564e7f30/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L677)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Something is funny here. Comparing this and the previous method...
---both say they are getting a prefix, but they get different things
---one says it takes a url and the other says it takes a baseUrl, but the comments indicate both are expected to be passed more-or-less the same thing.
It's not obvious why a typically URL has so many components. In real life, 5b4b4b4b would typically be an email address, and 1234567890 is a book ID, right?
Looks like the real difference is encoding...
But it would be nicer still if the names and/or comments indicated more of why the part at the END of the URL is called a Prefix, and what it's good for...
Of course the comments are not new (may even be mine!) but the name change drew attention to the problem :-)
</blockquote></details>

I agree it is awkward. See if that helps.

**Review by JohnThomson — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @hatton)

___
*[`src/BloomExe/WebLibraryIntegration/BloomS3Client.cs` line 677 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-NonZWQUAY9tjuc9lVfC:-Nors46V1erjl9ewLqCC:b-c2x4uv) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d3973e6b356d0088a5dbd2b41d03f1c6564e7f30/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L677)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I agree it is awkward. See if that helps.
</blockquote></details>

Definite improvement. It's clear what the URL in the first method is. I think it would help to say a little more about baseUrl....i.e., that it is the value of one of the book fields that our API yields when we query parse.com for data about a book (if I figured it out correctly from the old code). Up to you if it's worth doing more. It wasn't very hard to deduce what it is from VS.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @hatton and @JohnThomson)

___
*[`src/BloomExe/WebLibraryIntegration/BloomS3Client.cs` line 677 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-NonZWQUAY9tjuc9lVfC:-NorvlFM0lfUmCwEpG9g:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d3973e6b356d0088a5dbd2b41d03f1c6564e7f30/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L677)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Definite improvement. It's clear what the URL in the first method is. I think it would help to say a little more about baseUrl....i.e., that it is the value of one of the book fields that our API yields when we query parse.com for data about a book (if I figured it out correctly from the old code). Up to you if it's worth doing more. It wasn't very hard to deduce what it is from VS.
</blockquote></details>

Done.

**Review by JohnThomson — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r2, 4 of 7 files at r3, 4 of 4 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252#-:-Np0kDAB2fs2Vj4YJA3U:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Pull request merged**
