### PR TITLE
BL-4162 Add Zoom Control

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1695)

### CODE REVIEW

**Comment by andrew-polk** [comment]
A couple nit things. Otherwise the code looks good. I believe we are awaiting UI review.

---

Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/CollectionTab/LibraryView.cs, line 170 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1695#-KlYYep419khPaLMLJ02:-KlYYep419khPaLMLJ03:b8annon) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6844e313a523888861c8971c054863277d81a673/src/BloomExe/CollectionTab/LibraryView.cs#L170)):*
> ```Smalltalk
> 	// Without this we get a white border we don't want.
> 	// Thanks to https://stackoverflow.com/questions/1918247/how-to-disable-the-line-under-tool-strip-in-winform-c
> 	internal class BorderlessToolStripRenderer : ToolStripSystemRenderer
> ```

There are several classes which accomplish this in Bloom and libpalaso, but the others all seem to extend ToolStripProfessionalRenderer. I bring it up in case we want to consider doing something "better," though I'm not sure what that would be at this point or what effort it would be worth.

---

*[src/BloomExe/Workspace/WorkspaceView.cs, line 183 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1695#-KlY_A_CSe3w4Q6dEmPR:-KlY_A_CSe3w4Q6dEmPS:b-kq6n3s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6844e313a523888861c8971c054863277d81a673/src/BloomExe/Workspace/WorkspaceView.cs#L183)):*
> _zoomWwrapper

_zoomWrapper

---

*[src/BloomExe/Workspace/WorkspaceView.cs, line 482 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1695#-KlY_a8qDVZLbEa2jFkX:-KlY_a8qDVZLbEa2jFkY:b79ydwj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6844e313a523888861c8971c054863277d81a673/src/BloomExe/Workspace/WorkspaceView.cs#L482)):*
> // Todo: set up revese communication.

Was this todo for implementing the scroll wheel? If so, TODO can be removed.

---

*[src/BloomExe/Workspace/ZoomControl.cs, line 28 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1695#-KlYbpA6ZfWywADv7ysY:-KlYbpA6ZfWywADv7ysZ:b-emgi62) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6844e313a523888861c8971c054863277d81a673/src/BloomExe/Workspace/ZoomControl.cs#L28)):*
> ```Smalltalk
> 			set
> 			{
> 				var newValue = Math.Max(value, 30);
> ```

We don't want to set a theoretical maximum?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1695#-:-KlYc22WLW1iZwW41GbN:bdlcrb0)*

**Comment by hatton** [comment]
UI looks great, John.
Except the Collection Tab toolbar items aren't right... is this what you expect to see?

image

**Comment by JohnThomson** [comment]
Hadn't thought very much about it, I guess (no screen shot to match :-). I
expected those two buttons (Make BloomPack appears also in a source
collection, and Send/Receive is hanging about somewhere to appear if we
ever turn it on). I'm not sure why their centers are aligned; I think they
have the usual amount of space between them and the Publish tab (which will
shrink in smaller windows). Did you want to keep the icons for these ones
and have them side by side, or have some other indication they are
clickable?

I'm probably being dense, but if you could spell out what is wrong it might
save me time...Sorry...

JohnT

**Comment by hatton** [comment]
They really miss their icons, for one thing ;-) The only change in the card was to move them to follow the make bloompack button (e.g. left-aligned).

**Comment by JohnThomson** [comment]
I think I have it right now.

---

Review status: 16 of 18 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/CollectionTab/LibraryView.cs, line 170 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1695#-KlYYep419khPaLMLJ02:-Km7Tuvr4XDAIjvd3ViJ:b9aelo0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6844e313a523888861c8971c054863277d81a673/src/BloomExe/CollectionTab/LibraryView.cs#L170)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

There are several classes which accomplish this in Bloom and libpalaso, but the others all seem to extend ToolStripProfessionalRenderer. I bring it up in case we want to consider doing something "better," though I'm not sure what that would be at this point or what effort it would be worth.
</blockquote></details>

As a result of some other changes, no longer needed at all.

---

*[src/BloomExe/Workspace/WorkspaceView.cs, line 183 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1695#-KlY_A_CSe3w4Q6dEmPR:-Km7U9sfeoLE-5VwgDr2:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6844e313a523888861c8971c054863277d81a673/src/BloomExe/Workspace/WorkspaceView.cs#L183)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> _zoomWwrapper

_zoomWrapper
</blockquote></details>

Done.

---

*[src/BloomExe/Workspace/WorkspaceView.cs, line 482 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1695#-KlY_a8qDVZLbEa2jFkX:-Km7UN4OMwcM8SkfsSkA:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6844e313a523888861c8971c054863277d81a673/src/BloomExe/Workspace/WorkspaceView.cs#L482)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> // Todo: set up revese communication.

Was this todo for implementing the scroll wheel? If so, TODO can be removed.
</blockquote></details>

Done.

---

*[src/BloomExe/Workspace/ZoomControl.cs, line 28 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1695#-KlYbpA6ZfWywADv7ysY:-Km7UP4bF6IWJSaJNHMA:bc9m99w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6844e313a523888861c8971c054863277d81a673/src/BloomExe/Workspace/ZoomControl.cs#L28)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We don't want to set a theoretical maximum?
</blockquote></details>

John didn't ask for one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1695#-:-Km7TayNN3TLCFvF2rIt:beiu82i)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1695#-:-Km8Jedk7dWLKNXJooYz:bnfp4nl)*

**Comment by hatton** [comment]
Ok, sorry to ask for one more thing... having looked at the Collection tab, it's not working out visually. So let's right-justify the button bar to that it ends up looking like it did before on this tab, except now the "Make Bloom Pack" will be over with the other buttons when it is visible. Thanks.

**Comment by hatton** [comment]
After that, please go ahead and merge and if there are any further visual tweaks, I'll do them later.

**Comment by andrew-polk** [comment]
Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1695)*

**Pull request merged**
