### PR TITLE
Making bloompack of single book doesn't fail if invalid HTML (BL-8943)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4073)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4073)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[src/BloomExe/CollectionTab/LibraryModel.cs, line 392 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4073#-MLyYJmPBj6OIxcOoCBC:-MLyYJmPBj6OIxcOoCBD:b-515l0t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/25001b634c56f89247e178b58cc5ab5185d265ec/src/BloomExe/CollectionTab/LibraryModel.cs#L392)):*
> ```Smalltalk
> 		/// </summary>
> 		/// <param name="path">The path to write to. Precondition: Must not exist.</param>
> 		internal void MakeBloomPackInternal(string path, string dir, string dirNamePrefix, bool forReaderTools, bool isCollection)
> ```

I didn't like that originally, the test code re-implements MakeBloomPackInternal, and that I would have to make the logic change in both the real code and the test code.  So I turned the old MakeBloomPackInternal function into 2 functions, a MakeBloomPackWithUI and a MakeBloomPackInternal which has the UI-less logic.  And I figured the unit tests can call into MakeBloomPackInternal and test the same code that way.

That kinda works, except now the boilerplate above it in the call stack is duplicated in 2 places, which is still kinda annoying.

Alternatively, I could instead tackle it at a level of adding a IsUIDisabled property to LibraryModel. It would normally be false, but it would be true in the unit tests. The Bloom code would check it and decided whether to show the MEssageDialog and the various other things.  The unit test would call into the top-level public functions, MakeBloomPack and MakeSingleBookBloomPack.

Thoughts?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4073)* status: all files reviewed, 3 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/CollectionTab/LibraryModel.cs, line 392 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4073#-MLyYJmPBj6OIxcOoCBC:-MM2zfqrEaqIdwh8cSsh:bszxinz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/25001b634c56f89247e178b58cc5ab5185d265ec/src/BloomExe/CollectionTab/LibraryModel.cs#L392)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I didn't like that originally, the test code re-implements MakeBloomPackInternal, and that I would have to make the logic change in both the real code and the test code.  So I turned the old MakeBloomPackInternal function into 2 functions, a MakeBloomPackWithUI and a MakeBloomPackInternal which has the UI-less logic.  And I figured the unit tests can call into MakeBloomPackInternal and test the same code that way.

That kinda works, except now the boilerplate above it in the call stack is duplicated in 2 places, which is still kinda annoying.

Alternatively, I could instead tackle it at a level of adding a IsUIDisabled property to LibraryModel. It would normally be false, but it would be true in the unit tests. The Bloom code would check it and decided whether to show the MEssageDialog and the various other things.  The unit test would call into the top-level public functions, MakeBloomPack and MakeSingleBookBloomPack.

Thoughts?
</blockquote></details>

I think I would rather have tests call an inner function without UI than have the logic in a method change depending on whether we are running unit tests.

The real problem here is we have UI logic in the model layer (definitely not something to tackle for 4.9).

Do I understand correctly that the only real change here is to call CompressCollectionDirectory or CompressBookDirectory conditionally rather than always CompressCollectionDirectory?

I'm tempted to ask that that change be the only one for 4.9. But I guess "it's just a beta..."
___
*[src/BloomTests/CollectionTab/LibraryModelTests.cs, line 33 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4073#-MM1XaoW3zTKLZe-QSVh:-MM1XaoW3zTKLZe-QSVi:b-cacbhq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/25001b634c56f89247e178b58cc5ab5185d265ec/src/BloomTests/CollectionTab/LibraryModelTests.cs#L33)):*
> ```Smalltalk
> 			// ENHANCE: Sometimes making the FakeCollection temporary folder causes an UnauthorizedAccessException.
> 			// Not exactly sure why or what to do about it. Possibly it could be related to file system operations
> 			// being async in nature???
> ```

I'm unclear if this is something you think is new with these changes. I don't remember seeing this happen (or at least not causing a test failure) before.
___
*[src/BloomTests/CollectionTab/LibraryModelTests.cs, line 164 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4073#-MM2z5fpBPdh7r7FTOXg:-MM2z5fpBPdh7r7FTOXh:b-vcef0o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/25001b634c56f89247e178b58cc5ab5185d265ec/src/BloomTests/CollectionTab/LibraryModelTests.cs#L164)):*
> ```Smalltalk
> 			var actualFiles = GetActualFilenamesFromZipfile(bloomPackName);
> 
> 			// +2 for collection-level CustomCollectionSettings and FakeCss.css file, -4 for corrupt, .map and .bak files, so the count is -3
> ```

All these comments need the "so the count is x" updated.

But I don't understand what in this PR is changing these. Something in CompressCollectionDirectory was eliminating fakecss.css?

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4073)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/CollectionTab/LibraryModel.cs, line 392 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4073#-MLyYJmPBj6OIxcOoCBC:-MMGWuPm5DOBdqQKvEGE:b-nvsb6z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/25001b634c56f89247e178b58cc5ab5185d265ec/src/BloomExe/CollectionTab/LibraryModel.cs#L392)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think I would rather have tests call an inner function without UI than have the logic in a method change depending on whether we are running unit tests.

The real problem here is we have UI logic in the model layer (definitely not something to tackle for 4.9).

Do I understand correctly that the only real change here is to call CompressCollectionDirectory or CompressBookDirectory conditionally rather than always CompressCollectionDirectory?

I'm tempted to ask that that change be the only one for 4.9. But I guess "it's just a beta..."
</blockquote></details>

Answer: Yes, the only real change is that we call one of the 2 conditionally instead of always CompressCollectionDirectory.

I think if one analyzed it painstakingly, it can be deduced that everything is equivalent except that we use DirectorySeparatorChar instead of "/", or at least, that was my intention/belief.
___
*[src/BloomTests/CollectionTab/LibraryModelTests.cs, line 33 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4073#-MM1XaoW3zTKLZe-QSVh:-MMGXDll7vKe-SndD3O9:bktwuc4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/25001b634c56f89247e178b58cc5ab5185d265ec/src/BloomTests/CollectionTab/LibraryModelTests.cs#L33)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm unclear if this is something you think is new with these changes. I don't remember seeing this happen (or at least not causing a test failure) before.
</blockquote></details>

Huh, that's mildly concerning if we don't remember seeing this happen before.
___
*[src/BloomTests/CollectionTab/LibraryModelTests.cs, line 164 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4073#-MM2z5fpBPdh7r7FTOXg:-MMGXO5VDoIF_hX7IASo:b2cwenx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/25001b634c56f89247e178b58cc5ab5185d265ec/src/BloomTests/CollectionTab/LibraryModelTests.cs#L164)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

All these comments need the "so the count is x" updated.

But I don't understand what in this PR is changing these. Something in CompressCollectionDirectory was eliminating fakecss.css?
</blockquote></details>

Thanks, fixed the count comments.

The difference is that previously the test executed a function in FakeLibraryModel, and now it executes a function in LibraryModel. Somehow, apparently that causes the code to generate CustomCollectionSettings.css (somehow), whereas previously FakeLibraryModel did not do that.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4073)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4073)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

**Review by andrew-polk — APPROVED** [review]
> Dismissed @sujeffreyl from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4073)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Pull request merged**
