### PR TITLE
BL-1085: Add mime info for bloom-desktop-unstable

### PR DESCRIPTION
**Pull request by phillip-hopper**
We won't know for sure if this fixes the problem until the Linux package is built.

### CODE REVIEW

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/249/
Test PASSed.

**Comment by JohnThomson** [comment]
Does that mean we can't test it until it is merged, or we shouldn't merge it until the testing happens?

I don't understand the significance of setting a mime-type like this, so a comment might be helpful. Or else it should be reviewed by someone who knows Linux well enough so that the reason for adding this is obvious.

**Comment by phillip-hopper** [comment]
The only way to test it is to try to install the Linux package, so the package must be built so it can be tested.  During the installation process the package manager sets up the mime types.

**Comment by StephenMcConnel** [comment]
It looks reasonable to me.  I can test it in a few minutes.

**Comment by phillip-hopper** [comment]
@StephenMcConnel The installer creates the bloompack association for bloom-desktop but not for bloom-desktop-unstable. And I experimented with the case-sensitive issue, and it appears that the file extensions for mime-types are not case sensitive.

**Comment by JohnThomson** [comment]
Since the whole point was apparently to create the association for bloom-desktop-unstable, seems Phil has some work to do.

**Comment by StephenMcConnel** [comment]
It would be better to merge the two existing .sharedmimeinfo files into bloom-desktop-unstable.sharedmimeinfo, and then delete the existing files.  Otherwise it looks okay.  The merged file would look something like this:

<?xml version="1.0" encoding="UTF-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
	<mime-type type="application/bloom-collection">
		<comment>Bloom Book Collection</comment>
		<glob pattern="*.bloomCollection"/>
	</mime-type>
	<mime-type type="application/bloom">
		<comment>Bloom books</comment>
		<sub-class-of type="application/zip"/>
		<glob pattern="*.bloompack"/>
	</mime-type>
</mime-info>

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-master-debug/267/
Test PASSed.

**Comment by StephenMcConnel** [comment]
LGTM as they say.  :-)

**Pull request merged**
