### PR TITLE
Auto-height can be turned off, yielding new resize control (BL-13854)

### PR DESCRIPTION
**Pull request by JohnThomson**
Also improves auto-height algorithm

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6651)

### CODE REVIEW

**Review by StephenMcConnel — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6651)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 1582 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6651#-O6amNzfE0Hq1rULZguz:-O6amNzfE0Hq1rULZgv-:buyp3it) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c12ee5ab92ad91cbd7fc6b95d97c936627ca2353/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L1582)):*
> ```XML
>                 );
>                 deltaY = newBubbleHeight - this.oldHeight;
>                 this.activeElement.style.height = `${newBubbleHeight}px`;
> ```

Doesn't the code need a return to avoid the height adjustment at this point?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6651)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 1582 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6651#-O6amNzfE0Hq1rULZguz:-O6bG_jNETpgKRFbaddf:b1nwbdr) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c12ee5ab92ad91cbd7fc6b95d97c936627ca2353/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L1582)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Doesn't the code need a return to avoid the height adjustment at this point?
</blockquote></details>

Technically it doesn't. The "s" control is only visible when things are set so that adjustBubbleHeightToContent will do nothing, so calling it is harmless. And on the other hand, we DO need to go on and call alignControlFrameWithActiveElement, so a return here would be a problem.
But I agree it is confusing. I even tried to write a comment but it evidently didn't work. I decided to go ahead and put that call in the cases that need it.

**Review by StephenMcConnel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6651#-:-O6bIwjy5ynLW0P2QT2w:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by StephenMcConnel — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6651)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
