### PR TITLE
BL-10772 On SS import, image re-use generates new image

### PR DESCRIPTION
**Pull request by gmartin7**
* make unique copies of image files, if the image is re-used

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5742)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5742)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 614 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5742#-NSHbP2o0r8jSVd7iCg6:-NSHbP2o0r8jSVd7iCg7:b-yb81tt) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/be76a4a419571d9c8e5b7f33356367dc812e806b/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L614)):*
> ```Smalltalk
> 				}
> 				_imgNamesSeen.Add(destFileName);
> 			}
> ```

The video code in this file for ensuring a unique name seems simpler.
Can we do something more like this? Or is there something about images which makes it need the added complexity?
```
				var dest = Path.Combine(videoDirectory, videoFile);
				while (RobustFile.Exists(dest))
				{
					videoFile = ImageUtils.GetUnusedFilename(videoDirectory,
						Path.GetFileNameWithoutExtension(videoFile), Path.GetExtension(videoFile));
					dest = Path.Combine(videoDirectory, videoFile);
				}
```

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5742)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 614 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5742#-NSHbP2o0r8jSVd7iCg6:-NSMafUeCI6U46_lut3Y:b-6zalja) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/be76a4a419571d9c8e5b7f33356367dc812e806b/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L614)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The video code in this file for ensuring a unique name seems simpler.
Can we do something more like this? Or is there something about images which makes it need the added complexity?
```
				var dest = Path.Combine(videoDirectory, videoFile);
				while (RobustFile.Exists(dest))
				{
					videoFile = ImageUtils.GetUnusedFilename(videoDirectory,
						Path.GetFileNameWithoutExtension(videoFile), Path.GetExtension(videoFile));
					dest = Path.Combine(videoDirectory, videoFile);
				}
```
</blockquote></details>

Much better. thx.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5742)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs` line 936 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5742#-NSMblWEBiJsaXMwe4a8:-NSMblWEBiJsaXMwe4a9:b-d28gxw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/133ed25bfe39b16e7236225c0a5b2070f2bdfdeb/src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs#L936)):*
> ```Smalltalk
> 		[TestCase("Othello 199.jpg")]
> 		[TestCase("Mars 3.png")]
> 		[TestCase("Mars 4.png")]
> ```

I'm probably just misunderstanding the context, but why is it `Mars 4` here but `Mars%2031` in the test above?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5742)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs` line 936 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5742#-NSMblWEBiJsaXMwe4a8:-NSMeIHD8-SPGHBnfHT-:b-xrfxm6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/133ed25bfe39b16e7236225c0a5b2070f2bdfdeb/src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs#L936)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm probably just misunderstanding the context, but why is it `Mars 4` here but `Mars%2031` in the test above?
</blockquote></details>

`Mars 3.png` is the "original" file. The new version of the code bumps that to "Mars 4.png" instead of appending a "1".

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5742)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs` line 936 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5742#-NSMblWEBiJsaXMwe4a8:-NSMgAOV9f7x_TCiO0Z_:b-1g2kou) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/133ed25bfe39b16e7236225c0a5b2070f2bdfdeb/src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs#L936)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

`Mars 3.png` is the "original" file. The new version of the code bumps that to "Mars 4.png" instead of appending a "1".
</blockquote></details>

(See `OneTimeSetup()` about 731.)

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5742)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs` line 936 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5742#-NSMblWEBiJsaXMwe4a8:-NSMsa89ByHoR0m0aRLy:be9c7zk) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/133ed25bfe39b16e7236225c0a5b2070f2bdfdeb/src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs#L936)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

(See `OneTimeSetup()` about 731.)
</blockquote></details>

OK, found what you were talking about and fixed it and other failing tests.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5742)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
