### PR TITLE
Allow control of how playing audio is highlighted (BL-11766)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5671)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5671)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts` line 58 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5671#-NPPLvwp7e4YcOIhASfj:-NPPLvwp7e4YcOIhASfk:b636rqg) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4cd30f8498353bb314cec04b389fb4c592364f28/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L58)):*
> ```XML
>     // its 'color' property is an empty string rather than undefined or null
>     // when it is not specified.
>     hiliteTextColor: string | undefined;
> ```

We're going to have decide between "highlight" and "hilite" (A foolish consistency being "the hobgoblin of little minds")
___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts` line 1858 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5671#-NPPO1uz1B4c_-ldCWJV:-NPPO1uz1B4c_-ldCWJW:b-n8pirn) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4cd30f8498353bb314cec04b389fb4c592364f28/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L1858)):*
> ```XML
>         );
>         // The only way I know to get the new hilight color in there is to re-render
>         // completely. (Note: not usng JSX here because this isn't a tsx file.)
> ```

But it easily could be? But anyhow, this file is getting quite big. so maybe all this audio highlighting wants to be its own file?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5671)* status: 7 of 11 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts` line 58 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5671#-NPPLvwp7e4YcOIhASfj:-NPSjepP1OaIlbqLnemf:b-bvx657) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4cd30f8498353bb314cec04b389fb4c592364f28/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L58)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

We're going to have decide between "highlight" and "hilite" (A foolish consistency being "the hobgoblin of little minds")
</blockquote></details>

I think I have made it hilite wherever only programmers will see it and highlight wherever the end users will. (Research says that hilite is an informal spelling especially used by programmers).
___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts` line 1858 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5671#-NPPO1uz1B4c_-ldCWJV:-NPU26T6Ahsr228u4GRd:b-cm1ykk) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4cd30f8498353bb314cec04b389fb4c592364f28/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L1858)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

But it easily could be? But anyhow, this file is getting quite big. so maybe all this audio highlighting wants to be its own file?
</blockquote></details>

I moved the ReactDom.Render into a function in the new AudioHighlight file. I looked at moving other functions, but all the new stuff somehow uses instance methods of StyleEditor. Short of a very major refactor, I think it would add complexity rather than removing it.

**Review by hatton — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5671)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5671)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
