### PR TITLE
Major version upgrades of some npm packages

### PR DESCRIPTION
**Pull request by sujeffreyl**
These are the ones that I feel more confident about.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4150)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4150)* status: 1 of 7 files reviewed, all discussions resolved

**Review by sujeffreyl — COMMENTED** [review]
Added some riskier changes.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4150#-:-MRQZdBxC46wU8nS6dxx:bkjga5n)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4150)* status: all files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/package.json, line 150 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4150#-MRQfxbb1sWpbGqbjI41:-MRQfxbb1sWpbGqbjI42:b-ijuuvh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fd9dc380efaaafce62e078f75d02b081e81c1e8a/src/BloomBrowserUI/package.json#L150)):*
> ```JSON
>         "@types/underscore": "^1.10.24",
>         "@types/webpack-env": "^1.13.9",
>         "@types/webrtc": "^0.0.25",
> ```

Looks like all these types got added to devDependencies but not removed from dependencies.
___
*[src/BloomBrowserUI/utils/bloomApi.ts, line 255 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4150#-MRQgPL7EZQzXdn8UwUK:-MRQgPL7EZQzXdn8UwUL:bhk6ydr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fd9dc380efaaafce62e078f75d02b081e81c1e8a/src/BloomBrowserUI/utils/bloomApi.ts#L255)):*
> ```XML
> 
>     public static postBoolean(urlSuffix: string, value: boolean) {
>         const data = this.adjustFalsyData(value); // Need to stringify FALSE value in axios 0.20
> ```

I think it is 0.21? And now that you found the github issue, should we link to it?

Maybe just remove this comment and expand/fix the one in the function?

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4150)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/package.json, line 150 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4150#-MRQfxbb1sWpbGqbjI41:-MRQn72D87ywdY0chWbU:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fd9dc380efaaafce62e078f75d02b081e81c1e8a/src/BloomBrowserUI/package.json#L150)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like all these types got added to devDependencies but not removed from dependencies.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/utils/bloomApi.ts, line 255 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4150#-MRQgPL7EZQzXdn8UwUK:-MRQgyP3Awae_i_viZ77:b-82p2uf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fd9dc380efaaafce62e078f75d02b081e81c1e8a/src/BloomBrowserUI/utils/bloomApi.ts#L255)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think it is 0.21? And now that you found the github issue, should we link to it?

Maybe just remove this comment and expand/fix the one in the function?
</blockquote></details>

It can be repro'd in both 0.20.* and 0.21.*
Good idea about linking to the github issue.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4150)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Pull request merged**
