### PR TITLE
Creates browserui/help and output/browser/help for MD help files

### PR DESCRIPTION
**Pull request by hatton**
Gulp converts the md to html in /help, HtmlHelplink points there, and BloomFileLocator can locate it.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1825)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/gulpfile.js, line 11 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1825#-KsnGdzYyp0ZDvCW3-TB:-KsnGdzZn31tpT_KgUhH:b-h231re) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/415637d1c4994243b5855b045be6ca2671954409/src/BloomBrowserUI/gulpfile.js#L11)):*
> ```JavaScript
> var MarkdownIt = require('markdown-it');
> var markdownItContainer = require('markdown-it-attrs');
> var markdownItAttrs = require('markdown-it-attrs');
> ```

Surprising that both names map to the same source. Shouldn't the first be markdown-it-container? (Or if it works without that...maybe we can have one less dependency in packages.json?)

---

*[src/BloomExe/BloomFileLocator.cs, line 138 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1825#-KsnIBmqPbknrn-eiX3l:-KsnIBmqPbknrn-eiX3m:bqusbud) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/415637d1c4994243b5855b045be6ca2671954409/src/BloomExe/BloomFileLocator.cs#L138)):*
> ```Smalltalk
> 		}
> 
> 		public static string GetBrowserFile(bool optional, params string[] parts)
> ```

Doesn't appear to be any implementation using this new param. Did you mean to switch to GetBestLocalizableFileDistributedWithApplication? (though all the callers I can find pass false...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1825)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/gulpfile.js, line 11 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1825#-KsnGdzYyp0ZDvCW3-TB:-KsnkmqjNf6jzqAK_Tvf:bt2vr1b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/415637d1c4994243b5855b045be6ca2671954409/src/BloomBrowserUI/gulpfile.js#L11)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Surprising that both names map to the same source. Shouldn't the first be markdown-it-container? (Or if it works without that...maybe we can have one less dependency in packages.json?)
</blockquote></details>

Fixed.

---

*[src/BloomExe/BloomFileLocator.cs, line 138 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1825#-KsnIBmqPbknrn-eiX3l:-Ksnl0LrIfXumtc_9sVi:bjzvt1g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/415637d1c4994243b5855b045be6ca2671954409/src/BloomExe/BloomFileLocator.cs#L138)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Doesn't appear to be any implementation using this new param. Did you mean to switch to GetBestLocalizableFileDistributedWithApplication? (though all the callers I can find pass false...
</blockquote></details>

This was done in a sort-of auto-pilot way because GetBestLocalizableFileDistributedWithApplication has this parameter. But I think you're right, that ultimately GetBestLocalizableFileDistributedWithApplication also has no callers that don't use false, so that parameter could go away and then it could go away on GetBrowserFile(). However at the moment, I'm feeling that it's good to make each caller be explicit about what should happen. The next improvement I would make would thus be to change from false (which isn't very readable) to something like "Required.True". But now I think I'm getting far afield of this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1825)*

**Comment by StephenMcConnel** [comment]
Review status: 11 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/gulpfile.js, line 11 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1825#-KsnGdzYyp0ZDvCW3-TB:-KsnxBvV-MFZ5Y0iEERk:bhu9osy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/415637d1c4994243b5855b045be6ca2671954409/src/BloomBrowserUI/gulpfile.js#L11)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

I've verified that the markdown-it-attrs extension works as expected, converting the {i18n=...} markers into i18n attributes as expected.  The markdown-it-container extension didn't recognize the :: marker, passing it through to the output html, but it also doesn't seem to need it because the <li> elements get the attributes which doesn't happen with the Markdig processor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1825)*

**Comment by JohnThomson** [comment]
Review status: 11 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/BloomFileLocator.cs, line 138 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1825#-KsnIBmqPbknrn-eiX3l:-KsoGzhhDsZQ0D9RhJlf:b-gfvp1t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/415637d1c4994243b5855b045be6ca2671954409/src/BloomExe/BloomFileLocator.cs#L138)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This was done in a sort-of auto-pilot way because GetBestLocalizableFileDistributedWithApplication has this parameter. But I think you're right, that ultimately GetBestLocalizableFileDistributedWithApplication also has no callers that don't use false, so that parameter could go away and then it could go away on GetBrowserFile(). However at the moment, I'm feeling that it's good to make each caller be explicit about what should happen. The next improvement I would make would thus be to change from false (which isn't very readable) to something like "Required.True". But now I think I'm getting far afield of this PR.
</blockquote></details>

That makes sense. But then why not pass 'optional' as the first argument of GetFileDistributedWithApplication? Then it would at least work if someone ever does pass true.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1825)*

**Comment by hatton** [comment]
Review status: 11 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/BloomFileLocator.cs, line 138 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1825#-KsnIBmqPbknrn-eiX3l:-Ksoc59iKo6kvbkFnFh0:b-kbx002) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/415637d1c4994243b5855b045be6ca2671954409/src/BloomExe/BloomFileLocator.cs#L138)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

That makes sense. But then why not pass 'optional' as the first argument of GetFileDistributedWithApplication? Then it would at least work if someone ever does pass true.
</blockquote></details>

Because then it would *not* work if it has to look elsewhere. As written, it works correctly either way. See the comment under the first if{}.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1825)*

**Comment by JohnThomson** [comment]
Review status: 11 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/BloomFileLocator.cs, line 138 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1825#-KsnIBmqPbknrn-eiX3l:-KsofxOPsn-KZtAtI4nb:bcia26s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/415637d1c4994243b5855b045be6ca2671954409/src/BloomExe/BloomFileLocator.cs#L138)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Because then it would *not* work if it has to look elsewhere. As written, it works correctly either way. See the comment under the first if{}.
</blockquote></details>

The first if? This method has two lines and no ifs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1825)*

**Comment by hatton** [comment]
Review status: 11 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/BloomFileLocator.cs, line 138 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1825#-KsnIBmqPbknrn-eiX3l:-KsoiPGq9xB33RhR5VqV:b-658xwj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/415637d1c4994243b5855b045be6ca2671954409/src/BloomExe/BloomFileLocator.cs#L138)):*
> GetFileDistributedWithApplication

Sorry, I was fixated on GetBestLocalizableFileDistributedWithApplication(), which is what was actually changed with this PR. FileLocator.GetFileDistributedWithApplication() is a lipalaso method; this doesn't warrant going and adding a feature to the api of that library.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1825)*

**Comment by JohnThomson** [comment]
Review status: 11 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/BloomFileLocator.cs, line 138 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1825#-KsnIBmqPbknrn-eiX3l:-KsovPB2li-nI3MU_nEA:bf56yo5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/415637d1c4994243b5855b045be6ca2671954409/src/BloomExe/BloomFileLocator.cs#L138)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

> GetFileDistributedWithApplication

Sorry, I was fixated on GetBestLocalizableFileDistributedWithApplication(), which is what was actually changed with this PR. FileLocator.GetFileDistributedWithApplication() is a lipalaso method; this doesn't warrant going and adding a feature to the api of that library.
</blockquote></details>

We're really communicating poorly...must be something to do with lack of sleep :-). I'm not proposing any change to libpalaso. The method you're calling, FileLocator.GetFileDistributedWithApplication, already has 'optional' as its first argument. I'm proposing that (2 lines down from this comment) the first argument you pass to it should be the new "optional" argument of this method, which would then actually have the intended effect if anyone passed true.
If this still doesn't make sense I think we should do a voice call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1825)*

**Comment by hatton** [comment]
Review status: 10 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/BloomFileLocator.cs, line 138 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1825#-KsnIBmqPbknrn-eiX3l:-KtIZ6E3SbYmMTjwUz0C:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/415637d1c4994243b5855b045be6ca2671954409/src/BloomExe/BloomFileLocator.cs#L138)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We're really communicating poorly...must be something to do with lack of sleep :-). I'm not proposing any change to libpalaso. The method you're calling, FileLocator.GetFileDistributedWithApplication, already has 'optional' as its first argument. I'm proposing that (2 lines down from this comment) the first argument you pass to it should be the new "optional" argument of this method, which would then actually have the intended effect if anyone passed true.
If this still doesn't make sense I think we should do a voice call.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1825)*

**Pull request merged**
