### PR TITLE
BL-5866 5867 Video folder and remove unused

### PR DESCRIPTION
**Pull request by gmartin7**
* 1st commit moves video files to video folder
* 2nd commit causes unused video files to be removed

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Somewhat in haste...just check with me if something doesn't make sense.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/BloomExe/Book/BookStorage.cs, line 465 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435#-LDMt65k1wmVwV_JYYOK:-LDMt65k1wmVwV_JYYOL:bycgu2o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c62087502eac3c455bf419b211449df333c6d35d/src/BloomExe/Book/BookStorage.cs#L465)):*
> ```Smalltalk
> 			var videoFolderPath = GetVideoFolderPath(_folderPath);
> 			var videoFilesToDeleteIfNotUsed = new List<string>();
> 			var videoExtensions = new HashSet<string>(new[] { ".mp4" });  // .mov, .avi, .orig...?
> ```

I think adding .orig here is good...we want to remove any of those where we're not using the corresponding mp4, and I think you have code that will preserve the ones we want.

---

*[src/BloomExe/Book/BookStorage.cs, line 469 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435#-LDMgiSU0G9bgSGYfDxz:-LDMgiSU0G9bgSGYfDy-:bay498b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c62087502eac3c455bf419b211449df333c6d35d/src/BloomExe/Book/BookStorage.cs#L469)):*
> ```Smalltalk
> 			if (Directory.Exists(videoFolderPath))
> 			{
> 				foreach (var path in Directory.EnumerateFiles(videoFolderPath).Where(
> ```

If you wind up only with one extension, you can just EnumerateFiles(videoFolderPath, "*.mp4")

---

*[src/BloomExe/Book/BookStorage.cs, line 470 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435#-LDMgyxCCAtdV-9Ltpvg:-LDMgyxCCAtdV-9Ltpvh:bsjdda6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c62087502eac3c455bf419b211449df333c6d35d/src/BloomExe/Book/BookStorage.cs#L470)):*
> ```Smalltalk
> 			{
> 				foreach (var path in Directory.EnumerateFiles(videoFolderPath).Where(
> 					s => videoExtensions.Contains(Path.GetExtension(s).ToLowerInvariant())))
> ```

is it Linux-dependent whether we want to use ToLowerInvariant? I'm not sure how it deals with case and extensions...maybe check with Steve?

---

*[src/BloomExe/Book/BookStorage.cs, line 489 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435#-LDMtRqm3WcTAS2l_-9b:-LDMtRqm3WcTAS2l_-9c:b-7r5p7n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c62087502eac3c455bf419b211449df333c6d35d/src/BloomExe/Book/BookStorage.cs#L489)):*
> ```Smalltalk
> 					}
> 				}
> 				foreach (var ext in videoExtensions)
> ```

Looks like this is aimed at keeping the corresponding .orig? But I don't think that generalizes; if for some reason we support .mov and .avi, I doubt we want to keep X.mov just because X.mp4 is in use.

---

*[src/BloomExe/Book/BookStorage.cs, line 505 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435#-LDMtkAd6g8SNv9wfSIJ:-LDMtkAd6g8SNv9wfSIK:bq6ivba) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c62087502eac3c455bf419b211449df333c6d35d/src/BloomExe/Book/BookStorage.cs#L505)):*
> ```Smalltalk
> 					RobustFile.Delete(path);
> 				}
> 				catch (Exception)
> ```

Can we reasonably specialize this? E.g., IOException + SecurityException? Catching Exception should be a last resort. What actual problems do we want to ignore?

---

*[src/BloomExe/Edit/EditingModel.cs, line 1398 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435#-LDMucdX3Aq_DfcJQUxU:-LDMucdX3Aq_DfcJQUxV:b-v81q4c) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c62087502eac3c455bf419b211449df333c6d35d/src/BloomExe/Edit/EditingModel.cs#L1398)):*
> ```Smalltalk
> 				var fileName = GetNewVideoFileName();
> 				var videoFolder = BookStorage.GetVideoDirectoryAndEnsureExistence(CurrentBook.FolderPath);
> 				var path = Path.Combine(videoFolder, fileName);
> ```

Seems there should be similar changes in the newest code for launching an external editor on the video...maybe you still need to rebase on that? If so please look for it and test that you aren't breaking it.

---

*[src/BloomTests/Book/BookStorageTests.cs, line 74 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435#-LDMuwDA-mCRxtC8RmoO:-LDMuwDA-mCRxtC8RmoP:b3pdb7o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c62087502eac3c455bf419b211449df333c6d35d/src/BloomTests/Book/BookStorageTests.cs#L74)):*
> ```Smalltalk
> 
> 		[Test]
> 		public void CleanupUnusedVideoFiles_BookHadUnusedVideo_VideosRemoved()
> ```

Remember to enhance with cases keeping and discarding .orig files

---

*[src/BloomTests/Book/BookStorageTests.cs, line 286 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435#-LDMvhtcABoZyZCB-SIW:-LDMvhtcABoZyZCB-SIX:b-fkq36o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c62087502eac3c455bf419b211449df333c6d35d/src/BloomTests/Book/BookStorageTests.cs#L286)):*
> ```Smalltalk
> 			if (makeOrigAlso && ext == ".mp4")
> 			{
> 				TempFile.WithFilename(Path.ChangeExtension(name, ".orig"));
> ```

How does this get disposed?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435#-:-LDMvtCKB9anWkBkXuZO:b-9nm4k6)*

**Comment by gmartin7** [comment]
Review status: 4 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/BloomExe/Book/BookStorage.cs, line 465 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435#-LDMt65k1wmVwV_JYYOK:-LDNcgv3CU-VFMHjscw8:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c62087502eac3c455bf419b211449df333c6d35d/src/BloomExe/Book/BookStorage.cs#L465)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think adding .orig here is good...we want to remove any of those where we're not using the corresponding mp4, and I think you have code that will preserve the ones we want.
</blockquote></details>

Done.

---

*[src/BloomExe/Book/BookStorage.cs, line 469 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435#-LDMgiSU0G9bgSGYfDxz:-LDNzOge7co1ZW79EZDv:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c62087502eac3c455bf419b211449df333c6d35d/src/BloomExe/Book/BookStorage.cs#L469)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

If you wind up only with one extension, you can just EnumerateFiles(videoFolderPath, "*.mp4")
</blockquote></details>

Done.

---

*[src/BloomExe/Book/BookStorage.cs, line 470 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435#-LDMgyxCCAtdV-9Ltpvg:-LDNfcroBQDuxMRbM3Ax:b9awh5b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c62087502eac3c455bf419b211449df333c6d35d/src/BloomExe/Book/BookStorage.cs#L470)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

is it Linux-dependent whether we want to use ToLowerInvariant? I'm not sure how it deals with case and extensions...maybe check with Steve?
</blockquote></details>

Steve says it'll work and the ToLowerInvariant() may have even been added to make sure it works on Linux (this is copied and adapted code).

---

*[src/BloomExe/Book/BookStorage.cs, line 489 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435#-LDMtRqm3WcTAS2l_-9b:-LDNzA9f18G_mdhF6jTE:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c62087502eac3c455bf419b211449df333c6d35d/src/BloomExe/Book/BookStorage.cs#L489)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Looks like this is aimed at keeping the corresponding .orig? But I don't think that generalizes; if for some reason we support .mov and .avi, I doubt we want to keep X.mov just because X.mp4 is in use.
</blockquote></details>

Done.

---

*[src/BloomExe/Book/BookStorage.cs, line 505 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435#-LDMtkAd6g8SNv9wfSIJ:-LDNxnXbEB4BIuPcugJ0:b-rc6wif) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c62087502eac3c455bf419b211449df333c6d35d/src/BloomExe/Book/BookStorage.cs#L505)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Can we reasonably specialize this? E.g., IOException + SecurityException? Catching Exception should be a last resort. What actual problems do we want to ignore?
</blockquote></details>

See what you think of what I did. If you like it, we may be able to use the same thing in a couple of preexisting methods that do this same "catch (Exception)". Hmm... I guess I did it in the audio method already.

---

*[src/BloomExe/Edit/EditingModel.cs, line 1398 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435#-LDMucdX3Aq_DfcJQUxU:-LDNgQKz6lI9FnG68xSl:b9pgkk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c62087502eac3c455bf419b211449df333c6d35d/src/BloomExe/Edit/EditingModel.cs#L1398)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Seems there should be similar changes in the newest code for launching an external editor on the video...maybe you still need to rebase on that? If so please look for it and test that you aren't breaking it.
</blockquote></details>

Nope. HandleEditVideoRequest() works fine the way it is. :)

---

*[src/BloomTests/Book/BookStorageTests.cs, line 74 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435#-LDMuwDA-mCRxtC8RmoO:-LDNg_qlAK89mWDLAFDT:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c62087502eac3c455bf419b211449df333c6d35d/src/BloomTests/Book/BookStorageTests.cs#L74)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Remember to enhance with cases keeping and discarding .orig files
</blockquote></details>

Done.

---

*[src/BloomTests/Book/BookStorageTests.cs, line 286 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435#-LDMvhtcABoZyZCB-SIW:-LDNhJSZC9_OGuBAnos4:biqc8cb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c62087502eac3c455bf419b211449df333c6d35d/src/BloomTests/Book/BookStorageTests.cs#L286)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

How does this get disposed?
</blockquote></details>

Cool! TearDown() does "_fixtureFolder.Dispose();", which disposes every TempFile in the BloomBookStorageTest folder.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435)*

**Comment by JohnThomson** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/BookStorage.cs, line 505 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435#-LDMtkAd6g8SNv9wfSIJ:-LDO3RQt2Ycb4g68F2Ad:b-c5x0u4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c62087502eac3c455bf419b211449df333c6d35d/src/BloomExe/Book/BookStorage.cs#L505)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

See what you think of what I did. If you like it, we may be able to use the same thing in a couple of preexisting methods that do this same "catch (Exception)". Hmm... I guess I did it in the audio method already.
</blockquote></details>

You can now actually do catch (Exception ex) when (ex is IOException || ex is SecurityException) which might be more readable. But what you have is OK if you don't want to bother. (I checked with Steve, he says this works in mono too).
Have you thought about whether those two cover the interesting cases? That was just off the top of my head...

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435)*

**Comment by gmartin7** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/BookStorage.cs, line 505 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435#-LDMtkAd6g8SNv9wfSIJ:-LDOBcbg1SPgDlKm_5O_:b9k8qm6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c62087502eac3c455bf419b211449df333c6d35d/src/BloomExe/Book/BookStorage.cs#L505)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

You can now actually do catch (Exception ex) when (ex is IOException || ex is SecurityException) which might be more readable. But what you have is OK if you don't want to bother. (I checked with Steve, he says this works in mono too).
Have you thought about whether those two cover the interesting cases? That was just off the top of my head...
</blockquote></details>

Oh! Much better! Then I don't need the silly flag boolean. I think we're okay with those exceptions. It's probably even less of a problem, since we're using RobustFile.Delete().

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435#-:-LDOKTyb-lDVPTAojCRk:bnfp4nl)*

**Pull request merged**
