### PR TITLE
Prevent extra space before lang2 or lang3 if they are displayed by themselves (BL-4515)

### PR DESCRIPTION
**Pull request by andrew-polk**
---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1644)

### CODE REVIEW

**Comment by andrew-polk** [comment]
This could go back to 3.8 if deemed safe.

**Comment by hatton** [comment]
👍 

Is there some bug in 3.8 that this would fix?

**Comment by andrew-polk** [comment]
Yes, this bug exists in 3.8 with the same symptoms.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1644#-:-KguTTO-3mg-tWiCecjQ:b-494ekf)*

**Comment by JohnThomson** [comment]
Overall, it feels as if we're making an architectural/semantic change to overcome a formatting problem. The elements ARE in language bloom-content2 etc. Are we sure there aren't rules we DO want triggered by that? Or that there won't be?
Can't we just enhance the rule that puts extra space above bloom-content2 to prevent it happening if there's a preceding bloom-editable? One way might be .bloom-content2 ~ .bloom-editable {margin-top: 12px} (that is, rule only fires for bloom-content2 if the preceding sibling is bloom-editable)

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomTests/Book/HtmlDomTests.cs, line 770 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1644#-KguYggKdCskpcOGhMbb:-KguYggKdCskpcOGhMbc:bnghfbx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d6ef9cf13d67757d580894614e15ea83045496e2/src/BloomTests/Book/HtmlDomTests.cs#L770)):*
> ```Smalltalk
> 		[TestCase("class1 class2 class3", "class1", "class2 class3")]
> 		[TestCase("class1 class2 class3", "class2", "class1 class3")]
> 		[TestCase("class1 class2 class3", "class3", "class1 class2")]
> ```

Should be at least one test case where the classToRemove is not present. Possibly with and without excess white space in the input. (Also below).

---

*[src/BloomTests/Book/HtmlDomTests.cs, line 808 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1644#-KguZrmNUixD9unIywAV:-KguZrmOdXKgQJ_YEJKk:b-szke2p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d6ef9cf13d67757d580894614e15ea83045496e2/src/BloomTests/Book/HtmlDomTests.cs#L808)):*
> UpdateContentLanguageClasses
Do we (or could we) have unit tests that could verify the changed behavior of this method?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1644#-:-Kgu_i4W_vsQWh_raF12:bkleeg4)*

**Comment by hatton** [comment]
@johnthomson  I appreciate the question. It's the right question to ask.  I think this is doing exactly the right *semantic* thing. We are tightening up the semantics of "content2" to mean "The second block of text". Previously it was getting muddled to mean something akin to "L2, unless L2 isn't selected, in which case L3". Indeed, if we weren't under the current time pressure, we might want to consider migrating "bloom-content2" --> "bloom-secondVisibleTextBlock". (and same for content3).

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1644#-:-KgugOKFyq-Wug9oiYkx:b-lo3so6)*

**Comment by andrew-polk** [comment]
Btw, for the curious, sibling and first/last rules don't work because the other divs are there, just hidden. There is no way, in css, to know if something is hidden. Additionally, we don't even know what order the divs will be in within the translation group.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomTests/Book/HtmlDomTests.cs, line 770 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1644#-KguYggKdCskpcOGhMbb:-KgujYDTNyFeTU9Uaame:b-zcjvte) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d6ef9cf13d67757d580894614e15ea83045496e2/src/BloomTests/Book/HtmlDomTests.cs#L770)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Should be at least one test case where the classToRemove is not present. Possibly with and without excess white space in the input. (Also below).
</blockquote></details>

Thanks

---

*[src/BloomTests/Book/HtmlDomTests.cs, line 808 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1644#-KguZrmNUixD9unIywAV:-KgujYpRK2-kjaxBXqhT:b-2dvv2f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d6ef9cf13d67757d580894614e15ea83045496e2/src/BloomTests/Book/HtmlDomTests.cs#L808)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

> UpdateContentLanguageClasses
Do we (or could we) have unit tests that could verify the changed behavior of this method?
</blockquote></details>

Let me see...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1644#-:-Kguj6piZve03G3jCZ5t:b-frgf22)*

**Comment by andrew-polk** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomTests/Book/HtmlDomTests.cs, line 770 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1644#-KguYggKdCskpcOGhMbb:-KgyE8ywD3nRhUqzZv9k:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d6ef9cf13d67757d580894614e15ea83045496e2/src/BloomTests/Book/HtmlDomTests.cs#L770)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Thanks
</blockquote></details>

Done.

---

*[src/BloomTests/Book/HtmlDomTests.cs, line 808 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1644#-KguZrmNUixD9unIywAV:-KgyEA4Bd4J233d1x6G5:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d6ef9cf13d67757d580894614e15ea83045496e2/src/BloomTests/Book/HtmlDomTests.cs#L808)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let me see...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1644)*

**Comment by JohnThomson** [comment]
If bloom-content2 is supposed to mean "the second visible block" (and presumably, bloom-content3 "the third visible block" and content1 the first), then I don't think we've quite achieved it. Rather, what we have is content1 on the vernacular block, if present; content2 on the N1 language block, if present and at least one other block is present; and content3 on the N2 language block, if present and at least one other is present.
Which incidentally suggests a possible problem: if default languages is N1,N2 then content2 will still be applied to the first even though there is nothing before it so we don't want the extra space. Probably nothing actually uses N2, N3 but I think we should be clear (be nice to comment somewhere!) exactly what these three classes are intended to mean and then make sure they are put in the right places to achieve that.
Mind you, I'm not sure what might break if we put bloom-content1 on the N1 or N2 block when it's the only one shown...quite possible we have some rules which assume it means vernacular.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomTests/Book/TranslationGroupManagerTests.cs, line 273 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1644#-Kgyov1vQuq20ghMUG_z:-Kgyov1vQuq20ghMUGa-:b-zhcsxx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c86d202a5d1c3c38d1dfd506919d7aa78d24b31c/src/BloomTests/Book/TranslationGroupManagerTests.cs#L273)):*
> ```Smalltalk
> 			var pageDiv = (XmlElement)dom.SafeSelectNodes("//div[contains(@class,'bloom-page')]")[0];
> 			TranslationGroupManager.UpdateContentLanguageClasses(pageDiv, _collectionSettings.Object, "xyz", "fr", null);
> 			AssertThatXmlIn.Dom(dom).HasSpecifiedNumberOfMatchesForXpath("//div[contains(@class, 'bloom-content2')]", 0);
> ```

I like to use HasNoMatchesFor since I often misread tests like this and wonder why the result should have this. That zero is pretty inconspicuous. I doubt it's worth a new commit if nothing else changes, but for future reference.
Is it worth also asserting that content3 is not present? (Or maybe it should be...depending on the answer to my latest question at the top...if so assert that?)
My intuition based on John's explanation of the new semantics is that this case should have (only) bloom-content1.
Similarly in following tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1644#-:-KgyqI9ZkstNTT6WFWt1:bab8bfp)*

**Comment by andrew-polk** [comment]
We definitely have styling rules on bloom-content1 and even a few on bloom-content2 and bloom-content3.

You are right that my solution does not exactly align with @Hatton's comment above. Additionally, JT's suggestion that if data-default-languages is N1,N2, the gap will still be there is correct.

JH convinced me yesterday all of this was not a problem, but it is very possible I didn't properly communicate the facts behind my misgivings about the implementation.

@Hatton, do we need to discuss this further?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1644#-:-KgzBGXADr8h53PNkTC6:b5vhl6k)*

**Comment by JohnThomson** [comment]
To be clear, I'm not renewing my previous suggestion. Both of you convinced me that changing where we put bloom-contentX is the way to go. I just want us to be clear where they ought to be put (and achieve that).

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1644#-:-KgzPkI6VxQNp7G8kpmU:bj2xl2h)*

**Comment by hatton** [comment]
We're going to get by with #1652 for 3.9, then return to this in 4.0.

**Pull request closed without merging**
