### PR TITLE
BL-11856 Make TC email match disregard case

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6197)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6197)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomExe/TeamCollection/TeamCollectionManager.cs` line 120 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6197#-NiL_3YO3Di9JhuBvxLj:-NiL_3YO3Di9JhuBvxLk:b-vfbcbw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cdfe5a243842cd6185d6d0006f2060f5ad3f5458/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L120)):*
> ```Smalltalk
> 				if (settings.Administrators.Length == 0)
> 					return true; // legacy TC, no admin recorded
> 				return settings.Administrators.Contains(CurrentUser, StringComparer.CurrentCultureIgnoreCase);
> ```

Why CurrentCultureIgnoreCase rather than InvariantCultureIgnoreCase?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6197)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomExe/TeamCollection/TeamCollectionManager.cs` line 120 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6197#-NiL_3YO3Di9JhuBvxLj:-NiL_3YO3Di9JhuBvxLk:b-vfbcbw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cdfe5a243842cd6185d6d0006f2060f5ad3f5458/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L120)):*
> ```Smalltalk
> 				if (settings.Administrators.Length == 0)
> 					return true; // legacy TC, no admin recorded
> 				return settings.Administrators.Contains(CurrentUser, StringComparer.CurrentCultureIgnoreCase);
> ```

Why CurrentCultureIgnoreCase rather than InvariantCultureIgnoreCase?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6197)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomExe/TeamCollection/TeamCollectionManager.cs` line 120 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6197#-NiL_3YO3Di9JhuBvxLj:-NiL_3YO3Di9JhuBvxLk:b-vfbcbw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cdfe5a243842cd6185d6d0006f2060f5ad3f5458/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L120)):*
> ```Smalltalk
> 				if (settings.Administrators.Length == 0)
> 					return true; // legacy TC, no admin recorded
> 				return settings.Administrators.Contains(CurrentUser, StringComparer.CurrentCultureIgnoreCase);
> ```

Why CurrentCultureIgnoreCase rather than InvariantCultureIgnoreCase?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6197)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/TeamCollection/TeamCollectionManager.cs` line 120 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6197#-NiL_3YO3Di9JhuBvxLj:-NiLd2_H3Wnzwq7fj8OF:b-jddmzs) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cdfe5a243842cd6185d6d0006f2060f5ad3f5458/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L120)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Why CurrentCultureIgnoreCase rather than InvariantCultureIgnoreCase?
</blockquote></details>

I wondered about that. Can email addresses have characters from other scripts in them, or are they limited to ascii characters, or something?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6197)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/TeamCollection/TeamCollectionManager.cs` line 120 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6197#-NiL_3YO3Di9JhuBvxLj:-NiM9SYfAuERK8UQsCjA:b-ojf8om) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cdfe5a243842cd6185d6d0006f2060f5ad3f5458/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L120)):*
> With the introduction of [internationalized domain names](https://en.wikipedia.org/wiki/Internationalized_domain_name "Internationalized domain name"), efforts are progressing to permit non-ASCII characters in email addresses. (from https://en.wikipedia.org/wiki/Email_address)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6197)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomExe/TeamCollection/TeamCollectionManager.cs` line 120 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6197#-NiL_3YO3Di9JhuBvxLj:-NiMD7HE45FTMYT4XBPd:b-67yt3v) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cdfe5a243842cd6185d6d0006f2060f5ad3f5458/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L120)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

> With the introduction of [internationalized domain names](https://en.wikipedia.org/wiki/Internationalized_domain_name "Internationalized domain name"), efforts are progressing to permit non-ASCII characters in email addresses. (from https://en.wikipedia.org/wiki/Email_address)
</blockquote></details>

It is very possible I'm not thinking clearly.
But I'm not seeing why we would ever want the comparison to change based on which culture the current user is using.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6197)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/TeamCollection/TeamCollectionManager.cs` line 120 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6197#-NiL_3YO3Di9JhuBvxLj:-Ni_eUbh6dY1O6oeD8e3:b-8vwgy1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cdfe5a243842cd6185d6d0006f2060f5ad3f5458/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L120)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

It is very possible I'm not thinking clearly.
But I'm not seeing why we would ever want the comparison to change based on which culture the current user is using.
</blockquote></details>

Done. Switched to `InvariantCultureIgnoreCase` after discussion this morning.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6197)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
