### PR TITLE
Optimize page switching

### PR DESCRIPTION
**Pull request by JohnThomson**
Three distinct changes, not very successful, but possibly worth having anyway, especially the Javascript ones.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1714)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 3 of 3 files at r1, 4 of 4 files at r2, 3 of 3 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/pageChooser/launch-page-chooser.ts, line 88 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1714#-KnGIRaHpZXLheR9xUjf:-KnGIRaHpZXLheR9xUjg:b-r7z0xo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/39f012fe7aac97b64d273510fcd48cea86391176/src/BloomBrowserUI/pageChooser/launch-page-chooser.ts#L88)):*
> ```XML
>         document.dispatchEvent(event);
>     }
>     // For when we someday change this file to TypeScript... since the above ctor is not declared anywhere.
> ```

Presumably you moved this from somewhere, but the file is now typescript. So the comment should either be removed or modified.

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 205 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1714#-KnGJchsMdWusHNPwq7y:-KnGJchsMdWusHNPwq7z:b-yb96x7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4449ba376991c2ec93e56338f6740bb91fb354c6/src/BloomExe/web/EnhancedImageServer.cs#L205)):*
> ```Smalltalk
> 		{
> 			Tuple<string, string> previousReply;
> 			if (_urlToFileAndType.TryGetValue(info.RawUrl, out previousReply))
> ```

I thought we were dubious of this change wondering if we would cache thing we shouldn't. I thought we were going to try implementing client-side caching first.

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 219 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1714#-KnGJLfymErlUjXsKyxi:-KnGJLfymErlUjXsKyxj:bvyuzw2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4449ba376991c2ec93e56338f6740bb91fb354c6/src/BloomExe/web/EnhancedImageServer.cs#L219)):*
> ```Smalltalk
> 				&& !info.FileUsedForResponse.StartsWith(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments)))
> 			{
> 				// This is very inefficient but it updates the dictionary without needing locking
> ```

Could you use ConcurrentDictionary instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1714)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/pageChooser/launch-page-chooser.ts, line 88 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1714#-KnGIRaHpZXLheR9xUjf:-KnGTTaM2yeI8Y-P8TJq:bre04xx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/39f012fe7aac97b64d273510fcd48cea86391176/src/BloomBrowserUI/pageChooser/launch-page-chooser.ts#L88)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Presumably you moved this from somewhere, but the file is now typescript. So the comment should either be removed or modified.
</blockquote></details>

In both places! Will do, if we go ahead with this.

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 205 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1714#-KnGJchsMdWusHNPwq7y:-KnGSpQKNxCxWj0ihQ5G:bqy0zpm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4449ba376991c2ec93e56338f6740bb91fb354c6/src/BloomExe/web/EnhancedImageServer.cs#L205)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I thought we were dubious of this change wondering if we would cache thing we shouldn't. I thought we were going to try implementing client-side caching first.
</blockquote></details>

I'm not very nervous about that since we're only caching the file path, not its content. I can't think of a Bloom URL that resolves to one file path at one moment and another one later. I suppose there COULD be such a thing...we can certainly decide this change isn't worth it. I thought it worth others taking a look at. I'm experimenting with client caching now...some issues there, too (see flowdock).

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 219 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1714#-KnGJLfymErlUjXsKyxi:-KnGSgwrv7KyHcXQ3kE3:b86lh67) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4449ba376991c2ec93e56338f6740bb91fb354c6/src/BloomExe/web/EnhancedImageServer.cs#L219)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Could you use ConcurrentDictionary instead?
</blockquote></details>

Tried that and it still slowed things down rather than helping, just like when I did my own synchronizing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1714)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r5, 4 of 4 files at r6, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1714#-:-KnL4O1yQeWLyGW_8evt:bnfp4nl)*

**Comment by hatton** [comment]
Reviewed 2 of 3 files at r3, 2 of 4 files at r4, 1 of 5 files at r5, 3 of 4 files at r6, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/BloomBrowserUI/bookEdit/editViewFrame.ts, line 50 at r7](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1714#-KnL62yyoGxj8vyUhRl8:-KnL62yyoGxj8vyUhRl9:bffvd3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95be40880e532a1808ab622986f47c4529ce8903/src/BloomBrowserUI/bookEdit/editViewFrame.ts#L50)):*
> ```XML
> 
> // Do this task when the toolbox is loaded. If it isn't already, we set a timeout and do it when we can.
> export function doWhenToolboxLoaded(task) {
> ```

Is it possible to put a signature on that task parameter?

---

*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 294 at r7](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1714#-KnL6GM0_TpLSgU5oUZx:-KnL6GM0_TpLSgU5oUZy:b-7me1vz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95be40880e532a1808ab622986f47c4529ce8903/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L294)):*
> ```XML
>     });
> 
>     var rootFrameExports = getEditViewFrameExports();
> ```

I think these var's can be let's?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1714)*

**Comment by JohnThomson** [comment]
Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/editViewFrame.ts, line 50 at r7](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1714#-KnL62yyoGxj8vyUhRl8:-KnL_oyTx-AkVD1yastW:b-gjug15) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95be40880e532a1808ab622986f47c4529ce8903/src/BloomBrowserUI/bookEdit/editViewFrame.ts#L50)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is it possible to put a signature on that task parameter?
</blockquote></details>

Sort of. We don't seem to have a signature for what getToolboxFrameExports() returns, but I put one showing task is a function with one parameter and giving it a name.

---

*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 294 at r7](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1714#-KnL6GM0_TpLSgU5oUZx:-KnL_nO8BsguLdd75zfR:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95be40880e532a1808ab622986f47c4529ce8903/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L294)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think these var's can be let's?
</blockquote></details>

Done.

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 205 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1714#-KnGJchsMdWusHNPwq7y:-KnKX8Mwy3FETZXPIKS8:b-20mmjb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4449ba376991c2ec93e56338f6740bb91fb354c6/src/BloomExe/web/EnhancedImageServer.cs#L205)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm not very nervous about that since we're only caching the file path, not its content. I can't think of a Bloom URL that resolves to one file path at one moment and another one later. I suppose there COULD be such a thing...we can certainly decide this change isn't worth it. I thought it worth others taking a look at. I'm experimenting with client caching now...some issues there, too (see flowdock).
</blockquote></details>

Removed this kind of caching.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1714)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1714)*

**Pull request merged**
