### PR TITLE
BL-5243 Detect and inform about Defender

### PR DESCRIPTION
**Pull request by gmartin7**
* Windows Defender update in October 2017 added a
   'feature' called Controlled Folder Access that causes problems
   when saving CollectionSettings in Documents folder.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1960)

### CODE REVIEW

**Comment by StephenMcConnel** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Collection/CollectionSettings.cs, line 455 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-Kz-tH4sWIoF5rXHhKf9:-Kz-tH4t3eUzRGFlXqoD:b-nyqwi7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e202b9c745aa3b85791b2a72723a577ffc742cc/src/BloomExe/Collection/CollectionSettings.cs#L455)):*
> ```Smalltalk
> 				// Quit
> 				Environment.Exit(-1);
> 			}
> ```

Should we verify that the problem is in the user's Documents folder?  since that's what the error message references.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960)*

**Comment by gmartin7** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Collection/CollectionSettings.cs, line 455 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-Kz-tH4sWIoF5rXHhKf9:-Kz-zDDYhZVsHeElI-6W:bjsbxge) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e202b9c745aa3b85791b2a72723a577ffc742cc/src/BloomExe/Collection/CollectionSettings.cs#L455)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Should we verify that the problem is in the user's Documents folder?  since that's what the error message references.
</blockquote></details>

... and I suppose it's only applicable to Windows too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960)*

**Comment by hatton** [comment]
> Similar to how we put up the Integrity Check dialog if we detect that pieces of Bloom have gone missing

So by that, I meant, not catch it somewhere that it's breaking us, but rather, handle it proactively, including for the initial run where, for example, we don't have any css in play yet (not until they create a collection). So  please create a class that for detecting and reporting this, and have program.cs call it, probably right after program.cs does the integrity detection. thx.

**Comment by gmartin7** [comment]
Ah! I never saw that line, for some reason! Okey - dokey, wilco.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-:-Kz0W9-HqP1IcP41VRR9:b-h5qw8f)*

**Comment by gmartin7** [comment]
done

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-:-Kz0teaThqVlU15c04F-:bb7f2mf)*

**Comment by hatton** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/BloomExe/MiscUI/BloomSystemCheck.cs, line 14 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-Kz6-H8Yfa9B889a6z-_:-Kz6-H8Yfa9B889a6z-a:b-7atbgs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce8157438f148bc7bf3575fd839bca8a10672ebb/src/BloomExe/MiscUI/BloomSystemCheck.cs#L14)):*
> ```Smalltalk
> 	/// This is a class for testing various user System things to make sure Bloom can run safely.
> 	/// </summary>
> 	public static class BloomSystemCheck
> ```

Ideally classes should do one thing, and that's what this does.  So DefenderFolderProtectionCheck would be a better name. 

---

*[src/BloomExe/MiscUI/BloomSystemCheck.cs, line 17 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-Kz60KOOg3OMusNRxAYT:-Kz60KOOg3OMusNRxAYU:b-j2q4xg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce8157438f148bc7bf3575fd839bca8a10672ebb/src/BloomExe/MiscUI/BloomSystemCheck.cs#L17)):*
> ```Smalltalk
> 	{
> 		private const string TestContents = "test";
> 		private const string TestFileName = "test.txt";
> ```

It's fragile

---

*[src/BloomExe/MiscUI/BloomSystemCheck.cs, line 30 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-Kz6-jmTzjl1bSbmmAX-:-Kz6-jmTzjl1bSbmmAX0:bs4nytk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce8157438f148bc7bf3575fd839bca8a10672ebb/src/BloomExe/MiscUI/BloomSystemCheck.cs#L30)):*
> ```Smalltalk
> 			if (!Platform.IsWindows)
> 			{
> 				return true; // so far this is only needed on Windows
> ```

can remove the so far comment

---

*[src/BloomExe/MiscUI/BloomSystemCheck.cs, line 35 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-Kz60xLRQ_ZZn6ao38lF:-Kz60xLRQ_ZZn6ao38lG:bvfpgr1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce8157438f148bc7bf3575fd839bca8a10672ebb/src/BloomExe/MiscUI/BloomSystemCheck.cs#L35)):*
> ```Smalltalk
> 			try
> 			{
> 				RobustFile.WriteAllText(testPath, TestContents);
> ```

Style wise, I wouldn't have some special variable to hold text that you don't care about. It just makes this code look more complicated than it is.

---

*[src/BloomExe/MiscUI/BloomSystemCheck.cs, line 43 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-Kz60Wev5IceVI3sIFrX:-Kz60Wev5IceVI3sIFrY:b-mfk50b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce8157438f148bc7bf3575fd839bca8a10672ebb/src/BloomExe/MiscUI/BloomSystemCheck.cs#L43)):*
> ```Smalltalk
> 				return false;				
> 			}
> 			Cleanup(testPath);
> ```

So the assumption is that if there was an exception, then there will never be a file left over? Probably true. But Cleanup() works either way, so why not wrap this in finally{}.

---

*[src/BloomExe/MiscUI/BloomSystemCheck.cs, line 47 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-Kz6-tqXvQG0jmJONJox:-Kz6-tqXvQG0jmJONJoy:b-44v27j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce8157438f148bc7bf3575fd839bca8a10672ebb/src/BloomExe/MiscUI/BloomSystemCheck.cs#L47)):*
> ```Smalltalk
> 		}
> 
> 		private static string GetMyDocsTestPath
> ```

We probably care about my docs if we're about to create a "Bloom" directory (new installation) or a new Collection under "Bloom".  But we *always* care about the actual bloom collection folder, which could be anywhere on disk. Indeed, one work-around is to move your collection to some place that is not under Defender lock down.  <--- That all could be in a comment

So you're testing Mru. Two things
1) Since that isn't always in mydocs, the title is misleading
2) it's not obvious to me that this is the collection we're working with, so maybe a comment that says it is?

Ok, that still leaves the new collection problem to deal with somehow. I.e. even if the collection is in some other place (C:\Bloom), if they they go to make a new collection, will we fail?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960)*

**Comment by gmartin7** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/BloomExe/MiscUI/BloomSystemCheck.cs, line 14 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-Kz6-H8Yfa9B889a6z-_:-Kz9t6lu-SXC_LlgfTDS:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce8157438f148bc7bf3575fd839bca8a10672ebb/src/BloomExe/MiscUI/BloomSystemCheck.cs#L14)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Ideally classes should do one thing, and that's what this does.  So DefenderFolderProtectionCheck would be a better name. 
</blockquote></details>

Done.

---

*[src/BloomExe/MiscUI/BloomSystemCheck.cs, line 17 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-Kz60KOOg3OMusNRxAYT:-Kz9t8r3DbOl5zm9Czxn:b-tq9e74) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce8157438f148bc7bf3575fd839bca8a10672ebb/src/BloomExe/MiscUI/BloomSystemCheck.cs#L17)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

It's fragile
</blockquote></details>

The filename is fragile?

---

*[src/BloomExe/MiscUI/BloomSystemCheck.cs, line 30 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-Kz6-jmTzjl1bSbmmAX-:-Kz9tJkufktVplcvV_vE:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce8157438f148bc7bf3575fd839bca8a10672ebb/src/BloomExe/MiscUI/BloomSystemCheck.cs#L30)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

can remove the so far comment
</blockquote></details>

Done.

---

*[src/BloomExe/MiscUI/BloomSystemCheck.cs, line 35 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-Kz60xLRQ_ZZn6ao38lF:-Kz9tNyeh5FAagTIBHvi:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce8157438f148bc7bf3575fd839bca8a10672ebb/src/BloomExe/MiscUI/BloomSystemCheck.cs#L35)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Style wise, I wouldn't have some special variable to hold text that you don't care about. It just makes this code look more complicated than it is.
</blockquote></details>

Done.

---

*[src/BloomExe/MiscUI/BloomSystemCheck.cs, line 43 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-Kz60Wev5IceVI3sIFrX:-Kz9tPsgfWNwpMeq8EDh:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce8157438f148bc7bf3575fd839bca8a10672ebb/src/BloomExe/MiscUI/BloomSystemCheck.cs#L43)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

So the assumption is that if there was an exception, then there will never be a file left over? Probably true. But Cleanup() works either way, so why not wrap this in finally{}.
</blockquote></details>

Done.

---

*[src/BloomExe/MiscUI/BloomSystemCheck.cs, line 47 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-Kz6-tqXvQG0jmJONJox:-Kz9wGisA9rUuZt13CzD:byoboc2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce8157438f148bc7bf3575fd839bca8a10672ebb/src/BloomExe/MiscUI/BloomSystemCheck.cs#L47)):*
> Ok, that still leaves the new collection problem to deal with somehow. I.e. even if the collection is in some other place (C:\Bloom), if they they go to make a new collection, will we fail?

If the user has successfully moved their collection to a non-locked down location, and then goes back and tries to open one that is in the "normal" location, then yes I would expect it to fail. Do you want CollectionSettings to call this check also?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960)*

**Comment by hatton** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs, line 17 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-Kz60KOOg3OMusNRxAYT:-KzEKMwknB7QllKFcQmJ:bbfwwqt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce8157438f148bc7bf3575fd839bca8a10672ebb/src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs#L17)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

The filename is fragile?
</blockquote></details>

Sorry, that was a thought I was starting and abandoned but failed to delete. The full thought was something about what if the "test.txt" from a previous run is still there, could you have a false positive, vs. using a random file name. Don't worry about it.

---

*[src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs, line 47 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-Kz6-tqXvQG0jmJONJox:-KzEKgxGOtCdWMRR35HM:b-uz6i4s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce8157438f148bc7bf3575fd839bca8a10672ebb/src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs#L47)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

> Ok, that still leaves the new collection problem to deal with somehow. I.e. even if the collection is in some other place (C:\Bloom), if they they go to make a new collection, will we fail?

If the user has successfully moved their collection to a non-locked down location, and then goes back and tries to open one that is in the "normal" location, then yes I would expect it to fail. Do you want CollectionSettings to call this check also?
</blockquote></details>

Yah. How about 

if(!DefenderFolderProtectionCheck.CanWriteToDirectory(path you want to check)){
     DefenderFolderProtectionCheck.NotifyUser(path you want to check)
}

Then you can 

---

*[src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs, line 71 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-KzEM02BhEAylJvRGbkb:-KzEM02BhEAylJvRGbkc:b-d4em28) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ec3a909a4aff71b1c77191a505767afee60a1eee/src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs#L71)):*
> ```Smalltalk
> 		{
> 			var heading = LocalizationManager.GetString("DefenderFolderProtectionCheck.WindowsDefenderProblemHeading", "Check Windows Defender “Controlled Access”.");
> 			var mainMsg = LocalizationManager.GetString("DefenderFolderProtectionCheck.WindowsDefenderProblem",
> ```

The general.specific seems backwards here. And I think we have a "general" for errors?

Something like

DefenderFolderProtectionCheck.WindowsDefenderProblem -->  Errors.DefenderFolderProtection

---

*[src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs, line 72 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-KzEMKlsfdB9QwHSL_EU:-KzEMKlsfdB9QwHSL_EV:bf0qowa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ec3a909a4aff71b1c77191a505767afee60a1eee/src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs#L72)):*
> ```Smalltalk
> 			var heading = LocalizationManager.GetString("DefenderFolderProtectionCheck.WindowsDefenderProblemHeading", "Check Windows Defender “Controlled Access”.");
> 			var mainMsg = LocalizationManager.GetString("DefenderFolderProtectionCheck.WindowsDefenderProblem",
> 				"A Windows update around October 2017 added a feature which prevents Bloom from being able to write its own files, if the collection folder is in a “Controlled Folder”. Your “Documents” folder is one such “Controlled Folder”, and by default, that is where Bloom collections live.");
> ```

"This program cannot write to the folder '......'. This might be caused by Windows Defender "Controlled Folder Access" or some other virus protection. "

Then we have the option of putting this in libpalaso for all the other apps.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960)*

**Comment by gmartin7** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs, line 17 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-Kz60KOOg3OMusNRxAYT:-KzPVHe4hJH5wpAHXWBy:bx5uu0y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce8157438f148bc7bf3575fd839bca8a10672ebb/src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs#L17)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Sorry, that was a thought I was starting and abandoned but failed to delete. The full thought was something about what if the "test.txt" from a previous run is still there, could you have a false positive, vs. using a random file name. Don't worry about it.
</blockquote></details>

Yeah, I was looking for an easy way to generate a random filename without actually creating the file... Didn't find such.

---

*[src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs, line 47 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-Kz6-tqXvQG0jmJONJox:-KzP_nvcW4YV6HCapdjE:bhwld3u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce8157438f148bc7bf3575fd839bca8a10672ebb/src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs#L47)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Yah. How about 

if(!DefenderFolderProtectionCheck.CanWriteToDirectory(path you want to check)){
     DefenderFolderProtectionCheck.NotifyUser(path you want to check)
}

Then you can 
</blockquote></details>

Done... not quite the way you mention, but...

---

*[src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs, line 71 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-KzEM02BhEAylJvRGbkb:-KzPQfgN9VtKwXq7yFI3:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ec3a909a4aff71b1c77191a505767afee60a1eee/src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs#L71)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

The general.specific seems backwards here. And I think we have a "general" for errors?

Something like

DefenderFolderProtectionCheck.WindowsDefenderProblem -->  Errors.DefenderFolderProtection
</blockquote></details>

Done.

---

*[src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs, line 72 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-KzEMKlsfdB9QwHSL_EU:-KzPT-ZIzCVgcf7yQ_Jl:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ec3a909a4aff71b1c77191a505767afee60a1eee/src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs#L72)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

"This program cannot write to the folder '......'. This might be caused by Windows Defender "Controlled Folder Access" or some other virus protection. "

Then we have the option of putting this in libpalaso for all the other apps.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960)*

**Comment by andrew-polk** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs, line 17 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-Kz60KOOg3OMusNRxAYT:-KzPop5hr5dBaRR49cha:b-urow1m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce8157438f148bc7bf3575fd839bca8a10672ebb/src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs#L17)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Yeah, I was looking for an easy way to generate a random filename without actually creating the file... Didn't find such.
</blockquote></details>

TempFile.CreateAndGetPathButDontMakeTheFile

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960)*

**Comment by gmartin7** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs, line 17 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960#-Kz60KOOg3OMusNRxAYT:-KzQ7-0Z8mdZ7200Xi01:bfki75d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce8157438f148bc7bf3575fd839bca8a10672ebb/src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs#L17)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

TempFile.CreateAndGetPathButDontMakeTheFile
</blockquote></details>

Thanks. That's better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1960)*

**Pull request merged**
