### PR TITLE
BL-6220 Handle Refresh of Ace by Daisy in Edit mode

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2575)

### CODE REVIEW

**Comment by JohnThomson** [comment]
The change to EditingModel alone might be sufficient, but the other changes seemed worth keeping by way of future-proofing some code a bit.

**Review by StephenMcConnel — CHANGES_REQUESTED** [review]
One minor question, but otherwise :lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2575#-:-LH5HLRmCFpC01GufqQh:b-y3pipn)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Edit/EditingModel.cs, line 110 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2575#-LH5H5it60y5yqXE8ym0:-LH5H5iu7uY0t9mwXl6i:b-k2h24m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/faf4cb5f225e8b9ffb0be6f51172a7a1a5300b6a/src/BloomExe/Edit/EditingModel.cs#L110)):*
> ```Smalltalk
> 				{
> 					OnBookSelectionChanged(null, null);
> 				}
> ```

Is there anything needed when book != CurrentBook?  or would the desired behavior be taken care of elsewhere?

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2575)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2575)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Edit/EditingModel.cs, line 110 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2575#-LH5H5it60y5yqXE8ym0:-LH5JO8kArsf_8mYaAku:bmlgrtq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/faf4cb5f225e8b9ffb0be6f51172a7a1a5300b6a/src/BloomExe/Edit/EditingModel.cs#L110)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Is there anything needed when book != CurrentBook?  or would the desired behavior be taken care of elsewhere?
</blockquote></details>

I don't think there is any desired behavior in the EditingModel if some book it's not showing gets refreshed...EditingModel is all about that one book. I can't imagine why this restriction wasn't there all along. In the current case, the book we're refreshing is the private copy made as a starting point for the epub; nothing else cares about that.

**Pull request merged**
