### PR TITLE
Fix bug suppressing recent notifications.

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4227)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4227)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 266 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4227#-MUEwXTD37KoVvTN9rva:-MUEwXTD37KoVvTN9rvb:bio86td) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91d25d46607048010d0f3078feebea8a8bcb00ff/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L266)):*
> ```Smalltalk
> 		}
> 
> 		// Return true if we have notified the user of changes recently. If we have NOT done so,
> ```

This says it's supposed to return true if recent, but I don't believe it does that.
And I observed in the debugger that with the original code, the first change is not acted upon.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4227)* status: all files reviewed, 1 unresolved discussion

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4227)* status: all files reviewed, 1 unresolved discussion

**Review by andrew-polk — APPROVED** [review]
> Dismissed @sujeffreyl from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4227)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Pull request merged**
