### PR TITLE
BL-5860 Enable typing image descriptions

### PR DESCRIPTION
**Pull request by JohnThomson**
Also: abandon using background image on cover
Also: imageContainer now uses box-sizing: border-box which may cause slight layout changes

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2330)

### CODE REVIEW

**Comment by hatton** [comment]
Reviewed 3 of 16 files at r1, 1 of 1 files at r2.
Review status: 4 of 15 files reviewed at latest revision, all discussions resolved.

---

*[src/BloomBrowserUI/bookEdit/js/bloomImages.ts, line 46 at r2](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2330#-LAV-iwb8f82grw_lQU-:-LAV-iwb8f82grw_lQU0:b-ra8j10) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e7b9b130ec35e2a56785c9bad3238941463a908/src/BloomBrowserUI/bookEdit/js/bloomImages.ts#L46)):*
> ```XML
> 
> export function SetupImage(image) {
>     // Remove any obsolete explicit image size and position left over from earlier versions of Bloom.
> ```

Yippee!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2330)*

**Comment by hatton** [comment]
Reviewed 8 of 16 files at r1.
Review status: 11 of 15 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2330)*

**Comment by hatton** [comment]
Reviewed 3 of 16 files at r1.
Review status: 14 of 15 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2330)*

**Comment by hatton** [comment]
Reviewed 1 of 16 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 11 at r2](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2330#-LAV2Nb0766AoGL27BHQ:-LAV2Nb0766AoGL27BHR:b-a0ndpm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e7b9b130ec35e2a56785c9bad3238941463a908/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L11)):*
> ```XML
> import { fireCSharpEditEvent } from "../../js/bloomEditing";
> 
> interface IImageDescriptionState {
> ```

You don't need empty props or state interfaces. Just write

    extends React.Component {

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 23 at r2](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2330#-LAV2qQd5tpKcS0lZ2_G:-LAV2qQd5tpKcS0lZ2_H:b-8ku4xe) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e7b9b130ec35e2a56785c9bad3238941463a908/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L23)):*
> ```XML
> export class ImageDescriptionToolControls extends React.Component<{}, IImageDescriptionState> {
>     constructor() {
>         super({});
> ```

This stuff isn't needed. Probably the whole constructor isn't needed.

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 30 at r2](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2330#-LAV3aNM7VnbpsFbmd3h:-LAV3aNM7VnbpsFbmd3i:b-v36yia) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e7b9b130ec35e2a56785c9bad3238941463a908/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L30)):*
> ```XML
>     public render() {
>         return (
>             <div className={"imageDescriptionBody"}>
> ```

I'm confused about "imageDescriptionBody"... would have thought I was looking at a currently-empty Image Description Tool; this name made me think it was the description itself.

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 48 at r2](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2330#-LAV3oCt3PkgMMH7vLzd:-LAV3oCt3PkgMMH7vLze:bqcgsd9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e7b9b130ec35e2a56785c9bad3238941463a908/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L48)):*
> ```XML
>     makeRootElement(): HTMLDivElement {
>         const root = document.createElement("div");
>         root.setAttribute("class", "videoBody");
> ```

"video" snuck in here...

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 69 at r2](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2330#-LAV428bB66u0rqHOx5b:-LAV428bB66u0rqHOx5c:bclolsr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e7b9b130ec35e2a56785c9bad3238941463a908/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L69)):*
> ```XML
> 
>     id(): string {
>         return "imageDescription";
> ```

How aout "imageDescriptionTool". 'cause it's not an image description.

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 74 at r2](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2330#-LAV32dn1nuOkiCaXLQj:-LAV32dn1nuOkiCaXLQk:b-m5jn2d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e7b9b130ec35e2a56785c9bad3238941463a908/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L74)):*
> ```XML
>     // required for ITool interface
>     hasRestoredSettings: boolean;
>     /* tslint:disable:no-empty */ // We need these to implement the interface, but don't need them to do anything.
> ```

I expect if you rebase you onto 4.2 again you can remove these tslint off switches.

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 103 at r2](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2330#-LAV28l8492wWD4-6tPe:-LAV28l8492wWD4-6tPf:bs1vy8i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e7b9b130ec35e2a56785c9bad3238941463a908/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L103)):*
> ```XML
>         if (addedTranslationGroup) {
>             // This inserts all the right bloom-editable divs in whatever languages are needed.
>             fireCSharpEditEvent("saveChangesAndRethinkPageEvent", "");
> ```

Would be great to always introduce api calls as needed, according to our current architecture, rather than perpetrating the old one.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2330)*

**Comment by JohnThomson** [comment]
Review status: 8 of 15 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 11 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2330#-LAV2Nb0766AoGL27BHQ:-LB7cAkC0flyL8_smFdO:b-f66jru) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e7b9b130ec35e2a56785c9bad3238941463a908/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L11)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

You don't need empty props or state interfaces. Just write

    extends React.Component {
</blockquote></details>

I was anticipating that there will eventually be something stateful in this control. But I suppose it can wait till then. (Also didn't know of this possible simplification.)

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 23 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2330#-LAV2qQd5tpKcS0lZ2_G:-LBNRnQO7H7b0iWzptWa:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e7b9b130ec35e2a56785c9bad3238941463a908/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L23)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This stuff isn't needed. Probably the whole constructor isn't needed.
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 30 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2330#-LAV3aNM7VnbpsFbmd3h:-LBNZVrO1x0YuUrGsHkj:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e7b9b130ec35e2a56785c9bad3238941463a908/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L30)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I'm confused about "imageDescriptionBody"... would have thought I was looking at a currently-empty Image Description Tool; this name made me think it was the description itself.
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 48 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2330#-LAV3oCt3PkgMMH7vLzd:-LBNZWaE6qV5JFNVvEld:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e7b9b130ec35e2a56785c9bad3238941463a908/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L48)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

"video" snuck in here...
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 69 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2330#-LAV428bB66u0rqHOx5b:-LBNSeo4ANL4cOV0tWAr:b-nrevnv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e7b9b130ec35e2a56785c9bad3238941463a908/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L69)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

How aout "imageDescriptionTool". 'cause it's not an image description.
</blockquote></details>

Various things append 'Tool' to this ID, so if you put 'Tool' in the ID you end up with imageDescriptionToolTool in undesirable places, including the UI, IIRC. Maybe there's some way to improve this...

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 74 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2330#-LAV32dn1nuOkiCaXLQj:-LBNZFai8ye3Evb9rmCu:b47thq0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e7b9b130ec35e2a56785c9bad3238941463a908/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L74)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I expect if you rebase you onto 4.2 again you can remove these tslint off switches.
</blockquote></details>

Done. (Switched to inherit from new adapter class.)

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 103 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2330#-LAV28l8492wWD4-6tPe:-LBNbVle5QA6rGd8_k9K:b-2lv6k3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e7b9b130ec35e2a56785c9bad3238941463a908/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L103)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Would be great to always introduce api calls as needed, according to our current architecture, rather than perpetrating the old one.
</blockquote></details>

This is a pre-existing way to deal with this situation, so changing it without duplicating is a bit of a project. I'm going to work on it as a separate commit. Up to you whether to wait for it before merging what I have.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2330)*

**Comment by hatton** [comment]
Review status: 8 of 15 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 11 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2330#-LAV2Nb0766AoGL27BHQ:-LBNlk-41q8NyfTssdKd:baheueq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e7b9b130ec35e2a56785c9bad3238941463a908/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L11)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I was anticipating that there will eventually be something stateful in this control. But I suppose it can wait till then. (Also didn't know of this possible simplification.)
</blockquote></details>

Reviewable is still showing the old code to me

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 69 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2330#-LAV428bB66u0rqHOx5b:-LBNlQJt05jZ78hXCNYg:b-h9bt8l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e7b9b130ec35e2a56785c9bad3238941463a908/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L69)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Various things append 'Tool' to this ID, so if you put 'Tool' in the ID you end up with imageDescriptionToolTool in undesirable places, including the UI, IIRC. Maybe there's some way to improve this...
</blockquote></details>

I saw that appending somewhere and thought "that's just going to lead to confusion". Maybe it's time to remove it?

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 74 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2330#-LAV32dn1nuOkiCaXLQj:-LBNlqkr0dgRYwZbSFci:b7084c2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e7b9b130ec35e2a56785c9bad3238941463a908/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L74)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done. (Switched to inherit from new adapter class.)
</blockquote></details>

Not seeing it yet

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 103 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2330#-LAV28l8492wWD4-6tPe:-LBNluzp29gPmxJC9Q_g:bb7efny) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e7b9b130ec35e2a56785c9bad3238941463a908/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L103)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This is a pre-existing way to deal with this situation, so changing it without duplicating is a bit of a project. I'm going to work on it as a separate commit. Up to you whether to wait for it before merging what I have.
</blockquote></details>

cool

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2330)*

**Comment by hatton** [comment]
Review status: 4 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 77 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2330#-LBW3hN9CO6NyrT61zC5:-LBW3hN9CO6NyrT61zC6:bx3nhvs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e7b9b130ec35e2a56785c9bad3238941463a908/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L77)):*
> ```XML
>     configureElements(container: HTMLElement) { }
>     finishToolLocalization(pane: HTMLElement) { }
>     /* tslint:enable:no-empty */
> ```

these tslint:empty's should not be needed anymore. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2330)*

**Pull request merged**
