### PR TITLE
Fix unescaped ampersands in LibraryListView (BL-9732)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4351)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4351)* status: all files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 371 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4351#-MXs2B_8Eqa8CkVPxYEf:-MXs2B_8Eqa8CkVPxYEg:b-jx5l42) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/21438459b4bfd0174b2f6991bcc51d4250deeec8/src/BloomExe/CollectionTab/LibraryListView.cs#L371)):*
> ```Smalltalk
> 				var lockNoticeLabel = new Label()
> 					{
> 						Text = TextUtils.EscapeForWinForms(lockNotice, true),
> ```

Would it be safer/better to do 
`lockNoticeLabel.SetTextSafely(lockNotice);`
on the line after the constructor call instead?

Same for collectionHeader and bloomLibraryLink below.

On the one hand, it doesn't matter much. But on the other, if someone were ever to change the value of useMnemonic here, that would just flow automatically to SetTextSafely. And it seems more encapsulating.
___
*[src/BloomTests/CollectionTab/LibraryListViewTests.cs, line 175 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4351#-MXs1SiV8qZ51C8aWyXA:-MXs1SiW2BCvHdM_7G8L:bk8kma1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/21438459b4bfd0174b2f6991bcc51d4250deeec8/src/BloomTests/CollectionTab/LibraryListViewTests.cs#L175)):*
> ```
> TitleEncoded
> ```
I'm not sure what the right thing is here, but it isn't encoded, right?
Maybe ButtonTextCorrect is sufficient?

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4351)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 371 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4351#-MXs2B_8Eqa8CkVPxYEf:-MXs5fJwDiPIQJuc1bO-:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/21438459b4bfd0174b2f6991bcc51d4250deeec8/src/BloomExe/CollectionTab/LibraryListView.cs#L371)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Would it be safer/better to do 
`lockNoticeLabel.SetTextSafely(lockNotice);`
on the line after the constructor call instead?

Same for collectionHeader and bloomLibraryLink below.

On the one hand, it doesn't matter much. But on the other, if someone were ever to change the value of useMnemonic here, that would just flow automatically to SetTextSafely. And it seems more encapsulating.
</blockquote></details>

Done.
___
*[src/BloomTests/CollectionTab/LibraryListViewTests.cs, line 175 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4351#-MXs1SiV8qZ51C8aWyXA:-MXs6Ebj0onSTGB31kEO:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/21438459b4bfd0174b2f6991bcc51d4250deeec8/src/BloomTests/CollectionTab/LibraryListViewTests.cs#L175)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> TitleEncoded
> ```
I'm not sure what the right thing is here, but it isn't encoded, right?
Maybe ButtonTextCorrect is sufficient?
</blockquote></details>

Done.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4351)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs, line 116 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4351#-MXs7nS3-NFRD0BApfbk:-MXs7nS4866iU4C6BR4B:ba0frvt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b93d2f9681a177d8fd09ec4b46f06128439a628d/src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs#L116)):*
> ```Smalltalk
> 			button.ImageAlign = ContentAlignment.MiddleLeft;
> 			button.Click += clickHandler;
> 			button.SetTextSafely(buttonLabelPadding + localizedLabel);
> ```

I noticed that when you try to change collections, the collection name is printed wrong (missing the ampersand).

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4351)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4351)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

**Review by andrew-polk — APPROVED** [review]
> Dismissed @sujeffreyl from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4351)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4351)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Pull request merged**
