### PR TITLE
When current book renamed, update path in settings (BL-11284)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5220)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
One minor thing. But the related conversation in Flowdock should be fleshed out more before we merge, probably.

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5220#-:-N49tTd25gJN2_d0IfA4:bxhms4k)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/Edit/EditingView.cs` line 112 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5220#-N49fhjz0_7Y23P4W-bI:-N49fhjz0_7Y23P4W-bJ:bdr2xw0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/292fb1bb513507dba70c0dbeb4708c7698f107f4/src/BloomExe/Edit/EditingView.cs#L112)):*
> ```Smalltalk
> 			Controls.Remove(_topBarPanel);
> 			SetupBrowserContextMenu();
> 			bookRenamedEvent.Subscribe((oldNew) =>
> ```

I'm missing the meaning of `oldNew`. Should it be `newBookFolderPath`?



_Code quote:_
```Smalltalk
oldNew
```

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5220)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/Edit/EditingView.cs` line 112 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5220#-N49fhjz0_7Y23P4W-bI:-N4CnR5iCDYPVg-koUo8:bkvnvj4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/292fb1bb513507dba70c0dbeb4708c7698f107f4/src/BloomExe/Edit/EditingView.cs#L112)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm missing the meaning of `oldNew`. Should it be `newBookFolderPath`?
</blockquote></details>

It's a KeyValuePair where the key is the old path and the value is the new path.
I have no recollection of why I (or someone) used that rather than a tuple or more specific object for the BookRenamedEvent, but the old name in this context was definitely misleading.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5220)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/Edit/EditingView.cs` line 112 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5220#-N49fhjz0_7Y23P4W-bI:-N4DYsYh1zOqSrj8cKBx:b764m1r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/292fb1bb513507dba70c0dbeb4708c7698f107f4/src/BloomExe/Edit/EditingView.cs#L112)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's a KeyValuePair where the key is the old path and the value is the new path.
I have no recollection of why I (or someone) used that rather than a tuple or more specific object for the BookRenamedEvent, but the old name in this context was definitely misleading.
</blockquote></details>

How about oldToNewPathKvp or just oldToNewPath?

**Review by JohnThomson — COMMENTED** [review]
https://issues.bloomlibrary.org/youtrack/issue/BL-11284 I think captures what we decided to do.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5220#-:-N4Dddb_9kkzZ4Jt43r6:b-260oyf)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/Edit/EditingView.cs` line 112 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5220#-N49fhjz0_7Y23P4W-bI:-N4DeaUqDbn6diz4l8er:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/292fb1bb513507dba70c0dbeb4708c7698f107f4/src/BloomExe/Edit/EditingView.cs#L112)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

How about oldToNewPathKvp or just oldToNewPath?
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5220)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by gmartin7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5220)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/BookStorage.cs` line 1731 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5220#-N4DkYa4ArMv0XzqJPN8:-N4DkYa4ArMv0XzqJPN9:b-fsma52) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5a7573472ec9a43fa9aa4cbad9b301a6ccaf99e6/src/BloomExe/Book/BookStorage.cs#L1731)):*
> ```Smalltalk
> 		{
> 			Debug.WriteLine($"ExpensiveInitialization({fullyUpdateBookFiles}) for {FolderPath}");
> 			_bookFilesFullyUpdated = true;
> ```

This is a really long method with various try-catches and about 4 ways to dump out with an error. Would there be any benefit to adding this line closer to the end where it's actually true that the files have been updated?
___
*[`src/BloomExe/Edit/EditingView.cs` line 118 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5220#-N4Dl_JSDkBHnKO2slcp:-N4Dl_JTDMKNx_k9ldwR:b-by2wkv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5a7573472ec9a43fa9aa4cbad9b301a6ccaf99e6/src/BloomExe/Edit/EditingView.cs#L118)):*
> ```Smalltalk
> 				{
> 					Settings.Default.CurrentBookPath = oldToNewPath.Value;
> 				}
> ```

So I gather the idea is the _model is correct at this point, but in the case of book renaming the Settings are out-of-date? Assuming that's what's going on, looks good.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5220)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomExe/Book/BookStorage.cs` line 1731 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5220#-N4DkYa4ArMv0XzqJPN8:-N4E5I9BC56_9iC6_jl4:b-93pky6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5a7573472ec9a43fa9aa4cbad9b301a6ccaf99e6/src/BloomExe/Book/BookStorage.cs#L1731)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

This is a really long method with various try-catches and about 4 ways to dump out with an error. Would there be any benefit to adding this line closer to the end where it's actually true that the files have been updated?
</blockquote></details>

I thought about that, but the other danger is that some early return prevents the flag from getting set. If it fails once it will probably fail again, so I don't see much point in another try.
___
*[`src/BloomExe/Edit/EditingView.cs` line 118 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5220#-N4Dl_JSDkBHnKO2slcp:-N4E5fkEC2Gow3ZDFe7E:byr4flj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5a7573472ec9a43fa9aa4cbad9b301a6ccaf99e6/src/BloomExe/Edit/EditingView.cs#L118)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

So I gather the idea is the _model is correct at this point, but in the case of book renaming the Settings are out-of-date? Assuming that's what's going on, looks good.
</blockquote></details>

Right.

**Review by gmartin7 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5220)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
