### PR TITLE
Fix undefined language in xMatter and group bubbles (BL-4487)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1630)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts, line 110 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1630#-Kg_E3MWlLEl3ZdlJnFE:-Kg_E3MWlLEl3ZdlJnFF:b4kn22a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c493d3bc246fa37f7de136bf3c669a8857aad299/src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts#L110)):*
> ```XML
> 
>     static wantHelpBubbleOnGroup(groupElement: JQuery) {
>         // We only ever show them on each field if this class requests it.
> ```

This comment has been made untrue. It might be helpful to replace it with some explanation of why xmatter should never do group-level hints. @hatton, are we sure that's what we'll always want? Another possible fix is just to modify our xmatter and put bloom-showHintOnEach on each appropriate group. More to change, but we'd keep the option of controlling it.

---

*[src/BloomBrowserUI/lib/localizationManager/localizationManager.ts, line 275 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1630#-Kg_ER_STtNuZDajNVnj:-Kg_ER_STtNuZDajNVnk:bu3n6ab) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c493d3bc246fa37f7de136bf3c669a8857aad299/src/BloomBrowserUI/lib/localizationManager/localizationManager.ts#L275)):*
> ```XML
>             if (!languageName) {
>                 //This can happen, for example, if the user enters {lang} in a hint bubble on a group
>                 return translated;
> ```

A friendlier thing to do, I suppose, would be to insert something like "current book languages", but that would be one more string to localize that's only needed in cases where the template designer has messed up...It's not obvious to me that {lang} is any better than "undefined" for an end user, but I suppose it makes it more obvious to the template designer what he/she has done wrong. I think I'm convinced that what you have is good, but I'll let this comment stand and if you think the other approach has any merit you could take it up with JohnH

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1630)*

**Comment by hatton** [comment]
> I think I'm convinced 

Hmm, does "think I'm convinced" mean "I'm leaning towards"? I'll lend you my support to get all the way there :-)

**Comment by andrew-polk** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts, line 110 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1630#-Kg_E3MWlLEl3ZdlJnFE:-Kga6oL0sJOH535EojFB:btzbql) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c493d3bc246fa37f7de136bf3c669a8857aad299/src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts#L110)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This comment has been made untrue. It might be helpful to replace it with some explanation of why xmatter should never do group-level hints. @hatton, are we sure that's what we'll always want? Another possible fix is just to modify our xmatter and put bloom-showHintOnEach on each appropriate group. More to change, but we'd keep the option of controlling it.
</blockquote></details>

Modified comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1630)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1630#-:-KgyoQ98QoUUmjby-t79:bnfp4nl)*

**Pull request merged**
