### PR TITLE
Don't report missing L10N for HelpMenu.Help Menu (BL-5610)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2227)

### CODE REVIEW

**Comment by hatton** [comment]
> But apparently because we reuse this ID from a Windows Forms component, there is some glitch which makes it get reported as a missing L10N (I never did figure out exactly what was going on).

Should we just fix that instead?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2227#-:-L6OxT1LoP_FkCaBEs15:b-gjw15b)*

**Comment by andrew-polk** [comment]
Ideally, yes. But after spending too much time on it, I figured it was a one-off and not worth more time. Feel free to override that.

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2227#-:-L6Re7L69SbkwzENxeb_:bi5i4g5)*

**Comment by hatton** [comment]
Yeah... we have to be vigilant against "just get it working", especially when we're not under a time crunch.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2227#-:-L6WuO-I6U7w8_35QiIj:b-1yum24)*

**Comment by hatton** [comment]
It could be the I've misunderstood, but I took your comment to mean that this *isn't* one off; that an id used in the c# context cannot also by used in javascript context.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2227#-:-L6WuY0b3Kl2MuaOlVyQ:b-q91zg1)*

**Comment by andrew-polk** [comment]
To clarify, the L10N was working. We were just getting errant "Missing L10N" reports. But I agree we don't want to continue to get errant reports. I'll look at it some more.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2227#-:-L6WxLWne5uLrUbMIrXB:b-ce45vd)*

**Comment by andrew-polk** [comment]
This is likely the only ID we would have this problem with because of the funkiness of presenting an icon in some languages and text in others. It seems to have something to do with having the English value of "Help" in the .xlf files so translators will translate that word, but then looking it up in code with `GetString("HelpMenu.Help Menu", "?")`.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2227#-:-L6bF8yCPcPI5dBnpUMy:b8879g6)*

**Pull request merged**
