### PR TITLE
Reduce images when creating epubs (BL-4731)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1542 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387#-LC8yJNO9V0g6dm7XXnE:-LC8yJNO9V0g6dm7XXnF:b-7eqe5s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32121b31f45f1a0e9448cd2c8aff91672e49f84c/src/BloomExe/Publish/Epub/EpubMaker.cs#L1542)):*
> ```Smalltalk
> 			{
> 				var imageBytes = BookCompressor.GetBytesOfReducedImage(srcPath);
> 				// REVIEW: I notice that .png files actually get bigger many times.  Do we need the guaranteed transparency,
> ```

Help me understand.
We certainly don't want to run a method "GetBytesOfReducedImage" and get back something with the same properties yet which is larger. How does transparency factor in?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387)*

**Comment by StephenMcConnel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1542 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387#-LC8yJNO9V0g6dm7XXnE:-LC9WIQ7A6bGHqOQYqf0:b-dz0e7w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32121b31f45f1a0e9448cd2c8aff91672e49f84c/src/BloomExe/Publish/Epub/EpubMaker.cs#L1542)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Help me understand.
We certainly don't want to run a method "GetBytesOfReducedImage" and get back something with the same properties yet which is larger. How does transparency factor in?
</blockquote></details>

When the cover image was background, it had to have a transparent background.  So the GetBytesOfReducedImage would convert all .png files to have a transparent background as well as possibly smaller dimensions.  The problem with .png files is that many line drawings are stored as 1-bit (true black and white) or possibly 2-bit/4-bit color (grayscale probably).  The .Net/Mono code only handles down to 8-bit color, so even a drawing with smaller dimensions can result in a larger file.  But do we still see any need for transparent backgrounds?  If not, then we should discard the adjusted image if it results in a bigger file.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387)*

**Comment by andrew-polk** [comment]
*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1542 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387#-LC8yJNO9V0g6dm7XXnE:-LC9cXZ04dKXnGyyHVxH:b-gmb5gl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32121b31f45f1a0e9448cd2c8aff91672e49f84c/src/BloomExe/Publish/Epub/EpubMaker.cs#L1542)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

When the cover image was background, it had to have a transparent background.  So the GetBytesOfReducedImage would convert all .png files to have a transparent background as well as possibly smaller dimensions.  The problem with .png files is that many line drawings are stored as 1-bit (true black and white) or possibly 2-bit/4-bit color (grayscale probably).  The .Net/Mono code only handles down to 8-bit color, so even a drawing with smaller dimensions can result in a larger file.  But do we still see any need for transparent backgrounds?  If not, then we should discard the adjusted image if it results in a bigger file.
</blockquote></details>

Sorry; I'm still missing something. Why does whether the image is applied as a background (via css) or via src affect whether we need the image itself to have a transparent background?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387)*

**Comment by StephenMcConnel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1542 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387#-LC8yJNO9V0g6dm7XXnE:-LC9deq2Bb-rPT6gENfn:b7gynvj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32121b31f45f1a0e9448cd2c8aff91672e49f84c/src/BloomExe/Publish/Epub/EpubMaker.cs#L1542)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; I'm still missing something. Why does whether the image is applied as a background (via css) or via src affect whether we need the image itself to have a transparent background?
</blockquote></details>

Hmm, I would guess it's not being background so much as being on the cover which is often colored paper that needs a transparent background.  So maybe it is still needed for cover page images.  Which would indicate another argument to enforce using the transformed image even if the file size increases to ensure the desired transparency.  I wonder if there's some way to check a .png file for already having a transparent background.  (This is getting more complicated and confusing the more I think about it.)

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387)*

**Comment by andrew-polk** [comment]
*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1542 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387#-LC8yJNO9V0g6dm7XXnE:-LC9hBlD7mTnr6P6c-h2:bfztlfd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32121b31f45f1a0e9448cd2c8aff91672e49f84c/src/BloomExe/Publish/Epub/EpubMaker.cs#L1542)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Hmm, I would guess it's not being background so much as being on the cover which is often colored paper that needs a transparent background.  So maybe it is still needed for cover page images.  Which would indicate another argument to enforce using the transformed image even if the file size increases to ensure the desired transparency.  I wonder if there's some way to check a .png file for already having a transparent background.  (This is getting more complicated and confusing the more I think about it.)
</blockquote></details>

Yeah, seems like only xmatter images matter for transparency. We should have thought of these issues when we did image compression for Bloom Reader. The method should also be renamed to reflect that it does more than reduce the size (or two different methods should be called). Sounds like this is a good opportunity to do things right.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1542 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387#-LC8yJNO9V0g6dm7XXnE:-LCA191WD_ws-zxXbO4d:b-djjwvp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32121b31f45f1a0e9448cd2c8aff91672e49f84c/src/BloomExe/Publish/Epub/EpubMaker.cs#L1542)):*
> When the cover image was background, it had to have a transparent background.  

Actually the transparency is to make line art look good against a colored background. It isn't related to whether the image is a background-image or img.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387)*

**Comment by StephenMcConnel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1542 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387#-LC8yJNO9V0g6dm7XXnE:-LCFEZuL4LyKCDZ-nCmJ:bpmr6s0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32121b31f45f1a0e9448cd2c8aff91672e49f84c/src/BloomExe/Publish/Epub/EpubMaker.cs#L1542)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

> When the cover image was background, it had to have a transparent background.  

Actually the transparency is to make line art look good against a colored background. It isn't related to whether the image is a background-image or img.
</blockquote></details>

As I went back to the original issue for reducing images (BL-4645), the pixel dimension of the images was the important criteria, not the filesize of the images.  So even when the file gets bigger in the processing, that doesn't matter much.  The .png files don't get that much bigger, and the .jpg files generally shrink a lot.  JohnT made the decision that keeping track of which images were going into xmatter and thus needed to be transparent wasn't worthwhile.  I'm thinking about revisiting this decision, and at least renaming the BookCompressor.GetBytesOfReducedImage method.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387)*

**Comment by andrew-polk** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1542 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387#-LC8yJNO9V0g6dm7XXnE:-LCFctLBBNWb8NOGCuOo:bwv9cbw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32121b31f45f1a0e9448cd2c8aff91672e49f84c/src/BloomExe/Publish/Epub/EpubMaker.cs#L1542)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I renamed the method and extensively edited its summary comment.  I think that's about all can be done easily.  Epub generation could fairly easily detect whether an image is from a .coverColor page, but .bloomd generation would find it rather difficult.  (Impossible is probably too strong a term...)
</blockquote></details>

May want to adjust the parameter name for this method now.

Also, why do we care about the image dimensions? I thought the original intent was to reduce file size.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1542 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387#-LC8yJNO9V0g6dm7XXnE:-LCFeoSgAa49Zhds00xH:b-x0loql) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32121b31f45f1a0e9448cd2c8aff91672e49f84c/src/BloomExe/Publish/Epub/EpubMaker.cs#L1542)):*
> why do we care about the image dimensions

If someone pastes in a 4000 x 4000 image, and we gave them an option to reduce that to something approximating what is needed for printing, or needed to show on a device, that would be welcome.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1542 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387#-LC8yJNO9V0g6dm7XXnE:-LCFhPNLA_66FeJEt0qv:b-jlmipm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32121b31f45f1a0e9448cd2c8aff91672e49f84c/src/BloomExe/Publish/Epub/EpubMaker.cs#L1542)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

> why do we care about the image dimensions

If someone pastes in a 4000 x 4000 image, and we gave them an option to reduce that to something approximating what is needed for printing, or needed to show on a device, that would be welcome.
</blockquote></details>

Sorry; I guess I'm still missing something. I get the print argument, but that is out of scope here.

For digital, I assume any device is going to do something to scale down the display of that 4000x4000 image to something which fits on the screen. 
If we can reduce the file size without degrading quality, we should. If we can reduce the dimensions and meanwhile increase the file size, we've lost something; what have we gained?

Anyway, if JH's happy, I'm willing to accept my ignorance and don't want that to hold up the merge.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387)*

**Comment by StephenMcConnel** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1542 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387#-LC8yJNO9V0g6dm7XXnE:-LCFhyzLCgEZivcjUj0b:b-bconex) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32121b31f45f1a0e9448cd2c8aff91672e49f84c/src/BloomExe/Publish/Epub/EpubMaker.cs#L1542)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; I guess I'm still missing something. I get the print argument, but that is out of scope here.

For digital, I assume any device is going to do something to scale down the display of that 4000x4000 image to something which fits on the screen. 
If we can reduce the file size without degrading quality, we should. If we can reduce the dimensions and meanwhile increase the file size, we've lost something; what have we gained?

Anyway, if JH's happy, I'm willing to accept my ignorance and don't want that to hold up the merge.
</blockquote></details>

The original intent was image dimensions (https://silbloom.myjetbrains.com/youtrack/issue/BL-4645).  I've changed the parameter name to reflect my new understanding.
@hatton - should I make a card for letting users limit image dimensions initially when assigning/pasting an image?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387)*

**Comment by andrew-polk** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1542 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387#-LC8yJNO9V0g6dm7XXnE:-LCFlICS0jSr51F0Qpi3:bdiylne) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32121b31f45f1a0e9448cd2c8aff91672e49f84c/src/BloomExe/Publish/Epub/EpubMaker.cs#L1542)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

The original intent was image dimensions (https://silbloom.myjetbrains.com/youtrack/issue/BL-4645).  I've changed the parameter name to reflect my new understanding.
@hatton - should I make a card for letting users limit image dimensions initially when assigning/pasting an image?
</blockquote></details>

I don't see anything in the original issue implying we want to reduce dimensions even if it is at the cost of larger file size. In fact, the linked article (and I think, the original intent) was about limiting file size. John simply gave dimension parameters (correct me if I'm wrong, John) assuming that setting a max dimension would not increase file size. However, we've now proven that isn't the case.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387)*

**Comment by StephenMcConnel** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1542 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387#-LC8yJNO9V0g6dm7XXnE:-LCFoDZoCi-80lAad0R3:bkocbar) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32121b31f45f1a0e9448cd2c8aff91672e49f84c/src/BloomExe/Publish/Epub/EpubMaker.cs#L1542)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't see anything in the original issue implying we want to reduce dimensions even if it is at the cost of larger file size. In fact, the linked article (and I think, the original intent) was about limiting file size. John simply gave dimension parameters (correct me if I'm wrong, John) assuming that setting a max dimension would not increase file size. However, we've now proven that isn't the case.
</blockquote></details>

My impression from https://wptheming.com/2015/09/responsive-image-best-practices/ was that it only talked about image dimensions when it used the word "size".  Maybe there was an assumption that download image byte count size is directly correlated to dimension size, and that the download byte count is really what matters, but it was never explicitly stated.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387)*

**Comment by andrew-polk** [comment]
*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1542 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387#-LC8yJNO9V0g6dm7XXnE:-LCFtVS23h7NkaMU2Ib5:bjg1y8r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32121b31f45f1a0e9448cd2c8aff91672e49f84c/src/BloomExe/Publish/Epub/EpubMaker.cs#L1542)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

My impression from https://wptheming.com/2015/09/responsive-image-best-practices/ was that it only talked about image dimensions when it used the word "size".  Maybe there was an assumption that download image byte count size is directly correlated to dimension size, and that the download byte count is really what matters, but it was never explicitly stated.
</blockquote></details>

Happy to let @hatton settle it as he wrote the original issue and my speculations on what the goal was are simply speculations.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387)*

**Comment by hatton** [comment]
Can we discuss this at your convenience @StephenMcConnel @andrew-polk. Thx.

**Comment by andrew-polk** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 812 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387#-LD2QKMP8Fy1kS7b8lFS:-LD2QKMP8Fy1kS7b8lFT:bvaa3h1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4aea17e69550e0d052a70dcc5b2c74bdf1d67c9e/src/BloomExe/Publish/Epub/EpubMaker.cs#L812)):*
> ```
> parent::div[contains(@class, 'bloom-imageContainer')]
> ```
I'm sure this is just my ignorance, but why is it not sufficient to say we want transparency if an ancestor has 'coverColor' class (the other part of the xpath)?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387)*

**Comment by StephenMcConnel** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 812 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387#-LD2QKMP8Fy1kS7b8lFS:-LD2WPS99RX4Q8jsNJB2:b-vettb4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4aea17e69550e0d052a70dcc5b2c74bdf1d67c9e/src/BloomExe/Publish/Epub/EpubMaker.cs#L812)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> parent::div[contains(@class, 'bloom-imageContainer')]
> ```
I'm sure this is just my ignorance, but why is it not sufficient to say we want transparency if an ancestor has 'coverColor' class (the other part of the xpath)?
</blockquote></details>

This may be overcautious on my part, but I don't think we want to try to touch branding or license images with transparency.  It's possible this check isn't needed since branding images tend to be .svg, which I don' think the transparency conversion handles anyway.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387#-:-LD2mOkJ0U8Kfktr7vZ7:bnfp4nl)*

**Pull request merged**
