### PR TITLE
Fix bloomBundles made by Bulk Publish (BL-10190)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomExe/BloomExe.csproj, line 563 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-MjkLz4N15AtYT9JlC0p:-MjkLz4N15AtYT9JlC0q:b-kvj3iq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0279297e5af16eed03327e632355f7669a597eaf/src/BloomExe/BloomExe.csproj#L563)):*
> ```XML
>     </Compile>
>     <Compile Include="Collection\NaturalSortComparer.cs" />
>     <Compile Include="Utils\BloomZipFile.cs" />
> ```

I moved it because I didn't like how the root had so many files inbetween BloomArchiveFile and BloomZipFile.
Utils already had some zip-related files.
Open to discussion about where we'd like it to go.

**Review by JohnThomson — COMMENTED** [review]
Nice piece of work. A few minor suggestions.

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-:-Mjo0ZQ53GRU3jDkEEoT:b-qsu38z)* status: all files reviewed, 8 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/Utils/BloomArchiveFile.cs, line 94 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-Mjnyb8U0Iv0tORDC22Q:-Mjnyb8U0Iv0tORDC22R:b96mts4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0279297e5af16eed03327e632355f7669a597eaf/src/BloomExe/Utils/BloomArchiveFile.cs#L94)):*
> ```Smalltalk
> 			if (progressCallback != null)
> 			{
> 				count = AddDirectory(directoryPath, dirNameOffest, null, true);
> ```

To get an accurate count, extensionsToExclude should be passed on.
___
*[src/BloomExe/Utils/BloomTarFile.cs, line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-MjnyjvIE6ZA4cLRUHE6:-MjnyjvIE6ZA4cLRUHE7:b7zwkri) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0279297e5af16eed03327e632355f7669a597eaf/src/BloomExe/Utils/BloomTarFile.cs#L13)):*
> ```Smalltalk
> {
> 	/// <summary>
> 	/// This just provides a convenient wrapper over a zipping library. It's not really specific to Bloom.
> ```

Tar is not a zipping library, is it?
___
*[src/BloomExe/Utils/BloomTarFile.cs, line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-Mjnz1t4AnWpKmROJE0k:-Mjnz1t4AnWpKmROJE0l:biaaqez) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0279297e5af16eed03327e632355f7669a597eaf/src/BloomExe/Utils/BloomTarFile.cs#L36)):*
> ```Smalltalk
> 		protected override bool ShouldCompress(string fileFullPath) => false;
> 
> 		protected override void AddFile(string path, string entryName, bool compress=true)
> ```

It seems strange for true to be both the default and not allowed.
I wonder if it's really necessary to forbid passing true? One goal in subclassing is that as far as possible, any subclass can be used in any way the abstract class can be. What if we just documented that BloomTarFile ignored the compress argument since it can't actually compress?
___
*[src/BloomExe/Utils/BloomTarFile.cs, line 51 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-Mjnzi1213iHt2_B_jC_:-Mjnzi1213iHt2_B_jCa:b-w7w4bh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0279297e5af16eed03327e632355f7669a597eaf/src/BloomExe/Utils/BloomTarFile.cs#L51)):*
> ```Smalltalk
> 			_tarStream.PutNextEntry(newEntry);
> 
> 			// Zip the file in buffered chunks
> ```

Not actually zipping it.
___
*[src/BloomTests/Utils/BloomTarFileTests.cs, line 66 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-Mjo-zrV1GA_rQ6kTXVC:-Mjo-zrW0A7dL3zWCh3b:bjay3y5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0279297e5af16eed03327e632355f7669a597eaf/src/BloomTests/Utils/BloomTarFileTests.cs#L66)):*
> ```Smalltalk
> 			}
> 		}
> 	}
> ```

Maybe this is adequately tested on the base class, but would it be worth including in the test a subfolder and at least one file that (by extension) should not be put in the archive? How about verifying that we get a correct count back and that the progress function gets called?
___
*[src/BloomExe/Utils/BloomZipFile.cs, line 48 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-Mjo-4Yu7xk0LyEwX1f5:-Mjo-4Yu7xk0LyEwX1f6:bqld6r0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0279297e5af16eed03327e632355f7669a597eaf/src/BloomExe/Utils/BloomZipFile.cs#L48)):*
> ```Smalltalk
> 		}
> 
> 		// TODO: Decide what to do about me
> ```

What needs doing here?
___
*[src/BloomExe/Utils/BloomZipFile.cs, line 77 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-Mjo-Ik71VLzheLZsYti:-Mjo-Ik71VLzheLZsYtj:b6uonww) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0279297e5af16eed03327e632355f7669a597eaf/src/BloomExe/Utils/BloomZipFile.cs#L77)):*
> ```Smalltalk
> 	/// To Use, create a BloomZipFile, add files and directories, then call Save().
> 	/// </summary>
> 	public class BloomOriginalZipFile
> ```

Do we still need this? If so, the comment should indicate how it's different from BloomZipFile.

**Review by sujeffreyl — COMMENTED** [review]
TODO: I should update the UI too.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-:-Mjo0d9a9EsjJPBjOvUE:b-fs6xyz)* status: all files reviewed, 8 unresolved discussions (waiting on @sujeffreyl)

**Review by sujeffreyl — COMMENTED** [review]
Yuck. Diff getting confusing switching between Version5.1 and master. Mostly better now.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-:-MjobTuE7qADv177C2Sn:b-j6tvf5)* status: 0 of 18 files reviewed, 8 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Utils/BloomZipFile.cs, line 48 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-Mjo-4Yu7xk0LyEwX1f5:-MjoGw1X4ANsaYNbwoyk:b-amy0fv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0279297e5af16eed03327e632355f7669a597eaf/src/BloomExe/Utils/BloomZipFile.cs#L48)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

What needs doing here?
</blockquote></details>

I needed to decide whether it goes in the base class or in just BloomZipFile. I researched the matter and found that TarArchive doesn't have SetComment, so I'll leave it just in BloomZipFile.
___
*[src/BloomExe/Utils/BloomZipFile.cs, line 77 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-Mjo-Ik71VLzheLZsYti:-MjoHkgq-2iXsnYXpoDF:b4rspca) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0279297e5af16eed03327e632355f7669a597eaf/src/BloomExe/Utils/BloomZipFile.cs#L77)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Do we still need this? If so, the comment should indicate how it's different from BloomZipFile.
</blockquote></details>

Nope. Sorry about that. Removed.
___
*[src/BloomExe/Utils/BloomArchiveFile.cs, line 94 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-Mjnyb8U0Iv0tORDC22Q:-Mjo6ttsA7WSAcdqesxc:b-u6tnpx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0279297e5af16eed03327e632355f7669a597eaf/src/BloomExe/Utils/BloomArchiveFile.cs#L94)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

To get an accurate count, extensionsToExclude should be passed on.
</blockquote></details>

Hmm. Good point. I guess that was an inconsistentcy introduced in my previous "bug fix" of this method, where I only updated half of it I guess. https://github.com/BloomBooks/BloomDesktop/commit/aed740adeb60e4b1092585c71af6bad720467fe3#diff-68632633d1e2d8931ab6d86d8023ca5ce91f4a2edb41d3e27743f3a52c4e8a71.
Fixed.
___
*[src/BloomExe/Utils/BloomTarFile.cs, line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-MjnyjvIE6ZA4cLRUHE6:-Mjo7QvR2T9mM-9dpHEG:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0279297e5af16eed03327e632355f7669a597eaf/src/BloomExe/Utils/BloomTarFile.cs#L13)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Tar is not a zipping library, is it?
</blockquote></details>

Done.
___
*[src/BloomExe/Utils/BloomTarFile.cs, line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-Mjnz1t4AnWpKmROJE0k:-Mjo8lee9Vmxriw7gjUe:bgglxjh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0279297e5af16eed03327e632355f7669a597eaf/src/BloomExe/Utils/BloomTarFile.cs#L36)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It seems strange for true to be both the default and not allowed.
I wonder if it's really necessary to forbid passing true? One goal in subclassing is that as far as possible, any subclass can be used in any way the abstract class can be. What if we just documented that BloomTarFile ignored the compress argument since it can't actually compress?
</blockquote></details>

OK, I think it's not technically required for the subclass to deal with the optional parameter in the same way as the parent. At least, the compiler doesn't seem to complain. Optional parameters don't affect the method signature at least...
___
*[src/BloomExe/Utils/BloomTarFile.cs, line 51 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-Mjnzi1213iHt2_B_jC_:-MjoA8BRDJBzD5Kb1WlJ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0279297e5af16eed03327e632355f7669a597eaf/src/BloomExe/Utils/BloomTarFile.cs#L51)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Not actually zipping it.
</blockquote></details>

Done.
___
*[src/BloomTests/Utils/BloomTarFileTests.cs, line 66 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-Mjo-zrV1GA_rQ6kTXVC:-MjoYYRCEPxxI5fUYIXG:b-myw1ky) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0279297e5af16eed03327e632355f7669a597eaf/src/BloomTests/Utils/BloomTarFileTests.cs#L66)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Maybe this is adequately tested on the base class, but would it be worth including in the test a subfolder and at least one file that (by extension) should not be put in the archive? How about verifying that we get a correct count back and that the progress function gets called?
</blockquote></details>

Base class didn't have any tests. I added some there to handle the extension and the count/progress case.

**Review by JohnThomson — APPROVED** [review]
LGTM, I think. It's a bit hard to be sure what I've seen previously. One minor and optional suggestion remaining.

> Reviewed 1 of 14 files at r2, 13 of 15 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-:-MjpEMHy38fnqdafYPno:bakn7e5)* status: all files reviewed, 4 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/Utils/BloomTarArchive.cs, line 41 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-MjpA1ynCkPyqidWP58v:-MjpA1ynCkPyqidWP58w:b-5gd8me) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5e615deb6b741b64103c6589cfa240b4756d6bec/src/BloomExe/Utils/BloomTarArchive.cs#L41)):*
> ```Smalltalk
> 		/// </summary>
> 		/// <param name="compress">This parameter is ignored because tar files don't support compression. It is recommended to pass "false" though.</param>
> 		protected override void AddFile(string path, string entryName, bool compress)
> ```

I did a little reading. There are oddities with inherited methods and default params. If I read right,

BloomAchiveFile x = new BloomTarArchive();
x.AddFile("whatever", "whatever") // valid, compress is true

var y = new BloomTarArchive();
y.AddFile("whatever", "whatever") ;  // fails to compile, y is of type BloomTarArchive and compress argument is required.

It's worse if you make compress default to false like I suggested for BloomTarArchive. Then, the two bits of code above both compile. But while the second is called with compress false, the first is still called with it true! The default is determined by the type of the variable declaration!

I don't like that the default changes with exactly how you declare the variable, even though it makes no difference to the current tar archive. So I think my preference would be to make all three versions of this method default to true, with a comment here that it is done to be consistent with the other implementation of the abstract class even though it is ignored here.

But I'm OK with keeping what you have if you prefer it or don't think the change is worth the trouble.
___
*[src/BloomExe/Utils/BloomTarFile.cs, line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-Mjnz1t4AnWpKmROJE0k:-MjpDjH62UgwfXDc9g7-:bxzp9q5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0279297e5af16eed03327e632355f7669a597eaf/src/BloomExe/Utils/BloomTarFile.cs#L36)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

OK, I think it's not technically required for the subclass to deal with the optional parameter in the same way as the parent. At least, the compiler doesn't seem to complain. Optional parameters don't affect the method signature at least...
</blockquote></details>

See comment in new location
___
*[src/BloomTests/Utils/BloomTarFileTests.cs, line 66 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-Mjo-zrV1GA_rQ6kTXVC:-MjpDoSn3BwPvwvt9Aj5:bd5l6n4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0279297e5af16eed03327e632355f7669a597eaf/src/BloomTests/Utils/BloomTarFileTests.cs#L66)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Base class didn't have any tests. I added some there to handle the extension and the count/progress case.
</blockquote></details>

thanks.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722)* status: 15 of 18 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Utils/BloomTarArchive.cs, line 41 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-MjpA1ynCkPyqidWP58v:-Mk2YZui7XexDDN7Dir3:b-5dn545) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5e615deb6b741b64103c6589cfa240b4756d6bec/src/BloomExe/Utils/BloomTarArchive.cs#L41)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I did a little reading. There are oddities with inherited methods and default params. If I read right,

BloomAchiveFile x = new BloomTarArchive();
x.AddFile("whatever", "whatever") // valid, compress is true

var y = new BloomTarArchive();
y.AddFile("whatever", "whatever") ;  // fails to compile, y is of type BloomTarArchive and compress argument is required.

It's worse if you make compress default to false like I suggested for BloomTarArchive. Then, the two bits of code above both compile. But while the second is called with compress false, the first is still called with it true! The default is determined by the type of the variable declaration!

I don't like that the default changes with exactly how you declare the variable, even though it makes no difference to the current tar archive. So I think my preference would be to make all three versions of this method default to true, with a comment here that it is done to be consistent with the other implementation of the abstract class even though it is ignored here.

But I'm OK with keeping what you have if you prefer it or don't think the change is worth the trouble.

</blockquote></details>

Yeah that sounds right to me and makes sense to me from a technical point of view, while also worrying me that it's really easy to shoot oneself in the foot.

I changed the variable name to compressIfAble and set the default to true for all 3.
___
*[src/BloomExe/Utils/BloomTarFile.cs, line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-Mjnz1t4AnWpKmROJE0k:-Mk2YwA28DbQVpc95hTF:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0279297e5af16eed03327e632355f7669a597eaf/src/BloomExe/Utils/BloomTarFile.cs#L36)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

See comment in new location
</blockquote></details>

Done.
___
*[src/BloomTests/Utils/BloomTarFileTests.cs, line 66 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-Mjo-zrV1GA_rQ6kTXVC:-Mk2YyK05ywJLEnXnxiI:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0279297e5af16eed03327e632355f7669a597eaf/src/BloomTests/Utils/BloomTarFileTests.cs#L66)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

thanks.
</blockquote></details>

Done.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 3 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Utils/BloomTarArchive.cs, line 41 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-MjpA1ynCkPyqidWP58v:-Mk2a0ET-r-hzCxsWIZB:b-4ra8dr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5e615deb6b741b64103c6589cfa240b4756d6bec/src/BloomExe/Utils/BloomTarArchive.cs#L41)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Yeah that sounds right to me and makes sense to me from a technical point of view, while also worrying me that it's really easy to shoot oneself in the foot.

I changed the variable name to compressIfAble and set the default to true for all 3.
</blockquote></details>

Good idea! Thanks.

**Review by sujeffreyl — COMMENTED** [review]
Finally updated the UI. Moving this out of draft status.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722#-:-Mk2oXJGE8GKkxydQ3oH:b-9n0j1q)* status: 18 of 20 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

**Pull request merged**
