### PR TITLE
Update Crowdin merge process to use CheckOrFixXliff

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2095)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[build/getDependencies-Linux.sh, line 105 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2095#-L3_ekGwFlbrHqHTjM17:-L3_ekGxaScT-QvAjCMd:b-fqsjnr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9fd01678a4b2ab9cf3ce2f126803ae5ac09c7385/build/getDependencies-Linux.sh#L105)):*
> ```Shell
> #     URL: http://build.palaso.org/viewType.html?buildTypeId=bt401
> #     clean: false
> #     revision: bloom-4.0.tcbuildtag
> ```

Is this intentional?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2095)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[build/getDependencies-Linux.sh, line 105 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2095#-L3_ekGwFlbrHqHTjM17:-L3a78_cABLyt8MDwgJ3:bx4j8eg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9fd01678a4b2ab9cf3ce2f126803ae5ac09c7385/build/getDependencies-Linux.sh#L105)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is this intentional?
</blockquote></details>

yes, for pdfjs, we don't want to change what we get until a newer version has really been gotten to work.  I might have been able to remove the "build" that was a fetch of a newer version, which could allow this to go back to "latest-successful".  But I'd have to check.  It's been a few weeks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2095)*

**Comment by andrew-polk** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[build/getDependencies-Linux.sh, line 105 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2095#-L3_ekGwFlbrHqHTjM17:-L3ca1tsvUTjSVS_4D3i:b9j948m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9fd01678a4b2ab9cf3ce2f126803ae5ac09c7385/build/getDependencies-Linux.sh#L105)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

yes, for pdfjs, we don't want to change what we get until a newer version has really been gotten to work.  I might have been able to remove the "build" that was a fetch of a newer version, which could allow this to go back to "latest-successful".  But I'd have to check.  It's been a few weeks.
</blockquote></details>

Latest successful and 4.0 tag are the same build. Please don't use tags for master builds.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2095)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[build/getDependencies-Linux.sh, line 105 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2095#-L3_ekGwFlbrHqHTjM17:-L3catdDnhN4IF945HLP:bux471f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9fd01678a4b2ab9cf3ce2f126803ae5ac09c7385/build/getDependencies-Linux.sh#L105)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Latest successful and 4.0 tag are the same build. Please don't use tags for master builds.
</blockquote></details>

I've modified the TC build appropriately.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2095)*

**Comment by andrew-polk** [comment]
:lgtm:
I don't understand the comment about 4.0 vs. 4.1 vs this is targeting master.  So I'll leave it to someone who understands to merge (or explain it to me... : ) ).

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2095#-:-L3e4LwRCbfYDySZhgvH:bf3rjqg)*

**Comment by StephenMcConnel** [comment]
That was a total goof on my part: the comment was intended for my other pull request.  (2099)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2095#-:-L3e8ZiEcMWfqLn5RSJh:b-n0sao9)*

**Pull request merged**
