### PR TITLE
BL-9217 i18n issues in Copyright and License

### PR DESCRIPTION
**Pull request by gmartin7**
2 commits
* 1st is just refactoring
* 2nd uses a new i18n id for the complete version of copyright/license

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4173)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4173)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[DistFiles/localization/en/Bloom.xlf, line 1499 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4173#-MT2_qPo8lheLYYk5RnC:-MT2_qPo8lheLYYk5RnD:b-ps9nge) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3c55700cbcfc4dd8c7c865bcb9af3ae2baa0a960/DistFiles/localization/en/Bloom.xlf#L1499)):*
> ```XML
>         <note>ID: EditTab.FrontMatter.FullOriginalCopyrightLicenseSentence</note>
>         <note>On the Credits page of a book being translated, Bloom shows the original copyright. {0} is original title, {1} is original copyright, and {2} is license information.</note>
>       </trans-unit>
> ```

Should we also be marking the original ones as deprecated. (Somehow add to the description that translators need not translate but can rather translate this?

Or maybe it would be better just to mark them as not used in 5.0+ (we have other examples of this in the file)?

And are you planning to follow-up in Crowdin to create these where we have the pieces translated already?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4173)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[DistFiles/localization/en/Bloom.xlf, line 1499 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4173#-MT2_qPo8lheLYYk5RnC:-MT2gqvP6LNYh3fnNa8F:b631jth) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3c55700cbcfc4dd8c7c865bcb9af3ae2baa0a960/DistFiles/localization/en/Bloom.xlf#L1499)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should we also be marking the original ones as deprecated. (Somehow add to the description that translators need not translate but can rather translate this?

Or maybe it would be better just to mark them as not used in 5.0+ (we have other examples of this in the file)?

And are you planning to follow-up in Crowdin to create these where we have the pieces translated already?
</blockquote></details>

It's much more complicated than that. The others are used in situations where not all the "parts" are available.
I would maybe be able to figure out the Crowdin bit...

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4173)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[DistFiles/localization/en/Bloom.xlf, line 1499 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4173#-MT2_qPo8lheLYYk5RnC:-MT2mnWY2AqLQzFI9nX-:bm0pibo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3c55700cbcfc4dd8c7c865bcb9af3ae2baa0a960/DistFiles/localization/en/Bloom.xlf#L1499)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

It's much more complicated than that. The others are used in situations where not all the "parts" are available.
I would maybe be able to figure out the Crowdin bit...
</blockquote></details>

So you're saying even if we have this new string translated, there are still situations where we use the existing strings?
Could you give an example?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4173)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[DistFiles/localization/en/Bloom.xlf, line 1499 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4173#-MT2_qPo8lheLYYk5RnC:-MT6kBr5BnNJwgEjHLgc:b-kml9vf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3c55700cbcfc4dd8c7c865bcb9af3ae2baa0a960/DistFiles/localization/en/Bloom.xlf#L1499)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

So you're saying even if we have this new string translated, there are still situations where we use the existing strings?
Could you give an example?
</blockquote></details>

We don't use this string unless it's been translated (into whatever lang we're wanting to use most) AND we have something in both license and copyright. Otherwise, we use the other pieces.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4173)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

___
*[DistFiles/localization/en/Bloom.xlf, line 1499 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4173#-MT2_qPo8lheLYYk5RnC:-MT7-nZR4FeuEemzrqep:b-zcjvte) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3c55700cbcfc4dd8c7c865bcb9af3ae2baa0a960/DistFiles/localization/en/Bloom.xlf#L1499)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

We don't use this string unless it's been translated (into whatever lang we're wanting to use most) AND we have something in both license and copyright. Otherwise, we use the other pieces.
</blockquote></details>

Thanks

**Pull request merged**
