### PR TITLE
BL-4749 move branding into book folder

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1773)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/XMatterHelper.cs, line 215 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1773#-Kqbwt-xaYIU6ayNpjR8:-Kqbwt-xaYIU6ayNpjR9:b-f25r4m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2e74cc46aab2fa6d9ff55b2487c7f1f881f4d49a/src/BloomExe/Book/XMatterHelper.cs#L215)):*
> ```Smalltalk
> 				{
> 					fileName = Path.GetFileName(pathToRealImage); // May have changed extension
> 					RobustFile.Copy(pathToRealImage, Path.Combine(bookFolderPath, fileName), true);
> ```

Will this throw an exception if it doesn't exist? The existing code returns silently in that case.
Or can FindBrandingImageFileIfPossible only return a non-null result if the file exists with some extension?

---

*[src/BloomExe/web/controllers/BrandingApi.cs, line 89 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1773#-KqbxoBD5YunQR2FpnZV:-KqbxoBD5YunQR2FpnZW:b-yiyx3d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2e74cc46aab2fa6d9ff55b2487c7f1f881f4d49a/src/BloomExe/web/controllers/BrandingApi.cs#L89)):*
> ```Smalltalk
> 			{
> 				var settingsPath = BloomFileLocator.GetOptionalBrandingFile(brandingNameOrFolderPath, "settings.json");
> 				if(!String.IsNullOrEmpty(settingsPath))
> ```

I've seen several of these changed recently. The code style I have set in ReSharper (which I haven't changed as far as I know), prefers string. Is this something we have agreed upon one way or the other?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1773)*

**Comment by JohnThomson** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/XMatterHelper.cs, line 215 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1773#-Kqbwt-xaYIU6ayNpjR8:-KqctjIxfSFVbpmO9D2C:b9y27kk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2e74cc46aab2fa6d9ff55b2487c7f1f881f4d49a/src/BloomExe/Book/XMatterHelper.cs#L215)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Will this throw an exception if it doesn't exist? The existing code returns silently in that case.
Or can FindBrandingImageFileIfPossible only return a non-null result if the file exists with some extension?
</blockquote></details>

Well, the existing code does ReplyWithImage if it gets a path that is not null (or empty) from FindBrandingImageFileIfPossible.  Based on that and my reading of the code, FindBrandingImageFileIfPossible will either return null or a path to an existing file. I suppose it MIGHT be a file that for some reason we can't copy, but that feels like a legitimate exception situation to me.

---

*[src/BloomExe/web/controllers/BrandingApi.cs, line 89 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1773#-KqbxoBD5YunQR2FpnZV:-KqcwNGWoqUn6j79PUkt:br5ldr1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2e74cc46aab2fa6d9ff55b2487c7f1f881f4d49a/src/BloomExe/web/controllers/BrandingApi.cs#L89)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I've seen several of these changed recently. The code style I have set in ReSharper (which I haven't changed as far as I know), prefers string. Is this something we have agreed upon one way or the other?
</blockquote></details>

I have no idea how this got changed or why I missed it in my own review. Reverting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1773)*

**Comment by JohnThomson** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/XMatterHelper.cs, line 215 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1773#-Kqbwt-xaYIU6ayNpjR8:-Kqcwc9RSsnDX1H_8C-b:b-ia5unb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2e74cc46aab2fa6d9ff55b2487c7f1f881f4d49a/src/BloomExe/Book/XMatterHelper.cs#L215)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Well, the existing code does ReplyWithImage if it gets a path that is not null (or empty) from FindBrandingImageFileIfPossible.  Based on that and my reading of the code, FindBrandingImageFileIfPossible will either return null or a path to an existing file. I suppose it MIGHT be a file that for some reason we can't copy, but that feels like a legitimate exception situation to me.
</blockquote></details>

For the sake of consistency, I changed it so my code also uses string.IsNullOrEmpty()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1773)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1773#-:-Kqd8tdkBwv6EIPsp9Dl:bnfp4nl)*

**Pull request merged**
