### PR TITLE
BL-5013 Update CC icon on license change

### PR DESCRIPTION
**Pull request by gmartin7**
Caching of images was not playing well with
resizing of images
* Removed one unused method
* Changed all cache-related paths to use fwd slashes
* When resizing images, used the original path to
   decide whether to cache or not.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1862)

### CODE REVIEW

**Comment by hatton** [comment]
👍

**Comment by JohnThomson** [comment]
Sorry, but I think it may need a little tweaking.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/web/RequestInfo.cs, line 193 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1862#-KuabJFTldi9WOF2jj4a:-KuabJFTldi9WOF2jj4b:bm9yccy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b714dc39e2419daa16d3505b8b74a531ba6bcf06/src/BloomExe/web/RequestInfo.cs#L193)):*
> ```Smalltalk
> 			// if we're using a lower resolution version of an image (with a generated filename),
> 			// we want ShouldCache to do its tests on the original filename.
> 			if (path.StartsWith(DoNotCacheFolder) || originalPath.StartsWith(DoNotCacheFolder))
> ```

Is there any reason to test path if we're given an originalPath?
I would have been inclined to make all the defaults for originalPath null, and then here simply
(originalPath ?? path).StartsWith...
It would then also be easy to put the replacing of \ with / here instead of in (one of) the callers of ReplyWithImage...which would be a good thing unless you are quite sure that all other callers of ReplyWithFileContent (that just pass the one argument) never pass backslashes...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1862#-:-KuadEJ0g7qz6-pzb88C:b-ty66fd)*

**Comment by JohnThomson** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/web/RequestInfo.cs, line 192 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1862#-KudsoUIIkGf8xmpAEXS:-KudsoUJkyHCAJLZecmR:bl29qih) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/024c874a27161c2d84245e874ed2f0aff5dc4bd8/src/BloomExe/web/RequestInfo.cs#L192)):*
> ```Smalltalk
> 			// if we're using a lower resolution version of an image (with a generated filename),
> 			// we want ShouldCache to do its tests on the original filename.
> 			if ((originalPath ?? path).Replace('\\','/').StartsWith(DoNotCacheFolder))
> ```

To make this work you have to change all the places that make originalPath be an empty string (when not used) to null.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1862)*

**Comment by gmartin7** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/web/RequestInfo.cs, line 193 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1862#-KuabJFTldi9WOF2jj4a:-KueVxq0VlBJjeig2E1L:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b714dc39e2419daa16d3505b8b74a531ba6bcf06/src/BloomExe/web/RequestInfo.cs#L193)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is there any reason to test path if we're given an originalPath?
I would have been inclined to make all the defaults for originalPath null, and then here simply
(originalPath ?? path).StartsWith...
It would then also be easy to put the replacing of \ with / here instead of in (one of) the callers of ReplyWithImage...which would be a good thing unless you are quite sure that all other callers of ReplyWithFileContent (that just pass the one argument) never pass backslashes...
</blockquote></details>

Done.

---

*[src/BloomExe/web/RequestInfo.cs, line 192 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1862#-KudsoUIIkGf8xmpAEXS:-KueVxIuwmedowRLy45D:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/024c874a27161c2d84245e874ed2f0aff5dc4bd8/src/BloomExe/web/RequestInfo.cs#L192)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

To make this work you have to change all the places that make originalPath be an empty string (when not used) to null.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1862)*

**Comment by JohnThomson** [comment]
Review status: 3 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/BloomExe/ImageProcessing/ImageServer.cs, line 111 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1862#-Kuey88UgfRHLZK_2dg0:-Kuey88UgfRHLZK_2dg1:b-x3h3mj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/262b790298031e3f61b5acb722300ff04282b3a3/src/BloomExe/ImageProcessing/ImageServer.cs#L111)):*
> ```Smalltalk
> 			}
> 
> 			info.ReplyWithImage(imageFile, imageFile == originalImageFile ? "" : originalImageFile);
> ```

One more place to pass null, not an empty string, if the second argument is not useful. Or, it would be quite harmless now to just pass originalImageFile unconditionally.

---

*[src/BloomTests/PretendRequestInfo.cs, line 60 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1862#-KueyMAMUFavtZ5ZWZpv:-KueyMAMUFavtZ5ZWZpw:be3h2t1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/262b790298031e3f61b5acb722300ff04282b3a3/src/BloomTests/PretendRequestInfo.cs#L60)):*
> ```Smalltalk
> 		}
> 
> 		public void ReplyWithFileContent(string path, string originalPath = "")
> ```

And another

---

*[src/BloomTests/PretendRequestInfo.cs, line 67 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1862#-KueyNLYwtNltI6JjR3m:-KueyNLYwtNltI6JjR3n:bl6ka8t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/262b790298031e3f61b5acb722300ff04282b3a3/src/BloomTests/PretendRequestInfo.cs#L67)):*
> ```Smalltalk
> 		}
> 
> 		public void ReplyWithImage(string path, string originalPath = "")
> ```

And yet one more...please check carefully!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1862)*

**Comment by gmartin7** [comment]
Review status: 2 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/BloomExe/ImageProcessing/ImageServer.cs, line 111 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1862#-Kuey88UgfRHLZK_2dg0:-Kugd_71tEUtyooEzeCD:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/262b790298031e3f61b5acb722300ff04282b3a3/src/BloomExe/ImageProcessing/ImageServer.cs#L111)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

One more place to pass null, not an empty string, if the second argument is not useful. Or, it would be quite harmless now to just pass originalImageFile unconditionally.
</blockquote></details>

Done.

---

*[src/BloomTests/PretendRequestInfo.cs, line 60 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1862#-KueyMAMUFavtZ5ZWZpv:-Kugdbkw-VE5o2B9fZoH:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/262b790298031e3f61b5acb722300ff04282b3a3/src/BloomTests/PretendRequestInfo.cs#L60)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

And another
</blockquote></details>

Done.

---

*[src/BloomTests/PretendRequestInfo.cs, line 67 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1862#-KueyNLYwtNltI6JjR3m:-Kugdcd_Ykiv1GL81MVn:b-nruy1x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/262b790298031e3f61b5acb722300ff04282b3a3/src/BloomTests/PretendRequestInfo.cs#L67)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

And yet one more...please check carefully!
</blockquote></details>

Done. Wow!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1862)*

**Pull request merged**
