### PR TITLE
Fix book download while closed not launched (BL-11340)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5243)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5243)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[`src/BloomExe/Book/BookSelection.cs` line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5243#-N4mckGD2Z_mFWoLWhal:-N4mckGD2Z_mFWoLWham:b-d62cmc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d49cc818a15d4cc74f5db880b021092741ea220a/src/BloomExe/Book/BookSelection.cs#L36)):*
> ```Smalltalk
> 		public void SelectBook(Book book, bool aboutToEdit = false)
> 		{
> 			using (PerformanceMeasurement.Global?.Measure("select book", book?.BookInfo?.QuickTitleUserDisplay ?? "null"))
> ```

In 5.2, we used to measure it in LibraryListView. In 5.3, nothing was measuring this at all. JT and I added this to BookSelection because it would capture more calls, which we think will all be good to measure.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5243)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

___
*[`src/BloomExe/Book/BookSelection.cs` line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5243#-N4mckGD2Z_mFWoLWhal:-N4mf2Sw1gZX2_J1qrEA:b-dw2ory) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d49cc818a15d4cc74f5db880b021092741ea220a/src/BloomExe/Book/BookSelection.cs#L36)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

In 5.2, we used to measure it in LibraryListView. In 5.3, nothing was measuring this at all. JT and I added this to BookSelection because it would capture more calls, which we think will all be good to measure.
</blockquote></details>

LGTM, but Gordon is currently working on doing the same thing in BL-11329, though he added code elsewhere.
So, I'm ok to merge this if Gordon is. Or perhaps better, this should be moved to a new PR for that issue.

**Review by gmartin7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5243)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[`src/BloomExe/Book/BookSelection.cs` line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5243#-N4n7VXe9Ot4jiO4-z3J:-N4n7VXe9Ot4jiO4-z3K:b-23e6dg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d49cc818a15d4cc74f5db880b021092741ea220a/src/BloomExe/Book/BookSelection.cs#L36)):*
> ```Smalltalk
> 		public void SelectBook(Book book, bool aboutToEdit = false)
> 		{
> 			using (PerformanceMeasurement.Global?.Measure("select book", book?.BookInfo?.QuickTitleUserDisplay ?? "null"))
> ```

JT and I decided that putting this in CollectionApi where my PR put it is better because there it includes the BBUD processing in its measurements.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5243)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @gmartin7)

___
*[`src/BloomExe/Book/BookSelection.cs` line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5243#-N4mckGD2Z_mFWoLWhal:-N50V25vAFVpVnPcPwFs:bhofej8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d49cc818a15d4cc74f5db880b021092741ea220a/src/BloomExe/Book/BookSelection.cs#L36)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

LGTM, but Gordon is currently working on doing the same thing in BL-11329, though he added code elsewhere.
So, I'm ok to merge this if Gordon is. Or perhaps better, this should be moved to a new PR for that issue.
</blockquote></details>

Deleted
___
*[`src/BloomExe/Book/BookSelection.cs` line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5243#-N4n7VXe9Ot4jiO4-z3J:-N50V9z92YguWKfOmfjC:b6o0jp3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d49cc818a15d4cc74f5db880b021092741ea220a/src/BloomExe/Book/BookSelection.cs#L36)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

JT and I decided that putting this in CollectionApi where my PR put it is better because there it includes the BBUD processing in its measurements.
</blockquote></details>

Thanks, deleted

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5243)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

**Review by andrew-polk — APPROVED** [review]
> Dismissed @gmartin7 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5243)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Pull request merged**
