### PR TITLE
Improve unit test coverage (BL-9500)

### PR DESCRIPTION
**Pull request by JohnThomson**
Just one small step in dealing with this

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4238)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4238)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomTests/TeamCollection/TeamCollectionApiTests.cs, line 41 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4238#-MUPsJlT2lAjmpXbEDIh:-MUPsJlT2lAjmpXbEDIi:bxnq618) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78f2b3bfdb5a40a8c48311f4b705fb5abde98f3d/src/BloomTests/TeamCollection/TeamCollectionApiTests.cs#L41)):*
> ```
> ProblemsWithLocation_ExistingTC_Fails
> ```
This and others are mismatched. I think you can use MethodBase.GetCurrentMethod()

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4238)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomTests/TeamCollection/TeamCollectionApiTests.cs, line 41 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4238#-MUPsJlT2lAjmpXbEDIh:-MUTm8_m836zUi0-eRWG:bp0dfg9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78f2b3bfdb5a40a8c48311f4b705fb5abde98f3d/src/BloomTests/TeamCollection/TeamCollectionApiTests.cs#L41)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> ProblemsWithLocation_ExistingTC_Fails
> ```
This and others are mismatched. I think you can use MethodBase.GetCurrentMethod()
</blockquote></details>

Done. Cool idea.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4238)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4238)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
