### PR TITLE
Avoid loading an image a second time when importing (BL-8638)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4100)

### CODE REVIEW

**Review by JohnThomson — APPROVED** [review]
LGTM, with one very minor suggestion

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4100#-:-MN_8IqxEGl14m7f7VyB:baq97v6)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/Edit/EditingView.cs, line 1138 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4100#-MN_6L1VAxgh4-yB3q9a:-MN_6L1VAxgh4-yB3q9b:b-7ca6ca) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/64b96fe46c5a1f7568f8fd0dab4a82a653e41516/src/BloomExe/Edit/EditingView.cs#L1138)):*
> ```Smalltalk
> 					catch (Exception error)
> 					{
> 						// Problems can happen during the PalasoImage.Save or PalasoImage.FromFileRobustly methods.
> ```

It appears we're no longer using FromFileRobustly any more? In any case the comment doesn't seem very useful. One inserts catch blocks because problems can happen in the try block.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4100)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Edit/EditingView.cs, line 1138 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4100#-MN_6L1VAxgh4-yB3q9a:-MN_BXVx2P_A5qKzmgTC:b-27nfwd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/64b96fe46c5a1f7568f8fd0dab4a82a653e41516/src/BloomExe/Edit/EditingView.cs#L1138)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It appears we're no longer using FromFileRobustly any more? In any case the comment doesn't seem very useful. One inserts catch blocks because problems can happen in the try block.
</blockquote></details>

removed the comment.

**Review by JohnThomson — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4100)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4100)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
