### PR TITLE
Bl 1067 wall calendar fix

### PR DESCRIPTION
**Pull request by gmartin7**
Note 3 separate commits:
1) Some refactoring before the main work
2) The main work of redoing the configure.js (reduces dependencies and increases readability, I hope)
3) Fix the 'real' problem which was Configurator putting in a 'base' element

### CODE REVIEW

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-master-debug/296/
Test PASSed.

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-master-debug/300/
Test PASSed.

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-master-debug/306/
Test PASSed.

**Comment by gmartin7** [comment]
OK, I've treated all of the code review comments and the code is much cleaner. Thank you!

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-master-debug/313/
Test PASSed.

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-master-debug/314/
Test PASSed.

**Comment by JohnThomson** [comment]
Nice job. I like the new names you came up with.

**Pull request merged**
