### PR TITLE
Implement clipboard and undo buttons for WV2 (BL-11642)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5817)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5817)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/WebView2Browser.cs` line 380 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5817#-NUYakoj1PwbrpW70pY5:-NUYakoj1PwbrpW70pY6:b-jz8a6d) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/451bba5cb60f28155ff71b015d0639381fee5715/src/BloomExe/WebView2Browser.cs#L380)):*
> ```Smalltalk
> 			{
> 				// Note: this is only used for the Undo button in the toolbar;
> 				// ctrl-z is handled in JavaScript directly.
> ```

Is it not feasible to just implement a Ctrl-z from code?
In other words, use C# code (or even js?) to simulate the user typing Ctrl-z?

Now that I say that... why not do that for ctrl-x, -c, and -v?
___
*[`src/BloomExe/WebView2Browser.cs` line 393 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5817#-NUYbEiC1_HZaqPC8lTu:-NUYbEiC1_HZaqPC8lTv:b-wxikr0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/451bba5cb60f28155ff71b015d0639381fee5715/src/BloomExe/WebView2Browser.cs#L393)):*
> ```Smalltalk
> 		/// We configure something in Javascript to keep track of this, since GeckoFx-45's CanXSelection properties aren't working,
> 		/// and a workaround involving making a GeckoWindow object and querying its selection led to memory leaks (BL-9757).
> 		/// </summary>
> ```

This comment needs to be updated or deleted.
___
*[`src/BloomExe/WebView2Browser.cs` line 439 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5817#-NUYbm7P87Z1DDEQj5Pq:-NUYbm7P87Z1DDEQj5Pr:b-krpuyc) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/451bba5cb60f28155ff71b015d0639381fee5715/src/BloomExe/WebView2Browser.cs#L439)):*
> ```Smalltalk
> 				if (result == "y")
> 				{
> 					result = RunJavaScript("editTabBundle.canUndo()");
> ```

Can we make use of modern js here to something like `editTabBundle?.canUndo.?()`?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5817)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/WebView2Browser.cs` line 380 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5817#-NUYakoj1PwbrpW70pY5:-NUYeD69DYLYVr_Z-P0I:b-7cd71y) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/451bba5cb60f28155ff71b015d0639381fee5715/src/BloomExe/WebView2Browser.cs#L380)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is it not feasible to just implement a Ctrl-z from code?
In other words, use C# code (or even js?) to simulate the user typing Ctrl-z?

Now that I say that... why not do that for ctrl-x, -c, and -v?
</blockquote></details>

Seems like it would be a pain at both ends...have to somehow prevent the default browser handling of the keys, and then find a way for C# to intercept keys that would otherwise go to the browser, and then invoke what the browser otherwise just does. But I suppose there might be a gain in consistency. I wasn't aiming for a large improvement in Undo handling, though, just to reinstate a reasonable approximation of what we had in Gecko.
___
*[`src/BloomExe/WebView2Browser.cs` line 393 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5817#-NUYbEiC1_HZaqPC8lTu:-NUYf4Bl3D3twuVpciNH:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/451bba5cb60f28155ff71b015d0639381fee5715/src/BloomExe/WebView2Browser.cs#L393)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This comment needs to be updated or deleted.
</blockquote></details>

Done.
___
*[`src/BloomExe/WebView2Browser.cs` line 439 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5817#-NUYbm7P87Z1DDEQj5Pq:-NUaioNfA7fU2x4U_QII:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/451bba5cb60f28155ff71b015d0639381fee5715/src/BloomExe/WebView2Browser.cs#L439)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Can we make use of modern js here to something like `editTabBundle?.canUndo.?()`?
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5817)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/WebView2Browser.cs` line 380 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5817#-NUYakoj1PwbrpW70pY5:-NUbrIfb1ZkPLPr_Qm0h:b-nsnw2m) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/451bba5cb60f28155ff71b015d0639381fee5715/src/BloomExe/WebView2Browser.cs#L380)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Seems like it would be a pain at both ends...have to somehow prevent the default browser handling of the keys, and then find a way for C# to intercept keys that would otherwise go to the browser, and then invoke what the browser otherwise just does. But I suppose there might be a gain in consistency. I wasn't aiming for a large improvement in Undo handling, though, just to reinstate a reasonable approximation of what we had in Gecko.
</blockquote></details>

I was actually suggesting we just let the browser do what it wants with those keystrokes. Isn't that what happens if the user actually types them?

But I see now that the undo button can affect more than just typing.

But I still question whether we need all the code for copy/cut/paste. What if we just invoked the keystroke and let the browser do it?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5817)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/WebView2Browser.cs` line 380 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5817#-NUYakoj1PwbrpW70pY5:-NUcurf-BIfH18vC4gjG:b-hts2fu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/451bba5cb60f28155ff71b015d0639381fee5715/src/BloomExe/WebView2Browser.cs#L380)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I was actually suggesting we just let the browser do what it wants with those keystrokes. Isn't that what happens if the user actually types them?

But I see now that the undo button can affect more than just typing.

But I still question whether we need all the code for copy/cut/paste. What if we just invoked the keystroke and let the browser do it?
</blockquote></details>

It would probably work for the clipboard functions. As you note, we've made some enhancements to Undo.
Something in me resists the idea of emulating keystrokes, but I can't really articulate why. It may just be laziness. But here's at least one issue: are we sure there's no way for a user to configure different keystrokes for clipboard? Does a Chinese or Arabic keyboard even have these keys?

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5817)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
