### PR TITLE
Second part of Bl-6109 epub manager hangs if temp file is locked

### PR DESCRIPTION
**Pull request by hatton**
First part is in libpalaso, but this can be merged independently.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2491)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Would make more sense if you could correct the typo in the commit message (hands => hangs)

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 204 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2491#-LEtwkJ16x-Pka34W8of:-LEtwkJ16x-Pka34W8og:bxssnrw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ff9c29ac743b02b066991727f0483dd037e0b47/src/BloomExe/Publish/Epub/EpubMaker.cs#L204)):*
> ```Smalltalk
> 			var exportRoot = Path.Combine(Path.GetTempPath(), kEPUBExportFolder);
> 			Directory.CreateDirectory(exportRoot); // this is ok if it already exists
> 			for (var i = 0; i < 20; i++)
> ```

20 tries at this could take 40s, right? Do we need to give some feedback? Of course it won't usually take anything like that...

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2491#-:-LEtwQ2L3Za4Dam5XoJ2:b-lywyc6)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2491)*

**Comment by hatton** [comment]
Review status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @JohnThomson, @andrew-polk, and @hatton)

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 204 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2491#-LEtwkJ16x-Pka34W8of:-LEuBZVd26WpTKAiJ1jO:b-dtfwlf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ff9c29ac743b02b066991727f0483dd037e0b47/src/BloomExe/Publish/Epub/EpubMaker.cs#L204)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

20 tries at this could take 40s, right? Do we need to give some feedback? Of course it won't usually take anything like that...
</blockquote></details>

Yeah, ok. Added progress capability.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2491)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2491#-:-LEujLEv8Bxs5SGlBrtK:bnfp4nl)*

**Pull request merged**
