### PR TITLE
Clean up UI for reporting bad zip (BL-10097)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4587)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Please add BL-10097 to the commit message and PR summary

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4587#-:-MeQZPJ--zRZJkpj2gZD:bxvr02r)* status: all files reviewed, 8 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/react_components/bookProblem.tsx, line 23 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4587#-MeQahYM-p7TKLJw5EXe:-MeQahYM-p7TKLJw5EXf:b56cr1z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95f8c98792b973e919e9552b08339b2b7506daf0/src/BloomBrowserUI/react_components/bookProblem.tsx#L23)):*
> ```
> There was a problem with the current book
> ```
Better as `There is a problem with the current book in the Team Collection system.`?
___
*[src/BloomBrowserUI/react_components/bookProblem.tsx, line 27 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4587#-MeQaquA3aUl3yR9-1Yd:-MeQaquA3aUl3yR9-1Ye:b-60g69p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95f8c98792b973e919e9552b08339b2b7506daf0/src/BloomBrowserUI/react_components/bookProblem.tsx#L27)):*
> ```
>  + props.clickHereArg
> ```
Did you consider doing something purely on the C# side such that we don't have to pass the arg back and forth?
I'm thinking along the lines of setting a static in CommonMessages. Not the ideal but maybe better than this?
___
*[src/BloomBrowserUI/react_components/bookProblem.tsx, line 28 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4587#-MeQ_uvI5YpFSBIcTnIu:-MeQ_uvJAbTLyy6bkfyp:bukpbkl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95f8c98792b973e919e9552b08339b2b7506daf0/src/BloomBrowserUI/react_components/bookProblem.tsx#L28)):*
> ```
> Click here for help
> ```
I think if the user ever sees this, there will be no link?
I'm unclear if the purpose of this default is to show something while waiting for the API call to return or in case of error or both.
If the former, perhaps the best default is what we expect the final text to be (at least for English) so the only thing which will change is the addition of the link.
If the latter, probably the best is to have an empty string.
___
*[src/BloomBrowserUI/react_components/bookProblem.tsx, line 37 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4587#-MeQbPIF90TsyRhikLRL:-MeQbPIG3u7d_lYZCt8F:b3mx7fl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95f8c98792b973e919e9552b08339b2b7506daf0/src/BloomBrowserUI/react_components/bookProblem.tsx#L37)):*
> ```
> brigher
> ```
brighter

Does VS not show you typos in comments? I think it is easy to configure it to do so.
___
*[src/BloomBrowserUI/react_components/bookProblem.tsx, line 46 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4587#-MeQciYz5yxuMUzPfw3h:-MeQciYz5yxuMUzPfw3i:bnbfb8y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95f8c98792b973e919e9552b08339b2b7506daf0/src/BloomBrowserUI/react_components/bookProblem.tsx#L46)):*
> ```
> disconnected
> ```
It isn't clear to me that it is useful to have an alt here, but if we include it, it probably needs to be more generic?
___
*[src/BloomBrowserUI/react_components/iconHeadingBodyMenu.tsx, line 10 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4587#-MeQc-NV9ZD6A8Sk_N_8:-MeQc-NV9ZD6A8Sk_N_9:bbymjlu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95f8c98792b973e919e9552b08339b2b7506daf0/src/BloomBrowserUI/react_components/iconHeadingBodyMenu.tsx#L10)):*
> ```
> TeamCollectinBookStatusPanel
> ```
TeamCollectionBookStatusPanel
___
*[src/BloomBrowserUI/react_components/iconHeadingBodyMenu.tsx, line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4587#-MeQc9420GdLkSzWMDXR:-MeQc9420GdLkSzWMDXS:bp0wmvw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95f8c98792b973e919e9552b08339b2b7506daf0/src/BloomBrowserUI/react_components/iconHeadingBodyMenu.tsx#L13)):*
> ```
> IconHeadingBodyMenu
> ```
How would you feel about IconHeadingBodyMenuPanel?

And if the name is basically a list of ingredients, I think we want the prop names to match the list in the name.
title <> heading
subTitle <> body
___
*[src/BloomExe/CommonMessages.cs, line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4587#-MeQe0lu5W1TRz-_WzHU:-MeQe0lv-kFvS_2GnchM:b-tx66y9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95f8c98792b973e919e9552b08339b2b7506daf0/src/BloomExe/CommonMessages.cs#L36)):*
> ```
> GetProblemWithBookMessage
> ```
Probably better lives in TeamCollection?

**Review by JohnThomson — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4587#-:-MeRmhOr5W7r0XITVbE6:bb6un1j)* status: 6 of 10 files reviewed, 8 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/react_components/bookProblem.tsx, line 23 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4587#-MeQahYM-p7TKLJw5EXe:-MeRqruI2GG04FGCokp9:b-7932pe) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95f8c98792b973e919e9552b08339b2b7506daf0/src/BloomBrowserUI/react_components/bookProblem.tsx#L23)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> There was a problem with the current book
> ```
Better as `There is a problem with the current book in the Team Collection system.`?
</blockquote></details>

Done. Plus you made me realize this message is not as generic as this component is trying to be. Added some YAGNI comments.
___
*[src/BloomBrowserUI/react_components/bookProblem.tsx, line 27 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4587#-MeQaquA3aUl3yR9-1Yd:-MeRr-zY75yhPf9vPrHC:bf04ezl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95f8c98792b973e919e9552b08339b2b7506daf0/src/BloomBrowserUI/react_components/bookProblem.tsx#L27)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
>  + props.clickHereArg
> ```
Did you consider doing something purely on the C# side such that we don't have to pass the arg back and forth?
I'm thinking along the lines of setting a static in CommonMessages. Not the ideal but maybe better than this?
</blockquote></details>

I did, but as I understand JohnH's goal, we're wanting this to be a (somewhat) general-purpose control for reporting a problem with a book and offering help. It doesn't feel like something to take for granted that the source of the problem IS C#, though since the param signifies a file to attach, it's hard to see how it could originate in JS.
___
*[src/BloomBrowserUI/react_components/bookProblem.tsx, line 28 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4587#-MeQ_uvI5YpFSBIcTnIu:-MeRsDKlEwiUDZYX4xI9:bs036ir) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95f8c98792b973e919e9552b08339b2b7506daf0/src/BloomBrowserUI/react_components/bookProblem.tsx#L28)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Click here for help
> ```
I think if the user ever sees this, there will be no link?
I'm unclear if the purpose of this default is to show something while waiting for the API call to return or in case of error or both.
If the former, perhaps the best default is what we expect the final text to be (at least for English) so the only thing which will change is the addition of the link.
If the latter, probably the best is to have an empty string.
</blockquote></details>

Not sure I had either clearly in mind...the API requires a default to return until the real message. It's fast enough on my system I never noticed any flicker. Decided to go with the expected English text as that makes it easier to understand the code, at least.
___
*[src/BloomBrowserUI/react_components/bookProblem.tsx, line 37 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4587#-MeQbPIF90TsyRhikLRL:-MeRt1UK7XJXI_ms9nTR:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95f8c98792b973e919e9552b08339b2b7506daf0/src/BloomBrowserUI/react_components/bookProblem.tsx#L37)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> brigher
> ```
brighter

Does VS not show you typos in comments? I think it is easy to configure it to do so.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/react_components/bookProblem.tsx, line 46 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4587#-MeQciYz5yxuMUzPfw3h:-MeRtBp8AFT7PmYtacdr:b-rzjskn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95f8c98792b973e919e9552b08339b2b7506daf0/src/BloomBrowserUI/react_components/bookProblem.tsx#L46)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> disconnected
> ```
It isn't clear to me that it is useful to have an alt here, but if we include it, it probably needs to be more generic?
</blockquote></details>

Copy paste error.
___
*[src/BloomExe/CommonMessages.cs, line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4587#-MeQe0lu5W1TRz-_WzHU:-MeRtjWm2hQCKcfxBDR1:b-pjukq6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95f8c98792b973e919e9552b08339b2b7506daf0/src/BloomExe/CommonMessages.cs#L36)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> GetProblemWithBookMessage
> ```
Probably better lives in TeamCollection?
</blockquote></details>

As currently worded, yes. But I think this, like the component, wants to grow up to be a generic way of showing problems with the current book. If it does, the bit about Team Collection system will somehow have to become optional, and this location will be better. But maybe we should wait till then to put it here? Toss up in my mind, but I don't want to bother moving it, only to have to move it back later.
___
*[src/BloomBrowserUI/react_components/iconHeadingBodyMenu.tsx, line 10 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4587#-MeQc-NV9ZD6A8Sk_N_8:-MeRtP7E4mGJkgSHYUQY:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95f8c98792b973e919e9552b08339b2b7506daf0/src/BloomBrowserUI/react_components/iconHeadingBodyMenu.tsx#L10)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> TeamCollectinBookStatusPanel
> ```
TeamCollectionBookStatusPanel
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/react_components/iconHeadingBodyMenu.tsx, line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4587#-MeQc9420GdLkSzWMDXR:-MeRtQRv83mBC-7-Q8My:b448h3h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95f8c98792b973e919e9552b08339b2b7506daf0/src/BloomBrowserUI/react_components/iconHeadingBodyMenu.tsx#L13)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> IconHeadingBodyMenu
> ```
How would you feel about IconHeadingBodyMenuPanel?

And if the name is basically a list of ingredients, I think we want the prop names to match the list in the name.
title <> heading
subTitle <> body
</blockquote></details>

Done. Nice idea.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4587)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/react_components/bookProblem.tsx, line 23 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4587#-MeQahYM-p7TKLJw5EXe:-MeS3CrF8gixRRPbdWN0:b-q7t5ol) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95f8c98792b973e919e9552b08339b2b7506daf0/src/BloomBrowserUI/react_components/bookProblem.tsx#L23)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done. Plus you made me realize this message is not as generic as this component is trying to be. Added some YAGNI comments.
</blockquote></details>

I guess the question is whether it is intended to be reusable inside or outside the TC context.
It seems like one of his main goals was to reduce new l10n strings, so it seems if we want to be able to use it outside TC, we should drop the TC language now.

I've asked JH for clarity in the card.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4587)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
