### PR TITLE
BL-4694 Fix TextOverPicture resizing

### PR DESCRIPTION
**Pull request by gmartin7**
There was a problem where resizing a box messed
up its draggable containment, so now after we resize,
we go back through making it draggable and
clickable again.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1742)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/js/textOverPicture.ts, line 143 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1742#-Kp0ewUvbLhtfH2K3Kql:-Kp0ewUvbLhtfH2K3Kqm:bkw0h59) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/31f3db1399e579f25c11d69d9a9ab5b7f97dee80/src/BloomBrowserUI/bookEdit/js/textOverPicture.ts#L143)):*
> ```XML
>             // so now after we resize we go back through making it draggable and clickable again.
>             stop: function (event, ui) {
>                 topMgr.makeTOPBoxDraggableAndClickable($(this), scale);
> ```

Personally, I hate this feature of JS where 'this' changes in an embedded function. I much prefer the (event, ui) => ... syntax which doesn't do that. Unfortunately, you then have to figure out how to get at the resized object. If it's not a lot of trouble and you agree with me, you might consider doing that. Otherwise, LGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1742)*

**Comment by gmartin7** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/js/textOverPicture.ts, line 143 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1742#-Kp0ewUvbLhtfH2K3Kql:-Kp1Js8n3Aff7yXvF0d6:b-e6y92k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/31f3db1399e579f25c11d69d9a9ab5b7f97dee80/src/BloomBrowserUI/bookEdit/js/textOverPicture.ts#L143)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Personally, I hate this feature of JS where 'this' changes in an embedded function. I much prefer the (event, ui) => ... syntax which doesn't do that. Unfortunately, you then have to figure out how to get at the resized object. If it's not a lot of trouble and you agree with me, you might consider doing that. Otherwise, LGTM.
</blockquote></details>

After spending a couple of hours trying to figure out how to get it to work with the arrow syntax, I'm gonna have to stay with what works. All the jqueryUi examples I can find seem to use the syntax I'm using. I like the arrow syntax too, but it's doing something that I don't know how to get around.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1742)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/js/textOverPicture.ts, line 143 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1742#-Kp0ewUvbLhtfH2K3Kql:-Kp1QGMactMm98ILcT72:bwa0w4j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e02bc5b404bd21c6866d519611d1af6565d20b86/src/BloomBrowserUI/bookEdit/js/textOverPicture.ts#L143)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

After spending a couple of hours trying to figure out how to get it to work with the arrow syntax, I'm gonna have to stay with what works. All the jqueryUi examples I can find seem to use the syntax I'm using. I like the arrow syntax too, but it's doing something that I don't know how to get around.
</blockquote></details>

It's not just event.target, as in?

{stop: (event,ui)=> foo(event.target)} ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1742)*

**Comment by gmartin7** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/js/textOverPicture.ts, line 143 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1742#-Kp0ewUvbLhtfH2K3Kql:-Kp1UclTP1wN1m0igi1Q:byebv4j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e02bc5b404bd21c6866d519611d1af6565d20b86/src/BloomBrowserUI/bookEdit/js/textOverPicture.ts#L143)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

It's not just event.target, as in?

{stop: (event,ui)=> foo(event.target)} ?
</blockquote></details>

Boy, I feel silly. Of course. In this case, I need $(event.target), but yes indeed you are absolutely right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1742)*

**Comment by JohnThomson** [comment]
:lgtm: unless you want to get rid of a now-redundant variable

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/textOverPicture.ts, line 143 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1742#-Kp1iOmCrS9pgwwpvUPw:-Kp1iOmCrS9pgwwpvUPx:bk4xmd4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3462755304ee6880499b23c1e4949114bafbdf17/src/BloomBrowserUI/bookEdit/js/textOverPicture.ts#L143)):*
> ```XML
>             // so now after we resize we go back through making it draggable and clickable again.
>             stop: (event, ui) => {
>                 topMgr.makeTOPBoxDraggableAndClickable($(event.target), scale);
> ```

And now that you aren't messing with the meaning of 'this', topMgr is just an alias for 'this' so you can get rid of it, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1742#-:-Kp1iAMNnmW0nYFt7t3v:bvwlid8)*

**Comment by gmartin7** [comment]
Got rid of it two places. I also refactored the main entry point from bloomEditing a bit.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/textOverPicture.ts, line 143 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1742#-Kp1iOmCrS9pgwwpvUPw:-Kp1lN96hRIfgqNlNoW0:bzdjlw6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3462755304ee6880499b23c1e4949114bafbdf17/src/BloomBrowserUI/bookEdit/js/textOverPicture.ts#L143)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

And now that you aren't messing with the meaning of 'this', topMgr is just an alias for 'this' so you can get rid of it, right?
</blockquote></details>

right, both here and above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1742#-:-Kp1lVQ11SK6vbVIEuq5:bpog0g4)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1742#-:-KpFXpF80jcQwFPvUrZB:bnfp4nl)*

**Pull request merged**
