### PR TITLE
Various improvements to Games

### PR DESCRIPTION
**Pull request by JohnThomson**
Started out as updating Games to work with various recent changes, especially to how we do overlays. Ended up incorporating various refactorings and bug fixes and a couple more Games-related Notion cards.
Possibly easier to review individual commits, which indicate the purpose of each step. However, note the final commit cleans up various things.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6684)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 8 of 8 files at r2, 6 of 7 files at r3, 1 of 1 files at r4, 4 of 4 files at r5, 6 of 6 files at r6, 6 of 6 files at r7, 4 of 4 files at r8, 1 of 1 files at r9, 2 of 2 files at r10, 11 of 11 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6684)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 76 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6684#-O89BUqo9HpbwKEII_qq:-O89BUqo9HpbwKEII_qr:b-kuhi2h) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff73190548a431392d685a6482d74c0b71963310/DistFiles/localization/en/BloomMediumPriority.xlf#L76)):*
> ```XML
>         <note>ID: EditTab.Toolbox.DragActivity.DraggableTargetInstructions</note>
>       </trans-unit>
>       <trans-unit id="EditTab.Toolbox.DragActivity.EditWordToSpell" translate="yes">
> ```

Are we ready to add these strings to the translator's load?
Seems like Games are still in enough flux to keep these translate="no"?
Same below?
___
*[`src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.tsx` line 46 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6684#-O89CDh926_4BLlSIYd3:-O89CDh926_4BLlSIYd4:b-ancwnf) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff73190548a431392d685a6482d74c0b71963310/src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.tsx#L46)):*
> ```XML
>         contentsOfBubble: JQuery,
>         selectLangTag?: string,
>         forceShowAlwaysOnBody?: boolean
> ```

This param could probably use some comment help.
What does it do? Why would you want it true?
___
*[`src/BloomBrowserUI/bookEdit/toolbox/dragActivity/GamePromptDialog.tsx` line 219 at r8](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6684#-O89J_371MwlscHENd9S:-O89J_371MwlscHENd9T:b3b4zn5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2a16c9fb8ce08e3d3701bc45789842ce66462d4a/src/BloomBrowserUI/bookEdit/toolbox/dragActivity/GamePromptDialog.tsx#L219)):*
> ```XML
> };
> 
> export function splitIntoGraphemes(text: string): string[] {
> ```

Consider whether it is worth moving this and its test to a more general-purpose/shared file.
___
*[`src/BloomExe/Book/BookStorage.cs` line 1061 at r8](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6684#-O89Jr_wAeopKK8atp-3:-O89Jr_wAeopKK8atp-4:bld1f4n) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2a16c9fb8ce08e3d3701bc45789842ce66462d4a/src/BloomExe/Book/BookStorage.cs#L1061)):*
> ```Smalltalk
>                 FeatureId = "bloomGames6.1",
>                 FeaturePhrase = "Bloom Games added in 6.2",
>                 BloomDesktopMinVersion = "6.1",
> ```

Shouldn't the minVersion also be 6.2?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6684)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 76 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6684#-O89BUqo9HpbwKEII_qq:-O8D_0YiCIE-0NU6gmUR:bqsyjg6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff73190548a431392d685a6482d74c0b71963310/DistFiles/localization/en/BloomMediumPriority.xlf#L76)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Already done in a later commit
</blockquote></details>

Sorry; I missed that.
___
*[`src/BloomExe/Book/BookStorage.cs` line 1061 at r8](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6684#-O89Jr_wAeopKK8atp-3:-O8D_XdfAAuAUxPJ6bJ4:bpmot8x) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2a16c9fb8ce08e3d3701bc45789842ce66462d4a/src/BloomExe/Book/BookStorage.cs#L1061)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Yep. Changed one of them in my final review and missed the other.
</blockquote></details>

Sorry, but now I see that the featureId is "bloomGames6.1"
___
*[`src/BloomBrowserUI/utils/textUtilsSpec.ts` line 4 at r13](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6684#-O8D_T81CUecU5b1mjaW:-O8D_T81CUecU5b1mjaX:blwkxjg) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cb87d3a673585529cefa63a32dcac1eaafaf6a79/src/BloomBrowserUI/utils/textUtilsSpec.ts#L4)):*
> ```XML
> 
> describe("split into grapheme tests", () => {
>     fit("handles diacritics followed by space", () => {
> ```

You left this as "fit"

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6684)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6684)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/toolbox/dragActivity/GamePromptDialog.tsx` line 219 at r8](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6684#-O89J_371MwlscHENd9S:-O8Da-tW0DghKhfi_fIK:bb6un1j) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2a16c9fb8ce08e3d3701bc45789842ce66462d4a/src/BloomBrowserUI/bookEdit/toolbox/dragActivity/GamePromptDialog.tsx#L219)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Consider whether it is worth moving this and its test to a more general-purpose/shared file.
</blockquote></details>

Done
___
*[`src/BloomExe/Book/BookStorage.cs` line 1061 at r8](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6684#-O89Jr_wAeopKK8atp-3:-O8Dcm-d-Keu1tiuoQaC:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2a16c9fb8ce08e3d3701bc45789842ce66462d4a/src/BloomExe/Book/BookStorage.cs#L1061)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry, but now I see that the featureId is "bloomGames6.1"
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/utils/textUtilsSpec.ts` line 4 at r13](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6684#-O8D_T81CUecU5b1mjaW:-O8DcoHPCQCoul9_NPf1:bb7f2mf) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cb87d3a673585529cefa63a32dcac1eaafaf6a79/src/BloomBrowserUI/utils/textUtilsSpec.ts#L4)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

You left this as "fit"
</blockquote></details>

done

**Pull request merged**
