### PR TITLE
Fix a problem when pasting an image (BL-11558)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5461)

### CODE REVIEW

**Comment by hatton** [comment]
It's difficult to see what changed because of the refactor. Do you want to give us a description? Thx.

**Review by StephenMcConnel — COMMENTED** [review]
TryResizeImageWithGraphicsMagick() created a temporary file for GraphicsMagick to use when the image came from being pasted, but then promptly deleted the file at the end of the method.
TryResizeImageWithGraphicsMagick() did not try this, so a pasted image still had a null file, causing the problem report to pop up.
I essentially did three things i this changeset:
1) Abstract/refactor a method for creating the temporary file, which is now called from both TryResizeImageWithGraphicsMagick and TryResizeImageWithGraphicsMagick.
2) In that new method, store the path to the temporary file both in a class variable and in the image (where it may get overwritten or it may prevent TryResizeImageWithGraphicsMagick() from deleting it and still be available for TryResizeImageWithGraphicsMagick to use)
3) use the class variable to delete the file if it hasn't already been deleted by the time we know we'd be through with it

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5461#-:-NEIOjsp81YbmoGxpSsF:b-mah3xm)* status: 0 of 1 files reviewed, all discussions resolved

**Review by JohnThomson — APPROVED** [review]
A minor suggestion...up to you whether it's worth the trouble. If you don't think so, feel free to merge.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5461#-:-NEc0GVyA1DrmNfWY5c5:b9q0bbp)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 184 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5461#-NEc-U8c9mpyCxLua9P7:-NEc-U8c9mpyCxLua9P8:bklmlt1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/cb8828995b00177fd02f2521142e041f48b3981d/src/BloomExe/ImageProcessing/ImageUtils.cs#L184)):*
> ```Smalltalk
> 					imageInfo.Image.Save(destinationPath, ImageFormat.Png); // destinationPath already has .png extension
> 				if (_createdTempImageFile != null && RobustFile.Exists(_createdTempImageFile))
> 					RobustFile.Delete(_createdTempImageFile);
> ```

Maybe worth setting the variable to null here?
___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 798 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5461#-NEc-aypCgUSiyARP8pF:-NEc-aypCgUSiyARP8pG:b9fh94k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/cb8828995b00177fd02f2521142e041f48b3981d/src/BloomExe/ImageProcessing/ImageUtils.cs#L798)):*
> ```Smalltalk
> 			}
> 			imageInfo.SetCurrentFilePath(sourcePath);
> 			_createdTempImageFile = sourcePath;
> ```

This code would be in trouble with race conditions involving this variable if ever called on multiple threads. I'm not very worried since it's aimed at things the user does one at at time. But we could help ourselves catch this, in case we ever used it another way, by setting _createdTempImageFile to null above when done with it, and here throwing (or at least asserting) that it is null.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5461)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 184 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5461#-NEc-U8c9mpyCxLua9P7:-NEffkq345S_ILkrYaiL:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/cb8828995b00177fd02f2521142e041f48b3981d/src/BloomExe/ImageProcessing/ImageUtils.cs#L184)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Maybe worth setting the variable to null here?
</blockquote></details>

Done.
___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 798 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5461#-NEc-aypCgUSiyARP8pF:-NEfghgS9GU_3c2Ylqqi:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/cb8828995b00177fd02f2521142e041f48b3981d/src/BloomExe/ImageProcessing/ImageUtils.cs#L798)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This code would be in trouble with race conditions involving this variable if ever called on multiple threads. I'm not very worried since it's aimed at things the user does one at at time. But we could help ourselves catch this, in case we ever used it another way, by setting _createdTempImageFile to null above when done with it, and here throwing (or at least asserting) that it is null.
</blockquote></details>

Done.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5461)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
