### PR TITLE
BL-10033 Update Publish to Android UI

### PR DESCRIPTION
**Pull request by gmartin7**
* update .bloomd to .BloomPUB in Publish to File UI
* use new icons and radio button text
* N.B.: putting links into an .xlf file entails using ampersand
   codes for the < and >.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5119)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5119)* status: all files reviewed, 5 unresolved discussions (waiting on @gmartin7)

___
*[DistFiles/localization/en/Bloom.xlf, line 3487 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5119#-N07q7Us5iUZMisvbH9z:-N07q7Us5iUZMisvbHA-:b-fgjazy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65cd338f2cc3db544e1d7cb6ddb184d5bc9e02a9/DistFiles/localization/en/Bloom.xlf#L3487)):*
> ```XML
>       </trans-unit>
>       <trans-unit id="PublishTab.Android.BloomPUB.Hint.Heading" sil:dynamic="true">
>         <source xml:lang="en">Sharing .BloomPUB Files</source>
> ```

The mockup has no dot before BloomPUB



_Code quote:_
```XML
Sharing .BloomPUB Files
```
___
*[DistFiles/localization/en/Bloom.xlf, line 3491 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5119#-N07qQCV-XazT53_QL3Q:-N07qQCV-XazT53_QL3R:bdefewo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65cd338f2cc3db544e1d7cb6ddb184d5bc9e02a9/DistFiles/localization/en/Bloom.xlf#L3491)):*
> ```XML
>       </trans-unit>
>       <trans-unit id="PublishTab.Android.BloomPUB.Hint" sil:dynamic="true">
>         <source xml:lang="en">You can use SD cards and sharing apps like email, Google Drive, and WhatsApp to get your bloompub file onto a device that has &lt;a href="https://bloomlibrary.org/page/create/bloom-reader"&gt;Bloom Reader&lt;/a&gt; (Android) or &lt;a href="https://github.com/BloomBooks/bloompub-viewer/releases"&gt;Bloom Viewer&lt;/a&gt; (Windows). You can also create a stand-alone app using &lt;a href="https://software.sil.org/readingappbuilder/"&gt;Reading App Builder&lt;/a&gt;.</source>
> ```

The mockup has a dot before bloompub



_Code quote:_
```XML
bloompub
```
___
*[DistFiles/localization/en/Bloom.xlf, line 3491 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5119#-N07t04BEOb4ep6WEf9W:-N07t04BEOb4ep6WEf9X:b-bgairl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65cd338f2cc3db544e1d7cb6ddb184d5bc9e02a9/DistFiles/localization/en/Bloom.xlf#L3491)):*
> ```XML
>       </trans-unit>
>       <trans-unit id="PublishTab.Android.BloomPUB.Hint" sil:dynamic="true">
>         <source xml:lang="en">You can use SD cards and sharing apps like email, Google Drive, and WhatsApp to get your bloompub file onto a device that has &lt;a href="https://bloomlibrary.org/page/create/bloom-reader"&gt;Bloom Reader&lt;/a&gt; (Android) or &lt;a href="https://github.com/BloomBooks/bloompub-viewer/releases"&gt;Bloom Viewer&lt;/a&gt; (Windows). You can also create a stand-alone app using &lt;a href="https://software.sil.org/readingappbuilder/"&gt;Reading App Builder&lt;/a&gt;.</source>
> ```

I confirmed... JH meant to put BloomPUB Viewer in the mockup.



_Code quote:_
```XML
Bloom Viewer
```
___
*[src/BloomBrowserUI/react_components/l10nComponents.tsx, line 107 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5119#-N07ukwE68ml95K8YBCc:-N07ukwE68ml95K8YBCd:b-j80tfh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65cd338f2cc3db544e1d7cb6ddb184d5bc9e02a9/src/BloomBrowserUI/react_components/l10nComponents.tsx#L107)):*
> ```XML
>     private attributeString(tagType: string, props: any): string {
>         // warning: don't try to access props["href"] unless you're dealing with an anchor tag.
>         return tagType === "a" ? ' href="' + props["href"] + '"' : "";
> ```

I'm slightly concerned about this. 
What are the chances of this breaking existing stuff?
Questions come to mind such as:
What if there is an anchor with an onclick and no href? Or is that not allowed? Does `props["href"]` handle it gracefully if there is no href?
___
*[src/BloomBrowserUI/react_components/l10nComponents.tsx, line 128 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5119#-N07uU_mAOI1iCrbaQDN:-N07uU_mAOI1iCrbaQDO:bu1cu5g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65cd338f2cc3db544e1d7cb6ddb184d5bc9e02a9/src/BloomBrowserUI/react_components/l10nComponents.tsx#L128)):*
> ```XML
>                     "</" +
>                     type +
>                     ">"
> ```

Definitely not a requirement. But something to consider (maybe for next time):
I imagine this would be more readable with backticks and interpolation.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5119)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[DistFiles/localization/en/Bloom.xlf, line 3487 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5119#-N07q7Us5iUZMisvbH9z:-N0C0d0C--hYIxFvifF-:bw7jw64) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65cd338f2cc3db544e1d7cb6ddb184d5bc9e02a9/DistFiles/localization/en/Bloom.xlf#L3487)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The mockup has no dot before BloomPUB
</blockquote></details>

Ah right. The original mockup did. I didn't look carefully enough at the updated one. Done.
___
*[DistFiles/localization/en/Bloom.xlf, line 3491 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5119#-N07t04BEOb4ep6WEf9W:-N0C1KvB8yoSkqJma2sd:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65cd338f2cc3db544e1d7cb6ddb184d5bc9e02a9/DistFiles/localization/en/Bloom.xlf#L3491)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I confirmed... JH meant to put BloomPUB Viewer in the mockup.
</blockquote></details>

Done.
___
*[DistFiles/localization/en/Bloom.xlf, line 3491 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5119#-N07qQCV-XazT53_QL3Q:-N0C2gFf06XneuETU7NH:bfa55lg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65cd338f2cc3db544e1d7cb6ddb184d5bc9e02a9/DistFiles/localization/en/Bloom.xlf#L3491)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The mockup has a dot before bloompub
</blockquote></details>

This one is a bit tricky. If the English string going to `Crowdin` has `.bloompub`, the suggested French translation will drop the `b` altogether. I have no idea why other than maybe it sees `.b` as some sort of markup or because Crowdin thinks that all periods should be followed by a space? If I put `'.bloompub'` in the English source (both here and in the `.tsx` file), then the suggested French translation in Crowdin comes out `.bloompub` as desired. Not sure which is best. For now I've changed to `'.bloompub'` in the English.
___
*[src/BloomBrowserUI/react_components/l10nComponents.tsx, line 107 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5119#-N07ukwE68ml95K8YBCc:-N0CD03gAjpguCO4btqo:bda9mjp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65cd338f2cc3db544e1d7cb6ddb184d5bc9e02a9/src/BloomBrowserUI/react_components/l10nComponents.tsx#L107)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm slightly concerned about this. 
What are the chances of this breaking existing stuff?
Questions come to mind such as:
What if there is an anchor with an onclick and no href? Or is that not allowed? Does `props["href"]` handle it gracefully if there is no href?

</blockquote></details>

So I added an onClick handler and renamed/removed the href attribute to see what happens. We didn't get any errors in the Console and the underline disappeared off of the Bloom Reader link, but clicking on it did activate the click handler. So I think we're okay. Nothing untoward happens. I'm actually not sure why the underline disappears. Perhaps it is dependent on there being an `href`.
___
*[src/BloomBrowserUI/react_components/l10nComponents.tsx, line 128 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5119#-N07uU_mAOI1iCrbaQDN:-N0C42354Ofmn8kv7NZn:b-sd0cbq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65cd338f2cc3db544e1d7cb6ddb184d5bc9e02a9/src/BloomBrowserUI/react_components/l10nComponents.tsx#L128)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Definitely not a requirement. But something to consider (maybe for next time):
I imagine this would be more readable with backticks and interpolation.
</blockquote></details>

Done. I like!

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5119)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[DistFiles/localization/en/Bloom.xlf, line 3491 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5119#-N07qQCV-XazT53_QL3Q:-N0CPKFN7Mk_TOnQ8Xht:b-iv357o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65cd338f2cc3db544e1d7cb6ddb184d5bc9e02a9/DistFiles/localization/en/Bloom.xlf#L3491)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

This one is a bit tricky. If the English string going to `Crowdin` has `.bloompub`, the suggested French translation will drop the `b` altogether. I have no idea why other than maybe it sees `.b` as some sort of markup or because Crowdin thinks that all periods should be followed by a space? If I put `'.bloompub'` in the English source (both here and in the `.tsx` file), then the suggested French translation in Crowdin comes out `.bloompub` as desired. Not sure which is best. For now I've changed to `'.bloompub'` in the English.
</blockquote></details>

The "suggested translation" just means the the machine translation that it offers, right?
We don't care about how that comes out, do we?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5119)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[DistFiles/localization/en/Bloom.xlf, line 3491 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5119#-N07qQCV-XazT53_QL3Q:-N0Ceg_D9yR1sjipqLUr:b7ifus8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65cd338f2cc3db544e1d7cb6ddb184d5bc9e02a9/DistFiles/localization/en/Bloom.xlf#L3491)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The "suggested translation" just means the the machine translation that it offers, right?
We don't care about how that comes out, do we?
</blockquote></details>

I suppose I can put the .b in there and just hope the translators do their due diligence?

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5119)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
