### PR TITLE
Another branding fix (BL-11284 and BL-11162)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5214)

### CODE REVIEW

**Review by gmartin7 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5214)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by hatton — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5214)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/content/branding/Missing/branding.json` line 6 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5214#-N4486qt5UDiapF5Da3Z:-N4486qt5UDiapF5Da3_:bpsgxx4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/01048f31ad80b44dd923e716ab99d324a36f7654/src/content/branding/Missing/branding.json#L6)):*
> ```JSON
>             "data-book": "outside-back-cover-branding-bottom-html",
>             "lang": "*",
>             "content": "A future update of Bloom will contain the branding assets for this project.  Thank you for your patience.",
> ```

--> for this Enterprise Subscription

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5214)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/BookStorage.cs` line 2138 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5214#-N44EXpe7dsRFOZFJK5e:-N44EXpe7dsRFOZFJK5f:bh0wtk8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/01048f31ad80b44dd923e716ab99d324a36f7654/src/BloomExe/Book/BookStorage.cs#L2138)):*
> ```Smalltalk
> 				var key = _collectionSettings.BrandingProjectKey;
> 				// I think this is redundant: BrandingProjectKey will be set to 'Default' if we don't have some definite one.
> 				// Keeping this for paranoia, in case there's some path I don't know about where that doesn't happen.
> ```

I assume there is a `key` that matches "local community" enterprise?
___
*[`src/BloomExe/Book/BookStorage.cs` line 2151 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5214#-N44EKpv0SHN_bQil6Pu:-N44EKpv0SHN_bQil6Pv:ba2zawu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/01048f31ad80b44dd923e716ab99d324a36f7654/src/BloomExe/Book/BookStorage.cs#L2151)):*
> ```Smalltalk
> 				}
> 
> 				var filesToCopy = Directory
> ```

Do we have a "safe" version of this? Do we need one?

**Review by gmartin7 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5214)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`src/BloomExe/Book/BookStorage.cs` line 2138 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5214#-N44EXpe7dsRFOZFJK5e:-N44Gtzn2qquF1DiNU44:b-e5xa0u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/01048f31ad80b44dd923e716ab99d324a36f7654/src/BloomExe/Book/BookStorage.cs#L2138)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I assume there is a `key` that matches "local community" enterprise?
</blockquote></details>

Yep. "local-community".

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5214)* status: all files reviewed, 6 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`src/BloomExe/Book/BookStorage.cs` line 1843 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5214#-N44N__P1fhmL9S_Bb5l:-N44N__Q2jAgqKBaoON8:br4zm3a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/de5278533f76c12747711e31daab5746cdaec71d/src/BloomExe/Book/BookStorage.cs#L1843)):*
> ```Smalltalk
> 						InitialLoadErrors = error.Message;
> 						var msg = string.Format("<p>{0}</p><p>{1}</p><p>{2}</p>",
> 							LocalizationManager.GetString("Errors.ReadOnlyBookFolder", "This book cannot be edited because its folder is read-only."),
> ```

A quick search indicates this is the only use of this. If true, we should mark the string as obsolete in the .xlf (including 5.3 in the obsoletion note)
___
*[`src/BloomExe/Book/BookStorage.cs` line 2180 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5214#-N44OFBq-Jy1Ro8ulvXU:-N44OFBq-Jy1Ro8ulvXV:b4dl6ze) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/01048f31ad80b44dd923e716ab99d324a36f7654/src/BloomExe/Book/BookStorage.cs#L2180)):*
> ```Smalltalk
> 				{
> 					Debug.Fail("Brandings MUST provide a branding.css");
> 					// Nothing is better than having the file server search who-knows-where.
> ```

I first parsed this incorrectly.
I think it would be more clear as "An empty branding.css file is better than letting the file server search who-knows-where."



_Code quote:_
```Smalltalk
// Nothing is better than having the file server search who-knows-where.
```
___
*[`src/BloomExe/Book/BookStorage.cs` line 2191 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5214#-N44OrLl23niM8B-oyLb:-N44OrLl23niM8B-oyLc:bwdmk5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/de5278533f76c12747711e31daab5746cdaec71d/src/BloomExe/Book/BookStorage.cs#L2191)):*
> ```Smalltalk
> 				langsInPriorityOrder.Add("en");
> 			var msgFmt = LocalizationManager.GetString("BackCover.NewBrandingNotice",
> 				"A future update of Bloom will contain the branding assets for this project, \x201C{0}\x201D.  Thank you for your patience.",
> ```

I think we can mark this string as obsolete in the .xlf as well? Or maybe just remove it in this case.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5214)* status: 2 of 6 files reviewed, 6 unresolved discussions (waiting on @andrew-polk, @gmartin7, and @hatton)

___
*[`src/BloomExe/Book/BookStorage.cs` line 1843 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5214#-N44N__P1fhmL9S_Bb5l:-N47ph_h09M5nwzgtave:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/de5278533f76c12747711e31daab5746cdaec71d/src/BloomExe/Book/BookStorage.cs#L1843)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

A quick search indicates this is the only use of this. If true, we should mark the string as obsolete in the .xlf (including 5.3 in the obsoletion note)
</blockquote></details>

Done.



_Code quote:_
```Smalltalk
Errors.ReadOnlyBookFolder
```
___
*[`src/BloomExe/Book/BookStorage.cs` line 2138 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5214#-N44EXpe7dsRFOZFJK5e:-N47q-si4c1eKzlOjYJm:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/01048f31ad80b44dd923e716ab99d324a36f7654/src/BloomExe/Book/BookStorage.cs#L2138)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Yep. "local-community".
</blockquote></details>

Done.
___
*[`src/BloomExe/Book/BookStorage.cs` line 2151 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5214#-N44EKpv0SHN_bQil6Pu:-N47q1Er6OH8wK9hKRPi:bc15nd8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/01048f31ad80b44dd923e716ab99d324a36f7654/src/BloomExe/Book/BookStorage.cs#L2151)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Do we have a "safe" version of this? Do we need one?
</blockquote></details>

I don't know of one. The old code was using this form of enumeration, and we're not dealing with a situation where the folder contents are likely to be recently changed I think it's reasonably safe to leave it as-is.
___
*[`src/BloomExe/Book/BookStorage.cs` line 2180 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5214#-N44OFBq-Jy1Ro8ulvXU:-N47r8Gy10YV_TeeBIt_:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/01048f31ad80b44dd923e716ab99d324a36f7654/src/BloomExe/Book/BookStorage.cs#L2180)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I first parsed this incorrectly.
I think it would be more clear as "An empty branding.css file is better than letting the file server search who-knows-where."
</blockquote></details>

Done.
___
*[`src/BloomExe/Book/BookStorage.cs` line 2191 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5214#-N44OrLl23niM8B-oyLb:-N47pwmL6a6uYDxAZtNv:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/de5278533f76c12747711e31daab5746cdaec71d/src/BloomExe/Book/BookStorage.cs#L2191)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think we can mark this string as obsolete in the .xlf as well? Or maybe just remove it in this case.
</blockquote></details>

Done.



_Code quote:_
```Smalltalk
BackCover.NewBrandingNotice
```
___
*[`src/content/branding/Missing/branding.json` line 6 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5214#-N4486qt5UDiapF5Da3Z:-N47rlyQ90RzCTwd4sC-:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/01048f31ad80b44dd923e716ab99d324a36f7654/src/content/branding/Missing/branding.json#L6)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

--> for this Enterprise Subscription
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5214)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton)

**Pull request merged**
