### PR TITLE
Reduce number of synchronous calls to RunJavascript (BL-12691)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
Either switch to RunJavascriptAsync where feasible, or merge multiple consecutive calls to a single call to at least minimize exposure to problems with the synchronization code.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6111)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6111)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomExe/WebView2Browser.cs` line 549 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6111#-Neidxf-CgJQ8-TgMisc:-Neidxf-CgJQ8-TgMisd:b4ds0gj) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3a9c69cae7e68fb73bc89690af67ba604243410c/src/BloomExe/WebView2Browser.cs#L549)):*
> ```Smalltalk
> 		}
> 
> 		private async void checkIfCanUndo()
> ```

Hm. JH and I already worked through the changes for this one, but looks like they haven't been merged yet.
https://github.com/BloomBooks/BloomDesktop/pull/6096

I'm going to wait to finish my review until these changes are rebased on those.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6111)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/WebView2Browser.cs` line 549 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6111#-Neidxf-CgJQ8-TgMisc:-NfMFNWt7Bunw50Bh68u:b-vqjy8w) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3a9c69cae7e68fb73bc89690af67ba604243410c/src/BloomExe/WebView2Browser.cs#L549)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Hm. JH and I already worked through the changes for this one, but looks like they haven't been merged yet.
https://github.com/BloomBooks/BloomDesktop/pull/6096

I'm going to wait to finish my review until these changes are rebased on those.
</blockquote></details>

I've rebased the changes, and tweaked them a minor amount.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Looks like this PR got tagged with the wrong issue number. Should be BL-12691.
I don't see in the card that we intended to target 5.5. Actually, I thought this was pushed off to 5.6 as being too risky for 5.5. 
Otherwise, maybe it was that part of a conversation I missed? If so, we should probably update the card.

If we are going to target 5.6, I guess you can work on solidifying the commented out code?

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6111#-:-NfMk8h60sa_aHJJo3ht:b-6bph7s)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
I've edited the tag/title.  :-)  And changed the target/base to master.  SInce this is targeting Alpha now, I uncommented the more aggressive combining of consecutive calls to get data and tested more thoroughly.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6111#-:-NfNdc2cDcynBM46pACs:b-qqmn0t)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 2 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6111)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
