### PR TITLE
Implement RobustIO.EnumerateFilesInDirectory for image cleanup (BL-12…

### PR DESCRIPTION
**Pull request by StephenMcConnel**
…309)

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5901)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5901)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/ToPalaso/RobustIO.cs` line 16 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5901#-NXBxNrz2ugpyb5DbIUW:-NXBxNrz2ugpyb5DbIUX:b-6106tw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e23cfecf03ff4c3115efe523775839ff24be7c3f/src/BloomExe/ToPalaso/RobustIO.cs#L16)):*
> ```Smalltalk
> 		public static IEnumerable<string> EnumerateFilesInDirectory(string folderPath, string searchPattern = "*", SearchOption option=SearchOption.TopDirectoryOnly)
> 		{
> 			var fileSet = new HashSet<string>();
> ```

Probably worth a comment explaining why we need to maintain a set which accumulates across calls to the internal method.
___
*[`src/BloomExe/ToPalaso/RobustIO.cs` line 29 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5901#-NXBx1IX6_slSw16wbJp:-NXBx1IY0ZOdZbw_y5Z2:b-q1rihs) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e23cfecf03ff4c3115efe523775839ff24be7c3f/src/BloomExe/ToPalaso/RobustIO.cs#L29)):*
> ```Smalltalk
> 		}
> 
> 		private static IEnumerable<string> EnumerateFilesInDirectoryInternal(string folderPath, string searchPattern, SearchOption option, HashSet<string> fileSet)
> ```

The signature returns IEnumerable<string> but that is never used.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5901)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/ToPalaso/RobustIO.cs` line 16 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5901#-NXBxNrz2ugpyb5DbIUW:-NXC50eG6omuiY4UrqtM:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e23cfecf03ff4c3115efe523775839ff24be7c3f/src/BloomExe/ToPalaso/RobustIO.cs#L16)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Probably worth a comment explaining why we need to maintain a set which accumulates across calls to the internal method.
</blockquote></details>

Done.
___
*[`src/BloomExe/ToPalaso/RobustIO.cs` line 29 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5901#-NXBx1IX6_slSw16wbJp:-NXC4x15AHlThnpMFC-2:b3pryaq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e23cfecf03ff4c3115efe523775839ff24be7c3f/src/BloomExe/ToPalaso/RobustIO.cs#L29)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The signature returns IEnumerable<string> but that is never used.
</blockquote></details>

I removed the return value.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5901)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomExe/ToPalaso/RobustIO.cs` line 16 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5901#-NXBxNrz2ugpyb5DbIUW:-NXCFh-Q23b-vm_kdcz8:bgkkni6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e23cfecf03ff4c3115efe523775839ff24be7c3f/src/BloomExe/ToPalaso/RobustIO.cs#L16)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry; I should have been more explicit.
Why is it insufficient to just let the system call to `Directory.EnumerateFiles` start over? Won't the 2nd or 3rd attempts still give all the files in the directory, assuming it completes without an exception?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5901)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/ToPalaso/RobustIO.cs` line 16 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5901#-NXBxNrz2ugpyb5DbIUW:-NXCLuPG4RZckUajAoZM:b3b4o9a) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e23cfecf03ff4c3115efe523775839ff24be7c3f/src/BloomExe/ToPalaso/RobustIO.cs#L16)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; I should have been more explicit.
Why is it insufficient to just let the system call to `Directory.EnumerateFiles` start over? Won't the 2nd or 3rd attempts still give all the files in the directory, assuming it completes without an exception?
</blockquote></details>

Consider this scenario:  the first attempt returns only the first 10 files in the directory before throwing an IO exception.  The second attempt returns all of the files, including the first 10.  This results in the first 10 files possibly appearing twice in the enumeration, which is undesirable even if it's often (but not always) harmless.  The original method is defined to return files on the fly without waiting to accumulate all of them.
Obviously my comment wasn't sufficient to explain all this although I thought it was.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5901)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomExe/ToPalaso/RobustIO.cs` line 16 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5901#-NXBxNrz2ugpyb5DbIUW:-NXCNcQsCHJAhD-LGN7r:b-1z4svh) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e23cfecf03ff4c3115efe523775839ff24be7c3f/src/BloomExe/ToPalaso/RobustIO.cs#L16)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Consider this scenario:  the first attempt returns only the first 10 files in the directory before throwing an IO exception.  The second attempt returns all of the files, including the first 10.  This results in the first 10 files possibly appearing twice in the enumeration, which is undesirable even if it's often (but not always) harmless.  The original method is defined to return files on the fly without waiting to accumulate all of them.
Obviously my comment wasn't sufficient to explain all this although I thought it was.
</blockquote></details>

Sorry; I think I'm still not communicating my question well.

Why accumulate them at all?
Why can't we just do this:
```
			var files = new string[];
			RetryUtility.Retry(() =>
				files = System.IO.Directory.EnumerateFiles(folderPath, searchPattern, option),
				RetryUtility.kDefaultMaxRetryAttempts,
				RetryUtility.kDefaultRetryDelay,
				new HashSet<Type>
				{
					Type.GetType("System.IO.IOException"),
					Type.GetType("System.Runtime.InteropServices.ExternalException")
				});
			return files;

```
?

If it is still unclear or the answer seems obvious (which it may very well be and I'm missing it), let's meet.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5901)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomExe/ToPalaso/RobustIO.cs` line 16 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5901#-NXBxNrz2ugpyb5DbIUW:-NXCOWVF77THCkyO0mVv:b-tv90r6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e23cfecf03ff4c3115efe523775839ff24be7c3f/src/BloomExe/ToPalaso/RobustIO.cs#L16)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; I think I'm still not communicating my question well.

Why accumulate them at all?
Why can't we just do this:
```
			var files = new string[];
			RetryUtility.Retry(() =>
				files = System.IO.Directory.EnumerateFiles(folderPath, searchPattern, option),
				RetryUtility.kDefaultMaxRetryAttempts,
				RetryUtility.kDefaultRetryDelay,
				new HashSet<Type>
				{
					Type.GetType("System.IO.IOException"),
					Type.GetType("System.Runtime.InteropServices.ExternalException")
				});
			return files;

```
?

If it is still unclear or the answer seems obvious (which it may very well be and I'm missing it), let's meet.
</blockquote></details>

Actually, I think it may actually work (and be better) as:
```
			return RetryUtility.Retry(() =>
				System.IO.Directory.EnumerateFiles(folderPath, searchPattern, option),
				RetryUtility.kDefaultMaxRetryAttempts,
				RetryUtility.kDefaultRetryDelay,
				new HashSet<Type>
				{
					Type.GetType("System.IO.IOException"),
					Type.GetType("System.Runtime.InteropServices.ExternalException")
				});
```

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5901)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @StephenMcConnel)

___
*[`src/BloomExe/ToPalaso/RobustIO.cs` line 16 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5901#-NXBxNrz2ugpyb5DbIUW:-NXCRZoM3Ko1hNNpoDLm:bt3g828) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e23cfecf03ff4c3115efe523775839ff24be7c3f/src/BloomExe/ToPalaso/RobustIO.cs#L16)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Actually, I think it may actually work (and be better) as:
```
			return RetryUtility.Retry(() =>
				System.IO.Directory.EnumerateFiles(folderPath, searchPattern, option),
				RetryUtility.kDefaultMaxRetryAttempts,
				RetryUtility.kDefaultRetryDelay,
				new HashSet<Type>
				{
					Type.GetType("System.IO.IOException"),
					Type.GetType("System.Runtime.InteropServices.ExternalException")
				});
```
</blockquote></details>

Discussed in person. 
We don't know enough about the implementation of enumerables and generics to know if it would be safe without accumulating it ourselves. So going with Steve's initial implementation.

**Review by andrew-polk — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5901)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
