### PR TITLE
Upgrade Nuget packages to latest (BL-8947)

### PR DESCRIPTION
**Pull request by JohnThomson**
Also removes various unused references

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057)* status: all files reviewed, 13 unresolved discussions (waiting on @JohnThomson)

___
*[src/Bloom-ChorusPlugin/BloomChorusPlugin.csproj, line 105 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8Ux6hCL9fD22U7N37:-ML8Ux6hCL9fD22U7N38:b-4qnnqy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a60b5f1b223c977285b0180fc8eaae27ca612198/src/Bloom-ChorusPlugin/BloomChorusPlugin.csproj#L105)):*
> ```XML
>     </PropertyGroup>
>     <Error Condition="!Exists('$(SolutionDir)\.nuget\NuGet.targets')" Text="$([System.String]::Format('$(ErrorText)', '$(SolutionDir)\.nuget\NuGet.targets'))" />
>     <Error Condition="!Exists('..\..\packages\NUnit.3.12.0\build\NUnit.props')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\NUnit.3.12.0\build\NUnit.props'))" />
> ```

I don't think this should be here.
___
*[src/Bloom-ChorusPlugin/packages.config, line 31 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8U_171w0wxckzQ0qC:-ML8U_171w0wxckzQ0qD:b-xpzsxr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a60b5f1b223c977285b0180fc8eaae27ca612198/src/Bloom-ChorusPlugin/packages.config#L31)):*
> ```XML
>   <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.0.0" targetFramework="net461" />
>   <package id="System.Threading.Tasks.Extensions" version="4.5.4" targetFramework="net461" />
>   <package id="System.ValueTuple" version="4.5.0" targetFramework="net461" />
> ```

I don't think we should be adding all these.
___
*[src/BloomExe/BloomExe.csproj, line 3 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8UzOv1ij33OdEc4ZA:-ML8UzOv1ij33OdEc4ZB:b-4qnnqy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a60b5f1b223c977285b0180fc8eaae27ca612198/src/BloomExe/BloomExe.csproj#L3)):*
> ```XML
> <?xml version="1.0" encoding="utf-8"?>
> <Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
>   <Import Project="..\..\packages\NUnit.3.12.0\build\NUnit.props" Condition="Exists('..\..\packages\NUnit.3.12.0\build\NUnit.props')" />
> ```

I don't think this should be here.
___
*[src/BloomExe/BloomExe.csproj, line 198 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8Wsl74CK7wYf5IDez:-ML8Wsl74CK7wYf5IDf-:bkk2f53) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2fd1b252dfc281bd091afaf357cd53af4533f830/src/BloomExe/BloomExe.csproj#L198)):*
> ```XML
>       <HintPath>..\..\packages\Mono.Cecil.0.9.6.4\lib\net45\Mono.Cecil.Rocks.dll</HintPath>
>       <Private>True</Private>
>     </Reference>
> ```

Should we have @stephenmcconnel check all the removals before we merge?
___
*[src/BloomExe/BloomExe.csproj, line 1435 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8VrqOBDcH3q4SWP9p:-ML8VrqOBDcH3q4SWP9q:b-4qnnqy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a60b5f1b223c977285b0180fc8eaae27ca612198/src/BloomExe/BloomExe.csproj#L1435)):*
> ```XML
>     <Error Condition="'$(OS)'=='Windows_NT' AND !Exists('..\..\packages\Geckofx60.32.60.0.50\build\Geckofx60.32.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\Geckofx60.32.60.0.50\build\Geckofx60.32.targets'))" />
>     <Error Condition="'$(OS)'!='Windows_NT' AND !Exists('../../packages/Geckofx60.64.Linux.60.0.51/build/Geckofx60.64.Linux.targets')" Text="$([System.String]::Format('$(ErrorText)', '../../packages/Geckofx60.64.Linux.60.0.51/build/Geckofx60.64.Linux.targets'))" />
>     <Error Condition="!Exists('..\..\packages\NUnit.3.12.0\build\NUnit.props')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\NUnit.3.12.0\build\NUnit.props'))" />
> ```

I don't think this should be here.
___
*[src/BloomExe/packages.config, line 3 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8VxmP4UZMyewPOE4M:-ML8VxmP4UZMyewPOE4N:b-dyg8oi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2fd1b252dfc281bd091afaf357cd53af4533f830/src/BloomExe/packages.config#L3)):*
> ```XML
> <?xml version="1.0" encoding="utf-8"?>
> <packages>
>   
> ```

Let's put this line back.
___
*[src/BloomExe/packages.config, line 7 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8Vuod8_KcaKbd6EtH:-ML8Vuoe61CWa0ReeCRs:b2e85at) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a60b5f1b223c977285b0180fc8eaae27ca612198/src/BloomExe/packages.config#L7)):*
> ```XML
>   <package id="AWSSDK.Core" version="3.5.1.32" targetFramework="net461" />
>   <package id="AWSSDK.S3" version="3.5.3.10" targetFramework="net461" />
>   <package id="Castle.Core" version="4.4.1" targetFramework="net461" />
> ```

I don't see why we need to add this.
___
*[src/BloomExe/packages.config, line 12 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8W23gA5LB2MAAHds_:-ML8W23gA5LB2MAAHdsa:basdbxm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a60b5f1b223c977285b0180fc8eaae27ca612198/src/BloomExe/packages.config#L12)):*
> ```XML
>   <package id="DialogAdapters" version="0.1.11" targetFramework="net461" />
>   <package id="Fleck" version="1.1.0" targetFramework="net461" />
>   <package id="Geckofx60.32" version="60.0.50" targetFramework="net461" />
> ```

This should stay down in the Windows-specific section.
___
*[src/BloomExe/packages.config, line 22 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8W5tm0oMetDTGwUKz:-ML8W5tm0oMetDTGwUL-:bwv9i9i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a60b5f1b223c977285b0180fc8eaae27ca612198/src/BloomExe/packages.config#L22)):*
> ```XML
>   <package id="Microsoft.Web.Xdt" version="3.1.0" targetFramework="net461" />
>   <package id="Mono.Cecil" version="0.11.3" targetFramework="net461" />
>   <package id="Moq" version="4.14.7" targetFramework="net461" />
> ```

This shouldn't be here.
___
*[src/BloomExe/packages.config, line 31 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8W7QT-YNeN2mkhLD4:-ML8W7QT-YNeN2mkhLD5:b-gyo990) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a60b5f1b223c977285b0180fc8eaae27ca612198/src/BloomExe/packages.config#L31)):*
> ```XML
>   <package id="NUnit.Extension.NUnitV2ResultWriter" version="3.6.0" targetFramework="net461" />
>   <package id="NUnit.Extension.TeamCityEventListener" version="1.0.7" targetFramework="net461" />
>   <package id="NUnit.Extension.VSProjectLoader" version="3.8.0" targetFramework="net461" />
> ```

None of these NUnit ones should be here.
___
*[src/BloomExe/packages.config, line 43 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8WFbv2ks3sagyCTqr:-ML8WFbv2ks3sagyCTqs:br5pq3c) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a60b5f1b223c977285b0180fc8eaae27ca612198/src/BloomExe/packages.config#L43)):*
> ```XML
>   <package id="System.IO.FileSystem.Primitives" version="4.3.0" targetFramework="net461" />
>   <package id="System.Memory" version="4.5.4" targetFramework="net461" />
>   <package id="System.Numerics.Vectors" version="4.5.0" targetFramework="net461" />
> ```

Looks like this was in the Windows-specific section, too.
___
*[src/BloomTests/packages.config, line 7 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8W_TWEZlkP5pgx77B:-ML8W_TX1Sf4UX3c_6ll:bdb6iz6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a60b5f1b223c977285b0180fc8eaae27ca612198/src/BloomTests/packages.config#L7)):*
> ```XML
>   <package id="AWSSDK.Core" version="3.5.1.32" targetFramework="net461" />
>   <package id="AWSSDK.S3" version="3.5.3.10" targetFramework="net461" />
>   <package id="Castle.Core" version="4.4.1" targetFramework="net461" />
> ```

It looks like we are not using Castle.Core anymore.
___
*[src/BloomTests/packages.config, line 11 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8Wero6myeyShGPN6r:-ML8Wero6myeyShGPN6s:bytvbpt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a60b5f1b223c977285b0180fc8eaae27ca612198/src/BloomTests/packages.config#L11)):*
> ```XML
>   <package id="Glob" version="1.1.8" targetFramework="net461" />
>   <package id="icu.net" version="2.6.0" targetFramework="net461" />
>   <package id="JsonFx" version="2.0.1209.2802" targetFramework="net461" />
> ```

I'm surprised to see so many additions. Seems wrong. Like we are getting the union of packages needed for all projects.

**Review by JohnThomson — COMMENTED** [review]
I think I've dealt with all the issues. All tests pass on Windows. @stephenmcconnel maybe worth another pass on Linux?

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-:-MLEN02TC1n_6GKF34fR:b-owye64)* status: 12 of 21 files reviewed, 13 unresolved discussions (waiting on @andrew-polk and @StephenMcConnel)

___
*[src/Bloom-ChorusPlugin/BloomChorusPlugin.csproj, line 105 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8Ux6hCL9fD22U7N37:-MLE6ZGdEzhob4-Icorc:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a60b5f1b223c977285b0180fc8eaae27ca612198/src/Bloom-ChorusPlugin/BloomChorusPlugin.csproj#L105)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't think this should be here.
</blockquote></details>

Done.
___
*[src/Bloom-ChorusPlugin/packages.config, line 31 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8U_171w0wxckzQ0qC:-MLE7NmF6xZGVb7oR_wR:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a60b5f1b223c977285b0180fc8eaae27ca612198/src/Bloom-ChorusPlugin/packages.config#L31)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't think we should be adding all these.
</blockquote></details>

Done.
___
*[src/BloomExe/BloomExe.csproj, line 3 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8UzOv1ij33OdEc4ZA:-MLE7XPFASxehRqjGO60:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a60b5f1b223c977285b0180fc8eaae27ca612198/src/BloomExe/BloomExe.csproj#L3)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't think this should be here.
</blockquote></details>

Done.
___
*[src/BloomExe/BloomExe.csproj, line 198 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8Wsl74CK7wYf5IDez:-MLE7YFFCzPntAkjzo_u:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2fd1b252dfc281bd091afaf357cd53af4533f830/src/BloomExe/BloomExe.csproj#L198)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should we have @stephenmcconnel check all the removals before we merge?
</blockquote></details>

Done.
___
*[src/BloomExe/BloomExe.csproj, line 1435 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8VrqOBDcH3q4SWP9p:-MLE83g450_hNGPdxY8o:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a60b5f1b223c977285b0180fc8eaae27ca612198/src/BloomExe/BloomExe.csproj#L1435)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't think this should be here.
</blockquote></details>

Done.
___
*[src/BloomExe/packages.config, line 3 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8VxmP4UZMyewPOE4M:-MLE8_TOALj9paF1ecIx:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2fd1b252dfc281bd091afaf357cd53af4533f830/src/BloomExe/packages.config#L3)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's put this line back.
</blockquote></details>

Done.
___
*[src/BloomExe/packages.config, line 7 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8Vuod8_KcaKbd6EtH:-MLE8zev88K8H1ob_R4J:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a60b5f1b223c977285b0180fc8eaae27ca612198/src/BloomExe/packages.config#L7)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't see why we need to add this.
</blockquote></details>

Done.
___
*[src/BloomExe/packages.config, line 12 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8W23gA5LB2MAAHds_:-MLE9HV_7uLrKiz7HHK3:b-mlpa50) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a60b5f1b223c977285b0180fc8eaae27ca612198/src/BloomExe/packages.config#L12)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This should stay down in the Windows-specific section.
</blockquote></details>

Puzzled by this suggestion. This whole file is Windows-specific, and I don't see a windows-specific section in it.
___
*[src/BloomExe/packages.config, line 22 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8W5tm0oMetDTGwUKz:-MLE9Ad26K9Mt2NT4GMC:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a60b5f1b223c977285b0180fc8eaae27ca612198/src/BloomExe/packages.config#L22)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This shouldn't be here.
</blockquote></details>

Done.
___
*[src/BloomExe/packages.config, line 31 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8W7QT-YNeN2mkhLD4:-MLE94ABAWujVfzR2kB0:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a60b5f1b223c977285b0180fc8eaae27ca612198/src/BloomExe/packages.config#L31)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

None of these NUnit ones should be here.
</blockquote></details>

Done.
___
*[src/BloomExe/packages.config, line 43 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8WFbv2ks3sagyCTqr:-MLEGloM3yaMFwUZFqZT:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a60b5f1b223c977285b0180fc8eaae27ca612198/src/BloomExe/packages.config#L43)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like this was in the Windows-specific section, too.
</blockquote></details>

Done.
___
*[src/BloomTests/packages.config, line 7 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8W_TWEZlkP5pgx77B:-MLEGbVr3z1jPRtP5ay2:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a60b5f1b223c977285b0180fc8eaae27ca612198/src/BloomTests/packages.config#L7)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

It looks like we are not using Castle.Core anymore.
</blockquote></details>

Done.
___
*[src/BloomTests/packages.config, line 11 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-ML8Wero6myeyShGPN6r:-MLEGZPI1638_EuTBiOg:b-7bed1v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a60b5f1b223c977285b0180fc8eaae27ca612198/src/BloomTests/packages.config#L11)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm surprised to see so many additions. Seems wrong. Like we are getting the union of packages needed for all projects.
</blockquote></details>

I think I have cleaned it up.

**Review by JohnThomson — COMMENTED** [review]
Note..many of the stage 2 changes were things Steve worked out for Linux.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-:-MLENAl8ATImggbEYWAJ:b-3ed8z5)* status: 12 of 21 files reviewed, 13 unresolved discussions (waiting on @andrew-polk and @StephenMcConnel)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/BloomExe.csproj, line 150 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-MLEe3sp9B167NwsanaW:-MLEe3sp9B167NwsanaX:b-9esf6x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/89ab07cc6c4ad72087bd8db873854c47ee99a13b/src/BloomExe/BloomExe.csproj#L150)):*
> ```XML
>     <Reference Include="Moq, Version=4.14.0.0, Culture=neutral, PublicKeyToken=69f491c39445e920, processorArchitecture=MSIL">
>       <HintPath>..\..\packages\Moq.4.14.7\lib\net45\Moq.dll</HintPath>
>     </Reference>
> ```

I didn't comment on all these because I thought it would be a duplication to do it here and packages.config, but there are things added here which shouldn't be. Moq and Castle, at least.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/BloomExe.csproj, line 150 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057#-MLEe3sp9B167NwsanaW:-MLF-KIg7dDNZvkrmbvT:b-jhd3mf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/89ab07cc6c4ad72087bd8db873854c47ee99a13b/src/BloomExe/BloomExe.csproj#L150)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I didn't comment on all these because I thought it would be a duplication to do it here and packages.config, but there are things added here which shouldn't be. Moq and Castle, at least.
</blockquote></details>

Sorry. Hopefully I cleared out all the junk now.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4057)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
