### PR TITLE
Fix a race condition displaying and renaming a new book (BL-11524)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5587)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5587)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/Book.cs` line 902 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5587#-NMEd00M0Ppa8KVmy06Z:-NMEd00M0Ppa8KVmy06_:b-8qkb02) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/49fb0a6edff8134d2fd5092073b6634bd3b6ebdd/src/BloomExe/Book/Book.cs#L902)):*
> ```Smalltalk
> 		}
> 
> 		// This is useful when we need to BBUD immediately, but we are about to do another
> ```

Is there some way to fix the problem without this hack? It's kinda shocking.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5587)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/Book.cs` line 921 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5587#-NMFh-Y14bbKfj1Vclz9:-NMFh-Y14bbKfj1VclzA:b-vb1i2b) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2321b6720a2338077b2e3eda6d69d63cdb0b5090/src/BloomExe/Book/Book.cs#L921)):*
> ```Smalltalk
> 		public void BringBookUpToDate(IProgress progress, bool forCopyOfUpToDateBook = false)
> 		{
> 			_hasBeenBroughtUpToDate = true;
> ```

The polarity here seems backwards. It is common in software to have a `dirty` flag, not a `clean` tag.  I think this should be `needsUpdate` or some such.

Beyond convention, there is a semantic problem. If we do an update, and then change a book setting (future) that requires an update, well it is still true that the book was updated. However, we need it updated again, i.e., `needsUpdate = true`.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5587)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[`src/BloomExe/Book/Book.cs` line 902 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5587#-NMEd00M0Ppa8KVmy06Z:-NMFrTE63JiapIk-6Kxf:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/49fb0a6edff8134d2fd5092073b6634bd3b6ebdd/src/BloomExe/Book/Book.cs#L902)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is there some way to fix the problem without this hack? It's kinda shocking.
</blockquote></details>

Done.
___
*[`src/BloomExe/Book/Book.cs` line 921 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5587#-NMFh-Y14bbKfj1Vclz9:-NMFrVm58kSVm8XvT0Nj:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2321b6720a2338077b2e3eda6d69d63cdb0b5090/src/BloomExe/Book/Book.cs#L921)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

The polarity here seems backwards. It is common in software to have a `dirty` flag, not a `clean` tag.  I think this should be `needsUpdate` or some such.

Beyond convention, there is a semantic problem. If we do an update, and then change a book setting (future) that requires an update, well it is still true that the book was updated. However, we need it updated again, i.e., `needsUpdate = true`.

</blockquote></details>

Done.

**Review by hatton — APPROVED** [review]
> Reviewed 6 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5587)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5587)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
