### PR TITLE
Handle more audio files in Audio/Video publishing (BL-11401)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5312)

### CODE REVIEW

**Review by hatton — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5312)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 618 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5312#-N8PttSb0rgU9mbZDguZ:-N8PttSb0rgU9mbZDgu_:bkce4z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e4a078477c734e646fe040a1dd7725aa45c8db6f/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L618)):*
> ```Smalltalk
> 						// This API requires a localization ID, but as we hope no one will ever see it, I'm not actually
> 						// adding it to the XLF.
> 						progress.Message("PublishTab.RecordVideo.TooManyAudioFiles", "This recording has more audio files than Bloom can handle", ProgressKind.Error);
> ```

Could add "Try recording the book in smaller sections. You can then join the sections using some other video software."
___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 644 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5312#-N8Pt-x39-dXLEulTxkW:-N8Pt-x39-dXLEulTxkX:b-jv0sqq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e4a078477c734e646fe040a1dd7725aa45c8db6f/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L644)):*
> ```Smalltalk
> 
> 				// Restore original names, since that's what is expected if we preview the book or record again.
> 				// Review: should we try harder to make sure this happens even if something goes wrong?
> ```

I think, add to comment: "... or record again (the html is still referencing the original names... the renaming was solely for the process of running ffmpeg afterwards).
___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 648 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5312#-N8PtULI79g_ecmdsVhv:-N8PtULJ2gXIf1sFvUR-:bawnr78) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e4a078477c734e646fe040a1dd7725aa45c8db6f/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L648)):*
> ```Smalltalk
> 				// the worst problem if we don't restore them is that a subsequent attempt in the same session to record or
> 				// preview the book will fail to find them.
> 				foreach (var item in soundLog)
> ```

Yeah I do worry that a thousand renames could set off a malware detector and we don't have a way to deal with that?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5312)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 648 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5312#-N8PtULI79g_ecmdsVhv:-N8QVlx0CgJc05422JEg:b-ck1zjq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e4a078477c734e646fe040a1dd7725aa45c8db6f/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L648)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Yeah I do worry that a thousand renames could set off a malware detector and we don't have a way to deal with that?
</blockquote></details>

Sounds like maybe it IS worth the complication of building the command line without renaming, then rename if we must? My concern is, a typical audio file has a guid name, so if we keep the other improvements but don't rename we'll be looking at about 50 characters per file. So we'll only need the rename stuff when there are more than about 650 audio files. That's likely to be rare enough that the relevant path will almost never be tested, so if it breaks it will be some poor user who discovers it.
Or, instead of complicating, we could simplify, accept that we can't make a video with more than 650 audio files in one go, and remove the renaming code altogether.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5312)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 648 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5312#-N8PtULI79g_ecmdsVhv:-N8QXFRfDl_nuA5_pw3r:bayjc0a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e4a078477c734e646fe040a1dd7725aa45c8db6f/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L648)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Sounds like maybe it IS worth the complication of building the command line without renaming, then rename if we must? My concern is, a typical audio file has a guid name, so if we keep the other improvements but don't rename we'll be looking at about 50 characters per file. So we'll only need the rename stuff when there are more than about 650 audio files. That's likely to be rare enough that the relevant path will almost never be tested, so if it breaks it will be some poor user who discovers it.
Or, instead of complicating, we could simplify, accept that we can't make a video with more than 650 audio files in one go, and remove the renaming code altogether.
</blockquote></details>

I was thinking more like, the code could know what state it is in, like original-names, short-names, failed-to-change-all-names. But it's not clear what you do if you're in the failed state other than start over.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5312)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 648 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5312#-N8PtULI79g_ecmdsVhv:-N8QYJnrAcc-6L_3tz31:b9b871i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e4a078477c734e646fe040a1dd7725aa45c8db6f/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L648)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I was thinking more like, the code could know what state it is in, like original-names, short-names, failed-to-change-all-names. But it's not clear what you do if you're in the failed state other than start over.
</blockquote></details>

No, I think you have a point. If we renamed some but not all it should be possible to refresh the book before doing anything that needs it.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5312)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 644 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5312#-N8Pt-x39-dXLEulTxkW:-N8UXDEV6tYeYnXhaS3N:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e4a078477c734e646fe040a1dd7725aa45c8db6f/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L644)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think, add to comment: "... or record again (the html is still referencing the original names... the renaming was solely for the process of running ffmpeg afterwards).
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 648 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5312#-N8PtULI79g_ecmdsVhv:-N8UUNvn9u-ANmEaENGm:bp0vsor) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e4a078477c734e646fe040a1dd7725aa45c8db6f/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L648)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

No, I think you have a point. If we renamed some but not all it should be possible to refresh the book before doing anything that needs it.
</blockquote></details>

I made an attempt at handling it. Difficult to test...

**Review by hatton — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5312)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @hatton and @JohnThomson)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 618 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5312#-N8PttSb0rgU9mbZDguZ:-N8V-tPJ2G0AuOgvESdH:bb7mm0n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e4a078477c734e646fe040a1dd7725aa45c8db6f/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L618)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Could add "Try recording the book in smaller sections. You can then join the sections using some other video software."
</blockquote></details>

ping

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5312)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 618 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5312#-N8PttSb0rgU9mbZDguZ:-N8VMb1ABl2RX7B0uhim:bo5bk73) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e4a078477c734e646fe040a1dd7725aa45c8db6f/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L618)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

ping
</blockquote></details>

Done. (I cycled through every message Reviewable told me needed a reply...no idea why it skipped this. Sorry.)

**Pull request merged**
