### PR TITLE
Prevent a spurious overflow caused by paragraph mark (BL-11606)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5549)

### CODE REVIEW

**Review by jsubloom — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5549#-:-NHPzSpXCAUd__bkWdMQ:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 478 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5549#-NHPyy-l2Yt2m_I7g_AU:-NHPyy-l2Yt2m_I7g_AV:b4pphna) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7547129ed8fcaea084c627e85b1b483dd02f14b5/src/BloomBrowserUI/bookEdit/css/editMode.less#L478)):*
> ```Less
>         // This can actually add to the scrollHeight of the containing bloom-editable, resulting in Bloom concluding that it
>         // is overflowing. But if we hide any overflow of the :after, this doesn't happen.
>         // What is more surprising is that it actually seems to improve the alignment of the paragraph mark with the text.
> ```

Hmm... very surprising indeed. I thought changing overflow from visible to hidden wouldn't affect the positioning at all!
___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 480 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5549#-NHPz8jx6anNbQd2U-1H:-NHPz8jx6anNbQd2U-1I:b-wxkbia) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7547129ed8fcaea084c627e85b1b483dd02f14b5/src/BloomBrowserUI/bookEdit/css/editMode.less#L480)):*
> ```Less
>         // What is more surprising is that it actually seems to improve the alignment of the paragraph mark with the text.
>         // I haven't figured out why this is. See some of the later comments in BL-11606.
>         overflow: hidden;
> ```

The downside of this is if it ever actually goes below, it would be clipped off.  But I can see living with that, and in to the user that's probably less of a bad experience than the current one.

**Review by jsubloom — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5549)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by jsubloom — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5549#-:-NHPzXmm5VIMP-RSVSkI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5549)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 478 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5549#-NHPyy-l2Yt2m_I7g_AU:-NHV8Hrv4CPDBDxqm8bR:bt0x67k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7547129ed8fcaea084c627e85b1b483dd02f14b5/src/BloomBrowserUI/bookEdit/css/editMode.less#L478)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Hmm... very surprising indeed. I thought changing overflow from visible to hidden wouldn't affect the positioning at all!
</blockquote></details>

It's just possible that I was accidentally comparing, not with-and-without overflow:hidden, but overflow:hidden with some previous attempts to fix things by giving :after some padding or margin. In some cases this definitely moved it up too much.
___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 480 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5549#-NHPz8jx6anNbQd2U-1H:-NHV8iIaClUl8_3x7Qge:bb5nin4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7547129ed8fcaea084c627e85b1b483dd02f14b5/src/BloomBrowserUI/bookEdit/css/editMode.less#L480)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

The downside of this is if it ever actually goes below, it would be clipped off.  But I can see living with that, and in to the user that's probably less of a bad experience than the current one.
</blockquote></details>

Anyone changing a paragraph mark :after to something with a descender should test carefully! And if the user sets line height so small that text without descenders is clipped I think this will be the least of their problems. This isn't even something that appears in the final output, it's just there to possibly help understand what's going on while editing.

**Pull request merged**
