### PR TITLE
BL-5870 Edit video outside Bloom

### PR DESCRIPTION
**Pull request by JohnThomson**
(Also adds Restore Original command.)

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2432)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 88 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2432#-LDDGXHPA9J2MLJyB-yE:-LDDGXHQ-pJ63K4XRYAB:b-qz7xwc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c230a415cdaaf2d673d8497f4e9ebb955d4cc11b/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L88)):*
> Toolbox.SignLanguage.EditOutside

Needed in .xlf file

---

*[src/BloomExe/Edit/EditingModel.cs, line 1475 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2432#-LDDKAS4BK3zXdRIY4GT:-LDDKAS4BK3zXdRIY4GU:b-ihaaem) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c230a415cdaaf2d673d8497f4e9ebb955d4cc11b/src/BloomExe/Edit/EditingModel.cs#L1475)):*
> ```
> Toolbox.SignLanguage.MissingVideo
> ```
Needed in .xlf file

---

*[src/BloomExe/Edit/EditingModel.cs, line 1503 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2432#-LDDKcJs19hmIJEYVFbJ:-LDDKcJs19hmIJEYVFbK:b-yxxiha) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c230a415cdaaf2d673d8497f4e9ebb955d4cc11b/src/BloomExe/Edit/EditingModel.cs#L1503)):*
> ```
> File.Exists
> ```
It doesn't provide different code, but it is better to use RobustFile.Exists as RobustFile was intended to be a wholesale replacement. Same with several other changes in this PR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2432)*

**Comment by JohnThomson** [comment]
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 88 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2432#-LDDGXHPA9J2MLJyB-yE:-LDDPH5MBjSGGvKL4NYU:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c230a415cdaaf2d673d8497f4e9ebb955d4cc11b/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L88)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> Toolbox.SignLanguage.EditOutside

Needed in .xlf file
</blockquote></details>

Done.

---

*[src/BloomExe/Edit/EditingModel.cs, line 1475 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2432#-LDDKAS4BK3zXdRIY4GT:-LDDP_pq6gl4mfSnSJN6:b-fipc9s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c230a415cdaaf2d673d8497f4e9ebb955d4cc11b/src/BloomExe/Edit/EditingModel.cs#L1475)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Toolbox.SignLanguage.MissingVideo
> ```
Needed in .xlf file
</blockquote></details>

I decided to take it out instead. Since creating this I've improved the button enabling code, and it should simply be disabled if there is no video file.

---

*[src/BloomExe/Edit/EditingModel.cs, line 1503 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2432#-LDDKcJs19hmIJEYVFbJ:-LDDQSwN4yTPhFgWatUA:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c230a415cdaaf2d673d8497f4e9ebb955d4cc11b/src/BloomExe/Edit/EditingModel.cs#L1503)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> File.Exists
> ```
It doesn't provide different code, but it is better to use RobustFile.Exists as RobustFile was intended to be a wholesale replacement. Same with several other changes in this PR.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2432)*

**Comment by andrew-polk** [comment]
:lgtm:
Does this need UI Review?

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2432#-:-LDDbXhW3Nkpm3m4g0UA:b6vj6up)*

**Comment by gmartin7** [comment]
:lgtm:

---

Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2432#-:-LDDouwv351yI_T6diH6:bnfp4nl)*

**Pull request merged**
