### PR TITLE
Clear required xmatter when leaving that branding (BL-11290)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5216)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5216)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/XMatterPackFinder.cs` line 55 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5216#-N4DcHEvAhgSF400UlQs:-N4DcHEvAhgSF400UlQt:bao6o2b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b151326bb652d04433609fce6a23cd030230692e/src/BloomExe/Book/XMatterPackFinder.cs#L55)):*
> ```Smalltalk
> 		}
> 
> 		public string GetValidXmatter(string selectKey, string proposedXmatter)
> ```

Is it accurate to rename `selectKey` to `xmatterKeyFromBranding` both here and in `GetXmattersToOfferInSettings`?
I was pretty confused by the name.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5216)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/Book/XMatterPackFinder.cs` line 55 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5216#-N4DcHEvAhgSF400UlQs:-N4Dg4Bx3w-jIUuNJ6sB:bq9y1eu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b151326bb652d04433609fce6a23cd030230692e/src/BloomExe/Book/XMatterPackFinder.cs#L55)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is it accurate to rename `selectKey` to `xmatterKeyFromBranding` both here and in `GetXmattersToOfferInSettings`?
I was pretty confused by the name.
</blockquote></details>

I like xmatterKeyForcedByBranding even better. Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5216)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by gmartin7 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5216)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
