### PR TITLE
Handle audio spans better during pasting (BL-9221)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 244 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088#-MMaeQ8B4URkuI2A-PK6:-MMaeQ8CE5DrMDoaBZMu:b-elm3f5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/424ea2e45bf78dcd529463f4ebe5577a7b2025dd/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L244)):*
> ```XML
>         }
>         // The regex didn't match, but we may have .bloom-highlightSegment markup to remove.
>         return this.removeAudioSpanMarkupDuringPasting(inputText);
> ```

I'm missing something.
You say the regex didn't match, and I agree that's the only way to get here.
But then the first thing we do in `removeAudioSpanMarkupDuringPasting` is call `removeMatchingAudioSpan` using the same regex we just failed to match with.
___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 292 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088#-MMagDdD5dPvrnTJe7AT:-MMagDdD5dPvrnTJe7AU:bi8lrtq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/424ea2e45bf78dcd529463f4ebe5577a7b2025dd/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L292)):*
> ```XML
>         }
>         return inputText;
>     }
> ```

I'm wondering if it wouldn't greatly simplify all this code to get rid of the regexes and just use dom functions.
Things like span.hasClass("audio-sentence"), span.removeAttr("id"), etc.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088)* status: 0 of 2 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088#-MNOvhaH1SqpOOT-4jij:-MNOvhaH1SqpOOT-4jik:b-56irdd) (no related file):*
Reviewable isn't showing me Andrew's comments, so it's rather hard to respond to them.  But here's my replies:
1) I admit it may not be maximally efficient to call a method that repeats a failing regex match, but I thought the code would be clearer to use a common method for removing all audio span markup when there's nothing we can fix, but there still may be something to remove.
2) We're in a context where we have string data to deal with, not a DOM.  I suppose we could try to get the string in and out of a DOM, but that would add complexity itself, and I'm comfortable with the regex solution.

---

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088)* status: all files reviewed, 4 unresolved discussions (waiting on @StephenMcConnel)

*[a discussion](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088#-MNOvhaH1SqpOOT-4jij:-MNUA9EP9EuKRzCAgWaB:b-suq6gg) (no related file):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Reviewable isn't showing me Andrew's comments, so it's rather hard to respond to them.  But here's my replies:
1) I admit it may not be maximally efficient to call a method that repeats a failing regex match, but I thought the code would be clearer to use a common method for removing all audio span markup when there's nothing we can fix, but there still may be something to remove.
2) We're in a context where we have string data to deal with, not a DOM.  I suppose we could try to get the string in and out of a DOM, but that would add complexity itself, and I'm comfortable with the regex solution.
</blockquote></details>

Regarding #1, i'm ok with living with the duplicate call until the point we see really noticeable/bad perf impact from doing it twice.

---
___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 204 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088#-MNU8tF80yB8bgq--jQ-:-MNU8tF80yB8bgq--jQ0:b-70c833) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/424ea2e45bf78dcd529463f4ebe5577a7b2025dd/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L204)):*
> ```XML
>     }
> 
>     private static audioSentenceRegex =
> ```

I agree with Andrew's concern about using regex's versus DOM functions. I think regex's will be trickier to keep right / read / maintain in the future. I would also vote for DOM functions.

For the getting it in part, looks like you can do this: https://www.w3docs.com/snippets/javascript/how-to-create-a-new-dom-element-from-html-string.html
Out should be easy, just calling outerHtml on something.
Moving the contents of the span into its parent may require a little more DOM trickery but is also very doable.
___
*[src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts, line 169 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088#-MNU5cDbEZblZbmqBw-0:-MNU5cDbEZblZbmqBw-1:b-vhfgkn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/424ea2e45bf78dcd529463f4ebe5577a7b2025dd/src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts#L169)):*
> ```XML
> 
>     it("removeAudioSpanMarkupDuringPasting removes both .audio-sentence and .bloom-highlightSegment span markup", () => {
>         const input1 = '<p><span class="bold">This is a test!</span></p>';
> ```

These various inputs are great, but each of these inputs should get its own it() with a custom/correct name for it.
___
*[src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts, line 206 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088#-MNU5Q5B2t1wgIWO1icK:-MNU5Q5B2t1wgIWO1icL:b-i1fsn9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/424ea2e45bf78dcd529463f4ebe5577a7b2025dd/src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts#L206)):*
> ```XML
>         expect(result6).toBe(input6); // look closely at the input.  :-)
> 
>         const input7 =
> ```

Is this a duplicate of line 161?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 204 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088#-MNU8tF80yB8bgq--jQ-:-MNVggQl2-L544-vSm0l:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/424ea2e45bf78dcd529463f4ebe5577a7b2025dd/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L204)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I agree with Andrew's concern about using regex's versus DOM functions. I think regex's will be trickier to keep right / read / maintain in the future. I would also vote for DOM functions.

For the getting it in part, looks like you can do this: https://www.w3docs.com/snippets/javascript/how-to-create-a-new-dom-element-from-html-string.html
Out should be easy, just calling outerHtml on something.
Moving the contents of the span into its parent may require a little more DOM trickery but is also very doable.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts, line 169 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088#-MNU5cDbEZblZbmqBw-0:-MNVAUQ71RwV-DOhZs2w:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/424ea2e45bf78dcd529463f4ebe5577a7b2025dd/src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts#L169)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

These various inputs are great, but each of these inputs should get its own it() with a custom/correct name for it.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts, line 206 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088#-MNU5Q5B2t1wgIWO1icK:-MNVAJMC87ZPrz1GDcQd:b9ftxeu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/424ea2e45bf78dcd529463f4ebe5577a7b2025dd/src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts#L206)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Is this a duplicate of line 161?
</blockquote></details>

The data may be duplicated, but it's testing another path through the code.

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088)* status: all files reviewed, 4 unresolved discussions (waiting on @StephenMcConnel and @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 224 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088#-MNZOKvsBQ5OR56yMmg9:-MNZOKvt4p5_QV0az87w:b-tgoat4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c34e05ce5699128b45c97ff3c6f4d52cee0dec93/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L224)):*
> ```XML
>                 }
>             );
>             return temp.innerHTML;
> ```

I think here or slightly below, you can mention in a comment that it ought to be a safe assumption that audio-sentence and highlightSegment are mutually exclusive.
___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 234 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088#-MNZN2P68RkE-MU1bnm6:-MNZN2P68RkE-MU1bnm7:b-dsz7lp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c34e05ce5699128b45c97ff3c6f4d52cee0dec93/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L234)):*
> ```XML
> 
>     private static removeMatchingAudioSpanMarkup(
>         inputText: string,
> ```

Was thinking that this would be better off as inputHtml? (The same could apply to copyAudioFilesWithNewIdsDuringPasting).
___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 260 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088#-MNZNy2Q7hcQDqce-5PM:-MNZNy2Q7hcQDqce-5PN:b-mtrywi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c34e05ce5699128b45c97ff3c6f4d52cee0dec93/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L260)):*
> ```
> "span.audio-sentence"
> ```
Would it work if you did a single combined selector instead of two calls to removeMatchingAudioSpanMarkup?
I was thinking the selector would be "span.audio-sentence, span.bloom-highlightSegment".
Does that work?
___
*[src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts, line 206 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088#-MNU5Q5B2t1wgIWO1icK:-MNZPTftEhz9eNKFExdK:b3mqwd7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/424ea2e45bf78dcd529463f4ebe5577a7b2025dd/src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts#L206)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

The data may be duplicated, but it's testing another path through the code.
</blockquote></details>

Oh ok, I see the difference now. Thanks.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088)* status: all files reviewed, 4 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 224 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088#-MNZOKvsBQ5OR56yMmg9:-MN_EJ9lD9wCZVMip2yH:b-owszuf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c34e05ce5699128b45c97ff3c6f4d52cee0dec93/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L224)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I think here or slightly below, you can mention in a comment that it ought to be a safe assumption that audio-sentence and highlightSegment are mutually exclusive.
</blockquote></details>

I added to the comment at the beginning of the method to make this clear.
___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 234 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088#-MNZN2P68RkE-MU1bnm6:-MN_IYLP7fAHkwBJoCx-:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c34e05ce5699128b45c97ff3c6f4d52cee0dec93/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L234)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Was thinking that this would be better off as inputHtml? (The same could apply to copyAudioFilesWithNewIdsDuringPasting).
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 260 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088#-MNZNy2Q7hcQDqce-5PM:-MN_I_cA7hK1NOH_GiCF:b-1v97r1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c34e05ce5699128b45c97ff3c6f4d52cee0dec93/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L260)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> "span.audio-sentence"
> ```
Would it work if you did a single combined selector instead of two calls to removeMatchingAudioSpanMarkup?
I was thinking the selector would be "span.audio-sentence, span.bloom-highlightSegment".
Does that work?
</blockquote></details>

Done.  (yes)

**Review by sujeffreyl — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
