### PR TITLE
Prevent redundant calls to BringBookUpToDate for previews (BL-10227)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4616)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
This makes me nervous. It's a good thing if it works. But quite a bit of stuff changes the DOM. One that comes to mind is that one of the publishing paths (epub?) allows us to choose a different cover color. I suppose that gets saved and would trigger DoPostSaveTasks()? I suppose this is the right time to do it, when we've already made a big destabilizing change and need to test everything...
Please check that this doesn't break any unit tests, and consider whether any tests SHOULD be changed or added. (I can't immediately think of any, but it should be considered.)
Other than that nervousness, I only have one concrete suggestion (see below). Otherwise, LGTM.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4616#-:-MfcD7-g4AGdI-x5pBN3:b-9nbqmm)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/Book/Book.cs, line 741 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4616#-MfcCgLHEJt6Y5dTzByn:-MfcCgLHEJt6Y5dTzByo:b-ag8ocy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b30c2e9481d827b845c68ffff80f28c1daec7fc8/src/BloomExe/Book/Book.cs#L741)):*
> ```Smalltalk
> 
> 			// this is normally the vernacular, but when we're previewing a shell, well it won't have anything for the vernacular
> 			var primaryLanguage = Language1IsoCode;
> ```

Can anything change the languages here in a way that would require clearing the cache?
___
*[src/BloomExe/Book/Book.cs, line 2906 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4616#-MfcBpRh3_X3xkifzrPz:-MfcBpRh3_X3xkifzrQ-:b-eidvvd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b30c2e9481d827b845c68ffff80f28c1daec7fc8/src/BloomExe/Book/Book.cs#L2906)):*
> ```Smalltalk
> 		}
> 
> 		private void ClearPagesCache()
> ```

This is now doing more than clear the pages cache so it probably deserves a new name. ClearAllDomCaches? ClearCachedDataFromDom?

**Review by JohnThomson — COMMENTED** [review]
Another thing I wanted to research in connection with this issue: We recently changed to not SHOWING the  new ReactCollectionTab. However, I'm suspicious that we're still CREATING it and possibly updating it. There may be more potential to improve things (at least performance) if that's true and can be stopped.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4616#-:-MfcFUNUB5No7MOVR08R:b-nn8hl7)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
All of the unit tests pass.  (well, except for the 3 that always fail on my Linux box)
Changing the cover color for BloomPub in the publish tab changes the preview.  Changing the book languages in the edit pane changes the preview.  I suspect that almost any change (including metadata changes in ePUB) eventually results in DoPostSaveTasks being called.
I've done more to prevent creating the ReactCollectionTab.  The  ReactCollectionTab code still compiles, as far as I know, providing at least some measure of keeping up with code changes elsewhere.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4616#-:-MfdmN3y0lZ4cG2OrtnH:b-pi2g8d)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Book/Book.cs, line 741 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4616#-MfcCgLHEJt6Y5dTzByn:-MfdqdryC2e1XyccJl2N:btq2i0j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b30c2e9481d827b845c68ffff80f28c1daec7fc8/src/BloomExe/Book/Book.cs#L741)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Can anything change the languages here in a way that would require clearing the cache?
</blockquote></details>

The cache has already been cleared to get to this point in the code.  This is the middle of the method that creates _previewDom.
___
*[src/BloomExe/Book/Book.cs, line 2906 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4616#-MfcBpRh3_X3xkifzrPz:-MfdC-_JBz2jgep0qDk2:bml0xht) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b30c2e9481d827b845c68ffff80f28c1daec7fc8/src/BloomExe/Book/Book.cs#L2906)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This is now doing more than clear the pages cache so it probably deserves a new name. ClearAllDomCaches? ClearCachedDataFromDom?
</blockquote></details>

Done. renamed to ClearCachedDataFromDom

**Review by JohnThomson — APPROVED** [review]
Thanks for that. LGTM

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4616#-:-MfhICSQA1jP3BX0eL4_:b-y451oq)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

___
*[src/BloomExe/Book/Book.cs, line 741 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4616#-MfcCgLHEJt6Y5dTzByn:-MfhHg625qp2F8rsejEq:blhzpsa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b30c2e9481d827b845c68ffff80f28c1daec7fc8/src/BloomExe/Book/Book.cs#L741)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

The cache has already been cleared to get to this point in the code.  This is the middle of the method that creates _previewDom.
</blockquote></details>

Yes, I realize that. My point was that the outcome of making a new preview depends on these language choices, therefore, if they change, something must clear the cache so this gets called again. But from other comments it seems you've checked for that.

**Pull request merged**
