### PR TITLE
Support draggable videos as well as pictures

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6581)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6581)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/js/bloomVideo.ts` line 23 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6581#-O2jw15Q5zv4urbrNFbn:-O2jw15Q5zv4urbrNFbo:b729fhg) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8dfc7b3a75fc25681825a881c79628e1b8e4f479/src/BloomBrowserUI/bookEdit/js/bloomVideo.ts#L23)):*
> ```XML
>     if (target.tagName.toLowerCase() === "video") {
>         // If it's a draggable bloom game video in play mode, we don't want controls
>         // I'm not pleased that bloomVideo knows about Games, but it's also not great
> ```

What do you think of a new class or attribute which means this video should have no controls?

Then you're not leaking anything about games here. The games code creates video elements with class .no-controls (.bloom-no-controls?) and this code just removes controls in that case.

**Comment by andrew-polk** [comment]
Making draft until we reconcile with #6588

**Review by JohnThomson — COMMENTED** [review]
I think you figured out that they were identical, so we can proceed with this one you've reviewed.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6581#-:-O3dT-RYCGq8Wqnjgu5o:b-uonjay)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/js/bloomVideo.ts` line 23 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6581#-O2jw15Q5zv4urbrNFbn:-O3dSsbGA2gHzwwFDGu9:b2ymubs) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8dfc7b3a75fc25681825a881c79628e1b8e4f479/src/BloomBrowserUI/bookEdit/js/bloomVideo.ts#L23)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What do you think of a new class or attribute which means this video should have no controls?

Then you're not leaking anything about games here. The games code creates video elements with class .no-controls (.bloom-no-controls?) and this code just removes controls in that case.
</blockquote></details>

I gave it a bloom-ui class to help ensure it doesn't get saved. But I like the idea.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6581)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
