### PR TITLE
BL-13341 fix book button menu logic - "Duplicate" showing

### PR DESCRIPTION
**Pull request by nabalone**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6486)

### CODE REVIEW

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6486)* status: 0 of 2 files reviewed, 3 unresolved discussions

___
*[`src/BloomBrowserUI/collectionsTab/BookButton.tsx` line 211 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6486#-Nxm83h4135JLEMDzDaO:-Nxm83h4135JLEMDzDaP:bk929e7) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/960a8af8e9ad9e654c89bfcc4ec00886bfe9ebe6/src/BloomBrowserUI/collectionsTab/BookButton.tsx#L211)):*
> ```XML
>                 command: "collections/duplicateBook",
>                 shouldShow: () => 
>                     props.collection.isEditableCollection &&
> ```

This is the fix of the bug
___
*[`src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx` line 645 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6486#-Nxm8CIG2mRokhFBr3bZ:-Nxm8CIG2mRokhFBr3b_:bgv2e68) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/518fcdb38b4e6796f7a0f039c0dd622c13cca218/src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx#L645)):*
> ```XML
>             if (
>                 (spec.shouldShow && !spec.shouldShow()) ||
>                 (!spec.shouldShow && !isEditableCollection)
> ```

I found this logic difficult to parse and the behavior is very unexpected if you have not seen the logic or comments, which was the source of the bug in the first place. So I'm proposing that menu items always show up by default and shouldShow overrides that behavior. I think this makes the code much more readable. I had also played with making shouldShow required but then we would need a bunch of `shouldShow: () => true`. 

However, I'm concerned that people might be used to and remember the old shouldShow behavior and not notice this change. Would it help to rename it, e.g. to `show`? Or should I flip the logic and make it a `dontShow` parameter? Other ideas?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6486)* status: all files reviewed, 4 unresolved discussions (waiting on @nabalone)

___
*[`src/BloomBrowserUI/collectionsTab/BookButton.tsx` line 148 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6486#-Nxm7sK84monbLJosdd9:-NxmMEC_Ehk3m-46atTR:b-t0bor3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/960a8af8e9ad9e654c89bfcc4ec00886bfe9ebe6/src/BloomBrowserUI/collectionsTab/BookButton.tsx#L148)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

How do we as a team feel about trailing commas?
</blockquote></details>

I think prettier is opinionated about that. So we just let it decide.
___
*[`src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx` line 280 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6486#-NxmoNdK1nGdVSFQAeur:-NxmoNdK1nGdVSFQAeus:b-ntjur5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/960a8af8e9ad9e654c89bfcc4ec00886bfe9ebe6/src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx#L280)):*
> ```XML
>             label: "Troubleshooting",
>             l10nId: "CollectionTab.ContextMenu.Troubleshooting",
>             shouldShow: () => true, // show for all collections (except factory)
> ```

As we discussed, we can delete this shouldShow line.
___
*[`src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx` line 645 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6486#-Nxm8CIG2mRokhFBr3bZ:-NxmodelBIdaV6aFvRux:bpicatd) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/518fcdb38b4e6796f7a0f039c0dd622c13cca218/src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx#L645)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

I found this logic difficult to parse and the behavior is very unexpected if you have not seen the logic or comments, which was the source of the bug in the first place. So I'm proposing that menu items always show up by default and shouldShow overrides that behavior. I think this makes the code much more readable. I had also played with making shouldShow required but then we would need a bunch of `shouldShow: () => true`. 

However, I'm concerned that people might be used to and remember the old shouldShow behavior and not notice this change. Would it help to rename it, e.g. to `show`? Or should I flip the logic and make it a `dontShow` parameter? Other ideas?
</blockquote></details>

We agreed to reverse the logic since a default of dontShow (is hide better?): false seems more natural than shouldShow:true.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6486)* status: all files reviewed, 4 unresolved discussions (waiting on @nabalone)

___
*[`src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx` line 645 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6486#-Nxm8CIG2mRokhFBr3bZ:-Nxmp5DG1JR7Zgz661cB:b6im1bj) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/518fcdb38b4e6796f7a0f039c0dd622c13cca218/src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx#L645)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We agreed to reverse the logic since a default of dontShow (is hide better?): false seems more natural than shouldShow:true.
</blockquote></details>

I'm thinking `hide` is better than `dontShow`

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6486)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx` line 280 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6486#-NxmoNdK1nGdVSFQAeur:-Nxn1zTX8f8AIPedn-Dm:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/960a8af8e9ad9e654c89bfcc4ec00886bfe9ebe6/src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx#L280)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

As we discussed, we can delete this shouldShow line.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx` line 645 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6486#-Nxm8CIG2mRokhFBr3bZ:-NxnGiipAV0gacPEhB0p:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/518fcdb38b4e6796f7a0f039c0dd622c13cca218/src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx#L645)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm thinking `hide` is better than `dontShow`
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6486)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
