### PR TITLE
BL-11367 More Simple Dom Choice Activity work

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5289)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5289)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[`src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx` line 139 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5289#-N6iN-qG0Dwab1JPZ4gX:-N6iN-qG0Dwab1JPZ4gY:b-tvc38f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4b5e8f8e73ca3f3bfaa3c7f87cd89d8aec84556d/src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx#L139)):*
> ```XML
>                             "bloom-player/dist/bloomplayer.htm?centerVertically=true&url=" +
>                             encodeURIComponent(bookUrl) + // Need to apply encoding to the bookUrl again as data to use it as a parameter of another URL
>                             //nocommit "&independent=false" + // you can temporarily comment this out to send BloomPlayer analytics from Bloom Editor
> ```

The `nocommit` hook thing must not be working.



_Code quote:_
```XML
//nocommit
```
___
*[`src/BloomExe/Book/BookInfo.cs` line 1338 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5289#-N6iS7lI-NKrBO-S8ybE:-N6iS7lI-NKrBO-S8ybF:b-kgfuwl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4b5e8f8e73ca3f3bfaa3c7f87cd89d8aec84556d/src/BloomExe/Book/BookInfo.cs#L1338)):*
> ```Smalltalk
> 				Feature_Quiz = value.Contains("quiz");
> 				Feature_Widget = value.Contains("widget");
> 				Feature_SimpleDomChoice = value.Contains("multiple-choice");
> ```

`simple-dom-choice`?



_Code quote:_
```Smalltalk
multiple-choice
```
___
*[`src/content/templates/template books/Activity/simple-dom-choice-activities.pug` line 14 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5289#-N6iTLSP8epC3Iqoaqu-:-N6iTLSQB6rRbHG3aveM:b-38nv84) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4b5e8f8e73ca3f3bfaa3c7f87cd89d8aec84556d/src/content/templates/template%20books/Activity/simple-dom-choice-activities.pug#L14)):*
> ```Pug
> 
> mixin correctAnswerBubble
> 	label.bubble Put the correct answer here. Bloom will shuffle the buttons each time the book is read.
> ```

We're ignoring i18n for now, right?

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5289)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx` line 139 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5289#-N6iN-qG0Dwab1JPZ4gX:-N6iwTo4CT21iqrMG_qT:bao7c9y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4b5e8f8e73ca3f3bfaa3c7f87cd89d8aec84556d/src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx#L139)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The `nocommit` hook thing must not be working.
</blockquote></details>

yeah we don't actually have that, and I don't know how to do it.
___
*[`src/BloomExe/Book/BookInfo.cs` line 1338 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5289#-N6iS7lI-NKrBO-S8ybE:-N6iwhA03K9rlB6nybOV:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4b5e8f8e73ca3f3bfaa3c7f87cd89d8aec84556d/src/BloomExe/Book/BookInfo.cs#L1338)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

`simple-dom-choice`?
</blockquote></details>

Done.
___
*[`src/content/templates/template books/Activity/simple-dom-choice-activities.pug` line 14 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5289#-N6iTLSP8epC3Iqoaqu-:-N6ix6BP3zz2KnZPBFZo:btdx8l6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4b5e8f8e73ca3f3bfaa3c7f87cd89d8aec84556d/src/content/templates/template%20books/Activity/simple-dom-choice-activities.pug#L14)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We're ignoring i18n for now, right?
</blockquote></details>

What's the next step for to make is localizable?

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5289)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5289)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomExe/Book/BookInfo.cs` line 1338 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5289#-N6iS7lI-NKrBO-S8ybE:-N729m7Z3ZnpGaSG1sO_:b-sx3gnh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4b5e8f8e73ca3f3bfaa3c7f87cd89d8aec84556d/src/BloomExe/Book/BookInfo.cs#L1338)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm not seeing that change.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5289)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Book/BookInfo.cs` line 1338 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5289#-N6iS7lI-NKrBO-S8ybE:-N72YGbA4o9a4Q1VMRaV:b-wuej7j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4b5e8f8e73ca3f3bfaa3c7f87cd89d8aec84556d/src/BloomExe/Book/BookInfo.cs#L1338)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not seeing that change.
</blockquote></details>

Yikes. Lost it somehow.
___
*[`src/content/templates/template books/Activity/simple-dom-choice-activities.pug` line 14 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5289#-N6iTLSP8epC3Iqoaqu-:-N72XSnb8w5QgJh_K2Hb:b-jbd3oy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4b5e8f8e73ca3f3bfaa3c7f87cd89d8aec84556d/src/content/templates/template%20books/Activity/simple-dom-choice-activities.pug#L14)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think you just add the `data-i18n` attribute (and add it to the .xlf file).
</blockquote></details>

Turns out that Bloom doesn't support data-i18n in this context. I added it anyways an made a new card to support it, BL-11385.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5289)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx` line 139 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5289#-N6iN-qG0Dwab1JPZ4gX:-N729bMlBJ5eDmnu4VwC:b-h8l70r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4b5e8f8e73ca3f3bfaa3c7f87cd89d8aec84556d/src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx#L139)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

yeah we don't actually have that, and I don't know how to do it.
</blockquote></details>

I think uncommenting this is the only thing left. Then LGTM

**Pull request merged**
