### PR TITLE
[5.2] BL-11135 Fix Collection Settings error saving page

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5160)

### CODE REVIEW

**Review by gmartin7 — COMMENTED** [review]
This removes a 7yr old fix for BL-912 that is no longer needed.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5160#-:-N2ScEnfAFvXvsAvEjvY:bju2vcj)* status: 0 of 1 files reviewed, all discussions resolved

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5160)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomExe/Collection/CollectionSettingsDialog.cs` line 391 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5160#-N2SfHNB2_4tUX61aJT4:-N2SfHNB2_4tUX61aJT5:bpip4d0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b6bb0821c638d057b5de37884caaf22f55f75ec9/src/BloomExe/Collection/CollectionSettingsDialog.cs#L391)):*
> ```Smalltalk
> 			// tab and other tabs' work gets saved before switching tabs.
> 			// Let's not try to save some last edited page again here and possible cause an error.
> 			// We're primarily here to edit CollectionSettings and those changes were just saved above.
> ```

I'm skeptical that this comment will be useful in the future.
A comment on code which isn't there tends to be confusing because it seems to refer to the code which is there.

My preference would be to just get rid of it (a modification of it would have made a useful review comment if you hadn't put it in code).

Other, imo, less favorable options:
- Leave the comment with commented code.
- Make sure the comment is sufficiently set apart from the code using empty lines.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5160)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/Collection/CollectionSettingsDialog.cs` line 391 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5160#-N2SfHNB2_4tUX61aJT4:-N2StGcmBgzESFJfSCFK:blmcj36) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b6bb0821c638d057b5de37884caaf22f55f75ec9/src/BloomExe/Collection/CollectionSettingsDialog.cs#L391)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm skeptical that this comment will be useful in the future.
A comment on code which isn't there tends to be confusing because it seems to refer to the code which is there.

My preference would be to just get rid of it (a modification of it would have made a useful review comment if you hadn't put it in code).

Other, imo, less favorable options:
- Leave the comment with commented code.
- Make sure the comment is sufficiently set apart from the code using empty lines.
</blockquote></details>

Yeah, I should have just deleted it. Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5160)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
