### PR TITLE
Add unit tests to TeamCollectionApi (BL-9500)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417)* status: 0 of 14 files reviewed, 8 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomTests/DataBuilders/TCBookBuilder.cs, line 67 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZZ_Xxo1G9UuWhBchb2:-MZZ_Xxo1G9UuWhBchb3:b8nqng1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7df8ae7cd828989b2aac09b636a50d225cb12d31/src/BloomTests/DataBuilders/TCBookBuilder.cs#L67)):*
> ```Smalltalk
> 		/// Provides reasonable default values for an HtmlErrorReporter that would be used in unit tests
> 		/// </summary>
> 		public TCBookBuilder WithTestValues()
> ```

Why is this method 'with' and all the others 'set'? See longer comment below.
___
*[src/BloomTests/DataBuilders/TeamCollectionApiBuilder.cs, line 38 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZZa2xL3oUHxbH2_E65:-MZZa2xL3oUHxbH2_E66:b-kro1p3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7df8ae7cd828989b2aac09b636a50d225cb12d31/src/BloomTests/DataBuilders/TeamCollectionApiBuilder.cs#L38)):*
> ```Smalltalk
> 		/// </summary>
> 		/// <returns>Returns a TeamCollectionApi object that you can use</returns>
> 		public TeamCollectionApi Build()
> ```

May be overkill for the current task, but it would be even more useful if it would fill in reasonable defaults (possibly mocks?) for anything it needs that has not been specified. Ideally that would involve Builders for each of those classes, with their own defaults, but that's really exploding the scope of the project. Still, if you already have code to create those objects, consider whether any of it would be usefully moved here as a default.
___
*[src/BloomTests/DataBuilders/TeamCollectionApiBuilder.cs, line 45 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZZ_dd29HyPLVd00aBs:-MZZ_dd29HyPLVd00aBt:b-g9n9th) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7df8ae7cd828989b2aac09b636a50d225cb12d31/src/BloomTests/DataBuilders/TeamCollectionApiBuilder.cs#L45)):*
> ```Smalltalk
> 
> 		#region Basic Setters
> 		public TeamCollectionApiBuilder WithCollectionSettings(CollectionSettings collectionSettings)
> ```

Why are several of these WithX rather than SetX (like the methods on TCBookBuildier)? It would probably be better to settle on whatever convention is in the pattern. My intuition is that 'WithX' is expected to return a new instance (usually of an immutable object) with one property changed and the others cloned, while SetX modifies the object and returns it, but that may not be standard for the Builder pattern you are following.
___
*[src/BloomTests/TeamCollection/TeamCollectionApiTests.cs, line 168 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZZbism6f1WeJKAtZk1:-MZZbism6f1WeJKAtZk2:b-vzn3c7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7df8ae7cd828989b2aac09b636a50d225cb12d31/src/BloomTests/TeamCollection/TeamCollectionApiTests.cs#L168)):*
> ```Smalltalk
> 			Assert.Throws(typeof(System.Net.WebException), systemUnderTest);
> 
> 			SIL.Windows.Forms.Registration.Registration.Default.Email = originalValue;
> ```

try...finally? and elsewhere
___
*[src/BloomTests/TeamCollection/TeamCollectionApiTests.cs, line 172 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZZcqqTEIrIE1dhOcFV:-MZZcqqTEIrIE1dhOcFW:bbl8vkr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7df8ae7cd828989b2aac09b636a50d225cb12d31/src/BloomTests/TeamCollection/TeamCollectionApiTests.cs#L172)):*
> ```Smalltalk
> 		
> 		[Test]
> 		public void HandleCurrentBookStatus_LockedByRealUser_StatusIndicatesThatuser()
> ```

It's not clear to me what advantage there is in setting up a server and calling through that. Is there a difficulty about calling HandleCurrentBookStatus directly?
Of course this way tests more of the system...now you've done it it's probably not worth changing. However, I think it would be worth a comment, maybe on this test class as a whole since lots of tests seem to do it.
___
*[src/BloomTests/TeamCollection/TeamCollectionApiTests.cs, line 181 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZZd_EA5i5jT_UomKUw:-MZZd_EA5i5jT_UomKUx:b5dpr0q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7df8ae7cd828989b2aac09b636a50d225cb12d31/src/BloomTests/TeamCollection/TeamCollectionApiTests.cs#L181)):*
> ```Smalltalk
> 			api.RegisterWithApiHandler(_server.ApiHandler);
> 
> 			var mockTeamCollection = new Mock<DisconnectedTeamCollection>();
> ```

Why mock a DisconnectedTeamCollection? Are you trying to test what happens when working Disconnected? If so I'd think that a special case that could be reflected in the test method name. If not, a comment would be appropriate.
___
*[src/BloomTests/TeamCollection/TeamCollectionApiTests.cs, line 208 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZZdzRc4dbAn42-q22n:-MZZdzRc4dbAn42-q22o:b-skieio) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7df8ae7cd828989b2aac09b636a50d225cb12d31/src/BloomTests/TeamCollection/TeamCollectionApiTests.cs#L208)):*
> ```Smalltalk
> 			var mockTeamCollection = new Mock<DisconnectedTeamCollection>();
> 			apiBuilder.MockTeamCollectionManager.SetupGet(x => x.CurrentCollectionEvenIfDisconnected).Returns(mockTeamCollection.Object);
> 			mockTeamCollection.Setup(x => x.WhoHasBookLocked(It.IsAny<string>())).Returns("this user");
> ```

This test makes me aware that it's unfortunate the API class has special code for the FakeUser. I wish that was known about in fewer places and didn't need testing here. But it's probably beyond the scope of this to fix it.
___
*[src/BloomTests/TeamCollection/TeamCollectionApiTests.cs, line 221 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZZeKm32_XoF7-07hEm:-MZZeKm32_XoF7-07hEn:bhxxfao) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7df8ae7cd828989b2aac09b636a50d225cb12d31/src/BloomTests/TeamCollection/TeamCollectionApiTests.cs#L221)):*
> ```Smalltalk
> 		}
> 
> 		#endregion
> ```

This is as far as I had time to get, so you should ask someone else to review the rest.
Don't feel like you have to hold up merging this until I get back. Someone else can check anything you feel worth changing in response to my comments.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417)* status: 0 of 14 files reviewed, 8 unresolved discussions (waiting on @JohnThomson and @sujeffreyl)

___
*[src/BloomTests/DataBuilders/TCBookBuilder.cs, line 67 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZZ_Xxo1G9UuWhBchb2:-MZo2twJ8cYtASFC3ZYi:bhlbadf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7df8ae7cd828989b2aac09b636a50d225cb12d31/src/BloomTests/DataBuilders/TCBookBuilder.cs#L67)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Why is this method 'with' and all the others 'set'? See longer comment below.
</blockquote></details>

because I couldn't make up my mind :) Changed to With.
___
*[src/BloomTests/DataBuilders/TeamCollectionApiBuilder.cs, line 38 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZZa2xL3oUHxbH2_E65:-MZo3tMnEzQnJgCef3g1:brcye4h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7df8ae7cd828989b2aac09b636a50d225cb12d31/src/BloomTests/DataBuilders/TeamCollectionApiBuilder.cs#L38)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

May be overkill for the current task, but it would be even more useful if it would fill in reasonable defaults (possibly mocks?) for anything it needs that has not been specified. Ideally that would involve Builders for each of those classes, with their own defaults, but that's really exploding the scope of the project. Still, if you already have code to create those objects, consider whether any of it would be usefully moved here as a default.
</blockquote></details>

The stuff I read suggested a WithDefaultValues() method. I think I can come up with reasonable defaults for 4 of the 5 parameters. Guess callers will need to override _teamCollectionManager though.
___
*[src/BloomTests/DataBuilders/TeamCollectionApiBuilder.cs, line 45 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZZ_dd29HyPLVd00aBs:-MZo49pg6keda-3SVhvI:b-8fqhfz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7df8ae7cd828989b2aac09b636a50d225cb12d31/src/BloomTests/DataBuilders/TeamCollectionApiBuilder.cs#L45)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Why are several of these WithX rather than SetX (like the methods on TCBookBuildier)? It would probably be better to settle on whatever convention is in the pattern. My intuition is that 'WithX' is expected to return a new instance (usually of an immutable object) with one property changed and the others cloned, while SetX modifies the object and returns it, but that may not be standard for the Builder pattern you are following.
</blockquote></details>

I guess it suggested the terminology With(), although my personal thoughts were wondering why we didn't just always have Set return the object instead of returning void.
Changed to use With throughout.
___
*[src/BloomTests/TeamCollection/TeamCollectionApiTests.cs, line 168 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZZbism6f1WeJKAtZk1:-MZo4zFc46xs835RCnUN:b-ul8jrf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7df8ae7cd828989b2aac09b636a50d225cb12d31/src/BloomTests/TeamCollection/TeamCollectionApiTests.cs#L168)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

try...finally? and elsewhere
</blockquote></details>

Good idea
___
*[src/BloomTests/TeamCollection/TeamCollectionApiTests.cs, line 172 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZZcqqTEIrIE1dhOcFV:-MZo7RNcBa66rWffYLUj:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7df8ae7cd828989b2aac09b636a50d225cb12d31/src/BloomTests/TeamCollection/TeamCollectionApiTests.cs#L172)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's not clear to me what advantage there is in setting up a server and calling through that. Is there a difficulty about calling HandleCurrentBookStatus directly?
Of course this way tests more of the system...now you've done it it's probably not worth changing. However, I think it would be worth a comment, maybe on this test class as a whole since lots of tests seem to do it.
</blockquote></details>

Done.
___
*[src/BloomTests/TeamCollection/TeamCollectionApiTests.cs, line 181 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZZd_EA5i5jT_UomKUw:-MZo8YgoAqnPErKWLPq3:by9b214) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7df8ae7cd828989b2aac09b636a50d225cb12d31/src/BloomTests/TeamCollection/TeamCollectionApiTests.cs#L181)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Why mock a DisconnectedTeamCollection? Are you trying to test what happens when working Disconnected? If so I'd think that a special case that could be reflected in the test method name. If not, a comment would be appropriate.
</blockquote></details>

No particular reason, just figured it would be an instance of CurrentCollectionEvenifDisconnected. I guess I can just make a mock of TeamCollection instead.
___
*[src/BloomTests/TeamCollection/TeamCollectionApiTests.cs, line 208 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZZdzRc4dbAn42-q22n:-MZo8iCz0bj_-pJsTK_5:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7df8ae7cd828989b2aac09b636a50d225cb12d31/src/BloomTests/TeamCollection/TeamCollectionApiTests.cs#L208)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This test makes me aware that it's unfortunate the API class has special code for the FakeUser. I wish that was known about in fewer places and didn't need testing here. But it's probably beyond the scope of this to fix it.
</blockquote></details>

Done.

**Review by hatton — CHANGES_REQUESTED** [review]
This is cool to see. I love to see care taken to make test code maintainable and readable.  I made a few comments, but mostly we need to rebase this and work through the change in the milestone/message stuff.

> Reviewed 8 of 14 files at r1, 4 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-:-MZrT8e619V3oqoQWuoL:b-u1fnke)* status: 12 of 14 files reviewed, 12 unresolved discussions (waiting on @JohnThomson, @StephenMcConnel, and @sujeffreyl)

___
*[src/BloomExe/TeamCollection/TeamCollectionMessageLog.cs, line 33 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZrL66c7Rr2iw5q-WUr:-MZrL66c7Rr2iw5q-WUs:b4jnfzf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/73babb113d1a0fc13a0bbabaa24f7bf2b780b909/src/BloomExe/TeamCollection/TeamCollectionMessageLog.cs#L33)):*
> ```Smalltalk
> 		void WriteMessage(MessageAndMilestoneType messageType, string l10nId, string message, string param0="", string param1="");
> 		void WriteMessage(TeamCollectionMessage message);
> 		Tuple<MessageAndMilestoneType, String>[] PrettyPrintMessages { get; }
> ```

This will need re-working during rebase, I got rid of the Tuple mess.
___
*[src/BloomTests/BloomTests.csproj, line 271 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZrLKIn4nBB-ahb_mmE:-MZrLKIn4nBB-ahb_mmF:b-qwu0q9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/73babb113d1a0fc13a0bbabaa24f7bf2b780b909/src/BloomTests/BloomTests.csproj#L271)):*
> ```XML
>     <Compile Include="CLI\GetUsedFontsCommandTests.cs" />
>     <Compile Include="DataBuilders\HtmlErrorReporterBuilder.cs" />
>     <Compile Include="DataBuilders\TCBookBuilder.cs" />
> ```

Small thing, but we've been aiming to not abbreviate Team Collection in most public places. E.g. the next file here.
___
*[src/BloomTests/DataBuilders/TCBookBuilder.cs, line 9 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZrRmLo6VcDKjzPYsz6:-MZrRmLo6VcDKjzPYsz7:biqobhx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/73babb113d1a0fc13a0bbabaa24f7bf2b780b909/src/BloomTests/DataBuilders/TCBookBuilder.cs#L9)):*
> ```Smalltalk
> using System.ServiceModel.Channels;
> 
> namespace BloomTests.DataBuilders
> ```

Is there anything in here that is specific to Team Collections? If not, if this is a generally useful thing, then let's rename it.
___
*[src/BloomTests/DataBuilders/TCBookBuilder.cs, line 67 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZrQfQyCQa4aVkUPrsU:-MZrQfQyCQa4aVkUPrsV:b-7d2mty) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/73babb113d1a0fc13a0bbabaa24f7bf2b780b909/src/BloomTests/DataBuilders/TCBookBuilder.cs#L67)):*
> ```Smalltalk
> 		/// Provides reasonable default values for an HtmlErrorReporter that would be used in unit tests
> 		/// </summary>
> 		public TCBookBuilder WithTestValues()
> ```

Since everything here is a "test value", how about echoing the `WithDefaultValues()`?  
___
*[src/BloomTests/TeamCollection/TeamCollectionApiTests.cs, line 221 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZZeKm32_XoF7-07hEm:-MZrSSQP5TliT-VTzRfb:bqt4o3p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7df8ae7cd828989b2aac09b636a50d225cb12d31/src/BloomTests/TeamCollection/TeamCollectionApiTests.cs#L221)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This is as far as I had time to get, so you should ask someone else to review the rest.
Don't feel like you have to hold up merging this until I get back. Someone else can check anything you feel worth changing in response to my comments.
</blockquote></details>

I find it excruciated to review test cases. So this can be a "TODO" or we can ask @stephenmcconnel

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417)* status: 9 of 14 files reviewed, 12 unresolved discussions (waiting on @hatton, @JohnThomson, @StephenMcConnel, and @sujeffreyl)

___
*[src/BloomTests/BloomTests.csproj, line 271 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZrLKIn4nBB-ahb_mmE:-MZrtDrp4eOmFtX0mq8l:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/73babb113d1a0fc13a0bbabaa24f7bf2b780b909/src/BloomTests/BloomTests.csproj#L271)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Small thing, but we've been aiming to not abbreviate Team Collection in most public places. E.g. the next file here.
</blockquote></details>

Done.
___
*[src/BloomTests/DataBuilders/TCBookBuilder.cs, line 9 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZrRmLo6VcDKjzPYsz6:-MZrtQkk-llCcTKsZJhm:baibtor) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/73babb113d1a0fc13a0bbabaa24f7bf2b780b909/src/BloomTests/DataBuilders/TCBookBuilder.cs#L9)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is there anything in here that is specific to Team Collections? If not, if this is a generally useful thing, then let's rename it.
</blockquote></details>

Hmm, I'm a bit confused. Seems like it's pointing to the namespace name? But the namespace already doesn't mention anything about Team Collections in the namespace name.
___
*[src/BloomTests/DataBuilders/TCBookBuilder.cs, line 67 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZrQfQyCQa4aVkUPrsU:-MZruREf6K0MkyMQ5zuU:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/73babb113d1a0fc13a0bbabaa24f7bf2b780b909/src/BloomTests/DataBuilders/TCBookBuilder.cs#L67)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Since everything here is a "test value", how about echoing the `WithDefaultValues()`?  
</blockquote></details>

Done.

**Review by sujeffreyl — COMMENTED** [review]
> Reviewed 2 of 15 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417)* status: 2 of 18 files reviewed, 12 unresolved discussions (waiting on @hatton, @JohnThomson, and @StephenMcConnel)

___
*[src/BloomExe/TeamCollection/TeamCollectionMessageLog.cs, line 33 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZrL66c7Rr2iw5q-WUr:-MZs4psyD7HYY4eEZMh9:bapbyd2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/73babb113d1a0fc13a0bbabaa24f7bf2b780b909/src/BloomExe/TeamCollection/TeamCollectionMessageLog.cs#L33)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This will need re-working during rebase, I got rid of the Tuple mess.
</blockquote></details>

Rebased, still needs fixing of PrettyPrintMessages though.

**Review by sujeffreyl — COMMENTED** [review]
R5: Just simply selecting rebase onto version 5.0.  (No merge conflicts were auto-detected by Git)
R6: Fix the build errors resulting from PrettyPrintMessages getting reworked into GetProgressMessages()

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-:-MZs5G2t6CIL2BW1EsVl:bsn2jz8)* status: 1 of 18 files reviewed, 12 unresolved discussions (waiting on @hatton, @JohnThomson, @StephenMcConnel, and @sujeffreyl)

___
*[src/BloomExe/TeamCollection/TeamCollectionMessageLog.cs, line 33 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZrL66c7Rr2iw5q-WUr:-MZs5D0cCKhLzadoZTTY:b-886gsx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/73babb113d1a0fc13a0bbabaa24f7bf2b780b909/src/BloomExe/TeamCollection/TeamCollectionMessageLog.cs#L33)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Rebased, still needs fixing of PrettyPrintMessages though.
</blockquote></details>

Fixed

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 2 of 15 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417)* status: 2 of 18 files reviewed, 10 unresolved discussions (waiting on @hatton, @JohnThomson, @StephenMcConnel, and @sujeffreyl)

___
*[src/BloomTests/DataBuilders/TCBookBuilder.cs, line 9 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZrRmLo6VcDKjzPYsz6:-MZssKnx0hJHkJZLQFOV:bqk6e38) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/73babb113d1a0fc13a0bbabaa24f7bf2b780b909/src/BloomTests/DataBuilders/TCBookBuilder.cs#L9)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Hmm, I'm a bit confused. Seems like it's pointing to the namespace name? But the namespace already doesn't mention anything about Team Collections in the namespace name.
</blockquote></details>

The name of this file is "TCBookBuilder". I assume the "TC" stands for "TeamCollection". If true, then I am asking why this is named after TeamCollections when it doesn't not seem to be related to them. Does that help?

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417)* status: 2 of 18 files reviewed, 10 unresolved discussions (waiting on @hatton, @JohnThomson, @StephenMcConnel, and @sujeffreyl)

___
*[src/BloomTests/DataBuilders/TCBookBuilder.cs, line 9 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZrRmLo6VcDKjzPYsz6:-MZszbyn8M0Wy33AETYK:b-6knyeu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/73babb113d1a0fc13a0bbabaa24f7bf2b780b909/src/BloomTests/DataBuilders/TCBookBuilder.cs#L9)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

The name of this file is "TCBookBuilder". I assume the "TC" stands for "TeamCollection". If true, then I am asking why this is named after TeamCollections when it doesn't not seem to be related to them. Does that help?
</blockquote></details>

Thanks, now i see what you're referring to. You're right, seems it's general enough that it could be used outside of Team Collection.

Well, I wouldn't want to do BookBuilder(), because IMO that implies building our Bloom.Book.Book objects, but I could do something like... BookOnDiskBuilder? FilesystemBookBuilder?  BookWriter?

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417)* status: 1 of 18 files reviewed, 10 unresolved discussions (waiting on @hatton, @JohnThomson, @StephenMcConnel, and @sujeffreyl)

___
*[src/BloomTests/DataBuilders/TCBookBuilder.cs, line 9 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZrRmLo6VcDKjzPYsz6:-MZt2sPc47zcpW5hMpM9:b-mnrf40) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/73babb113d1a0fc13a0bbabaa24f7bf2b780b909/src/BloomTests/DataBuilders/TCBookBuilder.cs#L9)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Thanks, now i see what you're referring to. You're right, seems it's general enough that it could be used outside of Team Collection.

Well, I wouldn't want to do BookBuilder(), because IMO that implies building our Bloom.Book.Book objects, but I could do something like... BookOnDiskBuilder? FilesystemBookBuilder?  BookWriter?
</blockquote></details>

BookFolderBuilder?

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417)* status: 1 of 18 files reviewed, 10 unresolved discussions (waiting on @hatton, @JohnThomson, @StephenMcConnel, and @sujeffreyl)

___
*[src/BloomTests/DataBuilders/TCBookBuilder.cs, line 9 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-MZrRmLo6VcDKjzPYsz6:-MZt43fI1UDvnI3jRfpb:b-qcldua) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/73babb113d1a0fc13a0bbabaa24f7bf2b780b909/src/BloomTests/DataBuilders/TCBookBuilder.cs#L9)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

BookFolderBuilder?
</blockquote></details>

That works

**Review by hatton — APPROVED** [review]
> Reviewed 1 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417)* status: 2 of 18 files reviewed, 10 unresolved discussions (waiting on @hatton, @JohnThomson, @StephenMcConnel, and @sujeffreyl)

**Review by sujeffreyl — COMMENTED** [review]
> Reviewed 2 of 16 files at r3, 1 of 2 files at r4, 8 of 15 files at r5, 6 of 7 files at r6.
> Dismissed @JohnThomson and @hatton from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417)* status: all files reviewed, 9 unresolved discussions (waiting on @hatton and @JohnThomson)

**Review by sujeffreyl — COMMENTED** [review]
:lgtm:

> Dismissed @JohnThomson and @hatton from 9 discussions.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417#-:-MZtWCJK9Sa8mId1lsHZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Pull request merged**
