### PR TITLE
BL-9976 Video and image comics

### PR DESCRIPTION
**Pull request by gmartin7**
* handle pic over pic editing
* make comic bubbles not draggable when the book is
   locked
* remove Image Description overlay button
* make pic/vid placeholders square

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4607)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4607)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 2550 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4607#-MfA5oOVBntUSad6o_y6:-MfA5oOWEzmXii38cIpC:b9jss3z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/49bca50d739a532bb1092504c63be2594b0451d1/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2550)):*
> ```XML
>         const desiredHeight = makeSquare
>             ? wrapperBox.width()
>             : wrapperBox.height();
> ```

I don't like that a function which is supposed to set the position is modifying the size.
Shouldn't we be passing in wrapperBox with the correct size?

Seems like we should push the logic all the way up to `finishAddingOverPictureElement` to determine the correct height and set it.

Where does the height value come from now? The css? I thought so, but you removed that. So if the height currently comes from css, it seems like it would break the addition of actual text boxes.

If it does come from css, would a more elegant solution be to add an additional class to square .bloom-textOverPicture elements which overrides the height?

Happy to discuss this.
___
*[src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx, line 52 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4607#-MfA7Lfd1yR1LnBdrlee:-MfA7Lfe9Tt1tQ7DlflB:btaq0z2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/49bca50d739a532bb1092504c63be2594b0451d1/src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx#L52)):*
> ```
> newPageCount
> ```
The comment clarifies, but just seeing the variable name, it seems like a count of new pages.
How about something like 
`NewPageReadyCounter`
`ReadyCounter`
`StateCounter`
`StateRefreshCounter`
`LockedStateCounter`
`LockedStateRefreshCounter`

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4607)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 2550 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4607#-MfA5oOVBntUSad6o_y6:-MfEBt5U5xT3tGTuLj4S:b4jddz0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/49bca50d739a532bb1092504c63be2594b0451d1/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2550)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't like that a function which is supposed to set the position is modifying the size.
Shouldn't we be passing in wrapperBox with the correct size?

Seems like we should push the logic all the way up to `finishAddingOverPictureElement` to determine the correct height and set it.

Where does the height value come from now? The css? I thought so, but you removed that. So if the height currently comes from css, it seems like it would break the addition of actual text boxes.

If it does come from css, would a more elegant solution be to add an additional class to square .bloom-textOverPicture elements which overrides the height?

Happy to discuss this.
</blockquote></details>

And actually... the default video Container really ought to be a 4:3 ratio of width:height to fit what the sign language tool generates. Done
___
*[src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx, line 52 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4607#-MfA7Lfd1yR1LnBdrlee:-MfE2EL2DbZ_Khhlarsh:b-f2rfzr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/49bca50d739a532bb1092504c63be2594b0451d1/src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx#L52)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> newPageCount
> ```
The comment clarifies, but just seeing the variable name, it seems like a count of new pages.
How about something like 
`NewPageReadyCounter`
`ReadyCounter`
`StateCounter`
`StateRefreshCounter`
`LockedStateCounter`
`LockedStateRefreshCounter`
</blockquote></details>

As per discussion, I will use `pageRefreshIndicator`.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4607)* status: all files reviewed, 3 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 1788 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4607#-MfJAB_w0QWW3YMtw2sE:-MfJAB_w0QWW3YMtw2sF:boj174v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9f52bdd759a4a466abf24b9d5cdc7beb22a2499/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L1788)):*
> ```XML
>             wrapperBox.css("height", width);
>         }
>     }
> ```

So I still don't understand how the text box height gets set.
It's probably worth a comment here since we're only addressing non-text boxes in this method.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 1802 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4607#-MfJ9j3VB6hUMSTt3Z9-:-MfJ9j3VB6hUMSTt3Z90:blppl6e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9f52bdd759a4a466abf24b9d5cdc7beb22a2499/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L1802)):*
> ```
> // initialPlacement: only true if we are creating a new element
> ```
now obsolete
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 2535 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4607#-MfJ9lYbB5-XWPlZrnxX:-MfJ9lYbB5-XWPlZrnxY:b-5y8nf5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9f52bdd759a4a466abf24b9d5cdc7beb22a2499/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2535)):*
> ```
> // makeSquare: Should only be set when initially inserting picture or video over picture placeholders.
> ```
now obsolete

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4607)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 1788 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4607#-MfJAB_w0QWW3YMtw2sE:-MfiGd8G1dfDxwBK_Pw5:b-m93wz6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9f52bdd759a4a466abf24b9d5cdc7beb22a2499/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L1788)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

So I still don't understand how the text box height gets set.
It's probably worth a comment here since we're only addressing non-text boxes in this method.
</blockquote></details>

Comment added. As JQuery has just added the element in `wrapperBox`, the min-height of 30px from `bubble.less` has been applied to the `.bloom-textOverPicture` element.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 1802 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4607#-MfJ9j3VB6hUMSTt3Z9-:-MfiAMwo8RA6mzyvJ37J:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9f52bdd759a4a466abf24b9d5cdc7beb22a2499/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L1802)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> // initialPlacement: only true if we are creating a new element
> ```
now obsolete
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 2535 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4607#-MfJ9lYbB5-XWPlZrnxX:-MfiAWqk9wzBE5gN_-xb:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9f52bdd759a4a466abf24b9d5cdc7beb22a2499/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2535)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> // makeSquare: Should only be set when initially inserting picture or video over picture placeholders.
> ```
now obsolete
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4607)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
