### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by jsubloom**
Minor changes to be consistent with BL-9515

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5743)

### CODE REVIEW

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5743)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`ReadMe.md` line 82 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5743#-NS7xn2L4o_ZPDNqpK5q:-NS7xn2L4o_ZPDNqpK5r:bdqeeop) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/86f9032655b7bbadbb1b021a464896a6a0a7c541/ReadMe.md#L82)):*
> ```Markdown
> Javascript dependencies should be introduced using
> 
>     yarn add <modulename>
> ```

Ok, technically this is a functional change not related to BL-9515, but I think the old one (2 spaces AKA meaningless) was wrong and the new one (4 spaces AKA code block) is better.

**Review by jsubloom — COMMENTED** [review]
Formatted preview: https://github.com/jsubloom/BloomDesktop/blob/updateReadme/ReadMe.md

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5743#-:-NS7yMqa8p1gGw9W-Zf_:b-4e6pte)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5743)* status: all files reviewed, 1 unresolved discussion

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5743)* status: all files reviewed, 1 unresolved discussion

**Review by andrew-polk — APPROVED** [review]
> Dismissed @jsubloom from a discussion.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5743)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsubloom)

**Pull request merged**
