### PR TITLE
BL-5272 Pause sending WiFi adds while sending book

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2135)

### CODE REVIEW

**Comment by andrew-polk** [comment]
:lgtm: but it feels a little risky for a day or two before a release (though the risk of leaving it out could be worse?)
At the least, I would like someone else to look, too.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2135#-:-L4I4F0oHjbodqgQU_Hn:b-pfb1np)*

**Comment by hatton** [comment]
John, can you aim this at 4.1 instead? We'll cherry-pick back after a week of testing. Thx.

**Comment by JohnThomson** [comment]
Can't make rebase work...closing and cherry-picking to a new PR

**Comment by andrew-polk** [comment]
Superceded by #2136

**Pull request closed without merging**
