### PR TITLE
BL-5050 Remove log spam from optional branding images

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1864)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 610 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1864#-KudoWGTZMOFxu5wqb0l:-KudoWGTZMOFxu5wqb0m:b7eu4pa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f5b19dacfdb29ab94fd6e6c6f968d103b9617e7c/src/BloomExe/web/EnhancedImageServer.cs#L610)):*
> ```Smalltalk
> 					info.ContentType = "text/html";
> 					info.WriteCompleteOutput("");
> 					return true; // If we haven't found an optional Branding image by now, give up w/o logging it.
> ```

Sorry, this is not right. Returning true here pretends to the browser that we HAVE found the image, so you are changing behavior as well as the desired change to logging. Also, I suspect that returning something that is supposed to be an image as an empty file that claims to be text will not have good results.
To fix this problem we need to find out where the missing file is being LOGGED even though ReportMissingFile is not called.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1864)*

**Comment by gmartin7** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 610 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1864#-KudoWGTZMOFxu5wqb0l:-Kudzyb1pvxOv3yw7gb7:b-y48n9n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f5b19dacfdb29ab94fd6e6c6f968d103b9617e7c/src/BloomExe/web/EnhancedImageServer.cs#L610)):*
> we need to find out where the missing file is being LOGGED
Refactored things so there's only one Ignore method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1864)*

**Comment by JohnThomson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 611 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1864#-Kuenh8Cr6l68lyW2THp:-Kuenh8Cr6l68lyW2THq:ba9818y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15942ad8a1ce9aac4c0e4d076e8fdec6964a0d38/src/BloomExe/web/EnhancedImageServer.cs#L611)):*
> ```Smalltalk
> 		}
> 
> 		// overridden in tests (Really?! Where!?)
> ```

Clearly it isn't, as a simple search reveals. Presumably there was an intent to override in order to test code that calls it. It would be more helpful to either make it non-virtual or amend the comment to something like "virtual to support possible overrides in tests"

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 612 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1864#-Kuer0nB21TeisI5ayfT:-Kuer0nB21TeisI5ayfU:b-8k62s2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15942ad8a1ce9aac4c0e4d076e8fdec6964a0d38/src/BloomExe/web/EnhancedImageServer.cs#L612)):*
> ```Smalltalk
> 
> 		// overridden in tests (Really?! Where!?)
> 		internal virtual void ReportMissingFile(string localPath, string path, IRequestInfo info)
> ```

It's rather ugly passing this extra parameter just so we can test whether we really want to report the missing file...a special case not even hinted at in the method name. Since this is only called in one place, I think it would be better to move the IgnoreFileIfMissing to the caller, which would remove the necessity for a third parameter. (Bad enough that no comment explains the different significance and expected contents of path and localPath...but that problem isn't new. 

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 638 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1864#-KueqMOtXQKkNTL4Ld_f:-KueqMOtXQKkNTL4Ld_g:b-peehaf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15942ad8a1ce9aac4c0e4d076e8fdec6964a0d38/src/BloomExe/web/EnhancedImageServer.cs#L638)):*
> ```Smalltalk
> 				// We don't need even a toast for missing images in the book folder. That's the user's problem and should be adequately
> 				// documented by the browser message saying the file is missing.
> 				if (!localPath.StartsWith((CurrentBook?.FolderPath ?? "").Replace("\\", "/")))
> ```

This appears to be yet another case in which we don't report missing files, and so presumably should be handled in IgnoreFileIfMissing...otherwise the other ReportMissingFile will report them.

---

*[src/BloomExe/web/ServerBase.cs, line 468 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1864#-Kuerwy4Ul1RA2IGayxb:-Kuerwy4Ul1RA2IGayxc:bsn5n7p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15942ad8a1ce9aac4c0e4d076e8fdec6964a0d38/src/BloomExe/web/ServerBase.cs#L468)):*
> ```Smalltalk
> 		/// Includes branding files marked "optional".
> 		/// </summary>
> 		protected bool IgnoreFileIfMissing(IRequestInfo info, out string path, string localPath = "")
> ```

The naming here begs for confusion! This method has a variable localPath but also an out param called path, whose return value is stored in the calling method's localPath variable. Assuming there is some distinction between path and localPath, at least use the names consistently. Better, come up with some names that indicate more clearly what the distinction is.

---

*[src/BloomExe/web/ServerBase.cs, line 498 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1864#-KueotMcaL6MBDKbg1an:-KueotMcaL6MBDKbg1ao:bf3y0c5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15942ad8a1ce9aac4c0e4d076e8fdec6964a0d38/src/BloomExe/web/ServerBase.cs#L498)):*
> ```Smalltalk
> 			// images with src derived from Branding API img elements get this marker 
> 			// in XMatterHelper.CleanupBrandingImages() to prevent spurious reports of 
> 			// images that are intentionally optional. 
> ```

This comment is misplaced...it belongs to the lines that look for optional in the query.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1864)*

**Comment by gmartin7** [comment]
Much better now. Thanks for the very helpful comments.

---

Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 611 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1864#-Kuenh8Cr6l68lyW2THp:-KutzrFJ78L0dLvHz1qW:b-2cleji) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15942ad8a1ce9aac4c0e4d076e8fdec6964a0d38/src/BloomExe/web/EnhancedImageServer.cs#L611)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Clearly it isn't, as a simple search reveals. Presumably there was an intent to override in order to test code that calls it. It would be more helpful to either make it non-virtual or amend the comment to something like "virtual to support possible overrides in tests"
</blockquote></details>

Done. No longer 'virtual'. If someone wants to add tests in this area later, they can make the necessary changes.

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 612 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1864#-Kuer0nB21TeisI5ayfT:-Kuu7meKoxUG8wF1PXog:bp6qvqr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15942ad8a1ce9aac4c0e4d076e8fdec6964a0d38/src/BloomExe/web/EnhancedImageServer.cs#L612)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's rather ugly passing this extra parameter just so we can test whether we really want to report the missing file...a special case not even hinted at in the method name. Since this is only called in one place, I think it would be better to move the IgnoreFileIfMissing to the caller, which would remove the necessity for a third parameter. (Bad enough that no comment explains the different significance and expected contents of path and localPath...but that problem isn't new. 
</blockquote></details>

Done. Much better now. Thanks.

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 638 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1864#-KueqMOtXQKkNTL4Ld_f:-Kuu6nfHZpGb7hYuN6fS:b-crmbfv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15942ad8a1ce9aac4c0e4d076e8fdec6964a0d38/src/BloomExe/web/EnhancedImageServer.cs#L638)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This appears to be yet another case in which we don't report missing files, and so presumably should be handled in IgnoreFileIfMissing...otherwise the other ReportMissingFile will report them.
</blockquote></details>

Moved to ShouldReportFailedRequest().

---

*[src/BloomExe/web/ServerBase.cs, line 457 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1864#-Kuewydnxa1Uol7Ceh7n:-Kuu7SStzm5e6uF_4ppl:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15942ad8a1ce9aac4c0e4d076e8fdec6964a0d38/src/BloomExe/web/ServerBase.cs#L457)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

For consistency with the other method of the same name, consider moving the Ignore test to the caller.
</blockquote></details>

Done.

---

*[src/BloomExe/web/ServerBase.cs, line 468 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1864#-Kuerwy4Ul1RA2IGayxb:-Kuu7VR9pdd6J4A-54Q_:bqunsmw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15942ad8a1ce9aac4c0e4d076e8fdec6964a0d38/src/BloomExe/web/ServerBase.cs#L468)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It appears that with (almost) perfect consistency, localPath means the output of GetLocalPathWithoutQuery(info). So it's bizarre that one caller of this method passes that in, while the other requires it to be passed out. I suggest that it be consistently passed in, that is, move the call to GetLocalPathWithoutQuery(info) into the local caller and make localPath solely an 'in' parameter. Since we're now getting in to error reporting, not anything that is performance-critical, it's also worth considering just passing info (and extracting localPath again in the method).
I'd also like to see this method renamed, since it's now not exactly about files...something like IgnoreFailedRequest(). Or, since we already have one double-negative caller, reverse it and call it ShouldReportFailedRequest()
</blockquote></details>

Done. ShouldReportFailedRequest() now takes info and an optional folderPath. Greatly simplifies things.

---

*[src/BloomExe/web/ServerBase.cs, line 498 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1864#-KueotMcaL6MBDKbg1an:-Kuu7i21U8UeSY42_g11:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15942ad8a1ce9aac4c0e4d076e8fdec6964a0d38/src/BloomExe/web/ServerBase.cs#L498)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This comment is misplaced...it belongs to the lines that look for optional in the query.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1864#-:-Kuu7sW5EMoILtVPbBjz:b-a3ynbx)*

**Comment by StephenMcConnel** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1864#-:-KuvEsxUp0wr2ojOM2Qh:bnfp4nl)*

**Pull request merged**
