### PR TITLE
Move non-xml files to subfolders in epubs (BL-6037)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2510)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

---

*[src/BloomExe/Book/HtmlDom.cs, line 1490 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2510#-LFK9czR9JGPi_dJcxHq:-LFK9czR9JGPi_dJcxHr:bem3c21) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6dd48dc7bff5f317e99ecb907a7cb4ca1f139e8/src/BloomExe/Book/HtmlDom.cs#L1490)):*
> ```Smalltalk
> 				// This does not need to be encoded until sent over the network.
> 				// Indeed, encoding it breaks links within epubs.
> 				imgOrDivWithBackgroundImage.SetAttribute("src", url.NotEncoded);
> ```

Woah that's scary.  Maybe can you add some manual test ideas to the issue to check some of the places this would break?  Maybe @johnthomson (who is good at such lists) should weigh in?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2510)*

**Comment by JohnThomson** [comment]
Do we want to put the .smil files in a sub-folder too? That's another large class of non-xml files.
Looks basically good, but I'm nervous about not url encoding src attrs.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed, 5 unresolved discussions (waiting on @StephenMcConnel)

---

*[src/BloomExe/Book/HtmlDom.cs, line 1490 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2510#-LFK9czR9JGPi_dJcxHq:-LFNFNp33gITOZVgut5b:b-yy4zox) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6dd48dc7bff5f317e99ecb907a7cb4ca1f139e8/src/BloomExe/Book/HtmlDom.cs#L1490)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Woah that's scary.  Maybe can you add some manual test ideas to the issue to check some of the places this would break?  Maybe @johnthomson (who is good at such lists) should weigh in?
</blockquote></details>

Yes, how will it get encoded when sent over the network if it isn't stored that way? Is this something browsers know? Are you sure this is how all src attributes should be stored in all images, not just epubs? Do we need a similar change for the src attributes of <source> elements in <video> ones?

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1556 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2510#-LFNIqZhEQvN_YwE4TGd:-LFNIqZhEQvN_YwE4TGe:bat1x8s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6dd48dc7bff5f317e99ecb907a7cb4ca1f139e8/src/BloomExe/Publish/Epub/EpubMaker.cs#L1556)):*
> ```Smalltalk
> 				var group = fontFileFinder.GetGroupForFont (font);
> 				if (group != null) {
> 					AddFontFace (sb, font, "normal", "normal", group.Normal, "../"+kFontsFolder+"/");
> ```

I think the ../ deserves a comment, especially since the argument is called 'subFolder' which this isn't. I gather the point is that AddFontFace is constructing a css file, which will be in its own subfolder, and the path has to be relative to the css file, not the root document?
Since AddFontFace is probably only called here, maybe it would be clearer to just let that method know where fonts are found relative to the CSS file it is making?

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 2025 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2510#-LFNKYCIAn-09qlN8HnG:-LFNKYCIAn-09qlN8HnH:b-g4vqjw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6dd48dc7bff5f317e99ecb907a7cb4ca1f139e8/src/BloomExe/Publish/Epub/EpubMaker.cs#L2025)):*
> ```Smalltalk
> 															   // right but if we substitute them we can be sure things are fine.
> 															   // I'm deliberately not using UrlPathString here because it doesn't correctly encode a lot of Ascii characters like =$&<>
> 															   // which are technically not valid in hrefs
> ```

The comment above is now misplaced. It explains the Replace commands a few lines down.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 2027 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2510#-LFNKaqfDNJ-PYJ3JaRb:-LFNKaqfDNJ-PYJ3JaRc:bnuhits) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6dd48dc7bff5f317e99ecb907a7cb4ca1f139e8/src/BloomExe/Publish/Epub/EpubMaker.cs#L2027)):*
> ```Smalltalk
> 															   // which are technically not valid in hrefs
> 			if (!String.IsNullOrEmpty(subfolder) && originalFileName.StartsWith(subfolder+"/"))
> 				originalFileName = originalFileName.Substring(subfolder.Length+1);	// we don't need to change the folder to be part of the filename
> ```

This worries me. We're using originalFileName in _mapChangedFileNames. If the client was unexpectedly passing us a file that's already in the folder, will the value in _mapChangedFileNames really do what the caller expects? Makes the code even harder than it was to reason about. How hard would it be to fix whatever clients pass names already including the subfolder?

---

*[src/BloomTests/Publish/ExportEpubTests.cs, line 115 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2510#-LFNR3BL-xmfKkfkhR0f:-LFNR3BL-xmfKkfkhR0g:blfynuk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6dd48dc7bff5f317e99ecb907a7cb4ca1f139e8/src/BloomTests/Publish/ExportEpubTests.cs#L115)):*
> ```Smalltalk
> 		}
> 
> 		private void CheckFontStylesheet()
> ```

Seems it might be useful to add a test somewhere that, after a typical conversion, there are no files in the root directory with typical extensions for the things that should be in subfolders.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2510#-:-LFNS5iiDN26AmON7oOD:b195y6k)*

**Comment by StephenMcConnel** [comment]
.smil files are XML even though the name doesn't give a clue for that.  The sample display in the issue shows them in the same folder as the .xhtml files.

---

Review status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @JohnThomson, @hatton, and @StephenMcConnel)

---

*[src/BloomExe/Book/HtmlDom.cs, line 1490 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2510#-LFK9czR9JGPi_dJcxHq:-LFNxx1p5Hvkl-fb3pp_:bslikkn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6dd48dc7bff5f317e99ecb907a7cb4ca1f139e8/src/BloomExe/Book/HtmlDom.cs#L1490)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Yes, how will it get encoded when sent over the network if it isn't stored that way? Is this something browsers know? Are you sure this is how all src attributes should be stored in all images, not just epubs? Do we need a similar change for the src attributes of <source> elements in <video> ones?
</blockquote></details>

My testing shows a problem here with at least one tortuous filename.  So this part of the change needs to be restricted to epubs, which absolutely do require it.  If we were to restructure BloomReader books using folders for images, they would probably need to not UrlEncode the references as well.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1556 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2510#-LFNIqZhEQvN_YwE4TGd:-LFNyjCYBU8CLPXZYy63:b-sav8w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6dd48dc7bff5f317e99ecb907a7cb4ca1f139e8/src/BloomExe/Publish/Epub/EpubMaker.cs#L1556)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think the ../ deserves a comment, especially since the argument is called 'subFolder' which this isn't. I gather the point is that AddFontFace is constructing a css file, which will be in its own subfolder, and the path has to be relative to the css file, not the root document?
Since AddFontFace is probably only called here, maybe it would be clearer to just let that method know where fonts are found relative to the CSS file it is making?
</blockquote></details>

AddFontFace is called in two places, once for the epubs and once for BloomReader books which aren't organized (yet?) into folders.
I added an explanatory comment as suggested, and renamed the method's argument.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 2025 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2510#-LFNKYCIAn-09qlN8HnG:-LFO4S0e5vdiYzW3Fx0v:bwhglds) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6dd48dc7bff5f317e99ecb907a7cb4ca1f139e8/src/BloomExe/Publish/Epub/EpubMaker.cs#L2025)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

The comment above is now misplaced. It explains the Replace commands a few lines down.
</blockquote></details>

Moved.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 2027 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2510#-LFNKaqfDNJ-PYJ3JaRb:-LFOgAe18yfS1VHRZn-A:b-lx50gt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6dd48dc7bff5f317e99ecb907a7cb4ca1f139e8/src/BloomExe/Publish/Epub/EpubMaker.cs#L2027)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This worries me. We're using originalFileName in _mapChangedFileNames. If the client was unexpectedly passing us a file that's already in the folder, will the value in _mapChangedFileNames really do what the caller expects? Makes the code even harder than it was to reason about. How hard would it be to fix whatever clients pass names already including the subfolder?
</blockquote></details>

I've refactored things so that _mapChangedFileNames is no longer needed.  I've also added a few comments to explain things.

---

*[src/BloomTests/Publish/ExportEpubTests.cs, line 115 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2510#-LFNR3BL-xmfKkfkhR0f:-LFOwtoV-5C4abjA5o3k:bp85dg0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6dd48dc7bff5f317e99ecb907a7cb4ca1f139e8/src/BloomTests/Publish/ExportEpubTests.cs#L115)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Seems it might be useful to add a test somewhere that, after a typical conversion, there are no files in the root directory with typical extensions for the things that should be in subfolders.
</blockquote></details>

I added a check of the folder structure to a number of existing unit tests.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2510#-:-LFNyGnXCJI9slzt8Ujy:bk34jqb)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 6 of 8 files at r2.
Review status: all files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

---

*[src/BloomTests/Publish/ExportEpubTests.cs, line 115 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2510#-LFNR3BL-xmfKkfkhR0f:-LFSTLAx8hGMWTjceR6q:bj4rjc5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6dd48dc7bff5f317e99ecb907a7cb4ca1f139e8/src/BloomTests/Publish/ExportEpubTests.cs#L115)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I added a check of the folder structure to a number of existing unit tests.
</blockquote></details>

Nice. Will break every time we add a new file type, but I think that's good...makes sure we don't do it by accident.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2510#-:-LFSTWT185ViQcbW8DY6:bnfp4nl)*

**Comment by hatton** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @hatton and @StephenMcConnel)

---

*[src/BloomExe/Book/HtmlDom.cs, line 1484 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2510#-LFSYbOp3pBzlwidmBql:-LFSYbOp3pBzlwidmBqm:bs6ikub) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aa5cb18677e882761da2ab503ac9f29ea9ebca06/src/BloomExe/Book/HtmlDom.cs#L1484)):*
> ```Smalltalk
> 		/// or a div with an inline style with an background-image rule
> 		/// </summary>
> 		public static void SetImageElementUrl(ElementProxy imgOrDivWithBackgroundImage, UrlPathString url, bool urlEncode = true)
> ```

@StephenMcConnel  Is there a good reason to change this to having a default? It's very important that we all explicit choose this each time.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2510)*

**Comment by hatton** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @hatton and @StephenMcConnel)

---

*[src/BloomExe/Book/HtmlDom.cs, line 1484 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2510#-LFSYbOp3pBzlwidmBql:-LFSdPOqE-e0qsoW7sKD:b1o8pja) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aa5cb18677e882761da2ab503ac9f29ea9ebca06/src/BloomExe/Book/HtmlDom.cs#L1484)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I made the default to avoid changing existing code.  If you want the choice to always be explicit, I could certainly make the additional changes to do that (in a new PR).
</blockquote></details>

Steve I misread this, didn't see that it's a totally new parameter.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2510)*

**Pull request merged**
