### PR TITLE
BL-9493 TeamCollectionBookStatusPanel

### PR DESCRIPTION
**Pull request by gmartin7**
* Fix package.json so yarn scripts are visible
* Rename main component
* Get Storybook up and running
* Work on buttons
* Avatars - off to 5.1 and another card
* User log input - off to 5.1
* Get icon working right
* Change button color by lockState
* Put in all localized strings
* Move getLockedInfoChild() to StatusPanel
* Add theme
* Move button method to main file
* Move status panel common component back
   to teamCollection folder from react_components
* Add lockedByMeElsewhere status

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4191)

### CODE REVIEW

**Comment by gmartin7** [comment]
Apparently have some work to do on "locked" state (locked by other person)...

**Comment by hatton** [comment]
Do we really have to make tsx's for each icon?

Is there a reason to use .less files instead of inline styling?

**Review by gmartin7 — COMMENTED** [review]
I made tsx `SvgIcon` files for the icons because:
* it's simple to make the switch (just have to change (e.g.) fill-rule -> fillRule)
* it just works in both Bloom and Storybook (doing  doesn't work in Storybook)
* you get accessibility built in

I prefer .less files BY FAR to the `emotion` hackiness (and we don't have it in Bloom Desktop yet). Less files show the structure of the rules better and there are a number of rules in this case.

I could go with the material-ui `CSSProperties` method at a pinch (like in `colorSwatch.tsx`).

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4191#-:-MTNIh4BAtLHYhFnWS49:bcyf85a)* status: 0 of 14 files reviewed, all discussions resolved

**Review by gmartin7 — COMMENTED** [review]
drat! That comment should be `(doing img tag src=someSvgPath doesn't work in Storybook)`.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4191#-:-MTNPGyI7HKO1Rj2W9bX:b-7geicg)* status: 0 of 14 files reviewed, all discussions resolved

**Review by hatton — COMMENTED** [review]
> it's simple to make the switch (just have to change (e.g.) fill-rule -> fillRule)

Is there a color switching part to this task?

> you get accessibility built in

What does that mean?

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4191#-:-MTbjiRQEkVGbIrflmhf:bvzxtch)* status: 0 of 14 files reviewed, all discussions resolved

**Review by gmartin7 — COMMENTED** [review]
color switching: I don't think so
accessibility: I was just referring to the statement in the material-ui SVGIcon docs that says `It comes with built-in accessibility.`

So from discussion this morning, my understanding is that this PR's `.less` file isn't the way we're going eventually, but it's okay for now. Also, that we want to use plain-vanilla `.svg` files. I will figure out how to get them to work with storybook (using the `--static-dir` flag).

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4191#-:-MTfgLKgB7fcVXml-7aG:bm95h41)* status: 0 of 14 files reviewed, all discussions resolved

**Review by gmartin7 — COMMENTED** [review]
@hatton Are we ready to update `Available.svg/Check In.svg/Check Out.svg` with your latest Figma design?

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4191#-:-MTgY7cdAhUE5hTDZQKY:bg10o4r)* status: 0 of 15 files reviewed, all discussions resolved

**Review by andrew-polk — APPROVED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4191)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
