### PR TITLE
Make new collection tab show new download

### PR DESCRIPTION
**Pull request by JohnThomson**
- Responsibility for knowing to watch the downloaded books folder moved from LibraryLIstView to BookCollection
- Responsibility to debounce changes to the folder moved likewise
- Responsibility to decide whether a change to the folder should cause selecting the changed or added book moved to WorkspaceView
- new event when collection created allows WorkspaceView to attach to the folder changed event on the collection
- fixed other issues with deleting a book and side effects of selecting one

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4928)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4928)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Collection/BookCollection.cs, line 130 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4928#-MtxsPhTBPj3DpNQr2fJ:-MtxsPhU9XT32QZhRwZk:berakxd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a363bd364b9e38bed55f53ef1a3481a03dd5bab9/src/BloomExe/Collection/BookCollection.cs#L130)):*
> ```Smalltalk
> 							// I'm giving it a generous 10 seconds before paying attention to new changes to
> 							// this folder. Probably excessive, but this monitor is meant to catch new downloads;
> 							// it's unlikely the same book can be downloaded again within 10 seconds.
> ```

Do we want to move some or all of this comment into the new method?
___
*[src/BloomExe/Collection/BookCollection.cs, line 185 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4928#-MtxslzU1yqky-KRluhB:-MtxslzU1yqky-KRluhC:bsjlidz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a363bd364b9e38bed55f53ef1a3481a03dd5bab9/src/BloomExe/Collection/BookCollection.cs#L185)):*
> ```Smalltalk
> 			var infoToDelete = _bookInfos.FirstOrDefault(b => b.FolderPath == bookInfo.FolderPath);
> 			//Debug.Assert(_bookInfos.Contains(bookInfo)); this will occur if we delete a book from the BloomLibrary section
> 			_bookInfos.Remove(infoToDelete);
> ```

I guess Remove(null) will be ok?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4928)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/Collection/BookCollection.cs, line 130 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4928#-MtxsPhTBPj3DpNQr2fJ:-Mtyep3mBpynL3azIJ5J:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a363bd364b9e38bed55f53ef1a3481a03dd5bab9/src/BloomExe/Collection/BookCollection.cs#L130)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Do we want to move some or all of this comment into the new method?
</blockquote></details>

Done.
___
*[src/BloomExe/Collection/BookCollection.cs, line 185 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4928#-MtxslzU1yqky-KRluhB:-MtyepaB4pWHgQMibHOh:b-ftbjof) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a363bd364b9e38bed55f53ef1a3481a03dd5bab9/src/BloomExe/Collection/BookCollection.cs#L185)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I guess Remove(null) will be ok?
</blockquote></details>

Not sure. Shouldn't ever be null. I added a guard just in case.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4928)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4928)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
