### PR TITLE
Comply with more Epub 3.2 rules (BL-9067)

### PR DESCRIPTION
**Pull request by JohnThomson**
- contentinfo elements should not be nested
- tabindex should not be used (at least not with value > 0)
- displayTransformability should not use /resizeText

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3937)

### CODE REVIEW

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3937)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by StephenMcConnel — COMMENTED** [review]
A couple of minor naming quibbles that could be be ignored, but otherwise looks okay.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3937#-:-MHrsaLq2SuGPdaHytV5:b20tokq)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/ToPalaso/XmlExtensions.cs, line 32 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3937#-MHrs3q0ExpEGMAdXWhn:-MHrs3q14BdewyITAsnD:bpml0pz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/96dd2eac9014f627a0f93018cbb7e5699c45fc76/src/BloomExe/ToPalaso/XmlExtensions.cs#L32)):*
> ```Smalltalk
> 		/// </summary>
> 		/// <returns></returns>
> 		public static XmlElement ParentWithAttributeValue(this XmlElement start, string targetAttr, string targetVal)
> ```

Ancestor would be a better name than Parent for this method.
___
*[src/BloomTests/Publish/ExportEpubTestsBaseClass.cs, line 499 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3937#-MHrsLkw2goGeObNy-Ng:-MHrsLkw2goGeObNy-Nh:bi445ho) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/96dd2eac9014f627a0f93018cbb7e5699c45fc76/src/BloomTests/Publish/ExportEpubTestsBaseClass.cs#L499)):*
> ```Smalltalk
> 				{
> 				case "synchronizedAudioText": foundSynchronizedAudio = true; break;
> 				case "displayTransformability": foundResizeText = true; break;
> ```

should this variable be renamed?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3937)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @StephenMcConnel)

___
*[src/BloomExe/ToPalaso/XmlExtensions.cs, line 32 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3937#-MHrs3q0ExpEGMAdXWhn:-MHupdbQ95tu_qTEjJbD:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/96dd2eac9014f627a0f93018cbb7e5699c45fc76/src/BloomExe/ToPalaso/XmlExtensions.cs#L32)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Ancestor would be a better name than Parent for this method.
</blockquote></details>

Done.
___
*[src/BloomTests/Publish/ExportEpubTestsBaseClass.cs, line 499 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3937#-MHrsLkw2goGeObNy-Ng:-MHupeVqBcoevWfjES8Z:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/96dd2eac9014f627a0f93018cbb7e5699c45fc76/src/BloomTests/Publish/ExportEpubTestsBaseClass.cs#L499)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

should this variable be renamed?
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3937)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

**Pull request merged**
