### PR TITLE
Start of Publish to Android screen with supporting react components

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1734)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Why did axios move away from generics for the return type? Should we be doing something to verify or at least document what the return types are?

Should we be adding the new strings to Bloom.en.tmx?

---

Reviewed 28 of 48 files at r1.
Review status: 28 of 48 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[src/BloomBrowserUI/package.json, line 43 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Kohzn1Sz7ZEkkrokl4P:-Kohzn1Sz7ZEkkrokl4Q:b8ua3l4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/package.json#L43)):*
> ```JSON
>         "time-require": "^0.1.2",
>         "toastr": "^2.1.2",
>         "tslint": "^5.4.3",
> ```

Honestly, in our process, I haven't seen where it matters at all, but wouldn't it make more sense for this to be in devDependencies?

---

*[src/BloomBrowserUI/webpack.config.js, line 68 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi-MpuAoJGAgRi-Z5h:-Koi-MpuAoJGAgRi-Z5i:b-t1i2gj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/webpack.config.js#L68)):*
> ```JavaScript
>         // alias: {
>         //   "react-dom": pathToReactDom,
>         //   react: pathToReact // the point of this is to use the minified version. https://christianalfoni.github.io/react-webpack-cookbook/Optimizing-rebundling.html
> ```

Leaving this here, commented, implies we are not using the minified version.

---

*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 50 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi0BrwekyZI25aO78L:-Koi0BrwekyZI25aO78M:b1xildr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L50)):*
> ```XML
> import { TextFragment } from '../readers/libSynphony/bloomSynphonyExtensions';
> import axios from 'axios';
> //import Axios from "axios";
> ```

Wants to be deleted

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 8 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi0f7jsmqa351Bt3Fe:-Koi0f7jsmqa351Bt3Ff:b-shgfm4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L8)):*
> ```XML
> import { H1, H2, LocalizableElement, IUILanguageAwareProps } from "../../react_components/l10n";
> 
> interface ComponentState {
> ```

Not IComponentState?

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 20 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi0ndOnocN6NIm2FKz:-Koi0ndOnocN6NIm2FL-:bepext3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L20)):*
> overal

overall

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 35 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi13h_RZwnQD5EP405:-Koi13h_RZwnQD5EP406:b-vsov5o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L35)):*
> publish.android.learnAboutDigitalPublishingOptions

Don't we want to keep consistent casing with other l10n ids?

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 40 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi1PYKmy6qqdWa-nOG:-Koi1PYKmy6qqdWa-nOH:bqxp1kp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L40)):*
> Bloom Reader app

Other instances of this string below are "*the* Bloom Reader app"

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 58 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi1vvbnN1Ie3Ozp94N:-Koi1vvbnN1Ie3Ozp94O:bkuwjbr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L58)):*
> an device

a device

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 65 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi1yWKtyxxSAax5drg:-Koi1yWKtyxxSAax5drh:bi6rdk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L65)):*
> ```XML
>                 </BloomButton>
>                 <br />
>                 <BloomButton l10nkey="publish.android.connectWifi"
> ```

Don't we want to hide this button for now?

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 66 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi1tRtbmq_Srs-MTsZ:-Koi1tRtbmq_Srs-MTs_:b-omwuvg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L66)):*
> an device using a USB cable

a device using Wifi

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 70 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi1nEYwbdUByQnzNr3:-Koi1nEYwbdUByQnzNr4:buxfc5w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L70)):*
> Wifi

WiFi? or Wi-Fi? 

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 74 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi2BJf9RRYRCNFd7Cv:-Koi2BJf9RRYRCNFd7Cw:b-l6a4b7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L74)):*
> ```XML
> 
>                 <H1 l10nkey="publish.android.stepSend">
>                     Step 4: Send this book to the device.
> ```

This is the only step with a period at the end

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 77 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi24l082J7_MAYAhbv:-Koi24l082J7_MAYAhbw:bkuwjbr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L77)):*
> an device

a device

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 79 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi2HF5qkLdTg81LbXl:-Koi2HF5qkLdTg81LbXm:b6ot8a1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L79)):*
> connectWifi

sendBook

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-:-Koi-lti2LJrQuyC-6dL:bea17xd)*

**Comment by hatton** [comment]
Well, best I can tell, the project itself was not responsible for the TS typings that added that, but the project replaced them with internal ones that it maintains (which is better). People have made git issues about it, but, no action.

Too soon to bake in these string... I don't know if this is really the UI we'll ship with.

---

Review status: 28 of 48 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[src/BloomBrowserUI/package.json, line 43 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Kohzn1Sz7ZEkkrokl4P:-KoiBjd3FIMTFr6IUJD2:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/package.json#L43)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Honestly, in our process, I haven't seen where it matters at all, but wouldn't it make more sense for this to be in devDependencies?
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/webpack.config.js, line 68 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi-MpuAoJGAgRi-Z5h:-KoiBndb0y04w6hQWQOL:b7na9z8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/webpack.config.js#L68)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Leaving this here, commented, implies we are not using the minified version.
</blockquote></details>

That is true. Webpack has started complaining about being given minified source.

---

*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 50 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi0BrwekyZI25aO78L:-KoiC36lgvL_uCK_wj8h:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L50)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Wants to be deleted
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 8 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi0f7jsmqa351Bt3Fe:-KoiCAmnkfbDy-nhULX0:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L8)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Not IComponentState?
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 20 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi0ndOnocN6NIm2FKz:-KoiCDt40a4gm8CnpYrk:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L20)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> overal

overall
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 35 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi13h_RZwnQD5EP405:-KoiCrECDjwMn53q6cN3:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L35)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> publish.android.learnAboutDigitalPublishingOptions

Don't we want to keep consistent casing with other l10n ids?
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 40 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi1PYKmy6qqdWa-nOG:-KoiCwz-lIIlFvbGkZZk:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L40)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> Bloom Reader app

Other instances of this string below are "*the* Bloom Reader app"
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 58 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi1vvbnN1Ie3Ozp94N:-KoiD-NLXB0Zp7zVG4gT:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L58)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> an device

a device
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 65 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi1yWKtyxxSAax5drg:-KoiD1BVKezfi0dG1PBH:byh3wwv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L65)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Don't we want to hide this button for now?
</blockquote></details>

Sure... eventually...  understand this is just a working prototype, being PR'd now because you wanted it to build your actual work on to of it.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 66 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi1tRtbmq_Srs-MTsZ:-KoiDRwZkLwWMl1us8qt:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L66)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> an device using a USB cable

a device using Wifi
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 70 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi1nEYwbdUByQnzNr3:-KoiDhoq1RKhAWmja3Qq:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L70)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> Wifi

WiFi? or Wi-Fi? 
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 77 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi24l082J7_MAYAhbv:-KoiDne2qXN0dBU6NhvB:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L77)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> an device

a device
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 79 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi2HF5qkLdTg81LbXl:-KoiDy-8PeljCPZWVFKt:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L79)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> connectWifi

sendBook
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-:-KoiBSsR_5fnPFw8P3P2:bfoieec)*

**Comment by andrew-polk** [comment]
For now, we need to turn off Android in the Publish tab for Linux, but I can add that if you don't.

---

Reviewed 20 of 48 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/BloomBrowserUI/webpack.config.js, line 68 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Koi-MpuAoJGAgRi-Z5h:-KomunOPpJaaXShvJjES:b8mv8pa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/692e47bd98ad4d226f0a4c827ab36d29e661915e/src/BloomBrowserUI/webpack.config.js#L68)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

That is true. Webpack has started complaining about being given minified source.
</blockquote></details>

Perhaps a comment to that effect?

---

*[src/BloomBrowserUI/react_components/l10n.tsx, line 15 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Komvz5nqCA6eSnyPSAm:-Komvz5nqCA6eSnyPSAn:b-dpnse1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4f1127b9f445f1cd08405eaba33054a10a5dc5f9/src/BloomBrowserUI/react_components/l10n.tsx#L15)):*
> l10nkey

l10nKey

---

*[src/BloomBrowserUI/react_components/l10n.tsx, line 16 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Komw-lj8hv51hpo883K:-Komw-lj8hv51hpo883L:b-9713zt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4f1127b9f445f1cd08405eaba33054a10a5dc5f9/src/BloomBrowserUI/react_components/l10n.tsx#L16)):*
> l10ncomment

l10nComment

---

*[src/BloomBrowserUI/react_components/progressBox.tsx, line 9 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-Komwd0iRObMNEaEyspk:-Komwd0iRObMNEaEyspl:b-kn2qc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4f1127b9f445f1cd08405eaba33054a10a5dc5f9/src/BloomBrowserUI/react_components/progressBox.tsx#L9)):*
> progres

progress

---

*[src/BloomExe/ProjectContext.cs, line 112 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-KomxAtJx86_A2oh5eOm:-KomxAtJx86_A2oh5eOn:bjx7lmv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4f1127b9f445f1cd08405eaba33054a10a5dc5f9/src/BloomExe/ProjectContext.cs#L112)):*
> PublishToAndroidAPI

PublishToAndroidApi

---

*[src/BloomExe/Publish/AndroidView.cs, line 22 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-KomxMs44e72fL3ykUeL:-KomxMs44e72fL3ykUeM:b6y3u7w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4f1127b9f445f1cd08405eaba33054a10a5dc5f9/src/BloomExe/Publish/AndroidView.cs#L22)):*
> //TODO localization

You've done this now, I think.

---

*[src/BloomExe/Publish/PublishView.cs, line 485 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-KomyMg4mc7t5qAt4x5Z:-KomyMg4mc7t5qAt4x5_:b-wzpj6l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4f1127b9f445f1cd08405eaba33054a10a5dc5f9/src/BloomExe/Publish/PublishView.cs#L485)):*
> ```Smalltalk
> 					_androidControl.BackColor = saveBackGround; // keep own color.
> 																// Typically this control is dock.fill. It has to be in front of tableLayoutPanel1 (which is Left) for Fill to work.
> 					_androidControl.BringToFront();
> ```

This is also in the AndroidView code. Is it needed/desired in both places?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1734#-:-Komxu0LTENOiixDam-O:bpunk5b)*

**Comment by hatton** [comment]
Taking Andrew up on his offer to dot any remaining i's, merging.

**Pull request merged**
