### PR TITLE
Re-do fix for titles with linebreaks (BL-11717)

### PR DESCRIPTION
**Pull request by sujeffreyl**
Addresses the failing unit test BloomTests.Book.BookInfoTests.TitleSetter_FixesTitleWithXml. The \r\n is handled different by XmlDocument vs XElement. (Also, that path was previously not trimmed)

- - -
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5522)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
This might be a little confusing without looking at a bunch of things in Git.

Originally, we had functions in both Book and BookData. They were very similar, but they hadn't been combined in the past mainly because one used XMLDocument and one used XElement.
Round 1 fix: Fixes the BookData function (but not the Book function)
Round 2 fix: Steve attempts to combine the two. The Book function is now basically running the code from the BookData function.
However, XMLDocument and XElement treat \r\n differently, so that is 1 cause of the failing unit test.  (The other cause is that we now apply .Trim() to both, whereas we previously only apply it in the BookData scenario. That's easy to fix though)
Round 3 fix: I do it the other way around... still combined, but using the Book function as the base for both instead of BookData as the base for both. There's still some risk in how the 2 might Parse/Load documents differently... but hopefully it doesn't really matter.  (IDK. BookData mostly uses XElement, but there is one reference to XmlDocument)

The other idea is to give up yet again on fully combining the 2 functions. But I feel like we're as close as we'll ever be to pulling it off.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5522#-:-NG2TeW02jgNjwGYQxss:bzbblfw)* status: 0 of 2 files reviewed, all discussions resolved

**Comment by andrew-polk** [comment]
Marking as draft pending discussion in the card.

**Review by sujeffreyl — COMMENTED** [review]
I merged this work with the less-risky version of it in 5.4. I changed this PR to target master now.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5522#-:-NGd1zpJEpOTIEA-NNjF:b-v1iywv)* status: 0 of 4 files reviewed, all discussions resolved

**Review by JohnThomson — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5522)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5522)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[`src/BloomTests/Book/BookTests.cs` line 4633 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5522#-NHBXspj65NCYhVXLqR5:-NHBXspk6a_wJcagVg8b:b-gk28ly) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e58a2f9f9996f613a0b30ac573ae4febf082db6/src/BloomTests/Book/BookTests.cs#L4633)):*
> ```Smalltalk
> 			
> 			Assert.That(result, Is.EqualTo("Enter Shift-Enter Last Line "));
> 		}
> ```

Seems like we should have at least one unit test for each of the (now three) enumeration members. It might work to just change the param and output of two of these.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5522)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomTests/Book/BookTests.cs` line 4633 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5522#-NHBXspj65NCYhVXLqR5:-NHPuPkcE9t9BmKgq6QO:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e58a2f9f9996f613a0b30ac573ae4febf082db6/src/BloomTests/Book/BookTests.cs#L4633)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Seems like we should have at least one unit test for each of the (now three) enumeration members. It might work to just change the param and output of two of these.
</blockquote></details>

Done.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5522)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Pull request merged**
