### PR TITLE
Minor cleanup for WebView2 (BL-11362)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5345)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5345)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomExe/GeckoFxBrowser.cs` line 1319 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5345#-N9gVJoq9QIPsbS6xRTR:-N9gVJoq9QIPsbS6xRTS:b4o3bil) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fb454e42ed7474a90548f88cf26fce4167c7acdf/src/BloomExe/GeckoFxBrowser.cs#L1319)):*
> ```Smalltalk
> 		/// so that it can open the file or external website itself.
> 		/// </summary>
> 		public void HandleLinkClick(GeckoAnchorElement anchor, DomEventArgs eventArgs, string workingDirectoryForFileLinks)
> ```

So this is just never used?
___
*[`src/BloomExe/IBrowser.cs` line 21 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5345#-N9gUY0w9-s5tB960ZRw:-N9gUY0w9-s5tB960ZRx:b17fvmr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7f843b5fa1094d392d35ca38cb108389c4e0ee91/src/BloomExe/IBrowser.cs#L21)):*
> ```Smalltalk
> 	public abstract class Browser : UserControl
> 	{
> 		public const string CdataPrefix = "/*<![CDATA[*/";
> ```

I don't totally know what these are, but do they really belong in the browser stuff at all? Could they go to `XmlHtmlConverter`?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5345)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[`src/BloomExe/GeckoFxBrowser.cs` line 1319 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5345#-N9gVJoq9QIPsbS6xRTR:-N9gYmRaEgHOj4S5d_in:b7u03hh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fb454e42ed7474a90548f88cf26fce4167c7acdf/src/BloomExe/GeckoFxBrowser.cs#L1319)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

So this is just never used?
</blockquote></details>

Correct
___
*[`src/BloomExe/IBrowser.cs` line 21 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5345#-N9gUY0w9-s5tB960ZRw:-N9gYpoH7-BL2WyzHjOn:bkoxbn1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7f843b5fa1094d392d35ca38cb108389c4e0ee91/src/BloomExe/IBrowser.cs#L21)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I don't totally know what these are, but do they really belong in the browser stuff at all? Could they go to `XmlHtmlConverter`?
</blockquote></details>

Yeah, I wasn't sure where they should go. I did wonder about XmlHtmlConverter myself. I'll move them there.

**Review by hatton — COMMENTED** [review]
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5345)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5345)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/BloomExe/GeckoFxBrowser.cs` line 1319 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5345#-N9gVJoq9QIPsbS6xRTR:-N9gZW5g8NxiebMpJKUf:b-t1xpff) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fb454e42ed7474a90548f88cf26fce4167c7acdf/src/BloomExe/GeckoFxBrowser.cs#L1319)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Correct
</blockquote></details>

Was true even in 5.3, apparently.
___
*[`src/BloomExe/IBrowser.cs` line 21 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5345#-N9gUY0w9-s5tB960ZRw:-N9gZZ0p0LtlzjUJbskL:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7f843b5fa1094d392d35ca38cb108389c4e0ee91/src/BloomExe/IBrowser.cs#L21)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Yeah, I wasn't sure where they should go. I did wonder about XmlHtmlConverter myself. I'll move them there.
</blockquote></details>

Done.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5345)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomExe/GeckoFxBrowser.cs` line 1140 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5345#-N9g_YIAEyrHBtgCIPv6:-N9g_YIB4PbYHtKJ9HYb:bloo87d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/488e75cb2c64640b252f031d1477235911b61939/src/BloomExe/GeckoFxBrowser.cs#L1140)):*
> ```Smalltalk
> 		/// xhtml characters like >.
> 		/// </summary>
> 		public static string WrapUserStyleInCdata(string innerCssStyles)
> ```

Sorry to drag this out, but now it becomes clear that his whole method should move to `HtmlDom`, its only user. I didn't look closely enough to see if this `cDataprefix` really does need to be in common between this and the XMLHtmlCOnverter or not.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5345)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[`src/BloomExe/GeckoFxBrowser.cs` line 1140 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5345#-N9g_YIAEyrHBtgCIPv6:-N9geqE31kNyhqT5-hzj:b-fby2tp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/488e75cb2c64640b252f031d1477235911b61939/src/BloomExe/GeckoFxBrowser.cs#L1140)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Sorry to drag this out, but now it becomes clear that his whole method should move to `HtmlDom`, its only user. I didn't look closely enough to see if this `cDataprefix` really does need to be in common between this and the XMLHtmlCOnverter or not.
</blockquote></details>

No worries. I'm glad to move things forward more cleanly.
The method was also used in GeckoFxBrowser, but I've factored it out now.

**Review by hatton — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5345)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @hatton)

**Review by hatton — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5345)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Pull request merged**
