### PR TITLE
Prevent edits when not checked out (BL-9780)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4357)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4357)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx, line 15 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4357#-MYB_o7wDyZ2rO3Ls_0L:-MYB_o7wDyZ2rO3Ls_0M:b-wkh87z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a6f891ec1e7c2c195432b40347d4daebc21a6825/src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx#L15)):*
> ```XML
>         "teamCollection/needsCheckoutToEdit",
>         false
>     );
> ```

I'm having a hard time with each place the publish UI is asking TCManager if the book can be edited.
It feels like the publish UI shouldn't know about TCManager but should ask some other object if the book is editable.

Perhaps collection? But I fully admit that I don't have a good grasp of how the model works between TCManager, TCCollection, and Collection.
Perhaps book? But I understand your concern that a book not know about team collections, either, so that doesn't seem right.

Taking my thoughts a different direction... the logic here of editable fields in publish view being enabled should be the same logic for the enabling of the edit tab, right?
So in which API would it make sense to expose WorkspaceModel.EditTabLocked? CommonAPI?
If you agree, that should be the one source of truth for if the current book can be edited, then it seems that the context menu should utilize that, too.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 163 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4357#-MYB_CF894Kj8ZacwCK9:-MYB_CF9DZwwN4dgeIA0:b-fwiy9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a6f891ec1e7c2c195432b40347d4daebc21a6825/src/BloomExe/CollectionTab/LibraryListView.cs#L163)):*
> ```Smalltalk
> 					else
> 					{
> 						menuItem.Enabled = true;
> ```

I think this would feel a little cleaner/better/faster if we had an early return before the foreach.
Or is the problem that we need to re-enable items if the user opens the menu, checks out the book, then opens the menu again?
___
*[src/BloomExe/Publish/PublishView.cs, line 41 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4357#-MYBXYv_-3N-E90aCnN-:-MYBXYv_-3N-E90aCnN0:b-o5g45w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a6f891ec1e7c2c195432b40347d4daebc21a6825/src/BloomExe/Publish/PublishView.cs#L41)):*
> ```Smalltalk
> 		private PublishEpubApi _publishEpubApi;
> 		private BloomWebSocketServer _webSocketServer;
> 		private TeamCollectionManager _tcManager;
> ```

Feels like this would be more natural in PublishModel. What do you think?
Then BloomLibraryUploadControl can just ask the model if the book can be edited.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4357)* status: 5 of 18 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx, line 15 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4357#-MYB_o7wDyZ2rO3Ls_0L:-MYFkegQ2ccdxcNzG-iX:b-l9nz6j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a6f891ec1e7c2c195432b40347d4daebc21a6825/src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx#L15)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm having a hard time with each place the publish UI is asking TCManager if the book can be edited.
It feels like the publish UI shouldn't know about TCManager but should ask some other object if the book is editable.

Perhaps collection? But I fully admit that I don't have a good grasp of how the model works between TCManager, TCCollection, and Collection.
Perhaps book? But I understand your concern that a book not know about team collections, either, so that doesn't seem right.

Taking my thoughts a different direction... the logic here of editable fields in publish view being enabled should be the same logic for the enabling of the edit tab, right?
So in which API would it make sense to expose WorkspaceModel.EditTabLocked? CommonAPI?
If you agree, that should be the one source of truth for if the current book can be edited, then it seems that the context menu should utilize that, too.
</blockquote></details>

I moved it into current and renamed it.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 163 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4357#-MYB_CF894Kj8ZacwCK9:-MYBxWj97_GwpCsV--P_:b4x9pd1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a6f891ec1e7c2c195432b40347d4daebc21a6825/src/BloomExe/CollectionTab/LibraryListView.cs#L163)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this would feel a little cleaner/better/faster if we had an early return before the foreach.
Or is the problem that we need to re-enable items if the user opens the menu, checks out the book, then opens the menu again?
</blockquote></details>

Menu items were never before disabled, only hidden. So it seemed likely to me that we might need to do something to make sure they are enabled when they should be. If it's not needed now, it at least makes things more robust.
___
*[src/BloomExe/Publish/PublishView.cs, line 41 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4357#-MYBXYv_-3N-E90aCnN-:-MYGHa5e4sVAen00M0dg:b-ujk046) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a6f891ec1e7c2c195432b40347d4daebc21a6825/src/BloomExe/Publish/PublishView.cs#L41)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Feels like this would be more natural in PublishModel. What do you think?
Then BloomLibraryUploadControl can just ask the model if the book can be edited.
</blockquote></details>

I settled on an approach that doesn't need a TC at all, so all changes to both the view and model went away.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4357)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx, line 15 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4357#-MYB_o7wDyZ2rO3Ls_0L:-MYGLFos5FzgDSgkz-3e:b-pne6ww) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a6f891ec1e7c2c195432b40347d4daebc21a6825/src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx#L15)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I moved it into current and renamed it.
</blockquote></details>

I'm not sure if you missed my suggestion to make the book's context menu also use this or if you decided not to for some reason.
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 458 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4357#-MYGLUun0HzgzIwfmiuL:-MYGLUun0HzgzIwfmiuM:b-heok7s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7f8b473ee97db12482fb2797bf07ff3fc0c980e/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L458)):*
> ```Smalltalk
> 
> 			// We can edit it unless TC says we need a checkout to do it.
> 			return !_tcManager.NeedCheckoutToEdit(_bookSelection.CurrentSelection.FolderPath);
> ```

It looks like we lost the check for registration being sufficient. 
Do we need to include that check at any of the callers?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4357)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx, line 15 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4357#-MYB_o7wDyZ2rO3Ls_0L:-MYGalbt6NjGhGLRuOWF:bgnrgwy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a6f891ec1e7c2c195432b40347d4daebc21a6825/src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx#L15)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not sure if you missed my suggestion to make the book's context menu also use this or if you decided not to for some reason.
</blockquote></details>

The context menu code is tied to the book associated with a particular button. It's possible that we currently only support this menu for the selected book or that it becomes the selected book before this code runs, but I didn't want to count on that. So I'm not using the API that asks whether the current book is editable.
I looked into giving that method an optional argument for which book to test. But it would want a book object and the current context doesn't have one, only a BookInfo.
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 458 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4357#-MYGLUun0HzgzIwfmiuL:-MYGcbEMB_kUA0cTtIxO:b-fhfn7q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7f8b473ee97db12482fb2797bf07ff3fc0c980e/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L458)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

It looks like we lost the check for registration being sufficient. 
Do we need to include that check at any of the callers?
</blockquote></details>

Our current policy for all other ways TC can be disabled is that if you already have the book checked out, you can go on editing it. It seemed reasonable to me to apply that to this case also.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4357)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
