### PR TITLE
BL-9016 order ePub audio by playback ordering

### PR DESCRIPTION
**Pull request by gmartin7**
* works in Simply Reading app
* in Readium preview, the audio will start with the first text box on the page,
   whether that is the first in the playback order or not. This can result in
   some audio not playing.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3973)

### CODE REVIEW

**Review by gmartin7 — COMMENTED** [review]
I looked in the `readium-js-viewer` repo for any open audio issues and didn't find this one. :(

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3973#-:-MIW-3oi8idyR52jBJYe:bikk5av)* status: 0 of 1 files reviewed, all discussions resolved

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Let's discuss the impact tomorrow morning.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3973#-:-MIW99MU2p7HCxc-R_q5:b-1mgceg)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 708 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3973#-MIW8r4BE1cS2BZV88n-:-MIW8r4BE1cS2BZV88n0:b3ut9l2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6cc0ab2cd7496e78369a555d25bc6e21f45b3cb/src/BloomExe/Publish/Epub/EpubMaker.cs#L708)):*
> ```
> orderedAudioSentenceElements.Count() > 1
> ```
orderedAudioSentenceElements.Any() would be one less iteration.
Should we just make `orderedAudioSentenceElements = OrderByTabindex(audioSentenceElementsWithRecordedAudio).ToList()`?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3973)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 708 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3973#-MIW8r4BE1cS2BZV88n-:-MIZbO4o40KdNOwBBu9o:b-8nu8q6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6cc0ab2cd7496e78369a555d25bc6e21f45b3cb/src/BloomExe/Publish/Epub/EpubMaker.cs#L708)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> orderedAudioSentenceElements.Count() > 1
> ```
orderedAudioSentenceElements.Any() would be one less iteration.
Should we just make `orderedAudioSentenceElements = OrderByTabindex(audioSentenceElementsWithRecordedAudio).ToList()`?
</blockquote></details>

Any() is not equal to Count > 1. Not sure how to use Any() in this case.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3973)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 708 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3973#-MIW8r4BE1cS2BZV88n-:-MIZmdAPEfAwBs5bMCQK:b8sd2s0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6cc0ab2cd7496e78369a555d25bc6e21f45b3cb/src/BloomExe/Publish/Epub/EpubMaker.cs#L708)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Any() is not equal to Count > 1. Not sure how to use Any() in this case.
</blockquote></details>

I did make the .ToList() change, but now I'm going to close the PR.

**Comment by gmartin7** [comment]
Closing this PR because of the Readium preview "side-effect". We may re-evaluate if either Readium2 releases or we get complaints.

**Pull request closed without merging**
