### PR TITLE
Fix a pair of i18n problems in TypeScript code (BL-5314)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2128)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/js/bloomImages.ts, line 250 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2128#-L4DGBBOZoy2UOQBkPD-:-L4DGBBPiPxNyI55ERKJ:b-fv8te4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6a813ac4946e780023d9d1f3871ad84f695e05a6/src/BloomBrowserUI/bookEdit/js/bloomImages.ts#L250)):*
This method has this warning:

> WARNING! This gets the translated text only if it is already loaded. Otherwise it just gives English back and will give translation next time.
     * Instead, use asyncGetTextInLang().

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2128)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/bloomImages.ts, line 253 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2128#-L4I1tFWxlZ_zCczcLvu:-L4I1tFWxlZ_zCczcLvv:bjqmc5r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ebe01c8d1d155204e44ed998ccf788da92f8636c/src/BloomBrowserUI/bookEdit/js/bloomImages.ts#L253)):*
> ```XML
>             .done(translation => {
>                var title = translation.replace(/'/g, "&apos;");
>                 $(container).prepend("<button class='editMetadataButton imageButton imgMetadataProblem " + buttonModifier +
> ```

Can we use typescript string interpolation here to prevent duplicating strings? Same below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2128)*

**Comment by StephenMcConnel** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/bloomImages.ts, line 250 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2128#-L4DGBBOZoy2UOQBkPD-:-L4IQwxcI2zyTxngJJB8:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6a813ac4946e780023d9d1f3871ad84f695e05a6/src/BloomBrowserUI/bookEdit/js/bloomImages.ts#L250)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This method has this warning:

> WARNING! This gets the translated text only if it is already loaded. Otherwise it just gives English back and will give translation next time.
     * Instead, use asyncGetTextInLang().
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/js/bloomImages.ts, line 253 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2128#-L4I1tFWxlZ_zCczcLvu:-L4IUsuqu0YD02KAqL5u:b-iav500) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ebe01c8d1d155204e44ed998ccf788da92f8636c/src/BloomBrowserUI/bookEdit/js/bloomImages.ts#L253)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Can we use typescript string interpolation here to prevent duplicating strings? Same below.
</blockquote></details>

I've changed to using string interpolation, but I don't think it buys anything except looking nicer.  The generated javascript is identical to what I had before.  String interpolation is just syntactic sugar as I understand it.  I had thought of using it, but when I read about it, it doesn't work like a named format string in C# which is interpreted by a method call and can be reused to give a different result when the variable (s) change and the format is interpreted again by another method call.  It's interpreted once where it's defined.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2128)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/bloomImages.ts, line 253 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2128#-L4I1tFWxlZ_zCczcLvu:-L4LeY4eXg7_IKz-QTWy:b955eqd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ebe01c8d1d155204e44ed998ccf788da92f8636c/src/BloomBrowserUI/bookEdit/js/bloomImages.ts#L253)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I've changed to using string interpolation, but I don't think it buys anything except looking nicer.  The generated javascript is identical to what I had before.  String interpolation is just syntactic sugar as I understand it.  I had thought of using it, but when I read about it, it doesn't work like a named format string in C# which is interpreted by a method call and can be reused to give a different result when the variable (s) change and the format is interpreted again by another method call.  It's interpreted once where it's defined.
</blockquote></details>

The goal was to let you not duplicate the strings in the fail functions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2128)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/bloomImages.ts, line 253 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2128#-L4I1tFWxlZ_zCczcLvu:-L4MaM0UQ59GmYsjRhsu:b58w5e8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ebe01c8d1d155204e44ed998ccf788da92f8636c/src/BloomBrowserUI/bookEdit/js/bloomImages.ts#L253)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The goal was to let you not duplicate the strings in the fail functions.
</blockquote></details>

I've rewritten the code to eliminate as much string duplication as I think reasonable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2128)*

**Comment by andrew-polk** [comment]
*[src/BloomBrowserUI/bookEdit/js/bloomImages.ts, line 265 at r4](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2128#-L4MsSdXnmGbHDtWYFVs:-L4MsSdXnmGbHDtWYFVt:bxmx9ie) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ff414b1015a22ec193bd7c412406818a7ba65d08/src/BloomBrowserUI/bookEdit/js/bloomImages.ts#L265)):*
> AltMsg2

Was this an inadvertent change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2128)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/bloomImages.ts, line 253 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2128#-L4I1tFWxlZ_zCczcLvu:-L4MwXCF30FNhRgyNMIP:b-3ecx5y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ebe01c8d1d155204e44ed998ccf788da92f8636c/src/BloomBrowserUI/bookEdit/js/bloomImages.ts#L253)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I've rewritten the code to eliminate as much string duplication as I think reasonable.
</blockquote></details>

Sorry for complicating things. I used the term string interpolation, but what I actually meant was string formatting with parameters where you can define the parameters after the fact.
So, similar C# code would be
string.Format("<button class='editMetadataButton imageButton imgMetadataProblem ${0}' title='${1}'></button>", GetButtonModifier(container), title);
vs.
string.Format("<button class='editMetadataButton imageButton imgMetadataProblem ${0}' title='${1}'></button>", GetButtonModifier(container), englishText);
But apparently, there is no simple way to do this in js/ts land.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2128)*

**Comment by StephenMcConnel** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/bloomImages.ts, line 265 at r4](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2128#-L4MsSdXnmGbHDtWYFVs:-L4N3OdLkM9HtSq3itsm:bpbwkyh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ff414b1015a22ec193bd7c412406818a7ba65d08/src/BloomBrowserUI/bookEdit/js/bloomImages.ts#L265)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> AltMsg2

Was this an inadvertent change?
</blockquote></details>

oops.  yes.  I've pushed a fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2128)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2128#-:-L4N4X0c34zNM_jk3LpP:bnfp4nl)*

**Pull request merged**
