### PR TITLE
Adjust height of boxes in Setup Decodable Reader Stages dialog (BL-2938)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
Reduce the height so that a scroll bar doesn't display immediately.

[Review on Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/873)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[src/BloomBrowserUI/bookEdit/readerSetup/ReaderSetup.jade, line 61 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/873#-K3GhSY3eObSv04QgADJ)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8bf14dacb85200cd79da7e68fed9ef17370b6ad6/src/BloomBrowserUI/bookEdit/readerSetup/ReaderSetup.jade#L61)):</sup>
I find it suspicious that two values are both reduced to 297, but one started at 328 and one at 330.
It's also generally undesirable to have styles like this stored in jade/html. I know you found it this way, but does this magic number (297) have any significance that we could call out by naming the style these elements have or even giving a .less name to the dimension? Is this height calculated from any other dimensions in a way we could bring out in less?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/873)

**Comment by JohnThomson** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/873)

**Comment by StephenMcConnel** [comment]
redone using flexboxes (with JohnT's help)

**Comment by JohnThomson** [comment]
LGTM (with a minor suggestion). But it was partly my idea...probably John Hatton should review also.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.less, line 169 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/873#-K3KneIvmVpNCHYgF1yU:-K3KneIvmVpNCHYgF1yV:-1841998451) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95463cd5a615e5a8a1fce507c9752f1b122eb2fe/src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.less#L169)):_
Some comments may be worth adding--something like "a container which is expected to have as direct children a flex-top-section and a flex-bottom-section. The top-section will be just big enough to hold its content; the bottom section will fill the rest of the space (as this container will fill the space its parent makes available).
The names are actually too specific; top-section should work for any child that should size to its content, and more than one bottom-section should share the remaining space available. But we haven't tried it beyond the simple top/bottom arrangement."
I'm also wondering whether we need the reader-setup prefixes. These styles could well be useful elsewhere.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/873#-:-K3KoiYJAmyUDsEdRRze:1505508390)_

**Comment by StephenMcConnel** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.less, line 169 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/873#-K3KneIvmVpNCHYgF1yU:-K3LNhAEvuQb3iZZqWM8:-867864505) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95463cd5a615e5a8a1fce507c9752f1b122eb2fe/src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.less#L169)):_
Done.  I've renamed the classes to something more functionally descriptive, and added a comment describing the classes.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/873)_

**Comment by JohnThomson** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/873)_

**Pull request merged**
