### PR TITLE
BL-12404 book-on-blorg badges

### PR DESCRIPTION
**Pull request by nabalone**
- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6075)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
Looks good. A few minor things.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6075#-:-Nd2J3P31bLeqwF6el7c:bk8cpmf)* status: all files reviewed, 4 unresolved discussions (waiting on @nabalone)

___
*[`src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx` line 30 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6075#-Nd2HNjSBuvazTILGPlP:-Nd2HNjSBuvazTILGPlQ:b-5eqffx) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d4b9e20b4bb04c579751eb630de5176b23cc9dc4/src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx#L30)):*
> console.log("result", result);

Let's go ahead and remove this.
___
*[`src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx` line 36 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6075#-Nd2HYR12mW35OrHSGtY:-Nd2HYR12mW35OrHSGtZ:b2mzil3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d4b9e20b4bb04c579751eb630de5176b23cc9dc4/src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx#L36)):*
> ```XML
>                     if (result.data.draft) {
>                         setBadge(BadgeType.Draft);
>                     } else if (result.data.inCirculation == false) {
> ```

=== rather than ==
___
*[`src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx` line 56 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6075#-Nd2IGZbDcUj2WyZ_KFL:-Nd2IGZbDcUj2WyZ_KFM:b-yard5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d4b9e20b4bb04c579751eb630de5176b23cc9dc4/src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx#L56)):*
> ```XML
>             updateBadges();
>         }
>     );
> ```

Do we already re-render all the buttons when entering the collections tab?
If so, it doesn't seem like we need this?
___
*[`src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx` line 71 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6075#-Nd2Hqrs7m1Cxjl1tSmP:-Nd2Hqrs7m1Cxjl1tSmQ:b-wv4p9t) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d4b9e20b4bb04c579751eb630de5176b23cc9dc4/src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx#L71)):*
> ```XML
>         >
>             <React.Fragment>
>                 {badge != BadgeType.None && (
> ```

!== rather than !=

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6075)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx` line 30 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6075#-Nd2HNjSBuvazTILGPlP:-Nd6Ey861zOEAodWv5gK:b34car6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d4b9e20b4bb04c579751eb630de5176b23cc9dc4/src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx#L30)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> console.log("result", result);

Let's go ahead and remove this.
</blockquote></details>

Done. Sorry I keep doing this. I am now trying to write myself a git hook that will catch these 
___
*[`src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx` line 36 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6075#-Nd2HYR12mW35OrHSGtY:-Nd6FJaIBzVQQUXeIr-z:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d4b9e20b4bb04c579751eb630de5176b23cc9dc4/src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx#L36)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

=== rather than ==
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx` line 56 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6075#-Nd2IGZbDcUj2WyZ_KFL:-Nd6Kqcf4H-FrtowUeRz:bbx28ff) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d4b9e20b4bb04c579751eb630de5176b23cc9dc4/src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx#L56)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Do we already re-render all the buttons when entering the collections tab?
If so, it doesn't seem like we need this?
</blockquote></details>

The buttons do not automatically re-render for me
___
*[`src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx` line 71 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6075#-Nd2Hqrs7m1Cxjl1tSmP:-Nd6FXdZ3Elyi1szC40p:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d4b9e20b4bb04c579751eb630de5176b23cc9dc4/src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx#L71)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

!== rather than !=
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6075)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)

___
*[`src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx` line 30 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6075#-Nd2HNjSBuvazTILGPlP:-Nd6OxJ_8mkNVvtigY5s:bep3uba) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d4b9e20b4bb04c579751eb630de5176b23cc9dc4/src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx#L30)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Done. Sorry I keep doing this. I am now trying to write myself a git hook that will catch these
</blockquote></details>

At one time, we tried to add a git hook which would catch lines //nocommit, so we could add such a comment after a line like this.
I'm not sure what happened to it.
But if you come up with something useful, we should have the whole team use it.

The best prevention is to do a self-code review.

But it's also not a big deal. We all do it.
___
*[`src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx` line 56 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6075#-Nd2IGZbDcUj2WyZ_KFL:-Nd6PPku-54UUUWai1qr:b-d5rsdk) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d4b9e20b4bb04c579751eb630de5176b23cc9dc4/src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx#L56)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

The buttons do not automatically re-render for me
</blockquote></details>

Interesting. There must be some mechanism by which we update the book thumbnails.
That should, in theory, be refreshing a single book rather than all.
It is probably worth 15 minutes to see how easy it would be to refresh just the book we uploaded.
___
*[`src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx` line 71 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6075#-Nd2Hqrs7m1Cxjl1tSmP:-Nd6Pg-_2KVVtddlxK2q:b598n3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d4b9e20b4bb04c579751eb630de5176b23cc9dc4/src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx#L71)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks. I see you also found and fixed other places.
Is this being flagged by eslint?
Do you have the eslint extension?
If it isn't being flagged, we should probably look at adding the rule to make it.

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6075)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx` line 56 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6075#-Nd2IGZbDcUj2WyZ_KFL:-Nd7GRIU0L9S1iAE3O40:b-7yo9lz) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d4b9e20b4bb04c579751eb630de5176b23cc9dc4/src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx#L56)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Interesting. There must be some mechanism by which we update the book thumbnails.
That should, in theory, be refreshing a single book rather than all.
It is probably worth 15 minutes to see how easy it would be to refresh just the book we uploaded.
</blockquote></details>

Done. I didn't use the same websocket event as the thumbnail image updates because they update when the book is modified whereas we want to update when the book is published to blorg
___
*[`src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx` line 71 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6075#-Nd2Hqrs7m1Cxjl1tSmP:-Nd7GxN4-rVQld1kWysL:b-e701ks) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d4b9e20b4bb04c579751eb630de5176b23cc9dc4/src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx#L71)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Thanks. I see you also found and fixed other places.
Is this being flagged by eslint?
Do you have the eslint extension?
If it isn't being flagged, we should probably look at adding the rule to make it.
</blockquote></details>

I do have ESlint and it's not flagging

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6075)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nabalone)

___
*[`src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx` line 71 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6075#-Nd2Hqrs7m1Cxjl1tSmP:-Nd7KvP80kMiInXk_yeD:b2s21ey) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d4b9e20b4bb04c579751eb630de5176b23cc9dc4/src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx#L71)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

I do have ESlint and it's not flagging
</blockquote></details>

Ok, thanks. I've added it as a warning on master.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6075)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nabalone)

**Pull request merged**
