### PR TITLE
BL-10015 Improve error, info, and caution boxes

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4510)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
Looks good with one minor puzzle. May not be worth fixing...up to you.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4510#-:-MajJfS1093Y5JwArVU9:b-h44ugq)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx, line 134 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4510#-MajIagu61arBAFWYhjk:-MajIagv5L7q5FRAA9fg:b-9oxf52) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/36de585ebe493fad29222eeccd4389946384ade8/src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx#L134)):*
> ```XML
> 
>                 p {
>                     // removing these leaves us with just
> ```

removing what? I'm not following.

**Review by StephenMcConnel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4510)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx, line 151 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4510#-MajKpXi24sP8BkHHErM:-MajKpXi24sP8BkHHErN:bs2g6uc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/36de585ebe493fad29222eeccd4389946384ade8/src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx#L151)):*
> ```XML
>                     Matching local collection:
>                 </Span>
> ```

Are we sure we don't want that space between the label span and the content span?  (and elsewhere as well)
(I'll take your word that removing these space spans is the Right Thing To Do.)

**Review by hatton — COMMENTED** [review]
oooh 2 reviewers. Feels luxurious!

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4510#-:-MajenJdDqfJAePUIX5n:bn2cbxw)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton)

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4510)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson and @StephenMcConnel)

___
*[src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx, line 134 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4510#-MajIagu61arBAFWYhjk:-Mb1Wu7U61TdIkq9Sw9t:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/36de585ebe493fad29222eeccd4389946384ade8/src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx#L134)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

removing what? I'm not following.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx, line 151 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4510#-MajKpXi24sP8BkHHErM:-Mb1XCtV9DnUMJODn3CA:b-2bh3u2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/36de585ebe493fad29222eeccd4389946384ade8/src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx#L151)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Are we sure we don't want that space between the label span and the content span?  (and elsewhere as well)
(I'll take your word that removing these space spans is the Right Thing To Do.)
</blockquote></details>

Oh, sorry. I didn't know until reading up on it just now that `<span> </span>` creates a space.  I took it just be a NOP. Put in a `{" "}` which seems to be the current react idiomatic way.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4510)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @JohnThomson and @StephenMcConnel)

___
*[src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx, line 134 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4510#-MajIagu61arBAFWYhjk:-MbCZbxPD12uJNORuAl-:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/36de585ebe493fad29222eeccd4389946384ade8/src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx#L134)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx, line 151 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4510#-MajKpXi24sP8BkHHErM:-MbCZbZo-Dtngf8gnDgZ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/36de585ebe493fad29222eeccd4389946384ade8/src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx#L151)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Oh, sorry. I didn't know until reading up on it just now that `<span> </span>` creates a space.  I took it just be a NOP. Put in a `{" "}` which seems to be the current react idiomatic way.
</blockquote></details>

Done.

**Pull request merged**
