### PR TITLE
BL-5437 Get talking ePub to Save

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2077)

### CODE REVIEW

**Comment by StephenMcConnel** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Publish/AudioProcessor.cs, line 27 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2077#-L3Fazsp7kNnPpoTmpnC:-L3Fazsp7kNnPpoTmpnD:bl7o1ye) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/13fc82a31884c5f15b41988296f22423cec94fac/src/BloomExe/Publish/AudioProcessor.cs#L27)):*
> ```Smalltalk
> 		/// results. (See BL-5437)
> 		/// </summary>
> 		public static bool IsAnyCompressedAudioMissing(string bookFolderPath, XmlDocument dom)
> ```

okay, you're reminding the caller what the inputs need to be.  seems reasonable.  :-)

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1347 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2077#-L3Fb5-ZAVoTXZilcvRW:-L3Fb5-ZAVoTXZilcvRX:b-dim7mn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/13fc82a31884c5f15b41988296f22423cec94fac/src/BloomExe/Publish/Epub/EpubMaker.cs#L1347)):*
> ```Smalltalk
> 			// the comparison is unreliable (.wav files are larger and take longer to copy than the corresponding .mp3 files).
> 			// So we compare the original book's audio files to determine if any are missing -- BL-5437
> 			return PublishWithoutAudio || !AudioProcessor.IsAnyCompressedAudioMissing(_originalBook.FolderPath, Book.RawDom);
> ```

nice catch of a seemingly trivial difference.  I assume you've tested this enough to be sure it works.  :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2077)*

**Comment by StephenMcConnel** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2077)*

**Comment by StephenMcConnel** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2077#-:-L3FbqORZp3KG7Ggaqn0:bnfp4nl)*

**Comment by StephenMcConnel** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2077)*

**Comment by gmartin7** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1347 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2077#-L3Fb5-ZAVoTXZilcvRW:-L3FdEu0qAlJ-3KqWy0F:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/13fc82a31884c5f15b41988296f22423cec94fac/src/BloomExe/Publish/Epub/EpubMaker.cs#L1347)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

nice catch of a seemingly trivial difference.  I assume you've tested this enough to be sure it works.  :-)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2077)*

**Pull request merged**
