### PR TITLE
BL-4256 Add 'Reset Style' link to StyleEditor

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1482)

### CODE REVIEW

**Comment by gmartin7** [comment]
For review. Will wait to merge until Andrew's StyleEditor pug refactor is in.

**Comment by andrew-polk** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[DistFiles/localization/Bloom.en.tmx, line 1446 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1482#-KcYdyUj4xLMXdVOYWDy:-KcYdyUj4xLMXdVOYWDz:b-lhhx3e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/77c9769287f43b4f31ad84c5ea7ebc20ceb02f26/DistFiles/localization/Bloom.en.tmx#L1446)):*
> ```
>       </tuv>
>     </tu>
>     <tu tuid="EditTab.FormatDialog.ResetStyle">
> ```

This might be nitpicking, but I think we are trying to keep these files as alphabetized as possible because Paul's tool alphabetizes, so diffs may be more complicated than necessary later.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 343 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1482#-KcYes4Ne-Cvf6Fw0y_c:-KcYes4O3oirmogWC914:bkgl6uw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/77c9769287f43b4f31ad84c5ea7ebc20ceb02f26/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L343)):*
> ```XML
>         var styleSheet = this.GetOrCreateUserModifiedStyleSheet();
>         if (styleSheet == null) {
>             alert('styleSheet == null');
> ```

I assume this is here for debugging? I don't like the idea this could happen in the real world. How about return; instead?

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 348 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1482#-KcYfGTx7O9PXxYs9nuh:-KcYfGTx7O9PXxYs9nui:bx2tszt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/77c9769287f43b4f31ad84c5ea7ebc20ceb02f26/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L348)):*
> ```XML
>         var ruleList: CSSRuleList = (<any>styleSheet).cssRules;
>         if (ruleList == null) {
>             ruleList = <any>[];
> ```

Or simply return;

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 707 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1482#-KcYedb_yaCOUkOcD51i:-KcYedb_yaCOUkOcD51j:b-jwvba4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/77c9769287f43b4f31ad84c5ea7ebc20ceb02f26/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L707)):*
> ```XML
>                             + editor.makeDiv('style-group', 'state-initial', null, null,
>                                 editor.makeSelect(editor.styles, styleName, 'styleSelect')
>                                 + editor.makeDiv('style-reset', null, null, null,
> ```

Looks like this is the only part which will need to be moved after my refactor change. Should be simple.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1482)*

**Comment by andrew-polk** [comment]
@gmartin7 this is ready to be rebased

**Comment by gmartin7** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[DistFiles/localization/Bloom.en.tmx, line 1446 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1482#-KcYdyUj4xLMXdVOYWDy:-Kccwg6J8eezMSVwyozV:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/77c9769287f43b4f31ad84c5ea7ebc20ceb02f26/DistFiles/localization/Bloom.en.tmx#L1446)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This might be nitpicking, but I think we are trying to keep these files as alphabetized as possible because Paul's tool alphabetizes, so diffs may be more complicated than necessary later.
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 343 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1482#-KcYes4Ne-Cvf6Fw0y_c:-KccwhZnTRraEH6EWrFH:b-z90zu5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/77c9769287f43b4f31ad84c5ea7ebc20ceb02f26/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L343)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I assume this is here for debugging? I don't like the idea this could happen in the real world. How about return; instead?
</blockquote></details>

Copied from another method. I should have looked at it more carefully. Done.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 348 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1482#-KcYfGTx7O9PXxYs9nuh:-KccwrhF2D7EOJXtAIYK:b-z90zu5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/77c9769287f43b4f31ad84c5ea7ebc20ceb02f26/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L348)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Or simply return;
</blockquote></details>

Copied from another method. I should have looked at it more carefully. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1482)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1482#-:-KccyZcCN1LartN_xn2x:bnfp4nl)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1482)*

**Pull request merged**
