### PR TITLE
Clean up obsolete files/folders when uploading (BL-7616)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5390)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5390)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Book/BookStorage.cs` line 206 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5390#-NByB734899fHc7bXzTA:-NByB735Bz5I7mU3uAgX:b-iyvqpf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a8e60e176422167cc217d130f7ab7610dd29858/src/BloomExe/Book/BookStorage.cs#L206)):*
> ```Smalltalk
> 			// https://issues.bloomlibrary.org/youtrack/issue/BL-9479 for what has
> 			// happened in the past that still can use cleanup in new work.
> 			accumulator.AddRange(Directory.GetFiles(folderPath, "placeHolder*.png"));
> ```

Does this mean we never upload any placeHolder files?
That doesn't see right, either. 
It seems like if the book contains a placeholder image at the time of upload, we still want to include it.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5390)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/Book/BookStorage.cs` line 206 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5390#-NByB734899fHc7bXzTA:-NC1JDFr3kJ0C8l4vhEd:bwzpxrp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a8e60e176422167cc217d130f7ab7610dd29858/src/BloomExe/Book/BookStorage.cs#L206)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Does this mean we never upload any placeHolder files?
That doesn't see right, either. 
It seems like if the book contains a placeholder image at the time of upload, we still want to include it.
</blockquote></details>

I've changed the code to upload placeHolder.png files that are actually referenced in the book's html file,
but to delete any other leftover files that are not referenced by the html.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5390)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Book/BookStorage.cs` line 216 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5390#-NC668cI5JqENhyo8FaS:-NC668cI5JqENhyo8FaT:b42xxov) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/81d2431a88155b329742eb383a684d5a6d621c7e/src/BloomExe/Book/BookStorage.cs#L216)):*
> ```Smalltalk
> 			// happened in the past that still can use cleanup in new work.
> 			var bookName = Path.GetFileName(bookFolderPath);
> 			var htmlPath = Path.Combine(bookFolderPath, bookName+".htm");
> ```

Can we rely on the book file name being the same as the folder name? (I can't remember how the rename stuff works.)
___
*[`src/BloomExe/Book/BookStorage.cs` line 227 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5390#-NC66M5D3ZGJtREtX-x3:-NC66M5D3ZGJtREtX-x4:bf6v2gc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/81d2431a88155b329742eb383a684d5a6d621c7e/src/BloomExe/Book/BookStorage.cs#L227)):*
> ```Smalltalk
> 					accumulator.Add(filepath);
> 				}
> 			}
> ```

If I understand the context correctly, we are just removing the obsolete placeholder files from the staged book which will be uploaded. Should we instead remove them from the real book, perhaps in BringBookUpToDate?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5390)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Book/BookStorage.cs` line 216 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5390#-NC668cI5JqENhyo8FaS:-NCLgR9u922-0dd8Wbm8:b-87mjdx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/81d2431a88155b329742eb383a684d5a6d621c7e/src/BloomExe/Book/BookStorage.cs#L216)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Can we rely on the book file name being the same as the folder name? (I can't remember how the rename stuff works.)
</blockquote></details>

FindBookHtmlInFolder(folder) is probably better. What I had here is actually the first candidate found by that method.
___
*[`src/BloomExe/Book/BookStorage.cs` line 227 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5390#-NC66M5D3ZGJtREtX-x3:-NCLigziBxr-jCNCv7K8:b-70e92e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/81d2431a88155b329742eb383a684d5a6d621c7e/src/BloomExe/Book/BookStorage.cs#L227)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If I understand the context correctly, we are just removing the obsolete placeholder files from the staged book which will be uploaded. Should we instead remove them from the real book, perhaps in BringBookUpToDate?
</blockquote></details>

I've added code to CleanupUnusedImageFiles (called by ExpensiveInitialization) to delete unused copies of placeHolder.png, but not the base image itself.  But I think leaving the code here is safe, and may help in rare cases where a user goes directly to Publish from Collections on an old book.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5390)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Book/BookStorage.cs` line 227 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5390#-NC66M5D3ZGJtREtX-x3:-NCLq13i1MOB8wTrjeOd:bequ2bv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/81d2431a88155b329742eb383a684d5a6d621c7e/src/BloomExe/Book/BookStorage.cs#L227)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I've added code to CleanupUnusedImageFiles (called by ExpensiveInitialization) to delete unused copies of placeHolder.png, but not the base image itself.  But I think leaving the code here is safe, and may help in rare cases where a user goes directly to Publish from Collections on an old book.
</blockquote></details>

Ok, but I think we can optimize a little.
Looks like we don't need to check if the file exists after calling `FindBookHtmlInFolder` as that will return null if it doesn't.
We could check if there are any placeHolder images in the book folder before reading the html file.
Indeed we can wait to find the html file until after that, too, since we always expect to find one.
(And finding a placeholder file should be the unusual case? Or am I wrong and we usually get here with the base one?)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5390)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/Book/BookStorage.cs` line 227 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5390#-NC66M5D3ZGJtREtX-x3:-NCM1K9L6AEq2ChEhzBX:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/81d2431a88155b329742eb383a684d5a6d621c7e/src/BloomExe/Book/BookStorage.cs#L227)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Ok, but I think we can optimize a little.
Looks like we don't need to check if the file exists after calling `FindBookHtmlInFolder` as that will return null if it doesn't.
We could check if there are any placeHolder images in the book folder before reading the html file.
Indeed we can wait to find the html file until after that, too, since we always expect to find one.
(And finding a placeholder file should be the unusual case? Or am I wrong and we usually get here with the base one?)
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5390)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
