### PR TITLE
Properly handle change layout with image and video overlays (BL-11201)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5169)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5169)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/HtmlDom.cs` line 827 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5169#-N2xcrlK6uGDHsphnKZs:-N2xcrlK6uGDHsphnKZt:bsaaz3t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/759f4b553883051c7a52e7354eca899686bf05f8/src/BloomExe/Book/HtmlDom.cs#L827)):*
> ```Smalltalk
> 		}
> 
> 		private static List<XmlElement> GetTranslationGroups(XmlElement pageElement)
> ```

Seems like we should rename this to something like `GetTranslationGroupsNotInImageContainer`
And similar for `GetTranslationGroupCount`



_Code quote:_
```Smalltalk
GetTranslationGroups
```

**Review by andrew-polk — COMMENTED** [review]
I think this should be attached to issue BL-11201 instead of BL-11147?

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5169#-:-N2xeR145Kz0qlu3J1zh:bgch1zv)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
Yes, I fixed the commit only a minute or so after I submitted it, but forgot to fix the PR. Seems like single-commit PRs should automatically take their title from the commit!

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5169#-:-N3-xNly7hkYXZVjSHgv:b9fywo2)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5169)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/Book/HtmlDom.cs` line 827 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5169#-N2xcrlK6uGDHsphnKZs:-N35IBnk3pHckVlGfbqn:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/759f4b553883051c7a52e7354eca899686bf05f8/src/BloomExe/Book/HtmlDom.cs#L827)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems like we should rename this to something like `GetTranslationGroupsNotInImageContainer`
And similar for `GetTranslationGroupCount`
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5169)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
