### PR TITLE
BL-4234 allow user to specify paragraph indent

### PR DESCRIPTION
**Pull request by JohnThomson**
and spacing (BL-4235)

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1468)

### CODE REVIEW

**Comment by JohnThomson** [comment]
PR now updated to reinstate Emphasis options.

**Comment by andrew-polk** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 316 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1468#-KcKDiiGkI0UhxbSCCUl:-KcKDiiGkI0UhxbSCCUm:b-pnd3er) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8d6950c0faac985a4cc395d59e04d5fe23438c08/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L316)):*
> ```XML
>             // The substring strips off the initial period and the rule body, leaving the selector.
>             var match = ruleList[i].cssText.trim().substring(1, index).toLowerCase().trim();
>             if (match == styleAndLang) {
> ```

I'm probably just not understanding what is happening here, but it seems we lost the distinction between logic for ignoreLanguage true vs. false.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 1021 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1468#-KcKG4ZVr1k64okhdl8j:-KcKG4ZW0PT1I02ZW-C7:b-ab94ud) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8d6950c0faac985a4cc395d59e04d5fe23438c08/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L1021)):*
> ```XML
>     changeBold() {
>         if (this.ignoreControlChanges) return;
>         var rule = this.getStyleRule(false);
> ```

There are several places here where getStyleRule(true) was changed to getStyleRule(false). Did you mean to make them getStyleRule(true, false)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1468)*

**Comment by andrew-polk** [comment]
A couple points for clarification. Other than that, looks good. Though I admit I got slightly bleary-eyed at some point.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1468#-:-KcKGNiJGnFJGqqqPbZ3:bnloxhr)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 316 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1468#-KcKDiiGkI0UhxbSCCUl:-KcNxPhDY5pXSuGnsYPh:bm4o0id) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8d6950c0faac985a4cc395d59e04d5fe23438c08/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L316)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm probably just not understanding what is happening here, but it seems we lost the distinction between logic for ignoreLanguage true vs. false.
</blockquote></details>

StyleAndLang will have an appropriate component in that case (see about 15 lines up). Likewise it will have a 'p' if the rule needs that. So simply searching for the right thing before the { covers all the cases, I believe.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 1021 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1468#-KcKG4ZVr1k64okhdl8j:-KcNxxSd7yXV-7UhIHeg:b-pld6d1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8d6950c0faac985a4cc395d59e04d5fe23438c08/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L1021)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

There are several places here where getStyleRule(true) was changed to getStyleRule(false). Did you mean to make them getStyleRule(true, false)?
</blockquote></details>

No, bold, italic, and underline are all inherited, so they don't need the new logic that makes the rules apply to child paragraphs. However, they moved from the old 'more' tab which is never language-dependent (first 'true') to the characters tab where they may or may not be...the logic is parallel now to the logic for font name and similar things, not the logic for indent and paragraph spacing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1468)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1468#-:-KcOVUN5ru0W_wno9k7g:bnfp4nl)*

**Pull request merged**
