### PR TITLE
Let the overlay control bar extend outside the page (BL-13897)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6668)

### CODE REVIEW

**Review by StephenMcConnel — CHANGES_REQUESTED** [review]
One question and one minor spelling correction.  If the answer to the question is "yes everything is okay" then we could merge this without bothering about the spelling.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6668#-:-O75v94JAudkTLYdQ2jQ:b-tp25th)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 2002 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6668#-O75tmSV1LFuqu8CyzMA:-O75tmSV1LFuqu8CyzMB:bezjrsn) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d11ae19d2babcc0041347d4b048841ad5b735496/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2002)):*
> ```XML
>         const contextControlsWidth = 300;
>         // Subtracting half the width of the context control frame and adding half the width of the control Frame
>         // canters it. The width of the context controls is scaled by its own transform (which we set
> ```

canters => centers (but we can let it pass if there's not other issues)
___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 2009 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6668#-O75uInI5PSROpbyCFGU:-O75uInI5PSROpbyCFGV:b-k0rddi) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d11ae19d2babcc0041347d4b048841ad5b735496/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2009)):*
> ```XML
>             window.scrollX +
>             controlFrameRect.width / 2 -
>             (contextControlsWidth / 2) * scale;
> ```

how much of this computation should scale be applied to?  It's just applied to the contextControlsWidth value, which could be correct.  If the window.scrollXY values are already scaled properly, then this should be okay.

**Review by JohnThomson — COMMENTED** [review]
I responded to that. But JohnH caught some problems testing so there's another commit to check.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6668#-:-O760AM_-N7hPj2EZTZh:b-rm9a4p)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 2002 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6668#-O75tmSV1LFuqu8CyzMA:-O76-qRc0--enzWpAxaR:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d11ae19d2babcc0041347d4b048841ad5b735496/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2002)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

canters => centers (but we can let it pass if there's not other issues)
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 2009 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6668#-O75uInI5PSROpbyCFGU:-O76-x-vBgDQIQc7qq6_:bncemd7) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d11ae19d2babcc0041347d4b048841ad5b735496/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2009)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

how much of this computation should scale be applied to?  It's just applied to the contextControlsWidth value, which could be correct.  If the window.scrollXY values are already scaled properly, then this should be okay.
</blockquote></details>

It seems to work right when scrolling. I can't imagine that anything related to the window would be scaled; scaling is caused by a transform:scale applied to the element just above the page.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6668)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 2009 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6668#-O75uInI5PSROpbyCFGU:-O761GIx7Og1AnUDZ3b1:bng0gke) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d11ae19d2babcc0041347d4b048841ad5b735496/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2009)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It seems to work right when scrolling. I can't imagine that anything related to the window would be scaled; scaling is caused by a transform:scale applied to the element just above the page.
</blockquote></details>

Believe me, I did a LOT of testing before I got all the right things scaled and not scaled!

**Review by StephenMcConnel — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6668)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by StephenMcConnel — APPROVED** [review]
Deleting obsolete code must feel good!

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6668#-:-O762W0iEE7Zssn68AiE:bmjxjs2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
