### PR TITLE
Persist Talking Book Languages and Text Languages settings (BL-10055)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4610)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
As far as I can tell, this PR is only for the BloomReader side.
Is the BloomLibrary side coming in a separate PR?

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4610#-:-MfAQBGP75FKxdAL7B_t:b-3pevp0)* status: all files reviewed, 5 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/Publish/LangsToPublishSetting.cs, line 11 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4610#-MfAJ9rXEUNFPyExTCu3:-MfAJ9rXEUNFPyExTCu4:bsqeopg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d0204af71ff7c563fe9a4dd4e0b3c41005ebc9e2/src/BloomExe/Publish/LangsToPublishSetting.cs#L11)):*
> ```
> publish
> ```
published
___
*[src/BloomExe/Publish/LangsToPublishSetting.cs, line 16 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4610#-MfAJ7P40KuqS3jya94K:-MfAJ7P40KuqS3jya94L:b-3620j3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d0204af71ff7c563fe9a4dd4e0b3c41005ebc9e2/src/BloomExe/Publish/LangsToPublishSetting.cs#L16)):*
> ```
> BloomReader
> ```
We discussed that since we already have a second consumer of bloompubs (BloomPUB Viewer), that this might be better as BloomPub/BloomPUB. Did you have any further thoughts on that (I can't remember where we landed)?
___
*[src/BloomExe/Publish/LangToPublishCheckboxValue.cs, line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4610#-MfAKRCA-qCyso7hdD0B:-MfAKRCA-qCyso7hdD0C:by3otex) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d0204af71ff7c563fe9a4dd4e0b3c41005ebc9e2/src/BloomExe/Publish/LangToPublishCheckboxValue.cs#L13)):*
> ```
> LangToPublishCheckboxValue
> ```
I'm ok with it as is if you decide not to make a change by claiming yagni (could always be changed later).
But I wonder if this should be more generic like `IncludeExcludeOrDefaultCheckboxValue` or even `IncludeExcludeDefaultEnum` or similar.

And then IsUserSpecified might become IsSpecified?
___
*[src/BloomExe/Publish/LangToPublishCheckboxValue.cs, line 18 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4610#-MfAPZWvCc1AyOCp6r0y:-MfAPZWvCc1AyOCp6r0z:b-jypq9t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d0204af71ff7c563fe9a4dd4e0b3c41005ebc9e2/src/BloomExe/Publish/LangToPublishCheckboxValue.cs#L18)):*
> ```
> 		IncludeByDefault,
> 		ExcludeByDefault
> ```
I see why, when working with the non-persisted values, this distinction is helpful.
But it seems somewhat unfortunate to persist with two values which mean the same thing.
It might be more complication than it is worth, but did you consider what it would look like to persist each of these values as the same value (like "Default"). Then I think you would have to add "Default" to the enum for deserialization.
___
*[src/BloomExe/Publish/Android/PublishToAndroidApi.cs, line 91 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4610#-MfAPCn813nV0MbL8E5Z:-MfAPCn813nV0MbL8E5_:bk9b519) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d0204af71ff7c563fe9a4dd4e0b3c41005ebc9e2/src/BloomExe/Publish/Android/PublishToAndroidApi.cs#L91)):*
> ```
> // We need a copy of the hashset, so that if _languagesToPublish changes, this settings object won't.
> ```
I don't think this comment is up-to-date or relevant now.
Can probably just delete.

**Review by sujeffreyl — COMMENTED** [review]
I guess it's whatever you guys want, but I think the BL side should be in a separate PR.  The issue is titled "Control which Talking Book languages when publishing BLOOMPUB" (emphasis mine]). Honestly, I think the current PR is already scope creep from the original issue, and adding the BL one too would be further scope creep IMO.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4610#-:-MfDU-G0Dgsib40PavX5:bow0fic)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/Publish/LangsToPublishSetting.cs, line 11 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4610#-MfAJ9rXEUNFPyExTCu3:-MfDUUai7TtimbpvDnqA:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d0204af71ff7c563fe9a4dd4e0b3c41005ebc9e2/src/BloomExe/Publish/LangsToPublishSetting.cs#L11)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> publish
> ```
published
</blockquote></details>

Done.
___
*[src/BloomExe/Publish/LangsToPublishSetting.cs, line 16 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4610#-MfAJ7P40KuqS3jya94K:-MfDUjAi89nsgJvFyYfj:b-dc5ryk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d0204af71ff7c563fe9a4dd4e0b3c41005ebc9e2/src/BloomExe/Publish/LangsToPublishSetting.cs#L16)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> BloomReader
> ```
We discussed that since we already have a second consumer of bloompubs (BloomPUB Viewer), that this might be better as BloomPub/BloomPUB. Did you have any further thoughts on that (I can't remember where we landed)?
</blockquote></details>

Hmm. Yeah, when I think about it, we did land on "bloompub" instead. I thought I had this recollection of changing the name immediately after our discussion, so I had been purposely not touching the name in recent days, but well... apparently I did not actually change the name immediately after our discussion.
Fixed
___
*[src/BloomExe/Publish/Android/PublishToAndroidApi.cs, line 91 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4610#-MfAPCn813nV0MbL8E5Z:-MfDnQ5O6odcEU4DyGwy:bfjnph2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d0204af71ff7c563fe9a4dd4e0b3c41005ebc9e2/src/BloomExe/Publish/Android/PublishToAndroidApi.cs#L91)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> // We need a copy of the hashset, so that if _languagesToPublish changes, this settings object won't.
> ```
I don't think this comment is up-to-date or relevant now.
Can probably just delete.
</blockquote></details>

I gave a shot at updating it. See what you think.
___
*[src/BloomExe/Publish/LangToPublishCheckboxValue.cs, line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4610#-MfAKRCA-qCyso7hdD0B:-MfDW6BGAgsYYTR2eXzt:b-mlktco) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d0204af71ff7c563fe9a4dd4e0b3c41005ebc9e2/src/BloomExe/Publish/LangToPublishCheckboxValue.cs#L13)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> LangToPublishCheckboxValue
> ```
I'm ok with it as is if you decide not to make a change by claiming yagni (could always be changed later).
But I wonder if this should be more generic like `IncludeExcludeOrDefaultCheckboxValue` or even `IncludeExcludeDefaultEnum` or similar.

And then IsUserSpecified might become IsSpecified?
</blockquote></details>

Hmm. At one point I was trying to put something more generic like DefaultCheckboxValue or CheckboxWithDefaultValue or something like that. But then I was using Checked/Unchecked/Default, and I decided I strongly preferred Include/Exclude over Checked/Unchecked.

I wasn't a fan of IncludeExcludeOrDefaultCheckboxValue or even IncludeExcludeDefaultEnum.
Based on looking through the C# docs, I tried to come up with a shorter Noun Phrase...
Trying out InclusionSettings
___
*[src/BloomExe/Publish/LangToPublishCheckboxValue.cs, line 18 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4610#-MfAPZWvCc1AyOCp6r0y:-MfDZZkK67GR1XcjHt-_:bporgtw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d0204af71ff7c563fe9a4dd4e0b3c41005ebc9e2/src/BloomExe/Publish/LangToPublishCheckboxValue.cs#L18)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> 		IncludeByDefault,
> 		ExcludeByDefault
> ```
I see why, when working with the non-persisted values, this distinction is helpful.
But it seems somewhat unfortunate to persist with two values which mean the same thing.
It might be more complication than it is worth, but did you consider what it would look like to persist each of these values as the same value (like "Default"). Then I think you would have to add "Default" to the enum for deserialization.
</blockquote></details>

Hmm, I see what you mean.. but all the solutions I can think of seem worse than the problem. So, they're all some variation of working with a 4-way enum after InitialzieLangaugesInBook is called, but going to a 3-way enum when saving the metainfo, which can occur multiple times since we now save whenever the checkbox is changed as well as at other times... so we could have some kind of two mirrored variables, that's more data and more code to do the conversion, and using a setter to update from the serialized version to the in-memory version doesn't really work because JSON deserialization bypasses the setters.... 
i guess maybe you're saying we could have a 5-way enum and have a getter to convert it to just 3 of the states during serialization... but then how would we get the 4-way value during the in-memory phase? Well sure you could just add a 2nd pseudoGetter function, but... having the 2nd pseudoGetter makes the code more complex, and I think this whole concept of having a 5-way enum that is a 4-way enum in-memory but a 3-way enum on disk is more trouble than it's worth.

Or... write a custom enum serializer that serializes IncludeByDefault and ExcludeByDefault to the string "Default", and deserializes it as... well, I guess you're saying introducing a 5th value Default that it would deserialize to? Well, adding a custom enum serializer seems like more work and complexity than it's worth.

So, my take is that "In all the solutions I thought of, the cost seemed greater to me than the reward I think we'll get". Let me know if you think otherwise.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Yeah, sorry. That was my confusion. I was thinking that the expanded scope had already requested Bloomlibrary persistence.

> Reviewed 4 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4610#-:-MfE6Gmf1cDSV6cde9qH:b-82xees)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomExe/Publish/LangToPublishCheckboxValue.cs, line 18 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4610#-MfAPZWvCc1AyOCp6r0y:-MfE6V6U2OWpGp8I4XrQ:b-laxmh8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d0204af71ff7c563fe9a4dd4e0b3c41005ebc9e2/src/BloomExe/Publish/LangToPublishCheckboxValue.cs#L18)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Hmm, I see what you mean.. but all the solutions I can think of seem worse than the problem. So, they're all some variation of working with a 4-way enum after InitialzieLangaugesInBook is called, but going to a 3-way enum when saving the metainfo, which can occur multiple times since we now save whenever the checkbox is changed as well as at other times... so we could have some kind of two mirrored variables, that's more data and more code to do the conversion, and using a setter to update from the serialized version to the in-memory version doesn't really work because JSON deserialization bypasses the setters.... 
i guess maybe you're saying we could have a 5-way enum and have a getter to convert it to just 3 of the states during serialization... but then how would we get the 4-way value during the in-memory phase? Well sure you could just add a 2nd pseudoGetter function, but... having the 2nd pseudoGetter makes the code more complex, and I think this whole concept of having a 5-way enum that is a 4-way enum in-memory but a 3-way enum on disk is more trouble than it's worth.

Or... write a custom enum serializer that serializes IncludeByDefault and ExcludeByDefault to the string "Default", and deserializes it as... well, I guess you're saying introducing a 5th value Default that it would deserialize to? Well, adding a custom enum serializer seems like more work and complexity than it's worth.

So, my take is that "In all the solutions I thought of, the cost seemed greater to me than the reward I think we'll get". Let me know if you think otherwise.
</blockquote></details>

Yeah. The other approach would be just a 3-way enum such that you always had to refigure what default means.
I suppose another would be two enums, one 3-way for persistence, one 4-way for in-process. And converting between the two.
I doubt either of those would be better.

So let's comment here saying that from a persistence perspective, the two defaults are actually the same thing but to simplify on one most simple enum we can use everywhere, we have distinct values for them.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4610)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Publish/LangToPublishCheckboxValue.cs, line 18 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4610#-MfAPZWvCc1AyOCp6r0y:-MfEyeAB02BqBZ7wp2wQ:bmv5ap0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d0204af71ff7c563fe9a4dd4e0b3c41005ebc9e2/src/BloomExe/Publish/LangToPublishCheckboxValue.cs#L18)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Yeah. The other approach would be just a 3-way enum such that you always had to refigure what default means.
I suppose another would be two enums, one 3-way for persistence, one 4-way for in-process. And converting between the two.
I doubt either of those would be better.

So let's comment here saying that from a persistence perspective, the two defaults are actually the same thing but to simplify on one most simple enum we can use everywhere, we have distinct values for them.
</blockquote></details>

Updated. See what you think.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4610)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Pull request merged**
