### PR TITLE
Improvements to BloomEnterpriseButton (BL-11266)

### PR DESCRIPTION
**Pull request by JohnThomson**
And make it work properly in PDF Print tab

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5691)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5691)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`DistFiles/localization/en/Bloom.xlf` line 1728 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5691#-NPxyi7P6akHTfex2gXZ:-NPxyi7P6akHTfex2gX_:bkndgu9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/06b7d187353e6ee895f52d1dd85d10cd2b9f822c/DistFiles/localization/en/Bloom.xlf#L1728)):*
> ```XML
>       </trans-unit>
>       <trans-unit id="EditTab.FrontMatter.ImageCreditMissing">
>         <source xml:lang="en"> {0} (page {1})Enterp</source>
> ```

errant key strokes

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5691)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/Bloom.xlf` line 1728 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5691#-NPxyi7P6akHTfex2gXZ:-NQ0RmXaEFj90ujVv6EW:b-ucfkn4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/06b7d187353e6ee895f52d1dd85d10cd2b9f822c/DistFiles/localization/en/Bloom.xlf#L1728)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

errant key strokes
</blockquote></details>

Thanks.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5691)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @JohnThomson)

**Review by andrew-polk — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5691)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
