### PR TITLE
Ensure all quote marks recognized at sentence end (BL-5063)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1947)

### CODE REVIEW

**Comment by andrew-polk** [comment]
This feels a bit scary. Probably mostly because I don't fully understand it.
Could you add some unit tests, please?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1947#-:-KySUTl1kKnqaXQ7tlc-:bebf3ty)*

**Comment by andrew-polk** [comment]
(split_sentencesSpec.js)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1947#-:-KySVAL0ifqtI5GKS03e:bgn3get)*

**Comment by StephenMcConnel** [comment]
done

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1947#-:-KySku7KS_VRAkwRpZ5M:bb7f2mf)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1947)*

**Pull request merged**
