### PR TITLE
BL-12403 Tweaks to Progress bar

### PR DESCRIPTION
**Pull request by gmartin7**
* Books on Blorg
* Add tooltip link to blorg books in current language
* Fix "-1" problem

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6085)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6085)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
A few suggestions. We'll see if I did them correctly/helpfully in Reviewable...

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6085#-:-NdaaUSn-9Kvlni5f8_m:b9naq02)* status: all files reviewed, 6 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx` line 54 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6085#-NdaZWfL4U_9cwbiqKJ_:-NdaZWfL4U_9cwbiqKJa:undefined) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c1d63a9d7d94b8f58c66052738bb581b1f4da25d/src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx#L54)):*
> ```XML
>     }, []);
> 
>     // Verify 'translated' status. It was harder than expected to avoid a momentary "-1 language books..."
> ```





_Suggestion:_
```XML
    // Verify label is ready for display. i.e. `useL10n` hook has completed.
    // It was harder than expected to avoid a momentary "-1 language books..."
```
___
*[`src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx` line 57 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6085#-NdaZtYj5no7QevRn1br:-NdaZtYj5no7QevRn1bs:undefined) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c1d63a9d7d94b8f58c66052738bb581b1f4da25d/src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx#L57)):*
> ```XML
>     // We don't set the percentage until the label we are going to use no longer has a placeholder and
>     // not longer has a "-1" in it.
>     // N.B. The percentage value governs the height of the progress bar, so no percentage, no progress bar.
> ```





_Suggestion:_
```XML
    // N.B. The percentage value governs the height of the progress bar, so no percentage, no progress bar.
    //
    // I (Andrew), in review, wanted to suggest that we have a callback from useL10n which could be used to 
    // deal with a situation like this. But the hook is designed to allow for the params to be passed in
    // even after the initial result. Thus I couldn't see any way to guarantee such a callback only fires
    // after all the pieces are in place.
```
___
*[`src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx` line 58 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6085#-Nda_vqP0kJ-0UiQXAov:-Nda_vqP0kJ-0UiQXAow:undefined) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c1d63a9d7d94b8f58c66052738bb581b1f4da25d/src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx#L58)):*
> ```XML
>     // not longer has a "-1" in it.
>     // N.B. The percentage value governs the height of the progress bar, so no percentage, no progress bar.
>     const translationComplete =
> ```





_Suggestion:_
```XML
    const isLabelReadyForDisplay =
```
___
*[`src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx` line 69 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6085#-Ndaa0p5Bk64gjJq9efv:-Ndaa0p5Bk64gjJq9efw:undefined) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c1d63a9d7d94b8f58c66052738bb581b1f4da25d/src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx#L69)):*
> ```XML
>             bookCount > -1 &&
>             languageName !== "" &&
>             translationComplete
> ```





_Suggestion:_
```XML
            isLabelReadyForDisplay
```
___
*[`src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx` line 80 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6085#-Ndaa6eU45ocm5FLdaK6:-Ndaa6eU45ocm5FLdaK7:undefined) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c1d63a9d7d94b8f58c66052738bb581b1f4da25d/src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx#L80)):*
> ```XML
>             }
>         }
>     }, [webGoal, bookCount, languageName, translationComplete]);
> ```





_Suggestion:_
```XML
    }, [webGoal, bookCount, languageName, isLabelReadyForDisplay]);
```
___
*[`src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx` line 116 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6085#-NdaaM0P2zZn1DowGDp0:-NdaaM0P2zZn1DowGDp1:undefined) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c1d63a9d7d94b8f58c66052738bb581b1f4da25d/src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx#L116)):*
> ```XML
>                         flex-direction: column;
>                         height: ${height}px;
>                         //width: 312px;
> ```

**Comment by andrew-polk** [comment]
*[`src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx` line 56 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6085#-Ndab-ZU2cINVJLJKPzc:-Ndab-ZU2cINVJLJKPzd:undefined) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c1d63a9d7d94b8f58c66052738bb581b1f4da25d/src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx#L56)):*
> ```XML
>     // Verify 'translated' status. It was harder than expected to avoid a momentary "-1 language books..."
>     // We don't set the percentage until the label we are going to use no longer has a placeholder and
>     // not longer has a "-1" in it.
> ```





_Suggestion:_
```XML
    // no longer has a "-1" in it.
```

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6085)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx` line 54 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6085#-NdaZWfL4U_9cwbiqKJ_:-NdadW4v4IMnaPidY-km:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c1d63a9d7d94b8f58c66052738bb581b1f4da25d/src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx#L54)):*
> ```XML
>     }, []);
> 
>     // Verify 'translated' status. It was harder than expected to avoid a momentary "-1 language books..."
> ```

Done.
___
*[`src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx` line 56 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6085#-Ndab-ZU2cINVJLJKPzc:-NdadWU5EukZse6Uf_1G:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c1d63a9d7d94b8f58c66052738bb581b1f4da25d/src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx#L56)):*
> ```XML
>     // Verify 'translated' status. It was harder than expected to avoid a momentary "-1 language books..."
>     // We don't set the percentage until the label we are going to use no longer has a placeholder and
>     // not longer has a "-1" in it.
> ```

Done.
___
*[`src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx` line 57 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6085#-NdaZtYj5no7QevRn1br:-Ndae66tE2s7aFHELC4s:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c1d63a9d7d94b8f58c66052738bb581b1f4da25d/src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx#L57)):*
> ```XML
>     // We don't set the percentage until the label we are going to use no longer has a placeholder and
>     // not longer has a "-1" in it.
>     // N.B. The percentage value governs the height of the progress bar, so no percentage, no progress bar.
> ```

Done.
___
*[`src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx` line 58 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6085#-Nda_vqP0kJ-0UiQXAov:-Ndadcrh5LdhPNUr2Xrc:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c1d63a9d7d94b8f58c66052738bb581b1f4da25d/src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx#L58)):*
> ```XML
>     // not longer has a "-1" in it.
>     // N.B. The percentage value governs the height of the progress bar, so no percentage, no progress bar.
>     const translationComplete =
> ```

Done.
___
*[`src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx` line 69 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6085#-Ndaa0p5Bk64gjJq9efv:-NdaeEqG43928-HYUHfs:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c1d63a9d7d94b8f58c66052738bb581b1f4da25d/src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx#L69)):*
> ```XML
>             bookCount > -1 &&
>             languageName !== "" &&
>             translationComplete
> ```

Done.
___
*[`src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx` line 80 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6085#-Ndaa6eU45ocm5FLdaK6:-Ndae84rAb-2aoCzdjzR:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c1d63a9d7d94b8f58c66052738bb581b1f4da25d/src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx#L80)):*
> ```XML
>             }
>         }
>     }, [webGoal, bookCount, languageName, translationComplete]);
> ```

Done.
___
*[`src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx` line 116 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6085#-NdaaM0P2zZn1DowGDp0:-NdaeCPA9VtW45qquzT_:b-qsx7u6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c1d63a9d7d94b8f58c66052738bb581b1f4da25d/src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx#L116)):*
> ```XML
>                         flex-direction: column;
>                         height: ${height}px;
>                         //width: 312px;
> ```

Done. Oops.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6085)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
