### PR TITLE
BL-5748 Make background music level non-linear

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2272)

### CODE REVIEW

**Comment by andrew-polk** [comment]
This needs to retarget Version4.2. Sorry.

**Comment by JohnThomson** [comment]
LGTM with minor questions/suggestions

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx, line 212 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2272#-L7Zu-i6HY5GevzM2QWO:-L7Zu-i6HY5GevzM2QWP:b-5jxu3i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7e1803af77055479d430e2118bff1fd816f66c10/src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx#L212)):*
> ```XML
>                 audioVolumeFraction = parseFloat(audioVolumeStr);
>             } catch (e) {
>                 audioVolumeFraction = 1.0;
> ```

I think we want kDefaultVolumeFraction here...or do nothing since you set that above.

---

*[src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx, line 229 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2272#-L7ZujXuWkdJd6WU9fdD:-L7ZujXuWkdJd6WU9fdE:b-79x7zi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7e1803af77055479d430e2118bff1fd816f66c10/src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx#L229)):*
> ```XML
>     // We are using 3 but 2 is also ok. Using 3 because the effect feels right to me (subjectively,
>     // with a very small sample size).
>     static kLowEndVolumeSensitivity: number = 3;
> ```

Maybe there should be something in the comment or name to indicate this is an exponent? It's not obvious what the meaning of '3' is or whether it has to be a whole number.

---

*[src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx, line 247 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2272#-L7_1FJgeMtuaH7eTomZ:-L7_1FJgeMtuaH7eTom_:bnbmwkp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7e1803af77055479d430e2118bff1fd816f66c10/src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx#L247)):*
> ```XML
>                 1 / MusicToolControls.kLowEndVolumeSensitivity
>             ) * 100
>         );
> ```

How well do these functions round trip? For example, suppose the slider is moved to 3...algorithm sets volume attr to 0.000027 ...I suppose we're storing enough precision that  converting it back to a rounded integer will produce 3? And similarly for all 101 possible slider values?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2272#-:-L7_2vDRXGjdQ0WXvLVF:b-58pg41)*

**Comment by JohnThomson** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2272)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx, line 212 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2272#-L7Zu-i6HY5GevzM2QWO:-L7_8d2JnYdxPlwLD8Vz:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7e1803af77055479d430e2118bff1fd816f66c10/src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx#L212)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think we want kDefaultVolumeFraction here...or do nothing since you set that above.
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx, line 229 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2272#-L7ZujXuWkdJd6WU9fdD:-L7_8gR_TGBwMjWmeqN8:b-ih1ffj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7e1803af77055479d430e2118bff1fd816f66c10/src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx#L229)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Maybe there should be something in the comment or name to indicate this is an exponent? It's not obvious what the meaning of '3' is or whether it has to be a whole number.
</blockquote></details>

I shouldn't think it does have to be a whole number.

---

*[src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx, line 247 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2272#-L7_1FJgeMtuaH7eTomZ:-L7_9XCBQpRlSYLIk4qM:b-w7gsoz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7e1803af77055479d430e2118bff1fd816f66c10/src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx#L247)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

How well do these functions round trip? For example, suppose the slider is moved to 3...algorithm sets volume attr to 0.000027 ...I suppose we're storing enough precision that  converting it back to a rounded integer will produce 3? And similarly for all 101 possible slider values?
</blockquote></details>

You're just trying to make my life complicated :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2272)*

**Pull request merged**
