### PR TITLE
Add ability to convert color images to CMYK (BL-4457)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1704)

### CODE REVIEW

**Comment by hatton** [comment]
On Windows at least, the font that the License Dialog uses is scary. Please just add style="font-family:sans-serif" to the <body> tag.

**Comment by hatton** [comment]
See what you can do about adding some localization to this... even without getting other versions of the eula, if the text you add at the top, and the dialog title, and the button text were localizable, at least people would know what it is they are seeing.

**Comment by hatton** [comment]
Please make the title of the license dialog read "Adobe Color Profile License Agreement".

**Comment by StephenMcConnel** [comment]
The button text is already localizable.  I've added code to set the dialog title with a localized string, and to prepend a localized string to the content of the markdown license file.  I tried setting the style on the body tag since that's the only place I could see to do it.
I also added another command line switch to ghostscript that actually causes CMYK conversion as far as I can tell.  ("strings x.pdf | grep /ColorSpace/")

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1704#-:-KmXcfy36uhi688lxPz6:b2qpr6c)*

**Comment by hatton** [comment]
Review status: 0 of 17 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/app.config, line 19 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1704#-KmYmy8fbjDewWMO2Shn:-KmYmy8fbjDewWMO2Sho:b-9c6rd5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d2eb329ac815a67aada436cee9446e2354940f6/src/BloomExe/app.config#L19)):*
> ```
>         <value />
>       </setting>
>       <setting name="UserInterfaceLanguageSetExplicitly" serializeAs="String">
> ```

 I'm surprised to see this in this PR. I assume you really want it?

---

*[src/BloomExe/BloomExe.csproj, line 1352 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1704#-KmYnI6WzZ93gucjJJU4:-KmYnI6WzZ93gucjJJU5:b-vx6gn7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d2eb329ac815a67aada436cee9446e2354940f6/src/BloomExe/BloomExe.csproj#L1352)):*
> ```XML
>   </ItemGroup>
>   <ItemGroup>
>     <IccFiles Include="..\..\DistFiles\icc\Color Profile EULA.pdf" />
> ```

Let's drop this.

---

*[src/BloomExe/Publish/PdfMaker.cs, line 108 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1704#-KmYnSTy5A0qagM2lu4j:-KmYnSTy5A0qagM2lu4k:b96uanb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d2eb329ac815a67aada436cee9446e2354940f6/src/BloomExe/Publish/PdfMaker.cs#L108)):*
> ```Smalltalk
> 				if (!String.IsNullOrEmpty(ChosenColorProfile.IccFile))
> 				{
> 					rgbProfile = FileLocator.GetFileDistributedWithApplication("icc/RGB/AdobeRGB1998.icc");
> ```

Shall we change name from "icc" --> "color profiles"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1704)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/app.config, line 19 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1704#-KmYmy8fbjDewWMO2Shn:-KmbIFXPEPMm7PTD2a9u:b-t9vshd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d2eb329ac815a67aada436cee9446e2354940f6/src/BloomExe/app.config#L19)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

 I'm surprised to see this in this PR. I assume you really want it?
</blockquote></details>

This was an artifact from Visual Studio.  I've removed it.

---

*[src/BloomExe/BloomExe.csproj, line 1352 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1704#-KmYnI6WzZ93gucjJJU4:-KmbIL0GaZ00tAsQMZCL:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d2eb329ac815a67aada436cee9446e2354940f6/src/BloomExe/BloomExe.csproj#L1352)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Let's drop this.
</blockquote></details>

Done.

---

*[src/BloomExe/Publish/PdfMaker.cs, line 108 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1704#-KmYnSTy5A0qagM2lu4j:-KmbIMaUvON0IkDJfsIF:b-9ezep3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d2eb329ac815a67aada436cee9446e2354940f6/src/BloomExe/Publish/PdfMaker.cs#L108)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Shall we change name from "icc" --> "color profiles"?
</blockquote></details>

changed directory name to ColorProfiles

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1704)*

**Pull request merged**
