### PR TITLE
Massive renaming

### PR DESCRIPTION
**Pull request by JohnThomson**
To the best of my knowledge, all these changes are simple renames: file name changes in the first commit (and one snuck into the second), and class and method renames in the second. It should only be necessary to review a few places where I changed comments.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033)

### CODE REVIEW

**Review by jsubloom — CHANGES_REQUESTED** [review]
> Reviewed 77 of 77 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/web/BloomApiHandler.cs, line 56 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033#-MyCrda1EC8vpgboCdPz:-MyCrda1EC8vpgboCdQ-:b-tjo4j7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/09ab26f992b2728238bf4e77edc4356f70721dc6/src/BloomExe/web/BloomApiHandler.cs#L56)):*
> ```Smalltalk
> 		/// where the local path of the URI starts with /bloom/api/ and what follows in the localPath matches
> 		/// the regex pattern passed to the method. This is very inefficient and we are trying to retire this method
> 		/// and its variants. Please design apis that can be used with the new RegisterEndpoint
> ```

RegisterEndpointHandler



_Code quote:_
```Smalltalk
RegisterEndpoint
```
___
*[src/BloomExe/web/BloomApiHandler.cs, line 66 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033#-MyCrVAM6b74CL1qgj9O:-MyCrVAM6b74CL1qgj9P:b-tjo4j7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/09ab26f992b2728238bf4e77edc4356f70721dc6/src/BloomExe/web/BloomApiHandler.cs#L66)):*
> ```Smalltalk
> 		/// Please also consider whether a new RegisterEndpointStartsWith would serve.</remarks>
> 		/// <param name="pattern">Simple string or regex to match APIs that this can handle. This must match what comes after the ".../api/" of the URL</param>
> 		[Obsolete("Method is deprecated, please use RegisterEndpoint or other variant")]
> ```

RegisterEndpointHandler



_Code quote:_
```Smalltalk
RegisterEndpoint
```
___
*[src/BloomExe/web/BloomApiHandler.cs, line 214 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033#-MyCrsyYAltOv5AKQTID:-MyCrsyYAltOv5AKQTIE:bgcqblr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/09ab26f992b2728238bf4e77edc4356f70721dc6/src/BloomExe/web/BloomApiHandler.cs#L214)):*
> ```Smalltalk
> 				// would work as intended by testing that pair.Key.ToLower.StartsWith(endpointPath).
> 				// To encourage progress towards this, we have renamed things so that new pattern registrations
> 				// can be made only by using the deprecated RegisterEndpointLegacy; the new RegisterEndPoint
> ```

Add Handler again. Also check with "whole word match" for any other usages off RegisterEndpoint... I'm not as eagle-eyed as Andrew :)



_Code quote:_
```Smalltalk
RegisterEndPoint
```
___
*[src/BloomTests/Edit/ConfiguratorTest.cs, line 115 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033#-MyCsd78Etp7hC8tTq69:-MyCsd78Etp7hC8tTq6A:b-snclxa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/09ab26f992b2728238bf4e77edc4356f70721dc6/src/BloomTests/Edit/ConfiguratorTest.cs#L115)):*
> ```Smalltalk
> 			var firstData = DynamicJson.Serialize(new
> 			{
> 				library = new { one = "1", color="red" }
> ```

Optional: Could consider renaming this too, but this looks like it might be more effort since it seems to be part of some API, I don't mind skipping this
___
*[src/BloomTests/Edit/ConfiguratorTest.cs, line 122 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033#-MyCsUnf6asLTUPZ-Gef:-MyCsUnf6asLTUPZ-Geg:b-jsnf7j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/09ab26f992b2728238bf4e77edc4356f70721dc6/src/BloomTests/Edit/ConfiguratorTest.cs#L122)):*
> ```Smalltalk
> 			});
> 
> 			var first = new Configurator(_libraryFolder.Path, NavigationIsolator.GetOrCreateTheOneNavigationIsolator());
> ```

Probably mean to rename _libraryFolder too?



_Code quote:_
```Smalltalk
_libraryFolder
```
___
*[src/BloomTests/TestDoubles/CollectionTab/FakeCollectionModel.cs, line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033#-MyCsrW-9VGZv0IMhb0A:-MyCsrW-9VGZv0IMhb0B:b-bd7o2e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/09ab26f992b2728238bf4e77edc4356f70721dc6/src/BloomTests/TestDoubles/CollectionTab/FakeCollectionModel.cs#L13)):*
> ```Smalltalk
> {
> 	// A simplified implementation of CollectionModel that cuts some corners in order to ease setup.
> 	// Tries to provide enough functionality to allow construction of LibraryListView without exceptions, to be able to return/load a collection, and instntiate a dummy SourceCollectionsList which has a dummy templates collection
> ```

LibraryListView probably no longer exists



_Code quote (from src/BloomTests/TestDoubles/CollectionTab/FakeCollectionModel.cs):_
```Smalltalk
LibraryListView
```

**Review by gmartin7 — COMMENTED** [review]
> Reviewed 34 of 77 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033)* status: all files reviewed, 9 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Edit/AudioRecording.cs, line 104 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033#-My9esDBEfk8k553lTMN:-My9esDBEfk8k553lTMO:b-8iasxo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/cf4340f67b30882b3573d1062cc1ca70662dde21/src/BloomExe/Edit/AudioRecording.cs#L104)):*
> ```Smalltalk
> 			// Note: This handler locks and unlocks a shared resource (_completeRecording lock).
> 			// Any other handlers depending on this resource should not wait on the same thread (i.e. the UI thread) or deadlock can occur.
> 			apiHandler.RegisterEndpointHandler("audio/endRecord", HandleEndRecord, true).Measureable();
> ```

I confess I must be not understanding the difference between the old style apiHandler and the new one. Why couldn't these stay as RegisterEndpointHandler (and use what was the REHExact version)? Is it because of the `.Measurable()` on the end? The urls seem exact to me.
___
*[src/BloomExe/Edit/PageControlsApi.cs, line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033#-My9qIgW5KRtgMA4FcE6:-My9qIgW5KRtgMA4FcE7:bs7n7vf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/09ab26f992b2728238bf4e77edc4356f70721dc6/src/BloomExe/Edit/PageControlsApi.cs#L36)):*
> ```Smalltalk
> 		public void RegisterWithApiHandler(BloomApiHandler apiHandler)
> 		{
> 			apiHandler.RegisterEndpointLegacy(kApiUrlPart + "requestState", request =>
> ```

As before, I guess I need to know the difference between the old and new versions. I get that this is just a rename, though. Are some of these slated for removal of "Legacy" eventually?
___
*[src/BloomExe/CollectionTab/CollectionTabView.Designer.cs, line 173 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033#-My9eP6x-rL6Hh2-npuR:-My9eP6x-rL6Hh2-npuS:b-8pedem) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/09ab26f992b2728238bf4e77edc4356f70721dc6/src/BloomExe/CollectionTab/CollectionTabView.Designer.cs#L173)):*
> ```Smalltalk
> 			// 
> 			this._openCreateCollectionButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
> 			this._openCreateCollectionButton.Image = global::Bloom.Properties.Resources.OpenCreateCollection24x24;
> ```

Is this sufficient to rename the image? Or maybe I'll find a filename change elsewhere?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033)* status: all files reviewed, 9 unresolved discussions (waiting on @gmartin7 and @sujeffreyl)

___
*[src/BloomExe/Edit/AudioRecording.cs, line 104 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033#-My9esDBEfk8k553lTMN:-MyDEA2ZDAK7mY-veU3W:bagr32d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/cf4340f67b30882b3573d1062cc1ca70662dde21/src/BloomExe/Edit/AudioRecording.cs#L104)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I confess I must be not understanding the difference between the old style apiHandler and the new one. Why couldn't these stay as RegisterEndpointHandler (and use what was the REHExact version)? Is it because of the `.Measurable()` on the end? The urls seem exact to me.
</blockquote></details>

There are probably a couple of hundred calls to what is now RegisterEndpointLegacy. I'm guessing about 95% of them should ideally be changed to the new method that used to be RegisterEndpointHandlerExact. The trick is to figure out which 5% are handlers that actually deal with multiple similar localPaths. I'm thinking that is a task we can do gradually (and share). Most of them are not used so frequently that the performance cost is an issue. Still, the more that are changed, the faster all the rest will be, so I hope we'll continue to make progress with this.
___
*[src/BloomExe/Edit/PageControlsApi.cs, line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033#-My9qIgW5KRtgMA4FcE6:-MyDEyxr4tNQayRvrVMi:bg8ivhy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/09ab26f992b2728238bf4e77edc4356f70721dc6/src/BloomExe/Edit/PageControlsApi.cs#L36)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

As before, I guess I need to know the difference between the old and new versions. I get that this is just a rename, though. Are some of these slated for removal of "Legacy" eventually?
</blockquote></details>

Yes, all of them, I hope, will eventually switch to something else...most to the new RegisterEndpointHandler, some we may break up a handler that deals with several localPaths into multiple exact ones, some we may change things so that instead of multiple localPaths they are distinguished by a param, or we MIGHT decide to create RegisterEndpointHandlerStartsWith, or even RegisterEndpointHandlerPattern if we really need the "match by regex" for some reason.
___
*[src/BloomExe/web/BloomApiHandler.cs, line 56 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033#-MyCrda1EC8vpgboCdPz:-MyDFzet5yiykhKZFi8C:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/09ab26f992b2728238bf4e77edc4356f70721dc6/src/BloomExe/web/BloomApiHandler.cs#L56)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

RegisterEndpointHandler
</blockquote></details>

Done.
___
*[src/BloomExe/web/BloomApiHandler.cs, line 66 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033#-MyCrVAM6b74CL1qgj9O:-MyDG-6b50z20gRxbaxU:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/09ab26f992b2728238bf4e77edc4356f70721dc6/src/BloomExe/web/BloomApiHandler.cs#L66)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

RegisterEndpointHandler
</blockquote></details>

Done.
___
*[src/BloomExe/web/BloomApiHandler.cs, line 214 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033#-MyCrsyYAltOv5AKQTID:-MyDG0hrCT1WzcmBxtDX:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/09ab26f992b2728238bf4e77edc4356f70721dc6/src/BloomExe/web/BloomApiHandler.cs#L214)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Add Handler again. Also check with "whole word match" for any other usages off RegisterEndpoint... I'm not as eagle-eyed as Andrew :)
</blockquote></details>

Done.
___
*[src/BloomTests/Edit/ConfiguratorTest.cs, line 115 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033#-MyCsd78Etp7hC8tTq69:-MyDG3hq7CagOE17ETZF:b-hgbujh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/09ab26f992b2728238bf4e77edc4356f70721dc6/src/BloomTests/Edit/ConfiguratorTest.cs#L115)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Optional: Could consider renaming this too, but this looks like it might be more effort since it seems to be part of some API, I don't mind skipping this
</blockquote></details>

Yes, I'm assuming the JSON file is stored somewhere, and changing the name would likely cause problems.
___
*[src/BloomTests/Edit/ConfiguratorTest.cs, line 122 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033#-MyCsUnf6asLTUPZ-Gef:-MyDHjPt5dME9wc-kghF:b-boemjx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/09ab26f992b2728238bf4e77edc4356f70721dc6/src/BloomTests/Edit/ConfiguratorTest.cs#L122)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Probably mean to rename _libraryFolder too?
</blockquote></details>

Done. (And found several more things in this class to rename, too)
___
*[src/BloomExe/CollectionTab/CollectionTabView.Designer.cs, line 173 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033#-My9eP6x-rL6Hh2-npuR:-MyD8xRe2FQMKk4cXWjV:bvze8n7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/09ab26f992b2728238bf4e77edc4356f70721dc6/src/BloomExe/CollectionTab/CollectionTabView.Designer.cs#L173)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Is this sufficient to rename the image? Or maybe I'll find a filename change elsewhere?
</blockquote></details>

Apparently not. VS is too stupid to rename the associated file, or even provide an easy way to do so. I found several more resources to rename while fixing this!
___
*[src/BloomTests/TestDoubles/CollectionTab/FakeCollectionModel.cs, line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033#-MyCsrW-9VGZv0IMhb0A:-MyDIIUNDmSa0Y79l3o_:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/09ab26f992b2728238bf4e77edc4356f70721dc6/src/BloomTests/TestDoubles/CollectionTab/FakeCollectionModel.cs#L13)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

LibraryListView probably no longer exists
</blockquote></details>

Done.

**Review by jsubloom — APPROVED** [review]
:lgtm:

> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033#-:-MyDJF2z7L-ISb_7zf-t:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @gmartin7)

**Review by gmartin7 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by gmartin7 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5033#-:-MyDYleY4KUN8OFocF4R:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
