### PR TITLE
BL-4471 Direct user to help with file permissions

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1618)

### CODE REVIEW

**Comment by andrew-polk** [comment]
:lgtm: with one minor suggestion.
Feel free to merge without change.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DistFiles/localization/Bloom.en.tmx, line 2530 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1618#-KgLdh9El1aDQzFUsie5:-KgLdh9El1aDQzFUsie6:btmsxyp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/999b3f84fc135f31a4e78dd775373bec0b08e39d/DistFiles/localization/Bloom.en.tmx#L2530)):*
> ```
>       </tuv>
>     </tu>
>     <tu tuid="Errors.HelpFilePermissions">
> ```

Not a big deal, but I thought this had something to do with a help file.
Would FilePermissionsHelp be better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1618#-:-KgLe5Vw_hTmwfAQtL9i:b-gyqb8d)*

**Comment by JohnThomson** [comment]
Did your suggestion and caught a much more serious problem while testing it :-)

---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[DistFiles/localization/Bloom.en.tmx, line 2530 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1618#-KgLdh9El1aDQzFUsie5:-KgLkBz61nirxKgXxF0q:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/999b3f84fc135f31a4e78dd775373bec0b08e39d/DistFiles/localization/Bloom.en.tmx#L2530)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Not a big deal, but I thought this had something to do with a help file.
Would FilePermissionsHelp be better?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1618#-:-KgLkEEyLkyk97dWtGke:b-jiojpi)*

**Comment by hatton** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/BookStorage.cs, line 860 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1618#-KgLkZRwdiV4qmqI8tKF:-KgLkZRwdiV4qmqI8tKG:biqry5l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5e63109f68d15a6e1c612b444022c9cd321b27d1/src/BloomExe/Book/BookStorage.cs#L860)):*
> ```Smalltalk
> 			message = WebUtility.HtmlEncode(message);
> 			var helpUrl = @"http://community.bloomlibrary.org/t/how-to-fix-file-permissions-problems/78";
> 			var seeAlso = WebUtility.HtmlEncode(LocalizationManager.GetString("Errors.FilePermissionsHelp", "See {0} for one way to fix this."));
> ```

The weight of each new thing that needs to be localized * 12 is really weighing on me.

How about if we change this to something generic like "????.SeeWebPage", "See {0}", "Used to point the user to a web page. Put the '{0}' where the web page URL will go". Need to  think on what the ??? should be...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1618)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/BookStorage.cs, line 860 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1618#-KgLkZRwdiV4qmqI8tKF:-KgLlRuMuRbbHgF8SmbB:b-siuevv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5e63109f68d15a6e1c612b444022c9cd321b27d1/src/BloomExe/Book/BookStorage.cs#L860)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

The weight of each new thing that needs to be localized * 12 is really weighing on me.

How about if we change this to something generic like "????.SeeWebPage", "See {0}", "Used to point the user to a web page. Put the '{0}' where the web page URL will go". Need to  think on what the ??? should be...
</blockquote></details>

How about "Common.SeeWebPage".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1618)*

**Pull request merged**
