### PR TITLE
HandleThumbnailRequest gracefully fails if bookInfo is null (BL-12354)

### PR DESCRIPTION
**Pull request by jsubloom**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5941)

### CODE REVIEW

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5941)* status: 0 of 1 files reviewed, 4 unresolved discussions

___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 387 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5941#-NYKl-T6B7OzeHYw5gXN:-NYKl-T6B7OzeHYw5gXO:ba22vh5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f17a79b77c667680e0298b197e932d8278d1d3b7/src/BloomExe/web/controllers/CollectionApi.cs#L387)):*
> ```Smalltalk
> 		public void HandleThumbnailRequest(ApiRequest request)
> 		{
> 			var bookInfo = GetBookInfoFromRequestParam(request);
> ```

This isn't related to the issue, but.....
Should this line be after the lock?  What happens if this function call throws an exception?  Will _thumbnailEventsToWaitFor be messed up?
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 399 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5941#-NYKksT92ym70-p2FUse:-NYKksT92ym70-p2FUsf:bm3i4yg) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f17a79b77c667680e0298b197e932d8278d1d3b7/src/BloomExe/web/controllers/CollectionApi.cs#L399)):*
> ```Smalltalk
> 
> 			// Not sure what causes bookInfo to be null, but apparently it's possible: See BL-12354
> 			// Let's gracefully fail in this scenario
> ```

Even not knowing what causes bookInfo to be null in BL-12354, I figure this is still useful future-proofing. If in the future bookInfo comes back as null for some other reason, this will catch that too.
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 424 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5941#-NYKkcH--rHjsnFDH2oC:-NYKkcH--rHjsnFDH2oD:b-j5vxjw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f17a79b77c667680e0298b197e932d8278d1d3b7/src/BloomExe/web/controllers/CollectionApi.cs#L424)):*
> ```Smalltalk
> 				if (_collectionModel.GetBookFromBookInfo(bookInfo).HasFatalError)
> 					errorImg = Resources.Error70x70;
> 				using (var stream = ConvertImageToStream(errorImg))
> ```

NOTE: This is a change in functionality that technically has side effects. In the old code, the stream is not closed (as far as I can tell from inspection). In the new code, we close the stream here.
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 436 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5941#-NYKkpuHEmcb0m-QdBKk:-NYKkpuHEmcb0m-QdBKl:b-a0k91x) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f17a79b77c667680e0298b197e932d8278d1d3b7/src/BloomExe/web/controllers/CollectionApi.cs#L436)):*
> ```Smalltalk
> 		/// </summary>
> 		/// <remarks>The caller is responsible for ensuring the stream gets closed somehow</remarks>
> 		private MemoryStream ConvertImageToStream(System.Drawing.Bitmap image)
> ```

Or i can make it an extension method if preferred

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5941)* status: 0 of 1 files reviewed, 4 unresolved discussions

___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 424 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5941#-NYKkcH--rHjsnFDH2oC:-NYKlPVUD9qsM-orDT3g:b-90yz9s) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f17a79b77c667680e0298b197e932d8278d1d3b7/src/BloomExe/web/controllers/CollectionApi.cs#L424)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

NOTE: This is a change in functionality that technically has side effects. In the old code, the stream is not closed (as far as I can tell from inspection). In the new code, we close the stream here.
</blockquote></details>

request.ReplyWithStreamContent eventually calls this method, which doesn't close it. https://github.com/BloomBooks/BloomDesktop/blob/master/src/BloomExe/web/RequestInfo.cs#L252

**Review by andrew-polk — APPROVED** [review]

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5941)* status: 0 of 1 files reviewed, 4 unresolved discussions

___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 424 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5941#-NYKkcH--rHjsnFDH2oC:-NYKl_g9BH6LYtWt_87K:bvepm3u) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f17a79b77c667680e0298b197e932d8278d1d3b7/src/BloomExe/web/controllers/CollectionApi.cs#L424)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

request.ReplyWithStreamContent eventually calls this method, which doesn't close it. https://github.com/BloomBooks/BloomDesktop/blob/master/src/BloomExe/web/RequestInfo.cs#L252
</blockquote></details>

Well, this seems to be the only place where ReplyWithStream is used, so I guess we can do it either way we want.  (Making the producer of the stream close it, or  having the consumer of the stream close it)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5941)* status: all files reviewed, 2 unresolved discussions (waiting on @jsubloom)

___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 387 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5941#-NYKl-T6B7OzeHYw5gXN:-NYKmBPc4mZ_qPXXTO1E:bm9byke) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f17a79b77c667680e0298b197e932d8278d1d3b7/src/BloomExe/web/controllers/CollectionApi.cs#L387)):*
> Will \_thumbnailEventsToWaitFor be messed up?

Sure looks like it to me.
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 424 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5941#-NYKkcH--rHjsnFDH2oC:-NYKmPfU6Oj2h2nDmkqi:b-wx0gb8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f17a79b77c667680e0298b197e932d8278d1d3b7/src/BloomExe/web/controllers/CollectionApi.cs#L424)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

Well, this seems to be the only place where ReplyWithStream is used, so I guess we can do it either way we want.  (Making the producer of the stream close it, or  having the consumer of the stream close it)
</blockquote></details>

This feels like the more natural paradigm/idiom.
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 436 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5941#-NYKkpuHEmcb0m-QdBKk:-NYKmHZ35Lv1y-oWn-N1:b-um8xls) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f17a79b77c667680e0298b197e932d8278d1d3b7/src/BloomExe/web/controllers/CollectionApi.cs#L436)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

Or i can make it an extension method if preferred
</blockquote></details>

'tis good as is methinks

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5941)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 387 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5941#-NYKl-T6B7OzeHYw5gXN:-NYKn3LR0qVZhDjjBVeJ:b-qbusia) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f17a79b77c667680e0298b197e932d8278d1d3b7/src/BloomExe/web/controllers/CollectionApi.cs#L387)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> Will \_thumbnailEventsToWaitFor be messed up?

Sure looks like it to me.
</blockquote></details>

Ok, maybe I'll move it in master branch.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5941)* status: all files reviewed, 1 unresolved discussion

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5941)* status: all files reviewed, 1 unresolved discussion

___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 387 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5941#-NYKl-T6B7OzeHYw5gXN:-NYKpCXz8PBhH52xLfR0:b32wtd) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f17a79b77c667680e0298b197e932d8278d1d3b7/src/BloomExe/web/controllers/CollectionApi.cs#L387)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

Ok, maybe I'll move it in master branch.
</blockquote></details>

ok

**Review by andrew-polk — APPROVED** [review]
> Dismissed @jsubloom from a discussion.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5941)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsubloom)

**Pull request merged**
