### PR TITLE
Allow folder level bulk upload for Linux in Bloom GUI (BL-9997)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4592)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4592)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, line 643 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4592#-MekILkV-IHLQMBvnrtB:-MekILkV-IHLQMBvnrtC:b-6cehmp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fceb12acea37eeca1366fd6e12b4de7a78e262a2/src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs#L643)):*
> ```Smalltalk
> 		{
> 			// Note, this is Windows only.
> 			CommonOpenFileDialog dialog = new CommonOpenFileDialog
> ```

Is there a reason not to use DialogAdapters.OpenFileDialogAdapter?

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4592)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4592)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, line 643 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4592#-MekILkV-IHLQMBvnrtB:-MelNglE7HyBWJeTLpGt:bkq3m6c) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fceb12acea37eeca1366fd6e12b4de7a78e262a2/src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs#L643)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is there a reason not to use DialogAdapters.OpenFileDialogAdapter?
</blockquote></details>

This would simplify the code, but it would change the GUI behavior.  The CommonOpenFileDialog produces 

while DialogAdapters.FolderBrowserDialogAdapter produces 

DialogAdapters does not allow using the file chooser as a folder chooser like CommonOpenFileDialog does.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4592)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, line 643 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4592#-MekILkV-IHLQMBvnrtB:-MelPj5MBIavbt72cDPy:b-xex8pm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fceb12acea37eeca1366fd6e12b4de7a78e262a2/src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs#L643)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

This would simplify the code, but it would change the GUI behavior.  The CommonOpenFileDialog produces 

while DialogAdapters.FolderBrowserDialogAdapter produces 

DialogAdapters does not allow using the file chooser as a folder chooser like CommonOpenFileDialog does.

</blockquote></details>

Ok, thanks.
Should we go ahead and extract a platform-independent component for the next time we want this UI, then?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4592)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, line 643 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4592#-MekILkV-IHLQMBvnrtB:-Mf-9i8-8Yvf6yqReHxF:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fceb12acea37eeca1366fd6e12b4de7a78e262a2/src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs#L643)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Ok, thanks.
Should we go ahead and extract a platform-independent component for the next time we want this UI, then?
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4592)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
