### PR TITLE
BL-6303 Make Save on deactivate wait for Idle

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2646)

### CODE REVIEW

**Review by StephenMcConnel — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2646#-:-LIh7x0s4ZEB_w8DLOjm:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2646)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Edit/EditingView.cs, line 1413 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2646#-LIh7rxn-SDoUNwvpuAN:-LIh7rxn-SDoUNwvpuAO:b-i0blsg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/173c419f0e902cdeaa62f49a4c4dc029fe6df8ef/src/BloomExe/Edit/EditingView.cs#L1413)):*
> ```Smalltalk
> 					// and the HTML file and containing folder changed name. Instead, arrange to Save when
> 					// next idle.
> 					Application.Idle += SaveWhenIdle;
> ```

One of the places that Deactivate saved (based on my putting a Logger message in this eventhandler), was on program exit. Will it still do that? Or do we Save elsewhere if the user exits?

**Review by andrew-polk — APPROVED** [review]
Assuming the answer to Gordon's question is yes, :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2646#-:-LIhA4x9E7xECoTa0C3w:b-y08ur8)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2646)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Edit/EditingView.cs, line 1413 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2646#-LIh7rxn-SDoUNwvpuAN:-LIhEjHI6TUE9x8BLtoQ:b-fv0qo7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/173c419f0e902cdeaa62f49a4c4dc029fe6df8ef/src/BloomExe/Edit/EditingView.cs#L1413)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

One of the places that Deactivate saved (based on my putting a Logger message in this eventhandler), was on program exit. Will it still do that? Or do we Save elsewhere if the user exits?
</blockquote></details>

By test, it does. Also I'm sure this used to work, long before Steve added the Deactivate stuff, and his PR didn't take any of that out.

**Pull request merged**
