### PR TITLE
Add Borders and Background tab to TextBoxProperties (BL-4238,BL-4239)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1504)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.less, line 19 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-Kd7gpqbEz-Q4N0BmlBP:-Kd7gpqbEz-Q4N0BmlBQ:bof03kl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2e4289fc1685a9eb919bc8a3c2cfa0a2120a37a5/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.less#L19)):*
> ```Less
>         color: grey;
>     }
>     .mainBlock {
> ```

I moved this up to bloomDialog.less

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 935 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-Kd7gtFY3_H9JxrcANW9:-Kd7gtFY3_H9JxrcANWA:b-l66sg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2e4289fc1685a9eb919bc8a3c2cfa0a2120a37a5/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L935)):*
> ```XML
>     }
> 
>     preferredGray(): string {
> ```

I moved this into basePage.less

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504)*

**Comment by JohnThomson** [comment]
:lgtm:. I'm just being picky about a lot of little things. Open to being persuaded some should not change (or not worth it).

---

Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 120 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBZmDqfDGbXhHjZV1u:-KdBZmDqfDGbXhHjZV1v:b-rgupyj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L120)):*
> ```XML
>             'border-none', 'border-black', 'border-black-round', 'border-gray', 'border-gray-round',
>             'background-none', 'background-light-gray', 'background-gray', 'background-black',
>             'bordertop', 'borderleft', 'borderright', 'borderbottom'];
> ```

It kind of threw me that there is both a choose-one group of ids starting with border- and a group of related but not mutually exclusive ones that start with border. How about calling the second group edgetop etc? Or the first group borderstyle-X?

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 135 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBYs0svBjRJoqfkWf0:-KdBYs0tPUkPfT_Yfkh_:b2pge3w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L135)):*
> ```XML
>         for (var idIndex = 0; idIndex < buttonIds.length; idIndex++) {
>             var button = $('#' + buttonIds[idIndex]);
>             button.click(function () { dialog.buttonClick(this); });
> ```

This is an interesting case where the function() notation is may be  clearer than the => notation. I still very much prefer the => notation, because I frequently get confused by changing the definition of 'this. If I'm reading it correctly, our coding standard agrees (8.1). Discuss?

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 238 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBpe3LWgABpGW_cy3q:-KdBpe3LWgABpGW_cy3r:b12jtbz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L238)):*
> ```XML
>     }
> 
>     changeBorder(targetGroup, styleChanged: boolean) {
> ```

Took me a while to figure out what styleChanged means. Comment something like "styleChanged is true if the change was to the style of border, false if it involved one of the border side controls.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 245 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBrGv3eA8YuwTbcVx7:-KdBrGv3eA8YuwTbcVx8:b-xkuzx2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L245)):*
> ```XML
>         targetGroup.removeClass('bloom-border-black-round');
>         targetGroup.removeClass('bloom-border-gray');
>         targetGroup.removeClass('bloom-border-gray-round');
> ```

I suppose there's no way for the box to inherit a border from something (other than the faint one we put when it's selected, which we don't want to suppress) so we don't need an explicit bloom-border-none style?

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 288 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBq1Kx4cat1rQaDf5y:-KdBq1Kx4cat1rQaDf5z:bww5r41) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L288)):*
> ```XML
>     }
> 
>     anyBorderStyleButtonSelected(): boolean {
> ```

So this really means, any border style button EXCEPT the None one, right? Because one of them is ALWAYS selected. I'd like to find a better name...borderStyleIsNotNone? someBorderStyle? boxHasABorder is tempting, but it has to combine with the possibility that all the sides are off, which might cause it not to have even though a style is selected...

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 316 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBoxvYimhZbGCBpUCm:-KdBoxvYimhZbGCBpUCn:b-rsbnnt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L316)):*
> ```XML
>     }
> 
>     selectBorderNoneButton() {
> ```

I have a vague recollection of code that understands groups of buttons and can select one and deselect the others...probably triggered in response to click. Maybe that could be used here?

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts, line 16 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBsBgB78wML9zKE8Cw:-KdBsBgCI_qwCJr11h6Q:b-arxhaz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts#L16)):*
> ```XML
> 
>     it('changeBackground, to none, css set properly', function () {
>         $('body').append('<div id="background-none" class="selectedIcon"></div>');
> ```

It took me a while to figure out what this extra div was for...a comment noting that it simulates the button that changeBackground is looking for would help. (I think just on the first test using this strategy is probably enough.)

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts, line 40 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBtAaNNAemx2LI5y7p:-KdBtAaNNAemx2LI5y7q:b-6302le) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts#L40)):*
> ```XML
> 
>         expect($('#testTarget').hasClass('bloom-border-black')).toBeTruthy();
>         expect($('#testTarget').hasClass('bloom-top-border-off')).toBeFalsy();
> ```

Since #testTarget didn't have any of these classes to begin with, it's not a very stringent test.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts, line 83 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBtWzsZPhpv5bAam9h:-KdBtWzsZPhpv5bAam9i:b-me8wux) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts#L83)):*
> ```XML
>         dialog.changeBorder($('#testTarget'), true);
> 
>         expect($('#testTarget').hasClass('bloom-border-black')).toBeFalsy();
> ```

Again, would be a better test if the target had this class to begin with. (And in following tests.)

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts, line 124 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBu6WHenlIRTvSt2dl:-KdBu6WHenlIRTvSt2dm:bb1jmsl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts#L124)):*
> ```XML
> 
>     it('changeBorder, deselect side, css classes set properly', function () {
>         $('body').append('<div id="border-none"></div>');
> ```

For this to simulate deselecting a side, doesn't the target div have to be in the initial state of having some other combination of border sides? Similarly in following.

---

*[src/BloomBrowserUI/bookLayout/basePage.less, line 547 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBux49nORrp9RYbij6:-KdBux4AJPgMWMj-LF_S:b-20z9ip) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookLayout/basePage.less#L547)):*
> ```Less
>     border: 1px solid black;
>     border-radius: 0px;
>     box-sizing: border-box;
> ```

I think a comment is in order to explain why the box-sizing is needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-:-KdBvCaj2icke8_dHhvk:blme2c5)*

**Comment by JohnThomson** [comment]
I've made a few more responses that might help.

---

Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 135 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBYs0svBjRJoqfkWf0:-KdQvhfkePuvQ1adw7cA:bj2uvv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L135)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This fixes a bug where the user previously had to click the internal image or div in the button. Clicking around the edge would do nothing. To fix the bug, I simply copied what StyleEditor was doing. I didn't really think about how to write it with => notation.
</blockquote></details>

I did a bit more research. I think at some point I came up with e => {this.buttonClick(event.target.parentElement} which apparently doesn't cut it. However, I did some more research, and it turns out that event.target is the thing you clicked, not the thing the event is attached to. There is another property (http://api.jquery.com/event.currentTarget/) that is defined to be the same thing that would be 'this' for a function. So e => this.buttonClick(e.currentTarget) should be exactly equivalent to what you have (and avoid the need to define a variable to preserve the outer 'this').

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 245 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBrGv3eA8YuwTbcVx7:-KdQtMevAptQGyTJyVfr:b-47iulg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L245)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

For the none style case, we set all the bloom-xxx-border-off classes which set each side to none.
</blockquote></details>

Interesting. Doesn't that suppress the faint box around the area that appears in edit mode?

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts, line 124 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBu6WHenlIRTvSt2dl:-KdQtn0b73XRm7s8Un72:b-rfmcon) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts#L124)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Unless I can figure out a way to test the parent method, I think this is as good as it gets. We call changeBorder after the button selection happens.
</blockquote></details>

No, you're missing my point. Below you test, e.g., that testTarget.hasClass(bloom-border-gray) is false. But it's already false, so that would be true even if the SUT did nothing about turning it off. So the line above should have things like <div id="border-none" class="bloom-border-gray"></div>.
Or else I'm missing your point. I don't see how any parent method needs testing.

---

*[src/BloomBrowserUI/bookLayout/basePage.less, line 547 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBux49nORrp9RYbij6:-KdQuONBDtdbY_TDxwVj:b-7aghcd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookLayout/basePage.less#L547)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't know. : ) I copied it from the old style editor code.
I can try to do some research.
</blockquote></details>

Probably not worth a lot. If you don't know, there's no knowledge to conserve...someone can research it when someone needs to know!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-:-KdQwxRhdq-DY6T-hg9l:b-trqwyo)*

**Comment by andrew-polk** [comment]
Review status: 15 of 19 files reviewed at latest revision, 13 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 120 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBZmDqfDGbXhHjZV1u:-KdS3yVAsMjJE9BVedZn:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L120)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It kind of threw me that there is both a choose-one group of ids starting with border- and a group of related but not mutually exclusive ones that start with border. How about calling the second group edgetop etc? Or the first group borderstyle-X?
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 135 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBYs0svBjRJoqfkWf0:-KdS4G7VLaGuXTUYG4OW:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L135)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I did a bit more research. I think at some point I came up with e => {this.buttonClick(event.target.parentElement} which apparently doesn't cut it. However, I did some more research, and it turns out that event.target is the thing you clicked, not the thing the event is attached to. There is another property (http://api.jquery.com/event.currentTarget/) that is defined to be the same thing that would be 'this' for a function. So e => this.buttonClick(e.currentTarget) should be exactly equivalent to what you have (and avoid the need to define a variable to preserve the outer 'this').
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 238 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBpe3LWgABpGW_cy3q:-KdS8HG4O-kJiCqDWqoF:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L238)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Took me a while to figure out what styleChanged means. Comment something like "styleChanged is true if the change was to the style of border, false if it involved one of the border side controls.
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 245 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBrGv3eA8YuwTbcVx7:-KdSAI1DWW-DBqKwq-J5:b-rup8o7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L245)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Interesting. Doesn't that suppress the faint box around the area that appears in edit mode?
</blockquote></details>

No, the element we are working with here is the translationGroup. The other border is on the bloom-editable elements which are children of that.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 288 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBq1Kx4cat1rQaDf5y:-KdS8wYcUGmORgDjdzED:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L288)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

So this really means, any border style button EXCEPT the None one, right? Because one of them is ALWAYS selected. I'd like to find a better name...borderStyleIsNotNone? someBorderStyle? boxHasABorder is tempting, but it has to combine with the possibility that all the sides are off, which might cause it not to have even though a style is selected...
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 316 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBoxvYimhZbGCBpUCm:-KdSCYY8zS59223PAh_W:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L316)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I have a vague recollection of code that understands groups of buttons and can select one and deselect the others...probably triggered in response to click. Maybe that could be used here?
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts, line 16 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBsBgB78wML9zKE8Cw:-KdSGCaYvl5M9D_aIwDL:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts#L16)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It took me a while to figure out what this extra div was for...a comment noting that it simulates the button that changeBackground is looking for would help. (I think just on the first test using this strategy is probably enough.)
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts, line 40 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBtAaNNAemx2LI5y7p:-KdSKJ8trjMcyeP5XeM4:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts#L40)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Since #testTarget didn't have any of these classes to begin with, it's not a very stringent test.
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts, line 83 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBtWzsZPhpv5bAam9h:-KdSOmw3reO0WMlvYCFj:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts#L83)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Again, would be a better test if the target had this class to begin with. (And in following tests.)
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts, line 124 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBu6WHenlIRTvSt2dl:-KdSRQIgOAtNh6eTsNqv:bjii6ci) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts#L124)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

No, you're missing my point. Below you test, e.g., that testTarget.hasClass(bloom-border-gray) is false. But it's already false, so that would be true even if the SUT did nothing about turning it off. So the line above should have things like <div id="border-none" class="bloom-border-gray"></div>.
Or else I'm missing your point. I don't see how any parent method needs testing.
</blockquote></details>

Thanks for clarifying. Unfortunately, Reviewable removed your example, but I think I have improved the test in the way you suggest.

---

*[src/BloomBrowserUI/bookLayout/basePage.less, line 547 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBux49nORrp9RYbij6:-KdS9XCQTDb4O2UZ_FvJ:b32wtd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookLayout/basePage.less#L547)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Probably not worth a lot. If you don't know, there's no knowledge to conserve...someone can research it when someone needs to know!
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504)*

**Comment by JohnThomson** [comment]
Much improved...one place might still need a little attention. Thanks!

---

Review status: 12 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts, line 124 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBu6WHenlIRTvSt2dl:-KdWGmOtDST0mJTJBNJp:b-h1v0gp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts#L124)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Thanks for clarifying. Unfortunately, Reviewable removed your example, but I think I have improved the test in the way you suggest.
</blockquote></details>

This one still doesn't feel quite right. The new line you added gives it the class bloom-borderstyle-black-round to begin with, but you are checking for the SUT to add that. On the other hand, you want to check that the test removes e.g. bloom-top-border-off, but it's not there to begin with.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-:-KdWY4BBKtUkjNHkgzlL:b-ggiiun)*

**Comment by andrew-polk** [comment]
Review status: 12 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts, line 124 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBu6WHenlIRTvSt2dl:-KdW_BH-3xFdzQa9FG7F:b-brod02) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts#L124)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This one still doesn't feel quite right. The new line you added gives it the class bloom-borderstyle-black-round to begin with, but you are checking for the SUT to add that. On the other hand, you want to check that the test removes e.g. bloom-top-border-off, but it's not there to begin with.
</blockquote></details>

I admit these tests are confusing, even to me.
What I am attempting to mock with the test is the scenario in which the black round border style is selected and all border sides are selected. The user then deselects the bottom border.
So the state before user change should be that bloom-borderstyle-black-round is present but none of the bloom-xxx-border-off classes are present.
The user clicks the borderbottom button which removes class selectedIcon.
Then, we call changeBorder.
The border style remains unchanged as do the top, right, and left sides. But bloom-bottom-border-off is added.

I will try to add some clarifying comments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504)*

**Comment by JohnThomson** [comment]
Review status: 12 of 19 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts, line 124 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBu6WHenlIRTvSt2dl:-KdWfl8DA3IHTzI3rSM1:b-rvksem) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts#L124)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I admit these tests are confusing, even to me.
What I am attempting to mock with the test is the scenario in which the black round border style is selected and all border sides are selected. The user then deselects the bottom border.
So the state before user change should be that bloom-borderstyle-black-round is present but none of the bloom-xxx-border-off classes are present.
The user clicks the borderbottom button which removes class selectedIcon.
Then, we call changeBorder.
The border style remains unchanged as do the top, right, and left sides. But bloom-bottom-border-off is added.

I will try to add some clarifying comments.
</blockquote></details>

Seems then the initial state calls for adding the class bloom-borderstyle-black-round. OTOH, initial all-borders-on is correctly represented by NO border classes...that might be worth a comment. (Should be known after studying this code, but it tends to cause me confusion, though I think I see why you chose the negative classes.)
Might help to tag appropriate expects as // unchanged where you're just checking the SUT didn't mess things up (e.g., bloom-border-black false)

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts, line 130 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdWgmC_JOnymMIW3oap:-KdWgmC_JOnymMIW3oaq:b-1x2e25) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts#L130)):*
> ```XML
>         $('body').append('<div id="borderbottom"></div>');
>         $('body').append('<div id="borderleft" class="selectedIcon"></div>');
>         dialog.changeBorder($('#testTarget'), false);
> ```

A reminder here that 'false' means simulating a click on a side button might help

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504)*

**Comment by andrew-polk** [comment]
Review status: 12 of 19 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts, line 124 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504#-KdBu6WHenlIRTvSt2dl:-KdXFDD3fDPGd871B1Ef:b-fq3jo7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/578d1e72608901584317cb3b07fc39dec7966f03/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts#L124)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Seems then the initial state calls for adding the class bloom-borderstyle-black-round. OTOH, initial all-borders-on is correctly represented by NO border classes...that might be worth a comment. (Should be known after studying this code, but it tends to cause me confusion, though I think I see why you chose the negative classes.)
Might help to tag appropriate expects as // unchanged where you're just checking the SUT didn't mess things up (e.g., bloom-border-black false)
</blockquote></details>

Hm. I just realized that if you're seeing what I am seeing, it is no wonder that there is confusion between us. What I am currently seeing on Reviewable is not the latest version of this file (though github does have it).
Anyway, I did significantly clean up this test to make it more understandable. I'm going to go ahead and merge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1504)*

**Pull request merged**
