### PR TITLE
Adjust position of #overlay-context-controls (BL-13874)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6659)

### CODE REVIEW

**Review by JohnThomson — APPROVED** [review]
Does it work right with Image and Video overlays, which have a smaller bar? If so, can be merged.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6659#-:-O7-wCqU2e5JXTzXB_y_:b-wcvyvk)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6659)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 1468 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6659#-O70d1ww44pGPzmefRRR:-O70d1ww44pGPzmefRRS:brm9er1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/342b95b71bf93854bbf510465444489cdf75c6c0/src/BloomBrowserUI/bookEdit/css/editMode.less#L1468)):*
> ```Less
>     // below, centered. Wider than it ever needs to be; the button div inside
>     // will be fit-content and centered.
>     bottom: -58px;
> ```

Could we make things clearer with some variables along the lines @heightOfTextControlBar @heightOfOtherControlBar @controlBarGap? (I know, I didn't...but now we're moving from two magic numbers to four...). For example, hopefully 58px is the sum of @heightOfTextControlBar and @controlBarGap.
___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 1470 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6659#-O70aYdw0Y1fetjmtbJV:-O70aYdw0Y1fetjmtbJW:b-errsyv) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/342b95b71bf93854bbf510465444489cdf75c6c0/src/BloomBrowserUI/bookEdit/css/editMode.less#L1470)):*
> ```Less
>     bottom: -58px;
>     left: calc(50% - 150px);
>     width: 300px;
> ```

Looks like there are three settings (and two lines of comment) that are still common to simply  #overlay-context-controls. They aren't very likely to change, but I think it's still worth pulling out into one rule.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6659)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 1468 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6659#-O70d1ww44pGPzmefRRR:-O70ni1w4zdb79gETTeE:btpkgxw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/342b95b71bf93854bbf510465444489cdf75c6c0/src/BloomBrowserUI/bookEdit/css/editMode.less#L1468)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Could we make things clearer with some variables along the lines @heightOfTextControlBar @heightOfOtherControlBar @controlBarGap? (I know, I didn't...but now we're moving from two magic numbers to four...). For example, hopefully 58px is the sum of @heightOfTextControlBar and @controlBarGap.
</blockquote></details>

I've added these variables and tried to get nominal values for them.  They're at least within a pixel or so of what I saw in the WebView2 debugger, and provide essentially the same look on the screen.
___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 1470 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6659#-O70aYdw0Y1fetjmtbJV:-O70u7l15VsGKXshPhf5:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/342b95b71bf93854bbf510465444489cdf75c6c0/src/BloomBrowserUI/bookEdit/css/editMode.less#L1470)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Looks like there are three settings (and two lines of comment) that are still common to simply  #overlay-context-controls. They aren't very likely to change, but I think it's still worth pulling out into one rule.
</blockquote></details>

Done.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6659)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
