### PR TITLE
Fix BL-5824 which was using bloompack-installed customBookStyles instead

### PR DESCRIPTION
**Pull request by hatton**
In BL-5824, we got bit by a design decision we made that allows stylesheets installed via bloompack to override local ones. This was done so that we could send out new custom stylesheets via webpack and have those used in all the books. Fine. But that is indiscriminate; it also was grabbing any "customBookStyles.css" from those sources and using it instead and replacing that of your book.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2332)

### CODE REVIEW

**Comment by JohnThomson** [comment]
It appears from the comments and the commit summary that there are still circumstances where customBookStyles.css in a Bloompack should get used in "all" the books. (The ones IN the bloompack? Ones later derived from them? Existing books previously derived from books which they replace?) But the code as written seems to prevent all updates to customBookStyles.css and also overriding it by finding it anywhere else. (I'm also not following exactly what "those sources" are that we need to prevent getting it from.) 
Sorry, probably being dense here...still somewhat jeglagged.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2332#-:-LADP8nx0TT5CLRNHvLI:b-x22a1e)*

**Comment by hatton** [comment]
Good point, John. Given a single common name (e.g. "customBookStyles.css"), I can see no inexpensive way of having the system correctly choose which of these to use  (the expensive way would mean utilizing the book ancestry to first know when an update might be desired, then merging with an changes made to the local book's customBookStyles.css). So that "feature" of updating a stylesheet in existing books by updating something in your "sources for new books" will have to be done by using a distinct css name. I checked, and the Primer template already uses a unique css name (Story Primer.css). 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2332#-:-LADyluj2QecLcF-I1LA:bany1u6)*

**Comment by JohnThomson** [comment]
That's fine, but then I think the code and comments should simply say that we don't ever update or override this stylesheet from anywhere outside the book folder because of the danger of overwriting user changes.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2332#-:-LAMTfGd5_HTAX7uqfVs:b-cln14l)*

**Comment by hatton** [comment]
>  should simply say that we don't ever update or override this stylesheet from a

The comment says why we have this general behavior, and why we need this exception, then the code clearly makes the exception. I'd be happy to paste in a comment that would be clearer, if you can provide one? I think this system of asking other people to figure out what would be clear to oneself, back and forth, in a PR, is really technological breakdown. The reviewer should be able to just edit the code... especially comments.... Will come someday.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2332#-:-LAOPVhqEdepVApbPFpm:b-vv0ipp)*

**Comment by JohnThomson** [comment]
:lgtm: Hopefully my pickiness did some good. Sorry to hold things up.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2332#-:-LAnA1KYCfoPR4PQHnWM:b-psxpvn)*

**Pull request merged**
