### PR TITLE
Update XLIFF files to uniform formatting to generate a unified output…

### PR DESCRIPTION
**Pull request by PaulNel**
… for localized files (.jade, .md, .tmx, .txt)

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1402)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Though it didn't get put in place until 3.8, our new standard (based on the .editorconfig file) is that files, by default, should have a final newline (unless there is a reason not to). So I don't really like seeing those removed at this point.

I haven't had a chance to review all the files yet.

---

Reviewed 8 of 15 files at r1.
Review status: 8 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[DistFiles/leveledRTInfo/leveledReaderInfo-en.jade, line 15 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1402#-KaEJac3ZTQskoPHQZ9x:-KaEJac3ZTQskoPHQZ9y:b-7br51l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a67abff4753b651c2b62951aadd2cbf3d97e1647/DistFiles/leveledRTInfo/leveledReaderInfo-en.jade#L15)):*
> ```Pug
> 			em Predictability
> 			|  in a text means that the reader can guess what would come next. You can increase predictability by using repeated patterns. Here are some patterns you can use:
> 		ul 
> ```

Extra trailing space

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1402#-:-KaEKuoz1Xc3Eww4Ubwt:b-m9u1cl)*

**Comment by PaulNel** [comment]
Removed training space after "ul" in XLIFF. Regenerated leveled ReaderInfo-en.jade

**Comment by andrew-polk** [comment]
Reviewed 7 of 15 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[DistFiles/localization/Bloom.en.tmx, line 1 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1402#-KaOm1dRvjvfWkaCJc_R:-KaOm1dRvjvfWkaCJc_S:b47yd31) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2c6197ac0ee09556f8838ed9e235cc256994728d/DistFiles/localization/Bloom.en.tmx#L1)):*
> ```
> <?xml version="1.0" encoding="utf-8"?>
> ```

There are too many lines changed for me to look at this in detail.

The whitespace comment I made for the Palaso file applies here.

What changes were made?
It looks like you added some missing strings? Maybe did some re-sorting?
I think at least one item was deleted?

---

*[DistFiles/localization/Palaso.en.tmx, line 1 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1402#-KaOlSL8kyoWDvl2nTQL:-KaOlSL8kyoWDvl2nTQM:bsoyerl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2c6197ac0ee09556f8838ed9e235cc256994728d/DistFiles/localization/Palaso.en.tmx#L1)):*
> ```
> <?xml version="1.0" encoding="utf-8"?>
> ```

I'm a little dubious about these whitespace changes.
I would want to check: if we copy lines out of a user's local version of the file into here, will we then have mismatched whitespace? I.e. Does L10NSharp generate .tmx files specifically with this whitespace?

---

*[src/BloomBrowserUI/ePUB/bloomEpubPreview-en.jade, line 14 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1402#-KaOewE_7clHhKm51h-q:-KaOewEaF_TOX4bOcMAa:bxitkwp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2c6197ac0ee09556f8838ed9e235cc256994728d/src/BloomBrowserUI/ePUB/bloomEpubPreview-en.jade#L14)):*
> &nbsp;

Replacing the &nbsp; with a space at the end of the line is a bad idea because we are trying to maintain no trailing spaces in our repo, so that will get stripped off at some point.

You could, instead, make the next line
```
| = ' '
```

---

*[src/BloomBrowserUI/ePUB/bloomEpubPreview-en.jade, line 30 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1402#-KaOjHDPuehaCu0L2oWm:-KaOjHDPuehaCu0L2oWn:b-tdbfwr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2c6197ac0ee09556f8838ed9e235cc256994728d/src/BloomBrowserUI/ePUB/bloomEpubPreview-en.jade#L30)):*
> .htm)
> 				to

I know this isn't really your change, but rather than a line break, I think this should simply be a space.

---

*[src/BloomBrowserUI/ePUB/MissingLameModule-en.jade, line 9 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1402#-KaOjj-3muuCxk4H7Su_:-KaOjj-3muuCxk4H7Sua:b7yl55y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2c6197ac0ee09556f8838ed9e235cc256994728d/src/BloomBrowserUI/ePUB/MissingLameModule-en.jade#L9)):*
> ·

There are several spurious spaces at end of lines added in this file.

---

*[src/BloomBrowserUI/xMatter/Factory-XMatter/description-en.txt, line 1 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1402#-KaOkzC-9xUJ9Ls8WUcx:-KaOkzC1VMLTfT88DpXo:bylpt24) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2c6197ac0ee09556f8838ed9e235cc256994728d/src/BloomBrowserUI/xMatter/Factory-XMatter/description-en.txt#L1)):*
> [V1] Designed 

Adding a space here shows up in the UI, so this is not viable.

---

*[src/BloomBrowserUI/xMatter/SIL-Cameroon-XMatter/description-en.txt, line 2 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1402#-KaOl7Xxrj001thV5q3b:-KaOl7Xxrj001thV5q3c:b-5tw3ih) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2c6197ac0ee09556f8838ed9e235cc256994728d/src/BloomBrowserUI/xMatter/SIL-Cameroon-XMatter/description-en.txt#L2)):*
> * Includes ISO 639 code on the credits page.

This is an example of an instance of the final new line being removed which I mentioned in an earlier comment for the whole PR.

---

*[src/BloomBrowserUI/xMatter/SuperPaperSaver-XMatter/description-en.txt, line 1 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1402#-KaOl3aCfylACn7PCecL:-KaOl3aCfylACn7PCecM:bc60whm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2c6197ac0ee09556f8838ed9e235cc256994728d/src/BloomBrowserUI/xMatter/SuperPaperSaver-XMatter/description-en.txt#L1)):*
> [V1] Designed

Adding a space here shows up in the UI, so this is not viable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1402)*

**Comment by andrew-polk** [comment]
@PaulNel can we get this resolved or closed?

**Comment by PaulNel** [comment]
I am closing this pull request.

**Pull request closed without merging**
