### PR TITLE
Handle failure to load image from clipboard (BL-9009)

### PR DESCRIPTION
**Pull request by JohnThomson**
Make sure https://github.com/sillsdev/libpalaso/pull/980 is merged first!

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4023)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4023)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[DistFiles/localization/en/Bloom.xlf, line 1667 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4023#-MJcyL911rZeyAU3V1zf:-MJcyL911rZeyAU3V1zg:bptbvd3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/62886f28338303a9ea353d7e8a80778992711cf7/DistFiles/localization/en/Bloom.xlf#L1667)):*
> ```XML
>         <source xml:lang="en">Before you can paste an image, copy one onto your 'clipboard', from another program.</source>
>         <note>ID: EditTab.NoValidImageFoundOnClipboard</note>
>       </trans-unit>
> ```

Something's amiss with the changes to this file. You've changed the existing ID and the new ID doesn't match the new ID in EditingView.cs.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4023)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[DistFiles/localization/en/Bloom.xlf, line 1667 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4023#-MJcyL911rZeyAU3V1zf:-MJd3peJ-IjvzSbCkUPV:beukcwn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/62886f28338303a9ea353d7e8a80778992711cf7/DistFiles/localization/en/Bloom.xlf#L1667)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Something's amiss with the changes to this file. You've changed the existing ID and the new ID doesn't match the new ID in EditingView.cs.
</blockquote></details>

Sigh. Copied the old one and then changed the IDs of one copy and the text of the other! Fixed.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4023)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[DistFiles/localization/en/Bloom.xlf, line 1667 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4023#-MJcyL911rZeyAU3V1zf:-MJd67WP19Fl1j_UbB6v:bp3b88p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/62886f28338303a9ea353d7e8a80778992711cf7/DistFiles/localization/en/Bloom.xlf#L1667)):*
> ```
> EditTab.NoValidImageFoundOnClipboard
> ```
Sorry, this still doesn't match EditingView which has EditTab.CouldNotLoadClipboardImage

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4023)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[DistFiles/localization/en/Bloom.xlf, line 1667 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4023#-MJcyL911rZeyAU3V1zf:-MJd7Dyq05OOga90OS1A:b-wfhcg9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/62886f28338303a9ea353d7e8a80778992711cf7/DistFiles/localization/en/Bloom.xlf#L1667)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> EditTab.NoValidImageFoundOnClipboard
> ```
Sorry, this still doesn't match EditingView which has EditTab.CouldNotLoadClipboardImage
</blockquote></details>

Sigh. Changes unsaved in editor. Fixed.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4023)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
