### PR TITLE
Improve the user interaction for adding/removing book sources (BL-12011)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5730)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5730)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx` line 754 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5730#-NRcyWYp1E_3tQ-9G7lG:-NRcyWYp1E_3tQ-9G7lH:bq6ey4u) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2d48ae832480c5f32338cd3bf5bfab3903f40b19/src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx#L754)):*
> ```XML
>                 </div>
>             ) : props.isRemovableFolder ? (
>                 <div
> ```

In my opinion, it is worth pulling this whole div out as a local shared component since so much display logic shared with the one just above.
You'd have to pass collectionName, click handler, tooltip text, tooltip l10nId, icon (don't think BloomTooltip is needed?), but IMO that's worth it.
It also simplifies this part of the code significantly.
Thoughts?
___
*[`src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx` line 790 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5730#-NRcyTzl1UDmAKbcqvw7:-NRcyTzm0jBt0FkAoaBg:biz4n0p) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2d48ae832480c5f32338cd3bf5bfab3903f40b19/src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx#L790)):*
> ```XML
>                                 >
>                                     delete the folder. Click here to view the
>                                     folder on your drive.
> ```

The first part of this string got lost.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5730)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 192 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5730#-NRd0yB-66UmNm4i2vXx:-NRd0yB-66UmNm4i2vXy:b-d5gp82) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3a430b18e290f9a163b2b12480bb8c5177da0248/src/BloomExe/web/controllers/CollectionApi.cs#L192)):*
> ```Smalltalk
> 			{
> 				request.PostSucceeded();
> 				var title = LocalizationManager.GetString("CollectionTab.CancelOrDelete", "Cancel if you do not want to delete this folder.",
> ```

See comment in card about implementing this feature differently.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5730)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx` line 754 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5730#-NRcyWYp1E_3tQ-9G7lG:-NRdIYq85rZgf6Uds2hv:blxwce1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2d48ae832480c5f32338cd3bf5bfab3903f40b19/src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx#L754)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

In my opinion, it is worth pulling this whole div out as a local shared component since so much display logic shared with the one just above.
You'd have to pass collectionName, click handler, tooltip text, tooltip l10nId, icon (don't think BloomTooltip is needed?), but IMO that's worth it.
It also simplifies this part of the code significantly.
Thoughts?
</blockquote></details>

Done.  BloomTooltip might not be strictly needed, but that's the only way I could get the tooltip to look like John's mockup in the issue.
___
*[`src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx` line 790 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5730#-NRcyTzl1UDmAKbcqvw7:-NRd2A9fE-Fz10ML-rsG:bt2vr1b) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2d48ae832480c5f32338cd3bf5bfab3903f40b19/src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx#L790)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The first part of this string got lost.
</blockquote></details>

Fixed.
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 192 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5730#-NRd0yB-66UmNm4i2vXx:-NRd2DHEE87a3DVW3rre:b-3vfcn0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3a430b18e290f9a163b2b12480bb8c5177da0248/src/BloomExe/web/controllers/CollectionApi.cs#L192)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

See comment in card about implementing this feature differently.
</blockquote></details>

I changed to not passing in a title, and then checking whether the folder still exists instead of whether the user cancelled the dialog.
And not deleting the folder in code.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5730)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`DistFiles/localization/en/Bloom.xlf` line 722 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5730#-NRdJfKh8d7abV9pzF4Q:-NRdJfKh8d7abV9pzF4R:b-oosqsh) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4eeee52effef63ff6e90d657e7c1483ebcee3421/DistFiles/localization/en/Bloom.xlf#L722)):*
> ```XML
>         <note>This is the title of the folder-open dialog that is used to examine a collection folder to possibly delete..</note>
>         <note>ID: CollectionTab.CancelOrDelete</note>
>       </trans-unit>
> ```

Don't need this one now.
___
*[`src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx` line 754 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5730#-NRcyWYp1E_3tQ-9G7lG:-NRdKVkw9iUSjfvPu19V:b8ax0pq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2d48ae832480c5f32338cd3bf5bfab3903f40b19/src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx#L754)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Done.  BloomTooltip might not be strictly needed, but that's the only way I could get the tooltip to look like John's mockup in the issue.
</blockquote></details>

Sorry; I meant to say, "don't think BloomTooltip's id is needed?".
Anyway, done now.

Thanks.
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 192 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5730#-NRd0yB-66UmNm4i2vXx:-NRdJip76JrHX4Nk-Jsp:bciqbvf) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3a430b18e290f9a163b2b12480bb8c5177da0248/src/BloomExe/web/controllers/CollectionApi.cs#L192)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I changed to not passing in a title, and then checking whether the folder still exists instead of whether the user cancelled the dialog.
And not deleting the folder in code.
</blockquote></details>

Hm. I was assuming you were just going to open Windows Explorer and let the user do their thing. But I realize now that then we don't have a way to update the UI (unless we implement a file watcher).
Might still need to get JH's input here.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5730)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/Bloom.xlf` line 722 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5730#-NRdJfKh8d7abV9pzF4Q:-NRdOSLwEl42EeP6aMmg:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4eeee52effef63ff6e90d657e7c1483ebcee3421/DistFiles/localization/en/Bloom.xlf#L722)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Don't need this one now.
</blockquote></details>

Done.
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 192 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5730#-NRd0yB-66UmNm4i2vXx:-NRdOdzA-LQAf02rskq4:bgxtvup) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3a430b18e290f9a163b2b12480bb8c5177da0248/src/BloomExe/web/controllers/CollectionApi.cs#L192)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Hm. I was assuming you were just going to open Windows Explorer and let the user do their thing. But I realize now that then we don't have a way to update the UI (unless we implement a file watcher).
Might still need to get JH's input here.
</blockquote></details>

Agreed.  I added a comment to the issue.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5730)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 192 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5730#-NRd0yB-66UmNm4i2vXx:-NRdVqjB0j09dTtC0Z9B:b-zcjvte) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3a430b18e290f9a163b2b12480bb8c5177da0248/src/BloomExe/web/controllers/CollectionApi.cs#L192)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Agreed.  I added a comment to the issue.
</blockquote></details>

Thanks

**Review by andrew-polk — APPROVED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5730)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
