### PR TITLE
BL-4754 Connect to Android using WiFi broadcast

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1765)

### CODE REVIEW

**Comment by hatton** [comment]
Exciting! A few minor things and one question about disposability. Where I thought a //todo or //enhance comment warranted, I wrote my comment that way.  

I was on the lookout for reentry issues, because we could have 30 clients at the same time. Didn't notice any, but it might still be helpful to address the issue in comments, if only to make clear that requirement?

---

Reviewed 2 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 13 unresolved discussions.

---

*[src/BloomExe/Publish/BloomReaderPublisher.cs, line 150 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpuohgcYdawnbZuOMt-:-KpuohgdXHSC_skcBurI:b-z5imdi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/Publish/BloomReaderPublisher.cs#L150)):*
> ```Smalltalk
> 		}
> 
> 		public void SendBookToWiFi(Book.Book book, string androidIpAddress)
> ```

Maybe SendBookViaWifi?  or  SendBookToClientOnLocalSubNet?

---

*[src/BloomExe/Publish/BloomReaderPublisher.cs, line 155 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpumRvhiwPb57MfHGXk:-KpumRvhiwPb57MfHGXl:b-r56r5f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/Publish/BloomReaderPublisher.cs#L155)):*
> ```Smalltalk
> 			_progress.WriteMessage($"Sending {book.Title} to android {androidIpAddress}");
> 			var bloomdPath = BookCompressor.CompressBookForDevice(book);
> 			WebClient myClient = new WebClient();
> ```

Is WebClient disposable?

---

*[src/BloomExe/Publish/WiFiAdvertiser.cs, line 16 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpumozAW2BP8ZMuDSwd:-KpumozAW2BP8ZMuDSwe:bxnskbt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/Publish/WiFiAdvertiser.cs#L16)):*
> ```Smalltalk
> {
> 	/// <summary>
> 	/// This class broadcasts a message over the network offering to download a book to any Android that wants it.
> ```

I don't think of servers as downloading to clients. How about "offering to supply a book"

---

*[src/BloomExe/Publish/WiFiAdvertiser.cs, line 46 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpunGYdQtgm6sYWBwqt:-KpunGYdQtgm6sYWBwqu:b-rn56rr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/Publish/WiFiAdvertiser.cs#L46)):*
> ```Smalltalk
> 		}
> 
> 		public string BookTitle;
> ```

Nice to put public things at the top.

---

*[src/BloomExe/Publish/WiFiAdvertiser.cs, line 67 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpunWCrbrf-VQ4ey0Gg:-KpunWCrbrf-VQ4ey0Gh:be0e4b4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/Publish/WiFiAdvertiser.cs#L67)):*
> ```Smalltalk
> 			catch (Exception error)
> 			{
> 				//EventLog.WriteEntry("Application", string.Format("Error in Advertiser: {0}", error.Message), EventLogEntryType.Error);
> ```

For testing it would sure be great to push all errors out to the progress box.

---

*[src/BloomExe/Publish/WiFiAdvertiser.cs, line 83 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-Kpuq9W6oWA4CCUw-yGX:-Kpuq9W6oWA4CCUw-yGY:b-z4km18) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/Publish/WiFiAdvertiser.cs#L83)):*
> ```Smalltalk
> 			{
> 				_currentIpAddress = GetLocalIpAddress();
> 				dynamic dataObj = new DynamicJson();
> ```

dataObj --> advertisement?

---

*[src/BloomExe/Publish/WiFiAdvertiser.cs, line 84 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpuqTM55XKGMNLKLwXE:-KpuqTM55XKGMNLKLwXF:b-ob1laz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/Publish/WiFiAdvertiser.cs#L84)):*
> ```Smalltalk
> 				_currentIpAddress = GetLocalIpAddress();
> 				dynamic dataObj = new DynamicJson();
> 				dataObj.Title = BookTitle;
> ```

I am reminded of "Uncle Ken's Law": "Eventually, all strings are multistrings". Thus
// Enhance: add language of title

---

*[src/BloomExe/Publish/WiFiAdvertiser.cs, line 85 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpuqD9ZnaMYL04P4Qcd:-KpuqD9ZnaMYL04P4Qce:b-v24ncv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/Publish/WiFiAdvertiser.cs#L85)):*
> ```Smalltalk
> 				dynamic dataObj = new DynamicJson();
> 				dataObj.Title = BookTitle;
> 				dataObj.Version = BookVersion;
> ```

// Enhance: perhaps both sides should give their own version, as in .BloomVersion or .BloomProtocolVersion or something?

---

*[src/BloomExe/Publish/WiFiAdvertiser.cs, line 92 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpunpMcMQxA5agpodjv:-KpunpMcMQxA5agpodjw:b-6wakml) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/Publish/WiFiAdvertiser.cs#L92)):*
> ```Smalltalk
> 		}
> 
> 		private string GetLocalIpAddress()
> ```

Worth a comment pointing out that the "local" here means "on this subnet", as opposed to "of this machine".

---

*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 121 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpupeMB7LW5RCWHAITN:-KpupeMB7LW5RCWHAITO:b-ifjzpy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L121)):*
> ```Smalltalk
> 	/// listening (on another thread); hook NewMessageReceived to receive a packet each time a client sends it.
> 	/// </summary>
> 	class UDPListener
> ```

Wants to be its own file. Maybe named "BloomReaderUDPListener"

---

*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 125 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpupYK9eruqfCC3fd7Z:-KpupYK9eruqfCC3fd7_:bm0ooiu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L125)):*
> ```Smalltalk
> 		// must match BloomReader.NewBookListenerService.desktopPort
> 		// and be different from WiFiAdvertiser.Port and port in BloomReaderPublisher.SendBookToWiFi
> 		private int m_portToListen = 5915;
> ```

m_  --> _

---

*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 188 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpupjzISt1GBjSfiKrp:-KpupjzISt1GBjSfiKrq:baxphnn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L188)):*
> ```Smalltalk
> 	/// Helper class to hold the data we got from the Android, for the NewMessageReceived event of UDPListener
> 	/// </summary>
> 	class MyMessageArgs : EventArgs
> ```

Maybe name "AndroidMessageArgs"

---

*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 192 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpuqoYIQUqR7DymGI72:-KpuqoYIQUqR7DymGI73:b-7e6cqs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L192)):*
> ```Smalltalk
> 		public byte[] data { get; set; }
> 
> 		public MyMessageArgs(byte[] newData)
> ```

//TODO Make this into json, so that we can put in things like the version of BR that we're talking to.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-:-Kpursg96zpYWS0nBlMz:b-bfdowh)*

**Comment by andrew-polk** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[src/BloomExe/Publish/BloomReaderPublisher.cs, line 150 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpurGR6v1RWG75zqkgA:-KpurGR6v1RWG75zqkgB:bkqasir) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/Publish/BloomReaderPublisher.cs#L150)):*
> ```Smalltalk
> 		}
> 
> 		public void SendBookToWiFi(Book.Book book, string androidIpAddress)
> ```

What is the longest we anticipate this taking? We should consider putting it on a background thread or at least changing the cursor. (I should have done the same for USB, btw; I created a card for it.)

---

*[src/BloomExe/Publish/WiFiAdvertiser.cs, line 27 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpushjaYSHjOjA7Fq04:-KpushjaYSHjOjA7Fq05:b-8lh8am) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/Publish/WiFiAdvertiser.cs#L27)):*
> BloomPlayer

Bloom Reader?

---

*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 37 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpuppQKb1ex-Y1T3yUx:-KpuppQKb1ex-Y1T3yUy:bb0my2v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L37)):*
> ```Smalltalk
> 			server.RegisterEndpointHandler(kApiUrlPart + "connectWiFi/start", request => ConnectWiFiStartHandler(server, request), true);
> 			server.RegisterEndpointHandler(kApiUrlPart + "connect/cancel", ConnectCancelHandler, true);
> 			// Not yet
> ```

If you need to make another change, let's remove this commented code.

---

*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 121 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpurnG50gCdkp4L_z8b:-KpurnG50gCdkp4L_z8c:bvrc4o5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L121)):*
> ```Smalltalk
> 	/// listening (on another thread); hook NewMessageReceived to receive a packet each time a client sends it.
> 	/// </summary>
> 	class UDPListener
> ```

When is it worth moving this to libpalaso? There are definitely some advantages to having version 1 of the code start there (as opposed to having to port it). But there are also advantages to vetting it in Bloom first.

---

*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 126 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-Kpus23DAq3bpmA8m3aj:-Kpus23DAq3bpmA8m3ak:bphtcyv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L126)):*
> m_ListeningThread

m_listeningThread

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765)*

**Comment by andrew-polk** [comment]
Perhaps it belongs in another PR, but we should now enable the Android view in the Publish tab for Linux and hide the Connect via USB option.

**Comment by andrew-polk** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[src/BloomExe/Publish/BloomReaderPublisher.cs, line 150 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpurGR6v1RWG75zqkgA:-KpvFCugetnZdQMRq2do:b8qmjkh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/Publish/BloomReaderPublisher.cs#L150)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What is the longest we anticipate this taking? We should consider putting it on a background thread or at least changing the cursor. (I should have done the same for USB, btw; I created a card for it.)
</blockquote></details>

This is called from the listener thread in the UDPClient. It may eventually be worth spinning up more threads so we can serve multiple Androids at the same time, but we're at least not holding up the UI thread.

---

*[src/BloomExe/Publish/BloomReaderPublisher.cs, line 155 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpumRvhiwPb57MfHGXk:-KpvHAYJjcL9jO2yhDyU:bgwt35a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/Publish/BloomReaderPublisher.cs#L155)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is WebClient disposable?
</blockquote></details>

Yes. Fixed.

---

*[src/BloomExe/Publish/WiFiAdvertiser.cs, line 46 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpunGYdQtgm6sYWBwqt:-KpvHWkIzg6xvElS6xMl:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/Publish/WiFiAdvertiser.cs#L46)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Nice to put public things at the top.
</blockquote></details>

Done.

---

*[src/BloomExe/Publish/WiFiAdvertiser.cs, line 84 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpuqTM55XKGMNLKLwXE:-KpvK1kll2xyd8vZgzsP:b-jeidk3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/Publish/WiFiAdvertiser.cs#L84)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I am reminded of "Uncle Ken's Law": "Eventually, all strings are multistrings". Thus
// Enhance: add language of title
</blockquote></details>

I just put it in.

---

*[src/BloomExe/Publish/WiFiAdvertiser.cs, line 85 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpuqD9ZnaMYL04P4Qcd:-KpvKbP6f0X9ybikoH3P:bh5ilm2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/Publish/WiFiAdvertiser.cs#L85)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

// Enhance: perhaps both sides should give their own version, as in .BloomVersion or .BloomProtocolVersion or something?
</blockquote></details>

I just put it in (not checked on the other side yet, though.)

---

*[src/BloomExe/Publish/WiFiAdvertiser.cs, line 92 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpunpMcMQxA5agpodjv:-KpvLSPJdwqiYEAJNFo6:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/Publish/WiFiAdvertiser.cs#L92)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Worth a comment pointing out that the "local" here means "on this subnet", as opposed to "of this machine".
</blockquote></details>

Done.

---

*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 37 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpuppQKb1ex-Y1T3yUx:-KpvLZuJ82A2w7gJUgEO:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L37)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If you need to make another change, let's remove this commented code.
</blockquote></details>

Done.

---

*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 121 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpurnG50gCdkp4L_z8b:-KpvLoNFVCTyViVjOcof:b-1j4b6t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L121)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

When is it worth moving this to libpalaso? There are definitely some advantages to having version 1 of the code start there (as opposed to having to port it). But there are also advantages to vetting it in Bloom first.
</blockquote></details>

It's already in two places (since I copied something very similar from HearThis). But there are subtle differences...this one loops waiting for more clients, the HT one is just waiting for one message from the one android that is synchronizing. And it's a pretty small bit of code to be generalizing into something that can behave in different ways. I'm inclined to keep it private for now, but maybe I'm just being lazy.

---

*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 125 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpupYK9eruqfCC3fd7Z:-KpvMK432ELEKJTCSPGo:bb8lcrb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L125)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

m_  --> _
</blockquote></details>

I fixed this even before I saw your comment. (Actually even before I submitted the PR, but unfortunately I forgot to save changes.)

---

*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 126 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-Kpus23DAq3bpmA8m3aj:-KpvM_MxVZq2eQ_fy_oV:b-guz8kz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L126)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> m_ListeningThread

m_listeningThread
</blockquote></details>

Done. (Actually _listeningThread)

---

*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 188 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpupjzISt1GBjSfiKrp:-KpvNSSEXTKfDoQjuBQg:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L188)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Maybe name "AndroidMessageArgs"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[src/BloomExe/Publish/BloomReaderPublisher.cs, line 150 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpuohgcYdawnbZuOMt-:-KpvVzaWMCqYv2DOjI9O:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/Publish/BloomReaderPublisher.cs#L150)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Maybe SendBookViaWifi?  or  SendBookToClientOnLocalSubNet?
</blockquote></details>

Done.

---

*[src/BloomExe/Publish/WiFiAdvertiser.cs, line 16 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpumozAW2BP8ZMuDSwd:-KpvW-lzktcKbNBehq-e:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/Publish/WiFiAdvertiser.cs#L16)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I don't think of servers as downloading to clients. How about "offering to supply a book"
</blockquote></details>

Done.

---

*[src/BloomExe/Publish/WiFiAdvertiser.cs, line 27 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpushjaYSHjOjA7Fq04:-KpvW0q-OfKzt6qnqYPw:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/Publish/WiFiAdvertiser.cs#L27)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> BloomPlayer

Bloom Reader?
</blockquote></details>

Done.

---

*[src/BloomExe/Publish/WiFiAdvertiser.cs, line 67 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpunWCrbrf-VQ4ey0Gg:-KpvW2DzO7uhlhspe6wC:b-ou9uqi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/Publish/WiFiAdvertiser.cs#L67)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

For testing it would sure be great to push all errors out to the progress box.
</blockquote></details>

I've done this one at least.

---

*[src/BloomExe/Publish/WiFiAdvertiser.cs, line 83 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-Kpuq9W6oWA4CCUw-yGX:-KpvW5DbubwGN9WLkVpX:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/Publish/WiFiAdvertiser.cs#L83)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

dataObj --> advertisement?
</blockquote></details>

Done.

---

*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 121 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpupeMB7LW5RCWHAITN:-KpvW6KMdPvREEIpEVJ6:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L121)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Wants to be its own file. Maybe named "BloomReaderUDPListener"
</blockquote></details>

Done.

---

*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 192 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpuqoYIQUqR7DymGI72:-KpvW7qwEoxyPVKhlpno:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L192)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

//TODO Make this into json, so that we can put in things like the version of BR that we're talking to.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765)*

**Comment by andrew-polk** [comment]
*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 121 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpurnG50gCdkp4L_z8b:-KpypPQxnBquBba3ERJH:b-h7jcaq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L121)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's already in two places (since I copied something very similar from HearThis). But there are subtle differences...this one loops waiting for more clients, the HT one is just waiting for one message from the one android that is synchronizing. And it's a pretty small bit of code to be generalizing into something that can behave in different ways. I'm inclined to keep it private for now, but maybe I'm just being lazy.
</blockquote></details>

I guess my point was that we know we eventually want HearThis to be changed to do this, right? Not saying now is necessarily the best timing, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 121 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpurnG50gCdkp4L_z8b:-Kpz3okJlO7JaS1zOOCD:bi04h06) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L121)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I guess my point was that we know we eventually want HearThis to be changed to do this, right? Not saying now is necessarily the best timing, though.
</blockquote></details>

I guess it depends on the scope of your comment. HearThis already has a UDPListener class, which watches for the packet the Android sends when it gets the desktop IP address. The new thing we probably want to extend to HT is the Advertiser class which could replace the whole QR-code trick (but I think it would need some differences, since I doubt we want HTA to sync with any desktop that happens to be advertising).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765)*

**Comment by andrew-polk** [comment]
*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 121 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765#-KpurnG50gCdkp4L_z8b:-Kpz6AR1BuLvGANSiBLM:b-an6b3b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3622319d382bf05a9bde10613cce9a7a07ade78f/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L121)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I guess it depends on the scope of your comment. HearThis already has a UDPListener class, which watches for the packet the Android sends when it gets the desktop IP address. The new thing we probably want to extend to HT is the Advertiser class which could replace the whole QR-code trick (but I think it would need some differences, since I doubt we want HTA to sync with any desktop that happens to be advertising).
</blockquote></details>

Right. My scope was broad, including the replacement of the QR-code with the advertiser.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1765)*

**Pull request merged**
