### PR TITLE
Clarify disabled Bulk BloomPUB button (BL-10505)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4782)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4782)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @hatton and @StephenMcConnel)

___
*[src/BloomBrowserUI/react_components/requiresBloomEnterprise.less, line 67 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4782#-MlRfRVuDu9m-GTNaagL:-MlRfRVuDu9m-GTNaagM:b2axpil) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/713ff1715bc19fd8da3b26fbc07bba21e30bddaf/src/BloomBrowserUI/react_components/requiresBloomEnterprise.less#L67)):*
> ```Less
>         }
>     }
>     .requiresBloomEnterprise {
> ```

A couple years ago we switched to use Emotion where ever possible, so these styles should go on the JSX (TSX) for the component they are styling. Happy to help with that if you like. You can search for the codebase for "css={css" to see lots of examples.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4782)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx, line 258 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4782#-MlRh2ZGCGKSNCtXMJDO:-MlRh2ZGCGKSNCtXMJDP:bbq7jqe) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/713ff1715bc19fd8da3b26fbc07bba21e30bddaf/src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx#L258)):*
> ```XML
>         <ThemeProvider theme={theme}>
>             <BloomDialog {...propsForBloomDialog}>
>                 <div className="requiresBloomEnterpriseDialog">
> ```

Instead of class names + separate less files, we use emotion with inline css props. For examples, see the components in `BloomDialog`

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4782)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx, line 256 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4782#-MlRglzZ14I4hDtFttMS:-MnR8nEbE-cKkccLCNE0:b-i6jrco) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/713ff1715bc19fd8da3b26fbc07bba21e30bddaf/src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx#L256)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Markdown ate part of what I wrote. Fixed:

Not sure I'm understanding your reply. See if this helps: anything in Typescript-land should already be nested inside of a `<ThemeProvider>` we don't have to repeat it.

</blockquote></details>

OK, I understand what you're saying and what is going on in the code.  I've removed the unnecessary ThemeProvider wrapper.

**Review by hatton — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4782)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
