### PR TITLE
BL-5975 Add epub preview to the Epub2 screen

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2409)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Looks pretty good, though It is late in the afternoon...
Pretty complicated stuff with threading, etc. Yuck! React certainly isn't helping us simplify in that regard.

---

Reviewed 10 of 10 files at r1.
Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---

*[src/BloomBrowserUI/publish/epub/bloomEPUBPreview.less, line 1 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2409#-LCjjzpO-HQbjGXva9dV:-LCjjzpPA_P2Aml1Ziaf:b-e671d4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9c01b2cc0e7a415a22f0290f9e53fa11d5258d5e/src/BloomBrowserUI/publish/epub/bloomEPUBPreview.less#L1)):*
> ```Less
> @import "../../bloomUI.less";
> ```

We haven't actually removed the other Epub screen, have we? Should we remove this and that at the same time?

---

*[src/BloomExe/Publish/PublishView.cs, line 44 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2409#-LCjhAsd2lC99DR0Wk0w:-LCjhAsd2lC99DR0Wk0x:b5nvt62) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a87feac75415cb94fc5809a3b90158bddd87979/src/BloomExe/Publish/PublishView.cs#L44)):*
> ```Smalltalk
> 		private BloomWebSocketServer _webSocketServer;
> 		// This constant must match the ID that is used for the listener set up in the React component EpubPreview
> 		private const string kWebsocketPreviewId = "preview";
> ```

Should this be epubPreview? We know we want an Android preview at some point, though it may not end up on the Publish tab.

---

*[src/BloomExe/Publish/PublishView.cs, line 549 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2409#-LCjhdYH09RyRpn7jJYA:-LCjhdYH09RyRpn7jJYB:bdah44w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a87feac75415cb94fc5809a3b90158bddd87979/src/BloomExe/Publish/PublishView.cs#L549)):*
> ```
> initialiced
> ```
typo

---

*[src/BloomExe/Publish/PublishView.cs, line 556 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2409#-LCji1Mh6E95E2so4Xi2:-LCji1Mh6E95E2so4Xi3:bf90gze) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a87feac75415cb94fc5809a3b90158bddd87979/src/BloomExe/Publish/PublishView.cs#L556)):*
> ```
> "PublishTab.Epub.PreparingPreview", "Preparing Preview"
> ```
Is this an existing string? If not, we need it in the .xlf file.

---

*[src/BloomExe/Publish/PublishView.cs, line 582 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2409#-LCjiQWl6m2hzFCkqfXP:-LCjiQWl6m2hzFCkqfXQ:bu75trw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a87feac75415cb94fc5809a3b90158bddd87979/src/BloomExe/Publish/PublishView.cs#L582)):*
> ```
> newimageMode
> ```
newImageMode?

---

*[src/BloomExe/Publish/PublishView.cs, line 673 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2409#-LCjivIYCXxDfGqo05j0:-LCjivIYCXxDfGqo05j1:b-97gauz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a87feac75415cb94fc5809a3b90158bddd87979/src/BloomExe/Publish/PublishView.cs#L673)):*
> ```
> "PublishTab.Epub.PreparingDoc", "Done"
> ```
These don't match

---

*[src/BloomExe/Publish/Epub/PublishEpubApi.cs, line 120 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2409#-LCjgrtP5yvjEgtUzLtC:-LCjgrtP5yvjEgtUzLtD:b-10kub1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a87feac75415cb94fc5809a3b90158bddd87979/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L120)):*
> ```
> PublishTab.Epub.PreparingDoc", "Done"));
> ```
This L10N ID doesn't fit the message.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2409#-:-LCjkHr4BNXZHj2O6JSw:bu7xp1i)*

**Comment by JohnThomson** [comment]
It's not exactly making anything worse, either. The old preview just does all this before anything appears at all. Since the new view has quite a bit of stuff the user can usefully look at while preparing the preview, I thought it was worth pushing it into a background thread. It would be somewhat simpler if not also trying to avoid doing it all again for Save.

---

Review status: 7 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/BloomBrowserUI/publish/epub/bloomEPUBPreview.less, line 1 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2409#-LCjjzpO-HQbjGXva9dV:-LCk4TOE-TrLmxO0yixH:b-u06883) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9c01b2cc0e7a415a22f0290f9e53fa11d5258d5e/src/BloomBrowserUI/publish/epub/bloomEPUBPreview.less#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We haven't actually removed the other Epub screen, have we? Should we remove this and that at the same time?
</blockquote></details>

We still have ePUB/bloomEPUBPreview.less, and the old preview works fine without this file. I think JohnH must have copied it here expecting it to be needed, but most of it wasn't and what was felt more appropriate to me to simply include in publish/epub/epubPublishUI.less.
We're probably close to removing the old one, but I thought I'd let JohnH review this first.

---

*[src/BloomExe/Publish/PublishView.cs, line 44 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2409#-LCjhAsd2lC99DR0Wk0w:-LCk5e0q2CIV5gUfwF9N:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a87feac75415cb94fc5809a3b90158bddd87979/src/BloomExe/Publish/PublishView.cs#L44)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should this be epubPreview? We know we want an Android preview at some point, though it may not end up on the Publish tab.
</blockquote></details>

Done.

---

*[src/BloomExe/Publish/PublishView.cs, line 549 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2409#-LCjhdYH09RyRpn7jJYA:-LCk6zwqAWNcoJntGu0K:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a87feac75415cb94fc5809a3b90158bddd87979/src/BloomExe/Publish/PublishView.cs#L549)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> initialiced
> ```
typo
</blockquote></details>

Done.

---

*[src/BloomExe/Publish/PublishView.cs, line 556 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2409#-LCji1Mh6E95E2so4Xi2:-LCk649q-LWd1v4sk807:b-rwico0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a87feac75415cb94fc5809a3b90158bddd87979/src/BloomExe/Publish/PublishView.cs#L556)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> "PublishTab.Epub.PreparingPreview", "Preparing Preview"
> ```
Is this an existing string? If not, we need it in the .xlf file.
</blockquote></details>

Done. (Though we already have "Preparing Document". I wonder whether that could be reused?

---

*[src/BloomExe/Publish/PublishView.cs, line 582 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2409#-LCjiQWl6m2hzFCkqfXP:-LCk6b5h-fMIM-FkbSVv:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a87feac75415cb94fc5809a3b90158bddd87979/src/BloomExe/Publish/PublishView.cs#L582)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> newimageMode
> ```
newImageMode?
</blockquote></details>

Done.

---

*[src/BloomExe/Publish/PublishView.cs, line 673 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2409#-LCjivIYCXxDfGqo05j0:-LCk6mua9Dah5FKqFvvI:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a87feac75415cb94fc5809a3b90158bddd87979/src/BloomExe/Publish/PublishView.cs#L673)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> "PublishTab.Epub.PreparingDoc", "Done"
> ```
These don't match
</blockquote></details>

Done.

---

*[src/BloomExe/Publish/Epub/PublishEpubApi.cs, line 120 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2409#-LCjgrtP5yvjEgtUzLtC:-LCk6xO59XgKIr2lwflb:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a87feac75415cb94fc5809a3b90158bddd87979/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L120)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> PublishTab.Epub.PreparingDoc", "Done"));
> ```
This L10N ID doesn't fit the message.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2409#-:-LCk7-p_-y3AD57MpzMM:b-pz0c6g)*

**Comment by JohnThomson** [comment]
It's also more complicated in that the old preview had no controls the user could use that would require it to refresh.

---

Review status: 7 of 11 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2409#-:-LCk7y3T3kKC7DFWuhM7:bz22lsf)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2409#-:-LCn9xGn1C4NQ1zJk45h:bnfp4nl)*

**Pull request merged**
