### PR TITLE
(3.5) BL-3222 prevent crash if we can't save prefs

### PR DESCRIPTION
**Pull request by hatton**
In a libpalaso PR, I'll fix the actual problem.
This introduces a way to report non fatal problems like this in different way depending on the channel.

---
This change is [Review on Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/962)

### CODE REVIEW

**Comment by hatton** [comment]
@JohnThomson What do you think about us cherry picking this into 3.5?

**Comment by JohnThomson** [comment]
Reviewed 3 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/NonFatalProblem.cs, line 32 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/962#-KCaRgGPAZ-URSYLwQKt:-KCaRgGPAZ-URSYLwQKu:346949973) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2b9379ea5786879cd59b192f418b39295ea6c5a8/src/BloomExe/NonFatalProblem.cs#L32)):*
Is it intentional that for any OTHER channel (e.g., uganda) even things that should be thrown in release builds will not be thrown?

What if we changed it to channel.startsWith(s), and return an empty string as the sole item for Release, so it always matches? Also, if we made a special channel like betaKentWorkshop, it would be treated as beta.

---

*[src/BloomExe/NonFatalProblem.cs, line 61 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/962#-KCaQYPpiTOJCrAgLcve:-KCaQYPpiTOJCrAgLcvf:650582888) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2b9379ea5786879cd59b192f418b39295ea6c5a8/src/BloomExe/NonFatalProblem.cs#L61)):*
It's a pity to duplicate this logic. With a comment that ThrowIf and InformIf must have the same options in the same order, it might work to just return Matches((ThrowIf)t). Or as long as they DO have the same items, Matches(ThrowIf.Parse(t.ToString()).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/962)*

**Comment by JohnThomson** [comment]
I like this approach, and would love to see it used pretty much EVERYWHERE we catch and discard exceptions. Since most of those are really trying to catch just a few kinds of exceptions (e.g., anything that typically goes wrong with writing a file, or anything that typically  goes wrong with a network operation), we could make at least the developer channel throw after all for common kinds of exception that we don't want to ignore, like Null reference. Potentially we could create an enumeration of common kinds of NonFatalProblems, and work towards a real list of which kinds of exceptions should really be swallowed for each kind. (NonFatalProblemType.WritingNonessentialFile,...)

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/962#-:-KCaTchrxg32kh22G_jz:1750269446)*

**Comment by JohnThomson** [comment]
Feels very safe to cherry-pick to 3.5

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/962#-:-KCaVRFPqqgy7IqxcAEc:1509147844)*

**Comment by hatton** [comment]
Now that I have this new mechanism, I find myself immediately wanting it in the other issues I'm working on, but JT won't be able to get to look at this until next week. Am going to merge this into 3.6 now but will wait for a review before cherrypicking to 3.5.

**Comment by JohnThomson** [comment]
:lgtm:; I think this is fine to merge into 3.5

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/962#-:-KCpMpULCe4srHQox54S:929340976)*

**Pull request merged**
