### PR TITLE
Reduce images for .bloomd books (BL-4645)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1706)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Book/BookCompressor.cs, line 221 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1706#-KmlTvNsdV3XD3x9_Cj3:-KmlTvNsdV3XD3x9_Cj4:b-enekof) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7cf861ce8fda8ba8293f8db14e50469723f3812e/src/BloomExe/Book/BookCompressor.cs#L221)):*
> ```Smalltalk
> 		}
> 
> 		const int kMaxWidth = 300;
> ```

I'm questioning the choice of 300x300. The books could be displayed on a tablet. Even on some phones with higher resolutions, I wonder if this won't cause pixelation. Perhaps 600x600?

However, I did just read @hatton's comment in the issue. So I guess 300 is  an okay starting point.

---

*[src/BloomExe/Book/BookCompressor.cs, line 242 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1706#-KmlUx-8cQlp-2ntGHOf:-KmlUx-8cQlp-2ntGHOg:b-o8g63h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7cf861ce8fda8ba8293f8db14e50469723f3812e/src/BloomExe/Book/BookCompressor.cs#L242)):*
> ratioX, ratioY, ratio

Aren't these scale factors rather than ratios?
Doesn't seem like we are dealing with aspect ratio at all other than the fact you are scaling height and width by the same factor.

If I'm wrong or being too nitpicky, feel free to merge.

---

*[src/BloomTests/Book/BookCompressorTests.cs, line 37 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1706#-KmlVpFmAJ_GZJCbGc8i:-KmlVpFmAJ_GZJCbGc8j:bofup6g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7cf861ce8fda8ba8293f8db14e50469723f3812e/src/BloomTests/Book/BookCompressorTests.cs#L37)):*
> ```Smalltalk
> 
> 		[Test]
> 		public void GetBytesOfReducedImage_ReducesImageIfAppropriate()
> ```

I think it would be better if these were broken out into multiple tests and/or test cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1706)*

**Comment by andrew-polk** [comment]
I know it isn't part of this task, but should we consider running this for epub images? Or do we already do something different there? Maybe we should just create a new card.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1706#-:-KmlWBiXNI2vKtfBNxam:b-28i501)*

**Comment by StephenMcConnel** [comment]
I think this would be a separate task/issue.  But one that would be fairly easy to implement.  :-)

---

Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Book/BookCompressor.cs, line 242 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1706#-KmlUx-8cQlp-2ntGHOf:-Kn-qf1z6Tqm9xk8ALJt:b-ubl8ba) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7cf861ce8fda8ba8293f8db14e50469723f3812e/src/BloomExe/Book/BookCompressor.cs#L242)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ratioX, ratioY, ratio

Aren't these scale factors rather than ratios?
Doesn't seem like we are dealing with aspect ratio at all other than the fact you are scaling height and width by the same factor.

If I'm wrong or being too nitpicky, feel free to merge.
</blockquote></details>

renamed the variables to scale, scaleX, and scaleY

---

*[src/BloomTests/Book/BookCompressorTests.cs, line 37 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1706#-KmlVpFmAJ_GZJCbGc8i:-Kn-sc3eZx8bIE35uD0x:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7cf861ce8fda8ba8293f8db14e50469723f3812e/src/BloomTests/Book/BookCompressorTests.cs#L37)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think it would be better if these were broken out into multiple tests and/or test cases.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1706#-:-Kn-pk3HdC9mYnFtJ6uo:b-sik65a)*

**Comment by andrew-polk** [comment]
Ok, I'll create a card. Thanks.
:lgtm: 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1706#-:-Kn-ukE48lCD5O4QVqAk:bs0n93r)*

**Pull request merged**
