### PR TITLE
BL-6095 Check All text has recorded audio

### PR DESCRIPTION
**Pull request by hatton**
Currently does not distinguish body text from image descriptions. That will come with BL-6098

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2477)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed, 4 unresolved discussions (waiting on @hatton)

---

*[src/BloomExe/packages.config, line 25 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2477#-LEjyOAH31Vf6rPUCkZ6:-LEjyOAH31Vf6rPUCkZ7:b93v4hr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ee54723c71dc486510aaa75637f938657d652d3b/src/BloomExe/packages.config#L25)):*
> ```
> Changes above this line must be copied to ./Linux/packages.config
> ```
Looks like this got missed.

---

*[src/BloomExe/Book/AccessibilityCheckers.cs, line 78 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2477#-LEjytlO24CzOnv26H0q:-LEjytlO24CzOnv26H0r:bbyj4my) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ee54723c71dc486510aaa75637f938657d652d3b/src/BloomExe/Book/AccessibilityCheckers.cs#L78)):*
> ```Smalltalk
> 			if (!Directory.Exists(audioFolderPath))
> 			{
> 				yield return String.Format(messageTemplate, "All");
> ```

This won't make a coherent sentence in English.
Won't work for localization, either.

---

*[src/BloomExe/Book/AccessibilityCheckers.cs, line 88 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2477#-LEjzLli7gO3gdo64jkZ:-LEjzLli7gO3gdo64jk_:b-ebjb0t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ee54723c71dc486510aaa75637f938657d652d3b/src/BloomExe/Book/AccessibilityCheckers.cs#L88)):*
> ```Smalltalk
> 				{
> 					var pageLabel = HtmlDom.GetNumberOrLabelOfPageWhereElementLives(page);
> 					yield return String.Format(messageTemplate, pageLabel);
> ```

This will be awkward English for xmatter pages.

---

*[src/BloomExe/Book/AccessibilityCheckers.cs, line 103 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2477#-LEjzg-D1QJwsEAzTQqt:-LEjzg-D1QJwsEAzTQqu:bmjgko5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ee54723c71dc486510aaa75637f938657d652d3b/src/BloomExe/Book/AccessibilityCheckers.cs#L103)):*
> ```Smalltalk
> 		}
> 
> 		private static bool ElementContainsMissingAudio(XmlElement element, DirectoryInfo audioFolderInfo)
> ```

Surprised we don't have similar code elsewhere already. You must have looked, though.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2477)*

**Comment by StephenMcConnel** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed, 7 unresolved discussions (waiting on @hatton)

---

*[src/BloomExe/app.config, line 1 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2477#-LEjxsh84ADd73mhkWS_:-LEjxsh84ADd73mhkWSa:bbumq3v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ee54723c71dc486510aaa75637f938657d652d3b/src/BloomExe/app.config#L1)):*
> ```
> <?xml version="1.0" encoding="utf-8"?>
> ```

It looks like that pesky BOM got inserted at the beginning again with no other changes.

---

*[src/BloomExe/packages.config, line 23 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2477#-LEjxLPe7iQRUGaV0KAA:-LEjxLPf603uPrKTTJpg:bgphaho) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ee54723c71dc486510aaa75637f938657d652d3b/src/BloomExe/packages.config#L23)):*
> ```XML
>   <package id="SharpZipLib" version="0.86.0" targetFramework="net461" />
>   <package id="SourceMapDotNet" version="1.0.5478.26629" targetFramework="net461" />
>   <package id="System.ValueTuple" version="4.3.0" targetFramework="net461" />
> ```

These two changes must also be made to src/BloomExe/Linux/packages.config.  It's too bad that packages.config doesn't have either an include or a conditional operator.  At least, I've never heard of either one.

---

*[src/BloomExe/Book/AccessibilityCheckers.cs, line 60 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2477#-LEjymhe0Wn7wvtAB9sW:-LEjymhf6A_fckQeQP78:b-yvteas) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ee54723c71dc486510aaa75637f938657d652d3b/src/BloomExe/Book/AccessibilityCheckers.cs#L60)):*
> ```Smalltalk
> 		public static IEnumerable<string> CheckAudioForAllImageDescriptions(Book.Book book)
> 		{
> 			yield break;
> ```

Is there some code missing here?  or is this a placeholder for future work?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2477)*

**Comment by hatton** [comment]
Review status: all files reviewed, 6 unresolved discussions (waiting on @hatton)

---

*[src/BloomExe/app.config, line 1 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2477#-LEjxsh84ADd73mhkWS_:-LEk_Z8dAOx5MxeiFNGm:b8le8r0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ee54723c71dc486510aaa75637f938657d652d3b/src/BloomExe/app.config#L1)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

It looks like that pesky BOM got inserted at the beginning again with no other changes.
</blockquote></details>

I've gone in an fiddled with it.

---

*[src/BloomExe/packages.config, line 23 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2477#-LEjxLPe7iQRUGaV0KAA:-LEkaELq5fvVnN6TbpwZ:bqyxxr7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ee54723c71dc486510aaa75637f938657d652d3b/src/BloomExe/packages.config#L23)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

These two changes must also be made to src/BloomExe/Linux/packages.config.  It's too bad that packages.config doesn't have either an include or a conditional operator.  At least, I've never heard of either one.
</blockquote></details>

That's awkward, why aren't they shared? Done, though.

---

*[src/BloomExe/packages.config, line 25 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2477#-LEjyOAH31Vf6rPUCkZ6:-LEkaRQiCe2wbr7XTXRE:bb7hquh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ee54723c71dc486510aaa75637f938657d652d3b/src/BloomExe/packages.config#L25)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Changes above this line must be copied to ./Linux/packages.config
> ```
Looks like this got missed.
</blockquote></details>

huh?

---

*[src/BloomExe/Book/AccessibilityCheckers.cs, line 60 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2477#-LEjymhe0Wn7wvtAB9sW:-LEkaYo9DRMVynbobOHL:b2nign6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ee54723c71dc486510aaa75637f938657d652d3b/src/BloomExe/Book/AccessibilityCheckers.cs#L60)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Is there some code missing here?  or is this a placeholder for future work?
</blockquote></details>

yes

---

*[src/BloomExe/Book/AccessibilityCheckers.cs, line 78 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2477#-LEjytlO24CzOnv26H0q:-LEkadmp7IqGHsYiG-1r:b-7yw2dj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ee54723c71dc486510aaa75637f938657d652d3b/src/BloomExe/Book/AccessibilityCheckers.cs#L78)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This won't make a coherent sentence in English.
Won't work for localization, either.
</blockquote></details>

this message goes away in the next pr queued up behind this one.

---

*[src/BloomExe/Book/AccessibilityCheckers.cs, line 88 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2477#-LEjzLli7gO3gdo64jkZ:-LEkajtb9KMN1p3liYiu:bhex01u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ee54723c71dc486510aaa75637f938657d652d3b/src/BloomExe/Book/AccessibilityCheckers.cs#L88)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This will be awkward English for xmatter pages.
</blockquote></details>

ah well

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2477)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

---

*[src/BloomExe/packages.config, line 23 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2477#-LEjxLPe7iQRUGaV0KAA:-LEkdwPA005xYT1zQ6Wz:b-58wjnz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ee54723c71dc486510aaa75637f938657d652d3b/src/BloomExe/packages.config#L23)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

That's awkward, why aren't they shared? Done, though.
</blockquote></details>

Looks like this didn't get pushed.

---

*[src/BloomExe/packages.config, line 25 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2477#-LEjyOAH31Vf6rPUCkZ6:-LEkdWJmCIOQy4aU2Hfe:b-65xt0k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ee54723c71dc486510aaa75637f938657d652d3b/src/BloomExe/packages.config#L25)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

huh?
</blockquote></details>

I was just pointing out the same thing Steve was. We must have been reviewing at the same time.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2477)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2477#-:-LEl1kZI2_tI4uSaXtQI:bnfp4nl)*

**Pull request merged**
