### PR TITLE
Bl 2767 background images

### PR DESCRIPTION
**Pull request by hatton**
Currently, we using img tags for images. These are css-disadvantaged; you can't use css to say "grow this to fit its container, proportionally, and then center it as needed".  So we have javascript that has to run frequently to make inline width,height, margin-left, and margin-top on each image.

If instead we were using css background-image, we could do all that with css.

This PR makes that possible, and turns it on for just one case: the front-cover.

To keep from making a mess, this required a lot of refactoring. While I was in there, I added tests where they were missing, added classes where something looked ripe for encapsulation, and introduced a class to help reduce the number of url-encoding bugs.

To make it easier to review this large submission, I split the work into 6 commits which build on each other. I recommend these be read in order, rather than trying to swallow the whole PR.

[Review on Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/792)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 5 of 5 files at r4.
Review status: 11 of 26 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[src/BloomExe/Book/BookData.cs, line 695 \[r5\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/792#-K-dLJh5lRNHb9RkZB6W)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e23d1f62e9b728f08b75627630d0e507bf57a6c8/src/BloomExe/Book/BookData.cs#L695)):</sup>
Seeing this method used in context makes me wonder whether the name would be better without the "Get"


---

<sup>**[src/BloomExe/Edit/EditingView.cs, line 652 \[r5\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/792#-K-dMpSv4nqLBYp9GE9h)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e23d1f62e9b728f08b75627630d0e507bf57a6c8/src/BloomExe/Edit/EditingView.cs#L652)):</sup>
I suppose you've checked that all callers are ready to receive a div with background image? For unit testing those methods, it seems eventually we might want this to return your new wrapper class...not something that has to be done now, though.


---

<sup>**[src/BloomExe/Edit/PageEditingModel.cs, line 53 \[r5\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/792#-K-dO4DSydv8BG0MzMZt)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e23d1f62e9b728f08b75627630d0e507bf57a6c8/src/BloomExe/Edit/PageEditingModel.cs#L53)):</sup>
I wonder whether it would simplify things for whatever uses this metadata if it was always on the div that represents the image, whether the image itself is a child or just an attribute?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/792)

**Comment by JohnThomson** [comment]
Reviewed 7 of 7 files at r5.
Review status: 18 of 26 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/792)

**Comment by JohnThomson** [comment]
Reviewed 8 of 8 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/792)

**Comment by JohnThomson** [comment]
Should there be data migration to switch existing books to the new approach?


---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/792)

**Comment by hatton** [comment]
All xmatter is already always automatically migrated. 


---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[src/BloomExe/Book/BookData.cs, line 695 \[r5\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/792#-K-dLJh5lRNHb9RkZB6W)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e23d1f62e9b728f08b75627630d0e507bf57a6c8/src/BloomExe/Book/BookData.cs#L695)):</sup>
Done.


---

<sup>**[src/BloomExe/Edit/PageEditingModel.cs, line 53 \[r5\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/792#-K-dO4DSydv8BG0MzMZt)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e23d1f62e9b728f08b75627630d0e507bf57a6c8/src/BloomExe/Edit/PageEditingModel.cs#L53)):</sup>
Maybe. This PR doesn't seem to be the one to make that kind of a change.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/792)

**Pull request merged**
