### PR TITLE
[4.1]BL-5435 Localize formatting style names in Format Dialog

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2124)

### CODE REVIEW

**Comment by StephenMcConnel** [comment]
generally looks good.  a few questions and comments.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 37 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2124#-L48EIR5TqHUKzbRg2e7:-L48EIR5TqHUKzbRg2e8:b-oadv4d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2efa9a4572cee3349d89dfa8f2be9dc4444635ce/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L37)):*
> ```XML
> 
>     public hasStyleId(name: string): boolean {
>         return this.styleId.toLocaleLowerCase() == name.toLocaleLowerCase();
> ```

Is "toLocaleLowerCase" what you want to use?  In C# we usually use "ToLowerInvariant".  Is there an equivalent in TypeScript?  Just asking...

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 241 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2124#-L48Gf3yZwkj8IQcqkLH:-L48Gf3yZwkj8IQcqkLI:bgl95xy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2efa9a4572cee3349d89dfa8f2be9dc4444635ce/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L241)):*
> ```XML
>                         var index3 = label.lastIndexOf(".");
>                         var styleId = label.substring(index3 + 1, index2);
>                         // Check to see if we have an English display name defined for this style
> ```

Maybe the comment should read "Get the English display name if one is defined for this style"

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 262 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2124#-L48EqujgbhM47x7Q6wR:-L48EqujgbhM47x7Q6wS:b-cpmqns) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2efa9a4572cee3349d89dfa8f2be9dc4444635ce/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L262)):*
> ```XML
>     // We were thinking of using a custom css property in the style css definition,
>     // but we would have needed this switch to deal with existing books anyway, so...
>     // we'll just use the switch.
> ```

Maybe should add a comment that any changes made here must be made in the English Bloom.xlf file as well.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 268 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2124#-L48Ha5Agb3be1cM3Xby:-L48Ha5B8RN9JpHTVSlW:bzcd2i7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2efa9a4572cee3349d89dfa8f2be9dc4444635ce/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L268)):*
> ```XML
>             case "BigWords":
>                 displayName = "Big Words";
>                 break;
> ```

If TypeScript syntax allows, I would probably make the code for each case read something like 

case "BigWords":  return "Big Words";

on one line without any "break;" needed.

Then after the switch, "return null;" at the end of the method.

But maybe that's just me...

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 773 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2124#-L48IgkWT6kgJMoo4AIU:-L48IgkX2BLIcAgUyPnj:b9f27ik) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2efa9a4572cee3349d89dfa8f2be9dc4444635ce/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L773)):*
> ```XML
>                 }
>                 editor.styles.sort(function (a: FormattingStyle, b: FormattingStyle) {
>                     return a.englishDisplayName.toLowerCase().localeCompare(b.englishDisplayName.toLowerCase());
> ```

wouldn't we want to sort on the localized name if at all possible?  (Or maybe that happens later, so why sort now?  I'm not sure I understand this code vs. the code later that appears to be sorting on the localized names.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2124#-:-L48KHH2yS7rQx_C6P1h:b-2zfkke)*

**Comment by StephenMcConnel** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 262 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2124#-L48EqujgbhM47x7Q6wR:-L48KWeQZEC4rVt6rSve:b-o0xxzf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2efa9a4572cee3349d89dfa8f2be9dc4444635ce/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L262)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Maybe should add a comment that any changes made here must be made in the English Bloom.xlf file as well.
</blockquote></details>

It might be worth documenting these in the file I created yesterday the google drive Bloom Team folder.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2124)*

**Comment by gmartin7** [comment]
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 37 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2124#-L48EIR5TqHUKzbRg2e7:-L4C2iOtaFvO1qlkx6GR:bc1mhq5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2efa9a4572cee3349d89dfa8f2be9dc4444635ce/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L37)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Is "toLocaleLowerCase" what you want to use?  In C# we usually use "ToLowerInvariant".  Is there an equivalent in TypeScript?  Just asking...
</blockquote></details>

changed to toLowerCase() in both instances

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 241 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2124#-L48Gf3yZwkj8IQcqkLH:-L4C9dRxPQ4JxXfh0sre:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2efa9a4572cee3349d89dfa8f2be9dc4444635ce/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L241)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Maybe the comment should read "Get the English display name if one is defined for this style"
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 262 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2124#-L48EqujgbhM47x7Q6wR:-L4C7zHQuAxkvVht-Kmt:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2efa9a4572cee3349d89dfa8f2be9dc4444635ce/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L262)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

It might be worth documenting these in the file I created yesterday the google drive Bloom Team folder.
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 268 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2124#-L48Ha5Agb3be1cM3Xby:-L4C85t35f6hGykZNFys:b-8es3hn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2efa9a4572cee3349d89dfa8f2be9dc4444635ce/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L268)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

If TypeScript syntax allows, I would probably make the code for each case read something like 

case "BigWords":  return "Big Words";

on one line without any "break;" needed.

Then after the switch, "return null;" at the end of the method.

But maybe that's just me...
</blockquote></details>

But that would mess up the simplicity of "Equation" falling through (I've added a comment to make it clear it's supposed to fall through) to returning the id.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 773 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2124#-L48IgkWT6kgJMoo4AIU:-L4C9Q__vKe5shKhq8dc:b-174nm8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2efa9a4572cee3349d89dfa8f2be9dc4444635ce/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L773)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

wouldn't we want to sort on the localized name if at all possible?  (Or maybe that happens later, so why sort now?  I'm not sure I understand this code vs. the code later that appears to be sorting on the localized names.)
</blockquote></details>

Actually at this point I don't think the localized name has been looked up yet. So, yes, why sort now? Checking to see if we need this sort... You're right. This one is totally unneeded. Removing...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2124)*

**Comment by StephenMcConnel** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 268 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2124#-L48Ha5Agb3be1cM3Xby:-L4CIcIUcsKjAtzJgl3v:b3u4t0n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2efa9a4572cee3349d89dfa8f2be9dc4444635ce/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L268)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

But that would mess up the simplicity of "Equation" falling through (I've added a comment to make it clear it's supposed to fall through) to returning the id.
</blockquote></details>

I suppose.  It's just a stylistic suggestion to consider.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2124#-:-L4CIqpPGOMi4BpWYIuy:bnfp4nl)*

**Pull request merged**
