### PR TITLE
Fix compile warnings

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4894)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
Made this a draft. We can wait till 2022 to merge it.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4894#-:-MrZYgT64chawAsufQ8W:b-x4kgc2)* status: 0 of 8 files reviewed, 1 unresolved discussion

___
*[src/BloomExe/CollectionTab/ReactCollectionTabView.cs, line 68 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4894#-MrZYnV35wOyYT9IqQsG:-MrZYnV35wOyYT9IqQsH:b-9gzvw0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/eee9f89b48bfd0ee2d0cc0e0cef8025b17664257/src/BloomExe/CollectionTab/ReactCollectionTabView.cs#L68)):*
> ```Smalltalk
> 			TeamCollectionManager.TeamCollectionStatusChanged += (sender, args) =>
> 			{
> 				return; 
> ```

I'm not so sure about this, so i made it a commit just by itself so that it can be backed out if something terrible happens.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4894)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/CollectionTab/ReactCollectionTabView.cs, line 68 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4894#-MrZYnV35wOyYT9IqQsG:-Mt9FE5w9BPKA17YTPQf:bfq3jtu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/eee9f89b48bfd0ee2d0cc0e0cef8025b17664257/src/BloomExe/CollectionTab/ReactCollectionTabView.cs#L68)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I'm not so sure about this, so i made it a commit just by itself so that it can be backed out if something terrible happens.
</blockquote></details>

Have you run this by @johnthomson already?

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4894)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

___
*[src/BloomExe/CollectionTab/ReactCollectionTabView.cs, line 68 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4894#-MrZYnV35wOyYT9IqQsG:-Mt9HLz13EFj_9KTDpc2:b-2xjea9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/eee9f89b48bfd0ee2d0cc0e0cef8025b17664257/src/BloomExe/CollectionTab/ReactCollectionTabView.cs#L68)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Have you run this by @johnthomson already?
</blockquote></details>

Yes, I bumped the Flowdock thread so you can read it if you like.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4894)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Pull request merged**
