### PR TITLE
Update .tmx files that are generated from XLIFF 2.0

### PR DESCRIPTION
**Pull request by PaulNel**
Updated source strings to match changes in TMX
Sorted TMX files by @tuid to make it easier to identify differences between versions.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1324)

### CODE REVIEW

**Comment by andrew-polk** [comment]
I'm kind of struggling with what to do regarding your localization update PR. I think we definitely want to get the actual localization changes in to 3.7. I would prefer that be a separate PR.
Ideally, the re-sorting of the tmx file would be another PR. And the changing of English strings in both the code and tmx would be a third one. (I'm not sure if these belong in 3.7 or 3.8; maybe I need to talk to John.)
If that is overwhelming and/or you disagree that would be beneficial, let's talk about it.

---

Review status: 0 of 35 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1324#-:-KX7uH844lvaY95lSo86:bt7ti7o)*

**Comment by PaulNel** [comment]
URC would appreciate these changes for their projects. Bangla, Indonesian and Nepali updates are being worked on.

**Comment by andrew-polk** [comment]
Reviewed 35 of 35 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[DistFiles/localization/Bloom.en.tmx, line 3381 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1324#-KXBS-VSmUkmnw5tNGl1:-KXBS-VSmUkmnw5tNGl2:b-dl3shm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac5460c50eee1800cd799b4ad6ce4707ee2d920f/DistFiles/localization/Bloom.en.tmx#L3381)):*
> ```
>          <prop type="x-dynamic">true</prop>
>          <tuv xml:lang="en">
>             <seg>Level&amp;nbsp;</seg>
> ```

Where did this change come from? It seems wrong to me.

---

*[DistFiles/localization/Bloom.fr.tmx, line 4682 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1324#-KXBRPqyCt05FeAtDoKJ:-KXBRPqyCt05FeAtDoKK:b-bvadaq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac5460c50eee1800cd799b4ad6ce4707ee2d920f/DistFiles/localization/Bloom.fr.tmx#L4682)):*
> ```
>          </tuv>
>          <tuv xml:lang="fr">
>             <seg>Bloom n'a pu se connecter à BloomLibrary.org à partir des identifiants que vous avez enregistrés.Merci de vérifier votre connexion réseau.</seg>
> ```

Seems like there is a missing space here.

---

*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/ReaderSetup.jade, line 115 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1324#-KXBM-LBbOP2s4roGwNl:-KXBM-LBbOP2s4roGwNm:b-63lkvg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac5460c50eee1800cd799b4ad6ce4707ee2d920f/src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/ReaderSetup.jade#L115)):*
> Set

This should not be capitalized as it is not the beginning of a sentence. The sentence starts with First,

---

*[src/BloomBrowserUI/xMatter/SIL-Cameroon-XMatter/description-fr.txt, line 2 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1324#-KXBM_zi7CB4gm-Q5X7x:-KXBM_zi7CB4gm-Q5X7y:b-jo1iw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac5460c50eee1800cd799b4ad6ce4707ee2d920f/src/BloomBrowserUI/xMatter/SIL-Cameroon-XMatter/description-fr.txt#L2)):*
> crÃ©dits

Does this display correctly in the UI? It doesn't display correctly in Reviewable.io (the tool I am using to do the review).

---

*[src/BloomExe/Browser.cs, line 531 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1324#-KXBOm5eVmxtgSaw-1oU:-KXBOm5ftN8d6oCdQA1t:b3yucbm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac5460c50eee1800cd799b4ad6ce4707ee2d920f/src/BloomExe/Browser.cs#L531)):*
> ```Smalltalk
> 		{
> 			return e.ContextMenu.MenuItems.Add(
> 				LocalizationManager.GetString("Browser.OpenPageInFirefox", "Open Page in Firefox (which must be in the PATH environment variable)."),
> ```

Context menus don't typically use sentences, I don't believe (regardless, the other items in this one are not sentences.

---

*[src/BloomExe/Book/XMatterHelper.cs, line 47 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1324#-KXBPF3Io2dFT6RWEHr3:-KXBPF3Io2dFT6RWEHr4:b-8ki23) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac5460c50eee1800cd799b4ad6ce4707ee2d920f/src/BloomExe/Book/XMatterHelper.cs#L47)):*
> ```Smalltalk
> 			{
> 				var errorTemplate = LocalizationManager.GetString("Errors.XMatterNotFound",
>                     "This Book called for Front/Back Matter pack named '{0}', but Bloom couldn't find that on this computer. You can either install a Bloom Pack that will give you '{0}', or go to Settings:Book Making and change to another Front/Back Matter Pack.");
> ```

Not sure how this whitespace change got in, but it is erroneous.

---

*[src/BloomExe/Collection/BloomPack/BloomPackInstallDialog.cs, line 161 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1324#-KXBPNWeMX8UniKQ2V6u:-KXBPNWeMX8UniKQ2V6v:b-7kbl7k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac5460c50eee1800cd799b4ad6ce4707ee2d920f/src/BloomExe/Collection/BloomPack/BloomPackInstallDialog.cs#L161)):*
> ```Smalltalk
> 		{
> 			string msg = L10NSharp.LocalizationManager.GetString("BloomPackInstallDialog.SingleCollectionFolder",
>                 "Bloom Packs should have only a single collection folder at the top level of the .ZIP file.");
> ```

Another indentation erroneously changed from tabs to spaces. (I'm guessing all of them are and I just didn't notice?)

---

*[src/BloomExe/CollectionTab/LibraryBookView.Designer.cs, line 53 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1324#-KXBPtUEP_OYPZtJ8iE7:-KXBPtUEP_OYPZtJ8iE8:bcq0maw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac5460c50eee1800cd799b4ad6ce4707ee2d920f/src/BloomExe/CollectionTab/LibraryBookView.Designer.cs#L53)):*
> ```Smalltalk
> 			this._addToCollectionButton.Image = global::Bloom.Properties.Resources.newBook;
> 			this._addToCollectionButton.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
> 			this._L10NSharpExtender.SetLocalizableToolTip(this._addToCollectionButton, "Create a book in my language using this source book.");
> ```

Tooltips don't usually have periods.

---

*[src/BloomExe/CollectionTab/LibraryBookView.Designer.cs, line 60 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1324#-KXBPv_zkuPa045lb8XW:-KXBPv_zkuPa045lb8XX:bw483w7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac5460c50eee1800cd799b4ad6ce4707ee2d920f/src/BloomExe/CollectionTab/LibraryBookView.Designer.cs#L60)):*
> ```Smalltalk
> 			this._addToCollectionButton.Size = new System.Drawing.Size(255, 48);
> 			this._addToCollectionButton.TabIndex = 0;
> 			this._addToCollectionButton.Text = "Make a book using this source.";
> ```

I don't think we want a period on this.

---

*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1129 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1324#-KXBQ5HBuOQ6o-PL-pB9:-KXBQ5HBuOQ6o-PL-pBA:b-cv4tka) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac5460c50eee1800cd799b4ad6ce4707ee2d920f/src/BloomExe/CollectionTab/LibraryListView.cs#L1129)):*
> ```Smalltalk
> 			{
> 				MessageBox.Show(LocalizationManager.GetString("CollectionTab.BookMenu.ExportDocMessage",
>                     "Bloom will now open this HTML document in your word processing program (normally Word or LibreOffice). You will be able to work with the text and images of this book. These programs normally don't do well with preserving the layout, so don't expect much."));
> ```

This feels unnatural to me. How about starting the last sentence with "However, these"?

---

*[src/BloomExe/CollectionTab/MakeReaderTemplateBloomPackDlg.resx, line 124 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1324#-KXBQIhEAsyFmfAfmFrB:-KXBQIhEAsyFmfAfmFrC:b-hqqc4h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac5460c50eee1800cd799b4ad6ce4707ee2d920f/src/BloomExe/CollectionTab/MakeReaderTemplateBloomPackDlg.resx#L124)):*
> ```XML
>   </metadata>
>   <data name="_willCarrySettingsLabel.Text" xml:space="preserve">
>     <value>In addition, this Bloom Pack will carry your latest decodable and leveled reader settings for the \"{0}\" language. Anyone opening this Bloom Pack, who then opens a \"{0}\" collection, will have their current decodable and leveled reader settings replaced by the settings in this Bloom Pack. They will also get the current set of words for use in decodable readers.</value>
> ```

I'm guessing these quote marks aren't supposed to be escaped.

---

*[src/BloomExe/Workspace/WorkspaceView.Designer.cs, line 145 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1324#-KXBQqswV-e4JSH-R4_k:-KXBQqswV-e4JSH-R4_l:b-ve9rab) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac5460c50eee1800cd799b4ad6ce4707ee2d920f/src/BloomExe/Workspace/WorkspaceView.Designer.cs#L145)):*
> ```Smalltalk
> 			this._openCreateCollectionButton.ImageTransparentColor = System.Drawing.Color.Magenta;
> 			this._L10NSharpExtender.SetLocalizableToolTip(this._openCreateCollectionButton, "Open/Create/Get Collection");
> 			this._L10NSharpExtender.SetLocalizationComment(this._openCreateCollectionButton, "This is is the button you use to create a new collection, open a new one, or get " +
> ```

I know you didn't make this change, but since you are modifying the string anyway, you could correct the double "is".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1324)*

**Comment by PaulNel** [comment]
Splitting up this checkin into multiple pieces/steps

**Pull request closed without merging**
