### PR TITLE
BL-2998 Remove knowledge of DR from main server

### PR DESCRIPTION
**Pull request by JohnThomson**
Adds a mechanism to inject request handlers into the
main server, and uses it for handlers for the
Decodable and Leveled reader requests.

[Review on Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/907)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/web/ReadersHandler.cs, line 40 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/907#-K7HbZduO0sJf9ZLAHiY:-K7HbZdvV9z0ivNT8rAT:-473769136) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/689d0ad9d8df91b05873509ba489f8d7a062ebdf/src/BloomExe/web/ReadersHandler.cs#L40)):*
I could figure this out with more time, but... it seems at first glance like we can inject request handlers via DI, but then this init does some kind of second round of injection, which is weird.

---

*[src/BloomExe/web/ReadersHandler.cs, line 476 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/907#-K7Hb-U1aeri6BIJNk_-:-K7Hb-U1aeri6BIJNk_0:-415350801) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/689d0ad9d8df91b05873509ba489f8d7a062ebdf/src/BloomExe/web/ReadersHandler.cs#L476)):*
Leveled is missing an "e". But can it get a name that is descriptive, like "OpenLeveledReaderInfoInBrowser"?  Is it maybe the case that this can be changed to a generic "open url in browser" call that isn't even specific to readers?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/907)*

**Comment by JohnThomson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/web/ReadersHandler.cs, line 40 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/907#-K7HbZduO0sJf9ZLAHiY:-K7HeCjrrhcEIJ_na66S:870865042) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/689d0ad9d8df91b05873509ba489f8d7a062ebdf/src/BloomExe/web/ReadersHandler.cs#L40)):*
DI to connect these classes would mean that the EnhancedImageServer constructor knows about ReadersHandler (and any other special handlers like CurrentBookHandler), and I thought we were trying to avoid having it know anything about the readers.
Or I suppose we could avoid the special Init call by having something construct an instance of ReadersHandler and letting its contructor take an EIS, but currently nothing else in the system requires RH to be a non-static class.

---

*[src/BloomExe/web/ReadersHandler.cs, line 476 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/907#-K7Hb-U1aeri6BIJNk_-:-K7Hfrb7ybot_PVIAMJs:612756237) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/689d0ad9d8df91b05873509ba489f8d7a062ebdf/src/BloomExe/web/ReadersHandler.cs#L476)):*
I don't see anything specific to Readers here, so I will move it back to EIS and come up with some generic marker

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/907)*

**Comment by JohnThomson** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 449 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/907#-K7HmbKoupGEV5BzI63R:-K7HmbKoupGEV5BzI63S:-707624510) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2f6ce7aa757da567978d9d53446cee9123113fa1/src/BloomExe/web/EnhancedImageServer.cs#L449)):*
This more generic version needs to strip off the identifying prefix, because previously the leading "leveledRtInfo" was being used as part of the path to the file as well as to mark the URL as needing this behavior.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/907)*

**Comment by hatton** [comment]
Reviewed 1 of 4 files at r1, 2 of 4 files at r2.
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/web/ReadersHandler.cs, line 40 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/907#-K7HbZduO0sJf9ZLAHiY:-K7Hs8dK-ByDEelgArwk:1727703222) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/689d0ad9d8df91b05873509ba489f8d7a062ebdf/src/BloomExe/web/ReadersHandler.cs#L40)):*
Ah, ok. So what we're doing here is more like subscribing to events. In my mind, DI would mean that there is an IRequestHandler of some sort, and we inject a list objects implementing that interface into the server. No problem not doing that now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/907)*

**Pull request merged**
