### PR TITLE
Introduce Super Paper Saver

### PR DESCRIPTION
**Pull request by hatton**
Along the way, I corrected some typos, did a little refactoring, and introduced converting CamelCase xmatter names to words with spaces.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1220)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/xMatter/bloom-xmatter-mixins.jade, line 158 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1220#-KT7181avXELyW5zr9YT:-KT7181avXELyW5zr9YU:b-moupp8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9394ac4d52edf174205d0e257de3480323bb86b4/src/BloomBrowserUI/xMatter/bloom-xmatter-mixins.jade#L158)):*
> ```Jade
> 
> mixin standard-titlePage-back-cover
> 	// intentionallying leaving the export here saying that this is front, though it's actually back.
> ```

Could you add a line or two explaining why?

---

*[src/BloomExe/Book/XMatterInfo.cs, line 42 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1220#-KT7335TxaUL8xAv-Quq:-KT7335TxaUL8xAv-Qur:b63zvj1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9394ac4d52edf174205d0e257de3480323bb86b4/src/BloomExe/Book/XMatterInfo.cs#L42)):*
> ```Smalltalk
> 				var end = x.ToLowerInvariant().IndexOf("-xmatter");
> 				var label =  x.Substring(0, end);
> 				if (label == "Factory")
> ```

This is a very non-obvious substitution, which seems to deserve comment...is it for backwards compatibility? Why not just change the folder name?

---

*[src/BloomExe/Book/XMatterInfo.cs, line 51 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1220#-KT72GuwjjkK8VO1LC4g:-KT72GuwjjkK8VO1LC4h:b-gmks8m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9394ac4d52edf174205d0e257de3480323bb86b4/src/BloomExe/Book/XMatterInfo.cs#L51)):*
> ```Smalltalk
> 
> 		// from http://stackoverflow.com/a/5796793/723299
> 		private static string SplitCamelCase(string str)
> ```

It appears that this will only handle PascalCase (not the other variety of camelCase) since I don't see anything to capitalize the first letter. Also it doesn't look to me as though it will handle more than two words...that may be enough for now, but if I'm right it should be commented.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1220)*

**Comment by hatton** [comment]
Review status: 6 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Book/XMatterInfo.cs, line 42 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1220#-KT7335TxaUL8xAv-Quq:-KTAbDF2npKkWQMb7b5p:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9394ac4d52edf174205d0e257de3480323bb86b4/src/BloomExe/Book/XMatterInfo.cs#L42)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary>
> This is a very non-obvious substitution, which seems to deserve comment...is it for backwards compatibility? Why not just change the folder name?
</details>
Done.

---

*[src/BloomExe/Book/XMatterInfo.cs, line 51 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1220#-KT72GuwjjkK8VO1LC4g:-KTAZh6xNlp-zf7xmRC5:bh0qsm8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9394ac4d52edf174205d0e257de3480323bb86b4/src/BloomExe/Book/XMatterInfo.cs#L51)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary>
> It appears that this will only handle PascalCase (not the other variety of camelCase) since I don't see anything to capitalize the first letter. Also it doesn't look to me as though it will handle more than two words...that may be enough for now, but if I'm right it should be commented.
</details>
The first word doesn't require a space, so I'm not clear there is a problem there.  I think that it does handle any number of words; Testing shows it does handle multiple words.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1220)*

**Comment by hatton** [comment]
Review status: 6 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/xMatter/bloom-xmatter-mixins.jade, line 158 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1220#-KT7181avXELyW5zr9YT:-KTAbi7A7H-oso4Bm1Jt:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9394ac4d52edf174205d0e257de3480323bb86b4/src/BloomBrowserUI/xMatter/bloom-xmatter-mixins.jade#L158)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary>
> Could you add a line or two explaining why?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1220)*

**Comment by hatton** [comment]
Thanks for the review, @JohnThomson .

**Pull request merged**
