### PR TITLE
Update About

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3934)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3934)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[src/BloomBrowserUI/infoPages/aboutBox.htm, line 44 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3934#-MHW_7BD75zO2j4-2qO8:-MHW_7BD75zO2j4-2qO9:b-1anmm7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2f0474081b9f5d8e9d59707a63cebdfcf0c7d66b/src/BloomBrowserUI/infoPages/aboutBox.htm#L44)):*
> ```HTML
>         </p>
>         <p>
>             Dirk Sprenger&nbsp;(Volunteer):&nbsp;Testing
> ```

Also, not sure if we wanted to move Dirk to past contributors / which version that should start in?

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3934)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/infoPages/aboutBox.htm, line 44 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3934#-MHW_7BD75zO2j4-2qO8:-MHWdBjg755w1KELZGYF:bfra364) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2f0474081b9f5d8e9d59707a63cebdfcf0c7d66b/src/BloomBrowserUI/infoPages/aboutBox.htm#L44)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Also, not sure if we wanted to move Dirk to past contributors / which version that should start in?
</blockquote></details>

Yes, please go ahead and move him with this change.

Note the comment at the top of the file which states you're better off making these changes in BloomLibrary first. And there is a French file which may or may not need updating.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3934)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/infoPages/aboutBox.htm, line 44 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3934#-MHW_7BD75zO2j4-2qO8:-MHlTY8A5FatxFQjmRpt:brb8wc2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2f0474081b9f5d8e9d59707a63cebdfcf0c7d66b/src/BloomBrowserUI/infoPages/aboutBox.htm#L44)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Yes, please go ahead and move him with this change.

Note the comment at the top of the file which states you're better off making these changes in BloomLibrary first. And there is a French file which may or may not need updating.
</blockquote></details>

Apparently neither was in BL or BD fr version. Fr version doesn't really have a thorough past contributors list either.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3934)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
