### PR TITLE
Improve async unit tests

### PR DESCRIPTION
**Pull request by sujeffreyl**
Move away from the done() callback syntax. This syntax makes it easy to lose unhandled error messages (you get a timeout instead). As you can see, many of these tests weren't handling exceptions properly.
By changing this syntax, we can have a clearer picture of whether the timeouts are due to an unhandled error vs the code actually taking longer than 5 seconds.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4290)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4290)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts, line 1210 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4290#-MW0tp8QD9HGzAVmCPV1:-MW0tp8R4PKO0PySF2iA:b-daj5it) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1f62d32d90457a892d35ec20a423efbb2d34a2d7/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts#L1210)):*
> ```XML
>         }
> 
>         it("toggleRecordingMode(): converts from RecordSentence/PlaySentence to RecordTextBox/PlayTextBox upon recording", async () => {
> ```

So, this is one of the problematic unit tests.
You will notice that if an exception happens in the setup phase, it is not caught. It will cause a timeout in the unit test runner.  (This is a code defect, IMO... the try/catch should wrap the whole thing when using a done() based syntax, IMO).

I converted this to use a different syntax, so that Jasmine will automatically catch the errors and not time out so easily.

This change isn't going to solve our intermittent unit test problem directly.

However, by doing so, we can see whether or not the timeout is caused by an exception during the setup phase.  This is possible if some other test is messing up the necessary start state for this test.
My hunch is that this is probably not the case, but writing the unit tests this way will allow us to rule out this possibility. (or confirm it).

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4290)* status: all files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts, line 29 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4290#-MW1FBqx-NO8skMSzS9z:-MW1FBqx-NO8skMSzSA-:b8y5del) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1f62d32d90457a892d35ec20a423efbb2d34a2d7/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts#L29)):*
> ```XML
>         await initializeTalkingBookToolAsync();
>         done();
>     });
> ```

As discussed, this done syntax can also be removed, and we can update the comment above with your new knowledge.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4290)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts, line 29 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4290#-MW1FBqx-NO8skMSzS9z:-MW1H-Ic242srBCcEKfn:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1f62d32d90457a892d35ec20a423efbb2d34a2d7/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts#L29)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

As discussed, this done syntax can also be removed, and we can update the comment above with your new knowledge.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4290)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

**Pull request merged**
