### PR TITLE
Fix URL encoding of books with punctuation in title (BL-9041)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3969)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3969)* status: 0 of 5 files reviewed, 1 unresolved discussion

___
*[src/BloomExe/Extensions.cs, line 29 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3969#-MIUsN8B9mclrX4rF3LV:-MIUsN8C7uZqhvGIOYBR:b-ltrsth) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8106e2fdeaa3e8aeed8827a897d392fdfe0c9d60/src/BloomExe/Extensions.cs#L29)):*
> ```Smalltalk
> 		/// <param name="fileName">The raw filename used by the operating system</param>
> 		/// <returns>A well-formed, singly-encoded URL</returns>
> 		public static string ToLocalhostForBloomPlayer(this string fileName)
> ```

1) Actually, I don't really like the name of this method, but don't want to mess with the existing one... very open to ideas about a different method name or alternate solutions.
2) I also think the method doesn't really need to be an extension method and could go well in PublishToAndroidApi, but I feel like it needs to be in close proximity to the existing ToLocalhost method, so... here it is.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3969)* status: all files reviewed, 1 unresolved discussion

**Review by JohnThomson — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3969)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomExe/Extensions.cs, line 29 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3969#-MIUsN8B9mclrX4rF3LV:-MIV8Rxw5B-YHeM0jzYp:b-alu8jg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8106e2fdeaa3e8aeed8827a897d392fdfe0c9d60/src/BloomExe/Extensions.cs#L29)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

1) Actually, I don't really like the name of this method, but don't want to mess with the existing one... very open to ideas about a different method name or alternate solutions.
2) I also think the method doesn't really need to be an extension method and could go well in PublishToAndroidApi, but I feel like it needs to be in close proximity to the existing ToLocalhost method, so... here it is.
</blockquote></details>

As we discussed, let's call it ToLocalHostProperly for now, then plan to fix ToLocalHost in 5.0. Comment could mention that it is preferable to use this except where the URL will be decoded using UnescapeCharsForHttp, which we hope to retire.

**Review by JohnThomson — APPROVED** [review]
Should something that calls the renamed function be changed too?

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3969#-:-MIV9XUD-7Hxay-zaYVO:bc5rwx7)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

**Review by JohnThomson — APPROVED** [review]
never mind, found it.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3969#-:-MIVAA1d9poynRdsJY-a:bun383q)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3969)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
