### PR TITLE
BL-13084 Text Padding

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6326)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6326)* status: all files reviewed, 4 unresolved discussions (waiting on @hatton)

___
*[`src/content/appearanceThemes/appearance-theme-default.css` line 61 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6326#-NrlMHi72je4E1colY06:-NrlMHi72je4E1colY07:b-118ifi) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bd1cb3a9a63c67d03413ae3b9ecc835a54cdade8/src/content/appearanceThemes/appearance-theme-default.css#L61)):*
> ```CSS
>     --page-text-padding-bottom: 0em;
>     --page-text-padding-left: 0em;
>     --page-text-padding-right: 0em;
> ```

I'm not clear why there is a 'page-' at the start of these. They control padding for text (specifically bloom-editables on numbered pages). numberedPage-... might make sense, but I would call them just text-padding-left (etc).
___
*[`src/content/appearanceThemes/appearance-theme-default.css` line 223 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6326#-NrlLhu6BbpdAq7TrwEi:-NrlLhu6BbpdAq7TrwEj:b-pfhaus) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bd1cb3a9a63c67d03413ae3b9ecc835a54cdade8/src/content/appearanceThemes/appearance-theme-default.css#L223)):*
> ```CSS
>     padding-left: var(--page-text-padding-left);
> }
> /* TODO: don't apply these headings if we're in an overlay */
> ```

Do you want to do this before merging this PR? If not, does it need to be a card?
___
*[`src/content/appearanceThemes/appearance-theme-zero-margin-ebook.css` line 60 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6326#-NrlN929Ai363BPQs009:-NrlN929Ai363BPQs00A:b-dqef9h) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bd1cb3a9a63c67d03413ae3b9ecc835a54cdade8/src/content/appearanceThemes/appearance-theme-zero-margin-ebook.css#L60)):*
> ```CSS
> }
> 
> .Device16x9Portrait.numberedPage {
> ```

It's not obvious why top and bottom padding is appropriate for interactive pages, while left and right padding are not. If it was intentional, it deserves a comment.
Also, it would be nice to move this block near (if not into) the block that controls the other text padding variables.
___
*[`src/content/bookLayout/basePage.less` line 564 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6326#-NrlOWue3d5OG2mWu3Ru:-NrlOWue3d5OG2mWu3Rv:b-32kz6z) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bd1cb3a9a63c67d03413ae3b9ecc835a54cdade8/src/content/bookLayout/basePage.less#L564)):*
> ```Less
> }
> 
> // See comments below about the horizontal version of this rule.
> ```

This comment is now incomplete, because the horizontal version does NOT put space on either or both the top and bottom split like this one. Also it doesn't explain why we want the TG-only padding. (And it is puzzling. In our earlier discussions, and from comments above, I thought we did NOT want padding on just one side of a TG, because we wanted the new bloom-editable padding to usually be the same left and right and look even.)
(Also...we don't have any built-in pages where a split has a TG on both sides, but if someone made one, would you want a double page-split-vertical-gap?)

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6326)* status: all files reviewed, 8 unresolved discussions (waiting on @hatton)

___
*[`src/content/appearanceThemes/appearance-theme-default.css` line 215 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6326#-NtcH_Ir2RSuQJOjOZLC:-NtcH_Ir2RSuQJOjOZLD:bix6ewp) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4c5591915a5feff4ce2b81b8f05ce417f652936/src/content/appearanceThemes/appearance-theme-default.css#L215)):*
> ```CSS
> }
> 
> /* notice that we don't do this if the edit is inside an image (i.e. and overlay) */
> ```

"an overlay" (not "and")
___
*[`src/content/appearanceThemes/appearance-theme-default.css` line 216 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6326#-NtcJeKeAxY7e0HhQ_xS:-NtcJeKeAxY7e0HhQ_xT:bip1ona) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4c5591915a5feff4ce2b81b8f05ce417f652936/src/content/appearanceThemes/appearance-theme-default.css#L216)):*
> ```CSS
> 
> /* notice that we don't do this if the edit is inside an image (i.e. and overlay) */
> .numberedPage :not(.bloom-imageContainer) .bloom-editable {
> ```

If top and bottom apply to a bloom-editable, they will both be added to multilingual-editable-vertical-gap between languages in a multilingual book. Is that what we want? (Of course unlike the gap they will be inside the box we draw around the editable.)
Also: bloom-editables occur inside image containers not only for overlays, but also for image descriptions, IIRC. Do we want to suppress this there, too?
___
*[`src/content/bookLayout/basePage.less` line 554 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6326#-NtcKzSy2C_fR2Qq0tDX:-NtcKzSy2C_fR2Qq0tDY:buqlmed) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4c5591915a5feff4ce2b81b8f05ce417f652936/src/content/bookLayout/basePage.less#L554)):*
> ```Less
>     // and we're doing that so that when you snap something to 50%, both sides will be the same size.
>     // Related to BL-13073.
>     padding-right: calc(var(--page-verticalSplit-width) / 2);
> ```

It feels like it ought to be possible to have the value that says "split at 60%" in one place. Then we ought to be able to do a flex-box on the .split-pane.vertical-percent and give it a gap: var(--page-verticalSplit-width). Then set the .split-pane-component.position-left
    > .split-pane-component-inner' width to calc((100% - var(--page-verticalSplit-width)) * var(--split-percentage)) and the other one to something similar. Then each box would really be the right percentage of the non-gap space.
But I don't see how to get the UI-controlled percentage into a variable that applies to just this one spot.
___
*[`src/content/bookLayout/basePage.less` line 560 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6326#-NtcItvBCVQ8QN3zSHTy:-NtcItvBCVQ8QN3zSHTz:b-c2b1l1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4c5591915a5feff4ce2b81b8f05ce417f652936/src/content/bookLayout/basePage.less#L560)):*
> ```Less
>     .split-pane-component.position-right
>     > .split-pane-component-inner {
>     padding-left: calc(var(--page-verticalSplit-width) / 2);
> ```

I'm not clear why we're doing half-on-the-left, half-on-the-right, but the horizontal one uses all-on-the-bottom.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6326)* status: all files reviewed, 8 unresolved discussions (waiting on @JohnThomson)

___
*[`src/content/appearanceThemes/appearance-theme-default.css` line 61 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6326#-NrlMHi72je4E1colY06:-NtX_UYBD5k130X1oRle:bu1yydv) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bd1cb3a9a63c67d03413ae3b9ecc835a54cdade8/src/content/appearanceThemes/appearance-theme-default.css#L61)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm not clear why there is a 'page-' at the start of these. They control padding for text (specifically bloom-editables on numbered pages). numberedPage-... might make sense, but I would call them just text-padding-left (etc).
</blockquote></details>

Well, that's embarrassing!
___
*[`src/content/appearanceThemes/appearance-theme-default.css` line 223 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6326#-NrlLhu6BbpdAq7TrwEi:-NtXaJMNEdA5qBJvYvls:b60r506) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bd1cb3a9a63c67d03413ae3b9ecc835a54cdade8/src/content/appearanceThemes/appearance-theme-default.css#L223)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Do you want to do this before merging this PR? If not, does it need to be a card?
</blockquote></details>

Yes, done.
___
*[`src/content/appearanceThemes/appearance-theme-zero-margin-ebook.css` line 60 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6326#-NrlN929Ai363BPQs009:-NtXbLTlAWx_yc-Enviw:b-d8mu89) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bd1cb3a9a63c67d03413ae3b9ecc835a54cdade8/src/content/appearanceThemes/appearance-theme-zero-margin-ebook.css#L60)):*
> It's not obvious why top and bottom padding is appropriate for interactive pages, while left and right padding are not. If it was intentional, it deserves a comment.

Yeah I don't remember what that was about. Tested without and it seems right. Removed for now.

> Also, it would be nice to move this block near (if not into) the block that controls the other text padding variables.

I'm not clear what you're referring to here.
___
*[`src/content/bookLayout/basePage.less` line 564 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6326#-NrlOWue3d5OG2mWu3Ru:-NtXs0jz2WymasVFQgjo:bw3989b) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bd1cb3a9a63c67d03413ae3b9ecc835a54cdade8/src/content/bookLayout/basePage.less#L564)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This comment is now incomplete, because the horizontal version does NOT put space on either or both the top and bottom split like this one. Also it doesn't explain why we want the TG-only padding. (And it is puzzling. In our earlier discussions, and from comments above, I thought we did NOT want padding on just one side of a TG, because we wanted the new bloom-editable padding to usually be the same left and right and look even.)
(Also...we don't have any built-in pages where a split has a TG on both sides, but if someone made one, would you want a double page-split-vertical-gap?)
</blockquote></details>

We removed the bloom-translationGroup restriction, so it's back to how it was now.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6326)* status: all files reviewed, 8 unresolved discussions (waiting on @JohnThomson)

___
*[`src/content/bookLayout/basePage.less` line 554 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6326#-NtcKzSy2C_fR2Qq0tDX:-NtqGIW-CHKdP7_ZN2dj:b-mkdu3w) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4c5591915a5feff4ce2b81b8f05ce417f652936/src/content/bookLayout/basePage.less#L554)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It feels like it ought to be possible to have the value that says "split at 60%" in one place. Then we ought to be able to do a flex-box on the .split-pane.vertical-percent and give it a gap: var(--page-verticalSplit-width). Then set the .split-pane-component.position-left
    > .split-pane-component-inner' width to calc((100% - var(--page-verticalSplit-width)) * var(--split-percentage)) and the other one to something similar. Then each box would really be the right percentage of the non-gap space.
But I don't see how to get the UI-controlled percentage into a variable that applies to just this one spot.
</blockquote></details>

we decided to stick with what we have

**Pull request merged**
