### PR TITLE
Various improvements to publish to Bloom Reader and related

### PR DESCRIPTION
**Pull request by JohnThomson**
Adds a Refresh button
Removes automatic refresh when toggling a language check box
Various tweaks to the layout of the check boxes
Allow preview to be generated even if something goes wrong with navigating to the page we need for figuring out invisible stuff to delete (just don't delete it)
Fix up the way we release simulated page data to prevent race conditions releasing it too soon.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3499)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 7 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3499)* status: 7 of 12 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/publish/commonPublish/DeviceFrame.less, line 56 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3499#-LvQj59E1Lm4z2nsOvzm:-LvQj59E1Lm4z2nsOvzn:bfq4kk1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6a04ba9b3478c612fc76d213e062d988e5c7e5f/src/BloomBrowserUI/publish/commonPublish/DeviceFrame.less#L56)):*
> ```Less
>                 139,
>                 139
>             ); // also explicit in the svg; should this be some Bloom pallette color?
> ```

I'm surprised we need it here and in the svg. Isn't this sufficient?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3499)* status: 11 of 12 files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Publish/PublishHelper.cs, line 172 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3499#-LvQlk804wtF8z3VIRxb:-LvQlk804wtF8z3VIRxc:buw7n7u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6a04ba9b3478c612fc76d213e062d988e5c7e5f/src/BloomExe/Publish/PublishHelper.cs#L172)):*
> ```
> 			// the document will end up a little bigger. BloomReader and most epub readers
> 			// won't display things that are supposed to be invisible.
> ```
I didn't think this was true...

I'm a bit dubious that we just want to ignore this error condition... we should probably discuss.
___
*[src/BloomExe/Publish/Android/PublishToAndroidApi.cs, line 339 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3499#-LvQkZJHCoqeB2klN0nQ:-LvQkZJI0B71A-pq9yEx:bgvkv8h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6a04ba9b3478c612fc76d213e062d988e5c7e5f/src/BloomExe/Publish/Android/PublishToAndroidApi.cs#L339)):*
> ```Smalltalk
> 		{
> 			var newSettings = GetSettings();
> 			if (newSettings.Equals(_lastSettings) && _thumbnailBackgroundColor == _lastThumbnailBackgroundColor)
> ```

Is there a reason thumbnail color isn't part of the settings?
___
*[src/BloomExe/web/BloomServer.cs, line 1066 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3499#-LvQl4so9PmjrGkP3hIp:-LvQl4so9PmjrGkP3hIq:b4sdgo7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6a04ba9b3478c612fc76d213e062d988e5c7e5f/src/BloomExe/web/BloomServer.cs#L1066)):*
> ```Smalltalk
> 					}
> 
> 					_busyThreads++;
> ```

We don't need a lock (_queue) here?
___
*[src/BloomExe/web/BloomServer.cs, line 1135 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3499#-LvQlLzFBYFurJRtSApg:-LvQlLzFBYFurJRtSAph:b-3h3gv1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6a04ba9b3478c612fc76d213e062d988e5c7e5f/src/BloomExe/web/BloomServer.cs#L1135)):*
> ```Smalltalk
> 				{
> 					_busyThreads--;
> 				}
> ```

Should this be in the finally?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3499)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Publish/PublishHelper.cs, line 172 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3499#-LvQlk804wtF8z3VIRxb:-LvQpgbFBJ1WISuDxsQY:b85ba3g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6a04ba9b3478c612fc76d213e062d988e5c7e5f/src/BloomExe/Publish/PublishHelper.cs#L172)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> 			// the document will end up a little bigger. BloomReader and most epub readers
> 			// won't display things that are supposed to be invisible.
> ```
I didn't think this was true...

I'm a bit dubious that we just want to ignore this error condition... we should probably discuss.
</blockquote></details>

After discussion, JT had another idea about looking for possible deadlock in BloomServer.

Otherwise, discussed having the error thrown for epub only.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3499)* status: all files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/publish/commonPublish/DeviceFrame.less, line 56 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3499#-LvQj59E1Lm4z2nsOvzm:-LvR7zzY76w9rkiT95D-:b-umw1hx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6a04ba9b3478c612fc76d213e062d988e5c7e5f/src/BloomBrowserUI/publish/commonPublish/DeviceFrame.less#L56)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm surprised we need it here and in the svg. Isn't this sufficient?
</blockquote></details>

There ought to be some way for the document CSS to control colors in the SVG img, but I haven't found it yet. It can be done for inline svgs, but it's at best very tricky for an img whose src is an SVG. I tried one technique that involved using the SVG as a mask, but it gave different results in Gecko45 and Firefox, and neither of them were right.
We could inline the content of the SVG, but that's not very readable...
___
*[src/BloomExe/Publish/PublishHelper.cs, line 172 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3499#-LvQlk804wtF8z3VIRxb:-LvRBpCX630TPHHz1yHI:b-9jer7t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6a04ba9b3478c612fc76d213e062d988e5c7e5f/src/BloomExe/Publish/PublishHelper.cs#L172)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

After discussion, JT had another idea about looking for possible deadlock in BloomServer.

Otherwise, discussed having the error thrown for epub only.
</blockquote></details>

Found and fixed the real cause of the deadlocks, but also made the change selected here.
___
*[src/BloomExe/Publish/Android/PublishToAndroidApi.cs, line 339 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3499#-LvQkZJHCoqeB2klN0nQ:-LvRByZPAhBgyQzZ8tw9:b-44uanv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6a04ba9b3478c612fc76d213e062d988e5c7e5f/src/BloomExe/Publish/Android/PublishToAndroidApi.cs#L339)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is there a reason thumbnail color isn't part of the settings?
</blockquote></details>

It already existed before I invented settings so as to avoid more cycles of adding an argument to about 30 methods whenever there's a new setting that really only has one source and one place it's used. It would probably be a nice refactor to move it into settings, but I haven't looked into it yet. Reluctant to add to an already complex PR dealing with several issues, but maybe there should be a card, or even an immediate follow-up.
___
*[src/BloomExe/web/BloomServer.cs, line 1066 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3499#-LvQl4so9PmjrGkP3hIp:-LvRDBrwBnmyoCXESw2F:b-i09967) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6a04ba9b3478c612fc76d213e062d988e5c7e5f/src/BloomExe/web/BloomServer.cs#L1066)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We don't need a lock (_queue) here?
</blockquote></details>

Ask reviewable for a bit more context above. We're in one.
___
*[src/BloomExe/web/BloomServer.cs, line 1135 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3499#-LvQlLzFBYFurJRtSApg:-LvRDU-yCRxeH6UPonjK:bia5bdu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6a04ba9b3478c612fc76d213e062d988e5c7e5f/src/BloomExe/web/BloomServer.cs#L1135)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should this be in the finally?
</blockquote></details>

Definitely. Good catch.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3499)* status: 10 of 13 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/publish/commonPublish/DeviceFrame.less, line 56 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3499#-LvQj59E1Lm4z2nsOvzm:-LvS0cqAEmQGzM7vviSn:bb82xcl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6a04ba9b3478c612fc76d213e062d988e5c7e5f/src/BloomBrowserUI/publish/commonPublish/DeviceFrame.less#L56)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

There ought to be some way for the document CSS to control colors in the SVG img, but I haven't found it yet. It can be done for inline svgs, but it's at best very tricky for an img whose src is an SVG. I tried one technique that involved using the SVG as a mask, but it gave different results in Gecko45 and Firefox, and neither of them were right.
We could inline the content of the SVG, but that's not very readable...
</blockquote></details>

From TextOverPicture.less

// This can color the svg into whatever color we want. Currently bloom-purple.
// While working on this PR I changed the color 4 times and it's a pain to keep
// exporting new svgs.
// Eventually if the color settles down, we can replace this with just svg's colored like we want.
// To generate new filter rules like this, use https://codepen.io/sosuke/pen/Pjoqqp
@ComicAffordanceFilter: invert(48%) sepia(14%) saturate(1147%)
    hue-rotate(257deg) brightness(90%) contrast(84%);

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3499)* status: 10 of 13 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/publish/commonPublish/DeviceFrame.less, line 56 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3499#-LvQj59E1Lm4z2nsOvzm:-LvS0io2-egIgT2DvHQ3:bu0jsyv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6a04ba9b3478c612fc76d213e062d988e5c7e5f/src/BloomBrowserUI/publish/commonPublish/DeviceFrame.less#L56)):*
BTW not saying you should do this, just replying to 

> there ought to be some way for the document CSS to control colors in the SVG img

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3499)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/BloomExe/web/BloomServer.cs, line 1066 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3499#-LvQl4so9PmjrGkP3hIp:-LvS6j_Y5yx5nyaz2mgn:b-jhyysx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6a04ba9b3478c612fc76d213e062d988e5c7e5f/src/BloomExe/web/BloomServer.cs#L1066)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Ask reviewable for a bit more context above. We're in one.
</blockquote></details>

Got it. Thanks.

**Pull request merged**
