### PR TITLE
Update xliff files for markdown changes

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2009)

### CODE REVIEW

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2009#-:-L-ge47aYOecGE4KHcCf:bnfp4nl)*

**Comment by andrew-polk** [comment]
Argh. I merged this too quickly. In the Readme files, one instance of the email address in each file has become non-obfuscated.

**Comment by StephenMcConnel** [comment]
I think I saw some comments earlier this week (or last week?) on Flowdock about the obfuscation not being needed because these files are not exposed to the internet, but just to the Bloom browser window.  The underlying change is in either the markdown files themselves or in the markdown processing change that John Thomson made a few days ago.

**Comment by andrew-polk** [comment]
John Thomson was making that argument. We decided to keep the obfuscation and remove it during the gulp process. In my opinion, the only reason to obfuscate is for robots crawling our source code on github.

**Comment by andrew-polk** [comment]
So can we just put the obfuscation back in? Or is that going to cause a problem?

**Comment by StephenMcConnel** [comment]
The problem is that the xliff is created from the output of the gulp process.  So either we need to change something in the gulp process that creates both the html and xliff files to reobfuscate the xliff or else delay unobfuscating the html until after the xliff extraction process.  Or else programmers will have to live with these xliff files always claiming to have changed after the initial build process.  I find the last very irritating personally.  Maybe I should look into how to change the extraction program to obfuscate email addresses.  This is not a trivial problem due to the interlocking build process we have.  But I do understand the desire for obfuscated addresses in files checked in to github.

**Pull request merged**
