### PR TITLE
Another try at preserving branding (BL-13110)

### PR DESCRIPTION
**Pull request by JohnThomson**
- warn if upload will change branding on Blorg
- allow download-for-edit books to be edited using their original branding
- any time we open settings and the collection used to have a branding but lacks a code, show the old branding and message about it.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 15 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376)* status: 15 of 17 files reviewed, 10 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/collection/enterpriseSettings.tsx` line 136 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVnyRpAORSVZ7YuVLp:-NuVnyRpAORSVZ7YuVLq:b-6slp9u) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L136)):*
> ```XML
>                         {this.state.controlState === "SubscriptionLegacy" && (
>                             <Markdown
>                                 l10nKey="Settings.Enterprise.NeedsCode"
> ```

Should we change the id so that localizations get the new text?
___
*[`src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx` line 40 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVoq3cCDhot0NSIvgQ:-NuVoq3cCDhot0NSIvgR:b-c1phy6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx#L40)):*
> ```XML
>  * @returns A boolean, which is true if Bloom Enterprise is enabled and false otherwise
>  */
> export function useEnterpriseAvailable(failIfLockedToOneBook?: boolean) {
> ```

Probably if I thought harder it would occur to me eventually, but can you add a comment explaining why this parameter is needed here? It's not obvious why an API asking if BE is available should "fail" if we are locked to one book.
___
*[`src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx` line 188 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVpFOk39A1TNjQlJlh:-NuVpFOk39A1TNjQlJli:b-tj8oun) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx#L188)):*
> ```XML
>  * Checks the Bloom Enterprise settings and overlays a RequiresBloomEnterprise notice over the children if enterprise is off.
>  */
> export const RequiresBloomEnterpriseOverlayWrapper: React.FunctionComponent<{
> ```

Pls comment on this param too
___
*[`src/BloomExe/Collection/CollectionSettings.cs` line 393 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVpeu90zZHUe9Pi25S:-NuVpeu90zZHUe9Pi25T:b-wrtdxc) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomExe/Collection/CollectionSettings.cs#L393)):*
> ```Smalltalk
>         /// as we would do if creating a settings object from the settings file. (This is useful when
>         /// displaying the Branding dialog, to remind the user which branding they might want to find
>         /// a code for. We also use it to record the original branding for a book downloaded for editing,
> ```

To make this a bit clearer to my future self, let's change "a book downloaded for editing" to "a book downloaded using the 'Download for Editing' button on blorg".
___
*[`src/BloomExe/Collection/CollectionSettings.cs` line 397 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVq6b-6PCvje0I5S6R:-NuVq6b-6PCvje0I5S6S:b-dh9twq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomExe/Collection/CollectionSettings.cs#L397)):*
> ```Smalltalk
>         /// to be used, though we make an exception for that one book.)
>         /// </summary>
>         public static string LoadBranding(string pathToCollectionFile)
> ```

`LoadBranding` implied to me a lot more than this does. How about `ReadBrandingNameFromCollectionFile()`
___
*[`src/BloomExe/Collection/CollectionSettings.cs` line 481 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVqUblC0okQ0o-IRMD:-NuVqUblC0okQ0o-IRME:bo77dwe) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomExe/Collection/CollectionSettings.cs#L481)):*
> ```Smalltalk
>                         {
>                             // We make an exception when the collection is a single book downloaded for editing,
>                             // since we want to keep its branding. (The user can't add books to this collection without
> ```

How about
`the user can't add books to this collection without`  --> `The original uploader had a valid subscription when first uploaded, and we want to allow re-uploading for editing even if this user doesn't know that code or the subscription is expired`
___
*[`src/BloomExe/Collection/CollectionSettings.cs` line 483 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVqzSyDSaAycfon_bg:-NuVqzSyDSaAycfon_bh:b2q88pp) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomExe/Collection/CollectionSettings.cs#L483)):*
> ```Smalltalk
>                             // since we want to keep its branding. (The user can't add books to this collection without
>                             // first providing a valid branding.)
>                             _overrideBrandingForEditDownload = BrandingProjectKey;
> ```

Shall we make it parallel, like `_brandingProjectKeyOverrideForDownloadForEditing` ?
___
*[`src/BloomExe/Collection/CollectionSettingsDialog.cs` line 402 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVs3PT4vXe6ggK5sNV:-NuVs3PT4vXe6ggK5sNW:b-y1zr6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomExe/Collection/CollectionSettingsDialog.cs#L402)):*
> ```Smalltalk
>                 _collectionSettings.BrandingProjectKey = _brand;
>                 _collectionSettings.SubscriptionCode = _subscriptionCode;
>                 // We've definitely selected some branding, even if it's the default. So we no longer
> ```

Sorry I can't tell why we're deleting something here. Please comment.
___
*[`src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs` line 802 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVsdnQCW3mD-N-K3w0:-NuVsdnQCW3mD-N-K3w1:b-sog4f8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L802)):*
> ```Smalltalk
>             var existingThumbUrl = GetBloomLibraryThumbnailUrl(existingBookInfo);
> 
>             // We could get it from the data about the download-for-edit book, but why limit this to those books?
> ```

This reads like a // Review comment. If it's just an rhetorical question... let's change it to not be.
___
*[`src/BloomExe/Workspace/WorkspaceView.cs` line 957 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVtRJ-9LrmQJA6axlw:-NuVtRJ-9LrmQJA6axlx:b-1rtan7) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomExe/Workspace/WorkspaceView.cs#L957)):*
> ```Smalltalk
>                         var temp = dlg.ShowDialog(this);
>                         _currentlyOpenSettingsDialog = null;
>                         CollectionSettingsApi.EndFixEnterpriseBranding();
> ```

I'm uncomfortable with this kind of stateful API usage, but I don't know enough to suggest something different if you can't think of a different way.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376)* status: 9 of 17 files reviewed, 10 unresolved discussions (waiting on @hatton)

___
*[`src/BloomBrowserUI/collection/enterpriseSettings.tsx` line 136 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVnyRpAORSVZ7YuVLp:-NuZ_oQ12dqCNXtCNUSD:b-eycc5w) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L136)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Should we change the id so that localizations get the new text?
</blockquote></details>

As far as I can discover, we forgot to add this string to our XLF, so it can't ever have been localized. And if it now does (I deliberately didn't put translate="no") earlier Blooms will also be better of with the new wording, even in English.
___
*[`src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx` line 40 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVoq3cCDhot0NSIvgQ:-NuZdEa29U1dK4Sjqpeo:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx#L40)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Probably if I thought harder it would occur to me eventually, but can you add a comment explaining why this parameter is needed here? It's not obvious why an API asking if BE is available should "fail" if we are locked to one book.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx` line 188 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVpFOk39A1TNjQlJlh:-NuZeVs473IlY7Rvg7T6:bflzv3n) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx#L188)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Pls comment on this param too
</blockquote></details>

Done. (I also renamed it.)
___
*[`src/BloomExe/Collection/CollectionSettings.cs` line 393 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVpeu90zZHUe9Pi25S:-NuZevx_APyt2lNhPMc5:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomExe/Collection/CollectionSettings.cs#L393)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

To make this a bit clearer to my future self, let's change "a book downloaded for editing" to "a book downloaded using the 'Download for Editing' button on blorg".
</blockquote></details>

Done.
___
*[`src/BloomExe/Collection/CollectionSettings.cs` line 397 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVq6b-6PCvje0I5S6R:-NuZf1c7Cdtob7O5E41r:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomExe/Collection/CollectionSettings.cs#L397)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

`LoadBranding` implied to me a lot more than this does. How about `ReadBrandingNameFromCollectionFile()`
</blockquote></details>

Done.
___
*[`src/BloomExe/Collection/CollectionSettings.cs` line 481 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVqUblC0okQ0o-IRMD:-NuZftNM0MuLND77KJ_6:buaz6rm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomExe/Collection/CollectionSettings.cs#L481)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

How about
`the user can't add books to this collection without`  --> `The original uploader had a valid subscription when first uploaded, and we want to allow re-uploading for editing even if this user doesn't know that code or the subscription is expired`
</blockquote></details>

Done. (Actually I added that and kept a modified version of mine, since it was attempting to make a slightly different point.)
___
*[`src/BloomExe/Collection/CollectionSettings.cs` line 483 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVqzSyDSaAycfon_bg:-NuZgH2h3rQPgUsZedaf:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomExe/Collection/CollectionSettings.cs#L483)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Shall we make it parallel, like `_brandingProjectKeyOverrideForDownloadForEditing` ?
</blockquote></details>

Done.
___
*[`src/BloomExe/Collection/CollectionSettingsDialog.cs` line 402 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVs3PT4vXe6ggK5sNV:-NuZhvHe559D8vONoEo4:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomExe/Collection/CollectionSettingsDialog.cs#L402)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Sorry I can't tell why we're deleting something here. Please comment.
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs` line 802 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVsdnQCW3mD-N-K3w0:-NuZiDZpEM9ZxzsFek4E:b-hnd1br) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L802)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This reads like a // Review comment. If it's just an rhetorical question... let's change it to not be.
</blockquote></details>

I suppose in a way it was. I don't think you've ever confirmed my intuition that the "you are changing the branding" warning should be shown always, not just when re-uploading a "Download for editing" book. Assuming that is right, I don't think the comment is useful at all, so I deleted it.
___
*[`src/BloomExe/Workspace/WorkspaceView.cs` line 957 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVtRJ-9LrmQJA6axlw:-NuZlDr6Bn1ouwI8sQh3:b4xvnef) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomExe/Workspace/WorkspaceView.cs#L957)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I'm uncomfortable with this kind of stateful API usage, but I don't know enough to suggest something different if you can't think of a different way.
</blockquote></details>

I don't like it much either. Note, it is not new: we already had the ability to bring up the settings dialog in a special state where the enterprise tab is open and the key field is used to show the name of the branding this collection previously used, but lacks a current code for. What I basically did was to make that information show any time that tab is opened and the collection is in a state where it knows about a branding but doesn't have the corresponding code, not just when we first open the collection and find an invalid branding code.
I _think_ all the relevant logic could be moved out of the CollectionSettingsDialog and WorkspaceView into the CollectionSettingsApi, which could get its data from the collectionSettings rather than being told it independently. Then we might need to pass a param to the dialog to tell it when to open at the enterprise tab. If you want to do all that (I estimate a half day; I'm no longer familiar with the code if I ever was), I'd suggest a separate card and PR, especially since you're in a hurry to get this PR into testing.

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376)* status: 9 of 17 files reviewed, 11 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx` line 40 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVoq3cCDhot0NSIvgQ:-Nu_mwPA2mPa0ZCic9dt:b-3ishct) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx#L40)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Two problems. 1) It is not "failing", it's just returning false. 2) it seems kludgy. How about a different hook & API that tells you if it is the one locked book?
___
*[`src/BloomExe/web/controllers/CollectionSettingsApi.cs` line 81 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-Nu_mdQ79e4RQ136sfN5:-Nu_mdQ79e4RQ136sfN6:biwblbc) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/108f54176d332a8095baa071accd98e28a098d44/src/BloomExe/web/controllers/CollectionSettingsApi.cs#L81)):*
> ```Smalltalk
>         private bool IsEnterpriseEnabled(bool failIfLockedToOneBook)
>         {
>             if (failIfLockedToOneBook && _collectionSettings.LockedToOneDownloadedBook)
> ```

This isn't "failing", it's just return false.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376)* status: 9 of 17 files reviewed, 12 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx` line 244 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-Nu_nP6IDql6up2-sApt:-Nu_nP6IDql6up2-sApu:bxfz4wu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/108f54176d332a8095baa071accd98e28a098d44/src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx#L244)):*
> ```XML
>                         <RequiresBloomEnterpriseNotice
>                             darkTheme={true}
>                             failIfLockedToOneBook={props.showIfLockedToOneBook}
> ```

again, no "fail" happening here

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376)* status: 9 of 17 files reviewed, 6 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs` line 802 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVsdnQCW3mD-N-K3w0:-Nu_oPTP9h9wsQ4_faos:bfccy20) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L802)):*
> that the "you are changing the branding" warning should be shown always, not just when re-uploading a "Download for editing" book

OK

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376)* status: 9 of 17 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx` line 40 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVoq3cCDhot0NSIvgQ:-Nujne4D9KMTyXCkjcUw:b-bnc94v) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx#L40)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Two problems. 1) It is not "failing", it's just returning false. 2) it seems kludgy. How about a different hook & API that tells you if it is the one locked book?
</blockquote></details>

We discussed this and decided that the best solution is to just not the TC settings in this context.
___
*[`src/BloomExe/Workspace/WorkspaceView.cs` line 957 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVtRJ-9LrmQJA6axlw:-NujnOUY1CnAbh2SxadX:b-ha1c6y) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomExe/Workspace/WorkspaceView.cs#L957)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't like it much either. Note, it is not new: we already had the ability to bring up the settings dialog in a special state where the enterprise tab is open and the key field is used to show the name of the branding this collection previously used, but lacks a current code for. What I basically did was to make that information show any time that tab is opened and the collection is in a state where it knows about a branding but doesn't have the corresponding code, not just when we first open the collection and find an invalid branding code.
I _think_ all the relevant logic could be moved out of the CollectionSettingsDialog and WorkspaceView into the CollectionSettingsApi, which could get its data from the collectionSettings rather than being told it independently. Then we might need to pass a param to the dialog to tell it when to open at the enterprise tab. If you want to do all that (I estimate a half day; I'm no longer familiar with the code if I ever was), I'd suggest a separate card and PR, especially since you're in a hurry to get this PR into testing.
</blockquote></details>

We discussed this and decided that the key is that all this wants to be within the encapsulation of CollectionsSettings (or at least CollectionsSettingsApi)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376)* status: 9 of 17 files reviewed, 4 unresolved discussions (waiting on @hatton)

___
*[`src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs` line 802 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVsdnQCW3mD-N-K3w0:-Nu_uySw1BV0ydAxrwld:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L802)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

> that the "you are changing the branding" warning should be shown always, not just when re-uploading a "Download for editing" book

OK
</blockquote></details>

Done.
___
*[`src/BloomExe/Workspace/WorkspaceView.cs` line 957 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVtRJ-9LrmQJA6axlw:-NujvengAhkIcROmbuwO:bfr4h66) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomExe/Workspace/WorkspaceView.cs#L957)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

We discussed this and decided that the key is that all this wants to be within the encapsulation of CollectionsSettings (or at least CollectionsSettingsApi)
</blockquote></details>

I think I've accomplished what you want. There's still some state, but it's encapsulated in the CollectionsSettingsApi. We could possibly move a little more of the logic for launching the dialog into its own class, but it makes at least some sense for the Workspace to keep track of whether this dialog is open, I think.
___
*[`src/BloomExe/web/controllers/CollectionSettingsApi.cs` line 81 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-Nu_mdQ79e4RQ136sfN5:-NujzyW86W3rpwsu38SP:bwqrvd2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/108f54176d332a8095baa071accd98e28a098d44/src/BloomExe/web/controllers/CollectionSettingsApi.cs#L81)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This isn't "failing", it's just return false.
</blockquote></details>

Got rid of it.
___
*[`src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx` line 40 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVoq3cCDhot0NSIvgQ:-Nu_vFpw48Yo2nLHw7UQ:bwqrvd2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx#L40)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

We discussed this and decided that the best solution is to just not the TC settings in this context.
</blockquote></details>

Got rid of it.
___
*[`src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx` line 244 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-Nu_nP6IDql6up2-sApt:-Nuk-7wG3UqB3BQ1QXa4:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/108f54176d332a8095baa071accd98e28a098d44/src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx#L244)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

again, no "fail" happening here
</blockquote></details>

Done.

**Review by hatton — APPROVED** [review]
> Reviewed 3 of 6 files at r2, 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/Workspace/WorkspaceView.cs` line 957 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376#-NuVtRJ-9LrmQJA6axlw:-NuzpawX8sn6KaoERnJM:b-jmjr7y) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ce9b500aa3d93f477eaac2111400e2cd05cca541/src/BloomExe/Workspace/WorkspaceView.cs#L957)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think I've accomplished what you want. There's still some state, but it's encapsulated in the CollectionsSettingsApi. We could possibly move a little more of the logic for launching the dialog into its own class, but it makes at least some sense for the Workspace to keep track of whether this dialog is open, I think.
</blockquote></details>

Feels to me like the whole thing is a failure of encapsulation. I'll let it go now.

**Review by hatton — COMMENTED** [review]
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6376)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Pull request merged**
