### PR TITLE
Display an informational message after Copy Hyperlink (BL-10405)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4726)

### CODE REVIEW

**Review by StephenMcConnel — CHANGES_REQUESTED** [review]
looks good with one question that may or may not prompt a change.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4726#-:-Mk2mLEg-kOzSZxSW6Bq:b1ksdvw)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Edit/PageListView.cs, line 72 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4726#-Mk2m3LwBk_gxHkVTeDQ:-Mk2m3Lx48FI-OpH-vPW:bwnckkw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d36a762f64ba5e9f0c1f027453de1086466da255/src/BloomExe/Edit/PageListView.cs#L72)):*
> ```Smalltalk
> 						if (!_hyperlinkMessageShown)
> 						{
> 							_hyperlinkMessageShown = true;
> ```

I assume that it's acceptable for users to see this message every time they run Bloom and click on the "Copy Hyperlink" button the first time.
If so, then this change looks okay.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4726)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/Edit/PageListView.cs, line 72 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4726#-Mk2m3LwBk_gxHkVTeDQ:-Mk2scfe8-VH3m0j26BJ:bszv04j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d36a762f64ba5e9f0c1f027453de1086466da255/src/BloomExe/Edit/PageListView.cs#L72)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I assume that it's acceptable for users to see this message every time they run Bloom and click on the "Copy Hyperlink" button the first time.
If so, then this change looks okay.
</blockquote></details>

Waiting for JohnH's input on that. The card didn't specify whether it should occur every time they use the command, once per session, once per book, once per user, or whether it should have a "stop showing this" checkbox. I thought every time would be annoying, so I went for the next simplest thing.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4726)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/Edit/PageListView.cs, line 72 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4726#-Mk2m3LwBk_gxHkVTeDQ:-Mk2t89YAb5mGvnFt9fq:buz46tl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d36a762f64ba5e9f0c1f027453de1086466da255/src/BloomExe/Edit/PageListView.cs#L72)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Waiting for JohnH's input on that. The card didn't specify whether it should occur every time they use the command, once per session, once per book, once per user, or whether it should have a "stop showing this" checkbox. I thought every time would be annoying, so I went for the next simplest thing.
</blockquote></details>

I'm inclined not to wait another week for that input, though. We can always enhance it later.

**Review by StephenMcConnel — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4726#-:-Mk2ujcLCb2wQaZEUsmq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Edit/PageListView.cs, line 72 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4726#-Mk2m3LwBk_gxHkVTeDQ:-Mk2uhF7ApQp89nYoyi8:b-gxztsp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d36a762f64ba5e9f0c1f027453de1086466da255/src/BloomExe/Edit/PageListView.cs#L72)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm inclined not to wait another week for that input, though. We can always enhance it later.
</blockquote></details>

Fair enough.

**Review by StephenMcConnel — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4726)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by StephenMcConnel — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4726)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
