### PR TITLE
BL-3436 Allow user to make their own template book

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1523)

### CODE REVIEW

**Comment by andrew-polk** [comment]
A few nit things. Otherwise, :lgtm: 

---

Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/BloomBrowserUI/templates/template books/Template Starter/ReadMe-en.md, line 1 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1523#-Ke-QpLW8UpECO7Y8oTS:-Ke-QpLW8UpECO7Y8oTT:b-xh1mz6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c34f7d46714f314e9d931dfba4edb8376ba48a38/src/BloomBrowserUI/templates/template books/Template Starter/ReadMe-en.md#L1)):*
> an    original

trivial extra whitespace; not worth a change just for that

---

*[src/BloomBrowserUI/templates/template books/Template Starter/ReadMe-en.md, line 6 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1523#-Ke-R-JgeAy8buM8viDR:-Ke-R-JgeAy8buM8viDS:b43bdz7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c34f7d46714f314e9d931dfba4edb8376ba48a38/src/BloomBrowserUI/templates/template books/Template Starter/ReadMe-en.md#L6)):*
> The Title of your book should end in Template. Bloom currently requires this to enable the pages in your book to be available for use in other books.

I would have expected this limitation to go away with these code changes.
Deemed too costly?
I foresee user reports saying their template isn't behaving as they expected because they didn't read this.
Perhaps we can make it more obvious by making the Template Starter have, as an initial title, something explanatory?

---

*[src/BloomExe/Book/BookStarter.cs, line 352 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1523#-Ke-WCw-xyZ5MJYer3UP:-Ke-WCw-xyZ5MJYer3UQ:b83x9or) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c34f7d46714f314e9d931dfba4edb8376ba48a38/src/BloomExe/Book/BookStarter.cs#L352)):*
> Book.SetType()

I don't see this method. Perhaps it was intended to be added but not kept after changes to remove the enum?

---

*[src/BloomExe/Book/BookStarter.cs, line 358 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1523#-Ke-WXwrZnG_8bpDmQqP:-Ke-WXwrZnG_8bpDmQqQ:b-6uf0cd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c34f7d46714f314e9d931dfba4edb8376ba48a38/src/BloomExe/Book/BookStarter.cs#L358)):*
> ```Smalltalk
> 			}
> 
> //#if maybe //hard to pin down when a story primer, dictionary, etc. also becomes a new "source for new shells"
> ```

Any reason to leave the commented code in?

---

*[src/BloomExe/Book/HtmlDom.cs, line 1302 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1523#-Ke-YSAa50dDbaGtS2Ym:-Ke-YSAa50dDbaGtS2Yn:b-mdq3hp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c34f7d46714f314e9d931dfba4edb8376ba48a38/src/BloomExe/Book/HtmlDom.cs#L1302)):*
> ```Smalltalk
> 			if(label != null)
> 			{
> 				if(isTemplatePage)
> ```

A minor issue: you could save the xpath call by returning previously if !isTemplatePage

---

*[src/BloomTests/Book/BookTests.cs, line 375 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1523#-Ke-bHDUcfhcfcXqlkvo:-Ke-bHDUcfhcfcXqlkvp:b-4clhs6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c34f7d46714f314e9d931dfba4edb8376ba48a38/src/BloomTests/Book/BookTests.cs#L375)):*
> ```Smalltalk
> 
> 		[Test]
> 		public void InsertPageAfter_InTemplateBook_NewPageIsMarkedExtra()
> ```

Worth checking that it isn't extra if it isn't a template book?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1523#-:-Ke-c1eoH6nwFhs2FAMa:bg4nut2)*

**Comment by andrew-polk** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1523)*

**Comment by JohnThomson** [comment]
I think I've dealt with or responded to them all.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/BloomBrowserUI/templates/template books/Template Starter/ReadMe-en.md, line 1 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1523#-Ke-QpLW8UpECO7Y8oTS:-Ke0EwhEFoj_Oi9j4VaV:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c34f7d46714f314e9d931dfba4edb8376ba48a38/src/BloomBrowserUI/templates/template books/Template Starter/ReadMe-en.md#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> an    original

trivial extra whitespace; not worth a change just for that
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/templates/template books/Template Starter/ReadMe-en.md, line 6 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1523#-Ke-R-JgeAy8buM8viDR:-Ke0F-K5axXOkDPRuMm6:bkjg86v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c34f7d46714f314e9d931dfba4edb8376ba48a38/src/BloomBrowserUI/templates/template books/Template Starter/ReadMe-en.md#L6)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> The Title of your book should end in Template. Bloom currently requires this to enable the pages in your book to be available for use in other books.

I would have expected this limitation to go away with these code changes.
Deemed too costly?
I foresee user reports saying their template isn't behaving as they expected because they didn't read this.
Perhaps we can make it more obvious by making the Template Starter have, as an initial title, something explanatory?
</blockquote></details>

We need some way to distinguish templates whose pages should be offered everywhere (like Arithmetic) from ones that shouldn't (like Calendar). John wanted to keep the cost of this change down so we decided not to attempt that improvement yet. Bloom does stick "Template" in (both) titles to encourage this behavior. If you don't think that's enough, maybe discuss options with @hatton?

---

*[src/BloomExe/Book/BookStarter.cs, line 352 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1523#-Ke-WCw-xyZ5MJYer3UP:-Ke0Fwwen7qrWacoQ5cn:b-p84t04) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c34f7d46714f314e9d931dfba4edb8376ba48a38/src/BloomExe/Book/BookStarter.cs#L352)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> Book.SetType()

I don't see this method. Perhaps it was intended to be added but not kept after changes to remove the enum?
</blockquote></details>

It existed at one point, but changed names when Type went away. Fixed.

---

*[src/BloomExe/Book/BookStarter.cs, line 358 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1523#-Ke-WXwrZnG_8bpDmQqP:-Ke0GC5lfuvmeOrgLWas:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c34f7d46714f314e9d931dfba4edb8376ba48a38/src/BloomExe/Book/BookStarter.cs#L358)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Any reason to leave the commented code in?
</blockquote></details>

Done.

---

*[src/BloomExe/Book/HtmlDom.cs, line 1302 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1523#-Ke-YSAa50dDbaGtS2Ym:-Ke0Gk67j2Nd90Rvrteo:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c34f7d46714f314e9d931dfba4edb8376ba48a38/src/BloomExe/Book/HtmlDom.cs#L1302)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

A minor issue: you could save the xpath call by returning previously if !isTemplatePage
</blockquote></details>

Done.

---

*[src/BloomTests/Book/BookTests.cs, line 375 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1523#-Ke-bHDUcfhcfcXqlkvo:-Ke0H1fIls9VcYgUBVQA:bxdyih5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c34f7d46714f314e9d931dfba4edb8376ba48a38/src/BloomTests/Book/BookTests.cs#L375)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Worth checking that it isn't extra if it isn't a template book?
</blockquote></details>

I think that's the previous (existing) test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1523#-:-Ke0HBIRp7eg65ntUEI1:boqf1h8)*

**Comment by andrew-polk** [comment]
:lgtm:
I'll let either @Thomson or @Hatton merge it.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/templates/template books/Template Starter/ReadMe-en.md, line 6 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1523#-Ke-R-JgeAy8buM8viDR:-Ke0QmTzgRLKa6GM61zV:b-zhcw05) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c34f7d46714f314e9d931dfba4edb8376ba48a38/src/BloomBrowserUI/templates/template books/Template Starter/ReadMe-en.md#L6)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We need some way to distinguish templates whose pages should be offered everywhere (like Arithmetic) from ones that shouldn't (like Calendar). John wanted to keep the cost of this change down so we decided not to attempt that improvement yet. Bloom does stick "Template" in (both) titles to encourage this behavior. If you don't think that's enough, maybe discuss options with @hatton?
</blockquote></details>

He says the xmatter will have more information to help the user as they create their template.

---

*[src/BloomTests/Book/BookTests.cs, line 375 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1523#-Ke-bHDUcfhcfcXqlkvo:-Ke0Pce1Gq1yHbZWdD8W:b-otvfym) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c34f7d46714f314e9d931dfba4edb8376ba48a38/src/BloomTests/Book/BookTests.cs#L375)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think that's the previous (existing) test.
</blockquote></details>

Yes, I see it now. I didn't realize 'extra' was a previous concept. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1523#-:-Ke0QvOwbLqQxVwqTT63:b88h4w9)*

**Pull request merged**
