### PR TITLE
Optimize epub creation

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3941)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
Looks good, but I think we decided it is too risky for 4.8.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3941#-:-MI5OQFsDPqXIn01d-X5:bxidfru)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jsubloom — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3941)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/ProjectContext.cs, line 476 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3941#-MIKNwxC9sgxdNmFjaZU:-MIKNwxC9sgxdNmFjaZV:b-v5qklf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0912ab84536a53e01747376f1b3fbba88ca9b96e/src/BloomExe/ProjectContext.cs#L476)):*
> ```Smalltalk
> 		private static List<string> _userInstalledDirectories;
> 
> 		public static void ClearUserInStalledDirectoriesCache()
> ```

probably want to case it as "Installed" than "InStalled"

**Review by jsubloom — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3941)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/BloomFileLocator.cs, line 337 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3941#-MIKOepE3By7O9Odhxv_:-MIKOepE3By7O9Odhxva:b7oxgo3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0912ab84536a53e01747376f1b3fbba88ca9b96e/src/BloomExe/BloomFileLocator.cs#L337)):*
> ```
> out result
> ```
You could do out string result here and then save a line on declaring result 1 line above and then it being done with almost immediately after that.
___
*[src/BloomExe/ProjectContext.cs, line 446 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3941#-MIKPhUx2WknY1-HdYt7:-MIKPhUy9Kp1QOfcTaXc:b-tgtzvq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0912ab84536a53e01747376f1b3fbba88ca9b96e/src/BloomExe/ProjectContext.cs#L446)):*
> ```
> path
> ```
TryGetValue throws an exception if the key is null... I guess here I feel like we could easily add a null check and return false if null.

(Some of the other ones make me antsy too but I guess there's not much meaningful things we could do.

**Review by JohnThomson — COMMENTED** [review]
retargeted to 4.9

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3941#-:-MILtZVH8H9hf690vRJ9:bhjm0wi)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomExe/BloomFileLocator.cs, line 337 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3941#-MIKOepE3By7O9Odhxv_:-MILfIfG7e0FeOgrk6uC:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0912ab84536a53e01747376f1b3fbba88ca9b96e/src/BloomExe/BloomFileLocator.cs#L337)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> out result
> ```
You could do out string result here and then save a line on declaring result 1 line above and then it being done with almost immediately after that.
</blockquote></details>

Done.
___
*[src/BloomExe/ProjectContext.cs, line 446 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3941#-MIKPhUx2WknY1-HdYt7:-MILgDCD-r7hVlxY6o5R:beli9jn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0912ab84536a53e01747376f1b3fbba88ca9b96e/src/BloomExe/ProjectContext.cs#L446)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> path
> ```
TryGetValue throws an exception if the key is null... I guess here I feel like we could easily add a null check and return false if null.

(Some of the other ones make me antsy too but I guess there's not much meaningful things we could do.
</blockquote></details>

The argument is meant to be a path to a book folder. Passing null is almost certainly a programming error. So my inclination is just to let it fail fast. I'm pretty sure it would have done so before this change, as code tries to make a BookInfo out of a null that is supposed to be the path to the folder. The only two callers are enumerating directories and won't be passing nulls.
___
*[src/BloomExe/ProjectContext.cs, line 476 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3941#-MIKNwxC9sgxdNmFjaZU:-MILtchRDuaLDo1cHjzW:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0912ab84536a53e01747376f1b3fbba88ca9b96e/src/BloomExe/ProjectContext.cs#L476)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

probably want to case it as "Installed" than "InStalled"
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3941)* status: all files reviewed, 3 unresolved discussions (waiting on @sujeffreyl)

**Review by jsubloom — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3941)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
