### PR TITLE
BL-10507 ID Collision dialog

### PR DESCRIPTION
**Pull request by gmartin7**
* update wording per Koen
* fix thumb top-alignment

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4841)

### CODE REVIEW

**Review by StephenMcConnel — CHANGES_REQUESTED** [review]
Some minor questions, the most important being a file with only whitespace changes.  If the whitespace changes are actually desired, it maybe should be a separate PR.  The other questions about a method signature can be ignored if you like.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4841#-:-MprF4o9CxXu4IZgtN8W:bu40w6e)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs, line 175 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4841#-MprDAl96Q4hg-Gl1JeS:-MprDAlA2ux0m23Lcjwa:b2axbjq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/255c2b9b56ac4b905eddcc9218ce3a966883e155/src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs#L175)):*
> ```Smalltalk
> 		// but if necessary will be shrunk to fit within the indicated rectangle. We would like to set a default backColor,
> 		// since one caller uses it and the other doesn't. But it doesn't work. There are no compile-time constants to use.
> 		public static bool GenerateThumbnail(string originalPath, string pathToProcessedImage, int newWidth, Color backColor)
> ```

Could you use a default value of Color backColor = Color.Empty ?  Would there be any advantage to doing so?  So many trivial questions which may not deserve an answer...
___
*[src/BloomExe/Publish/Android/PublishToAndroidApi.cs, line 1 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4841#-MprDa_mAdSS5Bs-nOAp:-MprDa_mAdSS5Bs-nOAq:brokks6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/255c2b9b56ac4b905eddcc9218ce3a966883e155/src/BloomExe/Publish/Android/PublishToAndroidApi.cs#L1)):*
> ```Smalltalk
> using System;
> ```

Are these 656 lines with whitespace changes on purpose?  Is there any way / reason to avoid them?  Is it a line-ending fix to ensure \r\n on Windows?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4841)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs, line 175 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4841#-MprDAl96Q4hg-Gl1JeS:-Mps2m4r2sVfcokoNupl:bw1phxm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/255c2b9b56ac4b905eddcc9218ce3a966883e155/src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs#L175)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Could you use a default value of Color backColor = Color.Empty ?  Would there be any advantage to doing so?  So many trivial questions which may not deserve an answer...
</blockquote></details>

I tried that. Would have preferred that. Doesn't compile. Color.Empty "isn't a compile-time constant"
___
*[src/BloomExe/Publish/Android/PublishToAndroidApi.cs, line 1 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4841#-MprDa_mAdSS5Bs-nOAp:-Mps418dDhHc9K4FuelD:bov65y7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/255c2b9b56ac4b905eddcc9218ce3a966883e155/src/BloomExe/Publish/Android/PublishToAndroidApi.cs#L1)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Are these 656 lines with whitespace changes on purpose?  Is there any way / reason to avoid them?  Is it a line-ending fix to ensure \r\n on Windows?
</blockquote></details>

I'm only seeing that I took one extraneous space out of line 209 `request.ReplyWithImage(thumbnail.Path);`. Git isn't showing me any  whitespace changes.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4841)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs, line 175 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4841#-MprDAl96Q4hg-Gl1JeS:-MpsL4vq1vOwK7pGVnxM:b-ry71lg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/255c2b9b56ac4b905eddcc9218ce3a966883e155/src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs#L175)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I tried that. Would have preferred that. Doesn't compile. Color.Empty "isn't a compile-time constant"
</blockquote></details>

Color.Transparent might make a good default? If you want a default but the compiler won't let you just add "=Color.Transparent", you can achieve much the same effect with an overload that lacks the last argument and is implemented to call this one with the appropriate default. (Usually another option is to make the default null, then if the argument is null set it to the desired default in the first line. But Color is a struct so I don't think you can set it to null.)

**Review by StephenMcConnel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4841#-:-MpsNdCYAiKDCo2-QRBT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomExe/Publish/Android/PublishToAndroidApi.cs, line 1 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4841#-MprDa_mAdSS5Bs-nOAp:-MpsNNRr0oVHlOeSfqhZ:b7luc90) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/255c2b9b56ac4b905eddcc9218ce3a966883e155/src/BloomExe/Publish/Android/PublishToAndroidApi.cs#L1)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I'm only seeing that I took one extraneous space out of line 209 `request.ReplyWithImage(thumbnail.Path);`. Git isn't showing me any  whitespace changes.
</blockquote></details>

Either I misread things earlier, or Reviewable has decided to behave...  :-)

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4841)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/Publish/Android/PublishToAndroidApi.cs, line 1 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4841#-MprDa_mAdSS5Bs-nOAp:-MpvshAJDzFsWq7cwFht:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/255c2b9b56ac4b905eddcc9218ce3a966883e155/src/BloomExe/Publish/Android/PublishToAndroidApi.cs#L1)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Either I misread things earlier, or Reviewable has decided to behave...  :-)
</blockquote></details>

Done.

**Review by StephenMcConnel — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4841)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
