### PR TITLE
Add an initial set of appearance migrations (BL-13021)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
Also fix a few bugs in the appearance migration code.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271)* status: 0 of 12 files reviewed, 7 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/content/appearanceThemes/appearance-theme-efl-ebook-1.css` line 6 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRV5I43zEP3WTfWRIs:-NpRV5I43zEP3WTfWRIt:bdk2y8b) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/content/appearanceThemes/appearance-theme-efl-ebook-1.css#L6)):*
> ```CSS
> 
> .numberedPage::after {
>   display: none;
> ```

Let's use an appearance switch for show/hide page number
___
*[`src/content/appearanceThemes/appearance-theme-efl-ebook-1.css` line 11 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRTfRg7vxQ6q0Wo1RM:-NpRTfRg7vxQ6q0Wo1RN:b-cxx5hi) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/content/appearanceThemes/appearance-theme-efl-ebook-1.css#L11)):*
> ```CSS
> /* This statement hides the credits row on the front cover. */
> 
> .creditsRow {
> ```

Let's limit themes to interior (non-xmatter) aspects for now.  
___
*[`src/content/appearanceThemes/appearance-theme-efl-ebook-2.css` line 12 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRTw0b-bwvfaVUrXKP:-NpRTw0b-bwvfaVUrXKQ:b-cxx5hi) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/content/appearanceThemes/appearance-theme-efl-ebook-2.css#L12)):*
> ```CSS
> 
> .creditsRow {
>   display: none;
> ```

Let's limit themes to interior (non-xmatter) aspects for now.  
___
*[`src/content/appearanceThemes/appearance-theme-efl-ebook-3.css` line 8 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRTwuP1R_LRQ1X_g-6:-NpRTwuP1R_LRQ1X_g-7:b7tz073) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/content/appearanceThemes/appearance-theme-efl-ebook-3.css#L8)):*
> ```CSS
>  * Simply delete this statement if you want the credits row back. */
> .creditsRow {
>   display: none;
> ```

Let's limit themes to styling rather than hiding things, for now. Whether a field shows should have an appearance boolean in any case.
___
*[`src/content/appearanceThemes/appearance-theme-efl-ebook-3.css` line 17 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRUVJUDpYqsbEyH6au:-NpRUVJUDpYqsbEyH6av:b-ct61dm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/content/appearanceThemes/appearance-theme-efl-ebook-3.css#L17)):*
> ```CSS
> 
> :not(.bloom-interactive-page).Device16x9Landscape  {
>   --cover-margin-top: 2mm;
> ```

It would be nice to not have these cover things here, but maybe we need them. First though, should these be the new default? What are the current ones?
___
*[`src/content/appearanceThemes/appearance-theme-efl-ebook-3.css` line 52 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRU48u4hIzQW1uzar8:-NpRU48u4hIzQW1uzar9:b-bmcfxc) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/content/appearanceThemes/appearance-theme-efl-ebook-3.css#L52)):*
> ```CSS
>   --pageNumber-right-margin: unset;
> 
>   /* the following don't have variables to set, or to use the variables we do have. */
> ```

did you want "or use"?
___
*[`src/content/appearanceThemes/appearance-theme-efl-ebook-3.css` line 53 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRUHLqB9VV7y-nyaBr:-NpRUHLqB9VV7y-nyaBs:bdzbj49) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/content/appearanceThemes/appearance-theme-efl-ebook-3.css#L53)):*
> ```CSS
> 
>   /* the following don't have variables to set, or to use the variables we do have. */
>   color: black;
> ```

Wouldn't it be black by default?

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271)* status: 0 of 12 files reviewed, 8 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Book/AppearanceSettings.cs` line 836 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRVJly6DUBZj2ZQwhi:-NpRVJly6DUBZj2ZQwhj:b-xkhrqw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/BloomExe/Book/AppearanceSettings.cs#L836)):*
> ```Smalltalk
>             // We have a file that looks like it should have been migrated, so we don't want to complain about it.
>             // Do a few more checks to make sure we don't want to complain.
>             // REVIEW: are these checks all needed? or all valid?
> ```

@JohnThomson please review

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271)* status: 0 of 12 files reviewed, 8 unresolved discussions (waiting on @hatton)

___
*[`src/content/appearanceThemes/appearance-theme-efl-ebook-1.css` line 6 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRV5I43zEP3WTfWRIs:-NpVf_pU9tv833pIvy-h:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/content/appearanceThemes/appearance-theme-efl-ebook-1.css#L6)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Let's use an appearance switch for show/hide page number
</blockquote></details>

Done.
___
*[`src/content/appearanceThemes/appearance-theme-efl-ebook-1.css` line 11 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRTfRg7vxQ6q0Wo1RM:-NpVfvst-PdjE4JtD2YI:biqbwet) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/content/appearanceThemes/appearance-theme-efl-ebook-1.css#L11)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Let's limit themes to interior (non-xmatter) aspects for now.
</blockquote></details>

Done. I moved this to the replacement custom CSS file to maintain migration compatibility.
___
*[`src/content/appearanceThemes/appearance-theme-efl-ebook-2.css` line 12 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRTw0b-bwvfaVUrXKP:-NpVw8OaAnFNp6EPq1OP:biqbwet) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/content/appearanceThemes/appearance-theme-efl-ebook-2.css#L12)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Let's limit themes to interior (non-xmatter) aspects for now.
</blockquote></details>

Done. I moved this to the replacement custom CSS file to maintain migration compatibility.
___
*[`src/content/appearanceThemes/appearance-theme-efl-ebook-3.css` line 8 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRTwuP1R_LRQ1X_g-6:-NpVjaH-8q_M_sLw-eOm:bbk492b) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/content/appearanceThemes/appearance-theme-efl-ebook-3.css#L8)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Let's limit themes to styling rather than hiding things, for now. Whether a field shows should have an appearance boolean in any case.
</blockquote></details>

Done.  I moved this to the replacement custom CSS file to maintain migration compatibility.
___
*[`src/content/appearanceThemes/appearance-theme-efl-ebook-3.css` line 17 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRUVJUDpYqsbEyH6au:-NpWgX1yDab7HDj2I60k:baus2oa) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/content/appearanceThemes/appearance-theme-efl-ebook-3.css#L17)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

It would be nice to not have these cover things here, but maybe we need them. First though, should these be the new default? What are the current ones?
</blockquote></details>

The default page margins for Device16x9Landscape is 10px, which computes to about 2.65mm for all pages except the numbered pages where the bottom margin is 45px.  I imagine the desire was to have the page margins be the same on all the non-interactive pages.
___
*[`src/content/appearanceThemes/appearance-theme-efl-ebook-3.css` line 52 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRU48u4hIzQW1uzar8:-NpVmjOx9advf4-jHlbr:b5q904) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/content/appearanceThemes/appearance-theme-efl-ebook-3.css#L52)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

did you want "or use"?
</blockquote></details>

I removed the comment, moving the color setting to the customBookStyles2.css file and the other two lines to the pageNumbers.less file.
___
*[`src/content/appearanceThemes/appearance-theme-efl-ebook-3.css` line 53 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRUHLqB9VV7y-nyaBr:-NpVm_EVCnBf3SAnXExy:b3p5rcx) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/content/appearanceThemes/appearance-theme-efl-ebook-3.css#L53)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Wouldn't it be black by default?
</blockquote></details>

Usually, but not guaranteed.  the default for color is "inherit".
I moved the color setting to the replacement custom CSS file to maintain migration compatibility.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271)* status: 0 of 14 files reviewed, 9 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[`src/BloomExe/Book/AppearanceSettings.cs` line 836 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRVJly6DUBZj2ZQwhi:-Np__cCn8D_aSlB5YV6q:b-1mkngh) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/BloomExe/Book/AppearanceSettings.cs#L836)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

@JohnThomson please review
</blockquote></details>

@hatton This is first a UI question. When we have done a smart migration (that is, what's in customBookStyles.css was recognized, and we know how to pick a theme and possibly customBookStyles2.css to make it look good in appearance), do we still want the message that "customBookStyles.css is incompatible with modern themes, Bloom is ignoring it, you can delete it if you don't want it" and the delete button?

If we DO, then this new logic is not needed. If we DON'T, see the comment below.
___
*[`src/BloomExe/Book/AppearanceSettings.cs` line 843 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-Np_bQ8D12LRwhcNm_al:-Np_bQ8D12LRwhcNm_am:bpplj18) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8ac03a74f218b3905fd183afbea95100322e89d/src/BloomExe/Book/AppearanceSettings.cs#L843)):*
> ```Smalltalk
>                 // (We want to keep it around for backwards compatibility with earlier versions of Bloom.)
>                 return null;
>             }
> ```

I don't think we want these exceptions. If we recognize the customCss as something we know how to migrate, I think that's enough to assume we did. I would expect that some of our smart migrations of customStyles would migrate to default + customBookStyles2.css, and I don't see why those should be different from any other smart migration.
I would also expect that some migrations are implemented entirely in a custom theme, and no customBookSyles2.css is needed.
So I don't think either default them or absence of customBookStyles2.css should be a special case.
___
*[`src/content/appearanceThemes/appearance-theme-efl-ebook-2.css` line 12 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRTw0b-bwvfaVUrXKP:-Np_go1E2jU1sAuoHBp9:b627krd) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/content/appearanceThemes/appearance-theme-efl-ebook-2.css#L12)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Done. I moved this to the replacement custom CSS file to maintain migration compatibility.
</blockquote></details>

I'm not following JohnH's comment. We already have heaps of xmatter variables (cover margins, cover title languages, showing language and topic on the cover). Wouldn't another variable to control displaying the credits row be consistent?

**Review by hatton — COMMENTED** [review]
> Reviewed 1 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271)* status: 1 of 14 files reviewed, 9 unresolved discussions (waiting on @JohnThomson and @StephenMcConnel)

___
*[`src/BloomExe/Book/AppearanceSettings.cs` line 836 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRVJly6DUBZj2ZQwhi:-NpaqLzUAjz3olsU7wOZ:b-d1868i) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/BloomExe/Book/AppearanceSettings.cs#L836)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

@hatton This is first a UI question. When we have done a smart migration (that is, what's in customBookStyles.css was recognized, and we know how to pick a theme and possibly customBookStyles2.css to make it look good in appearance), do we still want the message that "customBookStyles.css is incompatible with modern themes, Bloom is ignoring it, you can delete it if you don't want it" and the delete button?

If we DO, then this new logic is not needed. If we DON'T, see the comment below.
</blockquote></details>

I don't know, let's talk about it

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271)* status: 1 of 15 files reviewed, 9 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`src/BloomExe/Book/AppearanceSettings.cs` line 843 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-Np_bQ8D12LRwhcNm_al:-Npassz_4A1c_UeaX8LV:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8ac03a74f218b3905fd183afbea95100322e89d/src/BloomExe/Book/AppearanceSettings.cs#L843)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't think we want these exceptions. If we recognize the customCss as something we know how to migrate, I think that's enough to assume we did. I would expect that some of our smart migrations of customStyles would migrate to default + customBookStyles2.css, and I don't see why those should be different from any other smart migration.
I would also expect that some migrations are implemented entirely in a custom theme, and no customBookSyles2.css is needed.
So I don't think either default them or absence of customBookStyles2.css should be a special case.
</blockquote></details>

Done.
___
*[`src/content/appearanceThemes/appearance-theme-efl-ebook-2.css` line 12 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRTw0b-bwvfaVUrXKP:-Npaj3VCALoLjsMOLT8v:b7ssw3n) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/content/appearanceThemes/appearance-theme-efl-ebook-2.css#L12)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm not following JohnH's comment. We already have heaps of xmatter variables (cover margins, cover title languages, showing language and topic on the cover). Wouldn't another variable to control displaying the credits row be consistent?
</blockquote></details>

I left the creditsRow hiding logic in the customBookStyles2.css files but changed to using a variable defined in appearance-theme-default.css and used in basePage.less.

**Review by JohnThomson — APPROVED** [review]
LGTM, but need to talk with JohnH about whether to show the customBookStyles problem message when we've done this kind of migration.

> Reviewed 4 of 12 files at r1, 5 of 10 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-:-NpeDvq235EPaO242IA5:b4gn5oc)* status: all files reviewed, 8 unresolved discussions (waiting on @hatton and @StephenMcConnel)

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnThomson and @StephenMcConnel)

___
*[`src/content/appearanceThemes/appearance-theme-efl-ebook-2.css` line 12 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRTw0b-bwvfaVUrXKP:-NpzOWBO8umjdOciiDm8:bgkupzi) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/content/appearanceThemes/appearance-theme-efl-ebook-2.css#L12)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I left the creditsRow hiding logic in the customBookStyles2.css files but changed to using a variable defined in appearance-theme-default.css and used in basePage.less.
</blockquote></details>

@JohnThomson your comment is talking about appearance in general having controls for the xmatter.  However my comment was only about themes, which are not being targetted at the full scope of what Appearance can do. Does that make sense?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271)* status: 14 of 20 files reviewed, 3 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`src/BloomExe/Book/AppearanceSettings.cs` line 836 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRVJly6DUBZj2ZQwhi:-Nq-vLeQ9lRBYBETjuvE:b-9g5e5k) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/BloomExe/Book/AppearanceSettings.cs#L836)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I don't know, let's talk about it
</blockquote></details>

Done.  Ie, we chatted earlier today on zulip and I think I've fixed things in accordance with the decision we came to
___
*[`src/content/appearanceThemes/appearance-theme-efl-ebook-2.css` line 12 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRTw0b-bwvfaVUrXKP:-Nq-v_n22xhhBERMxHG2:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/content/appearanceThemes/appearance-theme-efl-ebook-2.css#L12)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

@JohnThomson your comment is talking about appearance in general having controls for the xmatter.  However my comment was only about themes, which are not being targetted at the full scope of what Appearance can do. Does that make sense?
</blockquote></details>

Done.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
Most of the new changes are to support offering to delete customCollectionStyles.css if that is the problem CSS file that we are ignoring (and possibly have replaced with a custom theme). Did we agree to do that at some point? My thinking is that it is too dangerous...this book may be OK without it, but has the user checked all the other books in the collection? Moreover, unless ALL the other books in the collection have been migrated, once customCollectionStyles.css is gone, we won't even be able to look at it and use it to figure out which migration to use, or to detect that we can't safely migrate, if some books have conflicting customBookStyles.css as well. (It was not just an oversight that I didn't implement the delete button for customCollectionStyles.css!)

> Reviewed 2 of 6 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-:-Nq3iN2L76040wyv87Aj:bgnmtcp)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[`src/content/appearanceThemes/appearance-theme-efl-ebook-2.css` line 12 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRTw0b-bwvfaVUrXKP:-Nq-PP57DEMzZyxeWlXd:bprd3ey) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/content/appearanceThemes/appearance-theme-efl-ebook-2.css#L12)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

@JohnThomson your comment is talking about appearance in general having controls for the xmatter.  However my comment was only about themes, which are not being targetted at the full scope of what Appearance can do. Does that make sense?
</blockquote></details>

It makes sense that theme variables might be a subset of appearance ones, though it is news to me...I had thought the eventual idea was that all these variables could be controlled by theme or by the book settings dialog, once we built out the UI. I'd like to understand better your thinking on on what, in the long run, belongs in themes, what belongs in the dialog, what should be determined by xmatter and/or branding, what is just a variable for more manageable control by custom CSS, and whether we ever expect them to overlap.
But surely page numbers IS an interior aspect? Xmatter pages don't have them.

**Review by StephenMcConnel — COMMENTED** [review]
OK, I've removed the checks for customCollectionStyles.css.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-:-Nq3leDW3zjph6VlDkDf:b-klahiv)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[`src/content/appearanceThemes/appearance-theme-efl-ebook-2.css` line 12 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRTw0b-bwvfaVUrXKP:-Nq3kqHZ7MU3-rcnmuoF:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/content/appearanceThemes/appearance-theme-efl-ebook-2.css#L12)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It makes sense that theme variables might be a subset of appearance ones, though it is news to me...I had thought the eventual idea was that all these variables could be controlled by theme or by the book settings dialog, once we built out the UI. I'd like to understand better your thinking on on what, in the long run, belongs in themes, what belongs in the dialog, what should be determined by xmatter and/or branding, what is just a variable for more manageable control by custom CSS, and whether we ever expect them to overlap.
But surely page numbers IS an interior aspect? Xmatter pages don't have them.
</blockquote></details>

Done.

**Review by JohnThomson — COMMENTED** [review]
I don't see the removal. Some changes might legitmately remain, to show which is the conflicting file, but for example the delete button is still Delete  {firstPossiblyLegacyCss}

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-:-Nq48kv43RdJqAu_3Sn3:b-ls3bad)* status: 18 of 20 files reviewed, 3 unresolved discussions (waiting on @hatton)

**Review by StephenMcConnel — COMMENTED** [review]
Yes, after a test that explicitly checks that it's equal to customBookFolder.css

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-:-Nq4tnQa1rMu_EJSFLfR:b13p5fw)* status: 18 of 20 files reviewed, 3 unresolved discussions (waiting on @hatton and @JohnThomson)

**Review by JohnThomson — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton)

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/content/appearanceThemes/appearance-theme-efl-ebook-3.css` line 17 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRUVJUDpYqsbEyH6au:-Nq8YlDt4zCZt9BYqJpf:b-41fpp8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/content/appearanceThemes/appearance-theme-efl-ebook-3.css#L17)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

The default page margins for Device16x9Landscape is 10px, which computes to about 2.65mm for all pages except the numbered pages where the bottom margin is 45px.  I imagine the desire was to have the page margins be the same on all the non-interactive pages.
</blockquote></details>

We discussed and agreed to remove them

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271)* status: all files reviewed, 1 unresolved discussion

___
*[`src/content/appearanceThemes/appearance-theme-efl-ebook-3.css` line 17 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271#-NpRUVJUDpYqsbEyH6au:-Nq8hgqz0DAUTrOAXqW7:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b8dacc9b9bf04a6712adadd521cd60dc90f00905/src/content/appearanceThemes/appearance-theme-efl-ebook-3.css#L17)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

We discussed and agreed to remove them
</blockquote></details>

Done.

**Pull request merged**
