### PR TITLE
BL-6901, make next/prev buttons like Readium and optional

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3036)

### CODE REVIEW

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3036)* status: 0 of 5 files reviewed, 1 unresolved discussion

___
*[src/BloomBrowserUI/publish/previewCommon.less, line 71 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3036#-LZBY5NM3GeplTlt35C2:-LZBY5NM3GeplTlt35C3:bms8r8z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e46500a1165f696b94f7f7716ba3bdeb430c23a6/src/BloomBrowserUI/publish/previewCommon.less#L71)):*
> ```Less
> // First two conditions added for specificity
> html.publishTabScreen .preview-section {
>     // these buttons are positioned relative to the slider, our preview.
> ```

The positioning of these buttons (now more complex) really belongs in the bloom-player less file.

**Review by jsubloom — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3036)* status: all files reviewed, 1 unresolved discussion

**Review by jsubloom — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3036)* status: all files reviewed, 1 unresolved discussion

**Review by jsubloom — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3036)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Pull request merged**
