### PR TITLE
Remove locked/unlocked (translation/original) behavior (BL-11864)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5586)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 32 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5586)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 819 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5586#-NMF_Y9U7OghkveIvM-0:-NMF_Y9V9Nr7MAoFDZQu:b4vo19c) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6eb7d1838d7b1a37b6e8317dce2df18eff3577fb/src/BloomBrowserUI/bookEdit/css/editMode.less#L819)):*
> ```Less
>     /*border: transparent; /* jscript will translate to read only*/
>     cursor: pointer;
>     /*this signals to jscript that in this mode, when the user clicks on this div, it should raise the message in data-message (which bloom will catch)*/
> ```

These comments about "in this mode" are now obsolete and confusing.
(and is this even used anymore?)
___
*[`src/BloomBrowserUI/bookEdit/css/editPaneGlobal.less` line 88 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5586#-NMFa3j0CeWKnh2HQZhM:-NMFa3j0CeWKnh2HQZhN:b3y3b3a) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/37bf318b9af3e726987104f2ec5cc1a4ba40a49b/src/BloomBrowserUI/bookEdit/css/editPaneGlobal.less#L88)):*
> ```Less
>     border: none;
>     overflow: hidden auto; // we never want a horizontal scroll bar in source bubbles
> }
> ```

I'm not understanding why we don't still need some of the rules which were removed from this file.
___
*[`src/BloomExe/Edit/EditingModel.cs` line 380 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5586#-NMFUQ36AXofd8OxNzYf:-NMFUQ386If4Z5bN2-xi:bqa2nhu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/37bf318b9af3e726987104f2ec5cc1a4ba40a49b/src/BloomExe/Edit/EditingModel.cs#L380)):*
> ```Smalltalk
> 		public bool CanAddPages
> 		{
> 			get { return !(CurrentBook.LockedDown || CurrentBook.IsCalendar); }
> ```

How are we locking down Add Page (and paste, etc) for calendars now?



_Code quote:_
```Smalltalk
CurrentBook.IsCalendar
```

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5586)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 819 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5586#-NMF_Y9U7OghkveIvM-0:-NMFwRaPEmTyowoTZvte:b-vrxzf1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6eb7d1838d7b1a37b6e8317dce2df18eff3577fb/src/BloomBrowserUI/bookEdit/css/editMode.less#L819)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

These comments about "in this mode" are now obsolete and confusing.
(and is this even used anymore?)
</blockquote></details>

I took out the "in this mode" but I'm not sure whether it is still used
___
*[`src/BloomBrowserUI/bookEdit/css/editPaneGlobal.less` line 88 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5586#-NMFa3j0CeWKnh2HQZhM:-NMFwY9K2Ap0JrKglj4u:b-c3asgr) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/37bf318b9af3e726987104f2ec5cc1a4ba40a49b/src/BloomBrowserUI/bookEdit/css/editPaneGlobal.less#L88)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not understanding why we don't still need some of the rules which were removed from this file.
</blockquote></details>

I could be wrong. Here's the rough path I took as near as I remember:
1. All these rules are something to do with sourceBubbles, based on the other classes they use, and that I could only find these classes mentioned in source bubble code, if at all.
2. We've had no complaints of sourceBubbles behaving strangely when a book is unlocked (or locked)
3. Visually, I could detect no difference in a sourceBubble when I used debug tools to switch page between original and translation mode
4. As I examined the HTML produced for a source bubble, many of the rules simply didn't match anything. I could never find an element they applied to so as to test their effect.
5. The others didn't change anything: nothing happened as I turned things on and off. In particular, I couldn't find any circumstances, even with long source bubble content and a narrow screen, where a source bubble got a horizontal scroll bar, even without that rule.
6. JohnH said something to the effect "they don't do anything to source bubbles"
7. I can think of no reason for source bubbles to be different when a book is unlocked. If these rules did do something, I think it would be a bug. For example, why would we want source bubbles to have horizontal scroll bars in locked books but not in unlocked ones??
But it's confusing. There must have been a purpose to them once, but someone didn't bother to document it. I think I started to track them down in Git, but got stuck where a whole lot of stuff was moved from one file to another, and went back to investigating what they actually did.
___
*[`src/BloomExe/Edit/EditingModel.cs` line 380 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5586#-NMFUQ36AXofd8OxNzYf:-NMFw3pM8Ri6BZCa6pAv:b-bvf9g2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/37bf318b9af3e726987104f2ec5cc1a4ba40a49b/src/BloomExe/Edit/EditingModel.cs#L380)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

How are we locking down Add Page (and paste, etc) for calendars now?
</blockquote></details>

I was too eager. EditingModel.CanAddPages and uses of it now restored (but only depends on IsCalendar)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5586)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/css/editPaneGlobal.less` line 88 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5586#-NMFa3j0CeWKnh2HQZhM:-NMG4OhHAVh_ue8N-Jcv:b-ogkzv3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/37bf318b9af3e726987104f2ec5cc1a4ba40a49b/src/BloomBrowserUI/bookEdit/css/editPaneGlobal.less#L88)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I could be wrong. Here's the rough path I took as near as I remember:
1. All these rules are something to do with sourceBubbles, based on the other classes they use, and that I could only find these classes mentioned in source bubble code, if at all.
2. We've had no complaints of sourceBubbles behaving strangely when a book is unlocked (or locked)
3. Visually, I could detect no difference in a sourceBubble when I used debug tools to switch page between original and translation mode
4. As I examined the HTML produced for a source bubble, many of the rules simply didn't match anything. I could never find an element they applied to so as to test their effect.
5. The others didn't change anything: nothing happened as I turned things on and off. In particular, I couldn't find any circumstances, even with long source bubble content and a narrow screen, where a source bubble got a horizontal scroll bar, even without that rule.
6. JohnH said something to the effect "they don't do anything to source bubbles"
7. I can think of no reason for source bubbles to be different when a book is unlocked. If these rules did do something, I think it would be a bug. For example, why would we want source bubbles to have horizontal scroll bars in locked books but not in unlocked ones??
But it's confusing. There must have been a purpose to them once, but someone didn't bother to document it. I think I started to track them down in Git, but got stuck where a whole lot of stuff was moved from one file to another, and went back to investigating what they actually did.
</blockquote></details>

Thanks.
I guess I was just thinking we probably needed to keep one set or the other.
But I'm trusting your analysis.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5586)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/Book.cs` line 888 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5586#-NMG7LltCNioPmStL92T:-NMG7Llu5fUwQNUy_Y3V:bwgz3b5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/97f9468952f2433cf8768451522179c714968b18/src/BloomExe/Book/Book.cs#L888)):*
> ```Smalltalk
> 		{
> 			htmlDom.AddCreationType(LockedDown ? "translation" : "original");
> 		}
> ```

Looks like the rebase accidentally re-added this method.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5586)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
