### PR TITLE
Add ability to push books via USB/MTP to Android (BL-4648)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1729)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[Bloom.sln, line 75 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KntdzkyYIsV4GGmm7KY:-KntdzkyYIsV4GGmm7KZ:b-keqsv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b2c8266fecb8e71d2f5eeea18c804ab5c86dc133/Bloom.sln#L75)):*
> ```
> 		{5B04DA06-782F-41B8-84FB-EA1AB82E3FB0}.Release|Mixed Platforms.ActiveCfg = Release|x86
> 		{5B04DA06-782F-41B8-84FB-EA1AB82E3FB0}.Release|x86.ActiveCfg = Release|x86
> 		{5B04DA06-782F-41B8-84FB-EA1AB82E3FB0}.Release|x86.Build.0 = Release|x86
> ```

I'm not sure why these went away (or what they used to be for) or what it has to do with this PR.

---

*[src/BloomExe/Communication/AndroidDeviceConnection.cs, line 10 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KntenLoOUoRfFAVFjVX:-KntenLoOUoRfFAVFjVY:b-k0cs5k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6baf11f79c6eee2a798eb3d04391da375da4a502/src/BloomExe/Communication/AndroidDeviceConnection.cs#L10)):*
> ```Smalltalk
> namespace Bloom.Communication
> {
> 	class AndroidDeviceConnection
> ```

Wants a class comment.

---

*[src/BloomExe/Communication/AndroidDeviceConnection.cs, line 12 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-Kntf5_MGYTqRv-6miMM:-Kntf5_MGYTqRv-6miMN:b-ra5clq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6baf11f79c6eee2a798eb3d04391da375da4a502/src/BloomExe/Communication/AndroidDeviceConnection.cs#L12)):*
> ```Smalltalk
> 	class AndroidDeviceConnection
> 	{
> 		private const string kBloomFolder = "Bloom";
> ```

On the device? Or on the desktop? If the latter we already have constants etc for finding Bloom's folder.

---

*[src/BloomExe/Communication/AndroidDeviceConnection.cs, line 37 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KntgXRMWdORRX-sqGLc:-KntgXRMWdORRX-sqGLd:b-jlbd9h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6baf11f79c6eee2a798eb3d04391da375da4a502/src/BloomExe/Communication/AndroidDeviceConnection.cs#L37)):*
> ```Smalltalk
> 			_device = GetOneDevice(devices);
> 
> 			return _device != null;
> ```

Should we continue the timeout loop if none of the current devices has Bloom Reader?

---

*[src/BloomExe/Communication/AndroidDeviceConnection.cs, line 50 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KntfYcSksMzp8CwwbrV:-KntfYcSksMzp8CwwbrW:byhqx9x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6baf11f79c6eee2a798eb3d04391da375da4a502/src/BloomExe/Communication/AndroidDeviceConnection.cs#L50)):*
> ```Smalltalk
> 		public void SendBook(string bloomdPath)
> 		{
> 			if (_device == null)
> ```

Odd that you check for _bloomFolderPath above but not here

---

*[src/BloomExe/Communication/AndroidDeviceConnection.cs, line 108 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KntgqtPnDg77CKQFnCh:-KntgqtPnDg77CKQFnCi:bwet0ji) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6baf11f79c6eee2a798eb3d04391da375da4a502/src/BloomExe/Communication/AndroidDeviceConnection.cs#L108)):*
> ```Smalltalk
> 					if (theOneDevice != null)
> 						throw new ApplicationException(L10NSharp.LocalizationManager.GetString(
> 							"Publish.ReaderBookPublisher.MoreThanOneDevice", "More than one Android device with Bloom Reader is connected"));
> ```

You'll have to build some UI to handle this exception...I wonder whether it would be easier to just push to all of them? Could be quite useful to someone with a big USB hub trying to give a textbook to a large class of students. It doesn't seem very likely to me that someone accidentally connected more than one device that has BloomReader, or very harmful to push a book to an unintended one.

---

*[src/BloomExe/Communication/AndroidDeviceConnection.cs, line 119 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KntgJrqRoFlcrffoPNQ:-KntgJrqRoFlcrffoPNR:bmksoku) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6baf11f79c6eee2a798eb3d04391da375da4a502/src/BloomExe/Communication/AndroidDeviceConnection.cs#L119)):*
> ```Smalltalk
> 			foreach (var rso in device.GetDeviceRootStorageObjects())
> 			{
> 				if (rso.GetFolders(kBloomFolder).Any())
> ```

This seems an odd API to use to check whether a single folder exists...I suppose the device API doesn't have a DirectoryExists method?

---

*[src/BloomExe/Publish/ReaderBookPublisher.cs, line 49 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KntiNFel8AqVOX_aiWs:-KntiNFel8AqVOX_aiWt:b50206z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6baf11f79c6eee2a798eb3d04391da375da4a502/src/BloomExe/Publish/ReaderBookPublisher.cs#L49)):*
> ```Smalltalk
> 			catch (Exception e)
> 			{
> 				_progress.WriteError(unableToConnectMessage);
> ```

If the problem was two devices plugged in, we should let the user know that.

---

*[src/BloomExe/Publish/ReaderBookPublisher.cs, line 75 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-Kntilu6QUd3coFB30JC:-Kntilu6QUd3coFB30JD:b4ynnxt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6baf11f79c6eee2a798eb3d04391da375da4a502/src/BloomExe/Publish/ReaderBookPublisher.cs#L75)):*
> ```Smalltalk
> 				var bloomdPath = BookCompressor.CompressBookForDevice(book);
> 
> 				if (bookExistsOnDevice)
> ```

Probably not for MVP, but it would be nice to detect if we are replacing a newer version with an older one and provide a chance to cancel.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/BloomExe/Publish/ReaderBookPublisher.cs, line 75 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-Kntilu6QUd3coFB30JC:-Kntna1jIDooUTqPY_Xb:b-2cn3sj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6baf11f79c6eee2a798eb3d04391da375da4a502/src/BloomExe/Publish/ReaderBookPublisher.cs#L75)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Probably not for MVP, but it would be nice to detect if we are replacing a newer version with an older one and provide a chance to cancel.
</blockquote></details>

Detect and print to progress:yes, ask: no.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/BloomExe/Communication/AndroidDeviceConnection.cs, line 108 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KntgqtPnDg77CKQFnCh:-KntnybREdmgxa_bSHgk:b-ykhimv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6baf11f79c6eee2a798eb3d04391da375da4a502/src/BloomExe/Communication/AndroidDeviceConnection.cs#L108)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

You'll have to build some UI to handle this exception...I wonder whether it would be easier to just push to all of them? Could be quite useful to someone with a big USB hub trying to give a textbook to a large class of students. It doesn't seem very likely to me that someone accidentally connected more than one device that has BloomReader, or very harmful to push a book to an unintended one.
</blockquote></details>

Design decision was to make them remove all but one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/BloomExe/Communication/AndroidDeviceConnection.cs, line 108 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KntgqtPnDg77CKQFnCh:-Knu4YZkN2k5Qvsbo-Nx:bvmrc4k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6baf11f79c6eee2a798eb3d04391da375da4a502/src/BloomExe/Communication/AndroidDeviceConnection.cs#L108)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Design decision was to make them remove all but one.
</blockquote></details>

In Flowdock you stated, "Complain and don't do anything," which is what I have implemented. But I am happy to change it if the design changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/BloomExe/Communication/AndroidDeviceConnection.cs, line 108 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KntgqtPnDg77CKQFnCh:-Knu4z5V4v41wkDsg1LG:b7s3tyj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6baf11f79c6eee2a798eb3d04391da375da4a502/src/BloomExe/Communication/AndroidDeviceConnection.cs#L108)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

In Flowdock you stated, "Complain and don't do anything," which is what I have implemented. But I am happy to change it if the design changed.
</blockquote></details>

Oh, I see now that I misinterpreted. "Complain and don't do anything" was supposed to mean wait until they unplug down to one whereas I made a failure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[Bloom.sln, line 75 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KntdzkyYIsV4GGmm7KY:-Knu9SI_SaKKbumcAd4z:b-c208k7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b2c8266fecb8e71d2f5eeea18c804ab5c86dc133/Bloom.sln#L75)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm not sure why these went away (or what they used to be for) or what it has to do with this PR.
</blockquote></details>

Prevents Chorus project from building. But not related to this PR. I'll do it separately.

---

*[src/BloomExe/Communication/AndroidDeviceConnection.cs, line 37 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KntgXRMWdORRX-sqGLc:-Knu5fgjrr4QGF-iph72:b-fq6rav) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6baf11f79c6eee2a798eb3d04391da375da4a502/src/BloomExe/Communication/AndroidDeviceConnection.cs#L37)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Should we continue the timeout loop if none of the current devices has Bloom Reader?
</blockquote></details>

Yes, I suppose there is no reason to timeout.

---

*[src/BloomExe/Publish/ReaderBookPublisher.cs, line 49 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KntiNFel8AqVOX_aiWs:-Knu9eshEJt65qlAUTw5:b8s081x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6baf11f79c6eee2a798eb3d04391da375da4a502/src/BloomExe/Publish/ReaderBookPublisher.cs#L49)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

If the problem was two devices plugged in, we should let the user know that.
</blockquote></details>

Handled by the ApplicationException above. But this is all being reworked now...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729)*

**Comment by andrew-polk** [comment]
Review status: 5 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/BloomExe/Communication/AndroidDeviceConnection.cs, line 10 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KntenLoOUoRfFAVFjVX:-KnuUyu5adfugRAh7fFX:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6baf11f79c6eee2a798eb3d04391da375da4a502/src/BloomExe/Communication/AndroidDeviceConnection.cs#L10)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Wants a class comment.
</blockquote></details>

Done.

---

*[src/BloomExe/Communication/AndroidDeviceConnection.cs, line 12 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-Kntf5_MGYTqRv-6miMM:-KnuV-3mpumeHlr3xLLG:bubkiz5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6baf11f79c6eee2a798eb3d04391da375da4a502/src/BloomExe/Communication/AndroidDeviceConnection.cs#L12)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

On the device? Or on the desktop? If the latter we already have constants etc for finding Bloom's folder.
</blockquote></details>

Improved

---

*[src/BloomExe/Communication/AndroidDeviceConnection.cs, line 50 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KntfYcSksMzp8CwwbrV:-KnuV0fOkMsfmIQw6Bd4:bubkiz5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6baf11f79c6eee2a798eb3d04391da375da4a502/src/BloomExe/Communication/AndroidDeviceConnection.cs#L50)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Odd that you check for _bloomFolderPath above but not here
</blockquote></details>

Improved

---

*[src/BloomExe/Communication/AndroidDeviceConnection.cs, line 108 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KntgqtPnDg77CKQFnCh:-KnuV3wjNSxiB7-8XcCX:bubkiz5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6baf11f79c6eee2a798eb3d04391da375da4a502/src/BloomExe/Communication/AndroidDeviceConnection.cs#L108)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Oh, I see now that I misinterpreted. "Complain and don't do anything" was supposed to mean wait until they unplug down to one whereas I made a failure.
</blockquote></details>

Improved

---

*[src/BloomExe/Communication/AndroidDeviceConnection.cs, line 119 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KntgJrqRoFlcrffoPNQ:-KnuUuaCW8elFKKyyS0Y:bgk7mm5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6baf11f79c6eee2a798eb3d04391da375da4a502/src/BloomExe/Communication/AndroidDeviceConnection.cs#L119)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This seems an odd API to use to check whether a single folder exists...I suppose the device API doesn't have a DirectoryExists method?
</blockquote></details>

Improved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729)*

**Comment by andrew-polk** [comment]
Review status: 4 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/BloomExe/Communication/AndroidDeviceConnection.cs, line 37 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KntgXRMWdORRX-sqGLc:-Knuf0dB23oNWHieqJ1_:brwh7ko) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6baf11f79c6eee2a798eb3d04391da375da4a502/src/BloomExe/Communication/AndroidDeviceConnection.cs#L37)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Yes, I suppose there is no reason to timeout.
</blockquote></details>

Oh, I see I misunderstood your original question. But not this has all been reworked. No timeout anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729)*

**Comment by JohnThomson** [comment]
Few very minor things...feel free to merge with or without improvement.

---

Review status: 4 of 6 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/BloomExe/Communication/AndroidDeviceConnection.cs, line 11 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KoJW73vvHWGeySb-33H:-KoJW73vvHWGeySb-33I:bqnpw3m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/93fa6ae578a23ef70db8dcbc584ec76fb4c973c8/src/BloomExe/Communication/AndroidDeviceConnection.cs#L11)):*
> ```Smalltalk
> {
> 	/// <summary>
> 	/// Handles non-UI functions of connecting to an Android device and working with the file system there
> ```

Does it handle both approaches or just USB?

---

*[src/BloomExe/Communication/AndroidDeviceConnection.cs, line 16 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KoJXrRcJUhaRA2E7NNJ:-KoJXrRcJUhaRA2E7NNK:b-wwlcox) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/93fa6ae578a23ef70db8dcbc584ec76fb4c973c8/src/BloomExe/Communication/AndroidDeviceConnection.cs#L16)):*
> ```Smalltalk
> 	{
> 		public event EventHandler OneApplicableDeviceFound;
> 		public event EventHandler<List<string>> MoreThanOneApplicableDeviceFound;
> ```

It is conventional (but apparently not required) for the type argument of EventHandler to inherit from EventArgs. 

---

*[src/BloomExe/Communication/AndroidDeviceConnection.cs, line 117 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KoJWvK6UfPfG7JJZKqx:-KoJWvK6UfPfG7JJZKqy:bqfp95o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/93fa6ae578a23ef70db8dcbc584ec76fb4c973c8/src/BloomExe/Communication/AndroidDeviceConnection.cs#L117)):*
> ```Smalltalk
> 				_device = applicableDevices[0];
> 				EventHandler handler = OneApplicableDeviceFound;
> 				handler?.Invoke(this, null);
> ```

I've never known why, but it's usual to pass a new, empty EventArgs...or your subclass...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-:-KoJZ_XEL6YpcPJtKifa:blbti91)*

**Comment by JohnThomson** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729)*

**Comment by andrew-polk** [comment]
Review status: 3 of 6 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/BloomExe/Communication/AndroidDeviceUsbConnection.cs, line 16 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KoJXrRcJUhaRA2E7NNJ:-KoMqHDJOOi7W6K1Ns42:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/93fa6ae578a23ef70db8dcbc584ec76fb4c973c8/src/BloomExe/Communication/AndroidDeviceUsbConnection.cs#L16)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It is conventional (but apparently not required) for the type argument of EventHandler to inherit from EventArgs. 
</blockquote></details>

Done.

---

*[src/BloomExe/Communication/AndroidDeviceUsbConnection.cs, line 117 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KoJWvK6UfPfG7JJZKqx:-KoMqHxt6coF0OYexUQ-:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/93fa6ae578a23ef70db8dcbc584ec76fb4c973c8/src/BloomExe/Communication/AndroidDeviceUsbConnection.cs#L117)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I've never known why, but it's usual to pass a new, empty EventArgs...or your subclass...
</blockquote></details>

Done.

---

*[src/BloomExe/Communication/AndroidDeviceConnection.cs, line 11 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729#-KoJW73vvHWGeySb-33H:-KoMqFUHv-nvu2FpI6cu:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/93fa6ae578a23ef70db8dcbc584ec76fb4c973c8/src/BloomExe/Communication/AndroidDeviceConnection.cs#L11)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Does it handle both approaches or just USB?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1729)*

**Pull request merged**
