### PR TITLE
BL-5986 Improve ITool Interface

### PR DESCRIPTION
**Pull request by gmartin7**
* 1st commit is mostly cleanup, and a bit of using newPageReady()
* 2nd commit adds detachFromPage() to ITool interface

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2412)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 175 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2412#-LCkByph4ZIXbtDFBN59:-LCkByph4ZIXbtDFBN5A:b-5kixr8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a0ef07a0cfb2209f25802f8d4b3663f5092a3aab/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L175)):*
> ```XML
> 
>     public hideTool() {
>         this.detachFromPage();
> ```

Doesn't the core code call both, when the tool is going away? If so, this will get the task done twice.

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 182 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2412#-LCkCH7V6Iw97CKNxGiJ:-LCkCH7V6Iw97CKNxGiK:b3vzrca) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a0ef07a0cfb2209f25802f8d4b3663f5092a3aab/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L182)):*
> ```XML
>     }
> 
>     public updateMarkup() {
> ```

Is there a base-class method you can just not override?

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 199 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2412#-LCkCPvZ2vYjNbrdaQmx:-LCkCPvZ2vYjNbrdaQmy:b-f6eoku) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a0ef07a0cfb2209f25802f8d4b3663f5092a3aab/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L199)):*
> ```XML
>     private descriptionGotFocus = (e: Event) => this.reactControls.selectImageDescription(e.currentTarget as Element);
> 
>     // Update image descriptions, not on every edit, but whenever a new page is displayed.
> ```

We're not really updating the descriptions. We're making sure the page has the elements used to store them.

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 201 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2412#-LCkCaEiCuNSvRxcQpNH:-LCkCaEiCuNSvRxcQpNI:b-ssk0lb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a0ef07a0cfb2209f25802f8d4b3663f5092a3aab/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L201)):*
> ```XML
>     // Update image descriptions, not on every edit, but whenever a new page is displayed.
>     public newPageReady() {
>         this.reactControls.checkForChangePage();
> ```

This method might want a new name and maybe could be simplified? Is it still ever called when there's any doubt about whether we changed page?

---

*[src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx, line 252 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2412#-LCkCtgiD82PHtQxpTqO:-LCkCtgiD82PHtQxpTqP:bxbchcr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a0ef07a0cfb2209f25802f8d4b3663f5092a3aab/src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx#L252)):*
> ```XML
> 
>     public updateMarkup() {
>         // nothing to do here.
> ```

So omit override?

---

*[src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx, line 256 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2412#-LCkCpKz0oSkJH6EnNWG:-LCkCpKz0oSkJH6EnNWH:b8gsyu4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a0ef07a0cfb2209f25802f8d4b3663f5092a3aab/src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx#L256)):*
> ```XML
> 
>     public showTool() {
>         this.newPageReady();
> ```

Again, I'm surprised the core code doesn't handle this.

---

*[src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx, line 260 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2412#-LCkD1ZJ7WWKU2AIJPkC:-LCkD1ZJ7WWKU2AIJPkD:bsibyno) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a0ef07a0cfb2209f25802f8d4b3663f5092a3aab/src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx#L260)):*
> ```XML
> 
>     public hideTool() {
>         this.detachFromPage();
> ```

As before (and elsewhere)

---

*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts, line 30 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2412#-LCkDRHl5gWVndr2cnS5:-LCkDRHl5gWVndr2cnS6:b-vpwgb8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a0ef07a0cfb2209f25802f8d4b3663f5092a3aab/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts#L30)):*
> ```XML
> 
>     hideTool() {
>         this.detachFromPage();
> ```

Seems nearly everywhere hideTool wants to call detachFromPage. I think it would make sense for whatever calls hideTool to call detachFromPage() first, if that isn't already happening. We're certainly done with this tool manipulating this page if we're about to hide the tool. Similarly, whatever we do to start editing a page with this tool should be done when we show the tool as well as when we switch page, and this should be handled by the caller of showTool...I would think in this case it would be appropriate to call newPageReady after showTool, so it can always assume the tool is set up.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2412)*

**Comment by gmartin7** [comment]
Review status: 7 of 15 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 175 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2412#-LCkByph4ZIXbtDFBN59:-LCo6P69ESWvQp9rDp4S:b-n9ox1x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a0ef07a0cfb2209f25802f8d4b3663f5092a3aab/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L175)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Doesn't the core code call both, when the tool is going away? If so, this will get the task done twice.
</blockquote></details>

It does now. In fact, as now modified, hideTool() doesn't currently do anything, since toolbox.ts always calls detachFromPage() before calling hideTool().
The only difference between them is that detachFromPage() is also called (indirectly through removeToolboxMarkup) whenever C#-land is about to save the page (via EditingModel/View).

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 182 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2412#-LCkCH7V6Iw97CKNxGiJ:-LCnwwLU5z-Xdw7cUIyV:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a0ef07a0cfb2209f25802f8d4b3663f5092a3aab/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L182)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is there a base-class method you can just not override?
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 199 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2412#-LCkCPvZ2vYjNbrdaQmx:-LCo7jhg3wnMVzhb2rLL:b-upb98k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a0ef07a0cfb2209f25802f8d4b3663f5092a3aab/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L199)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We're not really updating the descriptions. We're making sure the page has the elements used to store them.
</blockquote></details>

Done. Updated the comment.

---

*[src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx, line 252 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2412#-LCkCtgiD82PHtQxpTqO:-LCnx2gPB_D3q_-CVOfl:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a0ef07a0cfb2209f25802f8d4b3663f5092a3aab/src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx#L252)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

So omit override?
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx, line 256 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2412#-LCkCpKz0oSkJH6EnNWG:-LCojUtF-69oMpAxMPrj:bsc0k56) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a0ef07a0cfb2209f25802f8d4b3663f5092a3aab/src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx#L256)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Again, I'm surprised the core code doesn't handle this.
</blockquote></details>

does now.

---

*[src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx, line 260 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2412#-LCkD1ZJ7WWKU2AIJPkC:-LCoB27g4PQlN3c13ne8:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a0ef07a0cfb2209f25802f8d4b3663f5092a3aab/src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx#L260)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

As before (and elsewhere)
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts, line 30 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2412#-LCkDRHl5gWVndr2cnS5:-LCojdcOCV2FI0-OVFCv:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a0ef07a0cfb2209f25802f8d4b3663f5092a3aab/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts#L30)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Seems nearly everywhere hideTool wants to call detachFromPage. I think it would make sense for whatever calls hideTool to call detachFromPage() first, if that isn't already happening. We're certainly done with this tool manipulating this page if we're about to hide the tool. Similarly, whatever we do to start editing a page with this tool should be done when we show the tool as well as when we switch page, and this should be handled by the caller of showTool...I would think in this case it would be appropriate to call newPageReady after showTool, so it can always assume the tool is set up.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2412)*

**Comment by gmartin7** [comment]
Review status: 7 of 15 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, line 201 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2412#-LCkCaEiCuNSvRxcQpNH:-LCol0ge4CaGeGRO9QdJ:bqphcv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a0ef07a0cfb2209f25802f8d4b3663f5092a3aab/src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx#L201)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This method might want a new name and maybe could be simplified? Is it still ever called when there's any doubt about whether we changed page?
</blockquote></details>

Changed to setStateForNewPage() and removed the check for a page change, since yes, this only gets called now when the page changes.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2412)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 10 of 11 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2412#-:-LCp4CD3EKcvqkLYWOdL:bnfp4nl)*

**Pull request merged**
