### PR TITLE
Report simplistic font analytics for upload, save pdf, print pdf, save ePUB, and any kind of make bloomPUB

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5380)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5380)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/BloomExe/WebLibraryIntegration/BookUpload.cs` line 590 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5380#-NBPIahy4t8_MCAlnGrS:-NBPIahz4n3mebsKLvin:bugnfsh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0cffff29c989aa0217ae6f4edb1b194171b2b0b/src/BloomExe/WebLibraryIntegration/BookUpload.cs#L590)):*
> ```Smalltalk
> 
> 				var prefix = BookUpload.UseSandboxByDefault ? "dev." : "";
> 				var url = $"https://{prefix}bloomlibrary.org/book/{parseId}"; 
> ```

This part is `BloomLibraryUploadControl.BloomLibraryUrlPrefix`
And you could extract the whole url to common logic with the call in `BloomLibraryUploadControl::ShowIdCollisionDialog()`



_Code quote:_
```Smalltalk
https://{prefix}bloomlibrary.org
```

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5380)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/BloomExe/web/UrlLookup.cs` line 49 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5380#-NBSrt6_9VHVPsVjaQiM:-NBSrt6_9VHVPsVjaQiN:b44p0sh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/804a6cc22b29509bbe2ad84bd9c3d23bca614fcc/src/BloomExe/web/UrlLookup.cs#L49)):*
> ```Smalltalk
> 		public static string BloomLibraryDetailPageUrlFromBookId(string bookId)
> 		{
> 			return BloomLibraryUrlPrefix + "/book/" + bookId;
> ```

Looks good assuming you intended to change the url we display after a successful upload from 
`BloomLibraryUrlPrefix + "/my-books/book/" + bookId`
to
`BloomLibraryUrlPrefix + "/book/" + bookId`

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5380)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/BloomExe/web/UrlLookup.cs` line 49 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5380#-NBSrt6_9VHVPsVjaQiM:-NBSs_UoB9iOYBECn2l8:b2esp64) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/804a6cc22b29509bbe2ad84bd9c3d23bca614fcc/src/BloomExe/web/UrlLookup.cs#L49)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

yeah, I couldn't think of how that made any difference. Can you?
</blockquote></details>

It will give them a breadcrumb for `My Books`

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5380)* status: 8 of 10 files reviewed, all discussions resolved (waiting on @andrew-polk)

___
*[`src/BloomExe/web/UrlLookup.cs` line 49 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5380#-NBSrt6_9VHVPsVjaQiM:-NBSw20H6bVxA6pk6TGe:bm4ypj3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/804a6cc22b29509bbe2ad84bd9c3d23bca614fcc/src/BloomExe/web/UrlLookup.cs#L49)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

It will give them a breadcrumb for `My Books`
</blockquote></details>

OK, fixed

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5380)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hatton)

**Pull request merged**
