### PR TITLE
BL-2905 Keep page description out of Epub

### PR DESCRIPTION
**Pull request by gmartin7**
[Review on Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/864)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Generally, in an epub, we prefer to remove content that should never be seen.  See EpubMaker.RemoveUnwantedContent(), where the comment notes, "Remove stuff that we don't want displayed. Some e-readers don't obey display:none. Also, not shipping it saves space." Any reason this can't be done that way?


---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/864)

**Comment by JohnThomson** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/864)

**Comment by gmartin7** [comment]
Shouldn't be a problem to do it that way, I just didn't know about that. Will look into it.


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/864)

**Comment by JohnThomson** [comment]
That should do it, but this method has unit tests, so it would be appropriate to add one.


---

Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/864)

**Comment by JohnThomson** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[src/BloomTests/Publish/ExportEpubTests.cs, line 526 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/864#-K31MX01e3PsYXy3emaP)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c36f46ff8500867dae1a1701ceb617249a51872d/src/BloomTests/Publish/ExportEpubTests.cs#L526)):</sup>
Sorry to be picky. But
--comments are not the place for a change history. That's what  we have git for.
--This  method is now misnamed. It's checking for more than things which end up display:none. Maybe InvisibleElements_AreRemoved? (If that doesn't overlap with too many other method names).


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/864)

**Comment by JohnThomson** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/864)

**Comment by gmartin7** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[src/BloomTests/Publish/ExportEpubTests.cs, line 526 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/864#-K31MX01e3PsYXy3emaP)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c36f46ff8500867dae1a1701ceb617249a51872d/src/BloomTests/Publish/ExportEpubTests.cs#L526)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/864)

**Comment by gmartin7** [comment]
test added and updated


---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/864)

**Comment by JohnThomson** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/864)

**Pull request merged**
