### PR TITLE
Upgrade registration data before TC needs it (BL-9715)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4313)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4313)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Registration/RegistrationDialog.cs, line 109 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4313#-MWkq0gx0cfvdiJPdUqb:-MWkq0gx0cfvdiJPdUqc:bqc1zou) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/85775c32753e71506ff26e8c3abfb680d40ab7c5/src/BloomExe/Registration/RegistrationDialog.cs#L109)):*
> ```
> 			// Allow registration information to be copied from version to version even if
> 			// the user has set the FEEDBACK environment variable.  If the user does register, or
> ```
At least this part, if not the whole comment (I don't really understand the rest without looking at BL-7956) wants to be back in `ShouldWeShowRegistrationDialog`.
___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 117 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4313#-MWkqJUpDp_Px4Zo8sBR:-MWkqJUpDp_Px4Zo8sBS:b-by5ov2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/85775c32753e71506ff26e8c3abfb680d40ab7c5/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L117)):*
> ```Smalltalk
> 			// This is usually done as part of deciding whether to show the dialog, but deciding
> 			// whether TC has a problem happens earlier than that in startup.
> 			RegistrationDialog.UpgradeRegistrationIfNeeded();
> ```

I don't suppose there is some other common code path where this could be moved higher? Probably not because Autofac is doing this?
It seems odd to have TeamCollectionManager constructor know anything about registration.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4313)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/Registration/RegistrationDialog.cs, line 109 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4313#-MWkq0gx0cfvdiJPdUqb:-MWxphpX-6TmSsKRLICC:b-4ykrcx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/85775c32753e71506ff26e8c3abfb680d40ab7c5/src/BloomExe/Registration/RegistrationDialog.cs#L109)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> 			// Allow registration information to be copied from version to version even if
> 			// the user has set the FEEDBACK environment variable.  If the user does register, or
> ```
At least this part, if not the whole comment (I don't really understand the rest without looking at BL-7956) wants to be back in `ShouldWeShowRegistrationDialog`.
</blockquote></details>

Not following you. The entire comment seems to me to be exactly about upgrading in order to keep the information between versions, and not at all about showing the dialog.
___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 117 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4313#-MWkqJUpDp_Px4Zo8sBR:-MWxpcqW2099pMqsM9GN:b-lg5h1g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/85775c32753e71506ff26e8c3abfb680d40ab7c5/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L117)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't suppose there is some other common code path where this could be moved higher? Probably not because Autofac is doing this?
It seems odd to have TeamCollectionManager constructor know anything about registration.
</blockquote></details>

I think you're right. Decided to do it even before we initialize autofac.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4313)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Registration/RegistrationDialog.cs, line 109 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4313#-MWkq0gx0cfvdiJPdUqb:-MWz3NgjC9RVWiWTkPha:b-8yspy3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/85775c32753e71506ff26e8c3abfb680d40ab7c5/src/BloomExe/Registration/RegistrationDialog.cs#L109)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Not following you. The entire comment seems to me to be exactly about upgrading in order to keep the information between versions, and not at all about showing the dialog.
</blockquote></details>

The comment explains why we need to execute this code even if FEEDBACK is off. That is in regard to an early return in `ShouldWeShowRegistrationDialog`.

But now that you call this so early in Program.Main, do we even need to call it in `ShouldWeShowRegistrationDialog`?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4313)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Registration/RegistrationDialog.cs, line 109 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4313#-MWkq0gx0cfvdiJPdUqb:-MWzbmUc921LKvrFIObV:b29307l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/85775c32753e71506ff26e8c3abfb680d40ab7c5/src/BloomExe/Registration/RegistrationDialog.cs#L109)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The comment explains why we need to execute this code even if FEEDBACK is off. That is in regard to an early return in `ShouldWeShowRegistrationDialog`.

But now that you call this so early in Program.Main, do we even need to call it in `ShouldWeShowRegistrationDialog`?
</blockquote></details>

OK, I guess you're right. I moved it back. Not sure whether to keep the call at all. Seems there might be some safety in making sure any existing info is up to date before deciding whether to launch. so I added a comment and kept it.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4313)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
