### PR TITLE
[4.5]BL-6893 Change Image Description UI

### PR DESCRIPTION
**Pull request by gmartin7**
* checkboxes -> links
* for now each link points to the same page that
   shows all of them.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3026)

### CODE REVIEW

**Comment by gmartin7** [comment]
This one is in Ready for UI review. @hatton

**Comment by JohnThomson** [comment]
Sorry if I shouldn't have merged it.

**Comment by hatton** [comment]
Yeah I don't understand why this went ahead after I said it needs me to come up with the links and content. That's not going to happen for maybe a month.

**Comment by hatton** [comment]
... and thus could end up in 4.6, and we'll want the previous code in 4.5.

**Comment by gmartin7** [comment]
This has been reverted in 4.5, but I'm going to leave this branch available for pulling in later.

**Pull request merged**
