### PR TITLE
Fix memory deltas and for linux 20210315

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4282)

### CODE REVIEW

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4282)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/Utils/PerformanceMeasurement.cs, line 46 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4282#-MVwKZ8k6D9oq81mZ-lF:-MVwKZ8k6D9oq81mZ-lG:b-kfhkd8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b1780fd13f375703682baf88bb598d2a0b157cc9/src/BloomExe/Utils/PerformanceMeasurement.cs#L46)):*
> ```
> Δ Private Bytes KB
> ```
How about changing the header so that we can tell which runs are using which definition of Delta?

e..g append "(since last measured)", etc.
___
*[src/BloomExe/Utils/PerformanceMeasurement.cs, line 106 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4282#-MVwIvcYBLWe5hZJDxSk:-MVwIvcYBLWe5hZJDxSl:bcy70q9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b1780fd13f375703682baf88bb598d2a0b157cc9/src/BloomExe/Utils/PerformanceMeasurement.cs#L106)):*
> ```Smalltalk
> 			if (!CurrentlyMeasuring)
> 				return null;
> 			var previousSize = 0L;
> ```

Optional: Could avoid the temp var and use fewer lines using null coalescing.   
e.g.
var previousSize = _previousMeasurement?.FinalSize ?? 0L;

(IMO, my brain would have an easier time than what the if, but either way is ok.)
___
*[src/BloomExe/Utils/PerformanceMeasurement.cs, line 179 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4282#-MVwI3AW8pZH8Xhj4KS8:-MVwI3AW8pZH8Xhj4KS9:baztfg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b1780fd13f375703682baf88bb598d2a0b157cc9/src/BloomExe/Utils/PerformanceMeasurement.cs#L179)):*
> ```Smalltalk
> 		private long _previousSizeKb;
> 
> 		public long FinalSize
> ```

Optional: If you prefer, I think you can condense this shorter using null-coalescing and optionally expression-modied property.
Something like this: (not sure if you need get somewhere)
public long FinalSize => _end?.privateBytesKb ?? _start.privateBytesKb ?? 0L;
___
*[src/BloomExe/Utils/PerformanceMeasurement.cs, line 179 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4282#-MVwLOlY-UxpgDyH9yN0:-MVwLOlY-UxpgDyH9yN1:b3owhvx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b1780fd13f375703682baf88bb598d2a0b157cc9/src/BloomExe/Utils/PerformanceMeasurement.cs#L179)):*
> ```Smalltalk
> 		private long _previousSizeKb;
> 
> 		public long FinalSize
> ```

I don't think this should be named FinalSize.
Am I understanding this correctly?
So we are calculating the difference since the last time we measured it.  But I guess the problem is that since these calls can be nested, the previous measurement may have already finished, or it may have not. If it hasn't finished yet, you're calculating it based on its start PerfPoint. (I think that seems reasonable).
But, later on this thing will get an _end PerfPoint assigned to.  So, the value returned here is not the "final" size returned, from that point of view.

So... I think this should be called like MostRecentSize or LastKnownSize or something like that?
___
*[src/BloomExe/Utils/PerformanceMeasurement.cs, line 190 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4282#-MVwHPaLEdjQ0KUy8B0k:-MVwHPaLEdjQ0KUy8B0l:b-xfwue5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fe2a9f23736ffc48fe58598581b7c30adac907fb/src/BloomExe/Utils/PerformanceMeasurement.cs#L190)):*
> ```
> _end.privateBytesKb - _start.privateBytesKb)
> ```
The delta is dropped here. I assume that's intentional? Just double-checking.
___
*[src/BloomExe/Utils/PerformanceMeasurement.cs, line 192 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4282#-MVwHZmXDsJpKknb7og1:-MVwHZmXDsJpKknb7og2:btbv7k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b1780fd13f375703682baf88bb598d2a0b157cc9/src/BloomExe/Utils/PerformanceMeasurement.cs#L192)):*
> ```
> previousSize
> ```
How about previousSizeKb so that whoever calls the constructor will have an easier time figuring out what units are expected?
___
*[src/BloomExe/Utils/PerformanceMeasurement.cs, line 214 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4282#-MVwGmuC6aLFyxPZS8K_:-MVwGmuD1ge58MMwIr_z:b-864y8o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b1780fd13f375703682baf88bb598d2a0b157cc9/src/BloomExe/Utils/PerformanceMeasurement.cs#L214)):*
> ```Smalltalk
> 		public override string ToString()
> 		{
> 			var bldr = new System.Text.StringBuilder();
> ```

I think the $"" syntax is better than format strings because you don't have to run your eyes left-to-right and count up indexes and whatnot, but...
even if we used a format string, I think we should just use String.Format directly instead of StringBuilder, since we're not like building up a string in a loop or anything like that. We're able to calculate the string all in one go.

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4282)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/Utils/PerformanceMeasurement.cs, line 179 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4282#-MVwI3AW8pZH8Xhj4KS8:-MVwM9-u4GEukYDCe-9T:b-htqd4f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b1780fd13f375703682baf88bb598d2a0b157cc9/src/BloomExe/Utils/PerformanceMeasurement.cs#L179)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Optional: If you prefer, I think you can condense this shorter using null-coalescing and optionally expression-modied property.
Something like this: (not sure if you need get somewhere)
public long FinalSize => _end?.privateBytesKb ?? _start.privateBytesKb ?? 0L;
</blockquote></details>

expression-bodied*, not expression-modied

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4282)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/Utils/PerformanceMeasurement.cs, line 46 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4282#-MVwKZ8k6D9oq81mZ-lF:-MVwcZ0G1bLqmTKQ5oCG:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b1780fd13f375703682baf88bb598d2a0b157cc9/src/BloomExe/Utils/PerformanceMeasurement.cs#L46)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> Δ Private Bytes KB
> ```
How about changing the header so that we can tell which runs are using which definition of Delta?

e..g append "(since last measured)", etc.
</blockquote></details>

Done.
___
*[src/BloomExe/Utils/PerformanceMeasurement.cs, line 106 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4282#-MVwIvcYBLWe5hZJDxSk:-MVwd8Ic93PVsaoiAt1y:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b1780fd13f375703682baf88bb598d2a0b157cc9/src/BloomExe/Utils/PerformanceMeasurement.cs#L106)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Optional: Could avoid the temp var and use fewer lines using null coalescing.   
e.g.
var previousSize = _previousMeasurement?.FinalSize ?? 0L;

(IMO, my brain would have an easier time than what the if, but either way is ok.)
</blockquote></details>

Done.
___
*[src/BloomExe/Utils/PerformanceMeasurement.cs, line 179 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4282#-MVwI3AW8pZH8Xhj4KS8:-MVwdZvo8M4vy0Oaol8D:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b1780fd13f375703682baf88bb598d2a0b157cc9/src/BloomExe/Utils/PerformanceMeasurement.cs#L179)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

expression-bodied*, not expression-modied
</blockquote></details>

Done.
___
*[src/BloomExe/Utils/PerformanceMeasurement.cs, line 179 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4282#-MVwLOlY-UxpgDyH9yN0:-MVwdt387b1FWr496-4r:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b1780fd13f375703682baf88bb598d2a0b157cc9/src/BloomExe/Utils/PerformanceMeasurement.cs#L179)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I don't think this should be named FinalSize.
Am I understanding this correctly?
So we are calculating the difference since the last time we measured it.  But I guess the problem is that since these calls can be nested, the previous measurement may have already finished, or it may have not. If it hasn't finished yet, you're calculating it based on its start PerfPoint. (I think that seems reasonable).
But, later on this thing will get an _end PerfPoint assigned to.  So, the value returned here is not the "final" size returned, from that point of view.

So... I think this should be called like MostRecentSize or LastKnownSize or something like that?
</blockquote></details>

Done.
___
*[src/BloomExe/Utils/PerformanceMeasurement.cs, line 190 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4282#-MVwHPaLEdjQ0KUy8B0k:-MVweywb254GNIoBXJzP:b-n7yha6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fe2a9f23736ffc48fe58598581b7c30adac907fb/src/BloomExe/Utils/PerformanceMeasurement.cs#L190)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> _end.privateBytesKb - _start.privateBytesKb)
> ```
The delta is dropped here. I assume that's intentional? Just double-checking.
</blockquote></details>

Done.  Added a comment to that effect.
___
*[src/BloomExe/Utils/PerformanceMeasurement.cs, line 192 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4282#-MVwHZmXDsJpKknb7og1:-MVweAB19zXDfL1LXUQR:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b1780fd13f375703682baf88bb598d2a0b157cc9/src/BloomExe/Utils/PerformanceMeasurement.cs#L192)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> previousSize
> ```
How about previousSizeKb so that whoever calls the constructor will have an easier time figuring out what units are expected?
</blockquote></details>

Done.
___
*[src/BloomExe/Utils/PerformanceMeasurement.cs, line 214 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4282#-MVwGmuC6aLFyxPZS8K_:-MVwezj6A4RdaEkKvozP:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b1780fd13f375703682baf88bb598d2a0b157cc9/src/BloomExe/Utils/PerformanceMeasurement.cs#L214)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I think the $"" syntax is better than format strings because you don't have to run your eyes left-to-right and count up indexes and whatnot, but...
even if we used a format string, I think we should just use String.Format directly instead of StringBuilder, since we're not like building up a string in a loop or anything like that. We're able to calculate the string all in one go.
</blockquote></details>

Done.

**Review by sujeffreyl — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4282)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
