### PR TITLE
MP3 option only enabled if book has narration (BL-10991)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5110)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
I suggest reviewing commit-by-commit

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5110#-:-N-cvBDX4z86L9SwCeaT:b-di24mz)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx, line 55 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5110#-N-cuyfNDHDCJXCGHkzu:-N-cuyfNDHDCJXCGHkzv:b-ixj0qz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8b180d2ea05f062c3a4f03b1bcc69260bde7afec/src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx#L55)):*
> ```XML
>     // Making our own version of format using useState, rather than using props.format directly, makes this go away somehow.
>     // (Maybe because we're making it more explicit to React that the state is being updated and it needs to re-render stuff,
>     // but I don't follow understand why it wasn't working before)
> ```

I don't 100% understand the problem, so I wasn't able to write a great explanation here. If anyone can figure out the problem better and therefore write 1) a better explanation, and/or 2) a better workaround, I would love that.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5110)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx, line 55 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5110#-N-cuyfNDHDCJXCGHkzu:-N-cw7AW5PdJdyX4KCdp:b-xecxdc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8b180d2ea05f062c3a4f03b1bcc69260bde7afec/src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx#L55)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I don't 100% understand the problem, so I wasn't able to write a great explanation here. If anyone can figure out the problem better and therefore write 1) a better explanation, and/or 2) a better workaround, I would love that.
</blockquote></details>

I initially thought the problem was due to a race condition, but the order the API calls returned in didn't seem to make any difference.

I thought the problem might've been because props.format is a field of an object, not a useState variable directly... but 1) it looked to me like the update of the avSettings object was happening appropriately, 2) when I tried to change PublishAudioVideo to use function syntaax for setState (real groaner BTW because useApiState did not handle that syntax yet), it still repro'd, and 3) when I changed PublishAudioVideo so that format was just a simple useState<string>, it still repro'd too.

Another weird thing is that I could repro it consistently in Bloom, but not really in my Firefox browser (v99)

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5110)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx, line 55 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5110#-N-cuyfNDHDCJXCGHkzu:-N-d3QpEDkO73qGpTiQP:b-7unziw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8b180d2ea05f062c3a4f03b1bcc69260bde7afec/src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx#L55)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I initially thought the problem was due to a race condition, but the order the API calls returned in didn't seem to make any difference.

I thought the problem might've been because props.format is a field of an object, not a useState variable directly... but 1) it looked to me like the update of the avSettings object was happening appropriately, 2) when I tried to change PublishAudioVideo to use function syntaax for setState (real groaner BTW because useApiState did not handle that syntax yet), it still repro'd, and 3) when I changed PublishAudioVideo so that format was just a simple useState<string>, it still repro'd too.

Another weird thing is that I could repro it consistently in Bloom, but not really in my Firefox browser (v99)
</blockquote></details>

Another thought that's too complicated for me to trace: props.icon is of type React.Node, whereas props.label is of type string. === would have different implications for these two types. Does that play into it?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
I added some comments (which I've left in place).
But then I experimented myself and pushed a branch which simplifies things and seems to work.
The downside is it doesn't handle future disabling of other formats. But I think we can treat that as yagni. If you think it is worth implementing, I think we can also make that work.
Branch name is AlternateApproachForBL10991.

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5110#-:-N-dSCNNAuj4Tkgzbju5:b3ld6bk)* status: all files reviewed, 3 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx, line 55 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5110#-N-cuyfNDHDCJXCGHkzu:-N-dJKxkAVWhqeSAB6fr:bbo2n4q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8b180d2ea05f062c3a4f03b1bcc69260bde7afec/src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx#L55)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Another thought that's too complicated for me to trace: props.icon is of type React.Node, whereas props.label is of type string. === would have different implications for these two types. Does that play into it?
</blockquote></details>

I agree it seems like it should work without the state variable.
You tried with using `props.format` rather than the reassigned/cloned `format`?

I would change the name to simply `format`. Or `selectedFormat`.
___
*[src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx, line 83 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5110#-N-dJ-uh8cgraETrYBrY:-N-dJ-uh8cgraETrYBrZ:b-ufq32i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8b180d2ea05f062c3a4f03b1bcc69260bde7afec/src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx#L83)):*
> ```XML
>             }
>         });
>     }, []);
> ```

I'm missing something.
This only runs once. And disabledFormats is initialized to an empty array.
So I don't understand all this logic of was this, now this.
___
*[src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx, line 133 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5110#-N-dJrRY8iFBzMWopdxr:-N-dJrRY8iFBzMWopdxs:bg6qc5t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8b180d2ea05f062c3a4f03b1bcc69260bde7afec/src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx#L133)):*
> ```XML
> 
>     useEffect(() => {
>         // Handle any disabled formats
> ```

I don't think this comment is accurate.
I would remove it or say something like `Ensure we don't select a disabled format`



_Code quote:_
```XML
// Handle any disabled formats
```

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5110)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx, line 83 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5110#-N-dJ-uh8cgraETrYBrY:-N-xShiT0fl0n6nzK6Zl:b-bo9ayw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8b180d2ea05f062c3a4f03b1bcc69260bde7afec/src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx#L83)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm missing something.
This only runs once. And disabledFormats is initialized to an empty array.
So I don't understand all this logic of was this, now this.

</blockquote></details>

It's just more generalized, able to work properly even if the 2nd param of  the useEffect changed in the future

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5110)* status: all files reviewed, 3 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx, line 83 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5110#-N-dJ-uh8cgraETrYBrY:-N-xW8Yn7g_0cMf92qHj:bxp5ucn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8b180d2ea05f062c3a4f03b1bcc69260bde7afec/src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx#L83)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

It's just more generalized, able to work properly even if the 2nd param of  the useEffect changed in the future
</blockquote></details>

Worth a comment, then, methinks

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5110)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx, line 55 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5110#-N-cuyfNDHDCJXCGHkzu:-N01FHldCsjjhukRcCTK:b-65inq0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8b180d2ea05f062c3a4f03b1bcc69260bde7afec/src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx#L55)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I agree it seems like it should work without the state variable.
You tried with using `props.format` rather than the reassigned/cloned `format`?

I would change the name to simply `format`. Or `selectedFormat`.
</blockquote></details>

OK, changed the name back to format
___
*[src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx, line 133 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5110#-N-dJrRY8iFBzMWopdxr:-N01EWLw7lOnG_9MAvH4:bb6un1j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8b180d2ea05f062c3a4f03b1bcc69260bde7afec/src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx#L133)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't think this comment is accurate.
I would remove it or say something like `Ensure we don't select a disabled format`
</blockquote></details>

Done

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Pull request merged**
