### PR TITLE
Give links to fix missing info during Web publish (BL-12103)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5765)

### CODE REVIEW

**Comment by hatton** [comment]
Looks good except sending people to the title for copyright seems worse than just showing the copyright box. I.e., ideally we'd take them to credits, but if that isn't possible, it would be better to just show the copyright/license?

**Review by andrew-polk — COMMENTED** [review]
Good point. I'll play with that.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5765#-:-NT0tn_I1ytFBZTIKzqD:bdxl9p7)* status: 0 of 4 files reviewed, all discussions resolved

**Review by hatton — COMMENTED** [review]
tomorrow, let's brainstorm to see if we can come up with an alternative to this `saved` callback.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5765#-:-NTFekKR07SEO2pI4uel:b-kdmyuj)* status: 0 of 7 files reviewed, all discussions resolved

**Review by jsubloom — COMMENTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5765)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 352 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5765#-NTFfxMk19dfF8GJwkwY:-NTFfxMk19dfF8GJwkwZ:b-wn4gp8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b1e7c91c42e0b7ae3ce5cb6d58a914b82302aeed/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L352)):*
> ```XML
>                                         }
>                                         onClick={() => {
>                                             showCopyrightAndLicenseInfoOrDialog();
> ```

Wrapping this in a lambda is unnecessary, you could just pass it directly.

**Review by andrew-polk — COMMENTED** [review]
Sounds good.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5765#-:-NTFhALF83ujuGbLDEMz:brxp9sq)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @jsubloom)

___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 352 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5765#-NTFfxMk19dfF8GJwkwY:-NTFhDtH8yoJTygO971y:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b1e7c91c42e0b7ae3ce5cb6d58a914b82302aeed/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L352)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

Wrapping this in a lambda is unnecessary, you could just pass it directly.
</blockquote></details>

Done.

**Review by jsubloom — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5765)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 824 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5765#-NTo3kFZEpATQmSZTaDs:-NTo3kFZEpATQmSZTaDt:birklwg) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d88eccacc9074986f49f52f740cf052d46d88986/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L824)):*
> ```XML
>                 </Div>
>                 <MustBeCheckedOut
>                     id={`fix-link-must-be-checked-out-${props.l10nKey}`}
> ```

Sorry to dig up obscure corner cases....  How do we know that l10nKey is valid as an ID?

Well, what is valid as an ID?  https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id says whitespace is the only thing that is strictly not okay. Some other categories of characters are also not recommended, but not strictly speaking wrong.

Consider the following regex: id="[^"]* [^"]*\"
It matches the l10nkey: "TemplateBooks.PageDescription.Picture on Left"

What would happen if this were passed to l10nKey?

Well, I guess two simple options that I think would be satisfactory are:
1) Replace " " (or, any whitespace, if more ambitious) with "-".  Then, the generated ID should at least be technically valid.
2) Since the documentation says browsers handle non-conforming IDs anyway, maybe we can just ignore the problem.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5765)* status: 3 of 9 files reviewed, 1 unresolved discussion (waiting on @jsubloom)

___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 824 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5765#-NTo3kFZEpATQmSZTaDs:-NToER1t1FWJodb__dER:b-e1auph) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d88eccacc9074986f49f52f740cf052d46d88986/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L824)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

Sorry to dig up obscure corner cases....  How do we know that l10nKey is valid as an ID?

Well, what is valid as an ID?  https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id says whitespace is the only thing that is strictly not okay. Some other categories of characters are also not recommended, but not strictly speaking wrong.

Consider the following regex: id="[^"]* [^"]*\"
It matches the l10nkey: "TemplateBooks.PageDescription.Picture on Left"

What would happen if this were passed to l10nKey?

Well, I guess two simple options that I think would be satisfactory are:
1) Replace " " (or, any whitespace, if more ambitious) with "-".  Then, the generated ID should at least be technically valid.
2) Since the documentation says browsers handle non-conforming IDs anyway, maybe we can just ignore the problem.
</blockquote></details>

Thanks; forced me to look at ID again which I wasn't liking anyway.

**Review by jsubloom — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5765)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
