### PR TITLE
BL-12805 Use text-wrap property

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6206)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6206)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[`src/content/bookLayout/basePage.less` line 1041 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6206#-Nijsb4z-kbZflF7p1Z1:-Nijsb4z-kbZflF7p1Z2:bhtjeco) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b778268fa67b3e5155c8d3cee59f8f766d6007f8/src/content/bookLayout/basePage.less#L1041)):*
> ```Less
> // Very long words should just allow themselves to be broken at the end of a line if they're
> // longer than a line.  See BL-12330.
> // Review: Should this rule be moved to basePage-sharedRules.less so it applies to ePUBs too?
> ```

Seems desirable.  I suggest you try it and see whether Daisy complains. It might be good to use word-wrap as well, in case some epub reader uses a very old browser; then again, this rule wasn't in epubs at all before now, so it can only improve things as far as I can see.
It's somewhat puzzling that the original rule was NOT in shared...
___
*[`src/content/bookLayout/basePage.less` line 1043 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6206#-Nijtdod3l98eSuOimXC:-Nijtdod3l98eSuOimXD:b2p05f3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b778268fa67b3e5155c8d3cee59f8f766d6007f8/src/content/bookLayout/basePage.less#L1043)):*
> ```Less
> // Review: Should this rule be moved to basePage-sharedRules.less so it applies to ePUBs too?
> .bloom-page .bloom-editable.bloom-visibility-code-on {
>     overflow-wrap: break-word; // 'overflow-wrap' is now the standard name for 'word-wrap'
> ```

Doesn't seem as if we need the comment here (it explains the PR rather than the current code)

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6206)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/content/bookLayout/basePage.less` line 1041 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6206#-Nijsb4z-kbZflF7p1Z1:-Nil-dgKBC15d07FuSMx:bhvcphu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b778268fa67b3e5155c8d3cee59f8f766d6007f8/src/content/bookLayout/basePage.less#L1041)):*
Moved. Compiled. Made sure Daisy was installed. Ran it on my book. 4 minor/1 moderate complaints about ARIA stuff, 1 serious complaint about epub-lang. None seem related to this.

> It's somewhat puzzling that the original rule was NOT in shared...

I agree.
___
*[`src/content/bookLayout/basePage.less` line 1043 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6206#-Nijtdod3l98eSuOimXC:-Nikn0j-9O7gSOs7hmul:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b778268fa67b3e5155c8d3cee59f8f766d6007f8/src/content/bookLayout/basePage.less#L1043)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Doesn't seem as if we need the comment here (it explains the PR rather than the current code)
</blockquote></details>

Done.

**Review by gmartin7 — COMMENTED** [review]
As noted in the issue, JH has decided we'll live with the non-WYSIWYG-ness for now.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6206#-:-NitxUB61nsHnnuvo4Fm:b-sz16ae)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

**Review by JohnThomson — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6206)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
