### PR TITLE
Add reader info to user error reports if applicable (BL-4240)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
If this looks safe enough, it might be backported to Version3.7.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1469)

### CODE REVIEW

**Comment by andrew-polk** [comment]
:lgtm:
I think this is probably safe enough for 3.7.
@Hatton, want to weigh in on back port to 3.7?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1469#-:-KcJLlh7lhdFlM6CzeGC:b-eh5b3k)*

**Comment by StephenMcConnel** [comment]
I've rebased this PR onto Version3.7.  This actually pulled in another change made previously, so you probably want to review this carefully.  I still think it should be safe.

**Comment by andrew-polk** [comment]
> his actually pulled in another change made previously

I don't understand what this means.
Something automatically added this change when you rebased? Or you had to make this change for your code to work in 3.7?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1469#-:-KcNjXVxlC7qKr6VxYng:b-iwyyzc)*

**Comment by StephenMcConnel** [comment]
It was semi-automatically pulled in when I rebased.  Essentially the GetAdditionalEnvironmentInfo() method.

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1469#-:-KcNx9fErh4ex1juK2UL:bnfp4nl)*

**Pull request merged**
