### PR TITLE
Updated Chinese strings

### PR DESCRIPTION
**Pull request by PaulNel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1445)

### CODE REVIEW

**Comment by andrew-polk** [comment]
My preference would be that we don't reformat all these files from the way L10NSharp generates them so we aren't constantly diff'ing meaningless whitespace. Thankfully, most diff engines have a way to ignore whitespace, so it isn't too much of a hassle, but if there is an easy way to tweak your XLiff->TMX converter, let's go ahead and do it.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[DistFiles/localization/Bloom.zh-Hans.tmx, line 1 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1445#-KbWFpjdLhIo-YVsFR3N:-KbWFpjdLhIo-YVsFR3O:b-ku1c5z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/04f811c0a9881120d195e33ba2447e368e2b0198/DistFiles/localization/Bloom.zh-Hans.tmx#L1)):*
> ```
> <?xml version="1.0" encoding="utf-8"?>
> ```

This file is impossible to review because it has been reordered, but I'm not sure how much we care.
Options:
-Make changes as two commits, the first with the reordering and no other changes (unreviewable), the second with the changes applied
-Say, "Oh well, I hope it's right. It probably is mostly right but likely has one or two mistakes here or there which may or may not get caught by the reviewer anyway due to the nature of the change."

---

*[DistFiles/localization/Palaso.zh-Hans.tmx, line 863 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1445#-KbWF8TTPC5cYf69J_5w:-KbWF8TTPC5cYf69J_5x:bmf0c0e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/04f811c0a9881120d195e33ba2447e368e2b0198/DistFiles/localization/Palaso.zh-Hans.tmx#L863)):*
> 出厂密码

You could claim this isn't a big deal since it doesn't actually work right now, but this needs to be literally "factory password" (not translated)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1445#-:-KbWGVybCEAh19rCJgmD:biyvgpy)*

**Comment by PaulNel** [comment]
For "Factory Password" - This has been translated in all languages to this point. If it needs to be in English as "Factory Password", why is it in the .TMX?

**Comment by andrew-polk** [comment]
Good question. It does need to be untranslated as the point is for someone to type that in their search engine to find the place we list it on the website. But as I say, searching out site doesn't actually work, so it isn't a big deal.
As you suggest, it needs to be replaced with {2}. I'll write it up as a separate issue. I won't hold up this merge for it.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1445#-:-KbW_gIFw9LZKptp96mo:b-rh6oso)*

**Comment by PaulNel** [comment]
Closing this pull request. Will submit a two new requests...first with sort order changed and second with string changes.

**Pull request closed without merging**
