### PR TITLE
BL-9815 and 9819 Better 'transparent' handling

### PR DESCRIPTION
**Pull request by gmartin7**
* for background color in Text Blocks and elsewhere

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4391)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4391)* status: all files reviewed, 3 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx, line 401 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4391#-MYq9esC1CfM5wN28lSy:-MYq9esC1CfM5wN28lSz:bast1gg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65afc74b86420f936541ddd031b1fe1b0da54298/src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx#L401)):*
> ```XML
>         // In this case opacity not undefined is different than !!opacity, since
>         // opacity can legitimately be defined as zero.
>         return opacityDecimal !== undefined && opacityDecimal < 1.0;
> ```

All of this makes me feel like there is something wrong in the model and/or type.
Is it possible to force the type to be a number, preferably between 0.0 and 1.0, where null and undefined are not allowed?
___
*[src/BloomBrowserUI/react_components/customColorPicker.tsx, line 49 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4391#-MYq8wxp1XUPKIoscCSt:-MYq8wxp1XUPKIoscCSu:b70ntfi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65afc74b86420f936541ddd031b1fe1b0da54298/src/BloomBrowserUI/react_components/customColorPicker.tsx#L49)):*
> ```XML
>     ): ISwatchDefn => {
>         // A Swatch that comes from the ChromePicker (not from clicking on a swatch), cannot be a gradient.
>         const opacity = color.rgb.a; // will be defined, so a falsey result means transparent here.
> ```

Seems better to just have the check below be opacity === 0.0 and remove the comment. What do you think?
___
*[src/BloomBrowserUI/react_components/customColorPicker.tsx, line 91 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4391#-MYq93ZK19NM9JAH7YEx:-MYq93ZK19NM9JAH7YEy:b-5zuu9p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65afc74b86420f936541ddd031b1fe1b0da54298/src/BloomBrowserUI/react_components/customColorPicker.tsx#L91)):*
> ```XML
>         const currentSwatch = colorChoice;
>         const rgbColor = tinycolor(currentSwatch.colors[0]).toRgb();
>         // One more spot where falsey is not equal to undefined
> ```

I'm not sure this or the other similar comments are really that helpful outside the context of this review.
Especially the "one more spot" seems like it would be more confusing than clarifying a year from now.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4391)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx, line 401 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4391#-MYq9esC1CfM5wN28lSy:-MYqIWVN2ZmGrPjk9OCD:b-4ftost) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65afc74b86420f936541ddd031b1fe1b0da54298/src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx#L401)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

All of this makes me feel like there is something wrong in the model and/or type.
Is it possible to force the type to be a number, preferably between 0.0 and 1.0, where null and undefined are not allowed?
</blockquote></details>

Done. I made ISwatchDefn's opacity a required number and everything "fell out" from there. Much simpler logic in a number of spots! Thanks!
___
*[src/BloomBrowserUI/react_components/customColorPicker.tsx, line 49 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4391#-MYq8wxp1XUPKIoscCSt:-MYqBtyU090lgYwRYSXl:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65afc74b86420f936541ddd031b1fe1b0da54298/src/BloomBrowserUI/react_components/customColorPicker.tsx#L49)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems better to just have the check below be opacity === 0.0 and remove the comment. What do you think?
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/react_components/customColorPicker.tsx, line 91 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4391#-MYq93ZK19NM9JAH7YEx:-MYqAVuxAVZ456Pu_8P0:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65afc74b86420f936541ddd031b1fe1b0da54298/src/BloomBrowserUI/react_components/customColorPicker.tsx#L91)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not sure this or the other similar comments are really that helpful outside the context of this review.
Especially the "one more spot" seems like it would be more confusing than clarifying a year from now.
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4391)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomBrowserUI/react_components/customColorPicker.tsx, line 50 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4391#-MYqNl7T54cHgrBY0Hgq:-MYqNl7T54cHgrBY0Hgr:brjhpx8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08f6b56744bd0fd66d4aea4f6772b16741378e81/src/BloomBrowserUI/react_components/customColorPicker.tsx#L50)):*
> ```
> opacity === undefined
> ```
This isn't possible now, right?
Or is this some safeguard because the underlying js really does allow for undefined even if ts doesn't?
Deserves a comment.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4391)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/react_components/customColorPicker.tsx, line 50 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4391#-MYqNl7T54cHgrBY0Hgq:-MYqPzweC_QsfdLHS6XV:bij7wy7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08f6b56744bd0fd66d4aea4f6772b16741378e81/src/BloomBrowserUI/react_components/customColorPicker.tsx#L50)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> opacity === undefined
> ```
This isn't possible now, right?
Or is this some safeguard because the underlying js really does allow for undefined even if ts doesn't?
Deserves a comment.
</blockquote></details>

Good catch. We did need a comment there. That's a ColorResult from 'react-color'.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4391)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

___
*[src/BloomBrowserUI/react_components/customColorPicker.tsx, line 50 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4391#-MYqNl7T54cHgrBY0Hgq:-MYqQOFA0Ct_cxcmG0mo:bx34gp2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08f6b56744bd0fd66d4aea4f6772b16741378e81/src/BloomBrowserUI/react_components/customColorPicker.tsx#L50)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Good catch. We did need a comment there. That's a ColorResult from 'react-color'.
</blockquote></details>

Ah. I misread originally. But the comment is helpful. Thanks.

**Pull request merged**
