### PR TITLE
Save page using RunJavaScript to get content

### PR DESCRIPTION
**Pull request by JohnThomson**
Old DOM manipulation approach appeared to contribute to memory leaks, so getting the page content a different way.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4288)

### CODE REVIEW

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4288)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 167 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4288#-MW0X3so6dwOTQqDLkds:-MW0X3sp0kXfupjDhaBr:blszg79) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9e7582c0185a4fd99c007065b47381a2a7bee54b/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L167)):*
> ```XML
>     $(container)
>         .find("div.bloom-editable")
>         .on("keydown", null, "F6", (e) => {
> ```

Many changes here are forced by some commit hook. The only one I wanted or think is non-formatting is the new function userStylesheetContent and replacing prepareToSavePage with getBodyContentForSavePage

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4288)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 1195 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4288#-MW0qN9KA4Sgrfv7a5Tk:-MW0qN9KA4Sgrfv7a5Tl:b7q96bl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1f3eaa6dc41bb067f3ac58a5ec26494406877f99/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L1195)):*
> ```
> // For usage, see editViewFrame.switchContentPage()
> ```
Perhaps unrelated to your change... but this comment seems out of date or irrelevant or inaccurate. At least, I can't make sense of it.

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4288)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 1208 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4288#-MW0yBww0TAANk4fNVJZ:-MW0yBww0TAANk4fNVJ_:b-z3pa9l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1f3eaa6dc41bb067f3ac58a5ec26494406877f99/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L1208)):*
> ```
> as CSSStyleSheet
> ```
The type declaration at the beginning and end of those are inconsistent.  (And also half-redundant). IMO, I think the following would be best?

const ss = Array.from(...) as CSSStyleSheet | undefined

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4288)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 1195 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4288#-MW0qN9KA4Sgrfv7a5Tk:-MW4v5B_2tYBfnT5xh9I:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1f3eaa6dc41bb067f3ac58a5ec26494406877f99/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L1195)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> // For usage, see editViewFrame.switchContentPage()
> ```
Perhaps unrelated to your change... but this comment seems out of date or irrelevant or inaccurate. At least, I can't make sense of it.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 1208 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4288#-MW0yBww0TAANk4fNVJZ:-MW4vhAZ43ArcePeiC2X:bg7qrtc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1f3eaa6dc41bb067f3ac58a5ec26494406877f99/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L1208)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> as CSSStyleSheet
> ```
The type declaration at the beginning and end of those are inconsistent.  (And also half-redundant). IMO, I think the following would be best?

const ss = Array.from(...) as CSSStyleSheet | undefined
</blockquote></details>

Done. (I'm baffled. When I first wrote this code, all I had was "as CSSStyleSheet" at the end and everything was fine. Then when I tried to copy it to 4.9, the compiler treated ss as of type StyleSheet and complained that ss didn't have cssRules. So I added the type declaration. But today I took it out again and all was fine, even without adding the extra | undefined. Still, that's the more accurate declaration, so I've put it in.

**Review by sujeffreyl — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4288)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4288)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by andrew-polk — APPROVED** [review]
> Dismissed @JohnThomson from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4288)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
