### PR TITLE
Show language names for written languages 2 and 3 (BL-13067)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
Also disable "Show Written Language 3 Title" if languge 3 is not defined.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6320)

### CODE REVIEW

**Review by hatton — COMMENTED** [review]
I think it would be simpler for translators if we just left the name out of the string? Then just append `(` name `)`

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6320#-:-NrHrVFo3qT6OWNSe__R:b-cl98gc)* status: 0 of 3 files reviewed, all discussions resolved

**Review by StephenMcConnel — COMMENTED** [review]
I'm open to that, but it violates one of the principles of localization of "don't try to piece strings together".  In this case, for the languages that we foresee being translated, it may not matter.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6320#-:-NrIBQ_F4ORMz8tuWRky:b-1f2zcy)* status: 0 of 3 files reviewed, all discussions resolved

**Review by hatton — COMMENTED** [review]
I hear you but I don't think it's two pieces of the same string. It's a label that is to the right of the original string, and should be regardless of the language. 

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6320#-:-NrICQYW1MVzRhbfBT6w:b-ml6ak)* status: 0 of 3 files reviewed, all discussions resolved

**Review by StephenMcConnel — COMMENTED** [review]
I've fixed the code as requested to not change the strings in the xlf file.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6320#-:-NrIIxAe1K5DCrJcG46k:b-xtwvz9)* status: 0 of 3 files reviewed, all discussions resolved

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6320)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/BloomExe/web/controllers/BookSettingsApi.cs` line 59 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6320#-NrLUc9U63FZchjWDQS8:-NraG9Jc78BweL3UcbEH:b34cgwg) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/7109fd8b3b659e1721ce9af6c5b0ab0a3c9754cb/src/BloomExe/web/controllers/BookSettingsApi.cs#L59)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Model-based API is preferred over UI-support-based API. Since languages are part of the model of `Collection`, I think this would rather be on `CollectionApi`. Thx.
</blockquote></details>

Done.  But on CollectionSettingsApi.

**Review by hatton — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6320)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
