### PR TITLE
 Fix uploading of problems to JIRA (BL-821)

### PR DESCRIPTION
**Pull request by ermshiperete**
This is done by switching to a different library to access JIRA.
This was necessary because of a mono bug that prevents the
deserialization of data received from Jira.

Additionally on Linux we have to use http instead of https, again
because of a bug in mono.

### CODE REVIEW

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/174/
Test FAILed.

**Comment by ermshiperete** [comment]
Causes test failures on Windows, so I'll have some more work to do...

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/179/
Test FAILed.

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/180/
Test PASSed.

**Comment by ermshiperete** [comment]
retest this please

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/189/
Test FAILed.

**Comment by ermshiperete** [comment]
retest this please

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/190/
Test FAILed.

**Comment by ermshiperete** [comment]
retest this please

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/191/
Test FAILed.

**Comment by ermshiperete** [comment]
retest this please

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/192/
Test FAILed.

**Comment by ermshiperete** [comment]
retest this please

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/193/
Test FAILed.

**Comment by ermshiperete** [comment]
retest this please

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/194/
Test FAILed.

**Comment by ermshiperete** [comment]
retest this please

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/195/
Test PASSed.

**Pull request merged**
