### PR TITLE
BL-8058 Add dashed border to template thumbs

### PR DESCRIPTION
**Pull request by gmartin7**
* This was a regression in 4.7.
* A change in thumbnail procedure missed adding dashes
   for template books
* Fixed tests (hitMax and related Assert)
* Added small square image test
* Focused main test on presence/absence of border
   (and renamed it)
* Also checked for use of Solid borderStyle in making thumbs.
   Didn't find any.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4140)

### CODE REVIEW

**Review by sujeffreyl — APPROVED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4140)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomTests/ImageProcessing/ImageUtilsTests.cs, line 216 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4140#-MQYPocdAfGYYaUKr6Ps:-MQYPoce2Poy9XZcAMOi:b9r55ia) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dfd48f5b65c2dbccd80ba4e0815e4fc3909cf720/src/BloomTests/ImageProcessing/ImageUtilsTests.cs#L216)):*
> ```
> {0}
> ```
Optional: I think "{0}" can be simplified down to "0"

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4140)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomTests/ImageProcessing/ImageUtilsTests.cs, line 216 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4140#-MQYPocdAfGYYaUKr6Ps:-MQYQfXrDMd-nazCSCEV:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dfd48f5b65c2dbccd80ba4e0815e4fc3909cf720/src/BloomTests/ImageProcessing/ImageUtilsTests.cs#L216)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> {0}
> ```
Optional: I think "{0}" can be simplified down to "0"
</blockquote></details>

Done.

**Review by sujeffreyl — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4140)* status: 4 of 5 files reviewed, all discussions resolved

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4140)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
