### PR TITLE
BL-10974 Replace Book Making tab w/React

### PR DESCRIPTION
**Pull request by gmartin7**
* get font list popover over Style Editor
* fix scrolling tab panes
* all controls exist in React now
* finish off UI parts
* get api calls working
* unfortunate need for Segoe font to get bold
* get Select to work
* clean out unused stuff in CollectionSettingsDialog

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087)* status: all files reviewed, 10 unresolved discussions (waiting on @gmartin7)

___
*[DistFiles/localization/en/Bloom.xlf, line 357 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087#-N--syBbCVQKCBaOEpB0:-N--syBbCVQKCBaOEpB1:b-594mzy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7b36f6e1c56b1f36ee15864b2b1e9b574f7c9bc7/DistFiles/localization/en/Bloom.xlf#L357)):*
> ```XML
>       </trans-unit>
>       <trans-unit id="CollectionSettingsDialog.BloomLibraryBookshelf">
>         <source xml:lang="en">Bloom Library Bookshelf</source>
> ```

Are you sure we want to start localizing this now?
(same with other strings)



_Code quote:_
```XML
Bloom Library Bookshelf
```
___
*[src/BloomBrowserUI/collection/bookMakingSettingsControl.tsx, line 14 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087#-N--sX5mBza4wpMy4Evt:-N--sX5mBza4wpMy4Evu:b4vs05f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/57b632662010f18562f64a1b1a3b33a4b358e494/src/BloomBrowserUI/collection/bookMakingSettingsControl.tsx#L14)):*
> ```XML
> 
> const topMargin = "24";
> const sideMargin = "26";
> ```

I'm ok with some pushback since we expect all these settings to go to the new style before *too* long, but...
I assume the general setup of the tab margins, etc. came from the enterprise and/or team collection tab? Then should we extract that UI logic?
___
*[src/BloomBrowserUI/react_components/formsSelect.tsx, line 27 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087#-N--o__T2pyerzkzBdwR:-N--o__T2pyerzkzBdwS:bpwaf8n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/57b632662010f18562f64a1b1a3b33a4b358e494/src/BloomBrowserUI/react_components/formsSelect.tsx#L27)):*
> ```XML
> // This component attempts to imitate a winforms combobox in React. As such it's probably a temporary
> // thing as Bloom matures and moves away from winforms altogether.
> const FormsSelect: React.FunctionComponent<FormsSelectProps> = props => {
> ```

What would you think of calling this `WinFormsStyleSelect`?



_Code quote:_
```XML
FormsSelect
```
___
*[src/BloomBrowserUI/react_components/formsSelect.tsx, line 46 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087#-N--onT-DGvzOORC0O0Z:-N--onT-DGvzOORC0O0_:b-9ppjhf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/57b632662010f18562f64a1b1a3b33a4b358e494/src/BloomBrowserUI/react_components/formsSelect.tsx#L46)):*
> ```XML
>     };
> 
>     // Match the border color of the other selects in the Format dialog.
> ```

This comment confuses me. I would assume "Format dialog" is the one from the cog in edit mode.
But that shouldn't be relevant for something imitating winforms.

Same for the comment below about Style tab.



_Code quote:_
```XML
Match the border color of the other selects in the Format dialog.
```
___
*[src/BloomBrowserUI/react_components/singleFontSection.tsx, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087#-N--j_8o0Rv7vHTKsces:-N--j_8o0Rv7vHTKscet:buhrg1m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/57b632662010f18562f64a1b1a3b33a4b358e494/src/BloomBrowserUI/react_components/singleFontSection.tsx#L40)):*
> ```XML
>     return (
>         <React.Fragment>
>             <Typography
> ```

What's the purpose of moving away from Div which is specifically designed to handle the l10n? (here and elsewhere)
___
*[src/BloomBrowserUI/react_components/xmatterChooserControl.tsx, line 10 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087#-N--qy8N9N0J-6RlllZw:-N--qy8N9N0J-6RlllZx:b8myavw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/57b632662010f18562f64a1b1a3b33a4b358e494/src/BloomBrowserUI/react_components/xmatterChooserControl.tsx#L10)):*
> ```XML
> import { makeStyles } from "@material-ui/styles";
> 
> interface XmatterInfo {
> ```

IXmatterInfo?



_Code quote:_
```XML
XmatterInfo
```
___
*[src/BloomBrowserUI/react_components/xmatterChooserControl.tsx, line 53 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087#-N--rOu1Ci2QqzBqp4rh:-N--rOu1Ci2QqzBqp4ri:b-v7dfos) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/57b632662010f18562f64a1b1a3b33a4b358e494/src/BloomBrowserUI/react_components/xmatterChooserControl.tsx#L53)):*
> ```XML
>     useEffect(() => {
>         BloomApi.get("settings/xmatter", result => {
>             setSelectedXmatter(result.data.Item1 as string);
> ```

Can you use named tuples on the c# side to make this cleaner (not Item1/Item2)?
If not, I think it would be worth creating a new dynamic object so the labels are explicit.
(same for number style)



_Code quote:_
```XML
Item1
```
___
*[src/BloomExe/web/ReactControl.cs, line 163 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087#-N--lV7WDqEFZh8h90-I:-N--lV7WDqEFZh8h90-J:b3exki0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/57b632662010f18562f64a1b1a3b33a4b358e494/src/BloomExe/web/ReactControl.cs#L163)):*
> ```Smalltalk
> 					</script>					
> 				</head>
> 				<body style='margin:0; height:auto; background-color:{backColor};'>
> ```

This change scares me. Did you look around at other react controls to try to verify nothing could have broken?



_Code quote:_
```Smalltalk
height:auto;
```
___
*[src/BloomExe/web/controllers/CollectionSettingsApi.cs, line 258 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087#-N--muZk87n4hG0gVgml:-N--muZk87n4hG0gVgmm:buszvpz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/57b632662010f18562f64a1b1a3b33a4b358e494/src/BloomExe/web/controllers/CollectionSettingsApi.cs#L258)):*
> ```Smalltalk
> 		{
> 			string currentXmatter = null;
> 			if (_xmatterOfferings.Count.Equals(0))
> ```

I'm a little unsure about caching _xmatterOfferings. Can't the list change based on what branding is selected?
___
*[src/BloomExe/web/controllers/CollectionSettingsApi.cs, line 292 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087#-N--nI5HD5z2sUsMUOpl:-N--nI5HD5z2sUsMUOpm:b52zlas) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/57b632662010f18562f64a1b1a3b33a4b358e494/src/BloomExe/web/controllers/CollectionSettingsApi.cs#L292)):*
> ```Smalltalk
> 		private object GetNumberingStyleData()
> 		{
> 			var numberingStyles = new List<object>();
> ```

This you could cache safely, I think.
Not that you need to. I just thought of it because you are caching xmatters.



_Code quote:_
```Smalltalk
numberingStyles
```

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087)* status: 6 of 22 files reviewed, 10 unresolved discussions (waiting on @andrew-polk)

___
*[DistFiles/localization/en/Bloom.xlf, line 357 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087#-N--syBbCVQKCBaOEpB0:-N-9Xnx21qPemfAzJgBF:b6qtf3h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7b36f6e1c56b1f36ee15864b2b1e9b574f7c9bc7/DistFiles/localization/en/Bloom.xlf#L357)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Are you sure we want to start localizing this now?
(same with other strings)
</blockquote></details>

Waiting on a decision from JH. For now, I've added this Header to the localizations and commented out the 2 descriptions below.
___
*[src/BloomBrowserUI/collection/bookMakingSettingsControl.tsx, line 14 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087#-N--sX5mBza4wpMy4Evt:-N-9Fupw8VIYGdygWlBP:b-ud3x51) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/57b632662010f18562f64a1b1a3b33a4b358e494/src/BloomBrowserUI/collection/bookMakingSettingsControl.tsx#L14)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm ok with some pushback since we expect all these settings to go to the new style before *too* long, but...
I assume the general setup of the tab margins, etc. came from the enterprise and/or team collection tab? Then should we extract that UI logic?
</blockquote></details>

I pulled out a commonTabSettings.ts file for the margins. The other 2 tabs, until now, used `.less` constants for this, but one was already using emotion and now the other one is. An argument could be made for making the whole margin string one thing, but I actually re-use the side margin as a column margin in the new bookMaking panel.
___
*[src/BloomBrowserUI/react_components/singleFontSection.tsx, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087#-N--j_8o0Rv7vHTKsces:-N-4hErAAT3g5VTFTm3t:b16qkj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/57b632662010f18562f64a1b1a3b33a4b358e494/src/BloomBrowserUI/react_components/singleFontSection.tsx#L40)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What's the purpose of moving away from Div which is specifically designed to handle the l10n? (here and elsewhere)
</blockquote></details>

At first I did it to get away from Segoe UI. Later, when JH discovered we needed Segoe in order to `bold` properly, I kept it because I still couldn't get the Div to bold properly
___
*[src/BloomBrowserUI/react_components/xmatterChooserControl.tsx, line 10 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087#-N--qy8N9N0J-6RlllZw:-N-4SiBLDdkbvEgBV02n:bwfewt6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/57b632662010f18562f64a1b1a3b33a4b358e494/src/BloomBrowserUI/react_components/xmatterChooserControl.tsx#L10)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

IXmatterInfo?
</blockquote></details>

Done. Probably best, though I think I've seen a lot of interfaces w/o it lately...
___
*[src/BloomBrowserUI/react_components/xmatterChooserControl.tsx, line 53 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087#-N--rOu1Ci2QqzBqp4rh:-N-8wy9dADJRI7rvDu51:bsarzzm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/57b632662010f18562f64a1b1a3b33a4b358e494/src/BloomBrowserUI/react_components/xmatterChooserControl.tsx#L53)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Can you use named tuples on the c# side to make this cleaner (not Item1/Item2)?
If not, I think it would be worth creating a new dynamic object so the labels are explicit.
(same for number style)
</blockquote></details>

Switched 3 api calls to dynamic objects with more reasonable names for the parts. Much better. Don't know why I couldn't get it to work before.
___
*[src/BloomExe/web/ReactControl.cs, line 163 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087#-N--lV7WDqEFZh8h90-I:-N-4Bq_224ccBmanxl3U:bnhh9ey) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/57b632662010f18562f64a1b1a3b33a4b358e494/src/BloomExe/web/ReactControl.cs#L163)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This change scares me. Did you look around at other react controls to try to verify nothing could have broken?
</blockquote></details>

Yep. The only other uses currently are the CollectionTabView (new Collection View), which seems to work fine and other tabs in the dialog I'm working on (which had the scrolling problem). I change the height here on the `body` to auto, but there is still a `height: 100%;` rule on the `html` tag itself AND on the contained `div#reactRoot` (the contents of which gets replaced by Javascript).
___
*[src/BloomExe/web/controllers/CollectionSettingsApi.cs, line 258 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087#-N--muZk87n4hG0gVgml:-N-4LUOA8_hi3O5WFIs9:b3bg9x2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/57b632662010f18562f64a1b1a3b33a4b358e494/src/BloomExe/web/controllers/CollectionSettingsApi.cs#L258)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm a little unsure about caching _xmatterOfferings. Can't the list change based on what branding is selected?
</blockquote></details>

Good point. I'm not sure why I did it that way. It might be that the original code in the actual dialog file was similar, but you're right. Safer not to cache.
___
*[src/BloomExe/web/controllers/CollectionSettingsApi.cs, line 292 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087#-N--nI5HD5z2sUsMUOpl:-N-4M_UiE65HaJAe3Xkm:b3h40qb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/57b632662010f18562f64a1b1a3b33a4b358e494/src/BloomExe/web/controllers/CollectionSettingsApi.cs#L292)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This you could cache safely, I think.
Not that you need to. I just thought of it because you are caching xmatters.
</blockquote></details>

OK! Not a bad idea, since this is in a "stick around for the entire Bloom lifetime" file! Done.
___
*[src/BloomBrowserUI/react_components/formsSelect.tsx, line 27 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087#-N--o__T2pyerzkzBdwR:-N-4WEbh9J05sPkpT9wi:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/57b632662010f18562f64a1b1a3b33a4b358e494/src/BloomBrowserUI/react_components/formsSelect.tsx#L27)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What would you think of calling this `WinFormsStyleSelect`?
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/react_components/formsSelect.tsx, line 46 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087#-N--onT-DGvzOORC0O0Z:-N-4fHfgB8jVOMt_e6tO:buffa32) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/57b632662010f18562f64a1b1a3b33a4b358e494/src/BloomBrowserUI/react_components/formsSelect.tsx#L46)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This comment confuses me. I would assume "Format dialog" is the one from the cog in edit mode.
But that shouldn't be relevant for something imitating winforms.

Same for the comment below about Style tab.
</blockquote></details>

And yet it is relevant, because we are indeed referring to the border gray color of the other selects in the Edit tab code dialog. Without this, the gray border on this one is too light in comparison to the others. Noted in a code comment too.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/react_components/singleFontSection.tsx, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087#-N--j_8o0Rv7vHTKsces:-N-A2AOd9j_mhAKVJ-Zp:bcp02wf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/57b632662010f18562f64a1b1a3b33a4b358e494/src/BloomBrowserUI/react_components/singleFontSection.tsx#L40)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

At first I did it to get away from Segoe UI. Later, when JH discovered we needed Segoe in order to `bold` properly, I kept it because I still couldn't get the Div to bold properly
</blockquote></details>

Seems odd that it would be different. And I don't think it explains some of the other uses of Typography instead of Div or P. But I suppose there is no specific reason it needs to use those.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087)* status: 20 of 22 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[DistFiles/localization/en/Bloom.xlf, line 357 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087#-N--syBbCVQKCBaOEpB0:-N-A1f362omZeD-Gc5rj:bgk9oqs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7b36f6e1c56b1f36ee15864b2b1e9b574f7c9bc7/DistFiles/localization/en/Bloom.xlf#L357)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Waiting on a decision from JH. For now, I've added this Header to the localizations and commented out the 2 descriptions below.
</blockquote></details>

JH says no l10n for any of 'em.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
