### PR TITLE
Give user suggestions when out of memory making PDFs (BL-5467)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This is almost asking for a browser-based error report option.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2494)

### CODE REVIEW

**Comment by andrew-polk** [comment]
I thought we intended to simply point to the url on the community site where this information is hosted.

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2494#-:-LEvMI9GDW5x3Jl41fGd:b-c08z4u)*

**Comment by hatton** [comment]
Yeah... until we have a way of sending low-priority strings to a separate file, we can't afford to ask localizers to take on more the necessary for the UI. Already, I see groups dropping out because it's all just overwhelming.

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2494#-:-LEvOmIG6GkfDXnp9JCM:b-qcwdwy)*

**Comment by StephenMcConnel** [comment]
Done.  There is now a browser based message dialog that allows the link the website to be displayed nicely.  It uses the HtmlLabel control from libpalaso.

---

Review status: 0 of 5 files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2494#-:-LEzOOHK1qcZnM9gHjio:bu8tw54)*

**Comment by andrew-polk** [comment]
:lgtm: other than an errant comment

---

Reviewed 5 of 6 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

---

*[src/BloomExe/MiscUI/HtmlLinkDialog.cs, line 16 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2494#-LEzUlDGAJXnzkS4FyMo:-LEzUlDGAJXnzkS4FyMp:bu9ufev) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0cc81419f4d3fefbd17049c0410901aef2ed9973/src/BloomExe/MiscUI/HtmlLinkDialog.cs#L16)):*
> ```
> 	It uses an internal geckofx based web display to show the message, including the HTML link.
> ```

This isn't true, is it?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2494#-:-LEzVEe26ktvilkBCbb4:b-5lrowc)*

**Comment by StephenMcConnel** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

---

*[src/BloomExe/MiscUI/HtmlLinkDialog.cs, line 16 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2494#-LEzUlDGAJXnzkS4FyMo:-LEzahnQA2rQrH3F1X36:b-rlyi4f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0cc81419f4d3fefbd17049c0410901aef2ed9973/src/BloomExe/MiscUI/HtmlLinkDialog.cs#L16)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> 	It uses an internal geckofx based web display to show the message, including the HTML link.
> ```

This isn't true, is it?
</blockquote></details>

Hmm, maybe the English isn't clear.  The HtmlLabel control, which display the message to the user in this dialog, uses a geckofx-based browser not a WinForms control for the message display.  It has code built-in to handle the first link when clicked to try to open the link target in the default system browser.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2494)*

**Pull request merged**
