### PR TITLE
BL-9044 Auto Update Dialog

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4260)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4260)* status: all files reviewed, 6 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomBrowserUI/webpack.common.js, line 55 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4260#-MV3p6e66VdMCEr3tuUa:-MV3p6e73DLQl-10v95i:b5od8uw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a93aeb069bb0112815f318e7033df82ef2a3c00/src/BloomBrowserUI/webpack.common.js#L55)):*
> ```
> utils/SoftwareUpdateDialog.tsx
> ```
I think this would be better in react_components
___
*[src/BloomBrowserUI/utils/SoftwareUpdateDialog.less, line 46 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4260#-MV3pFx04sg2WK7gsr2Q:-MV3pFx04sg2WK7gsr2R:b34xhgy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a93aeb069bb0112815f318e7033df82ef2a3c00/src/BloomBrowserUI/utils/SoftwareUpdateDialog.less#L46)):*
> ```Less
>         }
>     }
> }
> ```

I'm guessing much of this was copy/paste. Is there enough duplication to extract to a common less file?
___
*[src/BloomBrowserUI/utils/SoftwareUpdateDialog.tsx, line 50 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4260#-MV3qL2Z14AOUa6zkRtA:-MV3qL2Z14AOUa6zkRtB:b-ikize6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a93aeb069bb0112815f318e7033df82ef2a3c00/src/BloomBrowserUI/utils/SoftwareUpdateDialog.tsx#L50)):*
> ```
> autoUpdate
> ```
isAutoUpdate?
___
*[src/BloomBrowserUI/utils/SoftwareUpdateDialog.tsx, line 55 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4260#-MV3qjOTDClEnPChq1d_:-MV3qjOTDClEnPChq1da:bhg3i0y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a93aeb069bb0112815f318e7033df82ef2a3c00/src/BloomBrowserUI/utils/SoftwareUpdateDialog.tsx#L55)):*
> ```
> Paper
> ```
I don't understand what this is for, but I'm guessing it comes from an existing dialog and provides something in the UI we want.
Since 2 is an impossible number, should we extract a parent component which provides this (and goes with the extracted less suggested elsewhere)?
Then future changes to the basic dialog structure would be easy to change in one place.
___
*[src/BloomExe/web/controllers/InstallationSettingsApi.cs, line 7 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4260#-MV3lXH5-lWJpZ8Z8-p0:-MV3lXH68qqM3zUwigaj:b82hjq4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a93aeb069bb0112815f318e7033df82ef2a3c00/src/BloomExe/web/controllers/InstallationSettingsApi.cs#L7)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> 	/// <summary>
> 	/// Used by the Software Updates dialog.
> 	/// Intended for React components to deal with any system-wide Bloom settings.
> 	/// </summary>
> 	public class InstallationSettingsApi
> 	{
> 		public const string kApiUrlPart = "system/";
> ```
</details>

I feel like there is some inconsistency here. 
Is it for installation settings, system, etc.?

Let's either make it generic or specific. I guess I would lean toward generic...

Or maybe we should use FeatureControlApi?
___
*[src/BloomExe/web/controllers/InstallationSettingsApi.cs, line 17 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4260#-MV3oQA-8H2rAjW_B0XK:-MV3oQA-8H2rAjW_B0XL:bqins93) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a93aeb069bb0112815f318e7033df82ef2a3c00/src/BloomExe/web/controllers/InstallationSettingsApi.cs#L17)):*
> ```
> autoUpdateValues
> ```
autoUpdateBloomChoice?
autoUpdateSoftwareChoice?

Generally looking for more consistency in naming so this and the dialog name, etc. match as much as reasonable.

**Comment by andrew-polk** [comment]
___
*[src/BloomBrowserUI/utils/SoftwareUpdateDialog.tsx, line 55 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4260#-MV3qjOTDClEnPChq1d_:-MVHwsAyDeIkvgB8ZdBO:b-cdl4be) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a93aeb069bb0112815f318e7033df82ef2a3c00/src/BloomBrowserUI/utils/SoftwareUpdateDialog.tsx#L55)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Paper
> ```
I don't understand what this is for, but I'm guessing it comes from an existing dialog and provides something in the UI we want.
Since 2 is an impossible number, should we extract a parent component which provides this (and goes with the extracted less suggested elsewhere)?
Then future changes to the basic dialog structure would be easy to change in one place.
</blockquote></details>

As discussed, let's use Material's `Dialog` component

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4260)* status: 6 of 19 files reviewed, 6 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/webpack.common.js, line 55 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4260#-MV3p6e66VdMCEr3tuUa:-MVIEpV45yjo30TZl1vL:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a93aeb069bb0112815f318e7033df82ef2a3c00/src/BloomBrowserUI/webpack.common.js#L55)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> utils/SoftwareUpdateDialog.tsx
> ```
I think this would be better in react_components
</blockquote></details>

Done.
___
*[src/BloomExe/web/controllers/InstallationSettingsApi.cs, line 7 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4260#-MV3lXH5-lWJpZ8Z8-p0:-MVIDaHe5AgXNNUF2_0Z:bxzgbv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a93aeb069bb0112815f318e7033df82ef2a3c00/src/BloomExe/web/controllers/InstallationSettingsApi.cs#L7)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> 	/// <summary>
> 	/// Used by the Software Updates dialog.
> 	/// Intended for React components to deal with any system-wide Bloom settings.
> 	/// </summary>
> 	public class InstallationSettingsApi
> 	{
> 		public const string kApiUrlPart = "system/";
> ```
I feel like there is some inconsistency here. 
Is it for installation settings, system, etc.?

Let's either make it generic or specific. I guess I would lean toward generic...

Or maybe we should use FeatureControlApi?
</blockquote></details>

Used `FeatureControlApi`, but renamed it to avoid confusion with book features. Now called `SystemControlApi` and `featurecontrol/` url prefix has been changed to `system/`.

I'm wondering if we should try to move `system/enterpriseEnabled` to `collectionSettingsApi`?
___
*[src/BloomExe/web/controllers/InstallationSettingsApi.cs, line 17 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4260#-MV3oQA-8H2rAjW_B0XK:-MVIHPYyCzXqyyZAe0Vz:b18eply) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a93aeb069bb0112815f318e7033df82ef2a3c00/src/BloomExe/web/controllers/InstallationSettingsApi.cs#L17)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> autoUpdateValues
> ```
autoUpdateBloomChoice?
autoUpdateSoftwareChoice?

Generally looking for more consistency in naming so this and the dialog name, etc. match as much as reasonable.
</blockquote></details>

Went with `autoUpdateSoftwareChoice` and renamed the dialog to `AutoUpdateSoftwareDialog`. :)
___
*[src/BloomBrowserUI/utils/SoftwareUpdateDialog.less, line 46 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4260#-MV3pFx04sg2WK7gsr2Q:-MVIfoGP-rRPx-KoVttE:bectn8e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a93aeb069bb0112815f318e7033df82ef2a3c00/src/BloomBrowserUI/utils/SoftwareUpdateDialog.less#L46)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm guessing much of this was copy/paste. Is there enough duplication to extract to a common less file?
</blockquote></details>

Actually not so much. I don't see very much at all that could be extracted out.
___
*[src/BloomBrowserUI/utils/SoftwareUpdateDialog.tsx, line 50 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4260#-MV3qL2Z14AOUa6zkRtA:-MVIFDUe-wd3UMGDazvf:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a93aeb069bb0112815f318e7033df82ef2a3c00/src/BloomBrowserUI/utils/SoftwareUpdateDialog.tsx#L50)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> autoUpdate
> ```
isAutoUpdate?
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/utils/SoftwareUpdateDialog.tsx, line 55 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4260#-MV3qjOTDClEnPChq1d_:-MVIfdU25vBGyKiJMRes:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a93aeb069bb0112815f318e7033df82ef2a3c00/src/BloomBrowserUI/utils/SoftwareUpdateDialog.tsx#L55)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

As discussed, let's use Material's `Dialog` component
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4260)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomExe/web/controllers/InstallationSettingsApi.cs, line 7 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4260#-MV3lXH5-lWJpZ8Z8-p0:-MVIlyXfBHxCZ1wdcQj9:b-typ141) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a93aeb069bb0112815f318e7033df82ef2a3c00/src/BloomExe/web/controllers/InstallationSettingsApi.cs#L7)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Used `FeatureControlApi`, but renamed it to avoid confusion with book features. Now called `SystemControlApi` and `featurecontrol/` url prefix has been changed to `system/`.

I'm wondering if we should try to move `system/enterpriseEnabled` to `collectionSettingsApi`?
</blockquote></details>

Yes, it does seem better to do that while we're thinking about it. Thanks.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4260)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomExe/web/controllers/CollectionSettingsApi.cs, line 62 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4260#-MVNI825EDXmPbDtRsB6:-MVNI825EDXmPbDtRsB7:b-ezg9oj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c7f668db88e6dcc741f4d1b2dd3e9abcf121948e/src/BloomExe/web/controllers/CollectionSettingsApi.cs#L62)):*
> ```Smalltalk
> 					lock (request)
> 					{
> 						request.ReplyWithBoolean(IsEnterpriseEnabled);
> ```

common/enterpriseFeaturesEnabled used to return a string, but this returns a boolean. 
You've verified things work correctly for the client with this change?

**Pull request merged**
