### PR TITLE
Display Android Troubleshooting doc BL-4921

### PR DESCRIPTION
**Pull request by hatton**
The actualy location of this html may change as the xliff l10n work continues. For sure the html, which is currently checked in, will eventually be generated by the build instead.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1817)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Sorry, but I'm fairly baffled by this one. Maybe just tired. See if any of my comments/questions make sense, and if not, maybe someone else can take a look.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[DistFiles/infoPages/Publish-Android-Troubleshooting-en.htm, line 21 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1817#-KsL5JYkKqm8CqWMwE__:-KsL5JYkKqm8CqWMwE_a:b7amzf7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/61453043f722fc63788edbe8668cdefc1abfb0c8/DistFiles/infoPages/Publish-Android-Troubleshooting-en.htm#L21)):*
> ```HTML
>         <li>Make sure the computer and device are on the same WiFi network. A computer plugged in via cable to the WiFi router
>             still may be on its own network. It is technically possible to connect wired networks to be able to be on the
>             same local subnet as WiFi, but the Bloom team will not be able to provide any help in setting that up, sorry.</li>
> ```

It's technically possible to both be on WiFi, but not the SAME WiFi, too. For example ILC has both regular and guest WiFi networks. Maybe we should make the desktop display the network name, too? It's usually fairly readily accessible on the desktop, of course...if you know where to look.

---

*[src/BloomBrowserUI/react_components/htmlHelpLink.tsx, line 16 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1817#-KsL96NTk7zxQ1IV7RN5:-KsL96NTk7zxQ1IV7RN6:b-obpvcs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/61453043f722fc63788edbe8668cdefc1abfb0c8/src/BloomBrowserUI/react_components/htmlHelpLink.tsx#L16)):*
> ```XML
>         return (
>             <a target="_blank" href={"/bloom/htmlhelp/" + this.props.fileid}>
>                 {this.getLocalizedContent()}
> ```

Maybe I'm just dense today, but I don't see how this works. We have to stick some localhost: stuff on the front of a url for an independent browser to talk to our server, don't we? And that's what knows how to interpret bloom/htmlhelp etc.
No doubt you've tried and it DOES work, and maybe I'm just forgetting something we're all supposed to know...anyway, if you can think of a comment that might be worthwhile, it might be nice.

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 287 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1817#-KsL8_jfh-FULbPCRI4Q:-KsL8_jgD6075v8015Xq:b-mv63ww) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/61453043f722fc63788edbe8668cdefc1abfb0c8/src/BloomExe/web/EnhancedImageServer.cs#L287)):*
> ```Smalltalk
> 				return true;
> 			}
> 			else if (localPath.StartsWith("htmlhelp/", StringComparison.InvariantCulture))
> ```

Seems like we now usually add new UI stuff using api/whatever and add a new api class, rather than adding more cases to "the rat's nest of other possibilities"

---

*[src/BloomTests/web/EnhancedImageServerTests.cs, line 79 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1817#-KsL6dlq_9nVp0n8ReIx:-KsL6dlq_9nVp0n8ReIy:b-fns7eh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/61453043f722fc63788edbe8668cdefc1abfb0c8/src/BloomTests/web/EnhancedImageServerTests.cs#L79)):*
> ```Smalltalk
> 				var transaction = new PretendRequestInfo("htmlhelp/Publish-Android-Troubleshooting");
> 				server.MakeReply(transaction);
> 				Assert.IsTrue(transaction.ReplyImagePath.Contains(".htm"));
> ```

Slightly surprising that an IMAGE path contains .htm.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1817#-:-KsLAjSzTRkvDWYcxxiC:b6mnaaw)*

**Comment by hatton** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 287 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1817#-KsL8_jfh-FULbPCRI4Q:-KsdorEKIerz2VaE89kF:bq1qgy9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/61453043f722fc63788edbe8668cdefc1abfb0c8/src/BloomExe/web/EnhancedImageServer.cs#L287)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Seems like we now usually add new UI stuff using api/whatever and add a new api class, rather than adding more cases to "the rat's nest of other possibilities"
</blockquote></details>

Thanks, you saved me... actually an api for something very close to this already exists (ExternalLinkController). So I just improved that to be multilingual.

---

*[src/BloomTests/web/EnhancedImageServerTests.cs, line 79 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1817#-KsL6dlq_9nVp0n8ReIx:-KsdSpEFhaFc0jhutnv7:bm33mit) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/61453043f722fc63788edbe8668cdefc1abfb0c8/src/BloomTests/web/EnhancedImageServerTests.cs#L79)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Slightly surprising that an IMAGE path contains .htm.
</blockquote></details>

Ok, fixing the monstrosity of these "image" classes that I've been complaining about to the technical leads for 3 years now with no effect is hardly part of this little PR, but ok, I renamed that property of PretendRequestInfo to "ReplyPath".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1817)*

**Comment by hatton** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomTests/web/EnhancedImageServerTests.cs, line 79 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1817#-KsL6dlq_9nVp0n8ReIx:-KsdpCYsBMpXMdw_Kg9e:bt1zsg2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/61453043f722fc63788edbe8668cdefc1abfb0c8/src/BloomTests/web/EnhancedImageServerTests.cs#L79)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Ok, fixing the monstrosity of these "image" classes that I've been complaining about to the technical leads for 3 years now with no effect is hardly part of this little PR, but ok, I renamed that property of PretendRequestInfo to "ReplyPath".
</blockquote></details>

In the end I dropped this because of the different approach.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1817)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1817#-:-KsijT4nUVhPjpdQSNAx:bnfp4nl)*

**Pull request merged**
