### PR TITLE
Improve the Advanced Settings tab of the Setting dialog (BL-9842)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 6 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392)* status: 6 of 12 files reviewed, 9 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomBrowserUI/bookEdit/js/origami.ts, line 16 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYvYKe--cEbZ6jEDaGS:-MYvYKe0EZDzqNjG69Ag:b-87dvwg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e02cf0ee160d3e53d20d001c818b6c60e2d662be/src/BloomBrowserUI/bookEdit/js/origami.ts#L16)):*
> ```XML
>     BloomApi.get("app/enabledExperimentalFeatures", result => {
>         const enabledExperimentalFeatures: string = result.data;
>         const showExperimental: boolean = enabledExperimentalFeatures.includes(
> ```

We can make Widgets not be experimental (I didn't realize that they still are). So then this doesn't have to hit the features api at all.
___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 231 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYvYmek8y_h8G6fHn99:-MYvYmek8y_h8G6fHn9A:b-laknkq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e02cf0ee160d3e53d20d001c818b6c60e2d662be/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L231)):*
> ```XML
>                         showExperimentalTools = experimentalFeatures.data
>                             .toString()
>                             .includes("experimental-sources");
> ```

Like your TODO says, we don't have experimental tools, and when we do, it won't have anything to do with "experimental-sources", which are things like templates, not tools. And we won't have an "experimental-tools", either. We will have "grinder" or "table saw" or whatever. So I think as is, this is confusing and should probably be removed.
___
*[src/BloomExe/app.config, line 42 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYvZ_6H2xWCxKe5T5jy:-MYvZ_6H2xWCxKe5T5jz:bcw0x2a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e02cf0ee160d3e53d20d001c818b6c60e2d662be/src/BloomExe/app.config#L42)):*
> ```
>             <setting name="EnabledExperimentalFeatures" serializeAs="Xml">
>                 <value>
>                     <ArrayOfString xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" />
> ```

This could simply be `serializeAs="string"`. I'll add comments as I go, to see if it's true that this is simpler.
___
*[src/BloomExe/Program.cs, line 47 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYvZsSO7kG42pTsoLyK:-MYvZsSO7kG42pTsoLyL:bwx11lj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e02cf0ee160d3e53d20d001c818b6c60e2d662be/src/BloomExe/Program.cs#L47)):*
> ```Smalltalk
> 	static class Program
> 	{
> 		// It's not clear where these constant strings belong.  They're used in the global program settings,
> ```

Let's go ahead and concentrate all of this system in a single place, using a static `ExperimentalFeatures`.
In the names, please use our "k" prefix standard for constants. No need to use the work "allow", as that's what they all are. So `team-collections`, `experimental-source-books` would be our two current ones.
___
*[src/BloomExe/Program.cs, line 118 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYvZzVYA3hiGEgsLYxg:-MYvZzVYA3hiGEgsLYxh:b-y0k8pp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e02cf0ee160d3e53d20d001c818b6c60e2d662be/src/BloomExe/Program.cs#L118)):*
> ```Smalltalk
> 			LocalizationManager.ReturnOnlyApprovedStrings = !Settings.Default.ShowUnapprovedLocalizations;
> 
> 			// Migrate from old monolithic experimental features setting.
> ```

Seems like this belongs in the section labeled 

`//bring in settings from any previous version`

From there, go ahead and call out to the `ExperimentalFeatures` calls to do actually do this work.
___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 520 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYvdhNA-lF8a8P5TfMD:-MYvdhNA-lF8a8P5TfME:b-ygot1m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e02cf0ee160d3e53d20d001c818b6c60e2d662be/src/BloomExe/Collection/CollectionSettingsDialog.cs#L520)):*
> ```Smalltalk
> 		}
> 
> 		private void _showExperimentalFeatures_CheckedChanged(object sender, EventArgs e)
> ```

This method name is now out of date.
___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 521 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYvdb6o6o0Xb_ySgXdH:-MYvdb6o6o0Xb_ySgXdI:bbgkpdr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e02cf0ee160d3e53d20d001c818b6c60e2d662be/src/BloomExe/Collection/CollectionSettingsDialog.cs#L521)):*
> ```Smalltalk
> 
> 		private void _showExperimentalFeatures_CheckedChanged(object sender, EventArgs e)
> 		{
> ```

How about `ExperimentalFeatures.SetValue(ExperimentalFeatures.kExperimentalSourceBooks, _showExperimentalSourceBooks.Checked)`

Then that `SetValue()` this could become `Settings.Default.EnabledExperimentalFeatures.replace("team-collection","").replace(",,",",);
___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 651 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYvaoB_CBjAI49dqg1D:-MYvaoB_CBjAI49dqg1E:beco1p8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e02cf0ee160d3e53d20d001c818b6c60e2d662be/src/BloomExe/Collection/CollectionSettingsDialog.cs#L651)):*
> ```Smalltalk
> 		private void _allowTeamCollection_CheckedChanged(object sender, EventArgs e)
> 		{
> 			Settings.Default.EnabledExperimentalFeatures.Remove(Program.AllowTeamCollection);
> ```

How about `ExperimentalFeatures.SetValue(ExperimentalFeatures.kTeamCollection, _allowTeamCollection.Checked)`
___
*[src/BloomExe/web/controllers/AppApi.cs, line 21 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYvaSS9CcTy25EyMgjW:-MYvaSS9CcTy25EyMgjX:b-jn8i4d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e02cf0ee160d3e53d20d001c818b6c60e2d662be/src/BloomExe/web/controllers/AppApi.cs#L21)):*
> ```Smalltalk
> 			{
> 				if (request.HttpMethod == HttpMethods.Get)
> 				{
> ```

This can become `request.ReplyWithText(ExperimentalFeatures.TokensOfEnabledFeatures)`

which can then just be `return Settings.Default.EnabledExperimentalFeatures;`

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392)* status: 1 of 15 files reviewed, 9 unresolved discussions (waiting on @hatton)

___
*[src/BloomBrowserUI/bookEdit/js/origami.ts, line 16 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYvYKe--cEbZ6jEDaGS:-MYvj7wqDT4VzTqs65Ut:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e02cf0ee160d3e53d20d001c818b6c60e2d662be/src/BloomBrowserUI/bookEdit/js/origami.ts#L16)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

We can make Widgets not be experimental (I didn't realize that they still are). So then this doesn't have to hit the features api at all.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 231 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYvYmek8y_h8G6fHn99:-MYvkYxA4MsV3DqTdRod:b-r0y2yg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e02cf0ee160d3e53d20d001c818b6c60e2d662be/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L231)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Like your TODO says, we don't have experimental tools, and when we do, it won't have anything to do with "experimental-sources", which are things like templates, not tools. And we won't have an "experimental-tools", either. We will have "grinder" or "table saw" or whatever. So I think as is, this is confusing and should probably be removed.
</blockquote></details>

I left a comment in place along with the call to get the app/enabledExperimentalFeatures as a placeholder to remind us where to place such code.
___
*[src/BloomExe/app.config, line 42 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYvZ_6H2xWCxKe5T5jy:-MYvooiLB5nTM1yvwLtg:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e02cf0ee160d3e53d20d001c818b6c60e2d662be/src/BloomExe/app.config#L42)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This could simply be `serializeAs="string"`. I'll add comments as I go, to see if it's true that this is simpler.
</blockquote></details>

Done.
___
*[src/BloomExe/Program.cs, line 47 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYvZsSO7kG42pTsoLyK:-MYvonuL213eDFq-lONU:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e02cf0ee160d3e53d20d001c818b6c60e2d662be/src/BloomExe/Program.cs#L47)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Let's go ahead and concentrate all of this system in a single place, using a static `ExperimentalFeatures`.
In the names, please use our "k" prefix standard for constants. No need to use the work "allow", as that's what they all are. So `team-collections`, `experimental-source-books` would be our two current ones.
</blockquote></details>

Done.
___
*[src/BloomExe/Program.cs, line 118 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYvZzVYA3hiGEgsLYxg:-MYvor4l0leIz2n1t-HN:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e02cf0ee160d3e53d20d001c818b6c60e2d662be/src/BloomExe/Program.cs#L118)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Seems like this belongs in the section labeled 

`//bring in settings from any previous version`

From there, go ahead and call out to the `ExperimentalFeatures` calls to do actually do this work.
</blockquote></details>

Done.
___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 520 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYvdhNA-lF8a8P5TfMD:-MYvrSz5CS-z4KyfkA-V:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e02cf0ee160d3e53d20d001c818b6c60e2d662be/src/BloomExe/Collection/CollectionSettingsDialog.cs#L520)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This method name is now out of date.
</blockquote></details>

Done.
___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 521 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYvdb6o6o0Xb_ySgXdH:-MYvsNRf7VGpVToIeUo6:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e02cf0ee160d3e53d20d001c818b6c60e2d662be/src/BloomExe/Collection/CollectionSettingsDialog.cs#L521)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

How about `ExperimentalFeatures.SetValue(ExperimentalFeatures.kExperimentalSourceBooks, _showExperimentalSourceBooks.Checked)`

Then that `SetValue()` this could become `Settings.Default.EnabledExperimentalFeatures.replace("team-collection","").replace(",,",",);
</blockquote></details>

Done.
___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 651 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYvaoB_CBjAI49dqg1D:-MYvsn749sO7b3nk55Ji:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e02cf0ee160d3e53d20d001c818b6c60e2d662be/src/BloomExe/Collection/CollectionSettingsDialog.cs#L651)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

How about `ExperimentalFeatures.SetValue(ExperimentalFeatures.kTeamCollection, _allowTeamCollection.Checked)`
</blockquote></details>

Done.
___
*[src/BloomExe/web/controllers/AppApi.cs, line 21 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYvaSS9CcTy25EyMgjW:-MYvw3nO1iwQWApP31fh:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e02cf0ee160d3e53d20d001c818b6c60e2d662be/src/BloomExe/web/controllers/AppApi.cs#L21)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This can become `request.ReplyWithText(ExperimentalFeatures.TokensOfEnabledFeatures)`

which can then just be `return Settings.Default.EnabledExperimentalFeatures;`
</blockquote></details>

Done.

**Comment by andrew-polk** [comment]
___
*[src/BloomExe/ExperimentalFeatures.cs, line 48 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYz_bsM9WV1B3WeYnRj:-MYz_bsM9WV1B3WeYnRk:b-jcvm8h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e498931fcfe189e96e1f6dfc590ddd23f1180f3e/src/BloomExe/ExperimentalFeatures.cs#L48)):*
> ```Smalltalk
> 		{
> 			return Settings.Default.EnabledExperimentalFeatures.Contains(featureName);
> 		}
> ```

Is it feasible to add unit tests?

**Review by hatton — COMMENTED** [review]
> Reviewed 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton and @StephenMcConnel)

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/ExperimentalFeatures.cs, line 48 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYz_bsM9WV1B3WeYnRj:-MYzaFOlCw6xjFl7n5cY:b-75vo8x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e498931fcfe189e96e1f6dfc590ddd23f1180f3e/src/BloomExe/ExperimentalFeatures.cs#L48)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is it feasible to add unit tests?
</blockquote></details>

I'm trying to think what is worth testing. Maybe the boundary conditions of going from some features enabled to no features enabled?

**Comment by andrew-polk** [comment]
___
*[src/BloomExe/ExperimentalFeatures.cs, line 48 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYz_bsM9WV1B3WeYnRj:-MYzbTl6EtOn7oV0_Q7F:b-5ze9vn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e498931fcfe189e96e1f6dfc590ddd23f1180f3e/src/BloomExe/ExperimentalFeatures.cs#L48)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I'm trying to think what is worth testing. Maybe the boundary conditions of going from some features enabled to no features enabled?
</blockquote></details>

I guess the migration is simpler than I assumed. So that's likely not worth it.

Perhaps SetValue on an existing one doesn't add it again.
But it's pretty easy to test the basic functions, so likely worth that. 
This is all assuming unit tests can easily set/get Settings.Default.X

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/ExperimentalFeatures.cs, line 48 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYz_bsM9WV1B3WeYnRj:-MYzsdHV73TH7zVUp8_o:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e498931fcfe189e96e1f6dfc590ddd23f1180f3e/src/BloomExe/ExperimentalFeatures.cs#L48)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I guess the migration is simpler than I assumed. So that's likely not worth it.

Perhaps SetValue on an existing one doesn't add it again.
But it's pretty easy to test the basic functions, so likely worth that. 
This is all assuming unit tests can easily set/get Settings.Default.X
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
Note, I didn't do a full review. 
JH approved and Steve addressed the unit test I brought up, so I'm merging.

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-:-MYzxmRDDxk2oKAWtcPs:b-g70luv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

___
*[src/BloomTests/ExperimentalFeaturesTests.cs, line 14 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4392#-MYzxdWXD4Cxqp-WR3jP:-MYzxdWXD4Cxqp-WR3jQ:b-ue7auz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71039e8322c88fa0089872b60f8409c755ee67bc/src/BloomTests/ExperimentalFeaturesTests.cs#L14)):*
> ```Smalltalk
> 		/// </summary>
> 		[Test]
> 		public void SetValueWorksProperly()
> ```

I would have made this a series of tests, but I'm not going to hold things up.

**Pull request merged**
