### PR TITLE
remove a small bit of JQuery

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6060)

### CODE REVIEW

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6060)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[`src/BloomBrowserUI/bookEdit/js/bloomEditing.ts` line 1280 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6060#-Nc3SRcm69itn03T1nLi:-Nc3SRcm69itn03T1nLj:b-4214aa) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/320818597ff7b1aa8ddc202ac0fbfb787d7b0c0e/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L1280)):*
> ```XML
>     const marginBox = $(".marginBox");
>     marginBox.removeClass("origami-layout-mode");
>     marginBox.find(".bloom-translationGroup .textBox-identifier").remove();
> ```

I know it seems odd to take this out, but I couldn't find anything in file history to explain why it's here. As near as I can tell, `.textBox-identifier` is always a sibling of a translation-Group, not a child. And besides, it has the `bloom-ui` class which guarantees it will get deleted before saving anyway.

If we want to keep something similar, I would just delete all `.textBox-identifier` elements and not bother about looking for translation-groups.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6060)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/bookEdit/js/bloomEditing.ts` line 1278 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6060#-Nc3Wsu87bofc5Kd2pLJ:-Nc3Wsu87bofc5Kd2pLK:b38wlhj) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3f759a82d82874e41efc6b8a5c30b532a752c2c6/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L1278)):*
> ```XML
> // [GJM: But this doesn't call saveChangesAndRethinkPageEvent! I'm confused.]
> export const pageSelectionChanging = () => {
>     const marginBox = document.getElementsByClassName("marginBox")[0];
> ```

I guess there's only ever one marginBox in the dom in this context?
(The previous code would operate on all of them; the new code only operates on the first one.)
Maybe worth a comment.
___
*[`src/BloomBrowserUI/bookEdit/js/bloomEditing.ts` line 1280 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6060#-Nc3SRcm69itn03T1nLi:-Nc3WhTM1K5HnS_vSWA-:bvswkka) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/320818597ff7b1aa8ddc202ac0fbfb787d7b0c0e/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L1280)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I know it seems odd to take this out, but I couldn't find anything in file history to explain why it's here. As near as I can tell, `.textBox-identifier` is always a sibling of a translation-Group, not a child. And besides, it has the `bloom-ui` class which guarantees it will get deleted before saving anyway.

If we want to keep something similar, I would just delete all `.textBox-identifier` elements and not bother about looking for translation-groups.
</blockquote></details>

Indeed, in origami.ts -> layoutToggleClickHandler(), we have 
```
        marginBox.removeClass("origami-layout-mode");
        marginBox.find(".textBox-identifier").remove();
```
So probably worth changing this one to that instead of removing it.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6060)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/js/bloomEditing.ts` line 1278 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6060#-Nc3Wsu87bofc5Kd2pLJ:-Nc3n503DaYJSapbKc80:bp2wtp8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3f759a82d82874e41efc6b8a5c30b532a752c2c6/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L1278)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I guess there's only ever one marginBox in the dom in this context?
(The previous code would operate on all of them; the new code only operates on the first one.)
Maybe worth a comment.
</blockquote></details>

Done. Document here is the page memsim html thingy.
___
*[`src/BloomBrowserUI/bookEdit/js/bloomEditing.ts` line 1280 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6060#-Nc3SRcm69itn03T1nLi:-Nc3nBQWBFH-Ppk1QBMs:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/320818597ff7b1aa8ddc202ac0fbfb787d7b0c0e/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L1280)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Indeed, in origami.ts -> layoutToggleClickHandler(), we have 
```
        marginBox.removeClass("origami-layout-mode");
        marginBox.find(".textBox-identifier").remove();
```
So probably worth changing this one to that instead of removing it.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
Thanks!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6060#-:-Nc3qC9F9uwMwWH0T8ok:b-ucfknh)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
