### PR TITLE
Record Video handles arbitrary number of files (BL-11926)

### PR DESCRIPTION
**Pull request by jsubloom**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5648)

### CODE REVIEW

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5648)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 44 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5648#-NOWbIaj6arh6N5jS1uB:-NOWbIaj6arh6N5jS1uC:b-bz3zzi) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4b92644fce01f92b52cdd41055f464a531352441/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L44)):*
> ```Smalltalk
> 		private string _ffmpegPath;
> 		private TempFile _htmlFile;
> 		private TempFile _initialVideo;
> ```

You could also review Commit 2 separately (in GitHub). Some parts of the diff might be easier.

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5648)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 860 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5648#-NOWbdkJE7RjYa2jrI2d:-NOWbdkJE7RjYa2jrI2e:bte38ng) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4b92644fce01f92b52cdd41055f464a531352441/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L860)):*
> ```Smalltalk
> 				// Note: I feel like currentIterationProgress isn't that accurate.
> 				// (It reads the -progress file, but maybe that file isn't flushed often enough, or maybe it's non-linear...)
> 				// We could consider outputting the estimate only once per iteration, instead of via a timer.
> ```

Maybe we really should?

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5648)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 860 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5648#-NOWbdkJE7RjYa2jrI2d:-NOkSmMt0K7cAKuWLBIi:b-cfghh9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4b92644fce01f92b52cdd41055f464a531352441/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L860)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

Maybe we really should?
</blockquote></details>

But, then it's not predictable when the first or next time remaining estimate will be printed out.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
It's somewhat difficult to see what has changed, as some stuff has really moved. I've commented some minor things, but I think the only big one is what we discussed, that we should try to merge batches of 1000 and then combine those in one pass, so that no one audio segment gets processed more than twice.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5648#-:-NOkiW-a-I8o7_JJ-iAC:b-kg8q6f)* status: all files reviewed, 6 unresolved discussions (waiting on @jsubloom)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 508 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5648#-NOkUxdHABMjwJ1uunP4:-NOkUxdHABMjwJ1uunP5:b-accto0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4b92644fce01f92b52cdd41055f464a531352441/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L508)):*
> ```Smalltalk
> 			// configure ffmpeg to merge everything.
> 
> 			const int batchSize = 1000;	// If batch size is too large (e.g. 2500), ffmpeg will have "too many open files" error
> ```

Maybe say explicitly that there is a limit of 2900 based on our best effort to shorten the command line, but even apart from that ffmpeg has a problem somewhere between 1000 and 2500?
___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 771 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5648#-NOk_3jrDkxTkaDdU_yr:-NOk_3jrDkxTkaDdU_ys:b-90rwcq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4b92644fce01f92b52cdd41055f464a531352441/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L771)):*
> ```Smalltalk
> 			                    // by reducing it to 1/n where n is the total number of input streams.
> 								//
> 								// If merging the audio in passes (to avoid exceeding the CreateProcess limit),
> ```

This sounds like yet another limit. Let's standardize on one way of describing the problem, or just say "to avoid the limit on how many inputs we can handle".
___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 867 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5648#-NOkZZ0ZAVn8oXZs396X:-NOkZZ0ZAVn8oXZs396Y:b4no080) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4b92644fce01f92b52cdd41055f464a531352441/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L867)):*
> ```Smalltalk
> 				var timeSoFar = DateTime.Now - startTime;
> 
> 				double timePerIterationSoFar = timeSoFar.TotalMilliseconds / iterationsSoFar;
> ```

Are you satisfied that iterationsSoFar can't possibly be zero? Say if the first thing it needed to copy was a very large video? (Might not be a new problem...)
___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 901 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5648#-NOkYAiAEz3gQpA0HwSS:-NOkYAiAEz3gQpA0HwST:b-muhaip) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4b92644fce01f92b52cdd41055f464a531352441/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L901)):*
> ```Smalltalk
> 				// If progress=end, the process has finished and there is no point in estimating
> 				if (GetLastOccurenceOfKeyValue(progressFileContents, "progress", out string progressValue) && progressValue == "end")
> 					return 0;	// numIterationsDone should be updated instead.
> ```

This is not a 'todo', right? That is, some existing code is GOING to update that in this situation.

**Review by jsubloom — COMMENTED** [review]
That is a smart idea, but we discussed and decided that the extra dev time and code complexity was not worth it right now, given that it wouldn't make any difference unless huge number of files were involved.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5648#-:-NRKpiQm4AXjh4a7GMxR:b11o7qt)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 508 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5648#-NOkUxdHABMjwJ1uunP4:-NRKx7SK5BFFMevhGwnH:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4b92644fce01f92b52cdd41055f464a531352441/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L508)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Maybe say explicitly that there is a limit of 2900 based on our best effort to shorten the command line, but even apart from that ffmpeg has a problem somewhere between 1000 and 2500?
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 771 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5648#-NOk_3jrDkxTkaDdU_yr:-NRKxJx09dETdtpwjptZ:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4b92644fce01f92b52cdd41055f464a531352441/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L771)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This sounds like yet another limit. Let's standardize on one way of describing the problem, or just say "to avoid the limit on how many inputs we can handle".
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 867 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5648#-NOkZZ0ZAVn8oXZs396X:-NRKydbW8mbEl-J-J_O7:b-7g0ct8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4b92644fce01f92b52cdd41055f464a531352441/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L867)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Are you satisfied that iterationsSoFar can't possibly be zero? Say if the first thing it needed to copy was a very large video? (Might not be a new problem...)
</blockquote></details>

Hmm... hopefully some progress would've been made by now, but I suppose we can't guarantee it. Fixed.
___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 901 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5648#-NOkYAiAEz3gQpA0HwSS:-NRKz5B60MHxZbIZcVuM:b-ht0ukm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4b92644fce01f92b52cdd41055f464a531352441/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L901)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This is not a 'todo', right? That is, some existing code is GOING to update that in this situation.
</blockquote></details>

That's right.

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5648)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 860 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5648#-NOWbdkJE7RjYa2jrI2d:-NRdr1YZ90GAFEgrivWv:bhb7g12) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4b92644fce01f92b52cdd41055f464a531352441/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L860)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

But, then it's not predictable when the first or next time remaining estimate will be printed out.
</blockquote></details>

idk, it's too inaccurate to let it slide.  Other ways of estimating weren't that great either. This attempt instead prioritizes printing the progress percent (every 5 minutes, same timing as before), which to me feels like a less irritating user experience.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5648)* status: all files reviewed, 1 unresolved discussion

**Comment by JohnThomson** [comment]
LGTM, but has conflicts

**Review by JohnThomson — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5648)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
