### PR TITLE
Add link label to collect and insert image credits (BL-4222)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1465)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/editablePage.ts, line 82 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1465#-Kc3j35bnQFehAOiUsBv:-Kc3j35bnQFehAOiUsBw:b-fvwi0r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b20b5a5c426d868628c505dfb3e1eaa0d4359425/src/BloomBrowserUI/bookEdit/editablePage.ts#L82)):*
> ```XML
> //PasteImageCredits() is called by a script tag on a <a> element in a tooltip
> window['PasteImageCredits'] = () => {
>         EditableDivUtils.pasteImageCredits();
> ```

Looks like two indents on this line. Not a big deal, but I'm wondering why it occurred. (i.e. Do we need to look into our formatting settings some more?) What editor were you using?

---

*[src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts, line 138 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1465#-Kc3kHmY0yXFv8nBPZh3:-Kc3kHmY0yXFv8nBPZh4:b-tzfpae) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b20b5a5c426d868628c505dfb3e1eaa0d4359425/src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts#L138)):*
> if (data

If there is any expectation that data might be available here, a slight performance improvement would be to return immediately at the beginning of the function.
If this is just a sanity check, don't worry about it.

---

*[src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug, line 165 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1465#-Kc3kiSxjWacabQCdzTB:-Kc3kiSxjWacabQCdzTC:bh57lkc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b20b5a5c426d868628c505dfb3e1eaa0d4359425/src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug#L165)):*
> link-text

By convention, I think these non-standard attributes usually begin with "data-"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1465)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts, line 129 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1465#-Kc3qsx96G64gC-080mh:-Kc3qsx96G64gC-080mi:b-qvv7ax) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b20b5a5c426d868628c505dfb3e1eaa0d4359425/src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts#L129)):*
> ```XML
>             var divs = contribs.getElementsByTagName('div');
>             var artists;
>             for (var i = 0; i < divs.length; ++i) {
> ```

I don't understand what all this code is doing. Why is it not as simple as on line that literally just pastes in result.data (which the c# would not need to wrap in a div)?

---

*[src/BloomExe/web/controllers/ImageApi.cs, line 64 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1465#-Kc3pdfDbPcnQixwPQD3:-Kc3pdfDbPcnQixwPQD4:b-bqxu6v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b20b5a5c426d868628c505dfb3e1eaa0d4359425/src/BloomExe/web/controllers/ImageApi.cs#L64)):*
> ```Smalltalk
> 			if (missingCredits.Count > 0)
> 			{
> 				Console.WriteLine("The following images do not have any credit/copyright information:");
> ```

I like the idea of letting the user know, very much. Of course the user is never going to see the output of Console.Writeline().  I see two choices: create a toast, or paste in notices of the missing stuff. I'm leaning towards the latter. Go ahead and make it concise: "Missing credits: image1.png, image 4.jpg".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1465)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/editablePage.ts, line 82 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1465#-Kc3j35bnQFehAOiUsBv:-Kc3yybtsJRjTwtsR1dP:b-y9ncsx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b20b5a5c426d868628c505dfb3e1eaa0d4359425/src/BloomBrowserUI/bookEdit/editablePage.ts#L82)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like two indents on this line. Not a big deal, but I'm wondering why it occurred. (i.e. Do we need to look into our formatting settings some more?) What editor were you using?
</blockquote></details>

Done.  I'm not sure how it happened.  I've been using VSCode on Linux.  (and sometimes emacs)

---

*[src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts, line 129 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1465#-Kc3qsx96G64gC-080mh:-Kc4DXUL4nfDJZ_6M2_k:bumo0sw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b20b5a5c426d868628c505dfb3e1eaa0d4359425/src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts#L129)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I don't understand what all this code is doing. Why is it not as simple as on line that literally just pastes in result.data (which the c# would not need to wrap in a div)?
</blockquote></details>

I've added some commentary explaining what the code is doing.  If there's a simpler way to find the right location and insert the credits, I'd be happy to learn what it is.

---

*[src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts, line 138 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1465#-Kc3kHmY0yXFv8nBPZh3:-Kc3uJ99Mcg_i6hvKe5a:birwuuv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b20b5a5c426d868628c505dfb3e1eaa0d4359425/src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts#L138)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> if (data

If there is any expectation that data might be available here, a slight performance improvement would be to return immediately at the beginning of the function.
If this is just a sanity check, don't worry about it.
</blockquote></details>

Done.  I've changed the C# code so that data is empty if the user hasn't inserted any pictures.

---

*[src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug, line 165 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1465#-Kc3kiSxjWacabQCdzTB:-Kc3uBVV1ZNtTyWj2E9n:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b20b5a5c426d868628c505dfb3e1eaa0d4359425/src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug#L165)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> link-text

By convention, I think these non-standard attributes usually begin with "data-"
</blockquote></details>

Done.

---

*[src/BloomExe/web/controllers/ImageApi.cs, line 64 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1465#-Kc3pdfDbPcnQixwPQD3:-Kc3z9xy6iJgnoBfbL0g:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b20b5a5c426d868628c505dfb3e1eaa0d4359425/src/BloomExe/web/controllers/ImageApi.cs#L64)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I like the idea of letting the user know, very much. Of course the user is never going to see the output of Console.Writeline().  I see two choices: create a toast, or paste in notices of the missing stuff. I'm leaning towards the latter. Go ahead and make it concise: "Missing credits: image1.png, image 4.jpg".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1465)*

**Comment by andrew-polk** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1465)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts, line 129 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1465#-Kc3qsx96G64gC-080mh:-KcKF3bEsPO99A5Rgdqx:b-mkxae4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b20b5a5c426d868628c505dfb3e1eaa0d4359425/src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts#L129)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I've added some commentary explaining what the code is doing.  If there's a simpler way to find the right location and insert the credits, I'd be happy to learn what it is.
</blockquote></details>

Ah, yeah, I see. Ok, so the bubble does know what it is pointing at.  The bubble stores  a key in its "aria-describedby" attribute. Remove "-content" from that, and you have the tooltipId. Then look for a div which an "aria-describedby" that has that tooltipId. That's the div this bubble is pointing at. You can then remove these three attributes from the query. This will probably end up being a useful reusable bit of code to add to bloomQtipUtils (if qtip library itself doesn't already have such a thing).

If we didn't have this pointer from the qtip to the box, a good query to find the div would be something like $(contribs).find('div.bloom-visibility-code-on');  That will break if we ever display more than one language for this field. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1465)*

**Pull request merged**
