### PR TITLE
Add missing languages to BloomLibrary.AudioLangs (BL-11784)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5551)

### CODE REVIEW

**Review by jsubloom — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5551)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs` line 326 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5551#-NHQ5S-S-6hvIrhtG3YV:-NHQ5S-T69MGHXS-9ESn:b-hoytrm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/897124c429d7b6927b9cf4657cc53dc910c779d6/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L326)):*
> ```Smalltalk
> 			foreach (var langCode in allLangCodes)
> 			{
> 				if (!bookInfo.PublishSettings.BloomLibrary.AudioLangs.TryGetValue(langCode, out InclusionSetting _))
> ```

It seems like we could just use ContainsKey instead, which would also be (slightly) easier to grok.

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5551)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs` line 317 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5551#-NHQ892k7Mc6L0Z93Gdm:-NHQ892k7Mc6L0Z93Gdn:b-e5s1l0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/897124c429d7b6927b9cf4657cc53dc910c779d6/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L317)):*
> ```Smalltalk
> 			// any time we find a new language, even if it was previously off. So it seems better to copy
> 			// the setting from an arbitrary current language if any; if there are none, then we go with
> 			// the old default. For now, this will keep the old value of the setting. If we enhance the UI
> ```

Ok, i'll buy it.



_Code quote:_
```Smalltalk
			// any time we find a new language, even if it was previously off. So it seems better to copy
			// the setting from an arbitrary current language if any; if there are none, then we go with
			// the old default. For now, this will keep the old value of the setting. If we enhance the UI
```

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5551)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[`src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs` line 326 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5551#-NHQ5S-S-6hvIrhtG3YV:-NHV7Fq27wT949T5IFUm:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/897124c429d7b6927b9cf4657cc53dc910c779d6/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L326)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

It seems like we could just use ContainsKey instead, which would also be (slightly) easier to grok.
</blockquote></details>

Done.

**Review by jsubloom — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5551)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
