### PR TITLE
API work

### PR DESCRIPTION
**Pull request by hatton**
Covers BL-3229 and BL-3318

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1020)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Looks generally (very!) good. Various minor points...happy to leave it to your judgement which are worth doing something about.

---

Reviewed 65 of 65 files at r1.
Review status: all files reviewed at latest revision, 21 unresolved discussions, some commit checks failed.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/decodableReader.ts, line 224 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFL0Y5HZbwD7ssngn8B:-KFL0Y5HZbwD7ssngn8C:-1632614484) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/26c0076f15e277961393b8569986f50283002660/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/decodableReader.ts#L224)):*
is this no longer true? I find it useful to comment things that are called by C# code, because tools won't find those callers.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 754 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFL1Inj95H4fqsmbv9m:-KFL1Inj95H4fqsmbv9n:-400682180) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L754)):*
'The return' => result.data? (just slightly clearer)

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 895 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFL1zEWsqKuke8zKAqC:-KFL1zEWsqKuke8zKAqD:56953856) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L895)):*
is this reviewslog obsolete?

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 897 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFL2CAqUFZINxi4T4C2:-KFL2CAqUFZINxi4T4C3:-27593517) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L897)):*
I have a vague recollection that a few other delimiters are also supported...probably doesn't matter

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 957 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFL2TGwZJ1Iy1hIiHka:-KFL2TGwZJ1Iy1hIiHkb:-895282026) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L957)):*
Feels like another place to insert a custom do-nothing transform (rather than transforming twice)

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 1128 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFL3SdI66aKe0_BPKk5:-KFL3SdI66aKe0_BPKk6:-1048358515) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L1128)):*
If there's somewhere we keep track of technical debt, the fact that half the ReaderToolsModel methods are static, and the other half instance methods always invoked on the singleton ReaderToolsModel.model, should be high on the list to fix.

More important: is it safe to use a forEach iteration variable inside a 'then'? Seems like I've read about similar cases where all the 'then's share a single instance of index, which has the final value by the time the then blocks start executing...if so the old code had the same problem, but it seemed worth drawing attention to, if only so I can learn something.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerSetup/readerSetup.io.ts, line 132 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFL4qiW9BDShEIzYCYG:-KFL4qiW9BDShEIzYCYH:594843208) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerSetup/readerSetup.io.ts#L132)):*
The old code implies that callback could be null...is that intentionally no longer allowed?

---

*[src/BloomExe/ApplicationUpdateSupport.cs, line 274 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFL6dnLtvgsTEFDkCi5:-KFL6dnLtvgsTEFDkCi6:-401855741) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomExe/ApplicationUpdateSupport.cs#L274)):*
I don't think you meant to check in this change. There's a change set out there somewhere which adds a ToString below to make version work in the String.Format.

---

*[src/BloomExe/Browser.cs, line 406 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFL7TERaQfS0CJMBo0g:-KFL7TERaQfS0CJMBo0h:41877740) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomExe/Browser.cs#L406)):*
Cool discovery! Thank you!!

---

*[src/BloomExe/Edit/AudioRecording.cs, line 509 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFL9olovE_kHGpQGAhx:-KFL9olovE_kHGpQGAhy:-1818255580) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/26c0076f15e277961393b8569986f50283002660/src/BloomExe/Edit/AudioRecording.cs#L509)):*
If the comment above is right, it will typically be a server thread that asks for this to be created...I don't remember why I thought it should be created on the UI thread, but this makes me nervous...did you have a particular reason for thinking it not needed?

---

*[src/BloomExe/web/EndpointHandler.cs, line 21 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFLYViu_ZvIgs3ZY241:-KFLYViu_ZvIgs3ZY242:-1139457176) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomExe/web/EndpointHandler.cs#L21)):*
It's annoying that this public (and fairly widely used, at least in this PR) class is not defined in a file of the same name. I had trouble finding it when I wanted to come back and recheck something during the review.

---

*[src/BloomExe/web/EndpointHandler.cs, line 72 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFLIsKxUWeEEFng_Hrb:-KFLIsKylimtsBk_Tuqg:-2064645873) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomExe/web/EndpointHandler.cs#L72)):*
Minor quibble, but it's not obvious this is always a settings object...content? reply?

---

*[src/BloomExe/web/EndpointHandler.cs, line 92 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFLJJwVWT58ZuC6FfnU:-KFLJJwVWT58ZuC6FfnV:561128097) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomExe/web/EndpointHandler.cs#L92)):*
This is starting to show up a repeatedly. Is there a good place we could put a static method like BloomApplication.RunningUnitTests? Adds clarity, removes need for comment, and if they change nunit so this doesn't work we have one thing to fix. Plus, we can find all callers to discover all the places we are forced into special behavior while testing.

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 72 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFLMNsK77F8yEUKGdLo:-KFLMNsK77F8yEUKGdLp:1739484821) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomExe/web/EnhancedImageServer.cs#L72)):*
Marginally more efficient to put the ToLower() here.

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 203 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFLMURjy3CkbY4lmlua:-KFLMURjy3CkbY4lmlub:-201680308) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomExe/web/EnhancedImageServer.cs#L203)):*
Should use ToLowerInvariant (otherwise something nasty happens if key contain 'I' in Turkey)

---

*[src/BloomExe/web/ReadersApi.cs, line 117 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFLQwEn4BHvMCKcb8F1:-KFLQwEn4BHvMCKcb8F2:-957898161) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomExe/web/ReadersApi.cs#L117)):*
To be consistent with what you did for saveReaderToolSettings, this should lose the 'save', I think?

---

*[src/BloomExe/web/ReadersApi.cs, line 121 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFLR9p7caqQJIisNpiL:-KFLR9p7caqQJIisNpiM:1562088673) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomExe/web/ReadersApi.cs#L121)):*
Again, in the spirit of what you are doing, it seems to me the 'make' should go. The client doesn't know that the server has to 'make' the list, it just wants it.

---

*[src/BloomExe/web/ReadersApi.cs, line 136 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFLSCBnwY659R0ldgWk:-KFLSCBnwY659R0ldgWl:608540751) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomExe/web/ReadersApi.cs#L136)):*
case doesn't obviously succeed or fail or reply...I suppose ChooseAllowedWordListFile does so? Yes, I see it does...but it would be more elegant if it returned the text and you replied with it here. More consistent with other cases, and I think the method wouldn't even need the parameter...not a big deal, nor a new problem, but as long as you're cleaning all this up...

---

*[src/BloomExe/web/ReadersApi.cs, line 156 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFLSY6YLm2LNdQDeE6n:-KFLSY6YLm2LNdQDeE6o:-1930157919) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomExe/web/ReadersApi.cs#L156)):*
no 'return's above, so it looks as if every case will end up here

---

*[src/BloomTests/web/EndpointHandlerTests.cs, line 63 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFLVl5OaddRczqAwnZM:-KFLVl5OaddRczqAwnZN:1076261564) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomTests/web/EndpointHandlerTests.cs#L63)):*
EndPoint (with a D)

---

*[src/BloomTests/web/EndpointHandlerTests.cs, line 69 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFLW1_RCp0JQwEYlVn7:-KFLW1_RCp0JQwEYlVn8:-211635613) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomTests/web/EndpointHandlerTests.cs#L69)):*
If you can stand it, it would be nice to test that case is ignored and that keys that are nontrivial regular expressions work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-:-KFLZLRcpDW22tD4DStt:1508217297)*

**Comment by hatton** [comment]
Review status: 56 of 62 files reviewed at latest revision, 21 unresolved discussions, some commit checks failed.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/decodableReader.ts, line 224 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFL0Y5HZbwD7ssngn8B:-KFLgI7qZKomYTNdmZjR:1841142951) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/26c0076f15e277961393b8569986f50283002660/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/decodableReader.ts#L224)):*
Yes, it is no longer true. We are trying to stop that madness :-)

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 895 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFL1zEWsqKuke8zKAqC:-KFLh-1rAq2pschocdCJ:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L895)):*
Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 957 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFL2TGwZJ1Iy1hIiHka:-KFLhJWkPByF3M1A_e0s:573015856) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L957)):*
Not following you. 

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 1128 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFL3SdI66aKe0_BPKk5:-KFLhV6h7BlW_bO3dA0b:-1614804768) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L1128)):*
> If there's somewhere we keep track of technical debt, the fact that half the ReaderToolsModel methods are static, and the other half instance methods always invoked on the singleton ReaderToolsModel.model, should be high on the list to fix.

When we see debt we want fixed, we go fix it or get it on the Kanban.  I find the nice purple "TechnicalDebt" flag motivating:




> More important: is it safe to use a forEach iteration variable inside a 'then'? 

``stages.forEach(function(stage, index)`` gives us a javascript closure, so we're good inside that immediate context.  Now, moving on to the context of the ``then`` I can't prove it, but if closures didn't reach in there, I think I would have had errors in many places, so I'm assuming that's correct.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerSetup/readerSetup.io.ts, line 132 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFL4qiW9BDShEIzYCYG:-KFLlryI6nSU6_ysWFXj:-1366213946) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerSetup/readerSetup.io.ts#L132)):*
It was never null, so it was wasted code/complexity.

---

*[src/BloomExe/Edit/AudioRecording.cs, line 509 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFL9olovE_kHGpQGAhx:-KFLmTtC2Nqxk5ChtQgP:1206148860) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/26c0076f15e277961393b8569986f50283002660/src/BloomExe/Edit/AudioRecording.cs#L509)):*
All of these API request handlers are nowadays called on the UI thread by ``ApiRequest.Handle``, unless unit testing is detected. So no need for individual ones to do that. BTW Form.ActiveForm will be null if you're in some other window at the time this runs, which is how I noticed this was here.

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 203 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFLMURjy3CkbY4lmlua:-KFLo1oiDxDI8vF1N8j1:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomExe/web/EnhancedImageServer.cs#L203)):*
Done.

---

*[src/BloomExe/web/ReadersApi.cs, line 121 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFLR9p7caqQJIisNpiL:-KFLoBKCg2r4esdG7lrU:-357622563) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomExe/web/ReadersApi.cs#L121)):*
Nah, on this one we really are making a file for the user. This is not a request by the client.

---

*[src/BloomExe/web/ReadersApi.cs, line 156 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFLSY6YLm2LNdQDeE6n:-KFLozU1NwbcDfGNE_nW:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomExe/web/ReadersApi.cs#L156)):*
Done.

---

*[src/BloomTests/web/EndpointHandlerTests.cs, line 63 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFLVl5OaddRczqAwnZM:-KFLpzlND9isJA1dhslf:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomTests/web/EndpointHandlerTests.cs#L63)):*
Done.

---

*[src/BloomExe/ApplicationUpdateSupport.cs, line 274 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFL6dnLtvgsTEFDkCi5:-KFLmDrOZAuHCzhDrs1M:-607047664) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomExe/ApplicationUpdateSupport.cs#L274)):*
True! It doesn't compile without it, but will, presumably, when merged.

---

*[src/BloomExe/web/EndpointHandler.cs, line 21 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFLYViu_ZvIgs3ZY241:-KFLn3r5QI3KORRXK2LU:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomExe/web/EndpointHandler.cs#L21)):*
Done.

---

*[src/BloomExe/web/EndpointHandler.cs, line 72 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFLIsKxUWeEEFng_Hrb:-KFLnTXQ-Xe0kWJ4_aSb:-925700613) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomExe/web/EndpointHandler.cs#L72)):*
thanks. Artifact of refactoring tool.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020)*

**Comment by JohnThomson** [comment]
Review status: 56 of 62 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 957 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFL2TGwZJ1Iy1hIiHka:-KFN0WuGgdMSBUcvyb7s:290646520) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L957)):*
In a couple of places, where axios converts what we want to be a string into an object, we insert a do-nothing function that replaces the automatic input processing. Can't we do that here instead of letting axios convert the string to an object and then converting it back?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020)*

**Comment by hatton** [comment]
It was causing problems, having this branch open, so it's now merged into master. But there are some comments as yet un-dealt with, so I'm leaving the PR open.

**Comment by hatton** [comment]
Review status: 56 of 62 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, line 754 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFL1Inj95H4fqsmbv9m:-KHWkYKfWj5whQbnGRIi:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts#L754)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary>
> 'The return' => result.data? (just slightly clearer)</details>
Done.

---

*[src/BloomExe/web/ApiRequest.cs, line 92 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFLJJwVWT58ZuC6FfnU:-KHWjzro_ro0vtfiVuwk:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomExe/web/ApiRequest.cs#L92)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary>
> This is starting to show up a repeatedly. Is there a good place we could put a static method like BloomApplication.RunningUnitTests? Adds clarity, removes need for comment, and if they change nunit so this doesn't work we have one thing to fix. Plus, we can find all callers to discover all the places we are forced into special behavior while testing.</details>
Done.

---

*[src/BloomExe/web/ReadersApi.cs, line 117 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFLQwEn4BHvMCKcb8F1:-KHWg-l6s8bXBmKGOGIg:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomExe/web/ReadersApi.cs#L117)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary>
> To be consistent with what you did for saveReaderToolSettings, this should lose the 'save', I think?</details>
Done.

---

*[src/BloomExe/web/ReadersApi.cs, line 136 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFLSCBnwY659R0ldgWk:-KHWi9LB3xJTKNe_F2zI:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomExe/web/ReadersApi.cs#L136)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary>
> case doesn't obviously succeed or fail or reply...I suppose ChooseAllowedWordListFile does so? Yes, I see it does...but it would be more elegant if it returned the text and you replied with it here. More consistent with other cases, and I think the method wouldn't even need the parameter...not a big deal, nor a new problem, but as long as you're cleaning all this up...</details>
Done.

---

*[src/BloomTests/web/EndpointHandlerTests.cs, line 69 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020#-KFLW1_RCp0JQwEYlVn7:-KHf5Y6QSkpYyO6yWqxg:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a8f8f0ce311eca2d1e5a4a544bea65eda7c75e0a/src/BloomTests/web/EndpointHandlerTests.cs#L69)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary>
> If you can stand it, it would be nice to test that case is ignored and that keys that are nontrivial regular expressions work.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1020)*

**Comment by hatton** [comment]
Did more improvements based on these commens in PR 1061. CLosing this now

**Pull request closed without merging**
