### PR TITLE
Collection Menu Affordance (BL-10943)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4998)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4998)* status: 0 of 10 files reviewed, 1 unresolved discussion

___
*[src/BloomExe/Properties/Resources.Designer.cs, line 439 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4998#-MwlgEavAlhGrbcniOci:-MwlgEavAlhGrbcniOcj:b-grb121) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5304f119eeb7bda7dc9c44d71900dea7f4214d29/src/BloomExe/Properties/Resources.Designer.cs#L439)):*
> ```Smalltalk
>         ///   Looks up a localized resource of type System.Drawing.Bitmap.
>         /// </summary>
>         internal static System.Drawing.Bitmap greyTriangleButton {
> ```

I deleted the PNG file too. Hope this is ok.

By the way, there are other images loaded here in this file that VS says 0 references for.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4998)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx, line 87 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4998#-MwlpMftCbHAFbTjfxfr:-MwlpMftCbHAFbTjfxfs:bgikm2l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/335ef0d8ae1661ea27a604f5d414ae2ea89e7b40/src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx#L87)):*
> ```XML
> 
>     const handleCollectionMenuClick = (
>         event: any // React.MouseEvent<HTMLAnchorElement>   // TODO: Figure me out
> ```

todone?



_Code quote:_
```XML
// TODO: Figure me out
```

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4998)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx, line 87 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4998#-MwlpMftCbHAFbTjfxfr:-Mwm54AZ05tgLoit7w9I:bgyjg6b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/335ef0d8ae1661ea27a604f5d414ae2ea89e7b40/src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx#L87)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

todone?
</blockquote></details>

Ah, it's an HTMLButtonElement now.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4998)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Pull request merged**
