### PR TITLE
Fix ProgressDialog not closing/opening properly (BL-12140)

### PR DESCRIPTION
**Pull request by jsubloom**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5810)

### CODE REVIEW

**Review by jsubloom — COMMENTED** [review]
FYI, there are 2 commits in the PR. You may find it easier to review the schema change separately

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5810#-:-NUS8-xn3nyiqC5BtyBz:birf2i3)* status: 0 of 6 files reviewed, 5 unresolved discussions

___
*[`src/BloomBrowserUI/.eslintrc.js` line 44 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5810#-NUS88gC23y61XmUY79b:-NUS88gC23y61XmUY79c:b66c3q) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/157b820fdd95dd31307631ff768cca26978ae877/src/BloomBrowserUI/.eslintrc.js#L44)):*
> ```JavaScript
>         "@typescript-eslint/no-unused-vars": [
>             "warn",
>             { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }
> ```

I tryiedto use "_" as a unused placeholder name in one place, but the linter still wasn't happy with me until i changed these settings.
___
*[`src/BloomBrowserUI/react_components/Progress/ProgressDialog.tsx` line 47 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5810#-NUS8XOE5_4DQfK7f_SN:-NUS8XOE5_4DQfK7f_SO:b-kih90l) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/157b820fdd95dd31307631ff768cca26978ae877/src/BloomBrowserUI/react_components/Progress/ProgressDialog.tsx#L47)):*
> ```XML
> 
> /**
>  * The schema for the websocket data that EmbeddedProgressDialog is expecting
> ```

The reason I did this is because presumably the websocket is surely not passing implementaitons for onClose, onCancel, onReadyToReceive, etc. over JSON... right?

(I mean, it's probably theoretically possible with a some custom parsing, but...)
___
*[`src/BloomBrowserUI/react_components/Progress/ProgressDialog.tsx` line 62 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5810#-NUS8uLe2ooCeXrB1lhb:-NUS8uLe2ooCeXrB1lhc:b6aze8y) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/157b820fdd95dd31307631ff768cca26978ae877/src/BloomBrowserUI/react_components/Progress/ProgressDialog.tsx#L62)):*
> ```XML
> 
>     dialogEnvironment?: IBloomDialogEnvironmentParams;
>     determinate?: boolean;
> ```

determinate and size could theoretically go in IProgressDialogConfig, but BrowserProgrsesDialog.cs does not currently specify them as far as I can tell.
___
*[`src/BloomBrowserUI/react_components/Progress/ProgressDialog.tsx` line 71 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5810#-NUS91b9Ewfd7HNUT70e:-NUS91b9Ewfd7HNUT70f:b16j9p6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/157b820fdd95dd31307631ff768cca26978ae877/src/BloomBrowserUI/react_components/Progress/ProgressDialog.tsx#L71)):*
> ```XML
>         closeDialog,
>         propsForBloomDialog
>     } = useSetupBloomDialog(props.dialogEnvironment); // TODO: Think harder about initiallyOpen
> ```

Oops... I still need to work on this.
___
*[`src/BloomBrowserUI/react_components/Progress/ProgressDialog.tsx` line 407 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5810#-NUS9Alk9ABNNq4XHU-v:-NUS9Alk9ABNNq4XHU-w:b-zijmne) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/157b820fdd95dd31307631ff768cca26978ae877/src/BloomBrowserUI/react_components/Progress/ProgressDialog.tsx#L407)):*
> ```XML
>             }}
>             onReadyToReceive={() => post("progress/ready")}
>             dialogEnvironment={{
> ```

Note: Technically this refactoring is not 100% identical.  In the old code, I think (via code inspection) that it is initialized to this value, but when the websocket is opened, it sets dialogEnvironment to undefined?
Now I have this set to the initial value all the time.

I can't think of why that'd be problematic, but let me know if you do.

BTW, dialogEnvironment is never specified from the C# side.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5810)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @jsubloom)

___
*[`src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx` line 183 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5810#-NUWmhlL4ZVViOO4DIfy:-NUWmhlL4ZVViOO4DIfz:b-xnoy6i) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3acaf5342c859a5f05ea21189c8e45d3da8ab171/src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx#L183)):*
> ```XML
>     };
>     const [progressOpen, setProgressOpen] = useState(
>         progressDialogEnvironment.initiallyOpen
> ```

This will always be false, so why the change? In fact, I can't see that anything is achieved by pulling the dialogEnvironment into a const.
___
*[`src/BloomBrowserUI/react_components/Progress/ProgressDialog.tsx` line 71 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5810#-NUS91b9Ewfd7HNUT70e:-NUWntMj3y2qLprFF79P:b-zgwtly) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/157b820fdd95dd31307631ff768cca26978ae877/src/BloomBrowserUI/react_components/Progress/ProgressDialog.tsx#L71)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

Oops... I still need to work on this.
</blockquote></details>

I saw this and decided to stop reviewing until you are satisfied. Sending what comments I already made.

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5810)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx` line 183 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5810#-NUWmhlL4ZVViOO4DIfy:-NUWzgfv-TTe2kA2Cr_E:b-calj2c) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3acaf5342c859a5f05ea21189c8e45d3da8ab171/src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx#L183)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This will always be false, so why the change? In fact, I can't see that anything is achieved by pulling the dialogEnvironment into a const.
</blockquote></details>

Hmm, so I was kinda on the fence about this. The reason why I make it this way is that I realized that the inital value of the progressOpen state should be the same as progressDialogEnvironment.initiallyOpen.  I could write the constant "false" twice in two places. That's easier to read.
However, that's theoretically bad - it's really a single value but I wrote it twice.  I should really only write it once. (DRY)

Rebuttal: Unrealistic that we'd ever change the initial value away from false.
___
*[`src/BloomBrowserUI/react_components/Progress/ProgressDialog.tsx` line 71 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5810#-NUS91b9Ewfd7HNUT70e:-NUX-IX8-4nZ1pmtQ21g:byn3lmq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/157b820fdd95dd31307631ff768cca26978ae877/src/BloomBrowserUI/react_components/Progress/ProgressDialog.tsx#L71)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I saw this and decided to stop reviewing until you are satisfied. Sending what comments I already made.
</blockquote></details>

I already fixed this, but I forgot to resolve it.  Oops, sorry!  You can continue reviewing.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5810)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

**Review by andrew-polk — APPROVED** [review]
> Dismissed @JohnThomson from a discussion.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5810)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

**Review by andrew-polk — APPROVED** [review]
> Dismissed @jsubloom from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5810)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsubloom)

**Pull request merged**
