### PR TITLE
Various improvements to overlays

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6630)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Converting to draft while I sort out an overflow issue and deal with a cursor problem.

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6630)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 1399 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6630#-O670Ii6AMa12NMbBnau:-O670Ii6AMa12NMbBnav:b78dtzf) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2260b59458a83620d274b59cb36f58e28459d457/src/BloomBrowserUI/bookEdit/css/editMode.less#L1399)):*
> ```Less
>     // We call these crop handles, but for text boxes they are actually used to change width (and thus
>     // aspect ratio).
>     .bloom-ui-overlay-move-crop-handle {
> ```

Yeah lets just search/replace these to "side handles" (vs. "corner handles")
___
*[`src/BloomBrowserUI/bookEdit/js/bloomImages.ts` line 450 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6630#-O670XFu4c8tis7R8atd:-O670XFu4c8tis7R8ate:b76kd29) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2260b59458a83620d274b59cb36f58e28459d457/src/BloomBrowserUI/bookEdit/js/bloomImages.ts#L450)):*
> ```XML
>     // But then we may fail to turn it off when we should. I think it's better to just make sure that
>     // turning on a new one comes after turning off an old one.
>     if (patriarch) {
> ```

I'm not clear what "patriarch" is supposed to mean. Is it like, child/ ego/ parent / grandparent / patriarch? Looking at the assignment above, is it just `containingImageContainer`? That would be clearer.
___
*[`src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts` line 176 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6630#-O671vPi01k_FiITHk2d:-O671vPi01k_FiITHk2e:b-e4998u) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2260b59458a83620d274b59cb36f58e28459d457/src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts#L176)):*
> ```XML
>         let maxContentBottom = 0;
>         const children = Array.from(element.children);
>         // First, we need to make sure that the size and position of the children are not affected
> ```

I appreciate how well you comment stuff.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6630)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 1399 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6630#-O670Ii6AMa12NMbBnau:-O67Cc9L8WA9e6VihZMs:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2260b59458a83620d274b59cb36f58e28459d457/src/BloomBrowserUI/bookEdit/css/editMode.less#L1399)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Yeah lets just search/replace these to "side handles" (vs. "corner handles")
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/js/bloomImages.ts` line 450 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6630#-O670XFu4c8tis7R8atd:-O67DImG7BA_PWxvvP59:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2260b59458a83620d274b59cb36f58e28459d457/src/BloomBrowserUI/bookEdit/js/bloomImages.ts#L450)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I'm not clear what "patriarch" is supposed to mean. Is it like, child/ ego/ parent / grandparent / patriarch? Looking at the assignment above, is it just `containingImageContainer`? That would be clearer.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts` line 176 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6630#-O671vPi01k_FiITHk2d:-O67DSn446LJZWKMfoUU:b-ufhvn) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2260b59458a83620d274b59cb36f58e28459d457/src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts#L176)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I appreciate how well you comment stuff.
</blockquote></details>

I have 40 years' experience of wishing that the reason for doing something had been captured!

**Review by hatton — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6630)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @JohnThomson)

**Review by hatton — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6630)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
