### PR TITLE
Add a manual Preview button to AV publishing (BL-12763)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6745)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6745)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx` line 49 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6745#-OBR_aR2Dt2zLuPZa0al:-OBR_aR2Dt2zLuPZa0am:bpdc489) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/81d8d1557a928fc8b8bcd45115a94b82d4628b59/src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx#L49)):*
> onReset

Does this want a better name?
`onGeneratePreview()`?

And keyForReset/setKeyForReset could be something like `keyUsedToGenerateNewInstance`?

It's sad that we have to create a whole new instance of the control just to do this.
In one sense you're not making things worse, other than expanding this architecture to another control.
But if you see an simpler way to do this, maybe worth it?
___
*[`src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx` line 354 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6745#-OBRZyV-C8SY2wEcDw7B:-OBRZyV-C8SY2wEcDw7C:bthfgpw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/81d8d1557a928fc8b8bcd45115a94b82d4628b59/src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx#L354)):*
> // Any controls that would make this be on?

Worth keeping this comment?
If so, how about 
`// REVIEW: Are there any controls which should turn this on?`
___
*[`src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx` line 339 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6745#-OBRbU0E7HqM3NXgmfXD:-OBRbU0E7HqM3NXgmfXE:b-e8eicl) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/81d8d1557a928fc8b8bcd45115a94b82d4628b59/src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx#L339)):*
> ```XML
>                                     // which would not otherwise happen because it's not part of the props
>                                     key={avSettings.motion.toString()}
>                                     defaultLandscape={defaultLandscape}
> ```

Did we lose something by taking away the `|| avSettings.motion`? Or does DeviceAndControls handle that automagically?
___
*[`src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx` line 409 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6745#-OBRZcIB54QQofmZ9yRB:-OBRZcIB54QQofmZ9yRC:b-atr2ph) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/81d8d1557a928fc8b8bcd45115a94b82d4628b59/src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx#L409)):*
> ```XML
>                                             disabled={
>                                                 !isLicenseOK ||
>                                                 !props.showPreview
> ```

Shouldn't this use `arePlayAndResetDisabled`?
If not, it wants a comment.
___
*[`src/BloomBrowserUI/publish/commonPublish/DeviceAndControls.tsx` line 123 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6745#-OBRYMz45AIZkZ5vCf5M:-OBRYMz45AIZkZ5vCf5N:b-pw1a9e) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/81d8d1557a928fc8b8bcd45115a94b82d4628b59/src/BloomBrowserUI/publish/commonPublish/DeviceAndControls.tsx#L123)):*
> ```XML
>             >
>                 <iframe
>                     id="simple-preview"
> ```

This implies there is some other kind of (not so simple) preview.
Should we call it `preview-iframe` or `bloompub-preview-iframe`?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6745)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/publish/commonPublish/DeviceAndControls.tsx` line 123 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6745#-OBRYMz45AIZkZ5vCf5M:-OBSY58a4_indnchfBbc:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/81d8d1557a928fc8b8bcd45115a94b82d4628b59/src/BloomBrowserUI/publish/commonPublish/DeviceAndControls.tsx#L123)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This implies there is some other kind of (not so simple) preview.
Should we call it `preview-iframe` or `bloompub-preview-iframe`?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx` line 49 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6745#-OBR_aR2Dt2zLuPZa0al:-OBSGeUbAlCNDeMAIQOk:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/81d8d1557a928fc8b8bcd45115a94b82d4628b59/src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx#L49)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> onReset

Does this want a better name?
`onGeneratePreview()`?

And keyForReset/setKeyForReset could be something like `keyUsedToGenerateNewInstance`?

It's sad that we have to create a whole new instance of the control just to do this.
In one sense you're not making things worse, other than expanding this architecture to another control.
But if you see an simpler way to do this, maybe worth it?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx` line 339 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6745#-OBRbU0E7HqM3NXgmfXD:-OBSHB8n4BlpJGpUgdNp:b6ar48u) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/81d8d1557a928fc8b8bcd45115a94b82d4628b59/src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx#L339)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Did we lose something by taking away the `|| avSettings.motion`? Or does DeviceAndControls handle that automagically?
</blockquote></details>

No, I think it was a mistake. Fixed.
___
*[`src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx` line 354 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6745#-OBRZyV-C8SY2wEcDw7B:-OBSI1wx33kddTXARod1:b-t6471s) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/81d8d1557a928fc8b8bcd45115a94b82d4628b59/src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx#L354)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> // Any controls that would make this be on?

Worth keeping this comment?
If so, how about 
`// REVIEW: Are there any controls which should turn this on?`
</blockquote></details>

Improved comment
___
*[`src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx` line 409 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6745#-OBRZcIB54QQofmZ9yRB:-OBSIRkw8OtK-bYUBlH7:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/81d8d1557a928fc8b8bcd45115a94b82d4628b59/src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx#L409)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Shouldn't this use `arePlayAndResetDisabled`?
If not, it wants a comment.
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6745)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx` line 49 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6745#-OBR_aR2Dt2zLuPZa0al:-OBS_GQXBVt-ZMsePzGB:bmbiojl) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/81d8d1557a928fc8b8bcd45115a94b82d4628b59/src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx#L49)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You changed the one in the other file but not this one.
And I still think it would be helpful to rename keyForReset if we can come up with a good name.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6745)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx` line 49 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6745#-OBR_aR2Dt2zLuPZa0al:-OBSdiS50nnUjCkzF5So:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/81d8d1557a928fc8b8bcd45115a94b82d4628b59/src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx#L49)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

You changed the one in the other file but not this one.
And I still think it would be helpful to rename keyForReset if we can come up with a good name.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6745)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6745)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
