### PR TITLE
Fix error when changing to Title-On-Cover style (BL-10583)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4811)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4811)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 379 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4811#-MnCFLs87Lt0zYRkKpqd:-MnCFLs87Lt0zYRkKpqe:bppyvxl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8f1e373d5a36688bc2439fdf6a4c0b6be9248e21/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L379)):*
> ```
> HTMLElement
> ```
1) Updated to reflect new array being looped through
2) I didn't like that it casted it to type any, and found that if you ultimately cast it to HTMLElement instead of StyleSheet, TypeScript doesn't require casting through any/unknown first. Another plus is that the call to ownerNode is now type-checked (instead of doing <any>.ownerNode).

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4811)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 414 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4811#-MnCPBFw0pfsww-_s_PR:-MnCPBFw0pfsww-_s_PS:b-j5z23e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8f1e373d5a36688bc2439fdf6a4c0b6be9248e21/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L414)):*
> ```
>             // Just return the stylesheet array unchanged
>             return styleSheets;
> ```
I'm unsure about this. 
In this pathological case, maybe we would rather return no stylesheets?
Otherwise, we know we are producing the potential bug this PR is designed to prevent.

What bad things happen if we return an empty array?
___
*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 426 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4811#-MnCP5jQA0q4NaroXrki:-MnCP5jQA0q4NaroXrkj:b-zfb59w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8f1e373d5a36688bc2439fdf6a4c0b6be9248e21/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L426)):*
> ```
> I think
> ```
Let's verify and, if true, remove the "I think" from the comment.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4811)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 414 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4811#-MnCPBFw0pfsww-_s_PR:-MnR9E-B1tg22om7JBC7:b2h8xim) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8f1e373d5a36688bc2439fdf6a4c0b6be9248e21/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L414)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
>             // Just return the stylesheet array unchanged
>             return styleSheets;
> ```
I'm unsure about this. 
In this pathological case, maybe we would rather return no stylesheets?
Otherwise, we know we are producing the potential bug this PR is designed to prevent.

What bad things happen if we return an empty array?
</blockquote></details>

I traced the code. Looks like the result is it won't copy anything into userModifiedStyles section.

The upside is: We won't copy anything we shouldn't copy there.
The downside is: If there's anything we were supposed to be copying that we were before, we won't be copying it anymore.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4811)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 414 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4811#-MnCPBFw0pfsww-_s_PR:-MnRUg5j3OhMtcFGL76P:bqhq16i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8f1e373d5a36688bc2439fdf6a4c0b6be9248e21/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L414)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I traced the code. Looks like the result is it won't copy anything into userModifiedStyles section.

The upside is: We won't copy anything we shouldn't copy there.
The downside is: If there's anything we were supposed to be copying that we were before, we won't be copying it anymore.
</blockquote></details>

I'm inclined to go with the "do no harm" principle, i.e. to not copy if we're not sure.
But tell me if you think otherwise.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4811)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 414 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4811#-MnCPBFw0pfsww-_s_PR:-MnWU6hd4YIsD-pPNyNj:bi6se54) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8f1e373d5a36688bc2439fdf6a4c0b6be9248e21/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L414)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm inclined to go with the "do no harm" principle, i.e. to not copy if we're not sure.
But tell me if you think otherwise.
</blockquote></details>

The way I wrote is less of a departure from the legacy code path, which is a pro in the short term, but returning empty is more helpful in the long term.
___
*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 426 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4811#-MnCP5jQA0q4NaroXrki:-MnWUP0t6XfhLmTBovp0:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8f1e373d5a36688bc2439fdf6a4c0b6be9248e21/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L426)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> I think
> ```
Let's verify and, if true, remove the "I think" from the comment.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 367 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4811#-MnWV6Oh3NRUwKQMyHRI:-MnWV6Oh3NRUwKQMyHRJ:b5mghmi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac33644b30aa48d694482c7d02128f6b1d9d35df/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L367)):*
> ```
> const styleSheets = this.getBookNonInlineStyleSheets();
> ```
I get around the awkward problem of specifically defining the book stylesheets by focusing just on the relevant subset instead of getting the whole set of the book's stylesheets

**Review by andrew-polk — APPROVED** [review]
I'm ok with this going into 5.1, but I want to wait until after our initial beta release so the testing of this and any changes don't hold that up.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4811#-:-MnWynMZ3EjpFspKeKow:b-no705s)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4811)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

**Pull request merged**
