### PR TITLE
License checking (BL-7802)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3484)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
My review is a work in progress.

> Reviewed 4 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3484#-:-Lv79TCT1SMDAFzN5rCx:b-z44z8n)* status: 4 of 11 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Book/Book.cs, line 1728 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3484#-Lv76wVfBp7CjObTJdrZ:-Lv76wVfBp7CjObTJdr_:b-32dxd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e1d37a75a57e90fbf8b2a2760adc4fc596b5fd57/src/BloomExe/Book/Book.cs#L1728)):*
> ```Smalltalk
> 		public string MultilingualContentLanguage3 => _bookData.MultilingualContentLanguage3;
> 
> 		public IEnumerable<string> ActiveLanguages
> ```

Should this be a set?
___
*[src/BloomExe/Book/LicenseChecker.cs, line 29 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3484#-Lv77paZ7jdpf1tUQ0M6:-Lv77paZ7jdpf1tUQ0M7:bvemf4k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e1d37a75a57e90fbf8b2a2760adc4fc596b5fd57/src/BloomExe/Book/LicenseChecker.cs#L29)):*
> ```
> ProblemLanguages
> ```
GetProblemLanguages?
___
*[src/BloomExe/Book/LicenseChecker.cs, line 180 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3484#-Lv76OMUD3G-NUWCAMNv:-Lv76OMUD3G-NUWCAMNw:b94d2e5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e1d37a75a57e90fbf8b2a2760adc4fc596b5fd57/src/BloomExe/Book/LicenseChecker.cs#L180)):*
> ```
> ", "
> ```
Of course, this is not localized. But probably sufficient.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 7 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3484)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomTests/Book/LicenseCheckerTests.cs, line 33 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3484#-Lv7suUY3xRdya1BR-x6:-Lv7suUY3xRdya1BR-x7:bcxoy27) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e1d37a75a57e90fbf8b2a2760adc4fc596b5fd57/src/BloomTests/Book/LicenseCheckerTests.cs#L33)):*
> ```
> at the time of writing
> ```
Do we need a way to point to a test version of the license data? Seems like it to me. Otherwise, won't we be chasing things and/or invalidating our tests repeatedly?
___
*[src/BloomTests/Book/LicenseCheckerTests.cs, line 53 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3484#-Lv7tbq3C3PRt5a74qCG:-Lv7tbq3C3PRt5a74qCH:bsabp81) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e1d37a75a57e90fbf8b2a2760adc4fc596b5fd57/src/BloomTests/Book/LicenseCheckerTests.cs#L53)):*
> ```Smalltalk
> 		{
> 			var checker = new LicenseChecker();
> 			// bjn, at the time of writing, has a spurious newline, and comes back as bjn\n
> ```

I think this comment is not valid/helpful here

**Review by andrew-polk — COMMENTED** [review]
No longer "in progress".

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3484#-:-Lv7wolx4UhLouGXJoKX:b-fqsctt)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3484)* status: 8 of 11 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/Book/Book.cs, line 1728 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3484#-Lv76wVfBp7CjObTJdrZ:-Lv7yKnQA68FWCBG_ib5:b6ulfpo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e1d37a75a57e90fbf8b2a2760adc4fc596b5fd57/src/BloomExe/Book/Book.cs#L1728)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should this be a set?
</blockquote></details>

Done. (Not sure about RETURNING a set. The three callers all convert to an array.)
___
*[src/BloomExe/Book/LicenseChecker.cs, line 29 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3484#-Lv77paZ7jdpf1tUQ0M6:-Lv7yiQE7jbi1_t89EqN:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e1d37a75a57e90fbf8b2a2760adc4fc596b5fd57/src/BloomExe/Book/LicenseChecker.cs#L29)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> ProblemLanguages
> ```
GetProblemLanguages?
</blockquote></details>

Done.
___
*[src/BloomTests/Book/LicenseCheckerTests.cs, line 33 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3484#-Lv7suUY3xRdya1BR-x6:-Lv7vUQkEtWexlcjoyCM:b-je8b2w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e1d37a75a57e90fbf8b2a2760adc4fc596b5fd57/src/BloomTests/Book/LicenseCheckerTests.cs#L33)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> at the time of writing
> ```
Do we need a way to point to a test version of the license data? Seems like it to me. Otherwise, won't we be chasing things and/or invalidating our tests repeatedly?
</blockquote></details>

Several of the tests do use a fixed local version of the data. But I thought a couple of them should really go to the online data to make sure that really works. We may get a bit of noise, but I'm hoping that pretty soon we'll find some values we can count on to be there. Of course, things like the spurious newline might go away, leaving the functionality that handles that untested (though intact). At least one caller of SimpleTest is using the offline version that will always have the extra newline.
___
*[src/BloomTests/Book/LicenseCheckerTests.cs, line 53 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3484#-Lv7tbq3C3PRt5a74qCG:-Lv7zxbx0jI6Xa4wKfWt:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e1d37a75a57e90fbf8b2a2760adc4fc596b5fd57/src/BloomTests/Book/LicenseCheckerTests.cs#L53)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this comment is not valid/helpful here
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3484)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
