### PR TITLE
BL-471 Custom Page i18n

### PR DESCRIPTION
**Pull request by gmartin7**
I think it mostly works! The last commit may not be working quite right, but the rest is good for sure.

### CODE REVIEW

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/80/
Build succeeded

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/84/
Build succeeded

**Comment by gmartin7** [comment]
When you click to make a text box section, Bloom correctly displays the localized version of "Text Box" now. The only thing that doesn't work, is that when you toggle to regular mode and back again to origami mode, you've lost the "Text Box" indication even if the text box is empty. It should display "Text Box" again. I'm having trouble debugging into the origami code to figure out why that doesn't work.

**Comment by JohnThomson** [comment]
I wonder how much you gain by using the create/get strategy and making clones of things? Did this solve a definite performance problem or some other issue? If not it may be a case of premature optimization. I also wonder whether the reason the labels don't come back when you switch back to origami is that somehow the elements you want to clone are being destroyed. Might be worth a try just creating one from scratch wherever needed.

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/91/
Build succeeded

**Comment by gmartin7** [comment]
Finally got the 'Text Box' indicator working! IIRC the create/get strategy was used because if we created the html dynamically when we needed it (instead of initially on page creation) then the localization code wouldn't work correctly (e.g. data-i18n="EditTab.CustomPage.TextBox").

**Pull request merged**
