### PR TITLE
Fix preview of source templates (BL-13406)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
Also clean up various CSS files, eliminating two xmatter related files.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
I'm not done, but I'm being pulled into a meeting, so I'm publishing what I have so far.

> Reviewed 36 of 42 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-:-NxIzzC0BZcDfFJ-Tlep:b-4toj50)* status: 36 of 42 files reviewed, 6 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/content/appearanceThemes/appearance-theme-default.css` line 204 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxIweJ28wJqSnBSqY5U:-NxIweJ28wJqSnBSqY5V:bvicdgb) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24367eeb200891e3e91e2745c5be1de48c85542b/src/content/appearanceThemes/appearance-theme-default.css#L204)):*
> ```CSS
>  * These variables / rules are for xmatter pages.
>  */
> body {
> ```

I'm not seeing the benefit of having the body selector.
I think bloom-page would be better. Or even `.front-matter, .back-matter`.
___
*[`src/content/appearanceThemes/appearance-theme-default.css` line 205 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxIwnT66D4-va6dnPzd:-NxIwnT66D4-va6dnPze:b-x10zq5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24367eeb200891e3e91e2745c5be1de48c85542b/src/content/appearanceThemes/appearance-theme-default.css#L205)):*
> ```CSS
>  */
> body {
>     --MarginBetweenBlocks: 2em;
> ```

I'm thinking it is better to give this a more specific name like MarginBetweenXmatterBlocks. Same for MarginBetweenXmatterMinorItems.
___
*[`src/content/bookLayout/basePage-legacy-5-6.less` line 1378 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxIzV26BWVnCldXGuVx:-NxIzV26BWVnCldXGuVy:b-fah9u8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24367eeb200891e3e91e2745c5be1de48c85542b/src/content/bookLayout/basePage-legacy-5-6.less#L1378)):*
> ```Less
> }
> 
> // Rules from bloom-xmatter-sharedRules.less in 5.6 (and before). That file was removed in 6.0.
> ```

I wonder if it is better/safer/simpler to just copy these rules from 5.6?

Also, probably deserves a comment at the top where we claim this file is a copy of basePage.
___
*[`src/content/templates/template books/Arithmetic Template/ArithmeticTemplate.pug` line 42 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxIrZ1bCizdTRCiDd1g:-NxIrZ1bCizdTRCiDd1h:b-sn46uq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24367eeb200891e3e91e2745c5be1de48c85542b/src/content/templates/template%20books/Arithmetic%20Template/ArithmeticTemplate.pug#L42)):*
> ```Pug
> 		title 'Arithmetic'
> 		+stylesheets('ArithmeticTemplate.css')
> 		+stylesheet('appearance.css')
> ```

Should this be added to the `stylesheets` or `core-stylesheets` mixin?
___
*[`src/content/templates/template books/Arithmetic Template/appearance.css` line 1 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxIrdsC1ih3F6ma0dFm:-NxIrdsC1ih3F6ma0dFn:bthllcc) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24367eeb200891e3e91e2745c5be1de48c85542b/src/content/templates/template%20books/Arithmetic%20Template/appearance.css#L1)):*
> ```CSS
> /* This is the default theme, not only in the sense that it is the one we use by default for new books,
> ```

Am I correct this is a copy of appearance-theme-default.css?

I don't think we need a copy of this file in every template. See, for example, basePage.css or previewMode.css which is not in the template folder but gets found by special magic in the BloomServer stuff. 
So I think you can get rid of these new files, add a reference to `appearance-theme-default.css`, and hopefully the same magic will work. Note, if not, I think you need to debug BookStorage.GetSupportingFile.

Not only will that reduce clutter, but it will ensure that this file stays up to date.

You might be able to do something similar for the .json file.
___
*[`src/content/templates/template books/Digital Comic Book/Digital Comic Book.htm` line 91 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxIuLNR-IHT-FOB5eUF:-NxIuLNR-IHT-FOB5eUG:b4crvnw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24367eeb200891e3e91e2745c5be1de48c85542b/src/content/templates/template%20books/Digital%20Comic%20Book/Digital%20Comic%20Book.htm#L91)):*
> ```HTML
>             type="text/css"
>         />
>         <link rel="stylesheet" href="appearance.css" type="text/css" />
> ```

Maybe it doesn't matter at all in this case, but it seems odd to me to have this come after customCollectionStyles.
(Same for Paper comic)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Ok, done with initial review.

> Reviewed 6 of 42 files at r1.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-:-NxJhI4U8_QXudS19NPZ:b-e0e4t3)* status: all files reviewed, 9 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less` line 3 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxJeFyUBEp_0uMoiV4t:-NxJeFyUBEp_0uMoiV4u:b-3xnmxo) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24367eeb200891e3e91e2745c5be1de48c85542b/src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less#L3)):*
> ```Less
> @import (reference) "../../bloomUI.less";
> 
> @XMatterPackName: "template-preview";
> ```

We don't want this XMatterPackName line here.
___
*[`src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less` line 7 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxJgK0DEl5vDk9xGliY:-NxJgK0DEl5vDk9xGliZ:b47r4c4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24367eeb200891e3e91e2745c5be1de48c85542b/src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less#L7)):*
I'm going to paste JT's comment here and let you respond to that so I can understand better why we still need these rules.

> I would like to try to get rid of the remaining rules in standard-template-preview.css. If we really need rules that are specific to previewing built-in templates, they can just go into previewMode.less directly. But I suspect a lot of them are redundant (.frontCover {padding-top: var(--cover-margin-top);}) and others, like special order rules for title, cover image, and bottomBlock, or setting a min-height for the title, seem out of place. Why would the title of template book have a different min-height when in a preview than any other time?? It would be interesting to do a visual diff of template books in 5.6 and 6.0 if we just dropped these rules. Then we can get rid of the file itself!
___
*[`src/content/bookLayout/basePage-sharedRules.less` line 189 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxJfVgxAuFXdqml0xjJ:-NxJfVgxAuFXdqml0xjK:b6rgrak) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24367eeb200891e3e91e2745c5be1de48c85542b/src/content/bookLayout/basePage-sharedRules.less#L189)):*
> ```Less
>             line-height: 1.1;
>             min-height: auto; // elsewhere there is a min-height, that may or may not be a good idea, but for sure we don't want it here.
>             // This group is tricky. Because it's in xmatter, and we don't have distinct xmatter rules for legacy, it needs
> ```

My understanding is this file now only applies to non-legacy? If that's true we can clean this up to remove the rules for legacy.

But I'm not clear how thing work with epub.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470)* status: 3 of 45 files reviewed, 9 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less` line 3 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxJeFyUBEp_0uMoiV4t:-NxJxjFcBnYQFV2vY8tT:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24367eeb200891e3e91e2745c5be1de48c85542b/src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less#L3)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We don't want this XMatterPackName line here.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less` line 7 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxJgK0DEl5vDk9xGliY:-NxK1sYgDlFoDoM3hpfC:boo7osz) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24367eeb200891e3e91e2745c5be1de48c85542b/src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less#L7)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm going to paste JT's comment here and let you respond to that so I can understand better why we still need these rules.

> I would like to try to get rid of the remaining rules in standard-template-preview.css. If we really need rules that are specific to previewing built-in templates, they can just go into previewMode.less directly. But I suspect a lot of them are redundant (.frontCover {padding-top: var(--cover-margin-top);}) and others, like special order rules for title, cover image, and bottomBlock, or setting a min-height for the title, seem out of place. Why would the title of template book have a different min-height when in a preview than any other time?? It would be interesting to do a visual diff of template books in 5.6 and 6.0 if we just dropped these rules. Then we can get rid of the file itself!
</blockquote></details>

I've removed the rules that I've determined are not needed for previewing template books.  The remaining rules are needed to get the cover page to look reasonably balanced with the placement and size of the placeholder image.  Without a full xmatter setup, these front pages don't have enough content for the basePage rules to show them nicely.  Since this is only true for previewing the templates, I think the best place for these rules is in a preview less/css file.
___
*[`src/content/appearanceThemes/appearance-theme-default.css` line 204 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxIweJ28wJqSnBSqY5U:-NxKE1fFDzCrC74e-3AN:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24367eeb200891e3e91e2745c5be1de48c85542b/src/content/appearanceThemes/appearance-theme-default.css#L204)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not seeing the benefit of having the body selector.
I think bloom-page would be better. Or even `.front-matter, .back-matter`.
</blockquote></details>

Done.
___
*[`src/content/appearanceThemes/appearance-theme-default.css` line 205 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxIwnT66D4-va6dnPzd:-NxKE2rjBe3C2ZbLCtIV:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24367eeb200891e3e91e2745c5be1de48c85542b/src/content/appearanceThemes/appearance-theme-default.css#L205)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm thinking it is better to give this a more specific name like MarginBetweenXmatterBlocks. Same for MarginBetweenXmatterMinorItems.
</blockquote></details>

Done.
___
*[`src/content/bookLayout/basePage-legacy-5-6.less` line 1378 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxIzV26BWVnCldXGuVx:-NxKE6MU0SClWiWO3gtx:bvypr74) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24367eeb200891e3e91e2745c5be1de48c85542b/src/content/bookLayout/basePage-legacy-5-6.less#L1378)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I wonder if it is better/safer/simpler to just copy these rules from 5.6?

Also, probably deserves a comment at the top where we claim this file is a copy of basePage.
</blockquote></details>

These rules were essentially copied from generated CSS in 5.6.
I've added/revised comments at the top, and made this comment more prominent.
___
*[`src/content/bookLayout/basePage-sharedRules.less` line 189 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxJfVgxAuFXdqml0xjJ:-NxKGKcU17yB14Md3Odp:bcz9p23) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24367eeb200891e3e91e2745c5be1de48c85542b/src/content/bookLayout/basePage-sharedRules.less#L189)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

My understanding is this file now only applies to non-legacy? If that's true we can clean this up to remove the rules for legacy.

But I'm not clear how thing work with epub.
</blockquote></details>

That is my quandary: I'm not sure whether baseEPUB.less is generally affected by themes, or by the distinction between default and legacy.
I decided to move the legacy specific rules (and most of the commentary) to the top of baseEPUB.less just before basePage-sharedRules.less is imported.  This keeps this file clean, and places the rule where it might be needed.  I'd be happy to decide that ePUB doesn't need this complication if we want to go that way.
___
*[`src/content/templates/template books/Arithmetic Template/ArithmeticTemplate.pug` line 42 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxIrZ1bCizdTRCiDd1g:-NxNxhibCt3ss_1wvWTs:bmv7e27) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24367eeb200891e3e91e2745c5be1de48c85542b/src/content/templates/template%20books/Arithmetic%20Template/ArithmeticTemplate.pug#L42)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should this be added to the `stylesheets` or `core-stylesheets` mixin?
</blockquote></details>

I've added it to the definition of stylesheets and removed it from the various template .pug files.
___
*[`src/content/templates/template books/Arithmetic Template/appearance.css` line 1 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxIrdsC1ih3F6ma0dFm:-NxOAy_tCXuMXBuH6lsn:b8tdrq4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24367eeb200891e3e91e2745c5be1de48c85542b/src/content/templates/template%20books/Arithmetic%20Template/appearance.css#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Am I correct this is a copy of appearance-theme-default.css?

I don't think we need a copy of this file in every template. See, for example, basePage.css or previewMode.css which is not in the template folder but gets found by special magic in the BloomServer stuff. 
So I think you can get rid of these new files, add a reference to `appearance-theme-default.css`, and hopefully the same magic will work. Note, if not, I think you need to debug BookStorage.GetSupportingFile.

Not only will that reduce clutter, but it will ensure that this file stays up to date.

You might be able to do something similar for the .json file.
</blockquote></details>

Done (with small enhancement to BloomServer).  I decided we don't need the .json files because all they did was enforce the default theme, which is, well, the default.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470)* status: 3 of 45 files reviewed, 9 unresolved discussions (waiting on @andrew-polk)

___
*[`src/content/templates/template books/Digital Comic Book/Digital Comic Book.htm` line 91 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxIuLNR-IHT-FOB5eUF:-NxODoLP73Eu4f_h_Ixi:bj0sj4l) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24367eeb200891e3e91e2745c5be1de48c85542b/src/content/templates/template%20books/Digital%20Comic%20Book/Digital%20Comic%20Book.htm#L91)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Maybe it doesn't matter at all in this case, but it seems odd to me to have this come after customCollectionStyles.
(Same for Paper comic)
</blockquote></details>

moved to follow the eponymous css file
___
*[`src/content/templates/template books/Arithmetic Template/appearance.css` line 1 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxIrdsC1ih3F6ma0dFm:-NxODKMz8IB7ArNNmJk-:bt26xgf) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24367eeb200891e3e91e2745c5be1de48c85542b/src/content/templates/template%20books/Arithmetic%20Template/appearance.css#L1)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Done (with small enhancement to BloomServer).  I decided we don't need the .json files because all they did was enforce the default theme, which is, well, the default.
</blockquote></details>

Note that this embeds a line to the appearance-theme-default.css file in all the books created from the revised templates.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 38 of 42 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470)* status: 43 of 45 files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less` line 25 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxOLuNbApC1zV4LSZFy:-NxOLuNbApC1zV4LSZFz:b-b0rm3k) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b163588a9dcdbc8ffb3aa3d1d8546290da7d4afe/src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less#L25)):*
> ```Less
>             }
>         }
>         // This is needed for the Digital Comic Book and Sign Language to properly space items
> ```

Do you mean Paper Comic Book rather than Sign Language?
That's where I see this ID (besides Digital Comic Book).
___
*[`src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less` line 42 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxOLXg-23uZzMtFdSgQ:-NxOLXg-23uZzMtFdSgR:b-7nie1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b163588a9dcdbc8ffb3aa3d1d8546290da7d4afe/src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less#L42)):*
> ```Less
>         &[data-xmatter-page="about"] {
>             display: none;
>         }
> ```

Sorry, I know this is not particularly in scope, but I'm thinking we can just remove those about pages from the .htm and get rid of this rule.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less` line 25 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxOLuNbApC1zV4LSZFy:-NxOPG9I1IbiNk15Gv0K:b-i2p5uy) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b163588a9dcdbc8ffb3aa3d1d8546290da7d4afe/src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less#L25)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Do you mean Paper Comic Book rather than Sign Language?
That's where I see this ID (besides Digital Comic Book).
</blockquote></details>

The original comment referencing only the Digital Comic Book was correct.
___
*[`src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less` line 42 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470#-NxOLXg-23uZzMtFdSgQ:-NxOTm3vErX9f81teDSp:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b163588a9dcdbc8ffb3aa3d1d8546290da7d4afe/src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less#L42)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry, I know this is not particularly in scope, but I'm thinking we can just remove those about pages from the .htm and get rid of this rule.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6470)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
