### PR TITLE
Show image info tooltip only when no bubbles selected (BL-11738)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5603)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5603)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[`src/BloomBrowserUI/bookEdit/js/bloomImages.ts` line 422 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5603#-NMf8LgGAzwG_WmvyKIn:-NMf8LgGAzwG_WmvyKIo:b-s8uqqt) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f88336dba1433e5a331b92a52caf0bc72120a5c5/src/BloomBrowserUI/bookEdit/js/bloomImages.ts#L422)):*
> ```XML
>     } else {
>         EnableImageTooltip(container);
>     }
> ```

Isn't a bubble being selected different than the image being selected?
How does the logic work which makes the on-hover buttons (select image, paste, etc.) only appear when the image is "selected"? From playing with it, it seems different than if a bubble is selected. Can we use the same logic for this?

Also, that would (hopefully) disentangle the showing/hiding of the tooltip from bubbleManager. Ideally, bubbleManager should know nothing about it.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5603)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/js/bloomImages.ts` line 422 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5603#-NMf8LgGAzwG_WmvyKIn:-NMjFJzq2lmaPL-Tso0z:b1nzpk9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f88336dba1433e5a331b92a52caf0bc72120a5c5/src/BloomBrowserUI/bookEdit/js/bloomImages.ts#L422)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Isn't a bubble being selected different than the image being selected?
How does the logic work which makes the on-hover buttons (select image, paste, etc.) only appear when the image is "selected"? From playing with it, it seems different than if a bubble is selected. Can we use the same logic for this?

Also, that would (hopefully) disentangle the showing/hiding of the tooltip from bubbleManager. Ideally, bubbleManager should know nothing about it.
</blockquote></details>

It does sound a attractive from the UI perspective to make it align with the on-hover buttons.

Unfortunately, since I don't believe it's possible to disable the tooltip via CSS (only via setting title), that means we need to track the Javascript that adds the .bloom-hideImageButtons and .bloom-uiSuppressImageButtons classes.   Some references are in bloomImages (fine), 2 are in bubbleManager (not improving anything) and 2 more are in motionTool (entangling another file).  So is that even any better than the original situation?

Another con: When you load a page, the focus is in a bubble. In my PR, therefore the tooltip will not show up. However, the image editing buttons sometimes (!!!!!!!!) do show up initially, despite a bubble having focus. (This is arguably a problem with the image editing buttons).

Well... I guess it's probably still worth it to follow the on-hover image editing buttons?  Lining up with the on-hover image editing buttons does make a lot of sense from a user model point of view.  Having one model instead of two is also nice.
Thoughts before I do it?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5603)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[`src/BloomBrowserUI/bookEdit/js/bloomImages.ts` line 422 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5603#-NMf8LgGAzwG_WmvyKIn:-NMjRGCd2v-RSfOmGsYj:b-4qgdhr) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f88336dba1433e5a331b92a52caf0bc72120a5c5/src/BloomBrowserUI/bookEdit/js/bloomImages.ts#L422)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

It does sound a attractive from the UI perspective to make it align with the on-hover buttons.

Unfortunately, since I don't believe it's possible to disable the tooltip via CSS (only via setting title), that means we need to track the Javascript that adds the .bloom-hideImageButtons and .bloom-uiSuppressImageButtons classes.   Some references are in bloomImages (fine), 2 are in bubbleManager (not improving anything) and 2 more are in motionTool (entangling another file).  So is that even any better than the original situation?

Another con: When you load a page, the focus is in a bubble. In my PR, therefore the tooltip will not show up. However, the image editing buttons sometimes (!!!!!!!!) do show up initially, despite a bubble having focus. (This is arguably a problem with the image editing buttons).

Well... I guess it's probably still worth it to follow the on-hover image editing buttons?  Lining up with the on-hover image editing buttons does make a lot of sense from a user model point of view.  Having one model instead of two is also nice.
Thoughts before I do it?
</blockquote></details>

Yes, I think we need one source of truth for whether an image is selected. It sounds like we could really improve that model, but I'm not sure this tweak is worth diving into that.

I'm not sure I like this idea, but you could, in theory, add an event listener on hover which looks for the class (or a new one) and then sets or removes title from data-title.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5603)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/js/bloomImages.ts` line 422 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5603#-NMf8LgGAzwG_WmvyKIn:-NMoLYqg9-C-pCz3GlP2:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f88336dba1433e5a331b92a52caf0bc72120a5c5/src/BloomBrowserUI/bookEdit/js/bloomImages.ts#L422)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Yes, I think we need one source of truth for whether an image is selected. It sounds like we could really improve that model, but I'm not sure this tweak is worth diving into that.

I'm not sure I like this idea, but you could, in theory, add an event listener on hover which looks for the class (or a new one) and then sets or removes title from data-title.

</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
Nice improvements. Thanks.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5603#-:-NMpLH8B6w40mAtUxcGx:bjuqd5k)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Pull request merged**
