### PR TITLE
Handle updating license icons more robustly and quietly (BL-9533)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 316 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MTwRFvX49t8yyYYRgJr:-MTwRFvY3BWBQ14GdyX4:bq8d1af) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e7c83c6c4a611d18a160cb8b4557b6fc93265c2/src/BloomExe/Book/BookCopyrightAndLicense.cs#L316)):*
> ```Smalltalk
> 				// BL-9533: these errors keep happening, but we can't help users who respond to a toast and send in an error report.
> 				// Logging it will allow us to possibly correlate an error here with another problem that does get reported.
> 				Logger.WriteError($"Could not update license image (BL-3227) at {imagePath}", error);
> ```

I think we should also report it to Sentry.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 284 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MTwRIq_6brv1VpXc_DM:-MTwRIq_6brv1VpXc_DN:b-jsrfza) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e7c83c6c4a611d18a160cb8b4557b6fc93265c2/src/BloomExe/Book/BookCopyrightAndLicense.cs#L284)):*
> ```Smalltalk
> 			{
> 				// Almost all of the reports for BL-3227 that have been generated are for an UnauthorizedAccessException
> 				// in the FileStream constructor.  This can happen if the file has become read-only for some reason.
> ```

Does it happen if something else has it open? 
Can we tell the difference in code?
Do we have a theory of how it could be read-only attribute set?
___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 291 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MTwR6xkBsa0OeyxOULj:-MTwR6xkBsa0OeyxOULk:b-p7grvp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e7c83c6c4a611d18a160cb8b4557b6fc93265c2/src/BloomExe/Book/BookCopyrightAndLicense.cs#L291)):*
> ```Smalltalk
> 					var attr = File.GetAttributes(imagePath);
> 					if ((attr & FileAttributes.ReadOnly) == FileAttributes.ReadOnly)
> 						File.SetAttributes(imagePath, FileAttributes.Normal);
> ```

I would expect this to *increase* our number of failures, because it is not robust

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 291 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MTwR6xkBsa0OeyxOULj:-MTwRbkaBaFo41tlDaDX:b-hocqs3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e7c83c6c4a611d18a160cb8b4557b6fc93265c2/src/BloomExe/Book/BookCopyrightAndLicense.cs#L291)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I would expect this to *increase* our number of failures, because it is not robust
</blockquote></details>

(that is, the `File.GetAttributes()`. But maybe that never blocks?)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 284 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MTwRIq_6brv1VpXc_DM:-MTwZ0fa0wsl_6lRnKw5:b-m798oc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e7c83c6c4a611d18a160cb8b4557b6fc93265c2/src/BloomExe/Book/BookCopyrightAndLicense.cs#L284)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Does it happen if something else has it open? 
Can we tell the difference in code?
Do we have a theory of how it could be read-only attribute set?
</blockquote></details>

The documentation for FileStream constructor says that the UnauthorizedAccessException occurs if the given path is to a read-only file.  It says nothing about the file being open elsewhere for that error.  The first code I wrote for this issue caught the UnauthorizedAccessException specifically and then retried saving the image after changing the read-only attribute.  I'd be happy to go back to that approach, but it was more code overall.  I'd also be happy to try to tackle fixing the permissions settings as well, but that would be a lot more complicated (and worth doing only if the exception occurs indicating a need for a fix).

My only theory for how the read-only attribute is set is user action.  The problem could very well be a permission setting rather than an attribute setting, but that's far more complicated to try to fix in the code (and far more Windows-specific).
___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 291 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MTwR6xkBsa0OeyxOULj:-MTwYuly1bypSIjSEVXb:b-of7w1q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e7c83c6c4a611d18a160cb8b4557b6fc93265c2/src/BloomExe/Book/BookCopyrightAndLicense.cs#L291)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

(that is, the `File.GetAttributes()`. But maybe that never blocks?)
</blockquote></details>

Changed to use RobustFile.Get/SetAttributes.
___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 316 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MTwRFvX49t8yyYYRgJr:-MTwYOti04-hev5oxjRS:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e7c83c6c4a611d18a160cb8b4557b6fc93265c2/src/BloomExe/Book/BookCopyrightAndLicense.cs#L316)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think we should also report it to Sentry.
</blockquote></details>

Done.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @andrew-polk, @hatton, and @StephenMcConnel)

___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 284 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MTwRIq_6brv1VpXc_DM:-MTwjWz_-0_izT8rgG7a:b5hxfxx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e7c83c6c4a611d18a160cb8b4557b6fc93265c2/src/BloomExe/Book/BookCopyrightAndLicense.cs#L284)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

The documentation for FileStream constructor says that the UnauthorizedAccessException occurs if the given path is to a read-only file.  It says nothing about the file being open elsewhere for that error.  The first code I wrote for this issue caught the UnauthorizedAccessException specifically and then retried saving the image after changing the read-only attribute.  I'd be happy to go back to that approach, but it was more code overall.  I'd also be happy to try to tackle fixing the permissions settings as well, but that would be a lot more complicated (and worth doing only if the exception occurs indicating a need for a fix).

My only theory for how the read-only attribute is set is user action.  The problem could very well be a permission setting rather than an attribute setting, but that's far more complicated to try to fix in the code (and far more Windows-specific).
</blockquote></details>

I know it's not helpful, but I don't believe the problem is either a read only property, nor permission settings.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 284 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MTwRIq_6brv1VpXc_DM:-MU9IIP82U3X7eIVbWHn:bb2thdt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e7c83c6c4a611d18a160cb8b4557b6fc93265c2/src/BloomExe/Book/BookCopyrightAndLicense.cs#L284)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I know it's not helpful, but I don't believe the problem is either a read only property, nor permission settings.
</blockquote></details>

I have a vague theory that at least some of the read-only files are getting set that way by Windows when obtaining files "from the internet". But that theory doesn't go very far since we don't seem to have these problems with htm files.
___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 329 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MU9J-er1z8KYZaSC66N:-MU9J-er1z8KYZaSC66O:b3wcudv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a7643c16665f5d01db3475f40787fe299ce2ff1f/src/BloomExe/Book/BookCopyrightAndLicense.cs#L329)):*
> ```Smalltalk
> 						SentrySdk.CaptureException(error);
> 					});
> 				}
> ```

Other places, we do this conditionally if not running in a dev environment. We want that here, too.

Thinking out loud... is there a useful/feasible way to use NonFatalProblem to *only* report to Sentry? So the Sentry code can live in fewer places?

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk, @hatton, and @StephenMcConnel)

___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 284 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MTwRIq_6brv1VpXc_DM:-MU9KG521e0YSEFrED2R:bz5dg74) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e7c83c6c4a611d18a160cb8b4557b6fc93265c2/src/BloomExe/Book/BookCopyrightAndLicense.cs#L284)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I have a vague theory that at least some of the read-only files are getting set that way by Windows when obtaining files "from the internet". But that theory doesn't go very far since we don't seem to have these problems with htm files.
</blockquote></details>

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218)* status: all files reviewed, 6 unresolved discussions (waiting on @andrew-polk, @hatton, and @StephenMcConnel)

___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 295 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MUApVSS7LRH8Sulr29l:-MUApVSS7LRH8Sulr29m:bz4y6u4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9097438292c4fc068f87bf4ea0df548a5ab3e5b1/src/BloomExe/Book/BookCopyrightAndLicense.cs#L295)):*
> ```
> if ((originalFileAttributes & FileAttributes.ReadOnly) == FileAttributes.ReadOnly)
> ```
if (originalReadOnly == FileAttributes.ReadOnly)
___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 326 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MUAobBk-z2GVV9bE3B9:-MUAobBk-z2GVV9bE3BA:by36m6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9097438292c4fc068f87bf4ea0df548a5ab3e5b1/src/BloomExe/Book/BookCopyrightAndLicense.cs#L326)):*
> ```
> TODO
> ```
Creating a comment here so this doesn't get lost.
___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 328 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MUAplk04ZW84lN8PY24:-MUAplk04ZW84lN8PY25:b3pb3p8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9097438292c4fc068f87bf4ea0df548a5ab3e5b1/src/BloomExe/Book/BookCopyrightAndLicense.cs#L328)):*
> ```
> (originalFileAttributes & FileAttributes.ReadOnly)
> ```
originalReadOnly
___
*[src/BloomExe/Utils/MiscUtils.cs, line 78 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MUAoJEK7VYmXdYkOAnc:-MUAoJEL7arJSe6pYW39:b-6l0e3h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9097438292c4fc068f87bf4ea0df548a5ab3e5b1/src/BloomExe/Utils/MiscUtils.cs#L78)):*
> ```
> //#if !__MonoCS__
> ```
Can remove these, right?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 284 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MTwRIq_6brv1VpXc_DM:-MUB94NV8ySw0nm2yzDO:b-mx77jz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e7c83c6c4a611d18a160cb8b4557b6fc93265c2/src/BloomExe/Book/BookCopyrightAndLicense.cs#L284)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>


</blockquote></details>

noted.
___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 329 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MU9J-er1z8KYZaSC66N:-MUB8Ge68DZPmUWrZ7yJ:bekwvcv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a7643c16665f5d01db3475f40787fe299ce2ff1f/src/BloomExe/Book/BookCopyrightAndLicense.cs#L329)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Other places, we do this conditionally if not running in a dev environment. We want that here, too.

Thinking out loud... is there a useful/feasible way to use NonFatalProblem to *only* report to Sentry? So the Sentry code can live in fewer places?
</blockquote></details>

No longer using Sentry directly here.  We're using NonFatalProblem again because we do want the toast, just not the ability to send a report.
___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 295 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MUApVSS7LRH8Sulr29l:-MUB9sqh5IWlVyutkuv0:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9097438292c4fc068f87bf4ea0df548a5ab3e5b1/src/BloomExe/Book/BookCopyrightAndLicense.cs#L295)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> if ((originalFileAttributes & FileAttributes.ReadOnly) == FileAttributes.ReadOnly)
> ```
if (originalReadOnly == FileAttributes.ReadOnly)
</blockquote></details>

Done.
___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 326 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MUAobBk-z2GVV9bE3B9:-MUB9LRx7kHl1GKhUFRe:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9097438292c4fc068f87bf4ea0df548a5ab3e5b1/src/BloomExe/Book/BookCopyrightAndLicense.cs#L326)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> TODO
> ```
Creating a comment here so this doesn't get lost.
</blockquote></details>

Done.
___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 328 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MUAplk04ZW84lN8PY24:-MUB9ue48x8JauU3lTwG:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9097438292c4fc068f87bf4ea0df548a5ab3e5b1/src/BloomExe/Book/BookCopyrightAndLicense.cs#L328)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> (originalFileAttributes & FileAttributes.ReadOnly)
> ```
originalReadOnly
</blockquote></details>

Done.
___
*[src/BloomExe/Utils/MiscUtils.cs, line 78 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MUAoJEK7VYmXdYkOAnc:-MUB8-j4Eof7Dk4t_6bf:b-5h7zzn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9097438292c4fc068f87bf4ea0df548a5ab3e5b1/src/BloomExe/Utils/MiscUtils.cs#L78)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> //#if !__MonoCS__
> ```
Can remove these, right?
</blockquote></details>

Done.  Mono 5 does a lot better job of minimally mocking Windows-specific assemblies to at least compile even if all methods are Not Implemented.  And VS 2017 is adequately mocking the Mono.Posix assembly too...

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 326 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MUAobBk-z2GVV9bE3B9:-MUBB9msDByGqvUMTnMi:bwvnczb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9097438292c4fc068f87bf4ea0df548a5ab3e5b1/src/BloomExe/Book/BookCopyrightAndLicense.cs#L326)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not reflected in the version of the code I'm seeing

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218)* status: all files reviewed, 4 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[src/BloomExe/Linux/packages.config, line 31 at r6](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MUELjYZEzDdX7jPKj5r:-MUELjYZEzDdX7jPKj5s:b-973izu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/221d83f9c39faddbc66c6bf84c5bed3e6d093951/src/BloomExe/Linux/packages.config#L31)):*
> ```XML
>   <package id="Microsoft.Web.Xdt" version="3.1.0" targetFramework="net461" />
>   <package id="Mono.Cecil" version="0.11.3" targetFramework="net461" />
>   <package id="Mono.Posix" version="5.4.0.201" targetFramework="net461" />
> ```

Why doesn't the NuGet version work for Linux anymore? Should we add that as a comment to the csproj?

If we are removing this here, don't we need to move the one in the Windows packages.config down into the Windows-only section?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 326 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MUAobBk-z2GVV9bE3B9:-MUEiULA8mF8ZCwi6qox:b-z8wn82) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9097438292c4fc068f87bf4ea0df548a5ab3e5b1/src/BloomExe/Book/BookCopyrightAndLicense.cs#L326)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Not reflected in the version of the code I'm seeing
</blockquote></details>

JohnH provided a full URL to use here.
___
*[src/BloomExe/Linux/packages.config, line 31 at r6](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218#-MUELjYZEzDdX7jPKj5r:-MUEiaZ719QBOSFZ3mf5:bo44lov) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/221d83f9c39faddbc66c6bf84c5bed3e6d093951/src/BloomExe/Linux/packages.config#L31)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Why doesn't the NuGet version work for Linux anymore? Should we add that as a comment to the csproj?

If we are removing this here, don't we need to move the one in the Windows packages.config down into the Windows-only section?
</blockquote></details>

This assembly is built-in for Mono.  The nuget package doesn't provide an assembly for Linux anyway, just for Mac and Windows.
Referring to this assembly on Linux causes a weird msbuild error when the nuget package is also downloaded.
I moved the reference in packages.config for Windows to the Windows-only section.  I should have thought of that yesterday.  :-)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r7.
> Dismissed @hatton from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

**Pull request merged**
