### PR TITLE
Refactor Leveled/Decodable Reader - improve level num display (BL-10243)

### PR DESCRIPTION
**Pull request by sujeffreyl**
1) Simplify the structure so that it doesn't require modifying the DOM and inserting these span structures.
2) Make it so that the raw format string/placeholders "Level {0} of {1}" are not rendered to the user

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4632)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4632)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, line 372 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4632#-MgGgE3gCpy7QJbO2Pga:-MgGgE3gCpy7QJbO2Pgb:b-tikp8g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a119f20f0db997b195bc47fffb13914a3a0fa50b/src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts#L372)):*
> ```XML
>     }
> 
>     public updateStageNOfMInternal(stageParent: HTMLElement) {
> ```

Big idea #1: I wanted to simplify this structure so that it doesn't require parsing the format string and making these HTML spans and whatnot
___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, line 383 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4632#-MgGgUs57a01bZlEmZhy:-MgGgUs57a01bZlEmZhz:bhu9vgx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a119f20f0db997b195bc47fffb13914a3a0fa50b/src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts#L383)):*
> ```XML
>         // If not, it's not the end of the world to display it in English at first. (This function gets called several times,
>         // so one would expect that even if the localizations aren't ready the first time, it ought to be ready by the last time)
>         const localizedFormattedText = theOneLocalizationManager.getText(
> ```

Big Idea #2: The other thing I wanted to accomplish is that the raw format string "Level {0} of {1}" is not rendered to the user.

**Review by JohnThomson — APPROVED** [review]
LGTM. Couple of suggestions to consider, but could be merged as-is.

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4632#-:-MgHM0zq3jNu64fRgso5:b-hxn5n9)* status: all files reviewed, 4 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModelSpec.ts, line 203 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4632#-MgHLc4K2WHhEWohMWj2:-MgHLc4K2WHhEWohMWj3:b-ozgjxd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a119f20f0db997b195bc47fffb13914a3a0fa50b/src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModelSpec.ts#L203)):*
> ```XML
>     }
> 
>     it("fixes stageNofM with items in order", () => {
> ```

If you're doing another pass, this description made me think of the stages somehow being out of order. Could say "with format items in order" or, I think better, "with N before M".
Similarly below.
___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsSpec.ts, line 162 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4632#-MgHKRgB5bRsv2WRxgzq:-MgHKRgB5bRsv2WRxgzr:b-3ts09d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a119f20f0db997b195bc47fffb13914a3a0fa50b/src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsSpec.ts#L162)):*
> ```XML
>     });
> 
>     /* skipping until we figure out how to make work with localization See BL-3554
> ```

I don't suppose your changes help us to reinstate these tests? Just wondering since the localization strategy has changed.

**Review by sujeffreyl — COMMENTED** [review]
Oops, sorry. In r2, I accidentally pushed the wrong branch in git and pushed a commit that's not ready to be merged yet. 
In r3, I undo that.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4632#-:-MgMBZGc2k25HE8ngylH:b-c5xfh)* status: 6 of 10 files reviewed, 4 unresolved discussions (waiting on @JohnThomson and @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModelSpec.ts, line 203 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4632#-MgHLc4K2WHhEWohMWj2:-MgL_dKh0DLbbuoqHlGr:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a119f20f0db997b195bc47fffb13914a3a0fa50b/src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModelSpec.ts#L203)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

If you're doing another pass, this description made me think of the stages somehow being out of order. Could say "with format items in order" or, I think better, "with N before M".
Similarly below.
</blockquote></details>

Done.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4632)* status: 6 of 12 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsSpec.ts, line 162 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4632#-MgHKRgB5bRsv2WRxgzq:-MgfmOtRAtuzsUD26xdD:b-hhf6vj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a119f20f0db997b195bc47fffb13914a3a0fa50b/src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsSpec.ts#L162)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't suppose your changes help us to reinstate these tests? Just wondering since the localization strategy has changed.
</blockquote></details>

Was able to reinstate all the tests

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4632)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

**Pull request merged**
