### PR TITLE
Fix redundant / confusing book rename events (BL-10550)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4873)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4873)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1829 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4873#-Mqq88fE4I55USrFDjtX:-Mqq88fE4I55USrFDjtY:b-c3xi29) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8567462e0e3bc4bb1043c1b27ac24e50a0cb32df/src/BloomExe/CollectionTab/LibraryListView.cs#L1829)):*
> ```
> Book renamed to follow title (\"{book.TitleBestForUserDisplay}\")
> ```
I might be missing something, but this seems confusing to me.
I guess this is when the user deletes the text in the rename text box so the book name gets reset to the book title?
Is there a reason not to just do `Book renamed to \"{book.TitleBestForUserDisplay}\"`? Is it because from now on when the title changes, the book name will change whereas before it wouldn't?

I think it is the phrase "to follow title X" which is tripping me up. I'm not sure users will understand it and wonder if it is better just to go with the simple "renamed to X".

Thoughts?

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4873)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1829 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4873#-Mqq88fE4I55USrFDjtX:-MqtH6iA8CETBECS04Xq:bb0p70k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8567462e0e3bc4bb1043c1b27ac24e50a0cb32df/src/BloomExe/CollectionTab/LibraryListView.cs#L1829)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Book renamed to follow title (\"{book.TitleBestForUserDisplay}\")
> ```
I might be missing something, but this seems confusing to me.
I guess this is when the user deletes the text in the rename text box so the book name gets reset to the book title?
Is there a reason not to just do `Book renamed to \"{book.TitleBestForUserDisplay}\"`? Is it because from now on when the title changes, the book name will change whereas before it wouldn't?

I think it is the phrase "to follow title X" which is tripping me up. I'm not sure users will understand it and wonder if it is better just to go with the simple "renamed to X".

Thoughts?
</blockquote></details>

Yeah I would lean away from a special handling for this situation. This message would be appropriate for a log, but it's more detailed than we are aiming for here.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4873)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1829 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4873#-Mqq88fE4I55USrFDjtX:-Mqtus4E-wpBccZVc_vV:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8567462e0e3bc4bb1043c1b27ac24e50a0cb32df/src/BloomExe/CollectionTab/LibraryListView.cs#L1829)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Yeah I would lean away from a special handling for this situation. This message would be appropriate for a log, but it's more detailed than we are aiming for here.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4873)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
