### PR TITLE
[4.9] BL-9011 Stop saving a new placeHolder image on cut

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3977)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3977)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 84 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3977#-MIaS2Z63ZQxoQy42Jjc:-MIaS2Z63ZQxoQy42Jjd:b-ld79ar) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/556d09ac49f1fd03beaff9a4377d0db9a59bb4ae/src/BloomExe/ImageProcessing/ImageUtils.cs#L84)):*
> ProcessAndSaveImageIntoFolder

Certainly we don't ever need to process placeholder.png, but do we ever need to save it into the folder?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3977)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 84 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3977#-MIaS2Z63ZQxoQy42Jjc:-MIdyH4J20KfrjPb2lji:br3nh0o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/556d09ac49f1fd03beaff9a4377d0db9a59bb4ae/src/BloomExe/ImageProcessing/ImageUtils.cs#L84)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ProcessAndSaveImageIntoFolder

Certainly we don't ever need to process placeholder.png, but do we ever need to save it into the folder?
</blockquote></details>

We will if the `RobustFile.Exists()` fails.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3977)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 84 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3977#-MIaS2Z63ZQxoQy42Jjc:-MIeCEmN676ddS6elzsj:bgbybvu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/556d09ac49f1fd03beaff9a4377d0db9a59bb4ae/src/BloomExe/ImageProcessing/ImageUtils.cs#L84)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

We will if the `RobustFile.Exists()` fails.
</blockquote></details>

But you're checking if the image file exists at imageInfo.OriginalFilePath, not in bookFolderPath.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3977)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 84 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3977#-MIaS2Z63ZQxoQy42Jjc:-MIefpb46rs4QD9gdBdF:bnzhyqv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/556d09ac49f1fd03beaff9a4377d0db9a59bb4ae/src/BloomExe/ImageProcessing/ImageUtils.cs#L84)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

We will if the `RobustFile.Exists()` fails.
</blockquote></details>

With more understanding of the code... the answer is "no".

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3977)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 81 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3977#-MIehwV27b3xeDbzs-_9:-MIehwV30fe9UQdD2RKt:b-o9k9a4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d055f88fecb02d22fed5cfc763918b8700c29bf/src/BloomExe/ImageProcessing/ImageUtils.cs#L81)):*
> ```Smalltalk
> 
> 			if (!Directory.Exists(bookFolderPath))
> 				throw new DirectoryNotFoundException(bookFolderPath + " does not exist");
> ```

I'm not clear on the reason for moving this up. But moving it outside the try/catch seems problematic.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3977)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 84 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3977#-MIaS2Z63ZQxoQy42Jjc:-MIej2Cq7rCzQhR8nrXN:bgybbvj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/556d09ac49f1fd03beaff9a4377d0db9a59bb4ae/src/BloomExe/ImageProcessing/ImageUtils.cs#L84)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

But you're checking if the image file exists at imageInfo.OriginalFilePath, not in bookFolderPath.
</blockquote></details>

Which in the case of cutting an image (the only way to put a placeholder in, I believe), are the same thing. (See `EditingView.OnCutImage()`)
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 81 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3977#-MIehwV27b3xeDbzs-_9:-MIeichL-hKe-za9J8_z:b-fmroba) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d055f88fecb02d22fed5cfc763918b8700c29bf/src/BloomExe/ImageProcessing/ImageUtils.cs#L81)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not clear on the reason for moving this up. But moving it outside the try/catch seems problematic.
</blockquote></details>

Ah. Good point. An earlier version of my code needed it up there, but now I don't. I'll put it back.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3977)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
