### PR TITLE
Fix inserting paragraphs for instruction pages (BL-12654)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6081)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6081)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts` line 495 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6081#-NdagdU53dHdeGo-4z40:-NdagdU53dHdeGo-4z41:b2xi9vt) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e0ec11371ae5b1a02bbb9b657038bd9945e5b4e/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L495)):*
> ```XML
>                 e.stopPropagation();
>                 e.preventDefault();
>             }
> ```

I think we may be able to just not try to handle Enter ourselves at all.
A quick experiment I did indicates that wv2 does what we want on its own.

I also find that Shift-Enter is broken in our current 5.5.
I tried not handling that, and wv2 also seems to do what we want there.

So it would need some more testing, but I'm hopeful the fix here is just to remove the MakeShiftEnterInsertLineBreak function completely.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6081)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts` line 495 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6081#-NdagdU53dHdeGo-4z40:-NdbAfqB4BAobPSXjIxR:bvi2p5e) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e0ec11371ae5b1a02bbb9b657038bd9945e5b4e/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L495)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think we may be able to just not try to handle Enter ourselves at all.
A quick experiment I did indicates that wv2 does what we want on its own.

I also find that Shift-Enter is broken in our current 5.5.
I tried not handling that, and wv2 also seems to do what we want there.

So it would need some more testing, but I'm hopeful the fix here is just to remove the MakeShiftEnterInsertLineBreak function completely.
</blockquote></details>

Shift-enter inserts a <br/> element.  If that's what we want, just removing this function works perfectly as far as I can tell.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6081)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts` line 495 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6081#-NdagdU53dHdeGo-4z40:-NdbBgMP-XGNuIIpOx3X:b-e667jy) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e0ec11371ae5b1a02bbb9b657038bd9945e5b4e/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L495)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Shift-enter inserts a <br/> element.  If that's what we want, just removing this function works perfectly as far as I can tell.
</blockquote></details>

Bloom 5.4 (geckofx) inserts &lt;span class="bloom-linebreak">&lt;/span> for shift-enter.  5.5 without any special code inserts &lt;br/> (which is what I tried to type in the previous comment)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6081)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts` line 495 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6081#-NdagdU53dHdeGo-4z40:-NdbD9dh6b6QN5fIfiUv:bus4oyz) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e0ec11371ae5b1a02bbb9b657038bd9945e5b4e/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L495)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Bloom 5.4 (geckofx) inserts &lt;span class="bloom-linebreak">&lt;/span> for shift-enter.  5.5 without any special code inserts &lt;br/> (which is what I tried to type in the previous comment)
</blockquote></details>

With the existing code, 5.5 inserts the same thing as 5.4, but it doesn't display a line break visually in 5.5.  Either Chrome doesn't display empty spans, or the CSS has changed somewhere.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6081)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts` line 495 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6081#-NdagdU53dHdeGo-4z40:-NdbDpylAFjwUpSRzgAV:b-g99l1z) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e0ec11371ae5b1a02bbb9b657038bd9945e5b4e/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L495)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

With the existing code, 5.5 inserts the same thing as 5.4, but it doesn't display a line break visually in 5.5.  Either Chrome doesn't display empty spans, or the CSS has changed somewhere.
</blockquote></details>

I think what happens is that Chrome inserts the specified span, but doesn't move the insertion point to after the span.  It keeps inserting what you type in front of the span it enters for Shift-Enter.  So if you type Shift-Enter in the middle of the line, it seems to work, but it doesn't work correctly when typed at the end of a line.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6081)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts` line 495 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6081#-NdagdU53dHdeGo-4z40:-NdbkGR0-__XB8BvpR46:bej0y1m) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e0ec11371ae5b1a02bbb9b657038bd9945e5b4e/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L495)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I think what happens is that Chrome inserts the specified span, but doesn't move the insertion point to after the span.  It keeps inserting what you type in front of the span it enters for Shift-Enter.  So if you type Shift-Enter in the middle of the line, it seems to work, but it doesn't work correctly when typed at the end of a line.
</blockquote></details>

I've submitted changes that appear to work for shift-enter at the expense of going back to sometimes needing to insert &amp;zwnj; characters.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6081)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
