### PR TITLE
Refactor StyleEditor to use pug (BL-4264)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1481)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 677 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1481#-KcYUT4optnnd-2vCiHN:-KcYUT4optnnd-2vCiHO:b5rwvtf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/69cc99cad7094c24905f286d2254e6a3509561bc/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L677)):*
> ```XML
>                     // Not sufficient to hide because they have duplicate ids
>                     if (editor.authorMode) {
>                         $('#format-toolbar .hideForAuthorMode').remove();
> ```

I suppose they HAVE to have the same IDs? Feels like we're taking advantage of the browser being very forgiving about an illegal situation.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 956 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1481#-KcYTtr6OreiLUgN27Ry:-KcYTtr6OreiLUgN27Rz:b-3r8jq0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/69cc99cad7094c24905f286d2254e6a3509561bc/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L956)):*
> ```XML
>         if (!$('#' + id)) {
>             return;
>         }
> ```

This seems designed to hide a problem. But (a) I think it's redundant, since jquery is probably happy to just do nothing  if the pattern for the .html command matches nothing, and (b) if I try to populate a select that doesn't exist, I'd like to know! So I'd go for alert() rather than return, or something similar.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1481)*

**Comment by andrew-polk** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 677 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1481#-KcYUT4optnnd-2vCiHN:-KcYXFVr_nqgTic2DOS-:bazm0xz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/69cc99cad7094c24905f286d2254e6a3509561bc/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L677)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I suppose they HAVE to have the same IDs? Feels like we're taking advantage of the browser being very forgiving about an illegal situation.
</blockquote></details>

The don't HAVE to, but it is basically the exact same code (duplicated using a pug mixin).
By removing the duplicates here, the browser never receives an illegal situation. But your comment makes me wonder if the fundamental logic of having it duplicated is the right way to do it. (One of those situations where you refactor without thinking...) I will take a look and see if it can be done better.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 956 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1481#-KcYTtr6OreiLUgN27Ry:-KcYXx30FQjmFMYZ9Lzq:b-jlhqcz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/69cc99cad7094c24905f286d2254e6a3509561bc/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L956)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This seems designed to hide a problem. But (a) I think it's redundant, since jquery is probably happy to just do nothing  if the pattern for the .html command matches nothing, and (b) if I try to populate a select that doesn't exist, I'd like to know! So I'd go for alert() rather than return, or something similar.
</blockquote></details>

For
(a): It is an efficiency to leave the method early if we know there is nothing to do.
(b): It makes the calls to populateSelect simple by not needing to know which select boxes have and have not been removed from the html.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1481)*

**Comment by andrew-polk** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 677 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1481#-KcYUT4optnnd-2vCiHN:-KcYb3OqNSOkhHTmmiJt:bh6kvza) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/69cc99cad7094c24905f286d2254e6a3509561bc/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L677)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The don't HAVE to, but it is basically the exact same code (duplicated using a pug mixin).
By removing the duplicates here, the browser never receives an illegal situation. But your comment makes me wonder if the fundamental logic of having it duplicated is the right way to do it. (One of those situations where you refactor without thinking...) I will take a look and see if it can be done better.
</blockquote></details>

Well, the difference between the two scenarios is one has the tab one doesn't, so the structure is slightly different. I don't see an simple, straightforward way to improve it, but I'm sure I could figure it out if you think it is important.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1481)*

**Comment by JohnThomson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 677 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1481#-KcYUT4optnnd-2vCiHN:-KcYmD-2PYKlOY9rjnOn:b-oivovt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/69cc99cad7094c24905f286d2254e6a3509561bc/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L677)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Well, the difference between the two scenarios is one has the tab one doesn't, so the structure is slightly different. I don't see an simple, straightforward way to improve it, but I'm sure I could figure it out if you think it is important.
</blockquote></details>

It just feels as if we're very lucky that the browser recognizes two divs with the same ID and distinguishes them by class and removes the right one. Logically it should be able to assume any selector with an ID goes to a unique div. (That's why just hiding one doesn't work, I guess...because each has children with the same ids.)
One fairly simple thing to do would be for the pug to generate #tabroot and #tabrootAuthor, then if you don't want #tabrootAuthor you just delete it, if you do, delete the other and then change the ID of tabRootAuthor.
Of course we'd still be generating technically invalid HTML because of the children of those nodes that have duplicate IDs. In view of that, and since what you have works, I'm inclined to just keep it. Might be worth a comment in the pug to the effect that there are duplicate ids both at the root and in the mixin so the JS MUST delete one or the other.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 956 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1481#-KcYTtr6OreiLUgN27Ry:-KcYoVI23Sl4Najq8rwm:b-64oxvl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/69cc99cad7094c24905f286d2254e6a3509561bc/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L956)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

For
(a): It is an efficiency to leave the method early if we know there is nothing to do.
(b): It makes the calls to populateSelect simple by not needing to know which select boxes have and have not been removed from the html.
</blockquote></details>

That's fair. I think it deserves a comment explaining why sometimes not finding the select is expected.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1481)*

**Comment by andrew-polk** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 677 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1481#-KcYUT4optnnd-2vCiHN:-KcZDTF5jMbw8FVI7cAG:b-v209yy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/69cc99cad7094c24905f286d2254e6a3509561bc/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L677)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It just feels as if we're very lucky that the browser recognizes two divs with the same ID and distinguishes them by class and removes the right one. Logically it should be able to assume any selector with an ID goes to a unique div. (That's why just hiding one doesn't work, I guess...because each has children with the same ids.)
One fairly simple thing to do would be for the pug to generate #tabroot and #tabrootAuthor, then if you don't want #tabrootAuthor you just delete it, if you do, delete the other and then change the ID of tabRootAuthor.
Of course we'd still be generating technically invalid HTML because of the children of those nodes that have duplicate IDs. In view of that, and since what you have works, I'm inclined to just keep it. Might be worth a comment in the pug to the effect that there are duplicate ids both at the root and in the mixin so the JS MUST delete one or the other.

</blockquote></details>

While you are correct that we have duplicate #tabRoot elements before the remove is called, that is not what we are using to remove it. So we actually don't ever try to look up something by id when there is a duplicate. Regardless, I do think it would be much better to have all the tabs in the html once, and then hide the ones we aren't using. I think this is a special case where there is only one tab left, so don't include the tab itself. But perhaps we should generalize so that we always hide the tab if there is only one. I will look into the best way to do that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1481)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1481#-:-Kc_5IP8pKRfR1kTIVFh:bnfp4nl)*

**Pull request merged**
