### PR TITLE
BL-13703 new language chooser

### PR DESCRIPTION
**Pull request by nabalone**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769)

### CODE REVIEW

**Comment by nabalone** [comment]
I started to pull the libpalasso automatic language name setting out of Bloom, but did not finish. Those changes are in this PR along with comments on what would be left to be done. Not sure if I should pull all that out or what

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769)* status: all files reviewed, 9 unresolved discussions (waiting on @nabalone)

___
*[`src/BloomExe/web/controllers/CollectionSettingsApi.cs` line 320 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769#-OD7dKK62jCKBl5mjrF9:-OD7dKK62jCKBl5mjrFA:b-kkv4ex) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2082dd9c4c3a384163630ba474078fbc4c1388e/src/BloomExe/web/controllers/CollectionSettingsApi.cs#L320)):*
> //// Clear listeners

I think this comment is misplaced/wrong.
___
*[`src/BloomBrowserUI/collection/LanguageChooserDialog.tsx` line 24 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769#-OD7esry-YTzWGlth-BX:-OD7esry-YTzWGlth-BY:bas67ea) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2082dd9c4c3a384163630ba474078fbc4c1388e/src/BloomBrowserUI/collection/LanguageChooserDialog.tsx#L24)):*
> ```XML
> import BloomButton from "../react_components/bloomButton";
> 
> export interface ILanguageDataForBloom {
> ```

Seems odd to call this "ForBloom" within Bloom.
Do we lose something by calling it `ILanguageData`?
___
*[`src/BloomBrowserUI/collection/LanguageChooserDialog.tsx` line 31 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769#-OD7fBb48BImT4_sXIY8:-OD7fBb48BImT4_sXIY9:b-p7jktu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2082dd9c4c3a384163630ba474078fbc4c1388e/src/BloomBrowserUI/collection/LanguageChooserDialog.tsx#L31)):*
> ```XML
> }
> 
> export function formatLanguageDataForBloom(
> ```

Again, "ForBloom" seems like a misnomer.
How about `getLanguageData`?
___
*[`src/BloomBrowserUI/collection/LanguageChooserDialog.tsx` line 38 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769#-OD7ehIa29ilKBeAMZA9:-OD7ehIa29ilKBeAMZAA:b-qmj91z) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2082dd9c4c3a384163630ba474078fbc4c1388e/src/BloomBrowserUI/collection/LanguageChooserDialog.tsx#L38)):*
> ```XML
>         LanguageTag: languageTag || null,
>         DefaultName:
>             // TODO when published from language-chooser-react-mui, we should use
> ```

Isn't this published now?
___
*[`src/BloomBrowserUI/collection/LanguageChooserDialog.tsx` line 90 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769#-OD7gf18EQ9lxD7pqYLr:-OD7gf18EQ9lxD7pqYLs:bmxvr6v) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2082dd9c4c3a384163630ba474078fbc4c1388e/src/BloomBrowserUI/collection/LanguageChooserDialog.tsx#L90)):*
> ```XML
>             `}
>         >
>             <BloomButton
> ```

Can these be DialogOkButton and DialogCancelButton?

If not, let's comment why.
___
*[`src/BloomBrowserUI/collection/LanguageChooserDialog.tsx` line 162 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769#-OD7hP3l7GcY4AiueWUt:-OD7hP3l7GcY4AiueWUu:b-c1kyj3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2082dd9c4c3a384163630ba474078fbc4c1388e/src/BloomBrowserUI/collection/LanguageChooserDialog.tsx#L162)):*
> ```XML
>                         `}
>                     >
>                         Choose Language
> ```

We need to localize this.
Do you need the Typography component? If not, you can use <Div> (a custom component different than <div>). If so, you can use <Span> or <LocalizedString>.
___
*[`src/BloomExe/web/controllers/LanguageChangeEventArgs.cs` line 6 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769#-OD7c7ox2cElgfixkXDg:-OD7c7ox2cElgfixkXDh:bh21826) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2082dd9c4c3a384163630ba474078fbc4c1388e/src/BloomExe/web/controllers/LanguageChangeEventArgs.cs#L6)):*
> ```Smalltalk
> {
>     /// <summary>
>     /// Class for event args of BookDownload.BookDownloaded
> ```

This copy/pasted comment didn't get updated.
___
*[`src/BloomExe/web/controllers/LanguageChangeEventArgs.cs` line 13 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769#-OD7fowE45iRcVWeP6Gi:-OD7fowE45iRcVWeP6Gj:bzbqwuk) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2082dd9c4c3a384163630ba474078fbc4c1388e/src/BloomExe/web/controllers/LanguageChangeEventArgs.cs#L13)):*
> ```Smalltalk
>         public string DefaultName { get; set; }
>         public string DesiredName { get; set; }
>         public string Country { get; set; }
> ```

Is it true this should be kept in sync with ILanguageData(ForBloom) on the ts side?
If so, we should add comments in both places.
___
*[`src/BloomExe/Collection/CollectionSettings.cs` line 1182 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769#-OD7dnW_CUNG0gcB2fIP:-OD7dnW_CUNG0gcB2fIQ:b-qztq56) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2082dd9c4c3a384163630ba474078fbc4c1388e/src/BloomExe/Collection/CollectionSettings.cs#L1182)):*
> ```Smalltalk
>         /// BL-8174 But in case the tag includes Script/Region/Variant codes, we should show them somewhere too.
>         /// </summary>
>         // TODO make this consistent with the new Language Chooser default display name instead of using LibPalasso?
> ```

Maybe all these TODOs should be marked in some way to make them more easily searchable?
Like TODO BL-13703?
Or TODO (default name)?
Or TODO (default name BL-13703)?

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769)* status: 16 of 25 files reviewed, 9 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/collection/LanguageChooserDialog.tsx` line 24 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769#-OD7esry-YTzWGlth-BX:-OD8Zt-s-DPMsup6gQQv:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2082dd9c4c3a384163630ba474078fbc4c1388e/src/BloomBrowserUI/collection/LanguageChooserDialog.tsx#L24)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems odd to call this "ForBloom" within Bloom.
Do we lose something by calling it `ILanguageData`?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/collection/LanguageChooserDialog.tsx` line 31 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769#-OD7fBb48BImT4_sXIY8:-OD8ZtSl30a6UTeiaiJq:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2082dd9c4c3a384163630ba474078fbc4c1388e/src/BloomBrowserUI/collection/LanguageChooserDialog.tsx#L31)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Again, "ForBloom" seems like a misnomer.
How about `getLanguageData`?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/collection/LanguageChooserDialog.tsx` line 38 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769#-OD7ehIa29ilKBeAMZA9:-OD8_8y9CC0zyG6OGBXj:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2082dd9c4c3a384163630ba474078fbc4c1388e/src/BloomBrowserUI/collection/LanguageChooserDialog.tsx#L38)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Isn't this published now?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/collection/LanguageChooserDialog.tsx` line 90 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769#-OD7gf18EQ9lxD7pqYLr:-ODJ446t7xCRc4vtWy0E:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2082dd9c4c3a384163630ba474078fbc4c1388e/src/BloomBrowserUI/collection/LanguageChooserDialog.tsx#L90)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Can these be DialogOkButton and DialogCancelButton?

If not, let's comment why.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/collection/LanguageChooserDialog.tsx` line 162 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769#-OD7hP3l7GcY4AiueWUt:-ODJMJWo9idDTsOh28yH:bhlq9cr) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2082dd9c4c3a384163630ba474078fbc4c1388e/src/BloomBrowserUI/collection/LanguageChooserDialog.tsx#L162)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We need to localize this.
Do you need the Typography component? If not, you can use <Div> (a custom component different than <div>). If so, you can use <Span> or <LocalizedString>.
</blockquote></details>

Looks like Reviewable messed up your comment :(. How's an H1? Or let me know what component to use instead. I don't need the Typography component
___
*[`src/BloomExe/Collection/CollectionSettings.cs` line 1182 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769#-OD7dnW_CUNG0gcB2fIP:-ODJR8ImC0MPPHFdmGkm:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2082dd9c4c3a384163630ba474078fbc4c1388e/src/BloomExe/Collection/CollectionSettings.cs#L1182)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Maybe all these TODOs should be marked in some way to make them more easily searchable?
Like TODO BL-13703?
Or TODO (default name)?
Or TODO (default name BL-13703)?
</blockquote></details>

Done.
___
*[`src/BloomExe/web/controllers/CollectionSettingsApi.cs` line 320 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769#-OD7dKK62jCKBl5mjrF9:-ODJMmHe7AyXEcdSzV53:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2082dd9c4c3a384163630ba474078fbc4c1388e/src/BloomExe/web/controllers/CollectionSettingsApi.cs#L320)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> //// Clear listeners

I think this comment is misplaced/wrong.
</blockquote></details>

Done.
___
*[`src/BloomExe/web/controllers/LanguageChangeEventArgs.cs` line 6 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769#-OD7c7ox2cElgfixkXDg:-ODJNHWO4zjeQ2vANBaJ:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2082dd9c4c3a384163630ba474078fbc4c1388e/src/BloomExe/web/controllers/LanguageChangeEventArgs.cs#L6)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This copy/pasted comment didn't get updated.
</blockquote></details>

Done.
___
*[`src/BloomExe/web/controllers/LanguageChangeEventArgs.cs` line 13 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769#-OD7fowE45iRcVWeP6Gi:-ODJNmMY6ElO1jdIz7ud:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2082dd9c4c3a384163630ba474078fbc4c1388e/src/BloomExe/web/controllers/LanguageChangeEventArgs.cs#L13)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is it true this should be kept in sync with ILanguageData(ForBloom) on the ts side?
If so, we should add comments in both places.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nabalone)

___
*[`src/BloomBrowserUI/collection/LanguageChooserDialog.tsx` line 162 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6769#-OD7hP3l7GcY4AiueWUt:-ODMjuoeBA3vSiNkrtDA:bfreg41) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2082dd9c4c3a384163630ba474078fbc4c1388e/src/BloomBrowserUI/collection/LanguageChooserDialog.tsx#L162)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Looks like Reviewable messed up your comment :(. How's an H1? Or let me know what component to use instead. I don't need the Typography component
</blockquote></details>

Oops.
I was suggesting Div or Span. But H1 probably makes more sense.

**Pull request merged**
