### PR TITLE
Fix BL-3304 by renaming geckofxhtmltopdf.exe to BloomPdfMaker.exe

### PR DESCRIPTION
**Pull request by hatton**
The idea here is just to make it a bit more likely that a user will say "no" when an antivirus asks to quarantine this file, as AVG likes to do.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1003)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Seems like there ought to be a change to getDependencies to rename GeckoFxHtmlToPdf.exe after we retrieve it.

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[DistFiles/IntegrityFailureAdvice-en.md, line 16 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1003#-KEWuvA7pnQ3QVQCGxTj:-KEWuvA7pnQ3QVQCGxTk:1862644629) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/842969d37150dd486ff96fd7ee03770bcfb01670/DistFiles/IntegrityFailureAdvice-en.md#L16)):*
You seem to have removed the "Missing Files" section; if that was intended, the message needs more attention.

---

*[src/BloomExe/BloomExe.csproj, line 1244 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1003#-KEWw58fG9g5awla0apc:-KEWw58gBvoxzov4Flsq:1148541406) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/842969d37150dd486ff96fd7ee03770bcfb01670/src/BloomExe/BloomExe.csproj#L1244)):*
The additions above don't seem related to the name change, and I'm surprised they are needed. Surely we must have been copying these components already?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1003#-:-KEWwXUeY71AA1-2ARU6:1233174840)*

**Comment by hatton** [comment]
If so, then I'm not thinking correctly about how it works. In my thinking, we keep GFXTP.exe the same in our lib, and just rename it as we copy it.

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[DistFiles/IntegrityFailureAdvice-en.md, line 16 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1003#-KEWuvA7pnQ3QVQCGxTj:-KEX4zLprXRDSmkccYL8:1853354098) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/842969d37150dd486ff96fd7ee03770bcfb01670/DistFiles/IntegrityFailureAdvice-en.md#L16)):*
Odd, my diff here does not show removal

---

*[src/BloomExe/BloomExe.csproj, line 1244 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1003#-KEWw58fG9g5awla0apc:-KEX4vsaz_ZHacq5u0SD:-1559557167) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/842969d37150dd486ff96fd7ee03770bcfb01670/src/BloomExe/BloomExe.csproj#L1244)):*
Odd, my diff here does not show additions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1003#-:-KEX4b321cE-__MHiqeX:-1317509574)*

**Comment by hatton** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[DistFiles/IntegrityFailureAdvice-en.md, line 16 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1003#-KEWuvA7pnQ3QVQCGxTj:-KEX5XdKyIjW2RwV8hqb:178629188) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/842969d37150dd486ff96fd7ee03770bcfb01670/DistFiles/IntegrityFailureAdvice-en.md#L16)):*
But I found it. Will fix!

---

*[src/BloomExe/BloomExe.csproj, line 1244 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1003#-KEWw58fG9g5awla0apc:-KEX6C5KZvpi0Lip0Esk:64472531) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/842969d37150dd486ff96fd7ee03770bcfb01670/src/BloomExe/BloomExe.csproj#L1244)):*
OK, thanks for catching that. Previously the first 4 were done in a hand-modified version of csproj (Windows only) and VS apparently copied them in here. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1003)*

**Comment by StephenMcConnel** [comment]
I think getDependencies-xxx.sh files are generated, so it would be much harder to figure out how to get the renaming done there.

---

Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1003#-:-KEX7X_BfFYyL75wZ9Zk:1463687011)*

**Comment by JohnThomson** [comment]
They are generated from what TC does. I believe it would be fairly easy to configure TC to get GeckoFxHtmlToPdf.exe as BloomPdfMaker.exe, and hopefully the standard process of generating getDependencies would produce the right thing.
But, I can live with renaming it as we copy it from lib to output/{debug,release}. And since we don't reference it I think it will work. I just missed the change in BloomExe.csproj that was doing that.

OK, LGTM if/once the "missing files" thing is really dealt with.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[DistFiles/IntegrityFailureAdvice-en.md, line 21 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1003#-KEXRxy7JmrfYKfcWIh8:-KEXRxy7JmrfYKfcWIh9:861540497) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b63dbd89ba6f4c9b03a1ff5be734c14cf23c38f9/DistFiles/IntegrityFailureAdvice-en.md#L21)):*
This is the heading whose removal worries me (since the second commit still leaves the message telling people to look for this heading)...and I wonder whether some code is looking for it to insert some names...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1003#-:-KEXQVYLrK5QEIaj-wFS:2114613796)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DistFiles/IntegrityFailureAdvice-en.md, line 21 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1003#-KEXRxy7JmrfYKfcWIh8:-KEXtcYTEX0IGP0ijXuK:-533986464) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b63dbd89ba6f4c9b03a1ff5be734c14cf23c38f9/DistFiles/IntegrityFailureAdvice-en.md#L21)):*
it's there

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1003)*

**Pull request merged**
