### PR TITLE
Crop from Middle

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6607)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Just a couple minor things, mostly naming.

Also, your commit message and PR description still have "WIP".

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6607#-:-O4v-Zx41kIK1NfguRjG:bszcwx7)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 1372 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6607#-O4uy1Vy5jP35_pTbChq:-O4uy1Vy5jP35_pTbChr:b-a6ez6o) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/34b7e4b374cae146d9117c2ea3641e9886fe3023/src/BloomBrowserUI/bookEdit/css/editMode.less#L1372)):*
> ```Less
>     }
> 
>     &.middleButton .bloom-ui-overlay-center-handle {
> ```

I found it a little confusing that `.middleButton` is used on a parent of the button to show/hide the button.
Also, isn't it a handle more than a button (which is the nomenclature you've mostly used)?

Would it be better as something like bloom-ui-show-overlay-center-handle?

Is `reframe-handle` a better name than `center-handle`?
Or to match what you have in code, `movecrop-handle`?
___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 1163 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6607#-O4uzqDl6qdMUtsoyv0H:-O4uzqDl6qdMUtsoyv0I:b4njvem) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/34b7e4b374cae146d9117c2ea3641e9886fe3023/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L1163)):*
> ```XML
>         // the right of the overlay (this.activeElement.clientLeft + this.activElement.clientRight)
>         const newLeft = Math.max(
>             // Math.min(this.oldImageLeft + deltaX, 0);
> ```

Here are a few lines down, you have commented lines which repeat in the following line.
___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 2661 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6607#-O4v-3AD3MtxOR5aPudV:-O4v-3AD3MtxOR5aPudW:b-yl32xe) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/34b7e4b374cae146d9117c2ea3641e9886fe3023/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2661)):*
> ```XML
>         const controlFrame = document.getElementById("overlay-control-frame");
>         if (!controlFrame || !this.activeElement) return;
>         const ic = this.activeElement.getElementsByClassName(
> ```

For these very abbreviated variable names, it would be helpful to at least keep them consistent so that when working in this code, you immediately know what you're looking at.
So this would be `imgC`.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6607)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 1372 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6607#-O4uy1Vy5jP35_pTbChq:-O4w945K8TYmgOKBpzrN:b-xw9req) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/34b7e4b374cae146d9117c2ea3641e9886fe3023/src/BloomBrowserUI/bookEdit/css/editMode.less#L1372)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I found it a little confusing that `.middleButton` is used on a parent of the button to show/hide the button.
Also, isn't it a handle more than a button (which is the nomenclature you've mostly used)?

Would it be better as something like bloom-ui-show-overlay-center-handle?

Is `reframe-handle` a better name than `center-handle`?
Or to match what you have in code, `movecrop-handle`?
</blockquote></details>

I made it bloom-ui-overlay-move-crop-handle. Having some second thoughts about making these classes so verbose, since they're all inside the control frame, which already has bloom-ui to get it deleted; but at least it's consistent now.
___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 1163 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6607#-O4uzqDl6qdMUtsoyv0H:-O4w7xgi4CyoJn66_QVm:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/34b7e4b374cae146d9117c2ea3641e9886fe3023/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L1163)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Here are a few lines down, you have commented lines which repeat in the following line.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 2661 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6607#-O4v-3AD3MtxOR5aPudV:-O4w6sEWDgbP9TCQM0NM:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/34b7e4b374cae146d9117c2ea3641e9886fe3023/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2661)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

For these very abbreviated variable names, it would be helpful to at least keep them consistent so that when working in this code, you immediately know what you're looking at.
So this would be `imgC`.
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6607)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 1372 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6607#-O4uy1Vy5jP35_pTbChq:-O4wBFBl6DWNoPREoSuu:b-jmffz4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/34b7e4b374cae146d9117c2ea3641e9886fe3023/src/BloomBrowserUI/bookEdit/css/editMode.less#L1372)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I made it bloom-ui-overlay-move-crop-handle. Having some second thoughts about making these classes so verbose, since they're all inside the control frame, which already has bloom-ui to get it deleted; but at least it's consistent now.
</blockquote></details>

Thanks.

Sorry I was ambiguous. I was actually suggesting changing `bloom-ui-overlay-center-handle` to something like `bloom-ui-overlay-move-crop-handle` and changing `middleButton` to something like `bloom-ui-show-overlay-move-crop-handle`

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6607)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 1372 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6607#-O4uy1Vy5jP35_pTbChq:-O4wCw3a41F8urlcU6p4:bjbom8c) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/34b7e4b374cae146d9117c2ea3641e9886fe3023/src/BloomBrowserUI/bookEdit/css/editMode.less#L1372)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Thanks.

Sorry I was ambiguous. I was actually suggesting changing `bloom-ui-overlay-center-handle` to something like `bloom-ui-overlay-move-crop-handle` and changing `middleButton` to something like `bloom-ui-show-overlay-move-crop-handle`
</blockquote></details>

Sorry, should have realized that.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6607)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
