### PR TITLE
BL-9158 Add multiple pages with dialog

### PR DESCRIPTION
**Pull request by gmartin7**
2 commits
* 1st cleans up some types in BloomSelect
* 2nd does the multiple pages

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4043)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4043)* status: all files reviewed, 5 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomBrowserUI/react_components/smallNumberPicker.tsx, line 23 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4043#-MKa27i-0XwtRqp45SPY:-MKa27i06CG1F5-O1rP4:b-b3xrk2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/59e5059e7cdaf787474787d31cf70286f0f91f75/src/BloomBrowserUI/react_components/smallNumberPicker.tsx#L23)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     const initialValue = props.minLimit
>         ? props.minLimit
>         : props.minLimit === undefined
>         ? 1
>         : 0;
> ```
</details>

Why not `const initialValue = props.minLimit === undefined ? 1 : props.minLimit`?
Or 
> ```
>     const initialValue = props.minLimit;
>     if (initialValue === undefined) initialValue = 1;
> ```

But maybe moot. See below.
___
*[src/BloomBrowserUI/react_components/smallNumberPicker.tsx, line 66 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4043#-MKa3Rw78pHsylpEnBft:-MKa3Rw78pHsylpEnBfu:b-wjlucr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/59e5059e7cdaf787474787d31cf70286f0f91f75/src/BloomBrowserUI/react_components/smallNumberPicker.tsx#L66)):*
> ```XML
>     return (
>         <div className="smallNumberPicker">
>             {/* <NumberPickerTooltip title={props.tooltip}> */}
> ```

Any reason to keep these comments?
___
*[src/BloomBrowserUI/react_components/smallNumberPicker.tsx, line 67 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4043#-MKa3N2A-wAWTIDUFG3R:-MKa3N2A-wAWTIDUFG3S:bfgj33a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/59e5059e7cdaf787474787d31cf70286f0f91f75/src/BloomBrowserUI/react_components/smallNumberPicker.tsx#L67)):*
> ```XML
>         <div className="smallNumberPicker">
>             {/* <NumberPickerTooltip title={props.tooltip}> */}
>             <TextField onChange={handleNumberChange} value={chosenNumber} />
> ```

I think you can simply set `type="number"` on this and get rid of a bunch of logic.
https://material-ui.com/components/text-fields/

Any maybe even get rid of the component by using InputProps?
https://stackoverflow.com/a/59917771/7442826
___
*[src/BloomExe/web/controllers/AddOrChangePageApi.cs, line 46 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4043#-MKa69msA0QgXq9-XFMk:-MKa69msA0QgXq9-XFMl:b63d3pr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/59e5059e7cdaf787474787d31cf70286f0f91f75/src/BloomExe/web/controllers/AddOrChangePageApi.cs#L46)):*
> ```Smalltalk
> 			for (var i = 0; i < numberOfPagesToAdd; i++)
> 			{
> 				_templateInsertionCommand.Insert(templatePage as Page);
> ```

There's a bunch of stuff in Book.InsertPageAfter (which this will call) which only needs to happen once no matter how many pages (of the same kind) are added.
Did you consider moving the loop in there?
As it is, I'm concerned by the issues you were having trying to add 50 or more pages at once. If 50 or 30 was problematic for you, what is that number going to be for a user with 1/4 of the resources you have on your machine?
___
*[src/BloomExe/web/controllers/AddOrChangePageApi.cs, line 125 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4043#-MKa4zBBAZVCUvwDJXVM:-MKa4zBBAZVCUvwDJXVN:b9wi7vk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/59e5059e7cdaf787474787d31cf70286f0f91f75/src/BloomExe/web/controllers/AddOrChangePageApi.cs#L125)):*
> ```Smalltalk
> 			if (requestData.convertWholeBook)
> 				convertWholeBook = true;
> 			return (page, convertWholeBook, (int)requestData.numberToAdd);
> ```

Will this crash if numberToAdd isn't provided? Seems like maybe we should handle that case? And then it would probably simplify the caller code? Such that we don't need to pass anything if it is not used (no -1) and even could assume not passed = 1?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4043)* status: 5 of 13 files reviewed, 5 unresolved discussions (waiting on @andrew-polk and @gmartin7)

___
*[src/BloomBrowserUI/react_components/smallNumberPicker.tsx, line 23 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4043#-MKa27i-0XwtRqp45SPY:-MKaQkgRC1i_-IY_Zzer:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/59e5059e7cdaf787474787d31cf70286f0f91f75/src/BloomBrowserUI/react_components/smallNumberPicker.tsx#L23)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
>     const initialValue = props.minLimit
>         ? props.minLimit
>         : props.minLimit === undefined
>         ? 1
>         : 0;
> ```
Why not `const initialValue = props.minLimit === undefined ? 1 : props.minLimit`?
Or 
> ```
>     const initialValue = props.minLimit;
>     if (initialValue === undefined) initialValue = 1;
> ```

But maybe moot. See below.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/react_components/smallNumberPicker.tsx, line 66 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4043#-MKa3Rw78pHsylpEnBft:-MKaJt-aCR40F4WbOJUp:bf0ybwv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/59e5059e7cdaf787474787d31cf70286f0f91f75/src/BloomBrowserUI/react_components/smallNumberPicker.tsx#L66)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Any reason to keep these comments?
</blockquote></details>

Still trying to get the tooltips working somehow...
___
*[src/BloomBrowserUI/react_components/smallNumberPicker.tsx, line 67 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4043#-MKa3N2A-wAWTIDUFG3R:-MKaOHohE0DyQF2NMwRP:bonag09) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/59e5059e7cdaf787474787d31cf70286f0f91f75/src/BloomBrowserUI/react_components/smallNumberPicker.tsx#L67)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think you can simply set `type="number"` on this and get rid of a bunch of logic.
https://material-ui.com/components/text-fields/

Any maybe even get rid of the component by using InputProps?
https://stackoverflow.com/a/59917771/7442826
</blockquote></details>

As per our conversation/experimentation, I've added a comment about why we can't do that.
___
*[src/BloomExe/web/controllers/AddOrChangePageApi.cs, line 46 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4043#-MKa69msA0QgXq9-XFMk:-MKahM8u1AT9clQsobQj:bpgoue3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/59e5059e7cdaf787474787d31cf70286f0f91f75/src/BloomExe/web/controllers/AddOrChangePageApi.cs#L46)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

There's a bunch of stuff in Book.InsertPageAfter (which this will call) which only needs to happen once no matter how many pages (of the same kind) are added.
Did you consider moving the loop in there?
As it is, I'm concerned by the issues you were having trying to add 50 or more pages at once. If 50 or 30 was problematic for you, what is that number going to be for a user with 1/4 of the resources you have on your machine?

</blockquote></details>

You'll be happy to know we're back to adding up to 99 pages and it takes my machine about 4-5 seconds to return after doing all 99 pages with no problems! Thanks for the suggestions.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4043)* status: 5 of 13 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/web/controllers/AddOrChangePageApi.cs, line 125 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4043#-MKa4zBBAZVCUvwDJXVM:-MKakgqA8Sud3qhbwzIM:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/59e5059e7cdaf787474787d31cf70286f0f91f75/src/BloomExe/web/controllers/AddOrChangePageApi.cs#L125)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Will this crash if numberToAdd isn't provided? Seems like maybe we should handle that case? And then it would probably simplify the caller code? Such that we don't need to pass anything if it is not used (no -1) and even could assume not passed = 1?
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4043)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4043)* status: 12 of 15 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/react_components/smallNumberPicker.tsx, line 66 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4043#-MKa3Rw78pHsylpEnBft:-MKat0ycAneMN-VSobvG:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/59e5059e7cdaf787474787d31cf70286f0f91f75/src/BloomBrowserUI/react_components/smallNumberPicker.tsx#L66)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Still trying to get the tooltips working somehow...
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4043)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
