### PR TITLE
Keep readonly book folder from crashing Bloom altogether (BL-9226)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4163)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
While I see this is an improvement, we might as well give the user a message too. How about "Bloom could not delete the book."  ?

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4163#-:-MRvvokj24n_fSpVHyRe:b-z1j1jp)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/Book/BookStorage.cs, line 1676 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4163#-MRvvket-UDyeVZqfnrj:-MRvvket-UDyeVZqfnrk:b82megs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3615f22dd892e0e948f49515abb7ac4a4bbae144/src/BloomExe/Book/BookStorage.cs#L1676)):*
> ```Smalltalk
> 						ErrorMessagesHtml = WebUtility.HtmlEncode(error.Message);
> 						ErrorAllowsReporting = true;
> 						Logger.WriteEvent("*** ERROR in " + PathToExistingHtml);
> ```

Might as well tell the log what the context is here.

**Review by hatton — COMMENTED** [review]
OK, sorry, I read the original analysis more carefully. Why does l So I see that in the particular issue, something else is already giving an error, is that right? Is that the only context where this is likely to fail? I.e., what happens if the user specifically tries to delete a single book?

Would the answers to any of the above fit in a comment on this catch? Because all we can tell from the code is that we're effectively swallowing the error.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4163#-:-MRvwK6PAkvFVb20yGvg:b-1jyw3w)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
This isn't about deleting a book, it's about deleting branding.css inside the book's folder when that folder is read-only.
I've improved the error reporting and logging to be more specific, and added a screenshot to the issue.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4163#-:-MRzpx1u-bVn_ldakCKL:b470ovz)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/Book/BookStorage.cs, line 1676 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4163#-MRvvket-UDyeVZqfnrj:-MRzqEiI0VqmU1EvKnNw:b-3uhieq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3615f22dd892e0e948f49515abb7ac4a4bbae144/src/BloomExe/Book/BookStorage.cs#L1676)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Might as well tell the log what the context is here.
</blockquote></details>

Done.  I made this message to be specific about deleting the branding.css file.

**Review by hatton — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4163)* status: 1 of 2 files reviewed, all discussions resolved

**Pull request merged**
