### PR TITLE
Fix SL placeholder click handler often not working (BL-11279)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218)* status: 0 of 4 files reviewed, 2 unresolved discussions

___
*[`src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts` line 421 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218#-N48h1-D7ecMWEq2rotC:-N48h1-D7ecMWEq2rotD:b-jwdvps) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a98b4edd48f15fd11432b14027aef9356996f158/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L421)):*
> ```XML
>     }
> 
>     public getCurrentTool() {
> ```

I'm very surprised that this functionality has never been needed before? I hope I'm not doing something wrong, but I feel like it's a reasonable scenario...
___
*[`src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx` line 834 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218#-N48hGco-vJO-Y0C3Ce5:-N48hGco-vJO-Y0C3Ce6:b7n150g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a98b4edd48f15fd11432b14027aef9356996f158/src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx#L834)):*
> ```XML
>     public static theOneOverlayTool: OverlayTool | undefined;
> 
>     public static kToolId = "overlay";
> ```

This is so I can access it directly even across frames. Otherwise, I guess my code is in the page frame probably, but theOneOverlayTool is probably only defined in toolbox frame, anyhow OverlayTool.theOneOverlayTool()?.id() would return undefined, so this was a way to guarantee it was always defined in any scenario.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnThomson and @sujeffreyl)

___
*[`src/BloomBrowserUI/bookEdit/js/bloomVideo.ts` line 191 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218#-N49PTBQBHcQEkt2CkhE:-N49PTBQBHcQEkt2CkhF:b-ry65iy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a98b4edd48f15fd11432b14027aef9356996f158/src/BloomBrowserUI/bookEdit/js/bloomVideo.ts#L191)):*
> ```XML
>         if (
>             toolbox?.toolboxIsShowing() &&
>             currentToolId &&
> ```

redundant? If it's falsy it won't be equal to kToolId.
___
*[`src/BloomBrowserUI/bookEdit/js/bloomVideo.ts` line 195 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218#-N49Qufl7gDdVLC2f8RF:-N49Qufl7gDdVLC2f8RG:bd10gyb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a98b4edd48f15fd11432b14027aef9356996f158/src/BloomBrowserUI/bookEdit/js/bloomVideo.ts#L195)):*
> ```XML
>         ) {
>             // Looks like the overlay tool is selected (and the toolbox is open). Abort early.
>             return;
> ```

returning false from a jquery event handler is significant (prevents propagation and default action). I'm not clear what not returning anything will do, but you might want to do a little testing to make sure that no overlay-related behavior is suppressed.
___
*[`src/BloomBrowserUI/bookEdit/js/bloomVideo.ts` line 196 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218#-N49OWWC7kfGuA95RkX8:-N49OWWC7kfGuA95RkX9:bon7oxb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a98b4edd48f15fd11432b14027aef9356996f158/src/BloomBrowserUI/bookEdit/js/bloomVideo.ts#L196)):*
> ```XML
>             // Looks like the overlay tool is selected (and the toolbox is open). Abort early.
>             return;
>         }
> ```

Would it be useful to also check that containerDiv has a parent of class bloom-imageContainer or the class that identifies a TOP box?

I'm thinking that someone might do ordinary comics in a picture on a page that has video and picture quite separately, perhaps without ever realizing they can now do video overlays, and if they click on the independent video it would probably be good to take them to the tool.
___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 192 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218#-N49NPjT9z8D7EH_aqL9:-N49NPjU4A7NudIG0LDc:b-70rysb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ffd3a153dd2c72c98c46d9e068dd45376f32412/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L192)):*
> ```XML
>         });
>     }
> ```

I see we no longer use this class to decide whether to activate the SL tool, but are the effects described in the comment no longer needed either?
___
*[`src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx` line 834 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218#-N48hGco-vJO-Y0C3Ce5:-N49M7Vp24rL6zFg12Df:bnplll3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a98b4edd48f15fd11432b14027aef9356996f158/src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx#L834)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

This is so I can access it directly even across frames. Otherwise, I guess my code is in the page frame probably, but theOneOverlayTool is probably only defined in toolbox frame, anyhow OverlayTool.theOneOverlayTool()?.id() would return undefined, so this was a way to guarantee it was always defined in any scenario.
</blockquote></details>

You might want to check the bundle structure to make sure that using this one constant isn't bringing a whole mass of toolbox code into the page bundle. (Webpack has a mechanism to strip unused code in referenced files, but I'm not sure we ever got it working. So pulling in this one constant might pull in the whole of overlayTool.tsx and everything it references, and so on recursively.) We might need a little file with no imports for shared constants.

**Comment by sujeffreyl** [comment]
*[`src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx` line 834 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218#-N48hGco-vJO-Y0C3Ce5:-N4CyQCp0pTkm7DBo-7H:bncb0cy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a98b4edd48f15fd11432b14027aef9356996f158/src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx#L834)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

You might want to check the bundle structure to make sure that using this one constant isn't bringing a whole mass of toolbox code into the page bundle. (Webpack has a mechanism to strip unused code in referenced files, but I'm not sure we ever got it working. So pulling in this one constant might pull in the whole of overlayTool.tsx and everything it references, and so on recursively.) We might need a little file with no imports for shared constants.
</blockquote></details>

Hmm, interesting point.
So, if I change bloomVideo.ts to compare to the hard-coded constant "overlay", then I see editablePageBundle is 3662KB.
If it's compared to OverlayTool.kToolId, then the bundle size goes up 10% to 4021 KB :(

Let me think about what to do. I might just hardcode it... I have the recollection that there are tons of hardcoded strings in Bloom :(

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/js/bloomVideo.ts` line 191 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218#-N49PTBQBHcQEkt2CkhE:-N4Co33y0VDV74zBDMLg:b-dj7vt5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a98b4edd48f15fd11432b14027aef9356996f158/src/BloomBrowserUI/bookEdit/js/bloomVideo.ts#L191)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

redundant? If it's falsy it won't be equal to kToolId.
</blockquote></details>

If they are both null or they are both undefined, it would return true, which would be undesirable. "If both operands are null or both operands are undefined, return true." (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality)

At one earlier point in time (obviously with slightly different code), both the left hand side and the right hand side of the "===" returned undefined. (If your frame exports aren't all working properly)
___
*[`src/BloomBrowserUI/bookEdit/js/bloomVideo.ts` line 195 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218#-N49Qufl7gDdVLC2f8RF:-N4CpolB9NiEHBlSHgyX:bw7skye) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a98b4edd48f15fd11432b14027aef9356996f158/src/BloomBrowserUI/bookEdit/js/bloomVideo.ts#L195)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

returning false from a jquery event handler is significant (prevents propagation and default action). I'm not clear what not returning anything will do, but you might want to do a little testing to make sure that no overlay-related behavior is suppressed.
</blockquote></details>

The previous version of the code just exited out of the function (aka return undefined) in this case (actually, in all cases), so I think it is better to just return in all cases in this changelist.
___
*[`src/BloomBrowserUI/bookEdit/js/bloomVideo.ts` line 196 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218#-N49OWWC7kfGuA95RkX8:-N4CxGAr5FVqUNNauTtp:bs1umlp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a98b4edd48f15fd11432b14027aef9356996f158/src/BloomBrowserUI/bookEdit/js/bloomVideo.ts#L196)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Would it be useful to also check that containerDiv has a parent of class bloom-imageContainer or the class that identifies a TOP box?

I'm thinking that someone might do ordinary comics in a picture on a page that has video and picture quite separately, perhaps without ever realizing they can now do video overlays, and if they click on the independent video it would probably be good to take them to the tool.
</blockquote></details>

Sure, I had that as an alternative idea, they could be combined. Done.
___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 192 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218#-N49NPjT9z8D7EH_aqL9:-N4CnRUs0-vSqq0oi8oS:bmo6zr0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ffd3a153dd2c72c98c46d9e068dd45376f32412/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L192)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I see we no longer use this class to decide whether to activate the SL tool, but are the effects described in the comment no longer needed either?
</blockquote></details>

No, the effects needed in the comment are no longer needed. The removal of the "bloom-selected" class was only to support the click handler logic in bloomVideo.ts

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 192 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218#-N49NPjT9z8D7EH_aqL9:-N4DA1BQ5J5i0E_B0Ztt:bszi7fj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ffd3a153dd2c72c98c46d9e068dd45376f32412/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L192)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

No, the effects needed in the comment are no longer needed. The removal of the "bloom-selected" class was only to support the click handler logic in bloomVideo.ts
</blockquote></details>

Actually, let me think about this some more.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 192 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218#-N49NPjT9z8D7EH_aqL9:-N4DO_jD-1u42ZAGuxpd:br3znmg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ffd3a153dd2c72c98c46d9e068dd45376f32412/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L192)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Actually, let me think about this some more.
</blockquote></details>

Ok, so I changed my mind about this. I think when the overlay tool opens, we don't want video-over-picture to have the yellow border. Reverted.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218)* status: all files reviewed, 4 unresolved discussions (waiting on @sujeffreyl)

___
*[`src/BloomBrowserUI/bookEdit/js/bloomVideo.ts` line 191 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218#-N49PTBQBHcQEkt2CkhE:-N4DV2mQ7zyuSZCs0e-F:b-53ppok) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a98b4edd48f15fd11432b14027aef9356996f158/src/BloomBrowserUI/bookEdit/js/bloomVideo.ts#L191)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

If they are both null or they are both undefined, it would return true, which would be undesirable. "If both operands are null or both operands are undefined, return true." (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality)

At one earlier point in time (obviously with slightly different code), both the left hand side and the right hand side of the "===" returned undefined. (If your frame exports aren't all working properly)
</blockquote></details>

But surely, right now, ToolIds.kOverlayToolId will never be null or undefined?
___
*[`src/BloomBrowserUI/bookEdit/js/bloomVideo.ts` line 196 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218#-N49OWWC7kfGuA95RkX8:-N4DVTKA3c48SGyPII-f:b-ck8j75) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a98b4edd48f15fd11432b14027aef9356996f158/src/BloomBrowserUI/bookEdit/js/bloomVideo.ts#L196)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Sure, I had that as an alternative idea, they could be combined. Done.
</blockquote></details>

If you're doing another pass, the comment could be updated to match the improved condition ("and the video being clicked is an overlay", or perhaps better to start with that, "The video clicked is an overlay and we're showing the overlay tool, so don't switch to video tool")
___
*[`src/BloomBrowserUI/bookEdit/toolbox/toolIds.ts` line 1 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218#-N4DWtnxApHtVfS1Zv4Q:-N4DWtnxApHtVfS1Zv4R:b-g467l8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/667117f1b3570347995da3f61d333ba38f5f7a82/src/BloomBrowserUI/bookEdit/toolbox/toolIds.ts#L1)):*
> ```XML
> // Note: This class was created to have a short, easy to reference class
> ```

Might be worth a comment at the very start "DO NOT import anything into this file"
___
*[`src/BloomBrowserUI/bookEdit/toolbox/toolIds.ts` line 4 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218#-N4DXZHyE_K25wr_rx2u:-N4DXZHyE_K25wr_rx2v:b-w4vos) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/667117f1b3570347995da3f61d333ba38f5f7a82/src/BloomBrowserUI/bookEdit/toolbox/toolIds.ts#L4)):*
> ```XML
> // that wouldn't cause a lot of other things to get dragged into your bundle.
> // (Referencing a static variable in the relevant tool would cause a lot of things to get dragged into certain bundles)
> export class ToolIds {
> ```

Not seeing the benefit of the class. Wouldn't it be more natural in JS to just export the constant?

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @JohnThomson and @sujeffreyl)

___
*[`src/BloomBrowserUI/bookEdit/js/bloomVideo.ts` line 191 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218#-N49PTBQBHcQEkt2CkhE:-N4DlafLErSF0RH4i_mf:bbvb3wt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a98b4edd48f15fd11432b14027aef9356996f158/src/BloomBrowserUI/bookEdit/js/bloomVideo.ts#L191)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

But surely, right now, ToolIds.kOverlayToolId will never be null or undefined?
</blockquote></details>

I think it's more future proof with the check, but done.
___
*[`src/BloomBrowserUI/bookEdit/js/bloomVideo.ts` line 196 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218#-N49OWWC7kfGuA95RkX8:-N4DlZPz2rhamc3iuxUc:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a98b4edd48f15fd11432b14027aef9356996f158/src/BloomBrowserUI/bookEdit/js/bloomVideo.ts#L196)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

If you're doing another pass, the comment could be updated to match the improved condition ("and the video being clicked is an overlay", or perhaps better to start with that, "The video clicked is an overlay and we're showing the overlay tool, so don't switch to video tool")
</blockquote></details>

Done.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/toolbox/toolIds.ts` line 1 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218#-N4DWtnxApHtVfS1Zv4Q:-N4E8NTQ2J94cj4_3vtp:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/667117f1b3570347995da3f61d333ba38f5f7a82/src/BloomBrowserUI/bookEdit/toolbox/toolIds.ts#L1)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Might be worth a comment at the very start "DO NOT import anything into this file"
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/toolIds.ts` line 4 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218#-N4DXZHyE_K25wr_rx2u:-N4E8N3S8d6oqhsZK0bC:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/667117f1b3570347995da3f61d333ba38f5f7a82/src/BloomBrowserUI/bookEdit/toolbox/toolIds.ts#L4)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Not seeing the benefit of the class. Wouldn't it be more natural in JS to just export the constant?
</blockquote></details>

Done.

**Pull request merged**
