### PR TITLE
Support custom branding BL-3817

### PR DESCRIPTION
**Pull request by hatton**
Currently we support cover, title page, and back cover.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1208)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 58 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1208#-KSmUJdl78Xfd2bjns5d:-KSmUJdmuvQUialZwElM:bn5zpgh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3242a8d7fcb2231181aef8c8f0b151599fe616d7/src/BloomExe/Collection/CollectionSettingsDialog.cs#L58)):*
> ```Smalltalk
> //		                                                  UpdateDisplay();
> //		                                              };
> ```

I cleaned out a bunch of cruft in there, related to experimental features dropped a long time ago.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1208)*

**Comment by gmartin7** [comment]
Reviewed 5 of 20 files at r1.
Review status: 5 of 20 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/BloomBrowserUI/xMatter/bloom-xmatter-common.less, line 151 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1208#-KSrGM__vSLNGhDmG_DR:-KSrGM__vSLNGhDmG_DS:b-8j7vxd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4562817e37046865531dc6cde01ae17f480541c/src/BloomBrowserUI/xMatter/bloom-xmatter-common.less#L151)):*
> ```Less
>         .branding {
>             order: 0; // first (left) in the flex list
>             margin: 0; //unlike a long of logo placements, we're not trying to center this one with left/right auto margins
> ```

"a long of logo placements"?

---

*[src/BloomBrowserUI/xMatter/bloom-xmatter-common.less, line 157 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1208#-KSrGi9Eznu97wJ_bM8F:-KSrGi9Eznu97wJ_bM8G:b-1pm93k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4562817e37046865531dc6cde01ae17f480541c/src/BloomBrowserUI/xMatter/bloom-xmatter-common.less#L157)):*
> ```Less
>         // this contains the smallCoverCredits text box row, followed by the row that has the language names and topic
>         .bottomTextContent{
>             flex: 1 0 auto; // how this is desires to take up space relative to its parent, bottomBlock
> ```

"how this is desires to"?

---

*[src/BloomBrowserUI/xMatter/bloom-xmatter-common.less, line 455 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1208#-KSrHC1lYF7Ph0F59R7W:-KSrHC1lYF7Ph0F59R7X:b5dy3qh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4562817e37046865531dc6cde01ae17f480541c/src/BloomBrowserUI/xMatter/bloom-xmatter-common.less#L455)):*
> ```Less
> }
> 
> // we might end up with some branding that isn't supposed to be anchored at the bottom, but at the momement, this all we have
> ```

s/b "but at the moment, this is all we have"

---

*[src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs, line 715 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1208#-KSrKSN0yMs-Te9U9a_8:-KSrKSN0yMs-Te9U9a_9:b-j2nr13) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4562817e37046865531dc6cde01ae17f480541c/src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs#L715)):*
> ```Smalltalk
> 			this._L10NSharpExtender.SetLocalizableToolTip(this._brandingCombo, null);
> 			this._L10NSharpExtender.SetLocalizationComment(this._brandingCombo, null);
> 			this._L10NSharpExtender.SetLocalizingId(this._brandingCombo, "CollectionSettingsDialog._fontComboLanguage3");
> ```

_fontComboLanguage3?

---

*[src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs, line 728 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1208#-KSrKcH8_aWsrbe9Ave5:-KSrKcH8_aWsrbe9Ave6:b5inkb0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4562817e37046865531dc6cde01ae17f480541c/src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs#L728)):*
> ```Smalltalk
> 			this._L10NSharpExtender.SetLocalizableToolTip(this.label2, null);
> 			this._L10NSharpExtender.SetLocalizationComment(this.label2, "{0} is a language name.");
> 			this._L10NSharpExtender.SetLocalizingId(this.label2, "CollectionSettingsDialog.BookMakingTab.DefaultFontFor");
> ```

The previous 2 lines don't look right to me. Am I missing something?

---

*[src/BloomExe/Collection/CollectionSettingsDialog.resx, line 125 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1208#-KSrKzfFkOyT8l6ZsemT:-KSrKzfFkOyT8l6ZsemU:b-wnay6d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4562817e37046865531dc6cde01ae17f480541c/src/BloomExe/Collection/CollectionSettingsDialog.resx#L125)):*
> ```XML
>   <metadata name="_L10NSharpExtender.TrayLocation" type="System.Drawing.Point, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
>     <value>159, 17</value>
>   </metadata>
> ```

Odd... did this get duplicated somehow?

---

*[src/BloomExe/web/controllers/BrandingApi.cs, line 20 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1208#-KSrLnChJxPT61LbQ1oA:-KSrLnCivlyBOd4Pbep9:bn17q1u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4562817e37046865531dc6cde01ae17f480541c/src/BloomExe/web/controllers/BrandingApi.cs#L20)):*
> ```Smalltalk
> 		public void RegisterWithServer(EnhancedImageServer server)
> 		{
> 			server.RegisterEndpointHandler("branding/image", request =>
> ```

interesting... I'm looking forward to learning about these APIs (new since I worked on Bloom last).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1208)*

**Comment by gmartin7** [comment]
Reviewed 10 of 20 files at r1.
Review status: 15 of 20 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1208)*

**Comment by gmartin7** [comment]
Reviewed 5 of 20 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1208)*

**Comment by hatton** [comment]
Thanks @gmartin7

**Pull request merged**
