### PR TITLE
Add File meddling for debugging (BL-12669)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6100)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6100)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/FileMeddler/FileMeddler.csproj` line 1 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6100#-NfNGnFK5Qd_4wRCWEhJ:-NfNGnFK5Qd_4wRCWEhK:b3z6635) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2c597ad5fc4757dbbd559fda9eaeb547452c146c/src/FileMeddler/FileMeddler.csproj#L1)):*
> ```XML
> <Project Sdk="Microsoft.NET.Sdk">
> ```

Seems like it would be better to just ship the FileMeddler exe instead of forking it this way?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6100)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/FileMeddler/FileMeddler.csproj` line 1 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6100#-NfNGnFK5Qd_4wRCWEhJ:-NfmYoCF-bxWr2pnm_5j:bd65ojk) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2c597ad5fc4757dbbd559fda9eaeb547452c146c/src/FileMeddler/FileMeddler.csproj#L1)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Seems like it would be better to just ship the FileMeddler exe instead of forking it this way?
</blockquote></details>

How is the .exe going to be produced and consumed?  If we don't want to incorporate the code into the Bloom project, going all the way to publishing a nuget package to share with the world seems better than setting up a private build somewhere.  But I don't know how to set up either kind of build.  And the root repo being in your private account complicates matters a bit further.
I did consider using a git submodule to incorporate the code into Bloom, but I really would rather not go down that path.

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6100)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/FileMeddler/FileMeddler.csproj` line 1 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6100#-NfNGnFK5Qd_4wRCWEhJ:-Nfmc-0N1QiBj7MwcwVT:b-vclyr9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2c597ad5fc4757dbbd559fda9eaeb547452c146c/src/FileMeddler/FileMeddler.csproj#L1)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

How is the .exe going to be produced and consumed?  If we don't want to incorporate the code into the Bloom project, going all the way to publishing a nuget package to share with the world seems better than setting up a private build somewhere.  But I don't know how to set up either kind of build.  And the root repo being in your private account complicates matters a bit further.
I did consider using a git submodule to incorporate the code into Bloom, but I really would rather not go down that path.
</blockquote></details>

we have a small number of artifacts that we don't build. ghostscript, Lame, help files... this exe can go in like those do, however that is.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6100)* status: 4 of 12 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/FileMeddler/FileMeddler.csproj` line 1 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6100#-NfNGnFK5Qd_4wRCWEhJ:-NfrgKxT4nAB6bWJKcyP:b-a45dba) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2c597ad5fc4757dbbd559fda9eaeb547452c146c/src/FileMeddler/FileMeddler.csproj#L1)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

we have a small number of artifacts that we don't build. ghostscript, Lame, help files... this exe can go in like those do, however that is.
</blockquote></details>

OK, I've added meddle.exe to the bloom-win32-static-dependencies project on TeamCity.  (with Andrew's help)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 10 files at r1, 1 of 1 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6100)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/FileMeddler/FileMeddler.csproj` line 1 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6100#-NfNGnFK5Qd_4wRCWEhJ:-Nfv_Vqt7QcFJVHEJuWi:b-e38gjo) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2c597ad5fc4757dbbd559fda9eaeb547452c146c/src/FileMeddler/FileMeddler.csproj#L1)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

OK, I've added meddle.exe to the bloom-win32-static-dependencies project on TeamCity.  (with Andrew's help)
</blockquote></details>

@hatton 
Ready to merge now?

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6100)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @StephenMcConnel)

___
*[`src/FileMeddler/FileMeddler.csproj` line 1 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6100#-NfNGnFK5Qd_4wRCWEhJ:-Nfw9Y7Y1qVhKzfDhQUu:b32wtd) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2c597ad5fc4757dbbd559fda9eaeb547452c146c/src/FileMeddler/FileMeddler.csproj#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

@hatton 
Ready to merge now?
</blockquote></details>

ok

**Pull request merged**
