### PR TITLE
BL-6257 Detect when cover thumbnail image is ready

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2614)

### CODE REVIEW

**Comment by hatton** [comment]
It would be great if we could wire to the page or the image's onLoad event instead of guessing one ever-increasing amount of time? Is there JS active on this page when it's being rendered? Could it put something into the DOM to tell us when it is ready, and we could sleep/check/sleep/check?

**Review by hatton — COMMENTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2614)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/HtmlThumbNailer.cs, line 22 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2614#-LICI5CkCPEIUsGY5P8U:-LICI5Cl6zmvOAzlVtfs:bni0f0e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/51058f2b3528976aa286d42e1189b930e8fd5a9a/src/BloomExe/HtmlThumbNailer.cs#L22)):*
> ```Smalltalk
> using Bloom.Book;
> using Bloom.Properties;
> using Bloom.Publish.Android;
> ```

What brings Android in? Does something need to be refactored to put in a more reasonable place?
___
*[src/BloomExe/HtmlThumbNailer.cs, line 496 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2614#-LICJ5BfCWHrqFr_Nm4S:-LICJ5Bg5-n1VzlgkvF_:b-nlgu8d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/51058f2b3528976aa286d42e1189b930e8fd5a9a/src/BloomExe/HtmlThumbNailer.cs#L496)):*
> ```Smalltalk
> 						catch (Exception e)
> 						{
> ```

Exception swallow want obligatory comment about what will happen :-)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2614)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/HtmlThumbNailer.cs, line 22 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2614#-LICI5CkCPEIUsGY5P8U:-LICoIf7-otbg8KoQJ8y:b54em8w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/51058f2b3528976aa286d42e1189b930e8fd5a9a/src/BloomExe/HtmlThumbNailer.cs#L22)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

What brings Android in? Does something need to be refactored to put in a more reasonable place?
</blockquote></details>

I DID move it to a more reasonable place! But forgot to remove the 'using' declaration.
___
*[src/BloomExe/HtmlThumbNailer.cs, line 496 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2614#-LICJ5BfCWHrqFr_Nm4S:-LICti0GBRS6gcbgynmZ:b-hgk3y1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/51058f2b3528976aa286d42e1189b930e8fd5a9a/src/BloomExe/HtmlThumbNailer.cs#L496)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Exception swallow want obligatory comment about what will happen :-)
</blockquote></details>

I reworked it so the exception swallowing shouldn't be needed.

**Review by hatton — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2614)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @hatton)

**Pull request merged**
