### PR TITLE
Prevent bad bookshelf from showing in bulk bloompub publish (BL-12215)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5873)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5873)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/contentful/UseContentful.tsx` line 32 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5873#-NWEDAe_8PeypjBWsHqf:-NWEDAe_8PeypjBWsHqg:bschazj) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d2de276fc86972facf2aeebd42a82462a82063f1/src/BloomBrowserUI/contentful/UseContentful.tsx#L32)):*
> ```XML
>     const queryString = JSON.stringify(query);
>     useEffect(() => {
>         if (!query || query["fields.urlKey"] === "") {
> ```

I think a comment is needed here, and possibly an adjustment to the block comment on the method. What is the significance of this field being an empty string? Does that mean something different from it being null or undefined? Why would it be missing other than a bug in the caller? Why (if not otherwise obvious) would that trigger returning without doing the query?
___
*[`src/BloomBrowserUI/contentful/UseContentful.tsx` line 65 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5873#-NWEDqea06PaXLsGRrjO:-NWEDqea06PaXLsGRrjP:bc3g4vq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d2de276fc86972facf2aeebd42a82462a82063f1/src/BloomBrowserUI/contentful/UseContentful.tsx#L65)):*
> ```XML
> 
>     if (!query || query["fields.urlKey"] === "") {
>         // now we're past the hooks, we can take our early exit.
> ```

Likewise, why is this result appropriate for an empty fields.urlKey? Do we expect a later render with a query that does have this information?
___
*[`src/BloomExe/Collection/CollectionSettingsDialog.cs` line 313 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5873#-NWEEkEf4xCplP3NMpMW:-NWEEkEf4xCplP3NMpMX:bz2mif9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d2de276fc86972facf2aeebd42a82462a82063f1/src/BloomExe/Collection/CollectionSettingsDialog.cs#L313)):*
> ```Smalltalk
> 			_collectionSettings.SubscriptionCode = _subscriptionCode;
> 			if (oldBrand != _brand)
> 				_collectionSettings.DefaultBookshelf = "";
> ```

This doesn't seem as though it would be right if we're switching to a valid branding. Don't we want its idea of the right default bookshelf?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5873)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/contentful/UseContentful.tsx` line 32 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5873#-NWEDAe_8PeypjBWsHqf:-NWEWQcq3OCe26ud-_Uz:b-8td55u) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d2de276fc86972facf2aeebd42a82462a82063f1/src/BloomBrowserUI/contentful/UseContentful.tsx#L32)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think a comment is needed here, and possibly an adjustment to the block comment on the method. What is the significance of this field being an empty string? Does that mean something different from it being null or undefined? Why would it be missing other than a bug in the caller? Why (if not otherwise obvious) would that trigger returning without doing the query?
</blockquote></details>

I've revamped the fix to pass in undefined when the urlKey is falsy.  I've also added a bit of commentary to explain things.
___
*[`src/BloomBrowserUI/contentful/UseContentful.tsx` line 65 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5873#-NWEDqea06PaXLsGRrjO:-NWEdsNi1upMch6Vy7lW:bpo6whq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d2de276fc86972facf2aeebd42a82462a82063f1/src/BloomBrowserUI/contentful/UseContentful.tsx#L65)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Likewise, why is this result appropriate for an empty fields.urlKey? Do we expect a later render with a query that does have this information?
</blockquote></details>

An empty urlKey indiicates that we don't have anything to fetch.  But I've adjusted the code in the calling method to recognize the situation and pass in query===undefined.  (taking undue advantage of it being an "any" type)
___
*[`src/BloomExe/Collection/CollectionSettingsDialog.cs` line 313 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5873#-NWEEkEf4xCplP3NMpMW:-NWEVe2p4lc6HAEw0x0K:b-mx7x2c) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d2de276fc86972facf2aeebd42a82462a82063f1/src/BloomExe/Collection/CollectionSettingsDialog.cs#L313)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This doesn't seem as though it would be right if we're switching to a valid branding. Don't we want its idea of the right default bookshelf?
</blockquote></details>

If a branding has only one bookshelf, I suppose that somehow we could figure that out, but if it has multiple bookshelves I don't think we can tell which should be the chosen one.  (I think DefaultBookshelf might be better named as CurrentBookshelf, but that's a separate issue.)
We've never tried to automatically set a default bookshelf.  And we've never tried to clear out a stale bookshelf setting, which is what I'm trying to do.  I would argue that the latter is far more important.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5873)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/contentful/UseContentful.tsx` line 65 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5873#-NWEDqea06PaXLsGRrjO:-NWEj5GZ7oURu1px0sxD:b-lojz7v) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d2de276fc86972facf2aeebd42a82462a82063f1/src/BloomBrowserUI/contentful/UseContentful.tsx#L65)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

An empty urlKey indiicates that we don't have anything to fetch.  But I've adjusted the code in the calling method to recognize the situation and pass in query===undefined.  (taking undue advantage of it being an "any" type)
</blockquote></details>

much better. Thanks.
___
*[`src/BloomExe/Collection/CollectionSettingsDialog.cs` line 313 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5873#-NWEEkEf4xCplP3NMpMW:-NWEjKyP-JDDvLTuENJz:buewg5x) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d2de276fc86972facf2aeebd42a82462a82063f1/src/BloomExe/Collection/CollectionSettingsDialog.cs#L313)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

If a branding has only one bookshelf, I suppose that somehow we could figure that out, but if it has multiple bookshelves I don't think we can tell which should be the chosen one.  (I think DefaultBookshelf might be better named as CurrentBookshelf, but that's a separate issue.)
We've never tried to automatically set a default bookshelf.  And we've never tried to clear out a stale bookshelf setting, which is what I'm trying to do.  I would argue that the latter is far more important.
</blockquote></details>

I suppose it's the bookshelf that is currently the default one to put uploaded books on. So it has elements of both meanings.
Maybe comment "We don't know which if any of the new branding's bookshelves we should upload to by default, but it will certainly be wrong to upload to one that belongs to some previous branding"

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5873)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/contentful/UseContentful.tsx` line 65 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5873#-NWEDqea06PaXLsGRrjO:-NWEpfuvC7rn7SiocCGR:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d2de276fc86972facf2aeebd42a82462a82063f1/src/BloomBrowserUI/contentful/UseContentful.tsx#L65)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

much better. Thanks.
</blockquote></details>

Done.
___
*[`src/BloomExe/Collection/CollectionSettingsDialog.cs` line 313 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5873#-NWEEkEf4xCplP3NMpMW:-NWEpywR7rbETeSkoRYK:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d2de276fc86972facf2aeebd42a82462a82063f1/src/BloomExe/Collection/CollectionSettingsDialog.cs#L313)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I suppose it's the bookshelf that is currently the default one to put uploaded books on. So it has elements of both meanings.
Maybe comment "We don't know which if any of the new branding's bookshelves we should upload to by default, but it will certainly be wrong to upload to one that belongs to some previous branding"
</blockquote></details>

Done.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5873)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
