### PR TITLE
Stop removing transparency from all incoming images (BL-9349)

### PR DESCRIPTION
**Pull request by andrew-polk**
This warrants some discussion before merging. For one thing, it targets 4.9. So I've made it a draft even though the code change is complete.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4125)

### CODE REVIEW

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4125)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 95 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4125#-MQCkWufCFxIhMOsA2Vj:-MQCkWufCFxIhMOsA2Vk:b-dto8pg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/83b233dd63845910802fe4a2b5d5c4d22579a29f/src/BloomExe/ImageProcessing/ImageUtils.cs#L95)):*
> ```Smalltalk
> 				if (size.Width != imageInfo.Image.Width || size.Height != imageInfo.Image.Height)
> 				{
> 					// need to shrink jpeg file since it's larger than our maximum allowed size.
> ```

old comment mentions jpegs but it's now all types?
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 590 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4125#-MQCkotD00bcShHAOafd:-MQCkotD00bcShHAOafe:b-mr07cr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/83b233dd63845910802fe4a2b5d5c4d22579a29f/src/BloomExe/ImageProcessing/ImageUtils.cs#L590)):*
> ```Smalltalk
> 		/// If it becomes too difficult or expensive to determine, we punt and return false.
> 		/// </summary>
> 		public static bool HasTransparency(Image image)
> ```

This code looks familiar. Was it removed and you're putting it back? It matters because if we used it for years, we don't have to re-review it carefully.

**Comment by andrew-polk** [comment]
The first `if` of HasTransparency is basically the reverse of the logic in the method just above, `IsIndexedAndOpaque`. That is a fairly new method. But the subsequent pixel-by-pixel check is completely new.

**Review by StephenMcConnel — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4125)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 95 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4125#-MQDDa8L34S5QHVaaf2-:-MQDDa8L34S5QHVaaf20:b-wtw9bm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce46a4e4d07d8ce32bdf00db7ec32ff82e11959d/src/BloomExe/ImageProcessing/ImageUtils.cs#L95)):*
> ```Smalltalk
> 				if (size.Width != imageInfo.Image.Width || size.Height != imageInfo.Image.Height)
> 				{
> 					// need to shrink image file since it's larger than our maximum allowed size.
> ```

Should we retain the comment about it being safe to replace imageInfo.Image that was part of the deleted block?
I'll leave that to your discretion.
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 605 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4125#-MQDCqECECBQiFSMEbSg:-MQDCqED32HE_HFTh5TU:bfocqi0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce46a4e4d07d8ce32bdf00db7ec32ff82e11959d/src/BloomExe/ImageProcessing/ImageUtils.cs#L605)):*
> ```Smalltalk
> 			{
> 				// Yes, this is as expensive as it looks. But we take advantage of the fact that almost all
> 				// transparent images which someone would use in Bloom would be transparent in the corner.
> ```

This only checks one corner, but as a heuristic I suppose that's okay.
___
*[src/BloomTests/ImageProcessing/ImageUtilsTests.cs, line 77 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4125#-MQDEzGi1lR8RFZ5qflJ:-MQDEzGi1lR8RFZ5qflK:b-733yb0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce46a4e4d07d8ce32bdf00db7ec32ff82e11959d/src/BloomTests/ImageProcessing/ImageUtilsTests.cs#L77)):*
> ```Smalltalk
> 		[TestCase("shirt.png")]
> 		// I think shirt.png still has a transparent background after being fixed by optipng, but I'm not absolutely sure,
> 		// so I'm leaving both tests in place.
> ```

Is this comment about "both tests" still accurate, or should it be removed?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4125)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 95 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4125#-MQDDa8L34S5QHVaaf2-:-MQDKkT24n4SYTnjET4b:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce46a4e4d07d8ce32bdf00db7ec32ff82e11959d/src/BloomExe/ImageProcessing/ImageUtils.cs#L95)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Should we retain the comment about it being safe to replace imageInfo.Image that was part of the deleted block?
I'll leave that to your discretion.

</blockquote></details>

Done.
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 605 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4125#-MQDCqECECBQiFSMEbSg:-MQDKES4Bn4dJ0atmwJT:bps7dn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce46a4e4d07d8ce32bdf00db7ec32ff82e11959d/src/BloomExe/ImageProcessing/ImageUtils.cs#L605)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

This only checks one corner, but as a heuristic I suppose that's okay.
</blockquote></details>

Yeah, I'm ok with it until we have a specific image which proves this is insufficient.
___
*[src/BloomTests/ImageProcessing/ImageUtilsTests.cs, line 77 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4125#-MQDEzGi1lR8RFZ5qflJ:-MQDJK9O5V_1AmIDVor8:b-39owun) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce46a4e4d07d8ce32bdf00db7ec32ff82e11959d/src/BloomTests/ImageProcessing/ImageUtilsTests.cs#L77)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Is this comment about "both tests" still accurate, or should it be removed?
</blockquote></details>

I don't fully understand it. But I think it means that's why we have shirtWithTransparentBg as well as shirt.
So as far as I know it is is still relevant.
Certainly the change I made to combine the two tests into one didn't affect its relevancy.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4125)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 95 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4125#-MQCkWufCFxIhMOsA2Vj:-MQDLAei1MXwH1MZjNSN:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/83b233dd63845910802fe4a2b5d5c4d22579a29f/src/BloomExe/ImageProcessing/ImageUtils.cs#L95)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

old comment mentions jpegs but it's now all types?
</blockquote></details>

Done.
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 590 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4125#-MQCkotD00bcShHAOafd:-MQDLEPHBAuW1TiU0AG8:b-sykmko) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/83b233dd63845910802fe4a2b5d5c4d22579a29f/src/BloomExe/ImageProcessing/ImageUtils.cs#L590)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This code looks familiar. Was it removed and you're putting it back? It matters because if we used it for years, we don't have to re-review it carefully.
</blockquote></details>

The first if of HasTransparency is basically the reverse of the logic in the method just above, IsIndexedAndOpaque. That is a fairly new method. But the subsequent pixel-by-pixel check is completely new.

**Review by StephenMcConnel — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4125#-:-MQDQ78B8EYA5vqu5vE5:bg7igkv)* status: all files reviewed, 4 unresolved discussions (waiting on @hatton and @StephenMcConnel)

**Review by hatton — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4125)* status: all files reviewed, 4 unresolved discussions (waiting on @hatton and @StephenMcConnel)

**Pull request merged**
