### PR TITLE
Mask problematic history event type enumeration change (BL-13140)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
We should add a big warning comment to make sure we don't do this again.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345#-:-NsJdayr1UbEBljqNZA0:b7o9ntu)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/History/BookHistory.cs` line 79 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345#-NsJeK3z9UkXWVd3H7CC:-NsJeK3z9UkXWVd3H7CD:bqozd2p) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/30189953675a214b2f918116a195a631d3a229f7/src/BloomExe/History/BookHistory.cs#L79)):*
> ```Smalltalk
> 		/// See BL-13140.  Better heuristics are welcome, if you can think of any.
> 		/// </remarks>
> 		public static void FixEventTypesForEnumerationChange(List<BookHistoryEvent> events)
> ```

Should this be set up as some kind of migration so we only do it once?
We do have some other migrations like that.
___
*[`src/BloomExe/History/BookHistory.cs` line 117 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345#-NsJdvt-B1ZGRpKeOpGe:-NsJdvt-B1ZGRpKeOpGf:b9try5t) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/30189953675a214b2f918116a195a631d3a229f7/src/BloomExe/History/BookHistory.cs#L117)):*
> ```Smalltalk
> 				// the change was made to the BookHistoryEventType enumeration.
> 				else if (ev.BloomVersion == "5.6.0.0" /* developer build */ ||
> 					Regex.IsMatch(ev.BloomVersion, "^5\\.6\\.1[0-9][0-9][0-9]\\.", RegexOptions.CultureInvariant))
> ```

Can't we figure out exactly which release, beta, and alpha builds got this change?
Then, if we decide to ignore problems from developer builds, I think we can get rid of this else if?

**Review by StephenMcConnel — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345#-:-NsK9g0Q52uoypPd8Ts-:b-896fix)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/History/BookHistory.cs` line 79 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345#-NsJeK3z9UkXWVd3H7CC:-NsKP8kP6swjBj59I6EM:bjblqq7) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/30189953675a214b2f918116a195a631d3a229f7/src/BloomExe/History/BookHistory.cs#L79)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should this be set up as some kind of migration so we only do it once?
We do have some other migrations like that.
</blockquote></details>

Fixing the history.db file is trickier (and riskier) than masking the problem.  But possibly worth it.
___
*[`src/BloomExe/History/BookHistory.cs` line 117 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345#-NsJdvt-B1ZGRpKeOpGe:-NsKOxqgAKUX8vUPfInN:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/30189953675a214b2f918116a195a631d3a229f7/src/BloomExe/History/BookHistory.cs#L117)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Can't we figure out exactly which release, beta, and alpha builds got this change?
Then, if we decide to ignore problems from developer builds, I think we can get rid of this else if?
</blockquote></details>

Done.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/History/BookHistory.cs` line 79 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345#-NsJeK3z9UkXWVd3H7CC:-NsKmCqI5lJyvTQzUvHb:bqy7uti) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/30189953675a214b2f918116a195a631d3a229f7/src/BloomExe/History/BookHistory.cs#L79)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Fixing the history.db file is trickier (and riskier) than masking the problem.  But possibly worth it.
</blockquote></details>

I think repairing the actual database files would be possible if only books had history.db files, but there's also a collection level history.db file.  How would we tell whether or not that file had already been repaired?  I'm inclined to go with the intercept and mask approach for now.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/History/BookHistory.cs` line 79 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345#-NsJeK3z9UkXWVd3H7CC:-NsL52ydCeJbdDzD4bgK:b-k3iyhu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/30189953675a214b2f918116a195a631d3a229f7/src/BloomExe/History/BookHistory.cs#L79)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I think repairing the actual database files would be possible if only books had history.db files, but there's also a collection level history.db file.  How would we tell whether or not that file had already been repaired?  I'm inclined to go with the intercept and mask approach for now.
</blockquote></details>

Sorry; I actually hadn't realized you weren't changing the records despite you stating it in the commit message.
___
*[`src/BloomExe/History/BookHistory.cs` line 117 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345#-NsJdvt-B1ZGRpKeOpGe:-NsL5iXcAkxXHWbRxjYx:b-bjmj92) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/30189953675a214b2f918116a195a631d3a229f7/src/BloomExe/History/BookHistory.cs#L117)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think this covers release and alpha. Did the beta get this with the first released version?
Probably good to be explicit in the comment.
___
*[`src/BloomExe/History/BookHistory.cs` line 77 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345#-NsL5NuD5wKY9Bm9IroW:-NsL5NuD5wKY9Bm9IroX:b1mvmot) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f7d4a205bf3276631682643ced449788edf2ed42/src/BloomExe/History/BookHistory.cs#L77)):*
> Better heuristics are welcome, if you can think of any.

Let's remove this comment as it will be confusing later.
___
*[`src/BloomExe/History/BookHistory.cs` line 86 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345#-NsL5TUK2HWA9A3Rc4c-:-NsL5TUK2HWA9A3Rc4c0:b-mobj50) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f7d4a205bf3276631682643ced449788edf2ed42/src/BloomExe/History/BookHistory.cs#L86)):*
> 					// Some events with the broken type may have crept in while Bloom 5.6 was in alpha before
>					// the change was made to the BookHistoryEventType enumeration.

I think it would be more accurate to state that events before channel x, version y DO have the broken type.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/History/BookHistory.cs` line 117 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345#-NsJdvt-B1ZGRpKeOpGe:-NsOwRxhCsQ5hxMm9Hu2:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/30189953675a214b2f918116a195a631d3a229f7/src/BloomExe/History/BookHistory.cs#L117)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this covers release and alpha. Did the beta get this with the first released version?
Probably good to be explicit in the comment.
</blockquote></details>

Done.
___
*[`src/BloomExe/History/BookHistory.cs` line 77 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345#-NsL5NuD5wKY9Bm9IroW:-NsOupRr-V1AxbAYizH4:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f7d4a205bf3276631682643ced449788edf2ed42/src/BloomExe/History/BookHistory.cs#L77)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> Better heuristics are welcome, if you can think of any.

Let's remove this comment as it will be confusing later.
</blockquote></details>

Done.
___
*[`src/BloomExe/History/BookHistory.cs` line 86 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345#-NsL5TUK2HWA9A3Rc4c-:-NsOwWykAu3NUhTGlpEp:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f7d4a205bf3276631682643ced449788edf2ed42/src/BloomExe/History/BookHistory.cs#L86)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> 					// Some events with the broken type may have crept in while Bloom 5.6 was in alpha before
>					// the change was made to the BookHistoryEventType enumeration.

I think it would be more accurate to state that events before channel x, version y DO have the broken type.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
Approving but I asked @JohnThomson to take a look.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345#-:-NsP4t8442YXDvWFMwEH:b-s036ra)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by JohnThomson — COMMENTED** [review]
Let's make an explicit unit test that will fail if someone messes this up, along the lines

```
Assert.That((int)BookHistoryEventType.CheckOut, Is.EqualTo(0));
Assert.That((int)BookHistoryEventType.CheckIn, Is.EqualTo(1));
```

Possibly worth listing out every one of them!, given the grief this can cause.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345#-:-NsP5FQx18dh18xa4mlP:b-gemzy1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by JohnThomson — COMMENTED** [review]
Another way to make it difficult to change by mistake is to make the enum explicit, i.e.

```
public enum BookHistoryEventType
	{
		CheckOut = 0,
		CheckIn = 1,
		Created = 2,
		Renamed = 3,
		Uploaded = 4,
etc
```

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345#-:-NsPEL_Y4j8q3WO4NSk6:b-8m973z)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
I added a unit test.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345#-:-NsPl5-60KcZeTGxL1-P:b-aoo4p1)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @andrew-polk)

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 3 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
