### PR TITLE
BL-12666 Remove outdated webpack rule

### PR DESCRIPTION
**Pull request by gmartin7**
* everything seems to work fine without this

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6094)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6094)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/webpack.common.js` line 185 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6094#-Ndr33813-ul65hUWcrT:-Ndr33813-ul65hUWcrU:bhxc1ez) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f848308cb2307bbb2aec2fb35410e466810c75f6/src/BloomBrowserUI/webpack.common.js#L185)):*
> ```JavaScript
>                     }
>                 ]
>             },
> ```

I admit ignorance in this area.
And I can't tell from here how much research you've done already.
But I think we need to do more than just remove this and see if it works on your machine and even our team's machines.

Somewhere (I think) we have a minimum wv2 version we support.
I'm thinking maybe we want to target that version?
But, again, I don't fully understand what this is doing.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6094)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/webpack.common.js` line 185 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6094#-Ndr33813-ul65hUWcrT:-Ne9GGVO29KJlEnhSOCM:b-flbmuf) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f848308cb2307bbb2aec2fb35410e466810c75f6/src/BloomBrowserUI/webpack.common.js#L185)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I admit ignorance in this area.
And I can't tell from here how much research you've done already.
But I think we need to do more than just remove this and see if it works on your machine and even our team's machines.

Somewhere (I think) we have a minimum wv2 version we support.
I'm thinking maybe we want to target that version?
But, again, I don't fully understand what this is doing.
</blockquote></details>

I changed the rule per the docs to target our minimum WebView2/Edge version of 112.0.0.0. It builds fine and seems to work at least on my machine that has Edge version 116!

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6094)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/webpack.common.js` line 169 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6094#-NeA8UTo6ZkGBjM1J0Me:-NeA8UTpA71AsfD89a9R:be1ell8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8fc334a53848656481f345afef98cf386ac0663d/src/BloomBrowserUI/webpack.common.js#L169)):*
> ```JavaScript
>                             presets: [
>                                 // Ensure that we target our minimum version of WebView2/Edge.
>                                 // (See Program.IsWebviewMissingOrTooOld)
> ```

Looks good. Thanks for adding the comment directing us to the C# code.
Let's add a comment there pointing here.
Then we can merge.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6094)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/webpack.common.js` line 169 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6094#-NeA8UTo6ZkGBjM1J0Me:-NeAI6uD4bE_y1uiATKr:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8fc334a53848656481f345afef98cf386ac0663d/src/BloomBrowserUI/webpack.common.js#L169)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks good. Thanks for adding the comment directing us to the C# code.
Let's add a comment there pointing here.
Then we can merge.
</blockquote></details>

Done.

**Pull request merged**
