### PR TITLE
BL-4276 When making an adaptation, take note of original copyright and license

### PR DESCRIPTION
**Pull request by hatton**
Also, mothballing the Cameroon pack as we don't have any evidence that it is being used and have failed to get replies to requests for feedback. The original requester has been notified of this.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1586)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/BloomBrowserUI/templates/customXMatter/MXBPamphlet-XMatter/MXBPamphlet-XMatter.pug, line 35 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1586#-Kfkx9zsZK4FbZhCYTdB:-Kfkx9zsZK4FbZhCYTdC:bpn8dfi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aaafb84ec8c26f07d1ddd15700c1ead8b29ba4dc/src/BloomBrowserUI/templates/customXMatter/MXBPamphlet-XMatter/MXBPamphlet-XMatter.pug#L35)):*
> block-old-licenseAndCopyright

Does this exist? I don't see it. If not, won't it create a transpile-time error?

---

*[src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug, line 49 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1586#-Kfktq12HFLMg_v31Be2:-Kfktq12HFLMg_v31Be3:b-351tny) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aaafb84ec8c26f07d1ddd15700c1ead8b29ba4dc/src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug#L49)):*
> How to upgrade the English without losing all the rest?

I assumed if the ID didn't change, it would still use the existing (outdated) L10Ns for the other languages. If not, it seems you could simply manually update the other languages' tmx files with the new English text.
Or maybe I am missing what you are saying.

---

*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 299 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1586#-Kfky0u0m5Zp45hdT9k1:-Kfky0u0m5Zp45hdT9k2:b-j56zrc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aaafb84ec8c26f07d1ddd15700c1ead8b29ba4dc/src/BloomExe/Book/BookCopyrightAndLicense.cs#L299)):*
> //todo l10n

Looks like this is still a TODO

---

*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 302 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1586#-KfkyBQWRoGEiRQE-sAM:-KfkyBQWRoGEiRQE-sAN:bstr6r7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aaafb84ec8c26f07d1ddd15700c1ead8b29ba4dc/src/BloomExe/Book/BookCopyrightAndLicense.cs#L302)):*
> else

contains the same code as the if.
So if is changed (not removed), it probably needs another unit test for this case, too.

---

*[src/BloomTests/Book/BookCopyrightAndLicenseTests.cs, line 469 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1586#-Kfl-Kn1qO2Gn12LOqpe:-Kfl-Kn1qO2Gn12LOqpf:boo4oeb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aaafb84ec8c26f07d1ddd15700c1ead8b29ba4dc/src/BloomTests/Book/BookCopyrightAndLicenseTests.cs#L469)):*
> HasCopyrightAndLicenseAndExtra

Doesn't seem to match the setup which only has license.

---

*[src/BloomTests/Book/BookCopyrightAndLicenseTests.cs, line 497 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1586#-KfkzsXksnjeX2Tf2v9S:-KfkzsXlPTeqzc-5Xwvs:b-txlmki) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aaafb84ec8c26f07d1ddd15700c1ead8b29ba4dc/src/BloomTests/Book/BookCopyrightAndLicenseTests.cs#L497)):*
> Custome

Custom

---

*[src/BloomTests/Book/BookCopyrightAndLicenseTests.cs, line 541 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1586#-KfkzTXx9ka1ijyltQz9:-KfkzTXyov-9VxaOTCUu:bv0ys4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aaafb84ec8c26f07d1ddd15700c1ead8b29ba4dc/src/BloomTests/Book/BookCopyrightAndLicenseTests.cs#L541)):*
> what should we say about the license?

I forget what we set for custom license. null? Then check for null? Or include the custom license text in the set and check for it. Otherwise, why have "AllRightsReserved" in the method name? But I see you already have that case in another test, so not sure what we are looking for here.

---

*[src/BloomTests/Book/BookStarterTests.cs, line 651 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1586#-Kfl-fHFsGPiFw1WbIWK:-Kfl-fHFsGPiFw1WbIWL:b1km7yv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aaafb84ec8c26f07d1ddd15700c1ead8b29ba4dc/src/BloomTests/Book/BookStarterTests.cs#L651)):*
> Assert.IsTrue(false, "todo");

Guaranteed failure. : )

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1586)*

**Comment by andrew-polk** [comment]
Not seeing why simply renaming the Cameroon files will cause them to disappear from the UI.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1586#-:-Kfl-q1E42XZMUl5FeUb:b-ok030u)*

**Comment by hatton** [comment]
See xMatterPackFinder:

     foreach (var directory in Directory.GetDirectories(path, "*-XMatter", SearchOption.AllDirectories))

---

Review status: 15 of 19 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/BloomBrowserUI/templates/customXMatter/MXBPamphlet-XMatter/MXBPamphlet-XMatter.pug, line 35 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1586#-Kfkx9zsZK4FbZhCYTdB:-KflpexOcc2DVF634ymR:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aaafb84ec8c26f07d1ddd15700c1ead8b29ba4dc/src/BloomBrowserUI/templates/customXMatter/MXBPamphlet-XMatter/MXBPamphlet-XMatter.pug#L35)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> block-old-licenseAndCopyright

Does this exist? I don't see it. If not, won't it create a transpile-time error?
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug, line 49 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1586#-Kfktq12HFLMg_v31Be2:-KflpxITeuL_tX91fa8i:bti8rob) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aaafb84ec8c26f07d1ddd15700c1ead8b29ba4dc/src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug#L49)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> How to upgrade the English without losing all the rest?

I assumed if the ID didn't change, it would still use the existing (outdated) L10Ns for the other languages. If not, it seems you could simply manually update the other languages' tmx files with the new English text.
Or maybe I am missing what you are saying.
</blockquote></details>

I dunno... I want to come back to this in the future.

---

*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 299 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1586#-Kfky0u0m5Zp45hdT9k1:-KfmvJuxope74OxETsKJ:bzhvao2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aaafb84ec8c26f07d1ddd15700c1ead8b29ba4dc/src/BloomExe/Book/BookCopyrightAndLicense.cs#L299)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> //todo l10n

Looks like this is still a TODO
</blockquote></details>

Yah... I can't see how to readily pull it off. I've gone ahead and made it localize to the UI language, which is wrong but at least shows how to construct the strings, and created BL-4456 for someone to work on this.

---

*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 302 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1586#-KfkyBQWRoGEiRQE-sAM:-Kfmvi2Ilgd3H4lKMsPk:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aaafb84ec8c26f07d1ddd15700c1ead8b29ba4dc/src/BloomExe/Book/BookCopyrightAndLicense.cs#L302)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> else

contains the same code as the if.
So if is changed (not removed), it probably needs another unit test for this case, too.
</blockquote></details>

Done.

---

*[src/BloomTests/Book/BookCopyrightAndLicenseTests.cs, line 469 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1586#-Kfl-Kn1qO2Gn12LOqpe:-KfmwKEaJT9WGgLN6xRM:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aaafb84ec8c26f07d1ddd15700c1ead8b29ba4dc/src/BloomTests/Book/BookCopyrightAndLicenseTests.cs#L469)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> HasCopyrightAndLicenseAndExtra

Doesn't seem to match the setup which only has license.
</blockquote></details>

Done.

---

*[src/BloomTests/Book/BookCopyrightAndLicenseTests.cs, line 497 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1586#-KfkzsXksnjeX2Tf2v9S:-KfmwPRl4TSTsJqxAc6_:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aaafb84ec8c26f07d1ddd15700c1ead8b29ba4dc/src/BloomTests/Book/BookCopyrightAndLicenseTests.cs#L497)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> Custome

Custom
</blockquote></details>

Done.

---

*[src/BloomTests/Book/BookCopyrightAndLicenseTests.cs, line 541 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1586#-KfkzTXx9ka1ijyltQz9:-KfqGTUmhpnBLylf1tg4:bs98dss) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aaafb84ec8c26f07d1ddd15700c1ead8b29ba4dc/src/BloomTests/Book/BookCopyrightAndLicenseTests.cs#L541)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> what should we say about the license?

I forget what we set for custom license. null? Then check for null? Or include the custom license text in the set and check for it. Otherwise, why have "AllRightsReserved" in the method name? But I see you already have that case in another test, so not sure what we are looking for here.
</blockquote></details>

Thanks for the prompting; I completely rewrite this section and related tests.

---

*[src/BloomTests/Book/BookStarterTests.cs, line 651 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1586#-Kfl-fHFsGPiFw1WbIWK:-KfqGyAUTtNDlg7V95T6:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aaafb84ec8c26f07d1ddd15700c1ead8b29ba4dc/src/BloomTests/Book/BookStarterTests.cs#L651)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> Assert.IsTrue(false, "todo");

Guaranteed failure. : )
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1586#-:-KfloUKYDzYRo6K_UuVh:bw3jhwb)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug, line 49 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1586#-Kfktq12HFLMg_v31Be2:-KfqIEUp-FEMTBqEALaF:b-248seu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/aaafb84ec8c26f07d1ddd15700c1ead8b29ba4dc/src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug#L49)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I dunno... I want to come back to this in the future.
</blockquote></details>

For what it is worth, I just changed the ID and English text for another issue. I modified all the tmx files. Testing showed that other languages still displayed the outdated translated text.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1586#-:-KfqJOlF6LSMzYWFKQ-f:bnfp4nl)*

**Pull request merged**
