### PR TITLE
BL-2968 Limit ctrl-mousewheel to zooming main page

### PR DESCRIPTION
**Pull request by JohnThomson**
This actually involves disabling the built-in zoom
and implementing our own, just for the main page iframe.
It's a bit flaky in Gecko29 but will work well when we
upgrade to 42 or so, based on experiments using
"Open page in Firefox".

[Review on Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/895)

### CODE REVIEW

**Comment by hatton** [comment]
Reviewed 7 of 9 files at r1, 3 of 8 files at r2.
Review status: 8 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/bloomEditing.js, line 617 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/895#-K5GtF9Dj7x7BjoEqnjf:-K5GtF9Dj7x7BjoEqnjg:-1161672067) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a859312b49edbb38d3bb2b64bdbccb1fe73438fe/src/BloomBrowserUI/bookEdit/js/bloomEditing.js#L617)):*
Would $('body').css('scale') work here? If so, it would be simpler.

---

*[src/BloomExe/Browser.cs, line 727 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/895#-K5GtjEdEMzjFB3gXnFS:-K5GtjEdEMzjFB3gXnFT:315902044) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/22baa19e7e7f32e661f6ab4a41e4c66d22dc959e/src/BloomExe/Browser.cs#L727)):*
To my surprise, we're not using this, but I don't think that was a *decision*. So could we just comment out this stuff in case we want to bring it back?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/895)*

**Comment by JohnThomson** [comment]
Review status: 8 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/BloomBrowserUI/bookEdit/js/bloomEditing.js, line 617 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/895#-K5GtF9Dj7x7BjoEqnjf:-K5gjAJGtccwcpxOwHLM:269915630) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a859312b49edbb38d3bb2b64bdbccb1fe73438fe/src/BloomBrowserUI/bookEdit/js/bloomEditing.js#L617)):*
Don't know. I'll try it.

---

*[src/BloomExe/Browser.cs, line 727 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/895#-K5GtjEdEMzjFB3gXnFS:-K5ggWB5JbJTAoyCyI_n:1220925255) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/22baa19e7e7f32e661f6ab4a41e4c66d22dc959e/src/BloomExe/Browser.cs#L727)):*
We could, but I'm reluctant. The current version will interact in probably undesirable ways with the ctrl-wheel zooming; at best, any window resize will throw away the ctl-wheel zoom and set the zoom to page width or 100%.  If we turn auto-zoom back on we'll have to decide what to do about that. Also work is needed to reconcile this code which uses moz- styles with my code which uses the regular CSS (and this code puts the origin stuff in style while mine puts fixed stuff like that in the CSS). So it would take extra work to repair this so it really works before commenting it out.

Would it be appropriate to just put in a comment (maybe in the new  zoom code) noting that we once had code to zoom to page width, and giving the git revision to look at if we want to recover it?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/895)*

**Comment by JohnThomson** [comment]
Review status: 8 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/BloomBrowserUI/bookEdit/js/bloomEditing.js, line 617 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/895#-K5GtF9Dj7x7BjoEqnjf:-K5gkAwzmLE0KELtgR4R:-1845086051) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a859312b49edbb38d3bb2b64bdbccb1fe73438fe/src/BloomBrowserUI/bookEdit/js/bloomEditing.js#L617)):*
Unfortunately not. $('body').attr('style') is undefined. $('body').attr('transform') yields matrix(2.13, 0, 0, 2.13, 0, 0), which I suppose is the net effect of the scale setting and the origin setting (scale is 2.13). It doesn't look much easier to extract the number from that than from the whole style attribute.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/895)*

**Comment by hatton** [comment]
Reviewed 5 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/895)*

**Comment by hatton** [comment]
Needs to merged in by hand.

**Pull request merged**
