### PR TITLE
BL-11492 color picker changes

### PR DESCRIPTION
**Pull request by gmartin7**
* new BloomSketchPicker combines react-color parts we need
* add custom pointers and integration with
   customColorPicker
* add custom slider to Hue and Alpha
* tweak sizes
* Hex input accepts only # (1st char only) and hex digits
* Hex input sends onChangeComplete() when full color entered
* integrate Hex input into CustomColorPicker
* use ColorSwatch to display color in picker
* add crosshair cursor to Saturation box

- - -
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393)

### CODE REVIEW

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
Only got partway, need to review more later.

> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-:-NC5ncWJ4Csyl8tGw5PT:b-p2qsgj)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @gmartin7 and @sujeffreyl)

___
*[`src/BloomBrowserUI/react_components/color-picking/bloomSketchPicker.tsx` line 8 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-NC5kGFZ1olO0xOlvFia:-NC5kFEq3_HmmSQ_sm6U:b-rv3u4m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d67d21a760375a84abb0760bd00902402fd89d1/src/BloomBrowserUI/react_components/color-picking/bloomSketchPicker.tsx#L8)):*
> ```XML
> import CustomSliderCursor from "./customCursors";
> 
> // This component combines 3 'react-color' components in the style that we want.
> ```

Is this comment more about the FunctionComponent than about the props?
___
*[`src/BloomBrowserUI/react_components/color-picking/bloomSketchPicker.tsx` line 9 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-NC5kU_-4A8IVLDhW2rO:-NC5kU_02fUoYN59DZYT:b-54wf55) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d67d21a760375a84abb0760bd00902402fd89d1/src/BloomBrowserUI/react_components/color-picking/bloomSketchPicker.tsx#L9)):*
> ```XML
> 
> // This component combines 3 'react-color' components in the style that we want.
> interface IBloomSketchPicker {
> ```

I think these interfaces should normally have a "Props" suffix to them



_Code quote:_
```XML
IBloomSketchPicker
```
___
*[`src/BloomBrowserUI/react_components/color-picking/bloomSketchPicker.tsx` line 41 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-NC5krmGASgF8WPm5m2D:-NC5krmGASgF8WPm5m2E:b6vmsgj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d67d21a760375a84abb0760bd00902402fd89d1/src/BloomBrowserUI/react_components/color-picking/bloomSketchPicker.tsx#L41)):*
> ```XML
>                 `}
>             >
>                 <Saturation {...props} onChange={handleColorChange} />
> ```

What about just passing props.onChange instead? (which... I think means that just the {...props} is sufficient, and you don't even need this onChange={[something]} here?
There are a few other references to handleColorChange, none of which I think are strictly needed.



_Code quote:_
```XML
handleColorChange
```
___
*[`src/BloomBrowserUI/react_components/color-picking/customColorPicker.tsx` line 135 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-NC5nBK24K5v35KRHDbG:-NC5nBK24K5v35KRHDbH:borkysx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d67d21a760375a84abb0760bd00902402fd89d1/src/BloomBrowserUI/react_components/color-picking/customColorPicker.tsx#L135)):*
> ```XML
>                     onChangeComplete={handleHexCodeChange}
>                 />
>                 {/* eslint-disable-next-line @typescript-eslint/no-empty-function */}
> ```

Makes me think.... seems to me like ColorSwatch (and any relevant sub-components) should allow for it not to be defined?) I mean, pretty sure for like a Material component like a Button, it won't blow up or complain if you don't pass an onClick or an onWhatever function

**Review by gmartin7 — COMMENTED** [review]
I applied your changes as well as eliminating the `.less` file and renaming the main component to ColorPicker.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-:-NC6Oj5E2pQKSzsMe3pv:bd886dx)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @sujeffreyl)

___
*[`src/BloomBrowserUI/react_components/color-picking/bloomSketchPicker.tsx` line 8 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-NC5kGFZ1olO0xOlvFia:-NC5wOG4AwhkWOF_MHD1:b-2nvupi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d67d21a760375a84abb0760bd00902402fd89d1/src/BloomBrowserUI/react_components/color-picking/bloomSketchPicker.tsx#L8)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Is this comment more about the FunctionComponent than about the props?
</blockquote></details>

Done. Yep, moved the comment.
___
*[`src/BloomBrowserUI/react_components/color-picking/bloomSketchPicker.tsx` line 9 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-NC5kU_-4A8IVLDhW2rO:-NC5wVjvAMthIkV5Mwby:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d67d21a760375a84abb0760bd00902402fd89d1/src/BloomBrowserUI/react_components/color-picking/bloomSketchPicker.tsx#L9)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I think these interfaces should normally have a "Props" suffix to them
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/react_components/color-picking/bloomSketchPicker.tsx` line 41 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-NC5krmGASgF8WPm5m2D:-NC64wHKCAt6__QjySQZ:btjylih) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d67d21a760375a84abb0760bd00902402fd89d1/src/BloomBrowserUI/react_components/color-picking/bloomSketchPicker.tsx#L41)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

What about just passing props.onChange instead? (which... I think means that just the {...props} is sufficient, and you don't even need this onChange={[something]} here?
There are a few other references to handleColorChange, none of which I think are strictly needed.
</blockquote></details>

Done. Good catch! Excellent simplification.
___
*[`src/BloomBrowserUI/react_components/color-picking/customColorPicker.tsx` line 135 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-NC5nBK24K5v35KRHDbG:-NC66XkMDQRvXWvLFxb9:bdg8r5y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d67d21a760375a84abb0760bd00902402fd89d1/src/BloomBrowserUI/react_components/color-picking/customColorPicker.tsx#L135)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Makes me think.... seems to me like ColorSwatch (and any relevant sub-components) should allow for it not to be defined?) I mean, pretty sure for like a Material component like a Button, it won't blow up or complain if you don't pass an onClick or an onWhatever function
</blockquote></details>

Done. Made ColorSwatch `onClick()` optional. Just had to add one `if` clause.

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @gmartin7 and @sujeffreyl)

___
*[`src/BloomBrowserUI/react_components/color-picking/hexColorInput.tsx` line 28 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-NC6iioH6vQoc2I5ChHe:-NC6iioH6vQoc2I5ChHf:b-vdmst6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f82ce5125032b86cefbf67134dcaff9ad3278ad2/src/BloomBrowserUI/react_components/color-picking/hexColorInput.tsx#L28)):*
> ```XML
>     };
> 
>     const massageColorInput = (color: string): string => {
> ```

1) I think prefixing with the hashChar can come at the end. (Not a big deal right now, but I think it'll simplify my other 2 suggestions..)  (Also a tiny bit less work for the regexes to do)
2) Then, I suggest color.replace("#"). You can just use a string to replace the first one now.  Or, maybe if (!color.startsWith("#")) makes more sense. (Actually, I think it does)
3) Is there a requirement that if the color contains invalid characters or too many characters, to just silently ignore them and do our best? I feel like this is a scenario where it's better to just fail fast and throw an exception and complain about things.

Actually, what does happen if the user pastes in or manually enters an invalid hex code?  Are we able to notify them about this and complain about the situation?

Anyhoo, if you followed suggestion 1 already, then at this point we can detect "#" in the hexadecimal section, which AFAIK is only valid if it's the first character.
___
*[`src/BloomBrowserUI/react_components/color-picking/hexColorInput.tsx` line 41 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-NC6kGbE0IaOieLlp98n:-NC6kGbF0tfYwWMSqJQ4:bhub21o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f82ce5125032b86cefbf67134dcaff9ad3278ad2/src/BloomBrowserUI/react_components/color-picking/hexColorInput.tsx#L41)):*
> ```XML
>     useEffect(() => {
>         setCurrentColor(massageColorInput(getHexColorValueFromColorInfo()));
>     }, [props.initial]);
> ```

I think props.initial.colors works as well, and it would be better because then it would re-run it less times.
___
*[`src/BloomBrowserUI/react_components/color-picking/hexColorInput.tsx` line 45 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-NC6kg4J585dJ0lhHSzZ:-NC6kg4J585dJ0lhHSz_:brf6l5u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f82ce5125032b86cefbf67134dcaff9ad3278ad2/src/BloomBrowserUI/react_components/color-picking/hexColorInput.tsx#L45)):*
> ```XML
>     const handleInputChange: React.ChangeEventHandler<HTMLInputElement> = e => {
>         const result = massageColorInput(e.target.value);
>         setCurrentColor(result);
> ```

Food for thought (I don't know the answer): Should this line execute if result.length == 2?
___
*[`src/BloomBrowserUI/react_components/color-picking/colorPicker.tsx` line 124 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-NC6mBXhEgfm5GmVwwjP:-NC6mBXi9EuBtves8H4a:b-ugg1o4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f82ce5125032b86cefbf67134dcaff9ad3278ad2/src/BloomBrowserUI/react_components/color-picking/colorPicker.tsx#L124)):*
> ```XML
>                     height: 32px;
>                     width: 100%;
>                     margin-top: 16px;
> ```

This might be too ambitious...
But during our CSS training discussion, JT brought up the point the guy made about how it's often beneficial to avoid margin on the exterior of re-usable components. I see margin being used in a few places here. Would it be feasible to re-work it without margin in those places?
(Or alternatively, is this going to be used in such a way where that's not too applicable?)

**Review by sujeffreyl — COMMENTED** [review]
Thanks for the update and fixes! I finished reviewing the rest of the files too now.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-:-NC6mfW28Wxr49DCz2aP:b-cwzsx1)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @gmartin7 and @sujeffreyl)

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @sujeffreyl)

___
*[`src/BloomBrowserUI/react_components/color-picking/hexColorInput.tsx` line 28 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-NC6iioH6vQoc2I5ChHe:-NC7KqjV4TOHMA_l-LjS:bv67r96) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f82ce5125032b86cefbf67134dcaff9ad3278ad2/src/BloomBrowserUI/react_components/color-picking/hexColorInput.tsx#L28)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

1) I think prefixing with the hashChar can come at the end. (Not a big deal right now, but I think it'll simplify my other 2 suggestions..)  (Also a tiny bit less work for the regexes to do)
2) Then, I suggest color.replace("#"). You can just use a string to replace the first one now.  Or, maybe if (!color.startsWith("#")) makes more sense. (Actually, I think it does)
3) Is there a requirement that if the color contains invalid characters or too many characters, to just silently ignore them and do our best? I feel like this is a scenario where it's better to just fail fast and throw an exception and complain about things.

Actually, what does happen if the user pastes in or manually enters an invalid hex code?  Are we able to notify them about this and complain about the situation?

Anyhoo, if you followed suggestion 1 already, then at this point we can detect "#" in the hexadecimal section, which AFAIK is only valid if it's the first character.
</blockquote></details>

We can discuss this some more if you'd like. I modified the method to:
* force uppercase
* eliminate all characters NOT valid hex digits (including extraneous hash marks)
* insert the `#` at the beginning
* strip off anything after the 7th character

I think it's better to handle inputs without error messages, if possible. We can talk about that...
I added some clarifying comments.
___
*[`src/BloomBrowserUI/react_components/color-picking/hexColorInput.tsx` line 41 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-NC6kGbE0IaOieLlp98n:-NC7Liso7HGoH6RzvymX:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f82ce5125032b86cefbf67134dcaff9ad3278ad2/src/BloomBrowserUI/react_components/color-picking/hexColorInput.tsx#L41)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I think props.initial.colors works as well, and it would be better because then it would re-run it less times.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/react_components/color-picking/hexColorInput.tsx` line 45 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-NC6kg4J585dJ0lhHSzZ:-NC7Lppo6zMAKHp4UznK:bh4z4q0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f82ce5125032b86cefbf67134dcaff9ad3278ad2/src/BloomBrowserUI/react_components/color-picking/hexColorInput.tsx#L45)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Food for thought (I don't know the answer): Should this line execute if result.length == 2?
</blockquote></details>

Yes, I think so. Among other things, characters entered as lowercase, show up as uppercase.
___
*[`src/BloomBrowserUI/react_components/color-picking/colorPicker.tsx` line 124 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-NC6mBXhEgfm5GmVwwjP:-NC6oForEWrchT2Qd2-p:b-37wyfb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f82ce5125032b86cefbf67134dcaff9ad3278ad2/src/BloomBrowserUI/react_components/color-picking/colorPicker.tsx#L124)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

This might be too ambitious...
But during our CSS training discussion, JT brought up the point the guy made about how it's often beneficial to avoid margin on the exterior of re-usable components. I see margin being used in a few places here. Would it be feasible to re-work it without margin in those places?
(Or alternatively, is this going to be used in such a way where that's not too applicable?)
</blockquote></details>

Normally would be a good point, but this is always inside of ColorPickerDialog or stories.

**Review by sujeffreyl — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[`src/BloomBrowserUI/react_components/color-picking/hexColorInput.tsx` line 28 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-NC6iioH6vQoc2I5ChHe:-NCQEUif6y5ZTfz0zvWr:b-exb72m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f82ce5125032b86cefbf67134dcaff9ad3278ad2/src/BloomBrowserUI/react_components/color-picking/hexColorInput.tsx#L28)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

We can discuss this some more if you'd like. I modified the method to:
* force uppercase
* eliminate all characters NOT valid hex digits (including extraneous hash marks)
* insert the `#` at the beginning
* strip off anything after the 7th character

I think it's better to handle inputs without error messages, if possible. We can talk about that...
I added some clarifying comments.
</blockquote></details>

Ok, this seems reasonable, thanks!
___
*[`src/BloomBrowserUI/react_components/color-picking/colorPicker.tsx` line 124 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-NC6mBXhEgfm5GmVwwjP:-NCQDi7Y75TlENVKahyf:begf2i1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f82ce5125032b86cefbf67134dcaff9ad3278ad2/src/BloomBrowserUI/react_components/color-picking/colorPicker.tsx#L124)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Normally would be a good point, but this is always inside of ColorPickerDialog or stories.
</blockquote></details>

Ok, great!

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[`src/BloomBrowserUI/react_components/color-picking/hexColorInput.tsx` line 45 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-NC6kg4J585dJ0lhHSzZ:-NC__ep-6ciE_WsWdK8z:b4ddqnm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f82ce5125032b86cefbf67134dcaff9ad3278ad2/src/BloomBrowserUI/react_components/color-picking/hexColorInput.tsx#L45)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Yes, I think so. Among other things, characters entered as lowercase, show up as uppercase.
</blockquote></details>

If the user enters lowercase letters, this code (`massageColorInput()`) validates them and makes them appear as uppercase, but we aren't ready to trigger a change in color outside of the hex input until we get to 7 characters (hash + 6 hex digits).

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[`src/BloomBrowserUI/react_components/color-picking/hexColorInput.tsx` line 45 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-NC6kg4J585dJ0lhHSzZ:-NC_aS00CA5sUXrT6aZe:b-nar892) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f82ce5125032b86cefbf67134dcaff9ad3278ad2/src/BloomBrowserUI/react_components/color-picking/hexColorInput.tsx#L45)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

If the user enters lowercase letters, this code (`massageColorInput()`) validates them and makes them appear as uppercase, but we aren't ready to trigger a change in color outside of the hex input until we get to 7 characters (hash + 6 hex digits).
</blockquote></details>

Am I making sense? We need to store the massaged color via`setCurrentColor()` so the hex input control shows the updated value.

**Review by sujeffreyl — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-:-NCa4ts4EgGCnjvT0MKr:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @sujeffreyl)

___
*[`src/BloomBrowserUI/react_components/color-picking/hexColorInput.tsx` line 45 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393#-NC6kg4J585dJ0lhHSzZ:-NCa4lY1-iNYG6yo9_xs:b-ntc1l5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f82ce5125032b86cefbf67134dcaff9ad3278ad2/src/BloomBrowserUI/react_components/color-picking/hexColorInput.tsx#L45)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Am I making sense? We need to store the massaged color via`setCurrentColor()` so the hex input control shows the updated value.
</blockquote></details>

Ok i see. thanks for explaining!

**Review by sujeffreyl — APPROVED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5393)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
