### PR TITLE
Handle errors in sound recording better (BL-5833)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This may not directly address the issue, but does improve error
handling when something bad happens during recording.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2325)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[src/BloomExe/Edit/AudioRecording.cs, line 233 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2325#-L9HHvTe0df8OZmKh3Vm:-L9HHvTe0df8OZmKh3Vn:b-arqteu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/037179309a3ccffaa285dc074e94fa9786a4bc0d/src/BloomExe/Edit/AudioRecording.cs#L233)):*
> ```Smalltalk
> 			_recorder.Dispose();
> 			_recorder = new AudioRecorder(1);
> 			_recorder.PeakLevelChanged += ((s, e) => SetPeakLevel(e));
> ```

here forwards sure seems like it must be a repeat of some initialization code. Can we have the code appear just once?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2325)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Edit/AudioRecording.cs, line 233 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2325#-L9HHvTe0df8OZmKh3Vm:-L9HU0Ur8Ff6CayJHFwA:b-o6mc4z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/037179309a3ccffaa285dc074e94fa9786a4bc0d/src/BloomExe/Edit/AudioRecording.cs#L233)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

here forwards sure seems like it must be a repeat of some initialization code. Can we have the code appear just once?
</blockquote></details>

Okay, I refactored the code in a couple of ways to share initialization code, and improved the use of the ApplicationExit handler to not keep the object alive unnecessarily.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2325)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Edit/AudioRecording.cs, line 222 at r2](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2325#-L9jh2wI-XwjoxthWhnm:-L9zoJwK2P5yGinFly8o:bklkn12) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dfe347081ae2474693ad5122354858a834d5ebf0/src/BloomExe/Edit/AudioRecording.cs#L222)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

As you know, Application.DoEvents() is [always suspicious](https://stackoverflow.com/questions/5181777/use-of-application-doevents). So this would need a comment justifying it.
</blockquote></details>

This may have been a leftover of some code that got deleted when I decided it was overkill.  By itself, it certainly doesn't seem to be serving a purpose.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2325)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Edit/AudioRecording.cs, line 222 at r2](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2325#-L9jh2wI-XwjoxthWhnm:-L9zog_E4fu2B65A2eAo:b5gwx7n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dfe347081ae2474693ad5122354858a834d5ebf0/src/BloomExe/Edit/AudioRecording.cs#L222)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

This may have been a leftover of some code that got deleted when I decided it was overkill.  By itself, it certainly doesn't seem to be serving a purpose.
</blockquote></details>

(I deleted it.)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2325)*

**Pull request merged**
