### PR TITLE
BL-10270 Fix notification of book status change

### PR DESCRIPTION
**Pull request by gmartin7**
* fix Edit button active on TC conflict
* major refactor of collection preview edit/make button
* pulled selectedBookStatus hook up to collection tab
* added key to simpleMenu rows
* remove unused usings
* fire selection changed event on noticing remote change

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4663)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4663)* status: all files reviewed, 5 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomBrowserUI/app/selectedBook.ts, line 27 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4663#-MhP4K-V6p5IiBO5f6HP:-MhP4K-V6p5IiBO5f6HQ:bwk2djy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d02dae5aab823ac31183f5cb01db2a23e7cd633f/src/BloomBrowserUI/app/selectedBook.ts#L27)):*
> ```XML
>     // BookSelection.InvokeSelectionChanged(), via TeamCollectionApi.UpdateUiForBook().
>     // As a result, the top-level (WorkspaceView) handler for changing selection fires the websocket
>     // event referenced here.
> ```

There's a comment in UpdateUiForBook indicating that we don't want to do things this way.
I don't really understand it, but I'm suspicious the simplifications in this PR might be moving us away from that.

But I admit confusion...
___
*[src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx, line 30 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4663#-MhP8KCZ6rZFFxlxZhdV:-MhP8KCZ6rZFFxlxZhdW:byvojjp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d02dae5aab823ac31183f5cb01db2a23e7cd633f/src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx#L30)):*
> ```XML
>     newLocalBook: false,
>     error: ""
> };
> ```

I think it might make more sense to define this and IBookTeamCollectionStatus in the same file.
___
*[src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx, line 230 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4663#-MhP8Yk_30Z4869U2U7C:-MhP8Yk_30Z4869U2U7D:bvmlqzw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d02dae5aab823ac31183f5cb01db2a23e7cd633f/src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx#L230)):*
> ```XML
>             isTeamCollection && !canMakeBook ? (
>                 <div id="teamCollection">
>                     <TeamCollectionBookStatusPanel {...bookStatus} />
> ```

I'm not understanding the benefit of moving bookStatus up and passing it down.
I expected it was going to be because the button needed it, but I'm not seeing that.
___
*[src/BloomExe/CollectionTab/LibraryBookView.cs, line 156 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4663#-MhP13b11SUzKG4Pqt8-:-MhP13b11SUzKG4Pqt80:b-6xwup5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d02dae5aab823ac31183f5cb01db2a23e7cd633f/src/BloomExe/CollectionTab/LibraryBookView.cs#L156)):*
> ```Smalltalk
> 					_reactBookPreviewControl.Props = new { initialBookPreviewUrl = fakeTempFile.Key }; // need this for initial selection
> 					// Another 'bookStatus' event called 'changeBook' was sent here too, but it was never being used and now the
> 					// component that it was intended for uses the 'reload' event.
> ```

A year from now, I think this comment will be more confusing than helpful.
So unless I'm missing something, probably better off removing it.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1010 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4663#-MhP38x7B79Pojd8MzlR:-MhP38x7B79Pojd8MzlS:byi7wbe) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d02dae5aab823ac31183f5cb01db2a23e7cd633f/src/BloomExe/TeamCollection/TeamCollection.cs#L1010)):*
> ```Smalltalk
> 					HandleModifiedFile(changeArgs);
> 				else HandleCollectionSettingsChange(args);
> 				_tcManager.BookSelection?.InvokeSelectionChanged(false);
> ```

It is not clear to me why we need to call this here. At a minimum, I think we need a comment.

But see comment elsewhere about strategy.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4663)* status: 10 of 14 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/app/selectedBook.ts, line 27 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4663#-MhP4K-V6p5IiBO5f6HP:-MhUUdkYDBEqI7k9MJzl:bs31u2b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d02dae5aab823ac31183f5cb01db2a23e7cd633f/src/BloomBrowserUI/app/selectedBook.ts#L27)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

There's a comment in UpdateUiForBook indicating that we don't want to do things this way.
I don't really understand it, but I'm suspicious the simplifications in this PR might be moving us away from that.

But I admit confusion...
</blockquote></details>

My understanding from JT's input is that it's necessary to send a websocket message to update the javascript side of things. There is a regular C# event for the C# side of things. It would be nice if we only needed one of them. The C# event also has log file messages attached, I believe.
___
*[src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx, line 30 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4663#-MhP8KCZ6rZFFxlxZhdV:-MhUV6HM6D4eMMfLaRtk:b-81ws05) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d02dae5aab823ac31183f5cb01db2a23e7cd633f/src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx#L30)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think it might make more sense to define this and IBookTeamCollectionStatus in the same file.
</blockquote></details>

Yes, I'll be moving all this back to the status panel.
___
*[src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx, line 230 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4663#-MhP8Yk_30Z4869U2U7C:-MhPvah2BnOhmC9pw0Wi:bj61s21) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d02dae5aab823ac31183f5cb01db2a23e7cd633f/src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx#L230)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not understanding the benefit of moving bookStatus up and passing it down.
I expected it was going to be because the button needed it, but I'm not seeing that.
</blockquote></details>

Grr... You are right. The thing that actually fixed the problem was the `_tcManager.BookSelection?.InvokeSelectionChanged(false);` down below that bothered your sensibilities. :)
Moving the book status api call back down to the status panel file.
___
*[src/BloomExe/CollectionTab/LibraryBookView.cs, line 156 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4663#-MhP13b11SUzKG4Pqt8-:-MhUNOTV8HhKPkEBcw4S:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d02dae5aab823ac31183f5cb01db2a23e7cd633f/src/BloomExe/CollectionTab/LibraryBookView.cs#L156)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

A year from now, I think this comment will be more confusing than helpful.
So unless I'm missing something, probably better off removing it.
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1010 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4663#-MhP38x7B79Pojd8MzlR:-MhUQ5075kDwVFWl1R_V:bk3328l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d02dae5aab823ac31183f5cb01db2a23e7cd633f/src/BloomExe/TeamCollection/TeamCollection.cs#L1010)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

It is not clear to me why we need to call this here. At a minimum, I think we need a comment.

But see comment elsewhere about strategy.
</blockquote></details>

I thought about moving it to `UpdateBookStatus()`, which all of these `HandleX` methods call. But I realized that `UpdateBookStatus()` gets called a couple other places which don't have anything to do with remote repo updates.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4663)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @gmartin7)

___
*[src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, line 74 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4663#-MhVksuc1hjXq9fkuVC4:-MhVksuc1hjXq9fkuVC5:b-oea7vg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce6eed6340022fa6fb762974bd40aced1f4ad79f/src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx#L74)):*
> ```XML
>     selectedBookId: string | undefined;
>     editable: boolean;
>     reload: number;
> ```

Definitely open to discussion, 
but I'm not excited about passing down these props, particularly the reload one.

If I understand, to prevent this, our options are:
- Subscribe to reload event and use useMonitorBookSelection ourselves (in addition to the parent component).
- Pass the bookStatus from the parent component.

While I would be sad for you to move the code back up again... I would lean toward the latter. And maybe it was always the right thing to do for the parent to determine what the bookStatus is and simply give that to the child which then renders the UI for it.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4663)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, line 74 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4663#-MhVksuc1hjXq9fkuVC4:-MhZSffWALxBee6t7NoO:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ce6eed6340022fa6fb762974bd40aced1f4ad79f/src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx#L74)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Definitely open to discussion, 
but I'm not excited about passing down these props, particularly the reload one.

If I understand, to prevent this, our options are:
- Subscribe to reload event and use useMonitorBookSelection ourselves (in addition to the parent component).
- Pass the bookStatus from the parent component.

While I would be sad for you to move the code back up again... I would lean toward the latter. And maybe it was always the right thing to do for the parent to determine what the bookStatus is and simply give that to the child which then renders the UI for it.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4663)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
