### PR TITLE
Stop using microphone when talking book tool is not active (BL-12260)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5894)

### CODE REVIEW

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5894)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/Edit/AudioRecording.cs` line 332 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5894#-NWnhItUEuXuFleMqqUR:-NWnhItUEuXuFleMqqUS:b4fqm4v) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/81ab6a7fbe8b43c96573c3826b2699384de1aa79/src/BloomExe/Edit/AudioRecording.cs#L332)):*
> ```Smalltalk
> 		}
> 
> 		public void ResumeRecorder()
> ```

when you see this used in "shell", you think "huh? why are we recording?". How about `ResumeListening` with `PauseListening` or `ResumeMonitoringAudio`. Whichever you choose, I think `_monitoringAudio` can be made parallel (e.g. `_listening` or `_monitoringAudio`).

**Review by hatton — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5894)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5894)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/BloomExe/Edit/AudioRecording.cs` line 332 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5894#-NWnhItUEuXuFleMqqUR:-NWnkCJ9CObZRQM4U4Ww:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/81ab6a7fbe8b43c96573c3826b2699384de1aa79/src/BloomExe/Edit/AudioRecording.cs#L332)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

when you see this used in "shell", you think "huh? why are we recording?". How about `ResumeListening` with `PauseListening` or `ResumeMonitoringAudio`. Whichever you choose, I think `_monitoringAudio` can be made parallel (e.g. `_listening` or `_monitoringAudio`).
</blockquote></details>

Done.

**Review by hatton — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5894)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
