### PR TITLE
BL-2444: crashing with a GDI+ exception on some books with odd but va…

### PR DESCRIPTION
**Pull request by phillip-hopper**
Crashing with a GDI+ exception on some books with odd but valid titles.

### CODE REVIEW

**Comment by hatton** [comment]
Phil, looking at the PR, the youtrack issue, and the code, I still can't tell what the connection is between the code and symptom. Can you add that in one of those places? Thx.

**Comment by phillip-hopper** [comment]
More comments have been added to the code.

**Comment by StephenMcConnel** [comment]
Did you add comments in the code in response to John's comment above?  The connection seems clear to me, and the solution looks reasonable.

**Comment by phillip-hopper** [comment]
@StephenMcConnel Yes, I added comments

**Comment by StephenMcConnel** [comment]
looks okay to me.  :+1: :-)

**Pull request merged**
