### PR TITLE
Add BookCompressor (BL-4647)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1677)

### CODE REVIEW

**Comment by JohnThomson** [comment]
From things JohnH said, I gather this is aimed at putting the compacted book into BloomReader?

If so, I think there are things we would want to omit from the folder...probably similar to the ones we omit when making a BloomPack.

For example, I don't think the reader will use the PDF version of the book, which is often quite large.

It may also be desirable to filter any audio that is not actually used in the book...depending on what the reader will allow in the way of switching language, you could possibly also filter audio that isn't used by the current vernacular language. Also, the reader probably only wants the MP3, not the raw audio it is based on. (This potentially gets you into making sure all the audio you DO want has been compressed, unfortunately. May be able to reuse some code from epub maker.)

(Since this will be our own reader, we also have the option of using ogg instead of mp3...would we want to do that??)

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1677#-:-KkM9pkbRTx4pbovToi5:b-b5hduo)*

**Comment by StephenMcConnel** [comment]
A couple of minor questions, but otherwise looks okay.  The filtering already gets rid of the .wav files as JohnT requests (possibly in response to his review).  For this initial work, that may be good enough.

---

Reviewed 9 of 10 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/BookCompressor.cs, line 99 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1677#-KlzIgCpC7lIzXTJ_s7V:-KlzIgCpC7lIzXTJ_s7W:b-59p99z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/acaa9cd5686ea2ae54a0c68ad58dd9d12684f4b3/src/BloomExe/Book/BookCompressor.cs#L99)):*
> ```Smalltalk
> 				{
> 					DateTime = fi.LastWriteTime,
> 					IsUnicodeText = true
> ```

Do we know this is a text file? what happens if we mark an image or sound file IsUnicodeText=true?

---

*[src/BloomExe/CollectionTab/LibraryModel.cs, line 285 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1677#-KlzK-aBxYNqn_-7soSp:-KlzK-aBxYNqn_-7soSq:bcx1pnb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/acaa9cd5686ea2ae54a0c68ad58dd9d12684f4b3/src/BloomExe/CollectionTab/LibraryModel.cs#L285)):*
> ```Smalltalk
> 
> 						Logger.WriteEvent("BloomPack path will be " + path + ", made from " + dir + " with rootName " + Path.GetFileName(dir));
> 						var excludeAudio = true; // don't want audio in bloompack. todo: test
> ```

was the todo: test for verifying whether audio is really unwanted, or for verifying that it is successfully excluded?  your code rearrangement suggests the former.  if that's the case, "verify" might be a better single word for the todo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1677#-:-KlzN9jpLpuTM-OTzLJ3:bb1e2hc)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/BookCompressor.cs, line 99 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1677#-KlzIgCpC7lIzXTJ_s7V:-Km1Xb76aW-CUXALn6bM:b-9p4ydj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/acaa9cd5686ea2ae54a0c68ad58dd9d12684f4b3/src/BloomExe/Book/BookCompressor.cs#L99)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Do we know this is a text file? what happens if we mark an image or sound file IsUnicodeText=true?
</blockquote></details>

This part of the code was copied directly from LibraryModel, but, if I interpret the source from SharpZipLib correctly, it only has to do with the name and comment on the file, not the content of the file.

---

*[src/BloomExe/CollectionTab/LibraryModel.cs, line 285 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1677#-KlzK-aBxYNqn_-7soSp:-Km1WCAtUnEMJ-wCPPqd:bcrrnpk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/acaa9cd5686ea2ae54a0c68ad58dd9d12684f4b3/src/BloomExe/CollectionTab/LibraryModel.cs#L285)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

was the todo: test for verifying whether audio is really unwanted, or for verifying that it is successfully excluded?  your code rearrangement suggests the former.  if that's the case, "verify" might be a better single word for the todo.
</blockquote></details>

That comment was actually kept from the original code which returned unconditionally if we were processing the audio directory. I'll remove the todo as I assume that whatever wanted testing has been vetted at this point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1677)*

**Comment by andrew-polk** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/CollectionTab/LibraryModel.cs, line 285 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1677#-KlzK-aBxYNqn_-7soSp:-Km1YopUhRBOvF8Hu_CY:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/acaa9cd5686ea2ae54a0c68ad58dd9d12684f4b3/src/BloomExe/CollectionTab/LibraryModel.cs#L285)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

That comment was actually kept from the original code which returned unconditionally if we were processing the audio directory. I'll remove the todo as I assume that whatever wanted testing has been vetted at this point.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1677)*

**Comment by StephenMcConnel** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1677#-:-Km26oFJC2jMn4eqaI_9:bnfp4nl)*

**Pull request merged**
