### PR TITLE
Fix BL-6090 Duplicate book should have unique guid

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2470)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/BookStorage.cs, line 1442 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2470#-LEVBt9m-JLg9eItWqqN:-LEVBt9m-JLg9eItWqqO:bos30z4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c9399bd13202f992f8169388c10413965c43d7c3/src/BloomExe/Book/BookStorage.cs#L1442)):*
> ```Smalltalk
> 			// If the meta.json file is missing, ok that's weird but that means we
> 			// don't have a duplicate bookInstanceId to worry about.
> 			if (File.Exists(metaPath))
> ```

Today functionality is the same, but this should be RobustFile.Exists

---

*[src/BloomExe/Book/BookStorage.cs, line 1446 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2470#-LEVBc9I-7ywUA-Lh2RI:-LEVBc9I-7ywUA-Lh2RJ:bemqhfz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c9399bd13202f992f8169388c10413965c43d7c3/src/BloomExe/Book/BookStorage.cs#L1446)):*
> ```Smalltalk
> 				var meta = DynamicJson.Parse(File.ReadAllText(metaPath));
> 				meta.bookInstanceId = Guid.NewGuid().ToString();
> 				File.WriteAllText(metaPath, JsonConvert.SerializeObject(meta));
> ```

This should at least be RobustFile.Write...
Is that sufficient? Elsewhere we have even more robust code for writing meta.json which makes a backup first.

---

*[src/BloomExe/Book/BookStorage.cs, line 1457 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2470#-LEVC9Rr2Nnnzoqkbgbx:-LEVC9Rr2Nnnzoqkbgby:b-pwvw20) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c9399bd13202f992f8169388c10413965c43d7c3/src/BloomExe/Book/BookStorage.cs#L1457)):*
> ```
> avaialble
> ```

typo

---

*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1344 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2470#-LEVCVFW0fOqwCyMNXTG:-LEVCVFW0fOqwCyMNXTH:b5fobcd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c9399bd13202f992f8169388c10413965c43d7c3/src/BloomExe/CollectionTab/LibraryListView.cs#L1344)):*
> ```Smalltalk
> 		/// <param name="copyNum"></param>
> 		/// <returns></returns>
> 		private static string GetAvailableDirectory(string collectionDir, string baseName, int copyNum)
> ```

I think you meant to move this method rather than duplicate it?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2470)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/BloomExe/Book/BookStorage.cs, line 1442 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2470#-LEVBt9m-JLg9eItWqqN:-LEVG4nD2IWoPIYqTwnt:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c9399bd13202f992f8169388c10413965c43d7c3/src/BloomExe/Book/BookStorage.cs#L1442)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Today functionality is the same, but this should be RobustFile.Exists
</blockquote></details>

Done.

---

*[src/BloomExe/Book/BookStorage.cs, line 1446 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2470#-LEVBSlwABqq3ERKLLVo:-LEVE9L00KThdTZJBCAG:b9kmcge) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c9399bd13202f992f8169388c10413965c43d7c3/src/BloomExe/Book/BookStorage.cs#L1446)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

So is the .BloomBookOrder file rebuilt from the meta.json file each time the book is uploaded? What about the meta.downloadSource field (which also contains the Guid).
Both files contain the guid twice. :(
</blockquote></details>

Good questions....

Semantically,  meta.downloadSource should not change, seems to me. 

As far as I can tell, .BloomBookOrder  is not relevant to a book sitting on your disk. And sure, it has to be recreated when you do an upload... it's just a copy of meta.json.

The download code could very reasonably remove this file... it's not  relevant once we have the book book sitting on your disk. 

---

*[src/BloomExe/Book/BookStorage.cs, line 1446 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2470#-LEVBc9I-7ywUA-Lh2RI:-LEVFM_pDA-nYnx569Ao:b-lrzuc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c9399bd13202f992f8169388c10413965c43d7c3/src/BloomExe/Book/BookStorage.cs#L1446)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This should at least be RobustFile.Write...
Is that sufficient? Elsewhere we have even more robust code for writing meta.json which makes a backup first.
</blockquote></details>

Changed to Robust.

That's sufficient.

---

*[src/BloomExe/Book/BookStorage.cs, line 1457 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2470#-LEVC9Rr2Nnnzoqkbgbx:-LEVFvDy8oh3y3FF75DW:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c9399bd13202f992f8169388c10413965c43d7c3/src/BloomExe/Book/BookStorage.cs#L1457)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> avaialble
> ```

typo
</blockquote></details>

Done.

---

*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1344 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2470#-LEVCVFW0fOqwCyMNXTG:-LEVGdqlBWBjschA2yZw:b-8q4yt6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c9399bd13202f992f8169388c10413965c43d7c3/src/BloomExe/CollectionTab/LibraryListView.cs#L1344)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think you meant to move this method rather than duplicate it?
</blockquote></details>

Thanks. Originally moved, but was accidentally working on master branch, lost the "move" when I re-did it on 4.2.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2470)*

**Comment by gmartin7** [comment]
Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2470)*

**Comment by gmartin7** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2470#-:-LEVI5Ov9p4z2WxqDUUz:bnfp4nl)*

**Comment by gmartin7** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2470)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2470)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2470#-:-LEVJDRFAMDFajmzjIkl:bnfp4nl)*

**Pull request merged**
