### PR TITLE
Remove transparency from all incoming images (BL-3646)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1156)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 62 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1156#-KOrQ1Uppk8-LtpOeJrg:-KOrQ1Uppk8-LtpOeJrh:b-4zxbv0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/574d9a64eeed3327e8534965bf8c8e5ae3128e5d/src/BloomExe/ImageProcessing/ImageUtils.cs#L62)):*
> ```Smalltalk
> 				isEncodedAsJpeg = AppearsToBeJpeg(imageInfo);
> 				if (!isEncodedAsJpeg)
> 					imageInfo.Image = RemoveTransparency(imageInfo.Image);
> ```

This removes transparency from all images, not (as indicated in overall description of issue) only those being converted to jpeg.

Also, you are modifying a method argument (the imageInfo), which the old method did not do, I believe. If caller has other references to the old image there will be trouble. Hopefully you have checked this, but I wonder whether its desirable/necessary to modify the imageInfo and dispose the old image. At least, the method comment should warn of it.

---

*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 216 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1156#-KOrPB0ZXEFPhLD2pQjM:-KOrPB0ZXEFPhLD2pQjN:bg8wnb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/574d9a64eeed3327e8534965bf8c8e5ae3128e5d/src/BloomExe/ImageProcessing/ImageUtils.cs#L216)):*
> ```Smalltalk
> 		}
> 
> 		private static Image RemoveTransparency(Image image)
> ```

There should (at least!) be a warning here that the original image will be disposed and (presumably) the caller becomes responsible to dispose of the new image.

I wonder whether a better API would be to make the image argument a ref, thus more clearly conveying the idea that the intent is to replace the old image with the new one?

Even then the warning is needed; the caller might have other references to the old image.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1156)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 216 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1156#-KOrPB0ZXEFPhLD2pQjM:-KPJ_e7NNMj-PPFTlTQN:bnqspzi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/574d9a64eeed3327e8534965bf8c8e5ae3128e5d/src/BloomExe/ImageProcessing/ImageUtils.cs#L216)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary>
> There should (at least!) be a warning here that the original image will be disposed and (presumably) the caller becomes responsible to dispose of the new image.
> 
> I wonder whether a better API would be to make the image argument a ref, thus more clearly conveying the idea that the intent is to replace the old image with the new one?
> 
> Even then the warning is needed; the caller might have other references to the old image.
</details>
I was very unsure about the best way to do this. As far as I can tell, there is no way to modify the image in place, so we must create a new image.

I originally had coded it as a ref but felt that it was better to return (I think because it actually is a new image).

What if I just don't dispose of the original and change the method name to CreateImageWithoutTransparentBackground?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1156)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 216 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1156#-KOrPB0ZXEFPhLD2pQjM:-KPNd0XARxS7AHbTBML0:befu92o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/574d9a64eeed3327e8534965bf8c8e5ae3128e5d/src/BloomExe/ImageProcessing/ImageUtils.cs#L216)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> I was very unsure about the best way to do this. As far as I can tell, there is no way to modify the image in place, so we must create a new image.
> 
> I originally had coded it as a ref but felt that it was better to return (I think because it actually is a new image).
> 
> What if I just don't dispose of the original and change the method name to CreateImageWithoutTransparentBackground?
</details>
That would be satisfactory for this method but pushes the problem up to the caller. It's important that eventually we DO dispose of images we're no longer using or we are likely to make our memory problems worse. To ensure that we need to make it clear wherever we have a reference to an image what is responsible to dispose it. Ideally each image either is only referenced on the stack (and disposed when the last ref goes out of scope), or has just one reference in an object, and is disposed when that object is (if not before). In this case we DO apparently want to replace the old image in the imageInfo; but you need to trace back where those imageInfo objects come from and make sure nothing uses the disposed images and that both the new and old ones are properly disposed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1156)*

**Comment by andrew-polk** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 62 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1156#-KOrQ1Uppk8-LtpOeJrg:-KPO2XagAXULRw6d_Jhb:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/574d9a64eeed3327e8534965bf8c8e5ae3128e5d/src/BloomExe/ImageProcessing/ImageUtils.cs#L62)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary>
> This removes transparency from all images, not (as indicated in overall description of issue) only those being converted to jpeg.
> 
> Also, you are modifying a method argument (the imageInfo), which the old method did not do, I believe. If caller has other references to the old image there will be trouble. Hopefully you have checked this, but I wonder whether its desirable/necessary to modify the imageInfo and dispose the old image. At least, the method comment should warn of it.
</details>
Done.

---

*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 216 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1156#-KOrPB0ZXEFPhLD2pQjM:-KPO2ZOzoowwykuAG9mS:b-f1kyme) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/574d9a64eeed3327e8534965bf8c8e5ae3128e5d/src/BloomExe/ImageProcessing/ImageUtils.cs#L216)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary>
> That would be satisfactory for this method but pushes the problem up to the caller. It's important that eventually we DO dispose of images we're no longer using or we are likely to make our memory problems worse. To ensure that we need to make it clear wherever we have a reference to an image what is responsible to dispose it. Ideally each image either is only referenced on the stack (and disposed when the last ref goes out of scope), or has just one reference in an object, and is disposed when that object is (if not before). In this case we DO apparently want to replace the old image in the imageInfo; but you need to trace back where those imageInfo objects come from and make sure nothing uses the disposed images and that both the new and old ones are properly disposed.
</details>
Done.
It turns out that setting imageInfo.Image actually disposes of the original. I check all callers, and there are no instances where a reference is made before calling this method. Hopefully the comments are now sufficient.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1156)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1156#-:-KPPlgXvmd6Y5434fDl3:bnfp4nl)*

**Pull request merged**
