### PR TITLE
Fix language visibility yet another way (BL-13099)

### PR DESCRIPTION
**Pull request by JohnThomson**
Also fixes BL-13045 and possibly others.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6335)

### CODE REVIEW

**Review by StephenMcConnel — CHANGES_REQUESTED** [review]
Looks good apart from quibbles about code style that can probably be ignored if you disagree with them.

> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6335#-:-Ns9h3hVDr7XgmAsax-T:bgv7jdd)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/AppearanceSettings.cs` line 595 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6335#-Ns9c62M-GqkdEH1khgD:-Ns9c62M-GqkdEH1khgE:boi6m6m) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4d56165957ef27b5c75f4992cea1e8bb71f0a37e/src/BloomExe/Book/AppearanceSettings.cs#L595)):*
> ```Smalltalk
>         //    return false;
>         //}
>         //value = (bool)val.Value;
> ```

Should this commented out code be deleted?  or is it a meaningful alternative that we might yet need?  (maybe it's paired with the commented out code in the UpdateFromDynamic method?)
___
*[`src/BloomExe/Book/TranslationGroupManager.cs` line 345 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6335#-Ns9d7NABsCWWcVdtCFK:-Ns9d7NABsCWWcVdtCFL:b3b6wus) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4d56165957ef27b5c75f4992cea1e8bb71f0a37e/src/BloomExe/Book/TranslationGroupManager.cs#L345)):*
> ```Smalltalk
> 
>         private static void UpdateContentLanguageClassesOnElement(
>             XmlElement e,
> ```

Probably not worth changing on its own, but surely a better variable name than 'e' could be found.  Even 'xe' or 'elem' would be better in my opinion.  'e' is used too often for an Event or Exception object in handler code.  But that may be more of an issue in code reviews where you don't see the whole context.
___
*[`src/BloomExe/Book/TranslationGroupManager.cs` line 417 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6335#-Ns9dpkr7MDiirTp8xfe:-Ns9dpkr7MDiirTp8xff:bn4l0td) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4d56165957ef27b5c75f4992cea1e8bb71f0a37e/src/BloomExe/Book/TranslationGroupManager.cs#L417)):*
> ```Smalltalk
>         /// but it may be slightly more efficient to do so just once for the group.
>         /// </summary>
>         /// <param name="e"></param>
> ```

If these elements aren't provided with descriptions, I'd rather they be removed altogether.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6335)* status: 18 of 20 files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Book/AppearanceSettings.cs` line 595 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6335#-Ns9c62M-GqkdEH1khgD:-Ns9rFfLCvFpqDAHswZx:b-8pq9xg) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4d56165957ef27b5c75f4992cea1e8bb71f0a37e/src/BloomExe/Book/AppearanceSettings.cs#L595)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Should this commented out code be deleted?  or is it a meaningful alternative that we might yet need?  (maybe it's paired with the commented out code in the UpdateFromDynamic method?)
</blockquote></details>

Done. (I was a little attached to it because it took a LOT of figuring out, before I further figured out that it does NOT work when we parse the JSON file.)
___
*[`src/BloomExe/Book/TranslationGroupManager.cs` line 345 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6335#-Ns9d7NABsCWWcVdtCFK:-Ns9rfsXBUW93f2JnogW:btbl3fa) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4d56165957ef27b5c75f4992cea1e8bb71f0a37e/src/BloomExe/Book/TranslationGroupManager.cs#L345)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Probably not worth changing on its own, but surely a better variable name than 'e' could be found.  Even 'xe' or 'elem' would be better in my opinion.  'e' is used too often for an Event or Exception object in handler code.  But that may be more of an issue in code reviews where you don't see the whole context.
</blockquote></details>

Or even the 'e' in 'e.g.', which Resharper offered to change to the new name in several comments.
___
*[`src/BloomExe/Book/TranslationGroupManager.cs` line 417 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6335#-Ns9dpkr7MDiirTp8xfe:-Ns9s1Q82h_CrfsU9Xel:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4d56165957ef27b5c75f4992cea1e8bb71f0a37e/src/BloomExe/Book/TranslationGroupManager.cs#L417)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

If these elements aren't provided with descriptions, I'd rather they be removed altogether.
</blockquote></details>

Done.

**Review by StephenMcConnel — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6335#-:-Ns9tDc79TFaNoTkwMKy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 18 of 20 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6335)* status: all files reviewed, 2 unresolved discussions

___
*[`src/content/templates/bloom-foundation-mixins.pug` line 97 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6335#-Ns9xToO8kbD_HaBgSdk:-Ns9xS4X7yTVqA1Tbuxf:bkrv2vc) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dcf9f7a6338e67ae27d37a535c2d9310ab163a8f/src/content/templates/bloom-foundation-mixins.pug#L97)):*
> field-prototypeDeclaredExplicity-appearance

Can we fix the typo in this mixin now since you're changing the name anyway?



_Code quote:_
```Pug
field-prototypeDeclaredExplicity-appearance
```
___
*[`src/content/templates/template books/Paper Comic Book/Paper Comic Book.htm` line 194 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6335#-Ns9xu-s2xoyxhay7ena:-Ns9xu-s2xoyxhay7enb:b-4ofc8c) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dcf9f7a6338e67ae27d37a535c2d9310ab163a8f/src/content/templates/template%20books/Paper%20Comic%20Book/Paper%20Comic%20Book.htm#L194)):*
> ```HTML
> 
>             <div class="marginBox">
>                 <div class="bloom-translationGroup bookTitle" data-default-languages="V,N1"data-visibility-variable="cover-title-LN-show">
> ```

Will this lack of space between " and data cause a problem?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6335)* status: all files reviewed, 2 unresolved discussions

___
*[`src/content/templates/bloom-foundation-mixins.pug` line 97 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6335#-Ns9xToO8kbD_HaBgSdk:-NsA0xgE3JQl0uVdFDiA:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dcf9f7a6338e67ae27d37a535c2d9310ab163a8f/src/content/templates/bloom-foundation-mixins.pug#L97)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> field-prototypeDeclaredExplicity-appearance

Can we fix the typo in this mixin now since you're changing the name anyway?
</blockquote></details>

Done.
___
*[`src/content/templates/template books/Paper Comic Book/Paper Comic Book.htm` line 194 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6335#-Ns9xu-s2xoyxhay7ena:-NsA0yCg7TT-RSwGhlpL:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dcf9f7a6338e67ae27d37a535c2d9310ab163a8f/src/content/templates/template%20books/Paper%20Comic%20Book/Paper%20Comic%20Book.htm#L194)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Will this lack of space between " and data cause a problem?
</blockquote></details>

Done.

**Pull request merged**
