### PR TITLE
Move check for internet to UrlLookup.TryLookupUrl (BL-3840)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This should more robustly handle missing or intermittent internet.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1227)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/web/UrlLookup.cs, line 101 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1227#-KTQAIw_46UJuy-SHumD:-KTQAIw_46UJuy-SHumE:b-z6gt7i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/806542e2d9cfd08af2fe6d855cd1a1b9b41441e2/src/BloomExe/web/UrlLookup.cs#L101)):*
> ```Smalltalk
> 			if (!_internetAvailable)
> 				return false;
> 			if (!IsInternetAvailable())
> ```

Sorry if it feels like my comments regarding this code over the last couple days is sending you on a goose chase... but it strikes me as wrong to query a site which isn't where the data we want is just to see if we think we can retrieve the data we actually want. Is it possible to simply set a timeout on the real query to S3? Wouldn't that accomplish what we want with only one call?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1227)*

**Comment by StephenMcConnel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/web/UrlLookup.cs, line 101 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1227#-KTQAIw_46UJuy-SHumD:-KTQRgg8fUa2_0EAoG1u:b-q4cn7e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/806542e2d9cfd08af2fe6d855cd1a1b9b41441e2/src/BloomExe/web/UrlLookup.cs#L101)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Sorry if it feels like my comments regarding this code over the last couple days is sending you on a goose chase... but it strikes me as wrong to query a site which isn't where the data we want is just to see if we think we can retrieve the data we actually want. Is it possible to simply set a timeout on the real query to S3? Wouldn't that accomplish what we want with only one call?
</details>
In general I would agree on both counts.  Gordon (I think) looked at this and couldn't find any way to set a timeout on the "real query  to S3".  I suppose I could try one of the backup URLs stored in the resources (whose existence I was unaware of until this morning).  But even if we hardwire something here, 1) it might change on us, possibly invalidating the test URL, and 2) some pokes might register on our analytics when we wouldn't want them to.  If you want to suggest a better test URL that wouldn't be subject to those liabilities (stop working in the future if we change our web services or falsely impact analytics), I'd be happy to use it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1227)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/web/UrlLookup.cs, line 101 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1227#-KTQAIw_46UJuy-SHumD:-KTQX_AQb4SQ3gxWy6Sl:b3jyrp0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/806542e2d9cfd08af2fe6d855cd1a1b9b41441e2/src/BloomExe/web/UrlLookup.cs#L101)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary>
> In general I would agree on both counts.  Gordon (I think) looked at this and couldn't find any way to set a timeout on the "real query  to S3".  I suppose I could try one of the backup URLs stored in the resources (whose existence I was unaware of until this morning).  But even if we hardwire something here, 1) it might change on us, possibly invalidating the test URL, and 2) some pokes might register on our analytics when we wouldn't want them to.  If you want to suggest a better test URL that wouldn't be subject to those liabilities (stop working in the future if we change our web services or falsely impact analytics), I'd be happy to use it.
</details>
If we have to ping *some* url (which isn't the S3 url we want), that one is fine. I'm just still wondering if we can use the real one. This site indicates that setting timeouts and retry limits is part of the API :http://docs.aws.amazon.com/AWSSdkDocsNET/V2/DeveloperGuide/retries-timeouts.html. It is possible this particular call should be different than all our other S3 calls, I suppose, but I would have to think about that more. Even then, we could create another client object if we had to. I'll ping Gordon to see if he tried this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1227)*

**Comment by gmartin7** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/web/UrlLookup.cs, line 101 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1227#-KTQAIw_46UJuy-SHumD:-KTQjJZhSgCIbSEzKgcF:beav1su) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/806542e2d9cfd08af2fe6d855cd1a1b9b41441e2/src/BloomExe/web/UrlLookup.cs#L101)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> If we have to ping *some* url (which isn't the S3 url we want), that one is fine. I'm just still wondering if we can use the real one. This site indicates that setting timeouts and retry limits is part of the API :http://docs.aws.amazon.com/AWSSdkDocsNET/V2/DeveloperGuide/retries-timeouts.html. It is possible this particular call should be different than all our other S3 calls, I suppose, but I would have to think about that more. Even then, we could create another client object if we had to. I'll ping Gordon to see if he tried this.
</details>
Sorry, I didn't see that. If the example there at the end works, we should probably use that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1227)*

**Comment by StephenMcConnel** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/web/UrlLookup.cs, line 101 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1227#-KTQAIw_46UJuy-SHumD:-KTRM6zqNoHgoQiiRUbn:b-96dfrw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/806542e2d9cfd08af2fe6d855cd1a1b9b41441e2/src/BloomExe/web/UrlLookup.cs#L101)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary>
> Sorry, I didn't see that. If the example there at the end works, we should probably use that.
</details>
Done.  But I left the method for pinging the internet in place (but with a url to s3.amazonaws.com) in place in case we decide to use it somewhere else (or revert to using it here).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1227)*

**Comment by andrew-polk** [comment]
:lgtm: Thanks for you patience on this, Steve. And thanks for fixing the bug.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1227#-:-KTUWwf5Q0WltZyfUKZi:bszsgvs)*

**Pull request merged**
