### PR TITLE
Filter out redundant Team Collection messages (BL-9664)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4270)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
It's a good start. But I think we saw cases where, for some reason, we got a modify message before we got a 'new' message. This will keep just the modify message.  To handle that better, I think we should also improve the 'modify' code to look and see whether the corresponding local folder (for a .bloom file) exists and has local status. If not, we should convert it to a 'new'. (Just suppressing it would also be plausible, since the 'new' notification will probably arrive eventually...but now we have the redundancy code, it seems more robust to just go ahead and send 'new')

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4270#-:-MVSTeiiCjEx1DuY3xVR:b-j0e05j)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/TeamCollection/TeamCollectionMessageLog.cs, line 122 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4270#-MVSUq_r469fkTCDiPxm:-MVSUq_s48MVL-NLGE5G:blek8h5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8e0990a5794f9d9db27b21a9f3b8f27935ab5a46/src/BloomExe/TeamCollection/TeamCollectionMessageLog.cs#L122)):*
> ```Smalltalk
> 			if (messageType == MessageAndMilestoneType.NewStuff)
> 			{
> 				return Messages.Any((msg) => msg.MessageType == messageType && msg.L10NId == l10nId && msg.Param0 == param0 && msg.Param1 == param1);
> ```

Better just to look in CurrentNewStuff.  If we ever enhance things so that the log can show more history than the current session, we don't want to suppress change notifications based on history before the last reload.

**Review by StephenMcConnel — COMMENTED** [review]
I think this code will keep both the modify message and the new message since they have different l10nId values for different strings, but will show them out of order if they arrive that way.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4270#-:-MVT5thAAQp25K77HMRG:b-7ad3mm)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollectionMessageLog.cs, line 122 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4270#-MVSUq_r469fkTCDiPxm:-MVT4COT9gIzNaBDq7X-:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8e0990a5794f9d9db27b21a9f3b8f27935ab5a46/src/BloomExe/TeamCollection/TeamCollectionMessageLog.cs#L122)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Better just to look in CurrentNewStuff.  If we ever enhance things so that the log can show more history than the current session, we don't want to suppress change notifications based on history before the last reload.
</blockquote></details>

Done.

**Review by JohnThomson — COMMENTED** [review]
Sorry. Turns out the modified book handler is already ignoring messages about books that don't exist locally. So what you have should be enough to make sure we only get one NewBook message (and no Modified ones) for a new book. And there should never be a newbook message for a pre-existing book, and your code should ensure we only get one modified message. So I think we're OK.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4270#-:-MVTJ6gYC94EcU-0un6P:b-y2ti1r)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4270)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
