### PR TITLE
Improve notification of missing TMX string

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1172)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/web/I18NHandler.cs, line 95 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1172#-KQLhFPmzUZQrN7ze890:-KQLhFPmzUZQrN7ze891:b-ys2r6d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/23c65188450c9401040c7c357abb28e79e41385d/src/BloomExe/web/I18NHandler.cs#L95)):*
> ```Smalltalk
> 							//otherwise the next time we look for this string, it would get found and we would lose the ability to point out the 
> 							//problem to the developer.
> 							LocalizationManager.GetDynamicString("Bloom", "CopyToDistributionTmx_" + id, englishText);
> ```

Don't we only want to do this for developers? Otherwise, it can show up in the L10NSharp dialog for users.

---

*[src/BloomExe/web/I18NHandler.cs, line 108 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1172#-KQLhCBDlmSRZfywcCbs:-KQLhCBDlmSRZfywcCbt:bowqw3x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/23c65188450c9401040c7c357abb28e79e41385d/src/BloomExe/web/I18NHandler.cs#L108)):*
> ```Smalltalk
> 										id,
> 										englishText);
> 								NonFatalProblem.Report(ModalIf.None, PassiveIf.Alpha, "TMX ERROR", longMsg);
> ```

Not really an error, per se.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1172)*

**Comment by hatton** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/web/I18NHandler.cs, line 95 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1172#-KQLhFPmzUZQrN7ze890:-KQLtb48aFWlWHWWYDP9:b-1d7g7p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/23c65188450c9401040c7c357abb28e79e41385d/src/BloomExe/web/I18NHandler.cs#L95)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Don't we only want to do this for developers? Otherwise, it can show up in the L10NSharp dialog for users.
</details>
Right thanks! Fixed.

---

*[src/BloomExe/web/I18NHandler.cs, line 108 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1172#-KQLhCBDlmSRZfywcCbs:-KQLtcdsox2tQYnQ8bTC:b-l3rqgf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/23c65188450c9401040c7c357abb28e79e41385d/src/BloomExe/web/I18NHandler.cs#L108)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Not really an error, per se.
</details>
Hmm, to me it is. But I chose that message just for its effect, to get the developer's attention.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1172)*

**Comment by andrew-polk** [comment]
*[src/BloomExe/web/I18NHandler.cs, line 108 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1172#-KQLhCBDlmSRZfywcCbs:-KQLu9JXuHx3xFneYEv-:b9ox7mo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/23c65188450c9401040c7c357abb28e79e41385d/src/BloomExe/web/I18NHandler.cs#L108)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary>
> Hmm, to me it is. But I chose that message just for its effect, to get the developer's attention.
</details>
Yeah, that's what I figured (you wanted to get the dev's attention).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1172)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1172#-:-KQLuGY21RDdj-MVxf71:bnfp4nl)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1172)*

**Pull request merged**
