### PR TITLE
Add ability to copy leveled reader stats to clipboard (BL-10018)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4522)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4522)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[DistFiles/localization/en/Bloom.xlf, line 2226 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4522#-Mb8P3oKEey-M6DOIiQW:-Mb8P3oKEey-M6DOIiQX:b8lc4pq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2973789f88cf2f452fb4a4c1b26d14145eb3d7c3/DistFiles/localization/en/Bloom.xlf#L2226)):*
> ```XML
>         <source xml:lang="en">COPY BOOK STATS</source>
>         <note>ID: EditTab.Toolbox.LeveledReaderTool.CopyBookStatistics</note>
>       </trans-unit>
> ```

Do we want message like these to go to the translator in all caps? Or just provide title caps and let the material UI change the case?
I think the latter? That's what we did with EditTab.Toolbox.ComicTool.Options.AddChildBubble
___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.less, line 217 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4522#-Mb8RFOE9M25HftB11o5:-Mb8RFOE9M25HftB11o6:b-nfklfd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2973789f88cf2f452fb4a4c1b26d14145eb3d7c3/src/BloomBrowserUI/bookEdit/toolbox/toolbox.less#L217)):*
> ```Less
> 
> @smallGap: 4px;
> .copyBookStats {
> ```

Is there not a LR-specific less file?
I notice there is styling in the pug. That should be moved here.

How do we do the svg/label in the advanced section of the sign language tool? Is that a better solution than this? (may not be)
___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.less, line 225 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4522#-Mb8QSNV8wyU5dP2Escn:-Mb8QSNW6K_Kpf5e1FGb:b-rw486l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2973789f88cf2f452fb4a4c1b26d14145eb3d7c3/src/BloomBrowserUI/bookEdit/toolbox/toolbox.less#L225)):*
> ```Less
>         // Provide a small amount of space between the svg image and the text.
>         // (Trick stolen from https://coryrylan.com/blog/css-gap-space-with-flexbox.)
>         // "gap: @smallGap;" would be a lot simpler, but doesn't work until FF 63
> ```

Will you please find the doc and add this info regarding why we want a newer Geckofx?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4522)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[DistFiles/localization/en/Bloom.xlf, line 2226 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4522#-Mb8P3oKEey-M6DOIiQW:-MbC_XJb5Piat_6qckxC:b-i8q5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2973789f88cf2f452fb4a4c1b26d14145eb3d7c3/DistFiles/localization/en/Bloom.xlf#L2226)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Do we want message like these to go to the translator in all caps? Or just provide title caps and let the material UI change the case?
I think the latter? That's what we did with EditTab.Toolbox.ComicTool.Options.AddChildBubble
</blockquote></details>

The comics tool is TSX/React code.  This is used in a .pug file, which doesn't interface with material UI as far as I know.  But I can use css to do the uppercasing.
___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.less, line 217 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4522#-Mb8RFOE9M25HftB11o5:-MbCeA-a8xwe9QQaQ-5v:b8s8op6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2973789f88cf2f452fb4a4c1b26d14145eb3d7c3/src/BloomBrowserUI/bookEdit/toolbox/toolbox.less#L217)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is there not a LR-specific less file?
I notice there is styling in the pug. That should be moved here.

How do we do the svg/label in the advanced section of the sign language tool? Is that a better solution than this? (may not be)
</blockquote></details>

I created a LR-specific less file for this new content.

Trying to embed the image as a background-image for a button (as sign language does) results in a bad image display.  I'm not sure what is displayed for copy.svg, but it's not the image we want.  (The svg files used in sign language displayed okay, but not copy.svg.)  The current code works, and I've already spent a day getting it to work.
___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.less, line 225 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4522#-Mb8QSNV8wyU5dP2Escn:-MbCsf0S4Dg-zuYQXEoS:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2973789f88cf2f452fb4a4c1b26d14145eb3d7c3/src/BloomBrowserUI/bookEdit/toolbox/toolbox.less#L225)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Will you please find the doc and add this info regarding why we want a newer Geckofx?
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4522)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[DistFiles/localization/en/Bloom.xlf, line 2226 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4522#-Mb8P3oKEey-M6DOIiQW:-MbDHso76Pm0lfekpO6M:bm5eeod) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2973789f88cf2f452fb4a4c1b26d14145eb3d7c3/DistFiles/localization/en/Bloom.xlf#L2226)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

The comics tool is TSX/React code.  This is used in a .pug file, which doesn't interface with material UI as far as I know.  But I can use css to do the uppercasing.
</blockquote></details>

Ok, sorry; I didn't realize it was a different context.
Still not sure which is better. But this is probably better as we could choose not to display in all caps in the future and would still have legitimate translations.
___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.less, line 217 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4522#-Mb8RFOE9M25HftB11o5:-MbDJMkjCq25t09CVbM-:brcr6cm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2973789f88cf2f452fb4a4c1b26d14145eb3d7c3/src/BloomBrowserUI/bookEdit/toolbox/toolbox.less#L217)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I created a LR-specific less file for this new content.

Trying to embed the image as a background-image for a button (as sign language does) results in a bad image display.  I'm not sure what is displayed for copy.svg, but it's not the image we want.  (The svg files used in sign language displayed okay, but not copy.svg.)  The current code works, and I've already spent a day getting it to work.
</blockquote></details>

Looks like there is a readerTools.less already.
___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.less, line 225 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4522#-Mb8QSNV8wyU5dP2Escn:-MbDIt_m98XoMnDvdu4T:b-ucfkn4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2973789f88cf2f452fb4a4c1b26d14145eb3d7c3/src/BloomBrowserUI/bookEdit/toolbox/toolbox.less#L225)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4522)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.less, line 217 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4522#-Mb8RFOE9M25HftB11o5:-MbDTq9jAPWC0mXGKqs8:b2a63gy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2973789f88cf2f452fb4a4c1b26d14145eb3d7c3/src/BloomBrowserUI/bookEdit/toolbox/toolbox.less#L217)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like there is a readerTools.less already.
</blockquote></details>

moved the new code there

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4522)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
