### PR TITLE
BL-5869 User feedback while recording

### PR DESCRIPTION
**Pull request by gmartin7**
* insert div with .bloom-videoOverlay before video
   container while recording
* add a "Recording" label while recording
* remove it all when we're done
* also repaired sign language l10n keys

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449)

### CODE REVIEW

**Comment by JohnThomson** [comment]
This is good work, but I think it can be improved a bit. See what you think of the suggestions...I may be being too picky. Don't worry if any of them looks like being a lot of work, and feel free to disagree with any of them.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/BloomBrowserUI/bookEdit/css/editMode.less, line 580 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-LDrsb9ACyGwjue2MFex:-LDrsb9ACyGwjue2MFey:b-88yr3x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4052af093cf8039a989afbab3e06993c824eac5/src/BloomBrowserUI/bookEdit/css/editMode.less#L580)):*
> ```Less
> .bloom-videoOverlay {
>     position: absolute;
>     display: table;
> ```

When you're not making anything remotely table-like, but just want horizontal and vertical centering, I'd think it more natural to use some display:flex settings.

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 190 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-LDrw6s3BdqmOV74x9k7:-LDrw6s3BdqmOV74x9k8:b1iqulw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4052af093cf8039a989afbab3e06993c824eac5/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L190)):*
> ```XML
>     }
> 
>     public componentDidUpdate(prevProps, prevState: IComponentState) {
> ```

In the spirit of React, each case should put things in the right state, irrespective of previous state. But you are depending on countdown2 and 1 following 3, and that recording comes after that. Admittedly, that probably isn't going to change, but it would be much more elegant to slightly change hideVideoWithOverlay so it does nothing if the overlay is already present, and then the first three cases could be combined into one that calls it, while (just to make sure) case recording could call it too, before setting the label.

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 206 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-LDrwx_P6XSaDcpq1QPg:-LDrwx_P6XSaDcpq1QPh:b-c8b3k9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4052af093cf8039a989afbab3e06993c824eac5/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L206)):*
> ```XML
>             case "recording":
>                 // insert "Recording" message in C#-land where it is easily localized
>                 axios.post("/bloom/api/toolbox/recordingStart");
> ```

It feels heavy-weight to add a whole server call-back (which then has to manipulate the DOM from C#) just to avoid doing localization in JS. Can't you just do theOneLocalizationManager.asyncGetText(id, default).done(localizedString => <stick localized string in the label>)? We have lots of examples of this already.

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 401 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-LDrtRujAz5I2iY_FzlC:-LDrtRujAz5I2iY_FzlD:b-urxnpt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4052af093cf8039a989afbab3e06993c824eac5/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L401)):*
> ```XML
>     private static overlayClass: string = ".bloom-videoOverlay";
> 
>     public static hideVideoWithOverlay(): void {
> ```

What would you think of "showOverlayToHideVideo"? I keep expecting "hide" to remove something or make it invisible.

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 402 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-LDrtirX3s_jdkY5alov:-LDrtirX3s_jdkY5alow:bs1d7kd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4052af093cf8039a989afbab3e06993c824eac5/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L402)):*
> ```XML
> 
>     public static hideVideoWithOverlay(): void {
>         const containers = $(SignLanguageTool.getVideoContainers(true));
> ```

John has been trying to get me not to use JQuery in new code. Most things it does can be pretty easily done in plain JS, especially when you only have to support one fairly modern browser.

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 409 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-LDru8bMAqAgZIosaIhr:-LDru8bMAqAgZIosaIhs:besripn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4052af093cf8039a989afbab3e06993c824eac5/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L409)):*
> ```XML
>         containers.toArray().forEach((element, idx) => {
>             const elt = element as Element;
>             const w = elt.clientWidth;
> ```

(1) these width functions are very prone to fail at non-100% zoom factors. Have you tested?
(2) if you put the overlay inside the video container and make sure the container is position: relative, I think you can do all this with CSS: position: absolute; height: 100%; width: 100%; left: 0; top:0; (and you probably also need box-sizing: border-box; so the 100% size includes the border). (Sorry, I haven't tested this, just going from memory.)

---

*[src/BloomExe/Edit/EditingModel.cs, line 1458 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-LDrykFG7soP9RBA69PL:-LDrykFG7soP9RBA69PM:b-4g8e1k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4052af093cf8039a989afbab3e06993c824eac5/src/BloomExe/Edit/EditingModel.cs#L1458)):*
> ```Smalltalk
> 		// Notification from sign language tool that recording has begun.
> 		// We need to get a localized "Recording" message and insert it in the video overlay covering the current video.
> 		private void HandleRecordingStart(ApiRequest request)
> ```

If this survives, consider a name that doesn't suggest it's responsible to actually start the recording happening...maybe HandleStartRecordingLabel? HandleSettingRecordingLabel?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-:-LDrz3MRA-3sXVlb00bt:b-rjut4c)*

**Comment by gmartin7** [comment]
Much better. Thanks.

---

Review status: 3 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/css/editMode.less, line 580 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-LDrsb9ACyGwjue2MFex:-LDwXzoJ4PHuOjmrSUQp:bv7cbh0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4052af093cf8039a989afbab3e06993c824eac5/src/BloomBrowserUI/bookEdit/css/editMode.less#L580)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

When you're not making anything remotely table-like, but just want horizontal and vertical centering, I'd think it more natural to use some display:flex settings.
</blockquote></details>

OK, that worked well.

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 190 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-LDrw6s3BdqmOV74x9k7:-LDwyZ0K36Nt7EXnSg6x:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4052af093cf8039a989afbab3e06993c824eac5/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L190)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

In the spirit of React, each case should put things in the right state, irrespective of previous state. But you are depending on countdown2 and 1 following 3, and that recording comes after that. Admittedly, that probably isn't going to change, but it would be much more elegant to slightly change hideVideoWithOverlay so it does nothing if the overlay is already present, and then the first three cases could be combined into one that calls it, while (just to make sure) case recording could call it too, before setting the label.
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 206 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-LDrwx_P6XSaDcpq1QPg:-LDwgA-H8qeG0kQK5uUf:buraayj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4052af093cf8039a989afbab3e06993c824eac5/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L206)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It feels heavy-weight to add a whole server call-back (which then has to manipulate the DOM from C#) just to avoid doing localization in JS. Can't you just do theOneLocalizationManager.asyncGetText(id, default).done(localizedString => <stick localized string in the label>)? We have lots of examples of this already.
</blockquote></details>

And the React component already goes to the localization manager to get the same string! I was able to grab the string from the React DOM and stuff in the edit pane label. Works great! Verified that it grabs the French version if I define this string as approved in fr/Bloom.xlf.

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 401 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-LDrtRujAz5I2iY_FzlC:-LDw_n95Eo0GdW-7KaA_:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4052af093cf8039a989afbab3e06993c824eac5/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L401)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

What would you think of "showOverlayToHideVideo"? I keep expecting "hide" to remove something or make it invisible.
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 402 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-LDrtirX3s_jdkY5alov:-LDwylaF60MTyylZRweQ:b-ff36i0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4052af093cf8039a989afbab3e06993c824eac5/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L402)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

John has been trying to get me not to use JQuery in new code. Most things it does can be pretty easily done in plain JS, especially when you only have to support one fairly modern browser.
</blockquote></details>

Interesting translating my code to straight js... but it works!

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 409 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-LDru8bMAqAgZIosaIhr:-LDwXOGc-pZA8J32PSyL:b-y62ykb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4052af093cf8039a989afbab3e06993c824eac5/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L409)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

(1) these width functions are very prone to fail at non-100% zoom factors. Have you tested?
(2) if you put the overlay inside the video container and make sure the container is position: relative, I think you can do all this with CSS: position: absolute; height: 100%; width: 100%; left: 0; top:0; (and you probably also need box-sizing: border-box; so the 100% size includes the border). (Sorry, I haven't tested this, just going from memory.)
</blockquote></details>

Cool! I didn't need to move it inside. .split-pane-component-inner is already position: relative, so it works with css and flex. Much simpler. Thx.

---

*[src/BloomExe/Edit/EditingModel.cs, line 1458 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-LDrykFG7soP9RBA69PL:-LDwywUv6XNXrGsGjffx:b-wakapc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4052af093cf8039a989afbab3e06993c824eac5/src/BloomExe/Edit/EditingModel.cs#L1458)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

If this survives, consider a name that doesn't suggest it's responsible to actually start the recording happening...maybe HandleStartRecordingLabel? HandleSettingRecordingLabel?
</blockquote></details>

It didn't survive.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-:-LDwz-vgCjnL-y9bDlQx:b-iezfu3)*

**Comment by JohnThomson** [comment]
Yes, much improved. A couple of minor points and one (about only hiding the video you are going to record over) that is probably pretty important. Sorry I missed it the first time.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 204 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-LDxRTrc4tY5BWM10XSn:-LDxRTrc4tY5BWM10XSo:bbhuh26) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8991c18c348136d031972fb5124cca7146d7c6dd/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L204)):*
> ```XML
>                 break;
>             case "recording":
>                 SignLanguageTool.addRecordingLabelToOverlay(document);
> ```

To complete making it not depend on the state sequence, this case should call SignLanguageTool.showOverlayToHideVideo(); before trying to add to them.

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 420 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-LDxRvAK96xxK0kxMkN8:-LDxRvAK96xxK0kxMkN9:bmp0pv7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8991c18c348136d031972fb5124cca7146d7c6dd/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L420)):*
> ```XML
>         for (var i = 0; i < containers.length; i++) {
>             containers[i].previousElementSibling.firstChild.textContent = recordingLabel;
>         }
> ```

I should have picked this up earlier...but I suddenly realized: you're not recording over ALL the videos on the page at once! Only the selected one. Likewise, the overlay should probably only go on the selected one, thus emphasizing WHICH video you are about to replace if there is more than one.

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 426 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-LDxSNeC7k9Lz2XBc9l9:-LDxSNeC7k9Lz2XBc9lA:bi2q38a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8991c18c348136d031972fb5124cca7146d7c6dd/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L426)):*
> ```XML
>     public static removeVideoOverlay(): void {
>         const containers = SignLanguageTool.getVideoContainers(true);
>         for (var i = 0; i < containers.length; i++) {
> ```

Especially since we're trying not to depend on previous state, but anyway for safety, I'd like to see a check that we only remove the previous sibling if (a) there is one, and (b) it has the expected class to be the overlay.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-:-LDxTEyYBSlP3mtpViFN:bkkfw4g)*

**Comment by gmartin7** [comment]
OK. Fixed up all better.

---

Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 204 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-LDxRTrc4tY5BWM10XSn:-LEAvPhs2vsGDpK542pT:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8991c18c348136d031972fb5124cca7146d7c6dd/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L204)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

To complete making it not depend on the state sequence, this case should call SignLanguageTool.showOverlayToHideVideo(); before trying to add to them.
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 420 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-LDxRvAK96xxK0kxMkN8:-LEAvsbLEDMwraqlsWX4:b8b4fto) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8991c18c348136d031972fb5124cca7146d7c6dd/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L420)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I should have picked this up earlier...but I suddenly realized: you're not recording over ALL the videos on the page at once! Only the selected one. Likewise, the overlay should probably only go on the selected one, thus emphasizing WHICH video you are about to replace if there is more than one.
</blockquote></details>

Yes you're right. And the 'true' param in getVideoContainers() tells it to only get the selected container. I'll change the code in here to assume we only get one. Will we only get one video per page with '.bloom-selected'? Yes, I tested it with 2 videos on the page and it works fine.

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 426 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-LDxSNeC7k9Lz2XBc9l9:-LEB-k4V1h5JoFBxAXJz:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8991c18c348136d031972fb5124cca7146d7c6dd/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L426)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Especially since we're trying not to depend on previous state, but anyway for safety, I'd like to see a check that we only remove the previous sibling if (a) there is one, and (b) it has the expected class to be the overlay.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-:-LEB-rec9lFZc7dA-Lzq:bl33995)*

**Comment by JohnThomson** [comment]
:lgtm: (with one suggested thing to test before merging)

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 401 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-LEB2AzB64cQvKGqcMRR:-LEB2AzCD767YceXAHCI:b-yjtibg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d05f399970d713c912b89b82dc1d4aeb4e3742c4/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L401)):*
> ```XML
> 
>     // Make an overlay and slap it over the selected edit pane video still while we're recording
>     public static showOverlayToHideVideo(): void {
> ```

I wonder whether we need to do something to make sure no other div has the overlay? For example, what does (and what should?) happen if you click a different video while counting down to start recording? It's probably unlikely enough that we needn't worry about what behavior is correct for such cases (worse: click another video while recording!) but it shouldn't be obviously wrong. For example, perhaps clicking some other video, besides selecting it, is yet another way to stop recording and return to the waiting state? May want to check with JohnH.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-:-LEB3BtH8EZU7yliWg8p:b-3hijku)*

**Comment by gmartin7** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 401 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449#-LEB2AzB64cQvKGqcMRR:-LEFPJlPElokN7PnEnze:b-wyq4yh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d05f399970d713c912b89b82dc1d4aeb4e3742c4/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L401)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I wonder whether we need to do something to make sure no other div has the overlay? For example, what does (and what should?) happen if you click a different video while counting down to start recording? It's probably unlikely enough that we needn't worry about what behavior is correct for such cases (worse: click another video while recording!) but it shouldn't be obviously wrong. For example, perhaps clicking some other video, besides selecting it, is yet another way to stop recording and return to the waiting state? May want to check with JohnH.
</blockquote></details>

As per standup discussion, I'm merging this so it doesn't interfere with any future work in the area.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449)*

**Pull request merged**
