### PR TITLE
Add Language and Script page to the create collection wizard (BL-2912) [Bloom 3.6]

### PR DESCRIPTION
**Pull request by StephenMcConnel**
[Review on Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/879)

### CODE REVIEW

**Comment by StephenMcConnel** [comment]
THIS IS DESIGNATED FOR Bloom 3.6.  DO NOT MERGE YET.

**Comment by JohnThomson** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[src/BloomExe/CollectionCreating/NewCollectionWizard.cs, line 203 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/879#-K3Qz3-_Cu4q11_8l_FI:-K3Qz3-_Cu4q11_8l_FJ:1415048669) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fc4b0297ee7cd8d255a455541aece23512b48d86/src/BloomExe/CollectionCreating/NewCollectionWizard.cs#L203)):_
Shouldn't we do something to warn people if they typed an invalid height?

---

_[src/BloomExe/MiscUI/LanguageFontDetails.cs, line 40 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/879#-K3Qzcxzs28n0CpQZSPx:-K3Qzcxzs28n0CpQZSPy:37177805) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fc4b0297ee7cd8d255a455541aece23512b48d86/src/BloomExe/MiscUI/LanguageFontDetails.cs#L40)):_
It would be marginally more efficient to add the constant scroll bar width outside the loop

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/879)_

**Comment by StephenMcConnel** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/BloomExe/CollectionCreating/NewCollectionWizard.cs, line 203 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/879#-K3Qz3-_Cu4q11_8l_FI:-K3RIXn5UkBQBRrEw3yD:-547433779) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fc4b0297ee7cd8d255a455541aece23512b48d86/src/BloomExe/CollectionCreating/NewCollectionWizard.cs#L203)):_
This is a drop-down list that doesn't accept random typed input.  It has to be something on the list.

---

_[src/BloomExe/MiscUI/LanguageFontDetails.cs, line 40 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/879#-K3Qzcxzs28n0CpQZSPx:-K3RK39ZrM9l4cI2rUf6:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fc4b0297ee7cd8d255a455541aece23512b48d86/src/BloomExe/MiscUI/LanguageFontDetails.cs#L40)):_
Done.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/879)_

**Comment by JohnThomson** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/879)_

**Pull request merged**
