### PR TITLE
BL-12410 forum invitation dialog

### PR DESCRIPTION
**Pull request by nabalone**
Show forum invitation dialog every two weeks, shortly after launch, until they click "How to Join".

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035)

### CODE REVIEW

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035)* status: 0 of 10 files reviewed, 4 unresolved discussions

___
*[`src/BloomBrowserUI/react_components/forumInvitationDialog.tsx` line 86 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035#-NasqDTx7eavr8EGtroT:-NasqDTx7eavr8EGtroU:b-qnqw3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/13856f68cb2322b09300466451168bfc4a6f5046/src/BloomBrowserUI/react_components/forumInvitationDialog.tsx#L86)):*
> ```XML
>                     height: 170px;
>                     width: 400px;
>                     position: sticky;
> ```

This worked but I am not familiar with `position: sticky`. Is this good or is there a better way to do it?
___
*[`src/BloomBrowserUI/react_components/stories.tsx` line 476 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035#-NasqY2p79ZkVnlhIJCf:-NasqY2p79ZkVnlhIJCg:b-z7kctu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/13856f68cb2322b09300466451168bfc4a6f5046/src/BloomBrowserUI/react_components/stories.tsx#L476)):*
> ```XML
>         ))
>     )
>     .add("ForumInvitationDialog", () =>
> ```

This isn't really useful though because the forum invitation dialog doesn't show anything until it gets the user settings and determines it should
___
*[`src/BloomExe/app.config` line 3 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035#-Nasqs4W14jw1WhoEAxy:-Nasqs4W14jw1WhoEAxz:biwg6r0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/70e50ff3f9295e3ad7419ffe7c77291a5466b390/src/BloomExe/app.config#L3)):*
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <configuration>
>     <configSections>
> ```

Not sure why Visual Studio made all these whitespace changes
___
*[`src/BloomExe/WebView2Browser.cs` line 48 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035#-NasqxVpCNwBhhxrCihE:-NasqxVpCNwBhhxrCihF:b-4wta5d) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/13856f68cb2322b09300466451168bfc4a6f5046/src/BloomExe/WebView2Browser.cs#L48)):*
> ```Smalltalk
>                     _webview.CoreWebView2.NavigationStarting += (object sender1, CoreWebView2NavigationStartingEventArgs args1) =>
> 						{
> 							if (args1.Uri.StartsWith("http") && !args1.Uri.StartsWith("http://localhost"))
> ```

Is this the best way to check? Do we want to check for localhost more broadly or more narrowly? (I added the localhost clause to the code JH suggested)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035)* status: all files reviewed, 7 unresolved discussions (waiting on @nabalone)

___
*[`DistFiles/localization/en/BloomLowPriority.xlf` line 179 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035#-NavyJky7jy3-OPt6gOC:-NavyJky7jy3-OPt6gOD:b-xv7awp) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/13856f68cb2322b09300466451168bfc4a6f5046/DistFiles/localization/en/BloomLowPriority.xlf#L179)):*
> ```XML
>             <note>ID: EditTab.Toolbox.TalkingBookTool.MicrophoneAccessProblem</note>
>           </trans-unit>
>           <trans-unit id="ForumInvitationDialog.BloomCommunityForum">
> ```

Until 5.6 is getting ready to go beta, we'll need to add the translate="no" attribute on the trans-unit.
And it is helpful to add a comment about the version adding it.

So this trans-unit would become
```
          <trans-unit id="ForumInvitationDialog.BloomCommunityForum" translate="no">
            <!-- Added in 5.6 -->
            <source xml:lang="en">Bloom Community Forum</source>
            <note>ID: ForumInvitationDialog.BloomCommunityForum</note>
          </trans-unit>

```
Same for the others.

Since every user will see this dialog front and center, I think we actually want these strings in high priority.
But it looks like we don't have a high priority file... so they should go in Bloom.xlf.
___
*[`DistFiles/localization/en/BloomLowPriority.xlf` line 204 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035#-NavzEty3EiPxXNiiNXY:-NavzEty3EiPxXNiiNXZ:b-9ewb44) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/13856f68cb2322b09300466451168bfc4a6f5046/DistFiles/localization/en/BloomLowPriority.xlf#L204)):*
Rather than asking the translators to translate with a capitalized source string, I think we want to give them
> How to Join

Then the UI should capitalize it. (I think button labels will get capitalized by default. If not, you can capitalize it in code.)

My reasoning:
If we ever decide to change the style, we have the original translations.
___
*[`src/BloomBrowserUI/react_components/forumInvitationDialog.tsx` line 86 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035#-NasqDTx7eavr8EGtroT:-NawDSMb9ZqyhFqedWLX:b-8a1yhz) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/13856f68cb2322b09300466451168bfc4a6f5046/src/BloomBrowserUI/react_components/forumInvitationDialog.tsx#L86)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

This worked but I am not familiar with `position: sticky`. Is this good or is there a better way to do it?
</blockquote></details>

What is `position: sticky` accomplishing?
___
*[`src/BloomBrowserUI/react_components/stories.tsx` line 476 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035#-NasqY2p79ZkVnlhIJCf:-Naw9th8-ls6WJLu4u6B:b-plu0i3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/13856f68cb2322b09300466451168bfc4a6f5046/src/BloomBrowserUI/react_components/stories.tsx#L476)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

This isn't really useful though because the forum invitation dialog doesn't show anything until it gets the user settings and determines it should
</blockquote></details>

I think we may have a way to mock an api call somewhere for storybook...
Or maybe you can hardcode something, detecting the `normalDialogEnvironmentForStorybook` (see a couple lines above).
But I wouldn't spend more than 20 minutes on it.
If you want to leave the code here, but it still doesn't do much, I would add a code comment similar to the one you put in the PR.
___
*[`src/BloomExe/WebView2Browser.cs` line 48 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035#-NasqxVpCNwBhhxrCihE:-NawEqxs4icx4pi8cXDt:bfcr6kk) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/13856f68cb2322b09300466451168bfc4a6f5046/src/BloomExe/WebView2Browser.cs#L48)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Is this the best way to check? Do we want to check for localhost more broadly or more narrowly? (I added the localhost clause to the code JH suggested)
</blockquote></details>

Hm. Were you able to test this? (like by making your button temporarily use an href and verifying this code is called?)

There actually are one or two places we want to launch a localhost url in an external browser, but I'm guessing that will still be ok, because this code will just ignore the request and whatever is currently making it work will still work. But still worth a test.
The only place I know of off the top of my head is in the LR tool:

___
*[`src/BloomExe/web/controllers/AppApi.cs` line 116 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035#-NawBJHS4gVBCmSixkQd:-NawBJHS4gVBCmSixkQe:b-qvvlrm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/13856f68cb2322b09300466451168bfc4a6f5046/src/BloomExe/web/controllers/AppApi.cs#L116)):*
> ```Smalltalk
> 		// Get requests should have queryparam settingName
> 		// Post requests should have a json object with settingName and settingValue
> 		public void UserSettings(ApiRequest request)
> ```

I think naming this method `HandleUserSettings` would better align with our normal paradigm.

And do you think it would be better for it to be `HandleUserSetting` and rename the endpoint to `userSetting`?

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035)* status: 5 of 11 files reviewed, 6 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/react_components/forumInvitationDialog.tsx` line 86 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035#-NasqDTx7eavr8EGtroT:-NawOtviD1IKdZM9ufpY:bc7zzop) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/13856f68cb2322b09300466451168bfc4a6f5046/src/BloomBrowserUI/react_components/forumInvitationDialog.tsx#L86)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What is `position: sticky` accomplishing?
</blockquote></details>

Removed. I forgot that I was using this only for the "Get Online First" text which JH said to remove
___
*[`src/BloomBrowserUI/react_components/stories.tsx` line 476 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035#-NasqY2p79ZkVnlhIJCf:-Nax_3Ze5OMxkEsL8ofw:bj4fvy0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/13856f68cb2322b09300466451168bfc4a6f5046/src/BloomBrowserUI/react_components/stories.tsx#L476)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think we may have a way to mock an api call somewhere for storybook...
Or maybe you can hardcode something, detecting the `normalDialogEnvironmentForStorybook` (see a couple lines above).
But I wouldn't spend more than 20 minutes on it.
If you want to leave the code here, but it still doesn't do much, I would add a code comment similar to the one you put in the PR.
</blockquote></details>

How's this?
___
*[`src/BloomExe/WebView2Browser.cs` line 48 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035#-NasqxVpCNwBhhxrCihE:-NawZtSY6-UdN8dDSZgT:bdeakvi) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/13856f68cb2322b09300466451168bfc4a6f5046/src/BloomExe/WebView2Browser.cs#L48)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Hm. Were you able to test this? (like by making your button temporarily use an href and verifying this code is called?)

There actually are one or two places we want to launch a localhost url in an external browser, but I'm guessing that will still be ok, because this code will just ignore the request and whatever is currently making it work will still work. But still worth a test.
The only place I know of off the top of my head is in the LR tool:


</blockquote></details>

Yes, I did test this by temporarily making my button a normal link. Those leveled reader tool links still work and open localhost in an external browser.
___
*[`src/BloomExe/web/controllers/AppApi.cs` line 116 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035#-NawBJHS4gVBCmSixkQd:-Naw_oq32vKottm2ylml:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/13856f68cb2322b09300466451168bfc4a6f5046/src/BloomExe/web/controllers/AppApi.cs#L116)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think naming this method `HandleUserSettings` would better align with our normal paradigm.

And do you think it would be better for it to be `HandleUserSetting` and rename the endpoint to `userSetting`?
</blockquote></details>

Done.
___
*[`DistFiles/localization/en/BloomLowPriority.xlf` line 179 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035#-NavyJky7jy3-OPt6gOC:-NawU_HY44RLcSYsNATz:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/13856f68cb2322b09300466451168bfc4a6f5046/DistFiles/localization/en/BloomLowPriority.xlf#L179)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Until 5.6 is getting ready to go beta, we'll need to add the translate="no" attribute on the trans-unit.
And it is helpful to add a comment about the version adding it.

So this trans-unit would become
```
          <trans-unit id="ForumInvitationDialog.BloomCommunityForum" translate="no">
            <!-- Added in 5.6 -->
            <source xml:lang="en">Bloom Community Forum</source>
            <note>ID: ForumInvitationDialog.BloomCommunityForum</note>
          </trans-unit>

```
Same for the others.

Since every user will see this dialog front and center, I think we actually want these strings in high priority.
But it looks like we don't have a high priority file... so they should go in Bloom.xlf.
</blockquote></details>

Done.
___
*[`DistFiles/localization/en/BloomLowPriority.xlf` line 204 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035#-NavzEty3EiPxXNiiNXY:-NawUBjC36Q2EZBgwLA5:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/13856f68cb2322b09300466451168bfc4a6f5046/DistFiles/localization/en/BloomLowPriority.xlf#L204)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Rather than asking the translators to translate with a capitalized source string, I think we want to give them
> How to Join

Then the UI should capitalize it. (I think button labels will get capitalized by default. If not, you can capitalize it in code.)

My reasoning:
If we ever decide to change the style, we have the original translations.
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @nabalone)

___
*[`src/BloomBrowserUI/react_components/stories.tsx` line 476 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035#-NasqY2p79ZkVnlhIJCf:-Nb0heWG-HlA87d6J5x6:b-9aam7z) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/13856f68cb2322b09300466451168bfc4a6f5046/src/BloomBrowserUI/react_components/stories.tsx#L476)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

How's this?
</blockquote></details>

I went to play with it and discovered `StorybookDialogWrapper`
Since I had already coded it to see if it worked, I just added my change as a commit.
If you think it looks good, we can merge.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @nabalone)

**Review by nabalone — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035#-:-NbG2Bvs6Ci0_UCScdY6:bnfp4nl)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/react_components/stories.tsx` line 476 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035#-NasqY2p79ZkVnlhIJCf:-NbG21ZLDFWcxksGbWIo:bf454n5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/13856f68cb2322b09300466451168bfc4a6f5046/src/BloomBrowserUI/react_components/stories.tsx#L476)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I went to play with it and discovered `StorybookDialogWrapper`
Since I had already coded it to see if it worked, I just added my change as a commit.
If you think it looks good, we can merge.
</blockquote></details>

Oh great! Yes that looks much better

**Pull request merged**
