### PR TITLE
Don't have "Show in File Explorer" for factory collections (BL-11688)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5504)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5504)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/collectionsTab/BookButton.tsx` line 412 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5504#-NFj8nhm5Sfjq9WK-HIg:-NFj8nhm5Sfjq9WK-HIh:betjjy9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ab3d51f7f865e9ffd460af8bdedc96d310162523/src/BloomBrowserUI/collectionsTab/BookButton.tsx#L412)):*
> ```XML
>                 variant="outlined"
>                 size="large"
>                 title={title}
> ```

What convinces you we didn't have the path on purpose?
I.e. why are you considering this a regression as opposed to a feature?

It would probably be better to back this out of here and create a new card in case this isn't wanted.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5504)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/collectionsTab/BookButton.tsx` line 412 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5504#-NFj8nhm5Sfjq9WK-HIg:-NFjAo1z6pw_8TX6HIv3:ba27zrg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ab3d51f7f865e9ffd460af8bdedc96d310162523/src/BloomBrowserUI/collectionsTab/BookButton.tsx#L412)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What convinces you we didn't have the path on purpose?
I.e. why are you considering this a regression as opposed to a feature?

It would probably be better to back this out of here and create a new card in case this isn't wanted.
</blockquote></details>

See https://issues.bloomlibrary.org/youtrack/issue/BL-11020 which implies we want full path.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5504)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/collectionsTab/BookButton.tsx` line 412 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5504#-NFj8nhm5Sfjq9WK-HIg:-NFsv2e2ARjSP2w8gVp8:b-9ssi22) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ab3d51f7f865e9ffd460af8bdedc96d310162523/src/BloomBrowserUI/collectionsTab/BookButton.tsx#L412)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

See https://issues.bloomlibrary.org/youtrack/issue/BL-11020 which implies we want full path.
</blockquote></details>

Done. (Though I'm not convinced that showing the full path was intentional, especially for factory collections.)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5504)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
