### PR TITLE
BL-2894 Fix Source bubble scroll bar

### PR DESCRIPTION
**Pull request by gmartin7**
* remove scroll bar
* when a large bubble's textbox is selected,
   that bubble will overlap bubbles from other textboxes

[Review on Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/876)

### CODE REVIEW

**Comment by JohnThomson** [comment]
I don't really understand how this works, but I don't see any obvious problems apart from a couple of minor points, so if you're confident we can probably go ahead.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[src/BloomBrowserUI/bookEdit/css/editMode.css, line 1 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/876#-K3MGP9MeJe8K3syeO3-:-K3MGP9MeJe8K3syeO30:26073669) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/61ce6001a9e9e0d1301d12f177f1de2f1059e8a0/src/BloomBrowserUI/bookEdit/css/editMode.css#L1)):_
What's going on here? There's an editMode.less, but you haven't checked in a modified version.

---

_[src/BloomBrowserUI/bookEdit/css/editMode.css, line 9 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/876#-K3MIQCdzb_QQJ9G82xq:-K3MIQCe3q1lLfa0scMY:-1600752052) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/61ce6001a9e9e0d1301d12f177f1de2f1059e8a0/src/BloomBrowserUI/bookEdit/css/editMode.css#L9)):_
Isn't !important meant to be something of a last resort? Is there a reasonable way to make these rules specific enough to win without it? (Not saying there must be...just asking.)

---

_[src/BloomBrowserUI/bookEdit/sourceBubbles/bloomSourceBubbles.js, line 319 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/876#-K3MJ6qEpvkznOtE4pGS:-K3MJ6qEpvkznOtE4pGT:887185527) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/61ce6001a9e9e0d1301d12f177f1de2f1059e8a0/src/BloomBrowserUI/bookEdit/sourceBubbles/bloomSourceBubbles.js#L319)):_
Seems you already have this attr value in a variable

---

_[src/BloomBrowserUI/bookEdit/sourceBubbles/sourceBubbles.less, line 18 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/876#-K3MJSa8paMQz9GzIkyq:-K3MJSa8paMQz9GzIkyr:-1103482098) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/61ce6001a9e9e0d1301d12f177f1de2f1059e8a0/src/BloomBrowserUI/bookEdit/sourceBubbles/sourceBubbles.less#L18)):_
Can you explain a little more...why does importing into editMode require this?

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/876#-:-K3MK153KKXgNwD0BRaB:-861569803)_

**Comment by hatton** [comment]
I still see a mess here: http://issues.bloomlibrary.org/youtrack/issue/BL-2874#comment=102-6807

**Comment by gmartin7** [comment]
New commit refactors ts data-attr and adds some more waffling comments

---

Review status: 4 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/BloomBrowserUI/bookEdit/css/editMode.css, line 1 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/876#-K3MGP9MeJe8K3syeO3-:-K3_tvJCSC8zD4jaSN71:-16723989) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/61ce6001a9e9e0d1301d12f177f1de2f1059e8a0/src/BloomBrowserUI/bookEdit/css/editMode.css#L1)):_
Ah! Took me awhile too. At the top of editMode.less it says:
@import "../sourceBubbles/sourceBubbles.less";
and I changed THAT file.

---

_[src/BloomBrowserUI/bookEdit/css/editMode.css, line 9 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/876#-K3MIQCdzb_QQJ9G82xq:-K3_uPuEco7EvF7-iGNI:-111641980) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/61ce6001a9e9e0d1301d12f177f1de2f1059e8a0/src/BloomBrowserUI/bookEdit/css/editMode.css#L9)):_
replied to in the sourceBubbles.less version

---

_[src/BloomBrowserUI/bookEdit/sourceBubbles/bloomSourceBubbles.js, line 319 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/876#-K3MJ6qEpvkznOtE4pGS:-K3_xc5WZk0NFr6uazoS:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/61ce6001a9e9e0d1301d12f177f1de2f1059e8a0/src/BloomBrowserUI/bookEdit/sourceBubbles/bloomSourceBubbles.js#L319)):_
Done.

---

_[src/BloomBrowserUI/bookEdit/sourceBubbles/sourceBubbles.less, line 18 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/876#-K3MJSa8paMQz9GzIkyq:-K3_u_70HMK21GUytCIN:2041478918) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/61ce6001a9e9e0d1301d12f177f1de2f1059e8a0/src/BloomBrowserUI/bookEdit/sourceBubbles/sourceBubbles.less#L18)):_
Not really sure, but I think sourceBubbles.css AND editMode.css are both trying to apply and... I really don't know why it was necessary. But somehow it works with them there and it didn't without them. Sorry. That's rather unsatisfying. Also, apparently the comments in the .less file don't survive the import process into the editMode file. :(

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/876#-:-K3_xf5Fy7n5hi9JARiz:140264554)_

**Comment by JohnThomson** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/876)_

**Pull request merged**
