### PR TITLE
BL-6183 Color-blindness accessibility check

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2675)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Worth a review, but getting some out-of-memory problems we may need to do something about before merging.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2675)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx, line 25 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2675#-LJzd6fp42y18qwKS_8D:-LJzd6fp42y18qwKS_8E:brxp86a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a8e5fd4299e5f8bf4ce1215ee03e8ffaa6ef6d2/src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx#L25)):*
> ```XML
>         super({}, state);
>         this.state = { kindOfColorBlindness: "redGreen" };
>         BloomApi.get("accessibilityCheck/kindOfColorBlindness", result => {
> ```

Does this belong in componentDidMount?
___
*[src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx, line 107 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2675#-LJzdioT1QNF7pRKiWue:-LJzdioT1QNF7pRKiWuf:b-5l4d2g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a8e5fd4299e5f8bf4ce1215ee03e8ffaa6ef6d2/src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx#L107)):*
> ```XML
>             "accessibilityCheck/kindOfColorBlindness",
>             mode,
>             { headers: { "Content-Type": "application/json" } }
> ```

Isn't json the default content type? I.e. can you just call postData?
___
*[src/BloomExe/web/controllers/AccessibilityCheckApi.cs, line 148 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2675#-LJzcd4b5m8RQ8_wugcy:-LJzcd4b5m8RQ8_wugcz:bli4jbi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a8e5fd4299e5f8bf4ce1215ee03e8ffaa6ef6d2/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L148)):*
> ```
> differnt
> ```
different

**Review by andrew-polk — COMMENTED** [review]
Mostly looks good with a few minor comments.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2675#-:-LJzfFT_5jmqQaCraRHM:b-dsvzza)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2675)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx, line 10 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2675#-LJzgrEWBIgDZPeqT2_2:-LJzgrEWBIgDZPeqT2_3:b3gfl9s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a8e5fd4299e5f8bf4ce1215ee03e8ffaa6ef6d2/src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx#L10)):*
> ```
> import { deuteranopia, tritanopia, achromatopsia } from "color-blind";
> ```
This file is not included in the PR.

**Review by hatton — APPROVED** [review]
cool!

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2675#-:-LJziA0448JnMSMdMePR:b-7s4s8d)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx, line 153 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2675#-LJzh8A41iHUOoV6oqNh:-LJzh8A41iHUOoV6oqNi:b-afli9i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a8e5fd4299e5f8bf4ce1215ee03e8ffaa6ef6d2/src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx#L153)):*
> ```XML
>     }
> 
>     private static removeCbMarkup() {
> ```

If you have to make edits for Andrew anyhow, then, in method names, it's great if we can avoid non-standard abbreviations like Cb :-)  (i.e. these are ok: iso, id, os )

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2675)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx, line 183 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2675#-LK2WJKS4HLUonwOze-W:-LK2WJKT352q1o76Y-ZX:bks09q6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/59f1e6cc326a1a96a090a366ad2ede7490292d6d/src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx#L183)):*
> ```XML
>             // We could add an event listener for "loaded", but then we have to worry about
>             // removing it again...just waiting a bit is simpler.
>             window.setTimeout(() => this.makeCbOverlay(img), 100);
> ```

What are the chances of a situation where an image never loads? Should we have a timeout?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2675)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @andrew-polk, @JohnThomson, and @hatton)

___
*[src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx, line 10 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2675#-LJzgrEWBIgDZPeqT2_2:-LK2VC769m2Jww8Bmglp:b-x5glqf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a8e5fd4299e5f8bf4ce1215ee03e8ffaa6ef6d2/src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx#L10)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> import { deuteranopia, tritanopia, achromatopsia } from "color-blind";
> ```
This file is not included in the PR.
</blockquote></details>

It's an NPM module, and the change includes what I think is needed to make npm or yarn pull it in.
___
*[src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx, line 25 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2675#-LJzd6fp42y18qwKS_8D:-LK2W-Mo0frTi1pLJYn3:byx688c) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a8e5fd4299e5f8bf4ce1215ee03e8ffaa6ef6d2/src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx#L25)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Does this belong in componentDidMount?
</blockquote></details>

I suppose you're right. It's not obvious why, but https://reactjs.org/docs/faq-ajax.html seems like a fairly official recommendation to do it that way. We have similar code in the constructors for androidPublishUI and epubPublishUI (at least) that probably should be fixed, then. I fixed this one at least.
___
*[src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx, line 107 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2675#-LJzdioT1QNF7pRKiWue:-LK2VQ9r7Ad4_Gs1KwF3:bws4lvl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a8e5fd4299e5f8bf4ce1215ee03e8ffaa6ef6d2/src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx#L107)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Isn't json the default content type? I.e. can you just call postData?
</blockquote></details>

I tried it that way, and C# complained that there was no json data, so I guess the default is something like plain text.
___
*[src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx, line 153 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2675#-LJzh8A41iHUOoV6oqNh:-LK2axv_3F_IM9XIVgWB:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a8e5fd4299e5f8bf4ce1215ee03e8ffaa6ef6d2/src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx#L153)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

If you have to make edits for Andrew anyhow, then, in method names, it's great if we can avoid non-standard abbreviations like Cb :-)  (i.e. these are ok: iso, id, os )
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx, line 183 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2675#-LK2WJKS4HLUonwOze-W:-LK2ayJO1c8fHfYsjz6A:b-mud5cv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/59f1e6cc326a1a96a090a366ad2ede7490292d6d/src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx#L183)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What are the chances of a situation where an image never loads? Should we have a timeout?
</blockquote></details>

Seems fairly harmless to me to keep trying. I suppose it burns a few cycles, but how would we guess the longest time loading might take? If this isn't good enough I'd be more inclined to go to listening for "loaded". But I'm wondering whether there could be any sort of race condition where loading completes between when we check whether it is loaded and when we add the event handler.
___
*[src/BloomExe/web/controllers/AccessibilityCheckApi.cs, line 148 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2675#-LJzcd4b5m8RQ8_wugcy:-LK2bk8-2d20_kc5KhKE:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a8e5fd4299e5f8bf4ce1215ee03e8ffaa6ef6d2/src/BloomExe/web/controllers/AccessibilityCheckApi.cs#L148)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> differnt
> ```
different
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2675)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx, line 10 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2675#-LJzgrEWBIgDZPeqT2_2:-LK2cCpI8EbNqb4YbgLf:b-rlloai) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a8e5fd4299e5f8bf4ce1215ee03e8ffaa6ef6d2/src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx#L10)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's an NPM module, and the change includes what I think is needed to make npm or yarn pull it in.
</blockquote></details>

Ok, sorry. I tried to run it myself and got an error here. I didn't realize this was from npm, and I must not have run npm install.

**Pull request merged**
