### PR TITLE
Persist music settings on front cover (BL-5904)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359)

### CODE REVIEW

**Comment by hatton** [comment]
Reviewed 4 of 7 files at r1.
Review status: 4 of 7 files reviewed at latest revision, all discussions resolved.

---

*[src/BloomExe/Book/BookData.cs, line 210 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LAyz4qUCM9JJ1xQFpBc:-LAyz4qUCM9JJ1xQFpBd:b-s5dfx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ccfe1dadd8987703275129eb5898804752d7e65/src/BloomExe/Book/BookData.cs#L210)):*
> ```Smalltalk
> 			UpdateCredits(info);
> 		}
> ```

We all agree this is the most complicated class to wade through... so maybe we should expand the normal "comments on all public methods" to include private methods, in this class?

Also, in addition to saying what this does, This might be as good a place as any to explain what this whole kDataXMatterPage thing is about (I think that constant obscures the code rather than helps, but I think that's must be personal preference some I'm not asking for a change there). Would help our future selves to give the example of the frontCover needing attributes to remember what music to play.

---

*[src/BloomExe/Book/BookData.cs, line 211 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LAyz6p04A-_NFz8U83K:-LAyz6p04A-_NFz8U83L:b-u5507q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ccfe1dadd8987703275129eb5898804752d7e65/src/BloomExe/Book/BookData.cs#L211)):*
> ```Smalltalk
> 		}
> 
> 		private void UpdateXmatterDataAttributeSetInDataDiv(KeyValuePair<string, ISet<KeyValuePair<string, string>>> attributeSet)
> ```

Another thing that could help might be if we get these methods as descriptive as possible. Like, maybe in this case, "PushXmatterPageAttributesIntoDataDiv". 

---

*[src/BloomExe/Book/BookData.cs, line 216 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LAyzw4hE6-WsxXInhUe:-LAyzw4hE6-WsxXInhUf:bopfkbf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ccfe1dadd8987703275129eb5898804752d7e65/src/BloomExe/Book/BookData.cs#L216)):*
> ```Smalltalk
> 			if (dataDivElementToUpdate == null)
> 				dataDivElementToUpdate = AddDataDivElement(kDataXmatterPage, attributeSet.Key);
> 			else
> ```

Would this code be simpler if you just delete any matching element and then call AddDataDivElement?

---

*[src/BloomExe/Book/BookData.cs, line 230 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LAz-I6l9PHZ-PT76qM_:-LAz-I6l9PHZ-PT76qMa:brlbjib) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ccfe1dadd8987703275129eb5898804752d7e65/src/BloomExe/Book/BookData.cs#L230)):*
> ```Smalltalk
> 				dataDivElementToUpdate.SetAttribute(attributeKvp.Key, attributeKvp.Value);
> 
> 			_dataset.UpdateXmatterPageDataAttributeSet(attributeSet.Key, attributeSet.Value);
> ```

Afternoon here, but I was tracking this function until this line... I don't know what it is about. Could you put a comment on it?

---

*[src/BloomExe/Book/BookData.cs, line 488 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LAz3paS4FxIDb_46c-9:-LAz3paS4FxIDb_46c-A:bhicfbp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ccfe1dadd8987703275129eb5898804752d7e65/src/BloomExe/Book/BookData.cs#L488)):*
> ```Smalltalk
> 		}
> 
> 		public void AddDataDivBookVariable(string key, string lang, string form)
> ```

Given the new method below, a good name for this would be ``AddDataDivElementContainingBookVariable()``

---

*[src/BloomExe/Book/BookData.cs, line 1098 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LAz49aG15xyDsysxs_b:-LAz49aG15xyDsysxs_c:bifhvcy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ccfe1dadd8987703275129eb5898804752d7e65/src/BloomExe/Book/BookData.cs#L1098)):*
> ```Smalltalk
> 		}
> 
> 		public string GetXmatterPageDataAttributeValue(string key, string attributeName)
> ```

wants method comment

---

*[src/BloomExe/Book/DataSet.cs, line 76 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LAz4BuK8heUbvhsHhVk:-LAz4BuK8heUbvhsHhVl:bifhvcy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ccfe1dadd8987703275129eb5898804752d7e65/src/BloomExe/Book/DataSet.cs#L76)):*
> ```Smalltalk
> 		}
> 
> 		public void UpdateXmatterPageDataAttributeSet(string key, ISet<KeyValuePair<string, string>> xmatterPageDataAttributeSet)
> ```

wants method comment

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359)*

**Comment by andrew-polk** [comment]
Review status: 4 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/BloomExe/Book/BookData.cs, line 210 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LAyz4qUCM9JJ1xQFpBc:-LB2_9DwE3CmoTHPSg2l:bwl5shh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ccfe1dadd8987703275129eb5898804752d7e65/src/BloomExe/Book/BookData.cs#L210)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

We all agree this is the most complicated class to wade through... so maybe we should expand the normal "comments on all public methods" to include private methods, in this class?

Also, in addition to saying what this does, This might be as good a place as any to explain what this whole kDataXMatterPage thing is about (I think that constant obscures the code rather than helps, but I think that's must be personal preference some I'm not asking for a change there). Would help our future selves to give the example of the frontCover needing attributes to remember what music to play.
</blockquote></details>

Decided to add the fullest explanation on the constant itself since that is used in all these various methods (I think).

---

*[src/BloomExe/Book/BookData.cs, line 211 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LAyz6p04A-_NFz8U83K:-LB2asgq2DfLJcceiZfx:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ccfe1dadd8987703275129eb5898804752d7e65/src/BloomExe/Book/BookData.cs#L211)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Another thing that could help might be if we get these methods as descriptive as possible. Like, maybe in this case, "PushXmatterPageAttributesIntoDataDiv". 
</blockquote></details>

Done.

---

*[src/BloomExe/Book/BookData.cs, line 216 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LAyzw4hE6-WsxXInhUe:-LB2aPIRDGyenHCGVp0r:bra6ru2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ccfe1dadd8987703275129eb5898804752d7e65/src/BloomExe/Book/BookData.cs#L216)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Would this code be simpler if you just delete any matching element and then call AddDataDivElement?
</blockquote></details>

Yes; thanks. Done.

---

*[src/BloomExe/Book/BookData.cs, line 230 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LAz-I6l9PHZ-PT76qM_:-LB2Uu2p7uFP8kdyb_lW:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ccfe1dadd8987703275129eb5898804752d7e65/src/BloomExe/Book/BookData.cs#L230)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Afternoon here, but I was tracking this function until this line... I don't know what it is about. Could you put a comment on it?
</blockquote></details>

Done.

---

*[src/BloomExe/Book/BookData.cs, line 488 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LAz3paS4FxIDb_46c-9:-LB2TzysEjF7NsTaAgMf:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ccfe1dadd8987703275129eb5898804752d7e65/src/BloomExe/Book/BookData.cs#L488)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Given the new method below, a good name for this would be ``AddDataDivElementContainingBookVariable()``
</blockquote></details>

Done.

---

*[src/BloomExe/Book/BookData.cs, line 1098 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LAz49aG15xyDsysxs_b:-LB2Tm5VBVfEJjOk-tBH:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ccfe1dadd8987703275129eb5898804752d7e65/src/BloomExe/Book/BookData.cs#L1098)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

wants method comment
</blockquote></details>

Done.

---

*[src/BloomExe/Book/DataSet.cs, line 76 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LAz4BuK8heUbvhsHhVk:-LB2T95Y4FxDrPS9qho4:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ccfe1dadd8987703275129eb5898804752d7e65/src/BloomExe/Book/DataSet.cs#L76)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

wants method comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359)*

**Comment by hatton** [comment]
Review status: 3 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LB2qd4zBAIYH9PiMjDm:-LB2qd4zBAIYH9PiMjDn:b-cenzd7) (no related file):*
OK, looking good. I added a bunch more clarifying suggestions, for which I feel guilty. But heh, if it helps, it took me over an 64 minutes to come up with them, and will only take 5 minutes to implement them. And again, I'm giving it this level of attention only because this is area is historically thorny and any *future* mistakes we might make by misunderstanding are so very expensive.

---

*[src/BloomExe/Book/BookData.cs, line 230 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LAz-I6l9PHZ-PT76qM_:-LB2ehTNAcUgmO51riQf:b-gmuo54) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ccfe1dadd8987703275129eb5898804752d7e65/src/BloomExe/Book/BookData.cs#L230)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK I see clearly what you're doing, and I see that this exact side effect is what methods like UpdateSingleTextVariableInDataDiv() do already.  So no foul here, but I suspect this side-effect of putting things in this "dataset", which probably I wrote originally, and which isn't going to be addressed in this PR, might be the reason this code is hard. 

The comment for DataSet described it as a cache for document values. Maybe "BookDataCache" would be a better name than "dataset" which is just one fraction better than "thingy"? Anyhow, nothing to do here unless you are inspired.

---

*[src/BloomExe/Book/BookData.cs, line 717 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LB2psmO6Yng7oCbbr8S:-LB2psmO6Yng7oCbbr8T:bgl4ar6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5dad76d798b52d7ff8d97803271a508a82bac29a/src/BloomExe/Book/BookData.cs#L717)):*
> ```Smalltalk
> 						{
> 							GatherXmatterPageDataAttributeSets(data, node, key);
> 							continue;
> ```

Please add comment here before the ``continue``, 'cuase I had to do some actual thinking to figure this out (oh my!)

// This element has a data-xmatter-page attribute. So it is a bloom-page div. And currently a bloom-page cannot also be an element waiting to be filled with data-collection, so we're done here.

---

*[src/BloomExe/Book/BookData.cs, line 807 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LB2mW1VC_m2sPuY6K1K:-LB2mW1VC_m2sPuY6K1L:b-3kjlxc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5dad76d798b52d7ff8d97803271a508a82bac29a/src/BloomExe/Book/BookData.cs#L807)):*
> ```Smalltalk
> 		}
> 
> 		private void GatherXmatterPageDataAttributeSets(DataSet data, XmlElement node, string key)
> ```

Possible comment:
    // Xmatter pages sometimes have data-* attributes that can be changed by the user. For example, setting background music. This method reads those attributes into the given dataset under the xmatterPageKey.

data --> dataset
node --> xmatterPageElement
key --> xmatterPageKey

As I commented in a another method, I think it would be clearer if key was read here rather then coming in as a parameter. Else I had to look at the caller to infer that we wouldn't call this if it didn't have that key.

---

*[src/BloomExe/Book/BookData.cs, line 809 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LB2nl56EWabnwQG1asU:-LB2nl56EWabnwQG1asV:b96bc2c) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5dad76d798b52d7ff8d97803271a508a82bac29a/src/BloomExe/Book/BookData.cs#L809)):*
> ```Smalltalk
> 		private void GatherXmatterPageDataAttributeSets(DataSet data, XmlElement node, string key)
> 		{
> 			if (data.XmatterPageDataAttributeSets.ContainsKey(key))
> ```

This ``if`` clause makes the contract of this method more complicated. It means we don't always do what the method name says.

A clearer post-condition would be "After this method, the given dataset.XMatterPageDataAttrubuteSets[key] contains exactly the set of data-* attributes of the xmatterPageElement".

---

*[src/BloomExe/Book/BookData.cs, line 946 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LB2kLT78u3su2rEmoSm:-LB2kLT78u3su2rEmoSn:bb7o6w4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5dad76d798b52d7ff8d97803271a508a82bac29a/src/BloomExe/Book/BookData.cs#L946)):*
> ```Smalltalk
> 		}
> 
> 		private void UpdateXmatterPageDataAttributeSets(DataSet data, XmlElement node, string key)
> ```

key --> xmatterPageKey
node --> pageElement
data --> dataset (not that it helps much (see my other comment)!)

Having key/xmatterPageKey as a parameter is a bit confusing because it has to match an existing attribute on the pageElement. Is that true? I.e., could this just as well say

     var key = pageElement.GetAttribute("data-xmatter-page")?

I think that would be clearer than having it be a parameter.

But if there was a big concern for speed, then an Assert:

    Debug.Assert(key == pageElement.GetAttribute("data-xmatter-page"));

would at least make it crystal clear.

---

*[src/BloomExe/Book/BookData.cs, line 1117 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LB2mFd70ftD2aq_rHtj:-LB2mFd70ftD2aq_rHtk:b-2xwtdt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5dad76d798b52d7ff8d97803271a508a82bac29a/src/BloomExe/Book/BookData.cs#L1117)):*
> ```Smalltalk
> 		///		GetXmatterPageDataAttributeValue("frontCover", "data-backgroundaudio")
> 		/// </summary>
> 		public string GetXmatterPageDataAttributeValue(string key, string attributeName)
> ```

key --> xmatterPageKey

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359)*

**Comment by andrew-polk** [comment]
Review status: 3 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/BloomExe/Book/BookData.cs, line 717 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LB2psmO6Yng7oCbbr8S:-LB6DUSu0CKv0diYRrW8:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5dad76d798b52d7ff8d97803271a508a82bac29a/src/BloomExe/Book/BookData.cs#L717)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Please add comment here before the ``continue``, 'cuase I had to do some actual thinking to figure this out (oh my!)

// This element has a data-xmatter-page attribute. So it is a bloom-page div. And currently a bloom-page cannot also be an element waiting to be filled with data-collection, so we're done here.
</blockquote></details>

Done.

---

*[src/BloomExe/Book/BookData.cs, line 807 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LB2mW1VC_m2sPuY6K1K:-LB6N5UwAtkGalbif77H:bxiipec) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5dad76d798b52d7ff8d97803271a508a82bac29a/src/BloomExe/Book/BookData.cs#L807)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Possible comment:
    // Xmatter pages sometimes have data-* attributes that can be changed by the user. For example, setting background music. This method reads those attributes into the given dataset under the xmatterPageKey.

data --> dataset
node --> xmatterPageElement
key --> xmatterPageKey

As I commented in a another method, I think it would be clearer if key was read here rather then coming in as a parameter. Else I had to look at the caller to infer that we wouldn't call this if it didn't have that key.
</blockquote></details>

Actually, I think one of the things which makes this area of the code most confusing (at least to me) is that the node here (and in the caller) is not necessarily the xmatterPageElement. It might be the div in the data div.

That's probably why the if exists just below this.

Happy to discuss how to improve things.

---

*[src/BloomExe/Book/BookData.cs, line 946 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LB2kLT78u3su2rEmoSm:-LB6ORnK-UaXBnlN2nag:b-6rzta4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5dad76d798b52d7ff8d97803271a508a82bac29a/src/BloomExe/Book/BookData.cs#L946)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

key --> xmatterPageKey
node --> pageElement
data --> dataset (not that it helps much (see my other comment)!)

Having key/xmatterPageKey as a parameter is a bit confusing because it has to match an existing attribute on the pageElement. Is that true? I.e., could this just as well say

     var key = pageElement.GetAttribute("data-xmatter-page")?

I think that would be clearer than having it be a parameter.

But if there was a big concern for speed, then an Assert:

    Debug.Assert(key == pageElement.GetAttribute("data-xmatter-page"));

would at least make it crystal clear.
</blockquote></details>

Done except node--> pageElement (see note above).

---

*[src/BloomExe/Book/BookData.cs, line 1117 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LB2mFd70ftD2aq_rHtj:-LB6DSwsEu7FqEvlGV2I:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5dad76d798b52d7ff8d97803271a508a82bac29a/src/BloomExe/Book/BookData.cs#L1117)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

key --> xmatterPageKey
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359)*

**Comment by andrew-polk** [comment]
Review status: 3 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LB2qd4zBAIYH9PiMjDm:-LB6P7VjAg4hCRcXoykg:bc7b6i) (no related file):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

OK, looking good. I added a bunch more clarifying suggestions, for which I feel guilty. But heh, if it helps, it took me over an 64 minutes to come up with them, and will only take 5 minutes to implement them. And again, I'm giving it this level of attention only because this is area is historically thorny and any *future* mistakes we might make by misunderstanding are so very expensive.
</blockquote></details>

Glad for your work! Thanks. Sorry you had to spend so much time here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359)*

**Comment by andrew-polk** [comment]
Review status: 3 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Book/BookData.cs, line 807 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LB2mW1VC_m2sPuY6K1K:-LB7BoW3Ct1hG3DTeaHU:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5dad76d798b52d7ff8d97803271a508a82bac29a/src/BloomExe/Book/BookData.cs#L807)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I see. How about add a sentence to that effect in the comment. "Node" can still be "element" or "div".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359)*

**Comment by hatton** [comment]
Review status: 3 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/BookData.cs, line 809 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LB2nl56EWabnwQG1asU:-LB7g5K1290LPUN3_i1o:b-3ct1ck) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5dad76d798b52d7ff8d97803271a508a82bac29a/src/BloomExe/Book/BookData.cs#L809)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This ``if`` clause makes the contract of this method more complicated. It means we don't always do what the method name says.

A clearer post-condition would be "After this method, the given dataset.XMatterPageDataAttrubuteSets[key] contains exactly the set of data-* attributes of the xmatterPageElement".
</blockquote></details>

What say you?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359)*

**Comment by andrew-polk** [comment]
*[src/BloomExe/Book/BookData.cs, line 809 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LB2nl56EWabnwQG1asU:-LB7iM9u2aV14xkUTwtE:b-eh21sh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5dad76d798b52d7ff8d97803271a508a82bac29a/src/BloomExe/Book/BookData.cs#L809)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

What say you?
</blockquote></details>

Sorry; done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359)*

**Comment by andrew-polk** [comment]
Review status: 3 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Book/BookData.cs, line 815 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LB7kqQX-bIZ82I63C-_:-LB7n_tNDKIZszgEyGbY:b-i0fi8v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d2d20eb644a77b7832bef5e39e0f04bc9223dcc5/src/BloomExe/Book/BookData.cs#L815)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Sorry, something's still not right with the name... there is I think just one DataSet here, not plural?  How about ``GatherXmatterPageAttributesIntoDataSet()``?
</blockquote></details>

Set here was referring to the fact that this is a set of attributes. But it shouldn't have been plural. Modified.

---

*[src/BloomExe/Book/BookData.cs, line 825 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359#-LB7kc-c2C07SaiuoZHe:-LB7mlmBDPVhXK2DFOH_:byxej5m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d2d20eb644a77b7832bef5e39e0f04bc9223dcc5/src/BloomExe/Book/BookData.cs#L825)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

The docs of iset say that Add() should just return "false" if it's already there. I think as a caller I would expect this method to replace what is there if I call it with new data.
</blockquote></details>

dataSet.XmatterPageDataAttributeSets is a dictionary. So this will actually throw an ArgumentException if the key already exists in the dictionary.
Now that I realize that, I understand what the if was there which we just moved out.

Ok, so I've made it replace if it exists.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359)*

**Pull request merged**
