### PR TITLE
BL-5819 Add Paste Image Credits to MXB Pamphlet xmatter

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2568)

### CODE REVIEW

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2568)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Review by gmartin7 — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2568#-:-LGzwROy3UN0d6ExA_Vc:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by hatton** [comment]
@JohnThomson please merge to 4.2 beta so they can use it. Thanks.

**Comment by JohnThomson** [comment]
Cherry-picked to 4.2

**Pull request merged**
