### PR TITLE
BL-4938 Don't complain of missing images in book folder

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1844)

### CODE REVIEW

**Comment by hatton** [comment]
What does the UI do when the file isn't found?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1844#-:-KtY1PD1wjUsk3zBskPw:b-1xhfh9)*

**Comment by JohnThomson** [comment]
Standard browser thing..."This picture, AOR_CMB0577.png, is missing or was loading too slowly." (Probably that message is not localized :-<). (This is unchanged from before.)
That's assuming, of course, that there's no reason to look for a picture in the book folder other than to display it.
Now, that's true when we have an img element, on content pages. Your question prompted me to test what happens in xmatter, where we use background images. In that situation, you just get a blank box...not even a flower :-). Should we fix that as part of this issue, make a new one, or is it not worth trying to fix?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1844#-:-KtYPmJDpUcvT88qjDW2:b-7u2cmi)*

**Comment by hatton** [comment]
I think that too is ok. "where's my picture? Hmm... will have to chose it again". Now what I do wish for is just one message that we could show to someone when they open a book with missing pictures; something aimed at the incomplete dropbox scenario.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1844#-:-KtZ6Tc7ofoqtuskAXGV:bebgxz6)*

**Comment by JohnThomson** [comment]
It's certainly possible to scan for missing images (other than branding) when opening a book and put up some sort of message. Do you want to make that part of this issue?

**Comment by hatton** [comment]
>  Do you want to make that part of this issue?

No, sorry, let's put that off to 4.1. Now BL-4989.

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1844#-:-Ktv8jU4etD4rnpjKbhz:bnfp4nl)*

**Pull request merged**
