### PR TITLE
A more complete implementation of Pause in playback (

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4686)

### CODE REVIEW

**Review by jsubloom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4686)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[DistFiles/localization/en/Bloom.xlf, line 981 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4686#-Mi7Sg524KsjFgBWM0E3:-Mi7Sg524KsjFgBWM0E4:bxmaqmy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a934650c29ea29e2a0722a5279e5f77e54b62bb9/DistFiles/localization/en/Bloom.xlf#L981)):*
> ```XML
>         <note>ID: Common.Optional</note>
>       </trans-unit>
>       <trans-unit id="Common.Pause">
> ```

I guess based on what I learned yesterday, dynamic should be true.
___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 713 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4686#-Mi7TD4TAEPo_ztfoW_O:-Mi7TD4TAEPo_ztfoW_P:b-hb4x5c) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a934650c29ea29e2a0722a5279e5f77e54b62bb9/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L713)):*
> ```XML
> 
>     // In case play is currently paused, end that state, typically because we are doing another command.
>     private abortPause(): void {
> ```

Food for thought: Would this name make more sense as reset[Something]?
It seems like we call this even if it is not necessarily paused.
___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 1236 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4686#-Mi7UevHE-KNkpHBy7d4:-Mi7UevI3_B02PJhWA_W:b-gqedrf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a934650c29ea29e2a0722a5279e5f77e54b62bb9/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L1236)):*
> ```
>             // Review: another option is to say that if we don't find an audio-sentence parent, return the
>             // currentHighlight thing we started with.
> ```
I'm not a huge fan of what this is currently doing, and I guess I'd find the return currentHighlight if not found option more palatable.
___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 1311 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4686#-Mi7W7pk9jyK6TNLJtTS:-Mi7W7pk9jyK6TNLJtTT:bk0tr3u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a934650c29ea29e2a0722a5279e5f77e54b62bb9/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L1311)):*
> ```XML
>         }
> 
>         const oldElementsToPlay = this.elementsToPlayConsecutivelyStack;
> ```

TODO: I need to continue reviewing from here

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4686)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @sujeffreyl)

___
*[DistFiles/localization/en/Bloom.xlf, line 981 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4686#-Mi7Sg524KsjFgBWM0E3:-Mi7_XO20hhFcTtP4VFU:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a934650c29ea29e2a0722a5279e5f77e54b62bb9/DistFiles/localization/en/Bloom.xlf#L981)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I guess based on what I learned yesterday, dynamic should be true.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 713 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4686#-Mi7TD4TAEPo_ztfoW_O:-Mi7_7QXD0ESC-UKtEPR:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a934650c29ea29e2a0722a5279e5f77e54b62bb9/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L713)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Food for thought: Would this name make more sense as reset[Something]?
It seems like we call this even if it is not necessarily paused.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 1236 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4686#-Mi7UevHE-KNkpHBy7d4:-Mi7_7uuBLLdfrzpTMOO:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a934650c29ea29e2a0722a5279e5f77e54b62bb9/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L1236)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
>             // Review: another option is to say that if we don't find an audio-sentence parent, return the
>             // currentHighlight thing we started with.
> ```
I'm not a huge fan of what this is currently doing, and I guess I'd find the return currentHighlight if not found option more palatable.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 1311 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4686#-Mi7W7pk9jyK6TNLJtTS:-Mi7Woly9fOa11iLQYod:bl8gcbm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a934650c29ea29e2a0722a5279e5f77e54b62bb9/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L1311)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

TODO: I need to continue reviewing from here
</blockquote></details>

Git doesn't make it very clear what happened. Think of it like this: playCurrentInternalAsync is, as far as I remember, unchanged except that a big chunk was pulled out into a new function setupTimings. What remained was copied into the tail end of togglePlayCurrentAsync and reordered a bit so that certain things only happen if we're not resuming.

**Review by jsubloom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4686)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 1311 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4686#-Mi7W7pk9jyK6TNLJtTS:-MiMQH6aAwZ_FCo3FV0d:bbderuk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a934650c29ea29e2a0722a5279e5f77e54b62bb9/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L1311)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Git doesn't make it very clear what happened. Think of it like this: playCurrentInternalAsync is, as far as I remember, unchanged except that a big chunk was pulled out into a new function setupTimings. What remained was copied into the tail end of togglePlayCurrentAsync and reordered a bit so that certain things only happen if we're not resuming.
</blockquote></details>

Thanks, that comment helped a ton. Finished going through it
___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 3769 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4686#-MiMPxMrCCrUGflNvq6G:-MiMPxMrCCrUGflNvq6H:b31upm8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/466601405c7b5e4f7551bdb0a9174241874fe7d9/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L3769)):*
> ```XML
>             forceRedisplay: true
>         });
>         this.setStatus("split", Status.Disabled); // Disable it immediately (not asynchronously!) so that the button stops registering clicks
> ```

1) This comment says it is disabled immediately (not asynchronously), but now this is no longer the case.
2) I was wondering in general just what the right order is for these statements and documenting any kind of rationale for why the await should happen before the other things, if applicable

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4686)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 3769 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4686#-MiMPxMrCCrUGflNvq6G:-MiMyDYe5ONPVwPWI2zm:bhbqykf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/466601405c7b5e4f7551bdb0a9174241874fe7d9/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L3769)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

1) This comment says it is disabled immediately (not asynchronously), but now this is no longer the case.
2) I was wondering in general just what the right order is for these statements and documenting any kind of rationale for why the await should happen before the other things, if applicable
</blockquote></details>

I think I was just adding something that should happen before the main split work at the start of the method. All three things should be quite fast, but disabling the button is probably the most urgent and important. I moved it first.

**Review by jsubloom — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4686)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by jsubloom — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4686#-:-MiRVStn1AO1cXVM_A0H:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
