### PR TITLE
Try again to restrict allTitles to those uploaded  (BL-11577)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5456)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
See comments in Zulip

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5456#-:-NDofH0Y2Oajh3RFq6AI:b-5b2e6h)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @andrew-polk)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5456)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/WebLibraryIntegration/BloomS3Client.cs` line 212 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5456#-NE1deEYBgj0t3wiqk_r:-NE1deEYBgj0t3wiqk_s:b4bota) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e5484c01e854f1326a2cafb2c3e2785f3977896a/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L212)):*
> ```Smalltalk
> 		public void UploadBook(string storageKeyOfBookFolder, string pathToBloomBookDirectory, IProgress progress,
> 			string pdfToInclude, ISet<string> audioFilesToInclude, IEnumerable<string> videoFilesToInclude,
> 			string[] languagesToInclude, string metadataLang1Code, string metadataLang2Code, string lang1Code)
> ```

I don't understand why we need to pass lang1 in.
It seems like either:
1. lang1 should always be in languagesToInclude
2. if lang1 isn't in languagesToInclude, we don't need it in allTitles

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5456)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/WebLibraryIntegration/BloomS3Client.cs` line 212 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5456#-NE1deEYBgj0t3wiqk_r:-NE6JF6n5RQahcZ9_Zdl:baizmmm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e5484c01e854f1326a2cafb2c3e2785f3977896a/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L212)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't understand why we need to pass lang1 in.
It seems like either:
1. lang1 should always be in languagesToInclude
2. if lang1 isn't in languagesToInclude, we don't need it in allTitles
</blockquote></details>

I think at some point in the past we decided that "languagesToInclude" would be the list that the user has checked. That doesn't include language1, I think because it is always automatically included.
We could try to change that, but then we risk breaking something else...

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5456)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/WebLibraryIntegration/BloomS3Client.cs` line 212 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5456#-NE1deEYBgj0t3wiqk_r:-NE7CHL89fBz-Ym08O0J:b-emgikx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e5484c01e854f1326a2cafb2c3e2785f3977896a/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L212)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think at some point in the past we decided that "languagesToInclude" would be the list that the user has checked. That doesn't include language1, I think because it is always automatically included.
We could try to change that, but then we risk breaking something else...
</blockquote></details>

Sorry; I'm sure I'm just being dense, but I still don't understand.

If lang1 isn't guaranteed (or even possible) to be in languagesToInclude, why aren't we getting other errors like lang1 data being removed from the book?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5456)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/WebLibraryIntegration/BloomS3Client.cs` line 212 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5456#-NE1deEYBgj0t3wiqk_r:-NE7Vc-x-GzJy6OwbTLt:b-p8avx0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e5484c01e854f1326a2cafb2c3e2785f3977896a/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L212)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; I'm sure I'm just being dense, but I still don't understand.

If lang1 isn't guaranteed (or even possible) to be in languagesToInclude, why aren't we getting other errors like lang1 data being removed from the book?
</blockquote></details>

I didn't research that. In fact, I initially wrote the code assuming it would be included. But I noticed in testing that L1 wasn't in the list. I think it would be noticed both by users and our test code if the book's main language was missing, so I presume it was on purpose and something figures out that L1 can never be excluded. But I haven't figured out where that code is.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5456)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/WebLibraryIntegration/BloomS3Client.cs` line 212 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5456#-NE1deEYBgj0t3wiqk_r:-NENP9pa0FjrC2z7GT9Q:bfpua7k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e5484c01e854f1326a2cafb2c3e2785f3977896a/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L212)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I didn't research that. In fact, I initially wrote the code assuming it would be included. But I noticed in testing that L1 wasn't in the list. I think it would be noticed both by users and our test code if the book's main language was missing, so I presume it was on purpose and something figures out that L1 can never be excluded. But I haven't figured out where that code is.
</blockquote></details>

This makes me extremely uncomfortable, and it seems like it warrants further investigation.

I think we are asking for future bugs (or already have them) if languagesToInclude (which I've traced, at least in one place, to `book.BookInfo.PublishSettings.BloomLibrary.TextLangs.IncludedLanguages()`) doesn't include L1.
If the code further on assumes L1 is always published that isn't correct either, now that the user can turn off L1 in the book.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5456)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/WebLibraryIntegration/BloomS3Client.cs` line 212 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5456#-NE1deEYBgj0t3wiqk_r:-NEbPtFC55XySmRX8j7d:b-5d5pc1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e5484c01e854f1326a2cafb2c3e2785f3977896a/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L212)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This makes me extremely uncomfortable, and it seems like it warrants further investigation.

I think we are asking for future bugs (or already have them) if languagesToInclude (which I've traced, at least in one place, to `book.BookInfo.PublishSettings.BloomLibrary.TextLangs.IncludedLanguages()`) doesn't include L1.
If the code further on assumes L1 is always published that isn't correct either, now that the user can turn off L1 in the book.
</blockquote></details>

You're absolutely right. languagesToInclude does have L1 in it (when appropriate) and I have no recollection of what led me to think otherwise. Removed all the L1 changes. Sorry, and thanks for persisting.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5456)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
