### PR TITLE
Improve error reporting for writing image metadata (20240730)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6585)

### CODE REVIEW

**Comment by StephenMcConnel** [comment]
There is a notion page that needs to be published as part of this change.
https://www.notion.so/hattonjohn/Unable-to-change-image-license-9ea173f9781d4a688502e7ec78ec7fbe

**Review by andrew-polk — CHANGES_REQUESTED** [review]
We'll have to do some tricky merging as the .xlf change will need to make it into master.

but... I'm thinking at least some of this may still be helpful in 6.0+.
See https://issues.bloomlibrary.org/youtrack/issue/BL-13637 which occurred in 6.0.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6585#-:-O3Dz2Z13jNTMKkve6Vv:bcyznh5)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 272 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6585#-O3DztoO3wGOiw--3AxL:-O3DztoO3wGOiw--3AxM:b-ghcxqi) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b17e61ff86206795fb1cadcca720f4b1b8004a9c/src/BloomExe/ImageProcessing/ImageUtils.cs#L272)):*
> ```Smalltalk
> 			var msg = string.Format(msgFmt, Path.GetFileName(filePath));
> 			var btnLabel = LocalizationManager.GetString("EditTab.Toolbox.ImageDescriptionTool.MoreInformation",
> 				"For more information:");
> ```

I'm thinking this string doesn't really fit the scenario, especially with the colon at the end.
I think we have a "More info"?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6585)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 272 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6585#-O3DztoO3wGOiw--3AxL:-O3EDcVM-dgjQFBx1q7M:b-x9yut0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b17e61ff86206795fb1cadcca720f4b1b8004a9c/src/BloomExe/ImageProcessing/ImageUtils.cs#L272)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm thinking this string doesn't really fit the scenario, especially with the colon at the end.
I think we have a "More info"?
</blockquote></details>

This string is the shortest and most appropriate one I found.  I was trying to avoid adding another string to translate.  (We don't have a "More info" in any of the .xlf files.)  But if you really don't like the trailing colon, I'm open to suggestion.

**Review by StephenMcConnel — COMMENTED** [review]
I'm willing to handle the merging.  I know it will be a pain.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6585#-:-O3EELTA31VoEPT7c9OI:b-k6xv2m)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6585)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 272 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6585#-O3DztoO3wGOiw--3AxL:-O3EhoAv0LTHZFivKQMJ:b-qbdchg) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b17e61ff86206795fb1cadcca720f4b1b8004a9c/src/BloomExe/ImageProcessing/ImageUtils.cs#L272)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

This string is the shortest and most appropriate one I found.  I was trying to avoid adding another string to translate.  (We don't have a "More info" in any of the .xlf files.)  But if you really don't like the trailing colon, I'm open to suggestion.
</blockquote></details>

At JH's recommendation, I added a new string.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6585)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
