### PR TITLE
BL-9953 Fix origami rule precedence

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4901)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4901)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomBrowserUI/bookEdit/css/origami.less, line 53 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4901#-MsqZubpErxfJUaqsANE:-MsqZubpErxfJUaqsANF:b-asedep) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/80dd3c5696d1e33eb2e3f5d2bad071f3c2e8c80d/src/BloomBrowserUI/bookEdit/css/origami.less#L53)):*
> ```Less
> }
> 
> // BL-9953 Added 'p' so audioRecording rule won't have more precedence.
> ```

But this also makes it mean something different. That might be OK, but if you just want to increase precedence, another option is 

.origami-layout-mode.origami-layout-mode .bloom-editable

This will match exactly the same cases as before, but with one notch more precedence. (Actually I think it's a stronger increase in precedence, since classes are more important that elements.)

If you're sure you only want the paragraph colored, not the whole bloom-editable, I guess the original can stand.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4901)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/css/origami.less, line 53 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4901#-MsqZubpErxfJUaqsANE:-MsqaE-i3lK96NxSR1VC:bty5b0z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/80dd3c5696d1e33eb2e3f5d2bad071f3c2e8c80d/src/BloomBrowserUI/bookEdit/css/origami.less#L53)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

But this also makes it mean something different. That might be OK, but if you just want to increase precedence, another option is 

.origami-layout-mode.origami-layout-mode .bloom-editable

This will match exactly the same cases as before, but with one notch more precedence. (Actually I think it's a stronger increase in precedence, since classes are more important that elements.)

If you're sure you only want the paragraph colored, not the whole bloom-editable, I guess the original can stand.
</blockquote></details>

Yeah, I thought about the fact that I was changing the "target" of the rule, but it's the text in the `.bloom-editable` we're after here anyway (this rule grays it out, if the origami function is active) and the competing rule also "targets" the `p` element, so I figured this was best.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4901)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/css/origami.less, line 53 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4901#-MsqZubpErxfJUaqsANE:-MsqavdbB4QTb1YFU5i2:bv80yhn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/80dd3c5696d1e33eb2e3f5d2bad071f3c2e8c80d/src/BloomBrowserUI/bookEdit/css/origami.less#L53)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Yeah, I thought about the fact that I was changing the "target" of the rule, but it's the text in the `.bloom-editable` we're after here anyway (this rule grays it out, if the origami function is active) and the competing rule also "targets" the `p` element, so I figured this was best.
</blockquote></details>

I've added something to the comment too.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4901)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
