### PR TITLE
Make nicer history message for new book from source (BL-10550)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4929)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4929)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/Book/Book.cs, line 202 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4929#-MuGn9gi-4zNwG8HJKLS:-MuGn9gi-4zNwG8HJKLT:b8ppnle) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/41d9bb9b24d648ec4f35f6fd3e6a793e6b78f9cb/src/BloomExe/Book/Book.cs#L202)):*
> ```Smalltalk
> 							$"Created a new book \"{Storage.Dom.Title}\" from a source book \"{SourceToReportForNextRename}\"");
> 					else
> 						BookHistory.AddEvent(this, BookHistoryEventType.Created,
> ```

Though we are not doing l10n right now, I'm thinking about it... the `(folder=___)` versions are going to be a bit difficult to get translated.  When the book is 1st created, what will cause the folder name to differ from the title?

**Review by hatton — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4929)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @hatton and @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4929)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/Book/Book.cs, line 202 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4929#-MuGn9gi-4zNwG8HJKLS:-MuGp-TSE4-rPakyaq26:b-29lobb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/41d9bb9b24d648ec4f35f6fd3e6a793e6b78f9cb/src/BloomExe/Book/Book.cs#L202)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Though we are not doing l10n right now, I'm thinking about it... the `(folder=___)` versions are going to be a bit difficult to get translated.  When the book is 1st created, what will cause the folder name to differ from the title?
</blockquote></details>

Typically sanitizing file names, e.g., removing parentheses. (I was keeping an approach we presumably approved before when renaming.)

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4929)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @hatton)

___
*[src/BloomExe/Book/Book.cs, line 202 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4929#-MuGn9gi-4zNwG8HJKLS:-MuGqGmc9kc3PRVuCZXf:b8dkmfb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/41d9bb9b24d648ec4f35f6fd3e6a793e6b78f9cb/src/BloomExe/Book/Book.cs#L202)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Typically sanitizing file names, e.g., removing parentheses. (I was keeping an approach we presumably approved before when renaming.)
</blockquote></details>

OK. SO that's not important for the history message, we can remove it.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4929)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @hatton)

___
*[src/BloomExe/Book/Book.cs, line 202 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4929#-MuGn9gi-4zNwG8HJKLS:-MuIRCWs65BjNYbZ-5_1:bb6un1j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/41d9bb9b24d648ec4f35f6fd3e6a793e6b78f9cb/src/BloomExe/Book/Book.cs#L202)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

OK. SO that's not important for the history message, we can remove it.
</blockquote></details>

Done

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4929)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/Book/Book.cs, line 192 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4929#-MuIRuT6-0oPcipNlR7T:-MuIRuT6-0oPcipNlR7U:byi64u5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8a296308f58593f20dfa383e2abe50ccee1a2446/src/BloomExe/Book/Book.cs#L192)):*
> ```Smalltalk
> 						BookHistory.AddEvent(this, BookHistoryEventType.Renamed,
> 							$"Book title changed to \"{Storage.Dom.Title}\"");
> 					else
> ```

Similar to below, this is a pretty complicated message. Here, maybe the folder name actually carries some information, but can we still simplify away this complexity in the message somehow?

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4929)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/Book/Book.cs, line 192 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4929#-MuIRuT6-0oPcipNlR7T:-MuIU4Wt0okxBjk8TUWh:bgeac6y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8a296308f58593f20dfa383e2abe50ccee1a2446/src/BloomExe/Book/Book.cs#L192)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Similar to below, this is a pretty complicated message. Here, maybe the folder name actually carries some information, but can we still simplify away this complexity in the message somehow?
</blockquote></details>

Well for now, let's drop notice of the folder name. This message is about the book title. Extra credit would be that if the folder name changes as a result of an explicit rename (not a title change), then we emit a message just for that.

**Pull request merged**
