### PR TITLE
Individual book history (BL-10072)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5036)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5036)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx, line 230 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5036#-MyhpQsx-HkSZ-kqa4mJ:-MyhpQsx-HkSZ-kqa4mK:b-ghzyrd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/527202e2794d42a4b0276ca63dde6754cb9e1358/src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx#L230)):*
> ```XML
>                         }
>                     `}
>                 >
> ```

Is it time to pull out some of this UI tweaking of tabs to something common? 
We want all the tabs of this style to look the same, generally.
And I also need it for the copyright/license dialog (where I was trying to decide if it was worth it, too... but now we have 3).

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5036)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx, line 230 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5036#-MyhpQsx-HkSZ-kqa4mJ:-Myi4hpU7VxXUA8bW3zz:bts6bpf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/527202e2794d42a4b0276ca63dde6754cb9e1358/src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx#L230)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is it time to pull out some of this UI tweaking of tabs to something common? 
We want all the tabs of this style to look the same, generally.
And I also need it for the copyright/license dialog (where I was trying to decide if it was worth it, too... but now we have 3).
</blockquote></details>

I don't know. I agree it's tempting. OTOH, I looked at the three places so far that we use the Tabs Material UI component. One of them has no Emotion CSS at all, though it has some similar rules in a less file. But:
- one out of three wants the root Tab element to be height:100%; display:flex; flex-direction:column.
- two out of three want react-tabs__tab.react-tabs__tab to be uppercase
- one wants it blue, one white, and one leaves the default color
- one wants a white background, one a kDarkestBackground, and one default
- one wants flex-grow:1
- one sets react-tabs__tab--selected to white color and border, one blue, and one the default.
-  two of the three want a transparent border
- one wants them to be a flex column
-  two want react-tabs__tab-list to have no border
-  one wants react-tabs__tab-panel to have relative position and flex-grow 1
Now, it's just possible it would make things a little simpler to pull out a BloomTabs which deals with putting a parameterized backgroundColor and foregroundColor in the right places. We could probably standardize on uppercase and a transparent border for react-tabs__tab--selected. Maybe it's useful to make props for cssToApplyToLabels, cssToApplyToSelectedLabel,...
But maybe we want one or two MORE examples before it becomes clear what should be standard, what should be props, and what should be left for the caller to do in its own CSS?
Maybe we could pair to create such a thing for the C/L dialog and retrofit it to the others?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5036)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx, line 230 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5036#-MyhpQsx-HkSZ-kqa4mJ:-MyiQ6w_CehQm1EdpzAm:b-gqt7te) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/527202e2794d42a4b0276ca63dde6754cb9e1358/src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx#L230)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't know. I agree it's tempting. OTOH, I looked at the three places so far that we use the Tabs Material UI component. One of them has no Emotion CSS at all, though it has some similar rules in a less file. But:
- one out of three wants the root Tab element to be height:100%; display:flex; flex-direction:column.
- two out of three want react-tabs__tab.react-tabs__tab to be uppercase
- one wants it blue, one white, and one leaves the default color
- one wants a white background, one a kDarkestBackground, and one default
- one wants flex-grow:1
- one sets react-tabs__tab--selected to white color and border, one blue, and one the default.
-  two of the three want a transparent border
- one wants them to be a flex column
-  two want react-tabs__tab-list to have no border
-  one wants react-tabs__tab-panel to have relative position and flex-grow 1
Now, it's just possible it would make things a little simpler to pull out a BloomTabs which deals with putting a parameterized backgroundColor and foregroundColor in the right places. We could probably standardize on uppercase and a transparent border for react-tabs__tab--selected. Maybe it's useful to make props for cssToApplyToLabels, cssToApplyToSelectedLabel,...
But maybe we want one or two MORE examples before it becomes clear what should be standard, what should be props, and what should be left for the caller to do in its own CSS?
Maybe we could pair to create such a thing for the C/L dialog and retrofit it to the others?
</blockquote></details>

OK, I had a go and it seemed to come out reasonably well.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5036)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
