### PR TITLE
Fix the way previewMode makes gaps between pages

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6306)

### CODE REVIEW

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6306)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less` line 50 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6306#-Nqnx1jL86pL4b3TsQU3:-Nqnx1jL86pL4b3TsQU4:bg4rviw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/090f5207e41bd9a835f80ff1e88ab7531a0e71c9/src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less#L50)):*
> ```Less
>     // of the rest of the page and interferes with the padding that positions marginBox.
>     // border-bottom: 15px solid @bloom-darkestBackground !important;
>     margin-bottom: 15px;
> ```

Given that there are some `@media print` and `@media screen` rules in here, I guess this is used when creating the PDF, too?
I guess you've tested this doesn't have adverse effects on PDFs?

**Comment by andrew-polk** [comment]
This commit needs to link to BL-13087 in the comment

**Review by JohnThomson — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6306#-:-NqoA6kyBb7eecnHF2vw:bb6un1j)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less` line 50 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6306#-Nqnx1jL86pL4b3TsQU3:-Nqo9sVwB61iNPxnQekj:b-9ao56s) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/090f5207e41bd9a835f80ff1e88ab7531a0e71c9/src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less#L50)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Given that there are some `@media print` and `@media screen` rules in here, I guess this is used when creating the PDF, too?
I guess you've tested this doesn't have adverse effects on PDFs?
</blockquote></details>

For some reason that didn't occur to me. I did try BloomPubs, and have now tried PDFs, and I don't see any sign of the extra margin showing up, though I'm not sure why not!

**Review by andrew-polk — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6306)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
