### PR TITLE
BL-4502 Cursor on Thumbnails changes

### PR DESCRIPTION
**Pull request by weagale**
* Assigned the cursor to be a pointer
   (finger like on a web link)

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2324)

### CODE REVIEW

**Comment by andrew-polk** [comment]
This is definitely an improvement and addresses the original issue on the card, but it doesn't address JH's concern in the comment. Have you had a chance to look at what that would take?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.less, line 37 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2324#-L9GmaqjC4wk5GsB8_IN:-L9GmaqjC4wk5GsB8_IO:bg1tx97) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2cf4105ef668c5889bcfc26861fa97a69be7f5ad/src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.less#L37)):*
> ```Less
>     flex: 1 1 auto;
>     overflow-y: auto; // so it will scroll, if it needs to, instead of growing
>     cursor: pointer;
> ```

This seems to make the cursor a pointer even when not focused on a book. I don't think we want that.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2324#-:-L9GmLhj44GZGxUxSBXr:b-3aiovy)*

**Comment by andrew-polk** [comment]
What JH refers to in the card is that the thumbnails are not images but rather really small websites (just as the large page to edit is a website). So if a user managed to put a link in their book, for example, clicking that link in the thumbnail would try to navigate to the link. I'm not sure of the specific bugs JH refers to, but that is the idea.
So he was wondering if can just make those not clickable other than to select them. 
His idea: cover it with something transparent.
Another idea: capture the click event, select the page, prevent the event from propagating.
Probably other ideas would be workable, too.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2324#-:-L9GzzuU-KdXPfJowZWz:big2mdx)*

**Comment by weagale** [comment]
Ok, now I understand what JH is talking about better and have a testable event.  I did test the current version with a link in one page of my book (https://bloomlibrary.org/landing).  I was unable to get the thumbnail to launch the website.  

This link (below) suggests a way to inactivate the "mini-website" but as suspected it also makes it not-move-able.  (https://stackoverflow.com/questions/6727659/is-it-possible-to-make-an-html-anchor-tag-not-clickable-linkable-using-css?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa).

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2324#-:-L9HAo1O5-1c1IFz6btJ:bv8gcmc)*

**Comment by andrew-polk** [comment]
Just want to clarify after our discussion for the sake of others...
This change doesn't do anything to prevent clicks on things on the page (such as a url). Apparently we already prevent that somehow.
So I am going to merge this as it fixes the initial item in the card and let JH clarify what else, if anything, needs to be done.

:lgtm: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2324#-:-L9MLzta4M9twVXQv6I4:bgot6go)*

**Pull request merged**
