### PR TITLE
Provide estimate of time remaining during video creation (BL-11136)

### PR DESCRIPTION
**Pull request by andrew-polk**
and hide cancel button

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182)

### CODE REVIEW

**Review by gmartin7 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 77 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182#-N3_xfyhCp2xrx-MSZUL:-N3_xfyhCp2xrx-MSZUM:b-lu7lly) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/12864ac610209d68b131077698f940c7d6cc68c5/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L77)):*
> ```Smalltalk
> 			// force handles to be created
> 			_ = Handle; 
> 			_ = _content.Handle;
> ```

Really! I didn't know you could do that! Interesting...
___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 379 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182#-N3_y7Zr0EwvclbtBh7i:-N3_y7Zr0EwvclbtBh7j:b59qq79) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/12864ac610209d68b131077698f940c7d6cc68c5/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L379)):*
> ```Smalltalk
> 				//		"The parameter is a duration in hours, minutes, and seconds"),
> 				//	videoDuration);
> 				//progress.MessageWithoutLocalizing($"- {msg}");
> ```

Is this still supposed to be here?

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182)* status: 5 of 6 files reviewed, 8 unresolved discussions (waiting on @andrew-polk and @gmartin7)

___
*[`DistFiles/localization/en/Bloom.xlf` line 993 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182#-N3dsJO4C_RNAk_nzv-p:-N3dsJO4C_RNAk_nzv-q:bvtna1j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6cff2e33bb664a023bb86625cc80628bf6d35d01/DistFiles/localization/en/Bloom.xlf#L993)):*
> ```XML
>         <note>The parameter is a time</note>
>       </trans-unit>
> -->      
> ```

An andrew nit: trailing spaces



_Code quote:_
```XML
······
```
___
*[`DistFiles/localization/en/Bloom.xlf` line 4151 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182#-N3dvOrQ5i-eGCHPzUKQ:-N3dvOrQ5i-eGCHPzUKR:b-r5o0n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6cff2e33bb664a023bb86625cc80628bf6d35d01/DistFiles/localization/en/Bloom.xlf#L4151)):*
> ```XML
>         <source xml:lang="en">about {0} minutes</source>
>         <note>ID: PublishTab.RecordVideo.AboutNMinutes</note>
>         <note>The parameter is a number of minutes</note>
> ```

Does the word "parameter" make sense to a localizer? I think that's technical jargon and should be replaced by "{0}"

Likewise for other usages of "parameter" below.



_Code quote:_
```XML
parameter
```
___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 32 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182#-N3ds3kJ35Dpt5IUVWcM:-N3ds3kK9FhkXc9CoNYW:bwnnwv4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6cff2e33bb664a023bb86625cc80628bf6d35d01/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L32)):*
> ```Smalltalk
> 		private Browser _content;
> 		private Process _ffmpegProcess;
> 		private Boolean _ffmpegExited;
> ```

Is there a reason we specifically need Boolean vs bool?
___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 63 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182#-N3dsOBX7mRe3xvsy5r7:-N3dsOBX7mRe3xvsy5r8:b35rkn9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6cff2e33bb664a023bb86625cc80628bf6d35d01/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L63)):*
> ```Smalltalk
> 
> 		// 30fps is standard for SD video
> 		private const int kFrameRate = 30; 
> ```

An andrew nit: trailing space

Also after "_ = Handle;" below



_Code quote:_
```Smalltalk
·
```
___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 657 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182#-N3dxT0Z9X2AoY_j5P7s:-N3dxT0Z9X2AoY_j5P7t:b-gyblif) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6cff2e33bb664a023bb86625cc80628bf6d35d01/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L657)):*
> ```Smalltalk
> 						"about {0} minutes",
> 						"The parameter is a number of minutes"),
> 					Math.Ceiling(millisRemaining / 60000));
> ```

Pretty sure you decided to round up instead of rounding to closest on purpose. Is that correct?
___
*[`src/BloomExe/Utils/MiscUtils.cs` line 327 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182#-N3dtgXx9yBdbdBzRNUR:-N3dtgXx9yBdbdBzRNUS:b-wlpzek) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6cff2e33bb664a023bb86625cc80628bf6d35d01/src/BloomExe/Utils/MiscUtils.cs#L327)):*
> ```Smalltalk
> 		public static string ReadAllTextFromFileWhichMightGetWrittenTo(string path)
> 		{
> 			FileStream logFileStream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
> ```

I think we should wrap both of these in "using" clauses. What if logFileReader.ReadLine() throws an exception? Then the cleanup portion would not get executed as currently written. But I think it is desirable to clean it up, right?



_Code quote:_
```Smalltalk
			FileStream logFileStream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
			StreamReader logFileReader = new StreamReader(logFileStream);
```
___
*[`src/BloomExe/Utils/MiscUtils.cs` line 334 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182#-N3duIAqD-qjqbQo5YKk:-N3duIAqD-qjqbQo5YKl:b-xla275) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6cff2e33bb664a023bb86625cc80628bf6d35d01/src/BloomExe/Utils/MiscUtils.cs#L334)):*
> ```Smalltalk
> 			{
> 				string line = logFileReader.ReadLine();
> 				sb.AppendLine(line);
> ```

I'm not sure if this is too much of a corner case to deal with. So, what happens if the file is in the middle of writing and has written out just a partial line? I assume what will happen is that our while loop will happily ReadLine() even the last line, which is a partial line. Then it will calls sb.AppendLine(). Now in the StringBuilder, the end is the partial line FOLLOWED BY A NEWLINE CHARACTER, which is actually not an accurate representation of the stream?
Is there anything wrong with just doing ReadBlocks() and appending the blocks? I think that would allow the newline characters to be transmitted as presented in the stream (even if they differ from the OS defaults) and allow a partial line to be added without an extraneous newline in the buffer.

Does that make sense, or is this nothing we need to worry about?

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182)* status: 5 of 6 files reviewed, 9 unresolved discussions (waiting on @andrew-polk and @gmartin7)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 671 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182#-N3dzMpkA2IwjXTbWU_a:-N3dzMpkA2IwjXTbWU_b:b-kckd4y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6cff2e33bb664a023bb86625cc80628bf6d35d01/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L671)):*
> ```Smalltalk
> 
> 			var pattern = $"\\n{key}=(.*)\\n";
> 			var lastOccurenceRegex = new Regex($"{pattern}(?![\\s\\S]*{pattern})");
> ```

What about just matching on pattern and adding the RegexOptions.RightToLeft option?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182)* status: 5 of 6 files reviewed, 9 unresolved discussions (waiting on @gmartin7 and @sujeffreyl)

___
*[`DistFiles/localization/en/Bloom.xlf` line 993 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182#-N3dsJO4C_RNAk_nzv-p:-N3e25qBChoxvevysbll:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6cff2e33bb664a023bb86625cc80628bf6d35d01/DistFiles/localization/en/Bloom.xlf#L993)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

An andrew nit: trailing spaces
</blockquote></details>

Done.
___
*[`DistFiles/localization/en/Bloom.xlf` line 4151 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182#-N3dvOrQ5i-eGCHPzUKQ:-N3e2yqR53oNEnY3r5Dg:b3wste4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6cff2e33bb664a023bb86625cc80628bf6d35d01/DistFiles/localization/en/Bloom.xlf#L4151)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Does the word "parameter" make sense to a localizer? I think that's technical jargon and should be replaced by "{0}"

Likewise for other usages of "parameter" below.
</blockquote></details>

Thanks. I started using that because I didn't know if "the parameter" or "{0:hh:mm tt}" would be more confusing...
___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 32 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182#-N3ds3kJ35Dpt5IUVWcM:-N3e35t574iKqi6k2X4o:b-kz6mqf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6cff2e33bb664a023bb86625cc80628bf6d35d01/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L32)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Is there a reason we specifically need Boolean vs bool?
</blockquote></details>

nope, accidental
___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 63 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182#-N3dsOBX7mRe3xvsy5r7:-N3e3KupB2i2l8d7QSeJ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6cff2e33bb664a023bb86625cc80628bf6d35d01/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L63)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

An andrew nit: trailing space

Also after "_ = Handle;" below
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 657 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182#-N3dxT0Z9X2AoY_j5P7s:-N3e3PPj9nWmBzSg-V74:b2nign6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6cff2e33bb664a023bb86625cc80628bf6d35d01/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L657)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Pretty sure you decided to round up instead of rounding to closest on purpose. Is that correct?
</blockquote></details>

yes
___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 671 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182#-N3dzMpkA2IwjXTbWU_a:-N3eLiSO-UXpCyx1_59b:bjc4c4s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6cff2e33bb664a023bb86625cc80628bf6d35d01/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L671)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

What about just matching on pattern and adding the RegexOptions.RightToLeft option?
</blockquote></details>

Cool. I didn't know about that.
___
*[`src/BloomExe/Utils/MiscUtils.cs` line 327 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182#-N3dtgXx9yBdbdBzRNUR:-N3e4aYf8R8yaHUV3juq:bxvijfv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6cff2e33bb664a023bb86625cc80628bf6d35d01/src/BloomExe/Utils/MiscUtils.cs#L327)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I think we should wrap both of these in "using" clauses. What if logFileReader.ReadLine() throws an exception? Then the cleanup portion would not get executed as currently written. But I think it is desirable to clean it up, right?
</blockquote></details>

good catch; that's what happens when you copy code from SO...
___
*[`src/BloomExe/Utils/MiscUtils.cs` line 334 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182#-N3duIAqD-qjqbQo5YKk:-N3eM02F0RgMmZ0oVfFz:b-s9afv9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6cff2e33bb664a023bb86625cc80628bf6d35d01/src/BloomExe/Utils/MiscUtils.cs#L334)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I'm not sure if this is too much of a corner case to deal with. So, what happens if the file is in the middle of writing and has written out just a partial line? I assume what will happen is that our while loop will happily ReadLine() even the last line, which is a partial line. Then it will calls sb.AppendLine(). Now in the StringBuilder, the end is the partial line FOLLOWED BY A NEWLINE CHARACTER, which is actually not an accurate representation of the stream?
Is there anything wrong with just doing ReadBlocks() and appending the blocks? I think that would allow the newline characters to be transmitted as presented in the stream (even if they differ from the OS defaults) and allow a partial line to be added without an extraneous newline in the buffer.

Does that make sense, or is this nothing we need to worry about?
</blockquote></details>

My guess is it doesn't matter. But I think you're right.

**Review by gmartin7 — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182)* status: all files reviewed, 8 unresolved discussions (waiting on @sujeffreyl)

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk, @gmartin7, and @sujeffreyl)

___
*[`DistFiles/localization/en/Bloom.xlf` line 4151 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182#-N3dvOrQ5i-eGCHPzUKQ:-N3eS-k871fKJKOs7jZf:b4h04qf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6cff2e33bb664a023bb86625cc80628bf6d35d01/DistFiles/localization/en/Bloom.xlf#L4151)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Thanks. I started using that because I didn't know if "the parameter" or "{0:hh:mm tt}" would be more confusing...
</blockquote></details>

Sadly I bet they're both confusing... :(
___
*[`src/BloomExe/Utils/MiscUtils.cs` line 332 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182#-N3eW54Z8ilgUhFbwh8z:-N3eW54Z8ilgUhFbwh9-:btwb2k4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/13fdcb259e9085553434dd71b4931d734bc3b621/src/BloomExe/Utils/MiscUtils.cs#L332)):*
> ```Smalltalk
> 				StringBuilder sb = new StringBuilder();
> 
> 				int bufferLength = (int)logFileReader.BaseStream.Length;
> ```

I'm a little wary about the bufferLength. The file size could be unbounded. And you've written this as a public utility function, so its purposes are not solely for ffmpeg. Should it be capped at 1024 or 4096?

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk, @gmartin7, and @sujeffreyl)

___
*[`src/BloomExe/Utils/MiscUtils.cs` line 332 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182#-N3eW54Z8ilgUhFbwh8z:-N3eXGgFCqYe8yha8ANF:b-64rk8t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/13fdcb259e9085553434dd71b4931d734bc3b621/src/BloomExe/Utils/MiscUtils.cs#L332)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I'm a little wary about the bufferLength. The file size could be unbounded. And you've written this as a public utility function, so its purposes are not solely for ffmpeg. Should it be capped at 1024 or 4096?
</blockquote></details>

(Or fixed at {whateverBufferSize})

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @gmartin7 and @sujeffreyl)

___
*[`src/BloomExe/Utils/MiscUtils.cs` line 332 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182#-N3eW54Z8ilgUhFbwh8z:-N3ebhMbDNKWndQNazG7:b9xxiu6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/13fdcb259e9085553434dd71b4931d734bc3b621/src/BloomExe/Utils/MiscUtils.cs#L332)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

(Or fixed at {whateverBufferSize})
</blockquote></details>

Thanks. Low-level IO is an area I've never felt comfortable with. Here I copied something I misunderstood from the Microsoft doc example.

**Review by sujeffreyl — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @gmartin7 and @sujeffreyl)

**Review by sujeffreyl — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @gmartin7 and @sujeffreyl)

**Review by sujeffreyl — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @andrew-polk)

**Review by sujeffreyl — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
