### PR TITLE
Adjust better when image container size changes (BL-13965)

### PR DESCRIPTION
**Pull request by JohnThomson**
This converts the background image of an image container into an overlay, allowing it to be cropped.
The main image is left as a placeholder, so earlier Bloom versions won't find things too surprising.
We still have a way to identify one overlay as a background, with some special behaviors.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6734)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Not done, but publishing what I've reviewed so far.

> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6734#-:-OAe0sNz7s2E9rxxRJpm:b-az70k1)* status: 8 of 9 files reviewed, 7 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 4619 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6734#-OAe0jUY1mEAOqDxggqe:-OAe0jUY1mEAOqDxggqf:bs99rh9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e9b20de188ff05462d444ecdedfc29e5b757cf7/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L4619)):*
> ```XML
>         | "forTool"
>         | "forGamePlayMode" = "none";
> ```

Note to self: I am this far reviewing through this file.
___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 5757 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6734#-OAduawE2kUU-gCnhq9g:-OAduawE2kUU-gCnhq9h:b4p2w9q) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e9b20de188ff05462d444ecdedfc29e5b757cf7/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L5757)):*
> ```XML
>     // Typical source is something like "left: 224px; top: 79.6px; width: 66px; height: 30px;"
>     // We want to pass "top" and get 79.6.
>     public static getLabeledNumber(label: string, source: string): number {
> ```

Is it worth calling out the fact that this is specific to pixels?
So getLabeledNumberInPixels?
___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 5758 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6734#-OAduYKeAPz6-QnJx4sG:-OAduYKeAPz6-QnJx4sH:ba0zscn) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e9b20de188ff05462d444ecdedfc29e5b757cf7/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L5758)):*
> ```XML
>     // We want to pass "top" and get 79.6.
>     public static getLabeledNumber(label: string, source: string): number {
>         const match = source.match(new RegExp(label + this.numberPxRegex));
> ```

Odd that this calls a static using "this".
___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManagerSpec.ts` line 6 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6734#-OAdpb_dEvbbG8ngXXyC:-OAdpb_eCaXmeUIvvaV2:b-gg6qb3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e9b20de188ff05462d444ecdedfc29e5b757cf7/src/BloomBrowserUI/bookEdit/js/bubbleManagerSpec.ts#L6)):*
> ```XML
> // A (currently very incomplete) set of tests for BubbleManager.
> 
> fdescribe("BubbleManager.getLabeledNumber", () => {
> ```

fdescribe => describe (x2)
___
*[`src/BloomBrowserUI/bookEdit/js/OverlayContextControls.tsx` line 645 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6734#-OAdvVD_A6ZXZiD39xF-:-OAdvVD_A6ZXZiD39xF0:b-e782q7) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e9b20de188ff05462d444ecdedfc29e5b757cf7/src/BloomBrowserUI/bookEdit/js/OverlayContextControls.tsx#L645)):*
> setBackgroundId

I think backgroundL10nId or even backgroundMenuItemL10nId would be less confusing.
___
*[`src/BloomBrowserUI/lib/split-pane/split-pane.js` line 792 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6734#-OAdw9JBEjaL_hUoqm8r:-OAdw9JBEjaL_hUoqm8s:bz1hbe0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e9b20de188ff05462d444ecdedfc29e5b757cf7/src/BloomBrowserUI/lib/split-pane/split-pane.js#L792)):*
> ```JavaScript
>         }
>         let aspectRatio = img.naturalWidth / img.naturalHeight;
>         // but if there is a bloom-backgroundImage, common in imqges used for overlays, use that instead
> ```

typo

imqges => images
___
*[`src/BloomExe/Edit/EditingModel.cs` line 1675 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6734#-OAdy6FU8jS3noByXnPL:-OAdy6FU8jS3noByXnPM:b-cl9ffc) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e9b20de188ff05462d444ecdedfc29e5b757cf7/src/BloomExe/Edit/EditingModel.cs#L1675)):*
> ```Smalltalk
>                 );
> 
>             /* We're Saving to the DOM here only if it's a cover page, because lets us make the image transparent if it should be:
> ```

typo

There's a missing word in this sentence. 

because it/that lets us?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6734)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 5757 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6734#-OAduawE2kUU-gCnhq9g:-OArXMwJExStvhbrLWO7:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e9b20de188ff05462d444ecdedfc29e5b757cf7/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L5757)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is it worth calling out the fact that this is specific to pixels?
So getLabeledNumberInPixels?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 5758 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6734#-OAduYKeAPz6-QnJx4sG:-OArXZkaDHYyE1RvvfG8:bg03bzv) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e9b20de188ff05462d444ecdedfc29e5b757cf7/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L5758)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Odd that this calls a static using "this".
</blockquote></details>

Works because the method is static, too. Fixed.
___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManagerSpec.ts` line 6 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6734#-OAdpb_dEvbbG8ngXXyC:-OArXjH47NLWzqMtClz6:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e9b20de188ff05462d444ecdedfc29e5b757cf7/src/BloomBrowserUI/bookEdit/js/bubbleManagerSpec.ts#L6)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

fdescribe => describe (x2)
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/js/OverlayContextControls.tsx` line 645 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6734#-OAdvVD_A6ZXZiD39xF-:-OArYg16AU5b6dnVa459:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e9b20de188ff05462d444ecdedfc29e5b757cf7/src/BloomBrowserUI/bookEdit/js/OverlayContextControls.tsx#L645)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> setBackgroundId

I think backgroundL10nId or even backgroundMenuItemL10nId would be less confusing.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/lib/split-pane/split-pane.js` line 792 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6734#-OAdw9JBEjaL_hUoqm8r:-OArYGA96a8P3W-MGAFJ:bb7f2mf) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e9b20de188ff05462d444ecdedfc29e5b757cf7/src/BloomBrowserUI/lib/split-pane/split-pane.js#L792)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

typo

imqges => images
</blockquote></details>

done
___
*[`src/BloomExe/Edit/EditingModel.cs` line 1675 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6734#-OAdy6FU8jS3noByXnPL:-OArYcc24EwEyz-j4i61:b-7ql1td) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e9b20de188ff05462d444ecdedfc29e5b757cf7/src/BloomExe/Edit/EditingModel.cs#L1675)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

typo

There's a missing word in this sentence. 

because it/that lets us?
</blockquote></details>

fixed

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6734)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 4794 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6734#-OArxez2DnAA2K5b8l3s:-OArxez2DnAA2K5b8l3t:b-kl0ymx) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/5f39af99a1fd3b6730d61f34b23a65621988969d/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L4794)):*
> ```XML
>     private documentMouseUp = (ev: Event) => {
>         if (this.comicEditingSuspendedState === "forDrag") {
>             // the mousedown was in an origami slider
> ```

Please add a ; or . after "slider".
I first tried to read this comment as all one phrase.

Otherwise, LGTM

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6734)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 4794 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6734#-OArxez2DnAA2K5b8l3s:-OAsKam553rjzX39Eqbm:b-ud0vx8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/5f39af99a1fd3b6730d61f34b23a65621988969d/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L4794)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Please add a ; or . after "slider".
I first tried to read this comment as all one phrase.

Otherwise, LGTM
</blockquote></details>

I actually did a bit more than that. Worth another quick look.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6734)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
