### PR TITLE
Make Windows-specific bugfix Windows-specific

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2023)

### CODE REVIEW

**Comment by gmartin7** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Workspace/WorkspaceView.cs, line 1064 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2023#-L05tErsur8alMa4Gniu:-L05tErtb768aztX0XLY:bxwdvzf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c2e69873557a257be0517666419cdf22b3322e42/src/BloomExe/Workspace/WorkspaceView.cs#L1064)):*
> ```Smalltalk
> 	public class NestedDockedChildPanel : Panel
> 	{
> 		// This fix is Windows/.Net specific.  It prevents Bloom from displaying the main window at all in Linux/Mono.
> ```

So I assume it works fine in Linux without the override?!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2023#-:-L05tPAvIgj5Ya0t032J:bnfp4nl)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/BloomExe/Workspace/WorkspaceView.cs, line 1064 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2023#-L05tErsur8alMa4Gniu:-L05tyfm1rpC36629Xth:b-vfcyb6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c2e69873557a257be0517666419cdf22b3322e42/src/BloomExe/Workspace/WorkspaceView.cs#L1064)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

So I assume it works fine in Linux without the override?!
</blockquote></details>

To check this, watch the language-chooser combo in the top left as the window size changes and also, especially, as the language changes, especially between pairs of very long language names like Bahasa Indonesia. The down arrow on the menu should always be visible and right-aligned.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2023)*

**Comment by StephenMcConnel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Workspace/WorkspaceView.cs, line 1064 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2023#-L05tErsur8alMa4Gniu:-L07nTtxfmqFajrFUyZu:b-l6pvfv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c2e69873557a257be0517666419cdf22b3322e42/src/BloomExe/Workspace/WorkspaceView.cs#L1064)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

To check this, watch the language-chooser combo in the top left as the window size changes and also, especially, as the language changes, especially between pairs of very long language names like Bahasa Indonesia. The down arrow on the menu should always be visible and right-aligned.
</blockquote></details>

Yes, it seems to work okay on Linux, but in some sense that's immaterial because this fix for Windows makes the program not run at all on Linux.   I'm still not sure exactly what is going on in the guts of the Mono runtime, but I know the program won't display the main window on Linux.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2023)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Workspace/WorkspaceView.cs, line 1064 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2023#-L05tErsur8alMa4Gniu:-L0A8vBjsTUMqXk1c5a6:b-2y3vem) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c2e69873557a257be0517666419cdf22b3322e42/src/BloomExe/Workspace/WorkspaceView.cs#L1064)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Yes, it seems to work okay on Linux, but in some sense that's immaterial because this fix for Windows makes the program not run at all on Linux.   I'm still not sure exactly what is going on in the guts of the Mono runtime, but I know the program won't display the main window on Linux.
</blockquote></details>

OK, I will merge it, but testing is still appropriate to see whether an alternative fix is needed on Linux. I suspect it is unlikely, since apparently it's some bizarre way that Windows size changed messages jump in and our of kernel mode that causes something to run out of stack space.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2023)*

**Pull request merged**
