### PR TITLE
BL-9320 Make the new Widget template page a zero margin thing

### PR DESCRIPTION
**Pull request by gmartin7**
* This entailed making it part of the Digital Comic Template
   which moved it from Activities -> Digital Comic in the add page dialog

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4267)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4267)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.htm, line 406 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4267#-MVO9eOiEmL4O_2jlmWC:-MVO9eOj577TzisvgxX4:bp0bi0p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/bbbbd54391b7c8538e571a8253f261490fd2a331/src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.htm#L406)):*
> ```HTML
>         </div>
>         <div
>             class="A5Portrait bloom-page comic custom-widget-page customPage enterprise-only numberedPage"
> ```

`comic` seems wrong?
___
*[src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.htm, line 419 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4267#-MVO9iUo3gZJCsJYA4qr:-MVO9iUo3gZJCsJYA4qs:bj7sj94) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/bbbbd54391b7c8538e571a8253f261490fd2a331/src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.htm#L419)):*
> ```HTML
>             </div>
>             <div class="pageDescription" lang="en">
>                 A page where you can import an HTML5 widget which readers can
> ```

Is this properly `which` or `that`?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> This entailed making it part of the Digital Comic Template
> which moved it from Activities -> Digital Comic in the add page dialog

I don't think that is ok. Let's talk about this tomorrow if you're stuck.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4267#-:-MVPPsB2Aij3HFietsCm:bx0aezo)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @gmartin7)

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4267)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @gmartin7 and @hatton)

___
*[src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.htm, line 419 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4267#-MVO9iUo3gZJCsJYA4qr:-MVS3FV530ewk74B84yE:b-3ni9jr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/bbbbd54391b7c8538e571a8253f261490fd2a331/src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.htm#L419)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is this properly `which` or `that`?
</blockquote></details>

I think either way works. You prefer `that`?

**Comment by andrew-polk** [comment]
___
*[src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.htm, line 419 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4267#-MVO9iUo3gZJCsJYA4qr:-MVS9N-uBWcFrL9PMHvW:bt49zv0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/bbbbd54391b7c8538e571a8253f261490fd2a331/src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.htm#L419)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I think either way works. You prefer `that`?
</blockquote></details>

Based on https://www.grammarly.com/blog/which-vs-that/, I would choose which.

**Review by gmartin7 — COMMENTED** [review]
It's actually easier to close this PR and open a new one, since I needed to revert to the previous file structure.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4267#-:-MVSIcSu7-CECtrcmUI1:b-7gxahw)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.htm, line 406 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4267#-MVO9eOiEmL4O_2jlmWC:-MVSCsIe6ujnOo5q8GTD:b-ll2kns) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/bbbbd54391b7c8538e571a8253f261490fd2a331/src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.htm#L406)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

`comic` seems wrong?
</blockquote></details>

After discussion/pairing with Andrew, I'm pulling out a no-margin-page class to basePage.less that will be used by comic pages and the widget page.
___
*[src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.htm, line 419 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4267#-MVO9iUo3gZJCsJYA4qr:-MVSD8mMB1LhNpe0q50V:bbavz6l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/bbbbd54391b7c8538e571a8253f261490fd2a331/src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.htm#L419)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Based on https://www.grammarly.com/blog/which-vs-that/, I would choose which.
</blockquote></details>

Any objections, John?

**Pull request closed without merging**
