### PR TITLE
Add book level Make Bloom Pack menu command (BL-4442)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1588)

### CODE REVIEW

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DistFiles/localization/Bloom.en.tmx, line 729 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1588#-Kfm0PcvKlg62n6F846e:-Kfm0PcvKlg62n6F846f:b-cctffh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fc5fe2d83555525d78c53bdebc59310a073f0d65/DistFiles/localization/Bloom.en.tmx#L729)):*
> CollectionTab.BookMenu.MakeBlookPack

CollectionTab.BookMenu.MakeBloomPack

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1588#-:-Kfm5C4WO7LYzclS3ygc:bnfp4nl)*

**Comment by andrew-polk** [comment]
Except for one significant typo

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1588#-:-Kfm5MVkN_SvojdkaP5I:b-5a2om4)*

**Comment by StephenMcConnel** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[DistFiles/localization/Bloom.en.tmx, line 729 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1588#-Kfm0PcvKlg62n6F846e:-KfmHHs77VJFwzw517uq:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fc5fe2d83555525d78c53bdebc59310a073f0d65/DistFiles/localization/Bloom.en.tmx#L729)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> CollectionTab.BookMenu.MakeBlookPack

CollectionTab.BookMenu.MakeBloomPack
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1588)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1588)*

**Pull request merged**
