### PR TITLE
Update webpack to 4.x and update other items as well (BL-5776)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
Also cleaned up package.json, gulpfile.js, and webpack.config.js
of accumulated cruft.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2320)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---

*[src/BloomBrowserUI/package.json, line 87 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2320#-L97LjNSDkjUaJRo-2Mh:-L97LjNSDkjUaJRo-2Mi:bi6706w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c53073a5ff0d8699d0d9c36d0f0f84f767f6d14a/src/BloomBrowserUI/package.json#L87)):*
> ```JSON
>         "karma-teamcity-reporter": "^1.0.0",
>         "less": "^3.0.1",
>         "less-loader": "^4.1.0",
> ```

So I notice less, ts, typescript, pug, gulp loaders removed... those are somehow dependencies of something else, I guess, so don't have to be listed anymore? 

---

*[src/BloomBrowserUI/webpack.config.js, line 21 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2320#-L97KIqzC-_ya75SYeFa:-L97KIqzC-_ya75SYeFb:b-on9mxs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/be4f7ae00ca630b6b5315886a3c2d787cb53a63c/src/BloomBrowserUI/webpack.config.js#L21)):*
> ```
> babel-preset-env
> ```

While we're paying attention to this... what do you think about specifying our firefox version? Does it make much difference?

---

*[src/BloomBrowserUI/webpack.config.js, line 105 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2320#-L97LEWA2uap-fzqHhWC:-L97LEWA2uap-fzqHhWD:b3ph6q8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/be4f7ae00ca630b6b5315886a3c2d787cb53a63c/src/BloomBrowserUI/webpack.config.js#L105)):*
> ```JavaScript
>                     name: 'commonBundle',
>                     chunks: "initial",
>                     minChunks: 9,
> ```

Elsewhere you wrote up how you arrived at this. How about a putting the comment in here?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2320)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/package.json, line 87 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2320#-L97LjNSDkjUaJRo-2Mh:-L9BGY0P31q4fvF2e56g:b-vv7itx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c53073a5ff0d8699d0d9c36d0f0f84f767f6d14a/src/BloomBrowserUI/package.json#L87)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

So I notice less, ts, typescript, pug, gulp loaders removed... those are somehow dependencies of something else, I guess, so don't have to be listed anymore? 
</blockquote></details>

I restored less and less-loader at Wendy's request.  The items I removed were not mentioned explicitly in any of our files, but may well be loaded by something we do mention.  I removed the  pug items from the "dependencies" section (moving "gulp-pug" to "devDependencies") because our runtime code deals only with html files.  gulp-pug depends on pug, so it gets loaded automatically.  Note that webpack uses ts-loader instead of typescript-loader.

---

*[src/BloomBrowserUI/webpack.config.js, line 21 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2320#-L97KIqzC-_ya75SYeFa:-L9BH8ZL4X9Gj5Wv7nwG:bqlvqvz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/be4f7ae00ca630b6b5315886a3c2d787cb53a63c/src/BloomBrowserUI/webpack.config.js#L21)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

> ```
> babel-preset-env
> ```

While we're paying attention to this... what do you think about specifying our firefox version? Does it make much difference?
</blockquote></details>

I don't think that would help since firefox insists on updating itself every couple of months.  We don't all have firefox 45 preserved on our machines, and if we do, it's a battle to keep it from updating itself.

---

*[src/BloomBrowserUI/webpack.config.js, line 105 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2320#-L97LEWA2uap-fzqHhWC:-L9BRQIN2Jc7XoUGhypu:b-6dkk06) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/be4f7ae00ca630b6b5315886a3c2d787cb53a63c/src/BloomBrowserUI/webpack.config.js#L105)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Elsewhere you wrote up how you arrived at this. How about a putting the comment in here?
</blockquote></details>

Done.  I added a couple of other comments as well elsewhere.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2320)*

**Comment by hatton** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/webpack.config.js, line 21 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2320#-L97KIqzC-_ya75SYeFa:-L9DPnUL0Mm8gKwFv3dK:bgzzr4h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/be4f7ae00ca630b6b5315886a3c2d787cb53a63c/src/BloomBrowserUI/webpack.config.js#L21)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I don't think that would help since firefox insists on updating itself every couple of months.  We don't all have firefox 45 preserved on our machines, and if we do, it's a battle to keep it from updating itself.
</blockquote></details>

But... but... we ship a certain firefox as part of Bloom. This does *not* update itself. So I think you must be thinking that when *debugging* with whatever FF is installed. Since Bloom's FF is always going to be *older*, we can expect the FF being used for debugging to have *more things implemented, so the polyfills that webpack would implement would be > than actually needed. But for all I know this isn't a big win... just askin'.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2320)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/webpack.config.js, line 21 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2320#-L97KIqzC-_ya75SYeFa:-L9GXWLBCDEsVKpdDluS:b-40rlp5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/be4f7ae00ca630b6b5315886a3c2d787cb53a63c/src/BloomBrowserUI/webpack.config.js#L21)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

But... but... we ship a certain firefox as part of Bloom. This does *not* update itself. So I think you must be thinking that when *debugging* with whatever FF is installed. Since Bloom's FF is always going to be *older*, we can expect the FF being used for debugging to have *more things implemented, so the polyfills that webpack would implement would be > than actually needed. But for all I know this isn't a big win... just askin'.
</blockquote></details>

OK, I'm a bit slow catching on that it's the browser version for babel-preset-env translation you're talking about, not an npm version.  It took me a while, but I finally figured out the syntax for specifying browser versions when initializing babel-preset-env.  I'm not sure it's making any difference in the generated javascript, but it's now specified to handle Firefox back to version 45.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2320)*

**Pull request merged**
