### PR TITLE
On SS import, keep one editable from original as a template (BL-11483)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5402)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5402)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @hatton and @JohnThomson)

___
*[`src/BloomExe/Book/TranslationGroupManager.cs` line 524 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5402#-NCWmj0fEVvVrd3mjF4q:-NCWmj0fEVvVrd3mjF4r:bqhimc3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8b6dc2df6a55aa98836baf0e5cdca8e60a50f4d0/src/BloomExe/Book/TranslationGroupManager.cs#L524)):*
> ```Smalltalk
> 			{
> 				newElementInThisLanguage = groupElement.OwnerDocument.CreateElement("div");
> 				newElementInThisLanguage.SetAttribute("class", "bloom-editable normal-style");
> ```

Normally, bubbles get "Bubble". Is that relevant to this task?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5402)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/BloomExe/Book/TranslationGroupManager.cs` line 524 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5402#-NCWmj0fEVvVrd3mjF4q:-NCWqKqeAi9jLD1kHVH-:b-58l4a2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8b6dc2df6a55aa98836baf0e5cdca8e60a50f4d0/src/BloomExe/Book/TranslationGroupManager.cs#L524)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Normally, bubbles get "Bubble". Is that relevant to this task?
</blockquote></details>

It's relevant to the task, but not to this part of the fix. A different part of the fix will preserve the Bubble style (or any other) on the relevant part of the page that the importer is duplicating as a template (at least until/unless we decide we should export and import the style of a block). This is an extra patch to make sure that if we ever again get in a pathological situation where there is no prototype bloom-editable to copy, the one we create from scratch has _some_ style. (Apparently if it doesn't, our cog is not offered, so there's no way to repair things.)

**Review by hatton — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5402)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/TranslationGroupManager.cs` line 524 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5402#-NCWmj0fEVvVrd3mjF4q:-NCWs4FGCg9xWIN5X9E1:bd5l6mr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8b6dc2df6a55aa98836baf0e5cdca8e60a50f4d0/src/BloomExe/Book/TranslationGroupManager.cs#L524)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's relevant to the task, but not to this part of the fix. A different part of the fix will preserve the Bubble style (or any other) on the relevant part of the page that the importer is duplicating as a template (at least until/unless we decide we should export and import the style of a block). This is an extra patch to make sure that if we ever again get in a pathological situation where there is no prototype bloom-editable to copy, the one we create from scratch has _some_ style. (Apparently if it doesn't, our cog is not offered, so there's no way to repair things.)
</blockquote></details>

thanks!
___
*[`src/BloomExe/Edit/WebThumbNailList.cs` line 283 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5402#-NCWsANl06rXQEdT6y0T:-NCWsANl06rXQEdT6y0U:b-s74llv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8b6dc2df6a55aa98836baf0e5cdca8e60a50f4d0/src/BloomExe/Edit/WebThumbNailList.cs#L283)):*
> ```Smalltalk
> 			_browser.DocumentCompleted += WebBrowser_DocumentCompleted;
> 
> 			_baseForRelativePaths = pageListDom.BaseForRelativePaths;
> ```

Would it make sense to roll this into `_browser`? like `_browser.NavigateAsync` and then maybe make`Navigate` private?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5402)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`src/BloomExe/Edit/WebThumbNailList.cs` line 283 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5402#-NCWsANl06rXQEdT6y0T:-NCX8VuE8BGuz-RdtomP:b-20nw7y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8b6dc2df6a55aa98836baf0e5cdca8e60a50f4d0/src/BloomExe/Edit/WebThumbNailList.cs#L283)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Would it make sense to roll this into `_browser`? like `_browser.NavigateAsync` and then maybe make`Navigate` private?
</blockquote></details>

The thought of making Navigate async fills me with dread. That's what WebView2 wants you to do, but it will be viral through a whole lot of our code base: every method that navigates, every method that calls one of those methods, recursively.
We COULD try to make our Navigate thread-safe (which is what this change is about), but I'm a little nervous. It could presumably use itself as the control to invoke on, but that only works (IIRC) if it has a handle (somewhere after it's added to a form and the form is loaded), so the apparent safety might be  misleading., since we tend to want to navigate a browser soon after creating it.

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5402)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Edit/WebThumbNailList.cs` line 283 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5402#-NCWsANl06rXQEdT6y0T:-NCXDfQXAb39txnxv0OH:bwt8fe0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8b6dc2df6a55aa98836baf0e5cdca8e60a50f4d0/src/BloomExe/Edit/WebThumbNailList.cs#L283)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

The thought of making Navigate async fills me with dread. That's what WebView2 wants you to do, but it will be viral through a whole lot of our code base: every method that navigates, every method that calls one of those methods, recursively.
We COULD try to make our Navigate thread-safe (which is what this change is about), but I'm a little nervous. It could presumably use itself as the control to invoke on, but that only works (IIRC) if it has a handle (somewhere after it's added to a form and the form is loaded), so the apparent safety might be  misleading., since we tend to want to navigate a browser soon after creating it.
</blockquote></details>

Sorry, I just mean, if the right way to Navigate is to `Invoke((Action) (() => `, why not put that in the class? Why leave it to each caller to figure out? Maybe that doesn't make sense, just askin'

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5402)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`src/BloomExe/Edit/WebThumbNailList.cs` line 283 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5402#-NCWsANl06rXQEdT6y0T:-NC_54c0EaHStfrWri6W:b-8p7r9q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8b6dc2df6a55aa98836baf0e5cdca8e60a50f4d0/src/BloomExe/Edit/WebThumbNailList.cs#L283)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Sorry, I just mean, if the right way to Navigate is to `Invoke((Action) (() => `, why not put that in the class? Why leave it to each caller to figure out? Maybe that doesn't make sense, just askin'
</blockquote></details>

Yes, that's what the second paragraph above is addressing. Invoke() is something that can only be done by a Windows control that has a handle. Sometimes that could be the Browser itself. Sometimes that won't work.

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5402)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/Edit/WebThumbNailList.cs` line 283 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5402#-NCWsANl06rXQEdT6y0T:-NCkOtju6A3M7VZsij65:b-fcdh16) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8b6dc2df6a55aa98836baf0e5cdca8e60a50f4d0/src/BloomExe/Edit/WebThumbNailList.cs#L283)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Yes, that's what the second paragraph above is addressing. Invoke() is something that can only be done by a Windows control that has a handle. Sometimes that could be the Browser itself. Sometimes that won't work.
</blockquote></details>

I don't think it's the case in c# that something can "only be done" by code in location A, not B. So this same code could be in the class rather than in every caller of the class. Not worth continuing to go back and forth though :-)

**Pull request merged**
