### PR TITLE
Handle pasting image file with bad metadata better (BL-11933)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6219)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6219)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Edit/EditingView.cs` line 611 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6219#-NjP-xc9C2V3SHGRdlHs:-NjP-xc9C2V3SHGRdlHt:bv66st4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/da56e65f1d0e1b8ac0c6e5bd59fd822ad077c8d3/src/BloomExe/Edit/EditingView.cs#L611)):*
> ```Smalltalk
> 				imageBeingModified.Metadata = metadata;
> 				imageBeingModified.Metadata.StoreAsExemplar(Metadata.FileCategory.Image);
> 				try
> ```

I think this now has more knowledge about images than we want in `EditingView`. Move to `ImageUtils`?
___
*[`src/BloomExe/Edit/PageEditingModel.cs` line 61 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6219#-NjP06a4EtGJWGZBIDc8:-NjP06a4EtGJWGZBIDc9:b-fbr9fl) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/da56e65f1d0e1b8ac0c6e5bd59fd822ad077c8d3/src/BloomExe/Edit/PageEditingModel.cs#L61)):*
> ```Smalltalk
> 				imageInfo.Metadata.Write(Path.Combine(bookFolderPath, imageFileName));
> 			}
> 			catch (Exception ex)
> ```

I think this now has more knowledge about images than we want in `PageEditingModel`. Move to `ImageUtils`?
___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 388 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6219#-NjP0Dk_4em1Drjo1IgF:-NjP0Dk_4em1Drjo1IgG:b-86m184) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/da56e65f1d0e1b8ac0c6e5bd59fd822ad077c8d3/src/BloomExe/ImageProcessing/ImageUtils.cs#L388)):*
> ```Smalltalk
> 		private static bool TryStripMetadataWithGraphicsMagick(PalasoImage imageInfo, string sourcePath, string destinationPath)
> 		{
> 			var graphicsMagickPath = GetGraphicsMagickPath();
> ```

I notice there is a `RunGraphicsMagick()`. Why isn't that called everywhere, including here
___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 1046 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6219#-NjP0cEsA-DtrmdGvBj7:-NjP0cEsA-DtrmdGvBj8:bs75jpu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/da56e65f1d0e1b8ac0c6e5bd59fd822ad077c8d3/src/BloomExe/ImageProcessing/ImageUtils.cs#L1046)):*
> ```Smalltalk
> 		}
> 
> 		private static ExecutionResult RunGraphicsMagick(string graphicsMagickPath, string sourcePath, string destPath, Size size,
> ```

Why does this require a `graphicsMagickPath` parameter?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6219)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @hatton)

___
*[`src/BloomExe/Edit/EditingView.cs` line 611 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6219#-NjP-xc9C2V3SHGRdlHs:-NjP9dBL6L5IaGTOis8A:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/da56e65f1d0e1b8ac0c6e5bd59fd822ad077c8d3/src/BloomExe/Edit/EditingView.cs#L611)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think this now has more knowledge about images than we want in `EditingView`. Move to `ImageUtils`?
</blockquote></details>

Done.
___
*[`src/BloomExe/Edit/PageEditingModel.cs` line 61 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6219#-NjP06a4EtGJWGZBIDc8:-NjP9eYw2P9GWXz0KAnm:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/da56e65f1d0e1b8ac0c6e5bd59fd822ad077c8d3/src/BloomExe/Edit/PageEditingModel.cs#L61)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think this now has more knowledge about images than we want in `PageEditingModel`. Move to `ImageUtils`?
</blockquote></details>

Done.
___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 388 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6219#-NjP0Dk_4em1Drjo1IgF:-NjPVUHPBZbgXwQOOMx5:b-xe7nx1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/da56e65f1d0e1b8ac0c6e5bd59fd822ad077c8d3/src/BloomExe/ImageProcessing/ImageUtils.cs#L388)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I notice there is a `RunGraphicsMagick()`. Why isn't that called everywhere, including here
</blockquote></details>

I've rewritten the method to handle all the use cases.
___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 1046 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6219#-NjP0cEsA-DtrmdGvBj7:-NjPVap90ZwgHu6z5ok0:bkk7pu8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/da56e65f1d0e1b8ac0c6e5bd59fd822ad077c8d3/src/BloomExe/ImageProcessing/ImageUtils.cs#L1046)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Why does this require a `graphicsMagickPath` parameter?
</blockquote></details>

I've removed that parameter.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r3, all commit messages.
> Dismissed @hatton from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6219)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 1208 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6219#-NjrUQNbE5P7p-yJT8Cm:-NjrUQNbE5P7p-yJT8Cn:b-mq758v) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/90305dcaccdbde1d41ea9e08646707b58b14d5e7/src/BloomExe/ImageProcessing/ImageUtils.cs#L1208)):*
> ```Smalltalk
> 					var options = new GraphicsMagickOptions
> 					{
> 						Size = new Size(0,0),    // new Size(image.Image.Width, image.Image.Height) ?
> ```

Are you still unsure if it is better to send in image.Image's size?
If not, should we go ahead and remove the comment?
Otherwise, should we expand it?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6219)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 1208 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6219#-NjrUQNbE5P7p-yJT8Cm:-NkH4WRX41UMWsmiFzOv:bnxrjhb) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/90305dcaccdbde1d41ea9e08646707b58b14d5e7/src/BloomExe/ImageProcessing/ImageUtils.cs#L1208)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Are you still unsure if it is better to send in image.Image's size?
If not, should we go ahead and remove the comment?
Otherwise, should we expand it?
</blockquote></details>

I've revised the comment to explain in English that size=(0,0) means no scaling.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6219)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton)

**Pull request merged**
