### PR TITLE
Get Bloom output to pass epubcheck (BL-6046)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2446)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Mostly looks good. But, sorry, EpubMaker is one part of Bloom that is fairly comprehensively unit tested, so I'd like this new functionality to be, too. For some obscure reason the tests ended up in ExportEpubTests (see also ExportEpubWithLinksTests for what I think is an elegant way to do one export, but make a lot of independent unit tests of checking various outcomes) rather than EpubMakerTests.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/BloomBrowserUI/bookLayout/basePage.less, line 598 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2446#-LDmwXWyBMHmrT3YzfeI:-LDmwXWyBMHmrT3YzfeJ:b-294kgz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/039228353e4de506983e412c58db7a5524f4e891/src/BloomBrowserUI/bookLayout/basePage.less#L598)):*
> ```Less
>         height: 100%;
>         top:0;
>         
> ```

Blank line with trailing spaces here...something we try to avoid.

---

*[src/BloomBrowserUI/ePUB/baseEPUB.less, line 49 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2446#-LDmvopG5M0tBmbq-sVV:-LDmvopH9dM9IvGar9Rb:b-a662gm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/039228353e4de506983e412c58db7a5524f4e891/src/BloomBrowserUI/ePUB/baseEPUB.less#L49)):*
> ```Less
>         top:0;
>         
>         //position: absolute;
> ```

Does it work without position: absolute?
If so, we don't need to move and duplicate all this, just remove position: absolute.
If not, no point in having a set of rules in baseEPUB that is neither used nor correct.
I'd favor simply moving it to basePage.less, and putting a note that if we ever want to show them like this in epubs, we'll need to find an alternative to position: absolute.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1312 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2446#-LDmxyhwEL_B4MViEfAK:-LDmxyhwEL_B4MViEfAL:b-jk5ftj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/039228353e4de506983e412c58db7a5524f4e891/src/BloomExe/Publish/Epub/EpubMaker.cs#L1312)):*
> ```Smalltalk
> 		private void CheckForEpubProperties (HtmlDom pageDom, string filename)
> 		{
> 			// check for any script elements in the DOM
> ```

I find myself wondering whether some of these should be removed rather than triggering setting a flag. Of course many of them probably never occur in Bloom books. But do we EVER actually want a script to execute in a book? Of course we might one day...so I guess this is OK...just thought I'd check whether you considered that option.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2446#-:-LDmyZgs7ka16dE9RJXq:b-ifongv)*

**Comment by StephenMcConnel** [comment]
I refactored the test I created for checking accessibility improvments to create a new test class with multiple smaller tests and then added a few more tests for the epub validity checker fixes.

---

Review status: 1 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookLayout/basePage.less, line 598 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2446#-LDmwXWyBMHmrT3YzfeI:-LDnCmxtEJovofLwD74m:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/039228353e4de506983e412c58db7a5524f4e891/src/BloomBrowserUI/bookLayout/basePage.less#L598)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Blank line with trailing spaces here...something we try to avoid.
</blockquote></details>

Done.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1312 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2446#-LDmxyhwEL_B4MViEfAK:-LDn3A1-2PnoaKghI4aa:b-fouxds) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/039228353e4de506983e412c58db7a5524f4e891/src/BloomExe/Publish/Epub/EpubMaker.cs#L1312)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I find myself wondering whether some of these should be removed rather than triggering setting a flag. Of course many of them probably never occur in Bloom books. But do we EVER actually want a script to execute in a book? Of course we might one day...so I guess this is OK...just thought I'd check whether you considered that option.
</blockquote></details>

I don't think we'll actually see any <script> or <svg> elements in the Bloom book by the time we get to this check.  But I put the checks in the code in case this ever changes.  (The applies to all but one of the event attributes -- "onerror" is the only one I've seen in any of the files.)

---

*[src/BloomBrowserUI/ePUB/baseEPUB.less, line 49 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2446#-LDmvopG5M0tBmbq-sVV:-LDnAejx2fwIqWr72gNM:b-u7m893) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/039228353e4de506983e412c58db7a5524f4e891/src/BloomBrowserUI/ePUB/baseEPUB.less#L49)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Does it work without position: absolute?
If so, we don't need to move and duplicate all this, just remove position: absolute.
If not, no point in having a set of rules in baseEPUB that is neither used nor correct.
I'd favor simply moving it to basePage.less, and putting a note that if we ever want to show them like this in epubs, we'll need to find an alternative to position: absolute.
</blockquote></details>

No, it doesn't.  The text shows up in the right place horizontally, but displaced below the picture vertically.  I'm not sure how you would go about trying to show it like this in ePUBs, or why you would want to since this is an editing view.  So I'll Just not add this block to baseEPUB.less, and add to the comment here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2446#-:-LDsND3w4Hh9l5rq7k9C:b-s45t1m)*

**Comment by JohnThomson** [comment]
Nice work. Unless you think any of the moved stuff changed in ways that deserve my attention, this looks good to merge.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/BloomTests/Publish/ExportEpubTests.cs, line 134 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2446#-LEFTP_L2eLKdQyjQj0-:-LEFTP_MAx7oIK-2tF3s:b-6mlb48) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1312820cc87caa333fe0bb33c6c506df9395ed99/src/BloomTests/Publish/ExportEpubTests.cs#L134)):*
> ```Smalltalk
> 		}
> 
> 		private void CheckBasicsInManifest(params string[] imageFiles)
> ```

I assume all this 'deleted' stuff was actually moved?

---

*[src/BloomTests/Publish/ExportEpubTestsBaseClass.cs, line 312 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2446#-LEFT_lI86pD5aceLMpd:-LEFT_lJ5y03xBzFb7Op:bygcryi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/882b57d1e11874eac276cc0adc168b7eb7669cb0/src/BloomTests/Publish/ExportEpubTestsBaseClass.cs#L312)):*
> ```Smalltalk
> 		}
> 
> 		protected void CheckBasicsInPage(params string[] images)
> ```

I haven't reviewed this...assuming most of it was moved unchanged?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2446#-:-LEFTr37BVHH61_hCet6:bbwtfv)*

**Comment by StephenMcConnel** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomTests/Publish/ExportEpubTests.cs, line 134 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2446#-LEFTP_L2eLKdQyjQj0-:-LEFVq1m2FTTh6raI-tu:b-3n396q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1312820cc87caa333fe0bb33c6c506df9395ed99/src/BloomTests/Publish/ExportEpubTests.cs#L134)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I assume all this 'deleted' stuff was actually moved?
</blockquote></details>

yes, moved to the base class unchanged to share more widely.

---

*[src/BloomTests/Publish/ExportEpubTestsBaseClass.cs, line 312 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2446#-LEFT_lI86pD5aceLMpd:-LEFVuEu5Pe28Q3ESCGf:bk7r1i3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/882b57d1e11874eac276cc0adc168b7eb7669cb0/src/BloomTests/Publish/ExportEpubTestsBaseClass.cs#L312)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I haven't reviewed this...assuming most of it was moved unchanged?
</blockquote></details>

yes, moved to the base class unchanged to the base class to share more widely.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2446)*

**Pull request merged**
