### PR TITLE
Add color chooser to style dialog (BL-7859)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
- - -
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[`DistFiles/localization/en/Bloom.xlf` line 1499 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N8z4O28ETX7rUEW0s6F:-N8z4O28ETX7rUEW0s6G:bycjgn3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/51e16616f52aec4a88fded54cbd7a743a7c51a5f/DistFiles/localization/en/Bloom.xlf#L1499)):*
> ```XML
>             </trans-unit>
>             <trans-unit id="EditTab.FormatDialog.Color" sil:dynamic="true">
>                 <source xml:lang="en">Color</source>
> ```

"Color" is probably a common string; if it isn't already available under our "common" namespace, can you move this one there? Thanks.
___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.pug` line 47 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N8z4flx3zDn1JJvXMu2:-N8z4flx3zDn1JJvXMu3:b32fpap) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/51e16616f52aec4a88fded54cbd7a743a7c51a5f/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.pug#L47)):*
> ```Pug
> 							#italic.iconLetter(style="font-weight:italic") I
> 							#underline.iconLetter(style="text-decoration: underline") U
> 					.mainBlock.rightBlock(style="margin-top:15px")
> ```

I'm not clear why we have styles in StyleEditor.less *and* inline here?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[`DistFiles/localization/en/Bloom.xlf` line 1499 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N8z4O28ETX7rUEW0s6F:-N8zaNeqDGlfZ-rd2hIX:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/51e16616f52aec4a88fded54cbd7a743a7c51a5f/DistFiles/localization/en/Bloom.xlf#L1499)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

"Color" is probably a common string; if it isn't already available under our "common" namespace, can you move this one there? Thanks.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.pug` line 47 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N8z4flx3zDn1JJvXMu2:-N8zcJ_t3mAIXNUUp3VB:b2m0r21) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/51e16616f52aec4a88fded54cbd7a743a7c51a5f/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.pug#L47)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I'm not clear why we have styles in StyleEditor.less *and* inline here?
</blockquote></details>

I moved the styles all to inline in the pug.  The margin-top setting is inline because it is parallel to the inline setting for .mainBlock.leftBlock a few lines above this location.

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts` line 28 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N8z4v4Z6p-b2uoeuGYq:-N8z4v4Z6p-b2uoeuGYr:buy56d7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/51e16616f52aec4a88fded54cbd7a743a7c51a5f/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L28)):*
> ```XML
> import { ISwatchDefn } from "../../react_components/colorSwatch";
> import { IColorPickerDialogProps } from "../../react_components/colorPickerDialog";
> import { getSwatchFromBubbleSpecColor } from "../toolbox/overlay/overlayToolColorHelper";
> ```

Having to import from 4 different places to add one control smells of a true "component" waiting to be born :-)
___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts` line 1035 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N91jbRZ-pMsY5cZBcm_:-N91jbRZ-pMsY5cZBcma:b-syfv4k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1586e49b79e630cfadf85ae97d9cd012df2c89bc/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L1035)):*
> ```XML
>                             "/bloom/bookEdit/StyleEditor/StyleEditor.html"
>                         ),
>                         axios.get("/bloom/api/i18n/translate", {
> ```

It's not clear to me that this is faster in parallel in our situation, but this higher level call also returns a promise`theOneLocalizationManager.asyncGetTextInLang()`.

**Review by hatton — COMMENTED** [review]
Can we make the chooser about 6 pixels shorter, so that it's about the same height as the bold/italic/underline buttons?

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-:-N9259Im05Vaus9r_D6D:b-h4liox)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @hatton and @StephenMcConnel)

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts` line 2098 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N92RBwI7TAMg0I7d3z6:-N92RBwI7TAMg0I7d3z7:bkig95p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1586e49b79e630cfadf85ae97d9cd012df2c89bc/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L2098)):*
> ```XML
>             initialColor: textColorSwatch,
>             defaultSwatchColors: [
>                 { name: "black", colors: ["black"], opacity: 1 },
> ```

Steve here's some colors:
                { name: "black", colors: ["black"], opacity: 1 },
                { name: "white", colors: ["white"], opacity: 1 },
                // red to purple
                { name: "unused", colors: ["#ff1616"], opacity: 1 },
                { name: "unused", colors: ["#ff5757"], opacity: 1 },
                { name: "unused", colors: ["#ff66c4"], opacity: 1 },
                { name: "unused", colors: ["#cb6ce6"], opacity: 1 },
                { name: "unused", colors: ["#8c52ff"], opacity: 1 },
                // teal to blue
                { name: "unused", colors: ["#03989e"], opacity: 1 },
                { name: "unused", colors: ["#00c2cb"], opacity: 1 },
                { name: "unused", colors: ["#5ce1e6"], opacity: 1 },
                { name: "unused", colors: ["#5271ff"], opacity: 1 },
                { name: "unused", colors: ["#004aad"], opacity: 1 },
                // green to orange
                { name: "unused", colors: ["#007f37"], opacity: 1 },
                { name: "unused", colors: ["#7ed957"], opacity: 1 },
                { name: "unused", colors: ["#c9e265"], opacity: 1 },
                { name: "unused", colors: ["#ffde59"], opacity: 1 },
                { name: "unused", colors: ["#ff914d"], opacity: 1 }

You may need to put these elsewhere though, in order for these to be the default set that is shared with Overlay text. Bonus points for making ckeditor use whatever the user's palette is (i.e., when you select a word, the choices it gives you).



_Code quote:_
```XML
"
```

**Review by StephenMcConnel — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-:-N92LBe0BrN0I-jwh7_t:b-896fix)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @hatton)

___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts` line 28 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N8z4v4Z6p-b2uoeuGYq:-N92VhhN0Il2nFBfR1RM:b8nbeuo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/51e16616f52aec4a88fded54cbd7a743a7c51a5f/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L28)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Having to import from 4 different places to add one control smells of a true "component" waiting to be born :-)
</blockquote></details>

I've reduced the import from 2 different places: colorSwatch and colorPickerDialog by refactoring the basic guts of the color->swatch method and eliminating the unnecessary step of going through getEditTabBundleExports().
___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts` line 1035 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N91jbRZ-pMsY5cZBcm_:-N92LyMA90PRxQ2LUFDs:b-5o7289) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1586e49b79e630cfadf85ae97d9cd012df2c89bc/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L1035)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

It's not clear to me that this is faster in parallel in our situation, but this higher level call also returns a promise`theOneLocalizationManager.asyncGetTextInLang()`.
</blockquote></details>

theOneLocalizationManager.asyncGetTextInLang() returns a JQueryPromise<any>.
axios.get() returns Promise<AxiosResponse<any>>.  The axios.all expects the latter, and is not compatible with the former.
___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts` line 2098 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N92RBwI7TAMg0I7d3z6:-N92Z1haBIEUqVktm8PU:b5izre5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1586e49b79e630cfadf85ae97d9cd012df2c89bc/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L2098)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Steve here's some colors:
                { name: "black", colors: ["black"], opacity: 1 },
                { name: "white", colors: ["white"], opacity: 1 },
                // red to purple
                { name: "unused", colors: ["#ff1616"], opacity: 1 },
                { name: "unused", colors: ["#ff5757"], opacity: 1 },
                { name: "unused", colors: ["#ff66c4"], opacity: 1 },
                { name: "unused", colors: ["#cb6ce6"], opacity: 1 },
                { name: "unused", colors: ["#8c52ff"], opacity: 1 },
                // teal to blue
                { name: "unused", colors: ["#03989e"], opacity: 1 },
                { name: "unused", colors: ["#00c2cb"], opacity: 1 },
                { name: "unused", colors: ["#5ce1e6"], opacity: 1 },
                { name: "unused", colors: ["#5271ff"], opacity: 1 },
                { name: "unused", colors: ["#004aad"], opacity: 1 },
                // green to orange
                { name: "unused", colors: ["#007f37"], opacity: 1 },
                { name: "unused", colors: ["#7ed957"], opacity: 1 },
                { name: "unused", colors: ["#c9e265"], opacity: 1 },
                { name: "unused", colors: ["#ffde59"], opacity: 1 },
                { name: "unused", colors: ["#ff914d"], opacity: 1 }

You may need to put these elsewhere though, in order for these to be the default set that is shared with Overlay text. Bonus points for making ckeditor use whatever the user's palette is (i.e., when you select a word, the choices it gives you).
</blockquote></details>

If these colors are for text, shouldn't the two gray colors appear between black and white?  I copied the four colors of black to white from what overlay uses for the text color.  (I see now that I should have just imported the definition of defaultTextColors along with the method from overlayToolColorHelper.)

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319)* status: 1 of 7 files reviewed, 4 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts` line 1035 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N91jbRZ-pMsY5cZBcm_:-N97MP1N6i0KKX_H2WgP:bhi6xmb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1586e49b79e630cfadf85ae97d9cd012df2c89bc/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L1035)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

theOneLocalizationManager.asyncGetTextInLang() returns a JQueryPromise<any>.
axios.get() returns Promise<AxiosResponse<any>>.  The axios.all expects the latter, and is not compatible with the former.
</blockquote></details>

Since we already have a higher level file for doing this stuff in theOneLocalizationManager, go ahead an put your call there.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319)* status: 1 of 7 files reviewed, 4 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts` line 2098 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N92RBwI7TAMg0I7d3z6:-N97Mg-m07JL6kbSuj6J:byd2jz4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1586e49b79e630cfadf85ae97d9cd012df2c89bc/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L2098)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

If these colors are for text, shouldn't the two gray colors appear between black and white?  I copied the four colors of black to white from what overlay uses for the text color.  (I see now that I should have just imported the definition of defaultTextColors along with the method from overlayToolColorHelper.)
</blockquote></details>

I couldn't think of a place where I would want people to use grey text, but maybe that's a failure of imagination?

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319)* status: 1 of 7 files reviewed, 4 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts` line 1035 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N91jbRZ-pMsY5cZBcm_:-N97NAXK0Dud66-81gcy:b-iqrbjr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1586e49b79e630cfadf85ae97d9cd012df2c89bc/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L1035)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Since we already have a higher level file for doing this stuff in theOneLocalizationManager, go ahead an put your call there.
</blockquote></details>

Oh I see you did that now.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319)* status: 1 of 7 files reviewed, 7 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[`src/BloomBrowserUI/react_components/colorSwatch.tsx` line 98 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N97NQE76ka0oUoljO1T:-N97NQE8Cee8cdcKCM0k:b-9onoyl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91cd538c630134975b17f01515bf832923d3ec6/src/BloomBrowserUI/react_components/colorSwatch.tsx#L98)):*
> ```XML
> };
> 
> export const defaultSwatchColors: ISwatchDefn[] = [
> ```

I don't understand why we have two hard-coded lists still, here & in `launchColorPicker`
___
*[`src/BloomBrowserUI/react_components/colorSwatch.tsx` line 101 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N97NIAyCV5Fa96gEFZw:-N97NIAyCV5Fa96gEFZx:b-oygudi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91cd538c630134975b17f01515bf832923d3ec6/src/BloomBrowserUI/react_components/colorSwatch.tsx#L101)):*
> ```XML
>     // black to white
>     { name: "black", colors: ["black"], opacity: 1 },
>     { name: "gray", colors: ["gray"], opacity: 1 },
> ```

can remove the grays
___
*[`src/BloomBrowserUI/react_components/colorSwatch.tsx` line 107 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N97Na2w1TQ4MAfwTiMP:-N97Na2w1TQ4MAfwTiMQ:b-1jtijc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91cd538c630134975b17f01515bf832923d3ec6/src/BloomBrowserUI/react_components/colorSwatch.tsx#L107)):*
> ```XML
>     { name: "unused", colors: ["#ff1616"], opacity: 1 },
>     { name: "unused", colors: ["#ff5757"], opacity: 1 },
>     { name: "unused", colors: ["#ff66c4"], opacity: 1 },
> ```

I don't see the value of the "name". Can that be removed from ISwatchDefn? It would be clean to have this list simply be an array of strings, not this big structure.

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319)* status: 3 of 9 files reviewed, 6 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts` line 28 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N8z4v4Z6p-b2uoeuGYq:-N984YeqDC5P7FhZWzYe:b-r6joqs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/51e16616f52aec4a88fded54cbd7a743a7c51a5f/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L28)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I've reduced the import from 2 different places: colorSwatch and colorPickerDialog by refactoring the basic guts of the color->swatch method and eliminating the unnecessary step of going through getEditTabBundleExports().
</blockquote></details>

Let's go farther: I can't see any reason for clients of `showColorPickerDialog` to know anything about swatches.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319)* status: 3 of 9 files reviewed, 6 unresolved discussions (waiting on @hatton)

___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts` line 28 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N8z4v4Z6p-b2uoeuGYq:-N98Or6w2rVNl2VDstcO:b-lfyf5a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/51e16616f52aec4a88fded54cbd7a743a7c51a5f/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L28)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Let's go farther: I can't see any reason for clients of `showColorPickerDialog` to know anything about swatches.
</blockquote></details>

IColorPickerDialogProps has three members that use ISwatchDefn: initialColor, defaultSwatchColors, and onChange.  I suppose I could define a ISimpleColorPickerProps and a showSimpleColorPickerDialog that translate from simple color strings to swatches and back again as part of colorPickerDialog.tsx.  I'm sure there's a reason why the full colorPickerDialog uses swatches, but we could provide a simpler interface to it.
Which I've now done.
___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts` line 2098 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N92RBwI7TAMg0I7d3z6:-N98N89k36aZ7fs7aiEG:b-iqc1ry) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1586e49b79e630cfadf85ae97d9cd012df2c89bc/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L2098)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I couldn't think of a place where I would want people to use grey text, but maybe that's a failure of imagination?
</blockquote></details>

I can remove them.
___
*[`src/BloomBrowserUI/react_components/colorSwatch.tsx` line 98 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N97NQE76ka0oUoljO1T:-N98_UHv-KdsiYF3UdoF:b-hgxqbp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91cd538c630134975b17f01515bf832923d3ec6/src/BloomBrowserUI/react_components/colorSwatch.tsx#L98)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I don't understand why we have two hard-coded lists still, here & in `launchColorPicker`
</blockquote></details>

I don't understand this comment.
___
*[`src/BloomBrowserUI/react_components/colorSwatch.tsx` line 101 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N97NIAyCV5Fa96gEFZw:-N98Yh69B0-JFI1TdRh3:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91cd538c630134975b17f01515bf832923d3ec6/src/BloomBrowserUI/react_components/colorSwatch.tsx#L101)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

can remove the grays
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/react_components/colorSwatch.tsx` line 107 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N97Na2w1TQ4MAfwTiMP:-N98Yl3GCc4jQKfi0grZ:bu69xk2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91cd538c630134975b17f01515bf832923d3ec6/src/BloomBrowserUI/react_components/colorSwatch.tsx#L107)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I don't see the value of the "name". Can that be removed from ISwatchDefn? It would be clean to have this list simply be an array of strings, not this big structure.
</blockquote></details>

ISwatchDefn supports color gradients, which aren't used in the text color chooser but are used in the background color chooser for the overlay tool.  The *name* field may be superfluous, but the colors (array) and opacity fields are needed to support gradients.  It's pretty easy to map between an array of color strings and an array of ISwatchDefn structs that are all opaque with a single color.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319)* status: 3 of 9 files reviewed, 6 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[`src/BloomBrowserUI/react_components/colorSwatch.tsx` line 98 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N97NQE76ka0oUoljO1T:-N9bKcr23q1WKUwMf2RZ:bxxs1xj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91cd538c630134975b17f01515bf832923d3ec6/src/BloomBrowserUI/react_components/colorSwatch.tsx#L98)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I don't understand this comment.
</blockquote></details>

I've written up https://issues.bloomlibrary.org/youtrack/issue/BL-11433/Add-palette-enum-to-ColorPickerDialog which I think will clarify for you. For now, for this card, you can simply remove the `defaultColorPalette` prop from ` ISimpleColorPickerDialogProps`. The current *consumer* of that value can just use our one default palette... no need for client to give it to them.



_Code quote (from src/BloomBrowserUI/react_components/colorPickerDialog.tsx):_
```XML
defaultColorPalette: string[];
```

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319)* status: 1 of 9 files reviewed, 6 unresolved discussions (waiting on @hatton)

___
*[`src/BloomBrowserUI/react_components/colorSwatch.tsx` line 98 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319#-N97NQE76ka0oUoljO1T:-N9cmPoeCPbEP-nQ_2Xc:bb7f2mf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91cd538c630134975b17f01515bf832923d3ec6/src/BloomBrowserUI/react_components/colorSwatch.tsx#L98)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I've written up https://issues.bloomlibrary.org/youtrack/issue/BL-11433/Add-palette-enum-to-ColorPickerDialog which I think will clarify for you. For now, for this card, you can simply remove the `defaultColorPalette` prop from ` ISimpleColorPickerDialogProps`. The current *consumer* of that value can just use our one default palette... no need for client to give it to them.
</blockquote></details>

done

**Review by hatton — COMMENTED** [review]
> Reviewed 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319)* status: 5 of 9 files reviewed, 6 unresolved discussions (waiting on @hatton)

**Pull request merged**
