### PR TITLE
Handle the Team Collection being unavailable (BL-9748)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4326)

### CODE REVIEW

**Review by hatton — COMMENTED** [review]
> Reviewed 5 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4326)* status: 5 of 20 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4326#-MXXC2ti4FG7wia2L_cF:-MXXC2ti4FG7wia2L_cG:b8jhelg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e2a6448c8343b420b38f4bd6785de533b803bff/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L36)):*
> ```Smalltalk
> 		// and launching the TC dialog, are permitted and need it.
> 		// Also holds the DisconnectedTeamCollection when we can't connect
> 		public TeamCollection CurrentCollectionEvenIfDisabled { get; private set; }
> ```

Is there a difference between "Disabled" and "Disconnected"?

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 11 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4326)* status: 16 of 20 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 155 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4326#-MXXDK4X20Pl9pfq6SHC:-MXXDK4X20Pl9pfq6SHD:b3jgu0y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e2a6448c8343b420b38f4bd6785de533b803bff/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L155)):*
> ```Smalltalk
> 							if (!DropboxUtils.IsDropboxProcessRunning)
> 							{
> 								MakeDisconnected(repoFolderPath, "TeamCollection.NeedDropboxRunning",
> ```

It's tricky, but maybe we can split this up so that there is less translation to do for various situations, and targets other than Dropbox.  

"Dropbox does not appear to be running." / "Bloom cannot reach Dropbox.com" / "Bloom cannot find ...."

"When you have resolved this problem, please restart Bloom. Until then, your Team Collection will operate in “Disconnected” mode."

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 2 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4326)* status: 18 of 20 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Utils/DropboxUtils.cs, line 41 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4326#-MXXFoXE7ToueyA1PBmY:-MXXFoXE7ToueyA1PBmZ:b9raeej) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e2a6448c8343b420b38f4bd6785de533b803bff/src/BloomExe/Utils/DropboxUtils.cs#L41)):*
> ```Smalltalk
> 				{
> 					var json = RobustFile.ReadAllText(fixedPath, Encoding.UTF8);
> 					foreach (var match in new Regex("\\\"path\\\":\\s*\\\"(.*?)\\\"").Matches(json).Cast<Match>())
> ```

Not clear why this uses regex to parse json? We have json parsers around, and they are much easier to read and write?

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 2 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4326)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 128 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4326#-MXXGE8I1y0tUiYB5PLj:-MXXGE8I1y0tUiYB5PLk:bxf0th9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e2a6448c8343b420b38f4bd6785de533b803bff/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L128)):*
> ```Smalltalk
> 			});
> 			var impersonatePath = Path.Combine(_localCollectionFolder, "impersonate.txt");
> 			if (File.Exists(impersonatePath))
> ```

`RobustFile.Exists()`
___
*[src/BloomExe/Utils/DropboxUtils.cs, line 29 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4326#-MXXGWXL6nVmZU5lcQOn:-MXXGWXL6nVmZU5lcQOo:bcpsv30) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e2a6448c8343b420b38f4bd6785de533b803bff/src/BloomExe/Utils/DropboxUtils.cs#L29)):*
> ```Smalltalk
> 		/// though it isn't precisely accurate.
> 		/// </summary>
> 		public static bool IsPathInDropboxFolder(string path)
> ```

What happens if there is an exception in here? Even RobustFIle.Exists can throw.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4326)* status: 14 of 20 files reviewed, 5 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4326#-MXXC2ti4FG7wia2L_cF:-MXXdXNv3ueUyzbknwqV:b-hchzjd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e2a6448c8343b420b38f4bd6785de533b803bff/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L36)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is there a difference between "Disabled" and "Disconnected"?
</blockquote></details>

In my head there is, but I think it's better to use only one of them in method and class names, because there currently is not in practice. I've tried to clear it up.
___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 128 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4326#-MXXGE8I1y0tUiYB5PLj:-MXXJLnJ5Ps9BaXx4Je7:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e2a6448c8343b420b38f4bd6785de533b803bff/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L128)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

`RobustFile.Exists()`
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 155 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4326#-MXXDK4X20Pl9pfq6SHC:-MXXQ057-X2o8MN9pS9l:bavoovd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e2a6448c8343b420b38f4bd6785de533b803bff/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L155)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

It's tricky, but maybe we can split this up so that there is less translation to do for various situations, and targets other than Dropbox.  

"Dropbox does not appear to be running." / "Bloom cannot reach Dropbox.com" / "Bloom cannot find ...."

"When you have resolved this problem, please restart Bloom. Until then, your Team Collection will operate in “Disconnected” mode."
</blockquote></details>

Done. (A bit awkward for the one where the folder is not found and there are two possible corrective actions.)
___
*[src/BloomExe/Utils/DropboxUtils.cs, line 29 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4326#-MXXGWXL6nVmZU5lcQOn:-MXXXpB_B3j0AZ9-2D3k:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e2a6448c8343b420b38f4bd6785de533b803bff/src/BloomExe/Utils/DropboxUtils.cs#L29)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

What happens if there is an exception in here? Even RobustFIle.Exists can throw.
</blockquote></details>

Done.
___
*[src/BloomExe/Utils/DropboxUtils.cs, line 41 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4326#-MXXFoXE7ToueyA1PBmY:-MXX_GTP6gtkoXsJdX5G:by9w0ya) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e2a6448c8343b420b38f4bd6785de533b803bff/src/BloomExe/Utils/DropboxUtils.cs#L41)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Not clear why this uses regex to parse json? We have json parsers around, and they are much easier to read and write?
</blockquote></details>

Bit of a toss-up. I'm still marginally inclined to go with the REegex. Added a comment.

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4326)* status: 18 of 20 files reviewed, 4 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 202 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4326#-MXYYba09kq09hxkQLv_:-MXYYba09kq09hxkQLva:b-exwuhb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/79e2fc19ea08cbda4c84ce04fd0ed6255e0efe3e/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L202)):*
> ```Smalltalk
> 					{
> 						MakeDisconnected( repoFolderPath, "TeamCollection.MissingRepo",
> 							"Bloom could not find the team collection folder at '{0}'. If that drive or network is disconnected, re-connect it. If you have moved where that folder is located, 1) quit Bloom 2) go to the Team Collection folder and double-click “Join this Team Collection”.", repoFolderPath, Environment.NewLine);
> ```

Capitalization of "team collection"

**Review by hatton — COMMENTED** [review]
> Reviewed 1 of 6 files at r2, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4326)* status: 19 of 20 files reviewed, 3 unresolved discussions (waiting on @hatton and @JohnThomson)

**Pull request merged**
