### PR TITLE
Fix problem where current page is deleted before using it

### PR DESCRIPTION
**Pull request by JohnThomson**
The dispose of the previous current page was delayed until we had made a new one with the same key, which then got deleted.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3516)

### CODE REVIEW

**Review by jsubloom — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3516)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/web/BloomServer.cs, line 272 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3516#-LvpmhRu1lmdtk8pKPtb:-LvpmhRu1lmdtk8pKPtc:b-jtkz3s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/399e8c055b16133e6e1b99a6c1f85f7292eb4f41/src/BloomExe/web/BloomServer.cs#L272)):*
> ```Smalltalk
> 			lock (_theOneInstance._queue)
> 			{
> 				foreach (var item in _theOneInstance._idleTasks)
> ```

Optional:
If you're paranoid about nulls, you can check if either _idleTasks is null or if item is null.
If you think it's safe to assume they're non-null, that is fine too.
___
*[src/BloomExe/web/BloomServer.cs, line 1175 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3516#-Lvpn_nBC8O4n5OQkeq3:-Lvpn_nBC8O4n5OQkeq4:bqss5m0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/399e8c055b16133e6e1b99a6c1f85f7292eb4f41/src/BloomExe/web/BloomServer.cs#L1175)):*
> ```Smalltalk
> 					while (_busyThreads == 0 && _queue.Count == 0 && _idleTasks.Count > 0)
> 					{
> 						var task = _idleTasks.Dequeue();
> ```

Theoretically, the name of the local variable and the member variable should change... e.g. the subsequent line "idleTask = task.IdleTask" looks strange to me because the type of a "*task" is not consistently used in this line. I guess I would like task -> taskItem and _idleTasks -> _idleTaskItems better?
___
*[src/BloomExe/web/BloomServer.cs, line 1420 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3516#-LvpnuAVC2b6pGc_Z10u:-LvpnuAVC2b6pGc_Z10v:bpjws5s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/399e8c055b16133e6e1b99a6c1f85f7292eb4f41/src/BloomExe/web/BloomServer.cs#L1420)):*
> ```Smalltalk
> 		// (currently set when we add a new simulated page with the same
> 		// key as one we had queued for deletion but not yet deleted)
> 		public bool Aborted;
> ```

Optional: Maybe Cancelled, or CancellationRequested

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3516)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/web/BloomServer.cs, line 272 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3516#-LvpmhRu1lmdtk8pKPtb:-Lvppntp5xeWGONkfHZJ:b9lebn9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/399e8c055b16133e6e1b99a6c1f85f7292eb4f41/src/BloomExe/web/BloomServer.cs#L272)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Optional:
If you're paranoid about nulls, you can check if either _idleTasks is null or if item is null.
If you think it's safe to assume they're non-null, that is fine too.
</blockquote></details>

I think this is safe. There's no reason ever to push a null into the queue, and _idleTasks is initialized on declaration and marked readonly. 
___
*[src/BloomExe/web/BloomServer.cs, line 1175 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3516#-Lvpn_nBC8O4n5OQkeq3:-LvprISyDBqBW2_jEcLb:b-qwshjr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/399e8c055b16133e6e1b99a6c1f85f7292eb4f41/src/BloomExe/web/BloomServer.cs#L1175)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Theoretically, the name of the local variable and the member variable should change... e.g. the subsequent line "idleTask = task.IdleTask" looks strange to me because the type of a "*task" is not consistently used in this line. I guess I would like task -> taskItem and _idleTasks -> _idleTaskItems better?
</blockquote></details>

I did something a little different...don't like "Items" as part of a queue name...see what you think.
___
*[src/BloomExe/web/BloomServer.cs, line 1420 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3516#-LvpnuAVC2b6pGc_Z10u:-LvprPih-soavV_2wY9E:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/399e8c055b16133e6e1b99a6c1f85f7292eb4f41/src/BloomExe/web/BloomServer.cs#L1420)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Optional: Maybe Cancelled, or CancellationRequested
</blockquote></details>

Done.

**Review by jsubloom — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3516)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/web/BloomServer.cs, line 1413 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3516#-LvpsOk3EMg_oMoLmeG1:-LvpsOk3EMg_oMoLmeG2:b-ybpsos) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f22102adb654171bc7809c7d4d4b6001d5c9b5c9/src/BloomExe/web/BloomServer.cs#L1413)):*
> ```Smalltalk
> 		// The actual thing to do when idle
> 		// (currently typically to delete an obsolete simulated page)
> 		public Action WhatDoDo;
> ```

Spelling, should be "D" -> "T"

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3516)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/web/BloomServer.cs, line 1172 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3516#-LvpsYhK5velIqF4BR-b:-LvpsYhK5velIqF4BR-c:b-ruiw2m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f22102adb654171bc7809c7d4d4b6001d5c9b5c9/src/BloomExe/web/BloomServer.cs#L1172)):*
> ```Smalltalk
> 				// here, we need a lock on _queue. Rather than messing with two lock objects, I decided
> 				// to let _queue be used as a lock object for all access to either queue.)
> 				Action whatToDo = null;
> ```

Very Optional: Or action, or actionToDO?

**Review by jsubloom — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3516)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

**Review by jsubloom — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3516)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by jsubloom — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3516)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by jsubloom — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3516#-:-Lvpu9D47oFS-xncHytY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by jsubloom — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3516)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
