### PR TITLE
BL-5892 Put image description in alt text attr

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2372)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[src/BloomExe/Book/Book.cs, line 967 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2372#-LBcEMV28Z6Vsx2sej52:-LBcEMV28Z6Vsx2sej53:bfe1ege) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/51745556fdc976272b40daeba3f7cea01cc86816/src/BloomExe/Book/Book.cs#L967)):*
> ```Smalltalk
> 			UpdateTextsNewlyChangedToRequiresParagraph(bookDOM);
> 
> 			bookDOM.SetImageAltAttrsFromDescriptions(_collectionSettings.Language1Iso639Code);
> ```

I'm wondering why we are duplicating this text in the saved version of the book, rather than as part of the publication process.  Can you explain that in a comment?

---

*[src/BloomExe/Book/Book.cs, line 2041 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2372#-LBcEnShClGqNh6vQDnm:-LBcEnShClGqNh6vQDnn:b-40zqyn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/51745556fdc976272b40daeba3f7cea01cc86816/src/BloomExe/Book/Book.cs#L2041)):*
> ```Smalltalk
> 
> 				HtmlDom.ProcessPageAfterEditing(pageFromStorage, pageFromEditedDom);
> 				HtmlDom.SetImageAltAttrsFromDescriptions(pageFromStorage, _collectionSettings.Language1Iso639Code);
> ```

Same as my comment above

---

*[src/BloomExe/Book/HtmlDom.cs, line 1809 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2372#-LBcExxO0FGIxrQtkbja:-LBcExxO0FGIxrQtkbjb:b-upg75n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/51745556fdc976272b40daeba3f7cea01cc86816/src/BloomExe/Book/HtmlDom.cs#L1809)):*
> ```Smalltalk
> 						// a longdesc attr (does anything implement this?) or a separate link element whose 'alt'
> 						// indicates that it is a link to a long description. Not sure how that could work in an
> 						// epub, either.
> ```

If not already there, would be good for our benetech question list.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2372)*

**Comment by JohnThomson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Book/Book.cs, line 967 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2372#-LBcEMV28Z6Vsx2sej52:-LBfJLyK5eUZM4O4KAZi:bcmilqs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/51745556fdc976272b40daeba3f7cea01cc86816/src/BloomExe/Book/Book.cs#L967)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I'm wondering why we are duplicating this text in the saved version of the book, rather than as part of the publication process.  Can you explain that in a comment?
</blockquote></details>

I'm not sure I can. I don't recall even considering the other option, though once you point it out, it's obviously a reasonable alternative. I think I just assumed that, since we've concluded that this is the right thing to have in an accessible HTML document, we'd want it everywhere and always. I believe the relevant accessibility guidelines are part of WAC 2.0 which applies to HTML generally, not just epubs. But we don't have, or plan, anything that can take advantage of it while running Bloom or in any other kind of publication...though BloomReader might want it, as might a hypothetical book-reading extension to BloomLibrary. If there's a reason NOT to do it this way...e.g., if we need the old messages for slow-loading images while Bloom is running...I can redo it the other way. Or if you see any other reason to do it, for that matter. I don't think it would be much more or less difficult as long as we only want it for one kind of publication (except that this approach is already done, of course).

---

*[src/BloomExe/Book/HtmlDom.cs, line 1809 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2372#-LBcExxO0FGIxrQtkbja:-LBfLX2kEVWE0mOO7ad1:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/51745556fdc976272b40daeba3f7cea01cc86816/src/BloomExe/Book/HtmlDom.cs#L1809)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

If not already there, would be good for our benetech question list.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2372)*

**Comment by JohnThomson** [comment]
Decided to retarget PR on 4.1

**Comment by JohnThomson** [comment]
Sorry, closed wrong PR

**Pull request merged**
