### PR TITLE
First stage of talking book support

### PR DESCRIPTION
**Pull request by JohnThomson**
When we merge this, we will need to add new TC dependencies and use them to generate a new version of getDependencies (to add NAudio, and possibly Palaso.Media)

[Review on Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/801)

### CODE REVIEW

**Comment by hatton** [comment]
UI Review:

image

**Comment by hatton** [comment]
We should hide the source bubble when this is visible. It's easy to get the source on top:

image

**Comment by hatton** [comment]
Reviewed 19 of 29 files at r1, 23 of 29 files at r2.
Review status: 42 of 47 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[src/BloomBrowserUI/bookEdit/js/bloomBootstrap.js, line 38 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0l1N7HH5bWdojwLvkJ)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/bookEdit/js/bloomBootstrap.js#L38)):</sup>
Let's add a comment saying that this synphony stuff is being loaded all the time because we're using it to find sentences for audio recording


---

<sup>**[src/BloomExe/Edit/LameEncoder.cs, line 44 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0l2df80bOZj0zkHmu9)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomExe/Edit/LameEncoder.cs#L44)):</sup>
Let's change this id to a Bloom appropriate one. Also, the "to make mp3s" message made sense in context for HT, but not here.


---

<sup>**[src/BloomExe/Publish/EpubMaker.cs, line 222 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mG-gAylqedizMxNpX)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomExe/Publish/EpubMaker.cs#L222)):</sup>
If pageDom is part of a larger dom, this xpath will get more than you want. I think ".//" would be safer?


---

<sup>**[src/BloomExe/Publish/EpubMaker.cs, line 875 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mFbTHeaqHV0wmlIAr)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomExe/Publish/EpubMaker.cs#L875)):</sup>
How 'bout now :-)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801)

**Comment by hatton** [comment]
Reviewed 1 of 29 files at r2.
Review status: 43 of 47 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[src/BloomExe/Publish/EpubMaker.cs, line 196 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mITZ53gDEw5PIJcT5)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomExe/Publish/EpubMaker.cs#L196)):</sup>
This may be explained in some other file, but in this one, this was a bit of a puzzle. 
Where is this prepending done, and what is the semantics of it (since we are reading a number out of it, it must have some)?
Could comment that we are prepending an "i" because xml (and thus xhtml) requires you to start with a letter... worth a comment because modern html5 does not have that restriction.


---

<sup>**[src/BloomExe/Publish/EpubMaker.cs, line 223 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mGM6EGK7-p3Cl9EMb)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomExe/Publish/EpubMaker.cs#L223)):</sup>
Could we do this test now?


---

<sup>**[src/BloomTests/Book/ExportEpubTests.cs, line 741 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mPF1Gjcz_8BqQZwtY)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomTests/Book/ExportEpubTests.cs#L741)):</sup>
This is named like a test (well, it doesn't follow our conventions for unit tests, but it's at least an assertion). But there is no [test] attribute.

I'm required to complain about a such a monstexr test with 10 asserts, but but better that than none :-)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801)

**Comment by hatton** [comment]
Reviewed 3 of 29 files at r2.
Review status: 46 of 47 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

<sup>**[src/BloomBrowserUI/audio/audioRecording.less, line 10 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mQ1Docu5_MKxK895r)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.less#L10)):</sup>
can't guess what icon-red is


---

<sup>**[src/BloomBrowserUI/audio/audioRecording.less, line 47 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mQCTgltP1lc5vb6DY)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.less#L47)):</sup>
Soon these need to become real depressible buttons, which will remove the need for this hover styling. E.g. jquery.button().


---

<sup>**[src/BloomExe/Edit/AudioRecording.cs, line 243 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mQzuobahzjfNP9LlK)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomExe/Edit/AudioRecording.cs#L243)):</sup>
Please set all strings in this file to one that mirrors our UI hierarchy.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801)

**Comment by hatton** [comment]
Reviewed 1 of 29 files at r2.
Review status: all files reviewed at latest revision, 20 unresolved discussions, all commit checks successful.

---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 48 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mRXUX3XucxPWMnzk3)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L48)):</sup>
gulp. is the coding style for TS really to have lower case class names? I'll never get used to that.


---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 55 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mRr3a3yn-KboNUHQV)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L55)):</sup>
If nextSpan() changes state, let's make it a verb


---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 62 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mSBjBgXvHIt4D8w12)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L62)):</sup>
Typescript has enums. Could those be used for the state instead of strings?


---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 80 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mRvhF6zkRYom4vLd3)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L80)):</sup>
If prevSpan() changes state, let's make it a verb and remove the abbreviation


---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 178 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mSPkoGToEBk2NEQpb)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L178)):</sup>
Is it required to hard-code the port? Would "/bloom/audioDevices" work as well?


---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 206 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mSto2la-e6a5x2ujV)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L206)):</sup>
method needs a more descriptive name or a comment. I don't think it even wraps anything. It appears to instead create a button.

which needs a better name

text --> buttonLabel?

status --> statusClass?


---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 219 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mTcBXmiDAmdB8S7y7)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L219)):</sup>
Is this still true?


---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 232 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mTfQS4NfLPRyZrhxM)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L232)):</sup>
can remove hard code url


---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 355 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mUEcUvLlAJLjzqvci)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L355)):</sup>
I think it would help readability to add public/private/protected access modifiers.


---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 370 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mVRrMzmZZp1b5RgXj)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L370)):</sup>
It would be helpful to have all functions declare their return type


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801)

**Comment by JohnThomson** [comment]
I think all this is done. (Though note that Mike is interested in a VMS scenario where record-audio is used to make a direct audio-only translation of what's in the source bubble.)

At this point I have about six comments still to deal with. I decided to check in and publish comments on what I've fixed in case you want to take another look, especially at the UI.


---

Review status: 39 of 47 files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

<sup>**[src/BloomBrowserUI/audio/audioRecording.less, line 10 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mQ1Docu5_MKxK895r)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.less#L10)):</sup>
obsolete...removed


---

<sup>**[src/BloomBrowserUI/audio/audioRecording.less, line 47 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mQCTgltP1lc5vb6DY)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.less#L47)):</sup>
This styling applies to a popup list which you've probably never seen unless you managed to connect at least three input devices.


---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 48 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mRXUX3XucxPWMnzk3)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L48)):</sup>
https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines says PascalCase. I think we follow that about 50%. I fixed this one at least.


---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 55 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mRr3a3yn-KboNUHQV)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L55)):</sup>
Done ('moveToNextSpan')


---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 80 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mRvhF6zkRYom4vLd3)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L80)):</sup>
Done.


---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 206 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mSto2la-e6a5x2ujV)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L206)):</sup>
Renamed to makeHtmlForOneButtonGroup (and improved other names)


---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 219 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mTcBXmiDAmdB8S7y7)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L219)):</sup>
Removed.


---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 232 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mTfQS4NfLPRyZrhxM)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L232)):</sup>
Done.


---

<sup>**[src/BloomBrowserUI/bookEdit/js/bloomBootstrap.js, line 38 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0l1N7HH5bWdojwLvkJ)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/bookEdit/js/bloomBootstrap.js#L38)):</sup>
Done.


---

<sup>**[src/BloomExe/Edit/LameEncoder.cs, line 44 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0l2df80bOZj0zkHmu9)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomExe/Edit/LameEncoder.cs#L44)):</sup>
Good catch. Done.


---

<sup>**[src/BloomExe/Publish/EpubMaker.cs, line 196 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mITZ53gDEw5PIJcT5)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomExe/Publish/EpubMaker.cs#L196)):</sup>
I've added a comment, but am wondering whether I should change the audio recording code so it puts the extra 'i' in the filename, too.


---

<sup>**[src/BloomExe/Publish/EpubMaker.cs, line 222 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mG-gAylqedizMxNpX)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomExe/Publish/EpubMaker.cs#L222)):</sup>
Done.


---

<sup>**[src/BloomExe/Publish/EpubMaker.cs, line 223 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mGM6EGK7-p3Cl9EMb)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomExe/Publish/EpubMaker.cs#L223)):</sup>
Done.


---

<sup>**[src/BloomExe/Publish/EpubMaker.cs, line 875 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mFbTHeaqHV0wmlIAr)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomExe/Publish/EpubMaker.cs#L875)):</sup>
Done.


---

<sup>**[src/BloomTests/Book/ExportEpubTests.cs, line 741 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mPF1Gjcz_8BqQZwtY)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomTests/Book/ExportEpubTests.cs#L741)):</sup>
I've tried to improve the name (BookWithAudio_ProducesOverlay)...not sure I've got the convention straight. And of course added the [Test].
Should we have a team tutorial where you show us a better way to handle checking multiple things about the result of one action?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801)

**Comment by JohnThomson** [comment]
Review status: 37 of 47 files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 62 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mSBjBgXvHIt4D8w12)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L62)):</sup>
Done.


---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 178 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mSPkoGToEBk2NEQpb)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L178)):</sup>
Unfortunately not. That gets converted into a request that starts with the book folder. I'm not sure exactly how that happens.

I did move it to just one place in the file.


---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 355 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mUEcUvLlAJLjzqvci)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L355)):</sup>
Done.


---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 370 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mVRrMzmZZp1b5RgXj)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L370)):</sup>
Done.


---

<sup>**[src/BloomExe/Edit/AudioRecording.cs, line 243 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mQzuobahzjfNP9LlK)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomExe/Edit/AudioRecording.cs#L243)):</sup>
I made them EditTab.RecordingControl.X. Hope that's OK.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801)

**Comment by hatton** [comment]
Reviewed 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 178 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mSPkoGToEBk2NEQpb)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L178)):</sup>
Ok, so we could make the server understand a top-level "audioDevices" or whatever then. Still don't need to have this full-path hard-code at all.


---

<sup>**[src/BloomExe/Edit/LameEncoder.cs, line 44 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K1AO9frCsvji35It04A)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e528fc9dfea3b285d07a60206af75dbb9c3fb9c5/src/BloomExe/Edit/LameEncoder.cs#L44)):</sup>
Fix case on "Make"


---

<sup>**[src/BloomExe/Publish/EpubMaker.cs, line 196 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mITZ53gDEw5PIJcT5)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomExe/Publish/EpubMaker.cs#L196)):</sup>
Seems like a good idea, so that the ids "just match".


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801)

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 178 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mSPkoGToEBk2NEQpb)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L178)):</sup>
I'm not understanding "top level" in this context. I could conceivably make the server look for any URL that ENDS with 'audioDevices' or some name that's even less likely to occur in a file...sorry I don't know much yet about how ajax mangles the URL I give it.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801)

**Comment by JohnThomson** [comment]
Review status: 43 of 47 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[src/BloomBrowserUI/audio/audioRecording.ts, line 178 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mSPkoGToEBk2NEQpb)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomBrowserUI/audio/audioRecording.ts#L178)):</sup>
OK, fixed. /bloom/audioDevices works perfectly. I probably tried without the leading slash.


---

<sup>**[src/BloomExe/Edit/LameEncoder.cs, line 44 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K1AO9frCsvji35It04A)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e528fc9dfea3b285d07a60206af75dbb9c3fb9c5/src/BloomExe/Edit/LameEncoder.cs#L44)):</sup>
Done.


---

<sup>**[src/BloomExe/Publish/EpubMaker.cs, line 196 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801#-K0mITZ53gDEw5PIJcT5)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a62295cd6e6900b286e4ec5c2d8bea732ed9a4dd/src/BloomExe/Publish/EpubMaker.cs#L196)):</sup>
Done. (Note, however, that this will be a problem for publishing audio created with earlier versions of this PR; about 5/8 of recordings will not be published, unless you manually fix the file names and IDs in the HTML.)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801)

**Comment by hatton** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/801)

**Pull request merged**
