### PR TITLE
Add epub:type attributes where useful (BL-5893)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2366)

### CODE REVIEW

**Comment by StephenMcConnel** [comment]
It might be better to insert a section element to carry the epub:type attribute rather than putting it on the body element.  https://idpf.github.io/epub-guides/epub-aria-authoring/ says "Use of the epub:type attribute on the body element is now also strongly discouraged."

**Comment by hatton** [comment]
> "Use of the epub:type attribute on the body element is now also strongly discouraged."

Let's us obey, then :-)

**Comment by StephenMcConnel** [comment]
Adding section elements has been completed.

**Comment by JohnThomson** [comment]
Like almost everything else, this is tricky. Clearly they discourage putting epub:type on the body. But it's not clear to me that all these elements are legitimately 'sections'. For example, https://www.w3.org/TR/html/sections.html#the-section-element says "The section element is not a generic container element...A general rule is that the section element is appropriate only if the element’s contents would be listed explicitly in the document’s outline." and "Each section should be identified, typically by including a heading (h1-h6 element) as a child of the section element." We don't currently list most of these elements in TOC, and some (like "inside back cover") certainly shouldn't be. And hardly any of them have child headings. http://kb.daisy.org/publishing/docs/html/sections.html recommends using the aria-label attribute to identify the purpose of a section that lacks a heading. But then we already have epub:type which sort of does that. Maybe if we want to identify the epub:type of a page and 'section' is not appropriate we should just use 'div'?
Feel free to merge as-is and just add this comment to the list of benetech questions.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2366#-:-LBbL3bF4hDoc5EZxc9e:bvgf2mg)*

**Comment by StephenMcConnel** [comment]
I've added the comment (edited a bit) to the questions document.  I may well make the change to using either section or div in the work I'm doing for aria roles in BL-5894.

**Pull request merged**
