### PR TITLE
Tweak PDF output for full bleed pages (BL-11437)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Publish/PDF/PdfMaker.cs` line 75 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620#-NNlfe3G67hYRp2mrbuX:-NNlfe3G67hYRp2mrbuY:bij084o) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a441722141f48ba6f8b1cbd4da1e9347f48db0af/src/BloomExe/Publish/PDF/PdfMaker.cs#L75)):*
> ```Smalltalk
> 			{
> 				//var pgid = (string.IsNullOrEmpty(specs.PaperSizeName) ? "Custom" : specs.PaperSizeName) + (specs.Landscape ? "-L" : "-P");
> 				//RobustFile.Copy(specs.OutputPdfPath, Path.ChangeExtension(specs.OutputPdfPath, pgid + "-0.pdf"), true);
> ```

Any reason to keep this comment or the two below?
I guess you just used it for debugging?
So if you see value in keeping them, maybe add a line stating when/how they can be useful?
___
*[`src/WebView2PdfMaker/WebView2PdfComponent.cs` line 227 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620#-NNlhh2xETDXqvzytFBT:-NNlhh2y-0AEY8QGUZmV:bvz622q) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a441722141f48ba6f8b1cbd4da1e9347f48db0af/src/WebView2PdfMaker/WebView2PdfComponent.cs#L227)):*
> ```Smalltalk
> 			_printSettings.MarginRight = _options.GetWebView2RightMargin();
> 			// true if background colors and images should be printed.  (The default value is false.)
> 			_printSettings.ShouldPrintBackgrounds = true;
> ```

The way I read this and the comment, won't it output the cover color?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Publish/PDF/PdfMaker.cs` line 75 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620#-NNlfe3G67hYRp2mrbuX:-NNmCJPO1NqlKwLgho8n:b-yhpcq7) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a441722141f48ba6f8b1cbd4da1e9347f48db0af/src/BloomExe/Publish/PDF/PdfMaker.cs#L75)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Any reason to keep this comment or the two below?
I guess you just used it for debugging?
So if you see value in keeping them, maybe add a line stating when/how they can be useful?
</blockquote></details>

They're useful for debugging the steps in the PDF creation process for various page layouts.  A comment may be in order to persuade others of the value of not just deleting these lines...
___
*[`src/WebView2PdfMaker/WebView2PdfComponent.cs` line 227 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620#-NNlhh2xETDXqvzytFBT:-NNmC9ZU2bYq1bT3_GKY:bsu9xic) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a441722141f48ba6f8b1cbd4da1e9347f48db0af/src/WebView2PdfMaker/WebView2PdfComponent.cs#L227)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The way I read this and the comment, won't it output the cover color?
</blockquote></details>

Yes, and that's what the old program did as far as I can tell.  But perhaps I'm wrong.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/WebView2PdfMaker/WebView2PdfComponent.cs` line 227 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620#-NNlhh2xETDXqvzytFBT:-NNmMPyiApiY8eujsse8:b-7465j0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a441722141f48ba6f8b1cbd4da1e9347f48db0af/src/WebView2PdfMaker/WebView2PdfComponent.cs#L227)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Yes, and that's what the old program did as far as I can tell.  But perhaps I'm wrong.
</blockquote></details>

Printing a booklet or simple PDF does not include the background color. Rather the background of every page is white. This is intended because the user does not want to print the color.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/WebView2PdfMaker/WebView2PdfComponent.cs` line 227 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620#-NNlhh2xETDXqvzytFBT:-NNn4JjAABjGQb61Hjox:b-r2k880) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a441722141f48ba6f8b1cbd4da1e9347f48db0af/src/WebView2PdfMaker/WebView2PdfComponent.cs#L227)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Printing a booklet or simple PDF does not include the background color. Rather the background of every page is white. This is intended because the user does not want to print the color.
</blockquote></details>

Do we ever use background pictures in Bloom?  That's bundled with this value.  I'm happy to leave it false (no backgrounds printed) if that will work in practice.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/WebView2PdfMaker/WebView2PdfComponent.cs` line 227 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620#-NNlhh2xETDXqvzytFBT:-NNn9enj4PNc7TTYRYBw:bxnervc) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a441722141f48ba6f8b1cbd4da1e9347f48db0af/src/WebView2PdfMaker/WebView2PdfComponent.cs#L227)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Do we ever use background pictures in Bloom?  That's bundled with this value.  I'm happy to leave it false (no backgrounds printed) if that will work in practice.
</blockquote></details>

I don't think we use background images, but I get confused on that because at one time we did or we do in b-p or something.

Taking another tack on this... what prompted the change?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/WebView2PdfMaker/WebView2PdfComponent.cs` line 227 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620#-NNlhh2xETDXqvzytFBT:-NNrRw2U4RQN6X4_NjJp:bhitngi) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/7482dd14ef61a9665c0f325b32ac1d720533c5ca/src/WebView2PdfMaker/WebView2PdfComponent.cs#L227)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't think we use background images, but I get confused on that because at one time we did or we do in b-p or something.

Taking another tack on this... what prompted the change?
</blockquote></details>

I just thought it might be needed.  I changed back to false, but set it explicitly.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Publish/PDF/PdfMaker.cs` line 86 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620#-NNwE23R29B98GYAfkve:-NNwE23R29B98GYAfkvf:b-ik6pe5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3ee1750a11c65b470fd2413003854e3a13f9dcbe/src/BloomExe/Publish/PDF/PdfMaker.cs#L86)):*
> ```Smalltalk
> 				// the file before manipulating it further. Just noting it in case there are unexpected issues.
> 				var fixPdf = new ProcessPdfWithGhostscript(ProcessPdfWithGhostscript.OutputType.DesktopPrinting, worker);
> 				fixPdf.ProcessPdfFile(specs.OutputPdfPath, specs.OutputPdfPath);
> ```

We should either remove the page removal code from ProcessPdfFile or comment there that we aren't using it now, favoring instead to do it here.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/Publish/PDF/PdfMaker.cs` line 86 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620#-NNwE23R29B98GYAfkve:-NOFv6x-4B_wYpyy3EEw:blsnowr) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3ee1750a11c65b470fd2413003854e3a13f9dcbe/src/BloomExe/Publish/PDF/PdfMaker.cs#L86)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We should either remove the page removal code from ProcessPdfFile or comment there that we aren't using it now, favoring instead to do it here.
</blockquote></details>

Done.  (removed code)

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
