### PR TITLE
BL-3821 Swallow bad L10N keys

### PR DESCRIPTION
**Pull request by gmartin7**
* Integer keys swallowed
* 'none' swallowed

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1241)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/web/I18NHandler.cs, line 92 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1241#-KTuK3Os8KzKQlVssASb:-KTuK3Os8KzKQlVssASc:bq8addd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4751266c59284ab668705fadeddac268fcd1dc67/src/BloomExe/web/I18NHandler.cs#L92)):*
> ```Smalltalk
> 						if (IsInteger(id))
> 						{
> 							englishText = id;
> ```

Is this going to block any existing translated ids we already have from showing localized? 
i.e. If we already have translations of TemplateBooks.PageLabel.1, will this prevent those from showing up?
Same question for similar new code below.

---

*[src/BloomExe/web/I18NHandler.cs, line 174 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1241#-KTuJyMKVvUYLDXfux4y:-KTuJyMKVvUYLDXfux4z:bg32t8i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4751266c59284ab668705fadeddac268fcd1dc67/src/BloomExe/web/I18NHandler.cs#L174)):*
> ```Smalltalk
> 			try
> 			{
> 				Convert.ToInt32(key);
> ```

Did you consider int.TryParse? Seems better to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1241)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1241)*

**Comment by gmartin7** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/web/I18NHandler.cs, line 92 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1241#-KTuK3Os8KzKQlVssASb:-KTukjy7D_lttDtutfyU:bgzmrua) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4751266c59284ab668705fadeddac268fcd1dc67/src/BloomExe/web/I18NHandler.cs#L92)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Is this going to block any existing translated ids we already have from showing localized? 
> i.e. If we already have translations of TemplateBooks.PageLabel.1, will this prevent those from showing up?
> Same question for similar new code below.
</details>
Nope. In both cases, we try to get the dynamic translation of the string first, failing that we return the string if it parses to an integer, otherwise we report it as missing.

---

*[src/BloomExe/web/I18NHandler.cs, line 174 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1241#-KTuJyMKVvUYLDXfux4y:-KTuky8nBRV7GXw2Zs7a:bad1gb3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4751266c59284ab668705fadeddac268fcd1dc67/src/BloomExe/web/I18NHandler.cs#L174)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Did you consider int.TryParse? Seems better to me.
</details>
Good point. Much better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1241)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1241#-:-KTy-KobJMZxjePdmjWd:bnfp4nl)*

**Pull request merged**
