### PR TITLE
Fix Linux layout problem with Choose Collection dialog (BL-4409)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1626)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Needs to be rebased on Version3.9 branch

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1626#-:-KgQM6kmTDKSuBYPyyeu:b-nrw4kl)*

**Comment by StephenMcConnel** [comment]
Done.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1626#-:-KgQVxeziSP1a9c1-hzT:b-896fix)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs, line 370 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1626#-KgQbMC-VpYMDuFg-1iU:-KgQbMC-VpYMDuFg-1iV:bycw3ml) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1bedc97ad10bcb6da0800ce72c7b5ad89b5d70bd/src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs#L370)):*
While I agree this seems like it would solve the issue, I don't like having multiple extensions of ToolStripProfessionalRenderer to solve various issues. At the very least, it seems like this should extend NoBorderToolStripRenderer (and perhaps that needs to move out of Workspace).

Obviously, the ideal would be to have one class which works in every circumstance.

> Changing that class breaks other uses of Toolstrips in Bloom.

In what way? Do you deem it infeasible to have one class handle all scenarios?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1626)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs, line 370 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1626#-KgQbMC-VpYMDuFg-1iU:-KgQjLBBcRepyctPNsC5:b-6irnah) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1bedc97ad10bcb6da0800ce72c7b5ad89b5d70bd/src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs#L370)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

While I agree this seems like it would solve the issue, I don't like having multiple extensions of ToolStripProfessionalRenderer to solve various issues. At the very least, it seems like this should extend NoBorderToolStripRenderer (and perhaps that needs to move out of Workspace).

Obviously, the ideal would be to have one class which works in every circumstance.

> Changing that class breaks other uses of Toolstrips in Bloom.

In what way? Do you deem it infeasible to have one class handle all scenarios?
</blockquote></details>

OK, I've moved the code to the original class with an enhanced test for when the fix is applied.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1626)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1626#-:-KgQkBIeV0AvuLusAfOs:bnfp4nl)*

**Pull request merged**
