### PR TITLE
Stop using HtmlLabel from libpalaso (BL-12137)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5787)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5787)* status: 0 of 33 files reviewed, all discussions resolved

___
*[`src/BloomExe/Collection/BloomPack/BloomPackInstallDialog.resx` line 130 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5787#-NTzRQQHCCY9V3xwGX_f:-NTzRQQHCCY9V3xwGX_g:b-8lbqqh) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ed7e5be65267e200e388ba41a2f3e8b5ca7815e3/src/BloomExe/Collection/BloomPack/BloomPackInstallDialog.resx#L130)):*
> ```XML
>   </metadata>
>   <assembly alias="System.Drawing" name="System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
>   <data name="$this.Icon" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
> ```

All these large removals from .resx files are removing the encoded icon images and replacing them with calls to `global::Bloom.Properties.Resources.BloomIcon`.

It ended up with these changes because I was fixing the icon for BloomIntegrityDialog which was still the old one. And I just cleaned them all up at once.
___
*[`src/BloomExe/CollectionCreating/CollectionNameControl.cs` line 44 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5787#-NTzRilQ5xZJq9qWEzIP:-NTzRilQ5xZJq9qWEzIQ:bjshpde) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/1ce3cf53bd1177d1250ea60bd3ce6b987934342a/src/BloomExe/CollectionCreating/CollectionNameControl.cs#L44)):*
> ```Smalltalk
> 					if (DestinationAlreadyExists)
> 					{
> 						_collectionInfoLabel.Text = string.Format(LocalizationManager.GetString("NewCollectionWizard.AlreadyCollectionWithThatName.V2", "There is already a collection with that name, at {0}.\r\nPlease pick a unique name."), Path.GetDirectoryName(_collectionInfo.PathToSettingsFile));
> ```

JH agreed that losing the ability to link to the folder in Explorer was an acceptable casualty.
___
*[`src/BloomExe/CollectionTab/InDesignXmlInformationDialog.cs` line 1 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5787#-NTzRyVC60IXevgp5s0Q:-NTzRyVC60IXevgp5s0R:b-33elix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ed7e5be65267e200e388ba41a2f3e8b5ca7815e3/src/BloomExe/CollectionTab/InDesignXmlInformationDialog.cs#L1)):*
> ```Smalltalk
> using System;
> ```

Discovered this dialog isn't used (and it was trying to use HtmlLabel), so I removed it.

**Review by StephenMcConnel — CHANGES_REQUESTED** [review]
Generally looks good.  It's always nice to see obsolete cruft disappear.  :-)

> Reviewed 33 of 33 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5787#-:-NTzYTb087EDynZcFINt:bcx0atg)* status: all files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/Bloom.xlf` line 3364 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5787#-NTzUr_0AsomfTNrTQ-1:-NTzUr_16gTyPjDEQU5h:b-2s6a81) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/1ce3cf53bd1177d1250ea60bd3ce6b987934342a/DistFiles/localization/en/Bloom.xlf#L3364)):*
> ```XML
>       <trans-unit id="NewCollectionWizard.AlreadyCollectionWithThatName.V2">
>         <source xml:lang="en">There is already a collection with that name, at {0}.\nPlease pick a unique name.</source>
>         <note>ID: NewCollectionWizard.AlreadyCollectionWithThatName.V2</note>
> ```

see the comment below.
___
*[`DistFiles/localization/en/Bloom.xlf` line 3475 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5787#-NTzUE4-0rCiwh6H6zmx:-NTzUE404-zKb7BZyq3j:bt4tsik) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/1ce3cf53bd1177d1250ea60bd3ce6b987934342a/DistFiles/localization/en/Bloom.xlf#L3475)):*
> ```XML
>       <trans-unit id="NewCollectionWizard.WelcomePage.WelcomeLine2.V2">
>         <source xml:lang="en">In order to keep things simple and organized, Bloom keeps all the books you make in one or more 'Collections'. The first thing we need to do is make one for you.</source>
>         <note>ID: NewCollectionWizard.WelcomePage.WelcomeLine2.V2</note>
> ```

I think the new strings introduced for 5.5 have been tagged with translate="no" and frequently marked with a comment  with the intent of removing these as soon as 5.5 goes beta.  Perhaps we're close enough to not bother with this step at this point.
___
*[`src/BloomExe/MiscUI/BloomIntegrityDialog.cs` line 15 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5787#-NTzX7iC48rtYigsbYRh:-NTzX7iC48rtYigsbYRi:b9pwrbv) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/1ce3cf53bd1177d1250ea60bd3ce6b987934342a/src/BloomExe/MiscUI/BloomIntegrityDialog.cs#L15)):*
> ```Smalltalk
> namespace Bloom.MiscUI
> {
> 	public class BloomIntegrityDialog
> ```

Is this still an appropriate name for this class since it doesn't embody a dialog, but merely optionally displays one?
___
*[`src/BloomExe/Publish/PublishView.cs` line 276 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5787#-NTzXs5m6WqBBKXcIcA-:-NTzXs5m6WqBBKXcIcA0:bpblvuj) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/1ce3cf53bd1177d1250ea60bd3ce6b987934342a/src/BloomExe/Publish/PublishView.cs#L276)):*
> ```Smalltalk
> 							"Bloom ran out of memory while making the PDF. See {0}this article{1} for some suggestions to try.",
> 							"{0} and {1} are HTML link markup.  You can think of them as fancy quotation marks.");
> 						var msg = String.Format(fmt, "<a href='https://community.software.sil.org/t/solving-memory-problems-while-printing/500'>", "</a>");
> ```

What is going to happen with this HTML link in the string?
___
*[`src/BloomExe/Publish/PDF/PublishPdfApi.cs` line 278 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5787#-NTzY84EA4fRz4vC0Tl3:-NTzY84EA4fRz4vC0Tl4:bs6zhg9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/1ce3cf53bd1177d1250ea60bd3ce6b987934342a/src/BloomExe/Publish/PDF/PublishPdfApi.cs#L278)):*
> ```Smalltalk
> 							"Bloom ran out of memory while making the PDF. See {0}this article{1} for some suggestions to try.",
> 							"{0} and {1} are HTML link markup.  You can think of them as fancy quotation marks.");
> 						var msg = String.Format(fmt, "<a href='https://community.software.sil.org/t/solving-memory-problems-while-printing/500'>", "</a>");
> ```

what is going to happen with the HTML link in the message box display?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5787)* status: 30 of 33 files reviewed, 5 unresolved discussions (waiting on @StephenMcConnel)

___
*[`DistFiles/localization/en/Bloom.xlf` line 3364 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5787#-NTzUr_0AsomfTNrTQ-1:-NTzcqd0Cg_iuGJzGfkU:b-pnhr4h) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/1ce3cf53bd1177d1250ea60bd3ce6b987934342a/DistFiles/localization/en/Bloom.xlf#L3364)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

see the comment below.
</blockquote></details>

See below.
___
*[`DistFiles/localization/en/Bloom.xlf` line 3475 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5787#-NTzUE4-0rCiwh6H6zmx:-NTzcXFEBtH_Y5gOVeVS:ban5ffg) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/1ce3cf53bd1177d1250ea60bd3ce6b987934342a/DistFiles/localization/en/Bloom.xlf#L3475)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I think the new strings introduced for 5.5 have been tagged with translate="no" and frequently marked with a comment  with the intent of removing these as soon as 5.5 goes beta.  Perhaps we're close enough to not bother with this step at this point.
</blockquote></details>

You're right that we do that for new versions because the string could change before it goes live.

But here, we don't have that possibility.
And I want it to get into Crowdin when merged so I can go ahead and add the translations we already have (tweaked to remove the markup).
___
*[`src/BloomExe/Publish/PublishView.cs` line 276 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5787#-NTzXs5m6WqBBKXcIcA-:-NTzcLp6ByP5F_SLFPC4:b-jfi2zy) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/1ce3cf53bd1177d1250ea60bd3ce6b987934342a/src/BloomExe/Publish/PublishView.cs#L276)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

What is going to happen with this HTML link in the string?
</blockquote></details>

Works well with BloomMessageBox.
___
*[`src/BloomExe/Publish/PDF/PublishPdfApi.cs` line 278 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5787#-NTzY84EA4fRz4vC0Tl3:-NTzcSOyEwjomILaTs_X:b-jfi2zy) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/1ce3cf53bd1177d1250ea60bd3ce6b987934342a/src/BloomExe/Publish/PDF/PublishPdfApi.cs#L278)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

what is going to happen with the HTML link in the message box display?
</blockquote></details>

Works well with BloomMessageBox.
___
*[`src/BloomExe/MiscUI/BloomIntegrityDialog.cs` line 15 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5787#-NTzX7iC48rtYigsbYRh:-NTzd-2iBKaR0tcRKjtR:b-wlwfxh) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/1ce3cf53bd1177d1250ea60bd3ce6b987934342a/src/BloomExe/MiscUI/BloomIntegrityDialog.cs#L15)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Is this still an appropriate name for this class since it doesn't embody a dialog, but merely optionally displays one?
</blockquote></details>

Good point. How about BloomIntegrityChecker?

**Review by StephenMcConnel — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5787#-:-NU23s6Y-RAR2WkhZzjM:bnfp4nl)* status: 32 of 33 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

**Review by StephenMcConnel — APPROVED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5787)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
