### PR TITLE
BL-10891 Get xmatter import working better

### PR DESCRIPTION
**Pull request by gmartin7**
* cover image now gets copied
* after importing we bring the xmatter up-to-date and
   save the book

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4949)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
Need unit tests that fail without these fixes, please. (In the case of the xmatter one, that currently means you'll need to pass a collection settings in the test so BBUTD runs).
Another option is to say that it's not the SSImporter's job to BBUTD...that should be done by the caller if there isn't some other way it will get done.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4949#-:-Mv67N2S0nADH7b1NFUm:b1pwrtw)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 209 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4949#-Mv662tqD_uVgnQTvLI8:-Mv662tqD_uVgnQTvLI9:b-v6k9ut) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/529c20b135ad13503a29a89202f7f82e34623fa5/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L209)):*
> ```Smalltalk
> 					_collectionSettings.CharactersForDigitsForPageNumbers,
> 					_collectionSettings.Language1.IsRightToLeft);
> 				_book.BringXmatterHtmlUpToDate(_dest);
> ```

Is this helpful to do even if we don't have collection settings? I suppose if we're running from a command line, BBUTD will happen when we eventually open the book. And doing it unconditionally would probably break unit tests right and left by inserting extra xmatter pages. I think those reasons for not doing it should be commented.

**Review by gmartin7 — COMMENTED** [review]
I put quite a bit of effort into trying to create a unit test that actually had a Book object. Not easy. I've managed to test that the data div gets updated for cover image and title.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4949#-:-MvQUiMlAx8QnGAJ9CFX:bifsnq6)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 209 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4949#-Mv662tqD_uVgnQTvLI8:-MvKZ6ne8NDStVXeJaTO:b-f4j49k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/529c20b135ad13503a29a89202f7f82e34623fa5/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L209)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is this helpful to do even if we don't have collection settings? I suppose if we're running from a command line, BBUTD will happen when we eventually open the book. And doing it unconditionally would probably break unit tests right and left by inserting extra xmatter pages. I think those reasons for not doing it should be commented.
</blockquote></details>

You were absolutely right. Making the xmatter update and save unconditional breaks 90 tests! And both methods are part of BBUTD. Commented.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4949)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @gmartin7 and @JohnThomson)

___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 212 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4949#-MvVeWb602IyEEpGF1od:-MvVeWb602IyEEpGF1oe:bocf0ri) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2b8154985bbf13966b841fff8376cd8e310a477f/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L212)):*
> ```Smalltalk
> 			// If we run SS Importer from the CLI (without CollectionSettings), BringBookUpToDate()
> 			// will happen when we eventually open the book, but the user gets a better experience
> 			// if we do it here for the main production case where we DO have both the CollectionSettings
> ```

While you're improving comments...might be useful to say what bad user experience you're guarding against. Then if someone considers taking it out they know what to look for.
___
*[src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs, line 827 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4949#-MvVdKN-BYlsr4Chj-6x:-MvVdKN-BYlsr4Chj-6y:b-ceo4m5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/650cebc378a826a680c803cb8058dd8a5b5e0d6e/src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs#L827)):*
> ```Smalltalk
> 			var unexpectedClass = expectedClass == "side-right" ? "side-left" : "side-right";
> 			AssertThatXmlIn.Element(_contentPages[n]).HasNoMatchForXpath($"self::div[contains(@class, '" + unexpectedClass + "')]");
> 			AssertThatXmlIn.Element(_contentPages[n]).HasSpecifiedNumberOfMatchesForXpath($"self::div[contains(@class, '" + expectedClass + "')]", 1);
> ```

We seem to have lost something useful here. I don't think the new test needs to do such complex insertions as this one, but it would be nice to have some verification that an inserted page and a following pre-existing page both get updated to the right page number and side.
Then again...maybe it's enough just to test, as you almost do, that one page-side class gets fixed. That establishes that the relevant part of BBUTD is being called, and presumably tests elsewhere cover what that code does. If you decide we don't need any more, maybe just comment somewhere why you don't see a need for more elaborate checking of this aspect.
___
*[src/BloomTests/Spreadsheet/SpreadsheetImporterWithBookTests.cs, line 244 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4949#-MvVcKrp0xDnqHqRBkam:-MvVcKrp0xDnqHqRBkan:bpgtvrw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2b8154985bbf13966b841fff8376cd8e310a477f/src/BloomTests/Spreadsheet/SpreadsheetImporterWithBookTests.cs#L244)):*
> ```Smalltalk
> 		{
> 			var pageWithJustTextDom = AssertThatXmlIn.Element(_resultElement.SelectSingleNode("//div[@id='dc90dbe0-7584-4d9f-bc06-0e0326060054']") as XmlElement);
> 			// This page we added started out as 'side-right'.
> ```

Is the above a mistake? Because I'd think you'd want a case where the importer needs to change the side class.
Also...if this class is now the only test that import fixes page numbers and sides...seems like we'd want the importer to insert a content page, and check that the following page gets updated appropriately, and also that the inserted page is set up correctly. But maybe you have other tests that do that?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4949)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 212 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4949#-MvVeWb602IyEEpGF1od:-MvVi4PmEZAutE-s6jLE:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2b8154985bbf13966b841fff8376cd8e310a477f/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L212)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

While you're improving comments...might be useful to say what bad user experience you're guarding against. Then if someone considers taking it out they know what to look for.
</blockquote></details>

Done.
___
*[src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs, line 827 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4949#-MvVdKN-BYlsr4Chj-6x:-MvVjokh6lSZq_rReKSW:bmr22pc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/650cebc378a826a680c803cb8058dd8a5b5e0d6e/src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs#L827)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We seem to have lost something useful here. I don't think the new test needs to do such complex insertions as this one, but it would be nice to have some verification that an inserted page and a following pre-existing page both get updated to the right page number and side.
Then again...maybe it's enough just to test, as you almost do, that one page-side class gets fixed. That establishes that the relevant part of BBUTD is being called, and presumably tests elsewhere cover what that code does. If you decide we don't need any more, maybe just comment somewhere why you don't see a need for more elaborate checking of this aspect.
</blockquote></details>

I added a comment in the new test class explaining why I don't think this test is necessary any longer.
___
*[src/BloomTests/Spreadsheet/SpreadsheetImporterWithBookTests.cs, line 244 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4949#-MvVcKrp0xDnqHqRBkam:-MvVhfywEkWwtBEfJmky:b-ap3v79) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2b8154985bbf13966b841fff8376cd8e310a477f/src/BloomTests/Spreadsheet/SpreadsheetImporterWithBookTests.cs#L244)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is the above a mistake? Because I'd think you'd want a case where the importer needs to change the side class.
Also...if this class is now the only test that import fixes page numbers and sides...seems like we'd want the importer to insert a content page, and check that the following page gets updated appropriately, and also that the inserted page is set up correctly. But maybe you have other tests that do that?
</blockquote></details>

Yes, I changed it under you while you were reviewing it. ;)

**Review by JohnThomson — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4949)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
