### PR TITLE
BL-3021 Prompts/Explanations about talking books

### PR DESCRIPTION
**Pull request by JohnThomson**
[Review on Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/923)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/epub/bloomEpubPreview.htm, line 10 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/923#-K85JcX6uMwt8Fe31M2a:-K85JcX6uMwt8Fe31M2b:-1209686010) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/af5e5e7f5506c5f0f64a52cb9366854286c68ab7/src/BloomBrowserUI/epub/bloomEpubPreview.htm#L10)):*
I don't think we want to be putting copy/pasted javascript in our html. Can we factor this out from here and interIframChannel so that everywhere (including talkingBook.jade and this htm), we can just say "BloomHelp.Show(topic)"?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/923)*

**Comment by JohnThomson** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/BloomBrowserUI/epub/bloomEpubPreview.htm, line 10 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/923#-K85JcX6uMwt8Fe31M2a:-K869FShI6UWCJqh-6IU:1131972639) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/af5e5e7f5506c5f0f64a52cb9366854286c68ab7/src/BloomBrowserUI/epub/bloomEpubPreview.htm#L10)):*
Done...but the PR got a whole lot bigger (partly because of fixing some other problems this revealed)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/923)*

**Comment by hatton** [comment]
Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/sharedCode.ts, line 1 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/923#-K86bMnsBTtAOdDGhMN8:-K86bMnsBTtAOdDGhMN9:-751476183) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f2b9baffb542a79fa805c42c584433dbdd6b4e96/src/BloomBrowserUI/sharedCode.ts#L1)):*
I recommend just naming this one help, and then using the built-in fetch() command for ajax.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/923)*

**Comment by JohnThomson** [comment]
Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/sharedCode.ts, line 1 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/923#-K86bMnsBTtAOdDGhMN8:-K8Vx8s4n2X9kRXJqIgJ:-1620050057) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f2b9baffb542a79fa805c42c584433dbdd6b4e96/src/BloomBrowserUI/sharedCode.ts#L1)):*
I'm renaming the file bloomHelp.ts (since that's the class name)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/923)*

**Comment by JohnThomson** [comment]
Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/sharedCode.ts, line 1 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/923#-K86bMnsBTtAOdDGhMN8:-K8W330gaNcVBZXV0Y_c:1469151884) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f2b9baffb542a79fa805c42c584433dbdd6b4e96/src/BloomBrowserUI/sharedCode.ts#L1)):*
fetch() is not built-in until FF39. I just inlined the couple of lines of AJAX code.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/923)*

**Pull request merged**
