### PR TITLE
Prevent crash when saving .bloom file (BL-10159)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4659)

### CODE REVIEW

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4659)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1742 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4659#-Mh04e_G-dDbtSdmSUYR:-Mh04e_G-dDbtSdmSUYS:bjaa9co) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/cc7a2ad56cbc11b3f3e2496e210ce878ee90b4db/src/BloomExe/CollectionTab/LibraryListView.cs#L1742)):*
> ```Smalltalk
> 				NonFatalProblem.Report(ModalIf.All, PassiveIf.None,
> 					shortUserLevelMessage: null,
> 					"The file could not be saved. Make sure it is not open and try again.",
> ```

 Would this string look better as the shortUserLevelMessage, and have the detailedMessage be null or empty? What do you think?
___
*[src/BloomExe/CollectionTab/LibraryModel.cs, line 599 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4659#-Mh04R2Q7tamlOC2l5Qc:-Mh04R2Q7tamlOC2l5Qd:b-a66ekl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/cc7a2ad56cbc11b3f3e2496e210ce878ee90b4db/src/BloomExe/CollectionTab/LibraryModel.cs#L599)):*
> ```Smalltalk
> 		/// Zip up the book folder, excluding .pdf, .bloombookorder, .map, .bloompack, .db files.
> 		/// The resulting file will have a .bloom extension.
> 		/// </summary>
> ```

Please document the meaning of the return value.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4659)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1742 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4659#-Mh04e_G-dDbtSdmSUYR:-Mh0KNDO1OjoEARFRet1:b-a9fylx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/cc7a2ad56cbc11b3f3e2496e210ce878ee90b4db/src/BloomExe/CollectionTab/LibraryListView.cs#L1742)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

 Would this string look better as the shortUserLevelMessage, and have the detailedMessage be null or empty? What do you think?
</blockquote></details>

In this context, I couldn't tell that it made any UI difference, but this probably fits the paradigm better.
___
*[src/BloomExe/CollectionTab/LibraryModel.cs, line 599 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4659#-Mh04R2Q7tamlOC2l5Qc:-Mh0KSKxBWEQ54y8Ykdv:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/cc7a2ad56cbc11b3f3e2496e210ce878ee90b4db/src/BloomExe/CollectionTab/LibraryModel.cs#L599)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Please document the meaning of the return value.
</blockquote></details>

Done.

**Review by sujeffreyl — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4659)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @andrew-polk)

**Review by sujeffreyl — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4659)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
