### PR TITLE
Check for missing page content at strategic spots (BL-13123)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/IBrowser.cs` line 358 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357#-NtweGv44p-VAHsDGBBp:-NtweGv44p-VAHsDGBBq:b-jjtl1v) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3ff5ba8ff154d0620ae89ad916923e78862ea9b1/src/BloomExe/IBrowser.cs#L358)):*
> ```Smalltalk
>                 if (BookStorage.CheckForEmptyMarginBoxOnPage(_pageEditDom.DocumentElement))
>                 {
>                     Debug.Fail(
> ```

This makes sense to cause the break, but if it happens to a user, I think we do want a full-on `NotifyUserOfProblem()`?
___
*[`src/BloomExe/IBrowser.cs` line 359 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357#-NtwemLtDestiwqlkKkC:-NtwemLtDestiwqlkKkD:bnepgb) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3ff5ba8ff154d0620ae89ad916923e78862ea9b1/src/BloomExe/IBrowser.cs#L359)):*
> ```Smalltalk
>                 {
>                     Debug.Fail(
>                         "Debug Mode Only: Error in IBrowser.LoadPageDomFromBrowser -- the page has lost all content in the marginBox div!"
> ```

Please mention the Youtrack issue
___
*[`src/BloomExe/Book/Book.cs` line 3908 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357#-NtwdyVaEei1iZB6EA3y:-NtwdyVaEei1iZB6EA3z:b-31utu1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3ff5ba8ff154d0620ae89ad916923e78862ea9b1/src/BloomExe/Book/Book.cs#L3908)):*
> ```Smalltalk
>                         if (BookStorage.CheckForEmptyMarginBoxOnPage(pageFromStorage))
>                         {
>                             Debug.Fail(
> ```

See request for `NotifyUserOfProblem`, above
___
*[`src/BloomExe/Book/Book.cs` line 3909 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357#-NtwehIx8oaNcjwPP4N9:-NtwehIx8oaNcjwPP4NA:bnepgb) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3ff5ba8ff154d0620ae89ad916923e78862ea9b1/src/BloomExe/Book/Book.cs#L3909)):*
> ```Smalltalk
>                         {
>                             Debug.Fail(
>                                 "Debug Mode Only: Error in Book.SavePage saving whole book -- the current page has lost all content in the marginBox div!"
> ```

Please mention the Youtrack issue
___
*[`src/BloomExe/Book/BookStorage.cs` line 694 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357#-Ntwejoc5wAw3J5jT0Fe:-Ntwejoc5wAw3J5jT0Ff:bnepgb) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3ff5ba8ff154d0620ae89ad916923e78862ea9b1/src/BloomExe/Book/BookStorage.cs#L694)):*
> ```Smalltalk
>             {
>                 Debug.Fail(
>                     "Debug Mode Only: Error in BookStorage.SaveForPageChanged -- the page has lost all content in the marginBox div!"
> ```

Please mention the Youtrack issue
___
*[`src/BloomExe/Edit/EditingModel.cs` line 1199 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357#-NtwdljX4XsLlB1Y1JLa:-NtwdljX4XsLlB1Y1JLb:bvlea5u) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3ff5ba8ff154d0620ae89ad916923e78862ea9b1/src/BloomExe/Edit/EditingModel.cs#L1199)):*
> ```Smalltalk
>         {
>             if (_domForCurrentPage != null && !_inProcessOfSaving && !NavigatingSoSuspendSaving)
>             {
> ```

Will this litter the log? If you want to show that some future error happened during save, would `writeMinorEvent()` work for that (some recollection that it only goes out to the log in case of error?)
___
*[`src/BloomExe/Edit/EditingModel.cs` line 1222 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357#-NtwdRZj-S89TIr3cqx4:-NtwdRZj-S89TIr3cqx5:bib7kg0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3ff5ba8ff154d0620ae89ad916923e78862ea9b1/src/BloomExe/Edit/EditingModel.cs#L1222)):*
> ```Smalltalk
>                         _view.Invoke((Action)(() => SaveNow(forceFullSave)));
>                         Logger.WriteEvent(
>                             $"DEBUG: EditingModel.SaveNow() finished after Invoke to get on UI thread"
> ```

see log Q above
___
*[`src/BloomExe/Edit/EditingModel.cs` line 1295 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357#-Ntwdszx38HWw5kFdso8:-Ntwdszx38HWw5kFdso9:b-7ohm17) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3ff5ba8ff154d0620ae89ad916923e78862ea9b1/src/BloomExe/Edit/EditingModel.cs#L1295)):*
> ```Smalltalk
>                 MemoryManagement.CheckMemory(false, "after EditingModel.SaveNow()", false);
> #endif
>                 Logger.WriteEvent($"DEBUG: EditingModel.SaveNow() finished");
> ```

See note about minor even, above
___
*[`src/BloomExe/Edit/EditingModel.cs` line 1300 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357#-NtwdoSl6ntXroPu31po:-NtwdoSl6ntXroPu31pp:b-8m7q3z) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3ff5ba8ff154d0620ae89ad916923e78862ea9b1/src/BloomExe/Edit/EditingModel.cs#L1300)):*
> ```Smalltalk
>             {
>                 Logger.WriteEvent(
>                     $"DEBUG: EditingModel.SaveNow() called when _inProcessOfSaving={_inProcessOfDeleting}, NavigatingSoSuspendSaving={NavigatingSoSuspendSaving}, _domForCurrentPage={_domForCurrentPage}"
> ```

What does `DEBUG` do?

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357)* status: 0 of 4 files reviewed, 11 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Book/BookStorage.cs` line 3920 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357#-Nu0CsKA87ftZf23iQSQ:-Nu0CsKA87ftZf23iQSR:b9x5ziz) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/80a21adbf5c99e316b0aca1950a49427a270e36f/src/BloomExe/Book/BookStorage.cs#L3920)):*
> ```Smalltalk
>             RobustFile.AppendAllText(logpath, Environment.NewLine);
>             // Not an image file, but we want it included in the problem report.
>             exception.Data["ProblemImagePath"] = logpath;
> ```

Should we find (or create) a different way?
___
*[`src/BloomExe/Book/BookStorage.cs` line 3924 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357#-Nu0D7WlDXiNaMmnGFvf:-Nu0D7WlDXiNaMmnGFvg:b-pfvao1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/80a21adbf5c99e316b0aca1950a49427a270e36f/src/BloomExe/Book/BookStorage.cs#L3924)):*
> ```Smalltalk
>                 LocalizationManager.GetDynamicString(
>                     "BloomLowPriority",
>                     "ProblemReport.EmptyMarginBox",
> ```

Let's go with
`ProblemReport.PageStructureProblem`
and
`Bloom made a mistake on this page. Please report this to us, then check that nothing was lost.`

I'm assuming the details and pointers to youtrack issues will be in the log.

**Comment by hatton** [comment]
@StephenMcConnel we're going to wan this at least on 5.6, or also 5.5?

**Review by StephenMcConnel — COMMENTED** [review]
Noted.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357#-:-Nu0kBTn-_L9QqXNQf5E:bwygxsx)* status: 0 of 6 files reviewed, 11 unresolved discussions (waiting on @hatton)

___
*[`src/BloomExe/Book/BookStorage.cs` line 3920 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357#-Nu0CsKA87ftZf23iQSQ:-Nu0fuUN0JjzVAOLFrCD:b-kiu462) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/80a21adbf5c99e316b0aca1950a49427a270e36f/src/BloomExe/Book/BookStorage.cs#L3920)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Should we find (or create) a different way?
</blockquote></details>

Done.  I added a Data["ExtraFilePath"] for use in passing the filepath.
___
*[`src/BloomExe/Book/BookStorage.cs` line 3924 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357#-Nu0D7WlDXiNaMmnGFvf:-Nu0gTg36Y0bYallnOu0:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/80a21adbf5c99e316b0aca1950a49427a270e36f/src/BloomExe/Book/BookStorage.cs#L3924)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Let's go with
`ProblemReport.PageStructureProblem`
and
`Bloom made a mistake on this page. Please report this to us, then check that nothing was lost.`

I'm assuming the details and pointers to youtrack issues will be in the log.
</blockquote></details>

Done.

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Edit/EditingModel.cs` line 1199 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357#-NtwdljX4XsLlB1Y1JLa:-Nu0luFv-SR-efjgPuw_:b-u7dull) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3ff5ba8ff154d0620ae89ad916923e78862ea9b1/src/BloomExe/Edit/EditingModel.cs#L1199)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Minor events are never written to the log file.  I've looked  at the logger code and I think I know how to write them to a second file when this error is detected.  This isn't ideal, but the best compromise available.  The second file can be included in a problem report submission as well as the normal log file.
</blockquote></details>

Hmmm, that's a regression. I wrote that code 16 years ago or so, and the point of Minor was to log it if there is an error. Else what would be the point of minor events?

**Comment by hatton** [comment]
OK so all that's left is to retarget this to some earlier version?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/BloomExe/Edit/EditingModel.cs` line 1199 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357#-NtwdljX4XsLlB1Y1JLa:-Nu0maQk5nnxSk4YcALw:b-qnf33u) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3ff5ba8ff154d0620ae89ad916923e78862ea9b1/src/BloomExe/Edit/EditingModel.cs#L1199)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Hmmm, that's a regression. I wrote that code 16 years ago or so, and the point of Minor was to log it if there is an error. Else what would be the point of minor events?
</blockquote></details>

I've written code to get the minor events (which would also include all the error and non-minor events) into a file when we hit this one particular error, but it's certainly not a general solution.  I don't know why or when it changed.

**Review by StephenMcConnel — COMMENTED** [review]
I'm happy to retarget 5.5, but I don't know of any way to do that without essentially killing this PR and copying the relevant code over to Version5.5 manually.  The great C# reformatting in 5.7 makes this trickier that perhaps it could be, and I don't have any tools that reliably retarget a PR once created.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357#-:-Nu0t0MmA0u_civBHbtp:b-e97vwj)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @hatton)

**Review by hatton — COMMENTED** [review]
whatever you want to do. Merge whenever you want.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6357#-:-Nu10Qe-Dp53uOk6NpiL:biujv61)* status: 0 of 6 files reviewed, 1 unresolved discussion

**Comment by StephenMcConnel** [comment]
We're retargetting Version5.5 initially, then merging up to master instead of trying to cherry-pick backwards, which we know won't work.

**Pull request closed without merging**
