### PR TITLE
[4.2]BL-6019 Fix upload to use analytics

### PR DESCRIPTION
**Pull request by gmartin7**
* targets 4.2 so that Beta Internal can be used to bulk upload books

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2483)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gmartin7)

---

*[src/BloomExe/Program.cs, line 104 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2483#-LEkZ09eD-OB79IbGFOu:-LEkZ09f-mUAEQ0Z8Muk:bwp85c8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fd0e92d80b348b011279f1d8b1e2e0faf85c2847/src/BloomExe/Program.cs#L104)):*
> ```Smalltalk
> 						(UploadParameters opts) =>
> 						{
> 							InitializeAnalytics();
> ```

Don't we need to dispose here, too?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2483)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2483)*

**Comment by gmartin7** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @gmartin7)

---

*[src/BloomExe/Program.cs, line 104 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2483#-LEkZ09eD-OB79IbGFOu:-LEkaNnG2iCLKTHm61GT:b-mnoo55) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fd0e92d80b348b011279f1d8b1e2e0faf85c2847/src/BloomExe/Program.cs#L104)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Don't we need to dispose here, too?
</blockquote></details>

Drat! Well, that's why we do reviews!

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2483)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2483#-:-LEkaejb1YI82xu2eBJd:bnfp4nl)*

**Pull request merged**
