### PR TITLE
Prevent markup routine from interfering with longpress (BL-5215)

### PR DESCRIPTION
**Pull request by andrew-polk**
This is a less-than-satisfactory fix as it doesn't address the root issue,
but it does seem to work.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1951)

### CODE REVIEW

**Comment by JohnThomson** [comment]
looks basically good, but a few tweaks needed. In fact, I don't find it as unsatisfactory as you do. Expecting to be able to update markup successfully in the middle of a process that is conceptually a single keystroke seems unreasonable; preventing it entirely reasonable.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 389 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1951#-KyW99sSXkSxXuJ-_W0H:-KyW99sSXkSxXuJ-_W0I:bg6n81h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4945c5a5363cbc07d755e6431379d3569d169766/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L389)):*
> ```XML
>         }
> 
>         // the hard thing about all this is preserving the user's insertion point while we change the actual
> ```

This comment block has gotten separated from where the bookmark actually gets inserted.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 408 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1951#-KyW9JaYqY2SFl81B5x2:-KyW9JaYqY2SFl81B5x3:bfc0s0m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4945c5a5363cbc07d755e6431379d3569d169766/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L408)):*
> ```XML
>         // that elsewhere in this file). This code was added for BL-5215.
>         if (editableDiv.hasAttribute("data-longpress-evaluation-in-progress")) {
>             keypressTimer = null;
> ```

This line is puzzling in a few ways. For one thing, comment above says keypressTimer is typically an integer, so setting it to null is strange. Then, this path and the normal path set it to null, but the range selection early return above doesn't. My suspicion is that once the timer has timed out (which is what runs this function), the value just doesn't matter. It's only used to cancel the timer prematurely. If it's not necessary I'd be inclined to remove it; if it is, probably should be done in all return paths.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 409 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1951#-KyWAFemckY0CndrRApx:-KyWAFemckY0CndrRApy:b4f85sg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4945c5a5363cbc07d755e6431379d3569d169766/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L409)):*
> ```XML
>         if (editableDiv.hasAttribute("data-longpress-evaluation-in-progress")) {
>             keypressTimer = null;
>             handleKeydown();
> ```

I don't know exactly what this does, but it seems in need of explanation. What keydown might we be handling while we are aborting a display-update process that runs half a second after we get done handling key presses?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1951#-:-KyWAdy5W5yN7uBz-oGy:b-eulakj)*

**Comment by andrew-polk** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 389 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1951#-KyW99sSXkSxXuJ-_W0H:-KyXJJhXCGe88jWP7h7E:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4945c5a5363cbc07d755e6431379d3569d169766/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L389)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This comment block has gotten separated from where the bookmark actually gets inserted.
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 408 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1951#-KyW9JaYqY2SFl81B5x2:-KyXJHRWsKwDr3wlGyPw:bss4a2b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4945c5a5363cbc07d755e6431379d3569d169766/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L408)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This line is puzzling in a few ways. For one thing, comment above says keypressTimer is typically an integer, so setting it to null is strange. Then, this path and the normal path set it to null, but the range selection early return above doesn't. My suspicion is that once the timer has timed out (which is what runs this function), the value just doesn't matter. It's only used to cancel the timer prematurely. If it's not necessary I'd be inclined to remove it; if it is, probably should be done in all return paths.
</blockquote></details>

Removed.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 409 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1951#-KyWAFemckY0CndrRApx:-KyXIyXnKSscsyXyuiQz:b-izj2ib) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4945c5a5363cbc07d755e6431379d3569d169766/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L409)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't know exactly what this does, but it seems in need of explanation. What keydown might we be handling while we are aborting a display-update process that runs half a second after we get done handling key presses?
</blockquote></details>

I thought this would be necessary to get markup updated after a longpress selection. But you're right. It isn't needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1951)*

**Comment by JohnThomson** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 396 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1951#-KyXMO37bf7D_PeZf70Q:-KyXMO37bf7D_PeZf70R:b-m1dhei) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e05677773e759b6ebbf0717d0605194316f162c7/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L396)):*
> ```XML
>         // It would be great if we didn't have settle for using window.top,
>         // but the other player here (jquery.longpress.js) is in a totally different
>         // context currently, so my other attempts to share a boolean failed.
> ```

It seems you have already solved this problem, because the two bits of code are sharing the variable isLongPressEvaluating, which currently stores the name of the property of window.top that you will use for the kludge. But if you just declare it boolean (and not const) instead, you can just have if (isLongPressEvaluating) here and set the imported variable true or false directly in the other code, can't you?
If I'm missing something feel free to merge as-is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1951)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 396 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1951#-KyXMO37bf7D_PeZf70Q:-KyXNe3jRJLYKsVE4s8Q:b-6zmu52) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e05677773e759b6ebbf0717d0605194316f162c7/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L396)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It seems you have already solved this problem, because the two bits of code are sharing the variable isLongPressEvaluating, which currently stores the name of the property of window.top that you will use for the kludge. But if you just declare it boolean (and not const) instead, you can just have if (isLongPressEvaluating) here and set the imported variable true or false directly in the other code, can't you?
If I'm missing something feel free to merge as-is.
</blockquote></details>

I'll try it one more time... but no, I don't think it solves the problem. In this case, we are just looking up a string which never changes. In the case of a boolean, one has to see the other's changes. The block I couldn't get past using that method was that each file seemed to be using a separate instance of the boolean.

Anyway, I'll try and report back.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1951)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 396 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1951#-KyXMO37bf7D_PeZf70Q:-KyXPjjzbQyQFk7o7h_E:b-fhvxdv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e05677773e759b6ebbf0717d0605194316f162c7/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L396)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'll try it one more time... but no, I don't think it solves the problem. In this case, we are just looking up a string which never changes. In the case of a boolean, one has to see the other's changes. The block I couldn't get past using that method was that each file seemed to be using a separate instance of the boolean.

Anyway, I'll try and report back.
</blockquote></details>

Confirmed. If I simply change it to a boolean, there is a compile error because once exported, it can't be changed.
Other attempts to do things like make it an object with a boolean property or use methods failed because each side seems to have its own instance (i.e. longpress sets the value but there is no change when toolbox looks at it).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1951)*

**Comment by hatton** [comment]
So it looks good to me. The only risk I see is that for some reason something else gets the keyup event and tells the browser not to propagate it, the flag will remain set. But only until the next key press, so I'd say :lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1951#-:-KyXpzV2sZOG3UfX4qwi:b62n764)*

**Pull request merged**
