### PR TITLE
Retrieve the parse URL from a file in bloom-desktop-files bucket on S3 (BL-3726)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1177)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/WebLibraryIntegration/BloomParseClient.cs, line 78 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1177#-KQ_yftJiKVk8fnqUgIM:-KQ_yftJiKVk8fnqUgIN:b-4pmrrm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/269bd016ba2a65d05412b8157f0c7bc7d29d8d09/src/BloomExe/WebLibraryIntegration/BloomParseClient.cs#L78)):*
> ```Smalltalk
> 			catch (Exception)
> 			{
> 				// fallback below
> ```

Shall we log what the exception is?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1177)*

**Comment by andrew-polk** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/WebLibraryIntegration/BloomParseClient.cs, line 78 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1177#-KQ_yftJiKVk8fnqUgIM:-KQa-cKxLmV5GHsXOPlx:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/269bd016ba2a65d05412b8157f0c7bc7d29d8d09/src/BloomExe/WebLibraryIntegration/BloomParseClient.cs#L78)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary>
> Shall we log what the exception is?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1177)*

**Comment by hatton** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: 4 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Properties/Resources.Designer.cs, line 219 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1177#-KQgZXv8yOq9a9Tf3NUl:-KQgZXv8yOq9a9Tf3NUm:bnbr3eg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e44f42fb7405666371953538ecead2ff9a58ead/src/BloomExe/Properties/Resources.Designer.cs#L219)):*
> ```Smalltalk
>         ///}.
>         /// </summary>
>         internal static string current_service_urls {
> ```

Wants to be PascalCase.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1177)*

**Comment by andrew-polk** [comment]
Review status: 4 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Properties/Resources.Designer.cs, line 219 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1177#-KQgZXv8yOq9a9Tf3NUl:-KR4pHMuEjI2DvMoiZup:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0e44f42fb7405666371953538ecead2ff9a58ead/src/BloomExe/Properties/Resources.Designer.cs#L219)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary>
> Wants to be PascalCase.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1177)*

**Comment by hatton** [comment]
Reviewed 10 of 13 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1177)*

**Pull request merged**
