### PR TITLE
BL-6846 move old recording instead of copy/delete

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3027)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3027)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Edit/AudioRecording.cs, line 399 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3027#-LZ0VZBY5DctXvXjFxCs:-LZ0VZBZ2pJ1F3hirM9J:b9svllf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b0021f5f10ffe7ddf80504632c72b409d1ceaa7c/src/BloomExe/Edit/AudioRecording.cs#L399)):*
> ```Smalltalk
> 
> 			int counter = 0;
> 			backupPath = Path.ChangeExtension(path, "bak");
> ```

Won't this make the .wav and .mp3 get the same filename?
Don't we want to append .bak?
___
*[src/BloomExe/Edit/AudioRecording.cs, line 410 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3027#-LZ0WD9a3lWvAy1IcTC2:-LZ0WD9a3lWvAy1IcTC3:b-xfsovs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b0021f5f10ffe7ddf80504632c72b409d1ceaa7c/src/BloomExe/Edit/AudioRecording.cs#L410)):*
> ```
> 			// the system started recording. So we pay the price of a small chance of backups being left
> 			// around the book directory to avoid that danger.
> ```
I'm not sure about this.
Seems like we should be doing something to try to get rid of these.
Options:
1. Delete old backups right now. Disadvantage: will cause the same delay we are trying to get rid of. But we don't expect it to happen.
2. Make removal of these backups part of book initialization.
3. Don't try to remove .bak files ever but ensure that all publication paths (including bloom pack... ignore .bak files). Maybe they already do?
4. ?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3027)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/Edit/AudioRecording.cs, line 399 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3027#-LZ0VZBY5DctXvXjFxCs:-LZ0k3w29n2SKKCCW3Gl:b-czph9z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b0021f5f10ffe7ddf80504632c72b409d1ceaa7c/src/BloomExe/Edit/AudioRecording.cs#L399)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Won't this make the .wav and .mp3 get the same filename?
Don't we want to append .bak?
</blockquote></details>

Whichever comes second will detect a conflict (because the name it wants to use is already in use) and generate a slightly modified name. But appending .bak is probably an even better idea.
___
*[src/BloomExe/Edit/AudioRecording.cs, line 410 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3027#-LZ0WD9a3lWvAy1IcTC2:-LZ0jirAAxThmnfuKTWI:bcocr4i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b0021f5f10ffe7ddf80504632c72b409d1ceaa7c/src/BloomExe/Edit/AudioRecording.cs#L410)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> 			// the system started recording. So we pay the price of a small chance of backups being left
> 			// around the book directory to avoid that danger.
> ```
I'm not sure about this.
Seems like we should be doing something to try to get rid of these.
Options:
1. Delete old backups right now. Disadvantage: will cause the same delay we are trying to get rid of. But we don't expect it to happen.
2. Make removal of these backups part of book initialization.
3. Don't try to remove .bak files ever but ensure that all publication paths (including bloom pack... ignore .bak files). Maybe they already do?
4. ?
</blockquote></details>

In normal operation, the backup is either restored or deleted when the record button is released. So having them around should be rare.
I believe we already don't include .bak files in any of our publications.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3027)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/Edit/AudioRecording.cs, line 399 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3027#-LZ0VZBY5DctXvXjFxCs:-LZ0loa80qrYA19jpg6e:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b0021f5f10ffe7ddf80504632c72b409d1ceaa7c/src/BloomExe/Edit/AudioRecording.cs#L399)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Whichever comes second will detect a conflict (because the name it wants to use is already in use) and generate a slightly modified name. But appending .bak is probably an even better idea.
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3027)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomExe/Edit/AudioRecording.cs, line 410 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3027#-LZ0WD9a3lWvAy1IcTC2:-LZ0zcrZ-q4gyNnrFHy8:b3xxp43) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b0021f5f10ffe7ddf80504632c72b409d1ceaa7c/src/BloomExe/Edit/AudioRecording.cs#L410)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

In normal operation, the backup is either restored or deleted when the record button is released. So having them around should be rare.
I believe we already don't include .bak files in any of our publications.
</blockquote></details>

The ideal still seems we would try to get rid of them at some point.
What do you think of trying to delete all associated backups for a given file on a separate thread rather than just the most recent?
Or removing all audio/*.bak files on book initialization?

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3027)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3027)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Edit/AudioRecording.cs, line 410 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3027#-LZ0WD9a3lWvAy1IcTC2:-LZ1e_DZ5zu2H1rMdCz5:b83tqp1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b0021f5f10ffe7ddf80504632c72b409d1ceaa7c/src/BloomExe/Edit/AudioRecording.cs#L410)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The ideal still seems we would try to get rid of them at some point.
What do you think of trying to delete all associated backups for a given file on a separate thread rather than just the most recent?
Or removing all audio/*.bak files on book initialization?
</blockquote></details>

At this point, it will get rid of all backups with the right prefix upon making a successful recording.
Timing is not critical at this point so I haven't used a background thread. In fact, I no longer see a reason to pick on one particular backup to delete in the background during the recording, so I removed that too. Usually there wouldn't even be one to delete at that point.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3027)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3027)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
