### PR TITLE
BL-13426 Ensure bloomcollection file is .bloomcollection or .bloomlibrary

### PR DESCRIPTION
**Pull request by nabalone**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6481)

### CODE REVIEW

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6481)* status: 0 of 5 files reviewed, 3 unresolved discussions

___
*[`DistFiles/localization/en/BloomLowPriority.xlf` line 47 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6481#-NxYxXge29ea4sqmco9H:-NxYxXge29ea4sqmco9I:b6nn2iv) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/5953068d5814460e31ced210ac720347be1cf825/DistFiles/localization/en/BloomLowPriority.xlf#L47)):*
> ```XML
>                 <note>ID: OpenCreateCloneControl.InZipFileMessage</note>
>             </trans-unit>
>             <trans-unit id="OpenCreateCloneControl.InvalidFileTypeMessage">
> ```

Not sure what priority this should be
___
*[`src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs` line 200 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6481#-NxYxaz59OBvQT4e46pe:-NxYxaz59OBvQT4e46pf:b-gwza1s) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/749bc5ca1e2b3fa3415739f5f886aa888faac2dc/src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs#L200)):*
> ```Smalltalk
>         public void SelectCollectionAndClose(string path)
>         {
>             if (Bloom.Utils.LongPathAware.GetExceedsMaxPath(path))
> ```

Moved this into `ReportInvalidCollection` because I don't see why the `Add Source Collection` file selection shouldn't have this check, and to put all the checks together
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 455 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6481#-NxYy-XB2oFXQty1BgTk:-NxYy-XB2oFXQty1BgTl:bj5xvt6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/5953068d5814460e31ced210ac720347be1cf825/src/BloomExe/web/controllers/CollectionApi.cs#L455)):*
> ```Smalltalk
>                 if (
>                     dlg.ShowDialog() == DialogResult.Cancel
>                     || MiscUtils.ReportIfInvalidCollection(dlg.FileName)
> ```

This means more checks in the file selection process for Add Source Collection. Please let me know if there is a reason we don't want these checks to happen here for some reason. e.g. I don't think a user should be selecting from their existing source collections folder when adding a source collection, and it wouldn't do anything anyway

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6481)* status: all files reviewed, 5 unresolved discussions (waiting on @nabalone)

___
*[`DistFiles/localization/en/BloomLowPriority.xlf` line 47 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6481#-NxYxXge29ea4sqmco9H:-NxZ-Xkr8EZRhlS8S5yg:b-adurut) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/5953068d5814460e31ced210ac720347be1cf825/DistFiles/localization/en/BloomLowPriority.xlf#L47)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Not sure what priority this should be
</blockquote></details>

Low is right. 
As a general rule, anything we hope the user doesn't see is low.
___
*[`src/BloomExe/Utils/MiscUtils.cs` line 318 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6481#-NxZ-tUJ-Ucvi2RUqnHS:-NxZ-tUJ-Ucvi2RUqnHT:bw5z82m) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/5953068d5814460e31ced210ac720347be1cf825/src/BloomExe/Utils/MiscUtils.cs#L318)):*
> ```Smalltalk
>                 var msg = L10NSharp.LocalizationManager.GetString(
>                     "OpenCreateCloneControl.InvalidFileTypeMessage",
>                     "Please select a .bloomCollection file or a .bloomLibrary file."
> ```

I think the message should just be "Please select a .bloomCollection file." since the .bloomLibrary extension is just legacy (from my understanding).
___
*[`src/BloomExe/Utils/MiscUtils.cs` line 345 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6481#-NxZ1g3KCZnMCfZ4wnsJ:-NxZ1g3LB8ozm5pLnvtQ:bnespc2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/5953068d5814460e31ced210ac720347be1cf825/src/BloomExe/Utils/MiscUtils.cs#L345)):*
Maybe IsInvalidCollectionExtension?

Maybe add a comment like
> .bloomlibrary is just for legacy reasons. See also OpenAndCreateCollectionDialog.

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6481)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Utils/MiscUtils.cs` line 318 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6481#-NxZ-tUJ-Ucvi2RUqnHS:-NxmCj0QCQr6EeBc4-53:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/5953068d5814460e31ced210ac720347be1cf825/src/BloomExe/Utils/MiscUtils.cs#L318)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think the message should just be "Please select a .bloomCollection file." since the .bloomLibrary extension is just legacy (from my understanding).
</blockquote></details>

Done.
___
*[`src/BloomExe/Utils/MiscUtils.cs` line 345 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6481#-NxZ1g3KCZnMCfZ4wnsJ:-NxmE0mAAllHxYP1Vk3D:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/5953068d5814460e31ced210ac720347be1cf825/src/BloomExe/Utils/MiscUtils.cs#L345)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Maybe IsInvalidCollectionExtension?

Maybe add a comment like
> .bloomlibrary is just for legacy reasons. See also OpenAndCreateCollectionDialog.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6481)* status: all files reviewed, 2 unresolved discussions

**Pull request merged**
