### PR TITLE
Update SIL packages and dependencies

### PR DESCRIPTION
**Pull request by JohnThomson**
This allows us to pull in an important fix to PalasoImage.FromFileRobustly()

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/BloomExe.csproj` line 1234 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvPq8I8fv7TB8GDiFI:-NOvPq8I8fv7TB8GDiFJ:bi8cane) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomExe/BloomExe.csproj#L1234)):*
> ```XML
>   </ItemGroup>
>   <ItemGroup>
>     <None Include="README.md" />
> ```

This was added for that readme file we deleted, so we should delete this.
Same for BloomTests.
___
*[`src/BloomTests/BloomTests.csproj` line 109 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvQ8zSDd-VTLSSFNPW:-NOvQ8zSDd-VTLSSFNPX:bm4zesq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomTests/BloomTests.csproj#L109)):*
> ```XML
>     </Reference>
>     <Reference Include="DialogAdapters, Version=0.1.11.0, Culture=neutral, PublicKeyToken=7dc842182b0626dc, processorArchitecture=MSIL">
>       <HintPath>..\..\packages\DialogAdapters.Gtk2.0.1.11\lib\net461\DialogAdapters.dll</HintPath>
> ```

Need to get rid of this change (and the movement of the corresponding comment).
___
*[`src/BloomTests/BloomTests.csproj` line 121 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvQDVaBexo-xzO1qWn:-NOvQDVaBexo-xzO1qWo:bmxoxkj) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomTests/BloomTests.csproj#L121)):*
> ```XML
>     <Reference Include="FFMpegCore, Version=5.0.0.0, Culture=neutral, processorArchitecture=MSIL">
>       <HintPath>..\..\packages\FFMpegCore.5.0.0\lib\netstandard2.0\FFMpegCore.dll</HintPath>
>     </Reference>
> ```

We decided to remove this for Bloom.exe, so we should here, too.
___
*[`src/BloomTests/packages.config` line 8 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvQTHv6RrSZ8sT4Uec:-NOvQTHv6RrSZ8sT4Ued:b-varly8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomTests/packages.config#L8)):*
> ```XML
>   <package id="CommandLineParser" version="2.8.0" targetFramework="net461" />
>   <package id="DialogAdapters" version="0.1.11" targetFramework="net461" />
>   <package id="DialogAdapters.Gtk2" version="0.1.11" targetFramework="net472" />
> ```

Need to get rid of this change and the corresponding comment deletion.
___
*[`src/BloomTests/packages.config` line 10 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvQXItBi8xnjcWAyjf:-NOvQXItBi8xnjcWAyjg:b-d8jlny) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomTests/packages.config#L10)):*
> ```XML
>   <package id="DialogAdapters.Gtk2" version="0.1.11" targetFramework="net472" />
>   <package id="Enchant.Net" version="1.4.2" targetFramework="net461" />
>   <package id="FFMpegCore" version="5.0.0" targetFramework="net472" />
> ```

Let's remove this.
___
*[`src/BloomTests/README.md` line 1 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvQ_Ug3K5bmamrhSHN:-NOvQ_Ug3K5bmamrhSHO:buh8gf3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomTests/README.md#L1)):*
> ```Markdown
> # Instances
> ```

Let's delete this file like we did in Bloom.exe.

**Review by StephenMcConnel — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657)* status: all files reviewed, 9 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/BloomExe.csproj` line 378 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvR2tODQ8ROkfmuKxr:-NOvR2tODQ8ROkfmuKxs:b-4rjmws) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomExe/BloomExe.csproj#L378)):*
> ```XML
>       <HintPath>..\..\packages\System.Security.Cryptography.X509Certificates.4.3.0\lib\net461\System.Security.Cryptography.X509Certificates.dll</HintPath>
>       <Private>True</Private>
>     </Reference>
> ```

It seems like VStudio automatically inserts these, but they aren't really needed by Bloom.  At least that's what I remember from my earlier bout with updating libpalaso.
___
*[`src/BloomExe/Linux/packages.config` line 24 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvRNpf0EGsUHmOHKzq:-NOvRNpg6-WcJx0IIGoo:bxyp16e) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomExe/Linux/packages.config#L24)):*
> ```XML
>   <package id="ibusdotnet" version="2.0.3" targetFramework="net461" />
>   <package id="icu.net" version="2.8.1" targetFramework="net472" />
>   <package id="Instances" version="3.0.0" targetFramework="net472" />
> ```

What is this?  Is it really needed?
___
*[`src/BloomExe/Publish/PublishView.cs` line 975 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvRcsx8zhWaI7RXkbK:-NOvRcsx8zhWaI7RXkbL:b-rvb97k) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomExe/Publish/PublishView.cs#L975)):*
> ```Smalltalk
> 			Logger.WriteEvent("Calling Print on PDF Viewer");
> 			_model.ReportAnalytics("Print PDF");
> 			this._model.BookSelection.CurrentSelection.ReportSimplisticFontAnalytics(Bloom.ToPalaso.FontAnalytics.FontEventType.PublishPdf, "Print PDF");
> ```

I thought we had moved that stuff to libpalaso, but I could be mistaken.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657)* status: all files reviewed, 9 unresolved discussions (waiting on @andrew-polk and @StephenMcConnel)

___
*[`src/BloomExe/BloomExe.csproj` line 378 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvR2tODQ8ROkfmuKxr:-NOvSzLcDaW4AVAMxudw:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomExe/BloomExe.csproj#L378)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

It seems like VStudio automatically inserts these, but they aren't really needed by Bloom.  At least that's what I remember from my earlier bout with updating libpalaso.
</blockquote></details>

Done.



_Code quote:_
```XML
System.Security.Cryptography.Algorithms
```
___
*[`src/BloomExe/BloomExe.csproj` line 1234 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvPq8I8fv7TB8GDiFI:-NOvROl31wQ_iPFi4xYF:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomExe/BloomExe.csproj#L1234)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This was added for that readme file we deleted, so we should delete this.
Same for BloomTests.
</blockquote></details>

Done.
___
*[`src/BloomExe/Linux/packages.config` line 24 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvRNpf0EGsUHmOHKzq:-NOvTLop8yhDlqYf8nTc:b2vyj56) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomExe/Linux/packages.config#L24)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

What is this?  Is it really needed?
</blockquote></details>

Package manager added it automatically. I don't know why or whether it was right.
___
*[`src/BloomExe/Publish/PublishView.cs` line 975 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvRcsx8zhWaI7RXkbK:-NOvT3Tu9ip3dHQpPka9:bowa238) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomExe/Publish/PublishView.cs#L975)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I thought we had moved that stuff to libpalaso, but I could be mistaken.
</blockquote></details>

It has been copied there, but we decided 5.4 should go on using the version it currently does, since we aren't trying to fix something there. However, the DLL upgrade made the reference ambiguous, so I had to make it more specific.
___
*[`src/BloomTests/BloomTests.csproj` line 109 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvQ8zSDd-VTLSSFNPW:-NOvS3c91dCyeQCHK-gS:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomTests/BloomTests.csproj#L109)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Need to get rid of this change (and the movement of the corresponding comment).
</blockquote></details>

Done.
___
*[`src/BloomTests/BloomTests.csproj` line 121 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvQDVaBexo-xzO1qWn:-NOvS3OXAPjH1j0wmsY0:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomTests/BloomTests.csproj#L121)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We decided to remove this for Bloom.exe, so we should here, too.
</blockquote></details>

Done.
___
*[`src/BloomTests/packages.config` line 8 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvQTHv6RrSZ8sT4Uec:-NOvSPvvAxz2E6MKBokV:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomTests/packages.config#L8)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Need to get rid of this change and the corresponding comment deletion.
</blockquote></details>

Done.
___
*[`src/BloomTests/packages.config` line 10 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvQXItBi8xnjcWAyjf:-NOvSU5z5QH-UZLeDkL5:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomTests/packages.config#L10)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's remove this.
</blockquote></details>

Done.
___
*[`src/BloomTests/README.md` line 1 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvQ_Ug3K5bmamrhSHN:-NOvSeG-6W3TROOpfMgN:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomTests/README.md#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's delete this file like we did in Bloom.exe.
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/BloomExe.csproj` line 378 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvR2tODQ8ROkfmuKxr:-NOvcMp29WhtOFLYVH1s:bzf1wk) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomExe/BloomExe.csproj#L378)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

If we are not adding it for BloomExe, we shouldn't for BloomTests.
And we need to update both package.configs accordingly.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @StephenMcConnel)

___
*[`src/BloomExe/BloomExe.csproj` line 378 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvR2tODQ8ROkfmuKxr:-NOzBQDXDbZfwmGdKIk7:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomExe/BloomExe.csproj#L378)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If we are not adding it for BloomExe, we shouldn't for BloomTests.
And we need to update both package.configs accordingly.
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/BloomExe.csproj` line 378 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvR2tODQ8ROkfmuKxr:-NOzBsQy8BycO4Dstt1z:b1bisq1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomExe/BloomExe.csproj#L378)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BloomExe/packages.config is still adding them.

**Review by StephenMcConnel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 10 files at r1, 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-:-NOzCQXoBez-pvDP4U9Y:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Linux/packages.config` line 24 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvRNpf0EGsUHmOHKzq:-NOzC2mm72IOtgeuP35r:b-1agykm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomExe/Linux/packages.config#L24)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Package manager added it automatically. I don't know why or whether it was right.
</blockquote></details>

Well, if it doesn't work for Linux, I'll investigate further to see if it's needed on Windows.  It may be like the security related packages/DLLs.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @StephenMcConnel)

___
*[`src/BloomExe/BloomExe.csproj` line 378 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvR2tODQ8ROkfmuKxr:-NOzDi-G9lESTHNi6ard:b6uijiq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomExe/BloomExe.csproj#L378)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

BloomExe/packages.config is still adding them.
</blockquote></details>

Sorry. Thought I had looked but was seeing Linux/packages.config
___
*[`src/BloomExe/Linux/packages.config` line 24 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657#-NOvRNpf0EGsUHmOHKzq:-NOzDsw2EEA1lo8kxQby:b-ucfkn4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e73795f27d4d06107b26ee223224f4938c5e497a/src/BloomExe/Linux/packages.config#L24)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Well, if it doesn't work for Linux, I'll investigate further to see if it's needed on Windows.  It may be like the security related packages/DLLs.
</blockquote></details>

Thanks.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by andrew-polk — APPROVED** [review]
> Dismissed @StephenMcConnel from a discussion.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by andrew-polk — APPROVED** [review]
> Dismissed @JohnThomson from a discussion.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by StephenMcConnel — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5657)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
