### PR TITLE
BL-5959 require enterprise for sign lang and image desc

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2492)

### CODE REVIEW

**Comment by andrew-polk** [comment]
:lgtm: 
Assuming this needs UI Review, though.

---

Reviewed 5 of 5 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2492#-:-LEtz3hq8plyotdcztbu:b-mm5j18)*

**Comment by hatton** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 84 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2492#-LF83Od57npefzrOs7GN:-LF83Od57npefzrOs7GO:b-n1pbuy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9ffd413f173612e0a0f66e0bf2bb7afac9f4044a/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L84)):*
> ```XML
>     public render() {
>         return (
>             <RequiresBloomEnterpriseWrapper>
> ```

This is nice

---

*[src/BloomBrowserUI/react_components/requiresBloomEnterprise.less, line 11 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2492#-LF82z8yBY_ambVsSp_U:-LF82z8yBY_ambVsSp_V:b-m9ef1j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9ffd413f173612e0a0f66e0bf2bb7afac9f4044a/src/BloomBrowserUI/react_components/requiresBloomEnterprise.less#L11)):*
> ```Less
>     display:flex;
> }
> @triangleSize: 18px;
> ```

The "warning" symbol is used in several places in Bloom. Can we reused one of those or make this one reusable for other places, in stead of redefining it each time?

---

*[src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx, line 65 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2492#-LF82qeG46M22ZrRAbT5:-LF82qeG46M22ZrRAbT6:b-oa85w8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9ffd413f173612e0a0f66e0bf2bb7afac9f4044a/src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx#L65)):*
> ```XML
> export function enterpriseFeaturesEnabled(): boolean {
>     var page = ToolboxToolReactAdaptor.getPage();
>     return (page.classList.contains("enterprise-on"));
> ```

I see that this works for Edit Tab...  If instead we had an api endpoint for this, would this class would it then be useful for for Collection and Publish tab uses, too?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2492)*

**Comment by JohnThomson** [comment]
Review status: 1 of 8 files reviewed, 3 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 84 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2492#-LF83Od57npefzrOs7GN:-LFIufOcE2qOACfru2IH:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9ffd413f173612e0a0f66e0bf2bb7afac9f4044a/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L84)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This is nice
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/react_components/requiresBloomEnterprise.less, line 11 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2492#-LF82z8yBY_ambVsSp_U:-LFIukI35DvszFWGoJ2M:bh7zmqr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9ffd413f173612e0a0f66e0bf2bb7afac9f4044a/src/BloomBrowserUI/react_components/requiresBloomEnterprise.less#L11)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

The "warning" symbol is used in several places in Bloom. Can we reused one of those or make this one reusable for other places, in stead of redefining it each time?
</blockquote></details>

I found warning.svg in our artwork folder, but can't find that it is used anywhere (and it doesn't look like your mock-up for this issue);
C# code sometimes calls MessageBox with arguments that result in the system warning icon showing;
in a couple of places we use SystemIcons.Warning (probably the same icon);
I can't find any existing HTML world stuff that shows a warning icon.
Can you think of a specific place one appears in the HTML UI?

---

*[src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx, line 65 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2492#-LF82qeG46M22ZrRAbT5:-LFIupxq6dfMdny-pUXI:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9ffd413f173612e0a0f66e0bf2bb7afac9f4044a/src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx#L65)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I see that this works for Edit Tab...  If instead we had an api endpoint for this, would this class would it then be useful for for Collection and Publish tab uses, too?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2492)*

**Comment by andrew-polk** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed, 3 unresolved discussions (waiting on @hatton)

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2492)*

**Comment by hatton** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @hatton)

---

*[src/BloomBrowserUI/react_components/requiresBloomEnterprise.less, line 11 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2492#-LF82z8yBY_ambVsSp_U:-LFJblkw9oU2mVSK2EwA:b4gwoo2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9ffd413f173612e0a0f66e0bf2bb7afac9f4044a/src/BloomBrowserUI/react_components/requiresBloomEnterprise.less#L11)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I found warning.svg in our artwork folder, but can't find that it is used anywhere (and it doesn't look like your mock-up for this issue);
C# code sometimes calls MessageBox with arguments that result in the system warning icon showing;
in a couple of places we use SystemIcons.Warning (probably the same icon);
I can't find any existing HTML world stuff that shows a warning icon.
Can you think of a specific place one appears in the HTML UI?
</blockquote></details>



---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2492)*

**Comment by hatton** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @hatton)

---

*[src/BloomBrowserUI/react_components/requiresBloomEnterprise.less, line 11 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2492#-LF82z8yBY_ambVsSp_U:-LFJbxM-CUTNmen6fZj8:b-uer69v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9ffd413f173612e0a0f66e0bf2bb7afac9f4044a/src/BloomBrowserUI/react_components/requiresBloomEnterprise.less#L11)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>


</blockquote></details>

Also there is a warning symbol above the laptop symbol in the Talking Book, but that's probably built-in to that icon, not something we overlay.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2492)*

**Comment by hatton** [comment]
@JohnThomson the icon thing is not worth holding this up. But I'm afraid it has conflicts now. Sorry!

**Comment by hatton** [comment]
I resolved the conflicts

**Pull request merged**
