### PR TITLE
Add background audio attributes to title page

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1138)

### CODE REVIEW

**Comment by JohnThomson** [comment]
:lgtm: with a very minor quibble

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/BookData.cs, line 602 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1138#-KMa7fg1cq4vYeuuRWiI:-KMa7fg1cq4vYeuuRWiJ:-1681673914) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/095d64166bd56624efacf4c401167819b20d28d8/src/BloomExe/Book/BookData.cs#L602)):*
> ```Smalltalk
> 
> 		/// <summary>
> 		/// walk through the sourceDom, collecting up values from elements that have data-book or data-collection attributes.
> ```

or data-book-attributes :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1138#-:-KMa8Z5Xnp8-mvRsNrxw:249677779)*

**Comment by hatton** [comment]
It would be good to have this new feature of dataset added to the unit tests for dataset.

**Comment by andrew-polk** [comment]
Added another unit test in BookDataTests

---

Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/BookData.cs, line 602 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1138#-KMa7fg1cq4vYeuuRWiI:-KMeRsiNcGglBSLk1xzD:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/095d64166bd56624efacf4c401167819b20d28d8/src/BloomExe/Book/BookData.cs#L602)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary>
> or data-book-attributes :-)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1138#-:-KMeRwCuSu_qzyzCnVzS:-1702542713)*

**Comment by hatton** [comment]
Reviewed 3 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1138)*

**Pull request merged**
