### PR TITLE
BL-6203 Allow Branding settings.json file to update data div

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2562)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2562)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[DistFiles/branding/PNG-RISE/settings.json, line 7 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2562#-LGkZK2G0As2Gd-g3bzI:-LGkZK2G0As2Gd-g3bzJ:bhygfz5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6b95016cdd55ccddb1c577c1b5ab86b0817c31ca/DistFiles/branding/PNG-RISE/settings.json#L7)):*
> ```JSON
>             "Lang": "en",
>             "Content":
>                 "<p>If you have feedback (spelling corrections, sentence order, or other changes) that should be made to this book, please contact SIL PNG.</p><p>Email: do-smls@sil.org.pg</p><p>Phone:  7217-0330 extension 4604 or 4161</p><p>Or stop by an SIL office</p>"
> ```

The user now wants books@sil.org.pg per comment in the card.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2562)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[DistFiles/branding/PNG-RISE/settings.json, line 2 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2562#-LGl6QhA3pZ_q9Iv_AR8:-LGl6QhB3U1gti4r-1no:b-vonpwt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6b95016cdd55ccddb1c577c1b5ab86b0817c31ca/DistFiles/branding/PNG-RISE/settings.json#L2)):*
> ```JSON
> {
>     "DefaultData": [
> ```

In the code, you have a ``Override`` attribute. That suggests to me that "Default" here is  misleading.
"presets" would be a nice alternative.
___
*[DistFiles/branding/PNG-RISE/settings.json, line 4 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2562#-LGl6SB28M825zHRQ_j-:-LGl6SB3CNzg7ZjMT2w1:b-qaflk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6b95016cdd55ccddb1c577c1b5ab86b0817c31ca/DistFiles/branding/PNG-RISE/settings.json#L4)):*
> ```JSON
>     "DefaultData": [
>         {
>             "DataBook": "insideBackCover",
> ```

Are there constraints preventing mirroring the existing xml names, e.g. "data-book", "lang"?

**Review by hatton — COMMENTED** [review]
Can you speak to why you didn't want to do this from the issue?

>  Currently, BookCopyrightAndLicense has code that asks the branding api for the 2 known settings. Get rid of that.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2562#-:-LGl6xDHEyO5udkUOd7a:b-757tt6)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
Primarily, an oversight. I think I skipped it at first because I couldn't understand it, and forgot to come back to it. I'm still not entirely sure what you mean. The code in question actually asks the branding API for the whole Settings object derived from the JSON, and makes use of all THREE properties that object defines. My current hypothesis is that you mean that the new mechanism makes the whole old one obsolete, and we should remove it (and presumably rewrite any existing settings.json files in the new style).
Can do that if you want, but the old logic does a little more than the new: it is smart enough to refuse to change any part of the metadata if any part of it is non-empty. Do we want to move that into the new code, or discard it?
I suppose backwards compatibility isn't an issue (though it was in my thoughts deciding not to consider this code obsolete myself), since any Bloom release which has the new code can have an updated version of the relevant branding packs?

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2562#-:-LGlQaU026DgCwRwrw4f:bpffpj9)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[DistFiles/branding/PNG-RISE/settings.json, line 2 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2562#-LGl6QhA3pZ_q9Iv_AR8:-LGlScHN1FYmle0SrmCH:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6b95016cdd55ccddb1c577c1b5ab86b0817c31ca/DistFiles/branding/PNG-RISE/settings.json#L2)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

In the code, you have a ``Override`` attribute. That suggests to me that "Default" here is  misleading.
"presets" would be a nice alternative.

</blockquote></details>

Done.
___
*[DistFiles/branding/PNG-RISE/settings.json, line 4 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2562#-LGl6SB28M825zHRQ_j-:-LGlSekj1UBrSKy2k31K:bqpiosk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6b95016cdd55ccddb1c577c1b5ab86b0817c31ca/DistFiles/branding/PNG-RISE/settings.json#L4)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Are there constraints preventing mirroring the existing xml names, e.g. "data-book", "lang"?
</blockquote></details>

The existing fields in settings.json used C#-style names, so I followed suit.  We can't use data-book as a C# field name, but we could use JsonProperty annotations to change the names for the settings.json file. For me, it's a bit of a toss-up whether the gain of using json-type naming and the same names as in the html is worth the pain of using different names in the json file and the C# that interacts with it. I can try it if you want.
___
*[DistFiles/branding/PNG-RISE/settings.json, line 7 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2562#-LGkZK2G0As2Gd-g3bzI:-LGlQZ1A73IakdMVHwUi:b-376vyb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6b95016cdd55ccddb1c577c1b5ab86b0817c31ca/DistFiles/branding/PNG-RISE/settings.json#L7)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The user now wants books@sil.org.pg per comment in the card.
</blockquote></details>

Done. Good catch.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2562)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[DistFiles/branding/PNG-RISE/settings.json, line 2 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2562#-LGl6QhA3pZ_q9Iv_AR8:-LGlV5nqDCHLMf5Lv09S:b-t1worp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6b95016cdd55ccddb1c577c1b5ab86b0817c31ca/DistFiles/branding/PNG-RISE/settings.json#L2)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like this file got missed in the DefaultData => Presets change.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2562)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @hatton)

___
*[DistFiles/branding/PNG-RISE/settings.json, line 2 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2562#-LGl6QhA3pZ_q9Iv_AR8:-LGzd3sR-7WQIMERkEMF:b-886gsx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6b95016cdd55ccddb1c577c1b5ab86b0817c31ca/DistFiles/branding/PNG-RISE/settings.json#L2)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like this file got missed in the DefaultData => Presets change.
</blockquote></details>

Fixed

**Review by andrew-polk — APPROVED** [review]
I think this is waiting for @hatton at this point.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2562#-:-LGzuYRuCcpki-oWiLYb:b7nydz7)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Review by hatton — COMMENTED** [review]
> Can do that if you want, but the old logic does a little more than the new: it is smart enough to refuse to change any part of the metadata if any part of it is non-empty. Do we want to move that into the new code, or discard it?

Yeah, I think in a program as big as Bloom, if we see a clear way reduce complexity/surface area, or prevent increasing it, we must jump at it.

How about this: each preset has an mandatory attribute that takes an enum that selects for a behavior. The current choices would be: ifEmpty, ifAllCopyrightEmpty.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2562#-:-LH9r3nPDR-8uebt0kL7:b51tbew)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Review by JohnThomson — COMMENTED** [review]
OK, I've made the json use book-data and similar json-type names; got rid of the obsolete branding settings code and reworked relevant tests; replaced Override with a new, required property condition with values ifEmpty, ifAllCopyrightEmpty, and always...the latter is equivalent to the old Override=true. I think this addresses all the suggestions that have been made.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2562#-:-LHEwMjq7dS57l-M4NR4:b-a3n7tw)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @hatton)

**Pull request merged**
