### PR TITLE
Show progress during Create Collection (BL-9676)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 612 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293#-MW9oTSL0wPCrZWkzpNP:-MW9oTSL0wPCrZWkzpNQ:b-s0hosa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ba27e77db67898f0b4f5cbcaabe71943047567f6/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L612)):*
> ```Smalltalk
> 		/// </summary>
> 		/// <param name="repoFolder"></param>
> 		public void ConnectToTeamCollection(string repoFolder, WebSocketProgress progress)
> ```

Sorry I know this isn't new but the name does not communicate what is being done. We're already in a kind of "TeamCollection" object, so we're connecting to another one? That's what the method name suggests to me.

Based on the comment "... at least for now, it expects it to have nothing in it", then would `SetupRepoFolder` be correct?

Of course `ConnectToTeamCollectionWIthProgressDialog` would be similar.
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 626 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293#-MW9psbRAP_GG4nU4ufO:-MW9psbRAP_GG4nU4ufP:b7qfnwb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ba27e77db67898f0b4f5cbcaabe71943047567f6/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L626)):*
> ```Smalltalk
> 		public void ConnectToTeamCollectionWithProgressDialog(string repoFolder)
> 		{
> 			var url = BloomFileLocator.GetBrowserFile(false, "utils", "IndependentProgressDialog.html").ToLocalhost()
> ```

Now would be a great time to upgrade this to use your new `ReactDialog`.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 159 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293#-MWAVRG4BYFy-jhsZt-C:-MWAVRG4BYFy-jhsZt-D:b-4ckw9b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ba27e77db67898f0b4f5cbcaabe71943047567f6/src/BloomExe/TeamCollection/TeamCollection.cs#L159)):*
> ```
> WebSocketProgress
> ```
Might as well make this IWebSocketProgress, methinks.
Same for new param on ConnectToTeamCollection.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 612 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293#-MW9oTSL0wPCrZWkzpNP:-MWAdCrw3mUCE-1jex5-:b-y43f76) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ba27e77db67898f0b4f5cbcaabe71943047567f6/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L612)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Sorry I know this isn't new but the name does not communicate what is being done. We're already in a kind of "TeamCollection" object, so we're connecting to another one? That's what the method name suggests to me.

Based on the comment "... at least for now, it expects it to have nothing in it", then would `SetupRepoFolder` be correct?

Of course `ConnectToTeamCollectionWIthProgressDialog` would be similar.
</blockquote></details>

Well, it does make one local change to link the local connection to the new TC repo folder. I decided on SetupTeamCollection
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 626 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293#-MW9psbRAP_GG4nU4ufO:-MWB2GlAArssIUYIYg32:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ba27e77db67898f0b4f5cbcaabe71943047567f6/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L626)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Now would be a great time to upgrade this to use your new `ReactDialog`.
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 159 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293#-MWAVRG4BYFy-jhsZt-C:-MWB2ihiAVWU4R1jg3ph:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ba27e77db67898f0b4f5cbcaabe71943047567f6/src/BloomExe/TeamCollection/TeamCollection.cs#L159)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> WebSocketProgress
> ```
Might as well make this IWebSocketProgress, methinks.
Same for new param on ConnectToTeamCollection.
</blockquote></details>

Done.

**Review by hatton — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 6 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 642 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293#-MWBABG15gwuHZSXb92N:-MWBABG15gwuHZSXb92O:b-hmrt57) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/afd8decd691e5003b9763b0969520f57128cc5cd/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L642)):*
> ```Smalltalk
> 				// handle letting the user abort.
> 				dlg.ControlBox = false;
> 				var worker = new BackgroundWorker();
> ```

I know I should remember this, but alas... I find myself wondering about why this is done in the background, and if it has to be. Could be how sockets work, or having an embedded browser or... I don't know. Can you add a comment about that?
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 646 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293#-MWBAIPR4-CEOIJftpPz:-MWBAIPR4-CEOIJftpQ-:b3zrwh3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/afd8decd691e5003b9763b0969520f57128cc5cd/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L646)):*
> ```Smalltalk
> 				{
> 					// A way of waiting until the dialog is ready to receive progress messages
> 					while (!SocketServer.IsSocketOpen(kWebSocketContext))
> ```

This seems like something each thing wanting to do progress would need to repeat. Can you think of a way to move this feature into a component? In fact, could this entire method be a component (e.g. `BrowserProgressDialog`) that takes a delegate for the work to be done in the background?

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 141 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293#-MWBDXLSAkn_lVQPe1TO:-MWBDXLSAkn_lVQPe1TP:buct7ag) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/afd8decd691e5003b9763b0969520f57128cc5cd/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L141)):*
> ```Smalltalk
> 						CurrentCollection = new FolderTeamCollection(this, _localCollectionFolder, repoFolderPath);
> 						CurrentCollectionEvenIfDisabled = CurrentCollection;
> 						CurrentCollection.SocketServer = SocketServer;
> ```

Is there a reason this isn't a parameter to FolderTeamCollection?

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293)* status: 6 of 10 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 642 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293#-MWBABG15gwuHZSXb92N:-MWCVMjZBWYPfuxO8u2k:byromj2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/afd8decd691e5003b9763b0969520f57128cc5cd/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L642)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I know I should remember this, but alas... I find myself wondering about why this is done in the background, and if it has to be. Could be how sockets work, or having an embedded browser or... I don't know. Can you add a comment about that?
</blockquote></details>

I tried to explain in the remarks on the new BrowserProgressDialog class.
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 646 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293#-MWBAIPR4-CEOIJftpPz:-MWCVS3Z5nkkikO2TCIa:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/afd8decd691e5003b9763b0969520f57128cc5cd/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L646)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This seems like something each thing wanting to do progress would need to repeat. Can you think of a way to move this feature into a component? In fact, could this entire method be a component (e.g. `BrowserProgressDialog`) that takes a delegate for the work to be done in the background?
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 141 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293#-MWBDXLSAkn_lVQPe1TO:-MWCVp5W9MZzlVtc0fH_:bng4e2s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/afd8decd691e5003b9763b0969520f57128cc5cd/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L141)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is there a reason this isn't a parameter to FolderTeamCollection?
</blockquote></details>

I don't like masses of constructor arguments, especially when some are optional as is (increasingly) the case here. And many cases where an FTC is created (especially in testing) don't need a SocketServer at all, so having to manufacture one or mock one would just be a nuisance. It's in fact only needed for one thing, to run the progress dialog, so perhaps we could find some other way for the progress dialog to get it. But I can't think of an elegant one immediately.

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r2, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293)* status: 7 of 10 files reviewed, 5 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomExe/MiscUI/BrowserProgressDialog.cs, line 26 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293#-MWQSGTJBiR4hKWGGgp_:-MWQSGTJBiR4hKWGGgpa:b-ue9w0p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2b64cac02ee19e0243bdfe98c968f7f04c5da140/src/BloomExe/MiscUI/BrowserProgressDialog.cs#L26)):*
> ```Smalltalk
> 	public class BrowserProgressDialog
> 	{
> 		public static void DoWorkWithProgressDialog(BloomWebSocketServer socketServer, string socketContext, string title,
> ```

Let's add a <params> section that explains the return value of doWhat. I think it is something like "function that does the work and sends progress. Should return false to close the dialog, true to leave it open and show <here I'm unclear exactly what buttons gets shown>."
___
*[src/BloomExe/MiscUI/BrowserProgressDialog.cs, line 46 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293#-MWQRoReAKj0OC0O_04c:-MWQRoRf4Hr0zZK0b1Rh:b-nkpebq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2b64cac02ee19e0243bdfe98c968f7f04c5da140/src/BloomExe/MiscUI/BrowserProgressDialog.cs#L46)):*
> ```Smalltalk
> 					while (!socketServer.IsSocketOpen(socketContext))
> 						Thread.Sleep(50);
> 					var problems = doWhat(progress);
> ```

This would be significantly clearer if it didn't alternate between "problems' and "show-buttons'.  What I think is happening semantically here is.... well I'll make a comment above about declaringthe  api for `doWhat`.

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293)* status: all files reviewed, 6 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1350 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293#-MWQT4EEBg8H-HIkdAes:-MWQT4EEBg8H-HIkdAet:bln4n39) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2b64cac02ee19e0243bdfe98c968f7f04c5da140/src/BloomExe/TeamCollection/TeamCollection.cs#L1350)):*
> ```Smalltalk
> 					// for the user to read them and close the dialog manually?
> 					// Currently it stays open only if we detected problems.
> 					return problems;
> ```

I get that this works based on truthiness, but just reading it, one would think that the point is to return the problems. How about `problems.length > 0` ?

**Review by JohnThomson — COMMENTED** [review]
The architecture must be a disaster if it's this difficult to explain the api clearly...but I don't know how to improve it. Maybe we should do an interactive review?

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293#-:-MWRBanD3vPWqBecyhmX:b3l529f)* status: all files reviewed, 6 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/MiscUI/BrowserProgressDialog.cs, line 26 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293#-MWQSGTJBiR4hKWGGgp_:-MWR9oZA6cSJUJxs602m:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2b64cac02ee19e0243bdfe98c968f7f04c5da140/src/BloomExe/MiscUI/BrowserProgressDialog.cs#L26)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Let's add a <params> section that explains the return value of doWhat. I think it is something like "function that does the work and sends progress. Should return false to close the dialog, true to leave it open and show <here I'm unclear exactly what buttons gets shown>."
</blockquote></details>

Done.
___
*[src/BloomExe/MiscUI/BrowserProgressDialog.cs, line 46 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293#-MWQRoReAKj0OC0O_04c:-MWR9p6K4SJ0V0gbMQxu:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2b64cac02ee19e0243bdfe98c968f7f04c5da140/src/BloomExe/MiscUI/BrowserProgressDialog.cs#L46)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This would be significantly clearer if it didn't alternate between "problems' and "show-buttons'.  What I think is happening semantically here is.... well I'll make a comment above about declaringthe  api for `doWhat`.
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1350 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293#-MWQT4EEBg8H-HIkdAes:-MWRBU4z-28qvb57UgPS:b-4iwfip) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2b64cac02ee19e0243bdfe98c968f7f04c5da140/src/BloomExe/TeamCollection/TeamCollection.cs#L1350)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I get that this works based on truthiness, but just reading it, one would think that the point is to return the problems. How about `problems.length > 0` ?
</blockquote></details>

problems is a boolean, so no can do. I renamed it waitForUserToCloseDialogOrReportProblems.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1350 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293#-MWQT4EEBg8H-HIkdAes:-MWRiEIZ4BDqneaSGn1X:bckk9sr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2b64cac02ee19e0243bdfe98c968f7f04c5da140/src/BloomExe/TeamCollection/TeamCollection.cs#L1350)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

problems is a boolean, so no can do. I renamed it waitForUserToCloseDialogOrReportProblems.
</blockquote></details>

Oh, then that's an unfortunate name. English, man! How about `hasProblems`

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1350 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293#-MWQT4EEBg8H-HIkdAes:-MWUU5aXEX1w1f9mejNq:b-2x1vxs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2b64cac02ee19e0243bdfe98c968f7f04c5da140/src/BloomExe/TeamCollection/TeamCollection.cs#L1350)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Oh, then that's an unfortunate name. English, man! How about `hasProblems`
</blockquote></details>

hasProblems it it. (Sorry, it started out life as a list of problems, but in the end the only use was to see whether the list was empty. I should have renamed it when I simplified to a boolean.)

**Review by hatton — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4293)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Pull request merged**
