### PR TITLE
Drag to create bubbles

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3410)

### CODE REVIEW

**Review by jsubloom — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3410)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/toolbox/callout/callout.less, line 19 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3410#-LrtpLX2CnK1cQdDgb6k:-LrtpLX2CnK1cQdDgb6l:b-owklgr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0f3940a08644940ad98550fffa6c5a7b78851b77/src/BloomBrowserUI/bookEdit/toolbox/callout/callout.less#L19)):*
> ```Less
>     display: flex;
>     flex-wrap: wrap;
>     .dragInstructions {
> ```

Guess we don't need this anymore
___
*[src/BloomBrowserUI/bookEdit/toolbox/callout/callout.less, line 24 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3410#-Lrtpc_NC_sWQrGAWtkT:-Lrtpc_NC_sWQrGAWtkU:b-hmr9h1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0f3940a08644940ad98550fffa6c5a7b78851b77/src/BloomBrowserUI/bookEdit/toolbox/callout/callout.less#L24)):*
> ```Less
>         cursor: grab;
>     }
>     .speechButton {
> ```

Any thoughts on class vs ID here? We're not expecting multiple of these.
___
*[src/BloomBrowserUI/bookEdit/toolbox/callout/callout.less, line 28 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3410#-Lrtq0HyCyROR1BVJ-I1:-Lrtq0HyCyROR1BVJ-I2:b-7j0p8k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0f3940a08644940ad98550fffa6c5a7b78851b77/src/BloomBrowserUI/bookEdit/toolbox/callout/callout.less#L28)):*
> ```Less
>         width: 40px;
>     }
>     .textBlockButton {
> ```

Maybe we should prefix these names with calloutControl
___
*[src/BloomBrowserUI/bookEdit/toolbox/callout/calloutControls.tsx, line 160 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3410#-LrtqAJ70lgLwuooFowZ:-LrtqAJ8-VvfaAbF1BMN:b-jcu1mc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0f3940a08644940ad98550fffa6c5a7b78851b77/src/BloomBrowserUI/bookEdit/toolbox/callout/calloutControls.tsx#L160)):*
> ```XML
>         // drag these objects anywhere else, so they don't need any of
>         // the common data types.
>         ev.dataTransfer.setData("bloomBubble", style);
> ```

nice idea!
___
*[src/BloomBrowserUI/bookEdit/toolbox/callout/calloutControls.tsx, line 167 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3410#-LrtqRNdE-JtTZLPmOTM:-LrtqRNdE-JtTZLPmOTN:b-8q4o9s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0f3940a08644940ad98550fffa6c5a7b78851b77/src/BloomBrowserUI/bookEdit/toolbox/callout/calloutControls.tsx#L167)):*
> ```
> {" "}
> ```
Is &nbsp; any better?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3410)* status: all files reviewed, 4 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/toolbox/callout/callout.less, line 19 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3410#-LrtpLX2CnK1cQdDgb6k:-LrtvDpf5zmS_1WF2arc:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0f3940a08644940ad98550fffa6c5a7b78851b77/src/BloomBrowserUI/bookEdit/toolbox/callout/callout.less#L19)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Guess we don't need this anymore
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/toolbox/callout/callout.less, line 24 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3410#-Lrtpc_NC_sWQrGAWtkT:-LrtvvV22IBzKgEeQUZr:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0f3940a08644940ad98550fffa6c5a7b78851b77/src/BloomBrowserUI/bookEdit/toolbox/callout/callout.less#L24)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Any thoughts on class vs ID here? We're not expecting multiple of these.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/toolbox/callout/callout.less, line 28 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3410#-Lrtq0HyCyROR1BVJ-I1:-LrtwS7tClxbbjEm4eJ9:b4dt8vv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0f3940a08644940ad98550fffa6c5a7b78851b77/src/BloomBrowserUI/bookEdit/toolbox/callout/callout.less#L28)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Maybe we should prefix these names with calloutControl
</blockquote></details>

Done. (somewhat reluctantly)
___
*[src/BloomBrowserUI/bookEdit/toolbox/callout/calloutControls.tsx, line 167 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3410#-LrtqRNdE-JtTZLPmOTM:-Lrtwjtd6rUMo5R73R4z:buea5xo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0f3940a08644940ad98550fffa6c5a7b78851b77/src/BloomBrowserUI/bookEdit/toolbox/callout/calloutControls.tsx#L167)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> {" "}
> ```
Is &nbsp; any better?
</blockquote></details>

Something has hidden your suggestion. However, simply removing it seems fine, so I did that.

**Review by jsubloom — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3410)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/toolbox/callout/calloutControls.tsx, line 167 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3410#-LrtqRNdE-JtTZLPmOTM:-Lru2XEL8AffbraVvz9P:ba5280s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0f3940a08644940ad98550fffa6c5a7b78851b77/src/BloomBrowserUI/bookEdit/toolbox/callout/calloutControls.tsx#L167)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Something has hidden your suggestion. However, simply removing it seems fine, so I did that.
</blockquote></details>

Oh. I typed ampersand nbsp. Hmm.... does Reviewable allow me to inject HTML????????

**Review by jsubloom — APPROVED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3410)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
