### PR TITLE
Prevent reload with uncommitted rename recreating book (BL-9576)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4272)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Don't merge yet...just found another problem, tests are failing

**Comment by JohnThomson** [comment]
OK, fixed

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4272)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 137 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4272#-MVSvAX89KYXfBuEQBn9:-MVSvAX89KYXfBuEQBnA:bv8cuni) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ec690adc112818bb50691bf12b68d71527bc0c6a/src/BloomExe/TeamCollection/TeamCollection.cs#L137)):*
> ```Smalltalk
> 			// For a third, if we rename this book again, we need to record the
> 			// current repo name as the thing to clean up, not something it once was.
> 			WriteLocalStatus(bookFolderName, status);
> ```

So it is this call which clears status.oldName?
Could we be explicit about that in the comment?
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1004 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4272#-MVSuoPO5t5LRF5sE28H:-MVSuoPP8nLo9N__AW-R:bfqhshx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ec690adc112818bb50691bf12b68d71527bc0c6a/src/BloomExe/TeamCollection/TeamCollection.cs#L1004)):*
> ```
> var statusString = GetBookStatusJsonFromRepo(bookFolderName);
> ```
`var statusJson = GetBookStatusJsonFromRepo(bookFolderName);`
or
`var statusString = GetBookStatusStringFromRepo(bookFolderName);`
?

**Comment by JohnThomson** [comment]
I think I've dealt with both the issues you commented about. (Sorry, Reviewable is not working for me on this PR.)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4272)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4272)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
