### PR TITLE
[5.4] BL-12486 Add more User Info to YouTrack issues

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5989)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5989)* status: all files reviewed, 3 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomExe/Collection/CollectionSettings.cs` line 803 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5989#-N_6Bduu4nzD8f9MTnIa:-N_6BduvC9dynExayxNr:bvemflu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/655e478091c60df59d5109a69bb777b084967bbc/src/BloomExe/Collection/CollectionSettings.cs#L803)):*
> ```Smalltalk
> 				return CollectionSettingsApi.EnterpriseStatus.Community;
> 			return CollectionSettingsApi.EnterpriseStatus.Subscription;
> 		}
> ```

I see you copied this from 5.5. That's fine.
But please move it to where 5.5 has it in the code (or as close as possible) to minimize merge issues.
___
*[`src/BloomExe/ErrorReporter/HtmlErrorReporter.cs` line 3 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5989#-N_6B2gs1IkhoA0guIdo:-N_6B2gs1IkhoA0guIdp:b-qav6ro) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/655e478091c60df59d5109a69bb777b084967bbc/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L3)):*
> ```Smalltalk
> using System;
> using System.Diagnostics;
> using System.Windows.Forms;
> ```

Don't worry about changing it, but for the future, this type of cleanup is not desirable in an older branch (like Version5.4 at this point). The reason is it can cause unnecessary merge conflicts.
___
*[`src/BloomExe/web/controllers/ProblemReportApi.cs` line 891 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5989#-N_6BReH9s0u74MpyimZ:-N_6BReH9s0u74Mpyim_:b-59fne9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/655e478091c60df59d5109a69bb777b084967bbc/src/BloomExe/web/controllers/ProblemReportApi.cs#L891)):*
> ```Smalltalk
> 			}
> 			var enterpriseStatus = settings.GetEnterpriseStatus().ToString();
> 			var branding = settings.BrandingProjectKey;			bldr.AppendLine("Collection name: " + settings.CollectionName);
> ```

Any reason to separate these lines from the ones which use them below?
(And something strange happened here. The bldr.AppendLine... is at the end of your new stuff.
___
*[`src/BloomExe/web/controllers/ProblemReportApi.cs` line 901 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5989#-N_6BJf63SVS9qdvOiVD:-N_6BJf63SVS9qdvOiVE:b-iy2acd) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/655e478091c60df59d5109a69bb777b084967bbc/src/BloomExe/web/controllers/ProblemReportApi.cs#L901)):*
> ```Smalltalk
> 			bldr.AppendLine("Enterprise status: " + enterpriseStatus);
> 			bldr.AppendLine("Branding: " + (string.IsNullOrEmpty(branding) ? "None found" : branding));
> 			bldr.AppendLine("User timezone: " + TimeZone.CurrentTimeZone.StandardName);
> ```

Just noting here that JH asked for a change to GMT +- rather than the name.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5989)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Collection/CollectionSettings.cs` line 803 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5989#-N_6Bduu4nzD8f9MTnIa:-N_9prbn6xcW3CS7OWrL:bwfa0p2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/655e478091c60df59d5109a69bb777b084967bbc/src/BloomExe/Collection/CollectionSettings.cs#L803)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I see you copied this from 5.5. That's fine.
But please move it to where 5.5 has it in the code (or as close as possible) to minimize merge issues.
</blockquote></details>

Done. At end of file. There is another `5.5` method that slots in above this one.
___
*[`src/BloomExe/web/controllers/ProblemReportApi.cs` line 891 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5989#-N_6BReH9s0u74MpyimZ:-N_9nq-T7PDb8-P0l_RH:bozjxw0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/655e478091c60df59d5109a69bb777b084967bbc/src/BloomExe/web/controllers/ProblemReportApi.cs#L891)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Any reason to separate these lines from the ones which use them below?
(And something strange happened here. The bldr.AppendLine... is at the end of your new stuff.
</blockquote></details>

Nope and oops!
___
*[`src/BloomExe/web/controllers/ProblemReportApi.cs` line 901 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5989#-N_6BJf63SVS9qdvOiVD:-N_9ntNe0A8r3xmQdoqz:b-upaiz9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/655e478091c60df59d5109a69bb777b084967bbc/src/BloomExe/web/controllers/ProblemReportApi.cs#L901)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Just noting here that JH asked for a change to GMT +- rather than the name.
</blockquote></details>

Done. I put UTC+offset and then the tz name in parentheses. UTC+offset is enough to know the hour difference, but the name of the tz differs depending on the country sometimes and might be handy to know.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5989)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5989)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
