### PR TITLE
Firebase login (BL-8627)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3875)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3875)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/publish/LibraryPublish/LoginDialog.tsx, line 62 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3875#-MEP87M_CZUchYXGC7ZU:-MEP87M_CZUchYXGC7ZV:b-a4540j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2e320159b82bf21cba1a556284d628f8cec79033/src/BloomBrowserUI/publish/LibraryPublish/LoginDialog.tsx#L62)):*
> ```
> Please check your email and click on the link there, then log in again.
> ```
Do we need to internationalize this string?
___
*[src/BloomBrowserUI/publish/LibraryPublish/LoginDialog.tsx, line 117 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3875#-MEP82n04uAn8WIqiH5-:-MEP82n04uAn8WIqiH50:b-l9j23q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2e320159b82bf21cba1a556284d628f8cec79033/src/BloomBrowserUI/publish/LibraryPublish/LoginDialog.tsx#L117)):*
> ```
> Sign In / Sign Up
> ```
Do we need to internationalize this string?
___
*[src/BloomBrowserUI/publish/LibraryPublish/LoginDialog.tsx, line 222 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3875#-MEP8RGv5eMNdkj1LlZL:-MEP8RGv5eMNdkj1LlZM:b-jw5cdl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2e320159b82bf21cba1a556284d628f8cec79033/src/BloomBrowserUI/publish/LibraryPublish/LoginDialog.tsx#L222)):*
> ```
> Oops, something went wrong when trying to log you into our database.
> ```
Do we need to internationalize this string?
___
*[src/BloomExe/WebLibraryIntegration/BloomParseClient.cs, line 34 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3875#-MEP59joC3E1_vbRxC5Q:-MEP59jp9Bva6FI617jz:b-xfd1e1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2e320159b82bf21cba1a556284d628f8cec79033/src/BloomExe/WebLibraryIntegration/BloomParseClient.cs#L34)):*
> ```Smalltalk
> 			_userId = userId;
> 			_sessionToken = sessionToken;
> 		}
> ```

I think this is an alternative path to `Login()`.  In other words, the client will use this or `Login()`?
Is it possible to have one or more unit tests for this path? 
It looks like the existing `Login()` method is now only used by unit tests and command line utilities. Are we going to wish we converted the command line utilities at this time? Or it is sufficient to have two different code paths?
___
*[src/BloomExe/WebLibraryIntegration/FirebaseLoginDialog.cs, line 54 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3875#-MEP72J-7aN6BbARq4lf:-MEP72J-7aN6BbARq4lg:b-u0i9e3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2e320159b82bf21cba1a556284d628f8cec79033/src/BloomExe/WebLibraryIntegration/FirebaseLoginDialog.cs#L54)):*
> ```Smalltalk
> 		{
> 			var firebaseDialogRootPath = BloomFileLocator.GetBrowserFile(false, "publish", "LibraryPublish", "loginLoader.html");
> 			var url = firebaseDialogRootPath.ToLocalhost() + "?bucket=" + BookTransfer.UploadBucketNameForCurrentEnvironment + "&mode=getToken";
> ```

Seems worth extracting the previous two lines into a method which takes `additionalParams` or similar.
There are 3 usages.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3875)* status: 15 of 23 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/publish/LibraryPublish/LoginDialog.tsx, line 62 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3875#-MEP87M_CZUchYXGC7ZU:-MESsdbi2Qg3DmTWcCUM:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2e320159b82bf21cba1a556284d628f8cec79033/src/BloomBrowserUI/publish/LibraryPublish/LoginDialog.tsx#L62)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Please check your email and click on the link there, then log in again.
> ```
Do we need to internationalize this string?
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/publish/LibraryPublish/LoginDialog.tsx, line 117 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3875#-MEP82n04uAn8WIqiH5-:-MEStwtE2arIegdh8OFW:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2e320159b82bf21cba1a556284d628f8cec79033/src/BloomBrowserUI/publish/LibraryPublish/LoginDialog.tsx#L117)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Sign In / Sign Up
> ```
Do we need to internationalize this string?
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/publish/LibraryPublish/LoginDialog.tsx, line 222 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3875#-MEP8RGv5eMNdkj1LlZL:-MET9tfg2xOdxkoNS6E2:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2e320159b82bf21cba1a556284d628f8cec79033/src/BloomBrowserUI/publish/LibraryPublish/LoginDialog.tsx#L222)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Oops, something went wrong when trying to log you into our database.
> ```
Do we need to internationalize this string?
</blockquote></details>

Done.
___
*[src/BloomExe/WebLibraryIntegration/BloomParseClient.cs, line 34 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3875#-MEP59joC3E1_vbRxC5Q:-MEU7e-43PqeIiwD-i8_:b79464b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2e320159b82bf21cba1a556284d628f8cec79033/src/BloomExe/WebLibraryIntegration/BloomParseClient.cs#L34)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this is an alternative path to `Login()`.  In other words, the client will use this or `Login()`?
Is it possible to have one or more unit tests for this path? 
It looks like the existing `Login()` method is now only used by unit tests and command line utilities. Are we going to wish we converted the command line utilities at this time? Or it is sufficient to have two different code paths?
</blockquote></details>

I did quite a bit of work related to this, but could not get the new style of login to work in command line mode.
___
*[src/BloomExe/WebLibraryIntegration/FirebaseLoginDialog.cs, line 54 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3875#-MEP72J-7aN6BbARq4lf:-META_wK2hN5KZEkgFJN:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2e320159b82bf21cba1a556284d628f8cec79033/src/BloomExe/WebLibraryIntegration/FirebaseLoginDialog.cs#L54)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems worth extracting the previous two lines into a method which takes `additionalParams` or similar.
There are 3 usages.
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3875)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomExe/MiscUI/BrowserDialog.cs, line 13 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3875#-MEUBumz6yQCe6PGCefC:-MEUBumz6yQCe6PGCefD:bcpjsci) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a86a3f69aee8fe01dd2217d071b9ef57cee8d054/src/BloomExe/MiscUI/BrowserDialog.cs#L13)):*
> ```
> This applies only to cases where the dialog is shown hidden to execute some Javascript.
> ```
How about `This applies only to cases where the dialog is created (but hidden) to execute some Javascript.`?
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 626 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3875#-MEUDD0QBbX5NBZhr2P2:-MEUDD0R01nerS6sCi4s:b-kp4m2v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2e5ab58e1e4e555101732194b8fb24c7da2701e4/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L626)):*
> ```
> Settings.Default.WebUserId, Settings.Default.WebPassword
> ```
If we no longer read or write these, should we remove them from settings?

**Review by JohnThomson — COMMENTED** [review]
Lots of changes, not only to fix the problems noted here, but others noted as UI review in the issue, and a few that I discovered myself while working on the various suggestions.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3875#-:-MEZ0UEZ0upZAJ963FvU:b-gqfgqy)* status: 14 of 26 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/MiscUI/BrowserDialog.cs, line 13 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3875#-MEUBumz6yQCe6PGCefC:-MEZ07TRA2C1DYTmZHAH:b-91t50w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a86a3f69aee8fe01dd2217d071b9ef57cee8d054/src/BloomExe/MiscUI/BrowserDialog.cs#L13)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> This applies only to cases where the dialog is shown hidden to execute some Javascript.
> ```
How about `This applies only to cases where the dialog is created (but hidden) to execute some Javascript.`?
</blockquote></details>

I used "created but not shown"
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 626 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3875#-MEUDD0QBbX5NBZhr2P2:-MEZ0Cmy957GaTZfaSYJ:bbn9tfe) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2e5ab58e1e4e555101732194b8fb24c7da2701e4/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L626)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Settings.Default.WebUserId, Settings.Default.WebPassword
> ```
If we no longer read or write these, should we remove them from settings?
</blockquote></details>

Turns out we DO use the WebUserId still, though perhaps it no longer needs to be a setting: it's where we find out who is logged in to show in the label above the logout button.
I removed the password.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 13 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3875)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
