### PR TITLE
Record video full screen when appropriate (BL-12729)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 183 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138#-NgQjN1X3PXoy6-QE0K3:-NgQjN1X3PXoy6-QE0K4:b-nus9kz) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a35fdd6045a191c3b78459c8427655a101831f35/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L183)):*
> ```Smalltalk
> 				{
> 					adder.Add(LocalizationManager.GetString("PublishTab.RecordVideo.StopRecording", "Stop Recording"),
> 						(s1, e1) => { this.Close(); });	// OnClosed() handles cleanup.
> ```

@hatton 
Is this sufficient UX?
The recording window will fill the screen with only a right-click menu available to stop it.

(@StephenMcConnel correct me if I'm wrong.)
___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 1463 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138#-NgQjjgLAgzQutQ6MLWD:-NgQjjgLAgzQutQ6MLWE:b-ou0mte) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a35fdd6045a191c3b78459c8427655a101831f35/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L1463)):*
> ```Smalltalk
> 					// crop the video to the desired resolution. But that's a lot of work,
> 					// and it's not clear that it would be worth it.
> 					actualResolution = s_maxResolution;
> ```

I think we decided that in this case, we want it to do the largest available pre-defined size, not the max total size allowed by the screen.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 183 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138#-NgQjN1X3PXoy6-QE0K3:-NgQlf951M_JjQVQwyq3:b-q4b2v8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a35fdd6045a191c3b78459c8427655a101831f35/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L183)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

@hatton 
Is this sufficient UX?
The recording window will fill the screen with only a right-click menu available to stop it.

(@StephenMcConnel correct me if I'm wrong.)
</blockquote></details>

 I suppose "ESC" would be hard to add?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 183 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138#-NgQjN1X3PXoy6-QE0K3:-NgVWgRvDd6GJeYA9V6y:b-vq13j3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a35fdd6045a191c3b78459c8427655a101831f35/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L183)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I suppose "ESC" would be hard to add?
</blockquote></details>

See comments in card.
We decided this could be sufficient for round 1 with some other forthcoming changes.

(but there are a couple other things which need to be addressed in this PR anyway, so it might not be worth merging in two stages)
___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 1448 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138#-NgVWwocB5dFap4zBOjF:-NgVWwocB5dFap4zBOjG:boce1cr) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a35fdd6045a191c3b78459c8427655a101831f35/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L1448)):*
> ```Smalltalk
> 			{
> 				if (s_screenResolution.Width == desiredResolution.Width &&
> 					s_screenResolution.Height == desiredResolution.Height)
> ```

I think we need to improve on this algorithm to take into account that it may only be one dimension which can cause us to need to go into borderless mode.

Take, for example, my setup:
1920x1200

If I want to record a video which is 1920x1080, I should be able to in borderless mode, right?

The current code will say I can't because the widths aren't equal.
___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 1463 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138#-NgQjjgLAgzQutQ6MLWD:-NgVXdQ3DBneZclBoSN9:bxpv9br) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a35fdd6045a191c3b78459c8427655a101831f35/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L1463)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think we decided that in this case, we want it to do the largest available pre-defined size, not the max total size allowed by the screen.
</blockquote></details>

See above where we use GetBestResolutionForFormat

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 183 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138#-NgQjN1X3PXoy6-QE0K3:-NgVpUE36iGPZEbXNQvK:b-dai0fz) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a35fdd6045a191c3b78459c8427655a101831f35/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L183)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

See comments in card.
We decided this could be sufficient for round 1 with some other forthcoming changes.

(but there are a couple other things which need to be addressed in this PR anyway, so it might not be worth merging in two stages)
</blockquote></details>

I tried for a couple of hours to get the C# code to intercept keystrokes without any success before I even thought of adding a menu command.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 1463 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138#-NgQjjgLAgzQutQ6MLWD:-NgVpfSE4oMqB1zOrJur:b-l9xw4c) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a35fdd6045a191c3b78459c8427655a101831f35/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L1463)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

See above where we use GetBestResolutionForFormat
</blockquote></details>

This is the pre-existing code.  I didn't change anything in this branch of the if statement.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 1463 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138#-NgQjjgLAgzQutQ6MLWD:-NgVsNPf8FNDbgOFwrhb:b-wyx0it) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a35fdd6045a191c3b78459c8427655a101831f35/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L1463)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

This is the pre-existing code.  I didn't change anything in this branch of the if statement.
</blockquote></details>

Sorry; I guess one of us is missing something.

As far as I can tell, this is new:
`actualResolution = s_maxResolution;`

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 1463 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138#-NgQjjgLAgzQutQ6MLWD:-NgW4YyG4XPD5KwftDR6:belulqx) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a35fdd6045a191c3b78459c8427655a101831f35/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L1463)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; I guess one of us is missing something.

As far as I can tell, this is new:
`actualResolution = s_maxResolution;`
</blockquote></details>

I don't remember writing the comment, which is why I thought this was old code.  But apparently I wrote both this line (which is obviously wrong) and the comment.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 183 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138#-NgQjN1X3PXoy6-QE0K3:-NgW9r1gDl3PzC7xr9qe:bee79m8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a35fdd6045a191c3b78459c8427655a101831f35/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L183)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I tried for a couple of hours to get the C# code to intercept keystrokes without any success before I even thought of adding a menu command.
</blockquote></details>

I don't have time today, but the only change I can see working is to override the normal context menu hookup to not display a menu but to signal back to the window code that the context menu has been requested, so it can know to close from the right mouse click.
I don't think WebView2 gives any way to pass mouse click or keystroke events back to the C# code except for the context menu requested event.  At least I haven't found any looking the documentation so far.
___
*[`src/BloomExe/Publish/Video/RecordVideoWindow.cs` line 1448 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138#-NgVWwocB5dFap4zBOjF:-NgW6TEj4as0d-5Jfgiw:bde0flq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a35fdd6045a191c3b78459c8427655a101831f35/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L1448)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think we need to improve on this algorithm to take into account that it may only be one dimension which can cause us to need to go into borderless mode.

Take, for example, my setup:
1920x1200

If I want to record a video which is 1920x1080, I should be able to in borderless mode, right?

The current code will say I can't because the widths aren't equal.
</blockquote></details>

changed to >= instead of ==

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
I've changed the mouse right-click to close the window instead of bringing up the context menu.  This is the only mouse click that reaches the WinForms control in any fashion.  None of the keyboard events get through to the WinForms control.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138#-:-NgtB0Xk9SbJqaogp4Hx:b5j7t79)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @hatton)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
