### PR TITLE
Align comic bubbles middle (BL-8247)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042)* status: all files reviewed, 9 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 894 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042#-MKLh4Rz7HcZ3iL6HDDb:-MKLh4Rz7HcZ3iL6HDDc:b-i1rfi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/41935f6f3a623e1ecd2a442b6181093c650c2bd6/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L894)):*
> ```XML
>     });
> 
>     // Up and down arrow navigation don't work in editables with paragraphs that are flexboxes.
> ```

Do we have a FF bug to link to here?
___
*[src/BloomBrowserUI/bookEdit/js/lineNavigator.ts, line 9 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042#-MKMGcX891Ospb3sJX0G:-MKMGcX891Ospb3sJX0H:bmbsppe) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/41935f6f3a623e1ecd2a442b6181093c650c2bd6/src/BloomBrowserUI/bookEdit/js/lineNavigator.ts#L9)):*
> ```XML
> }
> 
> export class LineNavigator {
> ```

I'm not excited about the name. It would be better if we can come up with something specific to the cursor/insertion point moving. And maybe even somehow communicate this is to workaround a bug.

ArrowUpDownManager
ArrowKeyManager
ArrowKeyWorkaroundManager
ArrowKeyWorkaroundHandler
ArrowKeyOverride
ArrowKeyFixOverride
FlexboxArrowKeyFixer

I guess we don't actually use the class name anywhere outside the import statement, so I guess it actually doesn't matter much.

Also, let's add a class summary.
___
*[src/BloomBrowserUI/bookEdit/js/lineNavigator.ts, line 120 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042#-MKMIadpE5uBYGvEMpVO:-MKMIadpE5uBYGvEMpVP:byofz50) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/41935f6f3a623e1ecd2a442b6181093c650c2bd6/src/BloomBrowserUI/bookEdit/js/lineNavigator.ts#L120)):*
> ```XML
>         this.setSelectionTo(sel, newAnchor.node, newAnchor.offset);
> 
>         // Hmm, for some reason, after modifying the selection, now the default seems to work
> ```

Just for giggles, I don't suppose you tried just setting the selection to where it started and letting the default event happen? Or setting it elsewhere, then setting it back to the original, then letting the original event happen?
___
*[src/BloomBrowserUI/bookEdit/js/lineNavigator.ts, line 126 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042#-MKMGVqcECq8PCBjDI5m:-MKMGVqcECq8PCBjDI5n:bee9kte) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/41935f6f3a623e1ecd2a442b6181093c650c2bd6/src/BloomBrowserUI/bookEdit/js/lineNavigator.ts#L126)):*
> ```XML
>     }
> 
>     private setSelectionTo(sel: Selection, node: Node, offset: number): void {
> ```

This could be simplified slightly by passing an Anchor instead of Node and number.
___
*[src/BloomBrowserUI/bookEdit/js/lineNavigator.ts, line 156 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042#-MKMJD8kCxcxJmnDSYd_:-MKMJD8kCxcxJmnDSYda:b5qskib) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/41935f6f3a623e1ecd2a442b6181093c650c2bd6/src/BloomBrowserUI/bookEdit/js/lineNavigator.ts#L156)):*
> ```
> | {
> ```
This looks odd. Why does it start with a pipe? Is that just a start on a new line syntax thing?
___
*[src/BloomBrowserUI/bookEdit/js/lineNavigator.ts, line 186 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042#-MKMJlUE8F5Ms3MBM7gX:-MKMJlUE8F5Ms3MBM7gY:b7lo574) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/41935f6f3a623e1ecd2a442b6181093c650c2bd6/src/BloomBrowserUI/bookEdit/js/lineNavigator.ts#L186)):*
> ```XML
>         if (oldIndexFromStart === null) {
>             // this.log("ABORT - oldIndexFromStart is null.");
>             return;
> ```

Should this and below be `return undefined`? Why doesn't typescript complain about this?
___
*[src/BloomBrowserUI/bookEdit/js/lineNavigator.ts, line 437 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042#-MKMNEPL0MVOsnEkfY4m:-MKMNEPL0MVOsnEkfY4n:b-xtzaeq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/41935f6f3a623e1ecd2a442b6181093c650c2bd6/src/BloomBrowserUI/bookEdit/js/lineNavigator.ts#L437)):*
> ```
> : Anchor
> ```
since getAnchorAtIndex can return null, why isn't typescript enforcing that here?
___
*[src/BloomBrowserUI/bookEdit/js/lineNavigator.ts, line 497 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042#-MKMS4Ts6PuLqSfDpe29:-MKMS4Ts6PuLqSfDpe2A:b-s0cxdh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/41935f6f3a623e1ecd2a442b6181093c650c2bd6/src/BloomBrowserUI/bookEdit/js/lineNavigator.ts#L497)):*
> ```XML
>             }
>         } finally {
>             // ENHANCE: Maybe the other similar places should get a finally.
> ```

The only other relevant place I see is in printCharPositions which is just for debugging as I understand.
If I'm right and that is the only relevant place, let's remove this comment. Can implement in printCharPositions or not...
___
*[src/BloomBrowserUI/bookLayout/bubble.less, line 288 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042#-MKLgkQA7IsiPo3c9g-v:-MKLgkQA7IsiPo3c9g-w:bbne5r9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c80907625b9ad694733dcd36f598ef1bcdd37d15/src/BloomBrowserUI/bookLayout/bubble.less#L288)):*
> ```
> color: blue;
> ```
I don't understand what this is for.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 894 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042#-MKLh4Rz7HcZ3iL6HDDb:-MKeKECf3tj4rE_4DIEP:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/41935f6f3a623e1ecd2a442b6181093c650c2bd6/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L894)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Do we have a FF bug to link to here?
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookLayout/bubble.less, line 288 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042#-MKLgkQA7IsiPo3c9g-v:-MKeQg_N4dlP--bUFNb7:b-5rwapp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c80907625b9ad694733dcd36f598ef1bcdd37d15/src/BloomBrowserUI/bookLayout/bubble.less#L288)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> color: blue;
> ```
I don't understand what this is for.
</blockquote></details>

Oops. Just temporary code. I switch the colors sometimes to as an indication to know that my latest changes were picked up.
___
*[src/BloomBrowserUI/bookEdit/js/lineNavigator.ts, line 9 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042#-MKMGcX891Ospb3sJX0G:-MKelVFT5c3hPLjewx8x:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/41935f6f3a623e1ecd2a442b6181093c650c2bd6/src/BloomBrowserUI/bookEdit/js/lineNavigator.ts#L9)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not excited about the name. It would be better if we can come up with something specific to the cursor/insertion point moving. And maybe even somehow communicate this is to workaround a bug.

ArrowUpDownManager
ArrowKeyManager
ArrowKeyWorkaroundManager
ArrowKeyWorkaroundHandler
ArrowKeyOverride
ArrowKeyFixOverride
FlexboxArrowKeyFixer

I guess we don't actually use the class name anywhere outside the import statement, so I guess it actually doesn't matter much.

Also, let's add a class summary.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/js/lineNavigator.ts, line 120 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042#-MKMIadpE5uBYGvEMpVO:-MKeKI0t-IrpyxoJ_mE-:b-53mtgw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/41935f6f3a623e1ecd2a442b6181093c650c2bd6/src/BloomBrowserUI/bookEdit/js/lineNavigator.ts#L120)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Just for giggles, I don't suppose you tried just setting the selection to where it started and letting the default event happen? Or setting it elsewhere, then setting it back to the original, then letting the original event happen?
</blockquote></details>

I actually did try several variations of that, and unfortunately it didn't work :(
___
*[src/BloomBrowserUI/bookEdit/js/lineNavigator.ts, line 156 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042#-MKMJD8kCxcxJmnDSYd_:-MKeKXdFBfOUIrd1_PY6:b-4w6gt9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/41935f6f3a623e1ecd2a442b6181093c650c2bd6/src/BloomBrowserUI/bookEdit/js/lineNavigator.ts#L156)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> | {
> ```
This looks odd. Why does it start with a pipe? Is that just a start on a new line syntax thing?
</blockquote></details>

I had tried to get rid of it manually before, but Prettier insisted upon that syntax. Yes, I do think it's related to the first type starting on a new line.
___
*[src/BloomBrowserUI/bookEdit/js/lineNavigator.ts, line 186 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042#-MKMJlUE8F5Ms3MBM7gX:-MKeKoiG3spoO_3LvrIy:b9eejyf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/41935f6f3a623e1ecd2a442b6181093c650c2bd6/src/BloomBrowserUI/bookEdit/js/lineNavigator.ts#L186)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should this and below be `return undefined`? Why doesn't typescript complain about this?
</blockquote></details>

Hmm, it should be an explicit return undefined indeed. As for why it doesn't complain, I suspect it's related to how if you try to access the return value of a function that returns void, you get undefined.
Fixed.
___
*[src/BloomBrowserUI/bookEdit/js/lineNavigator.ts, line 437 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042#-MKMNEPL0MVOsnEkfY4m:-MKeLRpg54QxYjTKDcyW:b-u161pj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/41935f6f3a623e1ecd2a442b6181093c650c2bd6/src/BloomBrowserUI/bookEdit/js/lineNavigator.ts#L437)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> : Anchor
> ```
since getAnchorAtIndex can return null, why isn't typescript enforcing that here?
</blockquote></details>

On line 490, I added the "!" to say that getAnchorAtIndex should return a non-null value.
___
*[src/BloomBrowserUI/bookEdit/js/lineNavigator.ts, line 497 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042#-MKMS4Ts6PuLqSfDpe29:-MKeM1hmCc-H2WBo76-N:b-u783da) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/41935f6f3a623e1ecd2a442b6181093c650c2bd6/src/BloomBrowserUI/bookEdit/js/lineNavigator.ts#L497)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The only other relevant place I see is in printCharPositions which is just for debugging as I understand.
If I'm right and that is the only relevant place, let's remove this comment. Can implement in printCharPositions or not...
</blockquote></details>

Oh, i fixed one of these already. Thanks.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/js/lineNavigator.ts, line 126 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042#-MKMGVqcECq8PCBjDI5m:-MKeo3fk2_GzonyGA0n1:bbw2yrg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/41935f6f3a623e1ecd2a442b6181093c650c2bd6/src/BloomBrowserUI/bookEdit/js/lineNavigator.ts#L126)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This could be simplified slightly by passing an Anchor instead of Node and number.
</blockquote></details>

Sort of, but it'd actually increase the number of lines due to Prettier.
Also, the number of chars would increase with or without prettier.

I'll mark Won't Fix for now, but open to fixing it if pushed back on.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/js/lineNavigator.ts, line 437 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042#-MKMNEPL0MVOsnEkfY4m:-MKerJWWDi3lIFLvIQlF:bko60ap) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/41935f6f3a623e1ecd2a442b6181093c650c2bd6/src/BloomBrowserUI/bookEdit/js/lineNavigator.ts#L437)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

On line 490, I added the "!" to say that getAnchorAtIndex should return a non-null value.
</blockquote></details>

I got interrupted halfway and forgot to finish this comment. Although getAnchorAtIndex can sometimes return null, I think that given the inputs passed to it here, it is not normal or expected for it to return null. If it did return null, it would be exceptional, unexpected, and an error. So I felt ok with casting it to non-null and receiving an exception if it were actually null.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
