### PR TITLE
[5.5] Send Analytics through blorg BL-12617 

### PR DESCRIPTION
**Pull request by nabalone**
https://github.com/BloomBooks/BloomDesktop/pull/6061 to 5.5

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6080)

### CODE REVIEW

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6080)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[`src/BloomExe/packages.config` line 99 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6080#-NdBwt5b2hv7H2RrQGoY:-NdBwt5b2hv7H2RrQGoZ:bnowfbv) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9c12313d8ade650c7aa7d46c6d68fd200764e1f5/src/BloomExe/packages.config#L99)):*
> ```XML
>   <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="net461" />
>   <package id="System.Security.AccessControl" version="6.0.0" targetFramework="net472" />
>   <package id="System.Security.Cryptography.Algorithms" version="4.3.0" targetFramework="net472" />
> ```

Why did it do this? should we keep it?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6080)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)

___
*[`src/BloomExe/packages.config` line 99 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6080#-NdBwt5b2hv7H2RrQGoY:-NdCFwLs4TyshdDAiI8X:bnz51ue) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9c12313d8ade650c7aa7d46c6d68fd200764e1f5/src/BloomExe/packages.config#L99)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Why did it do this? should we keep it?
</blockquote></details>

I think something in libpalaso keeps wanting to add it.
Let's remove them.

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6080)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @andrew-polk)

___
*[`src/BloomExe/packages.config` line 99 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6080#-NdBwt5b2hv7H2RrQGoY:-NdD-vS7AH-jgizH28NX:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9c12313d8ade650c7aa7d46c6d68fd200764e1f5/src/BloomExe/packages.config#L99)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think something in libpalaso keeps wanting to add it.
Let's remove them.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6080)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nabalone)

**Pull request merged**
