### PR TITLE
Steps towards getting editingView to work with WebView2

### PR DESCRIPTION
**Pull request by JohnThomson**
The immediately useful part is that right-click commands are working in WebView2

- - -
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5349)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5349)* status: all files reviewed, 7 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/BloomExe.csproj` line 195 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5349#-N9n-MLNCTqU37R8LcWm:-N9n-MLNCTqU37R8LcWn:b7as96x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8e0d57edf0ce06a677ef1f7d15d836719fc1d62d/src/BloomExe/BloomExe.csproj#L195)):*
> ```XML
>     </Reference>
>     <Reference Include="Microsoft.VisualBasic" />
>     <Reference Include="Microsoft.Web.WebView2.Core, Version=1.0.1054.31, Culture=neutral, PublicKeyToken=2a8ab48044d2601e, processorArchitecture=MSIL" Condition="'$(OS)'=='Windows_NT'">
> ```

We need to keep these Windows conditions.
___
*[`src/BloomExe/BloomExe.csproj` line 1649 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5349#-N9n-TIvCdadTPVZTZv4:-N9n-TIvCdadTPVZTZv5:b8myh11) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5f7b6c9eb221527f208d74884557dd7620c9a54d/src/BloomExe/BloomExe.csproj#L1649)):*
> ```XML
>     <Error Condition="!Exists('..\..\packages\SIL.Windows.Forms.Keyboarding.10.0.0-beta0081\build\SIL.Windows.Forms.Keyboarding.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\SIL.Windows.Forms.Keyboarding.10.0.0-beta0081\build\SIL.Windows.Forms.Keyboarding.targets'))" />
>     <Error Condition="!Exists('..\..\packages\SIL.Windows.Forms.10.0.0-beta0081\build\SIL.Windows.Forms.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\SIL.Windows.Forms.10.0.0-beta0081\build\SIL.Windows.Forms.targets'))" />
>     <Error Condition="!Exists('..\..\packages\Microsoft.Web.WebView2.1.0.1293.44\build\Microsoft.Web.WebView2.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\Microsoft.Web.WebView2.1.0.1293.44\build\Microsoft.Web.WebView2.targets'))" />
> ```

This is a duplicate of the modified one above except the one above correctly has the Windows-only condition.
___
*[`src/BloomExe/GeckoFxBrowser.cs` line 451 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5349#-N9n23qeBvZ9paA_CBw4:-N9n23qeBvZ9paA_CBw5:b-mslpje) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5f7b6c9eb221527f208d74884557dd7620c9a54d/src/BloomExe/GeckoFxBrowser.cs#L451)):*
> ```Smalltalk
> 			if (_browser.Document.ReadyState != "complete")
> 				return;
> 			RaiseDocumentCompleted(sender, e);
> ```

Should we unsubscribe here?
___
*[`src/BloomExe/GeckoFxBrowser.cs` line 576 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5349#-N9n3_wX3Dmd2Jc_fO5G:-N9n3_wX3Dmd2Jc_fO5H:b-tmcd67) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5f7b6c9eb221527f208d74884557dd7620c9a54d/src/BloomExe/GeckoFxBrowser.cs#L576)):*
> ```Smalltalk
> 		}
> 
> 		// To allow Typescript code to implement right-click, we'll do our special developer menu
> ```

Did this comment get orphaned?
___
*[`src/BloomExe/packages.config` line 16 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5349#-N9n-gTn5LJRxRux9cow:-N9n-gTo7xQnNtL0DNmI:bpwyppk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8e0d57edf0ce06a677ef1f7d15d836719fc1d62d/src/BloomExe/packages.config#L16)):*
> ```XML
>        make sure you delete the Windows-specific packages specified above from any
> 	   lines you copied to Linux/packages.config
>    -->
> ```

Need to keep all the comments in this file.
___
*[`src/BloomExe/WebView2Browser.cs` line 18 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5349#-N9n-lpF41DaEyZlRto4:-N9n-lpG6hPu1KwCT2C9:bb7phvt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5f7b6c9eb221527f208d74884557dd7620c9a54d/src/BloomExe/WebView2Browser.cs#L18)):*
> ```Smalltalk
> 
> 			// I don't think anything we're doing here will take long enough for us to need to await it.
> 			InitWevView();
> ```

typo



_Code quote:_
```Smalltalk
InitWevView
```
___
*[`src/BloomExe/WebView2Browser.cs` line 61 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5349#-N9n2daVECCPJVUxpouX:-N9n2daVECCPJVUxpouY:b6cqiz4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5f7b6c9eb221527f208d74884557dd7620c9a54d/src/BloomExe/WebView2Browser.cs#L61)):*
> ```Smalltalk
> 			// based on https://stackoverflow.com/questions/63404822/how-to-disable-cors-in-wpf-webview2
> 			// this should disable CORS, but it doesn't seem to work. Keeping in case I need to try further.
> 			var op = new CoreWebView2EnvironmentOptions("--allow-insecure-localhost --disable-web-security");
> ```

Is this still needed and/or is the comment still accurate?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5349)* status: 10 of 15 files reviewed, 6 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/BloomExe.csproj` line 195 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5349#-N9n-MLNCTqU37R8LcWm:-N9qpClb4RzQWuPKqX-i:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8e0d57edf0ce06a677ef1f7d15d836719fc1d62d/src/BloomExe/BloomExe.csproj#L195)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We need to keep these Windows conditions.
</blockquote></details>

Done.



_Code quote:_
```XML
Condition="'$(OS)'=='Windows_NT'"
```
___
*[`src/BloomExe/BloomExe.csproj` line 1649 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5349#-N9n-TIvCdadTPVZTZv4:-N9qnB-H-eTXQunPoSn6:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5f7b6c9eb221527f208d74884557dd7620c9a54d/src/BloomExe/BloomExe.csproj#L1649)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This is a duplicate of the modified one above except the one above correctly has the Windows-only condition.
</blockquote></details>

Done.
___
*[`src/BloomExe/GeckoFxBrowser.cs` line 451 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5349#-N9n23qeBvZ9paA_CBw4:-N9qnb53D_q8g10fC44k:bv8d82r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5f7b6c9eb221527f208d74884557dd7620c9a54d/src/BloomExe/GeckoFxBrowser.cs#L451)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should we unsubscribe here?
</blockquote></details>

I don't think so. The point here is that the Webview2 doesn't have anything like ReadyStateChanged, so we hope its document completed event is more reliable than Gecko's. Raising DocumentCompleted when ReadyStateChanges to complete is a sort of bug-fix for GeckoFx, but with this change, clients don't have to be aware of it. Since the client is now only subscribing to the wrapper class DocumentCompleted, that subscription is the only one we need to remove.
___
*[`src/BloomExe/GeckoFxBrowser.cs` line 576 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5349#-N9n3_wX3Dmd2Jc_fO5G:-N9qpitZ6teYJfwDgsc5:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5f7b6c9eb221527f208d74884557dd7620c9a54d/src/BloomExe/GeckoFxBrowser.cs#L576)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Did this comment get orphaned?
</blockquote></details>

Done.
___
*[`src/BloomExe/packages.config` line 16 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5349#-N9n-gTn5LJRxRux9cow:-N9qq1poBU0s7e0y6L8v:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8e0d57edf0ce06a677ef1f7d15d836719fc1d62d/src/BloomExe/packages.config#L16)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Need to keep all the comments in this file.
</blockquote></details>

Done.
___
*[`src/BloomExe/WebView2Browser.cs` line 61 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5349#-N9n2daVECCPJVUxpouX:-N9qqjsqATSPgufqHG-d:b-hk378b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5f7b6c9eb221527f208d74884557dd7620c9a54d/src/BloomExe/WebView2Browser.cs#L61)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is this still needed and/or is the comment still accurate?
</blockquote></details>

I commented it out and added some more notes about why

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5349)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/packages.config` line 16 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5349#-N9n-gTn5LJRxRux9cow:-N9r1SzZ5ji-NK70OPwm:bvwu4nr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8e0d57edf0ce06a677ef1f7d15d836719fc1d62d/src/BloomExe/packages.config#L16)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There are two below which got removed as well.

Then feel free to merge.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5349)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/packages.config` line 16 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5349#-N9n-gTn5LJRxRux9cow:-N9r4bBf8G3njkvm56Pq:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8e0d57edf0ce06a677ef1f7d15d836719fc1d62d/src/BloomExe/packages.config#L16)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

There are two below which got removed as well.

Then feel free to merge.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5349)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
