### PR TITLE
BL-5404 cleanup after 2nd UI review of music toolbox

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2123)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.less, line 81 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2123#-L489osaD2xXz1uFJXM0:-L489osbAEdjGp99VvU5:bec8p3u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/87942fb93d03c0ef17dd69aac7a99d40e948410d/src/BloomBrowserUI/bookEdit/toolbox/toolbox.less#L81)):*
> ```Less
> .ui-accordion h3[data-toolId="decodableReaderTool"] span.ui-accordion-header-icon,
> .ui-accordion h3[data-toolId="leveledReaderTool"] span.ui-accordion-header-icon,
> .ui-accordion h3[data-toolId="musicTool"] span.ui-accordion-header-icon {
> ```

Can we remove the toolid specifier, so that each new tool doesn't have this step?

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.less, line 105 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2123#-L489yRa622LtR_F6dNe:-L489yRa622LtR_F6dNf:b6s6x3y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/87942fb93d03c0ef17dd69aac7a99d40e948410d/src/BloomBrowserUI/bookEdit/toolbox/toolbox.less#L105)):*
> ```Less
> }
> 
> .ui-accordion h3[data-toolId="musicTool"] span.ui-accordion-header-icon {
> ```

Is there by chance a way we supply this as part of the stylesheet of the control?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2123)*

**Comment by JohnThomson** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.less, line 81 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2123#-L489osaD2xXz1uFJXM0:-L4CGYNhwZ7yT9dbeJhx:b-3fw1q1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/87942fb93d03c0ef17dd69aac7a99d40e948410d/src/BloomBrowserUI/bookEdit/toolbox/toolbox.less#L81)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Can we remove the toolid specifier, so that each new tool doesn't have this step?
</blockquote></details>

Each of them will have to specify an icon or do something to hide the default accordion icon, but I guess that's OK.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.less, line 105 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2123#-L489yRa622LtR_F6dNe:-L4CGh9pH0Rpun_0yvry:bbhghh2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/87942fb93d03c0ef17dd69aac7a99d40e948410d/src/BloomBrowserUI/bookEdit/toolbox/toolbox.less#L105)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is there by chance a way we supply this as part of the stylesheet of the control?
</blockquote></details>

I moved it there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2123)*

**Comment by hatton** [comment]
Reviewed 5 of 5 files at r1.
Review status: 3 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.less, line 81 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2123#-L489osaD2xXz1uFJXM0:-L4DPzMNxa5rqw9ASoj8:b-o4g9gw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/87942fb93d03c0ef17dd69aac7a99d40e948410d/src/BloomBrowserUI/bookEdit/toolbox/toolbox.less#L81)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Each of them will have to specify an icon or do something to hide the default accordion icon, but I guess that's OK.
</blockquote></details>

Not sure I follow, but could you instead change the css so there is no default accordion icon?

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.less, line 105 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2123#-L489yRa622LtR_F6dNe:-L4DQ8hV1R3TOQkSW9M3:bllxdj1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/87942fb93d03c0ef17dd69aac7a99d40e948410d/src/BloomBrowserUI/bookEdit/toolbox/toolbox.less#L105)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I moved it there.
</blockquote></details>

So, we don't yet allow components to have their own stylesheet, is that right?  What would that take?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2123)*

**Comment by JohnThomson** [comment]
Review status: 3 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.less, line 105 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2123#-L489yRa622LtR_F6dNe:-L4GpJizOGlPw8WK8Swp:b-9jghrc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/87942fb93d03c0ef17dd69aac7a99d40e948410d/src/BloomBrowserUI/bookEdit/toolbox/toolbox.less#L105)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

So, we don't yet allow components to have their own stylesheet, is that right?  What would that take?
</blockquote></details>

I don't follow. Each (or most) panels have their own stylesheets, like music.less. That's where I moved the rule, which is what I thought you wanted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2123)*

**Comment by hatton** [comment]
Review status: 3 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.less, line 105 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2123#-L489yRa622LtR_F6dNe:-L4Gr1cSlKjEtR2ymfbh:b-86rq7d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/87942fb93d03c0ef17dd69aac7a99d40e948410d/src/BloomBrowserUI/bookEdit/toolbox/toolbox.less#L105)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't follow. Each (or most) panels have their own stylesheets, like music.less. That's where I moved the rule, which is what I thought you wanted.
</blockquote></details>

This comment is on a file named "toolbox.less", about a rule that is only applicable to "musicTool". Thus one might hope to find this rule in "musictool.less". Place this rule in the container, by contrast, breaks the component-ness we are aiming for.

Alternatively, we could have the api that tools implement have to provide an icon, and have the toolbox take that and stick it in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2123)*

**Comment by JohnThomson** [comment]
Review status: 3 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.less, line 81 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2123#-L489osaD2xXz1uFJXM0:-L4GxnrdeWMOIzmASwEq:b-85mcow) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/87942fb93d03c0ef17dd69aac7a99d40e948410d/src/BloomBrowserUI/bookEdit/toolbox/toolbox.less#L81)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Not sure I follow, but could you instead change the css so there is no default accordion icon?
</blockquote></details>

I think I have done that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2123)*

**Comment by JohnThomson** [comment]
Review status: 3 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.less, line 105 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2123#-L489yRa622LtR_F6dNe:-L4Gy0gLWbNnpSOpFLjF:bmg0rno) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/87942fb93d03c0ef17dd69aac7a99d40e948410d/src/BloomBrowserUI/bookEdit/toolbox/toolbox.less#L105)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This comment is on a file named "toolbox.less", about a rule that is only applicable to "musicTool". Thus one might hope to find this rule in "musictool.less". Place this rule in the container, by contrast, breaks the component-ness we are aiming for.

Alternatively, we could have the api that tools implement have to provide an icon, and have the toolbox take that and stick it in.
</blockquote></details>

I think you are not seeing the latest changes. I moved the rule from toolbox.less to music.less.
I have not yet moved ALL the tool-specific rules to the various tool's private less files...should we do that now? I don't know whether all of them already have such files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2123)*

**Comment by hatton** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2123)*

**Pull request merged**
