### PR TITLE
Fix BL-3115, and a number of small probs when html or json is corrupt

### PR DESCRIPTION
**Pull request by hatton**
The proximate problem was saving the book, in the constructor when it lacked a color and was too corrupt to be saved. We no longer save during construction. While I was in there, I made newly created books have the same cover color as the preview the user was shown.

Corrupt meta.json used to use a very different code path to talking to the user; changed that so that they get the same UI, with a button to send us the book.

[Review on Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/949)

### CODE REVIEW

**Comment by JohnThomson** [comment]
I may be being too picky with some of these...just pointing out what occurred to me. I don't think any of them are vital changes.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/BloomExe/Book/Book.cs, line 111 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949#-KB9JHf4UBeQCSmDRh_M:-KB9JHf4UBeQCSmDRh_N:-1456522075) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7d465c7b23e1373c4ccdd62a2a0a39e966d13612/src/BloomExe/Book/Book.cs#L111)):*
I wonder if there is a naming or similar problem here? It isn't obvious how info.IsEditable is related to Book.IsEditable (used about six lines up) or how either relates to whether we are creating a Book object for (a) an existing book folder (b) a new book for translating a shell (c) a new book being authored.  Anyway, it's not obvious to me how this test relates to the comment in the following line.
It's also not clear how this relates to the next block of code that is careful not to InitCoverColor if the book already has one. I wonder whether it would be clearer (absent other callers that really want to change an existing cover color) to put the guard against changing an existing color into the InitCoverColor method? Might then be appropriate to adjust the name...

---

*[src/BloomExe/Book/Book.cs, line 119 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949#-KB9LX09y_6Kp4bbJHyi:-KB9LX09y_6Kp4bbJHyj:-1311178900) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44bc116ac108c5ee8986050731ec324d8f4868f8/src/BloomExe/Book/Book.cs#L119)):*
I see why you don't want to Save in a constructor, but what ensures that the chosen color for a new book will get safely saved?

---

*[src/BloomExe/Book/Book.cs, line 486 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949#-KB9J5sXoxuf1qbZaoDb:-KB9J5sY8vKK29xjStdt:903436258) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7d465c7b23e1373c4ccdd62a2a0a39e966d13612/src/BloomExe/Book/Book.cs#L486)):*
Is there enough here that is common to _storage.GetBrokenBookRecommendationHtml for a static method?

---

*[src/BloomExe/Book/BookInfo.cs, line 397 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949#-KB9M342Ehn884dKQA9-:-KB9M342Ehn884dKQA90:-2004867532) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7d465c7b23e1373c4ccdd62a2a0a39e966d13612/src/BloomExe/Book/BookInfo.cs#L397)):*
Is the /*review*/ here now obsolete?

---

*[src/BloomExe/Book/BookServer.cs, line 28 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949#-KB9MUjXo-rkq9kDUeVU:-KB9MUjYyT08ENH8au1H:-575557091) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7d465c7b23e1373c4ccdd62a2a0a39e966d13612/src/BloomExe/Book/BookServer.cs#L28)):*
Better to use "bookInfo is ErrorBookInfo"...shorter and will handle the (improbable) case of subclasses.
Possibly better still to give BookInfo a virtual method for creating a corresponding book, which ErrorBookInfo could then override.

---

*[src/BloomExe/Book/ErrorBook.cs, line 64 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949#-KB9Mt5w_cWMU0vX8pae:-KB9Mt5w_cWMU0vX8paf:-1743129587) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7d465c7b23e1373c4ccdd62a2a0a39e966d13612/src/BloomExe/Book/ErrorBook.cs#L64)):*
If really obsolete, just delete? (and below)

---

*[src/BloomExe/CollectionTab/LibraryModel.cs, line 244 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949#-KB9NxHZSNCBx9udQRYa:-KB9NxHZSNCBx9udQRYb:422151564) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7d465c7b23e1373c4ccdd62a2a0a39e966d13612/src/BloomExe/CollectionTab/LibraryModel.cs#L244)):*
Feels to me that this should be something the Thumbnailer knows...unless possibly there could be a virtual method on Book which ErrorBook overrides?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949#-:-KB9Oo4i7X0acTTm_CXz:-436931764)*

**Comment by hatton** [comment]
Review status: 5 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/BloomExe/Book/Book.cs, line 111 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949#-KB9JHf4UBeQCSmDRh_M:-KBAZn2aKYCawnIyfymF:-679321445) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7d465c7b23e1373c4ccdd62a2a0a39e966d13612/src/BloomExe/Book/Book.cs#L111)):*
Added comments making it clear what's going on

---

*[src/BloomExe/Book/Book.cs, line 119 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949#-KB9LX09y_6Kp4bbJHyi:-KBAWDAQMveHBz23aIXh:741471432) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44bc116ac108c5ee8986050731ec324d8f4868f8/src/BloomExe/Book/Book.cs#L119)):*
Bloom is gonna save it when you leave the page it's showing you. And let's say I'm wrong, there's some corner case.... I don't see the damage.

---

*[src/BloomExe/Book/Book.cs, line 486 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949#-KB9J5sXoxuf1qbZaoDb:-KBAZMeZSFJ3N0KAIdvW:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7d465c7b23e1373c4ccdd62a2a0a39e966d13612/src/BloomExe/Book/Book.cs#L486)):*
Done.

---

*[src/BloomExe/Book/BookInfo.cs, line 397 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949#-KB9M342Ehn884dKQA9-:-KBAYHwjl9kGHQYpkVTT:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7d465c7b23e1373c4ccdd62a2a0a39e966d13612/src/BloomExe/Book/BookInfo.cs#L397)):*
Done.

---

*[src/BloomExe/Book/BookServer.cs, line 28 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949#-KB9MUjXo-rkq9kDUeVU:-KBAYDczNp2GVc1_e5EN:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7d465c7b23e1373c4ccdd62a2a0a39e966d13612/src/BloomExe/Book/BookServer.cs#L28)):*
Done.

---

*[src/BloomExe/Book/ErrorBook.cs, line 64 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949#-KB9Mt5w_cWMU0vX8pae:-KBAXLFMFSmYmfYZXl68:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7d465c7b23e1373c4ccdd62a2a0a39e966d13612/src/BloomExe/Book/ErrorBook.cs#L64)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949)*

**Comment by JohnThomson** [comment]
Review status: 5 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Book/Book.cs, line 114 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949#-KBIl6AQthhNQKpp-ii8:-KBIl6AQthhNQKpp-ii9:-389828752) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98f362f67c23e4c6ee72e75706aaacea279fc2d4/src/BloomExe/Book/Book.cs#L114)):*
So, IsEditable somehow corresponds to not newly-created? Why is it that a book newly created from a template or shell isn't editable at this point? Didn't we create it just for the purpose of editing? I think that's what's confusing to me, and the comment doesn't really help. Sorry.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949)*

**Comment by JohnThomson** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/Book.cs, line 114 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949#-KBIl6AQthhNQKpp-ii8:-KBIpI5LMPw2tZ3Y4cwm:-1058810907) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98f362f67c23e4c6ee72e75706aaacea279fc2d4/src/BloomExe/Book/Book.cs#L114)):*
IsEditable==false here tells you that you're actually showing a source, not a book in the user's collection

---

*[src/BloomExe/CollectionTab/LibraryModel.cs, line 244 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949#-KB9NxHZSNCBx9udQRYa:-KBIpZVG2vJBN19rhA-9:1000457366) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7d465c7b23e1373c4ccdd62a2a0a39e966d13612/src/BloomExe/CollectionTab/LibraryModel.cs#L244)):*
So, you just want this check moved to Thumbnailer?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/CollectionTab/LibraryModel.cs, line 244 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949#-KB9NxHZSNCBx9udQRYa:-KBIzBTVf4MWcpzGNalv:-670215106) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7d465c7b23e1373c4ccdd62a2a0a39e966d13612/src/BloomExe/CollectionTab/LibraryModel.cs#L244)):*
If you agree with me...it's not that important.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/Book.cs, line 114 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949#-KBIl6AQthhNQKpp-ii8:-KBIzSuiBV1XIiUu2r_n:-1248912641) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98f362f67c23e4c6ee72e75706aaacea279fc2d4/src/BloomExe/Book/Book.cs#L114)):*
Would this be right, then? "If the book is a template or shell (in a source collection, indicated by IsEditable being false), we pick a new color each run of the program (randomizing the colors of the books we create from them). If we're creating a book object for a book in the user's own collection that he can edit, we want to keep the color it already has, either from previous editing or just now copied from a template or shell, so a new book will match the current version of the template it was made from. So in that case we will only InitCoverColor if it somehow doesn't already have one."

That covers the following 'if' as well, so consider changing the following 'if' to an 'else if'? Seems it would be clearer then that the following block is only catching an exceptional situation.

Also I'd still like to see this method be consistent about using either info.IsEditable or plain (this.)IsEditable.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/Book.cs, line 114 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949#-KBIl6AQthhNQKpp-ii8:-KBJ5hVETHDa3ah75gED:-607302828) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/98f362f67c23e4c6ee72e75706aaacea279fc2d4/src/BloomExe/Book/Book.cs#L114)):*
Yes, that's about right, except it's no random.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/949)*

**Pull request merged**
