### PR TITLE
BL-10002 Lose refresh on comics

### PR DESCRIPTION
**Pull request by gmartin7**
* much more reliable setup
* takes care of gear icon not being functional
* better handling of child and duplicate bubbles
* a bit of refactoring

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4555)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
I'm asking JT to take a look, too.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4555#-:-McLVqnN9BaMFf-OV5tS:ba55rw5)* status: all files reviewed, 5 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 20 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4555#-McLRyN3BmM9t-1kbc7t:-McLRyN3BmM9t-1kbc7u:b-5ke752) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/813ea082614a24152bdf435e31692c9f8d2a5908/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L20)):*
> ```XML
> import { SetupElements, attachToCkEditor } from "./bloomEditing";
> 
> declare function GetSettings(): any; //c# injects this
> ```

Looks like we are supposed to import collectionSettings.d.ts.
And I think you can then make this a `settingsObject` instead of `any`.
My preference would be to rename `settingsObject` to `ICollectionSettings` or similar if it isn't a hassle.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 170 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4555#-McLUz8b0AL1zBrgKSgA:-McLUz8b0AL1zBrgKSgB:b-93fwj1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/813ea082614a24152bdf435e31692c9f8d2a5908/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L170)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>         const focusElements = Array.from(
>             activeElement.getElementsByClassName(
>                 "bloom-editable bloom-visibility-code-on"
>             )
>         ).filter(el => !el.parentElement!.classList.contains("box-header-off"));
> ```
</details>

Might as well extract this common bit of logic from focusFirst...
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 380 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4555#-McLVjQ8BX_IGw9ZV78t:-McLVjQ8BX_IGw9ZV78u:b-wrgghe) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/813ea082614a24152bdf435e31692c9f8d2a5908/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L380)):*
> ```
> true
> ```
false
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 1430 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4555#-McLVem2Cw17xgZb0qSw:-McLVem2Cw17xgZb0qSx:b-bqqg34) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/813ea082614a24152bdf435e31692c9f8d2a5908/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L1430)):*
> ```
> doNotReattach='true'
> ```
comment out of date
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 1589 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4555#-McLU9-WDoML5wnIRXcx:-McLU9-WDoML5wnIRXcy:bakusfu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/813ea082614a24152bdf435e31692c9f8d2a5908/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L1589)):*
> ```
> defLang
> ```
I don't know what a defLang is

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4555)* status: all files reviewed, 7 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 408 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4555#-McLg5uG1ASBlkjddWz9:-McLg5uG1ASBlkjddWzA:bxpgxw0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/813ea082614a24152bdf435e31692c9f8d2a5908/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L408)):*
> ```XML
>                 )[0] as HTMLElement;
>             }
>             this.focusLastVisibleEditable(focusableContainer);
> ```

Focusing the last visible editable was a compromise more-or-less forced on us when reloading the page after adding a bubble. But now we're updating the page in Javascript, can't we just unambiguously focus the new bubble we just made? Something up the call stack must know which one it is. (For one thing, it will work better with multiple images on the page, where the new bubble won't be absolutely last unless it's on the last image.) See my other comment for one idea.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 1598 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4555#-McLi79m8LjkGS45LcA1:-McLi79m8LjkGS45LcA2:bl3dvtj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/813ea082614a24152bdf435e31692c9f8d2a5908/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L1598)):*
> ```XML
>             "' lang='" +
>             defLang +
>             "'><p></p></div>";
> ```

Ideally, instead of doing this, we'd like to fill the TG with the results of posting "common/requestTranslationGroups" (badly named as it returns a sequence of bloom-editables that should be the content of one TG). I'm not clear what goes wrong if you do that. It would be an improvement if the code that inserts those results also focused the one in defLang, or the first with bloom-visibility-code-on, rather than having some other code focus the last editable on the page. Possibly you need to also postpone some initialization of those elements, like for ckeditor and focusIn. But that feels doable, and might make it easier to restrict that init to the new elements.
I don't have the whole picture, so this may be harder than I think. Feel free to push back.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4555)* status: 1 of 6 files reviewed, 7 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 20 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4555#-McLRyN3BmM9t-1kbc7t:-McPoqpnAC9UFZOc_4rJ:buymwvv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/813ea082614a24152bdf435e31692c9f8d2a5908/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L20)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like we are supposed to import collectionSettings.d.ts.
And I think you can then make this a `settingsObject` instead of `any`.
My preference would be to rename `settingsObject` to `ICollectionSettings` or similar if it isn't a hassle.
</blockquote></details>

Done. Not bad. Only used 4 places now. Renamed to `ICollectionSettings`, in the process confirming that there is not C# interface with the same name.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 170 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4555#-McLUz8b0AL1zBrgKSgA:-McQBy9657W7fmginRVi:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/813ea082614a24152bdf435e31692c9f8d2a5908/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L170)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
>         const focusElements = Array.from(
>             activeElement.getElementsByClassName(
>                 "bloom-editable bloom-visibility-code-on"
>             )
>         ).filter(el => !el.parentElement!.classList.contains("box-header-off"));
> ```
Might as well extract this common bit of logic from focusFirst...
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 380 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4555#-McLVjQ8BX_IGw9ZV78t:-McPuXJt6LdodbLcy7c5:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/813ea082614a24152bdf435e31692c9f8d2a5908/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L380)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> true
> ```
false
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 408 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4555#-McLg5uG1ASBlkjddWz9:-McQ8EwwEUWxEbUfn538:b-jpdh5b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/813ea082614a24152bdf435e31692c9f8d2a5908/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L408)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Focusing the last visible editable was a compromise more-or-less forced on us when reloading the page after adding a bubble. But now we're updating the page in Javascript, can't we just unambiguously focus the new bubble we just made? Something up the call stack must know which one it is. (For one thing, it will work better with multiple images on the page, where the new bubble won't be absolutely last unless it's on the last image.) See my other comment for one idea.
</blockquote></details>

Yes, and we do. This `else` branch is for when we come into the refresh method with no bubble... meaning we just deleted one. So we try to focus the last bloom-editable that is associated with this same `image-container` that we just deleted a bubble from. That way if you've added multiple bubbles and you delete one, the one that gets focused is the most recent one added.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 1430 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4555#-McLVem2Cw17xgZb0qSw:-McQ14cJDTHSrn5MkCAT:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/813ea082614a24152bdf435e31692c9f8d2a5908/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L1430)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> doNotReattach='true'
> ```
comment out of date
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 1589 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4555#-McLU9-WDoML5wnIRXcx:-McQ18AS8CJYvFE5VSNb:b9f37cj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/813ea082614a24152bdf435e31692c9f8d2a5908/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L1589)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> defLang
> ```
I don't know what a defLang is
</blockquote></details>

Done. (Originally copied from `StyleEditor.ts`, but I've given it a fuller name now... in both places.)
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 1598 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4555#-McLi79m8LjkGS45LcA1:-McQCAgvBB6Tt4SAW-mS:bvihrpa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/813ea082614a24152bdf435e31692c9f8d2a5908/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L1598)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Ideally, instead of doing this, we'd like to fill the TG with the results of posting "common/requestTranslationGroups" (badly named as it returns a sequence of bloom-editables that should be the content of one TG). I'm not clear what goes wrong if you do that. It would be an improvement if the code that inserts those results also focused the one in defLang, or the first with bloom-visibility-code-on, rather than having some other code focus the last editable on the page. Possibly you need to also postpone some initialization of those elements, like for ckeditor and focusIn. But that feels doable, and might make it easier to restrict that init to the new elements.
I don't have the whole picture, so this may be harder than I think. Feel free to push back.
</blockquote></details>

I wanted to use it. In fact, you're out-of-date, because my earlier PR moved it and renamed it. It's now `editView/requestTranslationGroupContent`. The problem was that this method `addTOPBoxInternal` returns the `contentElement` to the method that called it and runs off and does stuff with it while the api request would be executing. And between adding child bubbles and duplicating bubble families, this method gets reused a lot in quite a bewildering structure of method calls that I actually wrote out on my whiteboard the other day. I think it would take a lot of work to tease out how to make it all function asynchronously. :(

**Review by andrew-polk — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4555)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4555)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 1598 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4555#-McLi79m8LjkGS45LcA1:-McUhULK52n8Ugfmj1Re:btxecps) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/813ea082614a24152bdf435e31692c9f8d2a5908/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L1598)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I wanted to use it. In fact, you're out-of-date, because my earlier PR moved it and renamed it. It's now `editView/requestTranslationGroupContent`. The problem was that this method `addTOPBoxInternal` returns the `contentElement` to the method that called it and runs off and does stuff with it while the api request would be executing. And between adding child bubbles and duplicating bubble families, this method gets reused a lot in quite a bewildering structure of method calls that I actually wrote out on my whiteboard the other day. I think it would take a lot of work to tease out how to make it all function asynchronously. :(
</blockquote></details>

OK. You didn't make things worse, so we can leave that as a possible ToDo sometime.

**Pull request merged**
