### PR TITLE
Handle unnumbered content pages for Spreadsheet export (BL-11924)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
Also handle images being reused without new copies.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5642)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5642)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Spreadsheet/SpreadsheetExporter.cs` line 98 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5642#-NOWs4Xw6Nj8JXnvjKLu:-NOWs4Xw6Nj8JXnvjKLv:bdi2shp) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cd4a9939fa2dc5e0bbf1887b9f8004bed5d5c58e/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L98)):*
> ```Smalltalk
> 				// We ignore all xmatter pages, which were handled above by exporting data div data.
> 				var classes = (page.Attributes["class"]?.Value ?? "").Split(' ');
> 				if (classes.Contains("bloom-frontMatter") || classes.Contains("bloom-backMatter"))
> ```

Should we use XMatterHelper.IsBackMatterPage and XMatterHelper.IsFrontMatterPage? Or probably better, create XMatterHelper.IsXMatterPage?
___
*[`src/BloomExe/Spreadsheet/SpreadsheetExporter.cs` line 103 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5642#-NOWsBwUCl9NML3w1KFd:-NOWsBwUCl9NML3w1KFe:bvemmwm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cd4a9939fa2dc5e0bbf1887b9f8004bed5d5c58e/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L103)):*
> ```Smalltalk
> 				if (pageNumber == "")
> 				{
> 					// Do we need to do something for unnumbered pages?  Import doesn't really handle them very well.
> ```

I think you're the one with the knowledge here at this point (you say import has an issue), so I think we should answer this now.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5642)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Spreadsheet/SpreadsheetExporter.cs` line 98 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5642#-NOWs4Xw6Nj8JXnvjKLu:-NOjpVR71SSWZrpL6ZgH:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cd4a9939fa2dc5e0bbf1887b9f8004bed5d5c58e/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L98)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should we use XMatterHelper.IsBackMatterPage and XMatterHelper.IsFrontMatterPage? Or probably better, create XMatterHelper.IsXMatterPage?
</blockquote></details>

Done.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetExporter.cs` line 103 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5642#-NOWsBwUCl9NML3w1KFd:-NOk4Xsn7_gAhDFvzkFc:b-wkucyn) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cd4a9939fa2dc5e0bbf1887b9f8004bed5d5c58e/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L103)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think you're the one with the knowledge here at this point (you say import has an issue), so I think we should answer this now.
</blockquote></details>

Done.  I think I fixed import to handle unnumbered pages.  It was a relatively simple fix.

**Review by StephenMcConnel — COMMENTED** [review]
This was marked as "maybe 5.4" but currently targets 5.5.  I'll let others decide if this change is safe for 5.4.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5642#-:-NOk4ttZ-5OQKTL5ggNa:b-sak6ms)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5642)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by andrew-polk — APPROVED** [review]
Probably fine for 5.4, but let's test it first.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5642#-:-NOk9FzO6A4NtxoUf66U:b-icre1l)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
