### PR TITLE
BL-4042 more i18n

### PR DESCRIPTION
**Pull request by gmartin7**
* get DecodableRT sort tooltips localized
* add code to compile localized .jade for leveled RT
   'Keep in mind' links
* enable localizing of CKEditor tooltips

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1354)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[.gitignore, line 81 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1354#-KYE7DxkvVP1hOjL3Pkb:-KYE7DxkvVP1hOjL3Pkc:b-4m2c2l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ddc74bb6e7aeb610c0215f70fcb8406ef194abf7/.gitignore#L81)):*
> ```
> DistFiles/Bloom.chm
> DistFiles/optipng.exe
> DistFiles/leveledRTInfo/*.html
> ```

Confused. Do the html files need to be checked in? 
If yes, we can't ignore them.
If no, why is one modified in this PR?

---

*[src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxPanel.jade, line 65 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1354#-KYEJxzoQhuZWhzNDXLc:-KYEJxzoQhuZWhzNDXLd:b-lqwl4d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/634648e9151fbef6f4eeb39dbddc5909480d2fc4/src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxPanel.jade#L65)):*
> .FoThisLevel

Was this removed intentionally? The resulting ID doesn't seem like it could be what we want.

---

*[src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxPanel.ts, line 7 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1354#-KYEADtZ6SrgSlR-sLYS:-KYEADtZ6SrgSlR-sLYT:bkwukbb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ddc74bb6e7aeb610c0215f70fcb8406ef194abf7/src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxPanel.ts#L7)):*
> ```XML
> import {ToolBox} from "../../toolbox";
> import {theOneLibSynphony}  from '../libSynphony/synphony_lib';
> import theOneLocalizationManager from '../../../../lib/localizationManager/localizationManager';
> ```

Is this needed? I don't see it used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1354)*

**Comment by gmartin7** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[.gitignore, line 81 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1354#-KYE7DxkvVP1hOjL3Pkb:-KYEc4GyKiX7LEwDnuuJ:b-qvyfqd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ddc74bb6e7aeb610c0215f70fcb8406ef194abf7/.gitignore#L81)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Confused. Do the html files need to be checked in? 
If yes, we can't ignore them.
If no, why is one modified in this PR?
</blockquote></details>

They don't need to be checked in and I switched from .htm to .html. The modified one is a .htm that I deleted. (So the .jade should be switched to reference .html too.)
Hmm... I guess I'm assuming the installer will do the right thing and generate/install the .html files to the right place.

---

*[src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxPanel.jade, line 65 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1354#-KYEJxzoQhuZWhzNDXLc:-KYEbfNDs2xgRAC9Nogz:b-jhkj0b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/634648e9151fbef6f4eeb39dbddc5909480d2fc4/src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxPanel.jade#L65)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> .FoThisLevel

Was this removed intentionally? The resulting ID doesn't seem like it could be what we want.
</blockquote></details>

I went to try spelling it correctly (I'm a nit-picker for spelling), but I couldn't find anything that used that class, correct spelling or no! So I removed it.

---

*[src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxPanel.ts, line 7 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1354#-KYEADtZ6SrgSlR-sLYS:-KYEbuMDDqF1wsXQi2MO:bx2nhpz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ddc74bb6e7aeb610c0215f70fcb8406ef194abf7/src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxPanel.ts#L7)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is this needed? I don't see it used.
</blockquote></details>

Ah! Probably not. Earlier on I thought so and it never got removed. Will fix.
[Later: It looks like the one above it is unneeded too.('theOneLibSynphony'). Deleted both references.]

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1354)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.gitignore, line 81 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1354#-KYE7DxkvVP1hOjL3Pkb:-KYEnPXbHn9wXtaHvIP5:bgvnlmt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ddc74bb6e7aeb610c0215f70fcb8406ef194abf7/.gitignore#L81)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

They don't need to be checked in and I switched from .htm to .html. The modified one is a .htm that I deleted. (So the .jade should be switched to reference .html too.)
Hmm... I guess I'm assuming the installer will do the right thing and generate/install the .html files to the right place.
</blockquote></details>

The file I refer to you having modified is this one: /DistFiles/leveledRTInfo/leveledReaderInfo-ne.html

---

*[src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxPanel.jade, line 65 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1354#-KYEJxzoQhuZWhzNDXLc:-KYEnc8TkK5rtTO0dKkW:bjj6cdg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/634648e9151fbef6f4eeb39dbddc5909480d2fc4/src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxPanel.jade#L65)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I went to try spelling it correctly (I'm a nit-picker for spelling), but I couldn't find anything that used that class, correct spelling or no! So I removed it.
</blockquote></details>

But you didn't remove the ID. You changed it to EditTab.Toolbox.LeveledReaderTool.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1354)*

**Comment by gmartin7** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.gitignore, line 81 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1354#-KYE7DxkvVP1hOjL3Pkb:-KYEpC8t7mZ5ToGO9W6Q:beaxi0o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ddc74bb6e7aeb610c0215f70fcb8406ef194abf7/.gitignore#L81)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The file I refer to you having modified is this one: /DistFiles/leveledRTInfo/leveledReaderInfo-ne.html
</blockquote></details>

Oi! Good catch! That one had been in the repo, but should also be deleted.

---

*[src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxPanel.jade, line 65 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1354#-KYEJxzoQhuZWhzNDXLc:-KYEpuf_97UFOlqhHB54:b-4m0978) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/634648e9151fbef6f4eeb39dbddc5909480d2fc4/src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxPanel.jade#L65)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

But you didn't remove the ID. You changed it to EditTab.Toolbox.LeveledReaderTool.
</blockquote></details>

Oh my! What was I thinking!? Much easier to leave it as it was than to try to fix all the .tmx files for something the user won't see. Bummer. :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1354)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1354#-:-KYEsZlhIGtpx2QTsyjj:bnfp4nl)*

**Comment by gmartin7** [comment]
@hatton asked for a change to decodableReaderToolboxPanel.ts, which I have done.

**Comment by gmartin7** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1354)*

**Pull request merged**
