### PR TITLE
Fix javascript error (BL-9114)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4000)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4000)* status: 0 of 1 files reviewed, 2 unresolved discussions

___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 443 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4000#-MJ3G_dv4yAmCN2qP8Y8:-MJ3G_dw9bdyOd2pNk5h:b1j9so3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f03ca4b9055c27a5c99b7d05481cdf395a0b5e50/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L443)):*
> ```
> (field)
> ```
I guess this has been buggy for years, but Javascript didn't complain about it until we upgraded Typescript.  FYI, previously, even though I have no idea what it thinks $(this) is (don't get anything meaningful when i try to print it out...), but when you do $(this).find("p"), the result is that it finds every paragraph on the page, not the paragraphs that are descendants of field.
___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 463 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4000#-MJ3H51r43Pnva3uQg3Z:-MJ3H51s7xrS12ZQwJCS:b-c093ku) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f03ca4b9055c27a5c99b7d05481cdf395a0b5e50/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L463)):*
> ```
> $(field)
> ```
I didn't test this yet, wasn't sure how to get it to trigger.

But anyway, I (painstakingly) tried to find any other uses of $(this) inside an arrow function. I think this is the only other place.

**Review by andrew-polk — COMMENTED** [review]
Change seems fine as far as I can tell.
But it is difficult to understand what is really being affected here.
Does this fix a real bug?
If so, could you detail it in the card?

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4000#-:-MJ3Hajw5ufvJT64RPqK:bvks2xu)* status: all files reviewed, 2 unresolved discussions

**Review by andrew-polk — COMMENTED** [review]
Oops. I wrote that before you comments. Reading...

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4000#-:-MJ3HwfaCgbYagiKJisz:b8ro5el)* status: all files reviewed, 2 unresolved discussions

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4000)* status: all files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 443 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4000#-MJ3G_dv4yAmCN2qP8Y8:-MJ3IVA7-XUz89TLfwic:bv48rfx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f03ca4b9055c27a5c99b7d05481cdf395a0b5e50/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L443)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> (field)
> ```
I guess this has been buggy for years, but Javascript didn't complain about it until we upgraded Typescript.  FYI, previously, even though I have no idea what it thinks $(this) is (don't get anything meaningful when i try to print it out...), but when you do $(this).find("p"), the result is that it finds every paragraph on the page, not the paragraphs that are descendants of field.
</blockquote></details>

Thanks for finding and fixing this. Please include steps to repro the bug in the card.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4000)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
