### PR TITLE
Cleanup to record video

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5031)

### CODE REVIEW

**Review by jsubloom — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5031)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @JohnThomson and @sujeffreyl)

___
*[src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx, line 181 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5031#-My9c85hBK8mA_BzzSh-:-My9c85hBK8mA_BzzSh0:b8ua10u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/29dfc560b8a86bd979d52f3fe0071db822d7684e/src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx#L181)):*
> ```XML
>     };
>     const reset = () => {
>         sendMessageToPlayer({ pause: true });
> ```

Is it able to handle both pause and reset passed in the same object?
___
*[src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx, line 193 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5031#-My9cgos3fp7JAyoM3iH:-My9cgos3fp7JAyoM3iI:b-xa32oh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/29dfc560b8a86bd979d52f3fe0071db822d7684e/src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx#L193)):*
> ```XML
>             // something sends us an empty message, which we haven't figured out, but know we can ignore
>             if (!data || !data.data || data.data.length === 0) {
>                 //console.log("returning early");
> ```

I feel like the commented out console.logs don't provide sufficient value anymore, I'm in favor of removing them.
___
*[src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx, line 201 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5031#-My9cf7yB3Okbr0SB7sD:-My9cf7yB3Okbr0SB7sE:b8yr7m4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/29dfc560b8a86bd979d52f3fe0071db822d7684e/src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx#L201)):*
> ```XML
>                 const msg = JSON.parse(data.data);
>                 if (msg.messageType == "playbackComplete") {
>                     console.log("pausing");
> ```

Is this console.log still necessary?
___
*[src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx, line 333 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5031#-My9eP7MEyDLFh8Q0VYf:-My9eP7MEyDLFh8Q0VYg:be71juo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/29dfc560b8a86bd979d52f3fe0071db822d7684e/src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx#L333)):*
> ```XML
>                                                 css={css`
>                                                     color: ${kBloomBlue +
>                                                         (playing
> ```

Optional: I feel like it is not obvious enough that if the condition for disabled changes, then we should update this line as well. I suggest creating a local var called isPauseButtonDisabled and setting it to !playing, and then using that var on this line and in the Button props above.
___
*[src/BloomBrowserUI/publish/video/VideoOptionsGroup.tsx, line 409 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5031#-My9iI5D6or3_0kTPX4u:-My9iI5D6or3_0kTPX4v:bge132d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/29dfc560b8a86bd979d52f3fe0071db822d7684e/src/BloomBrowserUI/publish/video/VideoOptionsGroup.tsx#L409)):*
> ```XML
>                 </Popover>
>             </div>
>             <div
> ```

Wanted to double-check, does this div do something for use? Extra spacing?



_Code quote:_
```XML
div
```

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5031)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx, line 181 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5031#-My9c85hBK8mA_BzzSh-:-MyCr3Lr-FOJWUtGcnqv:bb7sa0c) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/29dfc560b8a86bd979d52f3fe0071db822d7684e/src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx#L181)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Is it able to handle both pause and reset passed in the same object?
</blockquote></details>

yes.
___
*[src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx, line 193 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5031#-My9cgos3fp7JAyoM3iH:-MyCreSK4PnoTuFcq7Gp:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/29dfc560b8a86bd979d52f3fe0071db822d7684e/src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx#L193)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I feel like the commented out console.logs don't provide sufficient value anymore, I'm in favor of removing them.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx, line 201 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5031#-My9cf7yB3Okbr0SB7sD:-MyCrf4D-0NWVK1--IHn:b2nhky0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/29dfc560b8a86bd979d52f3fe0071db822d7684e/src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx#L201)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Is this console.log still necessary?
</blockquote></details>

No.
___
*[src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx, line 333 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5031#-My9eP7MEyDLFh8Q0VYf:-MyCvFlMBc6rD3Fix1Pz:bb7f2mf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/29dfc560b8a86bd979d52f3fe0071db822d7684e/src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx#L333)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Optional: I feel like it is not obvious enough that if the condition for disabled changes, then we should update this line as well. I suggest creating a local var called isPauseButtonDisabled and setting it to !playing, and then using that var on this line and in the Button props above.
</blockquote></details>

done
___
*[src/BloomBrowserUI/publish/video/VideoOptionsGroup.tsx, line 409 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5031#-My9iI5D6or3_0kTPX4u:-MyCv_Ck1iz9K6W3bPYA:b-njtaol) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/29dfc560b8a86bd979d52f3fe0071db822d7684e/src/BloomBrowserUI/publish/video/VideoOptionsGroup.tsx#L409)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Wanted to double-check, does this div do something for use? Extra spacing?
</blockquote></details>

I think it was left over. Removed.

**Review by jsubloom — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5031)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx, line 181 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5031#-My9c85hBK8mA_BzzSh-:-MyD-Dzv3APIlwTIB1Jb:b-5t487) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/29dfc560b8a86bd979d52f3fe0071db822d7684e/src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx#L181)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

yes.
</blockquote></details>

Ok cool! Seems like it'd be better to just send a single combined message instead of two messages then?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5031)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx, line 181 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5031#-My9c85hBK8mA_BzzSh-:-MyD7OH10HCsBg8ISjDX:b4354s2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/29dfc560b8a86bd979d52f3fe0071db822d7684e/src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx#L181)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Ok cool! Seems like it'd be better to just send a single combined message instead of two messages then?
</blockquote></details>

Sorry, I was wrong. They need to be passed as separate messages.

**Review by jsubloom — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5031#-:-MyDAck3BEFXc6zz0-rF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx, line 181 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5031#-My9c85hBK8mA_BzzSh-:-MyDAY-F-Tf_ML8zR-c3:buxhaet) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/29dfc560b8a86bd979d52f3fe0071db822d7684e/src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx#L181)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Sorry, I was wrong. They need to be passed as separate messages.
</blockquote></details>

ok that's fine, thanks for checking!

**Pull request merged**
