### PR TITLE
[4.1]BL-4692 Paste Image Credits page nums

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1899)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/BookStorage.cs, line 364 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899#-KwgrDwW7ZOY6Cq53BQv:-KwgrDwW7ZOY6Cq53BQw:b21rupi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/54849b9a91f91f0bd27dd46074efd9e8a0712127/src/BloomExe/Book/BookStorage.cs#L364)):*
> ```Smalltalk
> 
> 		/// <summary>
> 		/// Returns a Dictionary&lt;string, List&lt;int&gt;&gt; that contains each image name and a list of pages
> ```

Do we want this in BookStorage? It doesn't seem to be related to files on disk at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899)*

**Comment by gmartin7** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/BookStorage.cs, line 364 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899#-KwgrDwW7ZOY6Cq53BQv:-KwkGLLbOcZtu40nTYT1:bg7dryf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/54849b9a91f91f0bd27dd46074efd9e8a0712127/src/BloomExe/Book/BookStorage.cs#L364)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Do we want this in BookStorage? It doesn't seem to be related to files on disk at all.
</blockquote></details>

Good point! Code moved back to ImageApi and test moved to its own file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899)*

**Comment by andrew-polk** [comment]
Looks good over all; a couple notes.

---

Reviewed 2 of 5 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/BloomExe/web/controllers/ImageApi.cs, line 159 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899#-Kwpxtnc3HVcR5nM0SS1:-Kwpxtnc3HVcR5nM0SS2:b9b8yll) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d85e872d28a287e306986b66c1802ab7bbc9319d/src/BloomExe/web/controllers/ImageApi.cs#L159)):*
> ```Smalltalk
> 			if (credits.TryGetValue(credit, out oldPagesList))
> 			{
> 				var newResult = new SortedSet<int>();
> ```

This seems overly complex. Can the main data structure use SortedSet instead of List so we don't have to convert back and forth and delete/add the key?

---

*[src/BloomExe/web/controllers/ImageApi.cs, line 222 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899#-Kwpy_xqrBlCIuC-UCOA:-Kwpy_xqrBlCIuC-UCOB:b-dhsgzu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d85e872d28a287e306986b66c1802ab7bbc9319d/src/BloomExe/web/controllers/ImageApi.cs#L222)):*
> ```Smalltalk
> 				return -1; // unsuccessful
> 			}
> 			// Review: I assume the data-page-number attribute is just normal arabic digit(s)
> ```

Let's not assume. Let's verify. : )

---

*[src/BloomTests/web/controllers/ImageApiTests.cs, line 168 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899#-KwpvjqPkYDnzob4xz_i:-KwpvjqPkYDnzob4xz_j:bcc7rdl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d85e872d28a287e306986b66c1802ab7bbc9319d/src/BloomTests/web/controllers/ImageApiTests.cs#L168)):*
> ```Smalltalk
> 			var dom = new XmlDocument();
> 			dom.LoadXml(xhtml);
> 			var imageNameToPages = ImageApi.GetWhichImagesAreUsedOnWhichPages(dom.SelectSingleNode("//body"));
> ```

Should we verify the total number of expected images?

---

*[src/BloomTests/web/controllers/ImageApiTests.cs, line 172 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899#-KwpvcmdeAJD_vRQRYd0:-KwpvcmdeAJD_vRQRYd1:b-d2272b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d85e872d28a287e306986b66c1802ab7bbc9319d/src/BloomTests/web/controllers/ImageApiTests.cs#L172)):*
> ```Smalltalk
> 			Assert.IsTrue(imageNameToPages.ContainsKey("back-cover-outside.svg"), "Branding images get filtered later");
> 			Assert.IsTrue(imageNameToPages.ContainsKey("placeHolder.png"), "Placeholder images get filtered later");
> 			Assert.IsTrue(!imageNameToPages.ContainsKey("AOR_aa013m.png"), "Wrongly includes background images from frontmatter");
> ```

Confused. Why don't we credit an image just because it is displayed using the background image method?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899#-:-KwpykIs-Syacj12hPBH:b-xqc8ji)*

**Comment by gmartin7** [comment]
Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/BloomExe/web/controllers/ImageApi.cs, line 159 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899#-Kwpxtnc3HVcR5nM0SS1:-KxETzAjfKGphxMkj-7H:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d85e872d28a287e306986b66c1802ab7bbc9319d/src/BloomExe/web/controllers/ImageApi.cs#L159)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This seems overly complex. Can the main data structure use SortedSet instead of List so we don't have to convert back and forth and delete/add the key?
</blockquote></details>

Done.

---

*[src/BloomExe/web/controllers/ImageApi.cs, line 222 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899#-Kwpy_xqrBlCIuC-UCOA:-KxEVrYjD2V-idiGfLts:brg80i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d85e872d28a287e306986b66c1802ab7bbc9319d/src/BloomExe/web/controllers/ImageApi.cs#L222)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's not assume. Let's verify. : )
</blockquote></details>

Oops. Bad assumption. Reworked to use SortedSet<string> and NaturalSortComparer to handle other numeral systems and multi-digit page numbers.

---

*[src/BloomTests/web/controllers/ImageApiTests.cs, line 168 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899#-KwpvjqPkYDnzob4xz_i:-KxF5TGUdlIqJyl6f9T3:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d85e872d28a287e306986b66c1802ab7bbc9319d/src/BloomTests/web/controllers/ImageApiTests.cs#L168)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should we verify the total number of expected images?
</blockquote></details>

Done.

---

*[src/BloomTests/web/controllers/ImageApiTests.cs, line 172 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899#-KwpvcmdeAJD_vRQRYd0:-KxF5UQoj3KR3Kcg40z_:bkjohwc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d85e872d28a287e306986b66c1802ab7bbc9319d/src/BloomTests/web/controllers/ImageApiTests.cs#L172)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Confused. Why don't we credit an image just because it is displayed using the background image method?
</blockquote></details>

Clarified the test. Actually I was saying frontmatter shouldn't be included. Added a test for background images elsewhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomTests/web/controllers/ImageApiTests.cs, line 172 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899#-KwpvcmdeAJD_vRQRYd0:-KxIYX9utogpdupRaZSK:b7l8vxp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d85e872d28a287e306986b66c1802ab7bbc9319d/src/BloomTests/web/controllers/ImageApiTests.cs#L172)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Clarified the test. Actually I was saying frontmatter shouldn't be included. Added a test for background images elsewhere.
</blockquote></details>

I'm still questioning the validity of this assertion that we don't include images from the xMatter. As a user, I would expect a list of images and their IP info to include all the images I added to the book.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899)*

**Comment by hatton** [comment]
Sure. Just not license or branding images

**Comment by gmartin7** [comment]
OK, this latest update covers 'legitimate' xmatter pictures too.

---

Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomTests/web/controllers/ImageApiTests.cs, line 172 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899#-KwpvcmdeAJD_vRQRYd0:-KxKQhQsPtloVBeGhlhW:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d85e872d28a287e306986b66c1802ab7bbc9319d/src/BloomTests/web/controllers/ImageApiTests.cs#L172)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm still questioning the validity of this assertion that we don't include images from the xMatter. As a user, I would expect a list of images and their IP info to include all the images I added to the book.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899#-:-KxKQY4KQwaSHfcBxzi3:b7zzq0y)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomTests/web/controllers/ImageApiTests.cs, line 152 at r4](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899#-KxNfe0Mr2VqY-VPRZBq:-KxNfe0Mr2VqY-VPRZBr:bl2nlbv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2dfe422efd404ad9457167cfef0c588575da1f26/src/BloomTests/web/controllers/ImageApiTests.cs#L152)):*
> Branding images get filtered later

Do we have tests for that? (Same for placeholder and license.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899)*

**Comment by gmartin7** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomTests/web/controllers/ImageApiTests.cs, line 152 at r4](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899#-KxNfe0Mr2VqY-VPRZBq:-KxOrJJ0-MYv-otRu2vi:bax4ytb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2dfe422efd404ad9457167cfef0c588575da1f26/src/BloomTests/web/controllers/ImageApiTests.cs#L152)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> Branding images get filtered later

Do we have tests for that? (Same for placeholder and license.)
</blockquote></details>

Good point. I've adjusted the tests to include the filtering.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomTests/web/controllers/ImageApiTests.cs, line 31 at r5](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899#-KxOtn4ht-QwTxEjZCm1:-KxOtn4ht-QwTxEjZCm2:b-b3da3f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8c4b1a3f8bc96a2c061b2526334ac64c44685b34/src/BloomTests/web/controllers/ImageApiTests.cs#L31)):*
> ```Smalltalk
> 
> 		[Test]
> 		public void GetWhichImagesAreUsedOnWhichPages_AccumulatesCorrectly()
> ```

Let's update the test names, then I think we are good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899)*

**Comment by gmartin7** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomTests/web/controllers/ImageApiTests.cs, line 31 at r5](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899#-KxOtn4ht-QwTxEjZCm1:-KxOvmx7EpdHrYIo6awV:bkafiz5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8c4b1a3f8bc96a2c061b2526334ac64c44685b34/src/BloomTests/web/controllers/ImageApiTests.cs#L31)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's update the test names, then I think we are good.
</blockquote></details>

Good point. Done. Merging...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1899)*

**Pull request merged**
