### PR TITLE
BL-5054 Fix Russian license for unrelated lgs

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1858)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Collection/CollectionSettings.cs, line 766 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1858#-KuQfXXsF2_LxK5L-sqs:-KuQfXXsF2_LxK5L-sqt:b1cn9h4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c348f37813eb80dc521ead5633adb951ed401c54/src/BloomExe/Collection/CollectionSettings.cs#L766)):*
> ```Smalltalk
> 				// This also would insert (for example) "fr" (French) after either "fre" or "fra" both French variants.
> 				// Unfortunately, this inserts "ru" (Russian) after "rub" (an African language), which isn't what's wanted.
> 				// So we end up comparing English names of both codes to see if the long one starts with the short one.
> ```

I don't see where in this code anything is "comparing English names"

---

*[src/BloomExe/Collection/CollectionSettings.cs, line 773 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1858#-KuQfYtZ3KwIN5E33BWs:-KuQfYtZ3KwIN5E33BWt:b-rjpql6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c348f37813eb80dc521ead5633adb951ed401c54/src/BloomExe/Collection/CollectionSettings.cs#L773)):*
> ```Smalltalk
> 						continue;
> 					var extra = culture.Split('-')[0]; // Generally insert corresponding language for longer culture
> 					if (extra == "zh")
> ```

This was in the original, but I don't see how the core language name, the first, always-there part, is called "extra".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1858)*

**Comment by gmartin7** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Collection/CollectionSettings.cs, line 766 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1858#-KuQfXXsF2_LxK5L-sqs:-KuQn0VH2inH1c0-d5vD:b-rmzwdw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c348f37813eb80dc521ead5633adb951ed401c54/src/BloomExe/Collection/CollectionSettings.cs#L766)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I don't see where in this code anything is "comparing English names"
</blockquote></details>

Oops. Forgot to change the comment.

---

*[src/BloomExe/Collection/CollectionSettings.cs, line 773 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1858#-KuQfYtZ3KwIN5E33BWs:-KuQnCFVgb75amuCjjtT:b7yan1m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c348f37813eb80dc521ead5633adb951ed401c54/src/BloomExe/Collection/CollectionSettings.cs#L773)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This was in the original, but I don't see how the core language name, the first, always-there part, is called "extra".
</blockquote></details>

renamed to 'fallback', which is already mentioned in the comments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1858)*

**Comment by hatton** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Collection/CollectionSettings.cs, line 766 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1858#-KuQfXXsF2_LxK5L-sqs:-KuR0SNjYggFvaTthRIe:bnq4khy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c348f37813eb80dc521ead5633adb951ed401c54/src/BloomExe/Collection/CollectionSettings.cs#L766)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Oops. Forgot to change the comment.
</blockquote></details>

I find all this "fallback" and the comment there about "rub" just confusing. There was a bug in the original; it assumed that the primary language name (which is not a "fallback") . Here's what BCP47 say:

langtag       = language
                 ["-" script]
                 ["-" region]
                 *("-" variant)
                 *("-" extension)
                 ["-" privateuse]

So the 2 or 3 characters before the dash are the *language* tag, full stop.

So now that you've fixed that bug, it actually is quite confusing to talk about the bug (the 'rub' sentence).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1858)*

**Comment by hatton** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Collection/CollectionSettings.cs, line 766 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1858#-KuQfXXsF2_LxK5L-sqs:-KuR1BSqwZQFJZxj5YXU:b3rqkf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c348f37813eb80dc521ead5633adb951ed401c54/src/BloomExe/Collection/CollectionSettings.cs#L766)):*
sorry sentence got cut off there:

> it assumed that the primary language name (which is not a "fallback")  was 2 characters, when it is often 3.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1858)*

**Comment by hatton** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Collection/CollectionSettings.cs, line 773 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1858#-KuQfYtZ3KwIN5E33BWs:-KuR1V6vTrpu6jvQUk6U:b-sa8pk5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c348f37813eb80dc521ead5633adb951ed401c54/src/BloomExe/Collection/CollectionSettings.cs#L773)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

renamed to 'fallback', which is already mentioned in the comments.
</blockquote></details>

Please name "language", since that's what the speck calls it, and "fallback" is a misunderstanding of what it is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1858)*

**Comment by gmartin7** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Collection/CollectionSettings.cs, line 766 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1858#-KuQfXXsF2_LxK5L-sqs:-KuUTeXk1JlGLeBzLaMS:bv59mvc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c348f37813eb80dc521ead5633adb951ed401c54/src/BloomExe/Collection/CollectionSettings.cs#L766)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

sorry sentence got cut off there:

> it assumed that the primary language name (which is not a "fallback")  was 2 characters, when it is often 3.

</blockquote></details>

Sounds good. I changed 'culture' to 'fullLangTag' and the misnamed 'fallback' to 'language'.

---

*[src/BloomExe/Collection/CollectionSettings.cs, line 773 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1858#-KuQfYtZ3KwIN5E33BWs:-KuUTbIog9zy66JIFMeh:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c348f37813eb80dc521ead5633adb951ed401c54/src/BloomExe/Collection/CollectionSettings.cs#L773)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Please name "language", since that's what the speck calls it, and "fallback" is a misunderstanding of what it is.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1858)*

**Comment by gmartin7** [comment]
Opening a new version of this on 3.9

**Pull request closed without merging**
