### PR TITLE
Reconnect any closed web sockets regularly (BL-12329)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/utils/WebSocketManager.ts` line 149 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917#-NXjoupdAY7fovaEI4ak:-NXjoupdAY7fovaEI4al:b8jkg3t) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c8b06064e00c1c64406083bba585040256e7f5c1/src/BloomBrowserUI/utils/WebSocketManager.ts#L149)):*
> ```XML
>                 // But note, we did not clear WebSocketManager.clientContextCallbacks[clientContext],
>                 // so we will keep the same callbacks.
>                 WebSocketManager.getOrCreateWebSocket(clientContext);
> ```

What would have if there were an exception in this method?
___
*[`src/BloomBrowserUI/utils/WebSocketManager.ts` line 155 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917#-NXjoiwJ5fdC4Gq-HOwR:-NXjoiwJ5fdC4Gq-HOwS:b-a9m850) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c8b06064e00c1c64406083bba585040256e7f5c1/src/BloomBrowserUI/utils/WebSocketManager.ts#L155)):*
> ```XML
>     }
> 
>     private static checkingForClose = false;
> ```

How a bout `startedClosedSockets()`
___
*[`src/BloomBrowserUI/utils/WebSocketManager.ts` line 157 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917#-NXjoe4e00b_UKxZnyUT:-NXjoe4e00b_UKxZnyUU:b-nqevtk) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c8b06064e00c1c64406083bba585040256e7f5c1/src/BloomBrowserUI/utils/WebSocketManager.ts#L157)):*
> ```XML
>     private static checkingForClose = false;
> 
>     private static checkForClosedSockets() {
> ```

How a bout `continuouslyCheckForClosedSockets()`

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[`src/BloomBrowserUI/utils/WebSocketManager.ts` line 149 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917#-NXjoupdAY7fovaEI4ak:-NXkYnIpAkdfzMlrFwv-:b6e97h) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c8b06064e00c1c64406083bba585040256e7f5c1/src/BloomBrowserUI/utils/WebSocketManager.ts#L149)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

What would have if there were an exception in this method?
</blockquote></details>

It would get reported as usual, I expect...logging and possibly a toast. However, the loop retrying every two seconds would be broken. I've fixed that.
It's conceivable that something will throw often enough to be annoying...but I'd like to find that out, if so, before we decide whether there are exceptions we can ignore.
___
*[`src/BloomBrowserUI/utils/WebSocketManager.ts` line 155 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917#-NXjoiwJ5fdC4Gq-HOwR:-NXkY24G0enD4jJ9VFQy:bnuj41k) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c8b06064e00c1c64406083bba585040256e7f5c1/src/BloomBrowserUI/utils/WebSocketManager.ts#L155)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

How a bout `startedClosedSockets()`
</blockquote></details>

I think I did better than that
___
*[`src/BloomBrowserUI/utils/WebSocketManager.ts` line 157 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917#-NXjoe4e00b_UKxZnyUT:-NXkYEh6CrVQm1lsOIcF:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c8b06064e00c1c64406083bba585040256e7f5c1/src/BloomBrowserUI/utils/WebSocketManager.ts#L157)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

How a bout `continuouslyCheckForClosedSockets()`
</blockquote></details>

Done.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/utils/WebSocketManager.ts` line 149 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917#-NXjoupdAY7fovaEI4ak:-NXky1qh9bqEdyTu0ZNM:b-kar3xp) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c8b06064e00c1c64406083bba585040256e7f5c1/src/BloomBrowserUI/utils/WebSocketManager.ts#L149)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It would get reported as usual, I expect...logging and possibly a toast. However, the loop retrying every two seconds would be broken. I've fixed that.
It's conceivable that something will throw often enough to be annoying...but I'd like to find that out, if so, before we decide whether there are exceptions we can ignore.
</blockquote></details>

Please add a comment saying what happens when there is an exception here. If you haven't already, please also actually try it. Thx.
___
*[`src/BloomBrowserUI/utils/WebSocketManager.ts` line 164 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917#-NXkxE348aV74GBpLrEV:-NXkxE348aV74GBpLrEW:b-7g2qzc) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/12f1d053ec6092433d7d916f9098d67d2bbfe9af/src/BloomBrowserUI/utils/WebSocketManager.ts#L164)):*
> ```XML
>         const looper = () => {
>             // Just in case something goes wrong with this iteration of reconnecting,
>             // we'd still like to keep trying., so do this first.
> ```

This comment isn't making it through my thick skull. If this has to do with `Reconnect` failing, can you spell that out? E.g. `We set the time then do one. If/when ReconnectClosedSockets() throws an exception, we ...`
___
*[`src/BloomBrowserUI/utils/WebSocketManager.ts` line 168 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917#-NXkxk4L8Kzmlnvzc4PG:-NXkxk4M48hCg796YOQQ:badmocn) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/12f1d053ec6092433d7d916f9098d67d2bbfe9af/src/BloomBrowserUI/utils/WebSocketManager.ts#L168)):*
> ```XML
>             this.ReconnectClosedSockets();
>         };
>         setTimeout(looper, 2000);
> ```

For a small price, you can remove the duplication of the `2000` by just calling `looper()`, but no problem if you prefer it this way.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[`src/BloomBrowserUI/utils/WebSocketManager.ts` line 149 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917#-NXjoupdAY7fovaEI4ak:-NXpckNs4Swvnb669EUY:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c8b06064e00c1c64406083bba585040256e7f5c1/src/BloomBrowserUI/utils/WebSocketManager.ts#L149)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Please add a comment saying what happens when there is an exception here. If you haven't already, please also actually try it. Thx.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/utils/WebSocketManager.ts` line 164 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917#-NXkxE348aV74GBpLrEV:-NXpcGWW3G6WZFBpxXwG:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/12f1d053ec6092433d7d916f9098d67d2bbfe9af/src/BloomBrowserUI/utils/WebSocketManager.ts#L164)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This comment isn't making it through my thick skull. If this has to do with `Reconnect` failing, can you spell that out? E.g. `We set the time then do one. If/when ReconnectClosedSockets() throws an exception, we ...`
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/utils/WebSocketManager.ts` line 168 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917#-NXkxk4L8Kzmlnvzc4PG:-NXpcllr8zyXyscYxGoF:b-virjuv) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/12f1d053ec6092433d7d916f9098d67d2bbfe9af/src/BloomBrowserUI/utils/WebSocketManager.ts#L168)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

For a small price, you can remove the duplication of the `2000` by just calling `looper()`, but no problem if you prefer it this way.
</blockquote></details>

I actually decided to make this one longer. See comment.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/utils/WebSocketManager.ts` line 149 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917#-NXjoupdAY7fovaEI4ak:-NXq9m2UCwDfapK7jVYw:bolujv) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c8b06064e00c1c64406083bba585040256e7f5c1/src/BloomBrowserUI/utils/WebSocketManager.ts#L149)):*
>     // (If this throws some exception, it will be reported as usual, and we will continue
    // to attempt reconnection of any sockets that need it at regular intervals.)

But the obvious question is, what is "normal"? Would it normal to get Dialog after dialog, every 2 seconds?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[`src/BloomBrowserUI/utils/WebSocketManager.ts` line 149 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917#-NXjoupdAY7fovaEI4ak:-NXqO9kf3miginNte39u:bd5psm6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c8b06064e00c1c64406083bba585040256e7f5c1/src/BloomBrowserUI/utils/WebSocketManager.ts#L149)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

>     // (If this throws some exception, it will be reported as usual, and we will continue
    // to attempt reconnection of any sockets that need it at regular intervals.)

But the obvious question is, what is "normal"? Would it normal to get Dialog after dialog, every 2 seconds?
</blockquote></details>

No. Javascript errors never produce dialogs. In Alpha builds they produce toasts, otherwise, they are just logged. And we already have code to suppress repetitions of the same toast. In theory you could get a different exception each time and have a lot of toasts, but that's true of quite a bit of code (e.g., the code that runs regularly to check what's on the clipboard). I'm not clear why we're more worried about it here. But I've tried to further clarify the comments.

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/utils/WebSocketManager.ts` line 164 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917#-NXkxE348aV74GBpLrEV:-NXqSdxK1SM5gyPJ9ucC:b-7pvwig) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/12f1d053ec6092433d7d916f9098d67d2bbfe9af/src/BloomBrowserUI/utils/WebSocketManager.ts#L164)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

great

**Review by hatton — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5917)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
