### PR TITLE
BL-4444 suppress internal Gecko errors

### PR DESCRIPTION
**Pull request by JohnThomson**
Attempts to suppress at least some errors
Gecko outputs to console and then handles.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1597)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Browser.cs, line 437 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1597#-Kfsqw1xzghrZTVKMYwP:-Kfsqw1xzghrZTVKMYwQ:b-o0qwyu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4fb9bd266caaeaa39515f00211f3d9705c42eae/src/BloomExe/Browser.cs#L437)):*
> ```Smalltalk
> 				return;
> 			// This is an attempt, based on the log in BL-4444, to eliminate JS errors
> 			// with stack traces that indicate they occurred in gecko's own source code.
> ```

This seems too broad to me. In this case, you've decided to swallow this error. But next time that error could be the key to tracking down a bug.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1597)*

**Comment by hatton** [comment]
I've added some comments to the youtrack issue. I'm thinking maybe we were to hasty to make this go away.

**Comment by andrew-polk** [comment]
Needs to be rebased on Version3.9 branch

**Comment by andrew-polk** [comment]
Closing for now as it has been a long time without merging and we don't seem to be getting complaints.

**Pull request closed without merging**
