### PR TITLE
Handle more complexities in locating translated xliff files

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1923)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/BloomFileLocator.cs, line 288 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1923#-KxhSuXL66ecWfnfhUYq:-KxhSuXL66ecWfnfhUYr:b-9ju2ok) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/94661886ce1b6d9491f5aa86006ea2826dee1261/src/BloomExe/BloomFileLocator.cs#L288)):*
> Second, books created from templates with description
> 		/// files carry copies of those description files.  Finding the corresponding translated xliff file in that
> 		/// scenario requires peeking inside the actual book's HTML to find it's original template name.

I don't understand this. Why do we care about created books? These descriptions show up when selecting the templates themselves but not when selecting a book created with one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1923)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/BloomFileLocator.cs, line 288 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1923#-KxhSuXL66ecWfnfhUYq:-KxhZ4gdj3vz9Av8AmBz:b-bugesw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/94661886ce1b6d9491f5aa86006ea2826dee1261/src/BloomExe/BloomFileLocator.cs#L288)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> Second, books created from templates with description
> 		/// files carry copies of those description files.  Finding the corresponding translated xliff file in that
> 		/// scenario requires peeking inside the actual book's HTML to find it's original template name.

I don't understand this. Why do we care about created books? These descriptions show up when selecting the templates themselves but not when selecting a book created with one.
</blockquote></details>

Created books historically carried the translated markdown files along with the English markdown ReadMe file.  When you initially select the file in the Collection pane, the properly translated version of the ReadMe would be displayed the same as if you were selecting the original template.
My code doesn't check the case of old books with copied markdown files, but the Bloom code in general doesn't try to display markdown properly either.  This situation may warrant another issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1923)*

**Comment by hatton** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/BloomFileLocator.cs, line 288 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1923#-KxhSuXL66ecWfnfhUYq:-Kxhcdz7bC8i5nStyWUA:bma7nb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/94661886ce1b6d9491f5aa86006ea2826dee1261/src/BloomExe/BloomFileLocator.cs#L288)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Created books historically carried the translated markdown files along with the English markdown ReadMe file.  When you initially select the file in the Collection pane, the properly translated version of the ReadMe would be displayed the same as if you were selecting the original template.
My code doesn't check the case of old books with copied markdown files, but the Bloom code in general doesn't try to display markdown properly either.  This situation may warrant another issue.
</blockquote></details>

Yah... we should talk about whether we actually want those readme-type-instructions to show on child books. It's not clear that we do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1923)*

**Comment by andrew-polk** [comment]
*[src/BloomExe/BloomFileLocator.cs, line 288 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1923#-KxhSuXL66ecWfnfhUYq:-KxhdkX_F0gitW-PDF8V:b-j48uwa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/94661886ce1b6d9491f5aa86006ea2826dee1261/src/BloomExe/BloomFileLocator.cs#L288)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Yah... we should talk about whether we actually want those readme-type-instructions to show on child books. It's not clear that we do.
</blockquote></details>

3.8 and 3.9 did not. 4.0 does. Seems like an unwanted side effect of something.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1923)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/BloomFileLocator.cs, line 288 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1923#-KxhSuXL66ecWfnfhUYq:-KxiKMeD7fcyv5XZRcSh:buuko9k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/94661886ce1b6d9491f5aa86006ea2826dee1261/src/BloomExe/BloomFileLocator.cs#L288)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

3.8 and 3.9 did not. 4.0 does. Seems like an unwanted side effect of something.
</blockquote></details>

The latest revision checks for template books before allowing the ReadMe files to be displayed on the collection tab.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1923)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/BloomFileLocator.cs, line 288 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1923#-KxhSuXL66ecWfnfhUYq:-KxiKiGi5Z8U2sIYHCit:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/94661886ce1b6d9491f5aa86006ea2826dee1261/src/BloomExe/BloomFileLocator.cs#L288)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

The latest revision checks for template books before allowing the ReadMe files to be displayed on the collection tab.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1923)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1923#-:-KxiLQN0I6w9Gr8C5GZ4:bnfp4nl)*

**Pull request merged**
