### PR TITLE
BL-9198 Copy from Comic source bubbles

### PR DESCRIPTION
**Pull request by gmartin7**
* actually allows copy to clipboard from ANY source bubble

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4072)

### CODE REVIEW

**Review by gmartin7 — COMMENTED** [review]
In the issue I ask if we should "toast" that we copied text to the clipboard...

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4072#-:-MM1CvAP-ObdFodprU7o:b-l1vdn)* status: 0 of 5 files reviewed, all discussions resolved

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4072)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.ts, line 193 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4072#-MM1I0dD1hibCc7shr9n:-MM1I0dD1hibCc7shr9o:bc7ngf5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0f0ce1ef7151391d6bb8acd1b7ec8f2a688e7373/src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.ts#L193)):*
> ```XML
>                         sourceElement
>                     );
>             }
> ```

As we discussed, we want to use a material-ui button.
___
*[src/BloomBrowserUI/react_components/icons/ContentCopyIcon.tsx, line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4072#-MM1Cq98Dz8xCeWERqrV:-MM1Cq98Dz8xCeWERqrW:b-eapx6a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0f0ce1ef7151391d6bb8acd1b7ec8f2a688e7373/src/BloomBrowserUI/react_components/icons/ContentCopyIcon.tsx#L13)):*
> ```XML
> );
> 
> export default ContentCopyIcon;
> ```

Why did we have to do this instead of using the icon from the icon package directly?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4072)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @gmartin7)

___
*[src/BloomBrowserUI/react_components/icons/ContentCopyIcon.tsx, line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4072#-MM1Cq98Dz8xCeWERqrV:-MM1RAU94MJ3yXA_l40U:bag1e5f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0f0ce1ef7151391d6bb8acd1b7ec8f2a688e7373/src/BloomBrowserUI/react_components/icons/ContentCopyIcon.tsx#L13)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Why did we have to do this instead of using the icon from the icon package directly?
</blockquote></details>

I don't believe this particular icon is in any of our packages.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4072)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomBrowserUI/react_components/icons/ContentCopyIcon.tsx, line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4072#-MM1Cq98Dz8xCeWERqrV:-MM1SX4P3QuVz3uEurk5:b-sqblgh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0f0ce1ef7151391d6bb8acd1b7ec8f2a688e7373/src/BloomBrowserUI/react_components/icons/ContentCopyIcon.tsx#L13)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I don't believe this particular icon is in any of our packages.
</blockquote></details>

I thought we used the material ui icon.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4072)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @gmartin7)

___
*[src/BloomBrowserUI/react_components/icons/ContentCopyIcon.tsx, line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4072#-MM1Cq98Dz8xCeWERqrV:-MM1TAiVC4uok8fNHfkz:b5oxrmc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0f0ce1ef7151391d6bb8acd1b7ec8f2a688e7373/src/BloomBrowserUI/react_components/icons/ContentCopyIcon.tsx#L13)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I thought we used the material ui icon.
</blockquote></details>

I don't know who www.materialui.co is. The official material-ui.com has a place to search official material-ui icons and what we want isn't there.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4072)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomBrowserUI/react_components/icons/ContentCopyIcon.tsx, line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4072#-MM1Cq98Dz8xCeWERqrV:-MM2MnnmErmQuGlo0mez:b-47qerb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0f0ce1ef7151391d6bb8acd1b7ec8f2a688e7373/src/BloomBrowserUI/react_components/icons/ContentCopyIcon.tsx#L13)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I don't know who www.materialui.co is. The official material-ui.com has a place to search official material-ui icons and what we want isn't there.
</blockquote></details>

I didn't realize I had pointed you at a non-official site.
So did you use that one? Or you got one from JH?
I can't find anything about license on materialui.co.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4072)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/react_components/icons/ContentCopyIcon.tsx, line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4072#-MM1Cq98Dz8xCeWERqrV:-MMHS1Yu8SOQKEvOipZx:b-57u240) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0f0ce1ef7151391d6bb8acd1b7ec8f2a688e7373/src/BloomBrowserUI/react_components/icons/ContentCopyIcon.tsx#L13)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I didn't realize I had pointed you at a non-official site.
So did you use that one? Or you got one from JH?
I can't find anything about license on materialui.co.
</blockquote></details>

I added a comment about where I got it from. The pt of origin seems to be India, for what it's worth.
___
*[src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.ts, line 193 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4072#-MM1I0dD1hibCc7shr9n:-MMHQA1O8eKaGQsht7Vd:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0f0ce1ef7151391d6bb8acd1b7ec8f2a688e7373/src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.ts#L193)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

As we discussed, we want to use a material-ui button.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4072)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
