### PR TITLE
BL-12451 Get WV2 to respond to Bloom's UI language

### PR DESCRIPTION
**Pull request by gmartin7**
* Sets an additional command line argument for WV2
* Unfortunately, users won't see the results of switching language in the
   browser (e.g. decimal separators) until the program is
   restarted.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6016)

### CODE REVIEW

**Comment by hatton** [comment]
What happens if the given language string is empty or bogus?

**Review by gmartin7 — COMMENTED** [review]
Updated to handle empty string... not sure what to do about "bogus"? That would mean Bloom's settings have been corrupted. I've tried to test with "odd" strings being fed into the WV2 browser for the 'accept-language' parameter. Results inconclusive. The problems I had been getting went away with a fresh build. This string comes from our own UI language dropdown.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6016#-:-N_oA74U0cdy5gk5L1AZ:baqw4sy)* status: 0 of 2 files reviewed, all discussions resolved

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6016)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomExe/WebView2Browser.cs` line 142 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6016#-N_oLkoJCQGH7WNxPPNr:-N_oLkoJCQGH7WNxPPNs:bar32i4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6f557767f737d24b6681b26541dd33bb0165104c/src/BloomExe/WebView2Browser.cs#L142)):*
> ```Smalltalk
> 			// Unfortunately, this setting cannot be changed "on the fly", so Bloom will need to be restarted before
> 			// a change in UI language will take effect at this level.
> 			// See https://github.com/MicrosoftEdge/WebView2Feedback/issues/3635 (which was just opened last week!)
> ```

Curious if you tried something like
```
webView2.CoreWebView2InitializationCompleted += webView_CoreWebView2InitializationCompleted;  

private void webView_CoreWebView2InitializationCompleted(object sender, Microsoft.Web.WebView2.Core.CoreWebView2InitializationCompletedEventArgs e)
{
    if (e.IsSuccess)
    {
        webView2.CoreWebView2.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.All);
        webView2.CoreWebView2.WebResourceRequested += CoreWebView2_WebResourceRequested;
    }
}

private void CoreWebView2_WebResourceRequested(object sender, CoreWebView2WebResourceRequestedEventArgs e)
{
    e.Request.Headers.SetHeader("Accept-Language", "en-US");
}
```
from 
https://github.com/MicrosoftEdge/WebView2Feedback/issues/833
___
*[`src/BloomExe/web/BloomServer.cs` line 1199 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6016#-N_oKZwn2iuEWOT-I8vf:-N_oKZwn2iuEWOT-I8vg:b8toah3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6f557767f737d24b6681b26541dd33bb0165104c/src/BloomExe/web/BloomServer.cs#L1199)):*
> ```Smalltalk
> 			return LocalizationManager.GetString("Errors.CannotConnectToBloomServer",
> 												 "Bloom was unable to start its own HTTP listener that it uses to talk to its embedded browser. If this happens even if you just restarted your computer, then ask someone to investigate if you have an aggressive firewall product installed, which may need to be uninstalled before you can use Bloom.");
> 		}
> ```

Doesn't this require a change in the .xlf?

Sigh. Then we have to deal with that causing Crowdin to lose  translations.
So either have to manually restore in the Crowdin interface or have to create a second string and mark the original as obsolete.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6016)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/WebView2Browser.cs` line 142 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6016#-N_oLkoJCQGH7WNxPPNr:-N_oZfrLCYyllUifpOR0:b-uu56gf) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6f557767f737d24b6681b26541dd33bb0165104c/src/BloomExe/WebView2Browser.cs#L142)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Curious if you tried something like
```
webView2.CoreWebView2InitializationCompleted += webView_CoreWebView2InitializationCompleted;  

private void webView_CoreWebView2InitializationCompleted(object sender, Microsoft.Web.WebView2.Core.CoreWebView2InitializationCompletedEventArgs e)
{
    if (e.IsSuccess)
    {
        webView2.CoreWebView2.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.All);
        webView2.CoreWebView2.WebResourceRequested += CoreWebView2_WebResourceRequested;
    }
}

private void CoreWebView2_WebResourceRequested(object sender, CoreWebView2WebResourceRequestedEventArgs e)
{
    e.Request.Headers.SetHeader("Accept-Language", "en-US");
}
```
from 
https://github.com/MicrosoftEdge/WebView2Feedback/issues/833
</blockquote></details>

Indeed I did. Didn't work. :(
___
*[`src/BloomExe/web/BloomServer.cs` line 1199 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6016#-N_oKZwn2iuEWOT-I8vf:-N_oZrUnEDVxdiP0TUn2:bdcrlf8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6f557767f737d24b6681b26541dd33bb0165104c/src/BloomExe/web/BloomServer.cs#L1199)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Doesn't this require a change in the .xlf?

Sigh. Then we have to deal with that causing Crowdin to lose  translations.
So either have to manually restore in the Crowdin interface or have to create a second string and mark the original as obsolete.
</blockquote></details>

Oh.
Right.
Or I could back out this change? <hopeful whimper>

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6016)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomExe/web/BloomServer.cs` line 1199 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6016#-N_oKZwn2iuEWOT-I8vf:-N_t5GQB7tuHHismGvqj:b-ikp706) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6f557767f737d24b6681b26541dd33bb0165104c/src/BloomExe/web/BloomServer.cs#L1199)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Reviewable removed my "hopeful whimper" in angle brackets! Probably thought it was HTML.
</blockquote></details>

I'm ok backing it out of this PR since it isn't really related.
Please create a card for 5.6 with something like, "More 'Firefox' cleanup" and description something like, "Search for 'Firefox' and clean up what should be cleaned up. Mostly comments, but at least one string."
Thanks.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6016)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/web/BloomServer.cs` line 1199 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6016#-N_oKZwn2iuEWOT-I8vf:-N_uWyiA9ttVRB6shNXA:b-by0gq0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6f557767f737d24b6681b26541dd33bb0165104c/src/BloomExe/web/BloomServer.cs#L1199)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm ok backing it out of this PR since it isn't really related.
Please create a card for 5.6 with something like, "More 'Firefox' cleanup" and description something like, "Search for 'Firefox' and clean up what should be cleaned up. Mostly comments, but at least one string."
Thanks.
</blockquote></details>

BL-12573 created in `5.6` board. Re-inserted "Firefox" for now...

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6016)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
