### PR TITLE
BL-5087 Add bulk upload capability

### PR DESCRIPTION
**Pull request by gmartin7**
This PR consists of 3 commits:
1 - Andrew's unsubmitted work for uploading Bible Storying Videos
2 - My work to get it creating pdfs and tagging with bookshelf name
3 - Making the process restartable
This is a command line addition to Bloom that I run from a 1 line .bat
file. Bloom needs to be called with "upload" verb, optional flag to
exclude audio files (--excludeAudio or -x), path of directory tree to
upload (e.g. K:\EnablingWriters).

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1892)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 2 of 6 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/BloomExe/Book/BookInfo.cs, line 320 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1892#-Kw_YM8fZd4BzYTCtGBf:-Kw_YM8fZd4BzYTCtGBg:bi88nrr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9c551bdba5c5cb3170ef014071c1767e9b86a93/src/BloomExe/Book/BookInfo.cs#L320)):*
> SetBookshelf

Should be "Bookshelf" or probably better, "Bookshelves" or probably better yet, for consistency, "BookshelfList"


There is a fair bit of duplicated code (from TopicsList). Can that be improved?

---

*[src/BloomExe/Book/BookInfo.cs, line 454 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1892#-Kw_YtUWy3IczIDswBdP:-Kw_YtUWy3IczIDswBdQ:b-2ikd8k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9c551bdba5c5cb3170ef014071c1767e9b86a93/src/BloomExe/Book/BookInfo.cs#L454)):*
> bookshelfs

"bookshelves" (if you're making other changes)

Worth extracting the duplicated code here?

---

*[src/BloomExe/CLI/UploadCommand.cs, line 20 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1892#-Kw_jQalYQym9cYD2QKX:-Kw_jQalYQym9cYD2QKY:b5xuu66) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9c551bdba5c5cb3170ef014071c1767e9b86a93/src/BloomExe/CLI/UploadCommand.cs#L20)):*
> then tear it down

Do we do this?

---

*[src/BloomExe/Publish/PublishView.cs, line 101 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1892#-Kw_jycK-nt7VGfVW7sY:-Kw_jycK-nt7VGfVW7sZ:bfzcm85) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9c551bdba5c5cb3170ef014071c1767e9b86a93/src/BloomExe/Publish/PublishView.cs#L101)):*
> ```Smalltalk
> 			_menusToolStrip.Renderer = new EditingView.FixedToolStripRenderer();
> 
> 			// As far as I can tell, this is not needed anymore, and its presence,
> ```

Pretty sure I made this change. Did you verify it?

---

*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 674 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1892#-Kw_mSnBxNR--8ahi8o_:-Kw_mSnBxNR--8ahi8oa:b-ust521) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9c551bdba5c5cb3170ef014071c1767e9b86a93/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L674)):*
> fileName

Is this really a file name? Seems like it is sometimes (or always?) a folder name.

---

*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 704 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1892#-Kw_jDRIgFzHU9oeR6xV:-Kw_jDRJM7MdkEYTu_5j:b-dch6dx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9c551bdba5c5cb3170ef014071c1767e9b86a93/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L704)):*
> ```Smalltalk
> 					// the autofac object (_scope in the ProjectContext) is used by autofac to create various objects, in particular, books.
> 					context = container.CreateProjectContext(collectionPath);
> 					Program.SetProjectContext(context);
> ```

I probably added this, but why is it needed now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1892)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1892)*

**Comment by gmartin7** [comment]
Review status: 7 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/BloomExe/Book/BookInfo.cs, line 320 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1892#-Kw_YM8fZd4BzYTCtGBf:-KwfZxod7PrXyuzpxyeG:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9c551bdba5c5cb3170ef014071c1767e9b86a93/src/BloomExe/Book/BookInfo.cs#L320)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> SetBookshelf

Should be "Bookshelf" or probably better, "Bookshelves" or probably better yet, for consistency, "BookshelfList"


There is a fair bit of duplicated code (from TopicsList). Can that be improved?
</blockquote></details>

Done.

---

*[src/BloomExe/Book/BookInfo.cs, line 454 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1892#-Kw_YtUWy3IczIDswBdP:-Kwf_-4OSfidIK2RhxMn:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9c551bdba5c5cb3170ef014071c1767e9b86a93/src/BloomExe/Book/BookInfo.cs#L454)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> bookshelfs

"bookshelves" (if you're making other changes)

Worth extracting the duplicated code here?
</blockquote></details>

Done.

---

*[src/BloomExe/CLI/UploadCommand.cs, line 20 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1892#-Kw_jQalYQym9cYD2QKX:-Kwf_K8dqV7edw1qOs-O:b1rig6z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9c551bdba5c5cb3170ef014071c1767e9b86a93/src/BloomExe/CLI/UploadCommand.cs#L20)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> then tear it down

Do we do this?
</blockquote></details>

You wrote it! ;)
I see a using() around the ApplicationContainer and I see you've set a Browser.XulRunnerShutdown event handler. That qualifies as tearing it down in my book.

---

*[src/BloomExe/Publish/PublishView.cs, line 101 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1892#-Kw_jycK-nt7VGfVW7sY:-KwfaAbhWnZW8tJfXgEf:bcdv6d6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9c551bdba5c5cb3170ef014071c1767e9b86a93/src/BloomExe/Publish/PublishView.cs#L101)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Pretty sure I made this change. Did you verify it?
</blockquote></details>

Yep, you did it. All I know is it works now! :)

---

*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 674 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1892#-Kw_mSnBxNR--8ahi8o_:-KwfcCdMs7zutHpWEotC:bo57ovx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9c551bdba5c5cb3170ef014071c1767e9b86a93/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L674)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> fileName

Is this really a file name? Seems like it is sometimes (or always?) a folder name.
</blockquote></details>

changed to 'lastFolderPart'

---

*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 704 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1892#-Kw_jDRIgFzHU9oeR6xV:-KwfcSo4WmdYO-jBFOb9:b-g2a1bq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9c551bdba5c5cb3170ef014071c1767e9b86a93/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L704)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I probably added this, but why is it needed now?
</blockquote></details>

Yes you did. Not sure, except that I know the code goes into this 'if' when changing to a new collection.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1892)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/PublishView.cs, line 104 at r4](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1892#-Kwfh9pXn6O-bvSjz6OY:-Kwfh9pXn6O-bvSjz6OZ:b-x8li6i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/000e788989a97e03f53b2efea8df21235ae4afa2/src/BloomExe/Publish/PublishView.cs#L104)):*
> ```Smalltalk
> 			// at least in this place in the code, causes errors when running command-line tools
> 			// like UploadCommand which needs a PublishView but must not have something fully initialized.
> 			//GeckoPreferences.Default["pdfjs.disabled"] = false;
> ```

This still makes me uneasy.

I'll add to the card that we need to test pdf display in Linux (where Adobe is not used).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1892)*

**Pull request merged**
