### PR TITLE
BL-5330 fix talking-book problem on new books

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2011)

### CODE REVIEW

**Comment by andrew-polk** [comment]
:lgtm:
Don't we want this to target 3.9?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2011#-:-L-hIUPkU9uGWCAypUs4:b-suhkje)*

**Comment by StephenMcConnel** [comment]
If the fix is safe and applicable to 3.9, I think we do.  I hadn't had much success reproducing the bug on 4.0, but if John reproduced it there, then this fix is needed there.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2011#-:-L-hSaQ2VtBn6JzGbuOE:bj04cwy)*

**Comment by andrew-polk** [comment]
According to the card, this issue was reported in 3.9.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2011#-:-L-hTdLDs4Z5wBjuT-rx:busqxc9)*

**Comment by JohnThomson** [comment]
Sorry, I intended to target 3.9. Fixed.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2011#-:-L-lI6W_Xv-m_qqjOHq9:bnci0um)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2011#-:-L-lMHu-jCWdsGX6El4m:bnfp4nl)*

**Pull request merged**
