### PR TITLE
Prevent double-click from editing TC book not checked out (BL-11865)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5585)

### CODE REVIEW

**Comment by hatton** [comment]
Great. Can you re-targeted to 5.3 please? Thanks.

**Review by StephenMcConnel — COMMENTED** [review]
I've never had luck retargeting an existing PR.  But I could redo the fix to target 5.3 initially.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5585#-:-NM5vxBREIOZOzmqpbj9:b-f2ufdo)* status: 0 of 1 files reviewed, all discussions resolved

**Review by StephenMcConnel — COMMENTED** [review]
OK, I think I've managed to retarget Version5.3 with github thinking it's the same PR.  I'm still not sure how all the git magic worked together although I know exactly what I did.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5585#-:-NM6B54u79beWJ0Q4r1P:bebxeei)* status: 0 of 1 files reviewed, all discussions resolved

**Review by hatton — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5585)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
