### PR TITLE
Add publish control which langs' narration audio to include (BL-10055)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/publish/ReaderPublish/PublishLanguagesGroup.tsx, line 73 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561#-McVsqFP3DvVpio07Qa7:-McVsqFP3DvVpio07Qa8:bg254u0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d10fbd460cdd052f82233aef84deb46a8f4930f/src/BloomBrowserUI/publish/ReaderPublish/PublishLanguagesGroup.tsx#L73)):*
> ```XML
>     return (
>         <div>
>             <LanguageSelectionSettingsGroup
> ```

So, as requested in the card, I generalized what we had for TextLanguages so that it could be re-used for both TextLanguages and Talking Book Languages.

But then I needed to add 3 callback functions to control the differing logics. (shouldBoxBeDisabled, shouldBoxBeChecked, and createUpdatedItem)

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/publish/ReaderPublish/PublishLanguagesGroup.tsx, line 73 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561#-McVsqFP3DvVpio07Qa7:-McVu_cS-C6ssrtLStv4:b-56lwzv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d10fbd460cdd052f82233aef84deb46a8f4930f/src/BloomBrowserUI/publish/ReaderPublish/PublishLanguagesGroup.tsx#L73)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

So, as requested in the card, I generalized what we had for TextLanguages so that it could be re-used for both TextLanguages and Talking Book Languages.

But then I needed to add 3 callback functions to control the differing logics. (shouldBoxBeDisabled, shouldBoxBeChecked, and createUpdatedItem)
</blockquote></details>

@hatton  see what you think

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/publish/ReaderPublish/PublishLanguagesGroup.tsx, line 73 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561#-McVsqFP3DvVpio07Qa7:-McW5OOPC-2cX7gYsH4d:b-k2iiwk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d10fbd460cdd052f82233aef84deb46a8f4930f/src/BloomBrowserUI/publish/ReaderPublish/PublishLanguagesGroup.tsx#L73)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

@hatton  see what you think
</blockquote></details>

I think  better way would be to have a single API call in which the server provides this whole control with all the information it is going to need? Even broader would make sense -- a single call to get / post all BloomPub Publish settings.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomBrowserUI/publish/ReaderPublish/LanguageSelectionSettingsGroup.tsx, line 33 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561#-McWBzdI6JPNir-ohLV8:-McWBzdI6JPNir-ohLV9:b-ksnqbo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d10fbd460cdd052f82233aef84deb46a8f4930f/src/BloomBrowserUI/publish/ReaderPublish/LanguageSelectionSettingsGroup.tsx#L33)):*
> ```
>                         // a complete regeneration of the page.
> ```
As we discussed, I don't think this is true anymore.
___
*[src/BloomExe/Publish/Android/NameRec.cs, line 3 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561#-McVvKEa8yNC9ZDpWwsp:-McVvKEa8yNC9ZDpWwsq:b-eauafj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d10fbd460cdd052f82233aef84deb46a8f4930f/src/BloomExe/Publish/Android/NameRec.cs#L3)):*
> ```
> Bloom.Publish.Android
> ```
I think this wants to be in Bloom.Publish.
(I'm pretty sure we will use it when the upload screen becomes a react control)
___
*[src/BloomExe/Publish/Android/NameRec.cs, line 5 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561#-McVvIRc-c8yKIbvyS6m:-McVvIRc-c8yKIbvyS6n:b5n7wh4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d10fbd460cdd052f82233aef84deb46a8f4930f/src/BloomExe/Publish/Android/NameRec.cs#L5)):*
> ```
> PublishLanguageGroup
> ```
PublishLanguagesGroup
___
*[src/BloomExe/Publish/Android/NameRec.cs, line 6 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561#-McVugZL3l2u2MzpE3vR:-McVugZL3l2u2MzpE3vS:bfsjcck) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d10fbd460cdd052f82233aef84deb46a8f4930f/src/BloomExe/Publish/Android/NameRec.cs#L6)):*
> ```
> NameRec
> ```
I know you inherited the name, but it wants a more descriptive name (and comment).
Is it a LanguagePublicationSettings?

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561)* status: 5 of 10 files reviewed, 5 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomBrowserUI/publish/ReaderPublish/LanguageSelectionSettingsGroup.tsx, line 33 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561#-McWBzdI6JPNir-ohLV8:-MckSKvf2rfQpmgxe3Jn:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d10fbd460cdd052f82233aef84deb46a8f4930f/src/BloomBrowserUI/publish/ReaderPublish/LanguageSelectionSettingsGroup.tsx#L33)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
>                         // a complete regeneration of the page.
> ```
As we discussed, I don't think this is true anymore.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/publish/ReaderPublish/PublishLanguagesGroup.tsx, line 73 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561#-McVsqFP3DvVpio07Qa7:-MckSNvx8G5uKOVf8vF4:b-16zj5p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d10fbd460cdd052f82233aef84deb46a8f4930f/src/BloomBrowserUI/publish/ReaderPublish/PublishLanguagesGroup.tsx#L73)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think  better way would be to have a single API call in which the server provides this whole control with all the information it is going to need? Even broader would make sense -- a single call to get / post all BloomPub Publish settings. 
</blockquote></details>

1) In the morning meeting we discussed this applying at the level of the language settings (rather than the entire BloomPub publish settings), but...
2) The vote was for the API call to post only the language updated, rather than post an object (which would contain the state of all languages) similar to what we received from the get.

So, no change being made for this regarding the Bloom API.
___
*[src/BloomExe/Publish/Android/NameRec.cs, line 3 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561#-McVvKEa8yNC9ZDpWwsp:-MckXjon4b6L8IP12Pj4:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d10fbd460cdd052f82233aef84deb46a8f4930f/src/BloomExe/Publish/Android/NameRec.cs#L3)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Bloom.Publish.Android
> ```
I think this wants to be in Bloom.Publish.
(I'm pretty sure we will use it when the upload screen becomes a react control)
</blockquote></details>

Done.
___
*[src/BloomExe/Publish/Android/NameRec.cs, line 5 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561#-McVvIRc-c8yKIbvyS6m:-MckU_9u9Y7T6Hv_WCQf:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d10fbd460cdd052f82233aef84deb46a8f4930f/src/BloomExe/Publish/Android/NameRec.cs#L5)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> PublishLanguageGroup
> ```
PublishLanguagesGroup
</blockquote></details>

Done.
___
*[src/BloomExe/Publish/Android/NameRec.cs, line 6 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561#-McVugZL3l2u2MzpE3vR:-MckVnmt2CGxCIdnrpJT:bchwtcj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d10fbd460cdd052f82233aef84deb46a8f4930f/src/BloomExe/Publish/Android/NameRec.cs#L6)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> NameRec
> ```
I know you inherited the name, but it wants a more descriptive name (and comment).
Is it a LanguagePublicationSettings?
</blockquote></details>

Well, only the last 2 are settings / options. In particular, "name" and "complete" aren't really settings... they're strings that need to be rendered on the UI. So....  maybe Info instead of Settings?

I preferred Publish (or Publishing) over Publication.

So, LanguagePublishInfo?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/publish/ReaderPublish/PublishLanguagesGroup.tsx, line 88 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561#-Mckx_HVArPZgy0zOEVg:-Mckx_HVArPZgy0zOEVh:b5xkllo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c7fbaa996dc506eccd27759f47fe6dad509176af/src/BloomBrowserUI/publish/ReaderPublish/PublishLanguagesGroup.tsx#L88)):*
> ```
> complete
> ```
How about `showIncompleteTranslationMessage` (or something shorter if you can come up with it) and reversing the logic?
`showIncompleteNote`?

And the comment is a bit confusing.
How about something like 
`// Never show for audio`
or
`// Only show for text checkboxes`
?

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/publish/ReaderPublish/PublishLanguagesGroup.tsx, line 88 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561#-Mckx_HVArPZgy0zOEVg:-McoRiRFD4LCO58EOlQM:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c7fbaa996dc506eccd27759f47fe6dad509176af/src/BloomBrowserUI/publish/ReaderPublish/PublishLanguagesGroup.tsx#L88)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> complete
> ```
How about `showIncompleteTranslationMessage` (or something shorter if you can come up with it) and reversing the logic?
`showIncompleteNote`?

And the comment is a bit confusing.
How about something like 
`// Never show for audio`
or
`// Only show for text checkboxes`
?
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Pull request merged**
