### PR TITLE
BL-9976 Add pics and video as options for comic "bubbles" over pictures

### PR DESCRIPTION
**Pull request by gmartin7**
This is 3 commits:
* 1st adds the comicTool shapes to drag (still need updated icons)
* 2nd just refactors/renames mostly from 'text over picture' to 'over picture 
   element' wording
* 3rd a lot of refactoring and the guts of getting video and pics over pics to work

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586)* status: all files reviewed, 7 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 27 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586#-MeBiuDV--Z9WddOibdH:-MeBiuDV--Z9WddOibdI:b-odziuv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3eab380b5c80bc1cf406e63641d432132253b53e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L27)):*
> ```XML
> // We could rename this class to "bloom-overPictureElement", but that would involve a migration.
> // For now we're keeping this name for backwards-compatibility, even though now the element could be
> // a video or even another picture.
> ```

Not just a migration...even if we implemented that, older versions of Bloom would not be able to handle files with the new class name.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 180 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586#-MeBk-96E0Xg4du3ygDy:-MeBk-96E0Xg4du3ygDz:b-v7mpvd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3eab380b5c80bc1cf406e63641d432132253b53e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L180)):*
> ```XML
>             )
>         ).filter(el => !el.parentElement!.classList.contains("box-header-off"));
>         if (focusableDivs.length === 0) {
> ```

It's not obvious why you want to include videos (and then pictures) only if there are no text bubbles. I think a comment would be helpful.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 404 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586#-MeBlvIa0-OJ8Eoj4m1j:-MeBlvIa0-OJ8Eoj4m1k:bo6fmqe) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3eab380b5c80bc1cf406e63641d432132253b53e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L404)):*
> ```XML
>             element.addEventListener(
>                 "focusin",
>                 BubbleManager.onFocusSetActiveElement
> ```

This feels like something we'd want on videos and pictures, even if there are also text bubbles? Or can they never get focus unless there are none?
(OTOH, I recall seeing code to focus the last thing in getAllVisibleFocusableDivs...that probably does want the last bloom-editable.  Yuck. Maybe it needs an argument to say what to do about non-text bubbles?
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 503 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586#-MeC-KoSD4xNS0rtRh8o:-MeC-KoTEywsOdGvN8Hg:b-nh82k6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3eab380b5c80bc1cf406e63641d432132253b53e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L503)):*
> ```XML
>             Array.from(focusedElement.classList).some(el =>
>                 BubbleManager.focusableClasses.includes(el)
>             )
> ```

I'm not clear on the point of this. Surely we only attached the listeners to elements we can focus?
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 1355 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586#-MeC0mxi3Ss8CgPQ7DgG:-MeC0mxi3Ss8CgPQ7DgH:b-cygvsl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3eab380b5c80bc1cf406e63641d432132253b53e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L1355)):*
> ```XML
>             document.getElementsByClassName(kTextOverPictureClass)
>         ).forEach(container => {
>             const focusables = this.getAllVisibleFocusableDivs(
> ```

Given that this function only sometimes includes videos and/or pictures, are you sure it will remove it everywhere we need?
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 2065 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586#-MeC2nAi3LCklUmANJZk:-MeC2nAi3LCklUmANJZl:b-o120l6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/af5f8d83df12a1bad20b0f4f126e04f1544ddfd8/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2065)):*
> ```XML
>             thisTOPBox.find(".bloom-editable").click(function(e) {
>                 this.focus();
>             });
> ```

I suppose you concluded this was redundant?
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 2591 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586#-MeC303tAU48Bg4vU-3B:-MeC303tAU48Bg4vU-3C:b-vtrgy3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3eab380b5c80bc1cf406e63641d432132253b53e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2591)):*
> ```XML
>         return secondTry
>             ? (secondTry as HTMLElement) // element was inside of a image over image
>             : (firstTry as HTMLElement); // element was just inside of a top level imageContainer
> ```

Is it certain that three layers can't happen?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586)* status: all files reviewed, 7 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 27 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586#-MeBiuDV--Z9WddOibdH:-MeCCWu76dQSUGXlTVeG:bq1yu4j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3eab380b5c80bc1cf406e63641d432132253b53e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L27)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Not just a migration...even if we implemented that, older versions of Bloom would not be able to handle files with the new class name.
</blockquote></details>

Right. I knew it was complicated. I guess it's more complicated than I thought! :(
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 180 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586#-MeBk-96E0Xg4du3ygDy:-MeCE5998A7zNZ759okS:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3eab380b5c80bc1cf406e63641d432132253b53e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L180)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's not obvious why you want to include videos (and then pictures) only if there are no text bubbles. I think a comment would be helpful.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 404 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586#-MeBlvIa0-OJ8Eoj4m1j:-MeCEK8Y894d7fX75sMv:b-spt75) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3eab380b5c80bc1cf406e63641d432132253b53e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L404)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This feels like something we'd want on videos and pictures, even if there are also text bubbles? Or can they never get focus unless there are none?
(OTOH, I recall seeing code to focus the last thing in getAllVisibleFocusableDivs...that probably does want the last bloom-editable.  Yuck. Maybe it needs an argument to say what to do about non-text bubbles?
</blockquote></details>

I've started using the term "focusableDiv" to include all 3 types: text, video, and image. So getAllVisibleFocusableDivs() above gets all of them (but there'll only be one type per "container"). So I AM adding the "focusin" to each kind. But the next conditional only applies to bloom-editables, because I doubt it makes sense to add ckeditor to an image or video.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 503 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586#-MeC-KoSD4xNS0rtRh8o:-MeCFGE69YE2NhQW1qjx:bjvh30z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3eab380b5c80bc1cf406e63641d432132253b53e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L503)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm not clear on the point of this. Surely we only attached the listeners to elements we can focus?
</blockquote></details>

Generally, yes, but there IS the case of the "somethingElseToFocus" that we put a focusin on. We use it to deselect all bubbles if they click on an imageContainer, but not on a bubble.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 1355 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586#-MeC0mxi3Ss8CgPQ7DgG:-MeCG1CI5uAgF9FH58wF:bb77ucv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3eab380b5c80bc1cf406e63641d432132253b53e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L1355)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Given that this function only sometimes includes videos and/or pictures, are you sure it will remove it everywhere we need?
</blockquote></details>

Yep.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 2065 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586#-MeC2nAi3LCklUmANJZk:-MeCGClm31NoAfqE8D_n:baq5jbb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/af5f8d83df12a1bad20b0f4f126e04f1544ddfd8/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2065)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I suppose you concluded this was redundant?
</blockquote></details>

Yep. I tried at one point generalizing the obsolete bloom-editable-only code, but it made no difference. If an element can handle a click event, it will focus if you click on it. If it can't handle a click event, it won't focus even if you do this. That was what the tabindex did for the image on image case, it made it handle a click by focusing the element... automatically.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 2591 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586#-MeC303tAU48Bg4vU-3B:-MeCGynh414pvl52vXYs:b-i3b2zv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3eab380b5c80bc1cf406e63641d432132253b53e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2591)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is it certain that three layers can't happen?
</blockquote></details>

If we make sure this method works, it can't. :)

**Review by JohnThomson — CHANGES_REQUESTED** [review]
Looking good. Couple of minor further suggestions.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586#-:-MeCL-EsCVNXK9qQlDsI:b-cfsk74)* status: all files reviewed, 3 unresolved discussions (waiting on @gmartin7 and @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 404 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586#-MeBlvIa0-OJ8Eoj4m1j:-MeCJv0X7v_oxxtZqpcq:b-101og0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3eab380b5c80bc1cf406e63641d432132253b53e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L404)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I've started using the term "focusableDiv" to include all 3 types: text, video, and image. So getAllVisibleFocusableDivs() above gets all of them (but there'll only be one type per "container"). So I AM adding the "focusin" to each kind. But the next conditional only applies to bloom-editables, because I doubt it makes sense to add ckeditor to an image or video.
</blockquote></details>

Where I got lost is I was thinking of the overPictureContainerElement as the imageContainer that holds (indirectly) a whole collection of bubbles, whereas it is actually the (previously TOP) element that represents ONE bubble. Both are plausible as things that contain bubble data. If it confused me it will confuse someone else, so it might be worth one more comment to make it clear that overPictureContainer must be the outer element of ONE SINGLE bubble (or whatever our new generic term is).
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 503 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586#-MeC-KoSD4xNS0rtRh8o:-MeCKo1a7FSTdc-hEsj3:bmz6scx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3eab380b5c80bc1cf406e63641d432132253b53e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L503)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Generally, yes, but there IS the case of the "somethingElseToFocus" that we put a focusin on. We use it to deselect all bubbles if they click on an imageContainer, but not on a bubble.
</blockquote></details>

Let's get that into a comment

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 404 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586#-MeBlvIa0-OJ8Eoj4m1j:-MeCN0U5CFpEYwNeurKc:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3eab380b5c80bc1cf406e63641d432132253b53e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L404)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Where I got lost is I was thinking of the overPictureContainerElement as the imageContainer that holds (indirectly) a whole collection of bubbles, whereas it is actually the (previously TOP) element that represents ONE bubble. Both are plausible as things that contain bubble data. If it confused me it will confuse someone else, so it might be worth one more comment to make it clear that overPictureContainer must be the outer element of ONE SINGLE bubble (or whatever our new generic term is).
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 503 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586#-MeC-KoSD4xNS0rtRh8o:-MeCNrOY3XD6rG8Q-y6S:br81bcd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3eab380b5c80bc1cf406e63641d432132253b53e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L503)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Let's get that into a comment
</blockquote></details>

As I was adding the comment... I realized that "somethingElseToFocus" is bloom-editable too. I may need to look at this again Monday.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 503 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586#-MeC-KoSD4xNS0rtRh8o:-MeRKq_NCP0IzNqg10Df:b-5o2wi2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3eab380b5c80bc1cf406e63641d432132253b53e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L503)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

As I was adding the comment... I realized that "somethingElseToFocus" is bloom-editable too. I may need to look at this again Monday.
</blockquote></details>

Removed that complicated code. I needed to make a "tweak" to the "somethingElseToFocus" code, so that clicking on the main picture (but not on an overPicture element) would disable the comic tool correctly (set active element to `undefined`).

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
