### PR TITLE
Fix BL-13387 Prevent double clicking image buttons

### PR DESCRIPTION
**Pull request by hatton**
The minimal fix here is just the one in bloomImages.ts.
However, looking at the rest of the code, it seems we were needlessly doing dangerous things to simulate synchronous behavior when it wasn't needed, so I removed that too.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6469)

### CODE REVIEW

**Comment by hatton** [comment]
Reviewers: Note that I removed some apparently needless and dangerous code that was attempting to delay saving the image until the Browser had loaded it. I couldn't figure out what this would be.  So I removed it.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6469)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/BloomExe/Edit/PageEditingModel.cs` line 82 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6469#-NxEsKos1KvsA7kto_Ms:-NxEsKos1KvsA7kto_Mt:b-k5asi4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cb14f5a0a3e47cd8e63caa182c6b8046d5342bc6/src/BloomExe/Edit/PageEditingModel.cs#L82)):*
> ```Smalltalk
>             messageBundle.creator = imageInfo.Metadata.Creator ?? "";
>             messageBundle.license = imageInfo.Metadata.License?.ToString() ?? "";
>             webSocketServer.SendBundle("edit", "changeImage", messageBundle);
> ```

After this method returns, the calling code in EditingModel saves the page. I think we need some guarantee that sending this bundle has updated the page before we save it, unless we can make a more radical change like initiating the save from the changeImage handler.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6469)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/Edit/PageEditingModel.cs` line 82 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6469#-NxEsKos1KvsA7kto_Ms:-NxF9sbg7ECrNHpTpE0u:bf6mk50) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cb14f5a0a3e47cd8e63caa182c6b8046d5342bc6/src/BloomExe/Edit/PageEditingModel.cs#L82)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

After this method returns, the calling code in EditingModel saves the page. I think we need some guarantee that sending this bundle has updated the page before we save it, unless we can make a more radical change like initiating the save from the changeImage handler.
</blockquote></details>

Thanks. Changed to use `RunJavascriptAsync()` to remove question around whether the websocket msg would be handled before the subsequent  `RunJavascriptAsync()` of the Save

**Review by JohnThomson — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6469)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[`src/BloomExe/Edit/PageEditingModel.cs` line 91 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6469#-NxNt4XS9dE4j3c-j-e6:-NxNt4XS9dE4j3c-j-e7:b3yhm9c) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c543871de98d1cc23d4b226da51dc695b8f1600b/src/BloomExe/Edit/PageEditingModel.cs#L91)):*
> ```Smalltalk
>             browser.RunJavascriptAsync(
>                 $"editTabBundle.getEditablePageBundleExports().changeImage({s})"
>             );
> ```

I've started putting in the pragma to turn off the warning for running async methods without await, in cases like this where it's been thought through carefully.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6469)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Edit/PageEditingModel.cs` line 91 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6469#-NxNt4XS9dE4j3c-j-e6:-NxO1Ml0Ewn0L6aa2hhz:bkx5cuf) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c543871de98d1cc23d4b226da51dc695b8f1600b/src/BloomExe/Edit/PageEditingModel.cs#L91)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I've started putting in the pragma to turn off the warning for running async methods without await, in cases like this where it's been thought through carefully.
</blockquote></details>

in my version of the code, it returns`Task`, and I don't get any warning. I think I'll go ahead and merge and we'll hide this warning eventually if my version is just behind somehow.

**Pull request merged**
