### PR TITLE
[4.1]BL-5441 BL-5442 Paste Image Credits

### PR DESCRIPTION
**Pull request by gmartin7**
* add ndash separator
* ignore placeholder1.png, placeholder2.png, etc.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2162)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/web/controllers/ImageApi.cs, line 130 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2162#-L4lhP1Gj476EiUDk7m9:-L4lhP1Gj476EiUDk7mA:b-7dir1v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7e90d1723af7c4bdb16a185e9e57d2e48236c64a/src/BloomExe/web/controllers/ImageApi.cs#L130)):*
> Public for testing

Not a big deal, but I think we typically make something internal if it is just being exposed for testing.

---

*[src/BloomExe/web/controllers/ImageApi.cs, line 178 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2162#-L4li73Rs13arJI4sOmq:-L4li73Rs13arJI4sOmr:b-7owdui) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7e90d1723af7c4bdb16a185e9e57d2e48236c64a/src/BloomExe/web/controllers/ImageApi.cs#L178)):*
> ```Smalltalk
> 			sb.Append(pages[0]);
> 			int lastPage;
> 			IsInt(pages[0], out lastPage);
> ```

Is there a reason not to use Int32.TryParse?

---

*[src/BloomExe/web/controllers/ImageApi.cs, line 178 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2162#-L4ljgc5oKbJe9GFoIRR:-L4ljgc5oKbJe9GFoIRS:b-q6zen9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7e90d1723af7c4bdb16a185e9e57d2e48236c64a/src/BloomExe/web/controllers/ImageApi.cs#L178)):*
> lastPage

Should/could this be `previousPage`?

---

*[src/BloomExe/web/controllers/ImageApi.cs, line 222 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2162#-L4ljIlkvS2ufLKh346P:-L4ljIlkvS2ufLKh346Q:b-2e2qtw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7e90d1723af7c4bdb16a185e9e57d2e48236c64a/src/BloomExe/web/controllers/ImageApi.cs#L222)):*
> ```Smalltalk
> 		}
> 
> 		private static bool IsIncrementOf(int lastPage, string newPage)
> ```

This method signature is really confusing me.

Would `AreAdjacentPages(int page, string nextPage)` be accurate?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2162)*

**Comment by gmartin7** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/web/controllers/ImageApi.cs, line 130 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2162#-L4lhP1Gj476EiUDk7m9:-L4mRtpcchpF2vfgxk1w:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7e90d1723af7c4bdb16a185e9e57d2e48236c64a/src/BloomExe/web/controllers/ImageApi.cs#L130)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> Public for testing

Not a big deal, but I think we typically make something internal if it is just being exposed for testing.
</blockquote></details>

Done.

---

*[src/BloomExe/web/controllers/ImageApi.cs, line 178 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2162#-L4li73Rs13arJI4sOmq:-L4mTdXQ65G0uAbH58QD:b-wte9b3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7e90d1723af7c4bdb16a185e9e57d2e48236c64a/src/BloomExe/web/controllers/ImageApi.cs#L178)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is there a reason not to use Int32.TryParse?
</blockquote></details>

Mostly I forgot. But now that I remember that exists, I also have to modify some stuff because the out result of mine was obviously not an increment of any other page number (-1).

---

*[src/BloomExe/web/controllers/ImageApi.cs, line 178 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2162#-L4ljgc5oKbJe9GFoIRR:-L4mRy6R59Z3MDGtRg47:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7e90d1723af7c4bdb16a185e9e57d2e48236c64a/src/BloomExe/web/controllers/ImageApi.cs#L178)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> lastPage

Should/could this be `previousPage`?
</blockquote></details>

Done.

---

*[src/BloomExe/web/controllers/ImageApi.cs, line 222 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2162#-L4ljIlkvS2ufLKh346P:-L4mS43a2ft4my748bQB:b-rutrdv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7e90d1723af7c4bdb16a185e9e57d2e48236c64a/src/BloomExe/web/controllers/ImageApi.cs#L222)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This method signature is really confusing me.

Would `AreAdjacentPages(int page, string nextPage)` be accurate?
</blockquote></details>

Almost. Xmatter pages like Inside Back Cover might be adjacent, but not an incremental number from the previous page. How about NewPageShouldBeGroupedWithPreviousPage?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2162)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/web/controllers/ImageApi.cs, line 222 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2162#-L4ljIlkvS2ufLKh346P:-L4q9bcl64yIOsaeSKRT:b-xsuxsy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7e90d1723af7c4bdb16a185e9e57d2e48236c64a/src/BloomExe/web/controllers/ImageApi.cs#L222)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Almost. Xmatter pages like Inside Back Cover might be adjacent, but not an incremental number from the previous page. How about NewPageShouldBeGroupedWithPreviousPage?
</blockquote></details>

New page makes me think we just created something. 
Let's go with PageShouldBeGroupedWithPreviousPage(int prevPage, string page), then go ahead and merge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2162)*

**Comment by gmartin7** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/web/controllers/ImageApi.cs, line 222 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2162#-L4ljIlkvS2ufLKh346P:-L4qS1RhZDhgBDEk9YJ4:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7e90d1723af7c4bdb16a185e9e57d2e48236c64a/src/BloomExe/web/controllers/ImageApi.cs#L222)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

New page makes me think we just created something. 
Let's go with PageShouldBeGroupedWithPreviousPage(int prevPage, string page), then go ahead and merge.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2162)*

**Pull request merged**
