### PR TITLE
Bl 2908 talking book accordion

### PR DESCRIPTION
**Pull request by JohnThomson**
[Review on Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/884)

### CODE REVIEW

**Comment by hatton** [comment]
Reviewed 3 of 12 files at r1, 31 of 33 files at r2.
Review status: 28 of 30 files reviewed at latest revision, 12 unresolved discussions.

---

_[src/BloomBrowserUI/audio/audioRecording.ts, line 292 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3u6MRLP-f9ojCFp2Qx:-K3u6MRLP-f9ojCFp2Qy:-1596803294) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomBrowserUI/audio/audioRecording.ts#L292)):_
Since you're using Typescript... you can use => instead of function() {}.  Not something you  need to change, just a more readable approach for the future.

---

_[src/BloomBrowserUI/bookEdit/accordion/Accordion.htm, line 28 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3u7AYVGGuf1fPc7ILo:-K3u7AYVGGuf1fPc7ILp:876542708) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomBrowserUI/bookEdit/accordion/Accordion.htm#L28)):_
Is there a currently (or imminently) a use for audio outside of talkingBook? If not, shall we put all of these files under talkingBook?

---

_[src/BloomBrowserUI/bookEdit/accordion/accordion.js, line 32 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3u836hpDVuqLh2Wtoa:-K3u836hpDVuqLh2Wtob:-318575015) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomBrowserUI/bookEdit/accordion/accordion.js#L32)):_
I know you're just extending what's already there, but... a tab-delimited parameter string? Odd.

---

_[src/BloomBrowserUI/bookEdit/accordion/talkingBook.ts, line 9 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3u9N5jQK3QkTh6VRKX:-K3u9N5jQK3QkTh6VRKY:283008345) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomBrowserUI/bookEdit/accordion/talkingBook.ts#L9)):_
This is surprising to me. There is no function name here, nor comment, to tell me what's going on. But looking at the code I figured I was looking at something that had to do with showing and hiding things. But then this actually starts the recording (or is labeled that way in any case). Wouldn't recording be started by a button?

---

_[src/BloomBrowserUI/bookEdit/accordion/talkingBook/talkingBook.jade, line 5 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3uA8CLfVoicE1DKgM9:-K3uA8CMaUXDSfs1XEDs:1196100548) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomBrowserUI/bookEdit/accordion/talkingBook/talkingBook.jade#L5)):_
Maybe I'll see this later, but for now, I'm wondering What is markuptype, and why is one of the types '3' instead of "markdown" or "html"?

---

_[src/BloomBrowserUI/bookEdit/accordion/talkingBook/talkingBook.ts, line 13 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3uBw-3aGOVAJsm8fxu:-K3uBw-3aGOVAJsm8fxv:24727127) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomBrowserUI/bookEdit/accordion/talkingBook/talkingBook.ts#L13)):_
Apologies if you see this comment twice... it seems my first one was lost.

Does recordAudio() really record audio? It doesn't seem like recording and hiding are the two states. I would have thought showing and hiding were the two states.

---

_[src/BloomBrowserUI/bookEdit/js/readerTools.js, line 110 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3uCRcxHpk68--HwBuY:-K3uCRcxHpk68--HwBuZ:1100761838) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomBrowserUI/bookEdit/js/readerTools.js#L110)):_
Really initializing a Reader (book) here? Or just a Reader *tool*?

---

_[src/BloomBrowserUI/bookEdit/js/readerTools.ts, line 184 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3uB3Im3HVP56IrjCLm:-K3uB3Im3HVP56IrjCLn:1045430919) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomBrowserUI/bookEdit/js/readerTools.ts#L184)):_
This doesn't appear to do what its name says. I appears to initialize a Leveled Reader Tool, not a Leveled Reader. The old name had the unfortunate abbreviation, but at least it had a T for Tool :-)

---

_[src/BloomBrowserUI/bookEdit/js/readerTools.ts, line 350 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3uBXadCYBEnRMlM2lD:-K3uBXadCYBEnRMlM2lE:-887004019) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomBrowserUI/bookEdit/js/readerTools.ts#L350)):_
Same as above comment... this panel is not a reader. It is a tool the reader here is the book you're editing.

---

_[src/BloomExe/BloomExe.csproj, line 224 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3uBhpQgzUm0njayNxf:-K3uBhpQgzUm0njayNxg:-1657563422) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomExe/BloomExe.csproj#L224)):_
--> Accordion.cs  ?

---

_[src/BloomExe/Edit/AccordionTool.cs, line 7 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3uAOM-WZcMYoLppa16:-K3uAOM-WZcMYoLppa17:1438157338) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomExe/Edit/AccordionTool.cs#L7)):_
I don't think of Accordion as a Tool. Rather, as a UI container that holds tools. 

---

_[src/BloomExe/Edit/EditingModel.cs, line 61 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3uCkXSjNM3esz_qjew:-K3uCkXSjNM3esz_qjex:-464663208) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomExe/Edit/EditingModel.cs#L61)):_
I thought it very unfortunate when we allowed this model and view to get intimate knowledge of the reader tools. Now's the time to fix that mistake. Rather than having this model acquiring knowledge of each new tool, we need a bit of architecture here. Nothing fancy, doesn't need to have a configuration file or even necessarily make use of dependency injection. But some interface for each tool, and then the model view can operate over a list of tools using that interface.

Next, the accordion, if it really needs c# support to set up a javascript/hml/css ui (which seems unlikely and definitely unwanted), would love to have its own c# class to at least contain the smell :-)

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884)_

**Comment by JohnThomson** [comment]
Review status: 5 of 63 files reviewed at latest revision, 12 unresolved discussions.

---

_[src/BloomBrowserUI/bookEdit/accordion/Accordion.htm, line 28 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3u7AYVGGuf1fPc7ILo:-K3uwDjHceZOv2AZlxk6:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomBrowserUI/bookEdit/accordion/Accordion.htm#L28)):_
Done.

---

_[src/BloomBrowserUI/bookEdit/accordion/accordion.js, line 32 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3u836hpDVuqLh2Wtoa:-K3uwLJOgw_1_k-rhFPA:-1264019568) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomBrowserUI/bookEdit/accordion/accordion.js#L32)):_
Probably whoever wrote it (very likely me) did not know how to extend the fireCSharpAccordionEvent mechanism to handle a variable number of parameters (or even just more than one), and did not want to add too many separate event watchers...probably a spurious fear.
I at least improved it to the extent of making the tool name a parameter rather than a case in the switch statement. But maybe we should change this to three distinct watchers?

---

_[src/BloomBrowserUI/bookEdit/accordion/talkingBook.ts, line 9 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3u9N5jQK3QkTh6VRKX:-K3v0Xs08FiJ04P_5s40:-77691888) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomBrowserUI/bookEdit/accordion/talkingBook.ts#L9)):_
I think I have switched all appropriate places to be show/HideRecordingTools.

---

_[src/BloomBrowserUI/bookEdit/accordion/talkingBook/talkingBook.jade, line 5 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3uA8CLfVoicE1DKgM9:-K3v2CSLwlinqimVOr_E:-1542809242) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomBrowserUI/bookEdit/accordion/talkingBook/talkingBook.jade#L5)):_
Something Gordon did. I presume it's what is required by the Accordion library we're using. The comparable line in decodableReader.jade has 1 and 10, leveledReader has 2 and 20.

---

_[src/BloomBrowserUI/bookEdit/accordion/talkingBook/talkingBook.ts, line 13 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3uBw-3aGOVAJsm8fxu:-K3v2Y-jsmkcpS2xYzy3:-829096152) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomBrowserUI/bookEdit/accordion/talkingBook/talkingBook.ts#L13)):_
Done. (See above)

---

_[src/BloomBrowserUI/bookEdit/js/readerTools.js, line 110 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3uCRcxHpk68--HwBuY:-K3v339otOuoAlxKCzMW:-1710808803) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomBrowserUI/bookEdit/js/readerTools.js#L110)):_
Added Tool to function name (also for Leveled)

---

_[src/BloomBrowserUI/bookEdit/js/readerTools.ts, line 184 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3uB3Im3HVP56IrjCLm:-K3v37r3spQSrZQuR4se:-829096152) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomBrowserUI/bookEdit/js/readerTools.ts#L184)):_
Done. (See above)

---

_[src/BloomBrowserUI/bookEdit/js/readerTools.ts, line 350 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3uBXadCYBEnRMlM2lD:-K3vUHaYexlAhzlIpazq:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomBrowserUI/bookEdit/js/readerTools.ts#L350)):_
Done.

---

_[src/BloomExe/BloomExe.csproj, line 224 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3uBhpQgzUm0njayNxf:-K3v3pKhdy95YKMKdVUN:332291536) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomExe/BloomExe.csproj#L224)):_
I think this one is right. It represents one of the tools in the Accordion, not the whole thing.

---

_[src/BloomExe/Edit/AccordionTool.cs, line 7 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3uAOM-WZcMYoLppa16:-K3v3wovK-Y0rP4Zn049:-189593077) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomExe/Edit/AccordionTool.cs#L7)):_
See above

---

_[src/BloomExe/Edit/EditingModel.cs, line 61 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3uCkXSjNM3esz_qjew:-K3vQnTTGbcUfVmA0GRQ:-205914900) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomExe/Edit/EditingModel.cs#L61)):_
I built enough framework to get rid of _showRecordingTools and the special methods that know about this tool. There may be more that can be done to take advantage of this for the other tools.
The editing model class seems to be all about setting up the HTML for editing the page and persisting the results. So I'm having a hard time seeing what belongs in your "smells" class. Maybe we should make a separate task and talk about it some?

---

_[src/BloomBrowserUI/audio/audioRecording.ts, line 292 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3u6MRLP-f9ojCFp2Qx:-K3uuZdXYLXv6ep_27LT:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomBrowserUI/audio/audioRecording.ts#L292)):_
Done.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884)_

**Comment by hatton** [comment]
Reviewed 75 of 83 files at r3.
Review status: 55 of 63 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884)*

**Comment by hatton** [comment]
Reviewed 4 of 83 files at r3.
Review status: 59 of 63 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/BloomExe/Edit/AccordionTool.cs, line 22 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K4-d1alUUcLtsAaZQYQ:-K4-d1alUUcLtsAaZQYR:-336354289) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34f56eb26f11b47081601d8c4f80d39ef7463c71/src/BloomExe/Edit/AccordionTool.cs#L22)):*
"Name" has too many meanings for me. Can you change this to convey how it used (and keep people from changing it if it would break existing users) "EnglishDisplayName"/"ToolId" etc. ?

---

*[src/BloomExe/Edit/AccordionTool.cs, line 34 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K4-cV844UBMIfx1OE4V:-K4-cV85m36YZnKykax_:1526620076) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34f56eb26f11b47081601d8c4f80d39ef7463c71/src/BloomExe/Edit/AccordionTool.cs#L34)):*
"With" here implies to me that I'm getting something and the something is incorporating the parameter, but that's not what we have here. How about "FromName" (or, as I recommend below) "FromToolId"/"CreateFromToolId". 

---

*[src/BloomExe/Edit/AccordionTool.cs, line 38 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K4-bvYStPcQ4zllEqfB:-K4-bvYStPcQ4zllEqfC:-403177710) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34f56eb26f11b47081601d8c4f80d39ef7463c71/src/BloomExe/Edit/AccordionTool.cs#L38)):*
These appear to be functioning as the same thing across  tools, so they can be part of the interface, with a single property name, (e.g. "ToolId").

---

*[src/BloomExe/Edit/EditingView.cs, line 932 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K4-dkrSxFd13KCh60_L:-K4-dkrSxFd13KCh60_M:-1332201544) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34f56eb26f11b47081601d8c4f80d39ef7463c71/src/BloomExe/Edit/EditingView.cs#L932)):*
We should find a way to make this not be public. The need for it points to lack of encapsulation.

---

*[src/BloomExe/Edit/TalkingBookTool.cs, line 19 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K4-e3ERMKzMIUy3CfhT:-K4-e3ERMKzMIUy3CfhU:1426457410) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34f56eb26f11b47081601d8c4f80d39ef7463c71/src/BloomExe/Edit/TalkingBookTool.cs#L19)):*
We need to find a way to not have the component need intimate knowledge of the UI used to enable/disable this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884)*

**Comment by hatton** [comment]
Reviewed 3 of 83 files at r3.
Review status: 62 of 63 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/accordion/talkingBook/talkingBook.jade, line 5 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3uA8CLfVoicE1DKgM9:-K4-eJ3BEImJwYmIRbsL:-34972640) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomBrowserUI/bookEdit/accordion/talkingBook/talkingBook.jade#L5)):*
Can we do something to fix it? It's a "magic number" and that violates our coding standard.

---

*[src/BloomExe/Edit/TalkingBookTool.cs, line 34 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K4-ewn3Rekq491-fNXm:-K4-ewn3Rekq491-fNXn:-444503152) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34f56eb26f11b47081601d8c4f80d39ef7463c71/src/BloomExe/Edit/TalkingBookTool.cs#L34)):*
Would it be correct to align these names, so that it is calleByCSharp.showTalkingBookTool()?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884)*

**Comment by hatton** [comment]
Reviewed 1 of 83 files at r3.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/accordion/talkingBook/talkingBook.jade, line 5 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3uA8CLfVoicE1DKgM9:-K4O9zjTqdu1XbW2SYIM:1817888874) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomBrowserUI/bookEdit/accordion/talkingBook/talkingBook.jade#L5)):*
Turns out it is meant to indicate which kind of synphony markup to display when this panel is active. Works fine to remove it altogether, so I did. I also added a comment to the other two panels.

---

*[src/BloomExe/Edit/AccordionTool.cs, line 22 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K4-d1alUUcLtsAaZQYQ:-K4OBSz6u9Ev4YXp9pqe:-999252401) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34f56eb26f11b47081601d8c4f80d39ef7463c71/src/BloomExe/Edit/AccordionTool.cs#L22)):*
Changed to JsonToolId

---

*[src/BloomExe/Edit/AccordionTool.cs, line 34 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K4-cV844UBMIfx1OE4V:-K4OC2fdzh6ACJaSr8GN:-1218083677) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34f56eb26f11b47081601d8c4f80d39ef7463c71/src/BloomExe/Edit/AccordionTool.cs#L34)):*
CreateForJsonToolId

---

*[src/BloomExe/Edit/AccordionTool.cs, line 38 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K4-bvYStPcQ4zllEqfB:-K4OCWpS-OdKDySjfalq:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34f56eb26f11b47081601d8c4f80d39ef7463c71/src/BloomExe/Edit/AccordionTool.cs#L38)):*
Done.

---

*[src/BloomExe/Edit/EditingView.cs, line 932 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K4-dkrSxFd13KCh60_L:-K4ONSJpFJFauPChzTyE:-2071046117) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34f56eb26f11b47081601d8c4f80d39ef7463c71/src/BloomExe/Edit/EditingView.cs#L932)):*
I put a method on the View which returns the body of the toolbox/accordion as an ElementProxy, and used that.
I realized afterwards that all the enhancements to ElementProxy are probably YAGNI (though maybe we WILL use some of them one day?) since there won't be any internal state to save in this tab once we move the recording controls themselves into the tab. Sigh.

---

*[src/BloomExe/Edit/TalkingBookTool.cs, line 19 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K4-e3ERMKzMIUy3CfhT:-K4OO5xLZzjq85jgaPhb:602277875) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34f56eb26f11b47081601d8c4f80d39ef7463c71/src/BloomExe/Edit/TalkingBookTool.cs#L19)):*
I'm proposing to leave this for now as it should go away when we remove the checkbox and move the recording controls themselves into the panel.

---

*[src/BloomExe/Edit/TalkingBookTool.cs, line 34 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K4-ewn3Rekq491-fNXm:-K4OOSRz3yurEOLHUSRR:-1326453572) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34f56eb26f11b47081601d8c4f80d39ef7463c71/src/BloomExe/Edit/TalkingBookTool.cs#L34)):*
I've changed this. However, there are multiple JS places that use showRecordingTools, which ought to be the same also (but see comment on showTalkingBookTool in talkingBook.ts).
But, I think both methods will go away when we move the controls into the panel. So I'm inclined not to worry about it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884)*

**Comment by hatton** [comment]
Reviewed 3 of 18 files at r4.
Review status: 50 of 65 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/accordion/talkingBook.ts, line 9 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3u9N5jQK3QkTh6VRKX:-K4P9cZoZEnQPKZit_3a:-513903711) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomBrowserUI/bookEdit/accordion/talkingBook.ts#L9)):*
Hmm.  The code opposite your comment here still shows "page.contentWindow['startRecording']();"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884)*

**Comment by hatton** [comment]
Reviewed 3 of 18 files at r4.
Review status: 53 of 65 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/BloomBrowserUI/BloomBrowserUI.csproj, line 63 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K4PA6a9DI0NZ1pVGnxC:-K4PA6a9DI0NZ1pVGnxD:349708310) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34f56eb26f11b47081601d8c4f80d39ef7463c71/src/BloomBrowserUI/BloomBrowserUI.csproj#L63)):*
John, what's the difference between "AudioRecordingTool" and "TalkingBook"? They are both under "bookEdit\accordion\" and i would have thought they were the same thing.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884)*

**Comment by hatton** [comment]
Reviewed 5 of 18 files at r4.
Review status: 58 of 65 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/BloomExe/Edit/AccordionTool.cs, line 43 \[r4\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K4PAzNDgiPLNYSGNo2c:-K4PAzNDgiPLNYSGNo2d:715733122) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3bdb03990cbe93405fa038f1d15152bf773b9f6c/src/BloomExe/Edit/AccordionTool.cs#L43)):*
I think you wanted Create *From* JsonToolId.  And the parameter should then be jsonToolId instead of "name".

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884)*

**Comment by hatton** [comment]
Review status: 58 of 65 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/BloomBrowserUI/BloomBrowserUI.csproj, line 63 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K4PA6a9DI0NZ1pVGnxC:-K4PBAczzEqaiQI57nWZ:-1169621808) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34f56eb26f11b47081601d8c4f80d39ef7463c71/src/BloomBrowserUI/BloomBrowserUI.csproj#L63)):*
Oh, maybe this is temporary, and for some reason the bubble stuff is currently located in the accordion but will be going away entirely.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884)*

**Comment by hatton** [comment]
Reviewed 7 of 18 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884)*

**Comment by JohnThomson** [comment]
Review status: 63 of 65 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/BloomBrowserUI/BloomBrowserUI.csproj, line 63 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K4PA6a9DI0NZ1pVGnxC:-K4PCnTEa3jkZB9kn5X_:1440134149) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34f56eb26f11b47081601d8c4f80d39ef7463c71/src/BloomBrowserUI/BloomBrowserUI.csproj#L63)):*
I'm not sure exactly what will happen to the bubble code when I move the controls into the talkingBook tool. Very likely this file goes away. If not it should probably get some new name.

It _might_ be worth keeping a distinction between the code that (hopefully generically) managers a set of controls for recording audio in this simple way, and anything that makes it specific to Bloom talking books. Probably too hard to do until we have at least one other client to help distinguish what is common.

---

*[src/BloomBrowserUI/bookEdit/accordion/talkingBook.ts, line 9 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K3u9N5jQK3QkTh6VRKX:-K4PFjM5ROqwgBZjMjUq:-769114976) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7377c2f2dd558693e85b05a63de8bf617f45877b/src/BloomBrowserUI/bookEdit/accordion/talkingBook.ts#L9)):*
As far as I can tell this is a shortcoming in Recordable. In a subsequent checkin this (new) file moved and was changed further. Recordable fails to show the result connected with this comment. You can see the end result ((<any>page.contentWindow).showRecordingTools();) in accordion/talkingBook/talkingBook.ts.

---

*[src/BloomExe/Edit/AccordionTool.cs, line 43 \[r4\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884#-K4PAzNDgiPLNYSGNo2c:-K4PGQuJ4g9__DuCYo5v:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3bdb03990cbe93405fa038f1d15152bf773b9f6c/src/BloomExe/Edit/AccordionTool.cs#L43)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/884)*

**Pull request merged**
