### PR TITLE
BL-13337 fix unwanted transparency in cover images

### PR DESCRIPTION
**Pull request by nabalone**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6451)

### CODE REVIEW

**Comment by nabalone** [comment]
*[`src/BloomExe/Book/BookCompressor.cs` line 516 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6451#-NwMvNGc4OrP-u5roJlr:-NwMvNGd9zGsDHlivjYi:b-yae2ex) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/23975c41e2082fb5587216c06f689316aa9734e6/src/BloomExe/Book/BookCompressor.cs#L516)):*
> ```Smalltalk
>                     var needTransparencyConversion =
>                         needsTransparentBackground
>                         && !appearsToBeJpeg
> ```

`ShouldMakeBackgroundTransparent` on the next line checks `appearsToBePng` before doing anything else and exits if not, so I think the `appearsToBeJpeg` is redundant

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6451)* status: all files reviewed, 4 unresolved discussions (waiting on @nabalone)

___
*[`src/BloomExe/Book/BookCompressor.cs` line 516 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6451#-NwMvNGc4OrP-u5roJlr:-NwelvUx1E54iY6FO1ml:b-yrvsek) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/23975c41e2082fb5587216c06f689316aa9734e6/src/BloomExe/Book/BookCompressor.cs#L516)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

`ShouldMakeBackgroundTransparent` on the next line checks `appearsToBePng` before doing anything else and exits if not, so I think the `appearsToBeJpeg` is redundant
</blockquote></details>

I don't think it's possible for a file that's really JPG to appearToBePng, so it should be safe to remove it.
___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 967 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6451#-Nweh19n78m2qyocnGU3:-Nweh19n78m2qyocnGU4:bdqul5p) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3129f51044f636e7eaeeb086d8842cf26c989a40/src/BloomExe/ImageProcessing/ImageUtils.cs#L967)):*
> ```Smalltalk
>             Size size,
>             bool makeOpaque,
>             bool makeTransparentifAppropriate,
> ```

Not a great fan of this name. The decision about whether it's appropriate to add transparency has three components: is it on the cover, is it PNG, does it seem to be line art (two colors, one of them white). It's inappropriate to add transparency if any of these is false, but one of them has already been evaluated and determines whether this argument is true.
ShouldMakeBackgroundTransparent has the same problem: it's actually only responsible for considering two of the three factors that determine whether we should do that.
It would be nice to unify the names and try to convey that this is about the nature of the image rather than where it is.
What really remains to be determined is whether it is a kind of image that we think it is possible and safe to give a transparent background. I thought about "MakeTransparentIfPngLineArt" but I don't really want to expose the algorithm in the name.
How about makeTransparentIfSafe/SafeToMakeBackgroundTransparent? Or we could take the position that it's not even possible except in these conditions, and use makeTransparentIfPossible/PossibleToMakeBackgroundTransparent.
Or we could take the position that we're deciding whether we think it is appropriate to change this kind of image.
I've spent too long thinking about this. I don't feel strongly about it. If you don't think one of those ideas is an improvement, it can stay the way it is.
___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 990 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6451#-NweeafSAvDYnFTzbTlL:-NweeafSAvDYnFTzbTlM:bw667p8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3129f51044f636e7eaeeb086d8842cf26c989a40/src/BloomExe/ImageProcessing/ImageUtils.cs#L990)):*
> ```Smalltalk
>             if (makeTransparentifAppropriate)
>             {
>                 using (var originalImage = PalasoImage.FromFileRobustly(path))
> ```

IIRC, this function has crashed a lot, especially if the metadata is wrong for the extension. I think it should have a try...catch. If we can't make an image from the file successfully, let's just not try to make anything transparent.
___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 1001 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6451#-NweeP3Z4ZYwnvrwZYDE:-NweeP3Z4ZYwnvrwZYDF:b9wnvcg) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3129f51044f636e7eaeeb086d8842cf26c989a40/src/BloomExe/ImageProcessing/ImageUtils.cs#L1001)):*
> ```Smalltalk
>                     Size = size,
>                     MakeOpaque = makeOpaque,
>                     MakeTransparent = makeTransparentifAppropriate && suitableToMakeTransparent,
> ```

We don't really need to check makeTransparentIfAppropriate again.
What if we just renamed suitableToMakeTransparent to makeTransparent?

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6451)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 967 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6451#-Nweh19n78m2qyocnGU3:-NwfOyaaAsW5sgoBKeO6:b-dsm40h) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3129f51044f636e7eaeeb086d8842cf26c989a40/src/BloomExe/ImageProcessing/ImageUtils.cs#L967)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Not a great fan of this name. The decision about whether it's appropriate to add transparency has three components: is it on the cover, is it PNG, does it seem to be line art (two colors, one of them white). It's inappropriate to add transparency if any of these is false, but one of them has already been evaluated and determines whether this argument is true.
ShouldMakeBackgroundTransparent has the same problem: it's actually only responsible for considering two of the three factors that determine whether we should do that.
It would be nice to unify the names and try to convey that this is about the nature of the image rather than where it is.
What really remains to be determined is whether it is a kind of image that we think it is possible and safe to give a transparent background. I thought about "MakeTransparentIfPngLineArt" but I don't really want to expose the algorithm in the name.
How about makeTransparentIfSafe/SafeToMakeBackgroundTransparent? Or we could take the position that it's not even possible except in these conditions, and use makeTransparentIfPossible/PossibleToMakeBackgroundTransparent.
Or we could take the position that we're deciding whether we think it is appropriate to change this kind of image.
I've spent too long thinking about this. I don't feel strongly about it. If you don't think one of those ideas is an improvement, it can stay the way it is.
</blockquote></details>

What do you think of calling it `isCoverImage` or something like that? That is really the information we are passing

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6451)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 967 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6451#-Nweh19n78m2qyocnGU3:-NwzgT3D7-J8oEBeotp7:bhkxmky) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3129f51044f636e7eaeeb086d8842cf26c989a40/src/BloomExe/ImageProcessing/ImageUtils.cs#L967)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

What do you think of calling it `isCoverImage` or something like that? That is really the information we are passing
</blockquote></details>

JohnT and I decided on forUseOnColoredBackground

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6451)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 990 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6451#-NweeafSAvDYnFTzbTlL:-Nx-0iqg-lCfby2KjtUE:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3129f51044f636e7eaeeb086d8842cf26c989a40/src/BloomExe/ImageProcessing/ImageUtils.cs#L990)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

IIRC, this function has crashed a lot, especially if the metadata is wrong for the extension. I think it should have a try...catch. If we can't make an image from the file successfully, let's just not try to make anything transparent.
</blockquote></details>

Done.
___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 1001 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6451#-NweeP3Z4ZYwnvrwZYDE:-Nx--KXq5e24UUxv7Hp_:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3129f51044f636e7eaeeb086d8842cf26c989a40/src/BloomExe/ImageProcessing/ImageUtils.cs#L1001)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We don't really need to check makeTransparentIfAppropriate again.
What if we just renamed suitableToMakeTransparent to makeTransparent?
</blockquote></details>

Done.

**Review by JohnThomson — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6451#-:-NyVRs2l-LOHQSi9l16Y:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)

**Pull request merged**
