### PR TITLE
Add aria attributes for accessibility (BL-5894)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
Also get epub output to pass conformance test as much as possible with
regard to these attributes and the epub:type attributes.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 998 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381#-LBwLrK6EFsFsBdttCIE:-LBwLrK6EFsFsBdttCIF:bgoey4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4a0bf50c6a6b3e22bc210fdcbfae4a641adddc20/src/BloomExe/Publish/Epub/EpubMaker.cs#L998)):*
> ```Smalltalk
> 			if (div != null)
> 			{
> 				if (HasClass(div, "frontCover"))
> ```

This if/else group has 4 copies of the same code. How about extracting a method?

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1022 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381#-LBwMA0z1L1qv5TzcVLV:-LBwMA10DFrfEgOWy1Ti:b-ldkty) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4a0bf50c6a6b3e22bc210fdcbfae4a641adddc20/src/BloomExe/Publish/Epub/EpubMaker.cs#L1022)):*
> ```Smalltalk
> 				// Possibly on title page
> 				var divOrigContrib = div.SelectSingleNode(".//div[@id='originalContributions']") as XmlElement;
> 				if (divOrigContrib != null && !String.IsNullOrWhiteSpace(divOrigContrib.InnerText))
> ```

I can't tell exactly, but the next 6 or so blocks seem to be the same code, with different parameters. Extract method?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 998 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381#-LBwLrK6EFsFsBdttCIE:-LBwasgZ9RweJ1WidtnJ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4a0bf50c6a6b3e22bc210fdcbfae4a641adddc20/src/BloomExe/Publish/Epub/EpubMaker.cs#L998)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This if/else group has 4 copies of the same code. How about extracting a method?
</blockquote></details>

Done.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1022 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381#-LBwMA0z1L1qv5TzcVLV:-LBwatli7W8yiWXm8JaG:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4a0bf50c6a6b3e22bc210fdcbfae4a641adddc20/src/BloomExe/Publish/Epub/EpubMaker.cs#L1022)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I can't tell exactly, but the next 6 or so blocks seem to be the same code, with different parameters. Extract method?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381)*

**Comment by JohnThomson** [comment]
Looks basically good. I made a few suggestions; see if you agree...

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 948 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381#-LC-nai008d8HhujPula:-LC-nai008d8HhujPulb:b7ug5gb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a658ab5b53527ff3c1af8662d6ba0ebb72bd1fe/src/BloomExe/Publish/Epub/EpubMaker.cs#L948)):*
> ```Smalltalk
> 			// "toc" is used in the nav.html file.
> 			// Since frontmatter, bodymatter, and backmatter must go on either body or section; putting any epub:type on
> 			// body is strongly deprecated, and style is supposed to mark something that goes in the table of contents, it
> ```

style => section?
I think what you're explaining here is the removal of the code setting epub:types such as cover, titlePage, frontMatter, but outside the context of this PR I don't think that's clear. Are you trying to say something like this?
"Various epub:types such as frontmatter, bodymatter, cover, titlePage, etc are true of certain pages in bloom books, but we can't currently use them. Guidelines call for them to be applied to section HTML elements (or body, but that is strongly deprecated), and other guidelines say sections must be used for things that belong in the table of contents, but we don't want a TOC entry for every xmatter page."
Then I think we want a question about this in the benetech document, because it's weird if the guidelines combine to prevent any use of some types that have been defined. (I'd recommend including in the question your sources for the various "supposed to"s in case they question it.)

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1045 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381#-LC-lsJdAIY6QcEy4dBB:-LC-lsJdAIY6QcEy4dBC:b-1e1w35) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a658ab5b53527ff3c1af8662d6ba0ebb72bd1fe/src/BloomExe/Publish/Epub/EpubMaker.cs#L1045)):*
> ```Smalltalk
> 						//// Simplest implementation of BL-5892...
> 						//var text = desc.InnerText.Trim();
> 						//img.SetAttribute("alt", text);
> ```

A recent change of mine should be ensuring that alt always matches the appropriate image description. So this might be redundant. But I don't think it hurts.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1060 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381#-LC-mYchCpa9Ci1KF-Y3:-LC-mYchCpa9Ci1KF-Y4:b-m1xaso) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a658ab5b53527ff3c1af8662d6ba0ebb72bd1fe/src/BloomExe/Publish/Epub/EpubMaker.cs#L1060)):*
> ```Smalltalk
> 		private bool SetRoleAndLabelForMatchingDiv(XmlElement div, string attributeValue, string labelId, string labelEnglish)
> 		{
> 			var divInternal = div.SelectSingleNode (".//div[" + attributeValue + "]") as XmlElement;
> ```

Is it certain that all the things you use this for only occur once, or that only the first occurrence should get a role? Of course this is called for each page, so something would have to be repeated on the same page...I guess that's unlikely?

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1422 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381#-LC-nGNn65X50oHpkCDt:-LC-nGNn65X50oHpkCDu:b-1dshs9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a658ab5b53527ff3c1af8662d6ba0ebb72bd1fe/src/BloomExe/Publish/Epub/EpubMaker.cs#L1422)):*
> ```Smalltalk
> 			var id = elt.Attributes ["id"].Value;
> 			var display = _browser.RunJavaScript ("getComputedStyle(document.getElementById('" + id + "'), null).display");
> 			return display != "none" || HasClass(elt, "bloom-imageDescription");
> ```

Seems this change is redundant with the one a few lines up.

---

*[src/BloomTests/Publish/ExportEpubTests.cs, line 1623 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381#-LC-pvooE2qUIsP4FG69:-LC-pvooE2qUIsP4FG6A:bknmy2t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a658ab5b53527ff3c1af8662d6ba0ebb72bd1fe/src/BloomTests/Publish/ExportEpubTests.cs#L1623)):*
> ```Smalltalk
> 			CheckAccessibilityInManifest(false, true, _defaultSourceValue, false);	// no sound files, but some image files
> 
> 			AssertThatXmlIn.String(_page1Data).HasSpecifiedNumberOfMatchesForXpath("//xhtml:*[@role='main']", _ns, 0);
> ```

We have "HasNoMatchesForXPath" for this case...sort of redundant, but I so often find myself doing a double take and asking "why should it match this" and then finally noting that the expected count is zero. 

---

*[src/BloomTests/Publish/ExportEpubTests.cs, line 1632 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381#-LC-qpw499QQ6MV9mVQi:-LC-qpw499QQ6MV9mVQj:b-k3ta2a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a658ab5b53527ff3c1af8662d6ba0ebb72bd1fe/src/BloomTests/Publish/ExportEpubTests.cs#L1632)):*
> ```Smalltalk
> 			AssertThatXmlIn.String(_page1Data).HasSpecifiedNumberOfMatchesForXpath("//xhtml:img[@aria-describedby]", _ns, 1);
> 			AssertThatXmlIn.String(_page1Data).HasSpecifiedNumberOfMatchesForXpath("//xhtml:img[@aria-describedby='figdesc1' and @id='bookfig1']", _ns, 1);
> 			AssertThatXmlIn.String(_page1Data).HasSpecifiedNumberOfMatchesForXpath("//xhtml:div[@id='figdesc1']", _ns, 1);
> ```

I'm not very excited about this one humongous test, especially given the difficulty of reading xpaths. How would you feel about making a class something like AriaRoleTests, with a one-time setup that creates the epub and extracts the page files, and then you could write distinct tests like "XmatterPagesHaveNoContentInfoRole" and "FrontCoverHasCorrectRole" that would help to make it clear what the xpaths are checking?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381#-:-LC-sEDu4ME2mXVoPOST:bnao5xi)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 948 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381#-LC-nai008d8HhujPula:-LC0h_Tz515ohbrAQ-uw:b-keaglj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a658ab5b53527ff3c1af8662d6ba0ebb72bd1fe/src/BloomExe/Publish/Epub/EpubMaker.cs#L948)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

style => section?
I think what you're explaining here is the removal of the code setting epub:types such as cover, titlePage, frontMatter, but outside the context of this PR I don't think that's clear. Are you trying to say something like this?
"Various epub:types such as frontmatter, bodymatter, cover, titlePage, etc are true of certain pages in bloom books, but we can't currently use them. Guidelines call for them to be applied to section HTML elements (or body, but that is strongly deprecated), and other guidelines say sections must be used for things that belong in the table of contents, but we don't want a TOC entry for every xmatter page."
Then I think we want a question about this in the benetech document, because it's weird if the guidelines combine to prevent any use of some types that have been defined. (I'd recommend including in the question your sources for the various "supposed to"s in case they question it.)
</blockquote></details>

Done.  Reworded this comment and added question to document.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1045 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381#-LC-lsJdAIY6QcEy4dBB:-LC0eQPjDTgXxTmSKXmr:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a658ab5b53527ff3c1af8662d6ba0ebb72bd1fe/src/BloomExe/Publish/Epub/EpubMaker.cs#L1045)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

A recent change of mine should be ensuring that alt always matches the appropriate image description. So this might be redundant. But I don't think it hurts.
</blockquote></details>

Done.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1060 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381#-LC-mYchCpa9Ci1KF-Y3:-LC0ehUp8eZbK2aPzn7n:bts4vm4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a658ab5b53527ff3c1af8662d6ba0ebb72bd1fe/src/BloomExe/Publish/Epub/EpubMaker.cs#L1060)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is it certain that all the things you use this for only occur once, or that only the first occurrence should get a role? Of course this is called for each page, so something would have to be repeated on the same page...I guess that's unlikely?
</blockquote></details>

The inputs vary.  Some of them look for an id attribute which certainly should be unique.  Others look for class or data-derived values which are unique within each Bloom book as far as I know.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1422 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381#-LC-nGNn65X50oHpkCDt:-LC0fD2d1X3V4OFLnmj0:b-sdzbw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a658ab5b53527ff3c1af8662d6ba0ebb72bd1fe/src/BloomExe/Publish/Epub/EpubMaker.cs#L1422)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Seems this change is redundant with the one a few lines up.
</blockquote></details>

Done.  oops.

---

*[src/BloomTests/Publish/ExportEpubTests.cs, line 1623 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381#-LC-pvooE2qUIsP4FG69:-LC0iZ_S01lhWSEMh8PQ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a658ab5b53527ff3c1af8662d6ba0ebb72bd1fe/src/BloomTests/Publish/ExportEpubTests.cs#L1623)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We have "HasNoMatchesForXPath" for this case...sort of redundant, but I so often find myself doing a double take and asking "why should it match this" and then finally noting that the expected count is zero. 
</blockquote></details>

Done.

---

*[src/BloomTests/Publish/ExportEpubTests.cs, line 1632 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381#-LC-qpw499QQ6MV9mVQi:-LC0wPi6Ck8h8vXc-YRI:bf33vv0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a658ab5b53527ff3c1af8662d6ba0ebb72bd1fe/src/BloomTests/Publish/ExportEpubTests.cs#L1632)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm not very excited about this one humongous test, especially given the difficulty of reading xpaths. How would you feel about making a class something like AriaRoleTests, with a one-time setup that creates the epub and extracts the page files, and then you could write distinct tests like "XmatterPagesHaveNoContentInfoRole" and "FrontCoverHasCorrectRole" that would help to make it clear what the xpaths are checking?
</blockquote></details>

Done after a fashion.  Although I didn't create a new class, I split the checks on the pages into a number of smaller methods with hopefully descriptive names.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381)*

**Comment by JohnThomson** [comment]
:lgtm: Thanks for your patience with my pickiness.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomTests/Publish/ExportEpubTests.cs, line 1632 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381#-LC-qpw499QQ6MV9mVQi:-LC4B2Fb9SIO_F-ePNuO:b-jd3nes) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0a658ab5b53527ff3c1af8662d6ba0ebb72bd1fe/src/BloomTests/Publish/ExportEpubTests.cs#L1632)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Done after a fashion.  Although I didn't create a new class, I split the checks on the pages into a number of smaller methods with hopefully descriptive names.
</blockquote></details>

I think that's a reasonable compromise here. But it's a good technique to bear in mind. One advantage is that the test runner can do all the tests, even if some break, which can give a better picture of what is broken.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381#-:-LC4BQzs9GAwN_yzA_On:bpjfu2y)*

**Pull request merged**
