### PR TITLE
Fix downloading a book with absurdly long image filename (BH-5988)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4860)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
I think something needs to be done about the truncation to 60. The other two are just suggestions, I'd be OK merging without them if you don't like the ideas or don't think it's worth it.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4860#-:-MqV1w0C4plhbwd2qekm:bg15f14)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 291 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4860#-MqV-1m52N7uKe_eqIol:-MqV-1m66oFaJbA4gCxJ:bqwvt4d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/736be4fc819f4e5ca855c2f13329d8432d7745b2/src/BloomExe/Publish/Epub/EpubMaker.cs#L291)):*
> ```Smalltalk
> 				// machine, but certainly will on the harvester machine.)
> 				BookInStagingFolder = BookInStagingFolder.Substring(0, 60);
> 			}
> ```

If the user's name is longer than 18 characters ('steve' + 60-47), this will truncate the whole book ID and start chopping off earlier parts of the path. I don't think the results will be good. You should probably force it to keep at least one or two digits of the ID.
You could also use the base64 approach I suggest below to get more randomness into the characters we keep, but that's optional.
___
*[src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, line 704 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4860#-MqV0jv5C0NSLX9zEKzW:-MqV0jv60gXn1GgU0Du6:b-g34pu1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/736be4fc819f4e5ca855c2f13329d8432d7745b2/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L704)):*
> ```Smalltalk
> 			for (int i = 0; i < 100; ++i)
> 			{
> 				var name = "BDS" + i;
> ```

How about generating a random couple of characters from a guid instead of "i"? I think that would give more randomness and less chance of collision with names from previous books.
For example, Convert.ToBase64String(Guid.NewGuid().ToByteArray()) will give a string of mostly useful characters...you could remove plus and slash (and maybe equals, though that can only occur at the end) and then take the first two characters and end up with around 4000 possible two-character strings instead of only 100, and without the first few being any more likely to have been used before than any others.
___
*[src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, line 721 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4860#-MqV1N5N8qdtNl6nlOuQ:-MqV1N5N8qdtNl6nlOuR:bh5xahw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/736be4fc819f4e5ca855c2f13329d8432d7745b2/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L721)):*
> ```Smalltalk
> 			{
> 				// can't delete it... hope we can copy into it.
> 			}
> ```

To make this a bit more robust...you could put this logic into the loop, with a condition like if (i > 10), so that if we try more than 10 names and they all exist, it will start trying to delete existing items. Then maybe let the loop continue as long as it needs to until it finds a name that is unused or where the target can be deleted.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4860)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 291 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4860#-MqV-1m52N7uKe_eqIol:-MqW-ORF2bM5WI4KfYZ3:bkdkv2g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/736be4fc819f4e5ca855c2f13329d8432d7745b2/src/BloomExe/Publish/Epub/EpubMaker.cs#L291)):*
> Convert.ToBase64String(Guid.NewGuid().ToByteArray())
I changed to both using Base64 (which I had already thought of since submitting the PR) and to checking how much over the long pathname gets.
___
*[src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, line 704 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4860#-MqV0jv5C0NSLX9zEKzW:-MqW95GmDegmJQu71qE5:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/736be4fc819f4e5ca855c2f13329d8432d7745b2/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L704)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

How about generating a random couple of characters from a guid instead of "i"? I think that would give more randomness and less chance of collision with names from previous books.
For example, Convert.ToBase64String(Guid.NewGuid().ToByteArray()) will give a string of mostly useful characters...you could remove plus and slash (and maybe equals, though that can only occur at the end) and then take the first two characters and end up with around 4000 possible two-character strings instead of only 100, and without the first few being any more likely to have been used before than any others.
</blockquote></details>

Done.
___
*[src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, line 721 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4860#-MqV1N5N8qdtNl6nlOuQ:-MqW95m00lvGc54MchVv:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/736be4fc819f4e5ca855c2f13329d8432d7745b2/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L721)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

To make this a bit more robust...you could put this logic into the loop, with a condition like if (i > 10), so that if we try more than 10 names and they all exist, it will start trying to delete existing items. Then maybe let the loop continue as long as it needs to until it finds a name that is unused or where the target can be deleted.
</blockquote></details>

Done.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4860)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @JohnThomson and @StephenMcConnel)

___
*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 294 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4860#-Mqa1JWK2OkOy9SNl4Ua:-Mqa1JWK2OkOy9SNl4Ub:b-u3myhr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b42f428996768610ee1f092dfb14696b0f1ad910/src/BloomExe/Publish/Epub/EpubMaker.cs#L294)):*
> ```Smalltalk
> 				// this file's path too long, throwing an exception rather than creating an ePUB.  (This may not happen on the local user's
> 				// machine, but certainly will on the harvester machine.)
> 				var longestName = Path.GetFileName(DirectoryUtils.GetLongestPathname(_book.FolderPath));
> ```

Technically, the longest filename might not the the filename of the longest path, e.g., bookFolder/video/abc.mp4 is longer than bookFolder/image.jpg. Maybe rewrite GetLongestPath to be GetLongestName? (Of course everything I can think of that lives in subfolders has Bloom-generated names and is very unlikely to be a problem longest-name. But since you're going to the trouble of figuring out how long the ID can be exactly, seems like it should be exactly right.)
___
*[src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, line 710 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4860#-Mqa6ZxS3HQCh6DHInEE:-Mqa6ZxS3HQCh6DHInEF:b-i4d9ii) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b42f428996768610ee1f092dfb14696b0f1ad910/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L710)):*
> ```Smalltalk
> 				if (!File.Exists(tempPath) && !Directory.Exists(tempPath))
> 					return name;
> 				if (i > 10)
> ```

Wants a comment like, "We're finding a lot of names in use. To improve our chances, and since this is probably garbage left behind by other uploads, start trying to clean them up."
___
*[src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, line 715 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4860#-Mqa4HnP6hUSMdvytJhe:-Mqa4HnP6hUSMdvytJhf:b-bwn7kc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b42f428996768610ee1f092dfb14696b0f1ad910/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L715)):*
> ```Smalltalk
> 					{
> 						if (File.Exists(tempPath))
> 							RobustFile.Delete(tempPath);
> ```

I wonder whether this might be a case for deliberately NOT using RobustFile? Each failed RobustFile.Delete will take several hundred milliseconds retrying...if there are several failures it might get quite slow. And probably the next random name will either not exist at all or be instantly deletable. (Don't forget to comment why so someone doesn't automatically 'fix' it.)
Of course the chance that none of the first ten can just be used is pretty small...I hope...assuming we're cleaning up these BDS things...

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4860)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 294 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4860#-Mqa1JWK2OkOy9SNl4Ua:-MqacLoPEzO4QETGFNnn:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b42f428996768610ee1f092dfb14696b0f1ad910/src/BloomExe/Publish/Epub/EpubMaker.cs#L294)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Technically, the longest filename might not the the filename of the longest path, e.g., bookFolder/video/abc.mp4 is longer than bookFolder/image.jpg. Maybe rewrite GetLongestPath to be GetLongestName? (Of course everything I can think of that lives in subfolders has Bloom-generated names and is very unlikely to be a problem longest-name. But since you're going to the trouble of figuring out how long the ID can be exactly, seems like it should be exactly right.)
</blockquote></details>

Done.
___
*[src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, line 710 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4860#-Mqa6ZxS3HQCh6DHInEE:-MqadBNT8NF6Y0di1fsn:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b42f428996768610ee1f092dfb14696b0f1ad910/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L710)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Wants a comment like, "We're finding a lot of names in use. To improve our chances, and since this is probably garbage left behind by other uploads, start trying to clean them up."
</blockquote></details>

Done.
___
*[src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, line 715 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4860#-Mqa4HnP6hUSMdvytJhe:-MqaeGDY040fsuBXyA7q:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b42f428996768610ee1f092dfb14696b0f1ad910/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L715)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I wonder whether this might be a case for deliberately NOT using RobustFile? Each failed RobustFile.Delete will take several hundred milliseconds retrying...if there are several failures it might get quite slow. And probably the next random name will either not exist at all or be instantly deletable. (Don't forget to comment why so someone doesn't automatically 'fix' it.)
Of course the chance that none of the first ten can just be used is pretty small...I hope...assuming we're cleaning up these BDS things...
</blockquote></details>

Done.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4860)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
