### PR TITLE
Allow books to specify XMatter (BL-4363)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1544)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/XMatterHelper.cs, line 36 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544#-KeLPHQX_-LpfOkFbsp0:-KeLPHQX_-LpfOkFbsp1:b-gh2dt6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e6896b6810c60f56f8a4845c643d68fba2db8ef1/src/BloomExe/Book/XMatterHelper.cs#L36)):*
> ```Smalltalk
> 		{
> 			_bookDom = bookDom;
> 			_nameOfXMatterPack = GetRequiredBookXMatter(bookDom);
> ```

We're assuming a simple name that will be found in one of the places we already look for xmatter. That's OK for the current purpose (Template Starter) but it might be worth noting in a comment that more might be needed if we really allow users to make their own xmatter packs.

---

*[src/BloomExe/Book/XMatterHelper.cs, line 82 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544#-KeLOlxH386fOs5fMnym:-KeLOlxH386fOs5fMnyn:butrvjc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e6896b6810c60f56f8a4845c643d68fba2db8ef1/src/BloomExe/Book/XMatterHelper.cs#L82)):*
> ```Smalltalk
> 		private string GetRequiredBookXMatter(HtmlDom bookDom)
> 		{
> 			var div = bookDom.Body.SelectSingleNode("div[@id='bloomDataDiv']/div[@data-book='xmatter']");
> ```

My intuition is that datadiv is for (possibly replicated) content of xmatter...stuff the user sees. This might be better in a <meta> tag? But I'd like to know what @hatton thinks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Book/XMatterHelper.cs, line 33 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544#-KeLZb8zvnbZhZ2KLkKs:-KeLZb8zvnbZhZ2KLkKt:b-hmholr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e6896b6810c60f56f8a4845c643d68fba2db8ef1/src/BloomExe/Book/XMatterHelper.cs#L33)):*
> ```Smalltalk
> 		/// <param name="nameOfXMatterPack">e.g. "Factory", "SILIndonesia"</param>
> 		/// <param name="fileLocator">The locator needs to be able tell us the path to an xmater html file, given its name</param>
> 		public XMatterHelper(HtmlDom bookDom, string nameOfXMatterPack, IFileLocator fileLocator)
> ```

nameOfXMatterPack --> nameOfDefaultXmatterPack, with a comment on the parameter that the book may override this.

---

*[src/BloomExe/Book/XMatterHelper.cs, line 82 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544#-KeLOlxH386fOs5fMnym:-KeLZqWfcHHyJGbAlBni:b-mfjz91) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e6896b6810c60f56f8a4845c643d68fba2db8ef1/src/BloomExe/Book/XMatterHelper.cs#L82)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

My intuition is that datadiv is for (possibly replicated) content of xmatter...stuff the user sees. This might be better in a <meta> tag? But I'd like to know what @hatton thinks.
</blockquote></details>

So options are meta, attribute on body (e.g. data-xmatter), or data-div as was done.  Are there any advantages or disadvantages to any of these?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Book/XMatterHelper.cs, line 82 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544#-KeLOlxH386fOs5fMnym:-KeZ6RKdYynqNMKe_t46:bejy6z2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e6896b6810c60f56f8a4845c643d68fba2db8ef1/src/BloomExe/Book/XMatterHelper.cs#L82)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

So options are meta, attribute on body (e.g. data-xmatter), or data-div as was done.  Are there any advantages or disadvantages to any of these?
</blockquote></details>

You pointed out elsewhere that it is more usual for stuff we manipulate to be in data-div. meta (near the start of the file) tends to be easier to find. data-div is associated with xmatter already (but currently mostly gets inserted into it, rather than controlling what it is). We don't seem to use body attributes for anything but already have <meta name="pageTemplateSource" content="Basic Book"></meta> which seems closely analogous to this. Most but not all data-div stuff is in a language and meant to be read by humans rather than used by the software.
Seems like a marginal decision...so maybe we should stick with what we have?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544)*

**Comment by hatton** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/Book/XMatterHelper.cs, line 82 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544#-KeLOlxH386fOs5fMnym:-KeZwuYvh-BEzM0QZcZc:b-zhyfck) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e6896b6810c60f56f8a4845c643d68fba2db8ef1/src/BloomExe/Book/XMatterHelper.cs#L82)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

You pointed out elsewhere that it is more usual for stuff we manipulate to be in data-div. meta (near the start of the file) tends to be easier to find. data-div is associated with xmatter already (but currently mostly gets inserted into it, rather than controlling what it is). We don't seem to use body attributes for anything but already have <meta name="pageTemplateSource" content="Basic Book"></meta> which seems closely analogous to this. Most but not all data-div stuff is in a language and meant to be read by humans rather than used by the software.
Seems like a marginal decision...so maybe we should stick with what we have?
</blockquote></details>

Steve changed to meta

---

*[src/BloomTests/Book/XMatterHelperTests.cs, line 164 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544#-KeZx9lj-CEk-DHzckCX:-KeZx9lk4WR1jUveOTAE:b-i4dvp3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/48a5fe5677405c23000ba0cee7efee327e56d6e4/src/BloomTests/Book/XMatterHelperTests.cs#L164)):*
> ```Smalltalk
> 		}
> 
> 		[Test]
> ```

This could be made much easier to read and maintain:

Factor out the bit that changes (the @content) and make that a parameter, using the [testcase] attributes. For cases where the meta doesn't appear ( it's in there somewhere, right?), you could make that a separate test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544)*

**Comment by JohnThomson** [comment]
Unless we really, really need this merged quickly, I think it would be good to add a change to BookStarter to ensure that the new meta field gets removed from the copy of the book that is made when the template is used to make a new book.

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544#-:-Ke_U7XznMboB-KmqYn6:b-mw1pe9)*

**Comment by hatton** [comment]
Yes, it would help me to merge this and then resume work on related issues.

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544#-:-Ke_YzV53jPdh4VE0tYf:bdn0kwc)*

**Comment by hatton** [comment]
That is, once the outstanding comments are dealt with.

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544#-:-Ke_Z8K8AxMyando_Vbk:bjh030a)*

**Comment by hatton** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/Book/XMatterHelper.cs, line 82 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544#-KeLOlxH386fOs5fMnym:-Ke_mjH1ZaeZi-GvfQEB:b5tn5qn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e6896b6810c60f56f8a4845c643d68fba2db8ef1/src/BloomExe/Book/XMatterHelper.cs#L82)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Steve changed to meta
</blockquote></details>

This whole method could be replaced by

bookDom.GetMetaValue("xmatter", "").Trim();

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/Book/XMatterHelper.cs, line 82 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544#-KeLOlxH386fOs5fMnym:-Kea5UO2udQfiJCjeJtD:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e6896b6810c60f56f8a4845c643d68fba2db8ef1/src/BloomExe/Book/XMatterHelper.cs#L82)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This whole method could be replaced by

bookDom.GetMetaValue("xmatter", "").Trim();
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomTests/Book/XMatterHelperTests.cs, line 164 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544#-KeZx9lj-CEk-DHzckCX:-Kea5VmRKZFX8xENVjm4:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/48a5fe5677405c23000ba0cee7efee327e56d6e4/src/BloomTests/Book/XMatterHelperTests.cs#L164)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This could be made much easier to read and maintain:

Factor out the bit that changes (the @content) and make that a parameter, using the [testcase] attributes. For cases where the meta doesn't appear ( it's in there somewhere, right?), you could make that a separate test.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/Book/XMatterHelper.cs, line 33 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544#-KeLZb8zvnbZhZ2KLkKs:-Kea5_3YV0mRhm4WjbaF:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e6896b6810c60f56f8a4845c643d68fba2db8ef1/src/BloomExe/Book/XMatterHelper.cs#L33)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

nameOfXMatterPack --> nameOfDefaultXmatterPack, with a comment on the parameter that the book may override this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544)*

**Comment by hatton** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[DistFiles/localization/Bloom.en.tmx, line 2464 at r4](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544#-Kedj8U5aW9Xu2Be7-kd:-Kedj8U5aW9Xu2Be7-ke:b-e4r8yf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1ea038665b13909af7fd0be4f1fc372cefe25c59/DistFiles/localization/Bloom.en.tmx#L2464)):*
> ```
>         <seg>This Book called for Front/Back Matter pack named '{0}', but Bloom couldn't find that on this computer.  {1} is being used instead, and the book will be modified accordingly if you edit it.</seg>
>       </tuv>
>     </tu>
> ```

Is this new situation different enough to justify a new thing to be translated?

The existing one:

"Errors.XMatterNotFound",
"This Book called for Front/Back Matter pack named '{0}', but Bloom couldn't find that on this computer. You can either install a Bloom Pack that will give you '{0}', or go to Settings:Book Making and change to another Front/Back Matter Pack.");

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544)*

**Comment by hatton** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/BloomExe/Book/XMatterHelper.cs, line 42 at r4](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544#-KedjWw0dsan9_s-zEgw:-Kedilbqo5WvkH0mlaek:boxvlao) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1ea038665b13909af7fd0be4f1fc372cefe25c59/src/BloomExe/Book/XMatterHelper.cs#L42)):*
> ```Smalltalk
> 			{
> 				_nameOfXMatterPack = specifiedXMatterPack;
> 				var errorTemplate = LocalizationManager.GetString("Errors.SpecifiedXMatterNotFound",
> ```

I'm not clear we want this (see the previous comment) but if we did, the code would be clearer if this definition was done next to where it is used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[DistFiles/localization/Bloom.en.tmx, line 2464 at r4](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544#-Kedj8U5aW9Xu2Be7-kd:-KedkQLjUcVun8uYYK6M:b51qkdt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1ea038665b13909af7fd0be4f1fc372cefe25c59/DistFiles/localization/Bloom.en.tmx#L2464)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is this new situation different enough to justify a new thing to be translated?

The existing one:

"Errors.XMatterNotFound",
"This Book called for Front/Back Matter pack named '{0}', but Bloom couldn't find that on this computer. You can either install a Bloom Pack that will give you '{0}', or go to Settings:Book Making and change to another Front/Back Matter Pack.");
</blockquote></details>

The new situation is that we are actually modifying the book to no longer specify the missing XMatter Pack, and the program is now going to try to use the setting from the collection.  It's possible (one would hope highly probable) that there's no need to change the collection setting to get a valid XMatter Pack.  The existing message is a bit misleading in that it's not the book that called for the missing XMatter pack, it was the collection doing so.   (Although the original code from BookStorage.cs had the check for xmatter from the head/meta element which made the source ambiguous.) How much information do we want to burden the user with?  I think the situations are different enough to warrant different messages, but I'm not a rice farmer, so I'm not the best judge of this.  :-)
If we want to make do with one message, it could be moved inside the GetXMatterDirectory() method, eliminating one of the method arguments.

---

*[src/BloomExe/Book/XMatterHelper.cs, line 42 at r4](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544#-KedjWw0dsan9_s-zEgw:-Kedmz34B5KnlNspQo2s:bf9oda8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1ea038665b13909af7fd0be4f1fc372cefe25c59/src/BloomExe/Book/XMatterHelper.cs#L42)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I'm not clear we want this (see the previous comment) but if we did, the code would be clearer if this definition was done next to where it is used.
</blockquote></details>

It's used in the next line to create an argument value for GetXMatterDirectory().  I suppose I could use another variable to hold the output of the String.Format() that uses errorTemplate, and use that variable as the argument to GetXMatterDirectory() if that would make the code clearer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544)*

**Comment by hatton** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[DistFiles/localization/Bloom.en.tmx, line 2464 at r4](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544#-Kedj8U5aW9Xu2Be7-kd:-Kf90it6N6K4pqwBzo0M:b-sk54l0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1ea038665b13909af7fd0be4f1fc372cefe25c59/DistFiles/localization/Bloom.en.tmx#L2464)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

The new situation is that we are actually modifying the book to no longer specify the missing XMatter Pack, and the program is now going to try to use the setting from the collection.  It's possible (one would hope highly probable) that there's no need to change the collection setting to get a valid XMatter Pack.  The existing message is a bit misleading in that it's not the book that called for the missing XMatter pack, it was the collection doing so.   (Although the original code from BookStorage.cs had the check for xmatter from the head/meta element which made the source ambiguous.) How much information do we want to burden the user with?  I think the situations are different enough to warrant different messages, but I'm not a rice farmer, so I'm not the best judge of this.  :-)
If we want to make do with one message, it could be moved inside the GetXMatterDirectory() method, eliminating one of the method arguments.
</blockquote></details>

OK. So, we need to get its English simplified... I don't even really know what to expect from "the book will be modified accordingly if you edit it", so I don't know how to simplify that. This would be clear

You can either install a Bloom Pack that will give you '{0}', or change the book's Front/Back Matter pack setting.

Is that true enough?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1544)*

**Pull request merged**
