### PR TITLE
Allow link in error report dialog to open new issue (BL-12278)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5893)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5893)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomExe/TeamCollection/TeamCollectionApi.cs` line 143 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5893#-NWstCIX1IfODqWvhho0:-NWstCIX1IfODqWvhho1:bebajrw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e150f921c40bd4181c130f0c66d9dae1cfe1748/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L143)):*
> ```Smalltalk
> 			var fileEncoded = request.Parameters["file"];
> 			var file = UrlPathString.CreateFromUrlEncodedString(fileEncoded).NotEncoded;
> 			request.PostSucceeded();    // this should come before a modal dialog
> ```

This is a nice simple fix if it works, but isn't the thread that wants to report the success still stuck running the modal? If that's not a problem I think it might be worth capturing why it's not in a comment, if the question I'm asking makes any sense.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5893)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/TeamCollection/TeamCollectionApi.cs` line 143 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5893#-NWstCIX1IfODqWvhho0:-NWsvnhCEh5wS2UHfHYc:btn02fa) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e150f921c40bd4181c130f0c66d9dae1cfe1748/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L143)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This is a nice simple fix if it works, but isn't the thread that wants to report the success still stuck running the modal? If that's not a problem I think it might be worth capturing why it's not in a comment, if the question I'm asking makes any sense.
</blockquote></details>

I think the real fix is in line 68 earlier in the file, but Reviewable won't show that to me for some reason.  I changed the sync parameter to false for registering this method.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5893)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomExe/TeamCollection/TeamCollectionApi.cs` line 143 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5893#-NWstCIX1IfODqWvhho0:-NWswMxvB9ge4jSsapuZ:b-dcr103) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e150f921c40bd4181c130f0c66d9dae1cfe1748/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L143)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I think the real fix is in line 68 earlier in the file, but Reviewable won't show that to me for some reason.  I changed the sync parameter to false for registering this method.
</blockquote></details>

So inconspicuous I missed it. I think, though, it would be good to comment to call attention to the need to keep this method able to safely run without sync.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5893)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/TeamCollection/TeamCollectionApi.cs` line 143 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5893#-NWstCIX1IfODqWvhho0:-NWsyzBr1nKWd82yOaYs:b-5gjy1u) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9e150f921c40bd4181c130f0c66d9dae1cfe1748/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L143)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

So inconspicuous I missed it. I think, though, it would be good to comment to call attention to the need to keep this method able to safely run without sync.
</blockquote></details>

I've added a method comment explaining all this, based on your suggested wording (from zulip).

**Review by JohnThomson — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5893#-:-NWt0uOPAAeCaCKdZYFU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
