### PR TITLE
Fix BL-11280 [5.2] Tweak boilerplate text in adaptation credits

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5199)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5199)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`DistFiles/localization/en/Bloom.xlf` line 1585 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5199#-N3uxgjR8zz-5f_NLH1A:-N3uxgjR8zz-5f_NLH1B:b-9jk9q3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/016e52566bbedfe240c497dbd6dff393b868e13b/DistFiles/localization/en/Bloom.xlf#L1585)):*
> ```XML
>       </trans-unit>
>       <trans-unit id="EditTab.FrontMatter.FullOriginalCopyrightLicenseSentence" sil:dynamic="true">
>         <source xml:lang="en">This book is an adaptation of original, {0}, {1}. Licensed under {2}.</source>
> ```

The downside is this will cause all existing translations of this to not be used (unless the translator and approver do it again).
Options: 
1. we can live with that
2. we can manually re-translate and re-approve on Crowdin
3. we can code to look for a new ID and text, use it if translated, else use the old ID and text
4. ?

FWIW, we have done each of 1-3 in the past.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5199)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/Bloom.xlf` line 1585 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5199#-N3uxgjR8zz-5f_NLH1A:-N3uzfnwB3YtAWhvLaLD:bczss3e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/016e52566bbedfe240c497dbd6dff393b868e13b/DistFiles/localization/en/Bloom.xlf#L1585)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The downside is this will cause all existing translations of this to not be used (unless the translator and approver do it again).
Options: 
1. we can live with that
2. we can manually re-translate and re-approve on Crowdin
3. we can code to look for a new ID and text, use it if translated, else use the old ID and text
4. ?

FWIW, we have done each of 1-3 in the past.
</blockquote></details>

Why is that? I didn't change the ID, nor the parameters, so why would an old translation stop working?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5199)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`DistFiles/localization/en/Bloom.xlf` line 1585 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5199#-N3uxgjR8zz-5f_NLH1A:-N3v0v0K7FrkeIwHS8md:b-6jm6jd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/016e52566bbedfe240c497dbd6dff393b868e13b/DistFiles/localization/en/Bloom.xlf#L1585)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Why is that? I didn't change the ID, nor the parameters, so why would an old translation stop working?
</blockquote></details>

When we push this change to Crowdin, it will invalidate every translation since the English source changed (in Crowdin).

The next time we sync changes from Crowdin to Bloom, it will attempt to propagate that change (the invalidation) to Bloom. We could, of course, if we had the wherewithal, not allow that change to happen. At that point, I'm not sure if Crowdin will try to continue pushing that change to Bloom on each subsequent sync or if it would one and done.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5199)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`DistFiles/localization/en/Bloom.xlf` line 1585 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5199#-N3uxgjR8zz-5f_NLH1A:-N3v20Gi5-NhVAkW4woN:b2oea04) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/016e52566bbedfe240c497dbd6dff393b868e13b/DistFiles/localization/en/Bloom.xlf#L1585)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

When we push this change to Crowdin, it will invalidate every translation since the English source changed (in Crowdin).

The next time we sync changes from Crowdin to Bloom, it will attempt to propagate that change (the invalidation) to Bloom. We could, of course, if we had the wherewithal, not allow that change to happen. At that point, I'm not sure if Crowdin will try to continue pushing that change to Bloom on each subsequent sync or if it would one and done.
</blockquote></details>

It is possible I'm wrong about the invalidation based on English string alone, but I'm pretty sure that's the case.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5199)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hatton)

___
*[`DistFiles/localization/en/Bloom.xlf` line 1585 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5199#-N3uxgjR8zz-5f_NLH1A:-N3v6KFS5Spex_v41YTw:b28scml) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/016e52566bbedfe240c497dbd6dff393b868e13b/DistFiles/localization/en/Bloom.xlf#L1585)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

It is possible I'm wrong about the invalidation based on English string alone, but I'm pretty sure that's the case.
</blockquote></details>

OK. Spent a long time looking for documentation on what happens, came up empty. So, I wrote a plan here: https://issues.bloomlibrary.org/youtrack/issue/BL-11280#focus=Comments-102-44431.0-0

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5199)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hatton)

**Pull request merged**
