### PR TITLE
Fix a problem losing smallCoverCredits data loading a book (BL-4591)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1674)

### CODE REVIEW

**Comment by StephenMcConnel** [comment]
something went horribly awry rebasing

**Comment by JohnThomson** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/BookData.cs, line 788 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1674#-KkH9PoAZJX12ZDYt3Hj:-KkH9PoAZJX12ZDYt3Hk:b-3nghxk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/eed25f533f339942ccf20cfb059d2afc4a5fe420/src/BloomExe/Book/BookData.cs#L788)):*
> ```Smalltalk
> 							lang = data.WritingSystemAliases[lang];
> 						}
> 						else if (lang == "*")
> ```

There are fields (like ISBN, maybe copyright) where "*" is actually the value of the lang attribute. Do we want the new behavior for those, or only ones where the lang attribute is empty, or even only where it is not present at all?
It may not matter, since probably no element anywhere has lang="*" AND data-default-languages set to something. But if the special case is actually "elements with no lang attr" I think it would be clearer to test for that rather than "*". (Also, with an earlier test for missing lang attribute, you might not need to repeat the logic for N1, N2, etc.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1674)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/BookData.cs, line 788 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1674#-KkH9PoAZJX12ZDYt3Hj:-KkHKxNUS8_u3yC3Yn25:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/eed25f533f339942ccf20cfb059d2afc4a5fe420/src/BloomExe/Book/BookData.cs#L788)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

There are fields (like ISBN, maybe copyright) where "*" is actually the value of the lang attribute. Do we want the new behavior for those, or only ones where the lang attribute is empty, or even only where it is not present at all?
It may not matter, since probably no element anywhere has lang="*" AND data-default-languages set to something. But if the special case is actually "elements with no lang attr" I think it would be clearer to test for that rather than "*". (Also, with an earlier test for missing lang attribute, you might not need to repeat the logic for N1, N2, etc.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1674)*

**Comment by JohnThomson** [comment]
Sorry, picked up a couple of possible issues...

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Book/BookData.cs, line 789 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1674#-KkHYvFOYAh4gdEQSEff:-KkHYqrmhBW8zWEWsKU9:btz7aib) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/86d813fce03d14d3c2009119c836d1c0886d8f14/src/BloomExe/Book/BookData.cs#L789)):*
> ```Smalltalk
> 						string lang;
> 						if (!node.HasAttribute("lang"))
> 							lang = node.GetOptionalStringAttribute("data-default-languages", "*");
> ```

I'm possibly being difficult here, but the previous version ignored data-default-languages (even if lang was missing) unless it contained one of the three special values. Do we know what else it might contain and whether they should all be treated as lang values? The plural suggests that it might contain, for example, something like "N1,N2" which might do something unexpected.

---

*[src/BloomExe/Book/BookData.cs, line 843 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1674#-KkHZSR_C_UH81gc4t76:-KkHZSR_C_UH81gc4t77:b-8ikrnc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/86d813fce03d14d3c2009119c836d1c0886d8f14/src/BloomExe/Book/BookData.cs#L843)):*
> ```Smalltalk
> 					{
> 						// See whether we need to delete something
> 						var lang = node.GetOptionalStringAttribute("lang", "*");
> ```

This looks like a duplicate of the logic you modified above...does it need the same mod? If so, time for a method...and please look for any others.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1674#-:-KkHZfl2fIPEvbnS-cIP:b3ajqny)*

**Comment by StephenMcConnel** [comment]
John and I have figured out the root cause of this problem, and a totally different approach is needed.  So I'm going to kill this PR and start over.

**Pull request closed without merging**
