### PR TITLE
Embed bold and italic variants of fonts needed in ebooks (BL-13811)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
Not sure everything I've commented on should be fixed. But worth a thought at least, I hope.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-:-OAdncyPEXXi5SbNEYlT:b-xagr6q)* status: all files reviewed, 6 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/FontProcessing/FontFileFinder.cs` line 117 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAdeZJN2BAt1C7GFj9v:-OAdeZJN2BAt1C7GFj9w:bch0a65) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/db289ffc7bedb7ba5d42671721afd7f6b6e33a88/src/BloomExe/FontProcessing/FontFileFinder.cs#L117)):*
> ```Smalltalk
>                 }
>                 if (!string.IsNullOrEmpty(group.Normal))
>                     yield return group.Normal;
> ```

It's possible that a font used only for headings, say, is also ONLY used bold/italic. Do we really want to include group.Italic, group.Bold, and group.Normal if we found a group.BoldItalic?
Then again, I can't find anywhere, past or present, where we care about more than the first result this function yields, so I'm not sure why we don't just have it return one result or null.
___
*[`src/BloomExe/Publish/PublishHelper.cs` line 215 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAdflDV7w1AVcWVQbJy:-OAdflDW40V1kfB6wA8q:bexrf5s) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/db289ffc7bedb7ba5d42671721afd7f6b6e33a88/src/BloomExe/Publish/PublishHelper.cs#L215)):*
> ```Smalltalk
>             {
>                 return fontName.GetHashCode() ^ fontStyle.GetHashCode() ^ fontWeight.GetHashCode();
>             }
> ```

I have a vague recollection that something should be done to make == and != work like Equals, though it may not matter for the limited purpose of this class.
___
*[`src/BloomExe/Publish/PublishHelper.cs` line 588 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAdhyta7prRQYda9PZv:-OAdhyta7prRQYda9PZw:b-amm9lb) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/db289ffc7bedb7ba5d42671721afd7f6b6e33a88/src/BloomExe/Publish/PublishHelper.cs#L588)):*
> ```Smalltalk
>             var fonts = fontFamily.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
>             // Fonts whose names contain spaces are quoted: remove the quotes.
>             return fonts[0].Replace("\"", "");
> ```

Is it likely enough to care about that we don't have the first one in the list installed, and are using one of the others? Maybe that should be left for a later enhancement, even if it's possible.
___
*[`src/BloomExe/Publish/PublishHelper.cs` line 606 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAdiJNb8CYZZ1cD-5kr:-OAdiJNb8CYZZ1cD-5ks:b30wgpp) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/db289ffc7bedb7ba5d42671721afd7f6b6e33a88/src/BloomExe/Publish/PublishHelper.cs#L606)):*
> ```Smalltalk
>             Debug.WriteLine(
>                 $"DEBUG PublishHelper.StoreFontUsed(): font=\"{font}\", fontStyle={fontInfo.fontStyle}, fontWeight={fontInfo.fontWeight}"
>             );
> ```

We might want to remove or comment out all the debug info before merging? I'm not sure. We don't do this so often in debug builds that it would be much nuisance.
___
*[`src/BloomExe/Publish/BloomPub/BloomPubMaker.cs` line 852 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAdjLmq-lW0lN_R-xUG:-OAdjLmq-lW0lN_R-xUH:binknk0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/db289ffc7bedb7ba5d42671721afd7f6b6e33a88/src/BloomExe/Publish/BloomPub/BloomPubMaker.cs#L852)):*
> ```Smalltalk
>                 x => x.fontName == defaultFont && x.fontStyle == "normal" && x.fontWeight == "400"
>             );
>             fontsWanted.RemoveWhere(x => x.fontName == "Andika New Basic");
> ```

Something funny here. I don't remember whether we ship all four variants of Andika in our readers. But if we do, we can probably remove any font whose name is Andika. And if we don't, then we probably can't safely remove Andika New Basic Bold, say, unless we're going to embed Andika Bold instead. (And maybe we SHOULD start shipping all versions of Andika as part of our readers, if we aren't already?)
___
*[`src/BloomExe/Publish/Epub/EpubMaker.cs` line 2849 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAdlDnMBlych6QwXFu-:-OAdlDnMBlych6QwXFu0:b-97taav) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/db289ffc7bedb7ba5d42671721afd7f6b6e33a88/src/BloomExe/Publish/Epub/EpubMaker.cs#L2849)):*
> ```Smalltalk
>             FontGroup group,
>             string relativePathFromCss = "",
>             bool sanitizeFileName = false
> ```

We don't do anything with this argument, so why have it?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/FontProcessing/FontFileFinder.cs` line 117 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAdeZJN2BAt1C7GFj9v:-OAsSNrg51xsA7A261O2:b9ziyej) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/db289ffc7bedb7ba5d42671721afd7f6b6e33a88/src/BloomExe/FontProcessing/FontFileFinder.cs#L117)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's possible that a font used only for headings, say, is also ONLY used bold/italic. Do we really want to include group.Italic, group.Bold, and group.Normal if we found a group.BoldItalic?
Then again, I can't find anywhere, past or present, where we care about more than the first result this function yields, so I'm not sure why we don't just have it return one result or null.
</blockquote></details>

I've changed the code to return only one file at most, but to use a fallback for closest match if the exact style and weight don't have a matching file.  I also made this explicit in the method comments.
___
*[`src/BloomExe/Publish/PublishHelper.cs` line 215 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAdflDV7w1AVcWVQbJy:-OAsJFlt1f0RMLvPqZ2X:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/db289ffc7bedb7ba5d42671721afd7f6b6e33a88/src/BloomExe/Publish/PublishHelper.cs#L215)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I have a vague recollection that something should be done to make == and != work like Equals, though it may not matter for the limited purpose of this class.
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/PublishHelper.cs` line 588 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAdhyta7prRQYda9PZv:-OAsKYcLDfC0-3QJAw9x:b-a9eb2q) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/db289ffc7bedb7ba5d42671721afd7f6b6e33a88/src/BloomExe/Publish/PublishHelper.cs#L588)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is it likely enough to care about that we don't have the first one in the list installed, and are using one of the others? Maybe that should be left for a later enhancement, even if it's possible.
</blockquote></details>

I added a comment about this possibility.
___
*[`src/BloomExe/Publish/PublishHelper.cs` line 606 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAdiJNb8CYZZ1cD-5kr:-OAsKswc8dXo7hntwJYz:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/db289ffc7bedb7ba5d42671721afd7f6b6e33a88/src/BloomExe/Publish/PublishHelper.cs#L606)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We might want to remove or comment out all the debug info before merging? I'm not sure. We don't do this so often in debug builds that it would be much nuisance.
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/BloomPub/BloomPubMaker.cs` line 852 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAdjLmq-lW0lN_R-xUG:-OAsKzt597KRrIOkF2vw:bymwrxu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/db289ffc7bedb7ba5d42671721afd7f6b6e33a88/src/BloomExe/Publish/BloomPub/BloomPubMaker.cs#L852)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Something funny here. I don't remember whether we ship all four variants of Andika in our readers. But if we do, we can probably remove any font whose name is Andika. And if we don't, then we probably can't safely remove Andika New Basic Bold, say, unless we're going to embed Andika Bold instead. (And maybe we SHOULD start shipping all versions of Andika as part of our readers, if we aren't already?)
</blockquote></details>

I think we've only been shipping Andika Regular, trying for a minimal file size impact.  I enhanced the check for Andika New Basic to include the style and weight.
___
*[`src/BloomExe/Publish/Epub/EpubMaker.cs` line 2849 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAdlDnMBlych6QwXFu-:-OAsPK0kBOZwE0s9Kj3W:b-e7zo6d) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/db289ffc7bedb7ba5d42671721afd7f6b6e33a88/src/BloomExe/Publish/Epub/EpubMaker.cs#L2849)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We don't do anything with this argument, so why have it?
</blockquote></details>

It should have been passed on the next method, which I've now done.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723)* status: all files reviewed, 5 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/FontProcessing/FontFileFinder.cs` line 117 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAdeZJN2BAt1C7GFj9v:-OAwdJrPB6tdEA-OII-S:b1c2z1f) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/db289ffc7bedb7ba5d42671721afd7f6b6e33a88/src/BloomExe/FontProcessing/FontFileFinder.cs#L117)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I've changed the code to return only one file at most, but to use a fallback for closest match if the exact style and weight don't have a matching file.  I also made this explicit in the method comments.
</blockquote></details>

I'm tempted to suggest changing it to GetFontFile() and just return one file or null, but (a) maybe not worth the effort, and (b) maybe when we do variable-weight we will be glad we can return more than one? Up to you; it's acceptable as-is.
___
*[`src/BloomExe/Publish/PublishHelper.cs` line 232 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAwcXoY530caHa5-coj:-OAwcXoY530caHa5-cok:b-aawxrj) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b491aafb9735cc7603b1535a1d3f0a28963084e2/src/BloomExe/Publish/PublishHelper.cs#L232)):*
> ```Smalltalk
>                 if (ReferenceEquals(info1, null) || ReferenceEquals(info2, null))
>                     return true;
>                 return !info1.Equals(info2);
> ```

I wouldn't bother mentioning this if there weren't other issues, but I prefer to reduce duplication by implementing != simply as "return ! info1 == info2". Not something I'd insist on if you prefer what you have.
___
*[`src/BloomExe/Publish/PublishHelper.cs` line 606 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAwcI461trnP5JaSJXY:-OAwcI461trnP5JaSJXZ:bc38vj) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b491aafb9735cc7603b1535a1d3f0a28963084e2/src/BloomExe/Publish/PublishHelper.cs#L606)):*
> ```Smalltalk
>             // use just the first one.  We don't need to worry about the fallback fonts, just the primary one.  It
>             // would be very unusual for the user not to have the primary font installed, but to have a fallback font
>             // installed that.
> ```

This new comment feels incomplete
___
*[`src/BloomExe/Publish/BloomPub/BloomPubMaker.cs` line 835 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAwbwmD7YaPjLMQY-IY:-OAwbwmD7YaPjLMQY-IZ:b-ea8kpd) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b491aafb9735cc7603b1535a1d3f0a28963084e2/src/BloomExe/Publish/BloomPub/BloomPubMaker.cs#L835)):*
> ```Smalltalk
>         /// find the files needed for those fonts.
>         /// Copy the font file for the normal style of that font family from the system font folder,
>         /// if permitted; or post a warning in progress if we can't embed it.
> ```

Sorry I missed this earlier, but this comment should be updated.
___
*[`src/BloomExe/Publish/BloomPub/BloomPubMaker.cs` line 837 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAwc45h43hvPvUumVU8:-OAwc45h43hvPvUumVU9:b8ual6t) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b491aafb9735cc7603b1535a1d3f0a28963084e2/src/BloomExe/Publish/BloomPub/BloomPubMaker.cs#L837)):*
> ```Smalltalk
>         /// if permitted; or post a warning in progress if we can't embed it.
>         /// Create an extra css file (fonts.css) which tells the book to find the font files for those font families
>         /// in the local folder, and insert a link to it into the book.
> ```

Is there anything we need to do to make fonts.css know about the additional font files we are copying?
___
*[`src/BloomExe/Publish/BloomPub/BloomPubMaker.cs` line 852 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAweAS4DFG3zwxObuhk:-OAweAS4DFG3zwxObuhl:b-c0r3ao) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b491aafb9735cc7603b1535a1d3f0a28963084e2/src/BloomExe/Publish/BloomPub/BloomPubMaker.cs#L852)):*
> ```Smalltalk
>                 x => x.fontName == defaultFont && x.fontStyle == "normal" && x.fontWeight == "400"
>             );
>             var boldAndika =
> ```

would it work to just do
fontsWanted.RemoveWhere(x => x.fontName == "Andika New Basic" && fontsWanted.Any( y => y.Name == defaultFont && y.fontStyle == x.fontStyle && y.fontWeight == x.fontWeight);
?
(Would still need one special case to remove ANB regular unconditionally)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/FontProcessing/FontFileFinder.cs` line 117 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAdeZJN2BAt1C7GFj9v:-OB1JBv73OzY2Krq09d4:b-5m4nzs) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/db289ffc7bedb7ba5d42671721afd7f6b6e33a88/src/BloomExe/FontProcessing/FontFileFinder.cs#L117)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm tempted to suggest changing it to GetFontFile() and just return one file or null, but (a) maybe not worth the effort, and (b) maybe when we do variable-weight we will be glad we can return more than one? Up to you; it's acceptable as-is.
</blockquote></details>

The whole point of variable weight fonts is that a single font file handles the different weights nicely.
I've changed the function to return just a single string, which might be null.
___
*[`src/BloomExe/Publish/PublishHelper.cs` line 232 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAwcXoY530caHa5-coj:-OB1Jneq0lvL5p27FMb7:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b491aafb9735cc7603b1535a1d3f0a28963084e2/src/BloomExe/Publish/PublishHelper.cs#L232)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I wouldn't bother mentioning this if there weren't other issues, but I prefer to reduce duplication by implementing != simply as "return ! info1 == info2". Not something I'd insist on if you prefer what you have.
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/PublishHelper.cs` line 606 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAwcI461trnP5JaSJXY:-OB1K8ES6bVpbOJqWHNB:b-dxxndy) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b491aafb9735cc7603b1535a1d3f0a28963084e2/src/BloomExe/Publish/PublishHelper.cs#L606)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This new comment feels incomplete
</blockquote></details>

The last sentence did end abruptly and ungrammatically.  I've finished off the sentence to make sense.  :-)
___
*[`src/BloomExe/Publish/BloomPub/BloomPubMaker.cs` line 835 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAwbwmD7YaPjLMQY-IY:-OB1Knv40wGGceY9__rX:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b491aafb9735cc7603b1535a1d3f0a28963084e2/src/BloomExe/Publish/BloomPub/BloomPubMaker.cs#L835)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Sorry I missed this earlier, but this comment should be updated.
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/BloomPub/BloomPubMaker.cs` line 837 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAwc45h43hvPvUumVU8:-OB1LY6a0OY92lGcnSVI:bl07656) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b491aafb9735cc7603b1535a1d3f0a28963084e2/src/BloomExe/Publish/BloomPub/BloomPubMaker.cs#L837)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is there anything we need to do to make fonts.css know about the additional font files we are copying?
</blockquote></details>

They're all listed in fontsWanted, and the code uses that list to generate fonts.css.
___
*[`src/BloomExe/Publish/BloomPub/BloomPubMaker.cs` line 852 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OAweAS4DFG3zwxObuhk:-OB1LVLo3UyiKZf0zm4J:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b491aafb9735cc7603b1535a1d3f0a28963084e2/src/BloomExe/Publish/BloomPub/BloomPubMaker.cs#L852)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

would it work to just do
fontsWanted.RemoveWhere(x => x.fontName == "Andika New Basic" && fontsWanted.Any( y => y.Name == defaultFont && y.fontStyle == x.fontStyle && y.fontWeight == x.fontWeight);
?
(Would still need one special case to remove ANB regular unconditionally)
</blockquote></details>

Done.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomExe/FontProcessing/FontFileFinder.cs` line 69 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OB1Sr4M7qwMDvA_Ayu3:-OB1Sr4N3B_uPy-dCfny:b-k3el29) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2e0bfd9b78fff3294c1f8d4bf620e10ede5c92b5/src/BloomExe/FontProcessing/FontFileFinder.cs#L69)):*
> ```Smalltalk
>         /// <returns>enumeration of file paths (possibly none) that contain data for the specified font name, and which
>         /// (as far as we can tell) we are allowed to embed.
>         /// Note that the enumeration contains either one file or none.  If a file specific to the requested style
> ```

Sorry, the comment now needs updating.

**Review by JohnThomson — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/FontProcessing/FontFileFinder.cs` line 69 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723#-OB1Sr4M7qwMDvA_Ayu3:-OB1VEe08Rvh13TxWjPt:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2e0bfd9b78fff3294c1f8d4bf620e10ede5c92b5/src/BloomExe/FontProcessing/FontFileFinder.cs#L69)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Sorry, the comment now needs updating.
</blockquote></details>

Done.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
