### PR TITLE
BL-4428 Remove need for Templates to be named Template

### PR DESCRIPTION
**Pull request by JohnThomson**
Now instead we look for a subfolder called "template"

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1564)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/Book.cs, line 1663 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1564#-KfI2EAsvu35GY_wlExr-r1-1663:-KfSOoWfz1_FRivpatUa:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/617bf824e965bffdafd7d4e273782ce918e6a634/src/BloomExe/Book/Book.cs#L1663)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

good catch
</blockquote></details>

Done.

---

*[src/BloomExe/web/controllers/PageTemplatesApi.cs, line 229 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1564#-KfI2EAsvu35GY_wlExs-r1-229:-KfSOpiG1VLDTdxeSq_S:b6p2jhp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/617bf824e965bffdafd7d4e273782ce918e6a634/src/BloomExe/web/controllers/PageTemplatesApi.cs#L229)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This comment made me realize there are some File operations just above your change in Book.cs which should use RobustFile, too. But that wasn't added in this PR...
</blockquote></details>

I've fixed the new one. For existing code, especially since there's another fairly major change to Book.cs pending, I suggest we make a card to at some point (start of next cycle?) switch all uses of File.whatever.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1564)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/web/controllers/PageTemplatesApi.cs, line 229 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1564#-KfI2EAsvu35GY_wlExs-r1-229:-KfSPlOzYYv1vWwN-WyJ:b8cin5w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/617bf824e965bffdafd7d4e273782ce918e6a634/src/BloomExe/web/controllers/PageTemplatesApi.cs#L229)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I've fixed the new one. For existing code, especially since there's another fairly major change to Book.cs pending, I suggest we make a card to at some point (start of next cycle?) switch all uses of File.whatever.
</blockquote></details>

Card created. Not seeing the change here, but I assume it is yet another instance of Reviewable not showing the latest.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1564)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/web/controllers/PageTemplatesApi.cs, line 229 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1564#-KfI2EAsvu35GY_wlExs-r1-229:-KfSQIa8fnNEkU6senbx:bc5hqx4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/617bf824e965bffdafd7d4e273782ce918e6a634/src/BloomExe/web/controllers/PageTemplatesApi.cs#L229)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Card created. Not seeing the change here, but I assume it is yet another instance of Reviewable not showing the latest.
</blockquote></details>

Hm. Nope just checked GitHub. I don't think this change made it in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1564)*

**Comment by JohnThomson** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/web/controllers/PageTemplatesApi.cs, line 229 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1564#-KfI2EAsvu35GY_wlExs-r1-229:-KfTBA_QDyq3NSs3iniH:b4rtwip) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/617bf824e965bffdafd7d4e273782ce918e6a634/src/BloomExe/web/controllers/PageTemplatesApi.cs#L229)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Hm. Nope just checked GitHub. I don't think this change made it in.
</blockquote></details>

I accidentally pushed the original change to master, but the fix got pushed to my fork. It's there now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1564)*

**Pull request merged**
