### PR TITLE
Remove some unused code

### PR DESCRIPTION
**Pull request by ermshiperete**

### CODE REVIEW

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/106/
Build succeeded

**Comment by davidmoore1** [comment]
Looks good to me +2

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/108/
Build succeeded

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/109/
Build succeeded

**Comment by JohnThomson** [comment]
JohnH does NOT want BloomServer removed. Although he has not had time to finish this work, it is a useful change we will probably finish one day.

**Comment by ermshiperete** [comment]
Would it make sense to have the BloomServer files on a separate branch?

**Comment by ermshiperete** [comment]
Offending commit removed.

**Comment by JohnThomson** [comment]
A separate branch for incomplete work sounds good to me.

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/131/
Test PASSed.

**Pull request merged**
