### PR TITLE
BL-6673 reinstate ctrl-space

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2906)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2906)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 226 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2906#-LRmvaeA-162Jk-2voYy:-LRmvaeA-162Jk-2voYz:b-bhmlgc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c365e87c7c846084c28ce1ddd3335ee7fb3255bd/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L226)):*
> ```XML
>     });
> 
>     $(document).keydown(e => {
> ```

Can you add a comment explaining why both this and the above removeFormat are both needed? Thx.

**Review by jsubloom — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2906)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 222 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2906#-LRn3lLY40MViJLMgrQd:-LRn3lLY40MViJLMgrQe:b-ekwpyz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1f0273b4a6d15e4d2a59bc19027e3ebce4ca1821/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L222)):*
> ```XML
> 
>     $(document).keydown(e => {
>         if (e.keyCode === 32 && e.ctrlKey) {
> ```


I suggest also having "&& !e.altKey".  I found that Ctrl+Alt+Space vs. Ctrl+Space have the same effect. IMO I do not think that we should expect Ctrl+Alt+Key to necessarily have the same effect as Ctrl+Key.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2906)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @hatton and @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 226 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2906#-LRmvaeA-162Jk-2voYy:-LRroTJX7Q8dcYPkmrnR:b7pqvpy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c365e87c7c846084c28ce1ddd3335ee7fb3255bd/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L226)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Can you add a comment explaining why both this and the above removeFormat are both needed? Thx.
</blockquote></details>

They aren't, and the old one has been removed. Somehow an incorrect, unfinished state of my changes got into the PR.
___
*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 222 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2906#-LRn3lLY40MViJLMgrQd:-LRrobzE0hwmOFki-nVj:b9udkw5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1f0273b4a6d15e4d2a59bc19027e3ebce4ca1821/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L222)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I suggest also having "&& !e.altKey".  I found that Ctrl+Alt+Space vs. Ctrl+Space have the same effect. IMO I do not think that we should expect Ctrl+Alt+Key to necessarily have the same effect as Ctrl+Key.
</blockquote></details>

I made it only work for ctrl-space, not if either shift or alt is pressed as well.

**Comment by andrew-polk** [comment]
___
*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 222 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2906#-LRn3lLY40MViJLMgrQd:-LRrzpnRCzQ1evJtBdRn:b-561xaw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1f0273b4a6d15e4d2a59bc19027e3ebce4ca1821/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L222)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I made it only work for ctrl-space, not if either shift or alt is pressed as well.
</blockquote></details>

I feel like there is a miscommunication here, so I'm going to clarify what I think each of you are saying.
Jeffrey is saying Ctrl+Alt+Space is removing formatting so we should add the check that Alt (and Shift?) *isn't* also pressed.
John is saying it already only works for Ctrl-Space.

**Comment by andrew-polk** [comment]
___
*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 222 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2906#-LRn3lLY40MViJLMgrQd:-LRs-Iac7E48qOHQPw5T:b9vcul8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1f0273b4a6d15e4d2a59bc19027e3ebce4ca1821/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L222)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I feel like there is a miscommunication here, so I'm going to clarify what I think each of you are saying.
Jeffrey is saying Ctrl+Alt+Space is removing formatting so we should add the check that Alt (and Shift?) *isn't* also pressed.
John is saying it already only works for Ctrl-Space.
</blockquote></details>

Oops. Ignore me. I didn't have the latest revision in Reviewable, apparently, and now see that John's comment was with regard to a change he did make after Jeffrey's comment.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2906)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Pull request merged**
