### PR TITLE
Add required epub accessibility metadata (BL-5895)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Code looks okay, but there are way too many questions in there which I am not qualified to answer.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 356 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LB7DLDR9Axrw60QKW-B:-LB7DLDSDF7g2Lsu-42d:b-wwa0jt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/144c4013d002bb3debae225af965a9614cc8b75c/src/BloomExe/Publish/Epub/EpubMaker.cs#L356)):*
> ```Smalltalk
> 					.Cast<XmlElement>()
> 					.Any(
> 						span => AudioProcessor.GetWavOrMp3Exists(Storage.FolderPath, span.Attributes["id"].Value) != null);
> ```

Looks like you fixed a bug here. Is this something we need to consider backporting? Or at least creating a card for so it can be tested?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-:-LB7Exbs1d4r5qVyaFSA:b7ivsb1)*

**Comment by StephenMcConnel** [comment]
Yes, I think John Thomson will have to look over this PR, and even then I suspect we'll have to live with some unanswered questions for awhile.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 356 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LB7DLDR9Axrw60QKW-B:-LB7SuB5AdBkU9iofXoz:b-eq1kwf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/144c4013d002bb3debae225af965a9614cc8b75c/src/BloomExe/Publish/Epub/EpubMaker.cs#L356)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like you fixed a bug here. Is this something we need to consider backporting? Or at least creating a card for so it can be tested?
</blockquote></details>

I'm not sure how this was even compiling to tell the truth.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-:-LB7SazJC0xTyaKcaVo6:b-5sqxhy)*

**Comment by andrew-polk** [comment]
*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 356 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LB7DLDR9Axrw60QKW-B:-LB7W1wD3QBqGzourkYz:bpq7tvh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/144c4013d002bb3debae225af965a9614cc8b75c/src/BloomExe/Publish/Epub/EpubMaker.cs#L356)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I'm not sure how this was even compiling to tell the truth.
</blockquote></details>

`true != null` is true 
and 
`false != null` is true
So this always returned true (as long as SafeSelectNodes returned something).

We should take a couple minutes to evaluate the impact of this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365)*

**Comment by StephenMcConnel** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 356 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LB7DLDR9Axrw60QKW-B:-LB8DxXBEHNjkXU-_igh:b3sj7ja) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/144c4013d002bb3debae225af965a9614cc8b75c/src/BloomExe/Publish/Epub/EpubMaker.cs#L356)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

`true != null` is true 
and 
`false != null` is true
So this always returned true (as long as SafeSelectNodes returned something).

We should take a couple minutes to evaluate the impact of this.
</blockquote></details>

The only effect I can see from studying the code is that epubs would always be marked as talking books if not told directly to publish without the sound files.  See ElectronicPublishView.SetupEpubControlContent().  That seems to be virtually the only place this method got called from (indirectly).

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 381 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LB7Q_ojCWUvF5Em7s-r:-LB82je31P0I-6Xyq6cm:b-vv43ci) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d7ec2c2232420da21a7df42720c29bebd759fe9/src/BloomExe/Publish/Epub/EpubMaker.cs#L381)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

If we have audio for the whole book (except possibly xmatter), we can probably make the (stronger) claim "auditory" (or, as above, "audiotory, visual" if we don't have audible image descriptions and think they may be essential to understand the content).
</blockquote></details>

I've replaced the comment lines above with a comment to this effect.  How hard would it be to detect full audio coverage?  Is it worth doing in this initial stage?

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 386 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LB7RfQZCBF2cD4l_qpH:-LB8Di2V1wn9Vu7LLOO8:b6cdwaw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d7ec2c2232420da21a7df42720c29bebd759fe9/src/BloomExe/Publish/Epub/EpubMaker.cs#L386)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Again, claiming this may require that ALL the non-xmatter text has audio. Or maybe just the fact that some of it does is enough. I can't find anything that says clearly either way, so I guess what you have is OK. Another question for Benetech? Do we have a list? If not consider making one.
</blockquote></details>

I started a list in the issue (BL-5895).

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 391 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LB7X2mJ5jcj4QDDsTpc:-LB840NDBx2Q8ju7KI2H:b2mxbix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d7ec2c2232420da21a7df42720c29bebd759fe9/src/BloomExe/Publish/Epub/EpubMaker.cs#L391)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

There's a few more 'always' ones, I suspect: looking at https://www.w3.org/wiki/WebSchemas/Accessibility, we could always state tableOfContents (albeit not very useful yet), and if we have image descriptions we can claim (I guess)  alternativeText and probably longDescription and (if description has audio) audioDescription. Maybe it's premature to do these until the image Description PR gets merged :-)
</blockquote></details>

Yes, I thought I'd wait on the image description related settings until those have been implemented.  I've added tableOfContents.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 419 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LB7Tj9u-pKJQKE4HthM:-LB84A67BKgdwXaEOA9X:b-h8hon2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d7ec2c2232420da21a7df42720c29bebd759fe9/src/BloomExe/Publish/Epub/EpubMaker.cs#L419)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

If the only images are our branding images and the CC ones, I doubt we should report the book as requiring image comprehension for understanding the content.
We have some utility functions like HtmlDom.GetImageElementUrl() that are designed to hide the ambiguity between img and background-image; could you use one of those rather than making this known in another place? Or at least put these functions there?
</blockquote></details>

I was wondering about those stock images.  I've revised the code to use HtmlDom.GetImageElementUrl() and to check for branding or licenses.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 356 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LB7DLDR9Axrw60QKW-B:-LB8JdCTABiUIRjljuap:b5xh5m7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/144c4013d002bb3debae225af965a9614cc8b75c/src/BloomExe/Publish/Epub/EpubMaker.cs#L356)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

The only effect I can see from studying the code is that epubs would always be marked as talking books if not told directly to publish without the sound files.  See ElectronicPublishView.SetupEpubControlContent().  That seems to be virtually the only place this method got called from (indirectly).
</blockquote></details>

And this bugfix might be worth backporting.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365)*

**Comment by JohnThomson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 381 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LB7Q_ojCWUvF5Em7s-r:-LBLkOVP7R1bYkRLlopD:blrvdzl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d7ec2c2232420da21a7df42720c29bebd759fe9/src/BloomExe/Publish/Epub/EpubMaker.cs#L381)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I've replaced the comment lines above with a comment to this effect.  How hard would it be to detect full audio coverage?  Is it worth doing in this initial stage?
</blockquote></details>

I would think it reasonable to assume full audio coverage if all text on a non-x-matter page has a associated recordings. (That is, all non-white-space text is covered by audio spans, and each corresponding recording exists). I believe it's generally understood that xmatter is not an essential part of the intellectual content of the work.
That might conceivably be too strong a requirement...I can vaguely imagine some text that doesn't need audio, like a stand-alone letter used as a page heading...but it would be a reasonable starting point.
For image descriptions, when we get those, I think we'd aim at consistency: if we say images must have descriptions in order to use plain 'textual', then we should require those descriptions to be recorded before claiming 'auditory' without 'visual'. If we think the images ARE important, then we could have 'auditory, visual' and even possibly 'auditory, textual' if the images have descriptions but no audio.
But I think I hold to my earlier theory that images are typically not essential to Bloom books, in which case, 'auditory' could be used if all the non-image-description non-x-matter text is recorded.
I tend to think that it IS worth doing. For a fully blind person, accessModeSufficient: auditory may well be the primary search criterion they use to find books they can use, so if we can provide it when it's true, doing so could be quite important. (Of course, where and how a blind person might make such a search for Bloom books in a minority language remains to be determined...)
Comprehension questions might eventually be another special case to ask Benetech about...but we don't (yet?) support them in epubs.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 386 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LB7RfQZCBF2cD4l_qpH:-LBLlVwL3-2orrZBgrZ5:b-jvp2za) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d7ec2c2232420da21a7df42720c29bebd759fe9/src/BloomExe/Publish/Epub/EpubMaker.cs#L386)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I started a list in the issue (BL-5895).
</blockquote></details>

I think they will easily get lost there, especially as we develop questions about multiple cards. How about a google doc? If not as a place to put them all, it could at least list the cards that have Benetech questions on them.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 428 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LBLm6dc5h-xrY0j-QTr:-LBLm6dc5h-xrY0j-QTs:b5at04f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ddfeeb88439f61e17ce2a139bba69cb8e6ef1829/src/BloomExe/Publish/Epub/EpubMaker.cs#L428)):*
> ```Smalltalk
> 			{
> 				var className = image.GetOptionalStringAttribute("class", "");
> 				switch (className)
> ```

Two thoughts: I'm nervous about this code assuming that branding and license images will never have any other classes. Don't we have a 'hasClass' or similar utility function somewhere?
I wonder whether it's also worth not counting any occurrences of placeholder.png. Of course, there shouldn't be any in a book ready to publish...

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 381 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LB7Q_ojCWUvF5Em7s-r:-LBN7g-J7K9njxgJttbr:bg3arb3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d7ec2c2232420da21a7df42720c29bebd759fe9/src/BloomExe/Publish/Epub/EpubMaker.cs#L381)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I would think it reasonable to assume full audio coverage if all text on a non-x-matter page has a associated recordings. (That is, all non-white-space text is covered by audio spans, and each corresponding recording exists). I believe it's generally understood that xmatter is not an essential part of the intellectual content of the work.
That might conceivably be too strong a requirement...I can vaguely imagine some text that doesn't need audio, like a stand-alone letter used as a page heading...but it would be a reasonable starting point.
For image descriptions, when we get those, I think we'd aim at consistency: if we say images must have descriptions in order to use plain 'textual', then we should require those descriptions to be recorded before claiming 'auditory' without 'visual'. If we think the images ARE important, then we could have 'auditory, visual' and even possibly 'auditory, textual' if the images have descriptions but no audio.
But I think I hold to my earlier theory that images are typically not essential to Bloom books, in which case, 'auditory' could be used if all the non-image-description non-x-matter text is recorded.
I tend to think that it IS worth doing. For a fully blind person, accessModeSufficient: auditory may well be the primary search criterion they use to find books they can use, so if we can provide it when it's true, doing so could be quite important. (Of course, where and how a blind person might make such a search for Bloom books in a minority language remains to be determined...)
Comprehension questions might eventually be another special case to ask Benetech about...but we don't (yet?) support them in epubs.
</blockquote></details>

Done.  I've added a method to check for full audio coverage of text on non-x-matter pages.  It doesn't check image descriptions since those haven't been implemented yet.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 386 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LB7RfQZCBF2cD4l_qpH:-LBMF5a38sLQYJwYpHuY:buzog2a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d7ec2c2232420da21a7df42720c29bebd759fe9/src/BloomExe/Publish/Epub/EpubMaker.cs#L386)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think they will easily get lost there, especially as we develop questions about multiple cards. How about a google doc? If not as a place to put them all, it could at least list the cards that have Benetech questions on them.
</blockquote></details>

Done.  Question copied to google doc (https://docs.google.com/document/d/1RXQ2gWZ6rOu6cJit19-LuLxQ4dQN1NBa8kf18tVVVmg).

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 428 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LBLm6dc5h-xrY0j-QTr:-LBMDolT6VIu-S6_gWeS:b-2rlryv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ddfeeb88439f61e17ce2a139bba69cb8e6ef1829/src/BloomExe/Publish/Epub/EpubMaker.cs#L428)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Two thoughts: I'm nervous about this code assuming that branding and license images will never have any other classes. Don't we have a 'hasClass' or similar utility function somewhere?
I wonder whether it's also worth not counting any occurrences of placeholder.png. Of course, there shouldn't be any in a book ready to publish...
</blockquote></details>

Done.  The class has a HasClass method that I wasn't aware of.  I added a check for placeHolder.png even though I think they're removed from the epub file.  I could be wrong about that...

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365)*

**Comment by JohnThomson** [comment]
Sorry, picked up a few more points...

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 381 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LB7Q_ojCWUvF5Em7s-r:-LBXJJZRAgSO1zYISYgg:byj9tvx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d7ec2c2232420da21a7df42720c29bebd759fe9/src/BloomExe/Publish/Epub/EpubMaker.cs#L381)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Done.  I've added a method to check for full audio coverage of text on non-x-matter pages.  It doesn't check image descriptions since those haven't been implemented yet.
</blockquote></details>

I don't think it will need changes for image Description, since those will be stored in bloom-editable divs much like other content.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 369 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LBX7Vmf0qO3hAatPWRz:-LBX7Vmf0qO3hAatPWS-:b-pqwt1r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6291b80a6a32302514ad8a3723631b0c9523ef45/src/BloomExe/Publish/Epub/EpubMaker.cs#L369)):*
> ```Smalltalk
> 			foreach (var page in book.RawDom.SafeSelectNodes("//div[@class]").Cast<XmlElement>())
> 			{
> 				if (!HasClass(page, "numberedPage"))
> ```

I don't suppose this class is ever applied to divs other than top-level pages, but it's a little odd to call a variable 'page' when many of them are not pages at all. Most similar code makes the xpath look for class bloom-page (though that's a little tricky and involves 'contains' because there may of course be other classes). 

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 371 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LBXAZwjEGSrxkMGNpE3:-LBXAZwjEGSrxkMGNpE4:bxtyt6n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6291b80a6a32302514ad8a3723631b0c9523ef45/src/BloomExe/Publish/Epub/EpubMaker.cs#L371)):*
> ```Smalltalk
> 				if (!HasClass(page, "numberedPage"))
> 					continue;
> 				foreach (var div in page.SafeSelectNodes(".//div[@contenteditable='true']").Cast<XmlElement>())
> ```

I'm not sure whether contenteditable is permanently stored for these divs, or only set in the current edit page...are you?
Various other places, especially talkingBook.getRecordableDivs(), find them by looking for class bloom-editable, so I think it would be better to do that here.
(I also find myself thinking that I've too long procrastinated making some class...probably HtmlDom...know in ONE place how to find all the page divs in a book, and how to find all the editable text divs in a page...)

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 418 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LBXCVwoBEnn8Dq1F7ey:-LBXCVwoBEnn8Dq1F7ez:bo6o0r4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6291b80a6a32302514ad8a3723631b0c9523ef45/src/BloomExe/Publish/Epub/EpubMaker.cs#L418)):*
> ```Smalltalk
> 
> 			// Including everything like this is probably the best we can do programmatically, unless we can detect full audio
> 			// coverage (even image descriptions?) and derive a simple "auditory" without "textual".  Really needs author input.
> ```

Seems we now are doing this so part of this comment is obsolete?

---

*[src/BloomTests/Publish/ExportEpubTests.cs, line 296 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LBXFbrUCirM2L74dFCK:-LBXFbrUCirM2L74dFCL:b-mszgnm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6291b80a6a32302514ad8a3723631b0c9523ef45/src/BloomTests/Publish/ExportEpubTests.cs#L296)):*
> ```Smalltalk
> 				}
> 				Assert.IsFalse(foundOther, "Unrecognized mode in accessModeSufficient in manifest");
> 				if (!hasFullAudio)
> ```

As I understand it, the only situation where we would not find accessModeSufficient: textual is if the book has audio with NO corresponding text...like a partly-transcribed SayMore recording. I don't think that's possible in Bloom. So I don't think we need the condition here.
I don't really think validation based on finding individual properties is enough. Sorry, I should have caught this earlier. https://github.com/daisy/epub-revision-a11y/wiki/ePub-3.1-Accessibility--Proposal-To-Schema.org has very helpful examples, though it predates the standard and may not be exactly right about everything. But it's important, for example, that a book only partly recorded has accessMode: textual and accessMode: auditory (there IS text and there IS sound) and accessModeSufficient: textual (you can read it ALL in text) but NOT accessModeSufficient: auditory (you can't get it ALL by listening); I think it should also have accessModeSufficient: textual, auditory indicating that you can use a combination of reading and listening to get it ALL. (For example, you can listen to the recorded parts on your way to work and read the rest.)
OTOH one that is fully recorded should have all three: "textual", "auditory", "textual, auditory" since you can get it all by reading, listening, or a combination.
And if I'm reading it right, if it has pictures (but we're assuming they're nonessential), it should also have the combinations of the above two or three with 'visual'.

---

*[src/BloomTests/Publish/ExportEpubTests.cs, line 1443 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LBXIi-o0n9FmUOiDf-h:-LBXIi-o0n9FmUOiDf-i:b-lmwtai) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6291b80a6a32302514ad8a3723631b0c9523ef45/src/BloomTests/Publish/ExportEpubTests.cs#L1443)):*
> ```Smalltalk
> 			var hasFullAudio = EpubMaker.HasFullAudioCoverage(book);
> 			Assert.IsFalse(hasFullAudio, "HasFullAudioCoverage should return false when an audio file is missing.");
> 			MakeEpub("output", "HasFullAudioCoverage_ReturnsTrue", book);
> ```

I think the idea is that the second argument of MakeEpub is a unique folder name for the book based on the test name. You're using the same one in several tests.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-:-LBXJ_B42kH1XNxxuEXO:b-9klyco)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 381 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LB7Q_ojCWUvF5Em7s-r:-LBXmxid1s5KEUm-AZVd:b-gjwy3t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d7ec2c2232420da21a7df42720c29bebd759fe9/src/BloomExe/Publish/Epub/EpubMaker.cs#L381)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't think it will need changes for image Description, since those will be stored in bloom-editable divs much like other content.
</blockquote></details>

OK, I'll take your word for it.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 369 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LBX7Vmf0qO3hAatPWRz:-LBXZMwd89Dlnl0tjrg6:b-575u14) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6291b80a6a32302514ad8a3723631b0c9523ef45/src/BloomExe/Publish/Epub/EpubMaker.cs#L369)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't suppose this class is ever applied to divs other than top-level pages, but it's a little odd to call a variable 'page' when many of them are not pages at all. Most similar code makes the xpath look for class bloom-page (though that's a little tricky and involves 'contains' because there may of course be other classes). 
</blockquote></details>

I've renamed the variable, but I don't know a really good name for it.  I hesitate to just use 'x' however.  :-)

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 371 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LBXAZwjEGSrxkMGNpE3:-LBXcUUS4WFypFDLpXqO:bd72ljt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6291b80a6a32302514ad8a3723631b0c9523ef45/src/BloomExe/Publish/Epub/EpubMaker.cs#L371)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm not sure whether contenteditable is permanently stored for these divs, or only set in the current edit page...are you?
Various other places, especially talkingBook.getRecordableDivs(), find them by looking for class bloom-editable, so I think it would be better to do that here.
(I also find myself thinking that I've too long procrastinated making some class...probably HtmlDom...know in ONE place how to find all the page divs in a book, and how to find all the editable text divs in a page...)
</blockquote></details>

contenteditable seems to be all over the book.htm files.  (Whether or not it should be is another question.)  It's set wherever class bloom-editable exists.  But I can change the code.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 418 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LBXCVwoBEnn8Dq1F7ey:-LBXmqSA3n6q5fFgYc3V:b-m1z0jv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6291b80a6a32302514ad8a3723631b0c9523ef45/src/BloomExe/Publish/Epub/EpubMaker.cs#L418)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Seems we now are doing this so part of this comment is obsolete?
</blockquote></details>

Done.  revised the comment

---

*[src/BloomTests/Publish/ExportEpubTests.cs, line 296 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LBXFbrUCirM2L74dFCK:-LBXs2Dx-m9ssMIz4IEe:b-ho4gb7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6291b80a6a32302514ad8a3723631b0c9523ef45/src/BloomTests/Publish/ExportEpubTests.cs#L296)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

As I understand it, the only situation where we would not find accessModeSufficient: textual is if the book has audio with NO corresponding text...like a partly-transcribed SayMore recording. I don't think that's possible in Bloom. So I don't think we need the condition here.
I don't really think validation based on finding individual properties is enough. Sorry, I should have caught this earlier. https://github.com/daisy/epub-revision-a11y/wiki/ePub-3.1-Accessibility--Proposal-To-Schema.org has very helpful examples, though it predates the standard and may not be exactly right about everything. But it's important, for example, that a book only partly recorded has accessMode: textual and accessMode: auditory (there IS text and there IS sound) and accessModeSufficient: textual (you can read it ALL in text) but NOT accessModeSufficient: auditory (you can't get it ALL by listening); I think it should also have accessModeSufficient: textual, auditory indicating that you can use a combination of reading and listening to get it ALL. (For example, you can listen to the recorded parts on your way to work and read the rest.)
OTOH one that is fully recorded should have all three: "textual", "auditory", "textual, auditory" since you can get it all by reading, listening, or a combination.
And if I'm reading it right, if it has pictures (but we're assuming they're nonessential), it should also have the combinations of the above two or three with 'visual'.
</blockquote></details>

If we have full audio coverage, then accessModeSufficient can be simply auditory.  If we don't, then textual must be included.  I've added comments to this effect to try to make the test clearer.
The link is useful.  I've added it to the code.

---

*[src/BloomTests/Publish/ExportEpubTests.cs, line 1443 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LBXIi-o0n9FmUOiDf-h:-LBXqT8z8I5vt7jhCTOv:b-2dmme8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6291b80a6a32302514ad8a3723631b0c9523ef45/src/BloomTests/Publish/ExportEpubTests.cs#L1443)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think the idea is that the second argument of MakeEpub is a unique folder name for the book based on the test name. You're using the same one in several tests.
</blockquote></details>

oops.  Fixed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 376 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LB7Oqwr7dPZr3LMx8lh:-LBXxTBC2_UIeWLmyYi6:b3bfotz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4d7ec2c2232420da21a7df42720c29bebd759fe9/src/BloomExe/Publish/Epub/EpubMaker.cs#L376)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Technically, I think it would depend on whether looking at the images is essential to understanding the content of the book. If they don't have descriptions and are important, we'd use accessModeSufficient "textual, visual" but not just textual. (accessModeSufficient: A list of single or combined accessModes that are sufficient to understand all the intellectual content of a resource.)
But unless we add UI, there's no way for us to know that. Most of our books you can probably get the main points by simply reading. Including both probably gives at least a hint that  visual may add something.
</blockquote></details>

I think this requires author input (UI) to know whether images are essential.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365)*

**Comment by StephenMcConnel** [comment]
I think https://docs.google.com/document/d/1RXQ2gWZ6rOu6cJit19-LuLxQ4dQN1NBa8kf18tVVVmg has that list of questions for Benetech.

---

Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-:-LBXxahM-vEX9OqHdTup:bibsf2a)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 369 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LBX7Vmf0qO3hAatPWRz:-LBbWazE6PjS9diGbxpL:b-vxjwhd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6291b80a6a32302514ad8a3723631b0c9523ef45/src/BloomExe/Publish/Epub/EpubMaker.cs#L369)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I've renamed the variable, but I don't know a really good name for it.  I hesitate to just use 'x' however.  :-)
</blockquote></details>

You're right, it's a tricky problem. Maybe I shouldn't have complained...you want the variable to be a page, and you immediately continue the loop if it isn't...maybe what you had was better. But I doubt it's worth another iteration.

---

*[src/BloomTests/Publish/ExportEpubTests.cs, line 296 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-LBXFbrUCirM2L74dFCK:-LBbXD9-29l2WfJoz-94:br3a24s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6291b80a6a32302514ad8a3723631b0c9523ef45/src/BloomTests/Publish/ExportEpubTests.cs#L296)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

If we have full audio coverage, then accessModeSufficient can be simply auditory.  If we don't, then textual must be included.  I've added comments to this effect to try to make the test clearer.
The link is useful.  I've added it to the code.

</blockquote></details>

I like the way it ended up. Much clearer.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365#-:-LBbWIFGBAGaOrH_ANBF:bnfp4nl)*

**Pull request merged**
