### PR TITLE
Use C# StartupScreenManager for React ForumInvitationDialog (BL-12410)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This prevents the AutoUpdateDialog and ForumInvitationDialog from appearing at the same time.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6072)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6072)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Workspace/WorkspaceView.cs` line 1093 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6072#-NcZTQNN61A-m0wV9vpl:-NcZTQNN61A-m0wV9vpm:bq67hy7) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cc413107889bbc07a6d86e175f21f861e54406e2/src/BloomExe/Workspace/WorkspaceView.cs#L1093)):*
> ```Smalltalk
> 		private void ShowForumInvitationDialogIfNeeded()
> 		{
> 			if (Settings.Default.ForumInvitationAcknowledged)
> ```

Rather than converting the dialog from pure react into a Winforms ReactDialog, could we instead have this method just call something like 
`_webSocketServer.LaunchDialog("ForumInvitationDialog", new DynamicJson());`
?
Looks like it was already created with `useEventLaunchedBloomDialog` which would consume that websocket event.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6072)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Workspace/WorkspaceView.cs` line 1113 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6072#-NcZcH0m3zWnwG-NQBwM:-NcZcH0n2kYF864erzx1:b-ob9sxh) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cc413107889bbc07a6d86e175f21f861e54406e2/src/BloomExe/Workspace/WorkspaceView.cs#L1113)):*
> ```Smalltalk
> 						dlg.ShowDialog(this);
> 					}
> 				}, shouldHideSplashScreen: true, lowPriority: false);
> ```

It would be hard to imagine anything *lower* priority than this. So if `lowPriority: false` is actually needed, it would be good to comment that.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6072)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @StephenMcConnel)

___
*[`src/BloomExe/Workspace/WorkspaceView.cs` line 1093 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6072#-NcZTQNN61A-m0wV9vpl:-NcZcckA6mDbofgsDqWY:bwui4py) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cc413107889bbc07a6d86e175f21f861e54406e2/src/BloomExe/Workspace/WorkspaceView.cs#L1093)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Rather than converting the dialog from pure react into a Winforms ReactDialog, could we instead have this method just call something like 
`_webSocketServer.LaunchDialog("ForumInvitationDialog", new DynamicJson());`
?
Looks like it was already created with `useEventLaunchedBloomDialog` which would consume that websocket event.
</blockquote></details>

Along the same line, we then wouldn't need the `WireupForWinforms()`.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6072)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomExe/Workspace/WorkspaceView.cs` line 1093 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6072#-NcZTQNN61A-m0wV9vpl:-NcZcUVz6lpnSLXZV70k:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cc413107889bbc07a6d86e175f21f861e54406e2/src/BloomExe/Workspace/WorkspaceView.cs#L1093)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Along the same line, we then wouldn't need the `WireupForWinforms()`.
</blockquote></details>

Done.
___
*[`src/BloomExe/Workspace/WorkspaceView.cs` line 1113 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6072#-NcZcH0m3zWnwG-NQBwM:-NccwWIA9J1h6PJnNtg5:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cc413107889bbc07a6d86e175f21f861e54406e2/src/BloomExe/Workspace/WorkspaceView.cs#L1113)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

It would be hard to imagine anything *lower* priority than this. So if `lowPriority: false` is actually needed, it would be good to comment that.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6072)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Review by andrew-polk — APPROVED** [review]
> Dismissed @hatton from a discussion.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6072)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
