### PR TITLE
Detect renames; verify deletes using tombstones (BL-10195 and BL-10124)

### PR DESCRIPTION
**Pull request by JohnThomson**
Also, deletes during sync move book to recycle bin

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4595)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4595)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 147 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4595#-Melht0X4ZPQ3DAOSNxL:-Melht0X4ZPQ3DAOSNxM:bs4ngez) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c555fcba92fd7331c64553542ffec96ba97c4f32/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L147)):*
> ```Smalltalk
> 			var pathToBookFileInRepo = GetPathToBookFileInRepo(Path.GetFileName(bookFolderPath));
> 			var pathForTombstone = Path.ChangeExtension(pathToBookFileInRepo, ".tombstone");
> 			return !RobustFile.Exists(pathToBookFileInRepo) && RobustFile.Exists(pathForTombstone);
> ```

Because of the way you've implemented this, perhaps it doesn't matter, but it still seems like it would be cleaner to delete a tombstone file if a user checks in a book with the name of an existing tombstone file?
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 175 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4595#-MelitHh0WDpI-i4COB2:-MelitHi5SYqMcEdoGlT:bt74ubq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c555fcba92fd7331c64553542ffec96ba97c4f32/src/BloomExe/TeamCollection/TeamCollection.cs#L175)):*
> ```Smalltalk
> 				if (SIL.PlatformUtilities.Platform.IsLinux || oldName.ToLowerInvariant() != bookFolderName.ToLowerInvariant())
> 					// no tombstone, we don't want others removing the book except as part of rename.
> 					DeleteBookFromRepo(oldName, false);
> ```

I didn't understand this comment at first; I initially parsed it as saying we were making this call because there is no tombstone.
Maybe this is clarity enough:
`DeleteBookFromRepo(oldName, makeTombstone: false);`
___
*[src/BloomExe/Utils/RobustZip.cs, line 58 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4595#-Mele1757XKIM9dm0_OQ:-Mele1757XKIM9dm0_OR:bazrbls) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c555fcba92fd7331c64553542ffec96ba97c4f32/src/BloomExe/Utils/RobustZip.cs#L58)):*
> ```
> using (var instream = zipFile.GetInputStream(entry))
> ```
Shouldn't this be in an else?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4595)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 147 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4595#-Melht0X4ZPQ3DAOSNxL:-MezRcxC-G-xlQZGEorI:ba3v1x1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c555fcba92fd7331c64553542ffec96ba97c4f32/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L147)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Because of the way you've implemented this, perhaps it doesn't matter, but it still seems like it would be cleaner to delete a tombstone file if a user checks in a book with the name of an existing tombstone file?
</blockquote></details>

Done. (I think it's worth keeping the check here, though, just in case now or later we miss some way of getting the .bloom back without deleting it. For example, a team admin restoring a backup might not think to delete the tombstone.)
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 175 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4595#-MelitHh0WDpI-i4COB2:-MezSHob1TApRpZDr1kM:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c555fcba92fd7331c64553542ffec96ba97c4f32/src/BloomExe/TeamCollection/TeamCollection.cs#L175)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I didn't understand this comment at first; I initially parsed it as saying we were making this call because there is no tombstone.
Maybe this is clarity enough:
`DeleteBookFromRepo(oldName, makeTombstone: false);`

</blockquote></details>

Done.
___
*[src/BloomExe/Utils/RobustZip.cs, line 58 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4595#-Mele1757XKIM9dm0_OQ:-MezT2QE6N7wqwTf0MmU:b-376vyb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c555fcba92fd7331c64553542ffec96ba97c4f32/src/BloomExe/Utils/RobustZip.cs#L58)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> using (var instream = zipFile.GetInputStream(entry))
> ```
Shouldn't this be in an else?
</blockquote></details>

Done. Good catch.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4595)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 147 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4595#-Melht0X4ZPQ3DAOSNxL:-MeziHsF7glInlh4ud6n:b-muttlx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c555fcba92fd7331c64553542ffec96ba97c4f32/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L147)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done. (I think it's worth keeping the check here, though, just in case now or later we miss some way of getting the .bloom back without deleting it. For example, a team admin restoring a backup might not think to delete the tombstone.)
</blockquote></details>

 I wouldn't think tombstones should know *anything* about file names, but only ids? I suppose that puts further pressure on keeping book ids unique. But the alternative seems like chaos?

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4595)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4595)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 147 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4595#-Melht0X4ZPQ3DAOSNxL:-Mf-Gl8OBgfwya7wXMmv:b7oy497) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c555fcba92fd7331c64553542ffec96ba97c4f32/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L147)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

 I wouldn't think tombstones should know *anything* about file names, but only ids? I suppose that puts further pressure on keeping book ids unique. But the alternative seems like chaos?
</blockquote></details>

 Bloom is, already, much more drastic about keeping IDs unique than I had previously realized. It checks them all at startup and if there are duplicates, it changes one of them.

The tombstone is wanted when Bloom notices that directory X, which contains a status file indicating it is part of the TC, does not correspond to any X.bloom in the repo. So at that point it can fairly readily get the ID of the book; I suppose we can then look for ID.tombstone instead of folderName.tombstone. I'll give it a go.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4595)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 147 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4595#-Melht0X4ZPQ3DAOSNxL:-Mf-wE_k8hGKPX1hZDVw:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c555fcba92fd7331c64553542ffec96ba97c4f32/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L147)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

 Bloom is, already, much more drastic about keeping IDs unique than I had previously realized. It checks them all at startup and if there are duplicates, it changes one of them.

The tombstone is wanted when Bloom notices that directory X, which contains a status file indicating it is part of the TC, does not correspond to any X.bloom in the repo. So at that point it can fairly readily get the ID of the book; I suppose we can then look for ID.tombstone instead of folderName.tombstone. I'll give it a go.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4595)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
