### PR TITLE
Improve UI for new leveled reader limits

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3917)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3917)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[DistFiles/localization/en/Bloom.xlf, line 2259 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3917#-MGP4Gmh93AfSiV4KOoy:-MGP4Gmh93AfSiV4KOoz:b-nc0dxv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f8c132453f5fbe417484944be569d5b2e86ff5e7/DistFiles/localization/en/Bloom.xlf#L2259)):*
> ```XML
>         <source xml:lang="en">this page</source>
>         <note>ID: EditTab.Toolbox.LeveledReaderTool.ThisPageLC</note>
>       </trans-unit>
> ```

Looks like this isn't used. If it should be, do we need to add a note for the translator to make this lower case?

Actually, I'm not finding most of these new EditTab.Toolbox.LeveledReaderTool.* ones being used. What am I missing?

**Review by jsubloom — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3917)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

___
*[DistFiles/localization/en/Bloom.xlf, line 2258 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3917#-MGP3wdKDbN2DsM9sO0E:-MGP3wdLCQGybQ2ALsy5:bb42s7c) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f8c132453f5fbe417484944be569d5b2e86ff5e7/DistFiles/localization/en/Bloom.xlf#L2258)):*
> ```XML
>       <trans-unit id="EditTab.Toolbox.LeveledReaderTool.ThisPageLC" sil:dynamic="true">
>         <source xml:lang="en">this page</source>
>         <note>ID: EditTab.Toolbox.LeveledReaderTool.ThisPageLC</note>
> ```

add a note explicitly stating that the translation should be in lowercase?
___
*[DistFiles/localization/en/Bloom.xlf, line 4348 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3917#-MGP5DWB1xGMXexqySiq:-MGP5DWB1xGMXexqySir:b5ibqg5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f8c132453f5fbe417484944be569d5b2e86ff5e7/DistFiles/localization/en/Bloom.xlf#L4348)):*
> ```XML
>       <trans-unit id="ReaderSetup.SentenceMaxWords2" sil:dynamic="true">
>         <source xml:lang="en">Per <g id="mgpw-1" ctype="x-html-strong">Sentence</g></source>
>         <note>ID: ReaderSetup.SentenceMaxWords</note>
> ```

This looks sufficiently complicated enough that a note is warranted.
___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts, line 456 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3917#-MGP8Npr-a5V2qpl2GIj:-MGP8Npr-a5V2qpl2GIk:b3bfs7z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f8c132453f5fbe417484944be569d5b2e86ff5e7/src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts#L456)):*
> ```
> [0]
> ```
Let's add more handling for if no elements are found. I guess we can return empty string pretty trivailly.
___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts, line 965 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3917#-MGP9ARg5JsBIaTHOOK3:-MGP9ARg5JsBIaTHOOK4:boo3dxy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f8c132453f5fbe417484944be569d5b2e86ff5e7/src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts#L965)):*
> ```
> id
> ```
I guess this is not new, but I was wondering why a variable called id gets passed as a class selector?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3917)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[DistFiles/localization/en/Bloom.xlf, line 2258 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3917#-MGP3wdKDbN2DsM9sO0E:-MGP_m4O-GeDy97Zd5Tu:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f8c132453f5fbe417484944be569d5b2e86ff5e7/DistFiles/localization/en/Bloom.xlf#L2258)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

add a note explicitly stating that the translation should be in lowercase?
</blockquote></details>

Done.
___
*[DistFiles/localization/en/Bloom.xlf, line 2259 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3917#-MGP4Gmh93AfSiV4KOoy:-MGP_MH089MtE7i5mqvh:b4hs6ak) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f8c132453f5fbe417484944be569d5b2e86ff5e7/DistFiles/localization/en/Bloom.xlf#L2259)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like this isn't used. If it should be, do we need to add a note for the translator to make this lower case?

Actually, I'm not finding most of these new EditTab.Toolbox.LeveledReaderTool.* ones being used. What am I missing?
</blockquote></details>

This PR, in addition to changing the dialog, adds a number of missing XLF strings from the original PR for this card. We decided to wait for UI review before adding them.
___
*[DistFiles/localization/en/Bloom.xlf, line 4348 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3917#-MGP5DWB1xGMXexqySiq:-MGPaYK983DIy_04IF-2:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f8c132453f5fbe417484944be569d5b2e86ff5e7/DistFiles/localization/en/Bloom.xlf#L4348)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

This looks sufficiently complicated enough that a note is warranted.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts, line 456 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3917#-MGP8Npr-a5V2qpl2GIj:-MGPbAaI8LMG-rpRFaec:b7xj4bm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f8c132453f5fbe417484944be569d5b2e86ff5e7/src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts#L456)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> [0]
> ```
Let's add more handling for if no elements are found. I guess we can return empty string pretty trivailly.
</blockquote></details>

I made it throw. This should not happen.
___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts, line 965 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3917#-MGP9ARg5JsBIaTHOOK3:-MGPc0fcCr1Kl58JZqJQ:bscaqsv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f8c132453f5fbe417484944be569d5b2e86ff5e7/src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts#L965)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> id
> ```
I guess this is not new, but I was wondering why a variable called id gets passed as a class selector?
</blockquote></details>

I added a comment which may help, and renamed the variable.

**Review by jsubloom — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3917)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3917)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
