### PR TITLE
Minor image import tweaks for handling BMP and TIFF images (BL-9377)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
These were intended for the earlier changeset, but inadvertantly were not
committed.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4190)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4190)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 58 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4190#-MTHQg9k7VAREMnejk8t:-MTHQg9lDiVxnSysJ5X1:b-55dguh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d95887f907f2756c55de90c34a0a88ae853c400c/src/BloomExe/ImageProcessing/ImageUtils.cs#L58)):*
> ```Smalltalk
> 			var currentPath = imageInfo.GetCurrentFilePath();
> 			if (!String.IsNullOrEmpty(currentPath) && HasJpegExtension(currentPath))
> 				return true;    // it must have been saved as a JPEG file even though loaded as something else
> ```

I think this needs a bit more explanation. Users are very capable of mistakes like starting with a tif file, reading that Bloom likes jpgs, and thinking they can convert it by changing the extension. Why would we believe the extension, if the file doesn't have the expected image info for a jpg? What consequences will there be, if it's NOT a jpg and we go ahead and treat it as such? Is there anything better we could do in those cases?
You might want to take a look at PalasoImage.GetCorrectImageExtension() and see if any of the ideas there are useful.
Similarly below

**Review by JohnThomson — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4190)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4190)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 58 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4190#-MTHQg9k7VAREMnejk8t:-MTMSF7tB62K9xH_r1gR:b-iptb82) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d95887f907f2756c55de90c34a0a88ae853c400c/src/BloomExe/ImageProcessing/ImageUtils.cs#L58)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think this needs a bit more explanation. Users are very capable of mistakes like starting with a tif file, reading that Bloom likes jpgs, and thinking they can convert it by changing the extension. Why would we believe the extension, if the file doesn't have the expected image info for a jpg? What consequences will there be, if it's NOT a jpg and we go ahead and treat it as such? Is there anything better we could do in those cases?
You might want to take a look at PalasoImage.GetCorrectImageExtension() and see if any of the ideas there are useful.
Similarly below
</blockquote></details>

The new check of imageInfo.GetCurrentFilePath() is pretty foolproof since that value is set only after saving the image, which is done only as jpeg or png and uses the right extension.
The old check of imageInfo.FileName has been around since John Hatton wrote it in 2015.  But if you think it should not be used any longer, I can agree to that.
Note that the taglib data for BMP and TIFF files do not include the original height and width values in my tests, so the file has probably been written to disk to the proper format.
But for the general case, doing a check along the lines of what PalasoImage.GetCorrectImageExtension() would be safest.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4190)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
