### PR TITLE
BL-6092 Fix capitalization of ePUB

### PR DESCRIPTION
**Pull request by gmartin7**
* also created appropriate l10n help keys and put
   them in the .xlf file

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2525)

### CODE REVIEW

**Comment by gmartin7** [comment]
Hoping to get Steve in a hangout soon to discuss this. In the meantime, I found several more l10n keys that didn't exist in the .xlf file. Most of this is new enough that the l10n keys were "todo" before, so it may not be a problem here anyway.

---

Review status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

---

*[DistFiles/localization/en/Bloom.xlf, line 2637 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2525#-LFrAzTv5JkDk6dCzy-z:-LFrhwQr95bBXDXcUtAK:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a42e20dccf63548de3ee1329efe5cb8d090e4226/DistFiles/localization/en/Bloom.xlf#L2637)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Gettings => Getting?
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/publish/epub/epubPublishUI.tsx, line 102 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2525#-LFrCYQAAZQ51ZxO_L-3:-LFrhvCq0_uJEOYVBYeS:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a42e20dccf63548de3ee1329efe5cb8d090e4226/src/BloomBrowserUI/publish/epub/epubPublishUI.tsx#L102)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Here too
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/publish/epub/epubPublishUI.tsx, line 120 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2525#-LFrCfBy0O1HVHjv3k38:-LFrirYz3R276i0Rne65:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a42e20dccf63548de3ee1329efe5cb8d090e4226/src/BloomBrowserUI/publish/epub/epubPublishUI.tsx#L120)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Don't see this corrected in the xlf
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2525#-:-LFroEFU4M_yC7aI4Kyj:b-7006uz)*

**Comment by gmartin7** [comment]
Review status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

---

*[src/BloomBrowserUI/publish/epub/epubPublishUI.tsx, line 102 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2525#-LFrCYQAAZQ51ZxO_L-3:-LFroweGAq0H2HM2VFaP:b-x056rj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a42e20dccf63548de3ee1329efe5cb8d090e4226/src/BloomBrowserUI/publish/epub/epubPublishUI.tsx#L102)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

These 3 help keys are also new ones that weren't previously in the .xlf file.

---

*[src/BloomBrowserUI/publish/epub/epubPublishUI.tsx, line 120 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2525#-LFrCfBy0O1HVHjv3k38:-LFrp9rO-YghK-YR2Itd:b-hqj2aa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a42e20dccf63548de3ee1329efe5cb8d090e4226/src/BloomBrowserUI/publish/epub/epubPublishUI.tsx#L120)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is the only changed l10n key that was already in the .xlf file.

---

*[src/BloomBrowserUI/publish/epub/epubPublishUI.tsx, line 51 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2525#-LFrohZS-MJ4mwsiQMsG:-LFrohZS-MJ4mwsiQMsH:b-h6ubu6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b545e60f4cdfaab083b8319c5936029420e82020/src/BloomBrowserUI/publish/epub/epubPublishUI.tsx#L51)):*
> ```XML
>                 <header>
>                     
>                     <H1 l10nKey="PublishTab.Epub.Title">Create an ePUB book</H1>
> ```

This is a new key that wasn't previously in the .xlf file.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2525)*

**Comment by gmartin7** [comment]
Review status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

---

*[src/BloomBrowserUI/publish/epub/epubPublishUI.tsx, line 120 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2525#-LFrCfBy0O1HVHjv3k38:-LFrplZa42VdqVjuRQUg:bz6c01j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a42e20dccf63548de3ee1329efe5cb8d090e4226/src/BloomBrowserUI/publish/epub/epubPublishUI.tsx#L120)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

This is the only changed l10n key that was already in the .xlf file.
</blockquote></details>

This one has been in our master branch 19 days.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2525)*

**Comment by gmartin7** [comment]
Steve had suggestions for notes if uploading a change was going to disapprove an already approved translation, but none of the strings in question have been translated yet on Crowdin, so I think we're okay.

---

Review status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

---

*[src/BloomBrowserUI/publish/epub/epubPublishUI.tsx, line 120 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2525#-LFrCfBy0O1HVHjv3k38:-LFrvnJY-FWXh3eGmMY3:bai4fmv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a42e20dccf63548de3ee1329efe5cb8d090e4226/src/BloomBrowserUI/publish/epub/epubPublishUI.tsx#L120)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

This one has been in our master branch 19 days.
</blockquote></details>

Verified that noone on Crowdin has translated this string yet, much less approved it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2525#-:-LFrvxn29pe62bMcdOi9:b-2ueeth)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed, 1 unresolved discussion

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2525#-:-LFsypak9QKacluQvHgD:bnfp4nl)*

**Pull request merged**
