### PR TITLE
Remove branding from xMatter definitions (BL-5139)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1920)

### CODE REVIEW

**Comment by gmartin7** [comment]
I see you've removed branding stuff. How does the system work now?

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1920#-:-KxQ7yP8hH2CiH9L6aGB:b-ci09f8)*

**Comment by andrew-polk** [comment]
I have the same question

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1920#-:-KxSlgWFxe-VyZ5tWA7p:b-vt9cej)*

**Comment by JohnThomson** [comment]
I'm at least 90% sure this is NOT the fix we want...I think it will remove the whole branding feature.

**Comment by StephenMcConnel** [comment]
You're right.  I should either have made it clear that I was doubtful of this code and wanted advice, or sought advice before submitting a PR.

**Pull request closed without merging**
