### PR TITLE
Handle clobber problems (BL-9627)

### PR DESCRIPTION
**Pull request by JohnThomson**
Also various other improvements to status change handling

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4249)

### CODE REVIEW

**Review by hatton — COMMENTED** [review]
> Reviewed 2 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4249)* status: 2 of 19 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, line 79 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4249#-MUzBpg8Eh6D5Q3IGYwy:-MUzBpg933fUnj4Tep8G:b-61x34s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/355f7c847d74c04b5fabdbc41fe086cc3ac31be1/src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx#L79)):*
> ```XML
>             }
>         };
>         WebSocketManager.addListener("bookStatus", listener);
> ```

If find this style overly boilerplate-y, vs.

 ```
 WebSocketManager.addListener("bookStatus", (e) => 
      if (e.id === "reload") {
                setReload(oldValue => oldValue + 1);
            }
);
```

But if you're doing it on purpose because you like the other way, then ok.

But either way, let's clean this up with something like

```
useWebSocketListener("bookStatus", (e) =>
```

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 17 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4249)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4249)* status: 18 of 19 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, line 79 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4249#-MUzBpg8Eh6D5Q3IGYwy:-MUzNab_DACdiJdO8M2w:b-cvdrdk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/355f7c847d74c04b5fabdbc41fe086cc3ac31be1/src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx#L79)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

If find this style overly boilerplate-y, vs.

 ```
 WebSocketManager.addListener("bookStatus", (e) => 
      if (e.id === "reload") {
                setReload(oldValue => oldValue + 1);
            }
);
```

But if you're doing it on purpose because you like the other way, then ok.

But either way, let's clean this up with something like

```
useWebSocketListener("bookStatus", (e) =>
```

</blockquote></details>

Done. Sorry, forgot we had those functions.

**Review by hatton — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4249)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
