### PR TITLE
Fix problematic "Edit this book" button showing (BL-9687)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4284)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4284)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 392 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4284#-MVwjiRP9E_3BgFrJ_il:-MVwjiRP9E_3BgFrJ_im:bmxd8bu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2b21b447c7a881fffe958bf5214d80cff8dc9354/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L392)):*
> ```Smalltalk
> 		}
> 
> 		public bool IsTeamCollection
> ```

The API doesn't seem like the best place to be introducing public (to c#) wrappers around TC stuff, which *already* have a main class and a manager class.  If you find ` _tcManager.CollectionStatus != TeamCollectionStatus.None` unwieldy, then you could introduce a `_tcManager.IsTeamCollection` read only property.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4284)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/CollectionTab/LibraryBookView.cs, line 146 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4284#-MVwo_jq1IfQ__y7gqDQ:-MVwo_jq1IfQ__y7gqDR:b-kex2at) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2b21b447c7a881fffe958bf5214d80cff8dc9354/src/BloomExe/CollectionTab/LibraryBookView.cs#L146)):*
> ```Smalltalk
> 			_editBookButton.Visible = TeamCollectionApi.TheOneInstance.IsTeamCollection ?
> 				TeamCollectionApi.TheOneInstance.CanEditBook() :
> 				_bookSelection.CurrentSelection != null && _bookSelection.CurrentSelection.IsEditable;
> ```

The original logic in ShowBook was
` _bookSelection.CurrentSelection.IsEditable && !_bookSelection.CurrentSelection.HasFatalError`
The original logic in LoadBook was
`_bookSelection.CurrentSelection != null`

I think it makes sense to bring the two together, but maybe we should reintroduce `HasFatalError`?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4284)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomExe/CollectionTab/LibraryBookView.cs, line 146 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4284#-MVwo_jq1IfQ__y7gqDQ:-MVwrCop2MgEHJGlSIDB:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2b21b447c7a881fffe958bf5214d80cff8dc9354/src/BloomExe/CollectionTab/LibraryBookView.cs#L146)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The original logic in ShowBook was
` _bookSelection.CurrentSelection.IsEditable && !_bookSelection.CurrentSelection.HasFatalError`
The original logic in LoadBook was
`_bookSelection.CurrentSelection != null`

I think it makes sense to bring the two together, but maybe we should reintroduce `HasFatalError`?
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 392 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4284#-MVwjiRP9E_3BgFrJ_il:-MVwpLTG-P1QktSMleI_:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2b21b447c7a881fffe958bf5214d80cff8dc9354/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L392)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

The API doesn't seem like the best place to be introducing public (to c#) wrappers around TC stuff, which *already* have a main class and a manager class.  If you find ` _tcManager.CollectionStatus != TeamCollectionStatus.None` unwieldy, then you could introduce a `_tcManager.IsTeamCollection` read only property.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4284)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Pull request merged**
