### PR TITLE
BL-2017 Allow user to control which languages when uploading

### PR DESCRIPTION
**Pull request by JohnThomson**
specifically, which languages are advertised in the library

### CODE REVIEW

**Comment by hatton** [comment]
John I'm not clear what the algorithm is intended to be.  
Looking quickly the code, I came under the impression that
1) We would have a checkbox for each language that could possibly be intended to be part of the upload
2) Those languages which had an empty box would have their checkboxes unchecked.

Testing the program, I see I'm wrong on both counts:
1) making a book in a language but not filling in anything doesn't get you any check box for that language (which seems ok to me).
2) Having even one box filled in is enough to get a check. 

Thus you either get a checked checkbox, or you get no checkbox. The program will never show you an unchecked checkbox.

Is the later behavior what you're aiming for here?

**Comment by hatton** [comment]
Would it be inexpensive to remember the value of checkboxes? Suzanne, at least, tends to upload books several times. Some due to Bloom changes, sometimes due to mistakes noticed, sometimes she adds new languages. At the moment, if there was a bogus language in there, and she forgets to uncheck it, it will get through.

**Comment by JohnThomson** [comment]
I definitely got unchecked boxes while testing. The intended behavior is what you described in the issue:
- ignore xmatter
- check box for anything in body that has non-empty content
- checked iff everything that has content in any language has content in this

**Comment by JohnThomson** [comment]
I think the checked list is what we put in meta.json for parse.com to use, so it's already persisted. We could use the current algorithm (when fixed) if there is nothing in meta.json, otherwise use the algorithm to come up with the list of languages and the meta.json to decide which to check.
The only downside I see is that it would not automatically turn on a checkbox when you finish translating a particular language.

**Comment by JohnThomson** [comment]
If you confirm that the algorithm works as desired, should we go ahead with this PR and make a new card for persisting choices? This whole thing was originally meant to be 3.2.

**Comment by hatton** [comment]
OK, added http://issues.bloomlibrary.org/youtrack/issue/BL-2299 for persisting. I'm also going to merge this because I'm not finding time to do further testing, so by merging Len can help.

**Pull request merged**
