### PR TITLE
Update the Settings file to use the renamed Palaso library classes

### PR DESCRIPTION
**Pull request by StephenMcConnel**
[Review on Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/875)

### CODE REVIEW

**Comment by hatton** [comment]
Will this preserve the user's existing settings?

**Comment by StephenMcConnel** [comment]
A quick test showed that Bloom still remembered the last collection that was open, so it appears to preserve the settings.  But that was only a quick test.

**Comment by hatton** [comment]
Go ahead and test a combination of settings which are known to palaso vs. known only to Bloom. An example of the former would be settings protection. An example of the later would be "show experimental templates".

**Comment by StephenMcConnel** [comment]
Standard Bloom settings (such as "Show Experimental Commands") migrate fine from Bloom 3.3.4.0 to Bloom 3.5.0.0 (developer build).  Registration information is lost.  The older user.config file has registration information under the name Palaso.UI.WindowsForms.Registration.Registration, while the new user.config file uses SIL.Windows.Forms.Registration.Registration.  Interestingly, the old information is copied over, but the program doesn't recognize it.

The Settings Protection settings are stored separately in a folder that has a guid in its name.  The old file uses Palaso.UI.WIndowsForms.SettingsProtection.SettingsProtectionSettings as the section name while the new file uses SIL.Windows.Forms.SettingsProtection.SettingsProtectionSettings.  In this case, the old value is not copied across.

**Comment by JohnThomson** [comment]
This change definitely helps make some things work properly. Damien is working on the two kinds that don't and which require fixes in libpalaso, not Bloom. I think we can go ahead and merge this.

**Pull request merged**
