### PR TITLE
Add Adjust Timings UI

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762)

### CODE REVIEW

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762)* status: 5 of 17 files reviewed, 26 unresolved discussions (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 289 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCFgGGeEBkfY8Oq85qR:-OCJzKkJ2ON-NjK86rUW:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/DistFiles/localization/en/BloomMediumPriority.xlf#L289)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

These should have translate="no"
</blockquote></details>

Done.
___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 299 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCFg-QW0MQEjv0ynzpk:-OCJzV2i3CkmV7lJFO3P:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/DistFiles/localization/en/BloomMediumPriority.xlf#L299)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not the UX guy, but I think something like
> This is disabled because there is not a whole text box recording.

or 

> This is enabled when there is a whole text box recording.

would be more consistent with other tool tips, etc.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsControl.tsx` line 9 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCFsYWO8gtuc_g6abKl:-OCK-1lgAUI_NrG1IfQB:bu6m1jz) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsControl.tsx#L9)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This looked awkward enough that I played around with it and its usage.
I think this import can be removed.
Then the even more awkward
`const ws = ((WaveSurferNamespace as unknown) as any).create({`
can be
`const ws = WaveSurfer.create({`
and 
`const data = ws.decodedData?.getChannelData(0);`
can be
```
// decodeData is private
const data = (ws as any).decodedData?.getChannelData(0);
```

Later:
I tried all that and it doesn't actually work at runtime because of the RegionsPlugin.
So I don't know if there's anything worth trying to capture in comments about why these imports and usages are so wonky. But maybe you inherited this and don't understand it either...
</blockquote></details>

Yes, I inherited it and don't understand it. I added a comment based on your research.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsControl.tsx` line 12 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCFt8kD9d-8E58o986_:-OCK-98S8ZJ0VRJAWiKV:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsControl.tsx#L12)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

kBloomPurple isn't used.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsControl.tsx` line 14 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCFtBuT0KfgB1-s7KCz:-OCK-Bgg9nDIRr4Z7tJx:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsControl.tsx#L14)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Any reason to keep this?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsControl.tsx` line 23 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCFtevr9BnG93oeIsZ1:-OCK-WSM5W1yd4yoC9GN:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsControl.tsx#L23)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think url is the audio file?

Maybe audioFileUrl?

Same in the dialog
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsControl.tsx` line 26 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCFuAJ49gwQSGAV2xVo:-OCK-ysg7P6uJK85uNyX:b7hn225) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsControl.tsx#L26)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I find it really awkward to pass in the fontFamily.
If I'm understand what the dialog is doing to get and pass this in, we can just do that in this control?

But maybe it isn't worth it.
</blockquote></details>

I rather like that the control is low-level enough that it just knows about editing a set of labeled segments with end-times within a recording. It doesn't know about how we store them on bloom-editables, or even need to import audioRecording.ts. It seems reasonable to me that we tell it what font to use for the labels, and much less ugly than making yet another component have knowledge of how we do bloom-editables and their styles.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsControl.tsx` line 66 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCFzfDU-mKXH1Nh0UkB:-OCK15TR3X1FjgvHoI5b:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsControl.tsx#L66)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Please comment or remove console.logs
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsControl.tsx` line 188 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCGDmGs7fVQX5wuNgBI:-OCK1Xdo9NvWM4S8cwS2:b3eef39) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsControl.tsx#L188)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Typically when one has factors which are guesses and may be tweaked in the future, it is good to call them out as consts up front so they can be easily modified.
Up to you if its worth it.
</blockquote></details>

I already had the two constants, but you may be right that it's better to put them right with the comment.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsControl.tsx` line 360 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCGE_Fq9MDPIkdpZQKH:-OCK1tSpChyVI2Ec7ott:ba3dfob) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsControl.tsx#L360)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

No reason to have the fragments here, but I guess no harm.
</blockquote></details>

Removed
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsDialog.tsx` line 50 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCFuSoo1NzYmioPuf1y:-OCK1w7u-Usu9STQW05N:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsDialog.tsx#L50)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> setFont

setFontFamily
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsDialog.tsx` line 53 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCGEu_0BqrwiAScJnm9:-OCK2M8BABXi3lQJi5E2:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsDialog.tsx#L53)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This copy/paste still has CopyrightAndLicense...
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsDialog.tsx` line 73 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCFvN9o5WPyuYobOS92:-OCK2MsP5wSMj1KI3_yH:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsDialog.tsx#L73)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think we should remove or comment the console.log statements.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsDialog.tsx` line 87 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCGFDto2OWlezr89i7K:-OCK2vHT1GalN76mOkuP:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsDialog.tsx#L87)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

There is a constant for this class name.
Same below.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsDialog.tsx` line 110 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCGFW5z1xsQ64fsJiWf:-OCKW9JB-oZvLiY3fnwn:b-wz4bcq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsDialog.tsx#L110)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think you handled no segments above?
</blockquote></details>

I handled no-segments-because-we-hadn't-partitioned-the text-into-segments. The review referred to the possibility that there might still be none after we partitioned it. But I now think that's very unlikely, if not impossible. You motivated me to do some more testing and handle some more edge cases and write a couple of more comprehensive comments (and fix an independent bug or two).
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsDialog.tsx` line 145 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCGFiCo6p-tJbaIgCz6:-OCK3YJCBNNrCtIl8aPm:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsDialog.tsx#L145)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Any reason to leave this in?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsDialog.tsx` line 166 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCGFk-k7avTQGKi_DNh:-OCK3forDqQdVmILtkIm:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsDialog.tsx#L166)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Any reason to leave this in?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsDialog.tsx` line 171 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCGG-MH4KkIo2_Wk9wV:-OCK3y_y4ZIO0D-ioLAI:bij0n4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsDialog.tsx#L171)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; this comment doesn't make sense to me. 
What is #json?
Are we reading json from something?
</blockquote></details>

Something I inherited; maybe at some point the endTimes came back from the control as json?
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts` line 4140 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCFirgF0Z7Wh5A2tCcu:-OCKNN-hAuAnBoYKqT8I:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L4140)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I would prefer
```
if (!duration) 
  return []; // should never happen

...
```
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts` line 4146 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCFjIc-60hFwA3C_rCZ:-OCKNy8O9g-2ult3NMqp:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L4146)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this would be more readable as 
```
// Prevent any segment being completely empty (here and below).
// (Though, I don't think extractFragmentsAndSetSpanIdsForAudioSegmentation
// should actually make empty segments...belt and braces here.)
textLength += segment.fragmentText?.length || 1;
```

Below, you might want to pull it out as a const:
`const fragmentLength = segment.fragmentText?.length || 1;`
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts` line 4426 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCFhHp1-Ky5KrwezuUf:-OCKPf6X03PH-HRjwwRo:b-2pio1g) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L4426)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Yuck. We really have to call C# to call javascript?
Deserves some comments. 
But seems like there must be another way?
</blockquote></details>

I guess John just didn't know the trick...despite having come up with the whole bloomFrames thing and his long ago comment that "this is ... simple" :-)
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookAdvancedSection.tsx` line 286 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCFgVw689pW9vYw8AxS:-OCKR9VNAKSVRL5qb2YH:b3on6fz) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookAdvancedSection.tsx#L286)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> // review: should this be enableEditTimings

Should be `enableAdjustTimings`, methinks.
</blockquote></details>

I don't really think we need a new constant for a single && that's only used in one place. enableEditTimings has another requirement that props.lastTimingsFilePath is falsy. This button, I believe, properly doesn't care about that.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/sounds.d.ts` line 4 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCFfDf012CtbmbMztsO:-OCKS9Yq9T6qLRdcAibi:bkfeuwq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/sounds.d.ts#L4)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is this file needed?
Is it worth a comment about what it is for given how obtuse it is (at least to me)?
</blockquote></details>

Things build without it, so I removed it. May have had something to do with playing "splat"?
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/splat.mp3` line  at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCFf-VV73Z8CLxiLKsT:-OCKQVTV1usnne619ySi:bhjcjal) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/splat.mp3#L)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like this file was just being used for testing and can be removed.
</blockquote></details>

I think at one point John tried playing this between the 'before' context and the 'after' context when a boundary moved. But later he settled on just playing the 'after'. Removed.
___
*[`src/BloomExe/web/BloomServer.cs` line 39 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCFgnFsAo_K36FEn5fB:-OCKRg-fEqJXU8EhSsXG:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomExe/web/BloomServer.cs#L39)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like these were added in error (if you're making changes anyway).
</blockquote></details>

Done.
___
*[`src/BloomExe/web/controllers/EditingViewApi.cs` line 35 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCFgy0K18nIvzlivHBD:-OCKRs9t1xYtte50XxRY:b-2dvejd) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomExe/web/controllers/EditingViewApi.cs#L35)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is the `_ = ` to prevent some kind of resharper warning?
</blockquote></details>

I don't know...but I removed this new endpoint which we no longer need
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/adjustTimingsControl.css` line 1 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCFhm5d-Dg4OwntzQBe:-OCKN2vw1sR-Ul0rjTEK:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/adjustTimingsControl.css#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

My understanding is we are trying to get away from separate css files whenever possible.
Is it not possible to do this in emotion?
If not, it's probably worth a comment at the top of this file.

And it seems like this should be bounded by something like the id of the dialog.

And if we do need the external file, this should be .less, right?

Later:
Ah, I see you did put a comment on the import. But still seems like it is worth a comment here.

And the rest of the comments above still apply.
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookAdvancedSection.tsx` line 286 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCFgVw689pW9vYw8AxS:-OCKvmLA4tt6oxSzWXqo:b9mq7ch) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookAdvancedSection.tsx#L286)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't really think we need a new constant for a single && that's only used in one place. enableEditTimings has another requirement that props.lastTimingsFilePath is falsy. This button, I believe, properly doesn't care about that.
</blockquote></details>

Sorry; I must be missing something.
We have a const above:
```
const enableAdjustTimings =
        props.recordingMode === RecordingMode.TextBox && props.hasAudio;
```
We can just use it, right?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookAdvancedSection.tsx` line 286 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762#-OCFgVw689pW9vYw8AxS:-OCKwupXCcl2EK-LbG6C:bsgib2d) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/79ca722568a66d96122336a3b210f810f707ff12/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookAdvancedSection.tsx#L286)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; I must be missing something.
We have a const above:
```
const enableAdjustTimings =
        props.recordingMode === RecordingMode.TextBox && props.hasAudio;
```
We can just use it, right?
</blockquote></details>

No, I missed that it was already defined. I thought you were asking me to make a new constant. Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6762)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
