### PR TITLE
BL-11150 paste hyperlink upgrade

### PR DESCRIPTION
**Pull request by gmartin7**
* upgraded BloomMessageBox's button options

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5177)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5177)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @gmartin7 and @hatton)

___
*[`src/BloomExe/web/controllers/ExternalLinkController.cs` line 58 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5177#-N3PJlPt9yGmmGJcj8h2:-N3PJlPt9yGmmGJcj8h3:b2a944k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5f23e89c7d1381198b3e01aecb43d8aa7d255c43/src/BloomExe/web/controllers/ExternalLinkController.cs#L58)):*
> ```Smalltalk
> 		}
> 
> 		public static void HandleGenericLink(ApiRequest request)
> ```

Instead, use `HtmlHelpLink`

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5177)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @gmartin7 and @hatton)

___
*[`src/BloomBrowserUI/utils/BloomMessageBox.tsx` line 77 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5177#-N3PKeoX3ZtTusuuuNY6:-N3PKeoX3ZtTusuuuNY7:bm59exv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5f23e89c7d1381198b3e01aecb43d8aa7d255c43/src/BloomBrowserUI/utils/BloomMessageBox.tsx#L77)):*
> ```XML
>     ));
> 
>     const leftButton = props.leftButton ? (
> ```

I don't understand why you take a `MessagBoxButton` prop and then don't use it, but instead pull out a few bits from it and make a new button.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5177)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @gmartin7 and @hatton)

___
*[`src/BloomBrowserUI/utils/BloomMessageBox.tsx` line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5177#-N3PL5Fh2w4pukYy5T8n:-N3PL5Fh2w4pukYy5T8o:bq9nnby) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5f23e89c7d1381198b3e01aecb43d8aa7d255c43/src/BloomBrowserUI/utils/BloomMessageBox.tsx#L36)):*
> ```XML
>     icon?: "warning" | undefined; // Effectively an enumeration, which we will add to as needed
>     dialogEnvironment?: IBloomDialogEnvironmentParams;
>     fromTypescript?: boolean; // If undefined, the request came from C#-land and the response is via api.
> ```

It's awkward to name a programming language as part of a function signature. Would it be feasible to let the default mean a normal close and have the c# callers set a prop`closeWithAPICall`?

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5177)* status: 2 of 9 files reviewed, 4 unresolved discussions (waiting on @gmartin7 and @hatton)

___
*[`src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts` line 239 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5177#-N3RA7uB3WTFG9ijtblB:-N3RA7uB3WTFG9ijtblC:b-45gemb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fad8c9de52cf49f3ebb000508e182aa5cc8da4c7/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L239)):*
> ```XML
>     }
> 
>     private static ShowMessageBox(pasteFailureMsg: string, okText: string) {
> ```

This looks like it doesn't belong to the `BloomField`, but rather something more general.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5177)* status: 2 of 9 files reviewed, 5 unresolved discussions (waiting on @gmartin7 and @hatton)

___
*[`src/BloomExe/MiscUI/BloomMessageBox.cs` line 16 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5177#-N3RBSce34PWDBwzJgW5:-N3RBSce34PWDBwzJgW6:b-npvj8m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fad8c9de52cf49f3ebb000508e182aa5cc8da4c7/src/BloomExe/MiscUI/BloomMessageBox.cs#L16)):*
> ```Smalltalk
> 	public class BloomMessageBox
> 	{
> 		public static string Show(IWin32Window owner, string messageHtml, MessageBoxButton[] rightButtons, MessageBoxIcon icon = MessageBoxIcon.None)
> ```

I think we should have a `public static void ShowMessageBox`. You can then remove this `closeWithAPICall` from the generic show (unless I'm missing something and that is always relevant`.
___
*[`src/BloomExe/MiscUI/BloomMessageBox.cs` line 18 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5177#-N3RAwOt0Cz9NXdydo0G:-N3RAwOt0Cz9NXdydo0H:b-jschmo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fad8c9de52cf49f3ebb000508e182aa5cc8da4c7/src/BloomExe/MiscUI/BloomMessageBox.cs#L18)):*
> ```Smalltalk
> 		public static string Show(IWin32Window owner, string messageHtml, MessageBoxButton[] rightButtons, MessageBoxIcon icon = MessageBoxIcon.None)
> 		{
> 			var closeWithAPICall = true;
> ```

It add unnecessary complexity to make a variable just to hold a constant. If you want to say more than `true` you can say `true // closeWithAPICall`
___
*[`src/BloomExe/Spreadsheet/SpreadsheetExporter.cs` line 405 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5177#-N3RBsGRD4LaRgdMsRfQ:-N3RBsGRD4LaRgdMsRfR:ba7t0qy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fad8c9de52cf49f3ebb000508e182aa5cc8da4c7/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L405)):*
> ```Smalltalk
> 					var messageBoxButtons = new[]
> 					{
> 						new MessageBoxButton() { Text = "Overwrite", Id = "overwrite", Style = "outlined" },
> ```

These styling decisions don't want to be here. For example, default is always contained in our current theme.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
I'm still working through this but it is lunch time. I'll publish what I have so far.

> Reviewed 1 of 6 files at r1, 2 of 7 files at r2, 6 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5177#-:-N3_q2p-4bWDYM2QA4q2:bfj5epu)* status: 9 of 11 files reviewed, 8 unresolved discussions (waiting on @andrew-polk, @gmartin7, and @hatton)

___
*[`src/BloomBrowserUI/utils/bloomMessageBoxSupport.ts` line 9 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/5177#-N3_ndzxElJn1hKrTGdM:-N3_ndzxElJn1hKrTGdN:by67jsz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9e59efb8be5f0fb64808750de195a913488ea3a0/src/BloomBrowserUI/utils/bloomMessageBoxSupport.ts#L9)):*
> ```XML
> // This class contains static methods that simplify using the BloomMessageBox component, especially from
> // a non-React environment.
> export default class BloomMessageBoxSupport {
> ```

I'm missing why this is better in a separate class instead of being a static on BloomMessageBox itself.
___
*[`src/BloomBrowserUI/utils/bloomMessageBoxSupport.ts` line 24 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/5177#-N3_mihqEBr4CyT1iJni:-N3_mihqEBr4CyT1iJnj:br77dn8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9e59efb8be5f0fb64808750de195a913488ea3a0/src/BloomBrowserUI/utils/bloomMessageBoxSupport.ts#L24)):*
> ```XML
>         if (!container) {
>             // Fallback to alert
>             alert(englishText);
> ```

I don't know if this is just theoretical/pathological and we never expect it to happen (and thus it doesn't matter at all). But we could/should provide the translated text here.

(So this check for container would go after we get the result of the first `.asyncGetText` call.)
___
*[`src/BloomExe/MiscUI/BloomMessageBox.cs` line 48 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/5177#-N3_plEf-vXdMUYbLHDJ:-N3_plEf-vXdMUYbLHDK:b-lrf9u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9e59efb8be5f0fb64808750de195a913488ea3a0/src/BloomExe/MiscUI/BloomMessageBox.cs#L48)):*
> ```Smalltalk
> 		public bool Default;
> 		[JsonProperty("style")]
> 		public string Style; // Currently allowed options: contained, text, outlined
> ```

This doesn't seem to be used.

**Review by andrew-polk — COMMENTED** [review]
done with initial pass

> Reviewed 1 of 8 files at r4, 1 of 1 files at r5.
> Dismissed @hatton from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5177#-:-N3aBccl7S9Pm2EwSo43:b-2iumvm)* status: all files reviewed, 4 unresolved discussions (waiting on @gmartin7 and @hatton)

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5177)* status: 8 of 11 files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomBrowserUI/utils/bloomMessageBoxSupport.ts` line 9 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/5177#-N3_ndzxElJn1hKrTGdM:-N3_tcZD0tTXakOChWux:b-gdqal3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9e59efb8be5f0fb64808750de195a913488ea3a0/src/BloomBrowserUI/utils/bloomMessageBoxSupport.ts#L9)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm missing why this is better in a separate class instead of being a static on BloomMessageBox itself.
</blockquote></details>

BloomMessageBox is a functional component in a .tsx file, not a class .ts file. I didn't think I could put it in there.
___
*[`src/BloomBrowserUI/utils/bloomMessageBoxSupport.ts` line 24 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/5177#-N3_mihqEBr4CyT1iJni:-N3_tsr46vBLmVfdngIS:b-1anips) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9e59efb8be5f0fb64808750de195a913488ea3a0/src/BloomBrowserUI/utils/bloomMessageBoxSupport.ts#L24)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't know if this is just theoretical/pathological and we never expect it to happen (and thus it doesn't matter at all). But we could/should provide the translated text here.

(So this check for container would go after we get the result of the first `.asyncGetText` call.)
</blockquote></details>

I'm hoping it's just "theoretical/pathological" as you say, but I can move it. Done.
___
*[`src/BloomExe/MiscUI/BloomMessageBox.cs` line 48 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/5177#-N3_plEf-vXdMUYbLHDJ:-N3_u1zb61OnzyRJvDef:b2xv962) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9e59efb8be5f0fb64808750de195a913488ea3a0/src/BloomExe/MiscUI/BloomMessageBox.cs#L48)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This doesn't seem to be used.
</blockquote></details>

Oops. Nope, it shouldn't be there. Done.

**Pull request merged**
