### PR TITLE
BL-4845 Step 4 different for WiFi

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1776)

### CODE REVIEW

**Comment by JohnThomson** [comment]
https://github.com/BloomBooks/BloomDesktop/pull/1776 makes a first attempt at this.
I did not add the new localization ID to our xliff files since I think we're waiting on that until the UI is more stable.
Current version replaces the Send button with 
"To start a transfer, run BloomReader, tap the icon in the top left of the screen, and choose "Get Books from Desktop." You can do this on as many devices as you like. Make sure the device is connected to the same WiFi network."

**Comment by andrew-polk** [comment]
Feel free to ignore my nitpicking the words since this will likely get changed again as we solidify the interface.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 122 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1776#-KqevsORy6PQfNbexVWf:-KqevsORy6PQfNbexVWg:b829c3j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/87724eb2db368ace74984d6b6f2047391aa0a6cd/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L122)):*
> BloomReader

Bloom Reader

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 122 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1776#-KqevwY-Z6Wp0TWHE6FI:-KqevwY-Z6Wp0TWHE6FJ:b-nl6hkd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/87724eb2db368ace74984d6b6f2047391aa0a6cd/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L122)):*
> icon

I wonder if we can/should be more explicit

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 124 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1776#-Kqew3g5OWqjt81aeF5U:-Kqew3g5OWqjt81aeF5V:bwconru) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/87724eb2db368ace74984d6b6f2047391aa0a6cd/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L124)):*
> same

Same as what? I think this is confused by the previous statement referring to multiple devices, but same in this case refers to the machine running Bloom. Is it correct to say WiFi network when the Bloom machine doesn't have to be connected via WiFi?
How about "connected to the same network as the computer running Bloom."

---

*[src/BloomBrowserUI/react_components/l10n.tsx, line 109 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1776#-KqevcUyKcSUwQqGJ1pV:-KqevcUyKcSUwQqGJ1pW:b-3n68v4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/87724eb2db368ace74984d6b6f2047391aa0a6cd/src/BloomBrowserUI/react_components/l10n.tsx#L109)):*
> ```XML
> }
> 
> export class Para extends LocalizableElement<ILocalizationProps, ILocalizationState> {
> ```

Can a react class be one letter? If so, I would vote for P to be consistent with H1, etc. Otherwise, how about Paragraph?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1776#-:-KqewyWDd7gPQ_e9RP4g:batra2p)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 122 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1776#-KqevsORy6PQfNbexVWf:-KqhUfuNSI5t23Ttc2nr:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/87724eb2db368ace74984d6b6f2047391aa0a6cd/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L122)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> BloomReader

Bloom Reader
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 122 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1776#-KqevwY-Z6Wp0TWHE6FI:-KqhUhUb8tIuBVI07Yxh:b-4m1u47) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/87724eb2db368ace74984d6b6f2047391aa0a6cd/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L122)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> icon

I wonder if we can/should be more explicit
</blockquote></details>

I wonder, too, but how? UI designers talk about the "hamburger" icon but I have no idea whether users know it as that. There's an even more technical name in Android programming literature, but even I don't remember it.
Trying "three-lines icon"

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 124 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1776#-Kqew3g5OWqjt81aeF5U:-KqhVCsVTy76VT6pB1iI:b9w6msl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/87724eb2db368ace74984d6b6f2047391aa0a6cd/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L124)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> same

Same as what? I think this is confused by the previous statement referring to multiple devices, but same in this case refers to the machine running Bloom. Is it correct to say WiFi network when the Bloom machine doesn't have to be connected via WiFi?
How about "connected to the same network as the computer running Bloom."
</blockquote></details>

I just said "as this computer"...I think that should be clear enough.

---

*[src/BloomBrowserUI/react_components/l10n.tsx, line 109 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1776#-KqevcUyKcSUwQqGJ1pV:-KqhVceK38WyajGq2WpV:b-ljpx1q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/87724eb2db368ace74984d6b6f2047391aa0a6cd/src/BloomBrowserUI/react_components/l10n.tsx#L109)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Can a react class be one letter? If so, I would vote for P to be consistent with H1, etc. Otherwise, how about Paragraph?
</blockquote></details>

Yes, I started that way, and it didn't work, but neither did Para at first, then I realized I hadn't saved one of the files. Then I tossed up over consistency vs a very short, cryptic name. With you leaning that way I've changed it back, and it does work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1776)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1776#-:-KqhYF-KkViMmE-lkDos:bnfp4nl)*

**Pull request merged**
