### PR TITLE
BL-9460 Support cover images with border w/out using filter

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4169)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4169)* status: all files reviewed, 4 unresolved discussions (waiting on @hatton)

___
*[src/BloomBrowserUI/bookEdit/js/bloomImages.ts, line 310 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4169#-MShhRJgCgsWZiV_Tc1J:-MShhRJgCgsWZiV_Tc1K:b69bhj8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e08c755da98da95d4eb1dd0c079baf5a9a00b1/src/BloomBrowserUI/bookEdit/js/bloomImages.ts#L310)):*
> ```
> $(img).css("purpose", "for-bloom-scale-with-code");
> ```
I think this isn't needed anymore?
___
*[src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less, line 198 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4169#-MShb4AV4y7ardfrq8Dg:-MShb4AW6zuCe3lVCa5v:b-t73dnw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e08c755da98da95d4eb1dd0c079baf5a9a00b1/src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less#L198)):*
> ```
> We use "scale-down" instead of "unset"
> ```
Either this is obsolete or I simply don't understand what it means.
___
*[src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.pug, line 0 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4169#-MShdbsDCx-tWzsxONtf:-MShdbsDCx-tWzsxONtg:b-igabcy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e08c755da98da95d4eb1dd0c079baf5a9a00b1/src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.pug#L0)):*
Can this be simplified to 
```
block front-cover-image
	+standard-cover-image.bloom-scale-with-code
```
?
___
*[src/BloomExe/Book/BookData.cs, line 989 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4169#-MShco5P-ObuxjVMdvdL:-MShco5Q1wtyTBODyU_x:bba8acz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e08c755da98da95d4eb1dd0c079baf5a9a00b1/src/BloomExe/Book/BookData.cs#L989)):*
> ```Smalltalk
> 				// the corresponding data-book.
> 				// Remove "style" is normally what want to do, but there is one case where we do not. See BL-9460.
> 				// "style"
> ```

If I'm understanding correctly... and there's a good chance I'm not... this should be uncommented so that the general case does not copy it, but then your special code below does copy it.

And then I think the second unit test can have the false case.

But the presence of the two tests makes me wonder if my misunderstanding is due to not knowing which way the data is flowing...

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4169)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/js/bloomImages.ts, line 310 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4169#-MShhRJgCgsWZiV_Tc1J:-MSjZF6QBqTl_AMyZgP7:bb7pcsz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e08c755da98da95d4eb1dd0c079baf5a9a00b1/src/BloomBrowserUI/bookEdit/js/bloomImages.ts#L310)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> $(img).css("purpose", "for-bloom-scale-with-code");
> ```
I think this isn't needed anymore?
</blockquote></details>

true
___
*[src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less, line 198 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4169#-MShb4AV4y7ardfrq8Dg:-MSjZRujDdDoYpdhCljv:b-xxzbe) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e08c755da98da95d4eb1dd0c079baf5a9a00b1/src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less#L198)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> We use "scale-down" instead of "unset"
> ```
Either this is obsolete or I simply don't understand what it means.
</blockquote></details>

Thx, it is out of date. Updated.
___
*[src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.pug, line  at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4169#-MShdbsDCx-tWzsxONtf:-MSjZtLcB7KYrgmuLwQe:b1xahkb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e08c755da98da95d4eb1dd0c079baf5a9a00b1/src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.pug#L)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Can this be simplified to 
```
block front-cover-image
	+standard-cover-image.bloom-scale-with-code
```
?
</blockquote></details>

Oh, thanks for that.
___
*[src/BloomExe/Book/BookData.cs, line 989 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4169#-MShco5P-ObuxjVMdvdL:-MSjbDQh6vClUKS--Y_5:b-z2z3if) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e08c755da98da95d4eb1dd0c079baf5a9a00b1/src/BloomExe/Book/BookData.cs#L989)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If I'm understanding correctly... and there's a good chance I'm not... this should be uncommented so that the general case does not copy it, but then your special code below does copy it.

And then I think the second unit test can have the false case.

But the presence of the two tests makes me wonder if my misunderstanding is due to not knowing which way the data is flowing...
</blockquote></details>

Yeah, this stuff is really hard, took JT & I a long time. The data flows both ways.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4169)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.pug, line  at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4169#-MShdbsDCx-tWzsxONtf:-MSjcwXACSejsZNp7hFg:b-v6u0kv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e08c755da98da95d4eb1dd0c079baf5a9a00b1/src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.pug#L)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Oh, thanks for that.
</blockquote></details>

Alas it didn't work. I suspect something like this is possible, perhaps with a change the common macro, but I'm not up to figuring it out given the time pressure.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4169)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/Book/BookData.cs, line 989 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4169#-MShco5P-ObuxjVMdvdL:-MSmmVhoBgtyqpz37a5v:b-y98vqa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e08c755da98da95d4eb1dd0c079baf5a9a00b1/src/BloomExe/Book/BookData.cs#L989)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Yeah, this stuff is really hard, took JT & I a long time. The data flows both ways. 
</blockquote></details>

So is this the situation we have now?
style gets copied both directions for your specific case but only one direction for everything else?
If that's correct, I think this comment could be enhanced.

If the time pressure isn't worth holding this up for a comment (and we're ok with style getting copied one way for everything, of course), go ahead and merge.

**Pull request merged**
