### PR TITLE
BL-4233 Allow adding hints to template boxes

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1484)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts, line 1 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1484#-KcdVMwWAtYytjPQ2RjZ:-KcdVMwWAtYytjPQ2Rj_:b-kwxdxu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e3a194aadb320704d7ccd7da932e2cb1bdcc4082/src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts#L1)):*
> ```XML
> /// <reference path="../../typings/jquery/jquery.d.ts" />
> ```

Seems like your editor is using 2-space tabs rather than 4-space.

---

*[src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts, line 120 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1484#-KcdUsa6wZrUZt30kIqo:-KcdUsa6wZrUZt30kIqp:bdbziqi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e3a194aadb320704d7ccd7da932e2cb1bdcc4082/src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts#L120)):*
> ```XML
> 
>         // get the default text/stringId
>         var doNotLocalize = false
> ```

Not a big deal, but this is missing a semicolon.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug, line 41 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1484#-KcdSJf8TqTVaIcbU4QL:-KcdSJf8TqTVaIcbU4QM:bvajsap) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e3a194aadb320704d7ccd7da932e2cb1bdcc4082/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug#L41)):*
> ```Pug
> 				select#lang-select
> 				#hint-content(contenteditable="true")
> 		//- Here follows a skeleton implementation of tab 2
> ```

Depending on which of ours gets merged first, the other should remove these comments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1484)*

**Comment by andrew-polk** [comment]
Does this need a UI review by @Hatton?

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1484#-:-KcdW4FZ9MH1RJ7593md:b-3nhe1h)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts, line 1 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1484#-KcdVMwWAtYytjPQ2RjZ:-KcxZClzuHjjLZDYrgvi:bsqxwcw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e3a194aadb320704d7ccd7da932e2cb1bdcc4082/src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems like your editor is using 2-space tabs rather than 4-space.
</blockquote></details>

This has been difficult lately. Two spaces is generally intentional (at least for JavaScript/TypeScript). Our coding standard has
18.1 Use soft tabs (space character) set to 2 spaces. eslint: indent jscs: validateIndentation
But a lot of stuff seems to be using 4 spaces and I don't like having large blocks of whitespace-only change so I've sometimes elected to follow the current state of the file (and may sometimes even have mixed the two). Maybe we need to discuss this again as a group?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1484)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts, line 1 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1484#-KcdVMwWAtYytjPQ2RjZ:-Kcxwqp6C-ZWinaOPaTe:b-cn1slv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e3a194aadb320704d7ccd7da932e2cb1bdcc4082/src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts#L1)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This has been difficult lately. Two spaces is generally intentional (at least for JavaScript/TypeScript). Our coding standard has
18.1 Use soft tabs (space character) set to 2 spaces. eslint: indent jscs: validateIndentation
But a lot of stuff seems to be using 4 spaces and I don't like having large blocks of whitespace-only change so I've sometimes elected to follow the current state of the file (and may sometimes even have mixed the two). Maybe we need to discuss this again as a group?
</blockquote></details>

Hm. Once again we have a discrepancy between our .editorconfig and https://github.com/airbnb/javascript. And this time it is not a difference between js and ts. It does seem we need to discuss this a group again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1484)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts, line 1 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1484#-KcdVMwWAtYytjPQ2RjZ:-Kd2-fDPjyNBHuJ5BgWz:bx0p1ct) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e3a194aadb320704d7ccd7da932e2cb1bdcc4082/src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Hm. Once again we have a discrepancy between our .editorconfig and https://github.com/airbnb/javascript. And this time it is not a difference between js and ts. It does seem we need to discuss this a group again.
</blockquote></details>

We decided today to use the .editorconfig settings of 4-space indentations for js and ts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1484)*

**Comment by JohnThomson** [comment]
Given that it's only in master, maybe we can let JohnH react to it after it gets merged?

---

Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts, line 1 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1484#-KcdVMwWAtYytjPQ2RjZ:-Kd2rDVMV_hSlk7VTWbf:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e3a194aadb320704d7ccd7da932e2cb1bdcc4082/src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We decided today to use the .editorconfig settings of 4-space indentations for js and ts.
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts, line 120 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1484#-KcdUsa6wZrUZt30kIqo:-Kd2rM_Wn4doPsMu27At:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e3a194aadb320704d7ccd7da932e2cb1bdcc4082/src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts#L120)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Not a big deal, but this is missing a semicolon.
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug, line 41 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1484#-KcdSJf8TqTVaIcbU4QL:-Kd2rXSnH6ojohXFjdiV:b-2mr7sm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e3a194aadb320704d7ccd7da932e2cb1bdcc4082/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug#L41)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Depending on which of ours gets merged first, the other should remove these comments.
</blockquote></details>

Actually, I _did_ remove the placeholder for bubbles.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1484#-:-Kd2s7zHUmW_MypOacer:bq421lf)*

**Comment by andrew-polk** [comment]
Makes sense. I actually have two PRs coming, the second of which I spent some effort making the UI more consistent, so I've asked JH to hold off evaluating until the second one.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug, line 41 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1484#-KcdSJf8TqTVaIcbU4QL:-Kd60YbmrmCiIisOn15K:bnclitp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e3a194aadb320704d7ccd7da932e2cb1bdcc4082/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug#L41)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Actually, I _did_ remove the placeholder for bubbles.
</blockquote></details>

I meant I removed my comments and you removed yours which means each of us has the others'. It's okay. I'm planning to merge yours first so I will make sure they are gone.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1484#-:-Kd60iUTMEe8qHDV43Fz:b-6ot8ja)*

**Pull request merged**
