### PR TITLE
Tweak width of button labels and multi-line handling (BL-10959)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4989)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4989)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/collectionsTab/BookButton.tsx, line 231 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4989#-MwD2sVWDIok8RCuE0iy:-MwD2sVX9_SJI311lxvs:b-ao1yw5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dc22ca4f8f35774022db88773a50d98b0f7efc3d/src/BloomBrowserUI/collectionsTab/BookButton.tsx#L231)):*
> ```XML
> 
>     const label =
>         bookLabel.length > 14 ? (
> ```

Even the Moon and the Cap will get truncated now. We really can't handle more than 14 characters?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4989)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/collectionsTab/BookButton.tsx, line 231 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4989#-MwD2sVWDIok8RCuE0iy:-MwD4wlTBUkryGxe-Ylb:bkdhv9r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dc22ca4f8f35774022db88773a50d98b0f7efc3d/src/BloomBrowserUI/collectionsTab/BookButton.tsx#L231)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Even the Moon and the Cap will get truncated now. We really can't handle more than 14 characters?
</blockquote></details>

This is an optimization. TruncateMarkup does some somewhat costly measurements to find out what will really fit on two lines. It will only truncate if really necessary. Moon and Cap is not affected. This just says that if there are 14 or less, we can skip measuring and assume it fits.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4989)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/collectionsTab/BookButton.tsx, line 231 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4989#-MwD2sVWDIok8RCuE0iy:-MwD6LZP2Mbg5Gqk94Km:b-sbf2ja) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dc22ca4f8f35774022db88773a50d98b0f7efc3d/src/BloomBrowserUI/collectionsTab/BookButton.tsx#L231)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This is an optimization. TruncateMarkup does some somewhat costly measurements to find out what will really fit on two lines. It will only truncate if really necessary. Moon and Cap is not affected. This just says that if there are 14 or less, we can skip measuring and assume it fits.
</blockquote></details>

I added a comment.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4989)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
