### PR TITLE
Another round of New Collection Tab fixes

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4948)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4948)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/web/controllers/BookCommandsApi.cs, line 66 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4948#-Mv64VSP-MuUx_PdV3Zb:-Mv64VSQ3XGZG0GmHYOA:bxdwiff) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/312a4c77b1b9a12faa6fe146d407d48ed68f8e4d/src/BloomExe/web/controllers/BookCommandsApi.cs#L66)):*
> ```Smalltalk
> 				request.PostSucceeded();
> 			}, false, false);
> 			// Todo: figure how to get and set the real thing. Make an Exact version of RegisterBooleanEndpointHandler and use it.
> ```

I don't know what this comment means. Is this TODO covered in Notion or a card?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4948)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/web/controllers/BookCommandsApi.cs, line 66 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4948#-Mv64VSP-MuUx_PdV3Zb:-Mv6BQ6i0fVW24XNtG7B:b8kfoqt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/312a4c77b1b9a12faa6fe146d407d48ed68f8e4d/src/BloomExe/web/controllers/BookCommandsApi.cs#L66)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I don't know what this comment means. Is this TODO covered in Notion or a card?
</blockquote></details>

The first part was done. The second is now.

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4948)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/web/BloomApiHandler.cs, line 123 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4948#-Mv6CUXL-dLlUMW-RMAm:-Mv6CUXL-dLlUMW-RMAn:b-5tg705) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dc99cf0a066aa0eb5cf652de7e100c0b22234605/src/BloomExe/web/BloomApiHandler.cs#L123)):*
> ```Smalltalk
> 		}
> 
> 		public void RegisterBooleanEndpointHandlerExact(string pattern, Func<ApiRequest, bool> readAction, Action<ApiRequest, bool> writeAction,
> ```

Go ahead and add a <summary> comment explaining what you mean by exact.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4948)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/web/BloomApiHandler.cs, line 123 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4948#-Mv6CUXL-dLlUMW-RMAm:-MvJ_1He111ofYvL5t2z:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dc99cf0a066aa0eb5cf652de7e100c0b22234605/src/BloomExe/web/BloomApiHandler.cs#L123)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Go ahead and add a <summary> comment explaining what you mean by exact.
</blockquote></details>

Done.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4948)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/web/BloomApiHandler.cs, line 123 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4948#-Mv6CUXL-dLlUMW-RMAm:-MvJ_38VEuV8_vQ5-4pL:b-n2xa5x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dc99cf0a066aa0eb5cf652de7e100c0b22234605/src/BloomExe/web/BloomApiHandler.cs#L123)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

However, things should become clearer with the renaming planned soon.

**Review by hatton — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4948)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
