### PR TITLE
Attempt to fix NUnit3 test runner on TC

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1267)

### CODE REVIEW

**Comment by ermshiperete** [comment]
I think a better way would be to use the NUnit3 task (i.e. probably get rid of the `RunNUnitTC` target and always use `RunNUnit`). The NUnit3 task could be extended to optionally support the `--teamcity` parameter.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[build/Bloom.proj, line 133 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1267#-KUbfeIssyM_WlNLo2sU:-KUbfeItXF1JHf7qAIUD:bsb6szt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/52b625fa3b09a4f2a8ad0475b77ea86282544201/build/Bloom.proj#L133)):*
> ```
> 	<Target Name="RunNUnitTC" Condition="'$(teamcity_version)' != ''">
> 		
> 		<Exec IgnoreExitCode="True" Command="nunit3-console.exe @(TestAssemblies) --exclude=SkipOnTeamCity">
> ```

I think this needs the path to `nunit3-console.exe`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1267#-:-KUbfoBmsdxpI-WCNr3n:bv5w2t6)*

**Comment by andrew-polk** [comment]
Hm. Yeah, I did consider that. I guess I'll go that route. So, the --teamcity would simply be a shortcut to exclude the SkipOnTeamCity tests?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1267#-:-KUbk92R2ueWCfxt3gDf:bew383z)*

**Comment by ermshiperete** [comment]
No, that's a parameter for nunit3-console. I think it creates some special output that TC uses to show the progress during a test run.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1267#-:-KUbnkbxIzZrtndoDmdE:b7hepph)*

**Comment by andrew-polk** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[build/Bloom.proj, line 133 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1267#-KUbfeIssyM_WlNLo2sU:-KUcgDx8X1kTkdFT2Icn:bxii2ko) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/52b625fa3b09a4f2a8ad0475b77ea86282544201/build/Bloom.proj#L133)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary>
> I think this needs the path to `nunit3-console.exe`.
</details>
Reworked

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1267)*

**Comment by andrew-polk** [comment]
Going to go ahead and merge. It either works or it doesn't...

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1267#-:-KUcgKALELuWiGseyIgI:b-y8kct0)*

**Pull request merged**
