### PR TITLE
Fixing duplicate IDs, don't change a book in a TC repo (BL-10512)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4777)

### CODE REVIEW

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4777)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/Book/BookInfo.cs, line 665 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4777#-MlRWsxi7tY43DHWQqmZ:-MlRWsxi7tY43DHWQqm_:bkujw7h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/bc68012c416195bb74531ae5998da669678f8542/src/BloomExe/Book/BookInfo.cs#L665)):*
> ```Smalltalk
> 					// than one member of a duplicate set to be in a TC is hopefully vanishingly rare. If it happens,
> 					// I think it's worth hearing about.
> 					throw new ApplicationException("More than one duplicate-id book's ID cannot be changed");
> ```

Even though this is largely for *us*, how about "Bloom found more than 2 books with an identical ID. You will need help from the Bloom Team to sort this out")

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4777)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/Book/BookInfo.cs, line 665 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4777#-MlRWsxi7tY43DHWQqmZ:-MlRYhj1BbWqfEBw5TXL:b5ex38z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/bc68012c416195bb74531ae5998da669678f8542/src/BloomExe/Book/BookInfo.cs#L665)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Even though this is largely for *us*, how about "Bloom found more than 2 books with an identical ID. You will need help from the Bloom Team to sort this out")
</blockquote></details>

The problem is not that there are more than two with the same ID...Bloom handles that fine. The problem is that more than ONE of them is in the shared repo as well as in the local collection, so any way we fix them will mess up the TC. How about, "Bloom found two or more books that are already shared in your Team Collection and have the same ID. You will need help from the Bloom Team to sort this out."

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4777)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/Book/BookInfo.cs, line 665 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4777#-MlRWsxi7tY43DHWQqmZ:-MlV9xWe2nhDwF-kEb5L:b-mjlzfg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/bc68012c416195bb74531ae5998da669678f8542/src/BloomExe/Book/BookInfo.cs#L665)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

The problem is not that there are more than two with the same ID...Bloom handles that fine. The problem is that more than ONE of them is in the shared repo as well as in the local collection, so any way we fix them will mess up the TC. How about, "Bloom found two or more books that are already shared in your Team Collection and have the same ID. You will need help from the Bloom Team to sort this out."
</blockquote></details>

I've changed it to my suggestion, so if that's OK with you it's ready to go.

**Review by hatton — COMMENTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4777)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/Book/BookInfo.cs, line 665 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4777#-MlRWsxi7tY43DHWQqmZ:-MlVCuXP9bvzb9u91FZ3:btw6e7q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/bc68012c416195bb74531ae5998da669678f8542/src/BloomExe/Book/BookInfo.cs#L665)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I've changed it to my suggestion, so if that's OK with you it's ready to go.
</blockquote></details>

Wording is fine, but that's probably the only part of this I'm going to review. I have trouble understanding the rest.

**Review by andrew-polk — COMMENTED** [review]
Looks ok to me. But I'm wondering if this can/should make use of the change in the other card to how we determine if a book is in a "saveable" state.

> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4777#-:-MllJiSr9Ric_hf91bUp:b-9veece)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
I don't think so. That new logic might be relevant if we advance to a more sophisticated version of this change, where we allow the algorithm to change IDs of books that are checked out. But for now, we're taking a more drastic approach: if the book exists in a TC repo (whether or not it is checked out) we don't allow the ID to change. (It's OK to fix books in a local TC that have NEVER been checked in, such as a book newly copied into the folder manually.)
(This is because, currently, changing the ID in the repo is likely to confuse other users of the collection, especially if the book has also been renamed.)

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4777#-:-MlpG0aN3go3ZncsHGRk:b-blnxwv)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/Book/BookInfo.cs, line 665 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4777#-MlRWsxi7tY43DHWQqmZ:-MlpI6FGEAWAd3R-eGg8:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/bc68012c416195bb74531ae5998da669678f8542/src/BloomExe/Book/BookInfo.cs#L665)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Wording is fine, but that's probably the only part of this I'm going to review. I have trouble understanding the rest.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4777)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Pull request merged**
