### PR TITLE
Add git hook to check for non-Robust File operations (BL-12669)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6090)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6090)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`build/check-csharp-file.sh` line 1 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6090#-NdgOpkY4ravS8YmT9TN:-NdgOpkY4ravS8YmT9TO:b-720c9w) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/386cec93d7bc34965532f4f512131d1cd5bbe54d/build/check-csharp-file.sh#L1)):*
> ```Shell
> #!/bin/sh
> ```

Should this file be called `check-csharp-files` (plural)?
___
*[`build/check-csharp-file.sh` line 18 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6090#-NdgNjO7CY1tlM0GT7mm:-NdgNjO7CY1tlM0GT7mn:b-exo0df) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/386cec93d7bc34965532f4f512131d1cd5bbe54d/build/check-csharp-file.sh#L18)):*
> ```Shell
> status=$?
> # if grep finds instances of File.<method>, then stop the commit.
> [ $status -eq 0 ] && exit 1 || exit 0
> ```

Not sure how far we want to take it, but...
SIL.Core also has RobustIO with wrappers for 
- Directory.Delete
- Directory.Move
- xElement.Save (not sure how you'd search for that...)

and our RobustIO has
- Directory.EnumerateFiles

and our RobustFileIO has
- new WaveFileReader
- Document.FromFile
- Metadata.FromFile
- TagLib.File.Create (which I guess would already be caught)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6090)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`build/check-csharp-file.sh` line 18 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6090#-NdgNjO7CY1tlM0GT7mm:-Ne5C92-A-BK-dx57Vz8:b-us9os8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/386cec93d7bc34965532f4f512131d1cd5bbe54d/build/check-csharp-file.sh#L18)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Not sure how far we want to take it, but...
SIL.Core also has RobustIO with wrappers for 
- Directory.Delete
- Directory.Move
- xElement.Save (not sure how you'd search for that...)

and our RobustIO has
- Directory.EnumerateFiles

and our RobustFileIO has
- new WaveFileReader
- Document.FromFile
- Metadata.FromFile
- TagLib.File.Create (which I guess would already be caught)
</blockquote></details>

I've added Directory.Delete, Directory.Move, Document.FromFile, and Metadata.FromFile to the hook, and fixed their usages (if any).  I deleted RobustFileIO.CreateWaveFileReader  because it is never called.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6090)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`build/check-csharp-file.sh` line 1 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6090#-NdgOpkY4ravS8YmT9TN:-Ne5NvcdEg5R9VlRAzWE:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/386cec93d7bc34965532f4f512131d1cd5bbe54d/build/check-csharp-file.sh#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should this file be called `check-csharp-files` (plural)?
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6090)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
