### PR TITLE
Report progress during team sync

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186)

### CODE REVIEW

**Review by StephenMcConnel — CHANGES_REQUESTED** [review]
Someone else should review this as well.  I found a few nits, but not sure I understood everything well enough to approve.

> Reviewed 26 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-:-MTCfsHC5dBqMXtpRNIX:b-z8lh93)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/utils/IndependentProgressDialog.html, line 16 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCdTYxBCyd52Qjx5uY:-MTCdTYy50nQHLzwXMMx:bxqo6t4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomBrowserUI/utils/IndependentProgressDialog.html#L16)):*
> ```HTML
>             //If we could do jsx here: ReactDOM.render(<ProgressBox/>, reactRoot);
>             //If we could access ReactDOM here: ReactDOM.render(React.createElement(IndependentProgressDialog, null), reactRoot);
>             // But withtout some new webpack wizardry, this will have to do in the meantime:
> ```

minor nit: "without" instead of "withtout"
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 648 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCeh_O0qMYU2kJ4lzF:-MTCeh_O0qMYU2kJ4lzG:b1kyfhq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/TeamCollection/TeamCollection.cs#L648)):*
> ```Smalltalk
> 					// warn the user
> 					var msgTemplate = LocalizationManager.GetString("TeamCollection.ConflictingEdit",
> 						"The book '{0}', which you have checked out and edited, was modified in the team collection by someone else. Your changes have been overwritten, but are saved to Lost-and-found.");
> ```

Did you change Bloom.xlf to reflect this change in wording?
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 41 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCf6292utb6s46cCW9:-MTCf6292utb6s46cCWA:b-jmxn9g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L41)):*
> ```Smalltalk
> 		}
> 
> 		private void HandleSendToClibpard(ApiRequest request)
> ```

"HandleSendToClipboard" -- your fingers apparently got crossed typing the method name.
___
*[src/BloomExe/web/WebSocketProgress.cs, line 172 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCfU5u8-8qegbea4a4:-MTCfU5u8-8qegbea4a5:b-yrg7fd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/941660841e936eebdbc9df0c5125d30e8bf3a8c7/src/BloomExe/web/WebSocketProgress.cs#L172)):*
> ```Smalltalk
> 		}
> 
> 		public override void MessageWithStyleWithoutLocalizing(string message, string cssStyleRules)
> ```

Deleting more than you add is always good.  (at least if it's the right thing to do)  :-)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186)* status: all files reviewed, 18 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/react_components/IndependentProgressDialog.less, line 46 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCwLpEEOO0RpZQqyOz:-MTCwLpEEOO0RpZQqyP-:bk55uhu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomBrowserUI/react_components/IndependentProgressDialog.less#L46)):*
> ```
>     // .MuiTypography-colorPrimary {
>     //     color: @bloom-purple;
>     // }
> ```
Any reason to keep this?
___
*[src/BloomBrowserUI/react_components/IndependentProgressDialog.less, line 57 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCwHYdAi-m4xHv65az:-MTCwHYdAi-m4xHv65b-:b-fb7w6x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomBrowserUI/react_components/IndependentProgressDialog.less#L57)):*
> ```Less
> 
> #copy-button {
>     background-image: url("../images//copy.svg");
> ```

Is the double slash correct?
___
*[src/BloomBrowserUI/react_components/IndependentProgressDialog.tsx, line 44 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCx5XT12s9K9M7skL5:-MTCx5XT12s9K9M7skL6:b-pg8y32) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomBrowserUI/react_components/IndependentProgressDialog.tsx#L44)):*
> ```
> Copy to Clipboard
> ```
This needs to be internationalized.
If not now, is there somewhere to make a note of it?
___
*[src/BloomBrowserUI/react_components/IndependentProgressDialog.tsx, line 71 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCxJl-1EWV3CTWZY1c:-MTCxJl-1EWV3CTWZY1d:b8dkxcu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomBrowserUI/react_components/IndependentProgressDialog.tsx#L71)):*
> ```
> Should we have Common.Close?
> ```
Yes, seems right to me. But I hate these cases where we already have the string with some too-specific ID. There is no good answer.
___
*[src/BloomBrowserUI/react_components/progressBox.tsx, line 37 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCzd8e5MK3lnGBnlXj:-MTCzd8e5MK3lnGBnlXk:bso20ls) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomBrowserUI/react_components/progressBox.tsx#L37)):*
> ```XML
>         //get progress messages from c#
>         WebSocketManager.addListener(props.clientContext, e => {
>             if (e.id === "message") {
> ```

I'm sure you've done your homework as you always do, but I'm not seeing changes which allow for a wholesale change here.

Or maybe you just didn't finish cleaning up places where we send progress but don't need to anymore?
___
*[src/BloomExe/TeamCollection/ProgressLogger.cs, line 51 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCrYEI7sM37lFIg2Jl:-MTCrYEI7sM37lFIg2Jm:by0hsfu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/TeamCollection/ProgressLogger.cs#L51)):*
> ```Smalltalk
> 		public void Message(string idSuffix, string message, MessageKind kind = MessageKind.Progress, bool useL10nIdPrefix = true)
> 		{
> 			throw new NotImplementedException();
> ```

Any reason not to just implement these two? 
Seems super simple.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 555 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCrx4L2dhvnntJ2fxE:-MTCrx4L2dhvnntJ2fxF:br283yw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/TeamCollection/TeamCollection.cs#L555)):*
> ```Smalltalk
> 							"Renaming the local book '{0}' because there is a new one with the same name from the Team Collection", bookName);
> 						progress.MessageWithoutLocalizing(msg);
> 							RobustFile.Move(oldBookPath, renamePath);
> ```

Extra indenting tab.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 670 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCsLq-CsXsZ77jG_7l:-MTCsLq-CsXsZ77jG_7m:bup1jp9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/TeamCollection/TeamCollection.cs#L670)):*
> ```
> TODO
> ```
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 684 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCsdtu8as2Af8t8RuG:-MTCsdtu8as2Af8t8RuH:bagf8jc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/TeamCollection/TeamCollection.cs#L684)):*
> ```
> Can add this
> ```
I don't understand. It looks like you have added it... at least you're passing it here.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 685 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCwyc-Edmv9fLqMxLC:-MTCwyc-Edmv9fLqMxLD:b-2y153w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/TeamCollection/TeamCollection.cs#L685)):*
> ```
> Team Collection Activity
> ```
This needs to be internationalized. If not now, is there a place to make note of it?
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 706 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCt5Ks9z1d1Lbm4xTx:-MTCt5Ks9z1d1Lbm4xTy:b7oc7bh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/TeamCollection/TeamCollection.cs#L706)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 				//dlg.Text = "Team Collection Activity";
> 				// None...no border anywhere
> 				// FixedSingle...full title bar with menu, maximize, minimize
> 				// dlg.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
> ```
</details>

Any reason to keep these comments?
If so, they could probably be clarified.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 734 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCtYFI9V-K6uQAgwjP:-MTCtYFI9V-K6uQAgwjQ:b-9rw0lx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/TeamCollection/TeamCollection.cs#L734)):*
> ```
> "show-buttons"
> ```
Worth a comment that this matches a string in js-land? Or is it obvious?
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 38 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCuD-v7SA6kzOwKnis:-MTCuD-v7SA6kzOwKnit:bivougy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L38)):*
> ```Smalltalk
> 			apiHandler.RegisterEndpointHandler("teamCollection/checkInCurrentBook", HandleCheckInCurrentBook, false);
> 			apiHandler.RegisterEndpointHandler("teamCollection/createTeamCollection", HandleCreateTeamCollection, true);
> 			apiHandler.RegisterEndpointHandler("teamCollection/sendToClipboard", HandleSendToClibpard, true);
> ```

You don't need a new endpoint for this. There's one in CommonAPI: common/clipboardText
___
*[src/BloomExe/web/WebSocketProgress.cs, line 79 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCyeB4A9O4xnY_-74F:-MTCyeB57X6Xbhc5NB8W:blcis91) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/web/WebSocketProgress.cs#L79)):*
> ```Smalltalk
> 			_bloomWebSocketServer.SendString(_clientContext, "progress", $"<span style='color:red'>{message}</span>");
> 			SIL.Reporting.Logger.WriteEvent($"Error: {message}");
> 		}
> ```

I'm probably just not understanding the impetus for this, but it seems backwards to be expanding the complexity of an obsolete method.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186)* status: 20 of 25 files reviewed, 17 unresolved discussions (waiting on @andrew-polk and @StephenMcConnel)

___
*[src/BloomBrowserUI/react_components/IndependentProgressDialog.less, line 46 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCwLpEEOO0RpZQqyOz:-MTDEM-z2O4278l068ti:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomBrowserUI/react_components/IndependentProgressDialog.less#L46)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
>     // .MuiTypography-colorPrimary {
>     //     color: @bloom-purple;
>     // }
> ```
Any reason to keep this?
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/react_components/IndependentProgressDialog.less, line 57 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCwHYdAi-m4xHv65az:-MTDHtky2Rf7ZmTlPktx:bheg9vm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomBrowserUI/react_components/IndependentProgressDialog.less#L57)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is the double slash correct?
</blockquote></details>

It worked...but I can't imagine how!
___
*[src/BloomBrowserUI/react_components/IndependentProgressDialog.tsx, line 44 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCx5XT12s9K9M7skL5:-MTDHya1A_Mi8DehNzdQ:b-a6xymf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomBrowserUI/react_components/IndependentProgressDialog.tsx#L44)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Copy to Clipboard
> ```
This needs to be internationalized.
If not now, is there somewhere to make a note of it?
</blockquote></details>

John didn't want new strings in Bloom.xlf until the new UI stabilizes. I made https://issues.bloomlibrary.org/youtrack/issue/BL-9522 to remind us.
___
*[src/BloomBrowserUI/react_components/IndependentProgressDialog.tsx, line 71 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCxJl-1EWV3CTWZY1c:-MTDIHnKC88NU4cc2OOM:bgg8tow) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomBrowserUI/react_components/IndependentProgressDialog.tsx#L71)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Should we have Common.Close?
> ```
Yes, seems right to me. But I hate these cases where we already have the string with some too-specific ID. There is no good answer.
</blockquote></details>

Maybe Steve has some way to change all the existing ones? This at least got it to stop complaining...
___
*[src/BloomBrowserUI/react_components/progressBox.tsx, line 37 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCzd8e5MK3lnGBnlXj:-MTDIZtc0cOK-rMCHCEI:b-p7sy8a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomBrowserUI/react_components/progressBox.tsx#L37)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm sure you've done your homework as you always do, but I'm not seeing changes which allow for a wholesale change here.

Or maybe you just didn't finish cleaning up places where we send progress but don't need to anymore?
</blockquote></details>

As near as I can determine, the only source of progressBox messages is WebSocketProgress.cs, which was ALREADY coded to send BOTH message/kind and ("for any old-style listeners) progress. The only way we were actually getting color was by embedding the markup directly in the message. So I've taken an in-progress refactoring a couple of steps further.
___
*[src/BloomBrowserUI/utils/IndependentProgressDialog.html, line 16 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCdTYxBCyd52Qjx5uY:-MTDJqHD8vZwHENcAs98:bb7f2mf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomBrowserUI/utils/IndependentProgressDialog.html#L16)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

minor nit: "without" instead of "withtout"
</blockquote></details>

done
___
*[src/BloomExe/TeamCollection/ProgressLogger.cs, line 51 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCrYEI7sM37lFIg2Jl:-MTDJv12CcpWs0xA8dCt:b-ohx3lq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/TeamCollection/ProgressLogger.cs#L51)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Any reason not to just implement these two? 
Seems super simple.
</blockquote></details>

Just YAGNI. The implementation is simple, but if they are used, there should be test cases...
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 555 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCrx4L2dhvnntJ2fxE:-MTDK9tUElIkfiGPcpwi:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/TeamCollection/TeamCollection.cs#L555)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Extra indenting tab.
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 648 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCeh_O0qMYU2kJ4lzF:-MTDKV66Akdohe6MniVF:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/TeamCollection/TeamCollection.cs#L648)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Did you change Bloom.xlf to reflect this change in wording?
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 670 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCsLq-CsXsZ77jG_7l:-MTDL7Ym5Wm31-vtijWp:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/TeamCollection/TeamCollection.cs#L670)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> TODO
> ```

</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 684 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCsdtu8as2Af8t8RuG:-MTDLIoO2w08Xz-Px5EA:bfvvqw2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/TeamCollection/TeamCollection.cs#L684)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Can add this
> ```
I don't understand. It looks like you have added it... at least you're passing it here.
</blockquote></details>

Obsolete comment, sorry.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 685 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCwyc-Edmv9fLqMxLC:-MTDLLyM7v9Mm-dpqdUp:b-34vmyd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/TeamCollection/TeamCollection.cs#L685)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Team Collection Activity
> ```
This needs to be internationalized. If not now, is there a place to make note of it?
</blockquote></details>

See above
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 706 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCt5Ks9z1d1Lbm4xTx:-MTDL_roBUSslmeB86jS:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/TeamCollection/TeamCollection.cs#L706)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> 				//dlg.Text = "Team Collection Activity";
> 				// None...no border anywhere
> 				// FixedSingle...full title bar with menu, maximize, minimize
> 				// dlg.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
> ```
Any reason to keep these comments?
If so, they could probably be clarified.
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 734 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCtYFI9V-K6uQAgwjP:-MTDN-y48u_rti_dimls:ba0az0v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/TeamCollection/TeamCollection.cs#L734)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> "show-buttons"
> ```
Worth a comment that this matches a string in js-land? Or is it obvious?
</blockquote></details>

I think it's fairly obvious that if you send a message to a WebSocket in Bloom, something in JS land is watching for it. But it could save some effort to say what, so I did.
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 38 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCuD-v7SA6kzOwKnis:-MTDNsOI9bIbtDlxHn0v:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L38)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

You don't need a new endpoint for this. There's one in CommonAPI: common/clipboardText
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 41 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCf6292utb6s46cCW9:-MTDNujP8xErgxzkqRL6:bn0zcki) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L41)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

"HandleSendToClipboard" -- your fingers apparently got crossed typing the method name.
</blockquote></details>

It's gone away. See Andrew's comment
___
*[src/BloomExe/web/WebSocketProgress.cs, line 79 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCyeB4A9O4xnY_-74F:-MTDO3ai22I5J7mmY0ID:bcdahxq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/web/WebSocketProgress.cs#L79)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm probably just not understanding the impetus for this, but it seems backwards to be expanding the complexity of an obsolete method. 
</blockquote></details>

It still has 16 callers in a totally different part of the system (Epub making). Trying to change them all was more than I wanted to tackle. And now that we're actually USING the Kind parameter, it was no longer a good idea to insert the markup into the message for that option as well as the (probably now unreceived?) 'progress' message.
___
*[src/BloomExe/web/WebSocketProgress.cs, line 172 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCfU5u8-8qegbea4a4:-MTDOvF13LKQZIMNGnhQ:b8ltog0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/941660841e936eebdbc9df0c5125d30e8bf3a8c7/src/BloomExe/web/WebSocketProgress.cs#L172)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Deleting more than you add is always good.  (at least if it's the right thing to do)  :-)
</blockquote></details>

It compiled without it, confirming VS's claim that it was unused. I don't think anything OTHER than Bloom is using this code.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnThomson and @StephenMcConnel)

___
*[src/BloomBrowserUI/react_components/progressBox.tsx, line 37 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCzd8e5MK3lnGBnlXj:-MTGaC_K8H-XHT25zwV6:b-ojyplc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomBrowserUI/react_components/progressBox.tsx#L37)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

As near as I can determine, the only source of progressBox messages is WebSocketProgress.cs, which was ALREADY coded to send BOTH message/kind and ("for any old-style listeners) progress. The only way we were actually getting color was by embedding the markup directly in the message. So I've taken an in-progress refactoring a couple of steps further.
</blockquote></details>

Continuing this conversation in the relevant one in WebSocketProgress...
___
*[src/BloomExe/web/WebSocketProgress.cs, line 79 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCyeB4A9O4xnY_-74F:-MTG_xIMDvAmUBvYMH09:bghuinm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/web/WebSocketProgress.cs#L79)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It still has 16 callers in a totally different part of the system (Epub making). Trying to change them all was more than I wanted to tackle. And now that we're actually USING the Kind parameter, it was no longer a good idea to insert the markup into the message for that option as well as the (probably now unreceived?) 'progress' message.
</blockquote></details>

I'm probably just not understanding something, but as you changed the receiver to get "message" instead of "progress", isn't it time to remove the code which sends "progress"?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @StephenMcConnel)

___
*[src/BloomExe/web/WebSocketProgress.cs, line 79 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-MTCyeB4A9O4xnY_-74F:-MTGeLHG9jkKy5Vok780:b-1p8pk5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/960305b41badec7f4c48d73fc7b351ce3aa211bd/src/BloomExe/web/WebSocketProgress.cs#L79)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm probably just not understanding something, but as you changed the receiver to get "message" instead of "progress", isn't it time to remove the code which sends "progress"?
</blockquote></details>

OK, you convinced me. I was thinking that being sure nothing ELSE is listening for progress was difficult. But a global search only found a few instances of "progress" in our TS code, none of which appear to be listeners, so I think all is well. I've removed the "progress" code.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

**Review by andrew-polk — APPROVED** [review]
Not ready yet.
JT is going to fix the copy button and remove the white bar at the top at the expense of losing the ability to move the dialog (for now).

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186#-:-MTGjz1sAo54YT4Yu-IV:b-9919xn)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> Dismissed @StephenMcConnel from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

**Review by andrew-polk — APPROVED** [review]
> Dismissed @StephenMcConnel from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186)* status: all files reviewed, 2 unresolved discussions

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4186)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
