### PR TITLE
Keep xmatter IDs through BringXmatterUpToDate (BL-13527)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6516)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6516)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/XMatterHelper.cs` line 361 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6516#-NzLBGFuEmNS9zlZtpMX:-NzLBGFuEmNS9zlZtpMY:b-t8eqg6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d954b16f4d571ec9508e77a29315b3242035b155/src/BloomExe/Book/XMatterHelper.cs#L361)):*
> ```Smalltalk
>             {
>                 var newPageDiv = _bookDom.RawDom.ImportNode(xmatterPage, true) as XmlElement;
>                 // If we're updating an existing book, we want to keep the IDs (as much as possible; sometimes
> ```

This was prompted by a page with an ID going away unexpectedly as it was replaced. I'm left wondering if we're looking at the back cover and the update of the xmatter were to cause us to have one less page then before, would we have the same problem we're trying to solve? The answer to my Q would probably work well as a comment somewhere around here.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6516)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/BloomExe/Book/XMatterHelper.cs` line 361 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6516#-NzLBGFuEmNS9zlZtpMX:-NzTA99a4Xq7LTzGlNLV:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d954b16f4d571ec9508e77a29315b3242035b155/src/BloomExe/Book/XMatterHelper.cs#L361)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This was prompted by a page with an ID going away unexpectedly as it was replaced. I'm left wondering if we're looking at the back cover and the update of the xmatter were to cause us to have one less page then before, would we have the same problem we're trying to solve? The answer to my Q would probably work well as a comment somewhere around here.
</blockquote></details>

Done.

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6516)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/XMatterHelper.cs` line 361 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6516#-NzLBGFuEmNS9zlZtpMX:-NzTMotH49eoNkmj3Ej8:bvy6swh) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d954b16f4d571ec9508e77a29315b3242035b155/src/BloomExe/Book/XMatterHelper.cs#L361)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK, I don't see from the comment how this is achieved? I.e. how is it that it will reset somehow to the first page, when before it would crash?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6516)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/BloomExe/Book/XMatterHelper.cs` line 361 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6516#-NzLBGFuEmNS9zlZtpMX:-NzTxiWk6BMnIjOXFd-X:b-tp7xzo) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d954b16f4d571ec9508e77a29315b3242035b155/src/BloomExe/Book/XMatterHelper.cs#L361)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

OK, I don't see from the comment how this is achieved? I.e. how is it that it will reset somehow to the first page, when before it would crash?
</blockquote></details>

It's part of https://github.com/BloomBooks/BloomDesktop/pull/6517. Exception handler around like 946. (Maybe I should have combined these, but they were presented as separate cards.)

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6516)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by hatton — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6516)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
