### PR TITLE
Fix Team Collection book status display to not ruin PDFs (BL-9786)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4354)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4354)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/CollectionTab/LibraryBookView.cs, line 202 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4354#-MXt0h758TBwUqyrmxSw:-MXt0h76AvERZcAXek8I:bwlgh0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4581f65a2e83f0b614678008b869156cd27fcc38/src/BloomExe/CollectionTab/LibraryBookView.cs#L202)):*
> ```Smalltalk
> 					previewDom.Body.AppendChild(divTeamCollection);
> 					_previewBrowser.Navigate(previewDom, source: BloomServer.SimulatedPageFileSource.Preview);
> 				}
> ```

I'm going to unashamedly blame Friday afternoon code review brain... but I *finally* figured out this works because this code is only executed on the real preview path, not on the PDF path. So on the PDF path we never create the "teamCollection" div.

I thought we had discussed a different approach (rearchitecting the structure, putting the book contents in an iframe such that the preview code doesn't need to know anything about the team collection panel).

Even if we went with the approach you've implemented, I don't see the benefit of having C# add the wrapper and ts remove it if needed. Doesn't C# already have the knowledge it needs to *not* add it if not needed?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4354)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/CollectionTab/LibraryBookView.cs, line 202 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4354#-MXt0h758TBwUqyrmxSw:-MY7AmEF01l-ouvJpBY6:b33qwj9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4581f65a2e83f0b614678008b869156cd27fcc38/src/BloomExe/CollectionTab/LibraryBookView.cs#L202)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm going to unashamedly blame Friday afternoon code review brain... but I *finally* figured out this works because this code is only executed on the real preview path, not on the PDF path. So on the PDF path we never create the "teamCollection" div.

I thought we had discussed a different approach (rearchitecting the structure, putting the book contents in an iframe such that the preview code doesn't need to know anything about the team collection panel).

Even if we went with the approach you've implemented, I don't see the benefit of having C# add the wrapper and ts remove it if needed. Doesn't C# already have the knowledge it needs to *not* add it if not needed?
</blockquote></details>

I changed the code to optionally insert the wrapper and book information div in the C# code, and simplified the TypeScript to either display the book info panel or not.
I have no idea what it would take to implement the Todo given in teamCollection/TeamCollectionBookStatusPanel.tsx that asks for redesign with the book content in an iframe.  That doesn't seem to fit using ReactDOM.render in my (extremely limited) understanding.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4354)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/CollectionTab/LibraryBookView.cs, line 202 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4354#-MXt0h758TBwUqyrmxSw:-MY7Jc01Aa2nopy90UyN:b-yqivjp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4581f65a2e83f0b614678008b869156cd27fcc38/src/BloomExe/CollectionTab/LibraryBookView.cs#L202)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I changed the code to optionally insert the wrapper and book information div in the C# code, and simplified the TypeScript to either display the book info panel or not.
I have no idea what it would take to implement the Todo given in teamCollection/TeamCollectionBookStatusPanel.tsx that asks for redesign with the book content in an iframe.  That doesn't seem to fit using ReactDOM.render in my (extremely limited) understanding.
</blockquote></details>

Ok, let's discuss tomorrow if someone should pair with you or what.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Not finished but posting what I have in case you want to take a look.

> Reviewed 5 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4354#-:-MYCcGqn3t9mI7ZgCeUu:b-oi0xi8)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @StephenMcConnel)

___
*[src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.less, line 19 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4354#-MYCbfDX8nihR32ihLK6:-MYCbfDY2vbFGA9F3iYa:buw4fc3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95814e5486d78dd1b92ebb625baef20825188bf3/src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.less#L19)):*
> ```Less
>     overflow-y: hidden; // inner iframe shows scrollbars as needed
>     overflow-x: hidden;
> }
> ```

How would you feel about replacing both the above with something like
```
#preview {
    // used when there's no team collection
    height: 99vh;
    width: 99vw;
    overflow-y: hidden; // inner iframe shows scrollbars as needed
    overflow-x: hidden;

    .abovePanel {
        height: calc(99vh - @status-panel-height);
    }
}

```

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4354)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.less, line 19 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4354#-MYCbfDX8nihR32ihLK6:-MYH5Flf8BH0oS0n-6yz:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95814e5486d78dd1b92ebb625baef20825188bf3/src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.less#L19)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

How would you feel about replacing both the above with something like
```
#preview {
    // used when there's no team collection
    height: 99vh;
    width: 99vw;
    overflow-y: hidden; // inner iframe shows scrollbars as needed
    overflow-x: hidden;

    .abovePanel {
        height: calc(99vh - @status-panel-height);
    }
}

```
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4354)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.less, line 19 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4354#-MYCbfDX8nihR32ihLK6:-MYHDaHgAh86NyLbowK8:bwcix07) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95814e5486d78dd1b92ebb625baef20825188bf3/src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.less#L19)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

IMO, it still makes more sense to have the .abovePanel rule in BookPanelPreview.less.
Either way.
___
*[src/BloomExe/CollectionTab/LibraryBookView.cs, line 232 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4354#-MYHCtraETiigXXoxJw5:-MYHCtraETiigXXoxJw6:b4nympa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3a8b56923dbad7eed7ed51377a694d5597acd826/src/BloomExe/CollectionTab/LibraryBookView.cs#L232)):*
> ```Smalltalk
> 			// to start navigating to their pages. Thus, painting of the two current views is held up until we've
> 			// generated not only the previously-visible part of the preview, but all the rest of it as well.
> 			// So, we abort whatever is going on in the preview browser by pointing it at an empty page.
> ```

I think this comment is now obsolete.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4354)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.less, line 19 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4354#-MYCbfDX8nihR32ihLK6:-MYHZbNkANxno-A_EuBG:b-vuunjc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95814e5486d78dd1b92ebb625baef20825188bf3/src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.less#L19)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

IMO, it still makes more sense to have the .abovePanel rule in BookPanelPreview.less.
Either way.
</blockquote></details>

Keeping it in the other file allows @status-panel-height to be confined to just one file, the one it's most associated with.
That's the main reason I did it the way I did.  I suppose I could define the variable in bloomUI.less and import that here
___
*[src/BloomExe/CollectionTab/LibraryBookView.cs, line 232 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4354#-MYHCtraETiigXXoxJw5:-MYHZI5l7aUpp6Ew8BsB:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3a8b56923dbad7eed7ed51377a694d5597acd826/src/BloomExe/CollectionTab/LibraryBookView.cs#L232)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this comment is now obsolete.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4354)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
