### PR TITLE
Rename .bloom files to .bloomSource files (BL-10673)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This does not include changing the extension in TeamCollection
repositories.  That requires some more thinking and design to prevent
chaos when different team members have different versions of Bloom.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4884)

### CODE REVIEW

**Comment by andrew-polk** [comment]
I haven't really looked at this in any detail, but I have some concerns.

The menu command to export as .bloom is used by StoryProducer folks. In theory, this change should be made in coordination with them. Though JH has communicated with them some, and they can always use an older version if needed. So maybe not a big deal.

If I'm correct, the migration of .bloom to .bloomSource in TC repos causes a problem. It means that unless an entire team upgrades Bloom at the same time, chaos will ensue.
The only alternative I can think of at the moment is to start creating .bloomSource but maintain the ability to read/update .bloom for existing books. Or only do .bloomSource for new TCs. Or something along those lines.

**Review by StephenMcConnel — COMMENTED** [review]
I don't think any alternative is feasible other than my review comment suggesting throwing up a dialog warning users that EVERYONE **MUST** UPGRADE Bloom at the SAME TIME, presumably with an option to abort the migration and somehow gracefully handle not being able to open the collection after all.  Trying to live with a mix of .bloom and .bloomSource files in the same repository seems like it's just asking for trouble and user confusion.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4884#-:-Mr4ETWBDNAE625uVo2w:b-l6mxna)* status: 0 of 18 files reviewed, all discussions resolved

**Review by StephenMcConnel — COMMENTED** [review]
As suggested by @hatton, I've removed all of the TeamCollection changes from this pull request. Running all of the tests locally and trying out the program on my private TeamCollection (after renaming books back to .bloom) worked okay as far as I could tell.  The method that actually creates the .bloom / .bloomSource files depends on the caller setting the extension properly.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4884#-:-Mr8TrgZ-AikUYrlLKJh:b-xsbfwz)* status: 0 of 18 files reviewed, all discussions resolved

**Review by andrew-polk — APPROVED** [review]
> Reviewed 9 of 18 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4884)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
