### PR TITLE
Move item-specific options for draggables from toolbox to context

### PR DESCRIPTION
**Pull request by JohnThomson**
Also fixes a glitch where nested menu items were not properly aligned after we switched away from 'dense' mode for popup menus.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6611)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6611)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 123 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6611#-O5EY0jdBx_0hCvvSgxb:-O5EY0jdBx_0hCvvSgxc:bpd8hly) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2ca9b475bdfeeb75af0d95678933f3e687264f3a/DistFiles/localization/en/BloomMediumPriority.xlf#L123)):*
> ```XML
>       </trans-unit>
>       <trans-unit id="EditTab.Toolbox.DragActivity.PartOfRightAnswerMore" translate="no">
>         <source xml:lang="en">Untick this item if it is not part of the right answer</source>
> ```

I would think "uncheck" is more user-friendly. Or unselect.
___
*[`src/BloomBrowserUI/bookEdit/js/OverlayContextControls.tsx` line 226 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6611#-O5E_djS07T2nbfvRWgI:-O5E_djS07T2nbfvRWgJ:b224ydx) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2ca9b475bdfeeb75af0d95678933f3e687264f3a/src/BloomBrowserUI/bookEdit/js/OverlayContextControls.tsx#L226)):*
> ```XML
>                 english: "",
>                 onClick: () => {}
>             },
> ```

If I'm reading this correctly, for the truthy `currentBubbleTargetId` case, we will get two horizontal lines here.
If that's intentional, it is probably worth a comment.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityTool.tsx` line 715 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6611#-O5EalUR83Hiwb24ZdBw:-O5EalUR83Hiwb24ZdBx:b-57h7l5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2ca9b475bdfeeb75af0d95678933f3e687264f3a/src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityTool.tsx#L715)):*
> ```XML
>             {
>                 name: "MP#",
>                 extensions: ["mp3"]
> ```

Sorry; I know you're just copying this code, but
1. is now the time to localize (if you still have that as a general TODO, don't bother)
2. Shouldn't name match extensions? i.e. if we're only accepting "mp3", shouldn't `name` reflect that?

**Comment by andrew-polk** [comment]
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 123 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6611#-O5EY0jdBx_0hCvvSgxb:-O5EbC6862XdyDSDXJbz:b-p32msw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2ca9b475bdfeeb75af0d95678933f3e687264f3a/DistFiles/localization/en/BloomMediumPriority.xlf#L123)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I would think "uncheck" is more user-friendly. Or unselect.
</blockquote></details>

But I'm ok merging as is.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6611)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 123 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6611#-O5EY0jdBx_0hCvvSgxb:-O5EdARZ5g2PlDpAomE3:bb8gpso) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2ca9b475bdfeeb75af0d95678933f3e687264f3a/DistFiles/localization/en/BloomMediumPriority.xlf#L123)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

But I'm ok merging as is.
</blockquote></details>

"Tick" comes from John's mockup. For check boxes, "tick" is British (and Australian) English while "check" is American. But this UI actually uses something that is shaped as a tick rather than an X, so maybe that's why John wrote it that way. I'm inclined to keep what he had for now.
___
*[`src/BloomBrowserUI/bookEdit/js/OverlayContextControls.tsx` line 226 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6611#-O5E_djS07T2nbfvRWgI:-O5Er3k02OrH2CbIxqs_:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2ca9b475bdfeeb75af0d95678933f3e687264f3a/src/BloomBrowserUI/bookEdit/js/OverlayContextControls.tsx#L226)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If I'm reading this correctly, for the truthy `currentBubbleTargetId` case, we will get two horizontal lines here.
If that's intentional, it is probably worth a comment.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityTool.tsx` line 715 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6611#-O5EalUR83Hiwb24ZdBw:-O5EsqBl6BLD2pBp4_3c:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2ca9b475bdfeeb75af0d95678933f3e687264f3a/src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityTool.tsx#L715)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; I know you're just copying this code, but
1. is now the time to localize (if you still have that as a general TODO, don't bother)
2. Shouldn't name match extensions? i.e. if we're only accepting "mp3", shouldn't `name` reflect that?
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6611)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6611)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
