### PR TITLE
Do not include fonts for languages not in the book (BL-9709)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4304)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4304)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @andrew-polk)

___
*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1993 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4304#-MWVxeT57ir61qvkA5nt:-MWVxeT57ir61qvkA5nu:b-5z32rb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9f5977a6e6ad3f8dd520fa309a4cdecad30f9695/src/BloomExe/Publish/Epub/EpubMaker.cs#L1993)):*
> ```Smalltalk
> 			return result;
> 		}
> ```

This was moved to GetUsedFontsCommand and heavily modified.
Didn't belong in EpubMaker for sure, and its only caller was there.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
Is visibility a concern? For example, this will exclude fonts for languages not selected for upload when a book is later harvested. I don't think it will exclude from a PDF fonts for language that are not visible. Whether it works for epubs and/or bloomd's will depend on whether language data for undesired languages has been removed before this runs.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4304#-:-MWW4NeBBZdo5y7ZgD4d:bxicmbu)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/CLI/GetUsedFontsCommand.cs, line 161 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4304#-MWW0P9A-rjpNcGvqSIi:-MWW0P9BEyL0P76YCzsY:b-dk2uf9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3f9d871f63c6e5d39a780e64c2088d44f6baf9f8/src/BloomExe/CLI/GetUsedFontsCommand.cs#L161)):*
> ```Smalltalk
> 			//		direction: ltr;
> 			//	}
> 			Regex languageCssRegex = new Regex(@"\[\s*lang\s*=\s*['""](.*)['""]\s*\]\s*{[^}]*}", RegexOptions.Compiled);
> ```

The (.*) for the language code would be a lot more efficient (and safer) as (.*?) to give the shortest possible match, or possibly ([^'""]*). In fact, I don't see why it can't treat everything down to the lang code in the last rule as a match, except perhaps that dot doesn't match line breaks. Do you have a test case that would ensure that doesn't happen?
___
*[src/BloomExe/CLI/GetUsedFontsCommand.cs, line 169 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4304#-MWW25_D9UZGLFwFlkjE:-MWW25_D9UZGLFwFlkjF:boh1zjf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3f9d871f63c6e5d39a780e64c2088d44f6baf9f8/src/BloomExe/CLI/GetUsedFontsCommand.cs#L169)):*
> ```Smalltalk
> 				if (languagesWithContent.Contains(langTag))
> 					continue;
> 				var cssForLang = match.Groups[0].Value;
> ```

Something about this name made me expect it to be the content of the {} rather than the entire rule. What would you think of 'wholeRule{forLang}'?

**Review by andrew-polk — COMMENTED** [review]
This is only running in the context of harvester. The GetUsedFonts command is a command line verb called by the harvester.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4304#-:-MWW9ug8-Zf-O8lkKuIN:b2q5dzp)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/CLI/GetUsedFontsCommand.cs, line 161 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4304#-MWW0P9A-rjpNcGvqSIi:-MWWA7Su9A4V7g3yvu1p:b-3vt415) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3f9d871f63c6e5d39a780e64c2088d44f6baf9f8/src/BloomExe/CLI/GetUsedFontsCommand.cs#L161)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

The (.*) for the language code would be a lot more efficient (and safer) as (.*?) to give the shortest possible match, or possibly ([^'""]*). In fact, I don't see why it can't treat everything down to the lang code in the last rule as a match, except perhaps that dot doesn't match line breaks. Do you have a test case that would ensure that doesn't happen?
</blockquote></details>

Good call. I did think about that a little, and the tests do prove it isn't getting everything. But I think your way is certainly betterer. : )
And I made a change to how we get the bit between the {...}. See if you think this is an improvement.
___
*[src/BloomExe/CLI/GetUsedFontsCommand.cs, line 169 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4304#-MWW25_D9UZGLFwFlkjE:-MWWMDxD4PNyuJv4GuAm:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3f9d871f63c6e5d39a780e64c2088d44f6baf9f8/src/BloomExe/CLI/GetUsedFontsCommand.cs#L169)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Something about this name made me expect it to be the content of the {} rather than the entire rule. What would you think of 'wholeRule{forLang}'?
</blockquote></details>

Done.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4304)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
