### PR TITLE
BL-12403 Books on Blorg progress bar

### PR DESCRIPTION
**Pull request by gmartin7**
* progress bar itself looks good
* now gets book counts from BL.org
* transition doesn't really work the way I'd like

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065)* status: all files reviewed, 4 unresolved discussions (waiting on @gmartin7)

___
*[`DistFiles/localization/en/Bloom.xlf` line 294 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065#-NcTyQeP0ano61JsBXUv:-NcTyQeP0ano61JsBXUw:b6anh4j) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ca94656970fc345d83f223a9a2cd6200187cbdbd/DistFiles/localization/en/Bloom.xlf#L294)):*
> ```XML
>         <note>minimal question indicating a link to information</note>
>       </trans-unit>
>       <trans-unit id="BooksOnBlorg.Progress.Goal" sil:dynamic="true">
> ```

Needs our standard `translate="no"` and a comment stating these are new for 5.6.
___
*[`src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx` line 71 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065#-NcU1pDz7aemH4dPNcCK:-NcU1pDz7aemH4dPNcCL:b-5u3egj) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ca94656970fc345d83f223a9a2cd6200187cbdbd/src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx#L71)):*
> ```XML
>                         height: 25px;
>                         width: 260px;
>                         transition: all 2s linear;
> ```

What don't you like about it?
Seems slow to me (without having seen it).

Did you try to mimic any other behavior we have elsewhere?

Probably need a gif in the card to show JH.
___
*[`src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx` line 93 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065#-NcU2-cU2orTDZKP_IEo:-NcU2-cU2orTDZKP_IEp:b5fw10q) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ca94656970fc345d83f223a9a2cd6200187cbdbd/src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx#L93)):*
> ```XML
>             ) : (
>                 <React.Fragment />
>             )}
> ```

Do you need the ternary operator with the fragment?
Or can you just do `percentage > -1 && <div>...</div>`?
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 231 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065#-NcU-HI77gbCWB0YQIyn:-NcU-HI77gbCWB0YQIyo:b-hlnnrb) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ca94656970fc345d83f223a9a2cd6200187cbdbd/src/BloomExe/web/controllers/CollectionApi.cs#L231)):*
> ```Smalltalk
> 			var client = new BloomParseClient();
> 			var query = "{\"langPointers\":{\"$inQuery\":{\"where\":{\"isoCode\":\"" + _settings.Language1Tag + "\"},\"className\":\"language\"}}}";
> 			var count = client.GetBookCount(query);
> ```

Let's move the parse-specific logic out of the CollectionApi class.
How about here we call
`client.GetBookCountByLanguage(_settings.Language1Tag)`
which, in turn, contains the parse smarts?

Plus, who knows if we won't want to reuse a `client.GetBookCountByLanguage()` method at some point?


On another note, I see why you weren't initially thinking of putting this handler in CollectionApi. Your component has little to do with collections other than the language comes from the collection. But I don't think there's a better place at this point.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065)* status: all files reviewed, 4 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 231 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065#-NcU-HI77gbCWB0YQIyn:-NcU2T6I8zw2YPbgxeaf:bjchvz0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ca94656970fc345d83f223a9a2cd6200187cbdbd/src/BloomExe/web/controllers/CollectionApi.cs#L231)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's move the parse-specific logic out of the CollectionApi class.
How about here we call
`client.GetBookCountByLanguage(_settings.Language1Tag)`
which, in turn, contains the parse smarts?

Plus, who knows if we won't want to reuse a `client.GetBookCountByLanguage()` method at some point?


On another note, I see why you weren't initially thinking of putting this handler in CollectionApi. Your component has little to do with collections other than the language comes from the collection. But I don't think there's a better place at this point.
</blockquote></details>

I suppose you could have put it in CollectionSettings just so it was with the other related ones. But that doesn't particularly seem better.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065)* status: 7 of 12 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/Bloom.xlf` line 294 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065#-NcTyQeP0ano61JsBXUv:-NcUDB8R5r8pa7UInGCc:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ca94656970fc345d83f223a9a2cd6200187cbdbd/DistFiles/localization/en/Bloom.xlf#L294)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Needs our standard `translate="no"` and a comment stating these are new for 5.6.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx` line 71 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065#-NcU1pDz7aemH4dPNcCK:-NcUUHss5SEQop7r5i4b:blu978i) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ca94656970fc345d83f223a9a2cd6200187cbdbd/src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx#L71)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What don't you like about it?
Seems slow to me (without having seen it).

Did you try to mimic any other behavior we have elsewhere?

Probably need a gif in the card to show JH.
</blockquote></details>

All other changes, including JH's new version of UI are in now. I can look at transition again Monday.
___
*[`src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx` line 93 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065#-NcU2-cU2orTDZKP_IEo:-NcUDSo4BTquiD8qsKYm:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ca94656970fc345d83f223a9a2cd6200187cbdbd/src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx#L93)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Do you need the ternary operator with the fragment?
Or can you just do `percentage > -1 && <div>...</div>`?
</blockquote></details>

Done.
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 231 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065#-NcU-HI77gbCWB0YQIyn:-NcUJixX17ZQkvOX1-pg:bscqkny) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ca94656970fc345d83f223a9a2cd6200187cbdbd/src/BloomExe/web/controllers/CollectionApi.cs#L231)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I suppose you could have put it in CollectionSettings just so it was with the other related ones. But that doesn't particularly seem better.
</blockquote></details>

Good idea! Done. (The BooksOnWebGoal is now in CollectionSettings too.)

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

**Comment by andrew-polk** [comment]
*[`src/BloomExe/WebLibraryIntegration/BloomParseClient.cs` line 158 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065#-NcUeUQd9Ber_ahwOOKU:-NcUeUQd9Ber_ahwOOKV:b-io0fq1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e7cb530ba3d9758f6a9e25125efb075f442b1e19/src/BloomExe/WebLibraryIntegration/BloomParseClient.cs#L158)):*
> ```Smalltalk
> 		public int GetBookCountByLanguage(string languageCode)
> 		{
> 			var query = "{\"langPointers\":{\"$inQuery\":{\"where\":{\"isoCode\":\"" + languageCode + "\"},\"className\":\"language\"}}}";
> ```

Oops. I just realized we dropped the rebrand part.

I think it will be
"{\"langPointers\":{\"$inQuery\":{\"where\":{\"isoCode\":\"" + languageCode + "\"},\"className\":\"language\"}},\"rebrand\":{\"$ne\":true}}"

**Comment by andrew-polk** [comment]
*[`src/BloomExe/WebLibraryIntegration/BloomParseClient.cs` line 158 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065#-NcUeUQd9Ber_ahwOOKU:-Nch9wz21eV1M9zZbYex:b-dgl4ma) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e7cb530ba3d9758f6a9e25125efb075f442b1e19/src/BloomExe/WebLibraryIntegration/BloomParseClient.cs#L158)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Oops. I just realized we dropped the rebrand part.

I think it will be
"{\"langPointers\":{\"$inQuery\":{\"where\":{\"isoCode\":\"" + languageCode + "\"},\"className\":\"language\"}},\"rebrand\":{\"$ne\":true}}"
</blockquote></details>

And we need to exclude books out of circulation and drafts.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/WebLibraryIntegration/BloomParseClient.cs` line 158 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065#-NcUeUQd9Ber_ahwOOKU:-NcxGm30APb22wIJnuez:b-9z0pq5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e7cb530ba3d9758f6a9e25125efb075f442b1e19/src/BloomExe/WebLibraryIntegration/BloomParseClient.cs#L158)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

And we need to exclude books out of circulation and drafts.
</blockquote></details>

Done. (I think you had it right; I had to fiddle with where I put the bits in relation to the various curly braces, but I got it eventually.)

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx` line 71 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065#-NcU1pDz7aemH4dPNcCK:-NcxqlzF2CSuUG0uLG1M:b-uagf0c) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ca94656970fc345d83f223a9a2cd6200187cbdbd/src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx#L71)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

All other changes, including JH's new version of UI are in now. I can look at transition again Monday.
</blockquote></details>

Used MUI's Fade component.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Review by andrew-polk — APPROVED** [review]
Code looks good. Needs UI review for the transition.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065#-:-NcxsqRk0j1-Dq5cdXdS:bw9jb63)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Review by gmartin7 — COMMENTED** [review]
Switched to 600ms and ease (default) transition, instead of linear.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065#-:-Nd18xXG0BPg_5dz2GMY:bsq2c4f)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
