### PR TITLE
Move FontAnalytics class to SIL.Reporting in libpalaso (BL-11641)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This required updating all of the libpalaso assemblies and a number of their dependencies.

- - -
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5560)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5560)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/BloomExe.csproj` line 1737 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5560#-NJHnuib-yJxGDbeKekc:-NJHnuib-yJxGDbeKekd:brbew8d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/84b02bc4c683de046023f3b03589e764e6e72384/src/BloomExe/BloomExe.csproj#L1737)):*
> ```XML
>   <Import Project="..\..\packages\SIL.Media.11.0.0-beta0050\build\SIL.Media.targets" Condition="Exists('..\..\packages\SIL.Media.11.0.0-beta0050\build\SIL.Media.targets')" />
>   <Import Project="..\..\packages\SIL.Windows.Forms.11.0.0-beta0050\build\SIL.Windows.Forms.targets" Condition="Exists('..\..\packages\SIL.Windows.Forms.11.0.0-beta0050\build\SIL.Windows.Forms.targets')" />
>   <Import Project="..\..\packages\SIL.Windows.Forms.Keyboarding.11.0.0-beta0050\build\SIL.Windows.Forms.Keyboarding.targets" Condition="Exists('..\..\packages\SIL.Windows.Forms.Keyboarding.11.0.0-beta0050\build\SIL.Windows.Forms.Keyboarding.targets')" />
> ```

Unfortunately, we can't allow the automatic changes to move these Imports down here. See comment just below.

Same for tests project.
___
*[`src/BloomExe/packages.config` line 98 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5560#-NJHoQl09QqKL6KccH10:-NJHoQl09QqKL6KccH11:bk5p5jn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/84b02bc4c683de046023f3b03589e764e6e72384/src/BloomExe/packages.config#L98)):*
> ```XML
>   <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net472" />
>   <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net472" />
>   <package id="System.Security.Cryptography.X509Certificates" version="4.3.0" targetFramework="net472" />
> ```

What in the world did someone add to libpalaso bring these in?
Does this mean they get included in the installer now?

**Comment by andrew-polk** [comment]
*[`src/BloomExe/packages.config` line 98 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5560#-NJHoQl09QqKL6KccH10:-NJHqs441QsyHAr6NuSI:b79or0f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/84b02bc4c683de046023f3b03589e764e6e72384/src/BloomExe/packages.config#L98)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What in the world did someone add to libpalaso bring these in?
Does this mean they get included in the installer now?
</blockquote></details>

Sigh. I tried to answer the first question myself. No obvious change in the last several months... There are two .cs files which have referenced Security.Cryptography for a long time now. So something is just now catching up??

It would be nice to know if this is bloating the installer, though, as I'm sure we don't need them.

**Comment by andrew-polk** [comment]
*[`src/BloomExe/packages.config` line 98 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5560#-NJHoQl09QqKL6KccH10:-NJHrdu_4oKTXyXoc2Xh:bjpy10z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/84b02bc4c683de046023f3b03589e764e6e72384/src/BloomExe/packages.config#L98)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sigh. I tried to answer the first question myself. No obvious change in the last several months... There are two .cs files which have referenced Security.Cryptography for a long time now. So something is just now catching up??

It would be nice to know if this is bloating the installer, though, as I'm sure we don't need them.
</blockquote></details>

Looks like these four dlls is a little over 1MB.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5560)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/BloomExe.csproj` line 1737 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5560#-NJHnuib-yJxGDbeKekc:-NJI77jO9af2Sr6_PPT5:bvuqklj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/84b02bc4c683de046023f3b03589e764e6e72384/src/BloomExe/BloomExe.csproj#L1737)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Unfortunately, we can't allow the automatic changes to move these Imports down here. See comment just below.

Same for tests project.
</blockquote></details>

I moved the Import elements to the suggested location with other Import elements just before the AfterBuild target element.
___
*[`src/BloomExe/packages.config` line 98 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5560#-NJHoQl09QqKL6KccH10:-NJI7KsaETLe9IPnkl2q:b-h8jti6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/84b02bc4c683de046023f3b03589e764e6e72384/src/BloomExe/packages.config#L98)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like these four dlls is a little over 1MB.
</blockquote></details>

I'm sure some function in the mass of assembly classes (which we probably never call) uses an assembly which uses one of these which uses the others.  libpalaso is sometimes not yet fine grained enough for our liking.  All I know is, before I let the automatic updating do its thing, I was getting test failures.  If you want to wait until January, I could try omitting these three assemblies in the packages.config and csproj files.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5560)* status: 8 of 13 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/packages.config` line 98 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5560#-NJHoQl09QqKL6KccH10:-NJIDzNT1ZriATTwXt-Y:b7cilpl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/84b02bc4c683de046023f3b03589e764e6e72384/src/BloomExe/packages.config#L98)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I'm sure some function in the mass of assembly classes (which we probably never call) uses an assembly which uses one of these which uses the others.  libpalaso is sometimes not yet fine grained enough for our liking.  All I know is, before I let the automatic updating do its thing, I was getting test failures.  If you want to wait until January, I could try omitting these three assemblies in the packages.config and csproj files.
</blockquote></details>

I've removed the four cryptography assemblies with no apparent ill effect.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 5 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5560)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

___
*[`src/BloomExe/BloomExe.csproj` line 1737 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5560#-NJHnuib-yJxGDbeKekc:-NJRFbqDDGtnOKrG7DVM:bkd1eun) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/84b02bc4c683de046023f3b03589e764e6e72384/src/BloomExe/BloomExe.csproj#L1737)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I moved the Import elements to the suggested location with other Import elements just before the AfterBuild target element.
</blockquote></details>

I decided it would be easier to make the change myself than try to communicate the problem I was seeing with the imports.  I was probably wrong. But what's done is done...

**Pull request merged**
