### PR TITLE
Prepare bulk edit for customer use (BL-9997)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545)* status: all files reviewed, 12 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/CLI/UploadCommand.cs, line 43 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbw1q1iBJJAb6Bu8NON:-Mbw1q1iBJJAb6Bu8NOO:bzb6msj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/CLI/UploadCommand.cs#L43)):*
> ```
> if present, upload -d <dest> must be
> ```
Since we have the shortcut `-d`, should we make the option called `destination`?
Then maybe here and below, we should have something like `if present, -destination (-d) must be`?
Or perhaps just `if present, destination (-d) must be`?

Also, I think we want all these statements throughout to be sentences.
___
*[src/BloomExe/CLI/UploadCommand.cs, line 99 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-MbvzxEiBVTHK5J6KtMi:-MbvzxEiBVTHK5J6KtMj:blfpqpr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/CLI/UploadCommand.cs#L99)):*
> ```
> or the current default
> ```
I don't know what this means.
___
*[src/BloomExe/Publish/PublishModel.cs, line 183 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbvtr6ZCkzfdhN8MrV_:-Mbvtr6ZCkzfdhN8MrVa:b-a5fgco) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/Publish/PublishModel.cs#L183)):*
> ```
> _currentlyLoadedBook = BookSelection?.CurrentSelection
> ```
This is just a nit, but I think it is confusing to have the elvis operator here since if BookSelection is null, it will crash on the next line.
___
*[src/BloomExe/WebLibraryIntegration/BloomParseClient.cs, line 77 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbw3Pab8jQ_fhCJY3Ln:-Mbw3Pab8jQ_fhCJY3Lo:bypfst0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BloomParseClient.cs#L77)):*
> ```
> BookTransfer.Destination == UploadDestination.Production ? false : BookTransfer.UseSandbox
> ```
It seems like having two parameters (Destination & UseSandbox) which mean almost (exactly?) the same thing but used in different contexts is only going to create future confusion.
Can we consolidate to one?

Then even more confusing is that BookTransfer also sometimes gets the Destination from the options object.
___
*[src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, line 38 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbw5An-AiWPJxajocrQ:-Mbw5An-AiWPJxajocrR:b-5dtoec) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L38)):*
> ```Smalltalk
> 		public const string SandboxBucketName = "BloomLibraryBooks-Sandbox";
> 		public const string ProductionBucketName = "BloomLibraryBooks";
> 		public const string DryRunBucketName = "dry-run";	// dummy name for "dry runs" that don't actually upload anything
> ```

I'm not very excited about hijacking bucket name to indicate a dry run.

Thinking a totally different direction... and obviously not having a good sense of how well it would work...
I wonder about the possibility of having a DryRunBloomS3Client or ReadOnlyBloomS3Client class which either extends BloomS3Client and overrides certain virtual methods or which inherits from a common abstract class.
I think that might make the code simpler, getting rid of all the places we check for dryrun bucket before doing something meaningful (which would also be more future-proof, perhaps?).
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 455 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbw6VaN5P0wtsPe1BkD:-Mbw6VaN5P0wtsPe1BkE:b9yiqeh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L455)):*
> ```Smalltalk
> 					var metaMsg = LocalizationManager.GetString("PublishTab.Upload.UploadingBookMetadata", "Uploading book metadata", "In this step, Bloom is uploading things like title, languages, and topic tags to the BloomLibrary.org database.");
> 					progress.WriteStatus(metaMsg);
> 					Console.WriteLine(metaMsg);
> ```

Should we be using a ConsoleProgress?
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 523 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbw6uf361HMETyEak_D:-Mbw6uf361HMETyEak_E:b-tbeoup) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L523)):*
> ```
> AppendErrorMessageToUploadLogFile(msg1, msg2);
> ```
Why don't we want to do this for a dry run?

Oh, I think I see. We aren't creating this file at all for a dry run. Seems like we should be so the user can view it? Then I guess we need to call it something different so it doesn't cause problems with the real run. Like append "DryRun" or something?
Then, of course, if we go this route, we can get rid of the conditional logic for the other places we write to the log file.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 662 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbw7BwD7n97yyXlKl30:-Mbw7BwD7n97yyXlKl31:byq23r4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L662)):*
> ```
> Sorry, this version of Bloom Desktop
> ```
Why don't we want to report this for a dry run?
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 677 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbw7fk-8Zy3kg8m8Ybc:-Mbw7fk-8Zy3kg8m8Ybd:bc950lu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L677)):*
> ```Smalltalk
> 						Console.WriteLine("signing out.  This will enable logging in for the bulk upload operation.");
> 						return;
> 					}
> ```

Again, I don't see why we wouldn't report this for a dry run.

And there is some funky indentation here.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 758 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-MbwA4M97pghNOx6p9sQ:-MbwA4M97pghNOx6p9sR:b-s6xhzv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L758)):*
> ```Smalltalk
> 			{
> 				Console.WriteLine("CAUGHT EXCEPTION: {0}", e.Message);
> 				Console.WriteLine(e.StackTrace);
> ```

Why do want to squash the exception at this level? 
Unless I'm missing something, we then try to deal with it again when the background worker completed.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 964 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-MbwBFODATKov4uMoRZm:-MbwBFODATKov4uMoRZn:b-5kpox5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L964)):*
> ```Smalltalk
> 			// and they apply to the book as a whole.
> 			if (bookParams.Dest != UploadDestination.DryRun)
> 				book.BookInfo.LanguageTableReferences = _parseClient.GetLanguagePointers(book.BookData.MakeLanguageUploadData(bookParams.LanguagesToUpload));
> ```

Is the idea here that in a dry run we don't need the information so save the cycles?

If you can't tell... I'm highly suspect of each logical fork based on DryRun.
Each one feels like a footgun, so I'm in favor of reducing them as much as possible.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 975 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-MbwBxLC84DLYhdV5t-U:-MbwBxLC84DLYhdV5t-V:b-abgcbr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L975)):*
> ```
> 				progressBox.WriteStatus(thumbnailMsg);
> 				Console.WriteLine(thumbnailMsg);
> ```
Do all these repetitions warrant a little utility method?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545)* status: all files reviewed, 11 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 455 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbw6VaN5P0wtsPe1BkD:-McBJx984lkXcfbAFT2S:b-9i6ufx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L455)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should we be using a ConsoleProgress?
</blockquote></details>

Steve and I talked about this. I thought we were simply not making use of `progress` at this point and thought it would be easy to just pass in a ConsoleProgress. But `progress` is a progress dialog at this point.
So never mind.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545)* status: all files reviewed, 11 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/CLI/UploadCommand.cs, line 43 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbw1q1iBJJAb6Bu8NON:-MbwdFHfDvxa322e4DhT:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/CLI/UploadCommand.cs#L43)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> if present, upload -d <dest> must be
> ```
Since we have the shortcut `-d`, should we make the option called `destination`?
Then maybe here and below, we should have something like `if present, -destination (-d) must be`?
Or perhaps just `if present, destination (-d) must be`?

Also, I think we want all these statements throughout to be sentences.
</blockquote></details>

Done.
___
*[src/BloomExe/CLI/UploadCommand.cs, line 99 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-MbvzxEiBVTHK5J6KtMi:-Mbwfe1Z88CRSsVlneqM:b-tglout) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/CLI/UploadCommand.cs#L99)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> or the current default
> ```
I don't know what this means.
</blockquote></details>

I deleted this final phrase:  I think it's restating the same thing because the "current default" is the last one opened (by the current version of Bloom).
___
*[src/BloomExe/Publish/PublishModel.cs, line 183 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbvtr6ZCkzfdhN8MrV_:-Mbwgl0rEEIbZd3V8nNv:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/Publish/PublishModel.cs#L183)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> _currentlyLoadedBook = BookSelection?.CurrentSelection
> ```
This is just a nit, but I think it is confusing to have the elvis operator here since if BookSelection is null, it will crash on the next line.
</blockquote></details>

Done.
___
*[src/BloomExe/WebLibraryIntegration/BloomParseClient.cs, line 77 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbw3Pab8jQ_fhCJY3Ln:-Mbwn3sl4jRBybPbuOE1:bu9mbix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BloomParseClient.cs#L77)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> BookTransfer.Destination == UploadDestination.Production ? false : BookTransfer.UseSandbox
> ```
It seems like having two parameters (Destination & UseSandbox) which mean almost (exactly?) the same thing but used in different contexts is only going to create future confusion.
Can we consolidate to one?

Then even more confusing is that BookTransfer also sometimes gets the Destination from the options object.
</blockquote></details>

I've made Destination be the ruling value.  I added a couple of static boolean checks based off of it (IsDryRun and IsTesting).
___
*[src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, line 38 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbw5An-AiWPJxajocrQ:-Mbx14KL7ik4Q7qO-Xu9:b-39tjfb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L38)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not very excited about hijacking bucket name to indicate a dry run.

Thinking a totally different direction... and obviously not having a good sense of how well it would work...
I wonder about the possibility of having a DryRunBloomS3Client or ReadOnlyBloomS3Client class which either extends BloomS3Client and overrides certain virtual methods or which inherits from a common abstract class.
I think that might make the code simpler, getting rid of all the places we check for dryrun bucket before doing something meaningful (which would also be more future-proof, perhaps?).
</blockquote></details>

I've changed to using BookTransfer.IsDryRun for the check.
I'm not sure defining a DryRun class would really simplify things.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 455 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbw6VaN5P0wtsPe1BkD:-Mbx821LCC2VlrouZNPh:bxj4fue) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L455)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should we be using a ConsoleProgress?
</blockquote></details>

The progress is built into the dialog that runs the background thread.  It might be possible to work around this, but some of the details in the code looked way too complicated to tackle just for fun.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 523 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbw6uf361HMETyEak_D:-MbxJFTG2-1QqcDsDngk:bk4k8es) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L523)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> AppendErrorMessageToUploadLogFile(msg1, msg2);
> ```
Why don't we want to do this for a dry run?

Oh, I think I see. We aren't creating this file at all for a dry run. Seems like we should be so the user can view it? Then I guess we need to call it something different so it doesn't cause problems with the real run. Like append "DryRun" or something?
Then, of course, if we go this route, we can get rid of the conditional logic for the other places we write to the log file.
</blockquote></details>

I've changed to having the dry run write to DryRunBloomBulkUploadLog.txt (while still reading BloomBulkUploadLog.txt initially for the list of files already uploaded).
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 662 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbw7BwD7n97yyXlKl30:-Mbx9eZE-gx9dumRz1sS:b-usedlg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L662)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Sorry, this version of Bloom Desktop
> ```
Why don't we want to report this for a dry run?
</blockquote></details>

Because it was crashing?  Probably due to the fake dry-run S3 bucket.  So that check can be removed here now.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 677 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbw7fk-8Zy3kg8m8Ybc:-MbxAl3YDaO85CAnbsVX:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L677)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Again, I don't see why we wouldn't report this for a dry run.

And there is some funky indentation here.
</blockquote></details>

Done.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 758 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-MbwA4M97pghNOx6p9sQ:-MbxCA344oqvTtG4z8Ah:bhv8bzu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L758)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Why do want to squash the exception at this level? 
Unless I'm missing something, we then try to deal with it again when the background worker completed.
</blockquote></details>

I've verified that the exception message and stack are displayed in the outer context.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 964 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-MbwBFODATKov4uMoRZm:-MbxJnpvA7WoCH41kFvG:b-p2r4sh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L964)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is the idea here that in a dry run we don't need the information so save the cycles?

If you can't tell... I'm highly suspect of each logical fork based on DryRun.
Each one feels like a footgun, so I'm in favor of reducing them as much as possible.
</blockquote></details>

OK, I'll let it hit the parse server again...
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 975 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-MbwBxLC84DLYhdV5t-U:-MbxL22661HoUn8d2WxA:b-wg77q3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L975)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> 				progressBox.WriteStatus(thumbnailMsg);
> 				Console.WriteLine(thumbnailMsg);
> ```
Do all these repetitions warrant a little utility method?
</blockquote></details>

The problem is that progress uses a combination of WriteStatus, WriteMessage, WriteError, and WriteVerbose, so there's less commonality than appears at first glance.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545)* status: all files reviewed, 6 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/CLI/UploadCommand.cs, line 43 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbw1q1iBJJAb6Bu8NON:-McBVdbs3NyGlmfmEJpS:bb5co1e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/CLI/UploadCommand.cs#L43)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks. What I meant to say is that these console messages which are sentences want to have periods at the end.
___
*[src/BloomExe/WebLibraryIntegration/BloomParseClient.cs, line 77 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbw3Pab8jQ_fhCJY3Ln:-McBZ_1eEucO0SUgf731:b6dd91t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BloomParseClient.cs#L77)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I've made Destination be the ruling value.  I added a couple of static boolean checks based off of it (IsDryRun and IsTesting).
</blockquote></details>

I might just be missing something, but seems like a production dry run is going to get the wrong (dev) parse url here.

Same for BloomLibraryUploadControl::BloomLibraryUrlPrefix though it is probably less likely to matter there?

Later:
After seeing UploadBucketNameForCurrentEnvironment again, now I'm thinking the model is wrong.
If I understand correctly, currently dry-run will always give development data including login.
Or maybe all these places don't matter because we don't really use their values in dry-run?
Sorry, these are probably confusing comments; can discuss if helpful.

It seems like we need one of the following:
1. dry-run is always production
2. dry-run/real-run and prod/dev need to be two separate switches
3. we need to introduce dry-run-dev

I certainly haven't thought through all the implications here, but one thing which might end up helping is to change the current IsTesting to IsProductionRun (and reverse the logic) or IsNotProductionRun for the analytics switches (but those switches might be the only place that ends up being used?).
___
*[src/BloomExe/WebLibraryIntegration/BloomParseClient.cs, line 23 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-McBbegw9pRu-965iu5A:-McBbegw9pRu-965iu5B:b-6x9ioj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac381aadf9400273cc97ab0e6d0de251b2a990e0/src/BloomExe/WebLibraryIntegration/BloomParseClient.cs#L23)):*
> ```Smalltalk
> 		public BloomParseClient()
> 		{
> 			var keys = AccessKeys.GetAccessKeys(BookTransfer.UploadBucketNameForCurrentEnvironment);
> ```

Sorry; my fault for asking that you get rid of the DryRun bucket...
But now this is getting real credentials with write permissions even for dry runs.
How we can effectively safeguard to ensure we don't do anything accidentally?

Ideas (but open to whatever):
1. Go back to clearing the credentials here when we have a dry run. (I think that would mean re-reversing a couple other logical branches based on dry run?) What we really want are read-only credentials, but I don't think we can do that easily... But on second thought, maybe everything is public read so this would work?
2. Making an early out for all the methods here which do write/delete.
3. Return null for each of MakePostRequest, MakePutRequest, MakeDeleteRequest. I'm guessing that the fallout of that would be annoying...
4. ?
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 523 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbw6uf361HMETyEak_D:-McBWkOGCX0vtKQsVslG:bg5wwg4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L523)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I've changed to having the dry run write to DryRunBloomBulkUploadLog.txt (while still reading BloomBulkUploadLog.txt initially for the list of files already uploaded).
</blockquote></details>

The errors here are still only getting written if not dryrun.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 369 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-McBfukb9PQAvn4O-CuL:-McBfukb9PQAvn4O-CuM:bywuiym) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac381aadf9400273cc97ab0e6d0de251b2a990e0/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L369)):*
> ```
> bool dryrun = false
> ```
This can just use the static now?
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 1088 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-McBf7cm7pzjziUve_n8:-McBf7cm7pzjziUve_n9:b-plke40) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac381aadf9400273cc97ab0e6d0de251b2a990e0/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L1088)):*
> ```
> public string Dest;
> ```
Should this be deleted now?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545)* status: all files reviewed, 6 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/CLI/UploadCommand.cs, line 43 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbw1q1iBJJAb6Bu8NON:-McFEFBdEdlCz5M307ZL:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/CLI/UploadCommand.cs#L43)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Thanks. What I meant to say is that these console messages which are sentences want to have periods at the end.
</blockquote></details>

Done.
___
*[src/BloomExe/WebLibraryIntegration/BloomParseClient.cs, line 77 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbw3Pab8jQ_fhCJY3Ln:-McFHlv82sr5XWf3truu:bfp33gi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BloomParseClient.cs#L77)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I might just be missing something, but seems like a production dry run is going to get the wrong (dev) parse url here.

Same for BloomLibraryUploadControl::BloomLibraryUrlPrefix though it is probably less likely to matter there?

Later:
After seeing UploadBucketNameForCurrentEnvironment again, now I'm thinking the model is wrong.
If I understand correctly, currently dry-run will always give development data including login.
Or maybe all these places don't matter because we don't really use their values in dry-run?
Sorry, these are probably confusing comments; can discuss if helpful.

It seems like we need one of the following:
1. dry-run is always production
2. dry-run/real-run and prod/dev need to be two separate switches
3. we need to introduce dry-run-dev

I certainly haven't thought through all the implications here, but one thing which might end up helping is to change the current IsTesting to IsProductionRun (and reverse the logic) or IsNotProductionRun for the analytics switches (but those switches might be the only place that ends up being used?).

</blockquote></details>

I've revised the code to use production if requested, use the sandbox if requested, and for dry runs (no explicit target request), use whatever the default is for the current environment (debug build or checking the BloomSandbox environment variable).  So users who haven't set that environment variable will always target production for dry runs.  Developers and testers can fiddle with that environment variable to target what they want.  (for release builds)
After various adjustments, changing IsTesting to IsProductionRun was obviously the right thing to do.
___
*[src/BloomExe/WebLibraryIntegration/BloomParseClient.cs, line 23 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-McBbegw9pRu-965iu5A:-McFM6w36AJwIseyY_-v:bzfaot1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac381aadf9400273cc97ab0e6d0de251b2a990e0/src/BloomExe/WebLibraryIntegration/BloomParseClient.cs#L23)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; my fault for asking that you get rid of the DryRun bucket...
But now this is getting real credentials with write permissions even for dry runs.
How we can effectively safeguard to ensure we don't do anything accidentally?

Ideas (but open to whatever):
1. Go back to clearing the credentials here when we have a dry run. (I think that would mean re-reversing a couple other logical branches based on dry run?) What we really want are read-only credentials, but I don't think we can do that easily... But on second thought, maybe everything is public read so this would work?
2. Making an early out for all the methods here which do write/delete.
3. Return null for each of MakePostRequest, MakePutRequest, MakeDeleteRequest. I'm guessing that the fallout of that would be annoying...
4. ?
</blockquote></details>

I've changed GetAccessKeys to not return S3 keys for BookTransfer.IsDryRun.  We need the Parse keys to handle testing IsThisVersionAllowedToUpload and logging in.
I put checks for BT.IsDryRun in the methods that write/delete in the parse client.  (#2 above, except that they're throwing an error because they shouldn't even get called.)  I don't think they're really needed at the moment, but caution is probably good for long-term safety.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 523 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-Mbw6uf361HMETyEak_D:-McFIQgA6Oxxy2FVJMLf:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0dde3b33eada34887a7d36805dc712d7b7ce7893/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L523)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The errors here are still only getting written if not dryrun.
</blockquote></details>

Done.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 369 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-McBfukb9PQAvn4O-CuL:-McFHbJb40x-vi29H8bv:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac381aadf9400273cc97ab0e6d0de251b2a990e0/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L369)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> bool dryrun = false
> ```
This can just use the static now?
</blockquote></details>

Done.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 1088 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545#-McBf7cm7pzjziUve_n8:-McFIkFO2wyugYu2Ivjl:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ac381aadf9400273cc97ab0e6d0de251b2a990e0/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L1088)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> public string Dest;
> ```
Should this be deleted now?
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
