### PR TITLE
BL-6657 Correct Accessibility checker for text box audio

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2836)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2836)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Book/AccessibilityCheckers.cs, line 157 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2836#-LPfztJh5VR9L9MF7Biw:-LPfztJh5VR9L9MF7Bix:bqqb1u0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15b525e16fce4a102a593b0baf676adc0e29b5b5/src/BloomExe/Book/AccessibilityCheckers.cs#L157)):*
> ```Smalltalk
> 						{
> 							// recurse down the tree, if we find a problem return it.
> 							foreach (XmlNode child in node.ChildNodes)
> ```

I'm sure I'm just not following the algorithm properly, but it feels like we are losing the ability to process multiple siblings (like two spans next to each other).
I'm having a hard time seeing if we have a test where the first sibling has audio and a subsequent one doesn't.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2836)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Book/AccessibilityCheckers.cs, line 157 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2836#-LPfztJh5VR9L9MF7Biw:-LPgNaNf9vb1mjw3-2Sx:b-1u9w0t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15b525e16fce4a102a593b0baf676adc0e29b5b5/src/BloomExe/Book/AccessibilityCheckers.cs#L157)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm sure I'm just not following the algorithm properly, but it feels like we are losing the ability to process multiple siblings (like two spans next to each other).
I'm having a hard time seeing if we have a test where the first sibling has audio and a subsequent one doesn't.
</blockquote></details>

The loop moved from outside to inside the last else (here). If any child of node has a problem it should be reported. I'll check for test case.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2836)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/BloomExe/Book/AccessibilityCheckers.cs, line 157 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2836#-LPfztJh5VR9L9MF7Biw:-LPgPClaBtzPxJIHdfnY:balc8br) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15b525e16fce4a102a593b0baf676adc0e29b5b5/src/BloomExe/Book/AccessibilityCheckers.cs#L157)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

The loop moved from outside to inside the last else (here). If any child of node has a problem it should be reported. I'll check for test case.
</blockquote></details>

Ok, taking another look, I think it is okay. I think I got confused by the change you made to the comments which used to say move to next sibling and was thinking there was now a path where we stopped processing siblings.
If you find the appropriate test case, go ahead and merge.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2836)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/BloomExe/Book/AccessibilityCheckers.cs, line 157 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2836#-LPfztJh5VR9L9MF7Biw:-LPgQKyV5vs8BMd6FWQL:bueqw3t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15b525e16fce4a102a593b0baf676adc0e29b5b5/src/BloomExe/Book/AccessibilityCheckers.cs#L157)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Ok, taking another look, I think it is okay. I think I got confused by the change you made to the comments which used to say move to next sibling and was thinking there was now a path where we stopped processing siblings.
If you find the appropriate test case, go ahead and merge.
</blockquote></details>

I made it return null if the first child has no problems, and around 8 tests fail.

**Pull request merged**
