### PR TITLE
[WIP; Don't merge] BL-8058 Re-add dashed border to template thumb

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomExe/BookThumbNailer.cs, line 104 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135#-MQJRJTL6ue_NajQPzxW:-MQJRJTM3KFjqzGl76ak:b7vg4ky) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4dc20cbd4711d2218e2d9bae9d483628430e7795/src/BloomExe/BookThumbNailer.cs#L104)):*
> ```Smalltalk
> 				CenterImageUsingTransparentPadding = false,
> 				FileName = "coverImage200.jpg",
> 				BorderStyle = GetThumbnailBorderStyle(book)
> ```

Though in the end, due to the implementation, it doesn't matter, it still seems wrong to set the BorderStyle to solid for normal book when we won't actually add a border.

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135)* status: all files reviewed, 5 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomExe/BookThumbNailer.cs, line 201 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135#-MQJOhGq8OMY_PDs-A7y:-MQJOhGrCygqUalclACR:beizeyo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4dc20cbd4711d2218e2d9bae9d483628430e7795/src/BloomExe/BookThumbNailer.cs#L201)):*
> ```
> dashedBorder
> ```
This looks like it's a boolean. I would prefer a variable name that implies that, like "isDashedBorder" or "shouldUseDashedBorder" or something like that.

Same comment to the var names in ImageUtils
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 924 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135#-MQJS2kc0EKLS2UemEWP:-MQJS2kc0EKLS2UemEWQ:b9xi4pj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4dc20cbd4711d2218e2d9bae9d483628430e7795/src/BloomExe/ImageProcessing/ImageUtils.cs#L924)):*
> ```Smalltalk
> 		}
> 
> 		public static Image ResizeImageIfNecessary(Size maxSize, Image image, bool dashedBorder)
> ```

I think this function and CenterImageIfNecessary could benefit from unit tests to make sure the border is or isn't drawn correctly.  BookThumbnailerTests  might provide some useful snippets that could be copy/pasted. I guess it's also possible to add the tests in BookThumbnailerTests, but IMO I think it's better in ImageUtilsTests where it's closer/more isolated to the new border-drawing code.
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 956 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135#-MQJPwEy-rAtBgk3MoBO:-MQJPwEy-rAtBgk3MoBP:bt6i960) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4dc20cbd4711d2218e2d9bae9d483628430e7795/src/BloomExe/ImageProcessing/ImageUtils.cs#L956)):*
> ```Smalltalk
> 			{
> 				if (!centerImage)
> 					return new Bitmap(image);
> ```

Would we require drawing a dashed border of this condition is met and dashedBorder = true?
See also a few lines above.
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 984 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135#-MQJQabvEIOEfmlkSxpz:-MQJQabvEIOEfmlkSxq-:b77v6it) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4dc20cbd4711d2218e2d9bae9d483628430e7795/src/BloomExe/ImageProcessing/ImageUtils.cs#L984)):*
> ```Smalltalk
> 				// See https://stackoverflow.com/questions/15438509/graphics-drawimage-throws-out-of-memory-exception?lq=1
> 				// (the second answer).
> 				// Review: I'm just refactoring what's already here, but I don't see how x and y can ever be anything but zero.
> ```

Not an expert in this area, but one conjecture i have from skimming this code: I think newWidth and newHeight could be set to fractional values, but probably newImage.Width is always an integer value?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomExe/BookThumbNailer.cs, line 104 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135#-MQJRJTL6ue_NajQPzxW:-MQJVg3DEC1sP3o-9MX9:bqfl77y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4dc20cbd4711d2218e2d9bae9d483628430e7795/src/BloomExe/BookThumbNailer.cs#L104)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Though in the end, due to the implementation, it doesn't matter, it still seems wrong to set the BorderStyle to solid for normal book when we won't actually add a border.
</blockquote></details>

Changed to None. Previous code used Solid, but I agree, in principle it should be None, since we don't add a border in that case.
___
*[src/BloomExe/BookThumbNailer.cs, line 201 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135#-MQJOhGq8OMY_PDs-A7y:-MQJWq9z90MGipMV8jvB:b-gc1wp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4dc20cbd4711d2218e2d9bae9d483628430e7795/src/BloomExe/BookThumbNailer.cs#L201)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> dashedBorder
> ```
This looks like it's a boolean. I would prefer a variable name that implies that, like "isDashedBorder" or "shouldUseDashedBorder" or something like that.

Same comment to the var names in ImageUtils
</blockquote></details>

I have switched to `shouldAddDashedBorder` here and in ImageUtils.
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 924 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135#-MQJS2kc0EKLS2UemEWP:-MQOsYvQ15zrGX5FC78p:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4dc20cbd4711d2218e2d9bae9d483628430e7795/src/BloomExe/ImageProcessing/ImageUtils.cs#L924)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I think this function and CenterImageIfNecessary could benefit from unit tests to make sure the border is or isn't drawn correctly.  BookThumbnailerTests  might provide some useful snippets that could be copy/pasted. I guess it's also possible to add the tests in BookThumbnailerTests, but IMO I think it's better in ImageUtilsTests where it's closer/more isolated to the new border-drawing code.
</blockquote></details>

Done.
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 956 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135#-MQJPwEy-rAtBgk3MoBO:-MQJZKHE2LjAyA7x629b:b9cy312) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4dc20cbd4711d2218e2d9bae9d483628430e7795/src/BloomExe/ImageProcessing/ImageUtils.cs#L956)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Would we require drawing a dashed border of this condition is met and dashedBorder = true?
See also a few lines above.
</blockquote></details>

Possibly. But unlikely. AFAIK, we come through here twice, once with desiredHeight and desiredWidth set to 200 and once with them set to 70. Both of those are pretty small to be the original size of a front cover image. (Plus the original would have to be square too.)
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 984 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135#-MQJQabvEIOEfmlkSxpz:-MQJZ4553lppXlPNnmL4:b-896kyz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4dc20cbd4711d2218e2d9bae9d483628430e7795/src/BloomExe/ImageProcessing/ImageUtils.cs#L984)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Not an expert in this area, but one conjecture i have from skimming this code: I think newWidth and newHeight could be set to fractional values, but probably newImage.Width is always an integer value?
</blockquote></details>

Both are always `int` values. Changed comment when I found that centering an image uses different values for either x or y.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135)* status: all files reviewed, 5 unresolved discussions (waiting on @gmartin7 and @sujeffreyl)

___
*[src/BloomExe/BookThumbNailer.cs, line 104 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135#-MQJRJTL6ue_NajQPzxW:-MQP-U3DAFw_qRGYlH2_:b-31jnez) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4dc20cbd4711d2218e2d9bae9d483628430e7795/src/BloomExe/BookThumbNailer.cs#L104)):*
> Previous code used Solid

And you're sure we don't have any use case which still wants that? I see the code still exists in MakeThumbNail to make a solid border.

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135)* status: all files reviewed, 5 unresolved discussions (waiting on @gmartin7 and @sujeffreyl)

___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 956 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135#-MQJPwEy-rAtBgk3MoBO:-MQP-tCqEKFkF3XwXE6D:bvr8kpp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4dc20cbd4711d2218e2d9bae9d483628430e7795/src/BloomExe/ImageProcessing/ImageUtils.cs#L956)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Possibly. But unlikely. AFAIK, we come through here twice, once with desiredHeight and desiredWidth set to 200 and once with them set to 70. Both of those are pretty small to be the original size of a front cover image. (Plus the original would have to be square too.)
</blockquote></details>

Hmm, that doesn't sound too reassuring to me, that means that if we did happen to pass in an image that was 199x199, the behavior would be wrong?

I'd prefer to fix that, regardless of how likely it is for us to use a 199 image.

Also, if so, I guess that implies we need a test image that is 199x199.
___
*[src/BloomTests/ImageProcessing/ImageUtilsTests.cs, line 154 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135#-MQOzVXJ7VluViaeqkS0:-MQOzVXJ7VluViaeqkS1:b5hua2n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5de474772d6719bb4515ee9da1b73ee7d28417b0/src/BloomTests/ImageProcessing/ImageUtilsTests.cs#L154)):*
> ```Smalltalk
> 		[TestCase(true, false, 70)] // Center image, no border, small thumb size
> 		[TestCase(true, true, 70)] // Center image, add dashed border, small thumb size
> 		public void DrawResizedImage(bool centerImage, bool addBorder, int desiredSize)
> ```

IMO, let's focus the test just on checking whether the border is drawn or not. That means, just pick one of the two sizes and stick with it (since they're both in the same class of being smaller than the target image), delete the other 4 test cases, delete the asserts that aren't about the border, and make the test name reflect this.
___
*[src/BloomTests/ImageProcessing/ImageUtilsTests.cs, line 209 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135#-MQOymIS6E5_tGCaXEyt:-MQOymIS6E5_tGCaXEyu:b-dz6r5i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5de474772d6719bb4515ee9da1b73ee7d28417b0/src/BloomTests/ImageProcessing/ImageUtilsTests.cs#L209)):*
> ```Smalltalk
> 
> 				if (i == maxX)
> 					hitMax = true;
> ```

I don't think this condition is ever hit. On the last iteration through the loop, i = maxX -1. It gets incremented to equal maxX, then the loop conditional is checked, then we don't re-enter the loop, and this line 209 is never reached, I believe.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135)* status: all files reviewed, 6 unresolved discussions (waiting on @gmartin7 and @sujeffreyl)

___
*[src/BloomTests/ImageProcessing/ImageUtilsTests.cs, line 172 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135#-MQP2iww3TFyuywVYVpW:-MQP2iww3TFyuywVYVpX:b-jph5zg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5de474772d6719bb4515ee9da1b73ee7d28417b0/src/BloomTests/ImageProcessing/ImageUtilsTests.cs#L172)):*
> ```
> shouldHaveBorder
> ```
shouldHaveDashedBorder
___
*[src/BloomTests/ImageProcessing/ImageUtilsTests.cs, line 209 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135#-MQOymIS6E5_tGCaXEyt:-MQP2Lf_52ekdcwgzYej:buo36m6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5de474772d6719bb4515ee9da1b73ee7d28417b0/src/BloomTests/ImageProcessing/ImageUtilsTests.cs#L209)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I don't think this condition is ever hit. On the last iteration through the loop, i = maxX -1. It gets incremented to equal maxX, then the loop conditional is checked, then we don't re-enter the loop, and this line 209 is never reached, I believe.
</blockquote></details>

I think this is hidden by the fact that the assert should be 
Assert.That(shouldHaveBorder == hitMax, Is.False, "Didn't find dashes.");
(or the Is.Not.EqualTo equivalent)

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomExe/BookThumbNailer.cs, line 104 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135#-MQJRJTL6ue_NajQPzxW:-MQY39fiDMrnIaVrcBZs:ber9o9k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4dc20cbd4711d2218e2d9bae9d483628430e7795/src/BloomExe/BookThumbNailer.cs#L104)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> Previous code used Solid

And you're sure we don't have any use case which still wants that? I see the code still exists in MakeThumbNail to make a solid border.
</blockquote></details>

Doesn't look like it.
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 956 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135#-MQJPwEy-rAtBgk3MoBO:-MQSkxra4cw4aMcsaNUQ:bla5n8m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4dc20cbd4711d2218e2d9bae9d483628430e7795/src/BloomExe/ImageProcessing/ImageUtils.cs#L956)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Hmm, that doesn't sound too reassuring to me, that means that if we did happen to pass in an image that was 199x199, the behavior would be wrong?

I'd prefer to fix that, regardless of how likely it is for us to use a 199 image.

Also, if so, I guess that implies we need a test image that is 199x199.
</blockquote></details>

Added a 199x199 test and I'll fix the code before resubmitting
___
*[src/BloomTests/ImageProcessing/ImageUtilsTests.cs, line 154 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135#-MQOzVXJ7VluViaeqkS0:-MQY6boeEtBK5A1W8JLd:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5de474772d6719bb4515ee9da1b73ee7d28417b0/src/BloomTests/ImageProcessing/ImageUtilsTests.cs#L154)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

IMO, let's focus the test just on checking whether the border is drawn or not. That means, just pick one of the two sizes and stick with it (since they're both in the same class of being smaller than the target image), delete the other 4 test cases, delete the asserts that aren't about the border, and make the test name reflect this.
</blockquote></details>

Done.
___
*[src/BloomTests/ImageProcessing/ImageUtilsTests.cs, line 172 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135#-MQP2iww3TFyuywVYVpW:-MQY5gVt2McjNQU_OXfu:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5de474772d6719bb4515ee9da1b73ee7d28417b0/src/BloomTests/ImageProcessing/ImageUtilsTests.cs#L172)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> shouldHaveBorder
> ```
shouldHaveDashedBorder
</blockquote></details>

Done.
___
*[src/BloomTests/ImageProcessing/ImageUtilsTests.cs, line 209 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4135#-MQOymIS6E5_tGCaXEyt:-MQY5O9y09n1bqkMqA9I:b-sc66ze) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5de474772d6719bb4515ee9da1b73ee7d28417b0/src/BloomTests/ImageProcessing/ImageUtilsTests.cs#L209)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this is hidden by the fact that the assert should be 
Assert.That(shouldHaveBorder == hitMax, Is.False, "Didn't find dashes.");
(or the Is.Not.EqualTo equivalent)
</blockquote></details>

Fixed the triggering of hitMax and the Assert in the new PR

**Comment by gmartin7** [comment]
Closing in favor of a new 5.0 PR.

**Pull request closed without merging**
