### PR TITLE
BL-5326 Move colors to common-mixins

### PR DESCRIPTION
**Pull request by gmartin7**
* unfortunately, some spacing issues I cleaned up
   might confuse things a bit, but I'm just refactoring.
* there is probably more that could be done here, but it's
   a bit open-ended.
* from now on, we should strive to put any reuseable colors
   in the common-mixins.less

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2049)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/pageThumbnailList/pageControls/pageControls.less, line 4 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2049#-L22N1MDHBienhmQXn0Y:-L22N1MDHBienhmQXn0Z:b-dwyaox) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/414fd70489bcd2af4c0e72520e71e691c24d952c/src/BloomBrowserUI/bookEdit/pageThumbnailList/pageControls/pageControls.less#L4)):*
> ```Less
> 
> @ButtonDarkerGray: @bloom-darkestgray;
> @bloom-disabledbuttongray: @bloom-gray;
> ```

This feels like something that belongs in common-mixins

---

*[src/BloomBrowserUI/templates/common-mixins.less, line 15 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2049#-L22NcOOwIg-zzpl8jSV:-L22NcOOwIg-zzpl8jSW:b-alhzhs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/414fd70489bcd2af4c0e72520e71e691c24d952c/src/BloomBrowserUI/templates/common-mixins.less#L15)):*
> ```Less
> @bloom-darkgray: #404040;
> @bloom-darkestgray: #363333;
> @bloom-buff: #D2D2D2;
> ```

I hesitate to be critical because you've clearly improved things a lot. But I hate to see all these named after what they are rather than how they are used.  If we ever wanted to introduce a different color scheme, many of these would suddenly be completely wrong.  Surely at least SOME meaningful names could be given? Many of these are re-used with more meaningful names in other files.
If they aren't used uniquely enough for a single meaningful name, maybe you could define some meaningful names in terms of these here? For example, if several things use the main-page background color, maybe you define something like @dialog-border and @main-page-background to both be bloom-darkestgray.
If that's too much work or involves overly difficult decisions at this point, could we at least have some comments that would help someone to know what to pick. For example, suppose I want to make a new toolbar with backgound, button, text, and active-item highlight matching the talking book tool. Ideally I ought be able to look at the names and/or comments here and know which four colors to use. As it is, I would be guessing: the highlight is an orange-ish yellow, is it bloom-yellow, bloom-orange, or maybe one of the salmons? Should the background be gray, darkgray, or darkestgray?
If you don't think this is worth attempting at this point I'm willing to merge as-is, but I'd be happier to see us take a slightly larger step towards maintainability.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2049)*

**Comment by gmartin7** [comment]
Review status: 7 of 20 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/pageThumbnailList/pageControls/pageControls.less, line 4 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2049#-L22N1MDHBienhmQXn0Y:-L26fB8pNUzDVACoAQ-x:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/414fd70489bcd2af4c0e72520e71e691c24d952c/src/BloomBrowserUI/bookEdit/pageThumbnailList/pageControls/pageControls.less#L4)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This feels like something that belongs in common-mixins
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/templates/common-mixins.less, line 15 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2049#-L22NcOOwIg-zzpl8jSV:-L26fDWldvXywh8W3sgt:bkj2zhv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/414fd70489bcd2af4c0e72520e71e691c24d952c/src/BloomBrowserUI/templates/common-mixins.less#L15)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I hesitate to be critical because you've clearly improved things a lot. But I hate to see all these named after what they are rather than how they are used.  If we ever wanted to introduce a different color scheme, many of these would suddenly be completely wrong.  Surely at least SOME meaningful names could be given? Many of these are re-used with more meaningful names in other files.
If they aren't used uniquely enough for a single meaningful name, maybe you could define some meaningful names in terms of these here? For example, if several things use the main-page background color, maybe you define something like @dialog-border and @main-page-background to both be bloom-darkestgray.
If that's too much work or involves overly difficult decisions at this point, could we at least have some comments that would help someone to know what to pick. For example, suppose I want to make a new toolbar with backgound, button, text, and active-item highlight matching the talking book tool. Ideally I ought be able to look at the names and/or comments here and know which four colors to use. As it is, I would be guessing: the highlight is an orange-ish yellow, is it bloom-yellow, bloom-orange, or maybe one of the salmons? Should the background be gray, darkgray, or darkestgray?
If you don't think this is worth attempting at this point I'm willing to merge as-is, but I'd be happier to see us take a slightly larger step towards maintainability.
</blockquote></details>

I've made quite a few changes to use semantic color names where possible. Should be much better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2049)*

**Comment by JohnThomson** [comment]
One more comment suggested, then just merge.

---

Review status: 7 of 20 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/templates/common-mixins.less, line 15 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2049#-L22NcOOwIg-zzpl8jSV:-L26wRnkN8iKwPJ52-cE:b8ej6hm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/414fd70489bcd2af4c0e72520e71e691c24d952c/src/BloomBrowserUI/templates/common-mixins.less#L15)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I've made quite a few changes to use semantic color names where possible. Should be much better.
</blockquote></details>

Much improved

---

*[src/BloomBrowserUI/templates/common-mixins.less, line 10 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2049#-L26vz80B-iKUuvqu84U:-L26vz80B-iKUuvqu84V:b-v4amyp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a9c6a8b1d0afdf91f1a583376c4746d0fcff107c/src/BloomBrowserUI/templates/common-mixins.less#L10)):*
> ```Less
> @DisabledButtonColor: @bloom-gray;
> @ControlColor: #96668F;
> @DarkBackgroundColor: #404040;
> ```

Deserves at least a comment to indicate whether it's the dark background in the central panel or the one used in toolboxes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2049#-:-L26wcOe6paoDXrP8ogA:bfrouxd)*

**Comment by gmartin7** [comment]
Review status: 7 of 20 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/templates/common-mixins.less, line 10 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2049#-L26vz80B-iKUuvqu84U:-L270EKLUwSf19zbkP_1:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a9c6a8b1d0afdf91f1a583376c4746d0fcff107c/src/BloomBrowserUI/templates/common-mixins.less#L10)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Deserves at least a comment to indicate whether it's the dark background in the central panel or the one used in toolboxes.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2049)*

**Pull request merged**
