### PR TITLE
Make Javascript tests work with Chrome

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5366)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5366)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/package.json` line 15 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5366#-NAuMWau42nnMjFZtaYd:-NAuMWav-tnUFzjZQjPB:b-7tb3mw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8c6c1a7c9cdbb23d7467a16e519c4b7a809b76f4/src/BloomBrowserUI/package.json#L15)):*
> ```JSON
>     "scripts": {
>         "// COMMENTS: make the action a space rather than empty string so `yarn run` can list the scripts": " ",
>         "test": "karma start --browsers Chrome_allow_autoplay  --single-run",
> ```

I think we should consider having `test` run on both browsers until we fully move to wv2.
Then we could have a test:ff and test:chrome if devs don't want to sacrifice the time to run both.
___
*[`src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts` line 392 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5366#-NAuLQ00CuUjXqN63Kvn:-NAuLQ00CuUjXqN63Kvo:bb7phvt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8c6c1a7c9cdbb23d7467a16e519c4b7a809b76f4/src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts#L392)):*
> ```XML
>             // but you can still check if the event was cancelled.
>             const keyboardEvent = new KeyboardEvent("keydown", keyEventInit);
>             //DispatchEvent dispatches a synthetic event event to target and returns true if either event's
> ```

typo



_Code quote:_
```XML
event event
```
___
*[`src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts` line 394 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5366#-NAuLXGaAit-WbHbmkaY:-NAuLXGaAit-WbHbmkaZ:bb7phvt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8c6c1a7c9cdbb23d7467a16e519c4b7a809b76f4/src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts#L394)):*
> ```XML
>             //DispatchEvent dispatches a synthetic event event to target and returns true if either event's
>             // cancelable attribute value is false or its preventDefault() method was not invoked, and false otherwise.
>             // Cancelable is true. Therefore, it returns true if prevenDefault was not invoked.
> ```

typo



_Code quote:_
```XML
prevenDefault
```

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5366)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5366)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/package.json` line 15 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5366#-NAuMWau42nnMjFZtaYd:-NAue06T-1zvHcl3sIlU:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8c6c1a7c9cdbb23d7467a16e519c4b7a809b76f4/src/BloomBrowserUI/package.json#L15)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think we should consider having `test` run on both browsers until we fully move to wv2.
Then we could have a test:ff and test:chrome if devs don't want to sacrifice the time to run both.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts` line 392 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5366#-NAuLQ00CuUjXqN63Kvn:-NAudvvn4VQt6Riqpr6s:bb7f2mf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8c6c1a7c9cdbb23d7467a16e519c4b7a809b76f4/src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts#L392)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

typo
</blockquote></details>

done
___
*[`src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts` line 394 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5366#-NAuLXGaAit-WbHbmkaY:-NAudv7S9-wpncnA-zQ_:bb7f2mf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8c6c1a7c9cdbb23d7467a16e519c4b7a809b76f4/src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts#L394)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

typo
</blockquote></details>

done

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5366)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
