### PR TITLE
Convert align left/right to start/end instead (BL-11400)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5324)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5324)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts` line 1887 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5324#-N8ydZnD00YHFzRkmsLC:-N8ydZnD00YHFzRkmsLD:b-6m8i9f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1fc5a5a8c8154298785de96ebb7b40530b049feb/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L1887)):*
> ```XML
>         }
> 
>         const positionRightButton = document.getElementById("position-right");
> ```

Why use two different ways to determine if the button has a specific class (jquery vs not)?
If necessary to leave it as is, it is probably worth a comment.

Otherwise, LGTM

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5324)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts` line 1887 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5324#-N8ydZnD00YHFzRkmsLC:-N8z-FWrC_SJY6kVQ4J0:bwqmv2b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1fc5a5a8c8154298785de96ebb7b40530b049feb/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L1887)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Why use two different ways to determine if the button has a specific class (jquery vs not)?
If necessary to leave it as is, it is probably worth a comment.

Otherwise, LGTM
</blockquote></details>

Ah, that is because we have been wanting to move away JQuery and I got flak in the past for adding new jquery code even to existing jquery code...

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5324)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts` line 1887 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5324#-N8ydZnD00YHFzRkmsLC:-N8zEhmA4EiC5P2QDIPG:b-5g2m9n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1fc5a5a8c8154298785de96ebb7b40530b049feb/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L1887)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Ah, that is because we have been wanting to move away JQuery and I got flak in the past for adding new jquery code even to existing jquery code... 
</blockquote></details>

Ah. The diff didn't make it very obvious this was essentially existing code.
Do you mind making it consistent (not jquery) while we're looking at it?

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5324)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Pull request merged**
