### PR TITLE
Fix BulkUploader to call ExpensiveInitialization(true) (BL-10347)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This ensures that the proper support files are included in the uploaded
books.

I also renamed a method to reduce confusion moving forward.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4697)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4697)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/Book/Book.cs, line 747 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4697#-MicXQBx9PgfXSHvU9fk:-MicXQBx9PgfXSHvU9fl:b6lekov) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f71adeea2dfd4c39adec42ff3c27264976534d13/src/BloomExe/Book/Book.cs#L747)):*
> ```Smalltalk
> 			}
> 			//Console.WriteLine("DEBUG GetPreviewHtmlFileForWholeBook(): calling BringBookUpToDate() for new previewDOM");
> 			BringBookUpToDateInternal(previewDom, new NullProgress());
> ```

Tell me about this change, thx.
___
*[src/BloomExe/WebLibraryIntegration/BulkUploader.cs, line 281 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4697#-MicX5_12pUiXkP5SFN1:-MicX5_12pUiXkP5SFN2:b2kamdj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f71adeea2dfd4c39adec42ff3c27264976534d13/src/BloomExe/WebLibraryIntegration/BulkUploader.cs#L281)):*
> ```Smalltalk
> 				var server = context.BookServer;
> 				var bookInfo = new BookInfo(uploadParams.Folder, true);
> 				var book = server.GetBookFromBookInfo(bookInfo, forSelectedBook: true);
> ```

Please go ahead an rename the `forSelectedBook` now that we are using it in a different way.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4697)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/Book/Book.cs, line 747 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4697#-MicXQBx9PgfXSHvU9fk:-MicZrz8-aq6ECvC265M:b-fawn7e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f71adeea2dfd4c39adec42ff3c27264976534d13/src/BloomExe/Book/Book.cs#L747)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Tell me about this change, thx.
</blockquote></details>

I've been confused by having two methods with the same name ever since I started working in this file.  I decided to rename the private method along the lines that we've used elsewhere in the program.  Whether the names are optimal or not, at least it's obvious there are two different (albeit closely related) methods.
___
*[src/BloomExe/WebLibraryIntegration/BulkUploader.cs, line 281 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4697#-MicX5_12pUiXkP5SFN1:-MicfZN72EreuEi1fh9Z:beqxwgd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f71adeea2dfd4c39adec42ff3c27264976534d13/src/BloomExe/WebLibraryIntegration/BulkUploader.cs#L281)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Please go ahead an rename the `forSelectedBook` now that we are using it in a different way.
</blockquote></details>

OK, but the renaming logically spreads out to several files and classes.  I changed it to "fixBookCompletely" which seems to express the general use/meaning of the flag rather than any one caller's intention.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4697)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/WebLibraryIntegration/BulkUploader.cs, line 281 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4697#-MicX5_12pUiXkP5SFN1:-Micn9O28GKelgqZxCvZ:b-3eft4s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f71adeea2dfd4c39adec42ff3c27264976534d13/src/BloomExe/WebLibraryIntegration/BulkUploader.cs#L281)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

OK, but the renaming logically spreads out to several files and classes.  I changed it to "fixBookCompletely" which seems to express the general use/meaning of the flag rather than any one caller's intention.
</blockquote></details>

Hmm, I don't of this as fixing as if something was broken. I'll have to look tomorrow for a name to suggest.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4697)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/WebLibraryIntegration/BulkUploader.cs, line 281 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4697#-MicX5_12pUiXkP5SFN1:-MicqYRt03w4BlusaptS:b-y0hgh6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f71adeea2dfd4c39adec42ff3c27264976534d13/src/BloomExe/WebLibraryIntegration/BulkUploader.cs#L281)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Hmm, I don't of this as fixing as if something was broken. I'll have to look tomorrow for a name to suggest.
</blockquote></details>

OK.  I was struggling to come up with a good name.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4697)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/WebLibraryIntegration/BulkUploader.cs, line 281 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4697#-MicX5_12pUiXkP5SFN1:-MigF3lj2EsqSOuQdUuj:bz5sieo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f71adeea2dfd4c39adec42ff3c27264976534d13/src/BloomExe/WebLibraryIntegration/BulkUploader.cs#L281)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

OK.  I was struggling to come up with a good name.
</blockquote></details>

what about "fullyUpdateBookFiles"?

**Review by StephenMcConnel — COMMENTED** [review]
The code for removing images checks for image references in the data div and keeps all of those around.  This should handle the case you mentioned.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4697#-:-Mjffgl83PWHgVYp7UNf:b-mmfdae)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/Book/BookStorage.cs, line 1614 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4697#-Mj6BFLe47XtFIrMZ3Cx:-Mjfe7pQ2YEsofWZ_Yig:b-c6fow8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/cdfb74800ea4e940174e008b734a70ec8fe4bbf5/src/BloomExe/Book/BookStorage.cs#L1614)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

So what is in between? The comment above implies we don't need to call it at all to show a title and thumbnail...the param should be true if we're going to edit or upload...could you describe a bit more what less is done if it is false and what might safely use that?
</blockquote></details>

I've added to the parameter comment what happens if it's false.  I have no idea what can safely call it set to false if it wants "more than just show a title and thumbnail".
This method is so old that I don't know anything about its history.  I'm not sure it's even called with the parameter set to false any longer.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 10 files at r4, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4697)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Pull request merged**
