### PR TITLE
BL-1103 Prevent two squirrel updates happening at once

### PR DESCRIPTION
**Pull request by JohnThomson**

### CODE REVIEW

**Comment by hatton** [comment]
Looks fine. With each new bit of code around this in workspace view, I wonder if it can't be spun out to its own class?

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-master-debug/351/
Test PASSed.

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-master-debug/352/
Test PASSed.

**Comment by StephenMcConnel** [comment]
looks good to me as well.

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-master-debug/357/
Test PASSed.

**Comment by hatton** [comment]
Great, thanks for doing that refactoring John.

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-master-debug/361/
Test FAILed.

**Pull request merged**
