### PR TITLE
Update collection pane when deleting single remaining book (BL-13970)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6691)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6691)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx` line 92 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6691#-O8d3KsY4qyXu6cE5pJq:-O8d3KsY4qyXu6cE5pJr:ba84e6y) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3bf3e270d2b5bda68ac04256fd08b70a8ac01d9a/src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx#L92)):*
> ```XML
>             // We need to reset for an empty list, or we'll keep showing the last
>             // remaining book that was just deleted.  See BL-13970.
>             setBooks(unfilteredBooks);
> ```

We don't need to call `setReloadParameter("");` in this case (as above)?

**Review by andrew-polk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6691)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6691)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx` line 92 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6691#-O8d3KsY4qyXu6cE5pJq:-O8dF1rC3NCzSZNnVHhG:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/3bf3e270d2b5bda68ac04256fd08b70a8ac01d9a/src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx#L92)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We don't need to call `setReloadParameter("");` in this case (as above)?
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6691)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
