### PR TITLE
BL-3406 make synphony handle &nbsp; as white space

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1058)

### CODE REVIEW

**Comment by hatton** [comment]
LGTM. Looks like you are saving the new paragraph thing for a different PR?

<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary>
> #### BL\-3406 make synphony handle &amp;nbsp; as white space
> 
> 
> 
> 
> </details>


---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1058#-:-KHVvWP4VubdVM5_kFml:-1188281530)*

**Comment by JohnThomson** [comment]
I thought I had seen the new paragraph thing but after making this change I couldn't reproduce it. If it's still not fixed (which seems likely) would probably make sense to combine with this.

<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary>
> LGTM. Looks like you are saving the new paragraph thing for a different PR?</details>


---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1058#-:-KHVy-yI1XI83Lxnhe-r:193510268)*

**Comment by JohnThomson** [comment]
OK, got it. Will add.

<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary>
> I thought I had seen the new paragraph thing but after making this change I couldn't reproduce it. If it's still not fixed (which seems likely) would probably make sense to combine with this.</details>


---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1058#-:-KHVyZCF0wNIni22_FnB:508042453)*

**Comment by JohnThomson** [comment]
New commit handles paragraph case (Sorry, I can't find a way back to the comment to respond to it in Reviewable.)

**Comment by hatton** [comment]
With a function name like "checkLeaf()" (which we inherited) and no comment, I haven't a clue what this does. I'll have to trust you :-)

:+1:

**Pull request merged**
