### PR TITLE
[5.5] BL-12333 Second try at unauthorized content pt 2

### PR DESCRIPTION
**Pull request by gmartin7**
* bloomPUB publishing

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5952)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5952)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomExe/web/WebSocketProgress.cs` line 145 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5952#-NYUiwoR26SWwTLYvLA1:-NYUiwoR26SWwTLYvLA2:byhpubb) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2148542bbcbda69c6e74c36380fafc8e3cca3c09/src/BloomExe/web/WebSocketProgress.cs#L145)):*
> ```Smalltalk
> 					HaveProblemsBeenReported = true;
> 					HaveDisablingErrorsBeenReported = true;
> 					break;
> ```

I'm probably just missing it, but what does DisablingError add that Error doesn't already provide?
When would we want an error which doesn't disable the output?

So, I think there's only three scenarios:
1. An error so bad we must close: Fatal.
1. An error which should prevent the action from completing: Error.
1. An error/warning which should NOT prevent the action from completing: Warning.

I think I understand the need for this switch to distinguish between Error and Warning... otherwise we don't know if the action should continue. But shouldn't that be switched between Error/Warning?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5952)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/web/WebSocketProgress.cs` line 145 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5952#-NYUiwoR26SWwTLYvLA1:-NYUpCgV6QvznB_VCsCe:b-zelzuz) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2148542bbcbda69c6e74c36380fafc8e3cca3c09/src/BloomExe/web/WebSocketProgress.cs#L145)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm probably just missing it, but what does DisablingError add that Error doesn't already provide?
When would we want an error which doesn't disable the output?

So, I think there's only three scenarios:
1. An error so bad we must close: Fatal.
1. An error which should prevent the action from completing: Error.
1. An error/warning which should NOT prevent the action from completing: Warning.

I think I understand the need for this switch to distinguish between Error and Warning... otherwise we don't know if the action should continue. But shouldn't that be switched between Error/Warning?
</blockquote></details>

Yes, but. Also Warnings are yellow and Errors are red. And currently neither of them abort the preview enough that it can't be saved.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5952)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/web/WebSocketProgress.cs` line 145 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5952#-NYUiwoR26SWwTLYvLA1:-NYUpxyx4g2ao-cX4gHW:b-blqd4i) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2148542bbcbda69c6e74c36380fafc8e3cca3c09/src/BloomExe/web/WebSocketProgress.cs#L145)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Yes, but. Also Warnings are yellow and Errors are red. And currently neither of them abort the preview enough that it can't be saved.
</blockquote></details>

Illegal/Doubtful fonts are Errors, but Bloom replaces them with Andika and soldiers on.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5952)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomExe/web/WebSocketProgress.cs` line 145 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5952#-NYUiwoR26SWwTLYvLA1:-NYUshtG-sy84VUL6bBJ:b1ligps) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2148542bbcbda69c6e74c36380fafc8e3cca3c09/src/BloomExe/web/WebSocketProgress.cs#L145)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Illegal/Doubtful fonts are Errors, but Bloom replaces them with Andika and soldiers on.
</blockquote></details>

Are you saying that before and after your change, the only difference between Error and Warning is the color?

It is possible that JH intends to have 4 cases (two of which are distinct only by color) as opposed to the 3 I outlined above, but that seems unlikely.

Let me ask the question another way to make sure I'm understanding:
If we change all the ones which should stop the action to Error and all the ones which shouldn't to Warning -- and we leave in your distinction in this switch such that UpdatePreview can tell the difference between Warning and Error -- is the color change the only bad thing which happens? Or are we too ingrained with this system now?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5952)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/web/WebSocketProgress.cs` line 145 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5952#-NYUiwoR26SWwTLYvLA1:-NYUwse74VUDZustHcWd:b-70253c) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2148542bbcbda69c6e74c36380fafc8e3cca3c09/src/BloomExe/web/WebSocketProgress.cs#L145)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Are you saying that before and after your change, the only difference between Error and Warning is the color?

It is possible that JH intends to have 4 cases (two of which are distinct only by color) as opposed to the 3 I outlined above, but that seems unlikely.

Let me ask the question another way to make sure I'm understanding:
If we change all the ones which should stop the action to Error and all the ones which shouldn't to Warning -- and we leave in your distinction in this switch such that UpdatePreview can tell the difference between Warning and Error -- is the color change the only bad thing which happens? Or are we too ingrained with this system now?
</blockquote></details>

First question: I believe so.
Second question: This PR's case is the only one I know of that should stop the action, other than actual Exceptions that generate "Fatal" messages that close Bloom.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5952)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomExe/web/WebSocketProgress.cs` line 145 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5952#-NYUiwoR26SWwTLYvLA1:-NYVNGP-DTkBxvVx66-t:bxqbscw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2148542bbcbda69c6e74c36380fafc8e3cca3c09/src/BloomExe/web/WebSocketProgress.cs#L145)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

First question: I believe so.
Second question: This PR's case is the only one I know of that should stop the action, other than actual Exceptions that generate "Fatal" messages that close Bloom.
</blockquote></details>

Just a quick note that I'm continuing to look at this.
I don't think we can sort of change the definition of Error to mean we should stop. 
1. It is used all over in other contexts.
2. I'm becoming more convinced that the distinction of these `ProgressKind`s should only affect UI, not behavior.

So mostly I'm looking at how we do what we need to here without relying on ProgressKind at all.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5952)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomExe/web/WebSocketProgress.cs` line 145 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5952#-NYUiwoR26SWwTLYvLA1:-NYVOs3s2_TVOKBdyZQ1:b1xwjwp) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2148542bbcbda69c6e74c36380fafc8e3cca3c09/src/BloomExe/web/WebSocketProgress.cs#L145)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Just a quick note that I'm continuing to look at this.
I don't think we can sort of change the definition of Error to mean we should stop. 
1. It is used all over in other contexts.
2. I'm becoming more convinced that the distinction of these `ProgressKind`s should only affect UI, not behavior.

So mostly I'm looking at how we do what we need to here without relying on ProgressKind at all.
</blockquote></details>

Ok, I added another comment in context on how I think we can do this.
___
*[`src/BloomExe/web/controllers/PublishApi.cs` line 374 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5952#-NYVOQ5_1O3DM6Ui-eb3:-NYVOQ5_1O3DM6Ui-eb4:bavei2u) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2148542bbcbda69c6e74c36380fafc8e3cca3c09/src/BloomExe/web/controllers/PublishApi.cs#L374)):*
> ```Smalltalk
> 			_lastSettings.RemoveInteractivePages = forVideo;
> 			PreviewUrl = MakeBloomPubForPreview(request.CurrentBook, _bookServer, _progress, _thumbnailBackgroundColor, _lastSettings);
> 			if (_progress.HaveDisablingErrorsBeenReported)
> ```

Instead of checking the state of what has been sent to progress here, what if we just check if PreviewUrl is non-null?

So,
```
			PreviewUrl = MakeBloomPubForPreview(request.CurrentBook, _bookServer, _progress, _thumbnailBackgroundColor, _lastSettings);
			if (PreviewUrl == null)
			{
				// Tried sending empty string, but SendString() ignores empty messages. "stopPreview" gets interpreted as a command to stop
				// the preview spinner.
				_webSocketServer.SendString(kWebSocketContext, kWebsocketEventId_Preview, "stopPreview");
				return false;
			}
			_webSocketServer.SendString(kWebSocketContext, kWebsocketEventId_Preview, PreviewUrl);
```

Then we can get rid of the extra complexity added to ProgressKind.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5952)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/web/controllers/PublishApi.cs` line 374 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5952#-NYVOQ5_1O3DM6Ui-eb3:-NYZ6Mci9jjUHgyUbGlE:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2148542bbcbda69c6e74c36380fafc8e3cca3c09/src/BloomExe/web/controllers/PublishApi.cs#L374)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Instead of checking the state of what has been sent to progress here, what if we just check if PreviewUrl is non-null?

So,
```
			PreviewUrl = MakeBloomPubForPreview(request.CurrentBook, _bookServer, _progress, _thumbnailBackgroundColor, _lastSettings);
			if (PreviewUrl == null)
			{
				// Tried sending empty string, but SendString() ignores empty messages. "stopPreview" gets interpreted as a command to stop
				// the preview spinner.
				_webSocketServer.SendString(kWebSocketContext, kWebsocketEventId_Preview, "stopPreview");
				return false;
			}
			_webSocketServer.SendString(kWebSocketContext, kWebsocketEventId_Preview, PreviewUrl);
```

Then we can get rid of the extra complexity added to ProgressKind.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5952)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
