### PR TITLE
More Full Bleed work (mainly BL-8872)

### PR DESCRIPTION
**Pull request by JohnThomson**
This has three commits, which may be easier to review separately

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3898)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 5 of 5 files at r2, 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3898)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[DistFiles/localization/en/Bloom.xlf, line 3571 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/3898#-MFbksGu0HuDK03qAazJ:-MFbksGu0HuDK03qAazK:b-zf5mwv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/cc91cde3a84ea3d954db5e5f7bab4efbdc228d57/DistFiles/localization/en/Bloom.xlf#L3571)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> <trans-unit id="PublishTab.OptionsMenu.SizeLayout">
>         <source xml:lang="en">Size/Orientation</source>
>         <note>ID: PublishTab.OptionsMenu.SizeLayout</note>
>         <note>Header for a region of the menu which lists various standard page sizes and orientations</note>
>       </trans-unit>
> ```
</details>

Removal of unused IDs/strings is tricky.
Our normal process will cause these translations to revert to English for a version or two (which is bad). 
So I think it has become our practice to mark these as obsolete with a note (including the Bloom version number).

Same for PublishTab.PdfMaker.PdfWithRGB below
___
*[DistFiles/localization/en/Bloom.xlf, line 3649 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/3898#-MFbmUYmDDCT8R7GcHki:-MFbmUYmDDCT8R7GcHkj:b-1fainl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/16133fe7a4119b1d09d6a8bd273ac3f10ee4971d/DistFiles/localization/en/Bloom.xlf#L3649)):*
> ```
> <note>obsolete</note>
> ```
I think this isn't supposed to be here?
___
*[src/BloomExe/Publish/PDF/MakePdfUsingGeckofxHtmlToPdfProgram.cs, line 217 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3898#-MFbjGKu8MCLCJDlBDLT:-MFbjGKv8Zy9A-a7tfw_:b-sa01qs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c033c8f4e98e3fb2e2d91104c17e5beca73e6c05/src/BloomExe/Publish/PDF/MakePdfUsingGeckofxHtmlToPdfProgram.cs#L217)):*
> ```Smalltalk
> 				bldr.Append($" -h {height} -w {width}");
> 			}
> 			else if (specs.PaperSizeName == "Comic")
> ```

I think with JH's change which just went in maybe this needs to be USComic?
So argues for a possible constant. Though JH tend to disagree on the use of constants in such cases.
___
*[src/BloomExe/Publish/PDF/MakePdfUsingGeckofxHtmlToPdfProgram.cs, line 245 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/3898#-MFbnGAc0JWZSPCY-wT5:-MFbnGAc0JWZSPCY-wT6:bb6e7zq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/16133fe7a4119b1d09d6a8bd273ac3f10ee4971d/src/BloomExe/Publish/PDF/MakePdfUsingGeckofxHtmlToPdfProgram.cs#L245)):*
> ```
> other than A5
> ```
I think this needs an update now.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3898)* status: 0 of 10 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[DistFiles/localization/en/Bloom.xlf, line 3571 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/3898#-MFbksGu0HuDK03qAazJ:-MFlktWnEfCf0VTv-Hxi:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/cc91cde3a84ea3d954db5e5f7bab4efbdc228d57/DistFiles/localization/en/Bloom.xlf#L3571)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> <trans-unit id="PublishTab.OptionsMenu.SizeLayout">
>         <source xml:lang="en">Size/Orientation</source>
>         <note>ID: PublishTab.OptionsMenu.SizeLayout</note>
>         <note>Header for a region of the menu which lists various standard page sizes and orientations</note>
>       </trans-unit>
> ```
Removal of unused IDs/strings is tricky.
Our normal process will cause these translations to revert to English for a version or two (which is bad). 
So I think it has become our practice to mark these as obsolete with a note (including the Bloom version number).

Same for PublishTab.PdfMaker.PdfWithRGB below
</blockquote></details>

Done.
___
*[DistFiles/localization/en/Bloom.xlf, line 3649 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/3898#-MFbmUYmDDCT8R7GcHki:-MFll2jgBkq-4taelwG0:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/16133fe7a4119b1d09d6a8bd273ac3f10ee4971d/DistFiles/localization/en/Bloom.xlf#L3649)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> <note>obsolete</note>
> ```
I think this isn't supposed to be here?
</blockquote></details>

Done.
___
*[src/BloomExe/Publish/PDF/MakePdfUsingGeckofxHtmlToPdfProgram.cs, line 217 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3898#-MFbjGKu8MCLCJDlBDLT:-MFllqWF2ZgtZCVz0CxA:b90zkog) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c033c8f4e98e3fb2e2d91104c17e5beca73e6c05/src/BloomExe/Publish/PDF/MakePdfUsingGeckofxHtmlToPdfProgram.cs#L217)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think with JH's change which just went in maybe this needs to be USComic?
So argues for a possible constant. Though JH tend to disagree on the use of constants in such cases.
</blockquote></details>

I changed the actual name. Seems like we have paper size names all over, and they occur in C#, JavaScript, LESS, and probably PUG too, which makes using constants of limited use. So I'm doubtful introducing a constant for just this one is worth doing.
___
*[src/BloomExe/Publish/PDF/MakePdfUsingGeckofxHtmlToPdfProgram.cs, line 245 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/3898#-MFbnGAc0JWZSPCY-wT5:-MFpS4B5-431a51xseDr:bl6aos6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/16133fe7a4119b1d09d6a8bd273ac3f10ee4971d/src/BloomExe/Publish/PDF/MakePdfUsingGeckofxHtmlToPdfProgram.cs#L245)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> other than A5
> ```
I think this needs an update now.
</blockquote></details>

Done. And many other things need changing from Comic to USComic. I rebased the PR.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r4, 4 of 5 files at r5, 9 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3898)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[DistFiles/localization/en/Bloom.xlf, line 3693 at r6](https://reviewable.io/reviews/bloombooks/bloomdesktop/3898#-MFpnum129Xmi3qVKL9E:-MFpnum129Xmi3qVKL9F:b-2u1417) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08b47133cc09802a70385fc7836e89032e1d4039/DistFiles/localization/en/Bloom.xlf#L3693)):*
> ```
> <note>obsolete as of Bloom 4.9</note>
> ```
I think you meant to put this on PublishTab.PdfMaker.PdfFile above.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3898)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[DistFiles/localization/en/Bloom.xlf, line 3693 at r6](https://reviewable.io/reviews/bloombooks/bloomdesktop/3898#-MFpnum129Xmi3qVKL9E:-MFqeLlS6SeFQMna610y:bvpfxyc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08b47133cc09802a70385fc7836e89032e1d4039/DistFiles/localization/en/Bloom.xlf#L3693)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> <note>obsolete as of Bloom 4.9</note>
> ```
I think you meant to put this on PublishTab.PdfMaker.PdfFile above.
</blockquote></details>

No. We used to have two file "types", PDF with RGB color and CMYK. Now just one, the new simple "PDF file". The CMYK string is still used (slightly modified) as a menu option, but it's just checked or unchecked, so we don't need text for the opposite any more.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3898)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[DistFiles/localization/en/Bloom.xlf, line 3693 at r6](https://reviewable.io/reviews/bloombooks/bloomdesktop/3898#-MFpnum129Xmi3qVKL9E:-MFqkJVS-Ep5SVOw6qRV:bsw21nz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08b47133cc09802a70385fc7836e89032e1d4039/DistFiles/localization/en/Bloom.xlf#L3693)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

No. We used to have two file "types", PDF with RGB color and CMYK. Now just one, the new simple "PDF file". The CMYK string is still used (slightly modified) as a menu option, but it's just checked or unchecked, so we don't need text for the opposite any more.
</blockquote></details>

Yes, sorry. The diff in Reviewable due to realphabetizing threw me off.

**Pull request merged**
