### PR TITLE
Remove blank pages from ePUB books (BL-4288)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1519)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 213 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1519#-KdkYGlJMQ08H6K3sDAG:-KdkYGlJMQ08H6K3sDAH:b-71dmqy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b03a025df593af920b56ef729c578a8f7dadf88a/src/BloomExe/Publish/EpubMaker.cs#L213)):*
> ```Smalltalk
> 			}
> 			// The copyright is not included in a <p> element but is displayed in the ePUB book.
> 			foreach (XmlElement div in pageElement.GetElementsByTagName("div"))
> ```

Is it safe to assume this is and always will be the only type of div containing text without a 'p'? 
Could we use xpath to find any text nodes? Or does that not work because some are hidden?
In that case, we would probably have to render the page in the browser and see if there is any text.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1519)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 200 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1519#-KdkbjwD7Umq7dHa8ouF:-KdkbjwD7Umq7dHa8ouG:b-3rvo42) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b03a025df593af920b56ef729c578a8f7dadf88a/src/BloomExe/Publish/EpubMaker.cs#L200)):*
> ```Smalltalk
> 		private bool IsBlankPage(XmlElement pageElement)
> 		{
> 			// Any text in a <p> element will be displayed.
> ```

Not necessarily. Anything that is not in a div marked with the language we are publishing will be dropped later. It's not even good enough to figure out whether a div is display:none, because it may be currently set up as a bilingual book, which means the national language text will be displayed on screen, but not in the epub.

Until recently, on content pages, you could just look for divs in the publish language, but xmatter has more complex rules for what to include, and recently we added the ability for content pages to specify blocks in a particular language. I don't know whether we've even thought about how such blocks should behave in an epub.

I suspect you will only get a reliable answer by generating the output page and THEN asking simply whether it has any text or images. We already try pretty hard not to put any hidden stuff on output pages.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 225 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1519#-Kdkd9IHplXw8p5p9FGX:-Kdkd9IIpLdaxRRyalHn:b-7ufyjf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b03a025df593af920b56ef729c578a8f7dadf88a/src/BloomExe/Publish/EpubMaker.cs#L225)):*
> ```Smalltalk
> 		/// Check that the image file exists, and is not the place holder image.
> 		/// </summary>
> 		private bool RealImageFileExists(XmlElement img)
> ```

Could probably be simplified if you check the output page, since I don't think we output pointers to images that don't exist. (Check that!)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1519)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 200 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1519#-KdkbjwD7Umq7dHa8ouF:-KdlW7lltPD5O8b5waJE:b-kihl8o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b03a025df593af920b56ef729c578a8f7dadf88a/src/BloomExe/Publish/EpubMaker.cs#L200)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Not necessarily. Anything that is not in a div marked with the language we are publishing will be dropped later. It's not even good enough to figure out whether a div is display:none, because it may be currently set up as a bilingual book, which means the national language text will be displayed on screen, but not in the epub.

Until recently, on content pages, you could just look for divs in the publish language, but xmatter has more complex rules for what to include, and recently we added the ability for content pages to specify blocks in a particular language. I don't know whether we've even thought about how such blocks should behave in an epub.

I suspect you will only get a reliable answer by generating the output page and THEN asking simply whether it has any text or images. We already try pretty hard not to put any hidden stuff on output pages.
</blockquote></details>

I moved to check to follow all the methods that remove data from the DOM.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 213 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1519#-KdkYGlJMQ08H6K3sDAG:-KdlVdFWdnaJEt5CI0wn:b-b42va9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b03a025df593af920b56ef729c578a8f7dadf88a/src/BloomExe/Publish/EpubMaker.cs#L213)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is it safe to assume this is and always will be the only type of div containing text without a 'p'? 
Could we use xpath to find any text nodes? Or does that not work because some are hidden?
In that case, we would probably have to render the page in the browser and see if there is any text.
</blockquote></details>

I've moved the check to after unwanted material has been removed from the DOM, and simplified it considerably.  The new code might conceivably let an occasional blank page by, but won't filter out any pages that do have content.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 225 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1519#-Kdkd9IHplXw8p5p9FGX:-KdlW0YrMUhdGgos_esg:b-jmolnu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b03a025df593af920b56ef729c578a8f7dadf88a/src/BloomExe/Publish/EpubMaker.cs#L225)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Could probably be simplified if you check the output page, since I don't think we output pointers to images that don't exist. (Check that!)
</blockquote></details>

I didn't really check this.  This code is generally following (but not quite identical) to that used in the CopyImages() method which removes img elements with invalid src values, but which is called after this method.  And the uses are different enough I didn't want to try to factor out a common method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1519)*

**Comment by andrew-polk** [comment]
Minor comment comment.
Otherwise, :lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 493 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1519#-KdzwXFpVNbI3JxW8pgX:-KdzwXFpVNbI3JxW8pgY:b44w5e1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dba407a3e96d1b6859fc2541db6a3f1245c0144e/src/BloomExe/Publish/EpubMaker.cs#L493)):*
> RemoveBloomUiElements()

listed twice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1519#-:-KdzxVqDuORpC2tkgzel:b-7zkca2)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 493 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1519#-KdzwXFpVNbI3JxW8pgX:-Ke-PQskpZHH974xwF6Y:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dba407a3e96d1b6859fc2541db6a3f1245c0144e/src/BloomExe/Publish/EpubMaker.cs#L493)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> RemoveBloomUiElements()

listed twice
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1519)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1519)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 128 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1519#-Ke-QvHbf2PabSFOr8Xo:-Ke-QvHbf2PabSFOr8Xp:bu4p80g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/241ed9515fe2373c6c0a8ad9df39f701984807aa/src/BloomExe/Publish/EpubMaker.cs#L128)):*
> ```Smalltalk
> 			foreach(XmlElement pageElement in Book.GetPageElements())
> 			{
> 				++pageIndex;
> ```

The code managing pageIndex and firstContentPageIndex feels as though it's getting complex, fragile, and distributed. As far as I can tell, we're only using pageIndex within the MakePageFile routine, and only to generate a page number. If we made it a member variable, that method could just increment it each time it actually makes a page file.
Then, the only thing we use firstContentPageIndex for is to detect when we get to the first content page and save its file name in _firstContentPageItem (I think for use in TOC). If we changed the if to look at the dom and record _firstContentPageItem the first time it sees a (non-empty) page that doesn't have bloom-frontMatter, we could dispense with firstContentPageIndex altogether. It would be one more place that knows about bloom-frontMatter, but much less fragile. (There may even already be a method we can pass a Dom or element and ask whether it's an xmatter page.)
Not insisting on either of these, I think what you have will work, but do you think this would be a worthwhile simplification?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1519)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 128 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1519#-Ke-QvHbf2PabSFOr8Xo:-Ke-pMt9vlRTrXQxMhy7:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/241ed9515fe2373c6c0a8ad9df39f701984807aa/src/BloomExe/Publish/EpubMaker.cs#L128)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

The code managing pageIndex and firstContentPageIndex feels as though it's getting complex, fragile, and distributed. As far as I can tell, we're only using pageIndex within the MakePageFile routine, and only to generate a page number. If we made it a member variable, that method could just increment it each time it actually makes a page file.
Then, the only thing we use firstContentPageIndex for is to detect when we get to the first content page and save its file name in _firstContentPageItem (I think for use in TOC). If we changed the if to look at the dom and record _firstContentPageItem the first time it sees a (non-empty) page that doesn't have bloom-frontMatter, we could dispense with firstContentPageIndex altogether. It would be one more place that knows about bloom-frontMatter, but much less fragile. (There may even already be a method we can pass a Dom or element and ask whether it's an xmatter page.)
Not insisting on either of these, I think what you have will work, but do you think this would be a worthwhile simplification?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1519)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1519#-:-Ke-wMUR-18c6RssiCE-:bnfp4nl)*

**Pull request merged**
