### PR TITLE
Position and size overlays in pixels like their tails (BL-11667)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5650)

### CODE REVIEW

**Review by andrew-polk — APPROVED** [review]
LGTM but I'm going to ask for another pair of eyes.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5650#-:-NOojR9l3toybA5P31Z_:bc0x0g6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by gmartin7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5650)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 2501 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5650#-NOoq_jQ6dyRDJBk-bIL:-NOoq_jQ6dyRDJBk-bIM:b-4axs54) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8e4ae4c2179ceac96477b9bce4bbba82847b0cc2/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2501)):*
> ```XML
>         wrapperBox.css("top", yOffset); // assumes numbers are in pixels
> 
>         BubbleManager.setTextboxPosition(wrapperBox, xOffset, yOffset); // translate px to %
> ```

I believe the comment is obsolete?
___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 3192 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5650#-NOoqF9x2w9R_zDUpsWV:-NOoqF9yD8u6bmSm9A4I:b-fptrm9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8e4ae4c2179ceac96477b9bce4bbba82847b0cc2/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L3192)):*
> ```XML
>     // (Not sure if this ever changes anything, except whem migrating. Earlier versions of Bloom
>     // stored the bubble position and size as a percentage of the image container size.
>     // The reasons for that are lost in history. The reasons to prefer an absolute position and
> ```

I'm pretty sure the original reason for setting as a percentage was that we thought it would maintain what the user intended better on scaling/resizing. If absolute works better, I'm good with that.
___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 3206 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5650#-NOoqq6ICQVcX_iXrxBR:-NOoqq6ICQVcX_iXrxBS:bs72ihz) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8e4ae4c2179ceac96477b9bce4bbba82847b0cc2/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L3206)):*
> ```XML
>             .css("left", unscaledRelativeLeft + "px")
>             .css("top", unscaledRelativeTop + "px")
>             // FYI: The wrapperBox width/height is rounded to the nearest whole pixel. Ideally we might like its more precise value...
> ```

`wrapperBox` doesn't exist anymore ;)

**Review by gmartin7 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5650)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

**Review by gmartin7 — COMMENTED** [review]
Just a couple of comment updates needed, I think.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5650#-:-NOpEhskD5OOfpoTT8pH:b-pvljti)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

**Review by jsubloom — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5650)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 2170 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5650#-NOpJyRO3m-CI8l73XHA:-NOpJyRO3m-CI8l73XHB:bvg24v7) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8e4ae4c2179ceac96477b9bce4bbba82847b0cc2/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2170)):*
> ```XML
>     private adjustRelativePointToImageContainer(
>         imageContainer: Element,
>         x: number, // unscaled
> ```

I think it should take in a Point, see my comments in Zulip

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5650)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @andrew-polk, @gmartin7, and @jsubloom)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 2170 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5650#-NOpJyRO3m-CI8l73XHA:-NOpRXx59h-s52NvjPIw:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8e4ae4c2179ceac96477b9bce4bbba82847b0cc2/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2170)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

I think it should take in a Point, see my comments in Zulip
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 2501 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5650#-NOoq_jQ6dyRDJBk-bIL:-NOpRcHFCBk4eWCw3N3Q:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8e4ae4c2179ceac96477b9bce4bbba82847b0cc2/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2501)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I believe the comment is obsolete?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 3206 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5650#-NOoqq6ICQVcX_iXrxBR:-NOpSM47EupQQn3UNxI7:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8e4ae4c2179ceac96477b9bce4bbba82847b0cc2/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L3206)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

`wrapperBox` doesn't exist anymore ;)
</blockquote></details>

Done.

**Review by gmartin7 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5650)* status: all files reviewed, 1 unresolved discussion (waiting on @jsubloom)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> Dismissed @jsubloom from a discussion.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5650)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
