### PR TITLE
Implement F2 rename for new Collections tab

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4967)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4967)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/collectionsTab/BookButton.tsx, line 98 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4967#-MveuOK49XUCFwdew5B6:-MveuOK49XUCFwdew5B7:bvldakz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/500011e47a413c945a1b04c1c267f518a6bec4d4/src/BloomBrowserUI/collectionsTab/BookButton.tsx#L98)):*
> ```XML
>             props.manager.setRenameCallback(() => setRenaming(true));
>             // Seems it would be good to clean up like this, but if we do,
>             // F2 dosn't work after clicking a second button. Hypothesis: somehow the button
> ```

doesn't
(if making changes)



_Code quote:_
```XML
dosn't
```
___
*[src/BloomBrowserUI/collectionsTab/BookButton.tsx, line 101 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4967#-MveuTdd4KtpnOXaIkAm:-MveuTdd4KtpnOXaIkAn:b-vejlvj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/500011e47a413c945a1b04c1c267f518a6bec4d4/src/BloomBrowserUI/collectionsTab/BookButton.tsx#L101)):*
> ```XML
>             // losing selected status cleanup happens after the button gaining it sets itself up.
>             // Anyway, it works better without this, and it doesn't seem to cause any problem
>             // when pressing F2 after deleting a book.
> ```

I guess that's the only relevant case of going from a book selected to having no book selected?
I can't think of any other.



_Code quote:_
```XML
when pressing F2 after deleting a book
```
___
*[src/BloomBrowserUI/collectionsTab/BookButton.tsx, line 104 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4967#-MveuGxNAPyOMJXUf9DX:-MveuGxNAPyOMJXUf9DY:b-phc6vf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/500011e47a413c945a1b04c1c267f518a6bec4d4/src/BloomBrowserUI/collectionsTab/BookButton.tsx#L104)):*
> ```XML
>             //return () => props.manager.setRenameCallback(undefined);
>         }
>     }, [selected]);
> ```

Does this properly handle the case of a book we aren't allowed to change? If it does, I don't see why.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4967)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4967)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/collectionsTab/BookButton.tsx, line 98 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4967#-MveuOK49XUCFwdew5B6:-MwWwGQn-G7CSEAy98Fr:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/500011e47a413c945a1b04c1c267f518a6bec4d4/src/BloomBrowserUI/collectionsTab/BookButton.tsx#L98)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

doesn't
(if making changes)
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/collectionsTab/BookButton.tsx, line 101 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4967#-MveuTdd4KtpnOXaIkAm:-MwWwP5Z-EcAxJgZYEGO:b-g3z7c7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/500011e47a413c945a1b04c1c267f518a6bec4d4/src/BloomBrowserUI/collectionsTab/BookButton.tsx#L101)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I guess that's the only relevant case of going from a book selected to having no book selected?
I can't think of any other.
</blockquote></details>

That was the only test case I could think of, except switching collections when we reload everything.
___
*[src/BloomBrowserUI/collectionsTab/BookButton.tsx, line 104 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4967#-MveuGxNAPyOMJXUf9DX:-MwXYTcm5jPRQAoY9q2r:bb28h82) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/500011e47a413c945a1b04c1c267f518a6bec4d4/src/BloomBrowserUI/collectionsTab/BookButton.tsx#L104)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Does this properly handle the case of a book we aren't allowed to change? If it does, I don't see why.
</blockquote></details>

No. Fixed.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4967)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
