### PR TITLE
BL-3960 Add Page Number style selector

### PR DESCRIPTION
**Pull request by gmartin7**
* in Settings dialog BookMaking tab
* the combo label and the combo contents are
   localizable

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1323)

### CODE REVIEW

**Comment by hatton** [comment]
UI Looks good.

**Comment by gmartin7** [comment]
Comments about better ways to make sure the tests clean up after themselves are welcome.

**Comment by andrew-polk** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[DistFiles/localization/Bloom.en.tmx, line 395 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1323#-KX6Kst5OwCBAOOuBI-z:-KX6Kst5OwCBAOOuBI0-:b-hp0o0g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c8e98456b033c29678bc8a2b24f49e5d3fb37ff9/DistFiles/localization/Bloom.en.tmx#L395)):*
> ```
>     <tu tuid="CollectionSettingsDialog.BookMakingTab.PageNumberingStyle.arabic-indic">
>       <tuv xml:lang="en">
>         <seg>arabic-indic</seg>
> ```

Shouldn't all these should be capitalized?

---

*[src/BloomTests/Collection/CollectionSettingsTests.cs, line 19 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1323#-KX6LUuUX-mftSXWbe6c:-KX6LUuUX-mftSXWbe6d:b1ogccf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c8e98456b033c29678bc8a2b24f49e5d3fb37ff9/src/BloomTests/Collection/CollectionSettingsTests.cs#L19)):*
> ```Smalltalk
> 		{
> 			SIL.Reporting.ErrorReport.IsOkToInteractWithUser = false;
> 			_folder = new TemporaryFolder("CollectionSettingsTests");
> ```

I think we need a TearDown method which disposes of _folder.

You can probably make this slightly more efficient by making them FixtureSetUp and FixtureTearDown

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1323)*

**Comment by gmartin7** [comment]
Review status: 5 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[DistFiles/localization/Bloom.en.tmx, line 395 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1323#-KX6Kst5OwCBAOOuBI-z:-KX6dWCBWGSuXfk6K98A:bxraysd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c8e98456b033c29678bc8a2b24f49e5d3fb37ff9/DistFiles/localization/Bloom.en.tmx#L395)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Shouldn't all these should be capitalized?
</details>
Ah. You're probably right. Other languages have different rules for whether language names should be capitalized or not, but for English, yes, they should be.a

---

*[src/BloomTests/Collection/CollectionSettingsTests.cs, line 19 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1323#-KX6LUuUX-mftSXWbe6c:-KX79T2jkwBnjiFxykpm:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c8e98456b033c29678bc8a2b24f49e5d3fb37ff9/src/BloomTests/Collection/CollectionSettingsTests.cs#L19)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> I think we need a TearDown method which disposes of _folder.
> 
> You can probably make this slightly more efficient by making them FixtureSetUp and FixtureTearDown
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1323)*

**Comment by andrew-polk** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1323)*

**Pull request merged**
