### PR TITLE
Fix legacy bugs, tweak MXB/Uzbekistan projects for default (BL-12913)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
The Uzbekistan xmatter was already largely fixed for forcing default.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6260)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
What will happen to books using these xmatters if they use legacy theme, either because the user chooses it for some reason, or because some customCss makes it the default, or because (BL13015) they are being re-harvested by 5.7 without having been opened, migrated, and re-uploaded after human checking by 5.7? 
(If this looks like a serious problem, we should talk it over with JohnH. Maybe we need to research whether any of these xmatters are used with conflicting customCss. Maybe they should be an exception to "harvester does not migrate". Maybe legacy is definitely forbidden for these xmatters. Maybe we don't allow them to be re-harvested. Maybe they are no longer in use, or the users can just be warned not to use legacy. Or, maybe we need to keep the old rules around, but add an extra limitations based on a class at the bloom-page level saying we are in legcy.)

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6260#-:-NpL-rTAENLpLTrL6RFP:b-dno12t)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/content/templates/xMatter/project-specific/ABC-Reader-XMatter/ABC-Reader-XMatter.less` line 350 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6260#-NpKyZDN8o1pxzkQ3yUj:-NpKyZDN8o1pxzkQ3yUk:b9e4j4h) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/70a098ae8744a821c2ce4e11775305bd985b58e5/src/content/templates/xMatter/project-specific/ABC-Reader-XMatter/ABC-Reader-XMatter.less#L350)):*
> ```Less
>         // left: 0.5in !important;
>         // width: (@halfLetterPageWidth - 1in) !important;
>         // height: (@halfLetterPageHeight - 0.9in) !important;
> ```

Let's not keep these comments. In the unlikely event that we need them again, we have Git.
___
*[`src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less` line 205 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6260#-NpL-Tlv1n0rpTavespR:-NpL-Tlv1n0rpTavespS:b7ax958) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c01a79af01a18c16ae433877b0b827c7f1672431/src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less#L205)):*
> ```Less
>         }
>     }
> }
> ```

It's not clear to me why we no longer need this (assuming we ever did)

**Review by StephenMcConnel — COMMENTED** [review]
We do have conflicting goals that require more thought and work.  Perhaps this PR should be split into two pieces, along the lines of the two commits.  (One for real bugfix and one for the updated less files and pending associated other work?)

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6260#-:-NpLAhu90V9_lsBOdHUd:b9ykjru)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/content/templates/xMatter/project-specific/ABC-Reader-XMatter/ABC-Reader-XMatter.less` line 350 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6260#-NpKyZDN8o1pxzkQ3yUj:-NpL7_5H8_TC8Euj0PA6:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/70a098ae8744a821c2ce4e11775305bd985b58e5/src/content/templates/xMatter/project-specific/ABC-Reader-XMatter/ABC-Reader-XMatter.less#L350)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Let's not keep these comments. In the unlikely event that we need them again, we have Git.
</blockquote></details>

Done.
___
*[`src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less` line 205 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6260#-NpL-Tlv1n0rpTavespR:-NpL86qACsNEv7Vh1Wck:b-p04q62) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c01a79af01a18c16ae433877b0b827c7f1672431/src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less#L205)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's not clear to me why we no longer need this (assuming we ever did)
</blockquote></details>

I don't understand your comment.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6260)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less` line 205 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6260#-NpL-Tlv1n0rpTavespR:-NpLL7qIAvgaawWwngYy:b-hm8qkf) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c01a79af01a18c16ae433877b0b827c7f1672431/src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less#L205)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I don't understand your comment.
</blockquote></details>

A bunch of lines were deleted, but I could not find what replaced them
___
*[`src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less` line 142 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6260#-NpLLdIA0PMHhHmIT1fP:-NpLLdIA0PMHhHmIT1fQ:b-uingo1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/1fc90fd54f4dc004c434c1fe29d9d7c6e627f37f/src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less#L142)):*
> ```Less
>     &.titlePage {
>         --cover-margin-top: 1in;
>         --page-margin-top: 1in;
> ```

I thought John wanted the MXB half-letter page sizes to become our default (by modifying the variable definitions in appearance-theme-default.css)?
Making rules more specific than the appearance ones will prevent us from ever having a setting for this in book settings dialog.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6260)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less` line 205 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6260#-NpL-Tlv1n0rpTavespR:-NpPxoB8CoYCA39njMGo:bu4wzfh) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c01a79af01a18c16ae433877b0b827c7f1672431/src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less#L205)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

A bunch of lines were deleted, but I could not find what replaced them
</blockquote></details>

ah, there were a coupe of identical rules, one selected by 
body[bookcreationtype="original"] and one selected by body[bookcreationtype="translation"].
The bookcreationtype attribute doesn't seem to exist anywhere, so I simplified
the selector to omit it, and removed one of the two identical rules.  Apparently reviewable doesn't deal well with this kind of change for some reason.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6260)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/content/appearanceThemes/appearance-theme-default.css` line 181 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6260#-NpVPavhDCKdNcmei3UD:-NpVPavhDCKdNcmei3UE:b-3dzr9b) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c5405e66ee33528469acc4ddda0c13c7f55f825f/src/content/appearanceThemes/appearance-theme-default.css#L181)):*
> ```CSS
>     --page-margin-left: 15mm;
>     --page-margin-right: 15mm;
>     --page-gutter: 10mm;    /* same as  @ExtraSpaceForBinding in old bookLayout/common-mixins.less */
> ```

I think we should make the cover top and bottom margins match the internal pages for a default.
___
*[`src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less` line 142 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6260#-NpLLdIA0PMHhHmIT1fP:-NpVPm6z3tqV_3jVl_ZQ:bypzv1z) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/1fc90fd54f4dc004c434c1fe29d9d7c6e627f37f/src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less#L142)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I thought John wanted the MXB half-letter page sizes to become our default (by modifying the variable definitions in appearance-theme-default.css)?
Making rules more specific than the appearance ones will prevent us from ever having a setting for this in book settings dialog.
</blockquote></details>

I think we should remove the ones that duplicate (but with more specificity) the theme default page sizes. Otherwise, the book settings dialog will unexpectedly fail to have any effect.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6260)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less` line 142 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6260#-NpLLdIA0PMHhHmIT1fP:-NpVQV7U3UlDZrFni0ld:b1xyw2e) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/1fc90fd54f4dc004c434c1fe29d9d7c6e627f37f/src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less#L142)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think we should remove the ones that duplicate (but with more specificity) the theme default page sizes. Otherwise, the book settings dialog will unexpectedly fail to have any effect.
</blockquote></details>

That is, it will fail to have any effect if we one day give it controls for these variables :-). And of course the problem will still occur for the xmatter pages. But we can cross that bridge when we come to it.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6260)* status: 3 of 9 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/content/appearanceThemes/appearance-theme-default.css` line 181 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6260#-NpVPavhDCKdNcmei3UD:-NpVUbWl6Xc01DLthKhe:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c5405e66ee33528469acc4ddda0c13c7f55f825f/src/content/appearanceThemes/appearance-theme-default.css#L181)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think we should make the cover top and bottom margins match the internal pages for a default.
</blockquote></details>

Done.
___
*[`src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less` line 142 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6260#-NpLLdIA0PMHhHmIT1fP:-NpVVaSy2MB1X1a-FjWQ:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/1fc90fd54f4dc004c434c1fe29d9d7c6e627f37f/src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less#L142)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

That is, it will fail to have any effect if we one day give it controls for these variables :-). And of course the problem will still occur for the xmatter pages. But we can cross that bridge when we come to it.
</blockquote></details>

Done.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 3 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6260)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
