### PR TITLE
BL-5530 controls for Pan and Zoom Preview

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2184)

### CODE REVIEW

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DistFiles/localization/en/Bloom.xlf, line 1463 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2184#-L5G6-MYrN2agKr9NAUr:-L5G6-MYrN2agKr9NAUs:b-3ipfjg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/256dc45afe8e527632ee936aa0deab9eaf226475/DistFiles/localization/en/Bloom.xlf#L1463)):*
> ```XML
>         <note>ID: EditTab.Toolbox.Music.NoMusic</note>
>       </trans-unit>
>       <trans-unit id="EditTab.Toolbox.PanAndZoom.PanAndZoomTool" sil:dynamic="true">
> ```

Was this deletion intentional?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2184#-:-L5G6dgPyp9J4G8JA9Rv:bnfp4nl)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DistFiles/localization/en/Bloom.xlf, line 1463 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2184#-L5G6-MYrN2agKr9NAUr:-L5G9xhtmh8nSfMT20mA:boz9oh6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/256dc45afe8e527632ee936aa0deab9eaf226475/DistFiles/localization/en/Bloom.xlf#L1463)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Was this deletion intentional?
</blockquote></details>

Yes. It had at some point become an unused duplicate of PanAndZoom.Heading

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2184)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[DistFiles/localization/en/Bloom.xlf, line 1479 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2184#-L5UCHSNGmk8Zmsc8iHx:-L5UCHSNGmk8Zmsc8iHy:b-g810z2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8dd03606d75dc65cf93818a0f47a3fb72f6d2602/DistFiles/localization/en/Bloom.xlf#L1479)):*
> ```XML
>         <source xml:lang="en">Background Music</source>
>         <note>ID: EditTab.Toolbox.PanAndZoom.Preview.Music</note>
>         <note>In the context where this is one of the features that may be included in Preview or not</note>
> ```

"In the context where this is"
This English is awkward, will be often read by non-native speakers. Same for the next two.

---

*[src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx, line 30 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2184#-L5UCooNhLfz2mua6agH:-L5UCooNhLfz2mua6agI:b-o0t77z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8dd03606d75dc65cf93818a0f47a3fb72f6d2602/src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx#L30)):*
> musicVolumeName

I can't figure out what that means. Is it "music volume Attribute"?

I can't figure out what "musicAttrName" could be either. 

---

*[src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx, line 140 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2184#-L5UDWxmPu-AgmdOV5H2:-L5UDWxmPu-AgmdOV5H3:beq2e0a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8dd03606d75dc65cf93818a0f47a3fb72f6d2602/src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx#L140)):*
> ```XML
>         currentlyPlaying: () => boolean,
>         setPlayState: (boolean) => void) {
>         let audioStr = this.getBloomPageAttr(this.musicAttrName);
> ```

Is Reviewable just no showing the indent here for this function?

---

*[src/BloomBrowserUI/bookEdit/toolbox/panAndZoom/panZoomToolControls.tsx, line 485 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2184#-L5UEBzq0suQ5utbFIdG:-L5UEBzrpg2l1VUuBCfH:b-mby1rh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8dd03606d75dc65cf93818a0f47a3fb72f6d2602/src/BloomBrowserUI/bookEdit/toolbox/panAndZoom/panZoomToolControls.tsx#L485)):*
> ```XML
>                             onClick={() => this.props.onPreviewClick()} />
>                         <div className="previewSettingsWrapper">
>                             <Div className="panAndZoom-label"
> ```

If I'm not mistaken, these capital "Div" things are labels. If true, they should really be named <Label> or even <L10NLabel>

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2184)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[DistFiles/localization/en/Bloom.xlf, line 1479 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2184#-L5UCHSNGmk8Zmsc8iHx:-L5V7DNP9xrg1ZzbqEsM:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8dd03606d75dc65cf93818a0f47a3fb72f6d2602/DistFiles/localization/en/Bloom.xlf#L1479)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

"In the context where this is"
This English is awkward, will be often read by non-native speakers. Same for the next two.
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx, line 30 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2184#-L5UCooNhLfz2mua6agH:-L5V82vVr8_hXB8q3Tzd:b1baf3w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8dd03606d75dc65cf93818a0f47a3fb72f6d2602/src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx#L30)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

> musicVolumeName

I can't figure out what that means. Is it "music volume Attribute"?

I can't figure out what "musicAttrName" could be either. 
</blockquote></details>

I added a comment and improved one of the names...not sure how to make the other clearer, see what you think after reading comment.

---

*[src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx, line 140 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2184#-L5UDWxmPu-AgmdOV5H2:-L5V8R5ZinxqTUDziENr:bu48f3o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8dd03606d75dc65cf93818a0f47a3fb72f6d2602/src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx#L140)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is Reviewable just no showing the indent here for this function?
</blockquote></details>

No, the weirdness is in how VS code wants to indent. The previous two lines are indented because they are continuations of the argument list of the function; the following lines, because they are the body of the function. It looks as if the "let audioStr" line is the body of setPlayState, but it's not; setPlayState is a function argument (taking a boolean and returning void) to the function previewBackgroundMusic, of which "let audioStr..." is the first line.
I've added some comments which may help.

---

*[src/BloomBrowserUI/bookEdit/toolbox/panAndZoom/panZoomToolControls.tsx, line 485 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2184#-L5UEBzq0suQ5utbFIdG:-L5VBCV4dxb0i7aBZkOa:b-ywjcxh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8dd03606d75dc65cf93818a0f47a3fb72f6d2602/src/BloomBrowserUI/bookEdit/toolbox/panAndZoom/panZoomToolControls.tsx#L485)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

If I'm not mistaken, these capital "Div" things are labels. If true, they should really be named <Label> or even <L10NLabel>
</blockquote></details>

Not in the technical sense of labeling an input...sorry, your comment seems incomplete.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2184)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2184)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/toolbox/panAndZoom/panZoomToolControls.tsx, line 485 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2184#-L5UEBzq0suQ5utbFIdG:-L5iy9ecgJX77wgoKMWF:b-kr06hj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8dd03606d75dc65cf93818a0f47a3fb72f6d2602/src/BloomBrowserUI/bookEdit/toolbox/panAndZoom/panZoomToolControls.tsx#L485)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Not in the technical sense of labeling an input...sorry, your comment seems incomplete.
</blockquote></details>

"Div" is bad name for a custom localize-able bit of text. In other conversations, I couldn't get it changed, so I'll just merge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2184)*

**Pull request merged**
