### PR TITLE
BL-6307 Use param instead of rename to defeat caching

### PR DESCRIPTION
**Pull request by JohnThomson**
Also deals with problems in "Show in Folder" caused by adding timing fragment to URI.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863)

### CODE REVIEW

**Review by jsubloom — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863)* status: all files reviewed, 7 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 660 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863#-LQiscGD0lEza9o9yLJA:-LQiscGD0lEza9o9yLJB:bwqo5se) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91ef872c9d397cf2ed6a0dd1c3a57335cb99eb1/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L660)):*
> ```XML
>     // src may have # followed by timings.
>     // strip them off.
>     public static stripExtrasFromVideoFile(combined: string) {
> ```

IMO the function names and the comments inside/above could be generalized to... ExtractPathComponent[FromUrl[String]], or StripQueryAndFragment[FromUrl[String]], etc, something like that. 
I think the code we wrote inside this function is good and general-purpose enough that it need not be limited to just video files.

We could move the comments explaining that we use the query parameter to bypass the cache into GetSelectedVideoPath.
___
*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 667 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863#-LQiruRx1Yl0FzMokhpP:-LQiruRx1Yl0FzMokhpQ:b-ma89ep) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91ef872c9d397cf2ed6a0dd1c3a57335cb99eb1/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L667)):*
> ```XML
>         // src may have # followed by timings.
>         const hashIndex = combined.indexOf("#");
>         if (hashIndex > 0) {
> ```

nit: IMO >= 0 is more accurate,... if the string is just "#", IMO the correct filename is "" not "#".  But hopefully this case will never happen

Same thoughts for paramIndex > 0
___
*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 671 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863#-LQisCDD1h0rReeAbAb9:-LQisCDD1h0rReeAbAbA:b143q9n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91ef872c9d397cf2ed6a0dd1c3a57335cb99eb1/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L671)):*
> ```XML
>         }
>         // src may have ? followed by fake params to defeat caching.
>         const paramIndex = combined.indexOf("?");
> ```

It doesn't really make any difference, but IMO it seems to make more sense to check for "?" first.  If we want to, we can even return immediately without bothering to process for "#". not sure I see the advantage of checking "#"
___
*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 815 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863#-LQiv1XP8YjMojxJwjGF:-LQiv1XP8YjMojxJwjGG:b-ggqgff) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91ef872c9d397cf2ed6a0dd1c3a57335cb99eb1/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L815)):*
> ```XML
>         BloomApi.get(
>             "toolbox/fileExists?filename=" +
>                 SignLanguageTool.stripExtrasFromVideoFile(src),
> ```

Well, here's one of your least-favorite questions...

Anyway, can you check if the innards BloomApi.get performs URL encoding of the query params?  My suspicion is that theoretically, this function right here should be responsible for encoding the query params.
___
*[src/BloomExe/Book/HtmlDom.cs, line 1786 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863#-LQiw3JiBBNHumWNGt4i:-LQiw3JiBBNHumWNGt4j:b-tv4vns) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91ef872c9d397cf2ed6a0dd1c3a57335cb99eb1/src/BloomExe/Book/HtmlDom.cs#L1786)):*
> ```
> paramString
> ```
Need to encode paramSting if urlEncode == true
___
*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 597 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863#-LQiwAtN0UFt-v5-Dagu:-LQiwAtN0UFt-v5-Dagv:b-glifos) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91ef872c9d397cf2ed6a0dd1c3a57335cb99eb1/src/BloomExe/web/controllers/SignLanguageApi.cs#L597)):*
> ```Smalltalk
> 			var fileName = StripTimingFromVideoUrl(fileNameWithTimings, out rawTimings);
> 			var paramIndex = fileName.IndexOf("?");
> 			if (paramIndex > 0)
> ```

Nit: >= 0 IMO
___
*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 710 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863#-LQiwKOHC2L8JGKnza5F:-LQiwKOHC2L8JGKnza5G:b-r0p18p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91ef872c9d397cf2ed6a0dd1c3a57335cb99eb1/src/BloomExe/web/controllers/SignLanguageApi.cs#L710)):*
> ```
> defeat this
> ```
I would prefer "bypass the cache", but it's ok either way

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 660 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863#-LQiscGD0lEza9o9yLJA:-LQp2hHL9Q9rJylKuFFu:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91ef872c9d397cf2ed6a0dd1c3a57335cb99eb1/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L660)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

IMO the function names and the comments inside/above could be generalized to... ExtractPathComponent[FromUrl[String]], or StripQueryAndFragment[FromUrl[String]], etc, something like that. 
I think the code we wrote inside this function is good and general-purpose enough that it need not be limited to just video files.

We could move the comments explaining that we use the query parameter to bypass the cache into GetSelectedVideoPath.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 667 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863#-LQiruRx1Yl0FzMokhpP:-LQp2qP6CSadHzuq-qXg:b-cc7kvu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91ef872c9d397cf2ed6a0dd1c3a57335cb99eb1/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L667)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

nit: IMO >= 0 is more accurate,... if the string is just "#", IMO the correct filename is "" not "#".  But hopefully this case will never happen

Same thoughts for paramIndex > 0
</blockquote></details>

I remember thinking of that but can't remember why I decided not to use >=. Have changed it.
___
*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 671 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863#-LQisCDD1h0rReeAbAb9:-LQp2xFZBUoflMnGdAfF:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91ef872c9d397cf2ed6a0dd1c3a57335cb99eb1/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L671)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

It doesn't really make any difference, but IMO it seems to make more sense to check for "?" first.  If we want to, we can even return immediately without bothering to process for "#". not sure I see the advantage of checking "#"
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 815 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863#-LQiv1XP8YjMojxJwjGF:-LQp4AWiCc6NVMFBYEs0:b-sbf2ja) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91ef872c9d397cf2ed6a0dd1c3a57335cb99eb1/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L815)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Well, here's one of your least-favorite questions...

Anyway, can you check if the innards BloomApi.get performs URL encoding of the query params?  My suspicion is that theoretically, this function right here should be responsible for encoding the query params.
</blockquote></details>

I added a comment.
___
*[src/BloomExe/Book/HtmlDom.cs, line 1786 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863#-LQiw3JiBBNHumWNGt4i:-LQp6Znd1IR2Vk8sllAE:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91ef872c9d397cf2ed6a0dd1c3a57335cb99eb1/src/BloomExe/Book/HtmlDom.cs#L1786)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> paramString
> ```
Need to encode paramSting if urlEncode == true
</blockquote></details>

Done.
___
*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 597 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863#-LQiwAtN0UFt-v5-Dagu:-LQp5HSGC4e7ga7a1Men:bb6un1j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91ef872c9d397cf2ed6a0dd1c3a57335cb99eb1/src/BloomExe/web/controllers/SignLanguageApi.cs#L597)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Nit: >= 0 IMO
</blockquote></details>

Done
___
*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 710 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863#-LQiwKOHC2L8JGKnza5F:-LQp5Z055JDfN9auKBoJ:b8hfa4e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91ef872c9d397cf2ed6a0dd1c3a57335cb99eb1/src/BloomExe/web/controllers/SignLanguageApi.cs#L710)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> defeat this
> ```
I would prefer "bypass the cache", but it's ok either way
</blockquote></details>

I reworded it a bit more, since 'bypass' doesn't feel quite right.

**Review by jsubloom — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @sujeffreyl and @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 653 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863#-LQp85k_4knI918H9vgR:-LQp85ka0FwbGu-JZ8Gp:b3xjyyk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ed5bb178c7d31a4192a5a34450576eb6567a6329/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L653)):*
> ```
> of
> ```
sp., "off"
___
*[src/BloomExe/Book/HtmlDom.cs, line 1786 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863#-LQp9gZ3E7G1x5NVvm4-:-LQp9gZ3E7G1x5NVvm40:b-3j1oxr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ed5bb178c7d31a4192a5a34450576eb6567a6329/src/BloomExe/Book/HtmlDom.cs#L1786)):*
> ```Smalltalk
> 			if (urlEncode)
> 			{
> 				paramString = HttpUtility.UrlEncode(paramString);
> ```

Ugh, eww. I think I would recommend changing the parameter to "encodedParamString" and not worrying about it.

The input to this line can easily by paramString = "?q=cats".  Both the "%" and "=" get encoded.  I suggest to let the caller of this function encode each of the key-value pairs individually and join them all together than bothering to split it up here.
___
*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 597 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863#-LQiwAtN0UFt-v5-Dagu:-LQp8rtsC2v1u4yvBN68:bb6ywmx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d91ef872c9d397cf2ed6a0dd1c3a57335cb99eb1/src/BloomExe/web/controllers/SignLanguageApi.cs#L597)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done
</blockquote></details>

LGTM

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 653 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863#-LQp85k_4knI918H9vgR:-LQswkiL4DzF-H6joME0:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ed5bb178c7d31a4192a5a34450576eb6567a6329/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L653)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> of
> ```
sp., "off"
</blockquote></details>

Done.
___
*[src/BloomExe/Book/HtmlDom.cs, line 1786 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863#-LQp9gZ3E7G1x5NVvm4-:-LQswmPT1_-YZeuBZPjB:buquou5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ed5bb178c7d31a4192a5a34450576eb6567a6329/src/BloomExe/Book/HtmlDom.cs#L1786)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Ugh, eww. I think I would recommend changing the parameter to "encodedParamString" and not worrying about it.

The input to this line can easily by paramString = "?q=cats".  Both the "%" and "=" get encoded.  I suggest to let the caller of this function encode each of the key-value pairs individually and join them all together than bothering to split it up here.
</blockquote></details>

Sigh, good catch. How did I miss that after spending the last two days reading about this? What's even more puzzling is that I did re-test, and somehow it worked, even though it presumably would have encoded the ? and =.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/Book/HtmlDom.cs, line 1786 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863#-LQp9gZ3E7G1x5NVvm4-:-LQt2WIxBk9kY6VKdqJz:b-oac3k8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ed5bb178c7d31a4192a5a34450576eb6567a6329/src/BloomExe/Book/HtmlDom.cs#L1786)):*
>  I think I would recommend changing the parameter to "encodedParamString" and not worrying about it.

The nice thing about having this parameter is forcing the programmer invoking this to think about it. But having a default (=true) on it somewhat defeats that advantage. I'd remove that.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/Book/HtmlDom.cs, line 1786 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863#-LQp9gZ3E7G1x5NVvm4-:-LQtN2jF8kvH05mfMeY_:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ed5bb178c7d31a4192a5a34450576eb6567a6329/src/BloomExe/Book/HtmlDom.cs#L1786)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

>  I think I would recommend changing the parameter to "encodedParamString" and not worrying about it.

The nice thing about having this parameter is forcing the programmer invoking this to think about it. But having a default (=true) on it somewhat defeats that advantage. I'd remove that.
</blockquote></details>

Done.

**Review by jsubloom — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2863)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
