### PR TITLE
[4.0]BL-5493 Fix message box

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2153)

### CODE REVIEW

**Comment by gmartin7** [comment]
This is actually difficult for me to test. The section of code I change here is the one that the Release Internal build was going through. It should pop up a standard message box. The 'form' variable I'm eliminating here was apparently the download progress box.
Anyone else have any better ideas?

**Comment by andrew-polk** [comment]
Doesn't that just unset the parent form? How does that help? For testing, can't you set your channel explicitly in code?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2153#-:-L4gSoPQQvwy-f-5jYgM:b-eaepts)*

**Comment by gmartin7** [comment]
Thanks for your pointer about setting stuff in code. That simplified several things. It looks like toasts (and Message Box?) don't work as well when they target a progress dialog. :(

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2153#-:-L4g_DBN9yk2wP2fiX_k:b-848pmd)*

**Comment by andrew-polk** [comment]
Sorry; I'm still confused. I don't see anything here related to toasts.
If the message box doesn't show when the parent is a progress dialog, should we conditionally set the parent if it isn't one? I'm guessing we explicitly wanted the behavior of centering on parent in most cases.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2153#-:-L4ga2JmO0rm70AKiWRX:bgou207)*

**Comment by gmartin7** [comment]
My fault for pushing a reviewable comment with no code change while I was working on the code. Good point about the conditional parent, though. I've done that in this latest version.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2153#-:-L4gmVRnrwoTVjJIrTo1:bjiu2cn)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/NonFatalProblem.cs, line 83 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2153#-L4gnhcmYhuT9tZP32VS:-L4gnhcmYhuT9tZP32VT:bfaxhx3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/96a958a8057c28114b9735f9ba2a2b8405a6f516/src/BloomExe/NonFatalProblem.cs#L83)):*
> modalThreshold = ModalIf.All;

Shouldn't this be `modalThreshold = passiveThreshold`?

---

*[src/BloomExe/NonFatalProblem.cs, line 100 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2153#-L4gp1CxBivTfF91wPBC:-L4goyTMMImyft0nt8-f:b-52wi2y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/96a958a8057c28114b9735f9ba2a2b8405a6f516/src/BloomExe/NonFatalProblem.cs#L100)):*
> ```Smalltalk
> 								MessageBox.Show(fullDetailedMessage, string.Empty, MessageBoxButtons.OK);
> 							} else {
> 								MessageBox.Show(formForSynchronizing, fullDetailedMessage, string.Empty, MessageBoxButtons.OK);
> ```

Seems like this deserves a comment 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2153)*

**Comment by gmartin7** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/NonFatalProblem.cs, line 83 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2153#-L4gnhcmYhuT9tZP32VS:-L4gqJSUPqlZ3mGFXd4k:b-1t5kvg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/96a958a8057c28114b9735f9ba2a2b8405a6f516/src/BloomExe/NonFatalProblem.cs#L83)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> modalThreshold = ModalIf.All;

Shouldn't this be `modalThreshold = passiveThreshold`?
</blockquote></details>

Good point. Done. Well, not quite that simple...

---

*[src/BloomExe/NonFatalProblem.cs, line 100 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2153#-L4gp1CxBivTfF91wPBC:-L4gqT8yQo_mSLF7_sKi:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/96a958a8057c28114b9735f9ba2a2b8405a6f516/src/BloomExe/NonFatalProblem.cs#L100)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems like this deserves a comment 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2153)*

**Comment by gmartin7** [comment]
And actually, it was me who just put that MessageBox in there. It didn't used to be a possibility, so no previously "explicitly wanted" behavior.

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2153#-:-L4gqeFeRf2wN2E8su7q:bg5i0xh)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/NonFatalProblem.cs, line 83 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2153#-L4gnhcmYhuT9tZP32VS:-L4gr1JDQoZi4UjfLgP5:bk824dy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/96a958a8057c28114b9735f9ba2a2b8405a6f516/src/BloomExe/NonFatalProblem.cs#L83)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Good point. Done. Well, not quite that simple...
</blockquote></details>

What if the enums are the same in the future? What if Parse fails?

---

*[src/BloomExe/NonFatalProblem.cs, line 96 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2153#-L4gqh82oP8ZaT9ZtHDO:-L4gqh82oP8ZaT9ZtHDP:b-pmcw4z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/38ce30e03f7f6609493de4763183b875ebc6b7f0/src/BloomExe/NonFatalProblem.cs#L96)):*
> ```Smalltalk
> 						else
> 						{
> 							// We don't want even our MessageBox targetting a ProgressDialog.
> ```

Sorry, but I want to help my future self. Why? What bad things happens? May be worth expanding the toast comment, too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2153)*

**Comment by gmartin7** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/NonFatalProblem.cs, line 83 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2153#-L4gnhcmYhuT9tZP32VS:-L4grX86X_vp23JzqwDu:bg7rq8x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/96a958a8057c28114b9735f9ba2a2b8405a6f516/src/BloomExe/NonFatalProblem.cs#L83)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What if the enums are the same in the future? What if Parse fails?
</blockquote></details>

I just copied what we do down below. I've now moved the comment and variable initialization up too, so I can use the variable.

---

*[src/BloomExe/NonFatalProblem.cs, line 96 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2153#-L4gqh82oP8ZaT9ZtHDO:-L4gtuydmLsNyTFc87aR:b-w3rvwt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/38ce30e03f7f6609493de4763183b875ebc6b7f0/src/BloomExe/NonFatalProblem.cs#L96)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry, but I want to help my future self. Why? What bad things happens? May be worth expanding the toast comment, too.
</blockquote></details>

Done. Is that better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2153)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/NonFatalProblem.cs, line 83 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2153#-L4gnhcmYhuT9tZP32VS:-L4gz2Nzlezcjxk_8EF5:b3gv9fp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/96a958a8057c28114b9735f9ba2a2b8405a6f516/src/BloomExe/NonFatalProblem.cs#L83)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I just copied what we do down below. I've now moved the comment and variable initialization up too, so I can use the variable.
</blockquote></details>

Still a problem lurking if the enums ever diverge...
But since I don't see why they would, I'll merge as is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2153)*

**Pull request merged**
