### PR TITLE
BL-4483 Books made from templates should use default license

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1624)

### CODE REVIEW

**Comment by JohnThomson** [comment]
https://github.com/BloomBooks/BloomDesktop/pull/1624

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/BookStarter.cs, line 188 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1624#-KgPTEOAX7WjFuHfZ4Xf:-KgPTEOBWgdgisQLaLbr:b-w0z3qg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f3eac6b31e9922bb517418d6c2da9313ab256818/src/BloomExe/Book/BookStarter.cs#L188)):*
> FixCc0License

Not a big deal, but is it really "fixing" it?

Additionally, per the discussion in our status meeting, this must only occur when the source book is a template.

---

*[src/BloomExe/Book/BookStarter.cs, line 203 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1624#-KgPT3pi2ONg36OH-uVB:-KgPT3pi2ONg36OH-uVC:b-6af92j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f3eac6b31e9922bb517418d6c2da9313ab256818/src/BloomExe/Book/BookStarter.cs#L203)):*
> <br></br>\r\n            You...

Presumably, you copied this from a real book, but it sure seems strange to me. For one thing, <br></br> isn't even valid html.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1624)*

**Comment by JohnThomson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/BookStarter.cs, line 188 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1624#-KgPTEOAX7WjFuHfZ4Xf:-KgPlhgobl-z-EftNKhn:b6i6e39) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f3eac6b31e9922bb517418d6c2da9313ab256818/src/BloomExe/Book/BookStarter.cs#L188)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> FixCc0License

Not a big deal, but is it really "fixing" it?

Additionally, per the discussion in our status meeting, this must only occur when the source book is a template.
</blockquote></details>

New version was already renamed (and calling it is now conditional)

---

*[src/BloomExe/Book/BookStarter.cs, line 203 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1624#-KgPT3pi2ONg36OH-uVB:-KgPlqENDrU72JtCkvVW:byycp5k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f3eac6b31e9922bb517418d6c2da9313ab256818/src/BloomExe/Book/BookStarter.cs#L203)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> <br></br>\r\n            You...

Presumably, you copied this from a real book, but it sure seems strange to me. For one thing, <br></br> isn't even valid html.
</blockquote></details>

new version doesn't insert anything at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1624)*

**Comment by andrew-polk** [comment]
:lgtm:
Looks good to me with one minor, optional suggestion for rewording a comment.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/BookStarter.cs, line 196 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1624#-KgPmqRNZKND2xh6Y_sU:-KgPmqRNZKND2xh6Y_sV:b-vfznsn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/757e6ee971bbb8dd343e3844783ac803579bedc1/src/BloomExe/Book/BookStarter.cs#L196)):*
> though we don't do it for that
> 			// since it's a shell

This comment confused me at first because the method name is RemoveLicenseFromShell.
Would it be more clear to say, "though we don't do it for books created from Vaccinations because it is a shell, not a template"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1624#-:-KgPnAXh93iXLmrWLv4h:bjuvnv6)*

**Comment by JohnThomson** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/BookStarter.cs, line 196 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1624#-KgPmqRNZKND2xh6Y_sU:-KgPukwcSLJCDmO_2WOQ:bh2gnpi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/757e6ee971bbb8dd343e3844783ac803579bedc1/src/BloomExe/Book/BookStarter.cs#L196)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> though we don't do it for that
> 			// since it's a shell

This comment confused me at first because the method name is RemoveLicenseFromShell.
Would it be more clear to say, "though we don't do it for books created from Vaccinations because it is a shell, not a template"
</blockquote></details>

Done. (Actually I reworded it a bit more than that.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1624)*

**Comment by hatton** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/BookStarter.cs, line 192 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1624#-KgPyBxo_wody457NJjo:-KgPyBxo_wody457NJjp:bdmvhx1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dab94b633b04f9ce3f98a93af704930b4cb871d3/src/BloomExe/Book/BookStarter.cs#L192)):*
> ```Smalltalk
> 		private void RemoveLicenseFromShell(BookStorage storage)
> 		{
> 			var dataDiv = storage.Dom.SelectSingleNode("//div[@id='bloomDataDiv']");
> ```

I think this method could reuse existing code:

    storage.Dom.RemoveBookSetting("licenseUrl")
    storage.Dom.RemoveBookSetting("licenseDescription")

etc.

I think it would be nice to see this method in BookCopyrightAndLicense, something like

    public void RemoveLicense(HtmlDom dom)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1624)*

**Comment by andrew-polk** [comment]
Needs to be rebased on Version3.9 branch

**Comment by JohnThomson** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/BookStarter.cs, line 192 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1624#-KgPyBxo_wody457NJjo:-KgQrFuAh7F46OJyeHhW:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dab94b633b04f9ce3f98a93af704930b4cb871d3/src/BloomExe/Book/BookStarter.cs#L192)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think this method could reuse existing code:

    storage.Dom.RemoveBookSetting("licenseUrl")
    storage.Dom.RemoveBookSetting("licenseDescription")

etc.

I think it would be nice to see this method in BookCopyrightAndLicense, something like

    public void RemoveLicense(HtmlDom dom)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1624)*

**Comment by hatton** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/BookStarter.cs, line 192 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1624#-KgPyBxo_wody457NJjo:-KgQsSwI--QcnW0bTZKh:bxly4ml) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dab94b633b04f9ce3f98a93af704930b4cb871d3/src/BloomExe/Book/BookStarter.cs#L192)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

That change has not shown up yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1624)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1624#-:-KgQsfhdxlaWZR-Sqggv:bnfp4nl)*

**Pull request merged**
