### PR TITLE
Clarify confusing localization

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4714)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4714)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[DistFiles/localization/en/Bloom.xlf, line 883 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4714#-MjZvVJB2-zqyKbpH4WS:-MjZvVJB2-zqyKbpH4WT:b-wo2ou6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fc83422250d4a20265c267ae7e057f8b11ac1c21/DistFiles/localization/en/Bloom.xlf#L883)):*
> ```XML
>         <source xml:lang="en">&amp;Cancel</source>
>         <note>This is identical to Common.Cancel. The duplication was introduced by a mistake.</note>
>         <note>This is shown at the bottom of a dialog box. It is paired with an action button like "OK" and it means "do not do the action".</note>
> ```

Ugh, if I look a little harder, there are obviously other WinForms strings that are like this too... Common.NextButton, Common.OkButton fore xample
___
*[DistFiles/localization/en/Bloom.xlf, line 884 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4714#-MjZvSlz9_OJGVtSWCtd:-MjZvSlz9_OJGVtSWCte:b-222awl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fc83422250d4a20265c267ae7e057f8b11ac1c21/DistFiles/localization/en/Bloom.xlf#L884)):*
> ```XML
>         <note>This is identical to Common.Cancel. The duplication was introduced by a mistake.</note>
>         <note>This is shown at the bottom of a dialog box. It is paired with an action button like "OK" and it means "do not do the action".</note>
>         
> ```

Or we could also try to remove the references to it.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4714)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @sujeffreyl)

___
*[DistFiles/localization/en/Bloom.xlf, line 885 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4714#-Mj_P7s71HQB1BMRLiVs:-Mj_P7s71HQB1BMRLiVt:b359ogd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fc83422250d4a20265c267ae7e057f8b11ac1c21/DistFiles/localization/en/Bloom.xlf#L885)):*
> ```XML
>         <note>This is shown at the bottom of a dialog box. It is paired with an action button like "OK" and it means "do not do the action".</note>
>         
>         <note>Please make sure to start your translation with an &amp; character, but pretend it doesn't have any meaning in the source text.</note>
> ```

But, what the translator has to do is much harder than that. The letter that follows the ampersand is the shortcut; for example, our dialogs can be canceled by typing Alt-C.  It's easy to imagine a language where every verb begins with a prefix...let's say 'pres'...that marks present imperative. So the localizations will be Preshelp, Presok, and Prescancel. If the translator just leaves the ampersand at the start, they will all have the shortcut Alt-P...unless of course something else sees it first and thinks Alt-P should mean Print. The translator should produce Pres&help, Pres&ok, and Pres&cancel. Of course, if those morphemes start with the same letter, he may need to be even more creative.
And beyond that, he really should think hard about shortcuts across the whole scope of the application and make them as mnemonic as possible in his language without duplication.
Maybe the comment should be more along the lines, "The ampersand marks a letter that will function as a keyboard shortcut for activating the button. Keyboard shortcuts need careful thought to make sure that each is unique. If in doubt, you can just leave out the ampersand."

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4714)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[DistFiles/localization/en/Bloom.xlf, line 885 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4714#-Mj_P7s71HQB1BMRLiVs:-MjeVc-OAjgIggsn0KpU:bv1z64n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fc83422250d4a20265c267ae7e057f8b11ac1c21/DistFiles/localization/en/Bloom.xlf#L885)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

But, what the translator has to do is much harder than that. The letter that follows the ampersand is the shortcut; for example, our dialogs can be canceled by typing Alt-C.  It's easy to imagine a language where every verb begins with a prefix...let's say 'pres'...that marks present imperative. So the localizations will be Preshelp, Presok, and Prescancel. If the translator just leaves the ampersand at the start, they will all have the shortcut Alt-P...unless of course something else sees it first and thinks Alt-P should mean Print. The translator should produce Pres&help, Pres&ok, and Pres&cancel. Of course, if those morphemes start with the same letter, he may need to be even more creative.
And beyond that, he really should think hard about shortcuts across the whole scope of the application and make them as mnemonic as possible in his language without duplication.
Maybe the comment should be more along the lines, "The ampersand marks a letter that will function as a keyboard shortcut for activating the button. Keyboard shortcuts need careful thought to make sure that each is unique. If in doubt, you can just leave out the ampersand."
</blockquote></details>

Ok, I made a simple test application to see what happens if there are collisions. I made two buttons with text "&Hello" and "&Hola". Unfortunately, WinForms didn't automatically resolve the situation. Both buttons had an underline under the "H" if you press Alt. It seems to me that the last one wins.

Argh. I think it's too much burden to put on the translators to come up with unique mnemonics in that language. Also, how are they supposed to do that? How do they know which other buttons it appears with? The Cancel button appears in more than one dialog. In theory, it could appear with different other buttons in each one, which would mean that a static mnemonic wouldn't work well (in theory).

On the bright side, at least for the cancel button there's a lot of cases where there's only 1-2 buttons, in which case the chance for collisions is lower at least.

Ok, some here are the thoughts I have:
1) Just doing the straightforward mnemonic and hoping for the best. It suspect it'll work ok a majority of the time? Even the "buggy" case is not that horrible.
2) Tell them to drop the ampersand in non-English translations? Except, many translations have already been made that include this string.
3) Tell the translator to come up with good unique mnemonics, except I don't think that's a reasonable or even tractable task for them, see above.
4) Code up some auto mnemonic collision fixer thing.
Only 1 and 2 sound semi-reasonable to me, I guess I like #1 better of the two.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4714)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @sujeffreyl)

___
*[DistFiles/localization/en/Bloom.xlf, line 885 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4714#-Mj_P7s71HQB1BMRLiVs:-Mjebbjp126620w0O5S0:b-du3j1v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fc83422250d4a20265c267ae7e057f8b11ac1c21/DistFiles/localization/en/Bloom.xlf#L885)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Ok, I made a simple test application to see what happens if there are collisions. I made two buttons with text "&Hello" and "&Hola". Unfortunately, WinForms didn't automatically resolve the situation. Both buttons had an underline under the "H" if you press Alt. It seems to me that the last one wins.

Argh. I think it's too much burden to put on the translators to come up with unique mnemonics in that language. Also, how are they supposed to do that? How do they know which other buttons it appears with? The Cancel button appears in more than one dialog. In theory, it could appear with different other buttons in each one, which would mean that a static mnemonic wouldn't work well (in theory).

On the bright side, at least for the cancel button there's a lot of cases where there's only 1-2 buttons, in which case the chance for collisions is lower at least.

Ok, some here are the thoughts I have:
1) Just doing the straightforward mnemonic and hoping for the best. It suspect it'll work ok a majority of the time? Even the "buggy" case is not that horrible.
2) Tell them to drop the ampersand in non-English translations? Except, many translations have already been made that include this string.
3) Tell the translator to come up with good unique mnemonics, except I don't think that's a reasonable or even tractable task for them, see above.
4) Code up some auto mnemonic collision fixer thing.
Only 1 and 2 sound semi-reasonable to me, I guess I like #1 better of the two.
</blockquote></details>

I agree, it's a difficult problem. Probably warrants a group discussion. I don't even know how likely it is that our users will use shortcuts.
I'm not sure what the straightforward mnemonic is...do you mean, just tell them to put it at the start and hope for the best? I don't think we can lock it to be 'C', it has to be a letter in the translation.
4 Sounds quite difficult. I suppose a minimal solution would be to remove the ampersand from all but one option that uses the same letter, so at least the effect is unambiguous.
I _think_ alt shortcuts are only used for dialogs (and probably only dialogs we're doing with Windows, not the newer ones implemented in HTML) so this is at least a problem that is diminishing rather than growing.
I lean towards the combination of 2 and 3: tell them they either need to come up with unique ones or remove them.
A plausible strategy might be to check EVERYTHING in the xlf files and make sure each shortcut key is only used once...if that proves too difficult some or all could be removed. Not sure how easy that is with the tools translators use.
How about, "If you include an ampersand in your translation, it will not be visible in Bloom. Instead, the letter following it will be a keyboard shortcut (e.g., &Cancel means that alt-C can be used to activate the Cancel button.) The letter marked with ampersand is usually the first one but does not have to be. It is important not to mark the same letter in two different controls in the same dialog. If you are not sure, just don't include an ampersand; the only consequence is that this control cannot be activated using an alt-key shortcut."

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4714)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[DistFiles/localization/en/Bloom.xlf, line 885 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4714#-Mj_P7s71HQB1BMRLiVs:-Mjis11s-7LYznw8lwfh:bb3p59j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fc83422250d4a20265c267ae7e057f8b11ac1c21/DistFiles/localization/en/Bloom.xlf#L885)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I agree, it's a difficult problem. Probably warrants a group discussion. I don't even know how likely it is that our users will use shortcuts.
I'm not sure what the straightforward mnemonic is...do you mean, just tell them to put it at the start and hope for the best? I don't think we can lock it to be 'C', it has to be a letter in the translation.
4 Sounds quite difficult. I suppose a minimal solution would be to remove the ampersand from all but one option that uses the same letter, so at least the effect is unambiguous.
I _think_ alt shortcuts are only used for dialogs (and probably only dialogs we're doing with Windows, not the newer ones implemented in HTML) so this is at least a problem that is diminishing rather than growing.
I lean towards the combination of 2 and 3: tell them they either need to come up with unique ones or remove them.
A plausible strategy might be to check EVERYTHING in the xlf files and make sure each shortcut key is only used once...if that proves too difficult some or all could be removed. Not sure how easy that is with the tools translators use.
How about, "If you include an ampersand in your translation, it will not be visible in Bloom. Instead, the letter following it will be a keyboard shortcut (e.g., &Cancel means that alt-C can be used to activate the Cancel button.) The letter marked with ampersand is usually the first one but does not have to be. It is important not to mark the same letter in two different controls in the same dialog. If you are not sure, just don't include an ampersand; the only consequence is that this control cannot be activated using an alt-key shortcut."
</blockquote></details>

"I'm not sure what the straightforward mnemonic is...do you mean, just tell them to put it at the start and hope for the best? I don't think we can lock it to be 'C', it has to be a letter in the translation."  Yep, I meant for the translator to put it at the start and it would use whatever the first letter of the translation is.

4: I was thinking about it while driving and was actually not feeling too bad about it anymore, if we were actively using WinForms. But since we're diminishing its use like you said, I didn't really want to pursue (4)

I would be very amenable to changing it to the note you suggested, do others agree?

**Review by sujeffreyl — COMMENTED** [review]
r2: rebase to master.
r3: Update to note suggested by JT

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4714#-:-N3dr7X46oRB-ZfFtJEr:b-i12sfl)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4714)* status: all files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

**Pull request merged**
