### PR TITLE
Bulk Publish requires Bloom enterprise (BL-10190)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4680)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4680)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @sujeffreyl)

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4680)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx, line 73 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4680#-Mhy7Qvx35VjFVNoIb0l:-Mhy7Qvx35VjFVNoIb0m:bi5dvta) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/290b8c08cb2c310bfbc77ab4b0933ee9e65681dd/src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx#L73)):*
> ```XML
>                                                      css={css`
>                                 ${props.iconStyles !== undefined
> ```

Open to feedback about whether to do this override everything at once approach or override individual things or just put a class on it or something else

**Review by JohnThomson — CHANGES_REQUESTED** [review]
Looks basically good. A few minor suggestions.

> Reviewed 10 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4680#-:-MiMrKP-7D7YTORQcsom:b-b0b1at)* status: all files reviewed, 4 unresolved discussions (waiting on @hatton and @sujeffreyl)

___
*[src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx, line 73 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4680#-Mhy7Qvx35VjFVNoIb0l:-MiMq4mgEHf20311KBms:b-758lr5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/290b8c08cb2c310bfbc77ab4b0933ee9e65681dd/src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx#L73)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Open to feedback about whether to do this override everything at once approach or override individual things or just put a class on it or something else
</blockquote></details>

What about including the default styles unconditionally followed by the props.iconStyles if any? Then iconStyles can easily just override whatever needs changing. (I think the browser will happily just use the last thing it sees for any particular property.)
___
*[src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx, line 17 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4680#-MiMnbDGBSbAYNOZon9H:-MiMnbDGBSbAYNOZon9I:b-p078xt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/157be9d553ddf2dc6f54d27b86a6bbbd202f9fb5/src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx#L17)):*
> ```XML
>  * A component that gets the Bloom Enterprise settings value and stores it in BloomEnterpriseAvailableContext.Provider.
>  * The child nodes of this component may access to Bloom Enterprise settings value using BloomEnterpriseAvailableContext.Consumer.
>  */
> ```

The usage of this is quite unusual...not something I've seen before, though it looks like it might be a standard way to do this producer/consumer thing:
```
        <RequiresBloomEnterpriseProvider>
            <BloomEnterpriseAvailableContext.Consumer>
                {enterpriseAvailable => {
```
Might be worth commenting and giving an example, or referring to the one below?
I gather that the reason to make it a provider rather than just a wrapper which passes enterpriseAvailable as a prop is so that at any level nested inside it you can put a BloomEnterpriseAvailableContext.Consumer? Anyway, the reason for this unusual approach deserves a comment, I think.
Also there are several other calls to ettings/enterpriseEnabled...would they benefit from this? Not that I'd really like to see them in the same PR or commit, but it would be good for the long-term health of our code to fix them before tackling something new.
___
*[src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx, line 42 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4680#-MiMoDKPD36k4ZcuXo65:-MiMoDKPD36k4ZcuXo66:b-j6j07g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/157be9d553ddf2dc6f54d27b86a6bbbd202f9fb5/src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx#L42)):*
> ```XML
> 
> /**
>  * Checks the Bloom Enterprise settings and appends a Bloom Enterprise icon after the children if enterprise is off.
> ```

Might be worth making it explicit in the comments that the children and icon will be displayed as a flex row.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4680)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @hatton, @JohnThomson, and @sujeffreyl)

___
*[src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx, line 73 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4680#-Mhy7Qvx35VjFVNoIb0l:-MiMuxp4EqOw9JdCMqlq:b6foigy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/290b8c08cb2c310bfbc77ab4b0933ee9e65681dd/src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx#L73)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

What about including the default styles unconditionally followed by the props.iconStyles if any? Then iconStyles can easily just override whatever needs changing. (I think the browser will happily just use the last thing it sees for any particular property.)
</blockquote></details>

Ah yes. Clever.
___
*[src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx, line 17 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4680#-MiMnbDGBSbAYNOZon9H:-MiRp-bzAqOZmt04pWRd:b-c56pvw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/157be9d553ddf2dc6f54d27b86a6bbbd202f9fb5/src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx#L17)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

The usage of this is quite unusual...not something I've seen before, though it looks like it might be a standard way to do this producer/consumer thing:
```
        <RequiresBloomEnterpriseProvider>
            <BloomEnterpriseAvailableContext.Consumer>
                {enterpriseAvailable => {
```
Might be worth commenting and giving an example, or referring to the one below?
I gather that the reason to make it a provider rather than just a wrapper which passes enterpriseAvailable as a prop is so that at any level nested inside it you can put a BloomEnterpriseAvailableContext.Consumer? Anyway, the reason for this unusual approach deserves a comment, I think.
Also there are several other calls to ettings/enterpriseEnabled...would they benefit from this? Not that I'd really like to see them in the same PR or commit, but it would be good for the long-term health of our code to fix them before tackling something new.
</blockquote></details>

Ok, so JT and I talked. The producer/consumer's benefits are probably not really that worthwhile for us.
Uhm, i was going to convert it to use props, but then while I was doing that I figured it might just be easier / require less intermediate levels to extract all the hooks stuff into a function that we can re-use. I think this is a similar pattern to other things we've done like with useL10n. Hopefully that's better.
___
*[src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx, line 42 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4680#-MiMoDKPD36k4ZcuXo65:-MiMu2moEXVHsP9eLrI7:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/157be9d553ddf2dc6f54d27b86a6bbbd202f9fb5/src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx#L42)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Might be worth making it explicit in the comments that the children and icon will be displayed as a flex row.
</blockquote></details>

Done.

**Review by JohnThomson — APPROVED** [review]
Much simpler this way. Thanks.

I think there are several other places we could benefit from useEnterpriseAvailable, if you wanted to tackle that quickly before we forget.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4680#-:-MiSWbTJ796euX1h8TVy:b-vcx215)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Pull request merged**
