### PR TITLE
[5.5] BL-12333 Close unauthorized licensed content hole

### PR DESCRIPTION
**Pull request by gmartin7**
* part 2 (BloomPUB)

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5929)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
I thought we were just going to reuse the check the preview code makes and let it put the error in the progress dialog.

(Why doesn't that work anymore?)

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5929#-:-NXvkf4v2LLhEwBdfBAP:b-8apn6)* status: 0 of 3 files reviewed, all discussions resolved

**Review by gmartin7 — COMMENTED** [review]
Before this PR, the user could click the save button and the check was made and the message put in the progress dialog... but the button was already clicked, so Bloom went ahead and saved the `.bloomPUB` file. And I wasn't sure how to interrupt that process, I guess.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5929#-:-NXvr5aFD9bDdGVZD2QH:b-o06tny)* status: 0 of 3 files reviewed, all discussions resolved

**Review by gmartin7 — COMMENTED** [review]
... let me see if I can do that reliably.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5929#-:-NXvtDcJ05idSBPFp9RT:b-u9rut)* status: 0 of 3 files reviewed, all discussions resolved

**Review by andrew-polk — COMMENTED** [review]
Ah, ok. So even though that would normally stop the preview, it wasn't stopping the save.
Well, if this is the right behavior, that's fine.
But we may want to pull JH in if you think it is. It is a change in UX. And it would be good if the various publication paths were similar in their UX where possible.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5929#-:-NXvtjsWA_e0yWblT3CG:b-c7l9k8)* status: 0 of 3 files reviewed, all discussions resolved

**Review by andrew-polk — COMMENTED** [review]
Another thought: are there other things which stop the preview? If yes, then we also need the save to stop for them. So we may need that general mechanism anyway.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5929#-:-NXvu2k1BuYOShkh2xyt:b-3frba9)* status: 0 of 3 files reviewed, all discussions resolved

**Comment by gmartin7** [comment]
Closing this PR in favor of https://github.com/BloomBooks/BloomDesktop/pull/5931

**Pull request closed without merging**
