### PR TITLE
Make Upload button work (BL-11581)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5685)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5685)* status: 0 of 21 files reviewed, all discussions resolved

___
*[`src/BloomExe/web/controllers/LibraryPublishApi.cs` line 94 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5685#-NPtC7pN3iKCx3gdXo51:-NPtC7pN3iKCx3gdXo52:b-sa0hhz) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ed7629c34d778e25d59a25ab6f3f6d9f989ab4ed/src/BloomExe/web/controllers/LibraryPublishApi.cs#L94)):*
> ```Smalltalk
> 		}
> 
> 		private void HandleUpload(ApiRequest request)
> ```

This is mostly copied from the existing control. But also heavily modified.

**Review by hatton — CHANGES_REQUESTED** [review]
I ran out of time, didn't get to reviewing LibraryPublishApi yet.

> Reviewed 20 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5685#-:-NPtIro85xJFa6cNn6yr:bs36q3s)* status: 20 of 21 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 135 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5685#-NPtEfWc0k1TueE29xv_:-NPtEfWdD2DDcbZupsVi:bsim8xn) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ed7629c34d778e25d59a25ab6f3f6d9f989ab4ed/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L135)):*
> ```XML
>                     }
>                 },
>                 document.getElementById("confirm-dialog-root") // This div is created below.
> ```

It's  unusual in an all-react component to have to resort to element ids.  Maybe you are doing this because confirmDialog is pre-existing or something? Can it be brought up to date as a normal BloomDialog that just exports its `show` method?
___
*[`src/BloomBrowserUI/react_components/Progress/progressBox.tsx` line 54 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5685#-NPtH1RK3ZpLbxTnuFUq:-NPtH1RK3ZpLbxTnuFUr:bx2fu28) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ed7629c34d778e25d59a25ab6f3f6d9f989ab4ed/src/BloomBrowserUI/react_components/Progress/progressBox.tsx#L54)):*
Could use a good explanator comment.  E.g., maybe the explanation is along the lines of: 

> This has to be an uncontrolled component (has its own state) so that it can directly wire to the backend, but we need the parent to "control" it in the sense of needing to clear it. The ref lets us give a handle to parent.
___
*[`src/BloomExe/Book/Book.cs` line 4570 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5685#-NPtIGZi9EkKIn4kGv6r:-NPtIGZi9EkKIn4kGv6s:b-rfmkzf) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ed7629c34d778e25d59a25ab6f3f6d9f989ab4ed/src/BloomExe/Book/Book.cs#L4570)):*
> ```Smalltalk
> 		public void AddHistoryRecordForLibraryUpload()
> 		{
> 			BookHistory.AddEvent(this, BookHistoryEventType.Uploaded, "Book uploaded to Bloom Library");
> ```

Do we know the URL? Should we add that to the message?
___
*[`src/BloomExe/web/WebProgressAdapter.cs` line 43 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5685#-NPtIej19jSNSNDXSDxb:-NPtIej19jSNSNDXSDxc:b5dt241) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ed7629c34d778e25d59a25ab6f3f6d9f989ab4ed/src/BloomExe/web/WebProgressAdapter.cs#L43)):*
> ```Smalltalk
> 		public bool ShowVerbose { set { _showVerbose = value; } }
> 
> 		public bool CancelRequested { get; set; }
> ```

Wants to lose the `{get; set;}`  :-)

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5685)* status: 20 of 21 files reviewed, 4 unresolved discussions (waiting on @hatton)

___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 135 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5685#-NPtEfWc0k1TueE29xv_:-NPtQbfFA6Ck1JQEJuEE:b-cgztnt) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ed7629c34d778e25d59a25ab6f3f6d9f989ab4ed/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L135)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

It's  unusual in an all-react component to have to resort to element ids.  Maybe you are doing this because confirmDialog is pre-existing or something? Can it be brought up to date as a normal BloomDialog that just exports its `show` method?
</blockquote></details>

Good catch. Yeah, I just wasn't thinking.
___
*[`src/BloomExe/web/WebProgressAdapter.cs` line 43 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5685#-NPtIej19jSNSNDXSDxb:-NPtMWh1EEO_KoG8AZU5:b7dm5jl) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ed7629c34d778e25d59a25ab6f3f6d9f989ab4ed/src/BloomExe/web/WebProgressAdapter.cs#L43)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Wants to lose the `{get; set;}`  :-)
</blockquote></details>

We can't because that is part of the IProgress interface.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5685)* status: 18 of 23 files reviewed, 4 unresolved discussions (waiting on @hatton)

___
*[`src/BloomBrowserUI/react_components/confirmDialog.tsx` line 55 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5685#-NPtSlyu8wH-CwVsknlo:-NPtSlyu8wH-CwVsknlp:b-7eq51y) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/638def973ead0d1caf7754bb84c84dff9395235c/src/BloomBrowserUI/react_components/confirmDialog.tsx#L55)):*
> ```XML
>     return (
>         <BloomDialog
>             className="bloomModalDialog confirmDialog"
> ```

Removing these classes should have been part of the work I did in a previous commit to bring confirmDialog into the BloomDialog world.
The `bloomModalDialog` class was subtly messing with the UI. The `confirmDialog` class was never used.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5685)* status: 18 of 23 files reviewed, 4 unresolved discussions (waiting on @hatton)

___
*[`src/BloomBrowserUI/react_components/Progress/progressBox.tsx` line 54 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5685#-NPtH1RK3ZpLbxTnuFUq:-NPwfN8p1Jc85ypkixj4:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ed7629c34d778e25d59a25ab6f3f6d9f989ab4ed/src/BloomBrowserUI/react_components/Progress/progressBox.tsx#L54)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Could use a good explanator comment.  E.g., maybe the explanation is along the lines of: 

> This has to be an uncontrolled component (has its own state) so that it can directly wire to the backend, but we need the parent to "control" it in the sense of needing to clear it. The ref lets us give a handle to parent.
</blockquote></details>

Done.
___
*[`src/BloomExe/Book/Book.cs` line 4570 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5685#-NPtIGZi9EkKIn4kGv6r:-NPwYFsIAdVqk5Nda51d:b3tmkjh) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ed7629c34d778e25d59a25ab6f3f6d9f989ab4ed/src/BloomExe/Book/Book.cs#L4570)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Do we know the URL? Should we add that to the message?
</blockquote></details>

This was just a refactor; but yes, that's a good idea!

**Review by hatton — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5685)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5685)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Comment by hatton** [comment]
Just has some conflicts now.

**Pull request merged**
