### PR TITLE
Dialogs on joining team collection (BL-9486)

### PR DESCRIPTION
**Pull request by JohnThomson**
Also implements the special merge behavior

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194)

### CODE REVIEW

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194)* status: 0 of 20 files reviewed, 1 unresolved discussion

___
*[src/BloomTests/TeamCollection/SyncAtStartupTests.cs, line 12 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194#-MTb9WUg14t0APm8RTSO:-MTb9WUg14t0APm8RTSP:bm99e2o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f32cac95fa9c05b5630ae9155818895f8ed8377a/src/BloomTests/TeamCollection/SyncAtStartupTests.cs#L12)):*
> ```Smalltalk
> using SIL.IO;
> 
> namespace BloomTests.TeamCollection
> ```

These tests are unchanged from the ones removed from TeamCollectionTests, except where FirstTimeJoin() is called, and the overrides in the new SyncAtStartupNewTests subclass.

**Comment by JohnThomson** [comment]
Don't merge yet. Giving the local and shared collections different names causes various complications.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194)* status: all files reviewed, 7 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/react_components/ExclaimTriangle.tsx, line 53 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194#-MTbBt2C0KrfKo1rT-ib:-MTbBt2D4S2VaD8kSH10:b-g76sla) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f32cac95fa9c05b5630ae9155818895f8ed8377a/src/BloomBrowserUI/react_components/ExclaimTriangle.tsx#L53)):*
> ```XML
>         //     />
>         //     <circle fill={props.exclaimColor} cy="430.8" cx="313.9" r="30.7" />
>         // </svg>
> ```

Any reason to keep the commented part?
___
*[src/BloomBrowserUI/teamCollection/NewTeamCollection.less, line 4 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194#-MTbRmPa2k_hi60kDnTP:-MTbRmPa2k_hi60kDnTQ:br2pjzy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f32cac95fa9c05b5630ae9155818895f8ed8377a/src/BloomBrowserUI/teamCollection/NewTeamCollection.less#L4)):*
> ```Less
> 
> // Note: because the IndependentProgressDialog.tsx is in the same webpack module and imports
> // IndependentProgressDialog.less, those styles also apply, so beware of unexpected interference.
> ```

Let's just wrap this whole thing in 
`#new-team-collection-screen {}` and do something similar for IndependentProgressDialog. Else we're asking for bugs.
___
*[src/BloomBrowserUI/teamCollection/NewTeamCollection.tsx, line 8 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194#-MTbUS_04OZN0mLzh3Cl:-MTbUS_1DxTO4scSN2gm:b3pb5bd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f32cac95fa9c05b5630ae9155818895f8ed8377a/src/BloomBrowserUI/teamCollection/NewTeamCollection.tsx#L8)):*
> ```XML
> import "./NewTeamCollection.less";
> 
> // A device for getting its code into the team collection module
> ```

This is also in TeamCollectionSettings. Do we really need it in both places?
If it is needed here, we should re-organize these imports/exports.
___
*[src/BloomBrowserUI/teamCollection/NewTeamCollection.tsx, line 33 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194#-MTbUmSg82vNHJIei6NI:-MTbUmSg82vNHJIei6NJ:b4e4w8y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f32cac95fa9c05b5630ae9155818895f8ed8377a/src/BloomBrowserUI/teamCollection/NewTeamCollection.tsx#L33)):*
> ```XML
>                     className="join-heading"
>                     l10nKey="TeamCollection.JoinHeading"
>                     l10nParam0={collectionName}
> ```

You can now add `temporarilyDisableI18nWarning={true}` to these.
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 117 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194#-MTbU2757f9513A-dtVb:-MTbU2757f9513A-dtVc:b-hppsbe) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f32cac95fa9c05b5630ae9155818895f8ed8377a/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L117)):*
> ```Smalltalk
> 				}
> 
> 				var sharingFolder = dlg.SelectedPath;
> ```

Worth commenting here or at least changing the variable name to indicate they are choosing a parent-level directory?
___
*[src/BloomTests/BloomTests.csproj, line 107 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194#-MTbRVbl95tqH1jjMIRk:-MTbRVbl95tqH1jjMIRl:b-tqgvod) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f32cac95fa9c05b5630ae9155818895f8ed8377a/src/BloomTests/BloomTests.csproj#L107)):*
> ```XML
>     <Reference Include="dotMemory.Unit, Version=111.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325, processorArchitecture=MSIL">
>       <HintPath>..\..\packages\JetBrains.dotMemoryUnit.3.1.20200127.214830\lib\net35\dotMemory.Unit.dll</HintPath>
>     </Reference>
> ```

This must be a mistake?

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194)* status: all files reviewed, 8 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 299 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194#-MTb_9rGDOFGcYEz_geo:-MTb_9rGDOFGcYEz_gep:b-9l13ht) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b5dd8ea3325a9481173e47f8a6ddb6a91501b7b2/src/BloomExe/TeamCollection/TeamCollection.cs#L299)):*
> ```Smalltalk
> 		/// <param name="parentFolder"></param>
> 		/// <returns></returns>
> 		public static string CollectionPath(string parentFolder)
> ```

I don't think this needs to be static.
Then GetLocalCollectionNameFromTcName can be non-static and can easily be implemented in FolderTeamCollection, I think, as an override of the base one which would just return its input.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/react_components/ExclaimTriangle.tsx, line 53 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194#-MTbBt2C0KrfKo1rT-ib:-MTbZQOqC1L8zaPICESw:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f32cac95fa9c05b5630ae9155818895f8ed8377a/src/BloomBrowserUI/react_components/ExclaimTriangle.tsx#L53)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Any reason to keep the commented part?
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/teamCollection/NewTeamCollection.less, line 4 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194#-MTbRmPa2k_hi60kDnTP:-MTbaL9I5BBFaU_1Pcjt:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f32cac95fa9c05b5630ae9155818895f8ed8377a/src/BloomBrowserUI/teamCollection/NewTeamCollection.less#L4)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's just wrap this whole thing in 
`#new-team-collection-screen {}` and do something similar for IndependentProgressDialog. Else we're asking for bugs.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/teamCollection/NewTeamCollection.tsx, line 8 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194#-MTbUS_04OZN0mLzh3Cl:-MTbcr6U8e7oBxHA07NI:bj7pndj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f32cac95fa9c05b5630ae9155818895f8ed8377a/src/BloomBrowserUI/teamCollection/NewTeamCollection.tsx#L8)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This is also in TeamCollectionSettings. Do we really need it in both places?
If it is needed here, we should re-organize these imports/exports.
</blockquote></details>

Not needed in both places. Even so it's a bit kludgy. Alternatives would include making a root file whose purpose is just to import everything we want in the team collection module, or writing a more complex webpack rule to tell it what files we want in the module. If we get any more 'root of a document" files we probably should do one or the other.
___
*[src/BloomBrowserUI/teamCollection/NewTeamCollection.tsx, line 33 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194#-MTbUmSg82vNHJIei6NI:-MTbb9UE0TFWR64poRJm:b-anmy47) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f32cac95fa9c05b5630ae9155818895f8ed8377a/src/BloomBrowserUI/teamCollection/NewTeamCollection.tsx#L33)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

You can now add `temporarilyDisableI18nWarning={true}` to these.
</blockquote></details>

Done where not using L10nParam0. Unfortunately it breaks those.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 299 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194#-MTb_9rGDOFGcYEz_geo:-MTbmqCFDDK12QSWOyH3:bqj30ly) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b5dd8ea3325a9481173e47f8a6ddb6a91501b7b2/src/BloomExe/TeamCollection/TeamCollection.cs#L299)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't think this needs to be static.
Then GetLocalCollectionNameFromTcName can be non-static and can easily be implemented in FolderTeamCollection, I think, as an override of the base one which would just return its input.
</blockquote></details>

Unfortunately the callers of  GetLocalCollectionNameFromTcName are necessarily static, being involved in the creation of local team collections which need to exist before we can make an instance of the class. I've tried to improve the comment.
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 117 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194#-MTbU2757f9513A-dtVb:-MTbblQwA-EvVzbCj9vs:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f32cac95fa9c05b5630ae9155818895f8ed8377a/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L117)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Worth commenting here or at least changing the variable name to indicate they are choosing a parent-level directory?
</blockquote></details>

Done.
___
*[src/BloomTests/BloomTests.csproj, line 107 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194#-MTbRVbl95tqH1jjMIRk:-MTbphyQ4DiWY9LHt1hN:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f32cac95fa9c05b5630ae9155818895f8ed8377a/src/BloomTests/BloomTests.csproj#L107)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This must be a mistake?
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194)* status: all files reviewed, 1 unresolved discussion

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 299 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194#-MTb_9rGDOFGcYEz_geo:-MTc23wQ-LgFmUzIAVrP:bx5g7mm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b5dd8ea3325a9481173e47f8a6ddb6a91501b7b2/src/BloomExe/TeamCollection/TeamCollection.cs#L299)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Unfortunately the callers of  GetLocalCollectionNameFromTcName are necessarily static, being involved in the creation of local team collections which need to exist before we can make an instance of the class. I've tried to improve the comment.
</blockquote></details>

I think we agreed that this method doesn't need to be static, but I guess you're saying the other callers must be.

**Review by andrew-polk — APPROVED** [review]
> Dismissed @JohnThomson from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4194)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
