### PR TITLE
Do not change image container size for border in edit mode (BL-10268)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4675)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4675)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.less, line 10 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4675#-Mh_daaq44OWqtofhbp6:-Mh_daaq44OWqtofhbp7:bjmjofi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/133c9050891edc76b90b394d4a3917a9c1a492c7/src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.less#L10)):*
> ```Less
>     background-color: @dark;
>     .bloom-editable,
>     div.bloom-imageContainer:after {
> ```

These additions to the `*Comic Book.less` files are not necessary for this fix but bring consistency such that now the border colors of imageContainers are always the same as the border color of text boxes.

**Review by JohnThomson — APPROVED** [review]
LGTM but a couple of suggestions to consider.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4675#-:-MhnHxj5ATdTznzXylgQ:b-77k5g1)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.less, line 10 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4675#-Mh_daaq44OWqtofhbp6:-MhnGKBJEK7ujbbksb0p:b-dbyk6p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/133c9050891edc76b90b394d4a3917a9c1a492c7/src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.less#L10)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

These additions to the `*Comic Book.less` files are not necessary for this fix but bring consistency such that now the border colors of imageContainers are always the same as the border color of text boxes.
</blockquote></details>

While you've found all the places where we need to fiddle with border colors and related stuff, would it be worth making another macro, something like .borderOnTopOfElementColor?
It would also be nice to somehow capture the idea "this has to be more specific than what triggers .borderOnTopOfElement" but I'm not sure how...maybe at least a comment on the new macro?
___
*[src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.less, line 27 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4675#-MhnG9s394g8jpZWuyJk:-MhnG9s394g8jpZWuyJl:ba3y74z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/133c9050891edc76b90b394d4a3917a9c1a492c7/src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.less#L27)):*
> ```Less
>     div.bloom-editable,
>     div.bloom-imageContainer:after {
>         border: thin solid white;
> ```

Of course you're not changing this, but why is this border 'thin' and most of the others 1px?

**Review by andrew-polk — COMMENTED** [review]
Sorry; the refactoring makes this very difficult to see what I've changed. Can discuss if helpful.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4675#-:-MhoEuOpBQZyoWnaI7ZX:bxq1cqf)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.less, line 10 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4675#-Mh_daaq44OWqtofhbp6:-Mho5RiV0kXxidcvTqrF:b-bjzwn5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/133c9050891edc76b90b394d4a3917a9c1a492c7/src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.less#L10)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

While you've found all the places where we need to fiddle with border colors and related stuff, would it be worth making another macro, something like .borderOnTopOfElementColor?
It would also be nice to somehow capture the idea "this has to be more specific than what triggers .borderOnTopOfElement" but I'm not sure how...maybe at least a comment on the new macro?
</blockquote></details>

As we discussed, we lose the commonality of the color being applied to both selectors that way, so we're going to leave this as is and add a comment to point to the mixin.
___
*[src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.less, line 27 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4675#-MhnG9s394g8jpZWuyJk:-Mhno9ItDHhOqr9ZBsFQ:b-gn7rkt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/133c9050891edc76b90b394d4a3917a9c1a492c7/src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.less#L27)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Of course you're not changing this, but why is this border 'thin' and most of the others 1px?
</blockquote></details>

I don't know. 
Notice that when making the macro, I had to choose one or the other. Previously, one was 1px, and one was thin. I went with 1px simply because it seemed to be more common in our less.
I was going on the assumption that it doesn't really matter and that we had randomly used one or the other. If you think that isn't a good assumption, I can try to investigate more.

As we discussed, we believe this is ok as is.

**Review by andrew-polk — COMMENTED** [review]
Or I could probably break the change into two commits.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4675#-:-MhoF5Rg1Lpmjb5S4HEJ:bw3b22d)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by JohnThomson — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4675)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
