### PR TITLE
BL-3335 Make ReaderToolsModel fully global

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1053)

### CODE REVIEW

**Comment by hatton** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1053)*

**Comment by hatton** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, line 1152 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1053#-KHNDUueT9a-TyM9MYHe:-KHNDUueT9a-TyM9MYHf:737715264) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8d9d75558ef69ff0f540b2847ce2eb7733efdb25/src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts#L1152)):*
> ```XML
> // Note: if at some point we load this code into more than one iframe, we probably need to do
> // something to make sure they both use the same instance
> export var theOneReaderToolsModel = new ReaderToolsModel();
> ```

We could do that by changing this to a function, so that you say

    getReaderToolsModel().setAllowedWordList()

and that could be something like

export getReaderToolsModel(): ReaderToolsModel {
     return (<any>top).theOneReaderToolsModel;

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1053)*

**Comment by JohnThomson** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, line 1152 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1053#-KHNDUueT9a-TyM9MYHe:-KHPwIBN_W2qB3a7yrKh:-956998511) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8d9d75558ef69ff0f540b2847ce2eb7733efdb25/src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts#L1152)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary>
> We could do that by changing this to a function, so that you say
> 
>     getReaderToolsModel().setAllowedWordList()
> 
> and that could be something like
> 
> export getReaderToolsModel(): ReaderToolsModel {
>      return (<any>top).theOneReaderToolsModel;</details>
Should we make that change now? Just expand the comment to note it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1053)*

**Comment by hatton** [comment]
Reviewed 8 of 8 files at r2.
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1053)*

**Pull request merged**
