### PR TITLE
BL-5741 Created a reusable color chooser component

### PR DESCRIPTION
**Pull request by weagale**
* Created a reusable color chooser component

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2279)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.css, line 1 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2279#-L7euhfv997jt7sl6pgC:-L7euhfv997jt7sl6pgD:by8fhs2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/650bb599a0c5a61c44476ee20341febe296189f8/src/BloomBrowserUI/publish/android/androidPublishUI.css#L1)):*
> ```CSS
> a:hover {
> ```

I'm pretty sure this file should not be committed as it is generated from less during the build process.
Same for colorChooser.css

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 119 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2279#-L7ewytRqlZfswyqQizR:-L7ewytRqlZfswyqQizS:b8xlcm4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/650bb599a0c5a61c44476ee20341febe296189f8/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L119)):*
> ```XML
>             "#B2CC7D", "#F8B576", "#D29FEF", "#ABB8C3", "#C1EF93", "#FFD4D4", "#FFAAD4"];
>         return (
>             <div id="androidPublishReactRoot" /*onFocus={(e) => this.somethingFocused(e)} onClick={(e) => this.somethingFocused(e)}*/>
> ```

If this isn't needed, let's remove it.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 131 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2279#-L7ewFSMBZDG0r2psjzf:-L7ewFSMBZDG0r2psjzg:b-l5rsjq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/650bb599a0c5a61c44476ee20341febe296189f8/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L131)):*
> imagePath

I'm not seeing the benefit of passing this in rather than setting it inside the component.
Same for colorsVisibleByDefault.
Same for colorPalette.
Same for onColorChanged.

---

*[src/BloomBrowserUI/react_components/colorChooser.tsx, line 4 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2279#-L7evQQBtZJmdp5ZF3_v:-L7evQQBtZJmdp5ZF3_w:b97b9pz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/650bb599a0c5a61c44476ee20341febe296189f8/src/BloomBrowserUI/react_components/colorChooser.tsx#L4)):*
> ```XML
> import * as React from "react";
> import * as ReactDOM from "react-dom";
> import ContentEditable from "./ContentEditable";
> ```

Based on what I saw online, I thought I saw that you could import the css here. That would make the css automatically get linked in when using the component rather than having to add explicit references to it (such as in androidPublishUI.html).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2279)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomBrowserUI/react_components/colorChooser.tsx, line 4 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2279#-L7evQQBtZJmdp5ZF3_v:-L7fY-FmPzNVzsBUX_km:b-hthp1g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/650bb599a0c5a61c44476ee20341febe296189f8/src/BloomBrowserUI/react_components/colorChooser.tsx#L4)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Based on what I saw online, I thought I saw that you could import the css here. That would make the css automatically get linked in when using the component rather than having to add explicit references to it (such as in androidPublishUI.html).
</blockquote></details>

I think you'd need to add a less-loader in webpack.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2279)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomBrowserUI/react_components/colorChooser.tsx, line 4 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2279#-L7evQQBtZJmdp5ZF3_v:-L7ilUnPMWLIf5nggFvk:b10qhan) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/650bb599a0c5a61c44476ee20341febe296189f8/src/BloomBrowserUI/react_components/colorChooser.tsx#L4)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think you'd need to add a less-loader in webpack.
</blockquote></details>

Ok. Not knowing how much work that is, I won't ask for it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2279)*

**Comment by weagale** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.css, line 1 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2279#-L7euhfv997jt7sl6pgC:-L7iqakAOsdD_PzH9LHD:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/650bb599a0c5a61c44476ee20341febe296189f8/src/BloomBrowserUI/publish/android/androidPublishUI.css#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm pretty sure this file should not be committed as it is generated from less during the build process.
Same for colorChooser.css
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 119 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2279#-L7ewytRqlZfswyqQizR:-L7itN7GINFhGm-42nrO:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/650bb599a0c5a61c44476ee20341febe296189f8/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L119)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If this isn't needed, let's remove it.
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 131 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2279#-L7ewFSMBZDG0r2psjzf:-L7itfVZSX5OuzM2xeWz:bo9yx6b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/650bb599a0c5a61c44476ee20341febe296189f8/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L131)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> imagePath

I'm not seeing the benefit of passing this in rather than setting it inside the component.
Same for colorsVisibleByDefault.
Same for colorPalette.
Same for onColorChanged.
</blockquote></details>

The thought here was to make the color chooser more adaptable in it's re-usability.  Do you want to be locked into the same color palette wherever you use it or send a different array of colors?  Do you want the color chooser to display automatically or be clicked on to appear?  Do you want to be locked into the "/bloom/api/publish/android/backColor"  somewhere else where this might be used?  That was the thought.  

---

*[src/BloomBrowserUI/react_components/colorChooser.tsx, line 4 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2279#-L7evQQBtZJmdp5ZF3_v:-L7ivSFnggBTe_JNOGfA:b-locel6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/650bb599a0c5a61c44476ee20341febe296189f8/src/BloomBrowserUI/react_components/colorChooser.tsx#L4)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Ok. Not knowing how much work that is, I won't ask for it.
</blockquote></details>

Ok thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2279)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 3 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 131 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2279#-L7ewFSMBZDG0r2psjzf:-L7j3IWJ8FMLW-VNLiPU:b-v2lwbw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/650bb599a0c5a61c44476ee20341febe296189f8/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L131)):*
<details><summary><i>Previously, weagale (WendyG) wrote…</i></summary><blockquote>

The thought here was to make the color chooser more adaptable in it's re-usability.  Do you want to be locked into the same color palette wherever you use it or send a different array of colors?  Do you want the color chooser to display automatically or be clicked on to appear?  Do you want to be locked into the "/bloom/api/publish/android/backColor"  somewhere else where this might be used?  That was the thought.  
</blockquote></details>

Hm. Okay, good point. Let me think some more. But I think we would at least want a default implementation of most of these so the client doesn't *have* to provide them.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2279)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2279)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 131 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2279#-L7ewFSMBZDG0r2psjzf:-L7j5Jgr0F7gC6GiXRXW:b8mr7iq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/650bb599a0c5a61c44476ee20341febe296189f8/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L131)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Hm. Okay, good point. Let me think some more. But I think we would at least want a default implementation of most of these so the client doesn't *have* to provide them.
</blockquote></details>

The motivation for this issue wasn't reusability. We're just trying to have clean code organization. But it's good to think about of course. I would say it would not be justifiable to expend effort/complexity make it reusable in other apps, when we have no other apps to use it. So it would not be justifiable to, for example, have the color pallet come in from props. You could probably justify designing for reusability *within* Bloom, as it would make sense to offer this in other context than just publish to Android. In those other within-Bloom contexts, this control would not have a different pallet. However, we can apply the agile principle of YAGNI even there, because  we don't have a design for elsewhere, so we don't even know what the requirements would be.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2279)*

**Comment by weagale** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 131 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2279#-L7ewFSMBZDG0r2psjzf:-L7jYsLZ-a--pGE1BOfS:b-ms0gy2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/650bb599a0c5a61c44476ee20341febe296189f8/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L131)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

The motivation for this issue wasn't reusability. We're just trying to have clean code organization. But it's good to think about of course. I would say it would not be justifiable to expend effort/complexity make it reusable in other apps, when we have no other apps to use it. So it would not be justifiable to, for example, have the color pallet come in from props. You could probably justify designing for reusability *within* Bloom, as it would make sense to offer this in other context than just publish to Android. In those other within-Bloom contexts, this control would not have a different pallet. However, we can apply the agile principle of YAGNI even there, because  we don't have a design for elsewhere, so we don't even know what the requirements would be.
</blockquote></details>

I put some defaults in there.  

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2279)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 131 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2279#-L7ewFSMBZDG0r2psjzf:-L7jtRrp8Ei8uslEtR8N:bhtdvlz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/650bb599a0c5a61c44476ee20341febe296189f8/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L131)):*
<details><summary><i>Previously, weagale (WendyG) wrote…</i></summary><blockquote>

I put some defaults in there.  
</blockquote></details>

Thanks. Now lets clean up androidPublishUI by allowing it to call without having to pass in the defaults.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2279)*

**Comment by weagale** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 131 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2279#-L7ewFSMBZDG0r2psjzf:-L7kKTzACGQ9LaoRzfYE:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/650bb599a0c5a61c44476ee20341febe296189f8/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L131)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Thanks. Now lets clean up androidPublishUI by allowing it to call without having to pass in the defaults.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2279)*

**Comment by weagale** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 131 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2279#-L7ewFSMBZDG0r2psjzf:-L7l7pCYBWzyjLiUYIsX:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/650bb599a0c5a61c44476ee20341febe296189f8/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L131)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

And delete the colors array, please.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2279)*

**Comment by andrew-polk** [comment]
*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 131 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2279#-L7ewFSMBZDG0r2psjzf:-L7ylDqo-S-VzvF-PaUm:b-qkf4d0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/650bb599a0c5a61c44476ee20341febe296189f8/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L131)):*
<details><summary><i>Previously, weagale (WendyG) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not seeing this change. Did you forget to push?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2279)*

**Comment by weagale** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 131 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2279#-L7ewFSMBZDG0r2psjzf:-L83c99YqziHoDwlrWfX:bwqzjhh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/650bb599a0c5a61c44476ee20341febe296189f8/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L131)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Not seeing this change. Did you forget to push?
</blockquote></details>

I probably didn't push it but I believe I have now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2279)*

**Comment by andrew-polk** [comment]
*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 131 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2279#-L7ewFSMBZDG0r2psjzf:-L83igqdA8EGpPYr21kZ:b6qh9ii) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/650bb599a0c5a61c44476ee20341febe296189f8/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L131)):*
<details><summary><i>Previously, weagale (WendyG) wrote…</i></summary><blockquote>

I probably didn't push it but I believe I have now.
</blockquote></details>

Your last push showed up but doesn't seem to have changed any code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2279)*

**Comment by weagale** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/publish/android/androidPublishUI.tsx, line 131 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2279#-L7ewFSMBZDG0r2psjzf:-L845fUNCxXDIHai7tWy:b-gtd6yk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/650bb599a0c5a61c44476ee20341febe296189f8/src/BloomBrowserUI/publish/android/androidPublishUI.tsx#L131)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Your last push showed up but doesn't seem to have changed any code.
</blockquote></details>

Ok, that̀s weird.  I redid the two little edits, and pushed again.  Would you mind seeing if you see them now?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2279)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2279#-:-L846wAS4tQauh-Liwxk:bnfp4nl)*

**Pull request merged**
