### PR TITLE
BL-5745 Fix mouse zoom

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2563)

### CODE REVIEW

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2563)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 1026 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2563#-LGl8swj7Xa7ohDaazvt:-LGl8swk56OYMH_uoH7n:bj3kd2e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2688facc644e1980ac0682f8b15f7fd8bc2639a3/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L1026)):*
> ```XML
>         // Note the direction of the zoom is opposite the direction of the scroll.
>         if (theEvent.deltaY < 0) {
>             command = "/bloom/api/edit/pageControls/zoomPlus";
> ```

I'm finding it very hard to figure out why this goes all the way back to the server to do the zoom. I look at the c# code and see properties that actually are methods, leading to events that just shift other properties... sigh.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2563)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 1026 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2563#-LGl8swj7Xa7ohDaazvt:-LGl9jSQAAMaitkmIYII:b-7cbf1u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2688facc644e1980ac0682f8b15f7fd8bc2639a3/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L1026)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I'm finding it very hard to figure out why this goes all the way back to the server to do the zoom. I look at the c# code and see properties that actually are methods, leading to events that just shift other properties... sigh.
</blockquote></details>

What is the point of having an interface for one property, implemented by one class?  IZoomManager.

By the way, I never could find out where the zoom *happens*. Just a maze of interfaces, properties, events... surely it does something to reload the page eventually, but I gave up. Sure it can't be this complicated, requiring this many files, to simply change and remember one integer?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2563)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 1026 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2563#-LGl8swj7Xa7ohDaazvt:-LGlUwMaDV1JnzFHbKAF:bv75fd2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2688facc644e1980ac0682f8b15f7fd8bc2639a3/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L1026)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

What is the point of having an interface for one property, implemented by one class?  IZoomManager.

By the way, I never could find out where the zoom *happens*. Just a maze of interfaces, properties, events... surely it does something to reload the page eventually, but I gave up. Sure it can't be this complicated, requiring this many files, to simply change and remember one integer?
</blockquote></details>

Some of the complication comes because the zoom control is in a shared toolbar, though currently hidden except for the edit tab. The interface potentially allows EditingView, PublishView, and whatever view occupies that space in the collection tab to each implement zoom, although only EditingView actually does at present. (The toolbar code asks each of them whether they implement it, though only one does. I guess a YAGNI violation, but the code needed some way to figure out whether the current main control could handle zoom).
And some of it is historical...the C# code was mostly written on the assumption that we were getting rid of mouse-wheel zooming and zoom would all be handled from C#, but users complained. And then along came text-over-picture which somehow made it necessary for zoom to reload the page...
The page reload now happens in EditingView's implementation of the Zoom setter in its implementation of IZoomManager. I thought I had at least improved things somewhat compared to having a property invoke javascript code which in turn invoked a server call to reload the page containing it. That gets rid of one whole cycle of C# calling JS calling C# :-)
No doubt there's room for more improvement. Making the Zoom setter a method would probably be a good next step.

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2563)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 1026 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2563#-LGl8swj7Xa7ohDaazvt:-LGllJbp-RUOn07pD415:bm7oml1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2688facc644e1980ac0682f8b15f7fd8bc2639a3/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L1026)):*
> Making the Zoom setter a method would probably be a good next step.

I support it. Let's do it. It's not realistic to think we can "make a card" to pay down every bit of entropy we encounter; better to just fix them when we or a reviewer notice them (within reason).

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2563)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 1026 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2563#-LGl8swj7Xa7ohDaazvt:-LGzLRk9DbDG1wpAjqWe:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2688facc644e1980ac0682f8b15f7fd8bc2639a3/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L1026)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

> Making the Zoom setter a method would probably be a good next step.

I support it. Let's do it. It's not realistic to think we can "make a card" to pay down every bit of entropy we encounter; better to just fix them when we or a reviewer notice them (within reason).
</blockquote></details>

Done.

**Pull request merged**
