### PR TITLE
Bl 2949reorganize toolbox

### PR DESCRIPTION
**Pull request by JohnThomson**
This is a fairly massive change. I think it is probably easiest to review one commit at a time. Most of them have helpful descriptions. The first commit does not. If I could figure out how to revise that one description, it would indicate that this begins the process by making a typescript file for the toolbox as a whole (previously just javascript) and one for each tool, and removing explicit knowledge of individual tools from the code that manages the toolbox as a whole.
The other changes progressively reorganize the toolbox-related code. The overall objective is to gather knowledge about the toolbox and its tools into the appropriate places and remove it from everywhere else. Appropriate places are considered to be:
- BloomBrowserUI/bookEdit/toolbox for anything in js/ts/html/jade/css/less etc land. The root folder should not have knowledge of individual tools, except that the main jade and html files know what components to include. Each tool has its own folder. Partly because of their close relationship, and partly still for historical reasons, some code in the decodableReader folder still deals with aspects of the leveledReader tool.
- ToolBoxTool and a subclass for each tool for CS code involved in the tool implementations
- ReadersHandler.cs for aspects of our local webserver that relate to the toolbox (maybe this should be renamed ToolboxHandler? But so far I think they are all for the reader tools.)
- There are still a few spots where other code is aware of the reader tools. LibraryListView manages a toolstrip menu item for making a 'Reader' Bloompack, and the Bloompack creation code has some special case code for making such a bloompack. EnhancedImageServer knows to initialize ReadersHandler and delegate requests starting with 'reader'. I haven't found a good way to improve these further.

[Review on Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/891)

### CODE REVIEW

**Comment by JohnThomson** [comment]
When we merge this, we can remove the TC dependency on libpalaoso. I've so far only manually edited the getDependencies scripts; once we update TC we could possibly regenerate them.

**Comment by hatton** [comment]
Reviewed 13 of 16 files at r1.
Review status: 0 of 85 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/decodableReader.ts, line 4 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yQ-VdsKgZ2C0G40oy:-K4yQ-VdsKgZ2C0G40oz:-849846801) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9fd495e0bc5b282d80d3743a2019286774f4dc56/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/decodableReader.ts#L4)):*
Could we spell out "options" instead? But probably if the method is ```restoreSettings```, the parameter wants to be ```settings```.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891)*

**Comment by hatton** [comment]
Reviewed 3 of 16 files at r1, 7 of 7 files at r2, 40 of 41 files at r3.
Review status: 21 of 85 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/Book.cs, line 295 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yT3gM5jukiijaqBoV:-K4yT3gM5jukiijaqBoW:739016567) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9856e1e83f4ed71f73394581e668993ed8e083b1/src/BloomExe/Book/Book.cs#L295)):*
I'm surprised that the Book class ever, but especially now, has knowledge of what javascript the reader tools need.

Earlier today I started a new toolbox component and didn't like that I had to add its javascript somewhere else. I wanted to be able to just add a normal ```<script>``` element in its ```<head>```.  

The following addition to EditingModel.AppendToolboxPanel() was enough for a single file inclusion:
```	var scriptInHead = subPanelDom.Head.SelectSingleNode("script");
			if (scriptInHead != null)
			{
				var scriptElement = subPanelDom.RawDom.CreateElement("script");
				var path = scriptInHead.GetStringAttribute("src");
				// use jquery getScript to dynamically load the script
                scriptElement.InnerText =
					"$.getScript('"+ path+"').done(function() {}).fail(function() {alert('failed to load "+ path+"')});";
				subPanelDom.Body.AppendChild(scriptElement);
			}```

Could that approach be used here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891)*
<!-- Sent from Reviewable.io -->

**Comment by hatton** [comment]
Reviewed 1 of 41 files at r3.
Review status: 21 of 85 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891)*

**Comment by hatton** [comment]
Reviewed 28 of 32 files at r4.
Review status: 40 of 85 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891)*

**Comment by hatton** [comment]
Reviewed 4 of 32 files at r4.
Review status: 40 of 85 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891)*

**Comment by hatton** [comment]
Reviewed 3 of 3 files at r5, 8 of 13 files at r6.
Review status: 48 of 85 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/BloomExe/Collection/BloomPack/BloomPackInstallDialog.cs, line 224 \[r5\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4ycTNZnqKrzJiyoiUO:-K4ycTNZnqKrzJiyoiUP:-362948200) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e08aa02d0d91e3d1cfacd9fd550a06ab03913b03/src/BloomExe/Collection/BloomPack/BloomPackInstallDialog.cs#L224)):*
this is so much better

---

*[src/BloomExe/Edit/DecodableReaderTool.cs, line 58 \[r6\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yd18Z4Jkutx7xkW2h:-K4yd18Z4Jkutx7xkW2i:705597108) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3b646d143f66f1a2bb392194891387448a7045fc/src/BloomExe/Edit/DecodableReaderTool.cs#L58)):*
Would it do this for arbitrary languages? Or just English? If the later, I think that was by design and we want to retain the ability to push out improved English examples.

Similarly, we would *like* to be able to push out new defaults for other languages but of course not touch their settings once they have modified them.

---

*[src/BloomExe/Edit/ToolboxTool.cs, line 97 \[r6\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yf-AKYYAhs8adSToZ:-K4yf-AKYYAhs8adSTo_:504430497) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3b646d143f66f1a2bb392194891387448a7045fc/src/BloomExe/Edit/ToolboxTool.cs#L97)):*
If the intent here is to set up this one tool, and not the entire toolbox, should this instead be SetupToolForCollection?

---

*[src/BloomExe/Edit/ToolboxTool.cs, line 106 \[r6\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yfaCbQLoMXAEMCHYb:-K4yfaCbQLoMXAEMCHYc:1721874977) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3b646d143f66f1a2bb392194891387448a7045fc/src/BloomExe/Edit/ToolboxTool.cs#L106)):*
Hmm. Again I'm confused here because this seems to be putting toolbox functionality in what is the base class of each tool.  Instead I would recommend an "ToolboxView" class for this stuff.s

---

*[src/BloomExe/Program.cs, line 567 \[r6\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4ygJbwgCqCdzFmOSPN:-K4ygJbwgCqCdzFmOSPO:1061012203) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3b646d143f66f1a2bb392194891387448a7045fc/src/BloomExe/Program.cs#L567)):*
This needs a better home. The original, too, never belonged waaaaaaaaay up in program.cs.  At least one step down in the right direction would be _applicationContainer.CreateProjectContext()

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891)*

**Comment by hatton** [comment]
Reviewed 5 of 13 files at r6, 4 of 5 files at r7, 20 of 20 files at r8, 6 of 6 files at r9, 2 of 2 files at r10, 12 of 12 files at r11.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/editViewFrame.js, line 2 \[r8\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yqn60OrzvyJWE-Dw1:-K4yqn60OrzvyJWE-Dw2:296196432) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b429350e6b818dd15c9fd4b304a391ecd5f26491/src/BloomBrowserUI/bookEdit/js/editViewFrame.js#L2)):*
Any chance we can we get this stuff out of here and into the decodable reader code?

---

*[src/BloomBrowserUI/bookEdit/test/libsynphony/split_sentences.test.js, line 4 \[r11\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4ys6g_45mo4-4QmTmh:-K4ys6g_45mo4-4QmTmi:1380873368) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/070351d3db3d4b58c99120547a951d95cf05a27a/src/BloomBrowserUI/bookEdit/test/libsynphony/split_sentences.test.js#L4)):*
Maybe we should remove this :-)

---

*[src/BloomBrowserUI/bookEdit/test/libsynphony/split_sentences.test.js, line 6 \[r11\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4ysAXyst4sjruAAUad:-K4ysAXyst4sjruAAUae:1306230744) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/070351d3db3d4b58c99120547a951d95cf05a27a/src/BloomBrowserUI/bookEdit/test/libsynphony/split_sentences.test.js#L6)):*
I know you're just moving stuff around, but while we're in here... no reason to have some of our files naming who started it.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/libsynphony/jquery.text-markup.js, line 40 \[r11\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4ytY8nbELXBADrcIYS:-K4ytY8nbELXBADrcIYT:-1511763286) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/070351d3db3d4b58c99120547a951d95cf05a27a/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/libsynphony/jquery.text-markup.js#L40)):*
Do we have new unit tests that show what you're fixing here? I can't tell because all the tests look "new" in this commit. 

Am I correct in guessing that we're going to need a very thorough manual testing round?

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/libsynphony/jquery.text-markup.js, line 87 \[r11\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yt2hFl2g-ARlFSBIQ:-K4yt2hFl2g-ARlFSBIR:20372493) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/070351d3db3d4b58c99120547a951d95cf05a27a/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/libsynphony/jquery.text-markup.js#L87)):*
Why yes, yes I believe there is!  https://github.com/julianshapiro/blast

---

*[src/BloomExe/web/ReadersHandler.cs, line 46 \[r6\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yifhPOlt4SBRMdKEb:-K4yifhPOlt4SBRMdKEc:-1656673796) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3b646d143f66f1a2bb392194891387448a7045fc/src/BloomExe/web/ReadersHandler.cs#L46)):*
any reason this is broken out into property and member variable? Since it can never change, a simple public static would do.

---

*[src/BloomTests/Book/BookInfoTests.cs, line 92 \[r9\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yrKUOD0C5imjXUVGv:-K4yrKUOD0C5imjXUVGw:126788067) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7f9fabd0a6f1176b17562fe875bee41258ba5321/src/BloomTests/Book/BookInfoTests.cs#L92)):*
Do we need a test showing migration from the readerToolIsAvailable-->toolboxIsOpen?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891)*

**Comment by hatton** [comment]
Wow this is a milestone in reversing the contest-induced entropy that was making Bloom a sad place to work. Thanks so much for doing it, John.

---

Review status: all files reviewed at latest revision, 14 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-:-K4yu694I78XWJGdxA_7:1462689636)*

**Comment by JohnThomson** [comment]
Review status: 68 of 91 files reviewed at latest revision, 13 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/editViewFrame.js, line 2 \[r8\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yqn60OrzvyJWE-Dw1:-K521IFLsol0LL_Qsz60:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b429350e6b818dd15c9fd4b304a391ecd5f26491/src/BloomBrowserUI/bookEdit/js/editViewFrame.js#L2)):*
Done.

---

*[src/BloomBrowserUI/bookEdit/test/libsynphony/split_sentences.test.js, line 4 \[r11\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4ys6g_45mo4-4QmTmh:-K51LAc5Pv6_V0_cYTrm:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/070351d3db3d4b58c99120547a951d95cf05a27a/src/BloomBrowserUI/bookEdit/test/libsynphony/split_sentences.test.js#L4)):*
Done.

---

*[src/BloomBrowserUI/bookEdit/test/libsynphony/split_sentences.test.js, line 6 \[r11\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4ysAXyst4sjruAAUad:-K51LB4qxvKjvyv9wUVa:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/070351d3db3d4b58c99120547a951d95cf05a27a/src/BloomBrowserUI/bookEdit/test/libsynphony/split_sentences.test.js#L6)):*
Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/decodableReader.ts, line 4 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yQ-VdsKgZ2C0G40oy:-K51LPPSC4BZvOw0pO-h:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9fd495e0bc5b282d80d3743a2019286774f4dc56/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/decodableReader.ts#L4)):*
Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/libsynphony/jquery.text-markup.js, line 40 \[r11\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4ytY8nbELXBADrcIYS:-K51Ll_3U6LpagDO18vH:-1064618308) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/070351d3db3d4b58c99120547a951d95cf05a27a/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/libsynphony/jquery.text-markup.js#L40)):*
It's hard to know where to put this information, but the commit description does say, "Only change to libsynphony tests is new checkLeveledReader.handlesDivsWithEmbeddedParas in bookEdit\test\libsynphony\jquery.text-markup.test.js". That is intended to cover the fixes here; may be worth a look to see whether you think it adequate.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/libsynphony/jquery.text-markup.js, line 87 \[r11\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yt2hFl2g-ARlFSBIQ:-K521LJiAKsoNZAzXyDK:991526357) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/070351d3db3d4b58c99120547a951d95cf05a27a/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/libsynphony/jquery.text-markup.js#L87)):*
That looks as if it would involve a complete rewrite of the sentence-level code, no longer using synphony. It may be very good, though I don't know how well it handles non-Roman. But it feels beyond the scope of this change.

---

*[src/BloomExe/Book/Book.cs, line 295 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yT3gM5jukiijaqBoV:-K522V5Uk4gUXWwDbibX:1255299915) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9856e1e83f4ed71f73394581e668993ed8e083b1/src/BloomExe/Book/Book.cs#L295)):*
Hmmm...several reactions.
(1). All I did to this file was REMOVE the need for it to know anything about reader tools JS code. The fact that it still knows about editing JS feels out of scope.
(2). I'm not clear why it does NOT work to just put a <script> element in the HTML file for the tab itself, as long as the target is in the folder, or relative to it.
(3). I can't make sense of your code at all; my reading of the doc on getScript suggests that it returns a promise and needs to be used with a done function. I gather the idea is to run the JavaScript and append the result to the body. Supposing it works, why do you want to do that? Is this making up for the lack of a #include in html?
(4). As for as getting knowledge of JS out of Book, this method is only used as part of creating a DOM for a page, which is used in two places in EditingModel. One of those wants the DOM for the process of saving changes and probably doesn't want the JS. So I think it would make very good sense to move the responsibility for adding the JS to EditingModel.
(5). I don't see how the 10 lines you have there are better than the one line now in Book.cs, assuming they server a similar purpose.

Sorry, I think I'm missing your point somehow.

---

*[src/BloomExe/Edit/DecodableReaderTool.cs, line 58 \[r6\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yd18Z4Jkutx7xkW2h:-K529jBzMPazmgF1Wq2n:-1974953927) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3b646d143f66f1a2bb392194891387448a7045fc/src/BloomExe/Edit/DecodableReaderTool.cs#L58)):*
I've reinstated it, because you're right, it's language-dependent. Still worries me a bit...I wonder whether our new installer will put meaningful modify dates on the shipping settings files? If not it just might be a nuisance for someone actually working in English...

---

*[src/BloomExe/Edit/ToolboxTool.cs, line 97 \[r6\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yf-AKYYAhs8adSToZ:-K52YMw1ugkNjUJDQB8w:663738538) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3b646d143f66f1a2bb392194891387448a7045fc/src/BloomExe/Edit/ToolboxTool.cs#L97)):*
It so happens at this point that only one tool needs it. But the intent of the static method on the base class was that this would be the central method that knows what setup if any each tool wants. (That's why I didn't just have the wider code call the DecodableTool method directly). So I think the current name is right.

---

*[src/BloomExe/Edit/ToolboxTool.cs, line 106 \[r6\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yfaCbQLoMXAEMCHYb:-K52ZwStoUmPCiNeaJ90:-1664355803) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3b646d143f66f1a2bb392194891387448a7045fc/src/BloomExe/Edit/ToolboxTool.cs#L106)):*
OK, I moved most of the static Toolbox methods to a new ToolboxView class

---

*[src/BloomExe/Program.cs, line 567 \[r6\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4ygJbwgCqCdzFmOSPN:-K52_gwKMAzaOkdlFj1j:-2122947871) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3b646d143f66f1a2bb392194891387448a7045fc/src/BloomExe/Program.cs#L567)):*
Moved it to the ProjectContext constructor (all the Create method does is call that)

---

*[src/BloomExe/web/ReadersHandler.cs, line 46 \[r6\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yifhPOlt4SBRMdKEb:-K52_xCnSShR-KZXLxmp:1319274386) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3b646d143f66f1a2bb392194891387448a7045fc/src/BloomExe/web/ReadersHandler.cs#L46)):*
I originally had an assert to prevent changing it, since we depend on having only one image server (allowing this class to be static). But some of our test code does need to change it, so I had to take the assert out. Done.

---

*[src/BloomTests/Book/BookInfoTests.cs, line 92 \[r9\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yrKUOD0C5imjXUVGv:-K52mHOhOK3CjLw_r09w:1634055763) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7f9fabd0a6f1176b17562fe875bee41258ba5321/src/BloomTests/Book/BookInfoTests.cs#L92)):*
Not only a test, but code to make it happen :-)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891)*

**Comment by hatton** [comment]
Reviewed 23 of 23 files at r12.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Book/Book.cs, line 295 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yT3gM5jukiijaqBoV:-K56MMn2MCA4ljY0bedj:-752703148) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9856e1e83f4ed71f73394581e668993ed8e083b1/src/BloomExe/Book/Book.cs#L295)):*
your comment got cut off

---

*[src/BloomExe/Edit/DecodableReaderTool.cs, line 58 \[r6\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yd18Z4Jkutx7xkW2h:-K56PmNbwrhMq-D47kDI:-1236926647) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3b646d143f66f1a2bb392194891387448a7045fc/src/BloomExe/Edit/DecodableReaderTool.cs#L58)):*
yes, I don't see how the date checking here helps. We should probably either just say that English is always overwritten, or else do what is needed to know if they've changed the English settings themselves; I don't see how dates are going to tell us that. For this PR, only the former seems appropriate.

---

*[src/BloomExe/Edit/ToolboxView.cs, line 17 \[r12\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K56R0ro5A7rfCbZNSM5:-K56R0ro5A7rfCbZNSM6:-1428324293) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/56f9441b8f573ffbea5f2576b2db3f80ca13b8c9/src/BloomExe/Edit/ToolboxView.cs#L17)):*
Does this comment mean that these functions are unused, because they are duplicated in c#? Confused.xn

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Book/Book.cs, line 295 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yT3gM5jukiijaqBoV:-K56dkIq75EPFAnai0md:-68996050) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9856e1e83f4ed71f73394581e668993ed8e083b1/src/BloomExe/Book/Book.cs#L295)):*
Grrr. That was a long complex comment! OK, I'll see what I remember.
2. I'm not clear why it does NOT work to just put a script element in the toolbox HTML, as long as it has a suitable relative src/href.
3. I don't understand how your script works. It appears to be trying to function as an HTML 'include' by running the JavaScript and inserting the resulting HTML into the body, but I would have thought the AppendChild needed to be in a done function, because getScript returns a promise.
4. I'm not clear how your ten lines of JS would replace my one line of C#, or why it would be better if they did.
5. If we want to remove this knowledge of JS from Book, we can easily move it to EditingModel. This function is only used by the function that generates PageDoms, and that is used in only two places in EditingModel, and I think only one of those actually needs to insert the JS file.

---

*[src/BloomExe/Edit/DecodableReaderTool.cs, line 58 \[r6\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yd18Z4Jkutx7xkW2h:-K56c049m9j2CyP4ucg9:-380107132) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3b646d143f66f1a2bb392194891387448a7045fc/src/BloomExe/Edit/DecodableReaderTool.cs#L58)):*
I was just reinstating what we had before, since I was wrong that we would never want to overwrite. I don't recall what I originally had in mind (if it was me) with the date check. I don't know a more reliable way to tell whether they edited the settings themselves. For the future, I suppose we could write something in the file to indicate it was updated by the program? Any better idea?

---

*[src/BloomExe/Edit/ToolboxView.cs, line 17 \[r12\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K56R0ro5A7rfCbZNSM5:-K56cmAfozYdgRWN1cob:2005302748) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/56f9441b8f573ffbea5f2576b2db3f80ca13b8c9/src/BloomExe/Edit/ToolboxView.cs#L17)):*
No, they are used. I was just trying to explain why this class is just static methods, unlike our other View classes which subclass some kind of control and are instantiated as children of other controls. Toolbox is special in that it is mainly implemented in HTML land within the main browser window. Ideally it would probably be entirely in that world, but for now we need a bit of C# support to make it happen, so made this class as a place for it. Or if things develop in an unexpected direction and we need a C# control to represent the toolbox, this class would develop into it, I expect.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/Book.cs, line 295 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yT3gM5jukiijaqBoV:-K56nKSjgs0UzUd_dRRf:-508910355) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9856e1e83f4ed71f73394581e668993ed8e083b1/src/BloomExe/Book/Book.cs#L295)):*
I'm not clear about "my one line of c#"; what I'm saying is that the component html is the natural place to declare any stylesheets that it the component depends upon. Vs. what we have now is that when you add a component, you have to go to some other file (bloomBootstrap.js", which is outside of the component folder, to register your component and its dependencies. That makes it less-component-y.

---

*[src/BloomExe/Edit/ToolboxView.cs, line 17 \[r12\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K56R0ro5A7rfCbZNSM5:-K56oV5PwvUFDaLxR2M9:84114911) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/56f9441b8f573ffbea5f2576b2db3f80ca13b8c9/src/BloomExe/Edit/ToolboxView.cs#L17)):*
OK, so the source of my confusion is "holding place".  Would this comment capture what you're saying?

/// This class supports the Edit Tab Toolbox as a whole. Eventually, all of this should be moved to javascript-land.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/Book.cs, line 295 \[r3\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K4yT3gM5jukiijaqBoV:-K56qtSxESk6hnLdlOHY:402289648) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9856e1e83f4ed71f73394581e668993ed8e083b1/src/BloomExe/Book/Book.cs#L295)):*
Maybe we should talk. The "one line" I thought you were complaining about originally was " dom.AddJavascriptFile("bookEdit/js/bloomBootstrap.js".ToLocalhost()); I thought you wanted to get that out of Book.cs.
IIRC, bloomBootstrap.cs is for the main page frame. I already removed entirely the corresponding file for the toolbox frame, which we weren't using consistently anyway. At this point stylesheets and scripts needed by the toolbox are mostly loaded by the root toolbox html/jade file, but I don't see any reason an individual tool couldn't load its own. I can try to figure out which are only needed by particular tools and move them if you want.

---

*[src/BloomExe/Edit/ToolboxView.cs, line 17 \[r12\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891#-K56R0ro5A7rfCbZNSM5:-K56twWQevXJHny-10hA:1370783966) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/56f9441b8f573ffbea5f2576b2db3f80ca13b8c9/src/BloomExe/Edit/ToolboxView.cs#L17)):*
I'll start with that and maybe say a little more.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/891)*

**Pull request merged**
