### PR TITLE
Make Publish to Audio/Video tooltips dynamic (BL-10992)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5284)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5284)* status: 0 of 10 files reviewed, 1 unresolved discussion

___
*[`src/BloomExe/Publish/Video/PublishAudioVideoAPI.cs` line 272 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5284#-N6OGjCF5AQDoHUNVtli:-N6OGjCF5AQDoHUNVtlj:b-kcy71b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f074c3f7e0de2aa0a59775bb17216d479b939c37/src/BloomExe/Publish/Video/PublishAudioVideoAPI.cs#L272)):*
> ```Smalltalk
> 		public static bool ShouldRecordAsLandscape(Book.Book book, string format)
> 		{
> 			if (book.BookInfo.PublishSettings.AudioVideo.Motion)
> ```

This is part of commit 2 (you may want to review commit-by-commit) which makes Square books publish as landscape videos for YouTube, rather than portrait. (YouTube is much more of a landscape world)

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5284)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx` line 29 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5284#-N6OOiCF3PHh89qNEFu7:-N6O_3Kk7NFZcyRFaL85:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f074c3f7e0de2aa0a59775bb17216d479b939c37/src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx#L29)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think I would just go ahead and make this `codec?`. Seems more true to the way it is used.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx` line 193 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5284#-N6ONy1u8rwpeiMv1SiE:-N6Ob1su6a8xdSVMQuAx:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f074c3f7e0de2aa0a59775bb17216d479b939c37/src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx#L193)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Not a big deal, but things are a bit more future-proof if you call this function when setting up the initial state of formatItems above.
</blockquote></details>

Done.
___
*[`src/BloomExe/Utils/NumUtils.cs` line 12 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5284#-N6ON8sG4xJMGMBTnQsX:-N6OVsA7270eSaiHtXfw:beav023) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f074c3f7e0de2aa0a59775bb17216d479b939c37/src/BloomExe/Utils/NumUtils.cs#L12)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

comparison

If it doesn't already, you would probably benefit from configuring VS to highlight spelling errors in comments.
</blockquote></details>

Fixed, and also set up. Thanks for the tip!
___
*[`src/BloomTests/Publish/Video/ResolutionTests.cs` line 89 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5284#-N6OMax00y1CGh-nnbdh:-N6ObQlM-2uBm-ffUI9I:b8yo2vu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f074c3f7e0de2aa0a59775bb17216d479b939c37/src/BloomTests/Publish/Video/ResolutionTests.cs#L89)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Not necessarily suggesting you change them now that they're written, but for next time, all the `GetAspectRatio` tests above can be combined by providing an `ExpectedResult` in the test case. 
https://docs.nunit.org/articles/nunit/writing-tests/attributes/testcase.html
</blockquote></details>

I was thinking about passing it as a parameter at first, but resisted because I couldn't think of a good unit test name that would encapsulate all of them. I came up with one i liked now though.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5284)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5284)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Pull request merged**
