### PR TITLE
Allow the legacy theme to be disabled for some xmatters (13022)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/BookStorage.cs` line 3706 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280#-NpW1NGs4AcHRN6x2zjA:-NpW1NGs4AcHRN6x2zjB:bgvskuj) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/632cf1be83c82a67d2cb96cfb49fc00a0047acc3/src/BloomExe/Book/BookStorage.cs#L3706)):*
> ```Smalltalk
>                 )
>                 {
>                     // Even if we had reason to use legacy, such as customCSS, if legacy is disabled don't use it.
> ```

It seems odd that essentially the same check is in Appearance, Book, and Storage

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/BloomExe/Book/BookStorage.cs` line 3706 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280#-NpW1NGs4AcHRN6x2zjA:-Np_XF_55D2D6_-mdLTk:bfo0zwf) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/632cf1be83c82a67d2cb96cfb49fc00a0047acc3/src/BloomExe/Book/BookStorage.cs#L3706)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

It seems odd that essentially the same check is in Appearance, Book, and Storage
</blockquote></details>

I've made an attempt to reduce the duplication...see what you think.

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/AppearanceSettings.cs` line 163 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280#-Nq-8PGHBZFXMkGn1ENp:-Nq-8PGHBZFXMkGn1ENq:bb8xwge) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a5ea92d6c5c9ba0c3632c28f979b08585be2fa34/src/BloomExe/Book/AppearanceSettings.cs#L163)):*
> ```Smalltalk
>     /// </summary>
>     /// <param name="legacyDisabled"></param>
>     public void DisableLegacyTheme(bool legacyDisabled)
> ```

I find this name to be, like definitely do this thing, when that's not what it does. How about `SetLegacyThemeCompatibility()`? I don't love that either, sigh. But at least my brain doesn't have to keep asking "why are we always disabling it"?

Another (more important) thing: is there a way that `Initialize()` could just store this?  It just feels there is too much communication going on between various pieces about this, I'm trying to figure out how to untangle it.
___
*[`src/BloomExe/Book/AppearanceSettings.cs` line 359 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280#-Nq-9-6Z7_nqS9vbKAbX:-Nq-9-6Z7_nqS9vbKAbY:bb40kdu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a5ea92d6c5c9ba0c3632c28f979b08585be2fa34/src/BloomExe/Book/AppearanceSettings.cs#L359)):*
> ```Smalltalk
>     /// When we get more confidence that we have migrated all the brandings and xmatters, we can stop passing them in.
>     /// </summary>
>     public bool Initialize(Tuple<string, string>[] cssFilesToCheck, bool disableLegacyTheme)
> ```

How about `bool legacyThemeCanBeUsed`
___
*[`src/BloomExe/Book/Book.cs` line 1708 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280#-Nq-BOAF4P7fMTRrbmp6:-Nq-BOAF4P7fMTRrbmp7:b-enposf) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a5ea92d6c5c9ba0c3632c28f979b08585be2fa34/src/BloomExe/Book/Book.cs#L1708)):*
> ```Smalltalk
>             Storage.MigrateToLevel4UseAppearanceSystem();
> 
>             BookInfo.AppearanceSettings.DisableLegacyTheme(Storage.DisableLegacyTheme);
> ```

3 code lines later we tell it again?
___
*[`src/BloomExe/Book/BookStorage.cs` line 3706 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280#-NpW1NGs4AcHRN6x2zjA:-Nq-ACTV4SbfyEtyUOF8:bgfmlb2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/632cf1be83c82a67d2cb96cfb49fc00a0047acc3/src/BloomExe/Book/BookStorage.cs#L3706)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I've made an attempt to reduce the duplication...see what you think.
</blockquote></details>

Sorry, I wasn't clear. It's not the duplication of code that seems off, but that 3 places have to think about it. But I suppose you're using Book to ask Storage and then tell Apperance, which is good.
___
*[`src/BloomExe/Book/BookStorage.cs` line 87 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280#-Nq-A5b6DIzctXmCeSPm:-Nq-A5b6DIzctXmCeSPn:b1cs8jo) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a5ea92d6c5c9ba0c3632c28f979b08585be2fa34/src/BloomExe/Book/BookStorage.cs#L87)):*
> ```Smalltalk
>         ExpandoObject BrandingAppearanceSettings { get; }
> 
>         bool DisableLegacyTheme { get; }
> ```

How about `bool xmatterIsIncompatibleWithLegacyTheme`

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280)* status: 0 of 8 files reviewed, 5 unresolved discussions (waiting on @hatton)

___
*[`src/BloomExe/Book/AppearanceSettings.cs` line 163 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280#-Nq-8PGHBZFXMkGn1ENp:-Nq3ozT3CqZJLPblPSiR:b-pda737) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a5ea92d6c5c9ba0c3632c28f979b08585be2fa34/src/BloomExe/Book/AppearanceSettings.cs#L163)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I find this name to be, like definitely do this thing, when that's not what it does. How about `SetLegacyThemeCompatibility()`? I don't love that either, sigh. But at least my brain doesn't have to keep asking "why are we always disabling it"?

Another (more important) thing: is there a way that `Initialize()` could just store this?  It just feels there is too much communication going on between various pieces about this, I'm trying to figure out how to untangle it.
</blockquote></details>

Certainly it can be stored, but at the time we discussed this project you were particularly worried about the complexity caused by having too much state. And I think I agree with your previous state of mind. If the settings object remembers this independently of just remembering the theme, we have one more thing to remember to update (e.g., if a different xmatter pack is chosen). The current callers of this method do not call Initialize() first, anyway, though that might be possible to change.
I came up with another name, and I've gotten rid of a few tangles.
___
*[`src/BloomExe/Book/AppearanceSettings.cs` line 359 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280#-Nq-9-6Z7_nqS9vbKAbX:-Nq4BymYDSKXZlM4rQ7h:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a5ea92d6c5c9ba0c3632c28f979b08585be2fa34/src/BloomExe/Book/AppearanceSettings.cs#L359)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

How about `bool legacyThemeCanBeUsed`
</blockquote></details>

Done.
___
*[`src/BloomExe/Book/Book.cs` line 1708 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280#-Nq-BOAF4P7fMTRrbmp6:-Nq4CjDUBoh4rH-Ws61f:ba3dfob) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a5ea92d6c5c9ba0c3632c28f979b08585be2fa34/src/BloomExe/Book/Book.cs#L1708)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

3 code lines later we tell it again?
</blockquote></details>

Removed
___
*[`src/BloomExe/Book/BookStorage.cs` line 3706 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280#-NpW1NGs4AcHRN6x2zjA:-Nq4J4aJEXt9QLfS3qCe:b451kzi) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/632cf1be83c82a67d2cb96cfb49fc00a0047acc3/src/BloomExe/Book/BookStorage.cs#L3706)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Sorry, I wasn't clear. It's not the duplication of code that seems off, but that 3 places have to think about it. But I suppose you're using Book to ask Storage and then tell Apperance, which is good.
</blockquote></details>

I realized that I don't need to know this for Initialize. We clearly need to pay attention to it in EnsureUpToDate, since this is how the theme would get forced away from legacy if we change xmatter. The settings dialog clearly needs to know so it can hide the legacy theme menu option. It's possible that the migration code could just leave it to EnsureUpToDate, but it's really hard to convince myself that no problems would be caused by leaving the book longer in the wrong theme. Those are now the only uses of LegacyThemeCanBeUsed
___
*[`src/BloomExe/Book/BookStorage.cs` line 87 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280#-Nq-A5b6DIzctXmCeSPm:-Nq4Dw59CkexR-pTXhgg:b7z42qd) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a5ea92d6c5c9ba0c3632c28f979b08585be2fa34/src/BloomExe/Book/BookStorage.cs#L87)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

How about `bool xmatterIsIncompatibleWithLegacyTheme`
</blockquote></details>

I don't like the opposite polarity. So I called it, too, LegacyThemeCanBeUsed. It's a bit awkward having something that defaults true if it's not in the file, but I think it beats having two names for the same data with opposite polarity.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/AppearanceSettings.cs` line 163 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280#-Nq-8PGHBZFXMkGn1ENp:-Nq8c7giCsyOLIhNmiw_:b-bmzd04) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a5ea92d6c5c9ba0c3632c28f979b08585be2fa34/src/BloomExe/Book/AppearanceSettings.cs#L163)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Certainly it can be stored, but at the time we discussed this project you were particularly worried about the complexity caused by having too much state. And I think I agree with your previous state of mind. If the settings object remembers this independently of just remembering the theme, we have one more thing to remember to update (e.g., if a different xmatter pack is chosen). The current callers of this method do not call Initialize() first, anyway, though that might be possible to change.
I came up with another name, and I've gotten rid of a few tangles.
</blockquote></details>

we discussed and we think we can get rid of this method and install rely on `initialize()` with a new parameter.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[`src/BloomExe/Book/AppearanceSettings.cs` line 163 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280#-Nq-8PGHBZFXMkGn1ENp:-Nq8uNym-Q8llnoFXhxt:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a5ea92d6c5c9ba0c3632c28f979b08585be2fa34/src/BloomExe/Book/AppearanceSettings.cs#L163)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

we discussed and we think we can get rid of this method and install rely on `initialize()` with a new parameter.
</blockquote></details>

Done.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/AppearanceSettings.cs` line 163 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280#-Nq-8PGHBZFXMkGn1ENp:-Nq8vMlQ1S_vDcLcj-nU:b-gtqxe) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a5ea92d6c5c9ba0c3632c28f979b08585be2fa34/src/BloomExe/Book/AppearanceSettings.cs#L163)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Reviewable is still showing this method to me.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[`src/BloomExe/Book/AppearanceSettings.cs` line 163 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280#-Nq-8PGHBZFXMkGn1ENp:-Nq8zw0T0LhNLl3W8RpC:b-z58jnu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a5ea92d6c5c9ba0c3632c28f979b08585be2fa34/src/BloomExe/Book/AppearanceSettings.cs#L163)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Reviewable is still showing this method to me.
</blockquote></details>

I thought it was still marginally useful (now private, only called by initialize). I can inline it if you want.

**Review by hatton — COMMENTED** [review]
> Reviewed 4 of 8 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by hatton — APPROVED** [review]
Ready to merge but has conflicts now.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6280#-:-Nq9Sa4518LvfkrCVNvD:b46a693)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Pull request merged**
