### PR TITLE
BL-999: Fix NotSupportedException when serving jpg files

### PR DESCRIPTION
**Pull request by phillip-hopper**
Also removed redundant setting of ContentType when serving images.

### CODE REVIEW

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/175/
Test PASSed.

**Comment by JohnThomson** [comment]
John has a huge commit related to images. I think we should hold off on this until you can merge it with his.

**Comment by JohnThomson** [comment]
Have we confirmed that this isn't a problem for XP, or definitely decided to abandon XP?

**Comment by phillip-hopper** [comment]
I tried black & white, as well as color images, jpeg and png, on Windows XP and there didn't appear to be any problem with the image rendering. However, I did get several out-of-memory messages.
image

**Comment by hatton** [comment]
I think the conclusion of our discussion the other day was we are going to leave XP at windows 3. I'm still deep in image stuff, but I'm going to try and just get this change in there so that the testing I have to do anyways will also be done with this change in place.

**Pull request merged**
