### PR TITLE
Refactor TextBoxProperties to use pug (BL-4264)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1475)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Already a nice improvement, but I have a few suggestions.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug, line 1 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1475#-KcTWQ2PZYoKsn4M_6he:-KcTWQ2PZYoKsn4M_6hf:biymb1b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a3c8137c65bcbdc0f2e47e056141bff8eaedeba/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug#L1)):*
> ```Pug
> #text-properties-dialog.bloom-ui.bloomDialogContainer
> ```

There seem to be a lot of duplicate numbers (e.g., two things are 420px wide, at least three have margin-left 7px) which suggests a stylesheet and classes should be used here.
That may be nontrivial, since this is an HTML fragment rather than a full document with head/body etc. But I don't think it would be unreasonable to add some appropriate style definitions to one of the UI-only stylesheets like editMode.less or bloomDialog.less.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 1 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1475#-KcTUNTpQXkCPQnadid0:-KcTUNTpQXkCPQnadid1:bpuhx3y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a3c8137c65bcbdc0f2e47e056141bff8eaedeba/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L1)):*
> ```XML
> import theOneLocalizationManager from "../../lib/localizationManager/localizationManager";
> ```

Why are we changing to double quotes here? Our coding standard calls for single quoted strings by default (6.1 in https://github.com/airbnb/javascript#strings). (Also throughout.)

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 47 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1475#-KcTXQyi1d8O_jO6x5_p:-KcTXQyi1d8O_jO6x5_q:b-ybz3b4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a3c8137c65bcbdc0f2e47e056141bff8eaedeba/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L47)):*
> ```XML
> 
>                 if (noFormatChange) {
>                     $(".formattingEnabled").hide();
> ```

Would it be cleaner to add a class to the root element and let style rules hide the unwanted elements?

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 380 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1475#-KcTVck7jdLy_PRtewY5:-KcTVck8o4h7JsmbZQzU:b-gofk1t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a3c8137c65bcbdc0f2e47e056141bff8eaedeba/src/BloomExe/web/EnhancedImageServer.cs#L380)):*
> ```Smalltalk
> 				case "topics":
> 					return GetTopicList(info);
> 				case "textBoxPropertiesContent":
> ```

I would not have thought we needed new image server code to handle simply getting a file content. There should already be a method to ask for a file that's in one of the locations Bloom knows about. Isn't it exactly analogous (from the fileserver point of view) to having the HTML ask for a linked file using an href etc.?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1475#-:-KcTY1X_oZuic2Y65oYG:bwzqiz9)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug, line 1 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1475#-KcTWQ2PZYoKsn4M_6he:-KcTYNnpmRWN17midMg4:b-bz50z5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a3c8137c65bcbdc0f2e47e056141bff8eaedeba/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug#L1)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

There seem to be a lot of duplicate numbers (e.g., two things are 420px wide, at least three have margin-left 7px) which suggests a stylesheet and classes should be used here.
That may be nontrivial, since this is an HTML fragment rather than a full document with head/body etc. But I don't think it would be unreasonable to add some appropriate style definitions to one of the UI-only stylesheets like editMode.less or bloomDialog.less.
</blockquote></details>

Agree these should be in less. My original refactoring (before we decided to go to pug) were going to include that change. I guess I could go ahead and do them now as part of this.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 1 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1475#-KcTUNTpQXkCPQnadid0:-KcTYdVPF7XwMQ2NU1Z6:bevvb2q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a3c8137c65bcbdc0f2e47e056141bff8eaedeba/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L1)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Why are we changing to double quotes here? Our coding standard calls for single quoted strings by default (6.1 in https://github.com/airbnb/javascript#strings). (Also throughout.)
</blockquote></details>

Hm. There are two commits here. The first is the real change. The second was to make tslint happy. tslint requires double quotes. So if our standard is single, we need to change our tslint config.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 47 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1475#-KcTXQyi1d8O_jO6x5_p:-KcTYwF18-aAk5RDlAB-:bru50sf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a3c8137c65bcbdc0f2e47e056141bff8eaedeba/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L47)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Would it be cleaner to add a class to the root element and let style rules hide the unwanted elements?
</blockquote></details>

You mean use js to add a class like conditionally-hidden and have conditionally-hidden in less with display:none?
The advantage would be cleaner pug. The disadvantage would be extra less.
Hm... I'll look how we do this other places.

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 380 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1475#-KcTVck7jdLy_PRtewY5:-KcTZNBHZBDKXgxnFvUY:bvvgjhg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a3c8137c65bcbdc0f2e47e056141bff8eaedeba/src/BloomExe/web/EnhancedImageServer.cs#L380)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I would not have thought we needed new image server code to handle simply getting a file content. There should already be a method to ask for a file that's in one of the locations Bloom knows about. Isn't it exactly analogous (from the fileserver point of view) to having the HTML ask for a linked file using an href etc.?
</blockquote></details>

You're probably right. I think I thought of that at one point and my thought got lost while working. Thanks for bringing it up. I'll take a look.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1475)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug, line 1 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1475#-KcTWQ2PZYoKsn4M_6he:-KcTltmSaIXYZDh6EWrX:blisn3m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a3c8137c65bcbdc0f2e47e056141bff8eaedeba/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Agree these should be in less. My original refactoring (before we decided to go to pug) were going to include that change. I guess I could go ahead and do them now as part of this.
</blockquote></details>

Could go either way with making it a separate PR, but I incline towards getting it right in this one.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 1 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1475#-KcTUNTpQXkCPQnadid0:-KcTmB4w_c0D1-jytn6k:b-q6sulx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a3c8137c65bcbdc0f2e47e056141bff8eaedeba/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Hm. There are two commits here. The first is the real change. The second was to make tslint happy. tslint requires double quotes. So if our standard is single, we need to change our tslint config.
</blockquote></details>

https://github.com/BloomBooks/BloomDesktop/pull/1477 does this (initially for 3.8, but should be merged to master).

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 47 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1475#-KcTXQyi1d8O_jO6x5_p:-KcTmHaB3XDB3teHQLlr:b-18g42r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a3c8137c65bcbdc0f2e47e056141bff8eaedeba/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L47)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

You mean use js to add a class like conditionally-hidden and have conditionally-hidden in less with display:none?
The advantage would be cleaner pug. The disadvantage would be extra less.
Hm... I'll look how we do this other places.
</blockquote></details>

I was more thinking of a class on the root element something like formattingDisabled. Then the first top div would get (in pug) a class like hideFormattingEnabled and the tab root gets hideFormattingDisabled , and we have rules like .formattingDisabled hideFormattingDisabled  {display: none} and .(not: formattingDisabled) hideFormattingEnabled  {display: none}. (That negated syntax may not be right.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1475)*

**Comment by andrew-polk** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug, line 1 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1475#-KcTWQ2PZYoKsn4M_6he:-KcU9nqPycJicpBYgxqM:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a3c8137c65bcbdc0f2e47e056141bff8eaedeba/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug#L1)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Could go either way with making it a separate PR, but I incline towards getting it right in this one.
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 1 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1475#-KcTUNTpQXkCPQnadid0:-KcU9o_dbVgr9jEN2UkI:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a3c8137c65bcbdc0f2e47e056141bff8eaedeba/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L1)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

https://github.com/BloomBooks/BloomDesktop/pull/1477 does this (initially for 3.8, but should be merged to master).
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 47 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1475#-KcTXQyi1d8O_jO6x5_p:-KcU9pFZGvFpF2wycMXg:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a3c8137c65bcbdc0f2e47e056141bff8eaedeba/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L47)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I was more thinking of a class on the root element something like formattingDisabled. Then the first top div would get (in pug) a class like hideFormattingEnabled and the tab root gets hideFormattingDisabled , and we have rules like .formattingDisabled hideFormattingDisabled  {display: none} and .(not: formattingDisabled) hideFormattingEnabled  {display: none}. (That negated syntax may not be right.)
</blockquote></details>

Done.

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 380 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1475#-KcTVck7jdLy_PRtewY5:-KcU9q3bp0pvgKnFvqP0:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a3c8137c65bcbdc0f2e47e056141bff8eaedeba/src/BloomExe/web/EnhancedImageServer.cs#L380)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

You're probably right. I think I thought of that at one point and my thought got lost while working. Thanks for bringing it up. I'll take a look.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1475)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1475#-:-KcUDd3YXgmmVd7P2PjU:bnfp4nl)*

**Pull request merged**
