### PR TITLE
Various things we don't want to export (BL-10766 et al)

### PR DESCRIPTION
**Pull request by JohnThomson**
BL-10766 branding info
BL-10767 licenseImg
BL-10755 placeHolder.png
BL-10768 image descriptions

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4883)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4883)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs, line 205 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4883#-Mr3ug5XBBmuQ3FBo0sI:-Mr3ug5XBBmuQ3FBo0sJ:bvfclt1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/56ab172e80bd786d0a29d81fc94b79a03eabaad2/src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs#L205)):*
> ```Smalltalk
> 			var branding =
> 				roundtrippedDom.SelectSingleNode("//div[@data-book='outside-back-cover-branding-bottom-html']");
> 			branding.ParentNode.RemoveChild(branding);
> ```

I don't understand why the setup is removing branding from the roundtripped dom.
Don't we expect the production code to do that?
If this isn't a mistake, I guess a comment is in order.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4883)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs, line 205 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4883#-Mr3ug5XBBmuQ3FBo0sI:-Mr47Q510FS9WfZ6LEZb:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/56ab172e80bd786d0a29d81fc94b79a03eabaad2/src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs#L205)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't understand why the setup is removing branding from the roundtripped dom.
Don't we expect the production code to do that?
If this isn't a mistake, I guess a comment is in order.
</blockquote></details>

Done.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4883)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs, line 205 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4883#-Mr3ug5XBBmuQ3FBo0sI:-Mr47a7L92o8uAhCPr6v:b-wzs2qi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/56ab172e80bd786d0a29d81fc94b79a03eabaad2/src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs#L205)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

(We don't expect import to remove anything, so with no branding stuff in the export, there will be no reason for it to change any branding stuff in the import DOM.)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4883)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

___
*[src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs, line 205 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4883#-Mr3ug5XBBmuQ3FBo0sI:-Mr47x_e8jCapOsIfVJB:b-54avio) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/56ab172e80bd786d0a29d81fc94b79a03eabaad2/src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs#L205)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

(We don't expect import to remove anything, so with no branding stuff in the export, there will be no reason for it to change any branding stuff in the import DOM.)
</blockquote></details>

Ok, thanks.

**Pull request merged**
