### PR TITLE
Add BookSettings Panel to toolbox

### PR DESCRIPTION
**Pull request by hatton**
Includes various refactorings that I did as I tried to figure out how to add a new panel.... still way too hard! One intentional change in UI behavior is that the talkingbook (and booksettings) are not included in the "more..." list.

One known bug is that I when you switch pages, the accordion will always forget you were in the bookSetting. One more magically wiring step that I haven't figured out or got wrong somehow.

[Review on Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/898)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Reviewed 3 of 28 files at r1.
Review status: 3 of 28 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/BloomBrowserUI/bookEdit/toolbox/bookSettings/bookSettings.htm, line 7 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/898#-K5CxP5SNT8fv6bS8dpd:-K5CxP5SNT8fv6bS8dpe:1993218521) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ff8a59723b9d0b07b7538e5fd0bdb8bb85534ec4/src/BloomBrowserUI/bookEdit/toolbox/bookSettings/bookSettings.htm#L7)):*
I have a nasty suspicion that something I did while trying to achieve the IDs you wanted made it NECESSARY for tool IDs to end with 'Tool'. This might be why it won't persist open.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/898)*

**Comment by JohnThomson** [comment]
Looks basically good. I gather that without the checkbox in More, the talking book stuff will always be available, (and also the book settings tool)?
Don't forget that there are all sorts of lovely complexities about books being locked down and how this has different effects in source and vernacular collections. Book has 'RecordedAsLockedDown' as well as just 'LockedDown', for example, and HtmlDom has IsLockedDown; there is code to try to make sure that uploaded and downloaded books are generally locked down.  You should probably check that nothing undesirable happens if you upload a book while it is TemporarilyUnlocked. I'm not sure there is a problem, just surprised that the actual implementation of unlocking would be this easy :-).
Then there is EditingModel.CanAddPages, which has a special case for calendars...do you want the new unlocking to override that?

---

Reviewed 25 of 28 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/BloomBrowserUI/bookEdit/toolbox/bookSettings/bookSettings.js, line 6 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/898#-K5CyBaGiFhOBoABVeiV:-K5CyBaGiFhOBoABVeiW:1552892592) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ff8a59723b9d0b07b7538e5fd0bdb8bb85534ec4/src/BloomBrowserUI/bookEdit/toolbox/bookSettings/bookSettings.js#L6)):*
There's an existing mechanism (which you may purposely be redesigning) for getting settings to tools. Since the reader settings, at least, are saved in meta.json, change with care

---

*[src/BloomExe/Edit/ToolboxTool.cs, line 51 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/898#-K5CzaeCneoIIia9g85c:-K5CzaeCneoIIia9g85d:118236532) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ff8a59723b9d0b07b7538e5fd0bdb8bb85534ec4/src/BloomExe/Edit/ToolboxTool.cs#L51)):*
Method should probably be renamed CreateFromStaticToolId

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 224 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/898#-K5D-2YPpv-KqeY7WLxm:-K5D-2YPpv-KqeY7WLxn:-2104333980) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ff8a59723b9d0b07b7538e5fd0bdb8bb85534ec4/src/BloomExe/web/EnhancedImageServer.cs#L224)):*
It's slightly unfortunate that toobox stuff is leaking into the image server class again. I wonder whether we should either (a) give up and say it will know about some toolbox stuff, in which case, we might want to merge ReadersHandler.cs back into this; or (b) rename ReadersHandler to ToolboxHandler and let it deal with all the toolbox stuff; or (c) have a new class for each tab that needs image server stuff.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/898#-:-K5D-mTyvohWlmgZJka_:-2127990659)*

**Comment by hatton** [comment]
> I gather that without the checkbox in More, the talking book stuff will always be available, (and also the book settings tool)?

Right

> Then there is EditingModel.CanAddPages, which has a special case for calendars...do you want the new unlocking to override that?

If there's a problem with that, I'm not seeing it at the moment. This is a bit like "just act like a normal program" switch.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/BloomBrowserUI/bookEdit/toolbox/bookSettings/bookSettings.htm, line 7 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/898#-K5CxP5SNT8fv6bS8dpd:-K5H0DLDm5iAjfkSfj8U:-585375219) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ff8a59723b9d0b07b7538e5fd0bdb8bb85534ec4/src/BloomBrowserUI/bookEdit/toolbox/bookSettings/bookSettings.htm#L7)):*
The only place I see the string "TalkingBookTool" is in the jade/html, so I changed my panelId to "bookSettings*Tool*', but that didn't help. 

---

*[src/BloomExe/Edit/ToolboxTool.cs, line 51 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/898#-K5CzaeCneoIIia9g85c:-K5H0vXQrDHjnU7Jvhyz:476062379) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ff8a59723b9d0b07b7538e5fd0bdb8bb85534ec4/src/BloomExe/Edit/ToolboxTool.cs#L51)):*
OK, changed to ```CreateFromToolId```

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 224 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/898#-K5D-2YPpv-KqeY7WLxm:-K5H1-9Z8b2bFMpe_l_n:456961396) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ff8a59723b9d0b07b7538e5fd0bdb8bb85534ec4/src/BloomExe/web/EnhancedImageServer.cs#L224)):*
On (b), get behind me! Under no circumstances should we de-componentize the readers.

Rather, as I've been complaining for 2 years now, the "image server" is a beast that needs to be broken up and endure some design :-)

What's not clear to me, in part because "booksettings" has only a single bit of information thusfar, is if we want the urls to be organized around the wider model (e.g. collectionSettings, CurrentBook, etc) or the UI component itself (e.g. a layer or code between the wider model and the tool, which just delivers the "ViewModel" for the tool).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/898#-:-K5Gx2OYBDRczKgx0GPd:-206089866)*

**Comment by JohnThomson** [comment]
No problem. Like I said, I was surprised, but you're better than I am at trying out your changes and spotting problems. I would definitely try uploading and downloading a book which is being edited in this mode though. (Of course it can't be being edited while you upload it...but at least, most recently edited in that mode).

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/bookSettings/bookSettings.htm, line 7 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/898#-K5CxP5SNT8fv6bS8dpd:-K5HPbV057_bZwdaNkRt:-995873883) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ff8a59723b9d0b07b7538e5fd0bdb8bb85534ec4/src/BloomBrowserUI/bookEdit/toolbox/bookSettings/bookSettings.htm#L7)):*
Yes, I wasn't sure. Sorry it proved a red herring.

---

*[src/BloomExe/web/EnhancedImageServer.cs, line 224 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/898#-K5D-2YPpv-KqeY7WLxm:-K5HPonFHOHDWF2OP0U8:-91306511) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ff8a59723b9d0b07b7538e5fd0bdb8bb85534ec4/src/BloomExe/web/EnhancedImageServer.cs#L224)):*
Yes, for just one more setting, it's probably fine to do what you've done and wait for a propitious moment to redesign the server.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/898#-:-K5HQ1xlw0Tnew4VtWi8:-366050054)*

**Pull request merged**
