### PR TITLE
BL-6053 Combine audio for each page into a single MP3

### PR DESCRIPTION
**Pull request by JohnThomson**
BL-6053 Combine audio for each page into a single MP3

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2445)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 573 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2445#-LDmga2vBmsnJSREol1o:-LDn3zI90zPoYVC0jyDK:bksqn3b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/caffc3423181550ee68061c3e510f14036ce3a84/src/BloomExe/Publish/Epub/EpubMaker.cs#L573)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

If we have a class named "AudioProcessor", this audio merging logic really wants to live in a method there. Also, let's avoid these ever longer methods, in favor of shorter ones that do one thing.
</blockquote></details>

Well, I've extracted that one thing into a method in AudioProcessor. Not sure whether more could be done to stop this method growing.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2445)*

**Comment by hatton** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 573 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2445#-LDmga2vBmsnJSREol1o:-LDn9-ELA0n4M_D8tbGD:b-59v8bv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/caffc3423181550ee68061c3e510f14036ce3a84/src/BloomExe/Publish/Epub/EpubMaker.cs#L573)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Well, I've extracted that one thing into a method in AudioProcessor. Not sure whether more could be done to stop this method growing.
</blockquote></details>

How about

    if (mergeAudio) {
         mergeAudio = MergeAudioSpans(spansWithAudio, ...);
    }

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2445)*

**Comment by JohnThomson** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 573 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2445#-LDmga2vBmsnJSREol1o:-LDnD3J0BU8L3WLuWcep:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/caffc3423181550ee68061c3e510f14036ce3a84/src/BloomExe/Publish/Epub/EpubMaker.cs#L573)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

How about

    if (mergeAudio) {
         mergeAudio = MergeAudioSpans(spansWithAudio, ...);
    }
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2445)*

**Comment by hatton** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 573 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2445#-LDmga2vBmsnJSREol1o:-LDnDvSi8qaEeXuIefCz:b-qsdm26) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/caffc3423181550ee68061c3e510f14036ce3a84/src/BloomExe/Publish/Epub/EpubMaker.cs#L573)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Cool. Just to keep you sharp: you'd really want to drop that "out", return the path:

    mergedAudioPath  = MergeAudioSpans(spansWithAudio);

 and then change

    string epubPath = mergeAudio ? mergedAudioPath : CopyFileToEpub(path);

to

    string epubPath =  mergedAudioPath? mergedAudioPath  : CopyFileToEpub(path);

But it's perfectly readable as is. Feel free to merge.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2445)*

**Comment by JohnThomson** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 573 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2445#-LDmga2vBmsnJSREol1o:-LDqLXMv64loe-Jr3dWN:btfusvq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/caffc3423181550ee68061c3e510f14036ce3a84/src/BloomExe/Publish/Epub/EpubMaker.cs#L573)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Cool. Just to keep you sharp: you'd really want to drop that "out", return the path:

    mergedAudioPath  = MergeAudioSpans(spansWithAudio);

 and then change

    string epubPath = mergeAudio ? mergedAudioPath : CopyFileToEpub(path);

to

    string epubPath =  mergedAudioPath? mergedAudioPath  : CopyFileToEpub(path);

But it's perfectly readable as is. Feel free to merge.
</blockquote></details>

A little more complex than that...mergeAudio was used in a few places...but I think you're right that this simplifies things overall. Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2445)*

**Pull request merged**
