### PR TITLE
BL-5710 Not enough space on device

### PR DESCRIPTION
**Pull request by gmartin7**
* fixed misspelled function
* added WebSocketServerSpy to test output to
   Bloom's WebSocket
* added MockUsbPublisher to throw Disk is Full Exception
* added test for Disk Full Exception catch
* added test for file size calculation

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2257)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Android/usb/UsbPublisher.cs, line 181 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2257#-L7131O8GAYQBHAaaDDO:-L7131O8GAYQBHAaaDDP:b-8hhpec) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a087884d6c034bd7d295073621abaaba804114e1/src/BloomExe/Publish/Android/usb/UsbPublisher.cs#L181)):*
> ```Smalltalk
> 		}
> 
> 		private void SendOutOfMemoryMessage()
> ```

Now that disks are gone, what is memory vs disk? In my dialect, this has become is memory vs "storage". Do you buy that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2257)*

**Comment by gmartin7** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Android/usb/UsbPublisher.cs, line 181 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2257#-L7131O8GAYQBHAaaDDO:-L71f8_VaxLqLOWSbUSC:b-5jzuwy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a087884d6c034bd7d295073621abaaba804114e1/src/BloomExe/Publish/Android/usb/UsbPublisher.cs#L181)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Now that disks are gone, what is memory vs disk? In my dialect, this has become is memory vs "storage". Do you buy that?
</blockquote></details>

I think this is one of these "six of one, half a dozen of another" things like my dad always talked about. The actual user-facing message says, "The device reported that it does not have enough space for this book.", but the actual exception we've caught is an OutOfMemoryException. I suppose for that matter we could call the method "SendBookIsTooBigForDeviceMessage", if we want.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2257)*

**Comment by hatton** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Android/usb/UsbPublisher.cs, line 181 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2257#-L7131O8GAYQBHAaaDDO:-L71lMfpOAhRwSAda78H:b95hs4u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a087884d6c034bd7d295073621abaaba804114e1/src/BloomExe/Publish/Android/usb/UsbPublisher.cs#L181)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I think this is one of these "six of one, half a dozen of another" things like my dad always talked about. The actual user-facing message says, "The device reported that it does not have enough space for this book.", but the actual exception we've caught is an OutOfMemoryException. I suppose for that matter we could call the method "SendBookIsTooBigForDeviceMessage", if we want.
</blockquote></details>

See that's what's confusing me. Why is out of storage space on a device generating an "OutOfMemory" exception in .net?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2257)*

**Comment by gmartin7** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Android/usb/UsbPublisher.cs, line 181 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2257#-L7131O8GAYQBHAaaDDO:-L75jf2AYo3WHmLKVplS:b-qy26i2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a087884d6c034bd7d295073621abaaba804114e1/src/BloomExe/Publish/Android/usb/UsbPublisher.cs#L181)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

See that's what's confusing me. Why is out of storage space on a device generating an "OutOfMemory" exception in .net?
</blockquote></details>

Good question. And thanks for pushing back. I think I'm handling the wrong exception. It should be IOException with HResult == 0x80070070. Bummer. Back to the drawing board.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2257)*

**Comment by gmartin7** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Android/usb/UsbPublisher.cs, line 181 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2257#-L7131O8GAYQBHAaaDDO:-L76OVpvct-spGWZcGpw:b-z0jhh2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a087884d6c034bd7d295073621abaaba804114e1/src/BloomExe/Publish/Android/usb/UsbPublisher.cs#L181)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Good question. And thanks for pushing back. I think I'm handling the wrong exception. It should be IOException with HResult == 0x80070070. Bummer. Back to the drawing board.
</blockquote></details>

OK, that should be better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2257)*

**Comment by hatton** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Android/usb/UsbPublisher.cs, line 181 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2257#-L7131O8GAYQBHAaaDDO:-L76apFuoOdDEY5vgA0Z:byco76l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a087884d6c034bd7d295073621abaaba804114e1/src/BloomExe/Publish/Android/usb/UsbPublisher.cs#L181)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

OK, that should be better.
</blockquote></details>

OK. Should get a more detailed person to look at the rest.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2257)*

**Comment by StephenMcConnel** [comment]
one question, but otherwise :lgtm:

---

Reviewed 7 of 11 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Android/usb/UsbPublisher.cs, line 205 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2257#-L7PfuoI3XT9M_vXaatJ:-L7PfuoJVPbAxXTfkJ_A:ba7js5m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c9c23e99fa4a135b5015ae154ea2a62c27c283ae/src/BloomExe/Publish/Android/usb/UsbPublisher.cs#L205)):*
> ```Smalltalk
> 			{
> 				var info = new FileInfo(pathToBloomdFile);
> 				size = info.Length / 1048576m; // file length is in bytes and 1Mb = 1024 * 1024 bytes
> ```

Is that m supposed to be there at the end of 1048576?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2257#-:-L7PmFA2Z0XFcHRFe8bc:b-31x5ty)*

**Comment by gmartin7** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Android/usb/UsbPublisher.cs, line 205 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2257#-L7PfuoI3XT9M_vXaatJ:-L7Pmn9mjwZajOT7_XAQ:b-muygv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c9c23e99fa4a135b5015ae154ea2a62c27c283ae/src/BloomExe/Publish/Android/usb/UsbPublisher.cs#L205)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Is that m supposed to be there at the end of 1048576?
</blockquote></details>

'm' is the 'decimal' type suffix (apparently 'd' was already taken for 'double'). See also 4 lines up and the "F1" format in the ToString() below makes the returned string always have one decimal place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2257)*

**Comment by StephenMcConnel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/Android/usb/UsbPublisher.cs, line 205 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2257#-L7PfuoI3XT9M_vXaatJ:-L7Po5gyZu6xAc5EJifw:b-hns0zm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c9c23e99fa4a135b5015ae154ea2a62c27c283ae/src/BloomExe/Publish/Android/usb/UsbPublisher.cs#L205)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

'm' is the 'decimal' type suffix (apparently 'd' was already taken for 'double'). See also 4 lines up and the "F1" format in the ToString() below makes the returned string always have one decimal place.
</blockquote></details>

OK.  then :lgtm: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2257)*

**Pull request merged**
