### PR TITLE
BL-12130 Add initial book settings Max Image Size

### PR DESCRIPTION
**Pull request by hatton**
There are known problems listed in the card, this is an attempt to stop the code falling out of date.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776)

### CODE REVIEW

**Comment by hatton** [comment]
Please squash before merging.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 44 of 44 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776)* status: all files reviewed, 16 unresolved discussions (waiting on @hatton)

___
*[`src/BloomBrowserUI/package.json` line 71 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZkFCO7Csq-A-_B-bZ:-NTZkFCO7Csq-A-_B-b_:b-kjw2di) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/package.json#L71)):*
> ```JSON
>         "color-blind": "^0.1.1",
>         "comicaljs": "^0.3.0",
>         "contentful": "^8.3.7",
> ```

I'm surprised this is working for you locally somehow (I thought even yarn link required an entry here... maybe not?), but we'll need to add config-r here now.
___
*[`src/BloomBrowserUI/bookEdit/EditViewFrame.pug` line 59 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZdmN93lgHRJq8otHz:-NTZdmN93lgHRJq8otI-:bomi7n8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0c77f1a8d14d50744aa0d07e1e78174e06d8b46c/src/BloomBrowserUI/bookEdit/EditViewFrame.pug#L59)):*
> ```Pug
> 								| Your browser does not support iframes.
> 				label.pure-overlay(for="pure-toggle-right" data-overlay="right")
> 		div#modal-dialog-container
> ```

Looking in editViewFrame.ts, it appears that this div is still used by `getModalDialogContainer()` which is still called by several dialogs.
___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 42 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZmYRl1zGUnfT27nWu:-NTZmYRl1zGUnfT27nWv:bwkvju3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L42)):*
> ```XML
> 
> export const BookSettingsDialog: React.FunctionComponent<{
>     data: any;
> ```

Maybe this is just a todo (not in the card), but I don't think you're ever going to use the data prop.
___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 57 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZhr1R8wBWY-SysmKu:-NTZhr1R8wBWY-SysmKv:b-kt2gho) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L57)):*
> ```XML
>     //     "{}",
>     //     () => propsForBloomDialog.open
>     // );
> ```

Can remove this commented code.
___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 76 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZhnHM4rBZ0M-pLGhX:-NTZhnHM4rBZ0M-pLGhY:b4zh7i8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L76)):*
> ```XML
>             return; // leave settings as undefined
>         }
>         if (typeof settingsString === "string") {
> ```

Isn't the type always string?
___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 84 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZiQenD7EpeEpV0UOg:-NTZiQenD7EpeEpV0UOh:b-pwsaih) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L84)):*
> ```XML
> 
>     return (
>         <React.Fragment>
> ```

Don't need the Fragment wrapper
___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 115 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZjXnW60jpR2X313C1:-NTZjXnW60jpR2X313C2:bcp93o8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L115)):*
> ```XML
>                             //themeOverrides={lightTheme}
>                             themeOverrides={{
>                                 // enhance: we'd like to just be passing `lightTheme` but at the moment that seems to clobber everything
> ```

Maybe this wants to be a todo in the card, too?
___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 161 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZj1y20Mo435OyADDo:-NTZj1y20Mo435OyADDp:bds7p0h) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L161)):*
> ```XML
>                             // todo: how do we make the pageThumbnailList reload? It's in a different browser, so
>                             // we can't use a global. It listens to websocket, but we currently can only listen,
>                             // we cannot send.
> ```

I didn't see this in the todo list in the card, so I'm commenting so it can at least not get lost.

One solution: since you're posting to the C#, you could have that send the websocket message.
___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 171 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZkd4fDLSDQKlK7vBF:-NTZkd4fDLSDQKlK7vBG:b-ye12q3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L171)):*
> ```XML
> };
> 
> type Resolution = {
> ```

Now is probably the time to think about how we want to structure the files, components, etc. for bookSettings.
In other words, we don't want to keep accumulating all the different things for all bookSettings in this file.

Probably a folder under bookSettings for each ConfigrGroup, at least.
Then maybe even another level for each complex item?

Or is a semantic structure less helpful because we may eventually reuse things across semantics?
So maybe just a subfolder for each complex control like `imageResolution`?
___
*[`src/BloomBrowserUI/collectionsTab/BookButton.tsx` line 215 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZXWGABE4aeo1vMhGD:-NTZXWGABE4aeo1vMhGE:bi7ezdr) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/collectionsTab/BookButton.tsx#L215)):*
> ```XML
>             {
>                 label: "Book Settings",
>                 l10nId: "Common.BookSettings",
> ```

I think this wants a new entry in an .xlf.
We've been marking everything with `translate="no"` and a comment with the version for 5.5. If we follow the same comment pattern everywhere, a find and replace will be easy.
___
*[`src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx` line 93 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZYGbo3ugOX_Gbw4Tl:-NTZYGbo3ugOX_Gbw4Tm:b-k9r1g6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx#L93)):*
> ```XML
>                     ${props.cssForDialogContents} // this is a "serializedStyle" but we think it gets toString()ed here
>                 `}
>                 //className={props.className} // any emotion css from the parent
> ```

This change concerns me. If you found that passing className is no longer working for passing emotion css, we probably have a lot of other things broken, too.
___
*[`src/BloomBrowserUI/react_components/color-picking/colorPicker.tsx` line 16 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZZEpb5r5o1uCqbLE5:-NTZZEpb5r5o1uCqbLE6:b3orgt4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/react_components/color-picking/colorPicker.tsx#L16)):*
> ```XML
> // The reason for using our own swatches is so we can support swatches with gradients and alpha.
> interface IColorPickerProps {
>     transparency?: boolean;
> ```

I guess you checked for all instances of this where it isn't set to ensure that it is now set to true?
___
*[`src/BloomBrowserUI/react_components/color-picking/colorPickerDialog.tsx` line 35 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZZW3tADuo2a_6ME2h:-NTZZW3tADuo2a_6ME2i:b3orgt4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/react_components/color-picking/colorPickerDialog.tsx#L35)):*
> ```XML
>     close?: (result: DialogResult) => void;
>     localizedTitle: string;
>     transparency?: boolean;
> ```

I guess you checked for all instances of this where it isn't set to ensure that it is now set to true?
___
*[`src/BloomBrowserUI/react_components/color-picking/colorPickerDialog.tsx` line 386 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZZXhD78y2UctFT62z:-NTZZXhD78y2UctFT63-:b3orgt4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/react_components/color-picking/colorPickerDialog.tsx#L386)):*
> ```XML
> export interface ISimpleColorPickerDialogProps {
>     localizedTitle: string;
>     transparency?: boolean;
> ```

I guess you checked for all instances of this where it isn't set to ensure that it is now set to true?
___
*[`src/BloomExe/Edit/EditingView.Designer.cs` line 159 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZbZY53ShpBi4ZWaoI:-NTZbZY53ShpBi4ZWaoJ:b3fq6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomExe/Edit/EditingView.Designer.cs#L159)):*
> ```Smalltalk
>             this._L10NSharpExtender.SetLocalizableToolTip(this._bookSettingsButton, null);
>             this._L10NSharpExtender.SetLocalizationComment(this._bookSettingsButton, null);
>             this._L10NSharpExtender.SetLocalizingId(this._bookSettingsButton, "EditTab.BookSettingsButton");
> ```

I think this wants to be `Common.BookSettings` to match the menu item?
___
*[`src/BloomTests/BloomTests.csproj` line 171 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZd-Ww9DfkdWGG38xj:-NTZd-Ww9DfkdWGG38xk:b-j3j8wa) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomTests/BloomTests.csproj#L171)):*
> ```XML
>     <Reference Include="Microsoft.Web.WebView2.Wpf, Version=1.0.1518.46, Culture=neutral, PublicKeyToken=2a8ab48044d2601e, processorArchitecture=MSIL">
>       <HintPath>..\..\packages\Microsoft.Web.WebView2.1.0.1518.46\lib\net45\Microsoft.Web.WebView2.Wpf.dll</HintPath>
>     </Reference>
> ```

I'm surprised to see these changes since you obviously didn't make any change to the tests themselves which might require it.
Probably you could just revert this file.

**Review by hatton — COMMENTED** [review]
Thanks for all that Andrew. In the last round, I also removed the menu item to show BookSettings, I'm not ready for anyone to actually use this yet.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-:-NUYXYSj8jhAo44gYRMe:bxzyl7o)* status: all files reviewed, 16 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[`src/BloomBrowserUI/package.json` line 71 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZkFCO7Csq-A-_B-bZ:-NUYP1NU9yix-4dAEoxU:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/package.json#L71)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm surprised this is working for you locally somehow (I thought even yarn link required an entry here... maybe not?), but we'll need to add config-r here now.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/EditViewFrame.pug` line 59 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZdmN93lgHRJq8otHz:-NUYPNVe6BKDiRmGQQqJ:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0c77f1a8d14d50744aa0d07e1e78174e06d8b46c/src/BloomBrowserUI/bookEdit/EditViewFrame.pug#L59)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looking in editViewFrame.ts, it appears that this div is still used by `getModalDialogContainer()` which is still called by several dialogs.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 42 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZmYRl1zGUnfT27nWu:-NUYPZ3t6ySYcJJDcQw6:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L42)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Maybe this is just a todo (not in the card), but I don't think you're ever going to use the data prop.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 57 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZhr1R8wBWY-SysmKu:-NUYPalM8WjxykRS3Q2o:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L57)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Can remove this commented code.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 76 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZhnHM4rBZ0M-pLGhX:-NUYPgzfA3jnAL7kc3Zf:bwgg31f) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L76)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Isn't the type always string?
</blockquote></details>

I don't remember. I do remember really wanting to do surgery on the c# and/or the ts side of this, because it had surprising behavior. But that I kept myself from going down that rabbit hole.
___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 84 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZiQenD7EpeEpV0UOg:-NUYQEw47HdkjoXW2SMV:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L84)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Don't need the Fragment wrapper
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 115 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZjXnW60jpR2X313C1:-NUYQTm_3qrGj7Vwd_5s:b2ni7qj) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L115)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Maybe this wants to be a todo in the card, too?
</blockquote></details>

meh
___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 161 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZj1y20Mo435OyADDo:-NUYRC8K8IBieE-Gi_O0:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L161)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I didn't see this in the todo list in the card, so I'm commenting so it can at least not get lost.

One solution: since you're posting to the C#, you could have that send the websocket message.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 171 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZkd4fDLSDQKlK7vBF:-NUYRHDVDJIVyo2pjqux:b-way6z1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L171)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Now is probably the time to think about how we want to structure the files, components, etc. for bookSettings.
In other words, we don't want to keep accumulating all the different things for all bookSettings in this file.

Probably a folder under bookSettings for each ConfigrGroup, at least.
Then maybe even another level for each complex item?

Or is a semantic structure less helpful because we may eventually reuse things across semantics?
So maybe just a subfolder for each complex control like `imageResolution`?
</blockquote></details>

Yeah that will come with time. This is all in progress.
___
*[`src/BloomBrowserUI/collectionsTab/BookButton.tsx` line 215 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZXWGABE4aeo1vMhGD:-NUYSchLAQL0BCkzTvri:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/collectionsTab/BookButton.tsx#L215)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this wants a new entry in an .xlf.
We've been marking everything with `translate="no"` and a comment with the version for 5.5. If we follow the same comment pattern everywhere, a find and replace will be easy.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx` line 93 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZYGbo3ugOX_Gbw4Tl:-NUYSoGU7yPiGAlIZnG4:b-5wh2u) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx#L93)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This change concerns me. If you found that passing className is no longer working for passing emotion css, we probably have a lot of other things broken, too.
</blockquote></details>

Possibly @JohnThomson will remember what we ran into there?
___
*[`src/BloomBrowserUI/react_components/color-picking/colorPicker.tsx` line 16 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZZEpb5r5o1uCqbLE5:-NUYT-nLADL_e_g75Dau:bqzla1u) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/react_components/color-picking/colorPicker.tsx#L16)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I guess you checked for all instances of this where it isn't set to ensure that it is now set to true?
</blockquote></details>

fair assumption
___
*[`src/BloomBrowserUI/react_components/color-picking/colorPickerDialog.tsx` line 35 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZZW3tADuo2a_6ME2h:-NUYT30T9h4C3ETR3W4i:bqzla1u) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/react_components/color-picking/colorPickerDialog.tsx#L35)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I guess you checked for all instances of this where it isn't set to ensure that it is now set to true?
</blockquote></details>

fair assumption
___
*[`src/BloomBrowserUI/react_components/color-picking/colorPickerDialog.tsx` line 386 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZZXhD78y2UctFT62z:-NUYT3cP0GupVbZF22sg:bqzla1u) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/react_components/color-picking/colorPickerDialog.tsx#L386)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I guess you checked for all instances of this where it isn't set to ensure that it is now set to true?
</blockquote></details>

fair assumption
___
*[`src/BloomExe/Edit/EditingView.Designer.cs` line 159 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZbZY53ShpBi4ZWaoI:-NUYTMd7E2U9lRMT8wMG:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomExe/Edit/EditingView.Designer.cs#L159)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this wants to be `Common.BookSettings` to match the menu item?
</blockquote></details>

Done.
___
*[`src/BloomTests/BloomTests.csproj` line 171 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZd-Ww9DfkdWGG38xj:-NUYUhQ3D9wt0oP04PCs:b-ba8bu1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomTests/BloomTests.csproj#L171)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm surprised to see these changes since you obviously didn't make any change to the tests themselves which might require it.
Probably you could just revert this file.
</blockquote></details>

I did add AppearanceSettingsTests.cs? Anyhow I set the rest to what is currently on master.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 57 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZhr1R8wBWY-SysmKu:-NUYenFQ0Ee3XB20BqOF:b-tq7fgl) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L57)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, I don't think this change made it in with your cherry pick.
___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 84 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZiQenD7EpeEpV0UOg:-NUYej-p0LcvmuXnaxWw:b-tq7fgl) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L84)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, I don't think this change made it in with your cherry pick.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776)* status: 44 of 45 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 57 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZhr1R8wBWY-SysmKu:-NUav6Vy5pmZKg0Wg_So:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L57)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry, I don't think this change made it in with your cherry pick.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 84 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZiQenD7EpeEpV0UOg:-NUav6nk7CuvY9sXnYb-:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L84)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry, I don't think this change made it in with your cherry pick.
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx` line 93 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NTZYGbo3ugOX_Gbw4Tl:-NUi0pwT9VzY8aqzur_X:b-7rl0jd) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a4191592ab79f2f1505cc3a6b86fb5b9ac9eb14d/src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx#L93)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Possibly @JohnThomson will remember what we ran into there?
</blockquote></details>

done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 79 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NUi4G_oB3skTmVzIxEZ:-NUi4G_oB3skTmVzIxE_:b433pv2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0ce80e48bf97e4dc1a382419a6508546805b795e/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L79)):*
> ```XML
>             cssForDialogContents={css`
>                 background-color: white;
>             `}
> ```

Need to remove this. 

Or make it just 
```
css={css`...
```
Then feel free to merge.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776)* status: 44 of 45 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 79 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776#-NUi4G_oB3skTmVzIxEZ:-NUiErih-9E78MFCIkgo:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0ce80e48bf97e4dc1a382419a6508546805b795e/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L79)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Need to remove this. 

Or make it just 
```
css={css`...
```
Then feel free to merge.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hatton)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 12 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5776)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hatton)

**Pull request merged**
