### PR TITLE
Bl 12759 Hide parse create language behind API

### PR DESCRIPTION
**Pull request by nabalone**
Ready for review but depends on https://github.com/BloomBooks/bloom-azure-functions/pull/65

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213)* status: all files reviewed, 2 unresolved discussions (waiting on @nabalone)

___
*[`src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs` line 368 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NiponIPCWIv8J9D_h5B:-NiponIPCWIv8J9D_h5C:b-mksf0t) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc1eaaafb92cabc40e0752ce6d4bc12fd9d5a16a/src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs#L368)):*
> ```Smalltalk
> 			{
> 				var lang = languages[i];
> 				var request = MakePostRequest("get-language-object-id");
> ```

Probably wants a comment explaining that this will create the language record if it doesn't exist. (and maybe include that's why it is a POST, not a GET).
___
*[`src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs` line 378 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NippGwl1X1xl86b0ONu:-NippGwl1X1xl86b0ONv:b-ckc5jo) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc1eaaafb92cabc40e0752ce6d4bc12fd9d5a16a/src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs#L378)):*
> ```Smalltalk
> 				var languageObjectId = response.Content;
> 
> 				result[i] = new ParseServerObjectPointer() {ClassName = "language", ObjectId = languageObjectId };
> ```

I haven't evaluated this to know what the best path forward is, but we want to move away from anything parse-specific.
At the very least, we want to rename `ParseServerObjectPointer`. (DatabaseObjectPointer??)
But I didn't look at how it is used. Is there a better, more generic model? I'm afraid the answer may be no without significant upheaval.

**Comment by andrew-polk** [comment]
*[`src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs` line 358 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-Niptiin5CJLsHAhvKdj:-Niptiin5CJLsHAhvKdk:b-1jk6d6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc1eaaafb92cabc40e0752ce6d4bc12fd9d5a16a/src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs#L358)):*
> (requires user to be logged in)

Is that true?
Are we passing a session token?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213)* status: all files reviewed, 3 unresolved discussions (waiting on @nabalone)

___
*[`src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs` line 378 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NippGwl1X1xl86b0ONu:-NipuEii6gQvMIO2di-P:b-7gz3n6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc1eaaafb92cabc40e0752ce6d4bc12fd9d5a16a/src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs#L378)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I haven't evaluated this to know what the best path forward is, but we want to move away from anything parse-specific.
At the very least, we want to rename `ParseServerObjectPointer`. (DatabaseObjectPointer??)
But I didn't look at how it is used. Is there a better, more generic model? I'm afraid the answer may be no without significant upheaval.
</blockquote></details>

Actually, do we need to take a bigger step back here and see if this language stuff should be part of the upload-start action?

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs` line 358 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-Niptiin5CJLsHAhvKdj:-Niv75GV2RZC4IKI-PO6:biifcl4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc1eaaafb92cabc40e0752ce6d4bc12fd9d5a16a/src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs#L358)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> (requires user to be logged in)

Is that true?
Are we passing a session token?
</blockquote></details>

Should it require user to be logged in? at least in Dev, the language table is public write so it doesn't look like anything would validate the token
___
*[`src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs` line 368 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NiponIPCWIv8J9D_h5B:-NivYqZ5A_n-Ma9mZmEk:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc1eaaafb92cabc40e0752ce6d4bc12fd9d5a16a/src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs#L368)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Probably wants a comment explaining that this will create the language record if it doesn't exist. (and maybe include that's why it is a POST, not a GET).
</blockquote></details>

Done.
___
*[`src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs` line 378 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NippGwl1X1xl86b0ONu:-Niv8jGN8gd6PYN6EZQm:b-hzu01x) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc1eaaafb92cabc40e0752ce6d4bc12fd9d5a16a/src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs#L378)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Actually, do we need to take a bigger step back here and see if this language stuff should be part of the upload-start action?
</blockquote></details>

You're right, it does look like it would be good to move the language stuff to upload-start. But do we need to worry about performance? Looking at comment
`                // Set this in the metadata so it gets uploaded. Do this in the background task as it can take some time.`
https://github.com/BloomBooks/BloomDesktop/blob/82908795356c8b12ad223d06c0cc63107b95f8fd/src/BloomExe/WebLibraryIntegration/BookUpload.cs#L489

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213)* status: all files reviewed, 3 unresolved discussions (waiting on @nabalone)

___
*[`src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs` line 358 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-Niptiin5CJLsHAhvKdj:-Nj8CrsR4B3U_F7mAYMz:b-p2f36l) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc1eaaafb92cabc40e0752ce6d4bc12fd9d5a16a/src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs#L358)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Should it require user to be logged in? at least in Dev, the language table is public write so it doesn't look like anything would validate the token
</blockquote></details>

I'm disinclined to change the permissions at this point, so I think we'll leave it as is.
So let's just remove that part of the comment.
___
*[`src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs` line 368 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NiponIPCWIv8J9D_h5B:-Nj8CqkF6lMn9cTBxqEp:bqojrr4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc1eaaafb92cabc40e0752ce6d4bc12fd9d5a16a/src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs#L368)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not seeing that yet.
___
*[`src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs` line 378 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NippGwl1X1xl86b0ONu:-Nj8CAHC6O7YsNB9pldm:b-48ki72) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc1eaaafb92cabc40e0752ce6d4bc12fd9d5a16a/src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs#L378)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

You're right, it does look like it would be good to move the language stuff to upload-start. But do we need to worry about performance? Looking at comment
`                // Set this in the metadata so it gets uploaded. Do this in the background task as it can take some time.`
https://github.com/BloomBooks/BloomDesktop/blob/82908795356c8b12ad223d06c0cc63107b95f8fd/src/BloomExe/WebLibraryIntegration/BookUpload.cs#L489
</blockquote></details>

I **think** by background task, it means the whole upload part (higher up the stack) which doesn't run on the UI thread. So I think whether we do it in the azure function or call it from BloomDesktop directly, that shouldn't affect things. 

But I see now after looking at the code, that we actually set the langPointers in meta.json. We'll need to evaluate if those are being read by anything. Doesn't seem to be read by Bloom itself.

Even if something does need them set in meta.json, I suppose we could return the langPointers values from upload-start. But then it is starting to feel less worth it.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213)* status: all files reviewed, 3 unresolved discussions (waiting on @nabalone)

___
*[`src/BloomExe/Book/BookInfo.cs` line 1185 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NjDOYi42g-xoJJ6NwIC:-NjDOYi42g-xoJJ6NwID:b-p2catj) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d1eee765bd1145be9bc8f17fe9062b3d4e823b16/src/BloomExe/Book/BookInfo.cs#L1185)):*
> ```Smalltalk
> 		public string[] Languages { get { return new string[0]; } set {}}
> 
> 		// Obsolete
> ```

Is there any reason to keep this property?
___
*[`src/BloomExe/Book/BookInfo.cs` line 1189 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NjDOWH00jmDKk27xe2D:-NjDOWH00jmDKk27xe2E:boe9nrb) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d1eee765bd1145be9bc8f17fe9062b3d4e823b16/src/BloomExe/Book/BookInfo.cs#L1189)):*
> ```Smalltalk
> 		public DatabaseUserObject[] LanguageTableReferences { get { return new DatabaseUserObject[0]; } set {} }
> 
> 		[JsonProperty("languageDescriptors")]
> ```

Do we need to serialize this?
i.e., should this be `[JsonIgnore]`?
___
*[`src/BloomExe/Book/BookInfo.cs` line 1321 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NjDOTwh8xAiLSMtCmTQ:-NjDOTwh8xAiLSMtCmTR:boe9nrb) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d1eee765bd1145be9bc8f17fe9062b3d4e823b16/src/BloomExe/Book/BookInfo.cs#L1321)):*
> ```Smalltalk
> 		/// Contains the database object ID of the person who uploaded the book.
> 		/// </summary>
> 		[JsonProperty("uploader")]
> ```

Do we need to serialize this?
i.e., should this be `[JsonIgnore]`?

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Book/BookInfo.cs` line 1185 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NjDOYi42g-xoJJ6NwIC:-NjE-v-BEJLjDlKuizgA:bglz3jp) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d1eee765bd1145be9bc8f17fe9062b3d4e823b16/src/BloomExe/Book/BookInfo.cs#L1185)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is there any reason to keep this property?
</blockquote></details>

Ok, I deleted it and seems to be no problem. But why are we keeping around `Languages` above?  And why `// This is obsolete but loading old Json files fails if we don't have a setter for it.`
___
*[`src/BloomExe/Book/BookInfo.cs` line 1189 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NjDOWH00jmDKk27xe2D:-NjETs_N2EXQ3ECe07NJ:b-rdo0g) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d1eee765bd1145be9bc8f17fe9062b3d4e823b16/src/BloomExe/Book/BookInfo.cs#L1189)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Do we need to serialize this?
i.e., should this be `[JsonIgnore]`?
</blockquote></details>

Not sure if I understand.  Should `LanguageDescriptors` be  `[JsonIgnore]`? They are now going into the meta.json
___
*[`src/BloomExe/Book/BookInfo.cs` line 1321 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NjDOTwh8xAiLSMtCmTQ:-NjEUm6h24w82tE78Na4:beabiir) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d1eee765bd1145be9bc8f17fe9062b3d4e823b16/src/BloomExe/Book/BookInfo.cs#L1321)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Do we need to serialize this?
i.e., should this be `[JsonIgnore]`?
</blockquote></details>

Really not sure I understand... do we put `[JsonIgnore]` on things that don't need to be serialized?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213)* status: all files reviewed, 3 unresolved discussions (waiting on @nabalone)

___
*[`src/BloomExe/Book/BookInfo.cs` line 1185 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NjDOYi42g-xoJJ6NwIC:-NjElSYw9WLTuiJh-AuX:blth4qe) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d1eee765bd1145be9bc8f17fe9062b3d4e823b16/src/BloomExe/Book/BookInfo.cs#L1185)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Ok, I deleted it and seems to be no problem. But why are we keeping around `Languages` above?  And why `// This is obsolete but loading old Json files fails if we don't have a setter for it.`
</blockquote></details>

Hm. Good question.
So after you removed this langPointers/LanguageTableReferences property, you were able to load a meta.json which had langPointers and had no problem? That's what I would expect. But you're right; the comment above is confusing.
___
*[`src/BloomExe/Book/BookInfo.cs` line 1321 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NjDOTwh8xAiLSMtCmTQ:-NjEl74sC1vexkP3Cby0:b4ivjb1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d1eee765bd1145be9bc8f17fe9062b3d4e823b16/src/BloomExe/Book/BookInfo.cs#L1321)):*
> do we put `[JsonIgnore]` on things that don't need to be serialized?

yes

I'm thinking we don't need `languageDescriptors` or `uploader` in the meta.json.
But we still need the properties so they can get into the info which goes to the azure function.

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Book/BookInfo.cs` line 1185 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NjDOYi42g-xoJJ6NwIC:-NjNigL2EGYxt8Pyxamw:b2nhswy) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d1eee765bd1145be9bc8f17fe9062b3d4e823b16/src/BloomExe/Book/BookInfo.cs#L1185)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Hm. Good question.
So after you removed this langPointers/LanguageTableReferences property, you were able to load a meta.json which had langPointers and had no problem? That's what I would expect. But you're right; the comment above is confusing.
</blockquote></details>

Yes
___
*[`src/BloomExe/Book/BookInfo.cs` line 1321 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NjDOTwh8xAiLSMtCmTQ:-NjNhXjDD8gDZqftl8Qu:b-jkpgs8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d1eee765bd1145be9bc8f17fe9062b3d4e823b16/src/BloomExe/Book/BookInfo.cs#L1321)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> do we put `[JsonIgnore]` on things that don't need to be serialized?

yes

I'm thinking we don't need `languageDescriptors` or `uploader` in the meta.json.
But we still need the properties so they can get into the info which goes to the azure function.
</blockquote></details>

I thought the azure function doesn't use `uploader` any more, but rather sets the uploader based on the session token. Does the harvester not need uploader to be in the meta.json?  

I'll put `[JsonIgnore]` on the `languageDescriptors`

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213)* status: all files reviewed, 3 unresolved discussions (waiting on @nabalone)

___
*[`src/BloomExe/Book/BookInfo.cs` line 1185 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NjDOYi42g-xoJJ6NwIC:-NjNywRuDk4os6c4A3ex:b-c7ahp) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d1eee765bd1145be9bc8f17fe9062b3d4e823b16/src/BloomExe/Book/BookInfo.cs#L1185)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

I guess we should remove it if we don't have reason to believe we need it (other than the comment above).
___
*[`src/BloomExe/Book/BookInfo.cs` line 1321 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NjDOTwh8xAiLSMtCmTQ:-NjNz0AMCYZV0A6Pte1X:b-ss5697) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d1eee765bd1145be9bc8f17fe9062b3d4e823b16/src/BloomExe/Book/BookInfo.cs#L1321)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

I thought the azure function doesn't use `uploader` any more, but rather sets the uploader based on the session token. Does the harvester not need uploader to be in the meta.json?  

I'll put `[JsonIgnore]` on the `languageDescriptors`
</blockquote></details>

Looks like harvester only gets uploader from parse directly.
So I guess we don't need it in meta.json or to send it to the api.
So unless it is used internally in BloomDesktop, I guess we can remove this property, too.

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Book/BookInfo.cs` line 1321 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NjDOTwh8xAiLSMtCmTQ:-NjOPWgl4bdpYs8NkqNc:btuvpfv) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d1eee765bd1145be9bc8f17fe9062b3d4e823b16/src/BloomExe/Book/BookInfo.cs#L1321)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like harvester only gets uploader from parse directly.
So I guess we don't need it in meta.json or to send it to the api.
So unless it is used internally in BloomDesktop, I guess we can remove this property, too.
</blockquote></details>

Ok, removed `uploader`

I think we actually need the `[JsonProperty("languageDescriptors")]` in order to get the `languageDescriptors` into the `webDataJson` which is put into the `upload-finish` request body

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Book/BookInfo.cs` line 1185 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NjDOYi42g-xoJJ6NwIC:-NjOrCCV1vuamFySTOH1:bvx6unm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d1eee765bd1145be9bc8f17fe9062b3d4e823b16/src/BloomExe/Book/BookInfo.cs#L1185)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I guess we should remove it if we don't have reason to believe we need it (other than the comment above).
</blockquote></details>

I removed the `LanguageTableReferences`, did you want me to remove the `Languages` also?

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nabalone)

___
*[`src/BloomExe/Book/BookInfo.cs` line 1185 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NjDOYi42g-xoJJ6NwIC:-NjOuCFK2pHsZnx_HYac:b-frl68e) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d1eee765bd1145be9bc8f17fe9062b3d4e823b16/src/BloomExe/Book/BookInfo.cs#L1185)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

I removed the `LanguageTableReferences`, did you want me to remove the `Languages` also?
</blockquote></details>

I wasn't asking you to, no.
Now that you're asking... I'm torn. Let's just leave it since we don't understand the comment.
___
*[`src/BloomExe/Book/BookInfo.cs` line 1321 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213#-NjDOTwh8xAiLSMtCmTQ:-NjOuN2aCLS4Qlk8PuDl:b-dutodt) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d1eee765bd1145be9bc8f17fe9062b3d4e823b16/src/BloomExe/Book/BookInfo.cs#L1321)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Ok, removed `uploader`

I think we actually need the `[JsonProperty("languageDescriptors")]` in order to get the `languageDescriptors` into the `webDataJson` which is put into the `upload-finish` request body
</blockquote></details>

Interesting. I hadn't been realizing that we actually rely on serialization to get webDataJson created.
That must be how we keep polluting meta.json.

Ok, that refactoring (teasing apart webDataJson from meta.json will have to wait for another day.

**Pull request merged**
