### PR TITLE
Implement TC status pane popup menu and about avatar item (BL-10014)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4554)

### CODE REVIEW

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4554)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, line 47 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4554#-McPgpE2EcaZGnPwi8-s:-McPgpE2EcaZGnPwi8-t:b-scjryo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/59845872f35c020f518512296d4f38db1a67604b/src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx#L47)):*
> ```
> setbookStatus]
> ```
setBookStatus

(if you end up making other changes after UI review; otherwise, don't bother)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4554)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4554)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, line 47 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4554#-McPgpE2EcaZGnPwi8-s:-Mck3Sxl2OlFJu41QlWX:bb7f2mf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/59845872f35c020f518512296d4f38db1a67604b/src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx#L47)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> setbookStatus]
> ```
setBookStatus

(if you end up making other changes after UI review; otherwise, don't bother)
</blockquote></details>

done

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4554)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
