### PR TITLE
Update ReadMe.md

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5861)

### CODE REVIEW

**Review by gmartin7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5861)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`ReadMe.md` line 32 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5861#-NVkemN83HimUKimKPtV:-NVkemN83HimUKimKPtW:bctf6zh) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d51981cc7f4746280b645e590bbb66691a7cb773/ReadMe.md#L32)):*
> ```Markdown
>     cd src/content
>     yarn
>     cd ../BloomBrowserUI
> ```

Can't you just do the `BloomBrowserUI` version and it runs `src/content` also? Or do you need to run `src/content` once by itself?

**Review by jsubloom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5861)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`ReadMe.md` line 21 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5861#-NVkfUTvEtbRIUNIt7t7:-NVkfUTwCpcgjDOaksM_:b-upzce1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d51981cc7f4746280b645e590bbb66691a7cb773/ReadMe.md#L21)):*
> ```Markdown
> Install yarn (https://yarnpkg.com/lang/en/docs/install/#windows-stable)
> 
> You'll need nodejs, but we manage nodejs by installing volta and informing volta which version to use with a setting in package.json:
> ```

Probably handy to link to https://docs.volta.sh/guide/getting-started

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5861)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @gmartin7 and @jsubloom)

___
*[`ReadMe.md` line 21 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5861#-NVkfUTvEtbRIUNIt7t7:-NVot0UBEWDIanV6N-w8:b-kkjpjm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d51981cc7f4746280b645e590bbb66691a7cb773/ReadMe.md#L21)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

Probably handy to link to https://docs.volta.sh/guide/getting-started
</blockquote></details>

Thanks. I had intended to do that.
___
*[`ReadMe.md` line 32 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5861#-NVkemN83HimUKimKPtV:-NVosxRG1ls2x9VFgzDU:b-evk2gk) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d51981cc7f4746280b645e590bbb66691a7cb773/ReadMe.md#L32)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Can't you just do the `BloomBrowserUI` version and it runs `src/content` also? Or do you need to run `src/content` once by itself?
</blockquote></details>

Nope. Have to run yarn explicitly in both places.

**Review by andrew-polk — COMMENTED** [review]
> Dismissed @gmartin7 and @jsubloom from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5861)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @gmartin7 and @jsubloom)

**Pull request merged**
