### PR TITLE
Add some basic analytics to Team Collection actions (BL-9868)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
Also fix some Linux related issues for Dropbox interaction.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4428)

### CODE REVIEW

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4428)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1563 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4428#-M_SNJ7kAXZLrpPMSc8Z:-M_XKWw8AdFS7iJJfn-H:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/254a3435389417b9bb10d7676966974e1a7f1659/src/BloomExe/TeamCollection/TeamCollection.cs#L1563)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Path.GetFileName(_localCollectionFolder) would give us a pretty good idea, though it may sometimes not be exactly the name we use elsewhere. When my latest PR lands, it will also be possible to get the collection settings as _tcManager.Settings, and from there, CollectionName.
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1751 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4428#-M_SMGiu4EGfeC3_4GcB:-M_XJtgM0IuqlzGf_wW_:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/254a3435389417b9bb10d7676966974e1a7f1659/src/BloomExe/TeamCollection/TeamCollection.cs#L1751)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's a bit of a toss-up, but since this is fairly important to us, I'd be inclined to make the base class method abstract, so we get at least that much reminder to implement it if we create another TC implementation class. Of course then you have to do something for DisconnectedTC...might make sense for that to answer 'Disconnected', though I don't think currently it will ever be used, since you can't do the TC things we're tracking while disconnected.
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 251 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4428#-M_SOQn96JRjaP8XF6oY:-M_XJIT96mA7X7VyOY6E:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/254a3435389417b9bb10d7676966974e1a7f1659/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L251)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I agree. 
Also, I think we may actually still have analytics for exceptions turned off in Segment anyway since we had that fiasco a few years ago when someone sent 300,000 exceptions.
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4428)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4428)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1563 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4428#-M_SNJ7kAXZLrpPMSc8Z:-M_X_sg2EsHFitzSRW8i:b-218mbc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/254a3435389417b9bb10d7676966974e1a7f1659/src/BloomExe/TeamCollection/TeamCollection.cs#L1563)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Well, the PR that allows you to use the other approach has now landed, so you may as well go ahead and make the change.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4428)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1563 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4428#-M_SNJ7kAXZLrpPMSc8Z:-M_XirUYEqgFS4AtE4uj:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/254a3435389417b9bb10d7676966974e1a7f1659/src/BloomExe/TeamCollection/TeamCollection.cs#L1563)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Well, the PR that allows you to use the other approach has now landed, so you may as well go ahead and make the change.
</blockquote></details>

Done.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4428)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
