### PR TITLE
Import/Export to Spreadsheet requires Bloom Enterprise (BL-10260)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4707)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4707)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/webpack.common.js, line 68 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4707#-Mj56buk-A7Zgj4PW4Xz:-Mj56buk-A7Zgj4PW4Y-:b-kmxaip) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/632d47fcc3c50c2c54a210ea200bcef487ecad37/src/BloomBrowserUI/webpack.common.js#L68)):*
> ```JavaScript
>             "./react_components/DefaultBookshelfControl.tsx",
>         progressDialogBundle: "./react_components/Progress/ProgressDialog.tsx",
>         problemReportBundle: "./problemDialog/ProblemDialog.tsx",
> ```

This is a duplicate of 3 lines above it. It doesn't seem necessary to me.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4707)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/webpack.common.js, line 68 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4707#-Mj56buk-A7Zgj4PW4Xz:-Mj56yzg26z04foIqMOm:b-xd5cyt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/632d47fcc3c50c2c54a210ea200bcef487ecad37/src/BloomBrowserUI/webpack.common.js#L68)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

This is a duplicate of 3 lines above it. It doesn't seem necessary to me.
</blockquote></details>

Introduced recently: https://github.com/BloomBooks/BloomDesktop/commit/95a76efafe6b88caa034fcb223653c54823db2f1

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4707)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx, line 185 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4707#-Mj5E6Oy5ZNrLXdaOKF7:-Mj5E6Oy5ZNrLXdaOKF8:b-acwn3k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/60290315fec01a90ec831261221c0bf132f258ca/src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx#L185)):*
> ```XML
>     // Designed to be invoked from WinForms land.
>     return (
>         <Dialog
> ```

Going forward, we want to use `<BloomDialog>` instead, as that allows us to have a more common look & feel. Not a deal-breaker for this PR, though.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4707)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1810 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4707#-Mj5ET9D3N_wZSQAv129:-Mj5ET9D3N_wZSQAv12A:blutah3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/60290315fec01a90ec831261221c0bf132f258ca/src/BloomExe/CollectionTab/LibraryListView.cs#L1810)):*
> ```Smalltalk
> 		/// <summary>Brings up a dialog that says it requires Bloom Enterprise and provides a button to the settings</summary>
> 		/// <param name="title">The title of the new window. Optional - the title isn't very discoverable at all</param>
> 		private void ShowRequiresEnterpriseNotice(string title = null)
> ```

Seems like this is a more general thing than just for Collection tab stuff? So this could go in its own file.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4707)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx, line 185 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4707#-Mj5E6Oy5ZNrLXdaOKF7:-MjFPw0r7dUHYBhXC3BK:b-e8sll6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/60290315fec01a90ec831261221c0bf132f258ca/src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx#L185)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Going forward, we want to use `<BloomDialog>` instead, as that allows us to have a more common look & feel. Not a deal-breaker for this PR, though.
</blockquote></details>

Sure. Got it to work. Doesn't change the look and feel for this one though, and code is more complicated to trace now
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1810 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4707#-Mj5ET9D3N_wZSQAv129:-MjF9Vfl1yR2HnE5R2Ro:b-o156rk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/60290315fec01a90ec831261221c0bf132f258ca/src/BloomExe/CollectionTab/LibraryListView.cs#L1810)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Seems like this is a more general thing than just for Collection tab stuff? So this could go in its own file.
</blockquote></details>

Made a new file MiscUI\Enterprise.cs

**Review by JohnThomson — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4707)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton)

**Pull request merged**
