### PR TITLE
BL-4878 Improve computation of version code

### PR DESCRIPTION
**Pull request by JohnThomson**
Ignores insignificant whitespace changes and element id changes (as are made by BringBookUpToDate(), even when no editing has occurred)

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1797)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Publish/BloomReaderPublisher.cs, line 201 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1797#-Krbjym5nohADzl42st9:-Krbjym60kdiGmJKE_Fn:b-z1im9b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/382159054c34c3b76e3a1899196dde4c8d2ac66f/src/BloomExe/Publish/BloomReaderPublisher.cs#L201)):*
> ```Smalltalk
> 
> 			var publishedFileName = book.Title + BookCompressor.ExtensionForDeviceBloomBook;
> 			using (var bloomdTempFile = TempFile.WithFilenameInTempFolder(BookStorage.SanitizeNameForFileSystem(publishedFileName)))
> ```

This is an unrelated fix for a bug I came across while working on this problem.

---

*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 110 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1797#-Krbk3okAyj-PHE-Ehu_:-Krbk3okAyj-PHE-Ehua:b-c7s5gf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/382159054c34c3b76e3a1899196dde4c8d2ac66f/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L110)):*
> ```Smalltalk
> 		private void SendBookTo(Book.Book book, string androidIpAddress)
> 		{
> 			try
> ```

This is more-or-less unrelated, too. Bloom seems to eat all exceptions on the thread that is publishing the books. This at least lets developers encounter them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1797)*

**Comment by gmartin7** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 105 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1797#-KrbwDNTdUPSvLWf4RoS:-KrbwDNTdUPSvLWf4RoT:b-4uq2cx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/382159054c34c3b76e3a1899196dde4c8d2ac66f/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L105)):*
> ```Smalltalk
> 			simplified = new Regex("(<[^>]*)\\s*id\\s*=\\s*(['\"]).*?\\2\\s*([^>]*>)").Replace(simplified, "$1$3");
> 			var bytes = Encoding.UTF8.GetBytes(simplified);
> 			return Convert.ToBase64String(SHA256Managed.Create().ComputeHash(bytes));
> ```

So you've been able to avoid worrying about xmatter by ignoring the page id?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1797#-:-KrbvKavtBhmwLQxcVFO:bnfp4nl)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 116 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1797#-KrcH3_103C5oA95XGfz:-KrcH3_103C5oA95XGg-:blcofn4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/382159054c34c3b76e3a1899196dde4c8d2ac66f/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L116)):*
> ```Smalltalk
> 			catch (Exception e)
> 			{
> 				Debug.Fail("got exception " + e.Message + " sending book");
> ```

Maybe a comment on why you don't want to or cannot use the normal user-accessible error system.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1797)*

**Comment by JohnThomson** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 105 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1797#-KrbwDNTdUPSvLWf4RoS:-Krfa_TIEcmQ889An_HJ:b-48tw8p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/382159054c34c3b76e3a1899196dde4c8d2ac66f/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L105)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

So you've been able to avoid worrying about xmatter by ignoring the page id?
</blockquote></details>

Right. By experiment, the only changes Bloom was making between one version of the book and another (unedited) one were page IDs and whitespace.
Can't promise we won't encounter some other case where we're still too picky, but the worst case is one unnecessary local download per publish cycle.

---

*[src/BloomExe/web/controllers/PublishToAndroidApi.cs, line 116 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1797#-KrcH3_103C5oA95XGfz:-KrfdhxKEOme_F35aaQm:b1k4gom) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/382159054c34c3b76e3a1899196dde4c8d2ac66f/src/BloomExe/web/controllers/PublishToAndroidApi.cs#L116)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Maybe a comment on why you don't want to or cannot use the normal user-accessible error system.
</blockquote></details>

Mostly I was being lazy. It wasn't part of this task, just something I added to help me try to figure out why one book wouldn't transfer. It wasn't very obvious what reporting method should be used on a background thread that eats exceptions somehow. I've attempted an improvement, though since I fixed the original bug it isn't very obvious how to test it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1797)*

**Pull request merged**
