### PR TITLE
[5.4] BL-12396 Guatemala branding #1

### PR DESCRIPTION
**Pull request by gmartin7**
* mostly affects Credits page
* waiting on response from Chris

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5972)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
I know this is mostly copied from another branding/xmatter.
Anything to review in particular?

> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5972#-:-NZT4oSW41dFhtNo1rUv:bz2mwz9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Review by gmartin7 — COMMENTED** [review]
Copied some yes. We'll shortly have another branding using the same xmatter (which will get commented in the later PR w/ the second branding). Mostly review the part that has 2 logos at the top of the credits page followed by a text block under those logos.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5972#-:-NZTBzQN2bzDu47lJGIr:b-pnxhg4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Review by gmartin7 — COMMENTED** [review]
Moved the comments I referred to above into this PR.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5972#-:-NZX30Gt1NoRiK8tyVGF:b6vn27j)* status: 8 of 13 files reviewed, all discussions resolved (waiting on @andrew-polk)

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5972)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/content/branding/Guatemala-RTI-GBEQT/branding.json` line 32 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5972#-NZXHbFTElbeTzh82gBf:-NZXHbFU8_zNgsa2U_rT:bbv29y0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/88900ff323a85ba18835a7dd341be245d7d9ab8a/src/content/branding/Guatemala-RTI-GBEQT/branding.json#L32)):*
> ```JSON
>             "content": "",
>             "condition": "always"
>         },
> ```

Is there a reason we need three slots for credits-page-branding-top? i.e. `top-middle`, `top-left`, `top-right`?
Can there just be a top which contains all the bits?
We're trying to just have certain slots in the xmatter which the branding can fill in. If those slots can be standard across xmatters, that's much better.
So anytime we introduce a new slot, we need to evaluate whether it is really necessary.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5972)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/content/branding/Guatemala-RTI-GBEQT/branding.json` line 32 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5972#-NZXHbFTElbeTzh82gBf:-NZXuzGm8MmMA3VCfOpf:bpszhva) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/88900ff323a85ba18835a7dd341be245d7d9ab8a/src/content/branding/Guatemala-RTI-GBEQT/branding.json#L32)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is there a reason we need three slots for credits-page-branding-top? i.e. `top-middle`, `top-left`, `top-right`?
Can there just be a top which contains all the bits?
We're trying to just have certain slots in the xmatter which the branding can fill in. If those slots can be standard across xmatters, that's much better.
So anytime we introduce a new slot, we need to evaluate whether it is really necessary.
</blockquote></details>

Hmm... I'll have to think about that. It may be that I can get away with the one slot... and no new xmatter. The main reason for the extra xmatter was just to handle the extra slots, so... I'll look at that tomorrow.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5972)* status: 7 of 13 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/content/branding/Guatemala-RTI-GBEQT/branding.json` line 32 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5972#-NZXHbFTElbeTzh82gBf:-NZbgJth8CgRYDtU6KeN:bzf0jot) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/88900ff323a85ba18835a7dd341be245d7d9ab8a/src/content/branding/Guatemala-RTI-GBEQT/branding.json#L32)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Hmm... I'll have to think about that. It may be that I can get away with the one slot... and no new xmatter. The main reason for the extra xmatter was just to handle the extra slots, so... I'll look at that tomorrow.
</blockquote></details>

Rearranged things significantly. How's that?

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5972)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

___
*[`src/content/branding/Guatemala-RTI-GBEQT/branding.json` line 32 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5972#-NZXHbFTElbeTzh82gBf:-N_-s1Fk2-H32SEkFYwb:bbquct2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/88900ff323a85ba18835a7dd341be245d7d9ab8a/src/content/branding/Guatemala-RTI-GBEQT/branding.json#L32)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Rearranged things significantly. How's that?
</blockquote></details>

Seems to greatly simplify things. Thanks.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5972)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
