### PR TITLE
Allow user to rename book independent of title (BL-10056)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4623)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4623)* status: 7 of 8 files reviewed, 6 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Book/Book.cs, line 4258 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4623#-MfjFUevD43ieZWUULKt:-MfjFUevD43ieZWUULKu:bu8cvac) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0869e67dd0499846466508a5daa96eca8ddf247/src/BloomExe/Book/Book.cs#L4258)):*
> ```Smalltalk
> 		/// </summary>
> 		/// <param name="newName"></param>
> 		public void SetUserName(string newName)
> ```

I expect such a method to set something called "userName".

How about SetAndLockBookName? or SetBookNameByUserAction? Or SetNameByUserChoice? or similar
___
*[src/BloomExe/Book/Book.cs, line 4273 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4623#-MfjGiGg2YH5Lk0DYXBq:-MfjGiGh9UNoS3g98ikr:bsi6izh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0869e67dd0499846466508a5daa96eca8ddf247/src/BloomExe/Book/Book.cs#L4273)):*
> ```Smalltalk
> 				BookInfo.Save();
> 			}
> 		}
> ```

I suppose you've already thought through this, and the logic is probably already there in Storage.SetBookName(newName) and Storage.UpdateBookFileAndFolderName(CollectionSettings);
but I'm a little surprised we don't have to do any further checking for folder name collisions.
___
*[src/BloomExe/Book/Book.cs, line 4274 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4623#-MfjH3uP-RxJPGxNQKNX:-MfjH3uP-RxJPGxNQKNY:bddx9np) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0869e67dd0499846466508a5daa96eca8ddf247/src/BloomExe/Book/Book.cs#L4274)):*
> ```Smalltalk
> 			}
> 		}
> 	}
> ```

Seems like you might be able to add a few useful unit tests?
For SetUserName and TitleBestForUserDisplay at least?
Maybe even Save/SavePage?

No heroics necessary, though.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1801 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4623#-MfjIFia9R3nrCUA0f4m:-MfjIFia9R3nrCUA0f4n:b-1wq9jk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0869e67dd0499846466508a5daa96eca8ddf247/src/BloomExe/CollectionTab/LibraryListView.cs#L1801)):*
> ```Smalltalk
> 
> 		public void HandleRenameCommand() {
> 			var button = SelectedButton;
> ```

Probably a dumb question, but is LibraryListView just the top left portion?
I just want to be sure F2 doesn't allow you access this feature on books in the lower left.
___
*[src/BloomExe/CollectionTab/LibraryListView.Designer.cs, line 684 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4623#-MfjDe4z-0nLwzy6lVVV:-MfjDe5--kS8igmjRm6Q:b-6hc66j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0869e67dd0499846466508a5daa96eca8ddf247/src/BloomExe/CollectionTab/LibraryListView.Designer.cs#L684)):*
> ```Smalltalk
> 			this._L10NSharpExtender.SetLocalizableToolTip(this.renameToolStripMenuItem, null);
> 			this._L10NSharpExtender.SetLocalizationComment(this.renameToolStripMenuItem, null);
> 			this._L10NSharpExtender.SetLocalizingId(this.renameToolStripMenuItem, ".renameToolStripMenuItem");
> ```

I think this wants to have a real ID and for that to be added to the xlf file.

(Looks like the excel export does to.)
___
*[src/BloomExe/Workspace/WorkspaceView.cs, line 241 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4623#-MfjDs8p-ELsHghw5FwI:-MfjDs8p-ELsHghw5FwJ:b-j1jqpe) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0869e67dd0499846466508a5daa96eca8ddf247/src/BloomExe/Workspace/WorkspaceView.cs#L241)):*
> ```Smalltalk
> 			if (CurrentTabView == _legacyCollectionView)
> 				_legacyCollectionView.HandleRenameCommand();
> 		}
> ```

Did you make a note somewhere to be sure we implement this in the new tab at some point?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4623)* status: 4 of 10 files reviewed, 6 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/Book/Book.cs, line 4258 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4623#-MfjFUevD43ieZWUULKt:-MfmOPP2DbQOz9kToV1A:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0869e67dd0499846466508a5daa96eca8ddf247/src/BloomExe/Book/Book.cs#L4258)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I expect such a method to set something called "userName".

How about SetAndLockBookName? or SetBookNameByUserAction? Or SetNameByUserChoice? or similar
</blockquote></details>

Done.
___
*[src/BloomExe/Book/Book.cs, line 4273 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4623#-MfjGiGg2YH5Lk0DYXBq:-MfmOTR8AJPbB-uJEi2W:b-j4mo77) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0869e67dd0499846466508a5daa96eca8ddf247/src/BloomExe/Book/Book.cs#L4273)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I suppose you've already thought through this, and the logic is probably already there in Storage.SetBookName(newName) and Storage.UpdateBookFileAndFolderName(CollectionSettings);
but I'm a little surprised we don't have to do any further checking for folder name collisions.
</blockquote></details>

Yes, UpdateBookFileAndFolderName does this.
___
*[src/BloomExe/Book/Book.cs, line 4274 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4623#-MfjH3uP-RxJPGxNQKNX:-Mfmex8y6f4xjyBOPQqN:b4l328) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0869e67dd0499846466508a5daa96eca8ddf247/src/BloomExe/Book/Book.cs#L4274)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems like you might be able to add a few useful unit tests?
For SetUserName and TitleBestForUserDisplay at least?
Maybe even Save/SavePage?

No heroics necessary, though.
</blockquote></details>

I made some attempt to at least test the new behavior
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1801 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4623#-MfjIFia9R3nrCUA0f4m:-MfmOo6p8HICFWAcYgmg:b-egr3p7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0869e67dd0499846466508a5daa96eca8ddf247/src/BloomExe/CollectionTab/LibraryListView.cs#L1801)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Probably a dumb question, but is LibraryListView just the top left portion?
I just want to be sure F2 doesn't allow you access this feature on books in the lower left.
</blockquote></details>

Good catch. I didn't even think of that. Was doing something really strange. Fixed.
___
*[src/BloomExe/CollectionTab/LibraryListView.Designer.cs, line 684 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4623#-MfjDe4z-0nLwzy6lVVV:-MfmSBal3CsuboOqox3k:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0869e67dd0499846466508a5daa96eca8ddf247/src/BloomExe/CollectionTab/LibraryListView.Designer.cs#L684)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this wants to have a real ID and for that to be added to the xlf file.

(Looks like the excel export does to.)
</blockquote></details>

Done.
___
*[src/BloomExe/Workspace/WorkspaceView.cs, line 241 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4623#-MfjDs8p-ELsHghw5FwI:-MfmSExX88jWq5LOw4mq:bjzdreo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0869e67dd0499846466508a5daa96eca8ddf247/src/BloomExe/Workspace/WorkspaceView.cs#L241)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Did you make a note somewhere to be sure we implement this in the new tab at some point?
</blockquote></details>

The whole menu is a ToDo in the new tab at this point, so I didn't think we needed a separate task for this item.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4623)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4623)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
