### PR TITLE
BL-6381 stage 2 of enterprise settings

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721)

### CODE REVIEW

**Review by andrew-polk — APPROVED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 11 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721#-LLbBvPREZn3Q4Uc2Ps8:-LLbBvPREZn3Q4Uc2Ps9:b-xhdx1j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9b00816cfef33f0e0b0471bbd856f9b902c704be/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L40)):*
> ```XML
>     // where the dialog is brought up when the collection is opened because
>     // its saved branding is not validated by a subscriptionCode. Gets inserted into
>     // the message and the code box.
> ```

If the code is good, don't we still show it (and allow people to copy it to give to a colleague)? If so, I would expect this to just be the same as subscription code, and what we just need to leave it to several states of the state machine to indicate that we have a code and it is invalid for  one of several reasons.
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 56 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721#-LLbBRADE3JhBV7E9CzM:-LLbBRADE3JhBV7E9CzN:b-arhkdk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9b00816cfef33f0e0b0471bbd856f9b902c704be/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L56)):*
> ```XML
> 
>     public componentDidMount() {
>         BloomApi.get("settings/enterpriseStatus", result => {
> ```

Is there an advantage to three separate endpoints, vs. one that returns the 3 pieces of data you need? 
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 398 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721#-LLbDV4QBQGNANOas7Ui:-LLbDV4QBQGNANOas7Uj:blloce4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9b00816cfef33f0e0b0471bbd856f9b902c704be/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L398)):*
> ```XML
> 
>     private onCopy() {
>         BloomApi.postJson("settings/copy", {
> ```

I think copy is generic and could go into commonapi instead?
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 404 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721#-LLbEAjN5mfo5Rq_IMVx:-LLbEAjN5mfo5Rq_IMVy:b-5vrnla) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9b00816cfef33f0e0b0471bbd856f9b902c704be/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L404)):*
> ```XML
> 
>     private checkForUpdates() {
>         BloomApi.post("settings/checkForUpdates");
> ```

Doesn't seem related to settings. CommonAPI?
___
*[src/BloomExe/web/controllers/CollectionSettingsApi.cs, line 74 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721#-LLbGOUh0hs0EZprJunM:-LLbGOUh0hs0EZprJunN:b4jp2z1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9b00816cfef33f0e0b0471bbd856f9b902c704be/src/BloomExe/web/controllers/CollectionSettingsApi.cs#L74)):*
> ```Smalltalk
> 			server.RegisterEndpointHandler(kApiUrlPart + "invalidBranding",
> 				request => { request.ReplyWithText(InvalidBranding ?? ""); }, false);
> 			server.RegisterEndpointHandler(kApiUrlPart + "paste",
> ```

copy and paste and checkForUpdates can move to commonapi

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721)* status: 8 of 14 files reviewed, 5 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721#-LLbBvPREZn3Q4Uc2Ps8:-LLe75O-4T_bsHkJZMsA:b-ays21q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9b00816cfef33f0e0b0471bbd856f9b902c704be/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L40)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

If the code is good, don't we still show it (and allow people to copy it to give to a colleague)? If so, I would expect this to just be the same as subscription code, and what we just need to leave it to several states of the state machine to indicate that we have a code and it is invalid for  one of several reasons.
</blockquote></details>

This is never used when the code is good. Most typically, it is used when there is NO code, but (from older Blooms) we do have a saved branding. It can also come up when there is a saved branding and expired code, though we could indeed do without it in that case. Conceivably there could also be an invalid code, though I think that could only come about as a result of hand-editing of the .bloomCollection file.
It's possible that we could have the back end insert the invalid branding into the subscription code, but we'd then need something else to trigger the appearance of the orange "older version of Bloom" message.
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 56 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721#-LLbBRADE3JhBV7E9CzM:-LLeCcKk2c3TNxlJ6yR3:b-xmg86n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9b00816cfef33f0e0b0471bbd856f9b902c704be/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L56)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is there an advantage to three separate endpoints, vs. one that returns the 3 pieces of data you need? 
</blockquote></details>

Mostly that I had already created them and don't have to decode a complex result. Also, two of them have POST variations parallel to the GET ones used here. It might be an improvement, but didn't seem obviously enough so to be worth redoing. I can if you want.
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 398 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721#-LLbDV4QBQGNANOas7Ui:-LLeD1hoDBbWq5TJUzgZ:baf9blj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9b00816cfef33f0e0b0471bbd856f9b902c704be/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L398)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think copy is generic and could go into commonapi instead?
</blockquote></details>

Don't know how I missed that. I remember looking for something like CommonApi and not finding it. I moved it (and paste) there, and merged them into a single api which can get or set clipboardText (which I find clearer; I kept getting confused about whether I should use copy or paste)
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 404 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721#-LLbEAjN5mfo5Rq_IMVx:-LLeIqIw-qDoJ0QAlprW:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9b00816cfef33f0e0b0471bbd856f9b902c704be/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L404)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Doesn't seem related to settings. CommonAPI?
</blockquote></details>

Done.
___
*[src/BloomExe/web/controllers/CollectionSettingsApi.cs, line 74 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721#-LLbGOUh0hs0EZprJunM:-LLeIsbf3wqUEIOCoCD7:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9b00816cfef33f0e0b0471bbd856f9b902c704be/src/BloomExe/web/controllers/CollectionSettingsApi.cs#L74)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

copy and paste and checkForUpdates can move to commonapi
</blockquote></details>

Done.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721)* status: 8 of 14 files reviewed, 5 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721#-LLbBvPREZn3Q4Uc2Ps8:-LLeKFkAB-5FPAxW829I:bzenhx3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9b00816cfef33f0e0b0471bbd856f9b902c704be/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L40)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This is never used when the code is good. Most typically, it is used when there is NO code, but (from older Blooms) we do have a saved branding. It can also come up when there is a saved branding and expired code, though we could indeed do without it in that case. Conceivably there could also be an invalid code, though I think that could only come about as a result of hand-editing of the .bloomCollection file.
It's possible that we could have the back end insert the invalid branding into the subscription code, but we'd then need something else to trigger the appearance of the orange "older version of Bloom" message.
</blockquote></details>

Ah, so what I tripped over (as always) is just the name.  Things can be invalid for many reasons. If it were "legacyBrandingName", all would be clear.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721)* status: 8 of 14 files reviewed, 5 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 56 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721#-LLbBRADE3JhBV7E9CzM:-LLeKd5jDWUMgGuj3z-U:b-wapmzm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9b00816cfef33f0e0b0471bbd856f9b902c704be/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L56)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Mostly that I had already created them and don't have to decode a complex result. Also, two of them have POST variations parallel to the GET ones used here. It might be an improvement, but didn't seem obviously enough so to be worth redoing. I can if you want.
</blockquote></details>

Would it be a complex result? I would have thought you'd have something like 

    this.setState(result.data);

where ``result.data`` equals {code: 'ldkfsdlfjdlk', etc.}

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721)* status: 8 of 14 files reviewed, 5 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721#-LLbBvPREZn3Q4Uc2Ps8:-LLeWy7j0ipDkfFyvfKu:b-52pqnh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9b00816cfef33f0e0b0471bbd856f9b902c704be/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L40)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Ah, so what I tripped over (as always) is just the name.  Things can be invalid for many reasons. If it were "legacyBrandingName", all would be clear.
</blockquote></details>

I've switched to using that name, though it involved several changes to avoid using a variable called legacyBrandingName for an invalid branding that is NOT legacy (e.g., expired). I think on the whole it does make things clearer.
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 56 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721#-LLbBRADE3JhBV7E9CzM:-LLeLfcx9ITM2AtSa08_:bzcrt52) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9b00816cfef33f0e0b0471bbd856f9b902c704be/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L56)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Would it be a complex result? I would have thought you'd have something like 

    this.setState(result.data);

where ``result.data`` equals {code: 'ldkfsdlfjdlk', etc.}
</blockquote></details>

Unless we move a lot of logic into C#, I'd need to extract status, code, and legacyBrandingName from the object and then call setControlState. Not a big deal, just not that much simpler, and I kind of like the symmetry of the get/post on two of the properties. But I can add the new API if you like.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721)* status: all files reviewed, 5 unresolved discussions (waiting on @hatton)

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721#-LLbBvPREZn3Q4Uc2Ps8:-LLegOFbCFWG91LE35AN:butaxgg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9b00816cfef33f0e0b0471bbd856f9b902c704be/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L40)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I've switched to using that name, though it involved several changes to avoid using a variable called legacyBrandingName for an invalid branding that is NOT legacy (e.g., expired). I think on the whole it does make things clearer.
</blockquote></details>

Confession: Later on my walk I was thinking that my previous self actually probably did mean that the subscription code could contain this same value, just with a state-machine state saying that we recognize it as a legacy branding. But that's irrelevant really, just wanted to admit my flakiness!
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 56 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721#-LLbBRADE3JhBV7E9CzM:-LLeh0smAXiZHqffVNXt:bv3524o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9b00816cfef33f0e0b0471bbd856f9b902c704be/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L56)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Unless we move a lot of logic into C#, I'd need to extract status, code, and legacyBrandingName from the object and then call setControlState. Not a big deal, just not that much simpler, and I kind of like the symmetry of the get/post on two of the properties. But I can add the new API if you like.
</blockquote></details>

Yeah... one of these things where it's fine, but I really hope future devs do it the simpler way. I hate this pressure of needing to code review for the future that comes with the constant "well I just copied the closest thing I found"...

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2721)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
