### PR TITLE
Control experimental template with tool as feature (BL-6047)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2530)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

---

*[src/BloomExe/CollectionTab/LibraryListView.cs, line 563 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2530#-LFso7ai2KZWAdIszM_M:-LFso7ai2KZWAdIszM_N:b-hh408n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a33c1f8c52025fc67f41bd41a2a51621c458c220/src/BloomExe/CollectionTab/LibraryListView.cs#L563)):*
> ```Smalltalk
> 					// Hide the experimental book if it has an assigned tool that isn't guaranteed to be visible itself (BL-6047).
> 					(Settings.Default.ShowExperimentalBooks && (String.IsNullOrEmpty(bookInfo.CurrentTool) || Settings.Default.ShowExperimentalFeatures)) ||
> 					(!String.IsNullOrEmpty(bookInfo.CurrentTool) && Settings.Default.ShowExperimentalFeatures);
> ```

This is difficult to figure the net effect of. I think we're saying,
if (!bookInfo.IsExperimental)
    return true; // this is all about usually hiding experimental books, this one isn't.
if (!Settings.Default.ShowExperimentalBooks)
    return false;  // and if we don't want to see any of them, we don't want this, since it is.
// OK, in general we want to see this experimental book
if (String.IsNullOrEmpty(bookInfo.CurrentTool))
    return true; // doesn't need any particular tool, go ahead and show it
if (Settings.Default.ShowExperimentalFeatures)
    return true; // The tool it needs will be available, show it
return false; // needs a (presumably experimental?) tool that isn't enabled
I would find that more readable, and it wouldn't leave me wondering why the last test in the expression above includes the sub-test for having a current tool.

What happens to a book which documents that it needs the sign language tool when someone opens it in Bloom 4.4, where the sign language tool is no longer experimental, and experimental tools are turned off?

Is it a problem that we will be able to open a sign language book, even without experimental features, if the previous user happens to have saved with the toolbox closed? Or is CurrentTool set even when the toolbox is closed?

Will it be impossible to open a picture dictionary without experimental features, even though it doesn't need any, if someone used a tool (e.g., talking book) on it? Or at least if they left that tool open when closing the book?

Seems to me that we need a way to document that a book needs a particular tool (whether or not it is current) and whether a particular tool is experimental (in the current version of Bloom).

---

*[src/BloomExe/web/controllers/PageTemplatesApi.cs, line 298 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2530#-LFsrMiCAfh-qfsILMa2:-LFsrMiCAfh-qfsILMa3:bs3an4h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a33c1f8c52025fc67f41bd41a2a51621c458c220/src/BloomExe/web/controllers/PageTemplatesApi.cs#L298)):*
> ```Smalltalk
> 		/// the user wants to see pages from this template based on the collection settings.
> 		/// </summary>
> 		private static bool EnabledTemplate(string path)
> ```

Is this supposed to give the same answers as LibraryListView.ShowThisBook? If so, can we combine somehow? What about putting the main logic in a method of BookInfo, and then this method could read the meta.json into a BookInfo and ask that?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2530)*

**Comment by JohnThomson** [comment]
This has gotten complicated and I still don't think it's right. The option of having a single button that controls experimental templates and features appeals more and more.

If this only affects ability to use templates we ship (not the resulting books) it might be OK.

---

Review status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2530#-:-LFsuk85DugoQtB4Aa7v:bt217xx)*

**Comment by hatton** [comment]
A big part of the problem appears to be that we have separate controls for experimental tools and experimental templates. Let's get rid of that distinction.

**Comment by StephenMcConnel** [comment]
Combining the two checkboxes into one was pretty much the conclusion I was tending toward.

---

Review status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @JohnThomson and @StephenMcConnel)

---

*[src/BloomExe/CollectionTab/LibraryListView.cs, line 563 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2530#-LFso7ai2KZWAdIszM_M:-LFwsIDnBdAeFDeEXIBt:b2mesbd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a33c1f8c52025fc67f41bd41a2a51621c458c220/src/BloomExe/CollectionTab/LibraryListView.cs#L563)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This is difficult to figure the net effect of. I think we're saying,
if (!bookInfo.IsExperimental)
    return true; // this is all about usually hiding experimental books, this one isn't.
if (!Settings.Default.ShowExperimentalBooks)
    return false;  // and if we don't want to see any of them, we don't want this, since it is.
// OK, in general we want to see this experimental book
if (String.IsNullOrEmpty(bookInfo.CurrentTool))
    return true; // doesn't need any particular tool, go ahead and show it
if (Settings.Default.ShowExperimentalFeatures)
    return true; // The tool it needs will be available, show it
return false; // needs a (presumably experimental?) tool that isn't enabled
I would find that more readable, and it wouldn't leave me wondering why the last test in the expression above includes the sub-test for having a current tool.

What happens to a book which documents that it needs the sign language tool when someone opens it in Bloom 4.4, where the sign language tool is no longer experimental, and experimental tools are turned off?

Is it a problem that we will be able to open a sign language book, even without experimental features, if the previous user happens to have saved with the toolbox closed? Or is CurrentTool set even when the toolbox is closed?

Will it be impossible to open a picture dictionary without experimental features, even though it doesn't need any, if someone used a tool (e.g., talking book) on it? Or at least if they left that tool open when closing the book?

Seems to me that we need a way to document that a book needs a particular tool (whether or not it is current) and whether a particular tool is experimental (in the current version of Bloom).
</blockquote></details>

This has been greatly simplified (essentially back to the original simplicity) by combining the two two experimental checkboxes.

---

*[src/BloomExe/web/controllers/PageTemplatesApi.cs, line 298 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2530#-LFsrMiCAfh-qfsILMa2:-LFwsFme2lhMHOarLTak:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a33c1f8c52025fc67f41bd41a2a51621c458c220/src/BloomExe/web/controllers/PageTemplatesApi.cs#L298)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is this supposed to give the same answers as LibraryListView.ShowThisBook? If so, can we combine somehow? What about putting the main logic in a method of BookInfo, and then this method could read the meta.json into a BookInfo and ask that?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2530#-:-LFswaUGDpgbyN4NcpUb:b-ihwuv)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2530#-:-LG0RtWSB_n2JU7V2bQ3:bnfp4nl)*

**Pull request merged**
