### PR TITLE
Less http-intensive palette supply to ckedit, better & localized default label

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5360)

### CODE REVIEW

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5360)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/Bloom.xlf` line  at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5360#-NAfMGYL7QYlneox9Xrs:-NAfOSonEW0_zNNETvyP:b-dbp5wx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f56b5e656686f2b7de18fd0d7c9853689df3ed43/DistFiles/localization/en/Bloom.xlf#L)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Reviewable thinks almost every line in this file is modified.
It isn't even distinguishing it as a whitespace change.
Line endings, maybe? Actually, it looks like indentation, but then I don't know why Reviewable doesn't just flag the whitespace change.
Hm. For part of the file it does.
</blockquote></details>

Yeah, so there are separate commits so that you can review.
___
*[`src/BloomBrowserUI/lib/ckeditor/plugins/colorbutton/plugin.js` line 229 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5360#-NAfLrj3-kbft9o-AhPy:-NAfO6wG-zXqwDgntlsM:b-14yupw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f56b5e656686f2b7de18fd0d7c9853689df3ed43/src/BloomBrowserUI/lib/ckeditor/plugins/colorbutton/plugin.js#L229)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

As far as I can guess, these are the only two lines changed here.
Seems like we need some kind of system for tracking custom changes (which I have a vague recollection we do...).
At the very least, maybe a comment at the top of the file?
Otherwise, the next time we upgrade the plugin, we'll lose this change.
</blockquote></details>

JT added several *hundred* lines to it recently, so I was under the impression that this is just a file we own/maintain.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5360)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`DistFiles/localization/en/Bloom.xlf` line  at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5360#-NAfMGYL7QYlneox9Xrs:-NAfRYza99300p58wceX:b-rjrvt1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f56b5e656686f2b7de18fd0d7c9853689df3ed43/DistFiles/localization/en/Bloom.xlf#L)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Yeah, so there are separate commits so that you can review.
</blockquote></details>

I see the two commits for plugin.js but not this one.
___
*[`src/BloomBrowserUI/lib/ckeditor/plugins/colorbutton/plugin.js` line 229 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5360#-NAfLrj3-kbft9o-AhPy:-NAfQgw4EyhdPHEQj8ED:b-46js7g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f56b5e656686f2b7de18fd0d7c9853689df3ed43/src/BloomBrowserUI/lib/ckeditor/plugins/colorbutton/plugin.js#L229)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

JT added several *hundred* lines to it recently, so I was under the impression that this is just a file we own/maintain.
</blockquote></details>

You might be thinking of another file?
This one was added when he added the color button. And I might be wrong, but I assumed it came as is from ckeditor.

@johnthomson Do you remember if you made any modifications to this file when you added it? And do you remember if there is a place to document such modifications?

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5360)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[`DistFiles/localization/en/Bloom.xlf` line  at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5360#-NAfMGYL7QYlneox9Xrs:-NAfVFWu3FrhSIadkkUg:b630x8i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f56b5e656686f2b7de18fd0d7c9853689df3ed43/DistFiles/localization/en/Bloom.xlf#L)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I see the two commits for plugin.js but not this one.
</blockquote></details>

If you open it and touch something, does it go back? Otherwise, seems best to let the format be.
___
*[`src/BloomBrowserUI/lib/ckeditor/plugins/colorbutton/plugin.js` line 229 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5360#-NAfLrj3-kbft9o-AhPy:-NAfVpdcCjS6OERglGNF:bm2ec8l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f56b5e656686f2b7de18fd0d7c9853689df3ed43/src/BloomBrowserUI/lib/ckeditor/plugins/colorbutton/plugin.js#L229)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

You might be thinking of another file?
This one was added when he added the color button. And I might be wrong, but I assumed it came as is from ckeditor.

@johnthomson Do you remember if you made any modifications to this file when you added it? And do you remember if there is a place to document such modifications?
</blockquote></details>

Oh, I see.  I think it's all fine.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5360)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`DistFiles/localization/en/Bloom.xlf` line  at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5360#-NAfMGYL7QYlneox9Xrs:-NAfb0Il7Pyy0l71hjEA:b7gl99b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f56b5e656686f2b7de18fd0d7c9853689df3ed43/DistFiles/localization/en/Bloom.xlf#L)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

If you open it and touch something, does it go back? Otherwise, seems best to let the format be.
</blockquote></details>

No; apparently I don't have anything set in vscode to format xlf files, so even if it try to make it format, it won't.
The last couple times you've touched this file, it appears it has thrashed on whitespace, but it appears to be back to what it was before those, so hopefully it is stable now.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5360)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hatton)

___
*[`src/BloomBrowserUI/lib/ckeditor/plugins/colorbutton/plugin.js` line 229 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5360#-NAfLrj3-kbft9o-AhPy:-NAfdtB78_O8FFR_mu48:bdjofx9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f56b5e656686f2b7de18fd0d7c9853689df3ed43/src/BloomBrowserUI/lib/ckeditor/plugins/colorbutton/plugin.js#L229)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Oh, I see.  I think it's all fine.
</blockquote></details>

Looks like the comment in config.js stating which branch we got our plugins from might be suffient.

**Comment by andrew-polk** [comment]
These commits already got merged separate from the PR. Closing.

**Pull request closed without merging**
