### PR TITLE
BL-7253 Optimize Save Page when rest of file unchanged

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245)

### CODE REVIEW

**Comment by hatton** [comment]
Alternatively, could we just say the Bloom is not appropriate for large books?

**Comment by JohnThomson** [comment]
Yes, that's possible, of course. I hate to do it to someone who's spent many hours crafting a 200+ page book, but maybe the cost of optimizing for this is too high. Maybe one day (soon?) we can offer a folio book option.

**Comment by JohnThomson** [comment]
We're tentatively going to hold this until 4.7. May do some review before then.

**Review by StephenMcConnel — CHANGES_REQUESTED** [review]
Looks generally okay.  I have a couple of suggestions, and a few minor comments that can be ignored.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-:-LiE_0kM3NE6GuELtcYS:byp8mrt)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Book/Book.cs, line 2416 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-LiEE6VqEWkl_IyxsCZQ:-LiEE6VrEIVa3zt20oFe:blag1zs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32476b04e5303236c4d0d7f2d9e36212adc4277e/src/BloomExe/Book/Book.cs#L2416)):*
> ```Smalltalk
> 				// page changed during editing. If that's so we can skip this step.
> 				if (!canJustWritePage)
> 					_bookData.SuckInDataFromEditedDom(editedPageDom); //this will do an updatetitle
> ```

I think this step should come after optionally setting the user modified styles since that step can change the value of canJustWritePage.   Am I overlooking something?
___
*[src/BloomExe/Book/Book.cs, line 2879 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-LiEEgg8AdrmTZX-0xK8:-LiEEgg8AdrmTZX-0xK9:b-4r31kb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32476b04e5303236c4d0d7f2d9e36212adc4277e/src/BloomExe/Book/Book.cs#L2879)):*
> ```Smalltalk
> 		public void SaveForPageChanged(string pageId, XmlElement modifiedPage)
> 		{
> 			_storage.SaveForPageChanged(pageId, modifiedPage);
> ```

Should this have one or both of the Guard.Against() calls from Save()?  Just asking, it's up to you to decide.
___
*[src/BloomExe/Book/BookStorage.cs, line 404 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-LiEJvLM8Rcr7dy1Qo2P:-LiEJvLM8Rcr7dy1Qo2Q:byq6buk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32476b04e5303236c4d0d7f2d9e36212adc4277e/src/BloomExe/Book/BookStorage.cs#L404)):*
> ```Smalltalk
> 		/// </summary>
> 		/// <param name="pageId"></param>
> 		/// <param name="modifiedPage"></param>
> ```

If I don't add any information, I usually delete the auto-inserted param comment lines.  But that's up to you...
___
*[src/BloomExe/Book/BookStorage.cs, line 411 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-LiELbRO7XD9SH9Xk8GY:-LiELbRO7XD9SH9Xk8GZ:b-n4dshh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32476b04e5303236c4d0d7f2d9e36212adc4277e/src/BloomExe/Book/BookStorage.cs#L411)):*
> ```Smalltalk
> 			watch.Start();
> 			var doc = new XmlDocument();
> 			doc.LoadXml("<html><body></body></html>");
> ```

Have you considered/tried using XmlElement.WriteContentTo(XmlWriter) in a new XmlHtmlConverter method to convert just an element to HTML5?  Maybe that wouldn't work because libtidy requires a full HTML document to work with...  And it might not buy much in any case.  You can be the judge of how silly this suggestion is.  :-)
___
*[src/BloomExe/Book/BookStorage.cs, line 468 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-LiESWR89Jo9u--meIgu:-LiESWR92tnRM_-lVSa1:b28zqbo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32476b04e5303236c4d0d7f2d9e36212adc4277e/src/BloomExe/Book/BookStorage.cs#L468)):*
> ```Smalltalk
> 			// In several states, we need to save up input text which we may or may not output, depending on
> 			// whether we complete the match we are attempting.
> 			string pending = "";
> ```

Wouldn't it be better for *pending* to be a StringBuilder rather than just a string?
___
*[src/BloomTests/Book/DataSetTests.cs, line 159 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-LiEXSOm4GHcOT_Tfyrp:-LiEXSOnC2WqKNWB-IVZ:b-8sf9xh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32476b04e5303236c4d0d7f2d9e36212adc4277e/src/BloomTests/Book/DataSetTests.cs#L159)):*
> ```Smalltalk
> 			var values = new HashSet<KeyValuePair<string, string>>();
> 			values.Add(new KeyValuePair<string, string>("key", "value"));
> 			first.UpdateXmatterPageDataAttributeSet("one", values);
> ```

You could extract the setup to a method that returns a dataset.  This would a) ensure that the datasets should be the same and b) allow you to make the datasets even more complex without the danger of missing something in one dataset or the other.  But that's up to you since currently the datasets are simple enough that it's easy to see they're the same.

**Review by JohnThomson — COMMENTED** [review]
All looked like good ideas. Thanks.
But the big question is, do you feel confident this is safe enough to ship?

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-:-LiJao4m0oUTSrja4WUB:b-q9ir8q)* status: 4 of 9 files reviewed, 6 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/Book/Book.cs, line 2416 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-LiEE6VqEWkl_IyxsCZQ:-LiJP7CD44wdSs9AXjcB:b-tavqwz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32476b04e5303236c4d0d7f2d9e36212adc4277e/src/BloomExe/Book/Book.cs#L2416)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I think this step should come after optionally setting the user modified styles since that step can change the value of canJustWritePage.   Am I overlooking something?
</blockquote></details>

This call is all about the dataDiv. It's not needed just because styles changed. I've re-arranged a couple of things to make this clearer.
___
*[src/BloomExe/Book/Book.cs, line 2879 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-LiEEgg8AdrmTZX-0xK8:-LiJPlt5BHh6xJ2sGfk3:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32476b04e5303236c4d0d7f2d9e36212adc4277e/src/BloomExe/Book/Book.cs#L2879)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Should this have one or both of the Guard.Against() calls from Save()?  Just asking, it's up to you to decide.
</blockquote></details>

Done.
___
*[src/BloomExe/Book/BookStorage.cs, line 404 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-LiEJvLM8Rcr7dy1Qo2P:-LiJPxr_4WbWAW5sySyl:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32476b04e5303236c4d0d7f2d9e36212adc4277e/src/BloomExe/Book/BookStorage.cs#L404)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

If I don't add any information, I usually delete the auto-inserted param comment lines.  But that's up to you...
</blockquote></details>

Done.
___
*[src/BloomExe/Book/BookStorage.cs, line 411 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-LiELbRO7XD9SH9Xk8GY:-LiJQR7r2exlaZPEYGYI:b-21s2bs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32476b04e5303236c4d0d7f2d9e36212adc4277e/src/BloomExe/Book/BookStorage.cs#L411)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Have you considered/tried using XmlElement.WriteContentTo(XmlWriter) in a new XmlHtmlConverter method to convert just an element to HTML5?  Maybe that wouldn't work because libtidy requires a full HTML document to work with...  And it might not buy much in any case.  You can be the judge of how silly this suggestion is.  :-)
</blockquote></details>

I don't know whether Tidy can work on just a fragment of a document. Just wrapping the outer tags around it won't cost much, but the fact that we have to import our node into a new document probably hurts us a bit. I found a way to avoid that, which will help things a bit more, though the big savings is not doing all the conversion steps on the whole book.
___
*[src/BloomExe/Book/BookStorage.cs, line 468 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-LiESWR89Jo9u--meIgu:-LiJUSFiBheQ1WvxvqrG:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32476b04e5303236c4d0d7f2d9e36212adc4277e/src/BloomExe/Book/BookStorage.cs#L468)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Wouldn't it be better for *pending* to be a StringBuilder rather than just a string?
</blockquote></details>

Done.
___
*[src/BloomTests/Book/DataSetTests.cs, line 159 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-LiEXSOm4GHcOT_Tfyrp:-LiJVRYp1v-4XGb9LFA8:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32476b04e5303236c4d0d7f2d9e36212adc4277e/src/BloomTests/Book/DataSetTests.cs#L159)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

You could extract the setup to a method that returns a dataset.  This would a) ensure that the datasets should be the same and b) allow you to make the datasets even more complex without the danger of missing something in one dataset or the other.  But that's up to you since currently the datasets are simple enough that it's easy to see they're the same.
</blockquote></details>

Done.

**Review by StephenMcConnel — APPROVED** [review]
:lgtm:  I think the code looks safe enough for a beta, and likely safe enough to ship.  I'd be comfortable merging to 4.6/master at this point.  I'd probably like Andrew to scan over it before merging, however, since it's a large enough change that affects normal operation.  (Being that kind of change, I would expect any lurking problems to surface quickly.)

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-:-LiKVRa71QwIjyYLi9vY:bqufrki)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Looks good overall. A few nits. And one possible source of future bugs I pointed out (or maybe the code handles it but I didn't notice).

> Reviewed 4 of 8 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-:-LiQKqnK7ye-1t5mG1_e:b-rbv9gs)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Book/Book.cs, line 2416 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-LiQ8HS7CKagLyH559Kk:-LiQ8HS7CKagLyH559Kl:b-8kk0pl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d54cf7ed39a28c1b26b0e4f3ecb094f37a24e588/src/BloomExe/Book/Book.cs#L2416)):*
> ```
> sharedDataWasChanged
> ```
Sorry, this is probably just nitpicking, but it might save a future bug, I guess...
The interaction between `canJustWritePage` and `sharedDataWasChanged` is bothering me.
It seems like either we should use `!canJustWritePage` here for the condition or we should create/set `canJustWritePage` just before we need it (before the next if).
___
*[src/BloomTests/Book/ReplacePageTests.cs, line 14 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-LiPs3zCBeaOeKGfslFV:-LiPs3zDB_g_SRsiTGk2:b-vjrqdn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d54cf7ed39a28c1b26b0e4f3ecb094f37a24e588/src/BloomTests/Book/ReplacePageTests.cs#L14)):*
> ```Smalltalk
> {
> 	[TestFixture()]
> 	public class ReplacePageTests
> ```

Something about this class name or namespace name is off. Should be able to easily tie back to BookStorage.
The typical place to put this would be BookStorageTests.cs. But maybe you were trying to keep it separate for smaller files?
___
*[src/BloomTests/Book/ReplacePageTests.cs, line 16 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-LiOtzU-Eye-SjxpGmOH:-LiOtzU-Eye-SjxpGmOI:b8xg1e1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d54cf7ed39a28c1b26b0e4f3ecb094f37a24e588/src/BloomTests/Book/ReplacePageTests.cs#L16)):*
> ```
> public
> ```
private
___
*[src/BloomTests/Book/ReplacePageTests.cs, line 42 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-LiQKRUP79FoG2-d_7aU:-LiQKRUQ658RiHFNISRV:bo4vcox) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d54cf7ed39a28c1b26b0e4f3ecb094f37a24e588/src/BloomTests/Book/ReplacePageTests.cs#L42)):*
> ```
> 			"<div id=\"234-abc\">the <div>old</div> <div class=\"not bloom page\">stuff</div></div>",
> ```
What if the page to be replaced had `<div class=\"bloom-page-header\">` in it? Or `<div class=\"hidden-bloom-page\">`?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @Class)

___
*[src/BloomExe/Book/Book.cs, line 2416 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-LiQ8HS7CKagLyH559Kk:-LiTTa-YCaJ4ts3gsVsY:b50xnrl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d54cf7ed39a28c1b26b0e4f3ecb094f37a24e588/src/BloomExe/Book/Book.cs#L2416)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> sharedDataWasChanged
> ```
Sorry, this is probably just nitpicking, but it might save a future bug, I guess...
The interaction between `canJustWritePage` and `sharedDataWasChanged` is bothering me.
It seems like either we should use `!canJustWritePage` here for the condition or we should create/set `canJustWritePage` just before we need it (before the next if).
</blockquote></details>

I had another go at making things clearer
___
*[src/BloomTests/Book/ReplacePageTests.cs, line 14 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-LiPs3zCBeaOeKGfslFV:-LiTqf9wC6dLuVl0r8P0:bxzdj58) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d54cf7ed39a28c1b26b0e4f3ecb094f37a24e588/src/BloomTests/Book/ReplacePageTests.cs#L14)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Something about this class name or namespace name is off. Should be able to easily tie back to BookStorage.
The typical place to put this would be BookStorageTests.cs. But maybe you were trying to keep it separate for smaller files?
</blockquote></details>

Partly that...also I think the Setup for BookStorageTests is fairly expensive and not relevant to these tests. I've done some renaming.
___
*[src/BloomTests/Book/ReplacePageTests.cs, line 16 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-LiOtzU-Eye-SjxpGmOH:-LiTqsBd9miHSVSczfbt:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d54cf7ed39a28c1b26b0e4f3ecb094f37a24e588/src/BloomTests/Book/ReplacePageTests.cs#L16)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> public
> ```
private
</blockquote></details>

Done.
___
*[src/BloomTests/Book/ReplacePageTests.cs, line 42 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245#-LiQKRUP79FoG2-d_7aU:-LiTrS9dEw0ysgaUhRck:b9r1zau) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d54cf7ed39a28c1b26b0e4f3ecb094f37a24e588/src/BloomTests/Book/ReplacePageTests.cs#L42)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> 			"<div id=\"234-abc\">the <div>old</div> <div class=\"not bloom page\">stuff</div></div>",
> ```
What if the page to be replaced had `<div class=\"bloom-page-header\">` in it? Or `<div class=\"hidden-bloom-page\">`?
</blockquote></details>

I found 100 occurrences of contains(@class,'bloom-page') in our source code. We have a LOT of work to do if we ever consider using a new class name that contains that substring and can occur in non-page elements! I don't think it's worth the added complexity to anticipate it here and now...a strong case for YAGNI. I did add a comment and made sure it contains that string so if we're ever searching for it to fix things we'll find this.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3245)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
