### PR TITLE
Process font licenses more accurately and stringently (BL-13806)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6619)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6619)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/FontProcessing/FontMetadata.cs` line 321 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6619#-O5KzfT4BrXAGREYRAB0:-O5KzfT4BrXAGREYRAB1:b6g66y2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/5ea556bac19447d1f408ad7fd5b9f8966c08b87d/src/BloomExe/FontProcessing/FontMetadata.cs#L321)):*
> ```Smalltalk
>                     licenseURL = "https://learn.microsoft.com/en-us/typography/fonts/font-faq";
>                     determinedSuitability = kUnsuitable;
>                     determinedSuitabilityNotes = L10NSharp.LocalizationManager.GetString(
> ```

Too bad that the L10nSharp API here requires you to add a string that nothing will ever read (because we don't code-scan), and you have to repeat it at least three items in this code. I'd recommend either just passing `""` or at least just get the string once and then reuse it.
___
*[`src/BloomExe/FontProcessing/FontMetadata.cs` line 414 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6619#-O5L-3oo422UAvW_lez8:-O5L-3oo422UAvW_lez9:b-lw4d4w) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/5ea556bac19447d1f408ad7fd5b9f8966c08b87d/src/BloomExe/FontProcessing/FontMetadata.cs#L414)):*
> ```Smalltalk
>                 {
>                     determinedSuitability = kOK;
>                     determinedSuitabilityNotes = "Freeware.";
> ```

My own heuristic is, "if it's not a sentence, it doesn't get a period".  That will help bring consistency (e.g. "Creative Commons"). Same for all others.

**Comment by hatton** [comment]
*[`DistFiles/localization/en/Bloom.xlf` line 4466 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6619#-O5L2q9qEiItXMxznRB2:-O5L2q9qEiItXMxznRB3:b-vp2ff9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/5ea556bac19447d1f408ad7fd5b9f8966c08b87d/DistFiles/localization/en/Bloom.xlf#L4466)):*
> ```XML
>       </trans-unit>
>       <trans-unit id="PublishTab.FontProblem.Microsoft" translate="no">
>         <source xml:lang="en">Microsoft does not allow its fonts to be used freely on the web or distributed in eBooks. Please use a different font.</source>
> ```

My bad, but seeing it in your screenshot made me realize, we should start this with something like:

`This is a font supplied by Microsoft for use on your computer alone. `

**Review by hatton — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6619)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6619)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[`src/BloomExe/FontProcessing/FontMetadata.cs` line 321 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6619#-O5KzfT4BrXAGREYRAB0:-O5L7KikDBBSU5UAhK0v:b-d6wl5r) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/5ea556bac19447d1f408ad7fd5b9f8966c08b87d/src/BloomExe/FontProcessing/FontMetadata.cs#L321)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Too bad that the L10nSharp API here requires you to add a string that nothing will ever read (because we don't code-scan), and you have to repeat it at least three items in this code. I'd recommend either just passing `""` or at least just get the string once and then reuse it.
</blockquote></details>

Done.  I changed to fetching the localized string in the typescript code, and using a cryptic phrase like the other places for this value.
___
*[`src/BloomExe/FontProcessing/FontMetadata.cs` line 414 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6619#-O5L-3oo422UAvW_lez8:-O5L7XfLEyBKJBnVCFO5:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/5ea556bac19447d1f408ad7fd5b9f8966c08b87d/src/BloomExe/FontProcessing/FontMetadata.cs#L414)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

My own heuristic is, "if it's not a sentence, it doesn't get a period".  That will help bring consistency (e.g. "Creative Commons"). Same for all others.
</blockquote></details>

Done.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6619)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[`DistFiles/localization/en/Bloom.xlf` line 4466 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6619#-O5L2q9qEiItXMxznRB2:-O5L9fpbAFzqluxTEMQq:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/5ea556bac19447d1f408ad7fd5b9f8966c08b87d/DistFiles/localization/en/Bloom.xlf#L4466)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

My bad, but seeing it in your screenshot made me realize, we should start this with something like:

`This is a font supplied by Microsoft for use on your computer alone. `
</blockquote></details>

Done.

**Pull request merged**
