### PR TITLE
Show placeholder message for unimplemented branding (BL-10312)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This allows new enterprise subscriptions to be used before the branding
files have been created and added to Bloom.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4721)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
Looks good...a few questions which might not require any actual changes.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4721#-:-MjoNUbXCC-M3xf7z1hs:bxtnc7v)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 424 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4721#-MjoKU0oC2FwXMZmxMIN:-MjoKU0oC2FwXMZmxMIO:b-pknxeu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e4a09bac80fc05251e12704cac8115f03aed676b/src/BloomExe/Collection/CollectionSettingsDialog.cs#L424)):*
> ```Smalltalk
> 		bool IsSubscriptionCodeKnown()
> 		{
> 			return BrandingProject.HaveFilesForBranding(_brand) || CollectionSettingsApi.GetExpirationDate(_subscriptionCode) != DateTime.MinValue;
> ```

Not quite sure how this is used, but should be be checking that the subscription hasn't expired? I suppose 'known' just means we recognize it even if it's expired?
___
*[src/BloomExe/web/BloomServer.cs, line 956 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4721#-MjoM8kBBWroHRuwafNu:-MjoM8kBBWroHRuwafNv:bmri76y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e4a09bac80fc05251e12704cac8115f03aed676b/src/BloomExe/web/BloomServer.cs#L956)):*
> ```Smalltalk
> 			using (var tempFile = TempFile.WithFilename("branding.css"))
> 			{
> 				var msgFmt = LocalizationManager.GetString("", "A future update of Bloom will contain the branding assets for this project, “{0}”.  Thank you for your patience.");
> ```

Do we not want an ID and an XLF entry yet?
___
*[src/BloomExe/web/BloomServer.cs, line 971 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4721#-MjoN9bvBVi8apHPwrYH:-MjoN9bvBVi8apHPwrYI:blo0vmi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e4a09bac80fc05251e12704cac8115f03aed676b/src/BloomExe/web/BloomServer.cs#L971)):*
> ```Smalltalk
>     text-align: center;
>     content: """ + msg + @""";
>     visibility: visible;
> ```

Would we give a better indication of eventual page layout by using position:absolute;top:0 so that the message overlays the hidden logo? Of course their logo might be a quite different size and shape...

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4721)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson and @StephenMcConnel)

___
*[src/BloomExe/web/BloomServer.cs, line 956 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4721#-MjoM8kBBWroHRuwafNu:-Mjoa8Ca8kgVgR6aY0Vb:b-nmcqaa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e4a09bac80fc05251e12704cac8115f03aed676b/src/BloomExe/web/BloomServer.cs#L956)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Do we not want an ID and an XLF entry yet?
</blockquote></details>

I added the string to BloomLowPriority.xlf, but forgot to copy the ID here.  Also, we need to specify L2 as the preferred language, not the current UI language.
___
*[src/BloomExe/web/BloomServer.cs, line 971 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4721#-MjoN9bvBVi8apHPwrYH:-MjoaNo1Dglnc8D5Ni-_:bvawkf9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e4a09bac80fc05251e12704cac8115f03aed676b/src/BloomExe/web/BloomServer.cs#L971)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Would we give a better indication of eventual page layout by using position:absolute;top:0 so that the message overlays the hidden logo? Of course their logo might be a quite different size and shape...
</blockquote></details>

At this stage, I don't think we need to worry about indicating future page layout.  But I think my error was bad CSS syntax in not getting display:none to work for the img.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4721)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 424 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4721#-MjoKU0oC2FwXMZmxMIN:-MkIJXoa2PQLKR3zJg9F:bysuem8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e4a09bac80fc05251e12704cac8115f03aed676b/src/BloomExe/Collection/CollectionSettingsDialog.cs#L424)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Not quite sure how this is used, but should be be checking that the subscription hasn't expired? I suppose 'known' just means we recognize it even if it's expired?
</blockquote></details>

That has been the existing behavior, recognizing codes even if they have expired.  The expiration date is checked elsewhere.  The dialog still show something like this for expired codes:

Based on the use of this value, it indicates that the branding/subscription code is recognized by Bloom even if it is outdated.  The comment in CollectionSettingsApi on the variable that stores what is computed here reads "True if the part of the subscription code that identifies the branding is one this version of Bloom knows about".  I've added a comment to this method explaining what is going on more clearly.

Actually, checking for the existence of the branding files may not be needed anymore, but I'm inclined to leave that part in place anyway.

**Review by JohnThomson — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4721#-:-MkImP0QEtZqokDrgU2c:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
