### PR TITLE
BL-3387 Don't choke if image is to big to save as jpeg

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1042)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 247 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1042#-KGnM0O2UboYFYS-z5cw:-KGnM0O2UboYFYS-z5cx:-1730099396) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d38f214cbc08c19a1e2e19dfadee552734ae156d/src/BloomExe/ImageProcessing/ImageUtils.cs#L247)):*
http://stackoverflow.com/questions/2117142/when-is-it-ok-to-catch-an-outofmemoryexception-and-how-to-handle-it is interesting here. Most recommend against it as nondeterministic (e.g., you MIGHT run out in a way that doesn't leave room to unwind the stack properly). Any chance of anticipating how much memory we will need and using a MemoryFailPoint to reserve it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1042)*

**Comment by hatton** [comment]
I am now firmly against the assumption that we should try to prevent all errors, especially by adding yet more code, which itself may have bugs. Instead, I think we should accept that at the boundaries of what we control (disk, network, big chunks of memory), failures will happen. With the miniscule programming resources we have, the appropriate thing is to make sure that the user experience is appropriate for each error, considering the almost crippling cost we now pay for each bug report, since the number of users we have is now large enough that even extremely rare errors will happen frequently.  In code like this, where we're prevented from seeing if an optimization might make sense, then appropriate user experience is just to passively make note of it.

**Comment by JohnThomson** [comment]
So I think you're saying, what is already in this PR is the best we can afford to do, even if there is a (probably very) small chance of making things worse by trying to carry on when things are badly broken? I can live with that.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1042#-:-KGqqkLcjXusRUpuMys4:-315762810)*

**Comment by hatton** [comment]
Pretty much. Not crashing on an optional check for an image optimization is the appropriate response to not having enough memory to do the check.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1042#-:-KGs69CV7_ezB2fRd0ac:-1899437020)*

**Pull request merged**
