### PR TITLE
Handle pasting text with audio spans properly (BL-9221)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070)* status: all files reviewed, 6 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 137 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070#-MLtZ_6S4Ei0m01YI4vr:-MLtZ_6S4Ei0m01YI4vs:b-qxepy7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/994bcbcf86a47e134e16ec49ee215766b63c661d/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L137)):*
> ```
> Firefox 60 imposes using RegExp.exec.
> ```
This comment is misplaced.
___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 197 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070#-MLt_BUaBe_MiVqO2XOg:-MLt_BUaBe_MiVqO2XOh:b4t6lc4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/994bcbcf86a47e134e16ec49ee215766b63c661d/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L197)):*
> ```XML
>     ): string {
>         const audioRegex = RegExp(
>             '<span id="([^"]*)" class="audio-sentence[" ][^>]*>([^<]*)</span>',
> ```

Is the `id` attr guaranteed to come before the `class` attr?

Is it possible to have something like `<span ... >I have a <strong>big</strong> dog</span>`?
___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 200 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070#-MLt_r2g44jDgQubSJrY:-MLt_r2g44jDgQubSJrZ:b-vahcxa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/994bcbcf86a47e134e16ec49ee215766b63c661d/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L200)):*
> ```
> array1
> ```
Can you come up with a better name? `regexMatches`? `audioSentenceSpans`?
___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 213 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070#-MLtb9Fo8x3VijBwhbxl:-MLtb9Fo8x3VijBwhbxm:b-ewlwhr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/994bcbcf86a47e134e16ec49ee215766b63c661d/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L213)):*
> ```XML
>                 `<span id="${newId}" class="audio-sentence">${
>                     array1[2]
>                 }</span>`;
> ```

My future self would like some enhancements here to help him understand what is going on. Maybe it would be enough just to give array1["index"] and array1[2] new variables with meaningful names? Otherwise a couple brief comments would help.
___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 214 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070#-MLtafcbBQlgpTsQ4-gr:-MLtafcbBQlgpTsQ4-gs:b-qlqypj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/994bcbcf86a47e134e16ec49ee215766b63c661d/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L214)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>             if ((window as any).__karma__) {
>                 console.log(
>                     `Test skips post: audio/copyAudioFile?oldId=${
>                         array1[1]
>                     }&newId=${newId}`
>                 );
> ```
</details>

Open to pushback here, but for some reason it feels safer to let the api call happen and let the server decide it shouldn't do anything with it.
___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 2754 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070#-MLtZ6DO2RIbNXCV2CPI:-MLtZ6DO2RIbNXCV2CPJ:b-wi6jfx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/994bcbcf86a47e134e16ec49ee215766b63c661d/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L2754)):*
> ```
> public
> ```
Doesn't need to be public

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 137 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070#-MLtZ_6S4Ei0m01YI4vr:-MM1awBoAb24-7Bp3K2I:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/994bcbcf86a47e134e16ec49ee215766b63c661d/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L137)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Firefox 60 imposes using RegExp.exec.
> ```
This comment is misplaced.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 197 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070#-MLt_BUaBe_MiVqO2XOg:-MM1oGUN7fDQERgFKNZm:b-u9nlhs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/994bcbcf86a47e134e16ec49ee215766b63c661d/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L197)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is the `id` attr guaranteed to come before the `class` attr?

Is it possible to have something like `<span ... >I have a <strong>big</strong> dog</span>`?
</blockquote></details>

Books in my Bloom directory have 4000+ occurrences of audio-sentence spans.  id comes before class in every one of them, and audio-sentence is the first item in the class attribute value.
On the other hand, id isn't always the first attribute...
Handling HTML markup inside the text is a requirement.
___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 200 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070#-MLt_r2g44jDgQubSJrY:-MM1azOw3Y-Z1_nilAeI:b8hh52b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/994bcbcf86a47e134e16ec49ee215766b63c661d/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L200)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> array1
> ```
Can you come up with a better name? `regexMatches`? `audioSentenceSpans`?
</blockquote></details>

I renamed it to "regexMatch".  It represents a single match result.
___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 213 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070#-MLtb9Fo8x3VijBwhbxl:-MM1crWz5qSYcwc3GzYA:byqup2a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/994bcbcf86a47e134e16ec49ee215766b63c661d/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L213)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

My future self would like some enhancements here to help him understand what is going on. Maybe it would be enough just to give array1["index"] and array1[2] new variables with meaningful names? Otherwise a couple brief comments would help.
</blockquote></details>

I provided variables with reasonable names and a link to the online documentation for Regexp.exec.
___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 214 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070#-MLtafcbBQlgpTsQ4-gr:-MM1cNXyC1OjVLIxbDW9:bs6dxir) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/994bcbcf86a47e134e16ec49ee215766b63c661d/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L214)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
>             if ((window as any).__karma__) {
>                 console.log(
>                     `Test skips post: audio/copyAudioFile?oldId=${
>                         array1[1]
>                     }&newId=${newId}`
>                 );
> ```
Open to pushback here, but for some reason it feels safer to let the api call happen and let the server decide it shouldn't do anything with it.
</blockquote></details>

I suppose that posting to something that doesn't exist or doesn't respond should work okay.  Removed the check for test code running.
___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 2754 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070#-MLtZ6DO2RIbNXCV2CPI:-MM1clCL8BFVS4xCXa4J:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/994bcbcf86a47e134e16ec49ee215766b63c661d/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L2754)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> public
> ```
Doesn't need to be public
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 197 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070#-MLt_BUaBe_MiVqO2XOg:-MM2X5Nb6EHELhETuvYo:bza5yv8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/994bcbcf86a47e134e16ec49ee215766b63c661d/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L197)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Books in my Bloom directory have 4000+ occurrences of audio-sentence spans.  id comes before class in every one of them, and audio-sentence is the first item in the class attribute value.
On the other hand, id isn't always the first attribute...
Handling HTML markup inside the text is a requirement.
</blockquote></details>

Sorry to push again, but this is still feeling a bit fragile. I hadn't actually noticed the requirement that `audio-sentence` comes first in the class list.
Ideally, we should handle id and class in either order, but as that is probably hard, we can probably live with it as is.
However, allowing for another class or a space before `audio-sentence` seems like it shouldn't be too hard and will be much more robust against future changes.
___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 214 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070#-MLtafcbBQlgpTsQ4-gr:-MM2WGs44VrBWzjy9ayR:bdzpgyv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/994bcbcf86a47e134e16ec49ee215766b63c661d/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L214)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I suppose that posting to something that doesn't exist or doesn't respond should work okay.  Removed the check for test code running.
</blockquote></details>

Hm. Yeah, I was thinking about that wrong, thinking we had to have a server running to have the tests pass, but of course that is never the case for TC.
Actually, I'm surprised this works as is. Maybe BloomApi is already robust against calls when there is no server.
___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 209 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070#-MM2Xi_GE5MNCy1uMohs:-MM2Xi_GE5MNCy1uMoht:bhkhpss) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1dd32db77e70bf9b7c9b70681c1a5146cdfa4963/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L209)):*
> ```
>             const group1Text: string = regexMatch[1];
>             const group2Text: string = regexMatch[2];
> ```
Not requiring it, but see if you think this would be a helpful change:
> ```
>             const oldId: string = regexMatch[1]; // group 1
>             const audioSentenceText: string = regexMatch[2]; // group 2
> ```

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 197 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070#-MLt_BUaBe_MiVqO2XOg:-MMGxulV6ZrlR43-xSXo:beiqjhg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/994bcbcf86a47e134e16ec49ee215766b63c661d/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L197)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry to push again, but this is still feeling a bit fragile. I hadn't actually noticed the requirement that `audio-sentence` comes first in the class list.
Ideally, we should handle id and class in either order, but as that is probably hard, we can probably live with it as is.
However, allowing for another class or a space before `audio-sentence` seems like it shouldn't be too hard and will be much more robust against future changes.
</blockquote></details>

Done.  I think the regular expression is now as robust as is possible in the RE language.
___
*[src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, line 209 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070#-MM2Xi_GE5MNCy1uMohs:-MM2zFaW1EQtVbJG9dk-:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1dd32db77e70bf9b7c9b70681c1a5146cdfa4963/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L209)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
>             const group1Text: string = regexMatch[1];
>             const group2Text: string = regexMatch[2];
> ```
Not requiring it, but see if you think this would be a helpful change:
> ```
>             const oldId: string = regexMatch[1]; // group 1
>             const audioSentenceText: string = regexMatch[2]; // group 2
> ```

</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
