### PR TITLE
Ignore unnecessary HTM files when making bloomd (BL-8943)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3920)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3920)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[src/BloomTests/Book/BookCompressorTests.cs, line 51 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3920#-MGib1Zi-gFWf2EqYS0d:-MGib1Zj6H1BXdUorUTM:b-7zq40e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4e57e298962ece395309dce3da584773f8bbf22e/src/BloomTests/Book/BookCompressorTests.cs#L51)):*
> ```Smalltalk
> 
> 		[Test]
> 		public void CompressDirectory_CompressBookWithExtraHtmlFiles_ExtrasAreIgnored()
> ```

I could've made a more E2E test by doing it in BloomPublishTests, but that added like 8 seconds of overhead to something that only needed 0.1-0.2 seconds. :(

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3920)* status: 0 of 3 files reviewed, 2 unresolved discussions

___
*[src/BloomExe/Book/BookCompressor.cs, line 111 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3920#-MGilV5GCR_hvqUtXLdy:-MGilV5H6v-XhiEMTV35:b-qdumrw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4e57e298962ece395309dce3da584773f8bbf22e/src/BloomExe/Book/BookCompressor.cs#L111)):*
> ```Smalltalk
> 			// These HTML files in other locations aren't generated by Bloom. They may not have the format Bloom expects,
> 			// causing needless parsing errors to be throw if we attempt to read them using Bloom code.
> 			var bookFile = isTopLevel ? BookStorage.FindBookHtmlInFolder(directoryToCompress) : null;
> ```

Hold up: This seems to cause a test failure in a seemingly unrelated test. Investigating...

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3920)* status: 0 of 8 files reviewed, 3 unresolved discussions

___
*[src/BloomExe/XmlHtmlConverter.cs, line 150 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3920#-MGjiLUc4xqokrAPn97E:-MGjiLUc4xqokrAPn97F:b-5fm4gi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/22866ca6c54063ed89852cedf4e9102e7538f845/src/BloomExe/XmlHtmlConverter.cs#L150)):*
> ```Smalltalk
> 					{
> 						var exceptionWithHtmlContents = new Exception(string.Format("{0}{2}{2}{1}",
> 							e.Message, newContents, Environment.NewLine), innerException: e);
> ```

This doesn't actually re-throw any relevant exceptions, but it looked bad to me. I added an innerException to it. I think it's harmless? I found it more difficult to test than I anticipated.
___
*[src/BloomExe/Book/BookCompressor.cs, line 111 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3920#-MGilV5GCR_hvqUtXLdy:-MGjinLo5chK5MOrkVtT:bxze2j0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4e57e298962ece395309dce3da584773f8bbf22e/src/BloomExe/Book/BookCompressor.cs#L111)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Hold up: This seems to cause a test failure in a seemingly unrelated test. Investigating...
</blockquote></details>

Apparently this some code is used to process bloompacks too, and the directory structure is not the same. :(

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 6 of 7 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3920)* status: all files reviewed, 3 unresolved discussions

**Pull request merged**
