### PR TITLE
UI tweaks for new upload screen (BL-11581)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5694)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5694)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 191 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5694#-NQ2C4SB9Yi6aT5bsr6V:-NQ2C4SB9Yi6aT5bsr6W:b-dan6j) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9cae86966f53e03a8d88dbd328001553d0d56530/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L191)):*
> ```XML
>     useEffect(() => {
>         // Without the setTimeout, it doesn't scroll all the way down.
>         // Smaller timeout numbers resulted in varying, insufficient scrolling.
> ```

Timeouts with 0 are fine. But any others just make one wonder about the effect of the speed of the computer. How are you dealing with that? If there are any other changes, you could comment on that.
___
*[`src/BloomBrowserUI/react_components/BloomStepper.tsx` line 9 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5694#-NQ2CoGeBNoagxKRk68A:-NQ2CoGeBNoagxKRk68B:b6t3e3i) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9cae86966f53e03a8d88dbd328001553d0d56530/src/BloomBrowserUI/react_components/BloomStepper.tsx#L9)):*
> ```XML
> 
> export const BloomStepper: React.FunctionComponent<{
>     defeatDisabling?: boolean;
> ```

This feels like a double negative.  How about `disableLaterSteps`, maybe no default, you have to decide.
___
*[`src/BloomBrowserUI/react_components/localizableMenuItem.tsx` line 148 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5694#-NQ2DXDO222sugCnWCq6:-NQ2DXDO222sugCnWCq7:bz4v8dn) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9cae86966f53e03a8d88dbd328001553d0d56530/src/BloomBrowserUI/react_components/localizableMenuItem.tsx#L148)):*
> ```XML
>                             opacity: ${meetsEnterpriseRequirement
>                                 ? undefined
>                                 : 0.38};
> ```

Can this `0.38` go into the theme as a constant so that we can get consistency?
___
*[`src/BloomBrowserUI/react_components/BloomDialog/commonDialogComponents.tsx` line 214 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5694#-NQ2Dmib0Eeoksg8Zdcj:-NQ2Dmib0Eeoksg8Zdck:b-z5k1op) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9cae86966f53e03a8d88dbd328001553d0d56530/src/BloomBrowserUI/react_components/BloomDialog/commonDialogComponents.tsx#L214)):*
> ```XML
> );
> 
> export const NoteBox: React.FunctionComponent<{
> ```

Is the the way? Or should we just introduce a new box, so that we get consistency? So this might be a "WaitBox".

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5694)* status: 4 of 20 files reviewed, 4 unresolved discussions (waiting on @hatton)

___
*[`src/BloomBrowserUI/react_components/BloomStepper.tsx` line 9 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5694#-NQ2CoGeBNoagxKRk68A:-NQ2LOhu6H2X2ym6NYJs:bqrs33c) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9cae86966f53e03a8d88dbd328001553d0d56530/src/BloomBrowserUI/react_components/BloomStepper.tsx#L9)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This feels like a double negative.  How about `disableLaterSteps`, maybe no default, you have to decide.
</blockquote></details>

Is this better/sufficient?
I generally prefer a default for these kinds of stylistic choices. My thinking: there's what we normally do; then there's the exceptions.
I also figured this prop would go away once we settle on which style we prefer between the new screen and the current audio/video screen.
___
*[`src/BloomBrowserUI/react_components/localizableMenuItem.tsx` line 148 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5694#-NQ2DXDO222sugCnWCq6:-NQ2PmXT7vd9L7wpDXZJ:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9cae86966f53e03a8d88dbd328001553d0d56530/src/BloomBrowserUI/react_components/localizableMenuItem.tsx#L148)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Can this `0.38` go into the theme as a constant so that we can get consistency?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/react_components/BloomDialog/commonDialogComponents.tsx` line 214 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5694#-NQ2Dmib0Eeoksg8Zdcj:-NQ2TlfYDEmlEcrCHvF7:bcckwmu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9cae86966f53e03a8d88dbd328001553d0d56530/src/BloomBrowserUI/react_components/BloomDialog/commonDialogComponents.tsx#L214)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is the the way? Or should we just introduce a new box, so that we get consistency? So this might be a "WaitBox".
</blockquote></details>

Yeah, I was pretty unsure myself...
Thanks for pushing it.
This is much better.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5694)* status: 4 of 20 files reviewed, 4 unresolved discussions (waiting on @hatton)

___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 191 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5694#-NQ2C4SB9Yi6aT5bsr6V:-NQ2hCjR9edNoSRZ2wMO:b-47nisj) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9cae86966f53e03a8d88dbd328001553d0d56530/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L191)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Timeouts with 0 are fine. But any others just make one wonder about the effect of the speed of the computer. How are you dealing with that? If there are any other changes, you could comment on that.
</blockquote></details>

I need to look at this more tomorrow.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5694)* status: 4 of 20 files reviewed, 4 unresolved discussions (waiting on @hatton)

___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 191 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5694#-NQ2C4SB9Yi6aT5bsr6V:-NQ6K5W-EZrKFahwtOCw:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9cae86966f53e03a8d88dbd328001553d0d56530/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L191)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I need to look at this more tomorrow.
</blockquote></details>

Done.

**Review by hatton — APPROVED** [review]
> Reviewed 15 of 16 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5694)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
