### PR TITLE
BL-4191 Catch exception when sending data to JS fails

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1419)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Question posted. Otherwise, :lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/web/RequestInfo.cs, line 86 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1419#-Kase-ZR3x1AMS2QqJO0:-Kase-ZR3x1AMS2QqJO1:btl5beq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1237b7ca9c2996bf440eca5f5f696a268817e395/src/BloomExe/web/RequestInfo.cs#L86)):*
> catch (HttpListenerException e)

I guess you've evaluated the possibility that we could catch and ignore something more sinister than the particular use case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1419#-:-Kase9u3INqhhZyIs_cp:b-ksv0zy)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/web/RequestInfo.cs, line 86 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1419#-Kase-ZR3x1AMS2QqJO0:-KawTLikCB99NUtBrUAD:bikt7xb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1237b7ca9c2996bf440eca5f5f696a268817e395/src/BloomExe/web/RequestInfo.cs#L86)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> catch (HttpListenerException e)

I guess you've evaluated the possibility that we could catch and ignore something more sinister than the particular use case?
</blockquote></details>

My default is if possible only to catch exceptions that I know can safely be ignored. We may of course find other kinds that can be thrown as a result of missing pages, but I don't know how to guess what they might be. I don't want to miss a report of some real problem (or worse, the information that would have helped solve some otherwise obscure problem). We already have more places than I like where we catch all exceptions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1419)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/web/RequestInfo.cs, line 86 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1419#-Kase-ZR3x1AMS2QqJO0:-KawUU65g4dxD5CA1RnH:bsg4v90) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1237b7ca9c2996bf440eca5f5f696a268817e395/src/BloomExe/web/RequestInfo.cs#L86)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

My default is if possible only to catch exceptions that I know can safely be ignored. We may of course find other kinds that can be thrown as a result of missing pages, but I don't know how to guess what they might be. I don't want to miss a report of some real problem (or worse, the information that would have helped solve some otherwise obscure problem). We already have more places than I like where we catch all exceptions.
</blockquote></details>

Sorry; I was unclear and you have misunderstood my question.
I was actually asking the opposite.
Have you thought about the fact that we could catch and ignore something here which we *don't* want to ignore?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1419)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/web/RequestInfo.cs, line 86 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1419#-Kase-ZR3x1AMS2QqJO0:-KawsvACi6kuYCf_VULw:b-xhxqp0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1237b7ca9c2996bf440eca5f5f696a268817e395/src/BloomExe/web/RequestInfo.cs#L86)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; I was unclear and you have misunderstood my question.
I was actually asking the opposite.
Have you thought about the fact that we could catch and ignore something here which we *don't* want to ignore?
</blockquote></details>

Well, we're in the local fileserver sending some information that javascript has requested and we can't write to the stream that is supposed to receive the information. We know of a (potentially large) family of cases where this isn't a serious problem: the page that made the request has been disposed. I don't know of any way to distinguish that problem from anything else that might raise this exception. Crashing when it happens is the problem I'm trying to solve, so the server must not do that. I've arranged to both log the error and write a debug message to maximize the chances that we will have the information we need if it happens for some reason that IS a problem. Can you think of anything more I can do?
In principle I could try to detect whether the current page has in fact changed, say between when the request was received and when the exception is raised, and only ignore it if there HAS been a change. That feels fragile: these requests happen in worker threads and I'm afraid of creating a race condition where this crash still happens, but rarely and unrepeatably.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1419)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/web/RequestInfo.cs, line 86 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1419#-Kase-ZR3x1AMS2QqJO0:-Kax9JsX7RvOORgjY9MG:bkylgl1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1237b7ca9c2996bf440eca5f5f696a268817e395/src/BloomExe/web/RequestInfo.cs#L86)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Well, we're in the local fileserver sending some information that javascript has requested and we can't write to the stream that is supposed to receive the information. We know of a (potentially large) family of cases where this isn't a serious problem: the page that made the request has been disposed. I don't know of any way to distinguish that problem from anything else that might raise this exception. Crashing when it happens is the problem I'm trying to solve, so the server must not do that. I've arranged to both log the error and write a debug message to maximize the chances that we will have the information we need if it happens for some reason that IS a problem. Can you think of anything more I can do?
In principle I could try to detect whether the current page has in fact changed, say between when the request was received and when the exception is raised, and only ignore it if there HAS been a change. That feels fragile: these requests happen in worker threads and I'm afraid of creating a race condition where this crash still happens, but rarely and unrepeatably.
</blockquote></details>

Nope; I can't think of a better way. I just wanted to verify you had thought through it (but of course you did!).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1419)*

**Pull request merged**
