### PR TITLE
Prevent crash when uploading unlicensed content (BL-12335)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5910)

### CODE REVIEW

**Review by gmartin7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5910#-:-NXQu7_s78LrBi_O1OxY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Review by gmartin7 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5910)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/web/controllers/LibraryPublishApi.cs` line 208 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5910#-NXQv9ys51JWKuDr2KSa:-NXQv9ys51JWKuDr2KSb:biqkjsn) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f456d22d7dd40a8a398c6dd18678d208fc6656fb/src/BloomExe/web/controllers/LibraryPublishApi.cs#L208)):*
> ```Smalltalk
> 			{
> 				_webSocketProgress.MessageWithoutLocalizing(checkerResult, ProgressKind.Error);
> 				e.Result = ("quiet", ""); // suppress other completion/fail messages
> ```

How did you know what to put here?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5910)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

___
*[`src/BloomExe/web/controllers/LibraryPublishApi.cs` line 208 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5910#-NXQv9ys51JWKuDr2KSa:-NXR-O7UCaoaWCi8Gp7T:b-otk77y) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f456d22d7dd40a8a398c6dd18678d208fc6656fb/src/BloomExe/web/controllers/LibraryPublishApi.cs#L208)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

How did you know what to put here?
</blockquote></details>

The bug happened when we started returning a tuple as the result (see the other setting of e.Result several lines down) but didn't return a tuple in this path.
The second value of the tuple won't be used in this case, so it doesn't matter what it is set to. For some reason, the compiler wouldn't let me make it `null`.

**Review by StephenMcConnel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5910#-:-NXR-ask71SQKTHdAXXH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

___
*[`src/BloomExe/web/controllers/LibraryPublishApi.cs` line 208 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5910#-NXQv9ys51JWKuDr2KSa:-NXR-Ijj6-OBzw_UHvw4:bxu5wn5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f456d22d7dd40a8a398c6dd18678d208fc6656fb/src/BloomExe/web/controllers/LibraryPublishApi.cs#L208)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

How did you know what to put here?
</blockquote></details>

Any string probably would do.  This path through the code returns a Tuple of uploadResult and parseId.  The uploadResult is "quiet" and we don't care what the parseId is, but it needs something to fill out the tuple.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5910)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`src/BloomExe/web/controllers/LibraryPublishApi.cs` line 208 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5910#-NXQv9ys51JWKuDr2KSa:-NXR0Zys3klbhIEIxA77:b9w52my) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f456d22d7dd40a8a398c6dd18678d208fc6656fb/src/BloomExe/web/controllers/LibraryPublishApi.cs#L208)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Any string probably would do.  This path through the code returns a Tuple of uploadResult and parseId.  The uploadResult is "quiet" and we don't care what the parseId is, but it needs something to fill out the tuple.
</blockquote></details>

Although the symptom is more a program crash, not a publish without permission.

**Pull request merged**
