### PR TITLE
Export to Spreadsheet Menu command improvements  (BL-10259)

### PR DESCRIPTION
**Pull request by nabalone**
https://issues.bloomlibrary.org/youtrack/issue/BL-10259

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4648)

### CODE REVIEW

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4648)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @nabalone)

___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 170 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4648#-MghDl2F4pDMH0hPjNFd:-MghDl2G3_214jZLsZZK:b-7br9g0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/792ba1665e5305225d98059f210791b10860205b/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L170)):*
> ```Smalltalk
> 					Console.WriteLine(ex.StackTrace);
> 					var msg = LocalizationManager.GetString("Spreadsheet:ExportFailed", "Export failed: ");
> 					NonFatalProblem.Report(ModalIf.All, PassiveIf.None, msg + ex.Message, showSendReport: false);
> ```

Is it right for this to be showSendReport: false? I think the error will mostly be from people having the spreadsheet open in Excel. Looks like this

**Review by JohnThomson — CHANGES_REQUESTED** [review]
Looks good...I think we can do a little better on the error reporting, though.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4648#-:-MgqcJi85p4LYFdJjCbd:b-czcyas)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)

___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 170 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4648#-MghDl2F4pDMH0hPjNFd:-Mgq_-GG2xznBnszTeMO:b-8932u3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/792ba1665e5305225d98059f210791b10860205b/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L170)):*
<details><summary><i>Previously, nabalone wrote…</i></summary><blockquote>

Is it right for this to be showSendReport: false? I think the error will mostly be from people having the spreadsheet open in Excel. Looks like this 


</blockquote></details>

See if you can figure out what kind of exception is thrown in this case (by debugging). If it's specific enough, it would be nice to convert it into something like your console message...maybe "Bloom could not write the spreadsheet because another program has it locked. Do you have it open in the Spreadsheet program?" That should be shown with showSendReport false. Possibly worth including ex.Message in the "additional details" param.
Then if we get some other, unexpected, error, that should be shown with showSendReport true.
(In case you're not familiar with this: you can have multiple catch clauses, for example, you might catch(AccessDeniedException ex) {...} catch(Exception ex) {...} and it will pick the first that matches the exact type of the exception.)
If the exception seems too vague for such a specific message let's discuss it.
Also: the Report function has an optional argument for an Exception. Please pass 'ex' as that argument...stack trace and other exception info will then automatically be logged and, if the error is  reported, sent to us.

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4648)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 170 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4648#-MghDl2F4pDMH0hPjNFd:-Mgqs1qK8dhEtyoEhT03:b-f1b1th) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/792ba1665e5305225d98059f210791b10860205b/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L170)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

See if you can figure out what kind of exception is thrown in this case (by debugging). If it's specific enough, it would be nice to convert it into something like your console message...maybe "Bloom could not write the spreadsheet because another program has it locked. Do you have it open in the Spreadsheet program?" That should be shown with showSendReport false. Possibly worth including ex.Message in the "additional details" param.
Then if we get some other, unexpected, error, that should be shown with showSendReport true.
(In case you're not familiar with this: you can have multiple catch clauses, for example, you might catch(AccessDeniedException ex) {...} catch(Exception ex) {...} and it will pick the first that matches the exact type of the exception.)
If the exception seems too vague for such a specific message let's discuss it.
Also: the Report function has an optional argument for an Exception. Please pass 'ex' as that argument...stack trace and other exception info will then automatically be logged and, if the error is  reported, sent to us.
</blockquote></details>

It doesn't seem to show a difference between the shortUserLevelMessage and the moreDetails, does this look confusing?

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4648)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @JohnThomson and @nabalone)

___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 170 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4648#-MghDl2F4pDMH0hPjNFd:-MgujB8B02GSk31iZGki:b-b1vw5b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/792ba1665e5305225d98059f210791b10860205b/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L170)):*
<details><summary><i>Previously, nabalone wrote…</i></summary><blockquote>

It doesn't seem to show a difference between the shortUserLevelMessage and the moreDetails, does this look confusing? 


</blockquote></details>

I think it's OK. A bit redundant, but our language is a bit less technical (and may be more likely to get localized). And there may be cases where the other message is not as similar.
___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 171 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4648#-MguipEAEZ7dfQTp0mAk:-MguipEAEZ7dfQTp0mAl:b-1ldxwt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8fd9178943ce4c5b924cbbc70da880f972cd9d42/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L171)):*
> ```Smalltalk
> 					Console.WriteLine(ex.StackTrace);
> 					NonFatalProblem.Report(ModalIf.All, PassiveIf.None, "Bloom could not write to the spreadsheet because another program has it locked. Do you have it open in another program?\r\n",
> 						moreDetails: ex.Message, showSendReport: false);
> ```

This is great, I didn't think it would be possible to get that specific. But, would you please pass the exception here too? I think it's worth getting it logged (Console.Writeline only helps while debugging) even though we're not encouraging them to report this problem.
As you've found it quite common to get this, I think it's worth localizing the message...like what is done in the other branch. Just make up an ID. Eventually, it will have to go in the XLF file to get translated, but we'll wait for that until the feature goes at least beta.

**Review by JohnThomson — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4648)* status: all files reviewed, 2 unresolved discussions (waiting on @nabalone)

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4648)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @JohnThomson and @nabalone)

___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 171 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4648#-MguipEAEZ7dfQTp0mAk:-MgwEQ7ZE_E5xRVaCpq0:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8fd9178943ce4c5b924cbbc70da880f972cd9d42/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L171)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This is great, I didn't think it would be possible to get that specific. But, would you please pass the exception here too? I think it's worth getting it logged (Console.Writeline only helps while debugging) even though we're not encouraging them to report this problem.
As you've found it quite common to get this, I think it's worth localizing the message...like what is done in the other branch. Just make up an ID. Eventually, it will have to go in the XLF file to get translated, but we'll wait for that until the feature goes at least beta.
</blockquote></details>

Done.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4648)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)

**Pull request merged**
