### PR TITLE
BL-11406 Thumbnail -> Cover Color control

### PR DESCRIPTION
**Pull request by gmartin7**
* Change text to 'Cover Color'
* Rename controls
* storybook can't handle short form Fragments

- - -
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @gmartin7 and @hatton)

___
*[`src/BloomBrowserUI/publish/ReaderPublish/CoverColorGroup.tsx` line 84 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352#-NA6-Vwn7mZqW9ASQb7x:-NA6-Vwn7mZqW9ASQb7y:bcskzfv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dd2c1f3f3827a75a318c0c58d6951c90dac82778/src/BloomBrowserUI/publish/ReaderPublish/CoverColorGroup.tsx#L84)):*
> ```XML
>                     // the api ignores the color parameter, but it
>                     // causes this to re-request the img whenever the backcolor changes
>                     src={imagePath + bookCoverColor}
> ```

This is a great example of where making a const, only to use it once, makes the code harder to read. It made me wonder how a color appended to the path would not mess up the path. But if you you list it here, I would see how the color becomes the value of a parameter.
___
*[`src/BloomBrowserUI/publish/ReaderPublish/CoverColorGroup.tsx` line 91 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352#-NA60AXY5XQXPc1aYU8q:-NA60AXY5XQXPc1aYU8r:btqcsr4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dd2c1f3f3827a75a318c0c58d6951c90dac82778/src/BloomBrowserUI/publish/ReaderPublish/CoverColorGroup.tsx#L91)):*
> ```XML
> };
> 
> function getDialogContainer(): Element | undefined {
> ```

This seems wrong, un react-ish? I would expect that, like with Progress Dialog, there would be something like a single `<ColorPickerDialog>` at the root of each screen where we need it, and code would just make it visible as needed?



_Code quote:_
```XML
l
```
___
*[`src/BloomBrowserUI/react_components/colorPickerDialog.tsx` line 394 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352#-NA60XRtBC7Jfi47Fw-u:-NA60XRtBC7Jfi47Fw-v:b-91bizy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dd2c1f3f3827a75a318c0c58d6951c90dac82778/src/BloomBrowserUI/react_components/colorPickerDialog.tsx#L394)):*
> ```XML
> }
> 
> export const ColorBlock: React.FC<IColorBlockProps> = props => {
> ```

What is a "ColorBlock"? Is it a button that shows a color and opens a dialog if you click it? If so, how about `ColorDisplayButton`

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[`src/BloomBrowserUI/publish/ReaderPublish/CoverColorGroup.tsx` line 84 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352#-NA6-Vwn7mZqW9ASQb7x:-NA623fy1LWv3TUhaZfu:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dd2c1f3f3827a75a318c0c58d6951c90dac82778/src/BloomBrowserUI/publish/ReaderPublish/CoverColorGroup.tsx#L84)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This is a great example of where making a const, only to use it once, makes the code harder to read. It made me wonder how a color appended to the path would not mess up the path. But if you you list it here, I would see how the color becomes the value of a parameter.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/ReaderPublish/CoverColorGroup.tsx` line 91 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352#-NA60AXY5XQXPc1aYU8q:-NA66byg19YSWVlBfbGi:b-sjdft) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dd2c1f3f3827a75a318c0c58d6951c90dac82778/src/BloomBrowserUI/publish/ReaderPublish/CoverColorGroup.tsx#L91)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This seems wrong, un react-ish? I would expect that, like with Progress Dialog, there would be something like a single `<ColorPickerDialog>` at the root of each screen where we need it, and code would just make it visible as needed?
</blockquote></details>

Yeah, this was my attempt to deal with the original dialog looking for something in the edit tab environment that isn't there in the publish tab. Looking at the ProgressDialog stuff, that does look better.... but might take me awhile.
___
*[`src/BloomBrowserUI/react_components/colorPickerDialog.tsx` line 394 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352#-NA60XRtBC7Jfi47Fw-u:-NA62kXx1mhe0cXdOaSe:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dd2c1f3f3827a75a318c0c58d6951c90dac82778/src/BloomBrowserUI/react_components/colorPickerDialog.tsx#L394)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

What is a "ColorBlock"? Is it a button that shows a color and opens a dialog if you click it? If so, how about `ColorDisplayButton`
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @andrew-polk, @gmartin7, and @hatton)

___
*[`src/BloomBrowserUI/react_components/stories.tsx` line 905 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352#-NALNl7f3vyzAtEn9_2S:-NALNl7f3vyzAtEn9_2T:b-fs9s89) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c6454b189d1111af1f31c5890c9c0e2c12817c60/src/BloomBrowserUI/react_components/stories.tsx#L905)):*
> ```XML
>         })
>     )
>     .add("Color Picker Button", () =>
> ```

I think this would be better as simply `ColorDisplayButton`.

For bonus points, you could group the color picker stuff together in storybook with a prepended Color/ or ColorPicker/.



_Code quote:_
```XML
Color Picker Button
```

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomBrowserUI/react_components/stories.tsx` line 905 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352#-NALNl7f3vyzAtEn9_2S:-NALRCxc78sX46QDKSGx:b-17bxaj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c6454b189d1111af1f31c5890c9c0e2c12817c60/src/BloomBrowserUI/react_components/stories.tsx#L905)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this would be better as simply `ColorDisplayButton`.

For bonus points, you could group the color picker stuff together in storybook with a prepended Color/ or ColorPicker/.
</blockquote></details>

Done. `Misc/ColorPicker` now contains the 3 tests. (They were already grouped under `Misc/Custom Color Chooser`, but it's less about custom and more about palettes now.)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352)* status: all files reviewed, 4 unresolved discussions (waiting on @gmartin7 and @hatton)

___
*[`src/BloomBrowserUI/react_components/colorPickerDialog.tsx` line 47 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352#-NAQ8gesEueQwrFkpoBT:-NAQ8gesEueQwrFkpoBU:btifhy9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9d34cd6dfdb4156f59df98fbd6b4a1b0fd48dc51/src/BloomBrowserUI/react_components/colorPickerDialog.tsx#L47)):*
> ```XML
> export interface IColorPickerDialogProps {
>     open?: boolean;
>     close?: (result: DialogResult) => void;
> ```

If you make ColorPickerDialog use BloomDialog, does that mean we don't need to add these props? Or is this a necessity because we are launching it from both a react and non-react context?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomBrowserUI/react_components/colorPickerDialog.tsx` line 47 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352#-NAQ8gesEueQwrFkpoBT:-NAQSZTd9smfXnAy_KEY:b-ahtxmx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9d34cd6dfdb4156f59df98fbd6b4a1b0fd48dc51/src/BloomBrowserUI/react_components/colorPickerDialog.tsx#L47)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If you make ColorPickerDialog use BloomDialog, does that mean we don't need to add these props? Or is this a necessity because we are launching it from both a react and non-react context?
</blockquote></details>

Interesting... I don't know. I actually was under the impression that it DID you BloomDialog, but now I see it doesn't.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomBrowserUI/react_components/colorPickerDialog.tsx` line 47 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352#-NAQ8gesEueQwrFkpoBT:-NAQV3q42iw7zg3hpcMG:bb6e5ya) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9d34cd6dfdb4156f59df98fbd6b4a1b0fd48dc51/src/BloomBrowserUI/react_components/colorPickerDialog.tsx#L47)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Interesting... I don't know. I actually was under the impression that it DID you BloomDialog, but now I see it doesn't.
</blockquote></details>

*use

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomBrowserUI/react_components/colorPickerDialog.tsx` line 47 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352#-NAQ8gesEueQwrFkpoBT:-NAQZ-hy-v4kLxY7LCah:b-z7muy9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9d34cd6dfdb4156f59df98fbd6b4a1b0fd48dc51/src/BloomBrowserUI/react_components/colorPickerDialog.tsx#L47)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

*use
</blockquote></details>

As this is supposed to be a "thin" change to get the Android cover color picker to use this dialog, I don't think I want to go into whether we should be using BloomDialog right now, when it might affect the StyleEditor color picker and the OverlayTool color picker.
OTOH, I don't know that we ARE launching this dialog from any non-react contexts.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomBrowserUI/publish/ReaderPublish/CoverColorGroup.tsx` line 91 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352#-NA60AXY5XQXPc1aYU8q:-NAR4LBT21VoSNHeQkyk:b-v2typ3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dd2c1f3f3827a75a318c0c58d6951c90dac82778/src/BloomBrowserUI/publish/ReaderPublish/CoverColorGroup.tsx#L91)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Yeah, this was my attempt to deal with the original dialog looking for something in the edit tab environment that isn't there in the publish tab. Looking at the ProgressDialog stuff, that does look better.... but might take me awhile.
</blockquote></details>

OK, no longer need this. I have ideas for further improvements too. Andrew & I think this dialog should use BloomDialog and initial work shows it might not be too bad, but I think I'll work on that after this is merged.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[`src/BloomBrowserUI/react_components/colorPickerDialog.tsx` line 47 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5352#-NAQ8gesEueQwrFkpoBT:-NAR5561-0gqgTsabM-7:b-5lppeq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9d34cd6dfdb4156f59df98fbd6b4a1b0fd48dc51/src/BloomBrowserUI/react_components/colorPickerDialog.tsx#L47)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

As this is supposed to be a "thin" change to get the Android cover color picker to use this dialog, I don't think I want to go into whether we should be using BloomDialog right now, when it might affect the StyleEditor color picker and the OverlayTool color picker.
OTOH, I don't know that we ARE launching this dialog from any non-react contexts.
</blockquote></details>

We decided we can come back to this after the merge.

**Pull request merged**
