### PR TITLE
BL-2907 Make accordion always available [3.6]

### PR DESCRIPTION
**Pull request by JohnThomson**
[Review on Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/874)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Should not merge into master until we make the 3.5 branch (this is a 3.6 feature)

**Comment by hatton** [comment]
Please remove the circle from both modes

**Comment by hatton** [comment]
John on my laptop here, once the decodable settings is open, you can't see any of the closed sections of the accordion. It's as if they are pushed off the bottom of the screen

**Comment by hatton** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/BloomExe/Edit/EditingModel.cs, line 1109 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/874#-K3_7IuMLapA-KJ6ZLPm:-K3_7IuMLapA-KJ6ZLPn:-1467935823) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/28ec168a94b19623f87498b4d147f13b6d2bdb84/src/BloomExe/Edit/EditingModel.cs#L1109)):_
Shall we rename ReaderToolsAvailable? Shall we move from "Accordion" to "Toolbox"? The later is presumably what we'll call it in documentation and training, so it would simplify things for new devs. That name change would be in may places.

But here,  we'd have ReaderToolsAvailable --> ToolboxIsOpen

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/874)_

**Comment by JohnThomson** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/BloomExe/Edit/EditingModel.cs, line 1109 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/874#-K3_7IuMLapA-KJ6ZLPm:-K3aa8YW2vIXf3UkQU4a:-1809108959) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/28ec168a94b19623f87498b4d147f13b6d2bdb84/src/BloomExe/Edit/EditingModel.cs#L1109)):_
I think it's a good idea but I'd rather make a separate card for it, to be worked on when we're not doing anything else with the accordion/toolbox. If I try to add it as a commit to this PR, merging Gordon's attempt at moving the audio into the toolbox will be a nightmare.
ReaderToolsAvailable is a field we push to parse.com (and download into templates) and is part of all the meta.json files in the bloom library. We can of course add code to migrate it. A quick test indicates that it won't be a problem if an old version of Bloom downloads a book with a meta.json that has toolboxIsOpen instead, but if it was a decodable book the old Bloom will have no way to access the reader tools (since readerToolsAvailable won't be there).

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/874)_

**Comment by hatton** [comment]
Reviewed 1 of 5 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/BloomExe/Edit/EditingModel.cs, line 1109 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/874#-K3_7IuMLapA-KJ6ZLPm:-K3aeOnbEvJKVXyGvg2b:-387512339) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/28ec168a94b19623f87498b4d147f13b6d2bdb84/src/BloomExe/Edit/EditingModel.cs#L1109)):_
I don't suppose Gordon's thing will fit what I asked for anyhow. I asked for an architecture in which section of the according is a component.  I don't see that here, so I don't expect to see it with his PR. But of course you're welcome to merge this and keep working on it with a new PR.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/874)_

**Pull request merged**
