### PR TITLE
Support HTML widget page elements (BL-8383)

### PR DESCRIPTION
**Pull request by JohnThomson**
Need a BR enhancement to prevent complaining about HTML files in folders (and ideally one to report problems in widgets).

Along the way I sorted out some confusion about the type of the "container" argument to bloomEditing.js's  SetupElements function.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714)* status: all files reviewed, 15 unresolved discussions (waiting on @JohnThomson)

___
*[DistFiles/localization/en/Bloom.xlf, line 2503 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6q9t3E8sgfA6H3t6bu:-M6q9t3E8sgfA6H3t6bv:bmlslhz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/DistFiles/localization/en/Bloom.xlf#L2503)):*
> ```
> ChangeWidget
> ```
ChooseWidget?
Same two lines below.
___
*[src/BloomBrowserUI/bookEdit/css/editMode.less, line 158 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qACxu9k6AZgCHhP6E:-M6qACxu9k6AZgCHhP6F:b-f9d790) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomBrowserUI/bookEdit/css/editMode.less#L158)):*
> ```
> changeWidgetButton
> ```
Sorry to nitpick. but I'd rather do this now than live with the inconsisentency forever.
Can you make "change" => "choose" everywhere?
___
*[src/BloomBrowserUI/bookEdit/js/origami.ts, line 372 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qAd0c13cLIp-89JSx:-M6qAd0c13cLIp-89JSy:bsqxjq3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomBrowserUI/bookEdit/js/origami.ts#L372)):*
> ```
> EditTab.CustomPage.HtmlWidget
> ```
This didn't make it into Bloom.xlf
___
*[src/BloomExe/ElementProxy.cs, line 213 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qChpU0O1B_b3EPWR2:-M6qChpU0O1B_b3EPWR3:bbw3md8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomExe/ElementProxy.cs#L213)):*
> ```
> SetClass(string className, bool wanted)
> ```
Something about the naming here is throwing me off.
How about Toggle? Or AddOrRemove? Or just two separate methods which could even call this common code?

Not a show-stopper. I figured it out, but it threw me at first.

Also, I'm surprised this code doesn't live somewhere already.
___
*[src/BloomExe/Book/BookStorage.cs, line 947 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qElWm8yUg6PtAXOce:-M6qElWm8yUg6PtAXOcf:b-9vvcyi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomExe/Book/BookStorage.cs#L947)):*
> ```Smalltalk
> 				var folder = Path.GetFileName(Path.GetDirectoryName(src));
> 				wantedFolders.Add(folder);
> 			}
> ```

Unless I'm missing something, this can be simplified by calling `GetActivityFolderNamesReferencedInBook`
___
*[src/BloomExe/Edit/EditingModel.cs, line 1399 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qG4h3BNfTzPjro-Ki:-M6qG4h3BNfTzPjro-Kj:bk8wbjl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomExe/Edit/EditingModel.cs#L1399)):*
> ```Smalltalk
> 		}
> 
> 		public static void MakeActivity(string bookFolderPath, string fullWidgetPath, ElementProxy widgetContainer)
> ```

What's the feasibility of moving all the activity-related code to another file?
___
*[src/BloomExe/Edit/EditingModel.cs, line 1412 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qGXTQ6K2RfnQ3YtVG:-M6qGXTQ6K2RfnQ3YtVH:bcrnkrh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomExe/Edit/EditingModel.cs#L1412)):*
> ```Smalltalk
> 				widgetName = Path.GetFileNameWithoutExtension(widgetPath) + suffix;
> 				widgetDestinationFolder = bookFolderPath + "/" + "activities" + "/" + widgetName;
> 			}
> ```

We don't have reusable code somewhere to do this? I guess maybe it is too specific to specific paths...
___
*[src/BloomExe/Edit/EditingModel.cs, line 1437 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qGyV59pmoz8ezoMAB:-M6qGyV69b2iEHiQj4we:b-ry098d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomExe/Edit/EditingModel.cs#L1437)):*
> ```Smalltalk
> 				}
> 			}
> 			zipFile.Close();
> ```

Surely it seems unzip code must or should live somewhere else...
___
*[src/BloomExe/Edit/EditingModel.cs, line 1477 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qKhFQAguz7QggMt7g:-M6qKhFR-l80DIr-nRmV:binem5f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomExe/Edit/EditingModel.cs#L1477)):*
> ```Smalltalk
> 				iframeProxy = widgetContainer.AppendChild("iframe");
> 			var indexPath = "activities" + "/" + widgetName + "/" + rootFileName;
> 			iframeProxy.SetAttribute("src", indexPath);
> ```

We don't need any encoding here?
___
*[src/BloomExe/Edit/EditingModel.cs, line 1486 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qFi6UBzlhV9NwWROL:-M6qFi6UBzlhV9NwWROM:b-h3u4m6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomExe/Edit/EditingModel.cs#L1486)):*
> ```Smalltalk
> 		}
> 
> 		private static bool SameContent(string dir1, string dir2)
> ```

Is there a better place for this method?
In some IO helper?
___
*[src/BloomExe/Edit/EditingView.cs, line 986 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qIpUJ3hrJgpg7IAOA:-M6qIpUJ3hrJgpg7IAOB:bboy8dp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomExe/Edit/EditingView.cs#L986)):*
> ```Smalltalk
> 		}
> 
> 		private void OnChangeWidget(DomEventArgs ge)
> ```

Seems it wouldn't be terribly difficult to move this method into the API-like classes. You should be able to get an editing model there, I think.
Don't do any heroics, though.
___
*[src/BloomTests/Book/BookStorageTests.cs, line 381 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qKnKqCVEhDwYxKKDB:-M6qKnKqCVEhDwYxKKDC:b-liezj6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomTests/Book/BookStorageTests.cs#L381)):*
> ```
> Onees
> ```
Ones 
___
*[src/BloomTests/Book/BookStorageTests.cs, line 416 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qLehf19viI5mei20D:-M6qLehf19viI5mei20E:b-ybg0xz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomTests/Book/BookStorageTests.cs#L416)):*
> ```Smalltalk
> 			// and so the test will survive if we should happen to remove the call to it
> 			// during GetInitialStorageWithCustomHtml(). But actually the redundant files
> 			// have already been removed.
> ```

Cleanup... isn't called directly in GetInitial...
Does it happen during `Save()`?
If so, you can pass the second param to tell it not to save.
___
*[src/BloomTests/Edit/EditingModelTests.cs, line 24 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qJpqe4AMBfdV06YR2:-M6qJpqe4AMBfdV06YR3:b-l5vxbl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomTests/Edit/EditingModelTests.cs#L24)):*
> ```
> 			// This is a monster but all the state we create in setting up for the test of a first-time
> 			// copy is useful in subsequent tests about duplicates and near-duplicates.
> ```
A thought... see what you think...
You could make Activity tests their own fixture so that you can do a one-time fixture setup with multiple tests which run.
Will likely encourage any future tests to get added whereas this mega test would likely discourage future tests.
___
*[src/BloomTests/Edit/EditingModelTests.cs, line 32 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qK7kH8Xb-uzcbq4Ed:-M6qK7kH8Xb-uzcbq4Ee:bsvlx95) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomTests/Edit/EditingModelTests.cs#L32)):*
> ```Smalltalk
> 					//var zipStream = new ZipOutputStream(fsOut);
> 					//zipStream.SetLevel(1); // fast, poor compression is fine for this
> 					//zipStream.Close();
> ```

Any reason to leave this commented code?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Edit/EditingModel.cs, line 1437 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qGyV59pmoz8ezoMAB:-M750Ac4Ex9M47o7mPtf:beuf1at) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomExe/Edit/EditingModel.cs#L1437)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Surely it seems unzip code must or should live somewhere else...
</blockquote></details>

Thanks. Sorry, I see now that comment could have come across as demeaning which was not my intention. I mostly was incredulous this code base doesn't already have unzip code somewhere.
___
*[src/BloomExe/web/controllers/EditingViewApi.cs, line 39 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M75-9Ju0ron0gF0Pvs8:-M75-9Ju0ron0gF0Pvs9:b-m54azm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6220c84db3eadc2314ed3e1b27cce2ce49839c7/src/BloomExe/web/controllers/EditingViewApi.cs#L39)):*
> ```Smalltalk
> 					LocalizationManager.GetString("EditTab.CantPasteImageLocked",
> 						"Sorry, this book is locked down so that images cannot be changed."));
> 				return;
> ```

I think the request needs to do something here.
ReplyWithText("")?
or fail?
___
*[src/BloomTests/Edit/EditingModelTests.cs, line 24 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qJpqe4AMBfdV06YR2:-M753X9BB08bH1rq02ah:b3tghqf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomTests/Edit/EditingModelTests.cs#L24)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> 			// This is a monster but all the state we create in setting up for the test of a first-time
> 			// copy is useful in subsequent tests about duplicates and near-duplicates.
> ```
A thought... see what you think...
You could make Activity tests their own fixture so that you can do a one-time fixture setup with multiple tests which run.
Will likely encourage any future tests to get added whereas this mega test would likely discourage future tests.
</blockquote></details>

Cool. By the way, I didn't mean to suggest you make a special file for MakeActivity, just a fixture.
But what you have is fine.
___
*[src/BloomTests/Edit/MakeActivityTests.cs, line 25 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M752oGZ2ajVn-LJyhTD:-M752oGZ2ajVn-LJyhTE:bwmcgqo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6220c84db3eadc2314ed3e1b27cce2ce49839c7/src/BloomTests/Edit/MakeActivityTests.cs#L25)):*
> ```Smalltalk
> 		private string secondActivityFolder;
> 		private string firstWidgetSrcPath;
> 		private string secondWidgetSrcPath;
> ```

Typically these would all begin with underscore.
___
*[src/BloomTests/Edit/MakeActivityTests.cs, line 35 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M7535fUED6P3UiNb-FT:-M7535fUED6P3UiNb-FU:b-buf55d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6220c84db3eadc2314ed3e1b27cce2ce49839c7/src/BloomTests/Edit/MakeActivityTests.cs#L35)):*
> ```
> // This is a default state for the zip, to which each test should return it if it modifies it.
> ```
Would it make more sense to set up the zip file once per test in the per-test setup method?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714)* status: 22 of 24 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[DistFiles/localization/en/Bloom.xlf, line 2503 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6q9t3E8sgfA6H3t6bu:-M74JOrI05frE-leCPxW:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/DistFiles/localization/en/Bloom.xlf#L2503)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> ChangeWidget
> ```
ChooseWidget?
Same two lines below.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/css/editMode.less, line 158 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qACxu9k6AZgCHhP6E:-M74Jifc31aYddHLQ32p:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomBrowserUI/bookEdit/css/editMode.less#L158)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> changeWidgetButton
> ```
Sorry to nitpick. but I'd rather do this now than live with the inconsisentency forever.
Can you make "change" => "choose" everywhere?
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/js/origami.ts, line 372 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qAd0c13cLIp-89JSx:-M74KSjnA7YAGj9BgZJS:b-376vyb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomBrowserUI/bookEdit/js/origami.ts#L372)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> EditTab.CustomPage.HtmlWidget
> ```
This didn't make it into Bloom.xlf
</blockquote></details>

Done. Good catch.
___
*[src/BloomExe/ElementProxy.cs, line 213 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qChpU0O1B_b3EPWR2:-M74MZZE5UDir8n5Tw09:b7f6alx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomExe/ElementProxy.cs#L213)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> SetClass(string className, bool wanted)
> ```
Something about the naming here is throwing me off.
How about Toggle? Or AddOrRemove? Or just two separate methods which could even call this common code?

Not a show-stopper. I figured it out, but it threw me at first.

Also, I'm surprised this code doesn't live somewhere already.
</blockquote></details>

Toggle is definitely wrong...it may not change anything. (May not add or remove, if it comes to that, but Toggle has an even more definite expectation of unconditional change.) I don't like either Set or AddOrRemove but the latter is perhaps marginally better so I added it and also separate Add and Remove methods.
___
*[src/BloomExe/Book/BookStorage.cs, line 947 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qElWm8yUg6PtAXOce:-M74OgqR5vu1xpe1nxkf:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomExe/Book/BookStorage.cs#L947)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Unless I'm missing something, this can be simplified by calling `GetActivityFolderNamesReferencedInBook`
</blockquote></details>

Done.
___
*[src/BloomExe/Edit/EditingModel.cs, line 1399 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qG4h3BNfTzPjro-Ki:-M74rtOWDUCIONLqBPVR:bl8widw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomExe/Edit/EditingModel.cs#L1399)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What's the feasibility of moving all the activity-related code to another file?
</blockquote></details>

A couple of big chunks got moved into utilities. But as we discussed, the Activity code is in a lot of places, so there's no good home for the new file. So on the whole I don't think this is the right answer, though it would be nice to end the continual growth of several files modified here.
___
*[src/BloomExe/Edit/EditingModel.cs, line 1412 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qGXTQ6K2RfnQ3YtVG:-M74UJc1Ak3fLryABD5m:b9dq6rs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomExe/Edit/EditingModel.cs#L1412)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We don't have reusable code somewhere to do this? I guess maybe it is too specific to specific paths...
</blockquote></details>

There's similar code for files, though I don't think we've yet extracted a method...this is the only place I know that needs a unique folder name.
___
*[src/BloomExe/Edit/EditingModel.cs, line 1437 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qGyV59pmoz8ezoMAB:-M74TYoTBauEpOus9pBM:bi95tjf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomExe/Edit/EditingModel.cs#L1437)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Thanks. Sorry, I see now that comment could have come across as demeaning which was not my intention. I mostly was incredulous this code base doesn't already have unzip code somewhere.
</blockquote></details>

I made a new utility class. (And I didn't find the comment objectionable.)
___
*[src/BloomExe/Edit/EditingModel.cs, line 1477 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qKhFQAguz7QggMt7g:-M74sG1oDViL_0Jxx9ua:b-2f9swh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomExe/Edit/EditingModel.cs#L1477)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We don't need any encoding here?
</blockquote></details>

No doubt we do.
___
*[src/BloomExe/Edit/EditingModel.cs, line 1486 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qFi6UBzlhV9NwWROL:-M74X_x8BDSxEinDiBaF:behfgod) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomExe/Edit/EditingModel.cs#L1486)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is there a better place for this method?
In some IO helper?
</blockquote></details>

I made a new ToLibPalaso.DirectoryUtils. I think there's such a class where it would be a logical fit...but don't want to mess with changing LibPalaso just for this.
___
*[src/BloomExe/Edit/EditingView.cs, line 986 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qIpUJ3hrJgpg7IAOA:-M74fsct16CgGuN9Us9m:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomExe/Edit/EditingView.cs#L986)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems it wouldn't be terribly difficult to move this method into the API-like classes. You should be able to get an editing model there, I think.
Don't do any heroics, though.
</blockquote></details>

Done.
___
*[src/BloomExe/web/controllers/EditingViewApi.cs, line 39 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M75-9Ju0ron0gF0Pvs8:-M78-dIW3y4wKta7kYRK:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6220c84db3eadc2314ed3e1b27cce2ce49839c7/src/BloomExe/web/controllers/EditingViewApi.cs#L39)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think the request needs to do something here.
ReplyWithText("")?
or fail?
</blockquote></details>

Done.
___
*[src/BloomTests/Book/BookStorageTests.cs, line 381 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qKnKqCVEhDwYxKKDB:-M74g3A_7keYrIYnM72k:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomTests/Book/BookStorageTests.cs#L381)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Onees
> ```
Ones 
</blockquote></details>

Done.
___
*[src/BloomTests/Book/BookStorageTests.cs, line 416 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qLehf19viI5mei20D:-M74gjGW6GsoMvjQAi1C:bxcd1ur) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomTests/Book/BookStorageTests.cs#L416)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Cleanup... isn't called directly in GetInitial...
Does it happen during `Save()`?
If so, you can pass the second param to tell it not to save.
</blockquote></details>

No. Happens during ExpensiveInitialization, called from the BookStorage constructor
___
*[src/BloomTests/Edit/EditingModelTests.cs, line 24 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qJpqe4AMBfdV06YR2:-M74rXI62kj1byBerjY5:b-1eav9x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomTests/Edit/EditingModelTests.cs#L24)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> 			// This is a monster but all the state we create in setting up for the test of a first-time
> 			// copy is useful in subsequent tests about duplicates and near-duplicates.
> ```
A thought... see what you think...
You could make Activity tests their own fixture so that you can do a one-time fixture setup with multiple tests which run.
Will likely encourage any future tests to get added whereas this mega test would likely discourage future tests.
</blockquote></details>

I think you're right. A little bit is lost because we're not testing the ability to stack up five widgets, and there's more cleanup after each test, but I think overall it's cleaner.
(And of course now the changes to the HTML Element are happening in Javascript, so can't test here.)
___
*[src/BloomTests/Edit/EditingModelTests.cs, line 32 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M6qK7kH8Xb-uzcbq4Ed:-M74rWq40KOp-r-62dbf:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c83b2be6448480452576c6bee09a6f2582764687/src/BloomTests/Edit/EditingModelTests.cs#L32)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Any reason to leave this commented code?
</blockquote></details>

Done.
___
*[src/BloomTests/Edit/MakeActivityTests.cs, line 25 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M752oGZ2ajVn-LJyhTD:-M7809CB6YC9GT4CIcJb:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6220c84db3eadc2314ed3e1b27cce2ce49839c7/src/BloomTests/Edit/MakeActivityTests.cs#L25)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Typically these would all begin with underscore.
</blockquote></details>

Done.
___
*[src/BloomTests/Edit/MakeActivityTests.cs, line 35 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714#-M7535fUED6P3UiNb-FT:-M784_LTE5m23fLstZQZ:b-d2g3kd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6220c84db3eadc2314ed3e1b27cce2ce49839c7/src/BloomTests/Edit/MakeActivityTests.cs#L35)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> // This is a default state for the zip, to which each test should return it if it modifies it.
> ```
Would it make more sense to set up the zip file once per test in the per-test setup method?
</blockquote></details>

You're right. 30 lines shorter and I think clearer as well.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3714)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
