### PR TITLE
Ensure & in copyright notice is handled for shell books (BL-4585)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1656)

### CODE REVIEW

**Comment by hatton** [comment]
Is it feasible to write a unit test showing the problem?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1656#-:-KhYdRBPnbssz5MWaKm-:b-cxcgt4)*

**Comment by JohnThomson** [comment]
Possibly I'm being too picky. Main thing is to have a test which checks the problem is fixed. See what you think.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomTests/Book/BookCopyrightAndLicenseTests.cs, line 571 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1656#-KiWR_b919ALaVCrPmJq:-KiWR_b919ALaVCrPmJr:b-460e53) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e1b7c3f69610a03346007a12a8c6770657d39fa/src/BloomTests/Book/BookCopyrightAndLicenseTests.cs#L571)):*
> ```Smalltalk
> 				@"<html>
> 				  <body>
> 				    <div id='bloomDataDiv'>
> ```

Can we shorten this? Makes it both faster to run and easier to read. It's not obvious that the purpose of this test requires anything in the body but the one copyright data div and maybe the data-derived copyright div and parents.
If we really need all this data it might be worth commenting why and also in a comment calling attention to the fact that the critical point of it all is the occurrence of the escaped ampersand in the copyright.

---

*[src/BloomTests/Book/BookCopyrightAndLicenseTests.cs, line 617 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1656#-KiWSu0lRE9PXu607nNE:-KiWSu0lRE9PXu607nNF:b-n303q7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e1b7c3f69610a03346007a12a8c6770657d39fa/src/BloomTests/Book/BookCopyrightAndLicenseTests.cs#L617)):*
> ```Smalltalk
> 			Assert.AreEqual("Adapted from original, Copyright © 2011, LASI &amp; SILA. Licensed under CC-BY-NC-SA 4.0.", nodes1.Item(0).InnerXml);
> 			var nodes2 = dom.RawDom.SelectNodes("/html/body//div[@data-derived='copyright']");
> 			Assert.AreEqual(1, nodes2.Count);
> ```

It's not obvious what the rest of this has to do with the purpose of the test. Recommend removing or explaining in a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1656#-:-KiWTEBYhYs6T_xd1Jrz:b-mtyjr1)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomTests/Book/BookCopyrightAndLicenseTests.cs, line 571 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1656#-KiWR_b919ALaVCrPmJq:-KibKnHW8QpZmJrQZEnu:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e1b7c3f69610a03346007a12a8c6770657d39fa/src/BloomTests/Book/BookCopyrightAndLicenseTests.cs#L571)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Can we shorten this? Makes it both faster to run and easier to read. It's not obvious that the purpose of this test requires anything in the body but the one copyright data div and maybe the data-derived copyright div and parents.
If we really need all this data it might be worth commenting why and also in a comment calling attention to the fact that the critical point of it all is the occurrence of the escaped ampersand in the copyright.
</blockquote></details>

Done.

---

*[src/BloomTests/Book/BookCopyrightAndLicenseTests.cs, line 617 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1656#-KiWSu0lRE9PXu607nNE:-KibKoPZm2-5I39b3PSQ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e1b7c3f69610a03346007a12a8c6770657d39fa/src/BloomTests/Book/BookCopyrightAndLicenseTests.cs#L617)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's not obvious what the rest of this has to do with the purpose of the test. Recommend removing or explaining in a comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1656)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1656#-:-Kiev1hgaI-8j6eOrtIC:bnfp4nl)*

**Pull request merged**
