### PR TITLE
Create Linux launcher to show instant splash screen (BL-4666)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1709)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/LinuxBloomLauncher/BloomSplash.png, line 0 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnBxWQm1WXNgyc_CS3S:-KnBxWQnQfWgwlsErGZC:b-25a0tg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/448bdc73929bef33245c0fc58c91884e10724c61/src/LinuxBloomLauncher/BloomSplash.png#L0)):*
1)  Let's remove the copyright date, so that we don't have to update this once a year.
2) Expensive to have just one copy of this? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709)*

**Comment by JohnThomson** [comment]
Looks basically good. A few minor questions, probably mostly reflecting my relative ignorance of Bloom on Linux.
I don't see any changes that seem aimed at actually causing the launcher to be the thing that runs when the user double-clicks the Bloom icon, or whatever other ways there are to launch it on Linux...

---

Review status: 0 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[Bloom.sln, line 31 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnFZJy_TSF-e7Q-Frus:-KnFZJy_TSF-e7Q-Frut:b-7ne7qi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/448bdc73929bef33245c0fc58c91884e10724c61/Bloom.sln#L31)):*
> ```
> EndProject
> Project("{2857B73E-F847-4B02-9238-064979017E93}") = "LinuxBloomLauncher", "src\LinuxBloomLauncher\LinuxBloomLauncher.cproj", "{6E2F50BB-FC1A-4F19-BD19-5B2457D3C411}"
> EndProject
> ```

is there something we can/should add (somewhere) to prevent trying to build this on Windows?

---

*[src/LinuxBloomLauncher/BloomLauncher.c, line 55 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnF_-7hXvCLD3tqtEKW:-KnF_-7hXvCLD3tqtEKX:bl319l2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/448bdc73929bef33245c0fc58c91884e10724c61/src/LinuxBloomLauncher/BloomLauncher.c#L55)):*
> ```C
> 	gtk_init(&argc, &argv);
> 	GtkWidget *window = gtk_window_new(GTK_WINDOW_TOPLEVEL);
> 	gtk_window_set_title(GTK_WINDOW(window), "Instant Bloom Splash Screen");
> ```

I suppose this isn't a title the user sees? If it is we'd want to think about localization, and probably drop "Instant"

---

*[src/LinuxBloomLauncher/BloomLauncher.c, line 71 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnF_UGWSL72O_bNarp-:-KnF_UGWSL72O_bNarp0:b1ulwe9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/448bdc73929bef33245c0fc58c91884e10724c61/src/LinuxBloomLauncher/BloomLauncher.c#L71)):*
> ```C
> 	/* create the image from the embedded resource and display it in the main window */
> 	GError *error = NULL;
> 	GdkPixbuf *pixbuf = gdk_pixbuf_new_from_resource("/sil/bloom/launch/BloomSplash.png", &error);
> ```

Is this name right for all channels? (I don't recall how Linux handles parallel alpha/beta/release installs...)

---

*[src/LinuxBloomLauncher/BloomLauncher.c, line 87 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnFe6U_yKoJfT0L1511:-KnFe6U_yKoJfT0L1512:bvj3y9v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/448bdc73929bef33245c0fc58c91884e10724c61/src/LinuxBloomLauncher/BloomLauncher.c#L87)):*
> ```C
> 		return 1;
> 	gchar ** envpBloom = GetEnvpForBloom();
> 	gboolean okay = g_spawn_async(NULL, argvBloom, envpBloom, G_SPAWN_DO_NOT_REAP_CHILD,
> ```

Any benefit (e.g., reduced overall startup time?) to doing this before we put up the window (but, to avoid race conditions, not before we make the flag file)? Or would that just make it likely that on a single-core system the splash screen would not be seen? And maybe the time to display it is negligible anyway...

---

*[src/LinuxBloomLauncher/BloomLauncher.c, line 134 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnFar5pdO5N_34mYdmx:-KnFar5pdO5N_34mYdmy:bl8tg4m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/448bdc73929bef33245c0fc58c91884e10724c61/src/LinuxBloomLauncher/BloomLauncher.c#L134)):*
> ```C
> {
> 	++counter;
> 	if (counter >= 60 || access(flagFile, F_OK))
> ```

This feels backwards...quit if you CAN access the flagFile...but I suppose this is a library method with a non-obvious meaning? It's not a function I'm familiar with or was easily able to google, so it might deserve a comment.

---

*[src/LinuxBloomLauncher/BloomLauncher.c, line 155 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnFbwUDcSOmVlB90SpA:-KnFbwUDcSOmVlB90SpB:bf4i6d4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/448bdc73929bef33245c0fc58c91884e10724c61/src/LinuxBloomLauncher/BloomLauncher.c#L155)):*
> ```C
> 
> 	argvNew[0] = g_strdup("/opt/mono4-sil/bin/mono");
> 	argvNew[1] = g_strdup("--debug");
> ```

Do we want --debug in production? Either way, I think some comment on why we pass these args (or maybe a cross-ref to some other doc) might be helpful...maybe not needed by other Linux devs, they might find it obvious; I'll let you judge. For my part, my recollection is to expect the executing program to be argv[0], so an explanation of why that isn't so might be helpful.

---

*[src/LinuxBloomLauncher/BloomLauncher.c, line 180 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnFcXk9HSlEehU5SvPP:-KnFcXk9HSlEehU5SvPQ:b4nn8jg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/448bdc73929bef33245c0fc58c91884e10724c61/src/LinuxBloomLauncher/BloomLauncher.c#L180)):*
> ```C
> 	programDirectory = g_strndup(progpath, enddirs - progpath);
> 	++enddirs;
> 	if (enddirs + strlen("Bloom.exe") > progpath + PATH_MAX)
> ```

Not channel-dependent?

---

*[src/LinuxBloomLauncher/BloomLauncher.c, line 270 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnFdLbBjVG69pdbGAKG:-KnFdLbBjVG69pdbGAKH:bi1fuha) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/448bdc73929bef33245c0fc58c91884e10724c61/src/LinuxBloomLauncher/BloomLauncher.c#L270)):*
> ```C
> {
> 	int fd = open(flagFile, O_CREAT|O_EXCL, 0644);
> 	if (fd < 0)
> ```

That is, if we failed to open it, presumably because it exists? I suppose there's no other plausible reason we might not be able to create it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-:-KnFf58O2PotShoUrZny:b-3j4xw6)*

**Comment by StephenMcConnel** [comment]
Using the launcher is done by the bloom-alpha shell script in the debian folder.

---

Review status: 0 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[Bloom.sln, line 31 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnFZJy_TSF-e7Q-Frus:-KnGvivQa39cO_tZPSVH:b-ubmxdo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/448bdc73929bef33245c0fc58c91884e10724c61/Bloom.sln#L31)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

is there something we can/should add (somewhere) to prevent trying to build this on Windows?
</blockquote></details>

I already made the explicit Build and Clean targets to be conditional on OS != Windows_NT in the .cproj file created by MonoDevelop.  I don't know of any way to make a project conditional in the .sln file.

---

*[src/LinuxBloomLauncher/BloomLauncher.c, line 55 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnF_-7hXvCLD3tqtEKW:-KnGw4oq8BT-cBmefSdJ:byc0d7f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/448bdc73929bef33245c0fc58c91884e10724c61/src/LinuxBloomLauncher/BloomLauncher.c#L55)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I suppose this isn't a title the user sees? If it is we'd want to think about localization, and probably drop "Instant"
</blockquote></details>

Yes, nobody ever sees this title.  I'm not sure whether the GTK system requires it or not, but the sample code I borrowed from had a title being set.  I've removed this line since it does seem rather pointless and doesn't seem to be needed.

---

*[src/LinuxBloomLauncher/BloomLauncher.c, line 71 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnF_UGWSL72O_bNarp-:-KnGwL_yxTWYz_cc1oU3:bgy3x2u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/448bdc73929bef33245c0fc58c91884e10724c61/src/LinuxBloomLauncher/BloomLauncher.c#L71)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is this name right for all channels? (I don't recall how Linux handles parallel alpha/beta/release installs...)
</blockquote></details>

we're using only one image for all channels at the moment, both on Linux and Windows.

---

*[src/LinuxBloomLauncher/BloomLauncher.c, line 87 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnFe6U_yKoJfT0L1511:-KnGwZ55ZkMGwlzyK54J:bvb09bk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/448bdc73929bef33245c0fc58c91884e10724c61/src/LinuxBloomLauncher/BloomLauncher.c#L87)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Any benefit (e.g., reduced overall startup time?) to doing this before we put up the window (but, to avoid race conditions, not before we make the flag file)? Or would that just make it likely that on a single-core system the splash screen would not be seen? And maybe the time to display it is negligible anyway...
</blockquote></details>

I moved the steps to create and add the image proper to the window after the spawn.  The actual "show" method is already after the spawn.  On my (admittedly fairly fast) Linux box, the image seems to pop up before the terminal window updates in response to my hitting Enter to execute this program.  :-)

---

*[src/LinuxBloomLauncher/BloomLauncher.c, line 134 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnFar5pdO5N_34mYdmx:-KnGQy60HDV3SYoU4EW0:b-lc3d5h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/448bdc73929bef33245c0fc58c91884e10724c61/src/LinuxBloomLauncher/BloomLauncher.c#L134)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This feels backwards...quit if you CAN access the flagFile...but I suppose this is a library method with a non-obvious meaning? It's not a function I'm familiar with or was easily able to google, so it might deserve a comment.
</blockquote></details>

access() is a standard Linux system call that return 0 if the file exists, -1 if it doesn't.  I agree the return value seems backward, but a lot of Linux methods (and Linux programs) use 0 for success and something nonzero for an error.

---

*[src/LinuxBloomLauncher/BloomLauncher.c, line 155 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnFbwUDcSOmVlB90SpA:-KnGP2Lk5ywZZDpn7rLX:b-6mqvb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/448bdc73929bef33245c0fc58c91884e10724c61/src/LinuxBloomLauncher/BloomLauncher.c#L155)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Do we want --debug in production? Either way, I think some comment on why we pass these args (or maybe a cross-ref to some other doc) might be helpful...maybe not needed by other Linux devs, they might find it obvious; I'll let you judge. For my part, my recollection is to expect the executing program to be argv[0], so an explanation of why that isn't so might be helpful.
</blockquote></details>

mono IS the executing program from the point of view of the Linux kernel.  I think --debug is needed to get line numbers in stack traces.  But it also slows down execution (to an unknown, possibly trivial, extent), so maybe we shouldn't use it.  The current shell scripts all seem to have it.

I've commented the --debug line out with a comment in case we decide to reinstate it.  I also added a comment explaining that mono is the executing program, Bloom.exe is just data for it.  :-)

---

*[src/LinuxBloomLauncher/BloomLauncher.c, line 180 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnFcXk9HSlEehU5SvPP:-KnGQCkQM0dwEy2VjxRC:b-k1u54e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/448bdc73929bef33245c0fc58c91884e10724c61/src/LinuxBloomLauncher/BloomLauncher.c#L180)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Not channel-dependent?
</blockquote></details>

On Linux, the channel is reflected in directory names and shell script names, not in the name of the Bloom.exe assembly itself.

---

*[src/LinuxBloomLauncher/BloomLauncher.c, line 270 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnFdLbBjVG69pdbGAKG:-KnGSCwqms_n-ygwkEod:b-dyteww) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/448bdc73929bef33245c0fc58c91884e10724c61/src/LinuxBloomLauncher/BloomLauncher.c#L270)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

That is, if we failed to open it, presumably because it exists? I suppose there's no other plausible reason we might not be able to create it?
</blockquote></details>

That's the only plausible reason I can think of.  I can think of some implausible ones, however.  :-)

I added a comment to make it more explicit.

---

*[src/LinuxBloomLauncher/BloomSplash.png, line  at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnBxWQm1WXNgyc_CS3S:-KnGwtCBtXwemmyu_JDD:b-divw2k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/448bdc73929bef33245c0fc58c91884e10724c61/src/LinuxBloomLauncher/BloomSplash.png#L)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

1)  Let's remove the copyright date, so that we don't have to update this once a year.
2) Expensive to have just one copy of this? 
</blockquote></details>

Done.  I've arranged to have one copy of BloomSplash.png (in the src folder) which is shared by the Windows and Linux code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-:-KnGvVta60-0Ylgln1Rc:b-47xzui)*

**Comment by JohnThomson** [comment]
:lgtm: with a couple of new minor questions/comments

---

Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/LinuxBloomLauncher/BloomLauncher.c, line 134 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnFar5pdO5N_34mYdmx:-KnKlX1R3O-xGaUCSdiz:b-8c0vdv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/448bdc73929bef33245c0fc58c91884e10724c61/src/LinuxBloomLauncher/BloomLauncher.c#L134)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

access() is a standard Linux system call that return 0 if the file exists, -1 if it doesn't.  I agree the return value seems backward, but a lot of Linux methods (and Linux programs) use 0 for success and something nonzero for an error.
</blockquote></details>

Thanks for helping my (and other Windows programmers') ignorance with the comment :-)

---

*[src/LinuxBloomLauncher/BloomLauncher.c, line 155 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnFbwUDcSOmVlB90SpA:-KnKm8DlQ1YZ9hziHyGV:b-9koi1n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/448bdc73929bef33245c0fc58c91884e10724c61/src/LinuxBloomLauncher/BloomLauncher.c#L155)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

mono IS the executing program from the point of view of the Linux kernel.  I think --debug is needed to get line numbers in stack traces.  But it also slows down execution (to an unknown, possibly trivial, extent), so maybe we shouldn't use it.  The current shell scripts all seem to have it.

I've commented the --debug line out with a comment in case we decide to reinstate it.  I also added a comment explaining that mono is the executing program, Bloom.exe is just data for it.  :-)
</blockquote></details>

Reinstating it is nontrivial, though, because it affects various counts and indexes for other arguments. If we keep the commented out line some warning might be appropriate.

---

*[src/LinuxBloomLauncher/BloomLauncher.c, line 154 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnKmT-Aon7Pmh74t5w_:-KnKmT-Aon7Pmh74t5wa:b-2m1hla) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/567a8c143f81c41f8bdff60eff55cdcede61e856/src/LinuxBloomLauncher/BloomLauncher.c#L154)):*
> ```C
> static gchar ** GetArgvForBloom(int argcOrig, char ** argvOrig)
> {
> 	gchar ** argvNew = g_new(gchar *, argcOrig + 2);	// 2 new args + terminating NULL
> ```

Two new args plus terminating null sounds to me like +3?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-:-KnKmsFJNvjOUTmC7KhH:bc74eno)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/LinuxBloomLauncher/BloomLauncher.c, line 155 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnFbwUDcSOmVlB90SpA:-KnKtsgDRLeo45dBoVYG:b-ay9frr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/448bdc73929bef33245c0fc58c91884e10724c61/src/LinuxBloomLauncher/BloomLauncher.c#L155)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Reinstating it is nontrivial, though, because it affects various counts and indexes for other arguments. If we keep the commented out line some warning might be appropriate.
</blockquote></details>

added comment to remind programmer what would need to be adjusted if we restore --debug

---

*[src/LinuxBloomLauncher/BloomLauncher.c, line 154 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-KnKmT-Aon7Pmh74t5w_:-KnKu-ZH9fxVYxLxzLKx:b-6mnqdc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/567a8c143f81c41f8bdff60eff55cdcede61e856/src/LinuxBloomLauncher/BloomLauncher.c#L154)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Two new args plus terminating null sounds to me like +3?
</blockquote></details>

oops.  forgot to adjust the comment.  fixed it now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 3 of 7 files at r1, 2 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1709#-:-KnLTdUEgBHb7Erz7HVk:bnfp4nl)*

**Pull request merged**
