### PR TITLE
When checked out book renamed, clean up on checkin (BL-9489)

### PR DESCRIPTION
**Pull request by JohnThomson**
When checked out book renamed, clean up on checkin (BL-9489)

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4232)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Is it intentional to have two different issue numbers? One in the commit summary and one in the description?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4232)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 732 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4232#-MUGFbcu8Rv8cyLazeSo:-MUGFbcu8Rv8cyLazeSp:b-l2hood) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c2852e37bbe29a2fc0c315da6e181888b5da03bc/src/BloomExe/TeamCollection/TeamCollection.cs#L732)):*
> ```
> BookHasBeenRenamed
> ```
I somewhat expect a method of this name to return a boolean.
How about `HandleBookRename` or `ProcessBookRename` or `OnBookRename` or similar?

**Review by JohnThomson — COMMENTED** [review]
Fixed. (An unintended result of a complicated rebase and squash)

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4232#-:-MUJF1ItDaUWT5IlPxdq:b-hhwssv)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 732 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4232#-MUGFbcu8Rv8cyLazeSo:-MUJF-xz4bdPzP10JjnK:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c2852e37bbe29a2fc0c315da6e181888b5da03bc/src/BloomExe/TeamCollection/TeamCollection.cs#L732)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> BookHasBeenRenamed
> ```
I somewhat expect a method of this name to return a boolean.
How about `HandleBookRename` or `ProcessBookRename` or `OnBookRename` or similar?
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4232)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
