### PR TITLE
BL-4749 remove any img that lacks a src

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1777)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/BookCompressor.cs, line 187 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1777#-Kqi-9BOifcDfP7jsOmm:-Kqi-9BOifcDfP7jsOmn:buw3ajq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/05db925d1890fb6ac77a8d4ba8eab46a4a5d05ef/src/BloomExe/Book/BookCompressor.cs#L187)):*
> That might be marginally more robust

I'm slightly concerned about whitespace differences which could cause the regex to miss. e.g. 
- &lt;/ img &gt;
- .../ &gt; &lt;/img&gt;

Could be unfounded as we have crafted the html by this point. But the prettify process could change at some point...
I'm definitely open to what you have. Thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1777)*

**Comment by JohnThomson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/BookCompressor.cs, line 187 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1777#-Kqi-9BOifcDfP7jsOmm:-KqiPjztaR2Rz9HjYjpG:bqd6i7o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/05db925d1890fb6ac77a8d4ba8eab46a4a5d05ef/src/BloomExe/Book/BookCompressor.cs#L187)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> That might be marginally more robust

I'm slightly concerned about whitespace differences which could cause the regex to miss. e.g. 
- &lt;/ img &gt;
- .../ &gt; &lt;/img&gt;

Could be unfounded as we have crafted the html by this point. But the prettify process could change at some point...
I'm definitely open to what you have. Thoughts?
</blockquote></details>

You motivated me to put in some more test cases and make the regex handle white space everywhere I think it is allowed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1777)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/BookCompressor.cs, line 191 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1777#-KqicdnPz6UnqWYdaeo9:-KqicdnPz6UnqWYdaeoA:b-ouwdo6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4651ea409c2223c54bbc1c9993894becf68561e9/src/BloomExe/Book/BookCompressor.cs#L191)):*
> ```Smalltalk
> 			// The javascript that hides the element if the file is not found doesn't work in the reader.
> 			var content = File.ReadAllText(bookFile, Encoding.UTF8);
> 			var regex = new Regex("]*src\\s*=\\s*(['\"])(.*?)\\1[^>]*(/>|>\\s*</img>)");
> ```

&gt; &lt;img[^&gt;]\*src\\\\s\*=\\\\s\*(['\\"])(.\*?)\\\\1[^&gt;]\*(/&gt;|&gt;\\\\s\*&lt;/img&gt;)

How about &lt;\\\\s\*img[^&gt;]\*src\\\\s\*=\\\\s\*(['\\"])(.\*?)\\\\1[^&gt;]\*(/\\\\s\*&gt;|&gt;\\\\s\*&lt;\\\\s\*/\\\\s\*img\\\\s\*&gt;)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1777)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/BookCompressor.cs, line 191 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1777#-KqicdnPz6UnqWYdaeo9:-KqjB_4bDV92auZoGgMK:bjdzmzv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4651ea409c2223c54bbc1c9993894becf68561e9/src/BloomExe/Book/BookCompressor.cs#L191)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

&gt; &lt;img[^&gt;]\*src\\\\s\*=\\\\s\*(['\\"])(.\*?)\\\\1[^&gt;]\*(/&gt;|&gt;\\\\s\*&lt;/img&gt;)

How about &lt;\\\\s\*img[^&gt;]\*src\\\\s\*=\\\\s\*(['\\"])(.\*?)\\\\1[^&gt;]\*(/\\\\s\*&gt;|&gt;\\\\s\*&lt;\\\\s\*/\\\\s\*img\\\\s\*&gt;)?
</blockquote></details>

According to https://stackoverflow.com/questions/3314535/white-space-inside-xml-html-tags, whitespace is not legal between open wedge and tag name, between / and closing wedge, or at the start of the closing tag. The last one is valid, though. I'll add it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1777)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1777#-:-Kqk1p3zKMubcbA1ccW6:bnfp4nl)*

**Pull request merged**
