### PR TITLE
Fix C# compiler warnings that are fairly trivial to fix

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4880)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
84 out of 173. Almost halfway. (The easy/simple half...)

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4880#-:-MqvUJGQ-p2trcpjVXRN:b9mmp1f)* status: 0 of 47 files reviewed, all discussions resolved

**Comment by andrew-polk** [comment]
___
*[src/BloomExe/Browser.cs, line 1061 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4880#-MqyaBGr4BZ6Dz_ZFmTA:-MqyaBGr4BZ6Dz_ZFmTB:bektp39) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9745147872e2ba12f7d618523eddbb09097180d0/src/BloomExe/Browser.cs#L1061)):*
> ```
> catch(Exception e)
> ```
I actually find it very annoying that these are treated as "unused" variables. They are very helpful when debugging to get at the actual exception.

I know you can disable the warning for all "unused" variables which we probably don't want to do. I wonder if there is any chance of being able to do so for just the exception ones.

Or maybe I just need to get better educated on how to see the exception in such a case when debugging?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4880)* status: 0 of 48 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomExe/Browser.cs, line 1061 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4880#-MqyaBGr4BZ6Dz_ZFmTA:-MqzkVHn4QOwZ4QDQk-Q:bf2ki2u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9745147872e2ba12f7d618523eddbb09097180d0/src/BloomExe/Browser.cs#L1061)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Thanks for pointing this out.

1) I researched the topic. Others had the same questions, but did not find any way to be able to disable the unused var warning only for exceptions. :(
2) I discovered that you can add a watch for "$exception", but... idk if I want to make those changes if it makes people's life more annoying. Of course, once you add it to the watch for that solution, it can stay there indefinitely...
3) You can put a pragma warning disable preprocessor directive before it, and a "[...] restore" directive after it, but that's more verbose than I like.
4) i could just back these out and live with the warning messages.

I'm not particularly happy with any of these options. I'm leaning towards (4) though.
</blockquote></details>

Let's run it by the team. Would we rather have the warning or is it ok to just learn to use $exception?

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4880)* status: 0 of 49 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Browser.cs, line 1061 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4880#-MqyaBGr4BZ6Dz_ZFmTA:-Mr9_e5-25PbrqUq2ECH:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9745147872e2ba12f7d618523eddbb09097180d0/src/BloomExe/Browser.cs#L1061)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's run it by the team. Would we rather have the warning or is it ok to just learn to use $exception?
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 23 of 48 files at r1, 26 of 26 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4880)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Pull request merged**
