### PR TITLE
Allow users to add/remove collections as sources of books (BL-12011)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5717)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5717)* status: all files reviewed, 6 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx` line 37 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5717#-NR56_AFCWPzwCPZTcqP:-NR56_AFCWPzwCPZTcqQ:b-55oqun) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54320cc359a6eff34625ea67ffdad998fcf77cff/src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx#L37)):*
> ```XML
> export const CollectionsTabPane: React.FunctionComponent<{}> = () => {
>     const collections = useApiJson("collections/list");
>     const [collectionCount, setCollectionCount] = useState(
> ```

Probably deserves a comment explaining its purpose (which if I understand is just to force a refresh?)
___
*[`src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx` line 632 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5717#-NR56Dmd3q5MRMOZ7E6X:-NR56Dmd3q5MRMOZ7E6Y:b-9gnx3v) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54320cc359a6eff34625ea67ffdad998fcf77cff/src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx#L632)):*
> ```XML
>     manager: BookSelectionManager;
>     isSpreadsheetFeatureActive: boolean;
>     removeSourceCollection: (id: string) => void;
> ```

I think it would be more idiomatic to call this something like `onRemoveSourceCollection` or `onClickRemove`.
___
*[`src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx` line 644 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5717#-NR55TBJ0cDPUQP9PM-K:-NR55TBJ0cDPUQP9PM-L:br2vhx1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54320cc359a6eff34625ea67ffdad998fcf77cff/src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx#L644)):*
> ```XML
>              * If it is, then we never want to delete it.  If it isn't, we want the UI/code to
>              *  allow for the collection to be deleted.
>              */}
> ```

I'm concerned about using this prop for making a decision as important as whether something can be deleted.
Can we just change the name to isFactoryCollection or similar?
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 169 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5717#-NR52iA80cMUVuPo8NEc:-NR52iA9-7VFjQBVqp2Y:b-gpo6df) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54320cc359a6eff34625ea67ffdad998fcf77cff/src/BloomExe/web/controllers/CollectionApi.cs#L169)):*
> ```Smalltalk
> 		private void HandleRemoveSourceCollection(ApiRequest request)
> 		{
> 			var id = request.RequiredPostString();
> ```

Is this `pathName`? Or maybe `collectionFolderPath`?



_Code quote:_
```Smalltalk
id
```
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 193 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5717#-NR54sDO7WtBC_ce7XTs:-NR54sDPCfsJ1jGtC0qe:b9yxmgq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54320cc359a6eff34625ea67ffdad998fcf77cff/src/BloomExe/web/controllers/CollectionApi.cs#L193)):*
> ```Smalltalk
> 			using (var dlg = new DialogAdapters.OpenFileDialogAdapter())
> 			{
> 				dlg.Title = "Choose Collection";
> ```

This needs l10n, right?



_Code quote:_
```Smalltalk
Choose Collection
```
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 219 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5717#-NR53EuF0Iu6Eqd6177U:-NR53EuGENrEs5ee8zGT:btbnzw4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54320cc359a6eff34625ea67ffdad998fcf77cff/src/BloomExe/web/controllers/CollectionApi.cs#L219)):*
> ```Smalltalk
> 			};
> 			_collectionModel.ReloadCollections();
> 			request.ReplyWithJson(JsonConvert.SerializeObject(output));
> ```

Unfortunately, I don't think we can delay the response until after the user selects the folder.
We'll need to respond immediately, then reply with the folder using a websocket event.
See CommonApi.HandleChooseFolder()

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5717)* status: all files reviewed, 6 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx` line 37 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5717#-NR56_AFCWPzwCPZTcqP:-NR58qyVA9B87JNbZL3w:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54320cc359a6eff34625ea67ffdad998fcf77cff/src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx#L37)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Probably deserves a comment explaining its purpose (which if I understand is just to force a refresh?)
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx` line 632 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5717#-NR56Dmd3q5MRMOZ7E6X:-NR5905837AEM_kTN3eL:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54320cc359a6eff34625ea67ffdad998fcf77cff/src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx#L632)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think it would be more idiomatic to call this something like `onRemoveSourceCollection` or `onClickRemove`.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx` line 644 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5717#-NR55TBJ0cDPUQP9PM-K:-NR59dud8cnAM5B2zhAB:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54320cc359a6eff34625ea67ffdad998fcf77cff/src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx#L644)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm concerned about using this prop for making a decision as important as whether something can be deleted.
Can we just change the name to isFactoryCollection or similar?
</blockquote></details>

Done.
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 169 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5717#-NR52iA80cMUVuPo8NEc:-NR5ANwT1I0GYMaJoOfn:b2e6p3s) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54320cc359a6eff34625ea67ffdad998fcf77cff/src/BloomExe/web/controllers/CollectionApi.cs#L169)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is this `pathName`? Or maybe `collectionFolderPath`?
</blockquote></details>

Done.  collectionFolderPath
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 193 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5717#-NR54sDO7WtBC_ce7XTs:-NR5C5jFBqfZZ4J0y8W0:b-4zc0h6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54320cc359a6eff34625ea67ffdad998fcf77cff/src/BloomExe/web/controllers/CollectionApi.cs#L193)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This needs l10n, right?
</blockquote></details>

Done.  I figured you would catch this.  (But you found other stuff as well.)
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 219 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5717#-NR53EuF0Iu6Eqd6177U:-NR8qEdHD5IWyq7X4d2P:bcuva9m) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54320cc359a6eff34625ea67ffdad998fcf77cff/src/BloomExe/web/controllers/CollectionApi.cs#L219)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Unfortunately, I don't think we can delay the response until after the user selects the folder.
We'll need to respond immediately, then reply with the folder using a websocket event.
See CommonApi.HandleChooseFolder()
</blockquote></details>

Done.  I've changed the code to return the new collection value by a websocket call.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5717)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx` line 644 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5717#-NR55TBJ0cDPUQP9PM-K:-NR8vEfL8xtwtd9hEhHh:b-9wq7p0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/54320cc359a6eff34625ea67ffdad998fcf77cff/src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx#L644)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks. 
Sorry, but I'd like to push it up one more level to the C# side. My concern is that we make a change there thinking we are only affecting localization but actually modifying this behavior.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5717)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
