### PR TITLE
Update csproj files to SDK format (BL-12611)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6051)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6051)* status: all files reviewed, 5 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/BloomExe.csproj` line 15 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6051#-Nb_LWVe06BaD3ssZuW-:-Nb_LWVe06BaD3ssZuW0:b-tton09) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/92ee707c5e765949fcbffeced2fb5fc4d231a4ba/src/BloomExe/BloomExe.csproj#L15)):*
> ```XML
>     <Version>5.6.000.0</Version>
>     <AssemblyVersion>5.6.000.0</AssemblyVersion>
>     <FileVersion>5.6.000.0</FileVersion>
> ```

Now that the copyright and version info stuff is here and in AssemblyInfo.cs, which is the source of truth?
Can/should we remove AssemblyInfo?
If this file is now the source of truth, we should update https://docs.google.com/document/d/1s1Sl8rj4lMwReJO-1JANPp8UyLaCTfFcMg6TKAigaYY/edit
___
*[`src/BloomExe/BloomExe.csproj` line 555 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6051#-Nb_N2LD1PdDbnUXZ40K:-Nb_N2LE1spj4zidYHms:bffdosg) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/92ee707c5e765949fcbffeced2fb5fc4d231a4ba/src/BloomExe/BloomExe.csproj#L555)):*
> ```XML
>     <Compile Remove="Book\PhashHelper.cs" />
>     <Compile Remove="ImageProcessing\LowResImageCache.cs" />
>     <Compile Remove="Platform\Platform.cs" />
> ```

Does this mean we don't use these files?
Seems like we should either delete them or let them be added to the project.
___
*[`src/BloomTests/BloomTests.csproj` line 147 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6051#-Nb_EW74EMO1DUEz6001:-Nb_EW74EMO1DUEz6002:b-qfy415) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/92ee707c5e765949fcbffeced2fb5fc4d231a4ba/src/BloomTests/BloomTests.csproj#L147)):*
> ```XML
>     <PackageReference Include="System.Security.Cryptography.Encoding" Version="4.3.0" />
>     <PackageReference Include="System.Security.Cryptography.Primitives" Version="4.3.0" />
>     <PackageReference Include="System.Security.Cryptography.X509Certificates" Version="4.3.0" />
> ```

I thought I had heard/read that with the new format, dependencies of dependencies don't need to be listed here.
Is that true?
If so, I think there are several packages, like the Cryptography stuff which we can further clean out. (same for BloomExe)
___
*[`src/BloomTests/ReflectionHelper/PrivateObject.cs` line 5 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6051#-Nb_CFTO4gnSEdXM3S2G:-Nb_CFTP-ogx8nIPDpkG:brxp46q) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/92ee707c5e765949fcbffeced2fb5fc4d231a4ba/src/BloomTests/ReflectionHelper/PrivateObject.cs#L5)):*
> ```Smalltalk
> using System.Reflection;
> 
> namespace BloomTests.ReflectionHelper
> ```

How do these ReflectionHelper classes overlap with or compliment the one in libpalaso?
If these are needed in addition to those, let's comment here about what gaps these fill in that aren't there.
(Or consider enhancing the libpalaso one to fill in the gaps instead.)
___
*[`src/WebView2PdfMaker/WebView2PdfMaker.csproj` line 13 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6051#-Nb_DHB2--vl9J8t6kgw:-Nb_DHB2--vl9J8t6kgx:bcvidqi) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/92ee707c5e765949fcbffeced2fb5fc4d231a4ba/src/WebView2PdfMaker/WebView2PdfMaker.csproj#L13)):*
> ```XML
>     <AssemblyTitle>WebView2PdfMaker</AssemblyTitle>
>     <Product>WebView2PdfMaker</Product>
>     <Copyright>Copyright © 2023</Copyright>
> ```

Might as well make this "© SIL International"?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6051)* status: all files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/BloomExe.csproj` line 555 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6051#-Nb_N2LD1PdDbnUXZ40K:-NbqBGc51wR6dzTg4Pl2:b-qmm5vu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/92ee707c5e765949fcbffeced2fb5fc4d231a4ba/src/BloomExe/BloomExe.csproj#L555)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Does this mean we don't use these files?
Seems like we should either delete them or let them be added to the project.
</blockquote></details>

Removed these presumably obsolete files.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6051)* status: all files reviewed, 4 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/BloomExe.csproj` line 45 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6051#-NbznsHTEDfHn9RyImoL:-NbznsHTEDfHn9RyImoM:bmfpmya) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d9a6a4070472e104cd7f9d303fb7ab8b1ad5bda6/src/BloomExe/BloomExe.csproj#L45)):*
> ```XML
>     <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
>       <_Parameter1>ClassLibrary1.Tests</_Parameter1>
>     </AssemblyAttribute>
> ```

    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>ClassLibrary1.Tests</_Parameter1>
    </AssemblyAttribute>

Was adding this one a mistake?
___
*[`src/BloomTests/ImageUpdaterTests.cs` line 1 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6051#-NbzpMUf9z9OJ3NodI3L:-NbzpMUf9z9OJ3NodI3M:b-myop6r) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/1f9405597fa7e4b8ffb16ff21265051c65d0ab20/src/BloomTests/ImageUpdaterTests.cs#L1)):*
> ```Smalltalk
> using System.Drawing;
> ```

Why is this file no longer wanted/needed?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6051)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/BloomExe.csproj` line 45 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6051#-NbznsHTEDfHn9RyImoL:-Nc-EsMABKqGSZFp56ge:b-komuhv) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d9a6a4070472e104cd7f9d303fb7ab8b1ad5bda6/src/BloomExe/BloomExe.csproj#L45)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>ClassLibrary1.Tests</_Parameter1>
    </AssemblyAttribute>

Was adding this one a mistake?
</blockquote></details>

Oops, I made one copy too many of the template I used for these elements and then forgot to delete it.
___
*[`src/BloomTests/ImageUpdaterTests.cs` line 1 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6051#-NbzpMUf9z9OJ3NodI3L:-Nc-FKU174kpzYmzdVTP:bjtnu1w) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/1f9405597fa7e4b8ffb16ff21265051c65d0ab20/src/BloomTests/ImageUpdaterTests.cs#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Why is this file no longer wanted/needed?
</blockquote></details>

This file was not being actively used.  It won't even compile.  Note the "using Palaso.*" statements -- those were replaced with "using SIL.*" some time ago.  The file dates back to 2015.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6051)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomExe/BloomExe.csproj` line 15 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6051#-Nb_LWVe06BaD3ssZuW-:-Nc-JUO63tKCBzPheVIQ:bbimo83) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/92ee707c5e765949fcbffeced2fb5fc4d231a4ba/src/BloomExe/BloomExe.csproj#L15)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I've been able delete the AssemblyInfo.cs files in the three projects.
</blockquote></details>

Thanks. Looks like you update the doc, too. Thanks.
___
*[`src/BloomTests/BloomTests.csproj` line 147 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6051#-Nb_EW74EMO1DUEz6001:-Nc-JScMDoQerR_Nx3XM:b-4t7wr8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/92ee707c5e765949fcbffeced2fb5fc4d231a4ba/src/BloomTests/BloomTests.csproj#L147)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I thought I had heard/read that with the new format, dependencies of dependencies don't need to be listed here.
Is that true?
If so, I think there are several packages, like the Cryptography stuff which we can further clean out. (same for BloomExe)
</blockquote></details>

Did you get a chance to look at this?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6051)* status: 24 of 28 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomTests/BloomTests.csproj` line 147 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6051#-Nb_EW74EMO1DUEz6001:-Nc3OKn49FeuVehLKJw8:b-qyd7bs) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/92ee707c5e765949fcbffeced2fb5fc4d231a4ba/src/BloomTests/BloomTests.csproj#L147)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Did you get a chance to look at this?
</blockquote></details>

I've now trimmed the PackageReference and Reference elements as much as I think I can get away with.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6051)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

___
*[`src/BloomTests/BloomTests.csproj` line 147 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6051#-Nb_EW74EMO1DUEz6001:-Nc4DSFM6jdtUsyeJ8wD:bb77rlh) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/92ee707c5e765949fcbffeced2fb5fc4d231a4ba/src/BloomTests/BloomTests.csproj#L147)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I've now trimmed the PackageReference and Reference elements as much as I think I can get away with.
</blockquote></details>

Yay!

**Pull request merged**
