### PR TITLE
BL-6137 Disable Import btn while recording

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2527)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 236 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2527#-LFrDJIS-TQv0eSl5Pax:-LFrDJIT1ozpfWQsiG_g:b2m6nh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/871a58a6d01e77fdc8dc7a9dadaa98a7cc28b5e8/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L236)):*
> ```XML
> 
>     private getImportButtonState(): string {
>         return (this.state.enabled && (this.state.haveRecording || this.recordingInProgress())) ?
> ```

Why can't we import a recording to replace one we already have? (i.e., why does haveRecording block import?)

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 240 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2527#-LFrDYqE5KDIO6_E2L6C:-LFrDYqE5KDIO6_E2L6D:b-xplmut) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/871a58a6d01e77fdc8dc7a9dadaa98a7cc28b5e8/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L240)):*
> ```XML
>     }
> 
>     private recordingInProgress(): boolean {
> ```

This name suggests to me something that we might call to check something external in order to SET the state. How about, inRecordingState? Not entirely happy with that...maybe you can do better.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2527)*

**Comment by gmartin7** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 236 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2527#-LFrDJIS-TQv0eSl5Pax:-LFrqnKCE6TUOABxDw9s:b-3op3u8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/871a58a6d01e77fdc8dc7a9dadaa98a7cc28b5e8/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L236)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Why can't we import a recording to replace one we already have? (i.e., why does haveRecording block import?)
</blockquote></details>

Not sure. I was just preserving previous function there. The Change Video on the actual video still is still functional (and with the same icon). Do we need to change this?

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 240 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2527#-LFrDYqE5KDIO6_E2L6C:-LFs5QRx395HrDBUECHz:b-6cejk5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/871a58a6d01e77fdc8dc7a9dadaa98a7cc28b5e8/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L240)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This name suggests to me something that we might call to check something external in order to SET the state. How about, inRecordingState? Not entirely happy with that...maybe you can do better.
</blockquote></details>

Yeah, I'm not coming up with anything better. It should be something like stateShowsRecordingInProgress or inNonWaitingState or inCountdownOrRecordingStates. Anything strike your fancy?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2527)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 236 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2527#-LFrDJIS-TQv0eSl5Pax:-LFsVfZ_3lDgf_7-cPk_:b-u1vzgw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/871a58a6d01e77fdc8dc7a9dadaa98a7cc28b5e8/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L236)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Not sure. I was just preserving previous function there. The Change Video on the actual video still is still functional (and with the same icon). Do we need to change this?
</blockquote></details>

Hmmm...I was just reading it as new code. Would you run this by JohnH and fix it accordingly?
Meanwhile, something has gone wrong with reversing the polarity of the old test. The button is always enabled if this.state.enabled is false, if I'm reading it right...try it on a page with no video element.

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 240 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2527#-LFrDYqE5KDIO6_E2L6C:-LFsWXU-EPBm4q18ZTtW:b-jm5q69) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/871a58a6d01e77fdc8dc7a9dadaa98a7cc28b5e8/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L240)):*
> stateShowsRecordingInProgress appeals to me more. If you're going to call it inNonWaitingState you may as well just inline the code (which I almost suggested, but didn't want to discourage your efforts to make it more readable).
If we renamed "waiting" to "idle", it would read pretty cleanly even without a method...(this.state.enabled && this.state.stateClass == "idle") ? "" : "disabled", that is, we have to be enabled and idle to start the import process (I'm assuming here that John doesn't want to forbid replacement imports).

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2527)*

**Comment by gmartin7** [comment]
Review status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @JohnThomson and @gmartin7)

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 236 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2527#-LFrDJIS-TQv0eSl5Pax:-LFsZEQ89gK6lO96tbkz:b3bb91y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/871a58a6d01e77fdc8dc7a9dadaa98a7cc28b5e8/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L236)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Hmmm...I was just reading it as new code. Would you run this by JohnH and fix it accordingly?
Meanwhile, something has gone wrong with reversing the polarity of the old test. The button is always enabled if this.state.enabled is false, if I'm reading it right...try it on a page with no video element.
</blockquote></details>

It might be... except the whole sign language tool is greyed out if there's no video element.
It's better now.

---

*[src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, line 240 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2527#-LFrDYqE5KDIO6_E2L6C:-LFsx0i151mgSM2Jq2Pj:b-99re7y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/871a58a6d01e77fdc8dc7a9dadaa98a7cc28b5e8/src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx#L240)):*
> (this.state.enabled && this.state.stateClass == "idle") ? "" : "disabled"
much better with 'idle', thx.
Also, the state.enabled check isn't necessary, since the top level of the control disables the whole panel if !state.enabled.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2527)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2527#-:-LFszySUEKwCdTYTD5Mr:bnfp4nl)*

**Pull request merged**
