### PR TITLE
BL-13357 fix error changing page size

### PR DESCRIPTION
**Pull request by nabalone**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6468)

### CODE REVIEW

**Comment by nabalone** [comment]
*[`src/BloomExe/Edit/EditingView.cs` line 391 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6468#-NwzvNZn4Oz2OPGTwNL1:-NwzvNZn4Oz2OPGTwNL2:b-jtjnga) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/87f24f6de85c0ad14940e3e6dc0d2727bdfd657d/src/BloomExe/Edit/EditingView.cs#L391)):*
> ```Smalltalk
>             //cancellation in case we switch documents.  Note we may also switch
>             //to some other way of making the thumbnails... e.g. it would be nice
>             //to have instant placeholders, with thumbnails later.
> ```

Do we want to preserve this comment? It is more than 9 years old

**Comment by nabalone** [comment]
*[`src/BloomExe/Edit/EditingView.cs` line 391 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6468#-NwzvNZn4Oz2OPGTwNL1:-Nwzvq8vEFLb_A69Lg87:bq697z2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/87f24f6de85c0ad14940e3e6dc0d2727bdfd657d/src/BloomExe/Edit/EditingView.cs#L391)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Do we want to preserve this comment? It is more than 9 years old
</blockquote></details>

I'm not sure what it means or refers to

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6468)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)

___
*[`src/BloomExe/Edit/EditingView.cs` line 391 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6468#-NwzvNZn4Oz2OPGTwNL1:-NxEFRaB3gM74-eGNKrv:b-jovit5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/87f24f6de85c0ad14940e3e6dc0d2727bdfd657d/src/BloomExe/Edit/EditingView.cs#L391)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

I'm not sure what it means or refers to
</blockquote></details>

No, it doesn't seem like it.
___
*[`src/BloomExe/Edit/EditingView.cs` line 415 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6468#-NxEFhsEBKQFYVEAXv0s:-NxEFhsEBKQFYVEAXv0t:bit1usk) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b30e42cd3225ac72766ca329735fa923f28b9d66/src/BloomExe/Edit/EditingView.cs#L415)):*
> ```Smalltalk
>                     _pageListView.Clear();
>                 }
>                 _model.OnBecomeVisible();
> ```

You've simplified things, and that's great!
But I've probably missed some discussions about this.
How/why does this solve the problem?
Do we need to be concerned about the fact that we're no longer waiting for idle to do this? (i.e. do we know why we thought it was important previously?

If these things have already been discussed, I'm happy for someone else with the context to just go ahead and approve without me.

**Comment by nabalone** [comment]
*[`src/BloomExe/Edit/EditingView.cs` line 415 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6468#-NxEFhsEBKQFYVEAXv0s:-NxrzqMK4AtjuAk5JJ1Q:ba53r68) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b30e42cd3225ac72766ca329735fa923f28b9d66/src/BloomExe/Edit/EditingView.cs#L415)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

You've simplified things, and that's great!
But I've probably missed some discussions about this.
How/why does this solve the problem?
Do we need to be concerned about the fact that we're no longer waiting for idle to do this? (i.e. do we know why we thought it was important previously?

If these things have already been discussed, I'm happy for someone else with the context to just go ahead and approve without me.
</blockquote></details>

@JohnThomson do you remember what we said about waiting for idle?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6468)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/Edit/EditingView.cs` line 415 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6468#-NxEFhsEBKQFYVEAXv0s:-NyVTAwu4SFWuuYtYrsp:b4lv5lr) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b30e42cd3225ac72766ca329735fa923f28b9d66/src/BloomExe/Edit/EditingView.cs#L415)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

@JohnThomson do you remember what we said about waiting for idle?
</blockquote></details>

I don't remember the details, sorry. What I do remember:
- postponing it was causing the problem...something like, one of the things the postponed method does is to build the new page list, and something else was trying to use it before it was rebuilt. I don't remember what changed between 5.6 and 6.0 to make this a problem.
- This method has been gradually losing functionality, mostly moving to EnsureUpToDate. It's a long term goal to get rid of it, so we don't have to wonder what should be there and what should be in EnsureUpToDate.
- We could not find any reason it needed to be postponed, or even any reason it might be desirable. On the contrary, if the edit view is visible, I can hardly imagine anything more urgent than getting the edited book ready to display.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6468)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nabalone)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6468)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nabalone)

**Pull request merged**
