### PR TITLE
Handle if overlay contains a non-overlay-image bubble

### PR DESCRIPTION
**Pull request by sujeffreyl**
I don't think it actually causes any errors at this current commit (because Jquery), but if you were to start doing vanilla JS assuming that containerDiv is not undefined as the types state, you'd be sorry :(

- - -
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5493)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5493)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 1149 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5493#-NFFKsWFA7T4YDD-cJCC:-NFFKsWFA7T4YDD-cJCD:bhgyspo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/67178be4ca7b4476de013288762953fc4ff91f2e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L1149)):*
> ```XML
>             this.cleanupMouseMoveHover(container);
>             if (this.activeElement) {
>                 tryRemoveImageEditingButtons(
> ```

If the active element is a speech bubble, this throws exceptions into my log and makes it more difficult to debug my actual changes (for a different PR).

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5493)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 1149 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5493#-NFFKsWFA7T4YDD-cJCC:-NFFL4T919vvMF4AyEZN:b-plrg6t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/67178be4ca7b4476de013288762953fc4ff91f2e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L1149)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

If the active element is a speech bubble, this throws exceptions into my log and makes it more difficult to debug my actual changes (for a different PR).
</blockquote></details>

(because the speech bubble doesn't have any imageContainer inside of it)

**Comment by andrew-polk** [comment]
Should target Version5.4

**Comment by sujeffreyl** [comment]
Changing the target brought in a lot of commits. Will close and create a new one.

**Review by andrew-polk — APPROVED** [review]

**Pull request closed without merging**
