### PR TITLE
Fix up video overlay control bar and menu (BL-13930)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6678)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6678)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`DistFiles/localization/en/Bloom.xlf` line 2133 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6678#-O7jR1z-6wmOKdMhShZ2:-O7jR1z-6wmOKdMhShZ3:bbfjxic) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/7048b6bd900f3e16ad68180d313e73ef8f1b5155/DistFiles/localization/en/Bloom.xlf#L2133)):*
> ```XML
>       </trans-unit>
>       <trans-unit id="EditTab.Toolbox.ComicTool.Options.ChooseVideo" sil:dynamic="true" translate="yes">
>         <source xml:lang="en">Choose Video from your computer...</source>
> ```

The mockup has "Computer" capitalized.
Then feel free to merge.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6678)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6678)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6678)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/Bloom.xlf` line 2133 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6678#-O7jR1z-6wmOKdMhShZ2:-O7kORPp2TYNYbwfHJQe:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/7048b6bd900f3e16ad68180d313e73ef8f1b5155/DistFiles/localization/en/Bloom.xlf#L2133)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The mockup has "Computer" capitalized.
Then feel free to merge.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6678)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
