### PR TITLE
BL-6392 don't delete 'extra' pages when localizing shells

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2732)

### CODE REVIEW

**Review by andrew-polk — APPROVED** [review]
:lgtm: 
@hatton, do we want this in 4.3?

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2732#-:-LM3QqcB-pyHLAxLB2gv:b-wbiiu7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2732)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomTests/Book/BookStarterTests.cs, line 833 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2732#-LM3WgI4DJKdSWhdnSTZ:-LM3WgI4DJKdSWhdnST_:b-7irr93) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5182aa985293c1d1d04024cd4f9b3bf43c950f62/src/BloomTests/Book/BookStarterTests.cs#L833)):*
> ```Smalltalk
> 			if (includeJson)
> 			{
> 				var json = "{'bookLineage':'first,second','bookInstanceId':'thisNewGuy','title':'Test Shell', 'suitableForMakingShells':" +
> ```

Is this addition of adding this directly related to this issue?

**Review by hatton — COMMENTED** [review]
yes

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2732#-:-LM3WrI58G9RcKy2bU0P:b2nign6)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2732)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomTests/Book/BookStarterTests.cs, line 833 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2732#-LM3WgI4DJKdSWhdnSTZ:-LM3gQdJD6RW_moWBcs4:b-v1s5on) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5182aa985293c1d1d04024cd4f9b3bf43c950f62/src/BloomTests/Book/BookStarterTests.cs#L833)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is this addition of adding this directly related to this issue?
</blockquote></details>

Making sure you saw this is while generating a test book.
I think it is required to be able to test the difference between how extra pages are handled in a template vs. shell.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2732)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomTests/Book/BookStarterTests.cs, line 833 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2732#-LM3WgI4DJKdSWhdnSTZ:-LM3htKO398kI7vYXmGP:b-i3xvab) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5182aa985293c1d1d04024cd4f9b3bf43c950f62/src/BloomTests/Book/BookStarterTests.cs#L833)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Making sure you saw this is while generating a test book.
I think it is required to be able to test the difference between how extra pages are handled in a template vs. shell.
</blockquote></details>

Yes, it enables repairing the old test case CreateBookOnDiskFromTemplate_PagesLabeledExtraAreNotAdded and adding the new one CreateBookOnDiskFromShell_PagesLabeledExtraAreAdded (which differ by whether the source is a template or a shell)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2732)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Pull request merged**
