### PR TITLE
Add more history events (BL-10550)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4827)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4827)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomBrowserUI/teamCollection/CollectionHistoryTable.tsx, line 24 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4827#-MnmIJQu3ZISn7ptAj3d:-MnmIJQu3ZISn7ptAj3e:blknj64) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c18fa0e25130287dc04e1140e75fa5396cbcf3e/src/BloomBrowserUI/teamCollection/CollectionHistoryTable.tsx#L24)):*
> ```XML
> }
> 
> const kEventTypes = ["Check In", "Created", "Renamed", "Uploaded", "Deleted"]; // REVIEW maybe better to do this in c# and just send it over?
> ```

Should we be adding the Deleted event type if we aren't using it?
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1390 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4827#-MnmI6kfD5Q7auJP2M81:-MnmI6kg5SXcUdpnEcL_:bqq39xq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c18fa0e25130287dc04e1140e75fa5396cbcf3e/src/BloomExe/TeamCollection/TeamCollection.cs#L1390)):*
> ```Smalltalk
> 			AddIfExists(paths, Path.Combine(folderPath, "log.txt"));
> 			AddIfExists(paths, Path.Combine(folderPath, "impersonate.txt"));
> 			AddIfExists(paths, Path.Combine(folderPath, "history.db"));
> ```

Does this represent a bug we should think about fixing in 5.1?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4827)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomBrowserUI/teamCollection/CollectionHistoryTable.tsx, line 24 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4827#-MnmIJQu3ZISn7ptAj3d:-Mo-vmJx6NpjJH7mF67t:b63rnzf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/608dc454b7076e23443d9315c1f6409f9f185a26/src/BloomBrowserUI/teamCollection/CollectionHistoryTable.tsx#L24)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should we be adding the Deleted event type if we aren't using it?
</blockquote></details>

Future proofing?  But it wouldn't be that hard to find the spot to add it in if/when we get collection level history.  Removed Deleted from the list.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1390 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4827#-MnmI6kfD5Q7auJP2M81:-Mo-uw_34FKiNdsuVYnh:bp0ebtt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/608dc454b7076e23443d9315c1f6409f9f185a26/src/BloomExe/TeamCollection/TeamCollection.cs#L1390)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Does this represent a bug we should think about fixing in 5.1?
</blockquote></details>

It's either a bug we should think about fixing in 5.1, or it's a misunderstanding on my part and it shouldn't be in 5.2 (this PR).  My understanding is that history.db is part of the book from the viewpoint of Team Collections, but not when uploaded or otherwise published.  Since @hatton  indicated that the history items should be added even when not in a Team Collection, my understanding may well be wrong.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4827)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[src/BloomBrowserUI/teamCollection/CollectionHistoryTable.tsx, line 24 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4827#-MnmIJQu3ZISn7ptAj3d:-Mo4i0Zp3TVjCpDPAhZb:b-p0z66u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/608dc454b7076e23443d9315c1f6409f9f185a26/src/BloomBrowserUI/teamCollection/CollectionHistoryTable.tsx#L24)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Future proofing?  But it wouldn't be that hard to find the spot to add it in if/when we get collection level history.  Removed Deleted from the list.
</blockquote></details>

I'm not seeing this change.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1390 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4827#-MnmI6kfD5Q7auJP2M81:-Mo4i2KnBcx886VGK_5u:b-d2s6ry) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/608dc454b7076e23443d9315c1f6409f9f185a26/src/BloomExe/TeamCollection/TeamCollection.cs#L1390)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

It's either a bug we should think about fixing in 5.1, or it's a misunderstanding on my part and it shouldn't be in 5.2 (this PR).  My understanding is that history.db is part of the book from the viewpoint of Team Collections, but not when uploaded or otherwise published.  Since @hatton  indicated that the history items should be added even when not in a Team Collection, my understanding may well be wrong.
</blockquote></details>

As far as I can tell, this is a bug in 5.1. I create a book, check it in, duplicate it. Now I have duplicate history events in the history view.

However, I think it also isn't a `TCSpecificFile` as you indicated. So it probably needs to get filtered out of duplicate creation and publications a different way.

I've created https://issues.bloomlibrary.org/youtrack/issue/BL-10646. So I think we need to remove it from here. Does that mean this change will need to wait on the other fix?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4827)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomBrowserUI/teamCollection/CollectionHistoryTable.tsx, line 24 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4827#-MnmIJQu3ZISn7ptAj3d:-Mo9Lw_98a-IxV2j7a8I:bd4t48a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/608dc454b7076e23443d9315c1f6409f9f185a26/src/BloomBrowserUI/teamCollection/CollectionHistoryTable.tsx#L24)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not seeing this change.
</blockquote></details>

Oops.  I forgot to push.  It should be there now.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4827)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @hatton)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4827)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @hatton)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1390 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4827#-MnmI6kfD5Q7auJP2M81:-Mo9ZDbW8_dyjtsZPTgj:bp1r29h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/608dc454b7076e23443d9315c1f6409f9f185a26/src/BloomExe/TeamCollection/TeamCollection.cs#L1390)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

As far as I can tell, this is a bug in 5.1. I create a book, check it in, duplicate it. Now I have duplicate history events in the history view.

However, I think it also isn't a `TCSpecificFile` as you indicated. So it probably needs to get filtered out of duplicate creation and publications a different way.

I've created https://issues.bloomlibrary.org/youtrack/issue/BL-10646. So I think we need to remove it from here. Does that mean this change will need to wait on the other fix?
</blockquote></details>

No, I just noticed this as a problem and added this fix for free.  :-)
I've removed this line of code here.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4827)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4827)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
