### PR TITLE
Add ProcessExtra.SafeStartInFront() to foreground new programs (BL-12432)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5979)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5979)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/ToPalaso/ProcessExtra.cs` line 37 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5979#-N_6ME_PAqal9stJQfju:-N_6ME_PAqal9stJQfjv:bcjx6ak) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/21dee97c3bd011cbc4ab6c6495b3f368633c0781/src/BloomExe/ToPalaso/ProcessExtra.cs#L37)):*
> ```Smalltalk
> 
> 			if (!String.IsNullOrEmpty(libpath))
> 				Environment.SetEnvironmentVariable("LD_LIBRARY_PATH", libpath);
> ```

Is this LD_LIBRARY_PATH stuff needed for Linux?
Should it be gated?
Let's comment it, please.
(here and in the next method)
___
*[`src/BloomExe/ToPalaso/ProcessExtra.cs` line 81 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5979#-N_6MjY41CLiY5FLxZvz:-N_6MjY50V_LKxnO8Nwn:bk412w6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/21dee97c3bd011cbc4ab6c6495b3f368633c0781/src/BloomExe/ToPalaso/ProcessExtra.cs#L81)):*
> ```Smalltalk
> 
> 			int count = 0;
> 			var timer = new System.Timers.Timer(1000);
> ```

One second seems like a long time to wait if you just clicked something which you expect to open immediately.
(Or am I missing where it runs immediately the first time?)
___
*[`src/BloomExe/ToPalaso/ProcessExtra.cs` line 105 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5979#-N_6NMjoAxdd9OWyhyQD:-N_6NMjoAxdd9OWyhyQE:b-r2dq4s) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/21dee97c3bd011cbc4ab6c6495b3f368633c0781/src/BloomExe/ToPalaso/ProcessExtra.cs#L105)):*
> ```Smalltalk
> 					{
> 						Debug.WriteLine($"DEBUG BringDesiredWindowToFront(\"{windowTitleToMatch}\",oldProcesses) matched {windows.Count} window(s) in {count + 1} second(s)");
> 						SetForegroundWindow(windows[0]);
> ```

I guess there is nothing to tell us which window opened most recently?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5979)* status: 24 of 27 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/ToPalaso/ProcessExtra.cs` line 37 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5979#-N_6ME_PAqal9stJQfju:-N_BJixBAC-_e6CrcLIX:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/21dee97c3bd011cbc4ab6c6495b3f368633c0781/src/BloomExe/ToPalaso/ProcessExtra.cs#L37)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is this LD_LIBRARY_PATH stuff needed for Linux?
Should it be gated?
Let's comment it, please.
(here and in the next method)
</blockquote></details>

Done.
___
*[`src/BloomExe/ToPalaso/ProcessExtra.cs` line 81 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5979#-N_6MjY41CLiY5FLxZvz:-N_BKYMV3lNGbZ_kR1iK:bp4thnc) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/21dee97c3bd011cbc4ab6c6495b3f368633c0781/src/BloomExe/ToPalaso/ProcessExtra.cs#L81)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

One second seems like a long time to wait if you just clicked something which you expect to open immediately.
(Or am I missing where it runs immediately the first time?)
</blockquote></details>

I changed to wait 0.1 seconds the first time and 1.0 seconds from there on out to 10.1 seconds before giving up.
___
*[`src/BloomExe/ToPalaso/ProcessExtra.cs` line 105 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5979#-N_6NMjoAxdd9OWyhyQD:-N_BJlJc6jWFGDYtzMY2:b29hvq1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/21dee97c3bd011cbc4ab6c6495b3f368633c0781/src/BloomExe/ToPalaso/ProcessExtra.cs#L105)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I guess there is nothing to tell us which window opened most recently?
</blockquote></details>

Nothing I know of.  These are all Win32 API calls, a subject that I don't know much about.  This is all based on sample code I found on stackoverflow.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5979)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5979)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
