### PR TITLE
BL-11539 AddPage dialog tweaks

### PR DESCRIPTION
**Pull request by gmartin7**
* use the MUI default icon color for the close icon
* enable initial Esc by switching focus to edit browser
   from page list browser just before bringing up the dialog

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5641)

### CODE REVIEW

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5641)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5641)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomExe/Edit/PageControlsApi.cs` line 131 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5641#-NOPvoCP6skal7Q9L2tJ:-NOPvoCP6skal7Q9L2tK:b-ie44co) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/82aef58ac7baf353851607d8fcec654c9a689466/src/BloomExe/Edit/PageControlsApi.cs#L131)):*
> ```Smalltalk
> 			if (_editingModel.CanAddPages)
> 			{
> 				_editingModel.GetEditingBrowser().Focus();
> ```

How about a brief comment here and in the other location indicating why we do this?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5641)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/Edit/PageControlsApi.cs` line 131 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5641#-NOPvoCP6skal7Q9L2tJ:-NOQ2U7ZElTfAjSRJyPH:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/82aef58ac7baf353851607d8fcec654c9a689466/src/BloomExe/Edit/PageControlsApi.cs#L131)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

How about a brief comment here and in the other location indicating why we do this?
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5641)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
