### PR TITLE
Fix "Choose Different Layout" to not disable Pages pane (BL-4071)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1388)

### CODE REVIEW

**Comment by hatton** [comment]
Steve, why is the program in the wrong modal state at this point?

**Comment by StephenMcConnel** [comment]
I've updated the comment on the one line of code to tell everything I know.  Essentially, the typescript code is not resetting the modal state to the correct value even though the code is there to do it.  I have no idea why that is happening.  I've traced the javascript  execution (via alerts) to the point of it calling document.dispatchEvent().  Somewhere between there and the event handler in our C# code, the event is being lost.  It may be due to something in the changes being made to the document, or a bug in geckofx45.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1388#-:-KZOMqJCZoYKvnHglto4:bfxt8k)*

**Comment by hatton** [comment]
Ok, so there may be something in there that we need to figure out/learn. Maybe we could get a pair together...

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1388#-:-KZPF4wshiWm6xxGN2ax:b-s6xstz)*

**Comment by StephenMcConnel** [comment]
I had an idea of something to try in the javascript, but it didn't work.  So this C# fix is the only fix I've come up with for this bug.

**Comment by StephenMcConnel** [comment]
The fireCSharpEvent method calls document.dispatchEvent.  For the working events, the document.baseURI points to the current page, with a guid based name.  For the event that disappears (leading to this bug), the document.baseURI points to "page-chooser-main.html".  This is what I suspected last night, but my attempted fix didn't work.  I'm not sure what to try to fix this.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1388#-:-KZT51PzcmD1JLu69z_Y:b-2z17qz)*

**Comment by StephenMcConnel** [comment]
Since the "page-chooser-main.html" document is launched from typescript/javascript, there's no way for the C# to hook into it.  At this point, the only solution I see is the C# one already proposed here.  It might be good to comment out the nonfunctional fireCSharpEvent call with commentary explaining why it will never work.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1388#-:-KZTZTUzuzS198koj7TW:bxin1rb)*

**Comment by andrew-polk** [comment]
@StephenMcConnel, please rebase on Version3.8.
@hatton, I'm leaving this for your review since you began it. Otherwise, let me know.

**Comment by andrew-polk** [comment]
Decided to go with a different approach: https://github.com/BloomBooks/BloomDesktop/pull/1425

**Pull request closed without merging**
