### PR TITLE
[5.4] BL-12506 Improve "Controlled Folder Access" error UI

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5998)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5998)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs` line 79 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5998#-N_GH0472Vw5_bzrqC-H:-N_GH0472Vw5_bzrqC-I:b-wqk6a) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d3867899bd63924d5eed62df853758a08b1edcce/src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs#L79)):*
> ```Smalltalk
> 				"This might be caused by Windows Defender \"Controlled Folder Access\" or some other virus protection.");
> 			var msg = string.Format(heading, failingFolder) + Environment.NewLine + Environment.NewLine + mainMsg;
> 			var caption = LocalizationManager.GetString("BloomIntegrity.WindowTitle", "Bloom Problem");
> ```

This ID is *semantically* wrong, even if it happens to have the string you're looking for. This is not about Bloom Integrity.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5998)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[`DistFiles/localization/en/Bloom.xlf` line 121 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5998#-N_KFQIK-ziWdifHPQdR:-N_KFQIK-ziWdifHPQdS:bv42yvr) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/211cf7d02b3824420d974b1840fe86f01453bd16/DistFiles/localization/en/Bloom.xlf#L121)):*
> ```XML
>         <source xml:lang="en">Bloom Problem</source>
>         <note>ID: BloomIntegrity.WindowTitle</note>
>         <note>Obsolete as of Bloom 5.4 (replaced by Common.ProblemTitle)</note>
> ```

I don't think there is any value to marking it obsolete AND replacing it in the code.
The reason to keep it in the .xlf file for a version or two is just to ensure that existing translations show up in Bloom.
But if you've changed the ID in the code, then having it in the .xlf file won't do anything.

So it's fine to change it in code and deal with the translations in Crowdin.
But then I think we should go ahead and remove the old one from the .xlf file.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5998)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`DistFiles/localization/en/Bloom.xlf` line 121 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5998#-N_KFQIK-ziWdifHPQdR:-N_KPlrsCKN0Ka4V79Gk:bksfnb) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/211cf7d02b3824420d974b1840fe86f01453bd16/DistFiles/localization/en/Bloom.xlf#L121)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't think there is any value to marking it obsolete AND replacing it in the code.
The reason to keep it in the .xlf file for a version or two is just to ensure that existing translations show up in Bloom.
But if you've changed the ID in the code, then having it in the .xlf file won't do anything.

So it's fine to change it in code and deal with the translations in Crowdin.
But then I think we should go ahead and remove the old one from the .xlf file.
</blockquote></details>

OK. Per our discussion, I've left this in and reverted the Integrity dialog change.
___
*[`src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs` line 79 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5998#-N_GH0472Vw5_bzrqC-H:-N_KJNqq8DbB5qfUG_qV:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d3867899bd63924d5eed62df853758a08b1edcce/src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs#L79)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This ID is *semantically* wrong, even if it happens to have the string you're looking for. This is not about Bloom Integrity. 
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> Dismissed @hatton from a discussion.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5998)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
