### PR TITLE
BL-4247 Allow user to configure extra end-of-sentence characters

### PR DESCRIPTION
**Pull request by JohnThomson**
(Also fixes most of BL-4241, layout problems in some localizations.)

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1466)

### CODE REVIEW

**Comment by StephenMcConnel** [comment]
:lgtm: although I'm not as confident of my TypeScript/Pug reviewing skills as I could be.  :-)

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.io.ts, line 129 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1466#-Kc57n-LxjNanOMgCXGX:-Kc57n-LxjNanOMgCXGY:b83fa7j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2492195173a3d1a51a6c675c3639deb3cccb321e/src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.io.ts#L129)):*
> ```XML
>   settings.letters = cleanSpaceDelimitedList((<HTMLInputElement>document.getElementById('dls_letters')).value);
>   settings.sentencePunct = (<HTMLInputElement>document.getElementById('dls_sentence_punct')).value.trim();
> ```

I suppose trim() is okay because the user has been directed to enter <space> as "\u0020" instead of as " ".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1466#-:-Kc59-zjrjDLtBFbOq2f:bt25ox7)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/bloomSynphonyExtensions.js, line 92 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1466#-Kc5KjMfdzLSPmvo775F:-Kc5KjMfdzLSPmvo775G:b-ulllsa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2492195173a3d1a51a6c675c3639deb3cccb321e/src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/bloomSynphonyExtensions.js#L92)):*
> ```JavaScript
>       .replace('*', '\\u002A').replace('~', '\\u007E').replace('[', '\\u005B').replace(']', '\\u005D')
>       .replace('<', '\\u003C').replace('>', '\\u003E');
>     LibSynphony.prototype.extraSentencePunct = extraRe;
> ```

Is '?' needed?   '+' is also missing, though a lot less likely to b typed in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1466)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/bloomSynphonyExtensions.js, line 92 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1466#-Kc5KjMfdzLSPmvo775F:-KcItNf85mmsnJMc7eBq:bh9vsr1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2492195173a3d1a51a6c675c3639deb3cccb321e/src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/bloomSynphonyExtensions.js#L92)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is '?' needed?   '+' is also missing, though a lot less likely to b typed in.
</blockquote></details>

I tested both. Not sure why they were not on the list I found of characters that might need escaping, but in this case I think they really don't, probably because it is in the context of a [] list.

---

*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.io.ts, line 129 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1466#-Kc57n-LxjNanOMgCXGX:-KcIu8diXFYH7zNFE43L:bflnaon) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2492195173a3d1a51a6c675c3639deb3cccb321e/src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.io.ts#L129)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I suppose trim() is okay because the user has been directed to enter <space> as "\u0020" instead of as " ".
</blockquote></details>

Right, and without that rule, it would be much too easy to make space sentence-terminating by mistake with unexpected consequences that would be hard to figure out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1466)*

**Comment by hatton** [comment]
Just waiting for the right time to merge this.

**Pull request merged**
