### PR TITLE
TalkingBook: Import Recording unit tests (BL-9066)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3942)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3942)* status: 0 of 3 files reviewed, 2 unresolved discussions

___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 3962 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3942#-MHwkwHL2wLVQj5rUv7u:-MHwkwHL2wLVQj5rUv7v:b-qsp33y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/53efd9aa8626bc5dd19c249df772a4267c6240b0/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L3962)):*
> ```XML
>     }
> 
>     public async importRecordingAsync(): Promise<void> {
> ```

Needed to be async-ified for the unit test to know when it was OK to start running the asserts.
___
*[src/BloomBrowserUI/utils/bloomApi.ts, line 336 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3942#-MHwlNBM3ldkKRLebBxO:-MHwlNBM3ldkKRLebBxP:bsy47bq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/53efd9aa8626bc5dd19c249df772a4267c6240b0/src/BloomBrowserUI/utils/bloomApi.ts#L336)):*
> ```XML
>                         ? successCallback
>                         : r => {
>                               return r; // Need to return the response (instead of having an empty body) so that the returned promise contains the AxiosResponse
> ```

Alternatively, I can make promise-only (no callback support) versions of these functions... but i think this works for both cases.

I did check that no existing callers looked at the return value of postDataWithjson, postData, and postDataWithConfig at least.
And if people were passing undefined for the callbacks, I don't think they should care about whether the callback returns Promise<void> vs. Promise<AxiosResposne>.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3942)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts, line 2187 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3942#-MIJyLcwBeFVh23aD-3Q:-MIJyLcxBXZb0G7mugG4:b-192zns) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/53efd9aa8626bc5dd19c249df772a4267c6240b0/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts#L2187)):*
> ```XML
>             const audioFilename = "2+2=4_audio.mp3";
>             const audioToCopyFilePath = `math+me_audio/${audioFilename}`;
>             const bookPath = `C:/John&JaneDoeCollection/math+me`;
> ```

I don't understand why we need to handle special characters. Is there some new scenario where we don't control the audio file names?
But, if we do, let's make it a serious torture test, with the really dangerous characters like space, percent, single quote, (you have) ampersand, both angle brackets, period, comma, question mark.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3942)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts, line 2187 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3942#-MIJyLcwBeFVh23aD-3Q:-MIJzA23Cc-lx663Pz-Q:b-3z2cj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/53efd9aa8626bc5dd19c249df772a4267c6240b0/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts#L2187)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't understand why we need to handle special characters. Is there some new scenario where we don't control the audio file names?
But, if we do, let's make it a serious torture test, with the really dangerous characters like space, percent, single quote, (you have) ampersand, both angle brackets, period, comma, question mark.
</blockquote></details>

The other issue here is that I'm not convinced a mock test is adequate, though I'm not clear how you can improve it. But what we need to test is the round trip: from whatever came up with the file name containing special characters, to what we store in the id (what do we need to do about making THAT a legal attribute value and legal ID, if the user can pick a file name??), through the API, to where C# needs to copy...and elsewhere, to check the existence of, and play, and record...the consistently correct file. If we can't do better, we should at least have paired unit tests that check what JS converts a really nasty file name to, with comments linking it to a C# one that takes that same value as input and comes up with the right file path.
And don't forget to check that epub generation will handle special characters in audio file names that may be illegal in epubs or cause unexpected problems for readers...and that BloomPlayer will properly cooperate over them with Bloom Reader and the Harvester and S3...

**Comment by sujeffreyl** [comment]
___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts, line 2187 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3942#-MIJyLcwBeFVh23aD-3Q:-MIK6pN8DSmLaU98UgAh:b7fnc7n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/53efd9aa8626bc5dd19c249df772a4267c6240b0/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts#L2187)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

The other issue here is that I'm not convinced a mock test is adequate, though I'm not clear how you can improve it. But what we need to test is the round trip: from whatever came up with the file name containing special characters, to what we store in the id (what do we need to do about making THAT a legal attribute value and legal ID, if the user can pick a file name??), through the API, to where C# needs to copy...and elsewhere, to check the existence of, and play, and record...the consistently correct file. If we can't do better, we should at least have paired unit tests that check what JS converts a really nasty file name to, with comments linking it to a C# one that takes that same value as input and comes up with the right file path.
And don't forget to check that epub generation will handle special characters in audio file names that may be illegal in epubs or cause unexpected problems for readers...and that BloomPlayer will properly cooperate over them with Bloom Reader and the Harvester and S3...
</blockquote></details>

We need to handle special chars because we put the filename into an HTTP request, so we need to make sure we encode it properly (if applicable).

This is from import recording, so 1) we don't control the filename of the file that gets imported from.
2) We also don't control the book title (which is in the destination), the user can type lots of strange things there.
The filename (excluding the directory) of the destination file is still a GUID w/no special chars, same as before, so once import recording succeeds we'll be back to normal.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3942)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts, line 2187 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3942#-MIJyLcwBeFVh23aD-3Q:-MIKSo5I-IbHmpGH-Bjr:b-jx97sh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/53efd9aa8626bc5dd19c249df772a4267c6240b0/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts#L2187)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

We need to handle special chars because we put the filename into an HTTP request, so we need to make sure we encode it properly (if applicable).

This is from import recording, so 1) we don't control the filename of the file that gets imported from.
2) We also don't control the book title (which is in the destination), the user can type lots of strange things there.
The filename (excluding the directory) of the destination file is still a GUID w/no special chars, same as before, so once import recording succeeds we'll be back to normal.
</blockquote></details>

Re: Round trip test.
1) From a unit test perspective, that is very much testing 2 very separate components. And IMO, I consider the bug that the JS generates a bad request.  My test checks that it generates a well-formed request. I think that's sufficient.
2) I guess what you suggest is an integration test, but it sounds too challenging for me to setup right now.

A paired C# one is OK though, i guess.

RE: Epub generation
I think this isn't applicable since the destination filename once import recording completes will be normal.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3942)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts, line 2187 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3942#-MIJyLcwBeFVh23aD-3Q:-MILkjrA8a99lDbqcbyl:b-t7tuuk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/53efd9aa8626bc5dd19c249df772a4267c6240b0/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts#L2187)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

All sounds good. So, I'm just hoping for a nastier test case in JS and a matching one in C#. I agree the full integration test is not reasonably doable.
</blockquote></details>

I made the tests more thorough in terms of checking punctuation, but also horribly convoluted to debug.  Also, the test code gets a lot more complex from scaling up to handle all punctuation than for verifying a single one.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3942)* status: all files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts, line 2187 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3942#-MIJyLcwBeFVh23aD-3Q:-MILv7YbEs5Uts91lv_t:buq4zdy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/53efd9aa8626bc5dd19c249df772a4267c6240b0/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts#L2187)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I made the tests more thorough in terms of checking punctuation, but also horribly convoluted to debug.  Also, the test code gets a lot more complex from scaling up to handle all punctuation than for verifying a single one.
</blockquote></details>

Sorry it was such a pain. Hopefully it will prove worth it.

**Review by JohnThomson — COMMENTED** [review]
LGTM, but do we want to target master, or 4.9?

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3942#-:-MILw2zY8A-f1eK2MfxS:bwvd3cm)* status: all files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

**Review by sujeffreyl — COMMENTED** [review]
master IMO due to the changes made in audioRecording.ts

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3942#-:-MIP3_aR2iTNqrVBcID0:b-5w0glx)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

**Pull request merged**
