### PR TITLE
Phase 1 language remodel: allow turning off L1 (BL-9838)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 20 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401)* status: 20 of 26 files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Book/Book.cs, line 1126 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZKBcsH1KVOTFcKmtOW:-MZKBcsH1KVOTFcKmtOX:b79da7e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65a42c636321a3ba90a4250d9afe2a2610df6ee5/src/BloomExe/Book/Book.cs#L1126)):*
> ```Smalltalk
> 			// anything with these attributes anywhere. Nor in BloomPlayer or BloomLibrary.
> 			// If we do discover a purpose, we might want to add a data-M1 for the first metadata
> 			// language.
> ```

The commit comment for this addition states, "Add language info to <body> so that a single branding can vary things by lang".
But I'm not seeing how they are used, either.
https://github.com/BloomBooks/bloomdesktop/commit/cb3d1de43f7e3186e56a85d56ad3bde852e5bc74
___
*[src/BloomExe/Book/Book.cs, line 1955 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZKEVw5DmFcr3TpqsWp:-MZKEVw6Er2SOhJeTc_Z:b-d5snd4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65a42c636321a3ba90a4250d9afe2a2610df6ee5/src/BloomExe/Book/Book.cs#L1955)):*
> ```
> after the MultilingualContentLanguage1
> ```
This is now obsolete.
___
*[src/BloomExe/Book/BookData.cs, line 159 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZKGzXj1hkzQdmkbcsd:-MZKGzXj1hkzQdmkbcse:b-ualwvy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65a42c636321a3ba90a4250d9afe2a2610df6ee5/src/BloomExe/Book/BookData.cs#L159)):*
> ```
> 		/// If the book is configured as bilingual, currently this is always the second
> 		/// of the two languages the user selected. Otherwise, it is the collection's L2.
> ```
Is this true? It doesn't fit with what I thought we were planning.
And if it is true, it seems like it would break an existing book which had L1 and L3 checked but not L2.
___
*[src/BloomExe/Book/BookData.cs, line 798 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZKJmKv5Ds1isJgb2CO:-MZKJmKv5Ds1isJgb2CP:b-v4ezdw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65a42c636321a3ba90a4250d9afe2a2610df6ee5/src/BloomExe/Book/BookData.cs#L798)):*
<details><summary><i alt="summary">Quoted 14 lines of code…</i></summary>

> ```
> 		public void Set(string key, XmlString value, bool isCollectionValue)
> 		{
> 			_dataset.UpdateGenericLanguageString(key, value, isCollectionValue);
> 			UpdateSingleTextVariableInDataDiv(key, _dataset.TextVariables[key]);
> 			if (key == "contentLanguage1")
> 				UpdateLang1Derivatives(value.Unencoded);
> 			else if (key == "contentLanguage2")
> 			{
> 				_cachedIsoLang2 = value.Unencoded;
> 				UpdateML1Derivatives();
> 			}
> 			else if (key == "contentLanguage3")
> 				UpdateLang3Derivatives(value.Unencoded);
> 		}
> ```
</details>

I'm getting really stuck here on the relationship between contentlanguageX and L1, ML1, L3.
Maybe this is what was at the crux of our discussion this morning which I had a hard time fully understanding?
Maybe this needs some comments?
___
*[src/BloomExe/Book/TranslationGroupManager.cs, line 305 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZKAePi4DLXhBsq9gaU:-MZKAePjA0PBjCrvbhZM:b-lmntbc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65a42c636321a3ba90a4250d9afe2a2610df6ee5/src/BloomExe/Book/TranslationGroupManager.cs#L305)):*
> ```Smalltalk
> 				// but it might be better to make a special case for "V, N1"
> 				// Changes here should result in consistent ones in Book.IsLanguageWanted and BookData.GatherDataItemsFromXElement
> 				// and RuntimeInformationInjector.AddUIDictionaryToDom and I18ApiHandleI18nRequest
> ```

Note to self: come back to this
___
*[src/BloomTests/Collection/CollectionSettingsTests.cs, line 151 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZJXkLC4-u5Lj9oEHmx:-MZJXkLC4-u5Lj9oEHmy:b-fi1moh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65a42c636321a3ba90a4250d9afe2a2610df6ee5/src/BloomTests/Collection/CollectionSettingsTests.cs#L151)):*
> ```Smalltalk
> 			var bookData = new BookData(new HtmlDom("<html><body></body></html>"), settings, null);
> 			Assert.That(bookData.GetLanguagePrioritiesForLocalizedTextOnPage(false), Is.EqualTo(results));
> 		}
> ```

I have some confusion surrounding these tests.
1. The method being tested is on BookData, not CollectionSettings. So it seems they aren't in the correct file.
2. Given #1, the interaction between collection settings and bookdata settings is now confusing. For example, contrasting this test to the one just above it, the only difference on the surface is whether or not we want to include L1. But the set up is different, one calling SetMultilingualContentLanguages and the other not.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401)* status: 20 of 26 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/Book/Book.cs, line 1126 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZKBcsH1KVOTFcKmtOW:-MZNWWAd8DqG6zha0htw:buu1ui6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65a42c636321a3ba90a4250d9afe2a2610df6ee5/src/BloomExe/Book/Book.cs#L1126)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The commit comment for this addition states, "Add language info to <body> so that a single branding can vary things by lang".
But I'm not seeing how they are used, either.
https://github.com/BloomBooks/bloomdesktop/commit/cb3d1de43f7e3186e56a85d56ad3bde852e5bc74
</blockquote></details>

I added a comment to capture that intent.
___
*[src/BloomExe/Book/Book.cs, line 1955 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZKEVw5DmFcr3TpqsWp:-MZNWkL4AjJcDMhVCUqT:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65a42c636321a3ba90a4250d9afe2a2610df6ee5/src/BloomExe/Book/Book.cs#L1955)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> after the MultilingualContentLanguage1
> ```
This is now obsolete.
</blockquote></details>

Done.
___
*[src/BloomExe/Book/BookData.cs, line 159 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZKGzXj1hkzQdmkbcsd:-MZNXLuV9TgOMOaYX9wP:b-2tp8zg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65a42c636321a3ba90a4250d9afe2a2610df6ee5/src/BloomExe/Book/BookData.cs#L159)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> 		/// If the book is configured as bilingual, currently this is always the second
> 		/// of the two languages the user selected. Otherwise, it is the collection's L2.
> ```
Is this true? It doesn't fit with what I thought we were planning.
And if it is true, it seems like it would break an existing book which had L1 and L3 checked but not L2.
</blockquote></details>

Was true briefly, changed after interactive review with JohnH. Fixed.
___
*[src/BloomExe/Book/BookData.cs, line 798 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZKJmKv5Ds1isJgb2CO:-MZNYijK6WMBbQ1WIVdY:b9fqyaa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65a42c636321a3ba90a4250d9afe2a2610df6ee5/src/BloomExe/Book/BookData.cs#L798)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> 		public void Set(string key, XmlString value, bool isCollectionValue)
> 		{
> 			_dataset.UpdateGenericLanguageString(key, value, isCollectionValue);
> 			UpdateSingleTextVariableInDataDiv(key, _dataset.TextVariables[key]);
> 			if (key == "contentLanguage1")
> 				UpdateLang1Derivatives(value.Unencoded);
> 			else if (key == "contentLanguage2")
> 			{
> 				_cachedIsoLang2 = value.Unencoded;
> 				UpdateML1Derivatives();
> 			}
> 			else if (key == "contentLanguage3")
> 				UpdateLang3Derivatives(value.Unencoded);
> 		}
> ```
I'm getting really stuck here on the relationship between contentlanguageX and L1, ML1, L3.
Maybe this is what was at the crux of our discussion this morning which I had a hard time fully understanding?
Maybe this needs some comments?
</blockquote></details>

I've tried.
___
*[src/BloomExe/Book/TranslationGroupManager.cs, line 305 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZKAePi4DLXhBsq9gaU:-MZNYmkGDfXeGAcFFx9U:b-lz6fz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65a42c636321a3ba90a4250d9afe2a2610df6ee5/src/BloomExe/Book/TranslationGroupManager.cs#L305)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Note to self: come back to this
</blockquote></details>

Not done? :-)
___
*[src/BloomTests/Collection/CollectionSettingsTests.cs, line 151 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZJXkLC4-u5Lj9oEHmx:-MZN_Xdd2kIEzXCDMjva:bpr2wkp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65a42c636321a3ba90a4250d9afe2a2610df6ee5/src/BloomTests/Collection/CollectionSettingsTests.cs#L151)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I have some confusion surrounding these tests.
1. The method being tested is on BookData, not CollectionSettings. So it seems they aren't in the correct file.
2. Given #1, the interaction between collection settings and bookdata settings is now confusing. For example, contrasting this test to the one just above it, the only difference on the surface is whether or not we want to include L1. But the set up is different, one calling SetMultilingualContentLanguages and the other not.
</blockquote></details>

I didn't move the test, so didn't give any thought to what class it is on. I think it just happened that the second one didn't need to make the BookData match the collection settings in order to pass, so I didn't add it. I've done so now, so at least it's clear that the only difference is whether to include L1. Perhaps the tests are just here because they need the CreateCollectionSettings method? Or perhaps at some point the method moved and the test didn't? I haven't actually changed the method being tested, it's just that its results no longer include collection language 3 if it's not selected.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 26 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401)* status: all files reviewed, 7 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Book/BookData.cs, line 798 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZKJmKv5Ds1isJgb2CO:-MZO7Lap8HemInBkxns-:b-cmk1k2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65a42c636321a3ba90a4250d9afe2a2610df6ee5/src/BloomExe/Book/BookData.cs#L798)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I've tried.
</blockquote></details>

We discussed this and decided we should introduce `UpdateLang2Derivatives` to limit confusion.
___
*[src/BloomExe/Book/TranslationGroupManager.cs, line 305 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZKAePi4DLXhBsq9gaU:-MZONQtn-1qP_JZYcUoX:b-57twl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65a42c636321a3ba90a4250d9afe2a2610df6ee5/src/BloomExe/Book/TranslationGroupManager.cs#L305)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Not done? :-)
</blockquote></details>

I think we decided in our discussion that if we go with this phase1 implementation, that this is the way to do it.
I'll leave it to you whether it is warranted to update the comment.
___
*[src/BloomTests/Book/BookDataTests.cs, line 1085 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZOOhMLCsD0315JMW40:-MZOOhMLCsD0315JMW41:bj265mv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/339521d25c3431a8d4a169e882b3259d2621e53f/src/BloomTests/Book/BookDataTests.cs#L1085)):*
> ```
> // Todo: test contentLanguageN attempting to set non-collection languages.
> ```
___
*[src/BloomTests/Book/BookDataTests.cs, line 1353 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZOOZc2EvBreN5OXV-6:-MZOOZc2EvBreN5OXV-7:b5bayrf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/339521d25c3431a8d4a169e882b3259d2621e53f/src/BloomTests/Book/BookDataTests.cs#L1353)):*
> ```Smalltalk
> 		//	data.SetMultilingualContentLanguages("en", "fr", "tpi");
> 		//	Assert.AreEqual("Tok Pisin", data.GetVariableOrNull("nameOfNationalLanguage2", "*").Xml);
> 		//}
> ```

Commented tests we discussed.
___
*[src/BloomTests/Book/BookTests.cs, line 414 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZOOIDR3TNp-VqSN4qT:-MZOOIDS8hz1CpXhbSug:b-td8zl2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/339521d25c3431a8d4a169e882b3259d2621e53f/src/BloomTests/Book/BookTests.cs#L414)):*
> ```Smalltalk
> 		//	book.BringBookUpToDate(new NullProgress());
> 		//	AssertThatXmlIn.Dom(dom).HasSpecifiedNumberOfMatchesForXpath("//span[text()='French']",1);
> 		//}
> ```

Commented test we discussed.
___
*[src/BloomTests/Book/BookTests.cs, line 448 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZOOO-Q0XnU3oBwYx9V:-MZOOO-R6GFD1wrf25BY:b-9qbj8u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/339521d25c3431a8d4a169e882b3259d2621e53f/src/BloomTests/Book/BookTests.cs#L448)):*
> ```Smalltalk
> 			book.SetMultilingualContentLanguages(bookData.Language1.Iso639Code);
> 			AssertThatXmlIn.Dom(book.RawDom).HasSpecifiedNumberOfMatchesForXpath("//div[@data-derived='languagesOfBook' and text()='ไทย']", 1);
> 		}
> ```

Another case where we should add a test for CollectionLanguage1 not in book?
___
*[src/BloomTests/Collection/CollectionSettingsTests.cs, line 151 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZJXkLC4-u5Lj9oEHmx:-MZONsOR-v19IyEkWPmm:b-ae4maj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65a42c636321a3ba90a4250d9afe2a2610df6ee5/src/BloomTests/Collection/CollectionSettingsTests.cs#L151)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I didn't move the test, so didn't give any thought to what class it is on. I think it just happened that the second one didn't need to make the BookData match the collection settings in order to pass, so I didn't add it. I've done so now, so at least it's clear that the only difference is whether to include L1. Perhaps the tests are just here because they need the CreateCollectionSettings method? Or perhaps at some point the method moved and the test didn't? I haven't actually changed the method being tested, it's just that its results no longer include collection language 3 if it's not selected.
</blockquote></details>

Thanks. As we discussed, it is probably worth at least adding a test where CollectionLanguage1 is not one of the book languages. Here and possibly a few other places.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Book/BookData.cs, line 2070 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZPTzZf3bcTFnBU2s08:-MZPTzZf3bcTFnBU2s09:b-w5gr7f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0f3f788eb9fb09743ee1af5099d451979f09cc7b/src/BloomExe/Book/BookData.cs#L2070)):*
> ```Smalltalk
> 		/// </summary>
> 		/// <returns>A prioritized enumerable of language codes</returns>
> 		public IEnumerable<string> GetLanguagePrioritiesForLocalizedTextOnPage(bool includeLang1 = true)
> ```

Sorry; I'm struggling a bit with this.
We have a flag to exclude L1. But is that collection L1 or book L1? You've implemented it to exclude both.
I can't get my brain to figure out if that is correct. Probably it is. Depends on how we use it, I guess. Do we need a comment for the parameter?
Also, the comment below says, "not the first if we're excluding vernacular". Seems we should change that to "excluding L1"

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401)* status: 23 of 27 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/Book/BookData.cs, line 798 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZKJmKv5Ds1isJgb2CO:-MZPV_cqCgRaMy6n5k8c:bb6un1j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65a42c636321a3ba90a4250d9afe2a2610df6ee5/src/BloomExe/Book/BookData.cs#L798)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We discussed this and decided we should introduce `UpdateLang2Derivatives` to limit confusion.
</blockquote></details>

Done
___
*[src/BloomExe/Book/BookData.cs, line 2070 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZPTzZf3bcTFnBU2s08:-MZS_vZ3-oEVb2O22kR3:b3vmpcz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0f3f788eb9fb09743ee1af5099d451979f09cc7b/src/BloomExe/Book/BookData.cs#L2070)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; I'm struggling a bit with this.
We have a flag to exclude L1. But is that collection L1 or book L1? You've implemented it to exclude both.
I can't get my brain to figure out if that is correct. Probably it is. Depends on how we use it, I guess. Do we need a comment for the parameter?
Also, the comment below says, "not the first if we're excluding vernacular". Seems we should change that to "excluding L1"
</blockquote></details>

Yes, I'm not really sure either. I've tried to improve the comment.
___
*[src/BloomExe/Book/TranslationGroupManager.cs, line 305 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZKAePi4DLXhBsq9gaU:-MZSai517Eup363fnqnu:bpsy4nz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65a42c636321a3ba90a4250d9afe2a2610df6ee5/src/BloomExe/Book/TranslationGroupManager.cs#L305)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think we decided in our discussion that if we go with this phase1 implementation, that this is the way to do it.
I'll leave it to you whether it is warranted to update the comment.
</blockquote></details>

Took out the comment. I think we've decided to stick with this for now.
___
*[src/BloomTests/Book/BookDataTests.cs, line 1085 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZOOhMLCsD0315JMW40:-MZSaorP7xpLN-TQ5Tbq:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/339521d25c3431a8d4a169e882b3259d2621e53f/src/BloomTests/Book/BookDataTests.cs#L1085)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> // Todo: test contentLanguageN attempting to set non-collection languages.
> ```

</blockquote></details>

Done.
___
*[src/BloomTests/Book/BookDataTests.cs, line 1353 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZOOZc2EvBreN5OXV-6:-MZSaqiR3liiG41iAyG1:bygikj8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/339521d25c3431a8d4a169e882b3259d2621e53f/src/BloomTests/Book/BookDataTests.cs#L1353)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Commented tests we discussed.
</blockquote></details>

Added explanation
___
*[src/BloomTests/Book/BookTests.cs, line 414 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZOOIDR3TNp-VqSN4qT:-MZSatwQ0uQ9PwfqyiZe:bygikj8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/339521d25c3431a8d4a169e882b3259d2621e53f/src/BloomTests/Book/BookTests.cs#L414)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Commented test we discussed.
</blockquote></details>

Added explanation
___
*[src/BloomTests/Book/BookTests.cs, line 448 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZOOO-Q0XnU3oBwYx9V:-MZSbKtdBIjDDYR-JWvY:b-euqj83) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/339521d25c3431a8d4a169e882b3259d2621e53f/src/BloomTests/Book/BookTests.cs#L448)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Another case where we should add a test for CollectionLanguage1 not in book?
</blockquote></details>

I'm inclined to think not. The first thing the method does is call the BookData method of the same name, which is now tested to throw if passed a non-collection language.
___
*[src/BloomTests/Collection/CollectionSettingsTests.cs, line 151 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZJXkLC4-u5Lj9oEHmx:-MZScDsI2elxYdCtefX7:bstxtro) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/65a42c636321a3ba90a4250d9afe2a2610df6ee5/src/BloomTests/Collection/CollectionSettingsTests.cs#L151)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Thanks. As we discussed, it is probably worth at least adding a test where CollectionLanguage1 is not one of the book languages. Here and possibly a few other places.
</blockquote></details>

I've added several more tests. Also realized we added a new function that has the same purpose as this one, so removed it, merged the new behavior into this and adjusted tests.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomTests/Book/BookDataTests.cs, line 1085 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZOOhMLCsD0315JMW40:-MZT3M2x09BcxQoRoiys:b-ixwllc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/339521d25c3431a8d4a169e882b3259d2621e53f/src/BloomTests/Book/BookDataTests.cs#L1085)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you remove the Todo comment, please? Then LGTM.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401)* status: 26 of 27 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomTests/Book/BookDataTests.cs, line 1085 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4401#-MZOOhMLCsD0315JMW40:-MZTePg0EXZQIO6MpjJc:b-r35m5a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/339521d25c3431a8d4a169e882b3259d2621e53f/src/BloomTests/Book/BookDataTests.cs#L1085)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Can you remove the Todo comment, please? Then LGTM.
</blockquote></details>

Done. Sorry, that was silly of me.

**Pull request merged**
