### PR TITLE
Allow growing answer boxes for non-Device16x9Landscape quiz (BL-9952)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4480)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4480)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less, line 12 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4480#-MaF6tya4vit-41i2oXD:-MaF6tya4vit-41i2oXE:bmco2ou) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1ddace04c9ecb1b897e18b47106cc8fe70f86b7d/src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less#L12)):*
> ```Less
>         height: 2.85em;
>     }
> }
> ```

I'm not excited about this fix.
1. It only fixes this layout whereas if there isn't another layout already with this problem, some day there will be.
2. I think is is more likely that someone will want multi-line answers than 6 answers.

Ideas/options
Reduce the bottom margin of answers. 10->9 is enough for D16x9L.
Eliminate an answer.
(Either of those could be done only if childIsOverflowingThis is set on the marginBox or for certain layouts or if layout marginbox is < certain height.)
Don't show the childIsOverflowingThis warning for quizzes (on some set of layouts).

Can discuss these or other options/ideas.
Probably worth asking @hatton who usually sees things from a better angle.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4480)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @hatton)

___
*[src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less, line 12 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4480#-MaF6tya4vit-41i2oXD:-MaU81Oe2A84VlVhIA8d:bism3n1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1ddace04c9ecb1b897e18b47106cc8fe70f86b7d/src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less#L12)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not excited about this fix.
1. It only fixes this layout whereas if there isn't another layout already with this problem, some day there will be.
2. I think is is more likely that someone will want multi-line answers than 6 answers.

Ideas/options
Reduce the bottom margin of answers. 10->9 is enough for D16x9L.
Eliminate an answer.
(Either of those could be done only if childIsOverflowingThis is set on the marginBox or for certain layouts or if layout marginbox is < certain height.)
Don't show the childIsOverflowingThis warning for quizzes (on some set of layouts).

Can discuss these or other options/ideas.
Probably worth asking @hatton who usually sees things from a better angle.
</blockquote></details>

The problem with conditioning a change on childIsOverflowing is that the overflow border marker remains for thumbnails even if we suppress it for the actual page.
I think reducing the bottom margin of answers from 10 to 9 for Device16x9Landscape quiz pages is probably the best compromise overall.  For comprehension quizzes, I would think questions and answers that fit in one landscape line would probably be best anyway.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4480)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less, line 12 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4480#-MaF6tya4vit-41i2oXD:-MaUV39M1sllillpEWfJ:b-2gph3w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1ddace04c9ecb1b897e18b47106cc8fe70f86b7d/src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less#L12)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

The problem with conditioning a change on childIsOverflowing is that the overflow border marker remains for thumbnails even if we suppress it for the actual page.
I think reducing the bottom margin of answers from 10 to 9 for Device16x9Landscape quiz pages is probably the best compromise overall.  For comprehension quizzes, I would think questions and answers that fit in one landscape line would probably be best anyway.
</blockquote></details>

Sorry I didn't catch this before, but I think we should move this down into the `.bloom-page.simple-comprehension-quiz` below.
I think this is a better solution than the first, but is still unfortunate that it requires explicitly listing affected layout(s).

I'm reaching out to JH again.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4480)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less, line 12 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4480#-MaF6tya4vit-41i2oXD:-MaUx3f25XYV6CUxZc6u:bf9yc2z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1ddace04c9ecb1b897e18b47106cc8fe70f86b7d/src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less#L12)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry I didn't catch this before, but I think we should move this down into the `.bloom-page.simple-comprehension-quiz` below.
I think this is a better solution than the first, but is still unfortunate that it requires explicitly listing affected layout(s).

I'm reaching out to JH again.
</blockquote></details>

pls grab me after standup

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4480)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less, line 12 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4480#-MaF6tya4vit-41i2oXD:-MaV-GvwCzfSdymnLija:b-3br32y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1ddace04c9ecb1b897e18b47106cc8fe70f86b7d/src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less#L12)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

pls grab me after standup
</blockquote></details>

I've moved the block of less code.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4480)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4480)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less, line 12 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4480#-MaF6tya4vit-41i2oXD:-MaZWQynAWGsUj8SNvRL:b-66j0uh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1ddace04c9ecb1b897e18b47106cc8fe70f86b7d/src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less#L12)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I've moved the block of less code.
</blockquote></details>

I've changed the PR to just not show overflow markup for quiz pages.  I think this is what we decided in the meeting earlier today.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4480)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton and @StephenMcConnel)

___
*[src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less, line 12 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4480#-MaF6tya4vit-41i2oXD:-MaZZIun-TYuhpXF692J:b-wrvtg5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1ddace04c9ecb1b897e18b47106cc8fe70f86b7d/src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less#L12)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I've changed the PR to just not show overflow markup for quiz pages.  I think this is what we decided in the meeting earlier today.
</blockquote></details>

What about just not calling these two lines of code if in a quiz?
In OverflowChecker::MarkOverflowInternal()
```
$this.addClass("thisOverflowingParent"); // but it's this one that is actually overflowing
$overflowingAncestor.addClass("childOverflowingThis");
```
Then we don't have to reset the border or add a test in PageThumbnail.tsx.
Only downside I see is we lose this
```
//BL-2512 when overflowing on pages where the text is allowed to run off the screen, the formatButton would not be visible/reachable, so you couldn't shrink the text
//in response to the overflow situation.
//So in this situation, we just show it at the top.
.thisOverflowingParent #formatButton {
    top: 0;
}
```
but even if we allow quiz answers to have different styles, I'm sure it never happens in practice.

Do you see other downsides?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4480)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less, line 12 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4480#-MaF6tya4vit-41i2oXD:-Ma_JEQZ64YkUdAlOruY:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1ddace04c9ecb1b897e18b47106cc8fe70f86b7d/src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less#L12)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What about just not calling these two lines of code if in a quiz?
In OverflowChecker::MarkOverflowInternal()
```
$this.addClass("thisOverflowingParent"); // but it's this one that is actually overflowing
$overflowingAncestor.addClass("childOverflowingThis");
```
Then we don't have to reset the border or add a test in PageThumbnail.tsx.
Only downside I see is we lose this
```
//BL-2512 when overflowing on pages where the text is allowed to run off the screen, the formatButton would not be visible/reachable, so you couldn't shrink the text
//in response to the overflow situation.
//So in this situation, we just show it at the top.
.thisOverflowingParent #formatButton {
    top: 0;
}
```
but even if we allow quiz answers to have different styles, I'm sure it never happens in practice.

Do you see other downsides?
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4480)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
