### PR TITLE
BL-5749 Add photo story mode features to body

### PR DESCRIPTION
**Pull request by hatton**
This is a semi-experimental step.
Adds a checkbox in Publish:Android
Does not yet persist that setting.
Does not have unit tests.

When the checkbox is selected, Bloom adds a set of 6 attributes to body which, together, constitute the "microsoft photo story mode".

To build with this PR, you will need to update your npm packages, as it requires an update to less.

When looking at the change to package.json, you'll need to look  at the individual commits, because it got reformated (sorry). Looking at the individual commits, you can see one where it is reformated, and another where the change is made.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2271)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Review status: 0 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/BloomBrowserUI/yarn.lock, line 41 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2271#-L7UcnCzCUR4vdjAxHfW:-L7UcnCzCUR4vdjAxHfX:b-yyg635) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a745bd713774ab12ae53d1400e35ba9d3e046f3/src/BloomBrowserUI/yarn.lock#L41)):*
> ```
>   resolved "https://registry.yarnpkg.com/accepts/-/accepts-1.3.3.tgz#c3ca7434938648c3e0d9c1e328dd68b622c284ca"
>   dependencies:
>     mime-types "~2.1.11"
> ```

I have no idea what this file means or why anything in it changed. I'm guessing it's to do with the new npm version? I have a vague recollection that we weren't checking yarn stuff in yet, but maybe I missed when that changed?

---

*[src/BloomBrowserUI/bookLayout/bookFeatures.less, line 28 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2271#-L7Ud_Afa5p5LuxoHlRL:-L7Ud_Afa5p5LuxoHlRM:b-j4a0na) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a745bd713774ab12ae53d1400e35ba9d3e046f3/src/BloomBrowserUI/bookLayout/bookFeatures.less#L28)):*
> ```Less
>             &[@{dataFeature}*="allOrientations"],
>             &[@{dataFeature}*="landscape"]
>                 .bloom-page[class*="Device16x9Landscape"],
> ```

These Device classes won't be found if we are printing, which is one of the media options above.

---

*[src/BloomBrowserUI/bookLayout/bookFeatures.less, line 54 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2271#-L7UdwVizWDJRYG7habm:-L7UdwVizWDJRYG7habn:blb8pvh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a745bd713774ab12ae53d1400e35ba9d3e046f3/src/BloomBrowserUI/bookLayout/bookFeatures.less#L54)):*
> ```Less
> 
>         &[class*="Device16x9Landscape"] {
>             width: @Device16x9Landscape-Width;
> ```

Surprised not to see something about height here...what makes it fill the screen vertically?

---

*[src/BloomExe/Book/Book.cs, line 390 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2271#-L7Um3iGfewscT7Yoll-:-L7Um3iGfewscT7Yoll0:bh8blgj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a745bd713774ab12ae53d1400e35ba9d3e046f3/src/BloomExe/Book/Book.cs#L390)):*
> ```Smalltalk
> 			// Don't let spaces between <strong>, <em>, or <u> elements be removed. (BL-2484)
> 			dom.RawDom.PreserveWhitespace = true;
> 			var newBody = dom.RawDom.SelectSingleNodeHonoringDefaultNS("//body");
> ```

is there a reason to use a different path here than in the above? It's puzzling, and presumably one or the other is most efficient.

---

*[src/BloomExe/Book/HtmlDom.cs, line 1050 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2271#-L7V2hN7dId26L3RnSTm:-L7V2hN7dId26L3RnSTn:b3ve13u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a745bd713774ab12ae53d1400e35ba9d3e046f3/src/BloomExe/Book/HtmlDom.cs#L1050)):*
> ```Smalltalk
> 		/// <param name="orientationConstraint"></param>
> 		/// <param name="mediaConstraint"></param>
> 		public  void SetBookFeature(string featureName, string orientationConstraint, string mediaConstraint)
> ```

Should orientationConstraint (maybe even mediaConstraint?) be enumerations? Only a few values make sense, and typos could be annoying.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2271)*

**Comment by JohnThomson** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2271)*

**Comment by JohnThomson** [comment]
Looks basically good...few minor questions, maybe not worth holding things up

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2271#-:-L7V4LNtpLagkllCnYjS:b-z6josm)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/BloomBrowserUI/yarn.lock, line 41 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2271#-L7UcnCzCUR4vdjAxHfW:-L7V7vmRFNMu9kppzaj4:bi1v5xa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a745bd713774ab12ae53d1400e35ba9d3e046f3/src/BloomBrowserUI/yarn.lock#L41)):*
Yah, at some point it got checked in. IIRC last time it was *me* asking *you* about it, and you pointed out that you were just letting it be up to date. Which was the right call :-)

> I have no idea what this file means 

Worth a google :-)

---

*[src/BloomBrowserUI/bookLayout/bookFeatures.less, line 28 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2271#-L7Ud_Afa5p5LuxoHlRL:-L7V8tgWYXChw21nrOqZ:b5o48hh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a745bd713774ab12ae53d1400e35ba9d3e046f3/src/BloomBrowserUI/bookLayout/bookFeatures.less#L28)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

These Device classes won't be found if we are printing, which is one of the media options above.
</blockquote></details>

Hmmm... I take you to mean to say that if it is set to print and landscape and you are in some other paper layout than Device16x9Landscape, it won't activate the features.  True, true... I'll change that to just "Landscape".

---

*[src/BloomBrowserUI/bookLayout/bookFeatures.less, line 54 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2271#-L7UdwVizWDJRYG7habm:-L7V9MjObNrVA40ZEtsp:b-um6tel) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a745bd713774ab12ae53d1400e35ba9d3e046f3/src/BloomBrowserUI/bookLayout/bookFeatures.less#L54)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Surprised not to see something about height here...what makes it fill the screen vertically?
</blockquote></details>

You can't specify both width and height without risking changing the orientation. So you specify one of them.

---

*[src/BloomExe/Book/Book.cs, line 390 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2271#-L7Um3iGfewscT7Yoll-:-L7V9g9ItQCqDkjUu5H4:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a745bd713774ab12ae53d1400e35ba9d3e046f3/src/BloomExe/Book/Book.cs#L390)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

is there a reason to use a different path here than in the above? It's puzzling, and presumably one or the other is most efficient.
</blockquote></details>

Done.

---

*[src/BloomExe/Book/HtmlDom.cs, line 1050 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2271#-L7V2hN7dId26L3RnSTm:-L7V9iXIwKGF71qIUy0w:bnmui0m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1a745bd713774ab12ae53d1400e35ba9d3e046f3/src/BloomExe/Book/HtmlDom.cs#L1050)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Should orientationConstraint (maybe even mediaConstraint?) be enumerations? Only a few values make sense, and typos could be annoying.
</blockquote></details>

Yes, eventually. Just getting the minimum done here...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2271)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Review status: 10 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2271#-:-L7VAiwQn2AAAgBZFv4M:bnfp4nl)*

**Comment by JohnThomson** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2271)*

**Pull request merged**
