### PR TITLE
Set the UI language from the system if possible (BL-4393)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1558)

### CODE REVIEW

**Comment by JohnThomson** [comment]
I don't see anything to make this happen only the FIRST time Bloom starts up on a particular system. If the user has chosen a non-OS-default UI language on an earlier run, we should stick with what they chose.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1558#-:-Kesop4ODTRf3fk6Q4Iy:b8wcp8d)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Program.cs, line 904 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1558#-Kf8AeRcRRVIqDMu3mnj:-Kf8AeRdIbxVWAgJ2qxq:b-s5y0zn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/00c2733ff98c9079a185a8141f118cff2695e642/src/BloomExe/Program.cs#L904)):*
> ```Smalltalk
> 				var uiLanguage =   LocalizationManager.UILanguageId;//just feeding this into subsequent creates prevents asking the user twice if the language of their os isn't one we have a tmx for
> 				// If the user has not set the interface language, try to use the system language if we can.
> 				// (See http://issues.bloomlibrary.org/youtrack/issue/BL-4393.)
> ```

The current code will silently follow the current UI language setting from the system as long as the user has never explicitly set the UI language inside Bloom.  This could conceivably cause the annoying dialog asking the user to choose an existing localization every time Bloom is started.  But if multiple users are using the same computer in multiple major languages for which Bloom has localizations, then Bloom could just track the current user's UI language setting.  This may be getting too fancy...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1558)*

**Comment by andrew-polk** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Properties/Settings.settings, line 2 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1558#-Kf8DDuv3VtKgrDT9HVI:-Kf8DDuwk0tm_fjlsLL7:b7frpa6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/00c2733ff98c9079a185a8141f118cff2695e642/src/BloomExe/Properties/Settings.settings#L2)):*
> ```
> <?xml version='1.0' encoding='utf-8'?>
> <SettingsFile xmlns="http://schemas.microsoft.com/VisualStudio/2004/01/settings" CurrentProfile="(Default)" GeneratedClassNamespace="Bloo_userInterfaceLanguagem.Properties" GeneratedClassName="Settings">
> ```

This is a bizarre change...
Find/replace gone wrong?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1558)*

**Comment by andrew-polk** [comment]
Did we say we were considering this for 3.7?

---

Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1558#-:-Kf8DzBD2m2PC8d5IU2H:bbp4a5z)*

**Comment by StephenMcConnel** [comment]
I think there was a mention of it at least for 3.8 if not 3.7.  I'm fairly happy with the final code being safe for 3.8.  I'm not sure it's worth perturbing 3.7, but that's not my call.

---

Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Program.cs, line 904 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1558#-Kf8AeRcRRVIqDMu3mnj:-Kf8cqlXn0ShoLb2zXag:bt5a60b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/00c2733ff98c9079a185a8141f118cff2695e642/src/BloomExe/Program.cs#L904)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

The current code will silently follow the current UI language setting from the system as long as the user has never explicitly set the UI language inside Bloom.  This could conceivably cause the annoying dialog asking the user to choose an existing localization every time Bloom is started.  But if multiple users are using the same computer in multiple major languages for which Bloom has localizations, then Bloom could just track the current user's UI language setting.  This may be getting too fancy...
</blockquote></details>

This comment no longer applies after I redid the code a third time.  It still tries to follow the UI language silently, but it filters the language tag to avoid provoking the internal L10N chooser dialog if at all possible.  And if it does provoke it, it will happen only once.

---

*[src/BloomExe/Properties/Settings.settings, line 2 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1558#-Kf8DDuv3VtKgrDT9HVI:-Kf8cMvmNgXICww4FpR5:bp6ujxi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/00c2733ff98c9079a185a8141f118cff2695e642/src/BloomExe/Properties/Settings.settings#L2)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This is a bizarre change...
Find/replace gone wrong?
</blockquote></details>

oops.  Probably finger confusion between emacs and monodevelop...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1558#-:-Kf8cViqXXfUEGYiSd_m:b1innvr)*

**Comment by hatton** [comment]
I think 3.8 is the right target here.

**Comment by hatton** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Program.cs, line 956 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1558#-KfCoPvKchwo_DA0xb3v:-KfCoPvKchwo_DA0xb3w:btdc8al) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/06bb20189733199227cf93a0e9052111cd0e4526/src/BloomExe/Program.cs#L956)):*
> ```Smalltalk
> 					// LocalizationManager.GetUILanguages(true) doesn't work before calling LocalizationManager.Create(),
> 					// so create a LocalizationManager that we know will succeed without bothering the user.
> 					var lmEn = LocalizationManager.Create("en", "Bloom", "Bloom", Application.ProductVersion,
> ```

Couple things:
1) I know this is a matter of preference... but the Bloom codebase generally leans towards spelling things out instead of non-pronounceable abbreviations; exceptions are for things like ui, iso, 'lang', etc.

2) this lmEn does not appear to be used, so could be removed.

3) maybe it *should* be used, because LocalizationManager is IDisposable()

4) Its start-up time is probably significant, and we already create one in Program.SetUpLocalization(), in the line after this one. Is it possible to create it first and then pass that to this method?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1558)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 3 files at r2.
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1558)*

**Comment by StephenMcConnel** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Program.cs, line 956 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1558#-KfCoPvKchwo_DA0xb3v:-KfHZ2r-PNATko1dGqsl:bjkk09r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/06bb20189733199227cf93a0e9052111cd0e4526/src/BloomExe/Program.cs#L956)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Couple things:
1) I know this is a matter of preference... but the Bloom codebase generally leans towards spelling things out instead of non-pronounceable abbreviations; exceptions are for things like ui, iso, 'lang', etc.

2) this lmEn does not appear to be used, so could be removed.

3) maybe it *should* be used, because LocalizationManager is IDisposable()

4) Its start-up time is probably significant, and we already create one in Program.SetUpLocalization(), in the line after this one. Is it possible to create it first and then pass that to this method?
</blockquote></details>

revised to use new L10NSharp method

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1558)*

**Pull request merged**
