### PR TITLE
Generate FeaturesRequired record for comic elements (BL-7795)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492)

### CODE REVIEW

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Book/BookStorage.cs, line 711 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492#-LvBkPgn2G7ynA7yTj89:-LvBkPgn2G7ynA7yTj8A:b-289dvq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7448f2dd2b93f4f3d4578dbb387889a43427609d/src/BloomExe/Book/BookStorage.cs#L711)):*
> ```Smalltalk
> 			foreach (var feature in _features)
> 			{
> 				if (dom.SelectSingleNode(feature.XPath) != null)
> ```

At one point we were wondering how long these xpaths take. I think we should measure that now... it would be easy to miss that every page change is now a second slower on a 50 page book. You could then put a comment in here with your results.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Book/BookStorage.cs, line 681 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492#-LvBlYReA6aKUUVTkPpD:-LvBlYReA6aKUUVTkPpE:b-gfm6q5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7448f2dd2b93f4f3d4578dbb387889a43427609d/src/BloomExe/Book/BookStorage.cs#L681)):*
> ```Smalltalk
> 				XPath = "//*[@data-audiorecordingmode='TextBox']"
> 			},
> 			new Feature() {FeatureId = "comics",
> ```

`"comics"` doesn't seem to envision new incompatible versions of comicaljs

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/Book/BookStorage.cs, line 681 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492#-LvBlYReA6aKUUVTkPpD:-LvC8aT6-IfTU9zudwo3:bv4bf3y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7448f2dd2b93f4f3d4578dbb387889a43427609d/src/BloomExe/Book/BookStorage.cs#L681)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

`"comics"` doesn't seem to envision new incompatible versions of comicaljs
</blockquote></details>

It's not clear to me what is gained by anticipating it. True, at some point, say Bloom 4.8, we may start pushing a feature requirement comics-2/4.8/"Support for comics--stage 2" (or "support for advanced comics," or maybe we can say something specific like "support for animated comics"). But to now tell users that they need 4.7 because it has "Support for comics--stage 1" doesn't seem to communicate anything more than simply that it needs "Support for comics".
Of course Bloom 4.8 would then need to figure out whether to specify that the book needs 4.7 for comics, or 4.8 for comics-2, and avoid adding both if it really needs 4.8. But I can't see that being any easier because we make the original featureId be "comics-1".

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Book/BookStorage.cs, line 681 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492#-LvBlYReA6aKUUVTkPpD:-LvCUfH3BMib4z587Rsu:b-q82xqc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7448f2dd2b93f4f3d4578dbb387889a43427609d/src/BloomExe/Book/BookStorage.cs#L681)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's not clear to me what is gained by anticipating it. True, at some point, say Bloom 4.8, we may start pushing a feature requirement comics-2/4.8/"Support for comics--stage 2" (or "support for advanced comics," or maybe we can say something specific like "support for animated comics"). But to now tell users that they need 4.7 because it has "Support for comics--stage 1" doesn't seem to communicate anything more than simply that it needs "Support for comics".
Of course Bloom 4.8 would then need to figure out whether to specify that the book needs 4.7 for comics, or 4.8 for comics-2, and avoid adding both if it really needs 4.8. But I can't see that being any easier because we make the original featureId be "comics-1".
</blockquote></details>

Maybe I'm missing something because your answer is complicated when the scenario is simple:

4.8 emits data-bubbles that that require 4.8+.
We bump some number, probably matching the comical library main number.
Someone opens that comic in 4.7, get told they need 4.8.
The end.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/Book/BookStorage.cs, line 681 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492#-LvBlYReA6aKUUVTkPpD:-LvCjk3X0teMlWD5yt0p:bb12iaw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7448f2dd2b93f4f3d4578dbb387889a43427609d/src/BloomExe/Book/BookStorage.cs#L681)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Maybe I'm missing something because your answer is complicated when the scenario is simple:

4.8 emits data-bubbles that that require 4.8+.
We bump some number, probably matching the comical library main number.
Someone opens that comic in 4.7, get told they need 4.8.
The end.

</blockquote></details>

I don't see how we can automate making it just depend on the Comical version number, because most likely Comical will go through many versions along the way to 4.8.
If we as programmers decide that everything Comical produced by 4.8 requires 4.8, all we have to do is bump the required version number field in the Feature.  As you say, the end.
There's a version (of comical data) in the bubble-data, so we could try to guess what we'll want to happen if we decide to bump that, but I don't see the advantage of doing it now rather than when we need it. If it's more complicated than that, then we probably need a new feature and a different xpath, or if it can't be decided by xpath, some new code. But I don't see anything to do in anticipation of that.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Book/BookStorage.cs, line 681 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492#-LvBlYReA6aKUUVTkPpD:-LvCuJSOEcDobUJ0Zvfb:b-z86ri8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7448f2dd2b93f4f3d4578dbb387889a43427609d/src/BloomExe/Book/BookStorage.cs#L681)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't see how we can automate making it just depend on the Comical version number, because most likely Comical will go through many versions along the way to 4.8.
If we as programmers decide that everything Comical produced by 4.8 requires 4.8, all we have to do is bump the required version number field in the Feature.  As you say, the end.
There's a version (of comical data) in the bubble-data, so we could try to guess what we'll want to happen if we decide to bump that, but I don't see the advantage of doing it now rather than when we need it. If it's more complicated than that, then we probably need a new feature and a different xpath, or if it can't be decided by xpath, some new code. But I don't see anything to do in anticipation of that.
</blockquote></details>

OK let's agree to disagree. I think the sequence "comical-1", "comical-2" etc is simpler, you think "comics",  "comics-1" is simpler.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Book/BookStorage.cs, line 681 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492#-LvBlYReA6aKUUVTkPpD:-LvD9ehQ7cUalOjJekCY:bp2d056) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7448f2dd2b93f4f3d4578dbb387889a43427609d/src/BloomExe/Book/BookStorage.cs#L681)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

OK let's agree to disagree. I think the sequence "comical-1", "comical-2" etc is simpler, you think "comics",  "comics-1" is simpler.
</blockquote></details>

OK, sure, we can use comical-1. I thought you wanted something more than that.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Book/BookStorage.cs, line 711 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492#-LvBkPgn2G7ynA7yTj89:-LvD9uGo3mch4VPWKI7w:bhy9ot6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7448f2dd2b93f4f3d4578dbb387889a43427609d/src/BloomExe/Book/BookStorage.cs#L711)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

At one point we were wondering how long these xpaths take. I think we should measure that now... it would be easy to miss that every page change is now a second slower on a 50 page book. You could then put a comment in here with your results.
</blockquote></details>

Will do.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/Book/BookStorage.cs, line 681 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492#-LvBlYReA6aKUUVTkPpD:-LvDEKvbEUyn1ycvo0Ia:bb6un1j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7448f2dd2b93f4f3d4578dbb387889a43427609d/src/BloomExe/Book/BookStorage.cs#L681)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

OK, sure, we can use comical-1. I thought you wanted something more than that.
</blockquote></details>

Done
___
*[src/BloomExe/Book/BookStorage.cs, line 711 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492#-LvBkPgn2G7ynA7yTj89:-LvDEJQp4T1BLALCI_7s:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7448f2dd2b93f4f3d4578dbb387889a43427609d/src/BloomExe/Book/BookStorage.cs#L711)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
> Dismissed @hatton from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Book/BookStorage.cs, line 715 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492#-LvHgdJlAOsxuhEeqEuK:-LvHgdJlAOsxuhEeqEuL:b-ygx4cx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c43ed9e1461dd2063b9726d7ce510dd024d9d686/src/BloomExe/Book/BookStorage.cs#L715)):*
> ```Smalltalk
> 				result = JsonConvert.SerializeObject(requiredVersions);
> 			}
> 			watch.Stop();
> ```

Are you sure we want to leave Stopwatch code in release code in a section where we are already somewhat concerned about performance?
Perhaps wrap in `#if DEBUG`s?

This might be taking it too far, but you could even have a Debug.Fail if the time ever gets too high (whatever that means).

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Book/BookStorage.cs, line 715 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492#-LvHgdJlAOsxuhEeqEuK:-LvN06A50sMSx3WljXTv:bzdt8uw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c43ed9e1461dd2063b9726d7ce510dd024d9d686/src/BloomExe/Book/BookStorage.cs#L715)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Are you sure we want to leave Stopwatch code in release code in a section where we are already somewhat concerned about performance?
Perhaps wrap in `#if DEBUG`s?

This might be taking it too far, but you could even have a Debug.Fail if the time ever gets too high (whatever that means).
</blockquote></details>

Various sites say the time to start and stop a stopwatch is negligible and one actually measured it as less than a microsecond. So I'm disinclined to pay even the small complexity penalty of #if DEBUG. We could, of course, just take it out now it served its purpose.
I don't think Debug.Fail is going to help much since it's only likely to become problematic when working with large files, something devs rarely do.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3492)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
