### PR TITLE
BL-1187: user-modified css rules were not being applied to children

### PR DESCRIPTION
**Pull request by phillip-hopper**

### CODE REVIEW

**Comment by JohnThomson** [comment]
This will probably work for new styles, but it won't fix any existing books that have the problem. I'm not sure my proposal would, either, but if it works at all it would at least fix everything in the collection at once. Is there some reason I'm missing why this is a better way to solve it?

**Comment by phillip-hopper** [comment]
It looks like you added your comments to Jira at the same time I was creating this pull request.  Actually, I like the way you proposed better.

**Comment by JohnThomson** [comment]
I suppose one question is, apart from font-family, are there any other rules around that just use the :lang selector? And another would be, is there anything we set in the style dialog that is NOT inheritable?

**Comment by JohnThomson** [comment]
We agreed that it would be better to use the [lang] approach. So I'm closing this one without merging.

**Pull request closed without merging**
