### PR TITLE
Fix Unicode in languagesOfBook displaying incorrectly (BL-9972)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4482)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4482)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomExe/Book/BookData.cs, line 416 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4482#-MaTgcgX0I_08Aj7BY2w:-MaTgcgX0I_08Aj7BY2x:b1ioj1i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/14e9ea168120b15c710a051d48ebbaa65e3469bd/src/BloomExe/Book/BookData.cs#L416)):*
> ```Smalltalk
> 			if (!data.TextVariables.TryGetValue("languagesOfBook", out langData))
> 				return;
> 			var languagesXml = langData.TextAlternatives.GetExactAlternative("*");	// NOTE: DataSetElementValue.TextAlternatives contains more or less the InnerXml of the element, not the InnerText
> ```

It would be helpful give an example, and  to explain why a language name contains xml, (I would say *html*), and not just unicode. I still don't understand why this is true. Thx.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4482)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/Book/BookData.cs, line 416 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4482#-MaTgcgX0I_08Aj7BY2w:-MaTs6235Z7E3O6aI8D1:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/14e9ea168120b15c710a051d48ebbaa65e3469bd/src/BloomExe/Book/BookData.cs#L416)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

It would be helpful give an example, and  to explain why a language name contains xml, (I would say *html*), and not just unicode. I still don't understand why this is true. Thx.
</blockquote></details>

Done.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4482)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomExe/Book/BookData.cs, line 416 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4482#-MaTgcgX0I_08Aj7BY2w:-MaTz49G62FNsBmyEl2m:b-dfnzjq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/14e9ea168120b15c710a051d48ebbaa65e3469bd/src/BloomExe/Book/BookData.cs#L416)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thx. Can you add the example as well, please? This issue would make for a goo one.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4482)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/Book/BookData.cs, line 416 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4482#-MaTgcgX0I_08Aj7BY2w:-MaUHQmj-77W1RjQrEen:b-6599op) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/14e9ea168120b15c710a051d48ebbaa65e3469bd/src/BloomExe/Book/BookData.cs#L416)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Thx. Can you add the example as well, please? This issue would make for a goo one.
</blockquote></details>

Ok, added the example.
Regarding the XML/HTML... yeah that is confusing. It's very true that from one perspective it is HTML... but these classes are related to reading/writing data from/to an XML document.

As to why it can't just contain Unicode... I think it's actually OK if it contains just Unicode. But I guess the introduction of the XmlString class caused it to get written with the entity reference instead of a Unicode character. Either is valid IMO.
However, this function here just wasn't prepared to deal with any special XML markup. For example, if a language name happened to contain an ampersand, I suspect it would've been handled incorrectly even in 4.9.

**Pull request merged**
