### PR TITLE
Fix bug in marking phrases for audio splitting (BL-10569)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This fix is for Version5.1.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4818)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4818)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @StephenMcConnel)

___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/bloomSynphonyExtensions.js, line 284 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4818#-Mnfatj74hzld0RTeRcf:-Mnfatj74hzld0RTeRcg:b-aj9d1r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/733c1728b7178ff4fa20a2f87f06503259fd2dcf/src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/bloomSynphonyExtensions.js#L284)):*
> ```JavaScript
>                     // Check for phrase marker followed by whitespace to maintain "interphrase" spacing.
>                     // See https://issues.bloomlibrary.org/youtrack/issue/BL-10569.
>                     const leading = fragment.search(/\S|$/);
> ```

I got confused.
I initially thought this was any non-whitespace followed by phrase marker at the end of the string.
But pipe is a special character in regex, so I think this is actually non-whitespace or end of string.
So the idea is to find the index of the first non-whitespace character or end of string.
Then we push all the whitespace as an `isSpace` TextFragment and the rest as a `!isSpace` TextFragment.

So that I don't have to figure that out in the future, could you add a comment to that effect?

Also, does this mean we can end up with a whitespace TextFragment at the end? Is that ok? The comment on the if statement above indicates it is not.

Also, is there an existing unit test suite we can feasibly add to here?

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4818)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by andrew-polk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4818)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4818)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/bloomSynphonyExtensions.js, line 284 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4818#-Mnfatj74hzld0RTeRcf:-Mnfq64z9He77nHcSS7p:b483iof) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/733c1728b7178ff4fa20a2f87f06503259fd2dcf/src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/bloomSynphonyExtensions.js#L284)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I got confused.
I initially thought this was any non-whitespace followed by phrase marker at the end of the string.
But pipe is a special character in regex, so I think this is actually non-whitespace or end of string.
So the idea is to find the index of the first non-whitespace character or end of string.
Then we push all the whitespace as an `isSpace` TextFragment and the rest as a `!isSpace` TextFragment.

So that I don't have to figure that out in the future, could you add a comment to that effect?

Also, does this mean we can end up with a whitespace TextFragment at the end? Is that ok? The comment on the if statement above indicates it is not.

Also, is there an existing unit test suite we can feasibly add to here?
</blockquote></details>

I think the comment "check to avoid blank segments at the end" means to avoid an empty TextFragment, not one that contains only whitespace.  I changed "blank" to empty" in the comment.
I've greatly expanded the commentary in this section along the lines of your suggestion.
I added a test for splitting "sentences" with phrase markers.   I was a bit surprised there wasn't one already.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4818)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/bloomSynphonyExtensions.js, line 284 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4818#-Mnfatj74hzld0RTeRcf:-Mng4UYM-ir6M_D9gVN_:b-6mhyx0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/733c1728b7178ff4fa20a2f87f06503259fd2dcf/src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/bloomSynphonyExtensions.js#L284)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I think the comment "check to avoid blank segments at the end" means to avoid an empty TextFragment, not one that contains only whitespace.  I changed "blank" to empty" in the comment.
I've greatly expanded the commentary in this section along the lines of your suggestion.
I added a test for splitting "sentences" with phrase markers.   I was a bit surprised there wasn't one already.
</blockquote></details>

Great, thanks!

**Pull request merged**
