### PR TITLE
Fix Windows builds for SIL.Media having both 32- and 64-bit dlls

### PR DESCRIPTION
**Pull request by StephenMcConnel**
---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4121)

### CODE REVIEW

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4121)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomTests/BloomTests.csproj, line 381 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4121#-MOlzLEY0POl7GIEQDD9:-MOlzLEY0POl7GIEQDDA:bp7drno) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e1341727250a4e4a2c3b87c01d529b578b162e1a/src/BloomTests/BloomTests.csproj#L381)):*
> ```XML
>   </Target>
>   -->
>   <PropertyGroup>
> ```

Maybe a comment explaining your findings for posterity would be helpful. Same in the BloomExe version.
___
*[src/BloomTests/BloomTests.csproj, line 384 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4121#-MOlyKDm5F9caWDgCrbR:-MOlyKDn54Z_dWvtfo7I:b-4216qg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e1341727250a4e4a2c3b87c01d529b578b162e1a/src/BloomTests/BloomTests.csproj#L384)):*
> ```
> *.dll
> ```
Maybe *.*.  Since we're subsequently going to remove the directory, if there happened to be something else in there, that's useless too.
Same in the BloomExe version.
___
*[src/BloomTests/BloomTests.csproj, line 385 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4121#-MOlyRIl--Z7AutxhDqE:-MOlyRIl--Z7AutxhDqF:b3nl3ru) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e1341727250a4e4a2c3b87c01d529b578b162e1a/src/BloomTests/BloomTests.csproj#L385)):*
> ```XML
> copy /Y "$(SolutionDir)packages\SIL.Media.8.0.0-beta0225\build\lib\win-x86\irrKlang.NET4.dll" "$(OutDir)"
> del /F "$(OutDir)lib\win-x64\*.dll"
> rmdir "$(OutDir)lib\win-x64"
> ```

Hypothesis: I think it should be safe to delete output\lib\win-x86 as well? Since older versions of Bloom don't have this lib folder in there. Also from what I see in fuslogvw, it attempted to load the 64-bit version, which makes me think it probably never toucehd lib\win-x86\IrrKlang.NET.dll?

If true, same thing probably applies for lib\win-x64 in the 64-bit path.

Same in the BloomExe version.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4121)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel and @sujeffreyl)

___
*[src/BloomTests/BloomTests.csproj, line 385 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4121#-MOlyRIl--Z7AutxhDqE:-MOm0Wbs0UZIaFMa_8CP:bd1ewy2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e1341727250a4e4a2c3b87c01d529b578b162e1a/src/BloomTests/BloomTests.csproj#L385)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Hypothesis: I think it should be safe to delete output\lib\win-x86 as well? Since older versions of Bloom don't have this lib folder in there. Also from what I see in fuslogvw, it attempted to load the 64-bit version, which makes me think it probably never toucehd lib\win-x86\IrrKlang.NET.dll?

If true, same thing probably applies for lib\win-x64 in the 64-bit path.

Same in the BloomExe version.
</blockquote></details>

I think we need to retain the binary dlls for the proper architecture.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4121)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel and @sujeffreyl)

**Review by StephenMcConnel — COMMENTED** [review]
I totally changed the implementation to user msbuild targets and tasks without any raw DOS commands.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4121#-:-MOmUsu9-dfMWUM6xLWV:b1t9gzl)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomTests/BloomTests.csproj, line 381 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4121#-MOlzLEY0POl7GIEQDD9:-MOmUrly7atcVfcYsJ6k:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e1341727250a4e4a2c3b87c01d529b578b162e1a/src/BloomTests/BloomTests.csproj#L381)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Maybe a comment explaining your findings for posterity would be helpful. Same in the BloomExe version.
</blockquote></details>

Done.
___
*[src/BloomTests/BloomTests.csproj, line 384 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4121#-MOlyKDm5F9caWDgCrbR:-MOmUnsR88kfMgQ4y1eg:b-ctza9d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e1341727250a4e4a2c3b87c01d529b578b162e1a/src/BloomTests/BloomTests.csproj#L384)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> *.dll
> ```
Maybe *.*.  Since we're subsequently going to remove the directory, if there happened to be something else in there, that's useless too.
Same in the BloomExe version.
</blockquote></details>

changed to using *.* for files to remove.
___
*[src/BloomTests/BloomTests.csproj, line 385 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4121#-MOlyRIl--Z7AutxhDqE:-MOmUfGI68uawtHFETUA:b-o6r7lm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e1341727250a4e4a2c3b87c01d529b578b162e1a/src/BloomTests/BloomTests.csproj#L385)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I think we need to retain the binary dlls for the proper architecture.
</blockquote></details>

and I think they need to be copied to $(OutDir) as well.  But that means we can blow away the lib folder there.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4121)* status: all files reviewed, 3 unresolved discussions (waiting on @sujeffreyl)

**Review by sujeffreyl — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4121)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

___
*[src/BloomTests/BloomTests.csproj, line 385 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4121#-MOlyRIl--Z7AutxhDqE:-MOmhGGH9cCAepZ5xYD2:b-9gurbj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e1341727250a4e4a2c3b87c01d529b578b162e1a/src/BloomTests/BloomTests.csproj#L385)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

and I think they need to be copied to $(OutDir) as well.  But that means we can blow away the lib folder there.
</blockquote></details>

That's unfortunate that we need the extra files -> increases the size, but I guess you found that's the right thing to do, so oh well.

**Pull request merged**
