### PR TITLE
Prevent async changes from previous keystrokes (BL-10133)

### PR DESCRIPTION
**Pull request by JohnThomson**
Reviewer note: this will make most sense if you start with the changes to toolbox.ts.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
I won't pretend it isn't ugly (as you agree).
But I don't see anything actually wrong.

I agree it seems risky for 5.0. Definitely doesn't seem worth it if the problem isn't a regression.

Sorry about the spelling nits. I just figured you might as well fix them while making changes.

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-:-MdU8Dol3R4b33X-iMiV:b-loyzw2)* status: all files reviewed, 8 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MdU3LVM6gZNuMllqzxV:-MdU3LVM6gZNuMllqzxW:b-8lrtts) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/802ca05d080b037af01595a626aa020fd9b91695/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L40)):*
> ```
> updateMarkupAsyn
> ```
updateMarkupAsync
___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 856 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MdU3TFZ1Rayz8SQiPKe:-MdU3TFZ1Rayz8SQiPKf:br5h6yr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/802ca05d080b037af01595a626aa020fd9b91695/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L856)):*
> ```
> thisKeyDown
> ```
I think we could help ourselves with a different name.
currentKeyDownCount?

currentKeyDownIndex and rename keydownCounter to iKeyDown? 
Or actually maybe it is the other way around? 
thisKeyDown -> iKeyDown, keydownCounter -> keyDownCount?

Or maybe none of those are better than what you have.
___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 942 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MdU3PIg1Ns6B0GWqVjI:-MdU3PIg1Ns6B0GWqVjJ:b6zczf0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/802ca05d080b037af01595a626aa020fd9b91695/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L942)):*
> ```XML
>                         // (after the async work is finished).
>                         // To counteract that minor annoyance, we set the selection before async works gets kicked off.
>                         // (and then the code below sets it again after the async work finishes)
> ```

I think you said you wanted to update this comment?
___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 2383 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MdU4ue48SRvA8X0FtLO:-MdU4ue5AKa8tjoSefhN:b-1s86ra) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/802ca05d080b037af01595a626aa020fd9b91695/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L2383)):*
> ```
> excuted
> ```
executed
___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 2807 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MdU66vG4b2kydhUDgxb:-MdU66vG4b2kydhUDgxc:b20gjll) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/802ca05d080b037af01595a626aa020fd9b91695/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L2807)):*
> ```
> public makeAudioSentenceElementsTest(
> ```
Probably deserves a comment. Same for other test method below.
___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 2831 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MdU6CM-1pAfsl-aKa9_:-MdU6CM-1pAfsl-aKa9a:b7va29t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/802ca05d080b037af01595a626aa020fd9b91695/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L2831)):*
> ```
> exectued
> ```
executed
___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 2859 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MdU6oRh156OvkBND-vE:-MdU6oRh156OvkBND-vF:b-ya22f0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e4ef9dc3ede0e4fe577e98ce0b8aa55746a18af3/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L2859)):*
> ```
> return;
> ```
Maybe I'm just missing something, but I think keeping the same logic means calling `return result` here.
___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookSpec.ts, line 49 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MdU3IfE9pt1vmwwlxzZ:-MdU3IfF5zhfkyRLwGw5:b-t0k4o7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/802ca05d080b037af01595a626aa020fd9b91695/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookSpec.ts#L49)):*
> ```
> updateMarkup
> ```
updateMarkupAsync

**Review by JohnThomson — COMMENTED** [review]
No problem. Glad to have them caught.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-:-MdXMEZy2fhWazjqFjB8:b-yymjni)* status: 5 of 9 files reviewed, 8 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MdU3LVM6gZNuMllqzxV:-MdXEkZa6RS8ODTvmUYz:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/802ca05d080b037af01595a626aa020fd9b91695/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L40)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> updateMarkupAsyn
> ```
updateMarkupAsync
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 856 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MdU3TFZ1Rayz8SQiPKe:-MdXFTe56MrX_Ym_azww:bbbgblm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/802ca05d080b037af01595a626aa020fd9b91695/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L856)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> thisKeyDown
> ```
I think we could help ourselves with a different name.
currentKeyDownCount?

currentKeyDownIndex and rename keydownCounter to iKeyDown? 
Or actually maybe it is the other way around? 
thisKeyDown -> iKeyDown, keydownCounter -> keyDownCount?

Or maybe none of those are better than what you have.
</blockquote></details>

I think I improved it.
___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 942 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MdU3PIg1Ns6B0GWqVjI:-MdXGzzz2t7No7hONkaf:bhrtslf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/802ca05d080b037af01595a626aa020fd9b91695/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L942)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think you said you wanted to update this comment?
</blockquote></details>

Don't understand it...in fact I think it is wrong, and probably we don't need the selectBookmarks call, which never achieved its intended purpose according to the comment. But I'm not sure enough to remove it, so I just added an explanation.
___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 2383 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MdU4ue48SRvA8X0FtLO:-MdXHSM78M-FNen86yHX:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/802ca05d080b037af01595a626aa020fd9b91695/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L2383)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> excuted
> ```
executed
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 2807 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MdU66vG4b2kydhUDgxb:-MdXHr0k89S7wGhf3vbP:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/802ca05d080b037af01595a626aa020fd9b91695/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L2807)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> public makeAudioSentenceElementsTest(
> ```
Probably deserves a comment. Same for other test method below.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 2831 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MdU6CM-1pAfsl-aKa9_:-MdXHvbiDPPGfvkv5md8:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/802ca05d080b037af01595a626aa020fd9b91695/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L2831)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> exectued
> ```
executed
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, line 2859 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MdU6oRh156OvkBND-vE:-MdXKmrW7FQXr6aHT755:b-q7hmc0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e4ef9dc3ede0e4fe577e98ce0b8aa55746a18af3/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L2859)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> return;
> ```
Maybe I'm just missing something, but I think keeping the same logic means calling `return result` here.
</blockquote></details>

I now think the old logic was wrong. The intent was, in a very rare case, to start again from the beginning. But it didn't achieve that, because the return only returned from the current iteration of the "each" function. I have rewritten the logic so that it really does start over. It turned out to be easier to write a loop than use a recursive call to achieve that.
(It's also a concern that here we're modifying the DOM in a method that is not supposed to. I've commented on that, too.)
___
*[src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookSpec.ts, line 49 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MdU3IfE9pt1vmwwlxzZ:-MdXMAnXBESqBnz95o7R:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/802ca05d080b037af01595a626aa020fd9b91695/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookSpec.ts#L49)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> updateMarkup
> ```
updateMarkupAsync
</blockquote></details>

Done.

**Comment by JohnThomson** [comment]
Converted to draft as we're not ready to merge this. Steps planned:
1. Want Andrew to be satisfied
2. I'd like Jeffrey to also take a look, since he did most of the work on making various bits of the code async
3. Unless this turns out to be a regression from 4.9 or real users complain, we are planning to cherry pick this to master rather than merging into 5.0, once all reviews are complete. We think it is fairly rare for users to do major editing with the talking book tool active, so this change may not be worth the risk for a beta.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 937 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MeQnOjPENu-5-VTit6q:-MeQnOjPENu-5-VTit6r:b8rzhck) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2bbde2004e503dfd145d30e05c820ff5fea6e266/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L937)):*
> ```XML
>                     if (currentTool.isUpdateMarkupAsync()) {
>                         // Set the selection now before starting off asynchronous work
>                         // JT: Following is the comment from before we had updateMarkupAsync return the function that makes
> ```

Well, I'm not sure if every statement is 100% precise (especially perhaps the first part of "we've possibly already modified", but I'm pretty sure that this effect must have been visible in some form for me to go about adding this code.
I would suspect with the new model of the async work just getting an action, it may not be needed.

I would definitely be in favor of you testing it out without it and seeing if there is any visible change when typing or editing/deleting, especially when creating new sentences.
___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 960 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MeQpJjiCBfADzS6-cdE:-MeQpJjk7SUJsshQ5LLr:bcbxat3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2bbde2004e503dfd145d30e05c820ff5fea6e266/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L960)):*
> ```XML
>                         if (
>                             keydownEventCounter ==
>                             counterValueThatIdentifiesThisKeyDown
> ```

Another idea is a lock-based approach, but I guess you would have to block the typing updates from appearing until the lock is released and... idk, i'm not really liking this idea too much. Do you agree?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson and @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 960 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MeQpJjiCBfADzS6-cdE:-MeV1Hrh0QXwanBtorS4:bem7dmr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2bbde2004e503dfd145d30e05c820ff5fea6e266/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L960)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Another idea is a lock-based approach, but I guess you would have to block the typing updates from appearing until the lock is released and... idk, i'm not really liking this idea too much. Do you agree?
</blockquote></details>

Trying to actually delay the keydown events strikes me as problematic. We'd probably have to do the same with all the other keyboard events, too, or they'd get in the wrong sequence. Besides, I'm not clear what you mean by 'lock'. We're not talking threads here, just async events happening on one thread, but in an unpredictable order.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 937 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MeQnOjPENu-5-VTit6q:-MeV9Ayf8UIpE6H1H_xo:bapt5ct) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2bbde2004e503dfd145d30e05c820ff5fea6e266/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L937)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Well, I'm not sure if every statement is 100% precise (especially perhaps the first part of "we've possibly already modified", but I'm pretty sure that this effect must have been visible in some form for me to go about adding this code.
I would suspect with the new model of the async work just getting an action, it may not be needed.

I would definitely be in favor of you testing it out without it and seeing if there is any visible change when typing or editing/deleting, especially when creating new sentences.
</blockquote></details>

I went ahead and tested, and it definitely IS needed, though I still don't understand why, nor why ONLY for async updates. I modified the comment extensively but am still unhappy that we don't understand what is going on better.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571)* status: all files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 937 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MeQnOjPENu-5-VTit6q:-MehHaviEEpLoWzuV8WT:bf7ozon) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2bbde2004e503dfd145d30e05c820ff5fea6e266/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L937)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I went ahead and tested, and it definitely IS needed, though I still don't understand why, nor why ONLY for async updates. I modified the comment extensively but am still unhappy that we don't understand what is going on better.
</blockquote></details>

Given the info we know now, we can probably revise this to make this a lot shorter
___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 931 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MehGg6Z9wq4a6ES2Pp7:-MehGg6Z9wq4a6ES2Pp8:bljeoc4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a05ccfc42c6c3752ac9982ecd14a114921a70af7/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L931)):*
> ```XML
>                 // ckeditor is inserting tons of comments which are messing with our parsing
>                 // See http://issues.bloomlibrary.org/youtrack/issue/BL-4775
>                 removeCommentsFromEditableHtml(editableDiv);
> ```

This line is what is modifying the DOM.
___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 1006 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MehGjz40mRrKXAIjzA0:-MehGjz40mRrKXAIjzA1:bqfxg2g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a05ccfc42c6c3752ac9982ecd14a114921a70af7/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L1006)):*
> ```XML
> export function removeCommentsFromEditableHtml(editable: HTMLElement) {
>     // [\s\S] is a hack representing every character (including newline)
>     editable.innerHTML = editable.innerHTML.replace(//g, "");
> ```

If you only reset the innerHTML when needed (and the comments in earlier code say that it's usually only upon paste), then it doesn't cause the cursor to be reset to the front (yet).  I think that the old version of updateMarkup still does modify the DOM though, and causes the cursor to be reset... but your changes to delay the DOM edits until later, in combination with the below code, should cause both the DOM edit and the resetting the selection to happen without any awaiting inbetween them and make the experience a lot smoother. And would mean we can get rid of the code under your "Original Comment" section.

Of course, having that part still makes it more robust. Or only running that part if removeCommentsFromEditableHtml actually modified something. The fxn could return wasDomModified

I came up with this code:
const newHtml = editable.innerHTML.replace(//g, "");
    if (newHtml !== editable.innerHTML) {
        editable.innerHTML = newHtml;
    }

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson and @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 1006 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MehGjz40mRrKXAIjzA0:-MekUC1LD0NaXQGQC43i:b-u1md59) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a05ccfc42c6c3752ac9982ecd14a114921a70af7/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L1006)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

If you only reset the innerHTML when needed (and the comments in earlier code say that it's usually only upon paste), then it doesn't cause the cursor to be reset to the front (yet).  I think that the old version of updateMarkup still does modify the DOM though, and causes the cursor to be reset... but your changes to delay the DOM edits until later, in combination with the below code, should cause both the DOM edit and the resetting the selection to happen without any awaiting inbetween them and make the experience a lot smoother. And would mean we can get rid of the code under your "Original Comment" section.

Of course, having that part still makes it more robust. Or only running that part if removeCommentsFromEditableHtml actually modified something. The fxn could return wasDomModified

I came up with this code:
const newHtml = editable.innerHTML.replace(//g, "");
    if (newHtml !== editable.innerHTML) {
        editable.innerHTML = newHtml;
    }
</blockquote></details>

I'm guessing you meant to keep the original RE, but Reviewable decided to remove your 'comment'?

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 1006 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MehGjz40mRrKXAIjzA0:-Mekbbhw2lXMO_OJGdyd:b-kpgco6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a05ccfc42c6c3752ac9982ecd14a114921a70af7/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L1006)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm guessing you meant to keep the original RE, but Reviewable decided to remove your 'comment'?
</blockquote></details>

Ah, correct, no changes are needed to the regex.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 937 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MeQnOjPENu-5-VTit6q:-MekkwgX2TJdg6LUZkyu:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2bbde2004e503dfd145d30e05c820ff5fea6e266/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L937)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Given the info we know now, we can probably revise this to make this a lot shorter
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 931 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MehGg6Z9wq4a6ES2Pp7:-Mekktpg-OUSbfT4hyl0:b-4hvi0m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a05ccfc42c6c3752ac9982ecd14a114921a70af7/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L931)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

This line is what is modifying the DOM.
</blockquote></details>

Got it.
___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 1006 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MehGjz40mRrKXAIjzA0:-MekkzLX7mglBWPPnQIR:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a05ccfc42c6c3752ac9982ecd14a114921a70af7/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L1006)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Ah, correct, no changes are needed to the regex.
</blockquote></details>

Done.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 937 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-MeQnOjPENu-5-VTit6q:-MekldKp2dec5tDMHuPh:bnxgib1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2bbde2004e503dfd145d30e05c820ff5fea6e266/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L937)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ah, I like this so much more!

**Review by sujeffreyl — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by andrew-polk — APPROVED** [review]
I'm good with this moving forward other than it still targets 5.0.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4571#-:-MezG2mP3Z7T8QQDqkbA:b7t7skr)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Comment by JohnThomson** [comment]
Going to do this on master (not in 5.0)

**Pull request closed without merging**
