### PR TITLE
BL-4018 Add (partial) to Chinese Localization

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1396)

### CODE REVIEW

**Comment by hatton** [comment]
This isn't a result of your change, but this needs improvment. "(partial)" is not enough context for a translator. I had to get into the coded to figure out what it meant. So we need 3 changes:
1) change "(partial)" --> "(incomplete translation)"
2) change PublishTab.Upload.Partial --> PublishTab.Upload.IncompleteTranslation
3) The place where this is used, BloomLibraryPublishControl, should use l10nsharp's comment feature to explain what this is. "This is added after the language name, in order to indicate that some parts of the book have not been translated into this language yet."

**Comment by gmartin7** [comment]
I think this is one of the PRs that's supposed to stay on master (and not 3.8).

**Comment by andrew-polk** [comment]
:lgtm: 
I think this should go in Version3.8, and I don't see any reason to not include it in the initial beta. Very low risk.

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1396#-:-KagkUBXItVVjkoq_FkG:biv5gma)*

**Comment by andrew-polk** [comment]
I've changed the base to be Version3.8, but it looks like it needs to be rebased, @Gordon.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1396#-:-Kagna5G98I83UXupYxh:b-cqmlah)*

**Pull request merged**
