### PR TITLE
BL-2321 More unit tests for e-pub creation

### PR DESCRIPTION
**Pull request by JohnThomson**
[Review on Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/883)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Drastically refactored. Diff is pretty much useless...hopefully the whole file is now much more readable.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/883#-:-K4-3bqahx75Pes8YNAs:-730824708)*

**Comment by hatton** [comment]
Reviewed 1 of 4 files at r1, 2 of 4 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 827 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/883#-K4-Izh53ziBPjEAGurD:-K4-Izh53ziBPjEAGurE:-2072484862) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4d642d01db1f6fabd18ba9e82fb896bc005f85a/src/BloomExe/Publish/EpubMaker.cs#L827)):*
And in dozens of other places. I don't think code needs these kinds of elementary comments. However I image that you could change the signature of safeselectnodes.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 851 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/883#-K4-JhMN7928EPIqNC49:-K4-JhMN7928EPIqNC4A:-827770197) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4d642d01db1f6fabd18ba9e82fb896bc005f85a/src/BloomExe/Publish/EpubMaker.cs#L851)):*
I see why you're copying to its own list, but I think this wasted effort/complexity. The result of SafeSelectNodes is *already* a copy, XmlNodeList, safe from actions made in the DOM. Do tell me if I'm wrong about that.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/883)*

**Comment by hatton** [comment]
OK, a few small comments and we're good!

---

Reviewed 1 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/883#-:-K4-LOX36Ckhc8hka5PW:-1754771216)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 827 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/883#-K4-Izh53ziBPjEAGurD:-K4-VlpSFMOGeNWhPK7P:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4d642d01db1f6fabd18ba9e82fb896bc005f85a/src/BloomExe/Publish/EpubMaker.cs#L827)):*
Done.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 851 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/883#-K4-JhMN7928EPIqNC49:-K4-VD1curgqWzpZAE0l:-1594060087) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4d642d01db1f6fabd18ba9e82fb896bc005f85a/src/BloomExe/Publish/EpubMaker.cs#L851)):*
"The XmlNodeList object returned by this method will be valid while the underlying document remains unchanged. If the underlying document changes, unexpected results may be returned (no exception will be thrown)." (from MS doc on XmlNode.SelectNodes). Makes me think the 'object' may be a thin wrapper over some sort of enumerator with a pointer into the document?
Since I'm making a fairly radical and relevant change to the document (deleting nodes in the list) while iterating over it, the copy seems warranted.
But maybe not. I'm not finding stuff on google where people complain about these lists behaving unexpectedly.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/883)*

**Comment by hatton** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 851 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/883#-K4-JhMN7928EPIqNC49:-K4-gku7Cvfy2CGTxayS:-743157097) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f4d642d01db1f6fabd18ba9e82fb896bc005f85a/src/BloomExe/Publish/EpubMaker.cs#L851)):*
Well, what you found there is sure enough for me. Shall we change the "SafeSelectNodes" to do the case and the copy, so that it is actually "safe" :-)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/883)*

**Comment by hatton** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/883)*

**Pull request merged**
