### PR TITLE
BL-6465 fine tune rule for using N1 as primary in shell preview

### PR DESCRIPTION
**Pull request by JohnThomson**
This reverts commit 947947b9f1c1c3b45262481b8a83e04bf6d3ed30.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2872)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Requesting @hatton 's input. The situation is rare...showing a preview of a shell that is already translated into the collection's primary language (and also has text in it's N1 language). The problem is minor and harmless (book looks a little odd) and the cost of having the fix is non-trivial...scanning the whole book for text in the language. Not sure it's worth it.

**Review by hatton — COMMENTED** [review]
OK, John, if you think it's too costly, I'm ok with living with this bug (though one of us will probably notice it annually and re-report it, and then investigate it, which is also a bit costly).

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2872#-:-LRJcF_LASd29N66kP8M:byvt4b2)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @hatton)

**Review by JohnThomson — COMMENTED** [review]
I thought it about a toss-up. You've advanced some good reasons to go ahead with the fix. Maybe we should measure the time cost of doing the check on a typical book? Maybe there's a fix with a lower performance cost?

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2872#-:-LRL53sT-6Hoho8RoDIl:b-48sjnb)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by JohnThomson** [comment]
I checked and the extra code takes less than a millisecond to run on Vaccinations. So if the fix otherwise looks good I think we can go ahead and merge.

**Pull request merged**
