### PR TITLE
Handle Dropbox conflicts gracefully (BL-9706)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4309)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4309)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1263 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4309#-MWjLrWd7eyf_rFpgM4A:-MWjLrWd7eyf_rFpgM4B:b-7k20dt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1aaf02bb9ed67941131e802e6980b9e0fd136ef8/src/BloomExe/TeamCollection/TeamCollection.cs#L1263)):*
> ```Smalltalk
> 						// in changes while both were offline.
> 						ReportProgressAndLog(progress, "ResolvedDropboxConflict",
> 						"It seems that, despite our best efforts to prevent it, two members of your team have made conflicting edits. The resulting book \"{0}\" has been moved to Lost & Found.",
> ```

This implies more than I think we want to... it's not clear that it's all on us ("our") shoulders here.  Ultimately it's up to the team to have a system, and in some cases we can do it for them, but in other cases it might not be (e.g. various future options, internet vs. dropbox access, etc.) 

Would this be accurate?

"Two members of your team had the book <title> checked out at the same time, so now the Team Collection has two different versions of the book. Bloom has moved <joe's> copy to the Lost & Found."

I'm tempted to then tell them to go read about it in the helps. I don't suppose we have a way for providing a help link?
___
*[src/BloomTests/TeamCollection/SyncAtStartupTests.cs, line 335 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4309#-MWjNHuH99TSHD-_TCvC:-MWjNHuH99TSHD-_TCvD:b2aovlq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1aaf02bb9ed67941131e802e6980b9e0fd136ef8/src/BloomTests/TeamCollection/SyncAtStartupTests.cs#L335)):*
> ```Smalltalk
> 		public void SyncAtStartup_DropBoxConflictCreatedRemotely_GeneratesMessage()
> 		{
> 			AssertProgress("It seems that, despite our best efforts to prevent it, two members of your team have made conflicting edits. The resulting book \"{0}\" has been moved to Lost & Found.",
> ```

Seems fragile to be based on the actual full text, but whatever.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4309)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1263 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4309#-MWjLrWd7eyf_rFpgM4A:-MWjbnrR59_8Sl3xq3bW:b-gm5dil) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1aaf02bb9ed67941131e802e6980b9e0fd136ef8/src/BloomExe/TeamCollection/TeamCollection.cs#L1263)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This implies more than I think we want to... it's not clear that it's all on us ("our") shoulders here.  Ultimately it's up to the team to have a system, and in some cases we can do it for them, but in other cases it might not be (e.g. various future options, internet vs. dropbox access, etc.) 

Would this be accurate?

"Two members of your team had the book <title> checked out at the same time, so now the Team Collection has two different versions of the book. Bloom has moved <joe's> copy to the Lost & Found."

I'm tempted to then tell them to go read about it in the helps. I don't suppose we have a way for providing a help link?
</blockquote></details>

To know that it is Joe's copy, we have to successfully parse the DropBox file name however it may be localized. And even then DropBox's name for Joe may not be the one our TeamCollection normally uses. I'd feel much more confident if we could come up with a wording into which we can just insert the name of the file we moved. (It typically will include a person's name and the original title; I'd just be happier leaving it for the user to parse them out.) How about, "Two members of your team had a book checked out at the same time, so the Team Collection got two different versions of it. Bloom has moved <filename> to the Lost & Found."?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4309)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[src/BloomTests/TeamCollection/SyncAtStartupTests.cs, line 335 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4309#-MWjNHuH99TSHD-_TCvC:-MWk61sB5vPWzrmGCBRq:b-e8ycoq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1aaf02bb9ed67941131e802e6980b9e0fd136ef8/src/BloomTests/TeamCollection/SyncAtStartupTests.cs#L335)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Seems fragile to be based on the actual full text, but whatever.
</blockquote></details>

Is it better to just verify the L10nId?

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4309)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1263 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4309#-MWjLrWd7eyf_rFpgM4A:-MWk8Ctw6UXs7HYfotZd:b-7mhg5m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1aaf02bb9ed67941131e802e6980b9e0fd136ef8/src/BloomExe/TeamCollection/TeamCollection.cs#L1263)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

To know that it is Joe's copy, we have to successfully parse the DropBox file name however it may be localized. And even then DropBox's name for Joe may not be the one our TeamCollection normally uses. I'd feel much more confident if we could come up with a wording into which we can just insert the name of the file we moved. (It typically will include a person's name and the original title; I'd just be happier leaving it for the user to parse them out.) How about, "Two members of your team had a book checked out at the same time, so the Team Collection got two different versions of it. Bloom has moved <filename> to the Lost & Found."?
</blockquote></details>

As a user, I would be *appalled* at Bloom for not "bothering to tell me" who the winner was. In many cases I would know that Bob was the one working on that book, and that Joe must have been messing around.

We should think about what it would take for the book itself to have this record, so you just have to ask the book.
___
*[src/BloomTests/TeamCollection/SyncAtStartupTests.cs, line 335 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4309#-MWjNHuH99TSHD-_TCvC:-MWk8k_yBEUIXnLEfntE:b40ydmq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1aaf02bb9ed67941131e802e6980b9e0fd136ef8/src/BloomTests/TeamCollection/SyncAtStartupTests.cs#L335)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is it better to just verify the L10nId?
</blockquote></details>

yes, if you can

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4309)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1263 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4309#-MWjLrWd7eyf_rFpgM4A:-MWkVMpb1LVcl49qeAV5:b5xkkeo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1aaf02bb9ed67941131e802e6980b9e0fd136ef8/src/BloomExe/TeamCollection/TeamCollection.cs#L1263)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

As a user, I would be *appalled* at Bloom for not "bothering to tell me" who the winner was. In many cases I would know that Bob was the one working on that book, and that Joe must have been messing around.

We should think about what it would take for the book itself to have this record, so you just have to ask the book.
</blockquote></details>

Oh drat. Didn't notice how Markdown mangled my message. What I meant to suggest was
```
   Two members of your team had a book checked out at the same time, so the Team Collection got two different
   versions of it. Bloom has moved "<filename>" to the Lost & Found.
```
which would typically come out as something like 
```
   Two members of your team had a book checked out at the same time, so the Team Collection got two different
   versions of it. Bloom has moved "MY PUPPY (COLIN SUGGETT's conflicted copy 2021-03-18)" to the Lost & Found.
```
That gives a pretty good idea that Colin's version of "MY PUPPY" lost, but is much easier to do than taking apart "MY PUPPY (COLIN SUGGETT's conflicted copy 2021-03-18)" and figuring out that we should say "Colin's copy" (or even that the book is "MY PUPPY", since we're not sure that localization might not reorder things).

Once we have a full edit history of the book, we might be able to do better, though it's likely that there will be a conflicted version of the history file, too. So at that point IF we can reliably extract the original filename from the name of the 'conflicted copy' we'd know (supposing Joe won and Bob lost) that Joe and someone else made changes to the book; that Joe won; and we'd have whatever comment Joe wrote ("just playing around"...so why check in??). So at that point we can say 
``` 
   "Two members of your team had the book "My puppy" checked out. Joe made the change "just playing around". The other person's changes
   are saved in Lost and Found as  "MY PUPPY (BOB AUTHOR's conflicted copy 2021-03-18)"
```
But that requires the whole history mechanism, besides a way to parse multilingual Dropbox filenames and deduce at least the original name.

I suppose conceivably we could match up the conflicted copy of history and also know how Bob described his change, if we get really good at Dropbox conflict filenames. Of course, it gets more and more complicated...Bob and Joe might each have made several changes, and perhaps someone else did, too, on at least one branch...

I'd still be inclined for now to go for some wording that just inserts the conflict file name to provide the details, and consider doing better when either (a) we have history or (b) we determine that this problem actually occurs enough to be a nuisance.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4309)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[src/BloomTests/TeamCollection/SyncAtStartupTests.cs, line 335 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4309#-MWjNHuH99TSHD-_TCvC:-MWkaS838wv7iP_CyX13:b-8cv5s1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1aaf02bb9ed67941131e802e6980b9e0fd136ef8/src/BloomTests/TeamCollection/SyncAtStartupTests.cs#L335)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

yes, if you can
</blockquote></details>

Sigh. It works for one of the places we want to check the message turned up, but not the other. At least it should be fairly easy to repair the test if we change the message.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4309)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1263 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4309#-MWjLrWd7eyf_rFpgM4A:-MWz-hfj-uoH-nwamO76:b-z8085g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1aaf02bb9ed67941131e802e6980b9e0fd136ef8/src/BloomExe/TeamCollection/TeamCollection.cs#L1263)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Oh drat. Didn't notice how Markdown mangled my message. What I meant to suggest was
```
   Two members of your team had a book checked out at the same time, so the Team Collection got two different
   versions of it. Bloom has moved "<filename>" to the Lost & Found.
```
which would typically come out as something like 
```
   Two members of your team had a book checked out at the same time, so the Team Collection got two different
   versions of it. Bloom has moved "MY PUPPY (COLIN SUGGETT's conflicted copy 2021-03-18)" to the Lost & Found.
```
That gives a pretty good idea that Colin's version of "MY PUPPY" lost, but is much easier to do than taking apart "MY PUPPY (COLIN SUGGETT's conflicted copy 2021-03-18)" and figuring out that we should say "Colin's copy" (or even that the book is "MY PUPPY", since we're not sure that localization might not reorder things).

Once we have a full edit history of the book, we might be able to do better, though it's likely that there will be a conflicted version of the history file, too. So at that point IF we can reliably extract the original filename from the name of the 'conflicted copy' we'd know (supposing Joe won and Bob lost) that Joe and someone else made changes to the book; that Joe won; and we'd have whatever comment Joe wrote ("just playing around"...so why check in??). So at that point we can say 
``` 
   "Two members of your team had the book "My puppy" checked out. Joe made the change "just playing around". The other person's changes
   are saved in Lost and Found as  "MY PUPPY (BOB AUTHOR's conflicted copy 2021-03-18)"
```
But that requires the whole history mechanism, besides a way to parse multilingual Dropbox filenames and deduce at least the original name.

I suppose conceivably we could match up the conflicted copy of history and also know how Bob described his change, if we get really good at Dropbox conflict filenames. Of course, it gets more and more complicated...Bob and Joe might each have made several changes, and perhaps someone else did, too, on at least one branch...

I'd still be inclined for now to go for some wording that just inserts the conflict file name to provide the details, and consider doing better when either (a) we have history or (b) we determine that this problem actually occurs enough to be a nuisance.
</blockquote></details>

Based on our verbal discussion, I went ahead with the change I suggested.

**Pull request merged**
