### PR TITLE
Stop new Bloom after downloading if called from Bloom (BL-3822)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1218)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Program.cs, line 225 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1218#-KT6yMAQlSTC2dFRN-AJ:-KT6yMAQlSTC2dFRN-AK:bvu0n75) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e27f8f2e9328d16aa50bd18820b157c903ff7354/src/BloomExe/Program.cs#L225)):*
> ```Smalltalk
> 					if (IsBloomBookOrder(args))
> 					{
> 						skipReleaseToken = HandleDownload(args[0], skipReleaseToken);
> ```

There's a mess here, probably one that I created when extracting HandleDownload into a method. skipReleaseToken is always going to be false going in; the only way it ever becomes true is if this method returns true! So no reason to pass it as an argument to that method.
But it's weird for a HandleDownload method to return a boolean indicating whether to release the mutex token at program exit, and weird to use that to control whether to exit now.
Suggestion: move the UniqueToken.AcquireTokenQuietly(_mutexId) test from that method here, and make a new method for the else block of that test, and let HandleDownload stop after attempting the download; it doesn't need to return anything. Then here we just have
HandleDownload();
if (try to get the token)
    Run();
else
{
    skipReleaseToken = false; // didn't get it, don't release it
    ReportDownloadOutcome(); // new method made out of else
    return 0; // exit, another Bloom was already running. (keep your longer comment)
}
This keeps all the token-management and program-startup logic in this method, and lets HandleDownload just do what its name says.
Sorry to ask you to clean up what was probably my mess! But our goal is to leave the code better than it started, not to repair one kludge with another.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1218)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Program.cs, line 225 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1218#-KT6yMAQlSTC2dFRN-AJ:-KTVtP31IroJbAOVPinB:b-ctpu5r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e27f8f2e9328d16aa50bd18820b157c903ff7354/src/BloomExe/Program.cs#L225)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary>
> There's a mess here, probably one that I created when extracting HandleDownload into a method. skipReleaseToken is always going to be false going in; the only way it ever becomes true is if this method returns true! So no reason to pass it as an argument to that method.
> But it's weird for a HandleDownload method to return a boolean indicating whether to release the mutex token at program exit, and weird to use that to control whether to exit now.
> Suggestion: move the UniqueToken.AcquireTokenQuietly(_mutexId) test from that method here, and make a new method for the else block of that test, and let HandleDownload stop after attempting the download; it doesn't need to return anything. Then here we just have
> HandleDownload();
> if (try to get the token)
>     Run();
> else
> {
>     skipReleaseToken = false; // didn't get it, don't release it
>     ReportDownloadOutcome(); // new method made out of else
>     return 0; // exit, another Bloom was already running. (keep your longer comment)
> }
> This keeps all the token-management and program-startup logic in this method, and lets HandleDownload just do what its name says.
> Sorry to ask you to clean up what was probably my mess! But our goal is to leave the code better than it started, not to repair one kludge with another.
</details>
Done.  I cleaned up the code the way I thought made it simplest overall.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1218)*

**Comment by JohnThomson** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Program.cs, line 232 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1218#-KThwoO8At8GabkdsLiW:-KThwoO8At8GabkdsLiX:b7pkffs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/717c248c0485661a4faf338af49af59a1c394d94/src/BloomExe/Program.cs#L232)):*
> ```Smalltalk
> 					else
> 					{
> 						// Another instance of Bloom is running.  That shouldn't be.
> ```

This comment doesn't feel quite right. "Shouldn't be" suggests to me some sort of internal error, but this is just that the user tried to start up a second instance (other than for a special case like a download). More like "we don't allow more than one except for special purposes like download"

Aren't we supposed to tell the user why we're exiting? Maybe that happens elsewhere, since I don't see any sign that you removed it.

Anyway, with that one minor suggestion, looks like a great improvement. Fantastic that we don't need the flag at all any more!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1218)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Program.cs, line 232 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1218#-KThwoO8At8GabkdsLiW:-KUNbAfKsKatPPX4B0mU:b80929i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/717c248c0485661a4faf338af49af59a1c394d94/src/BloomExe/Program.cs#L232)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary>
> This comment doesn't feel quite right. "Shouldn't be" suggests to me some sort of internal error, but this is just that the user tried to start up a second instance (other than for a special case like a download). More like "we don't allow more than one except for special purposes like download"
> 
> Aren't we supposed to tell the user why we're exiting? Maybe that happens elsewhere, since I don't see any sign that you removed it.
> 
> Anyway, with that one minor suggestion, looks like a great improvement. Fantastic that we don't need the flag at all any more!
</details>
Done.  I've reworked the comment extensively.  The UniqueToken.AcquireToken() method pops up a message box to tell the user what is happening if it fails to acquire the token.  That's why the second argument exists ("Bloom").

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1218)*

**Pull request merged**
