### PR TITLE
BL-6100 improve Axios error reporting

### PR DESCRIPTION
**Pull request by JohnThomson**
I don't expect this to actually fix BL-6100, but it should improve error reports enough to give us a chance to solve it.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2535)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Did you say there are places where we still need to call axios directly because we are doing something specific with caught exceptions? If so, should we comment in those locations why we aren't using BloomApi?

---

Reviewed 30 of 31 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

---

*[src/BloomBrowserUI/utils/bloomApi.ts, line 51 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2535#-LG29jO66fXd1OFKOgfe:-LG29jO66fXd1OFKOgff:b-cannw5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/80da3a4dbb92bf35b8b14c516c7062d5dc707e91/src/BloomBrowserUI/utils/bloomApi.ts#L51)):*
> ```
> acceptResult
> ```
Probably being dense, but the naming here is not connecting for me. 
My mind keeps wanting to make this into a boolean, as in will we accept the result?
How about successCallback?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2535#-:-LG2BEYDDb0LXimzNEP5:bh9ajhu)*

**Comment by hatton** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

---

*[src/BloomBrowserUI/utils/bloomApi.ts, line 51 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2535#-LG29jO66fXd1OFKOgfe:-LG2D56D4gREpC5eUWL5:b-o56bg6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/80da3a4dbb92bf35b8b14c516c7062d5dc707e91/src/BloomBrowserUI/utils/bloomApi.ts#L51)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> acceptResult
> ```
Probably being dense, but the naming here is not connecting for me. 
My mind keeps wanting to make this into a boolean, as in will we accept the result?
How about successCallback?
</blockquote></details>

Maybe ``successCallback`` ?

---

*[src/BloomBrowserUI/utils/bloomApi.ts, line 55 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2535#-LG2DCn66_5SJhqXRk86:-LG2DCn66_5SJhqXRk87:b-eyhf47) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/80da3a4dbb92bf35b8b14c516c7062d5dc707e91/src/BloomBrowserUI/utils/bloomApi.ts#L55)):*
> ```XML
>             BloomApi.wrapAxios(axios.get("/bloom/" + urlSuffix).then(acceptResult));
>         } else {
>             BloomApi.wrapAxios(axios.get("/bloom/" + urlSuffix));
> ```

Does this encourage abusing ``get`` by allowing side-effect `get` calls? In other words, why would we use ``get`` if we didn't have a callback to receive the result?

---

*[src/BloomBrowserUI/utils/bloomApi.ts, line 60 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2535#-LG2D_Ck5Ombs_VGmFSm:-LG2D_Ck5Ombs_VGmFSn:bdrg89y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/80da3a4dbb92bf35b8b14c516c7062d5dc707e91/src/BloomBrowserUI/utils/bloomApi.ts#L60)):*
> ```XML
> 
>     // This method is used to get a result from Bloom, passing paramaters to the nested axios call.
>     public static getP(urlSuffix: string, config: AxiosRequestConfig, acceptResult: (r: AxiosResponse) => void) {
> ```

If we want this, let's give it a human readable name, like getWithConfig :-)

I suppose you're doing this because you don't want an optional config to follow the callback?

One approach to consider would be to use the old C++ "Ex" convention, and combine all of these that take optional parameters, as in

public static getEx(urlSuffix: string, config?: AxiosRequestConfig, data?: any, callback...

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2535)*

**Comment by andrew-polk** [comment]
Reviewed 7 of 35 files at r3.
Review status: 9 of 37 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2535)*

**Comment by andrew-polk** [comment]
Reviewed 28 of 35 files at r3.
Review status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

---

*[src/BloomBrowserUI/bookEdit/js/bloomVideo.ts, line 33 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2535#-LG2L61NE-djviLqtSJP:-LG2L61NE-djviLqtSJQ:b-mbnw4r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/eeb5aaee4836655e4d60ff8b67a3ab8e608bad67/src/BloomBrowserUI/bookEdit/js/bloomVideo.ts#L33)):*
> ```XML
> 
> export function SetupVideoEditing(container) {
>     // sticking with axios because there's already a catch...though not obviously better than
> ```

If I had to guess, I would assume this was just put here for the developer's debugging purposes. It is new enough code, I assume we can safely change to using BloomApi. Thoughts?

Though... I guess the difference is this swallows the error. So I guess we better leave it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2535)*

**Comment by JohnThomson** [comment]
Done.

---

Review status: 27 of 37 files reviewed, 2 unresolved discussions (waiting on @andrew-polk, @JohnThomson, and @hatton)

---

*[src/BloomBrowserUI/bookEdit/js/bloomVideo.ts, line 33 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2535#-LG2L61NE-djviLqtSJP:-LG2QoX2-DAwLkeYrwAa:b20wrt7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/eeb5aaee4836655e4d60ff8b67a3ab8e608bad67/src/BloomBrowserUI/bookEdit/js/bloomVideo.ts#L33)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If I had to guess, I would assume this was just put here for the developer's debugging purposes. It is new enough code, I assume we can safely change to using BloomApi. Thoughts?

Though... I guess the difference is this swallows the error. So I guess we better leave it.
</blockquote></details>

On the contrary. There's no reason for this to fail. I should have looked more closely. If we don't get a response to whether enterprise is enabled, that's a bug, and we want a big, noisy report. I changed it.

---

*[src/BloomBrowserUI/utils/bloomApi.ts, line 51 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2535#-LG29jO66fXd1OFKOgfe:-LG2KQlbBPcvlAp21g1k:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/80da3a4dbb92bf35b8b14c516c7062d5dc707e91/src/BloomBrowserUI/utils/bloomApi.ts#L51)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Maybe ``successCallback`` ?
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/utils/bloomApi.ts, line 55 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2535#-LG2DCn66_5SJhqXRk86:-LG2Pfz-88iPXIiPVN8Q:bchlhk9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/80da3a4dbb92bf35b8b14c516c7062d5dc707e91/src/BloomBrowserUI/utils/bloomApi.ts#L55)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Does this encourage abusing ``get`` by allowing side-effect `get` calls? In other words, why would we use ``get`` if we didn't have a callback to receive the result?
</blockquote></details>

Removed (and fixed one place we were abusing it)

---

*[src/BloomBrowserUI/utils/bloomApi.ts, line 60 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2535#-LG2D_Ck5Ombs_VGmFSm:-LG2Pk-p7CinCioFeGIR:bire3na) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/80da3a4dbb92bf35b8b14c516c7062d5dc707e91/src/BloomBrowserUI/utils/bloomApi.ts#L60)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

If we want this, let's give it a human readable name, like getWithConfig :-)

I suppose you're doing this because you don't want an optional config to follow the callback?

One approach to consider would be to use the old C++ "Ex" convention, and combine all of these that take optional parameters, as in

public static getEx(urlSuffix: string, config?: AxiosRequestConfig, data?: any, callback...
</blockquote></details>

Done. (getWithConfig, postData, postDataWithConfig)

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2535#-:-LG2FEYcC6vlacvM_-KU:b-896fix)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r4.
Review status: all files reviewed, 2 unresolved discussions (waiting on @hatton)

---



*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2535#-:-LG2_Twp8VGlXavlse54:bnfp4nl)*

**Pull request merged**
