### PR TITLE
BL-4235 Specify paragraph spacing proportionally

### PR DESCRIPTION
**Pull request by JohnThomson**
Also fixes a problem where a normal-style indent could
not be overridden and another where duplicate style rules
were being made if the style name included caps.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1495)

### CODE REVIEW

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1495#-:-Kd1zoji2VKJnITGaNEm:bnfp4nl)*

**Comment by JohnThomson** [comment]
Don't merge yet! It's getting the case wrong when it makes new rules.

**Comment by JohnThomson** [comment]
OK, I think we're good now.

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1495#-:-Kd2JGV-tr8Sealsxqd_:bnfp4nl)*

**Pull request merged**
