### PR TITLE
Improvements to new Collection tab

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4913)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
I've only made it through some of the easier changes and not even all of those so far, but I'll publish what I have so far in case you want to start looking at it.

> Reviewed 19 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4913#-:-MtP0HsT2vnsGrZB5EaY:b-k1ayph)* status: 19 of 35 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomBrowserUI/react_components/delay.tsx, line 5 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4913#-MtOfeo2-r7uJUn-Cls8:-MtOfeo2-r7uJUn-Cls9:b22qxrk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e7a7256511a5296aac97b5a5a9f70e747ddfc441/src/BloomBrowserUI/react_components/delay.tsx#L5)):*
> ```XML
> // This class shows nothing for waitBeforeShow ms, then its children.
> // Thanks to goulashsoup on StackOverflow.
> class Delayed extends React.Component<
> ```

Could probably use a more descriptive name, like ShowAfterDelay or DelayedDisplay or DelayedVisibility or similar.
Or maybe the component should be WaitBeforeShow and the prop should be time or millis?
(and a file name to match)



_Code quote:_
```XML
Delayed
```
___
*[src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs, line 933 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4913#-MtOi41q1-ix3XrSYHOI:-MtOi41q1-ix3XrSYHOJ:be3fu7v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e7a7256511a5296aac97b5a5a9f70e747ddfc441/src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs#L933)):*
> ```Smalltalk
> 			this._newCollectionCheckbox.Size = new System.Drawing.Size(143, 23);
> 			this._newCollectionCheckbox.TabIndex = 12;
> 			this._newCollectionCheckbox.Text = "New Collection Tab";
> ```

I thought we were going to change this to something else.
Better to do it now because when we merge, it will go into Crowdin... except I don't see any changes to Bloom.xlf.



_Code quote:_
```Smalltalk
New Collection Tab
```

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 13 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4913)* status: 32 of 35 files reviewed, 6 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomBrowserUI/collectionsTab/BookButton.tsx, line 201 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4913#-MtPgBzo-DDTelYhp3_C:-MtPgBzo-DDTelYhp3_D:bfrc8t9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e7a7256511a5296aac97b5a5a9f70e747ddfc441/src/BloomBrowserUI/collectionsTab/BookButton.tsx#L201)):*
> ```XML
>     const downSize = 14; // size of down-arrow icon
> 
>     const setAdjustedContextMenuPoint = (x: number, y: number) => {
> ```

I think this deserves a comment



_Code quote:_
```XML
setAdjustedContextMenuPoint
```
___
*[src/BloomBrowserUI/collectionsTab/bookSelectionManager.tsx, line 103 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4913#-MtPckOx-H3pZJ-b11tJ:-MtPckOy5GLd9xwRmqdL:b2nie02) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e7a7256511a5296aac97b5a5a9f70e747ddfc441/src/BloomBrowserUI/collectionsTab/bookSelectionManager.tsx#L103)):*
> ```XML
> 
>     // You should generally avoid using this in render methods, since nothing will
>     // cause a re-render when it changes. It is intended for us in click handlers
> ```

use



_Code quote:_
```XML
us
```
___
*[src/BloomExe/Workspace/WorkspaceView.cs, line 269 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4913#-MtP_rGKDI3Bw-6TeTyI:-MtP_rGKDI3Bw-6TeTyJ:bl9rc15) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e7a7256511a5296aac97b5a5a9f70e747ddfc441/src/BloomExe/Workspace/WorkspaceView.cs#L269)):*
> ```Smalltalk
> 
> 		/// <summary>
> 		/// If this gets complex, we can create a WorkspaceApi, but for just one command it's not worth it, I think.
> ```

I disagree because as we move toward a single browser, WorkspaceView will go away but this handler will remain, so we'll need to do it eventually (if I understand correctly).



_Code quote:_
```Smalltalk
for just one command it's not worth it, I think
```
___
*[src/BloomExe/Workspace/WorkspaceView.Designer.cs, line 1 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4913#-MtPZrvC5pgqL0n-syo4:-MtPZrvC5pgqL0n-syo5:byka7kx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e7a7256511a5296aac97b5a5a9f70e747ddfc441/src/BloomExe/Workspace/WorkspaceView.Designer.cs#L1)):*
> ```Smalltalk
> #define SHOW_REACT_COLLECTION_TAB
> ```

As we discussed, we think we are ready to go ahead and remove this (here and in WorkspaceView.cs)

**Review by andrew-polk — COMMENTED** [review]
Finished my review now. Admittedly, I didn't look at everything as closely as I might have if JH hadn't already seen it.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4913#-:-MtPgOBPDrRBhyM7QLCq:b-jyr4u6)* status: 32 of 35 files reviewed, 6 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4913)* status: 24 of 38 files reviewed, 6 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/collectionsTab/BookButton.tsx, line 201 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4913#-MtPgBzo-DDTelYhp3_C:-MtiTpkI-jKf64DaVgXT:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e7a7256511a5296aac97b5a5a9f70e747ddfc441/src/BloomBrowserUI/collectionsTab/BookButton.tsx#L201)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this deserves a comment
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/collectionsTab/bookSelectionManager.tsx, line 103 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4913#-MtPckOx-H3pZJ-b11tJ:-MtiTyEQ81_zLlsEFsfr:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e7a7256511a5296aac97b5a5a9f70e747ddfc441/src/BloomBrowserUI/collectionsTab/bookSelectionManager.tsx#L103)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

use
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/react_components/delay.tsx, line 5 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4913#-MtOfeo2-r7uJUn-Cls8:-MtiU_hbEQ4T-PpggWSL:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e7a7256511a5296aac97b5a5a9f70e747ddfc441/src/BloomBrowserUI/react_components/delay.tsx#L5)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Could probably use a more descriptive name, like ShowAfterDelay or DelayedDisplay or DelayedVisibility or similar.
Or maybe the component should be WaitBeforeShow and the prop should be time or millis?
(and a file name to match)
</blockquote></details>

Done.
___
*[src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs, line 933 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4913#-MtOi41q1-ix3XrSYHOI:-MtiUcJk2MgWLUSWP4bI:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e7a7256511a5296aac97b5a5a9f70e747ddfc441/src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs#L933)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I thought we were going to change this to something else.
Better to do it now because when we merge, it will go into Crowdin... except I don't see any changes to Bloom.xlf.
</blockquote></details>

Done.
___
*[src/BloomExe/Workspace/WorkspaceView.cs, line 269 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4913#-MtP_rGKDI3Bw-6TeTyI:-MtiUhfu4GfOeDHs-AS7:b7dorey) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e7a7256511a5296aac97b5a5a9f70e747ddfc441/src/BloomExe/Workspace/WorkspaceView.cs#L269)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I disagree because as we move toward a single browser, WorkspaceView will go away but this handler will remain, so we'll need to do it eventually (if I understand correctly).
</blockquote></details>

Yes, JohnH said the same, though for a different reason. I'm not entirely convinced, because the whole implementation of this is (necessarily, I think) in WorkspaceView, so if that goes away we'll have to rethink this anyway. But I did it.
___
*[src/BloomExe/Workspace/WorkspaceView.Designer.cs, line 1 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4913#-MtPZrvC5pgqL0n-syo4:-MtilA347trGUampzA1U:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e7a7256511a5296aac97b5a5a9f70e747ddfc441/src/BloomExe/Workspace/WorkspaceView.Designer.cs#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

As we discussed, we think we are ready to go ahead and remove this (here and in WorkspaceView.cs)
</blockquote></details>

Done.



_Code quote:_
```Smalltalk
SHOW_REACT_COLLECTION_TAB
```

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 35 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4913)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/react_components/delay.tsx, line 5 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4913#-MtOfeo2-r7uJUn-Cls8:-MtiwmlkBQ-PIw1KPc6E:b-54rb5l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e7a7256511a5296aac97b5a5a9f70e747ddfc441/src/BloomBrowserUI/react_components/delay.tsx#L5)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry; I didn't communicate clearly. I was suggesting we change the component name such that when seeing it where it is used, it is more clear what the component is doing.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4913)* status: 36 of 38 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/react_components/delay.tsx, line 5 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4913#-MtOfeo2-r7uJUn-Cls8:-Mtj9wDw60mNX7DxAIc5:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e7a7256511a5296aac97b5a5a9f70e747ddfc441/src/BloomBrowserUI/react_components/delay.tsx#L5)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; I didn't communicate clearly. I was suggesting we change the component name such that when seeing it where it is used, it is more clear what the component is doing.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4913)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
