### PR TITLE
Add page-list nav element to epub navigation page (BL-5891)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2364)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/BloomTests/Publish/ExportEpubTests.cs, line 437 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2364#-LB78m6j9g9nHIpdFEgZ:-LB78m6j9g9nHIpdFEg_:b-bf3ywr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f47202adc86b434ee4ed362770c9867603d504f1/src/BloomTests/Publish/ExportEpubTests.cs#L437)):*
> ```Smalltalk
> 			AssertThatXmlIn.String(currentPage).HasAtLeastOneMatchForXpath("//div[contains(@class, 'theEndPage')]");
> 			var navPageData = CheckNavPage();
> 			AssertThatXmlIn.String(navPageData).HasAtLeastOneMatchForXpath(
> ```

I don't like using "AtLeastOne" if our expectation is exactly one. Let's use HasSpecifiedNumberOfMatchesForXpath instead where applicable.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2364)*

**Comment by StephenMcConnel** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomTests/Publish/ExportEpubTests.cs, line 437 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2364#-LB78m6j9g9nHIpdFEgZ:-LB7GJg572hPGy2-G-EU:ba7ik3u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f47202adc86b434ee4ed362770c9867603d504f1/src/BloomTests/Publish/ExportEpubTests.cs#L437)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't like using "AtLeastOne" if our expectation is exactly one. Let's use HasSpecifiedNumberOfMatchesForXpath instead where applicable.
</blockquote></details>

Done.  I actually had to implement the variant of that method to take a NameSpaceManager.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2364)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/BloomTests/FluentAssertXml.cs, line 171 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2364#-LB7H8_X0tLgl6ykN9I_:-LB7H8_X0tLgl6ykN9Ia:bbshlc8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e89a23fc9bfd4ac1b059ae00620746397f3d291e/src/BloomTests/FluentAssertXml.cs#L171)):*
> ```Smalltalk
> 		}
> 
> 		public void HasSpecifiedNumberOfMatchesForXpath(string xpath, XmlNamespaceManager nameSpaceManager, int count)
> ```

Too much duplication between this and the default namespace version.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2364)*

**Comment by StephenMcConnel** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomTests/FluentAssertXml.cs, line 171 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2364#-LB7H8_X0tLgl6ykN9I_:-LB7SJlR40aqnWYoEnPz:bjkr142) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e89a23fc9bfd4ac1b059ae00620746397f3d291e/src/BloomTests/FluentAssertXml.cs#L171)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Too much duplication between this and the default namespace version.
</blockquote></details>

I've removed as much duplication as possible in these two methods.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2364)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomTests/FluentAssertXml.cs, line 171 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2364#-LB7H8_X0tLgl6ykN9I_:-LB7VES650GGW9aG9o95:b-snlwdd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e89a23fc9bfd4ac1b059ae00620746397f3d291e/src/BloomTests/FluentAssertXml.cs#L171)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I've removed as much duplication as possible in these two methods.
</blockquote></details>

Not how I would have done it, but that works, too.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2364#-:-LB7VJzw1gn7fcSlLg6R:bnfp4nl)*

**Pull request merged**
