### PR TITLE
Increase memory limit before warning user

### PR DESCRIPTION
**Pull request by StephenMcConnel**
With Bloom now large address aware on Windows, a higher limit seems
quite reasonable.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294)

### CODE REVIEW

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/Edit/EditingModel.cs, line 655 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294#-MWAgs7G-mqmrU2FVrFy:-MWAgs7HErFxwVfc7GZj:b2nldpp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c5510120d4f08490c79c511207329644cf936ec1/src/BloomExe/Edit/EditingModel.cs#L655)):*
> ```
> 					// Bloom is "Large Address Aware", so we won't complain until we're using about half
> 					// (or two/thirds?) of the possible maximum for 32-bit systems.
> ```
This comment / section of code is too cryptic IMO.

One way to resolve it could be to split the safeLimit ternary into 3 lines, and make this comment at the end of the 32-bit branch line.

Also, I think we should just leave the two/thirds part out (Only relevant with the obscure setting, and let's just ignore that setting completely), and say just that the 2E9 number is "half of the possible max for a 32-bit LAA process on 64-bit Windows"

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/Edit/EditingModel.cs, line 662 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294#-MWAnvAj56-wV2l4qGh8:-MWAnvAj56-wV2l4qGh9:be6cyme) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c5510120d4f08490c79c511207329644cf936ec1/src/BloomExe/Edit/EditingModel.cs#L662)):*
> ```
> These strings are in the Palaso xliff files.
> ```
Have you tested that it successfully finds the translations when simply calling GetString?
I can't remember how this works with different sources.
___
*[src/BloomExe/Edit/EditingModel.cs, line 669 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294#-MWAnpyYENL6Hwg1QRNS:-MWAnpyZ98l7kLvJ_KQn:bp98ff4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c5510120d4f08490c79c511207329644cf936ec1/src/BloomExe/Edit/EditingModel.cs#L669)):*
> ```Smalltalk
> 							MessageBoxIcon.Warning);
> 					}
> 				}
> ```

All these guts want to live in a different file.

Also deserves a comment about why we don't want to just use the boolean parameter to use libpalaso's check and warning code.

**Comment by andrew-polk** [comment]
___
*[src/BloomExe/Edit/EditingModel.cs, line 669 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294#-MWAnpyYENL6Hwg1QRNS:-MWAp8isBBk4EhaXI-Jq:b2uvgjf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c5510120d4f08490c79c511207329644cf936ec1/src/BloomExe/Edit/EditingModel.cs#L669)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

All these guts want to live in a different file.

Also deserves a comment about why we don't want to just use the boolean parameter to use libpalaso's check and warning code.
</blockquote></details>

On the other hand, when we were talking about removing this from libpalaso, was it just the user interaction or the whole class? I kind of thought we were talking about the whole class.

**Comment by andrew-polk** [comment]
___
*[src/BloomExe/Edit/EditingModel.cs, line 669 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294#-MWAnpyYENL6Hwg1QRNS:-MWAqRaY-AGSwuIHIRl3:b7d9xwa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c5510120d4f08490c79c511207329644cf936ec1/src/BloomExe/Edit/EditingModel.cs#L669)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

On the other hand, when we were talking about removing this from libpalaso, was it just the user interaction or the whole class? I kind of thought we were talking about the whole class.
</blockquote></details>

On the other hand, it still seems generally useful to me.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @andrew-polk, @StephenMcConnel, and @sujeffreyl)

___
*[src/BloomExe/Edit/EditingModel.cs, line 655 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294#-MWAgs7G-mqmrU2FVrFy:-MWAqLV51w_B5T5Ukxer:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c5510120d4f08490c79c511207329644cf936ec1/src/BloomExe/Edit/EditingModel.cs#L655)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> 					// Bloom is "Large Address Aware", so we won't complain until we're using about half
> 					// (or two/thirds?) of the possible maximum for 32-bit systems.
> ```
This comment / section of code is too cryptic IMO.

One way to resolve it could be to split the safeLimit ternary into 3 lines, and make this comment at the end of the 32-bit branch line.

Also, I think we should just leave the two/thirds part out (Only relevant with the obscure setting, and let's just ignore that setting completely), and say just that the 2E9 number is "half of the possible max for a 32-bit LAA process on 64-bit Windows"
</blockquote></details>

Done.
___
*[src/BloomExe/Edit/EditingModel.cs, line 669 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294#-MWAnpyYENL6Hwg1QRNS:-MWAq3JBBARpfC79wrzI:b-tac9xq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c5510120d4f08490c79c511207329644cf936ec1/src/BloomExe/Edit/EditingModel.cs#L669)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

On the other hand, when we were talking about removing this from libpalaso, was it just the user interaction or the whole class? I kind of thought we were talking about the whole class.
</blockquote></details>

I could copy the whole class over, I suppose.  I've posted queries on Slack to find out if anyone else is using the class.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk, @StephenMcConnel, and @sujeffreyl)

**Review by sujeffreyl — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/Edit/EditingModel.cs, line 662 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294#-MWAnvAj56-wV2l4qGh8:-MWB3vog29G_TW5qXsgP:b-ojb1km) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c5510120d4f08490c79c511207329644cf936ec1/src/BloomExe/Edit/EditingModel.cs#L662)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> These strings are in the Palaso xliff files.
> ```
Have you tested that it successfully finds the translations when simply calling GetString?
I can't remember how this works with different sources.
</blockquote></details>

The different sources get merged together.  The source doesn't makes any difference.  Lookup is by the id string alone.
___
*[src/BloomExe/Edit/EditingModel.cs, line 669 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294#-MWAnpyYENL6Hwg1QRNS:-MWBSK4JA9An1Mf2mmcl:bnmabgm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c5510120d4f08490c79c511207329644cf936ec1/src/BloomExe/Edit/EditingModel.cs#L669)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I could copy the whole class over, I suppose.  I've posted queries on Slack to find out if anyone else is using the class.
</blockquote></details>

I decided to copy over the class and modify the setting of "safelimit" there.  It feels a lot less kludgy to me that way.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @StephenMcConnel)

___
*[src/BloomExe/Utils/MemoryManagement.cs, line 20 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294#-MWBV7Vz-k2SQ0RLE6Ew:-MWBV7Vz-k2SQ0RLE6Ex:b9j8hkj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/adef7ac4cad48736c82ced73c2b656263da9e5d1/src/BloomExe/Utils/MemoryManagement.cs#L20)):*
> ```Smalltalk
> 	/// This class contains methods useful for logging and warning the user about possible problems
> 	/// of memory shortage.
> 	/// </summary>
> ```

Probably worth a note here to our future selves explaining why this is nearly duplicated in libpalaso.
i.e. it was there but we copied it here rather than change it there because no one else was using it and the safelimit calculation is not universal or some such.
___
*[src/BloomExe/Utils/MemoryManagement.cs, line 109 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294#-MWBUjox8WRGMVeHTZD5:-MWBUjox8WRGMVeHTZD6:bqmba1i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/adef7ac4cad48736c82ced73c2b656263da9e5d1/src/BloomExe/Utils/MemoryManagement.cs#L109)):*
> ```Smalltalk
> 					1000000000L);
> 			// We also don't want Bloom to totally overwhelm the available physical memory.
> 			safelimit = Math.Min(safelimit, (long)memInfo.TotalPhysicalMemory);
> ```

I'm making the assumption that the calculation of safelimit is the only change you made from the original libpalaso code. If that is incorrect, please let me know so I can review more closely.
___
*[src/BloomExe/Utils/MemoryManagement.cs, line 125 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294#-MWBUyt669TF6_v4vsYg:-MWBUyt669TF6_v4vsYh:b-v0dhdu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/adef7ac4cad48736c82ced73c2b656263da9e5d1/src/BloomExe/Utils/MemoryManagement.cs#L125)):*
> ```Smalltalk
> 				var warning = LocalizationManager.GetString("MemoryWarning",
> 					"Unfortunately, {0} is starting to get short of memory, and may soon slow down or experience other problems. We recommend that you quit and restart it when convenient.");
> 				var caption = LocalizationManager.GetString("Warning", "Warning");
> ```

Probably still worth having the comment you had which states these strings are in the Palaso xliff

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/Utils/MemoryManagement.cs, line 20 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294#-MWBV7Vz-k2SQ0RLE6Ew:-MWBYftt3emtpnZ3lEUc:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/adef7ac4cad48736c82ced73c2b656263da9e5d1/src/BloomExe/Utils/MemoryManagement.cs#L20)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Probably worth a note here to our future selves explaining why this is nearly duplicated in libpalaso.
i.e. it was there but we copied it here rather than change it there because no one else was using it and the safelimit calculation is not universal or some such.
</blockquote></details>

Done.
___
*[src/BloomExe/Utils/MemoryManagement.cs, line 109 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294#-MWBUjox8WRGMVeHTZD5:-MWBYh4V99OivztQHkKZ:b-muyl2p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/adef7ac4cad48736c82ced73c2b656263da9e5d1/src/BloomExe/Utils/MemoryManagement.cs#L109)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm making the assumption that the calculation of safelimit is the only change you made from the original libpalaso code. If that is incorrect, please let me know so I can review more closely.
</blockquote></details>

That's a good assumption.  :-)
___
*[src/BloomExe/Utils/MemoryManagement.cs, line 125 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294#-MWBUyt669TF6_v4vsYg:-MWBYnh10JKAfXH6d0D4:bj8q9c9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/adef7ac4cad48736c82ced73c2b656263da9e5d1/src/BloomExe/Utils/MemoryManagement.cs#L125)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Probably still worth having the comment you had which states these strings are in the Palaso xliff
</blockquote></details>

Done.  The comment now also explains why, and why it's safe.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4294)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
