### PR TITLE
BL-4027/9 and 4036 TextBox Properties dialog

### PR DESCRIPTION
**Pull request by gmartin7**
* hook up dialog
* factor out common code to editableDivUtils from
   StyleEditor, toolbox and TextBoxProperties
* put basic Language tab UI in place
* get dialog to install data-default-languages attribute
   in appropriate translationGroup

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1359)

### CODE REVIEW

**Comment by andrew-polk** [comment]
I'm not going to claim to have fully reviewed TextBoxProperties.ts. I assume a lot of it was copied from the styles dialog.  And since it is brand new, it either works or it doesn't.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts, line 101 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYL0MOF0HaAoGuy1MJF:-KYL0MOF0Jo5tZt8jvdu:b-149uka) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5add0b792980cd18c33198afe6217b61ec2477ca/src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts#L101)):*
> i === 0

With for (var i = 1; ; i++), how could i ever be 0?

---

*[src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts, line 110 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYL0aP4-TbZ9IeKLuFt:-KYL0aP49ggaajopvsGF:b-4nb6dq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5add0b792980cd18c33198afe6217b61ec2477ca/src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts#L110)):*
> return

Why is it sufficient to attach this event to the first instance we happen to find which isn't ready? What happens if there are still other instances not ready?

---

*[src/BloomBrowserUI/bookEdit/js/origami.ts, line 119 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYL1VsF9BlkB67TCj-6:-KYL1VsF8o9udr8_Xpq2:bxkgtfc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5add0b792980cd18c33198afe6217b61ec2477ca/src/BloomBrowserUI/bookEdit/js/origami.ts#L119)):*
> textFormatButtonHandler

What is the purpose of this function? I don't see how it could be useful. And I don't see it used.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 46 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYL3PAq6HTe4fC_6_ja:-KYL3PAq3bkHujFqso6H:b-eq5ygv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5add0b792980cd18c33198afe6217b61ec2477ca/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L46)):*
> no longer works

In what way?
My initial thought is perhaps it is a timing issue and waiting for the availableFontNames to finish is usually enough time to complete successfully. But that's a complete guess.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-:-KYL4Xk-AuP9TSg0KwHu:b3gh282)*

**Comment by gmartin7** [comment]
Yes, copied and modified from StyleEditor.ts

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts, line 101 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYL0MOF0HaAoGuy1MJF:-KYLBI902yigB3A0uNNg:bj47prx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5add0b792980cd18c33198afe6217b61ec2477ca/src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts#L101)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> i === 0

With for (var i = 1; ; i++), how could i ever be 0?
</blockquote></details>

No idea. This same code was in toolbox.ts and StyleEditor.ts. I have removed the
"if (i===0)" block.

---

*[src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts, line 110 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYL0aP4-TbZ9IeKLuFt:-KYLBeosExaZ1nfFqsxr:b-d3d0za) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5add0b792980cd18c33198afe6217b61ec2477ca/src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts#L110)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> return

Why is it sufficient to attach this event to the first instance we happen to find which isn't ready? What happens if there are still other instances not ready?
</blockquote></details>

Good question. Again, not my code, just refactored. I assume that other instances would become ready later, but we only need one to act on our targetBox?

---

*[src/BloomBrowserUI/bookEdit/js/origami.ts, line 119 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYL1VsF9BlkB67TCj-6:-KYLC5RL2RypTUmD3ECA:biyd7i8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5add0b792980cd18c33198afe6217b61ec2477ca/src/BloomBrowserUI/bookEdit/js/origami.ts#L119)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> textFormatButtonHandler

What is the purpose of this function? I don't see how it could be useful. And I don't see it used.
</blockquote></details>

Oops. Must have been an early creation that I decided I didn't need. Deleted.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 46 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYL3PAq6HTe4fC_6_ja:-KYLCEvpBzr_GVAx5_BG:b-sqrr53) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5add0b792980cd18c33198afe6217b61ec2477ca/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L46)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> no longer works

In what way?
My initial thought is perhaps it is a timing issue and waiting for the availableFontNames to finish is usually enough time to complete successfully. But that's a complete guess.
</blockquote></details>

Maybe I did it wrong, but when I removed the axios call, the dialog no longer came up when I clicked on the gear icon. In later efforts, I made a new EnhancedImageServer call and used the axios call to get all the languages used in the book, but that turned out to not be a productive way to go for other reasons. If it can be removed and still have the dialog work, that would be ideal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-:-KYLAMXtD8wkTUjECFWR:bg7ew7x)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 2 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts, line 110 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYL0aP4-TbZ9IeKLuFt:-KYObr22A8SuH0gw1vJv:bndgm1q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5add0b792980cd18c33198afe6217b61ec2477ca/src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts#L110)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Good question. Again, not my code, just refactored. I assume that other instances would become ready later, but we only need one to act on our targetBox?
</blockquote></details>

@Hatton, thoughts?

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 46 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYL3PAq6HTe4fC_6_ja:-KYObM2l1sVLISDyoxn9:b-gw90zd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5add0b792980cd18c33198afe6217b61ec2477ca/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L46)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Maybe I did it wrong, but when I removed the axios call, the dialog no longer came up when I clicked on the gear icon. In later efforts, I made a new EnhancedImageServer call and used the axios call to get all the languages used in the book, but that turned out to not be a productive way to go for other reasons. If it can be removed and still have the dialog work, that would be ideal.
</blockquote></details>

I would try a delay before calling the code in the 'then' to see if it is, indeed, a timing issue.

I'm not really comfortable with the code as is, unless we can at least understand what is happening. If it is a timing issue, there is always the possibility that availableFontNames finishes too early to really solve the problem which would result in flaky behavior for users.

I guess the call to availableFontNames got in there in the first place due to being copy/modified from StyleEditor?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts, line 110 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYL0aP4-TbZ9IeKLuFt:-KYOj4HzCKzo76Yvlsn-:b1kx3bp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5add0b792980cd18c33198afe6217b61ec2477ca/src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts#L110)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

@Hatton, thoughts?
</blockquote></details>

As far as I know, there is only one instance of ckeditor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/bloomImages.ts, line 2 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYOjfxn77tRcegQLH-F:-KYOjfxn97pnlF8ze3Nk:b-wsrpek) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/54713ccdc178c1810e7e810d412035d6da12b6da/src/BloomBrowserUI/bookEdit/js/bloomImages.ts#L2)):*
> ```XML
> ///<reference path="../../lib/jquery.myimgscale.d.ts" />
> import '../../lib/jquery.resize'; // makes jquery resize work on all elements
> ```

How is this related to this PR? If it is not, please remove it.

---

*[src/BloomBrowserUI/bookEdit/js/origami.ts, line 119 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYOjypvBisE1JAzKYkR:-KYOjypv-eK8-L0nH2Kk:b-m11zg5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/54713ccdc178c1810e7e810d412035d6da12b6da/src/BloomBrowserUI/bookEdit/js/origami.ts#L119)):*
> ```XML
> }
> 
> function GetTextBoxPropDlg() {
> ```

Let's avoid abbreviations like this.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 54 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYOkeqw0xoVsk2Kpd45:-KYOkeqw0qTAJpBWi-Cv:b-ww5io5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/54713ccdc178c1810e7e810d412035d6da12b6da/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L54)):*
> ```XML
>                 var languageGroup = propDlg.getTextBoxLanguage(targetBox);
> 
>                 var html = '<div id="format-toolbar" class="bloom-ui bloomDialogContainer">'
> ```

Wow, this has got to be the most painful way possible of building a UI.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 83 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYOkuWnDWiCKr-97BTQ:-KYOkuWn6bcyqQvmE9PD:b-ivtrky) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/54713ccdc178c1810e7e810d412035d6da12b6da/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L83)):*
> ```XML
>                     //     + '</div>'; // end of tab-pane div
>                 }
>                 html += '</div>'; // end of format-toolbar div
> ```

In what sense is this dialog box a "toolbar"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 535 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYOlrC9C-uq6_TfJlqg:-KYOlrC90UeN0AsvFRwt:b-exssdd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/54713ccdc178c1810e7e810d412035d6da12b6da/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L535)):*
> ```XML
>         // its nefarious work. The following block achieves this.
>         // gjm: Refactored it into EditableDivUtils.
>         EditableDivUtils.WaitForCKEditorReady(window, targetBox, this.AttachToBox);
> ```

So CKEditor is attaching even in this "Change Layout" mode, where we don't use it?

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 127 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYOlMy208B6Dn6CHNX8:-KYOlMy239BehAp1JngQ:b-xd2qnw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/54713ccdc178c1810e7e810d412035d6da12b6da/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L127)):*
> ```XML
>      * @param toolbar
>      */
>     static positionInViewport(toolbar: JQuery): void {
> ```

Is this copy/pasted from StyleEditor? Why isn't it factored out?

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 150 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYOl6C3ANZ45quj8zSx:-KYOl6C362fq_6UTuj2B:b-iarc1f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/54713ccdc178c1810e7e810d412035d6da12b6da/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L150)):*
> ```XML
>     }
> 
>     makeDiv(id: string, className: string, style: string, i18nAttr: string, content: string): string {
> ```

I'm missing the point of this method. Why not just construct the string where it is needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359)*

**Comment by gmartin7** [comment]
Review status: 1 of 5 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/origami.ts, line 119 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYOjypvBisE1JAzKYkR:-KYPDL60BMyPqh64V-P5:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dd594e7565c8e4bebf5d1eb1e387a576bf062a27/src/BloomBrowserUI/bookEdit/js/origami.ts#L119)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Let's avoid abbreviations like this.
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 535 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYOlrC9C-uq6_TfJlqg:-KYQ-R3M1CzV7KZqnLkr:b-xishue) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dd594e7565c8e4bebf5d1eb1e387a576bf062a27/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L535)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

So CKEditor is attaching even in this "Change Layout" mode, where we don't use it?
</blockquote></details>

No, CKEditor never attaches to origami panes. Removed.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 46 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYL3PAq6HTe4fC_6_ja:-KYQ57DT54A1-AEMyphY:b-ucx2ls) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5add0b792980cd18c33198afe6217b61ec2477ca/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L46)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I would try a delay before calling the code in the 'then' to see if it is, indeed, a timing issue.

I'm not really comfortable with the code as is, unless we can at least understand what is happening. If it is a timing issue, there is always the possibility that availableFontNames finishes too early to really solve the problem which would result in flaky behavior for users.

I guess the call to availableFontNames got in there in the first place due to being copy/modified from StyleEditor?
</blockquote></details>

Much better! It turns out that a 0 sec setTimout call is enough to push the contents to the end of the event queue, which is all that's needed to get it to work. Removes the dependency on axios too!

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 54 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYOkeqw0xoVsk2Kpd45:-KYQRMtU2JvTIfxDUm7r:b9v1m32) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dd594e7565c8e4bebf5d1eb1e387a576bf062a27/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L54)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Wow, this has got to be the most painful way possible of building a UI.
</blockquote></details>

Hopefully I improved it a bit, but yes, you're right.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 83 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYOkuWnDWiCKr-97BTQ:-KYQQeWjD9uBe9bOONp_:bx735c6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dd594e7565c8e4bebf5d1eb1e387a576bf062a27/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L83)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

In what sense is this dialog box a "toolbar"?
</blockquote></details>

Renamed 'format-toolbar' to 'text-properties-dialog'. Renamed local variable 'toolbar' to 'dialogElement'.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 127 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYOlMy208B6Dn6CHNX8:-KYQQmdv8gH9ooEvrUan:buaywsi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dd594e7565c8e4bebf5d1eb1e387a576bf062a27/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L127)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is this copy/pasted from StyleEditor? Why isn't it factored out?
</blockquote></details>

I put it in editableDivUtils. I'm not sure that's the best place for it, but at least the file name ends in Utils.

---

*[src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, line 150 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYOl6C3ANZ45quj8zSx:-KYQ5dmg0-NnI0mkaCpb:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dd594e7565c8e4bebf5d1eb1e387a576bf062a27/src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts#L150)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I'm missing the point of this method. Why not just construct the string where it is needed?
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/js/bloomImages.ts, line 2 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYOjfxn77tRcegQLH-F:-KYPC51Y5qEeQOk33-6I:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dd594e7565c8e4bebf5d1eb1e387a576bf062a27/src/BloomBrowserUI/bookEdit/js/bloomImages.ts#L2)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

How is this related to this PR? If it is not, please remove it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359)*

**Comment by hatton** [comment]
LGTM. Has some conflicts now, probably just whitespace changes. Note that the .editorConfig changed, so your files probably don't have those changes yet.

**Comment by andrew-polk** [comment]
Reviewed 4 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts, line 110 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359#-KYL0aP4-TbZ9IeKLuFt:-KYTgRCo455C150DMugV:bwl7k5z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5add0b792980cd18c33198afe6217b61ec2477ca/src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts#L110)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

As far as I know, there is only one instance of ckeditor.
</blockquote></details>

This doesn't feel very satisfying. The code doesn't seem to properly reflect one instance nor does it seem to properly handle multiple instances. Since this is code which has been in place for a while and is simply being moved, I won't hold up the PR for it, though. Gordon, go ahead and merge unless you think it is worth taking a second look at this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1359)*

**Comment by hatton** [comment]
I've merged this... don't know why github doesn't know that. Maybe because I had to do conflict resolution on my machine?

**Pull request closed without merging**
