### PR TITLE
Detect settings changes and do notification (BL-9670)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4275)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4275)* status: 1 of 8 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 253 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4275#-MVhygFu3-k3cCxbc84r:-MVhygFu3-k3cCxbc84s:b-78ccqg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/83627e4d66ca4f9bdbd2a0f7abb6fbc9c1291217/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L253)):*
> ```Smalltalk
> 		/// </summary>
> 		/// <returns></returns>
> 		private bool RemoteCollectionFilesUpdated()
> ```

Remote --> Repo ?
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 253 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4275#-MVhzjxwA7pWMoylYOZ4:-MVhzjxwA7pWMoylYOZ5:bw9lp9s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/83627e4d66ca4f9bdbd2a0f7abb6fbc9c1291217/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L253)):*
> ```Smalltalk
> 		/// </summary>
> 		/// <returns></returns>
> 		private bool RemoteCollectionFilesUpdated()
> ```

Method names that could be a query or an action are expensive to read.  As a query, this could be `GetRepoCollectionFIlesUpdated()`
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 256 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4275#-MVhyvS061G03e_Xdcdj:-MVhyvS061G03e_Xdcdk:b-dq9n8c) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/83627e4d66ca4f9bdbd2a0f7abb6fbc9c1291217/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L256)):*
> ```Smalltalk
> 		{
> 			var savedModTime = LocalCollectionFilesRecordedSyncTime();
> 			return Directory.EnumerateFiles(Path.Combine(_repoFolderPath, "Other"))
> ```

Does `EnumerateFiles`  need Robust? Does it need try/catch? If not, maybe add comments saying why not.
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 490 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4275#-MVhzOrBCXfSA5WwgbxX:-MVhzOrBCXfSA5WwgbxY:bkdq5j4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/83627e4d66ca4f9bdbd2a0f7abb6fbc9c1291217/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L490)):*
> ```Smalltalk
> 		}
> 
> 		protected internal override void StopMonitoring()
> ```

Often these kinds of things are gated so that they don't die if called twice. As is, this will die on the `Dispose`

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4275)* status: 1 of 8 files reviewed, 4 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 253 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4275#-MVhygFu3-k3cCxbc84r:-MVwRkFu-A_tmbuENehE:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/83627e4d66ca4f9bdbd2a0f7abb6fbc9c1291217/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L253)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Remote --> Repo ?
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 253 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4275#-MVhzjxwA7pWMoylYOZ4:-MVwRl986snKi2nhVgCf:bxigaan) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/83627e4d66ca4f9bdbd2a0f7abb6fbc9c1291217/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L253)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Method names that could be a query or an action are expensive to read.  As a query, this could be `GetRepoCollectionFIlesUpdated()`
</blockquote></details>

I'm not seeing how anything in there can sound like a verb. And 'Get' in function names feels redundant so I try to avoid it if possible. I tried a different rename.
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 256 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4275#-MVhyvS061G03e_Xdcdj:-MVwUEn3-PwFPeGwCmwU:biv7ye8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/83627e4d66ca4f9bdbd2a0f7abb6fbc9c1291217/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L256)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Does `EnumerateFiles`  need Robust? Does it need try/catch? If not, maybe add comments saying why not.
</blockquote></details>

We apparently never created a robust version of EnumerateFiles. I'm not sure why not, we use it in several places. Potentially tricky since (unless you do the whole enumeration and return a list) you can't just restart if you've already returned some values. And there are probably subtle ways of changing behavior if enumerating over a directory that gets updated asynchronously. For this function, I think a try-catch is enough.
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 490 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4275#-MVhzOrBCXfSA5WwgbxX:-MVwVdr79fc3bqOOBWeG:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/83627e4d66ca4f9bdbd2a0f7abb6fbc9c1291217/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L490)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Often these kinds of things are gated so that they don't die if called twice. As is, this will die on the `Dispose`
</blockquote></details>

Done.

**Review by hatton — APPROVED** [review]
> Reviewed 4 of 8 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4275)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 253 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4275#-MVhzjxwA7pWMoylYOZ4:-MVwgD0GEdInQlQWCuem:b3m76pk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/83627e4d66ca4f9bdbd2a0f7abb6fbc9c1291217/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L253)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm not seeing how anything in there can sound like a verb. And 'Get' in function names feels redundant so I try to avoid it if possible. I tried a different rename.
</blockquote></details>

Yeah, the verb is inferred. My brain reads`RemoteCollectionFilesUpdated` as not grammatical English. So the brain has to fill something in. It seems to have 2 choices:
1) Add a ? at the end
2) Add a missing auxiliary verb, e.g. `RemoteCollectionFilesWereUpdated`, so that you get "were updated" as the verb.

I dislike introducing "have" just for... I'm not clear what for. Is "get" not the standard label for properties?
___
*[src/BloomExe/TeamCollection/RepoChangeEventArgs.cs, line 10 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4275#-MVwil84AvPNk0d7iDGm:-MVwil85EnqG1WxM2uCm:bzerf65) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b7d1ef0f5690ab783f8e679f26412ec10867240f/src/BloomExe/TeamCollection/RepoChangeEventArgs.cs#L10)):*
> ```Smalltalk
> {
> 	// General base class for three kinds of repo changes detected in event handlers.
> 	public class RepoChangeEventArgs
> ```

I don't understand why this file exists. Are you planning to add things to the even in the future?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4275)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 253 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4275#-MVhzjxwA7pWMoylYOZ4:-MW-QPl66btaLH9s5f0Y:byajmiw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/83627e4d66ca4f9bdbd2a0f7abb6fbc9c1291217/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L253)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Yeah, the verb is inferred. My brain reads`RemoteCollectionFilesUpdated` as not grammatical English. So the brain has to fill something in. It seems to have 2 choices:
1) Add a ? at the end
2) Add a missing auxiliary verb, e.g. `RemoteCollectionFilesWereUpdated`, so that you get "were updated" as the verb.

I dislike introducing "have" just for... I'm not clear what for. Is "get" not the standard label for properties?
</blockquote></details>

Well, I think of using Get as the start of a property getter as a Javascript convention...C# actually has a syntax for properties (which of course uses get and set as keywords). But this feels like a bit much code for a property. I can live with Get.
___
*[src/BloomExe/TeamCollection/RepoChangeEventArgs.cs, line 10 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4275#-MVwil84AvPNk0d7iDGm:-MW-S6K-ELbX8dL6DKMZ:b5yivtz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b7d1ef0f5690ab783f8e679f26412ec10867240f/src/BloomExe/TeamCollection/RepoChangeEventArgs.cs#L10)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I don't understand why this file exists. Are you planning to add things to the even in the future? 
</blockquote></details>

I added to the comment.

**Review by hatton — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4275)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 253 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4275#-MVhzjxwA7pWMoylYOZ4:-MW-U6gT9ClpI6CrrFMf:b-ooyrgq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/83627e4d66ca4f9bdbd2a0f7abb6fbc9c1291217/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L253)):*
> But this feels like a bit much code for a property. I can live with Get.

I see what you mean. `Get` normally implies "cheap".

**Pull request merged**
