### PR TITLE
Add a basic Fonts tab to the Book Settings dialog (BL-13763)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599)

### CODE REVIEW

**Comment by StephenMcConnel** [comment]
I couldn't figure out how to get exactly the same style list as the styles dialog, but I think the list I came up with is what is actually used in the book currently.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, 4 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599)* status: all files reviewed, 8 unresolved discussions (waiting on @StephenMcConnel)

___
*[`DistFiles/localization/en/Bloom.xlf` line 1572 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599#-O4MHUgD3lUnTrXLTKMO:-O4MHUgD3lUnTrXLTKMP:bml9v47) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cf2478cf824c89b23897bfa4f39548da3916e1b4/DistFiles/localization/en/Bloom.xlf#L1572)):*
> ```XML
>         <note>ID: EditTab.FormatDialog.Emphasis</note>
>       </trans-unit>
>       <trans-unit id="EditTab.FormatDialog.FirstPage" sil:dynamic="true">
> ```

Let's add `translate="no"` for all the new strings in this file and medium
___
*[`DistFiles/localization/en/Bloom.xlf` line 1572 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599#-O4MIB055h_5glvYiygi:-O4MIB055h_5glvYiygj:b-o5kq3d) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cf2478cf824c89b23897bfa4f39548da3916e1b4/DistFiles/localization/en/Bloom.xlf#L1572)):*
> ```XML
>         <note>ID: EditTab.FormatDialog.Emphasis</note>
>       </trans-unit>
>       <trans-unit id="EditTab.FormatDialog.FirstPage" sil:dynamic="true">
> ```

Shouldn't this ID be related to the book settings?
And should we move this into the MediumPriority file?
___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 691 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599#-O4MIa1m50RhNv2Ne6OS:-O4MIa1m50RhNv2Ne6OT:b-rez0di) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cf2478cf824c89b23897bfa4f39548da3916e1b4/DistFiles/localization/en/BloomMediumPriority.xlf#L691)):*
> ```XML
>         <note>ID: BookSettings.Fonts.TableDescription</note>
>       </trans-unit>
>       <trans-unit id="BookSettings.Fonts.credits" sil:dynamic="true">
> ```

Is there a way to make use of the existing localizations we should have for these page labels?
___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 301 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599#-O4MKdYV4IEIh7NAKnUx:-O4MKdYV4IEIh7NAKnUy:bx07cf1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cf2478cf824c89b23897bfa4f39548da3916e1b4/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L301)):*
> ```XML
>         isOpenAlready = false;
>         closeDialog();
>     }
> ```

Do the calls have to happen in this order? 
Or can you extract the common bits from the Ok button's onClick and then call postStirng?

Would it be even better to have StyleAndFontTable do the PostJson itself and then the prop is just closeDialog?
___
*[`src/BloomExe/web/controllers/BookSettingsApi.cs` line 68 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599#-O4LxwyJ4XVOtJL8ieV3:-O4LxwyL4CiP_AHRTdbP:b-ygpomi) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8da35deff29cc33643b1906e4138b4b2b0f286b8/src/BloomExe/web/controllers/BookSettingsApi.cs#L68)):*
> ```Smalltalk
>                 HandleStylesAndFonts,
>                 false
>             );
> ```

As I read through the code, I keep finding myself thinking, this has nothing to do with book settings.
What do you think of moving all this to a new FontAndStylesApi? Or even into the existing FontsApi?
___
*[`src/BloomExe/web/controllers/BookSettingsApi.cs` line 342 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599#-O4MFm-NEA2yZ2-jg5Tp:-O4MFm-NEA2yZ2-jg5Tq:b8pmqs8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8da35deff29cc33643b1906e4138b4b2b0f286b8/src/BloomExe/web/controllers/BookSettingsApi.cs#L342)):*
> ```Smalltalk
>             if (RobustFile.Exists(defaultLangStylesPath))
>             {
>                 var defaultLangStylesContent = RobustFile.ReadAllText(defaultLangStylesPath, System.Text.Encoding.UTF8);
> ```

Can/should we be using ProcessDefaultLangStyles() or FindFontsUsedInCss()?
___
*[`src/BloomExe/web/controllers/BookSettingsApi.cs` line 398 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599#-O4MH6DB6UoXD_B3x6ay:-O4MH6DB6UoXD_B3x6az:bj5b22d) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8da35deff29cc33643b1906e4138b4b2b0f286b8/src/BloomExe/web/controllers/BookSettingsApi.cs#L398)):*
> ```Smalltalk
>         }
> 
>         private static List<StyleAndFont> GetUserModifiedStylesAndFonts(HtmlDom dom)
> ```

I think you just did almost the same thing in HtmlDom for the initial bug fix related to this?
Can/should we pull the implementations together somehow?
___
*[`src/BloomExe/web/controllers/BookSettingsApi.cs` line 77 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599#-O4MJMlN0OyRRpzxw9eX:-O4MJMlN0OyRRpzxw9eY:bd6dlmw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cf2478cf824c89b23897bfa4f39548da3916e1b4/src/BloomExe/web/controllers/BookSettingsApi.cs#L77)):*
> ```Smalltalk
>         }
> 
>         private void HandleJumpToPage(ApiRequest request)
> ```

I think this endpoint should be moved up somewhere.
EditingViewApi?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599)* status: all files reviewed, 8 unresolved discussions (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/Bloom.xlf` line 1572 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599#-O4MHUgD3lUnTrXLTKMO:-O4MfcTR6dxvNlSCi-VE:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cf2478cf824c89b23897bfa4f39548da3916e1b4/DistFiles/localization/en/Bloom.xlf#L1572)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's add `translate="no"` for all the new strings in this file and medium
</blockquote></details>

Done.
___
*[`DistFiles/localization/en/Bloom.xlf` line 1572 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599#-O4MIB055h_5glvYiygi:-O4MfdMe0jULZR48Edta:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cf2478cf824c89b23897bfa4f39548da3916e1b4/DistFiles/localization/en/Bloom.xlf#L1572)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Shouldn't this ID be related to the book settings?
And should we move this into the MediumPriority file?
</blockquote></details>

Done.
___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 691 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599#-O4MIa1m50RhNv2Ne6OS:-O4MfvHy4CHlCvvZjrs3:byg6mxd) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cf2478cf824c89b23897bfa4f39548da3916e1b4/DistFiles/localization/en/BloomMediumPriority.xlf#L691)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is there a way to make use of the existing localizations we should have for these page labels?
</blockquote></details>

Done.  (Although I still prefer "Back Cover" to "Outside Back Cover".)
___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 301 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599#-O4MKdYV4IEIh7NAKnUx:-O4MlJV74TzRoPLhmzxR:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cf2478cf824c89b23897bfa4f39548da3916e1b4/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L301)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Do the calls have to happen in this order? 
Or can you extract the common bits from the Ok button's onClick and then call postStirng?

Would it be even better to have StyleAndFontTable do the PostJson itself and then the prop is just closeDialog?
</blockquote></details>

Done.
___
*[`src/BloomExe/web/controllers/BookSettingsApi.cs` line 68 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599#-O4LxwyJ4XVOtJL8ieV3:-O4MmmWb3A9NTjhmBFfM:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8da35deff29cc33643b1906e4138b4b2b0f286b8/src/BloomExe/web/controllers/BookSettingsApi.cs#L68)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

As I read through the code, I keep finding myself thinking, this has nothing to do with book settings.
What do you think of moving all this to a new FontAndStylesApi? Or even into the existing FontsApi?
</blockquote></details>

Done.
___
*[`src/BloomExe/web/controllers/BookSettingsApi.cs` line 342 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599#-O4MFm-NEA2yZ2-jg5Tp:-O4Mur_P2Gpjx3nMOobh:b-i72tdw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8da35deff29cc33643b1906e4138b4b2b0f286b8/src/BloomExe/web/controllers/BookSettingsApi.cs#L342)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Can/should we be using ProcessDefaultLangStyles() or FindFontsUsedInCss()?
</blockquote></details>

FindFontsUsedInCss() is highly optimized for just finding fonts.
I've extracted common code to use in ProcessDefaultLangStyles() and GetLanguagesAndDefaultFonts() so that there's only one Regex operation applied to langDefaultStyles.css content.  The new code has the (probably beneficial) side-effect of no longer always returning the 3 fonts "served" by Bloom as fonts used by the book when queried by harvester, even when they weren't being used in the book.
___
*[`src/BloomExe/web/controllers/BookSettingsApi.cs` line 398 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599#-O4MH6DB6UoXD_B3x6ay:-O4gq3992WunhXy_1BkV:bpcuetm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8da35deff29cc33643b1906e4138b4b2b0f286b8/src/BloomExe/web/controllers/BookSettingsApi.cs#L398)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think you just did almost the same thing in HtmlDom for the initial bug fix related to this?
Can/should we pull the implementations together somehow?
</blockquote></details>

I've provided a a single global Regex for both uses, commenting it thoroughly.  I think that's as far as we can go to reuse code here.  One case wants to ignore unused styles, the other case wants to include them.
___
*[`src/BloomExe/web/controllers/BookSettingsApi.cs` line 77 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599#-O4MJMlN0OyRRpzxw9eX:-O4Mmkh_DzH9aWwbGjft:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/cf2478cf824c89b23897bfa4f39548da3916e1b4/src/BloomExe/web/controllers/BookSettingsApi.cs#L77)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this endpoint should be moved up somewhere.
EditingViewApi?
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`DistFiles/localization/en/Bloom.xlf` line 4476 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599#-O4gu7pZ4m3j2LQYfjvN:-O4gu7pZ4m3j2LQYfjvO:bs3tpvd) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2632e21ad3d935301e09e1f0abee2eda594c3c9/DistFiles/localization/en/Bloom.xlf#L4476)):*
> ```XML
>         <source xml:lang="en">Check the Fonts section of the Book Settings dialog to locate this font.</source>
>         <note>ID: PublishTab.FontProblem.CheckInBookSettingsDialog</note>
>       </trans-unit>
> ```

One more to add translate="no" to.
___
*[`src/BloomExe/web/controllers/StylesAndFontsApi.cs` line 268 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599#-O4gx0Qo677zawUvfNQe:-O4gx0Qo677zawUvfNQf:b-kqq337) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2632e21ad3d935301e09e1f0abee2eda594c3c9/src/BloomExe/web/controllers/StylesAndFontsApi.cs#L268)):*
> ```Smalltalk
>                     if (string.IsNullOrEmpty(match.Groups[6].Value))
>                         continue;   // no font-family specified in this rule
> 					var styleAndFont = new StyleAndFont();
> ```

There's a mix of tabs and spaces for indentation here and a few other places.

Sorry; I really don't want to hold up a PR for this, but we have to get your CSharpier set up correctly. Else we'll just end up producing lots of unnecessary merge conflicts down the road.
Let's work on it together tomorrow.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/Bloom.xlf` line 4476 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599#-O4gu7pZ4m3j2LQYfjvN:-O4kVrAc8uQAJ53DwBJ1:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2632e21ad3d935301e09e1f0abee2eda594c3c9/DistFiles/localization/en/Bloom.xlf#L4476)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

One more to add translate="no" to.
</blockquote></details>

Done.
___
*[`src/BloomExe/web/controllers/StylesAndFontsApi.cs` line 268 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599#-O4gx0Qo677zawUvfNQe:-O4kVt0aDGCuHedZOv74:b-t1x0tp) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f2632e21ad3d935301e09e1f0abee2eda594c3c9/src/BloomExe/web/controllers/StylesAndFontsApi.cs#L268)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

There's a mix of tabs and spaces for indentation here and a few other places.

Sorry; I really don't want to hold up a PR for this, but we have to get your CSharpier set up correctly. Else we'll just end up producing lots of unnecessary merge conflicts down the road.
Let's work on it together tomorrow.
</blockquote></details>

Done.  A couple of other files also had tabs that have been fixed.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6599)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
