### PR TITLE
Forced Alignment 4.5 New UI

### PR DESCRIPTION
**Pull request by sujeffreyl**
New UI buttons and new transitions between client states

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3056)

### CODE REVIEW

**Comment by sujeffreyl** [comment]
___
*[DistFiles/localization/en/Bloom.xlf, line 2149 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3056#-LZu9AU3BRONP29aQhhw:-LZuysxIElgewEB-nH6B:b1kazc7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0cdfa5bfc80a03aae23948a69f33d1e295acac54/DistFiles/localization/en/Bloom.xlf#L2149)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Can we avoid needing to add both of these? The first one could be used with '5' inserted literally if we aren't doing them all as a numbered list yet.
</blockquote></details>

Are you ok with it momentarily display the literal text "{0}) Split" for a brief second before the JS comes in and replaces it?
Kinda difficult to work with because I don't think format string replacements are possible in pug? (or is it?)

**Comment by hatton** [comment]
> with CSS or just a separate HTML element or something like that. I
suppose there may be some language

Yup we already do that I think? Can't say for certain where... Maybe page
numbers?

**Comment by sujeffreyl** [comment]
> 
> 
> This would appear to just create new items, leaving the old, unused ones still there. Not what we want?
> 
> I'm not clear why the IDs were changed. Why not just edit?
> 
> Does changing things in git then flow upstream to crowdin? If not, use of the crowding CLI or website might be needed.

@hatton 
The same strings are used in 4.3 and 4.4. I didn't want to edit them for fear of breaking parity in 4.3 and 4.4. Although... I'm not 100% sure how this works, but I guess if we never release another patch for 4.4 or at least don't update the localizations for 4.4 anymore then it would be OK?

Right, yeah i read through the readme earlier and concluded that I should update the checkin files first, then upload them to crowdin?  But at the very least, you're certainly right that I need to do something on the crowdin website as well.

**Comment by andrew-polk** [comment]
I don't see any blocker discussions by @JohnThomson at this point. Since he is somewhat unavailable and we are trying to get this feature out to test, I'm going to go ahead and merge.
@JohnThomson can let us know if there are things he thinks really need changing.

**Comment by JohnThomson** [comment]
Yes, we're arguing about clarity of comments and possibly better architectures at this point. Sorry to have held things up. Hopefully if there's still something to improve it will get done the next time we're in this area. Hopefully we can also redo it in React.

**Pull request merged**
