### PR TITLE
Repair empty pages on selecting book (BL-13389)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461)

### CODE REVIEW

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/BookStorage.cs` line 3082 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461#-NwqIkEr6mM2QVOyEJ-K:-NwqIkEr6mM2QVOyEJ-L:bpetdvb) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ba7895fa1fcc45c37114024b42bbab27f7d9c6a2/src/BloomExe/Book/BookStorage.cs#L3082)):*
> ```Smalltalk
> 			var pathToBasicBook = Path.Combine(pathToBasicBookFolder, "Basic Book.html");
> 			var dom = XmlHtmlConverter.GetXmlDomFromHtmlFile(pathToBasicBook);
> 			var justTextPage = dom.SelectSingleNode("//div[@id='a31c38d8-c1cb-4eb9-951b-d2840f6a8bdb']");
> ```

please add comment on the import, if any, of this guid
___
*[`src/BloomExe/Book/BookStorage.cs` line 3083 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461#-NwqIwZI-j7dlZuGa5t2:-NwqIwZI-j7dlZuGa5t3:bpy5e42) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ba7895fa1fcc45c37114024b42bbab27f7d9c6a2/src/BloomExe/Book/BookStorage.cs#L3083)):*
> ```Smalltalk
> 			var dom = XmlHtmlConverter.GetXmlDomFromHtmlFile(pathToBasicBook);
> 			var justTextPage = dom.SelectSingleNode("//div[@id='a31c38d8-c1cb-4eb9-951b-d2840f6a8bdb']");
> 			var editable = justTextPage.SelectSingleNode(".//div[@lang='z']") as XmlElement;
> ```

please add comment reminding about the use  of "z"
___
*[`src/BloomExe/Book/BookStorage.cs` line 3087 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461#-NwqJ-aR007oupgD2jbe:-NwqJ-aR007oupgD2jbf:b-4trsvo) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ba7895fa1fcc45c37114024b42bbab27f7d9c6a2/src/BloomExe/Book/BookStorage.cs#L3087)):*
> ```Smalltalk
> 			// translators to waste time on. Moreover, it's purpose is just to let the user know something has
> 			// gone wrong, which will be fairly evident even with an incomprehensible message in it.
> 			editable.InnerText = "Sorry...Bloom messed up this page.";
> ```

How about "We apologize, but it appears that a bug in an older version of Bloom removed the contents of this page. Please delete it. If you have a backup of this book, you may be able to copy the page from the good copy back into this book."

**Comment by andrew-polk** [comment]
*[`src/BloomExe/Book/BookStorage.cs` line 3082 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461#-NwqIkEr6mM2QVOyEJ-K:-NwqQizS-SWYcHFHI0ZH:b3dbv1u) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ba7895fa1fcc45c37114024b42bbab27f7d9c6a2/src/BloomExe/Book/BookStorage.cs#L3082)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

please add comment on the import, if any, of this guid
</blockquote></details>

The factory page guids are consts in book.css

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[`src/BloomExe/Book/BookStorage.cs` line 3082 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461#-NwqIkEr6mM2QVOyEJ-K:-NwqRhy41S5YLIJK_5Zw:b-1uvql0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ba7895fa1fcc45c37114024b42bbab27f7d9c6a2/src/BloomExe/Book/BookStorage.cs#L3082)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The factory page guids are consts in book.css
</blockquote></details>

I mean add a comment in the code, not the PR review LOL :-)

**Comment by andrew-polk** [comment]
*[`src/BloomExe/Book/BookStorage.cs` line 3082 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461#-NwqIkEr6mM2QVOyEJ-K:-NwqSWzsCzKIFnm_Ysvm:b-smp5uy) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ba7895fa1fcc45c37114024b42bbab27f7d9c6a2/src/BloomExe/Book/BookStorage.cs#L3082)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I mean add a comment in the code, not the PR review LOL :-)
</blockquote></details>

And I mean he should use the const. : )

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[`src/BloomExe/Book/BookStorage.cs` line 3082 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461#-NwqIkEr6mM2QVOyEJ-K:-NwqTIKg5aHVQK6iCTCM:b9c3uw0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ba7895fa1fcc45c37114024b42bbab27f7d9c6a2/src/BloomExe/Book/BookStorage.cs#L3082)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

And I mean he should use the const. : )
</blockquote></details>

Where's the emoji feature in reviewable?  🤦🏽

**Comment by andrew-polk** [comment]
*[`src/BloomExe/Book/BookStorage.cs` line 3082 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461#-NwqIkEr6mM2QVOyEJ-K:-NwqUK9ACeFBcWJ49K9t:bu3i70z) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ba7895fa1fcc45c37114024b42bbab27f7d9c6a2/src/BloomExe/Book/BookStorage.cs#L3082)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Where's the emoji feature in reviewable?  🤦🏽
</blockquote></details>

My comment should have said "Book.cs"

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461)* status: all files reviewed, 5 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`src/BloomExe/Book/BookStorage.cs` line 3093 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461#-NwqUp8F2XTpuvyDHk7b:-NwqUp8F2XTpuvyDHk7c:b7cog5r) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ba7895fa1fcc45c37114024b42bbab27f7d9c6a2/src/BloomExe/Book/BookStorage.cs#L3093)):*
> ```Smalltalk
> 			// In that case the message will show up in the source bubble. Not ideal, but
> 			// it's a corner case of hack to alleviate the results of a rare bug that we
> 			// think we've prevented from ever again doing this much damage. I think it's good enough.
> ```

Does it hurt anything to just add it to L1, L2, and L3 (if it exists)? Or at least L1 and L2?
___
*[`src/BloomExe/Book/BookStorage.cs` line 3097 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461#-NwqV3S_0dCBl9DdA2YG:-NwqV3S_0dCBl9DdA2YH:b-49tvx9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ba7895fa1fcc45c37114024b42bbab27f7d9c6a2/src/BloomExe/Book/BookStorage.cs#L3097)):*
> ```Smalltalk
> 			foreach (var page in problems)
> 			{
> 				page.ParentNode.ReplaceChild(page.OwnerDocument.ImportNode(justTextPage,true), page);
> ```

This makes me realize CSharpier hasn't done its thing on this code (since we are in 5.6).
Could you at least get it run on this large block of new code so we don't have it later wanting to reformat once it gets to master?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomExe/Book/BookStorage.cs` line 3082 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461#-NwqIkEr6mM2QVOyEJ-K:-Nwt_Rhh6ZazCasTRU3j:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ba7895fa1fcc45c37114024b42bbab27f7d9c6a2/src/BloomExe/Book/BookStorage.cs#L3082)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

My comment should have said "Book.cs"
</blockquote></details>

Done.
___
*[`src/BloomExe/Book/BookStorage.cs` line 3083 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461#-NwqIwZI-j7dlZuGa5t2:-Nwt_SLxEcBmq5OxYGi7:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ba7895fa1fcc45c37114024b42bbab27f7d9c6a2/src/BloomExe/Book/BookStorage.cs#L3083)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

please add comment reminding about the use  of "z"
</blockquote></details>

Done.
___
*[`src/BloomExe/Book/BookStorage.cs` line 3087 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461#-NwqJ-aR007oupgD2jbe:-Nwta0Kk8QdIqO6x9RCf:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ba7895fa1fcc45c37114024b42bbab27f7d9c6a2/src/BloomExe/Book/BookStorage.cs#L3087)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

How about "We apologize, but it appears that a bug in an older version of Bloom removed the contents of this page. Please delete it. If you have a backup of this book, you may be able to copy the page from the good copy back into this book."
</blockquote></details>

Done.
___
*[`src/BloomExe/Book/BookStorage.cs` line 3093 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461#-NwqUp8F2XTpuvyDHk7b:-NwthXz73m63BJjUjjL-:b7t3j9n) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ba7895fa1fcc45c37114024b42bbab27f7d9c6a2/src/BloomExe/Book/BookStorage.cs#L3093)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Does it hurt anything to just add it to L1, L2, and L3 (if it exists)? Or at least L1 and L2?
</blockquote></details>

The message shows up in both the body of the page AND in the source bubble, which looks a bit strange.
Discussed with Andrew, decided not to.
Even if L1 is turned off, that just means the message shows up in the source bubble instead of on the page.
___
*[`src/BloomExe/Book/BookStorage.cs` line 3097 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461#-NwqV3S_0dCBl9DdA2YG:-Nwu8CdL82AbFEiL2tYq:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ba7895fa1fcc45c37114024b42bbab27f7d9c6a2/src/BloomExe/Book/BookStorage.cs#L3097)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This makes me realize CSharpier hasn't done its thing on this code (since we are in 5.6).
Could you at least get it run on this large block of new code so we don't have it later wanting to reformat once it gets to master?
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461)* status: all files reviewed, 4 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`src/BloomExe/Book/BookStorage.cs` line 3082 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461#-NwuCr52Dmu9s8_CwdSz:-NwuCr52Dmu9s8_CwdT-:b-r082ow) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/153aeb8510fb8ed55de53dd94ef58c37beab2020/src/BloomExe/Book/BookStorage.cs#L3082)):*
> ```Smalltalk
> 			if (problems.Count == 0)
> 				return;
> 			// Replace the messed up pages with modified clones of our "Just Text" page that say "Sorry...Bloom messed up this page."
> ```

This comment is now out of sync with the message.

**Comment by andrew-polk** [comment]
*[`src/BloomExe/Book/BookStorage.cs` line 3082 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461#-NwuCr52Dmu9s8_CwdSz:-NwuDFW26BZKbdXMoL7N:b57kx62) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/153aeb8510fb8ed55de53dd94ef58c37beab2020/src/BloomExe/Book/BookStorage.cs#L3082)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This comment is now out of sync with the message.
</blockquote></details>

Then, LGTM

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomExe/Book/BookStorage.cs` line 3082 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461#-NwuCr52Dmu9s8_CwdSz:-NwuF7_-3t_p10Ba1b7B:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/153aeb8510fb8ed55de53dd94ef58c37beab2020/src/BloomExe/Book/BookStorage.cs#L3082)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Then, LGTM
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton)

**Review by andrew-polk — APPROVED** [review]
> Dismissed @hatton from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6461)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
