### PR TITLE
Disallow page labels that would make for problematic file names BL-4392

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1553)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 607 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1553#-KejQXP6VPXmXBZroEAP:-KejQXP6VPXmXBZroEAQ:b8ow1cc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8bdd0964df41565d5bdfd25394c4d73bdbc3edb0/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L607)):*
> ```XML
>     $(pageLabel).blur(event => {
>         // characters that cause problem in windows file names (linux is less picky, according to mono source)
>         pageLabel.innerText = pageLabel.innerText.split(/[\/,\\,*,:,?,",<,>,|]/).join("");
> ```

Since you're using a regular expression here, the commas are not separators but (repeated) members of the set. Slightly misleading, and I don't see that comma is actually a problem character.

---

*[src/BloomExe/web/controllers/PageTemplatesApi.cs, line 120 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1553#-KejPtU65u4NsmIf1h_Q:-KejPtU7RD2AVXLZl3Bb:bpph2t6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8bdd0964df41565d5bdfd25394c4d73bdbc3edb0/src/BloomExe/web/controllers/PageTemplatesApi.cs#L120)):*
> ```Smalltalk
> 			//NB: even if we decide to give a refreshed image, it still won't be accurate,
> 			//if the user just made a change; the page won't actually be saved yet, so the
> 			//newly created thumbnail will not reflect the change. Ah well, we try.
> ```

This surprises me. I have a vague recollection that I had to make it save the current page before it launched the dialog. But I'm probably confusing this with something else.

---

*[src/BloomExe/web/controllers/PageTemplatesApi.cs, line 121 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1553#-KejQ9E3ESvMiGkE6mDI:-KejQ9E3ESvMiGkE6mDJ:b-fqgcjr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8bdd0964df41565d5bdfd25394c4d73bdbc3edb0/src/BloomExe/web/controllers/PageTemplatesApi.cs#L121)):*
> ```Smalltalk
> 			//if the user just made a change; the page won't actually be saved yet, so the
> 			//newly created thumbnail will not reflect the change. Ah well, we try.
> 			if (!localPath.Contains(_bookSelection.CurrentSelection.FolderPath))
> ```

Shouldn't we check for read-only here, in case the user manually enhanced a png and wants to keep it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1553)*

**Comment by hatton** [comment]
Review status: 2 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 607 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1553#-KejQXP6VPXmXBZroEAP:-KekLJytAfC_xsZZIvEM:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8bdd0964df41565d5bdfd25394c4d73bdbc3edb0/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L607)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Since you're using a regular expression here, the commas are not separators but (repeated) members of the set. Slightly misleading, and I don't see that comma is actually a problem character.
</blockquote></details>

Done.

---

*[src/BloomExe/web/controllers/PageTemplatesApi.cs, line 120 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1553#-KejPtU65u4NsmIf1h_Q:-KekPuZKgfK-9xhyGXE-:b9nz1ql) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8bdd0964df41565d5bdfd25394c4d73bdbc3edb0/src/BloomExe/web/controllers/PageTemplatesApi.cs#L120)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This surprises me. I have a vague recollection that I had to make it save the current page before it launched the dialog. But I'm probably confusing this with something else.
</blockquote></details>

Checked again, same result.

---

*[src/BloomExe/web/controllers/PageTemplatesApi.cs, line 121 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1553#-KejQ9E3ESvMiGkE6mDI:-KekMNSxTCmHDsU8gMwW:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8bdd0964df41565d5bdfd25394c4d73bdbc3edb0/src/BloomExe/web/controllers/PageTemplatesApi.cs#L121)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Shouldn't we check for read-only here, in case the user manually enhanced a png and wants to keep it?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1553)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 4 files at r2.
Review status: 3 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[DistFiles/localization/Bloom.en.tmx, line 4511 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1553#-KenRA6xaCC0hJvu5qkd:-KenRA6xaCC0hJvu5qke:bnfwh65) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3552de773207e8052e2c1d82dc269187f5e46393/DistFiles/localization/Bloom.en.tmx#L4511)):*
> TemplateStarter

Not "Template Starter"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1553)*

**Comment by hatton** [comment]
Review status: 3 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[DistFiles/localization/Bloom.en.tmx, line 4511 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1553#-KenRA6xaCC0hJvu5qkd:-KenTCljH_Tvuqd8eN95:b-dm9530) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3552de773207e8052e2c1d82dc269187f5e46393/DistFiles/localization/Bloom.en.tmx#L4511)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> TemplateStarter

Not "Template Starter"?
</blockquote></details>

Dunno... this was automatically generated

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1553)*

**Comment by JohnThomson** [comment]
:lgtm: once you figure out whether you need a space in TemplateStarter

---

Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/BloomExe/web/controllers/PageTemplatesApi.cs, line 120 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1553#-KejPtU65u4NsmIf1h_Q:-KenWaZFjgwfQAzvbifz:bo75nrj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8bdd0964df41565d5bdfd25394c4d73bdbc3edb0/src/BloomExe/web/controllers/PageTemplatesApi.cs#L120)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Checked again, same result.
</blockquote></details>

OK, my mistake.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1553#-:-KenWlcJ54VVAAVyeFio:bsbwl90)*

**Comment by hatton** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[DistFiles/localization/Bloom.en.tmx, line 4511 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1553#-KenRA6xaCC0hJvu5qkd:-KfCawr7tJIMubf474aM:b845o9n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3552de773207e8052e2c1d82dc269187f5e46393/DistFiles/localization/Bloom.en.tmx#L4511)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Dunno... this was automatically generated
</blockquote></details>

OK, I think the stub was created for it before I added the code that hides it from the user. I have now removed this entry from the TMX. Thanks for catching that!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1553)*

**Pull request merged**
