### PR TITLE
Fix thumbnail.png locked intermittent errors

### PR DESCRIPTION
**Pull request by jsubloom**
Multiple Bloom threads may be trying to build thumbnail.png simultaneously. Just a small workaround to retry it in that case.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5933)

### CODE REVIEW

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5933)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5933#-NY44vqB0BR8NJS3d5lZ):*
Please see card for discussion of possible alternate (but more risky) solutions

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5933)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @jsubloom)

___
*[`src/BloomExe/BookThumbNailer.cs` line 196 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5933#-NY45YGzAuu0EkjhCDBA:-NY45YGzAuu0EkjhCDBB:b-q1cqv3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/01e8c0cf92a8ee5bbd0d58777d65a20f49dde93f/src/BloomExe/BookThumbNailer.cs#L196)):*
> ```Smalltalk
> 			// PalasoImage.SaveImageSafely can also throw ApplicationExceptions
> 			// (See https://github.com/sillsdev/libpalaso/blob/f2482a5b3c6c75b50ec5672b1eb731b1a040a05a/SIL.Windows.Forms/ImageToolbox/PalasoImage.cs#L155)
> 			// This very well may be temporary (if it's a different Bloom thread that has it locked) and retrying it would likely succeed.
> ```

Let's link to the issue and state there are some ideas there for more fundamental fixes.
___
*[`src/BloomExe/Extensions.cs` line 203 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5933#-NY44voV0SChIPvvJAV_:-NY44voV0SChIPvvJAVa:b-l7ec0v) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/01e8c0cf92a8ee5bbd0d58777d65a20f49dde93f/src/BloomExe/Extensions.cs#L203)):*
> ```Smalltalk
> 
> 		/// <summary>
> 		/// A re-imlementation of PalasoImage.SaveImageRobustly, but with configurble parameters.
> ```

Let's add a comment about why we aren't adding this directly to libpalaso.
(As I understand, because we don't want to have to pull in a libpalaso change just before release?)

Go ahead and fix the typos in the existing comment, too, please.
(and please ensure VS is set up to flag comment typos)

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5933)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Extensions.cs` line 203 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5933#-NY44voV0SChIPvvJAV_:-NY4MtPw9uAFCeFy_I1m:b-ukeb2n) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/01e8c0cf92a8ee5bbd0d58777d65a20f49dde93f/src/BloomExe/Extensions.cs#L203)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's add a comment about why we aren't adding this directly to libpalaso.
(As I understand, because we don't want to have to pull in a libpalaso change just before release?)

Go ahead and fix the typos in the existing comment, too, please.
(and please ensure VS is set up to flag comment typos)
</blockquote></details>

Oh, yeah. I forgot to mention that.  Yes, that was the reason.

Was wondering if I should add this functionality to libpalaso and pull that in for 5.6.
(Although, not only is that more dev work, but that's also twice as much painstaking testing)

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5933)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/BookThumbNailer.cs` line 196 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5933#-NY45YGzAuu0EkjhCDBA:-NY4PvFY-NNlq5zB95IN:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/01e8c0cf92a8ee5bbd0d58777d65a20f49dde93f/src/BloomExe/BookThumbNailer.cs#L196)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's link to the issue and state there are some ideas there for more fundamental fixes.
</blockquote></details>

Done.
___
*[`src/BloomExe/Extensions.cs` line 203 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5933#-NY44voV0SChIPvvJAV_:-NY4PsBuEJQEHl0XiczS:bthp9z2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/01e8c0cf92a8ee5bbd0d58777d65a20f49dde93f/src/BloomExe/Extensions.cs#L203)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

Oh, yeah. I forgot to mention that.  Yes, that was the reason.

Was wondering if I should add this functionality to libpalaso and pull that in for 5.6.
(Although, not only is that more dev work, but that's also twice as much painstaking testing)
</blockquote></details>

Added remarks.
Fixed spelling.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5933)* status: all files reviewed, 1 unresolved discussion

___
*[`src/BloomExe/Extensions.cs` line 203 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5933#-NY44voV0SChIPvvJAV_:-NY4Wvjx21BH3XRjJBk8:b-usgzg4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/01e8c0cf92a8ee5bbd0d58777d65a20f49dde93f/src/BloomExe/Extensions.cs#L203)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

Added remarks.
Fixed spelling.
</blockquote></details>

Yeah.... libpalaso is becoming more overhead than its worth. At least in some scenarios. I wouldn't bother at this time.

**Review by andrew-polk — APPROVED** [review]
> Dismissed @jsubloom from a discussion.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5933)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsubloom)

**Pull request merged**
