### PR TITLE
BL-4199 Make sure user-defined styles in a template page are copied to the destination book

### PR DESCRIPTION
**Pull request by gmartin7**
* revert initial solution (which moved .Equation-style to .less file)
* make sure User Modified styles used on the new page
   get pulled into the new book

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1448)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Confusing, partly because the overall description is very vague. "Fix" could mean anything. And I'm not clear which changes have to do with fixing some initial solution. Do you mean, make sure user-defined styles in a template page are copied to the destination book?
How is the need to do this unique to a "different template" situation?
What stops us getting duplicate definitions of the same user-defined style? (or conflicting ones)?

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomExe/Book/Book.cs, line 1784 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1448#-KbjmPoY4vzsZf4ec7iT:-KbjmPoY4vzsZf4ec7iU:bcqnmdy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8f75bea123966c867b0f4e83c071cdaaa2ecb9d3/src/BloomExe/Book/Book.cs#L1784)):*
> ```Smalltalk
> 				_bookData.SuckInDataFromEditedDom(editedPageDom); //this will do an updatetitle
> 				// When the user edits the styles on a page, the new or modified rules show up in a <style/> element with title "userModifiedStyles". Here we copy that over to the book DOM.
> 				// Review GJM 27 Jan 2017: What's to keep the user from editing several new styles? We only copy over the first one?!
> ```

I think we only ever make one user style element. It can contain multiple rules.

---

*[src/BloomExe/Edit/EditingModel.cs, line 294 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1448#-Kbjmsr0i2qXgSBHNcca:-Kbjmsr0i2qXgSBHNccb:bcgsf1r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8f75bea123966c867b0f4e83c071cdaaa2ecb9d3/src/BloomExe/Edit/EditingModel.cs#L294)):*
> ```Smalltalk
> 				foreach (var newStyle in e.UserStyles)
> 				{
> 					CurrentBook.CreateEmptyUserModifiedStyleElement().InnerXml = newStyle.InnerXml;
> ```

We need to get straight whether there is supposed to be one user-defined style element or many. If many, the problem you spotted above should be addressed. If one, code here (and various places below) should not create many.

---

*[src/BloomExe/web/controllers/AddOrChangePageApi.cs, line 105 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1448#-KbjorSE82fy8E8SkEjw:-KbjorSE82fy8E8SkEjx:bb6kpsb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8f75bea123966c867b0f4e83c071cdaaa2ecb9d3/src/BloomExe/web/controllers/AddOrChangePageApi.cs#L105)):*
> ```Smalltalk
> 		}
> 
> 		private IEnumerable<XmlNode> GetUserModifiableStylesUsedOnPage(Book.Book templateBook, IPage page)
> ```

I'm not following the point of these two methods. GetClassKeyFromStyleNode seems to expect the inner text of the style node to begin with a stylename-style (and returns it). Then this routine is looking for @class Stylename-style using the same name. Are we trying to filter out empty style nodes or ones that are broken somehow? A clear example of a typical style node somewhere in all this would help.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1448#-:-KbjpYinP-H2jcoa6uGG:b-5ci3lb)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/Edit/EditingModel.cs, line 294 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1448#-Kbjmsr0i2qXgSBHNcca:-KbjqNhVoxRtXeW9Z050:bbgv8rf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8f75bea123966c867b0f4e83c071cdaaa2ecb9d3/src/BloomExe/Edit/EditingModel.cs#L294)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We need to get straight whether there is supposed to be one user-defined style element or many. If many, the problem you spotted above should be addressed. If one, code here (and various places below) should not create many.
</blockquote></details>

Right. We need to create one element with all the user styles in it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1448)*

**Comment by gmartin7** [comment]
Have changed the description. I hope it's not so vague.
It also uses much the same code for Change Layout (which works)
We don't copy in user-defined styles from the template if they are identical or conflicting with ones already there. We do copy in styles which only differ in existence or absense of 'lang' attribute (e.g. .BigWords-style[lang='en']...)

---

Review status: 1 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/web/controllers/AddOrChangePageApi.cs, line 105 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1448#-KbjorSE82fy8E8SkEjw:-Kbq_JPJ8AaImd4_rb-G:b9unq0h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8f75bea123966c867b0f4e83c071cdaaa2ecb9d3/src/BloomExe/web/controllers/AddOrChangePageApi.cs#L105)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm not following the point of these two methods. GetClassKeyFromStyleNode seems to expect the inner text of the style node to begin with a stylename-style (and returns it). Then this routine is looking for @class Stylename-style using the same name. Are we trying to filter out empty style nodes or ones that are broken somehow? A clear example of a typical style node somewhere in all this would help.
</blockquote></details>

The method compares what's in the style node (.Stylename-style) with what's on the page (searching for @class = Stylename-style). We filter out the styles that aren't used on the page we are inserting. (so we don't add extraneous styles).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1448#-:-KbqZfjclGm3frkmTRZM:bu6bjr7)*

**Comment by JohnThomson** [comment]
Much better, and getting close, I think. Just a couple of suggestions and one fairly important question.

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/BloomExe/Book/HtmlDom.cs, line 732 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1448#-KbqjuHqzfEN4m5qkbdf:-KbqjuHqzfEN4m5qkbdg:byxauu9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b2fb6b21b1ee19e21eaf793c992a03698977a03b/src/BloomExe/Book/HtmlDom.cs#L732)):*
> ```Smalltalk
> 		}
> 
> 		internal static XmlNode GetUserModifiableStylesUsedOnPage(HtmlDom pageDom)
> ```

I don't like this. The name implies it is just getting the element (and leaves one wondering how it is different from GetUserModifiedStyleElement), but it actually has (potentially) side effects modifying the document! That is in the (unlikely) event that the element contains styles whose names don't properly end in -style. If we really have to do this, it would be better to have a routine with a name like 'RepairUserModifiableStyles' and call it on the element obtained from GetUserModifiedStyleElement.
A comment explaining why we anticipate and must remove such styles would be helpful.

---

*[src/BloomExe/Book/HtmlDom.cs, line 819 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1448#-Kbql0sRoIQSfNgVBQRb:-Kbql0sRoIQSfNgVBQRc:b-ycs163) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b2fb6b21b1ee19e21eaf793c992a03698977a03b/src/BloomExe/Book/HtmlDom.cs#L819)):*
> ```Smalltalk
> 						continue;
> 					}
> 					yield return line.Trim(); // e.g. could have leading tabs
> ```

Can't a style rule spread over more than one line? (Of course the ones Bloom generates probably don't...is it safe to rely on that?) I'm willing to be persuaded as long as you've considered it...

---

*[src/BloomExe/web/controllers/AddOrChangePageApi.cs, line 104 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1448#-KbqnJarVgWUBOZcSsL4:-KbqnJarVgWUBOZcSsL5:bwt1nx8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b2fb6b21b1ee19e21eaf793c992a03698977a03b/src/BloomExe/web/controllers/AddOrChangePageApi.cs#L104)):*
> ```Smalltalk
> 			}
> 			var domForPage = templateBook.GetEditableHtmlDomForPage(page);
> 			userStylesOnPage = HtmlDom.GetUserModifiableStylesUsedOnPage(domForPage); // could be empty
> ```

It surprises me that the template page has a user-defined styles section. I thought this was typically per-book? After all we expect style definitions to be consistent across the pages.
I expect you have checked that this does get some user-defined styles from the template; otherwise the new code would not be working at all.
Have you checked that it doesn't just get a copy of all the user-defined styles in the template book? It would be unfortunate if we copy in styles not actually used on this page. (Earlier comments make me think you've thought about this...just checking.)

---

*[src/BloomTests/Book/HtmlDomTests.cs, line 580 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1448#-Kbqlos15pZ6omVFfffF:-Kbqlos15pZ6omVFfffG:b-rv5ado) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b2fb6b21b1ee19e21eaf793c992a03698977a03b/src/BloomTests/Book/HtmlDomTests.cs#L580)):*
> ```Smalltalk
> 			bookStyleNode.InnerText = HtmlDom.MergeUserStylesOnInsertion(bookStyleNode, pageStyleNode);
> 
> 			var xpath = "//style[@title=\"userModifiedStyles\" and contains(text(),'font-size: ginormous;')]";
> ```

Worth testing that it does NOT contain font-size: smaller (since an easy mistake would be to concatenate the two style lists)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1448#-:-Kbqo1IHkI4JHyafO0Ac:b2848r7)*

**Comment by gmartin7** [comment]
Review status: 6 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/BloomExe/Book/HtmlDom.cs, line 732 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1448#-KbqjuHqzfEN4m5qkbdf:-KbuanbUadBhtB_1x21K:b-6oaeiw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b2fb6b21b1ee19e21eaf793c992a03698977a03b/src/BloomExe/Book/HtmlDom.cs#L732)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't like this. The name implies it is just getting the element (and leaves one wondering how it is different from GetUserModifiedStyleElement), but it actually has (potentially) side effects modifying the document! That is in the (unlikely) event that the element contains styles whose names don't properly end in -style. If we really have to do this, it would be better to have a routine with a name like 'RepairUserModifiableStyles' and call it on the element obtained from GetUserModifiedStyleElement.
A comment explaining why we anticipate and must remove such styles would be helpful.
</blockquote></details>

Actually this points out a confusion in the tests. I need to fix the tests.
This method (in production) is only used on the page DOM being inserted into a book by the Add Page/Change Layout dialog. I've put more comments in this method to explain the situation.
It returns a filtered set of user-modifiable styles that are actually used on the page being inserted.

---

*[src/BloomExe/Book/HtmlDom.cs, line 819 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1448#-Kbql0sRoIQSfNgVBQRb:-KbuWGxCgcI5Jh2phC35:b-l05oj0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b2fb6b21b1ee19e21eaf793c992a03698977a03b/src/BloomExe/Book/HtmlDom.cs#L819)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Can't a style rule spread over more than one line? (Of course the ones Bloom generates probably don't...is it safe to rely on that?) I'm willing to be persuaded as long as you've considered it...
</blockquote></details>

I'm certainly glad I switched to THIS method of sorting out the styles! On an earlier pass I was splitting on period... which didn't take into account things like "line-height: 1.5"! Bloom does generate some fairly long styles, but they are all on the same line (as far as CRLF and other OS versions of line endings go). I suppose we could have problems if someone went hand-editing their styles... just in case, this latest version handles multi-line styles.

---

*[src/BloomExe/Edit/EditingModel.cs, line 294 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1448#-Kbjmsr0i2qXgSBHNcca:-KbuXTeyY4XSb4fMzYUl:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8f75bea123966c867b0f4e83c071cdaaa2ecb9d3/src/BloomExe/Edit/EditingModel.cs#L294)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Right. We need to create one element with all the user styles in it.
</blockquote></details>

Done.

---

*[src/BloomExe/web/controllers/AddOrChangePageApi.cs, line 104 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1448#-KbqnJarVgWUBOZcSsL4:-KbuXg8r-1HievTqtnik:b-lsbvd2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b2fb6b21b1ee19e21eaf793c992a03698977a03b/src/BloomExe/web/controllers/AddOrChangePageApi.cs#L104)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It surprises me that the template page has a user-defined styles section. I thought this was typically per-book? After all we expect style definitions to be consistent across the pages.
I expect you have checked that this does get some user-defined styles from the template; otherwise the new code would not be working at all.
Have you checked that it doesn't just get a copy of all the user-defined styles in the template book? It would be unfortunate if we copy in styles not actually used on this page. (Earlier comments make me think you've thought about this...just checking.)
</blockquote></details>

The Arithmetic template book has a user-defined styles section that includes a .Equation-style rule. The HtmlDom for the Page inherits the same <head> element. (Otherwise book-level styles would never work on the page.)

GetUserModifiableStylesUsedOnPage() compares the styles in the <head> user-defined styles section with the ones in the class attributes in the Pages DOM <body> to see which need to be copied over to the new book.

In fact, the changes to the .pug files in this last commit avoid the situation we had where the Arithmetic.htm file had 2 user-defined <style> elements! One had the standard .BigWords style and the other had the .Equation style that was imperative for this template.

---

*[src/BloomTests/Book/HtmlDomTests.cs, line 580 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1448#-Kbqlos15pZ6omVFfffF:-KbumZdl-cDBAF4_v_SB:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b2fb6b21b1ee19e21eaf793c992a03698977a03b/src/BloomTests/Book/HtmlDomTests.cs#L580)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Worth testing that it does NOT contain font-size: smaller (since an easy mistake would be to concatenate the two style lists)?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1448)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1448#-:-KbvLWhsJ08OSv2u9ZBh:bnfp4nl)*

**Pull request merged**
