### PR TITLE
BL-7019 Simple Quiz Page cleanup; generate JSON for quiz pages

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3206)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3206)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/templates/template books/Special/simpleComprehensionQuiz.less, line 45 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3206#-LfV3e-kE7VHtKT3Aa71:-LfV3e-l6KE8LK8NcsOT:b2dugql) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/90e24b40305796af8e35527ee97828dcc3061be5/src/BloomBrowserUI/templates/template books/Special/simpleComprehensionQuiz.less#L45)):*
> ```Less
> // The quiz page is formatted with just enough space for each question/answer, so a format button in
> // the usual place on the left overlaps the text annoyingly. So for these pages we move it to the
> // right. (Not sure why that wouldn't always be better.)
> ```

Usually the language name is on the right. We don't show it for quiz pages?

**Review by andrew-polk — COMMENTED** [review]
One question. If that's not an issue, go ahead and merge.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3206#-:-LfV56d_AhKBSMUWv3oI:b-gzwwas)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
Let's wait to merge this till I implement the new idea of using a version number of some sort to control hiding smart pages in Bloom 1.X

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3206#-:-LfV5OAd-uhgKFoNEdfn:b-eijiey)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/templates/template books/Special/simpleComprehensionQuiz.less, line 45 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3206#-LfV3e-kE7VHtKT3Aa71:-LfV5n2GDRhLNSfmLFeM:bm8yaeu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/90e24b40305796af8e35527ee97828dcc3061be5/src/BloomBrowserUI/templates/template books/Special/simpleComprehensionQuiz.less#L45)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Usually the language name is on the right. We don't show it for quiz pages?
</blockquote></details>

Yes, we do, and the mock-up shows the  language name moving over to make room for the format button, and I haven't made that happen yet. Sigh.

**Review by JohnThomson — COMMENTED** [review]
Latest version now has the attribute required for BR1

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3206#-:-LfVHQyK6hsARGxkBoxx:b2e8ui0)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/templates/template books/Special/simpleComprehensionQuiz.less, line 45 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3206#-LfV3e-kE7VHtKT3Aa71:-LfVHGC09abY4JtFzjQL:bmuwneq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/90e24b40305796af8e35527ee97828dcc3061be5/src/BloomBrowserUI/templates/template books/Special/simpleComprehensionQuiz.less#L45)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Yes, we do, and the mock-up shows the  language name moving over to make room for the format button, and I haven't made that happen yet. Sigh.
</blockquote></details>

OK, with the latest version the label will move over (and, per another of JohnH's requests, be hidden in boxes without the cog).

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3206)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
