### PR TITLE
Improve reporting when we can't update a support file (BL-11863)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/Utils/MiscUtils.cs` line 168 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615#-NNN7AvgA_5TOF36EGMT:-NNN7AvgA_5TOF36EGMU:b-pgpuhm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/1436e5ac5da4b26bf00ccbb2b62f442340beb8cb/src/BloomExe/Utils/MiscUtils.cs#L168)):*
> ```Smalltalk
> 						}
> 					}
> 				}
> ```

I think we can extract most of this logic to a common method which is used by `InstalledAntivirusPrograms()` and `InstalledAntivirusProgramNames()`.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/BookStorage.cs` line 2350 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615#-NNNIUu230gmz3CHTiyO:-NNNIUu230gmz3CHTiyP:bk1nsyd) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/1436e5ac5da4b26bf00ccbb2b62f442340beb8cb/src/BloomExe/Book/BookStorage.cs#L2350)):*
> ```Smalltalk
> 					$"Could not update one of the support files in this document ({documentPath} from {factoryPath}).");
> 				var avProgs = MiscUtils.InstalledAntivirusProgramNames();
> 				var shortMsg = "Can't Update Support File. ";
> ```

1) `shortMsg`: How about "Bloom can not update a file"
2) We should Localize all this

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomExe/Book/BookStorage.cs` line 2350 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615#-NNNIUu230gmz3CHTiyO:-NNbJ4D81_S16y_krHm3:bjqb28i) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/1436e5ac5da4b26bf00ccbb2b62f442340beb8cb/src/BloomExe/Book/BookStorage.cs#L2350)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

1) `shortMsg`: How about "Bloom can not update a file"
2) We should Localize all this
</blockquote></details>

I've localized the bits that the normal user sees, not all the stuff we put in the log.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`src/BloomExe/Book/BookStorage.cs` line 2361 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615#-NNbbhaWAswpXCQ8JVc4:-NNbbhaWAswpXCQ8JVc5:b-gw769o) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/164f72cac603b62a5a553f9007d82275d30e1e7b/src/BloomExe/Book/BookStorage.cs#L2361)):*
> ```Smalltalk
> 				// We probably want this eventually to be showSendReport:false, but don't currently have an
> 				// acceptable UI for when that is false and we are showing a dialog rather than a toast.
> 				NonFatalProblem.Report(ModalIf.All, PassiveIf.All, shortMsg, msg, e, showSendReport:true, showRequestDetails:true);
> ```

If I understood, there is still a question of whether this is the correct API to be using.
The one I was thinking of was NotifyUserOfProblem but I don't see a way to optionally add the report button, so I'm not sure if that is the right one.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomExe/Book/BookStorage.cs` line 2361 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615#-NNbbhaWAswpXCQ8JVc4:-NNbh9Rq8MSwQWVf1MSz:bm5u7os) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/164f72cac603b62a5a553f9007d82275d30e1e7b/src/BloomExe/Book/BookStorage.cs#L2361)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If I understood, there is still a question of whether this is the correct API to be using.
The one I was thinking of was NotifyUserOfProblem but I don't see a way to optionally add the report button, so I'm not sure if that is the right one.
</blockquote></details>

Yes, that works. You have to use our modified version (BloomErrorReport) to get the report button control. (Downside: no way to see the details, unless you know how to find the log file.)
___
*[`src/BloomExe/Utils/MiscUtils.cs` line 168 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615#-NNN7AvgA_5TOF36EGMT:-NNbhH9W1oYnrVp4T48-:bfn0ug3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/1436e5ac5da4b26bf00ccbb2b62f442340beb8cb/src/BloomExe/Utils/MiscUtils.cs#L168)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think we can extract most of this logic to a common method which is used by `InstalledAntivirusPrograms()` and `InstalledAntivirusProgramNames()`.
</blockquote></details>

Done as best I could

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`src/BloomExe/Book/BookStorage.cs` line 2354 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615#-NNc3Yno9TvCm32td_iN:-NNc3Yno9TvCm32td_iO:bwv0yf2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2d98d5b5d88531c777a1a6ebf8e7a39c8ab78767/src/BloomExe/Book/BookStorage.cs#L2354)):*
> ```Smalltalk
> 				var shortMsg = LocalizationManager.GetString("Errors.CannotUpdateFile", "There was a problem updating a support file");
> 
> 				var toast = new ToastNotifier();
> ```

I know you're sick of this change with all the modifications. So I'll not push this if you just want to merge. 

But if you agree it is an improvement worth making, we are probably ready for a wrapper around this logic.
I.e. We should a method we can call which toasts and then launches NotifyUserOfProblem on click.

Another benefit is keeping UI logic out of BookStorage. Now that I think of that... I'd probably push a bit more.... : )
So the method would be called something like UnobtrusivelyNotifyUser
___
*[`src/BloomExe/Book/BookStorage.cs` line 2377 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615#-NNc3RXh4RfD7C2FyIFY:-NNc3RXh4RfD7C2FyIFZ:bpuyaqn) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2d98d5b5d88531c777a1a6ebf8e7a39c8ab78767/src/BloomExe/Book/BookStorage.cs#L2377)):*
> ```Smalltalk
> 
> 					// Previously used this, but don't currently have an
> 					// acceptable UI for when that is false and we are showing a dialog rather than a toast.
> ```

This comment is now outdated (we do show a toast).



_Code quote:_
```Smalltalk
					// Previously used this, but don't currently have an
					// acceptable UI for when that is false and we are showing a dialog rather than a toast.
```

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`DistFiles/localization/en/Bloom.xlf` line 2830 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615#-NNc5T-VCqngrfvG1ebj:-NNc5T-VCqngrfvG1ebk:bn25b99) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/39fcd2a57d670e47823ae5cd63eaa69d0e90484a/DistFiles/localization/en/Bloom.xlf#L2830)):*
> ```XML
>       </trans-unit>
>       <trans-unit id="Errors.CannotUpdateFileLonger">
>         <source xml:lang="en">Bloom was not able to update a support file named "{0}". This is usually not a problem. If you continue to see these messages, see "{1}"</source>
> ```

Personally, I would add a period at the end of the second setence.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomExe/Book/BookStorage.cs` line 2354 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615#-NNc3Yno9TvCm32td_iN:-NNcBipG6TeLgPud96qC:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2d98d5b5d88531c777a1a6ebf8e7a39c8ab78767/src/BloomExe/Book/BookStorage.cs#L2354)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I know you're sick of this change with all the modifications. So I'll not push this if you just want to merge. 

But if you agree it is an improvement worth making, we are probably ready for a wrapper around this logic.
I.e. We should a method we can call which toasts and then launches NotifyUserOfProblem on click.

Another benefit is keeping UI logic out of BookStorage. Now that I think of that... I'd probably push a bit more.... : )
So the method would be called something like UnobtrusivelyNotifyUser
</blockquote></details>

Done.
___
*[`src/BloomExe/Book/BookStorage.cs` line 2377 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615#-NNc3RXh4RfD7C2FyIFY:-NNcBkyRA0FDDUQyuxXZ:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2d98d5b5d88531c777a1a6ebf8e7a39c8ab78767/src/BloomExe/Book/BookStorage.cs#L2377)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This comment is now outdated (we do show a toast).
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`src/BloomExe/Book/BookStorage.cs` line 2354 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615#-NNc3Yno9TvCm32td_iN:-NNcCmt-AXH-d8v_UK5X:b-ucfkn4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2d98d5b5d88531c777a1a6ebf8e7a39c8ab78767/src/BloomExe/Book/BookStorage.cs#L2354)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks.
___
*[`src/BloomExe/Book/BookStorage.cs` line 2358 at r6](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615#-NNcCeqhBeyWm1QxDibY:-NNcCeqhBeyWm1QxDibZ:b8tmzfl) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ee9a0d8e2a0f03de866639277d44586ec4d27bb1/src/BloomExe/Book/BookStorage.cs#L2358)):*
Sorry; I just realized this doesn't match JH's comment on Zulip:
> Where that last is a hyperlink to a page on docs.blorg.



_Code quote:_
```Smalltalk
https://community.software.sil.org/t/when-bloom-is-prevented-from-changing-png-image-files/4445
```

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`DistFiles/localization/en/Bloom.xlf` line 2830 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615#-NNc5T-VCqngrfvG1ebj:-NOz9aAD-Wbrl-o8dfDr:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/39fcd2a57d670e47823ae5cd63eaa69d0e90484a/DistFiles/localization/en/Bloom.xlf#L2830)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Personally, I would add a period at the end of the second setence.
</blockquote></details>

Done.
___
*[`src/BloomExe/Book/BookStorage.cs` line 2358 at r6](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615#-NNcCeqhBeyWm1QxDibY:-NOz9dFq-OEkDpY2_K4t:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ee9a0d8e2a0f03de866639277d44586ec4d27bb1/src/BloomExe/Book/BookStorage.cs#L2358)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; I just realized this doesn't match JH's comment on Zulip:
> Where that last is a hyperlink to a page on docs.blorg.
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`DistFiles/localization/en/Bloom.xlf` line 2830 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615#-NNc5T-VCqngrfvG1ebj:-NOzA2Jh3UPAC5t0s_Fq:buceqfo) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/39fcd2a57d670e47823ae5cd63eaa69d0e90484a/DistFiles/localization/en/Bloom.xlf#L2830)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I see the change in the .cs file, but not the .xlf file.
Then, LGTM.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`DistFiles/localization/en/Bloom.xlf` line 2830 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615#-NNc5T-VCqngrfvG1ebj:-NOzCwxh4PoglZ08zyr-:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/39fcd2a57d670e47823ae5cd63eaa69d0e90484a/DistFiles/localization/en/Bloom.xlf#L2830)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I see the change in the .cs file, but not the .xlf file.
Then, LGTM.
</blockquote></details>

Done.



_Code quote:_
```XML
Bloom was not able to update
```

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Review by andrew-polk — APPROVED** [review]
> Dismissed @hatton from a discussion.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Review by andrew-polk — APPROVED** [review]
> Dismissed @JohnThomson from a discussion.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5615)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
