### PR TITLE
Finish initial minimal Book Settings dialog (BL-12130)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6156)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6156)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 330 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6156#-Nh3igdREWJYTU5tgZRb:-Nh3igdREWJYTU5tgZRc:b4kfu17) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b6cbf6c54768632c5dbd0dbd25e3b95d28336f79/DistFiles/localization/en/BloomMediumPriority.xlf#L330)):*
> ```XML
>         <source xml:lang="en">BloomPUB</source>
>         <note>BookSettings.BloomPub</note>
>         <note>I'm not sure whether this can/should be translated.  It's used as the heading of a section of the dialog.</note>
> ```

Should not

**Review by hatton — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6156)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6156)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 78 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6156#-Nh3jbdM-n9u4mqn8Djl:-Nh3jbdN0Wb0VRbdFtyM:b-7go6c7) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b6cbf6c54768632c5dbd0dbd25e3b95d28336f79/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L78)):*
> ```XML
> 
>     const bookSettingsTitle = useL10n("Book Settings", "BookSettings.Title");
>     const bloomPubLabel = useL10n("BloomPUB", "BookSettings.BloomPub");
> ```

We don't translate BloomPub

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6156)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 78 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6156#-Nh3jbdM-n9u4mqn8Djl:-Nh3jrPSB7B1p2WPTLHi:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b6cbf6c54768632c5dbd0dbd25e3b95d28336f79/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L78)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

We don't translate BloomPub
</blockquote></details>

Done.

**Review by hatton — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6156)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Comment by andrew-polk** [comment]
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 357 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6156#-Nh3lcQW5oINN_q28vZ4:-Nh3lcQW5oINN_q28vZ5:b-32bk1h) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c3f71679d36904be86d0fe3b9256f6b7f13cc0af/DistFiles/localization/en/BloomMediumPriority.xlf#L357)):*
> ```XML
>       </trans-unit>
>       <trans-unit id="BookSettings.BloomPub.Resolution.Directions" sil:dynamic="true" translate="no">
>         <source xml:lang="en">Set the maximum image resolution when making BloomPubs (including display on BloomLibrary)</source>
> ```

Should be BloomPUB.
Same for usage in tsx.

**Pull request merged**
