### PR TITLE
BL-9320 Repair comic book pages

### PR DESCRIPTION
**Pull request by gmartin7**
* update existing books with comic pages

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4277)

### CODE REVIEW

**Comment by hatton** [comment]
What's our motivation for not letting `comic` continue to trigger the needed rule?

**Review by gmartin7 — COMMENTED** [review]
`comic` continues to trigger black background and other comic book things, but `no-margin-page` now triggers the change in marginBox (and hiding the page number) so that the custom Widget template can use that and not have black background, etc. where it is not part of a Digital Comic Book.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4277#-:-MVY1RTZBw3CXBqvQciM:b-oxqydl)* status: 0 of 2 files reviewed, all discussions resolved

**Comment by hatton** [comment]
Yeah that's an explanation, not motivation. Your current `.no-margin-page` selector can become `.no-margin-page,.comic`, and then no new c# code (which must be run forever) is needed.

**Review by gmartin7 — COMMENTED** [review]
Ah! I see. Yes, that's better.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4277#-:-MVY2k4v81z-qpC86HTP:bayscq1)* status: 0 of 2 files reviewed, all discussions resolved

**Comment by gmartin7** [comment]
Closing in favor of a better PR.

**Pull request closed without merging**
