### PR TITLE
Fix BL-3153 where browser asked for audio file before it was written

### PR DESCRIPTION
**Pull request by hatton**
On at least my machine, it was never possible to record something and play it back without switching pages. The reason is that at the end of the recording, the javascript would signal the html audio element that the source had changed. That would immediately hit the server up for the new file, but meanwhile the thread writing that file was still working on it. I tried various approaches but the cleanest ended up just telling the audio element not to preload the audio... just get it when the user clicks on "play".

In the process, I added some error handling around getting files, returning appropriate http codes.

[Review on Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/948)

### CODE REVIEW

**Comment by JohnThomson** [comment]
I don't know why I didn't experience this problem...I frequently recorded and played immediately afterwards without changing pages!

Anyway, I was previously using the preload to disable the Play button if necessary when the sentence becomes active. (IIRC it is enabled and its src changed when the current sentence changes, including when opening the page, and disabled if we get a notification that the file is missing.) So if you care about that behavior something new might be needed to reinstate it.
Possibly it's only when we start recording that we need to set preload to none, leave it that way when we enable the button at end of recording, but remove preload=none when changing the src for a different sentence?

Also check whether you will inappropriatly enable 'Play' if the user does a too-short click and so doesn't get a recording (but I think the endRecordCurrent event may still fire).

LGTM if neither of those is a problem.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/948#-:-KB9PlqVeSPyNKf2131u:-1608549058)*

**Comment by hatton** [comment]
OK, I wired the status of play and clear to whether the server can find the file.

---

Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/948#-:-KBFX2OStH0e_yUajqyI:-513769061)*

**Comment by JohnThomson** [comment]
Looks good as far as it goes, though if the server was on the other end of a network it would be a shame to pull the whole audio file down just to find out whether it is there.
I don't see any changes in the after-record-button-up code, though. At that point we need to adjust the enabling again (remembering that if it was too short a click, we may NOT have gotten a recording).

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/948#-:-KBIhBZ1-5JWTYVriDu2:-928678675)*

**Comment by JohnThomson** [comment]
I suppose it might be OK to just enable them after record,as you probably already do. The user will see a dialog if he did a too-short click, and will soon learn not to, and is fairly unlikely to try to Play right after being told he didn't do the recording right, and I don't think anything bad will happen if he does try.
One more thought: I'm surprised you don't need to do something to prevent that new Debug-only-file-not-found message from coming up every time you look for a missing recording.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/948#-:-KBIiKgc1bJLxyQlT6k0:-699903791)*

**Comment by hatton** [comment]
I want to return to the too-short thing, but I'm struggling with all the outstanding bits of this. I need it all merged and then we'll take stock.

**Pull request merged**
