### PR TITLE
Check for LAN sharing when checking Dropbox access (BL-10272)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4670)

### CODE REVIEW

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4670)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 1027 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4670#-MhVYmuz651_SjhRrPuy:-MhVYmuz651_SjhRrPuz:bh0ae3d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d6b2729be87d1afd63212cdfdde516d962d5e9c7/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L1027)):*
> ```Smalltalk
> 		}
> 
> 		private bool IsFolderOnLocalNetwork(string repoFolderPath)
> ```

Is there any way any of this could throw an exception? And if it did, what would happen?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4670)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 1027 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4670#-MhVYmuz651_SjhRrPuy:-MhZbsRl1dF2NWnhGk1a:b-f9n2j3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d6b2729be87d1afd63212cdfdde516d962d5e9c7/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L1027)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is there any way any of this could throw an exception? And if it did, what would happen?
</blockquote></details>

I've added a try-catch block around this code.  I doubt an exception would happen, but it's technically possible for a security exception to be thrown by the ManagementObject related functions.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4670)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 1068 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4670#-Mh_4mh-9xrqaSsOhZTa:-Mh_4mh-9xrqaSsOhZTb:b3lql3y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/170ade5fbb5c1d7c22b73e437832cfe9879d5c2d/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L1068)):*
> ```Smalltalk
> 			catch (Exception e)
> 			{
> 				Debug.WriteLine($"Caught exception in IsFolderOnLocalNetwork(\"{repoFolderPath}\"): {e}");
> ```

Should this be a sentry call?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4670)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 1068 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4670#-Mh_4mh-9xrqaSsOhZTa:-Mh_BoKI0jZFCj7P-50j:b-jsn211) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/170ade5fbb5c1d7c22b73e437832cfe9879d5c2d/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L1068)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Should this be a sentry call? 
</blockquote></details>

I don't anticipate any exceptions (which would almost certainly be Security related according the documentation), or that we could do anything useful with the exception information.  But I suppose I could put in a Sentry call if you think we should.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
LGTM but I'd like a little more explanation of one mysterious regular expression.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4670#-:-MiTPT0A4j2AmudB8cXh:bn7rd7n)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 1056 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4670#-MiTOQpe7yNpSui1jjKM:-MiTOQpg2msQMVsAtbEW:bn5tfyg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2d1458b04e74ec33c76932be3d105dba29fc74d8/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L1056)):*
> ```Smalltalk
> 				}
> 				// Check whether the repo folder is actually shared from the network
> 				if (Regex.Match(repoFolderPath, @"^\\{2}[\w-]+(\\{1}(([\w-][\w-\s]*[\w-]+[$$]?)|([\w-][$$]?$)))+").Success)
> ```


I think this deserves some explanation and maybe examples or even test cases (you could make a separate static method so it's easy to test). I tried pasting it into https://regex101.com/ to play with, and it claims that [\w-\s] is not valid...an attempt to make a range out of two shorthands. But apart from the difficulty of reading the RE, can you explain why it is needed? What would make "select * from win32_share" return something that isn't a shared directory? Is there some reference you could refer to for what makes a valid share path?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4670)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 1056 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4670#-MiTOQpe7yNpSui1jjKM:-MibTqU3ABC37ezI7Hht:b6wfxi2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2d1458b04e74ec33c76932be3d105dba29fc74d8/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L1056)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think this deserves some explanation and maybe examples or even test cases (you could make a separate static method so it's easy to test). I tried pasting it into https://regex101.com/ to play with, and it claims that [\w-\s] is not valid...an attempt to make a range out of two shorthands. But apart from the difficulty of reading the RE, can you explain why it is needed? What would make "select * from win32_share" return something that isn't a shared directory? Is there some reference you could refer to for what makes a valid share path?
</blockquote></details>

I copied the RE from somewhere.  (I added a reference.)  I've now adjusted the RE in a couple of places, including the one you found and commented on its structure.
The loop looking at results from "select * from win32_share" is testing for a local folder that we've shared with other people.  The RE and following checks for for folders that other people have shared with us.  I thought my comments made that clear, but obviously not clear enough.  I reworded the comment slightly to emphasize this point.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4670)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton)

**Pull request merged**
