### PR TITLE
Show Missing Copyright notice when appropriate (BL-10360)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5419)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5419)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`DistFiles/localization/en/Bloom.xlf` line 1175 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5419#-ND429yvDRqXm41JlA9O:-ND429yw6DU5xSPVwZqs:baoqnja) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/698021569455f42d81c52679936d04b6cbbfb407/DistFiles/localization/en/Bloom.xlf#L1175)):*
> ```XML
>       <trans-unit id="Copyright.MissingCopyright">
>         <source xml:lang="en">Missing Copyright</source>
>         <note>ID: Copyright.NotATranslation</note>
> ```

copy/paste error



_Code quote:_
```XML
Copyright.NotATranslation
```
___
*[`src/BloomExe/Edit/EditingModel.cs` line 810 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5419#-ND42UM3CnE3uVEFmp6m:-ND42UM3CnE3uVEFmp6n:biy2kyx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/698021569455f42d81c52679936d04b6cbbfb407/src/BloomExe/Edit/EditingModel.cs#L810)):*
> ```Smalltalk
> 			// But that situation is not currently possible through our UI, and further thought
> 			// suggests we want to know who says it is CC0. So commenting that aspect out.
> 			var copyRightOk = metadata.IsMinimallyComplete; // || metadata.License?.Token == "cc0";
> ```

(since you have to make a change anyway...)
This would be better without the capital R



_Code quote:_
```Smalltalk
copyRightOk
```

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5419)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5419)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/Bloom.xlf` line 1175 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5419#-ND429yvDRqXm41JlA9O:-ND47dTd88yWHQuD1l3b:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/698021569455f42d81c52679936d04b6cbbfb407/DistFiles/localization/en/Bloom.xlf#L1175)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

copy/paste error
</blockquote></details>

Done.
___
*[`src/BloomExe/Edit/EditingModel.cs` line 810 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5419#-ND42UM3CnE3uVEFmp6m:-ND47cqO1l8N_1tJhMOA:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/698021569455f42d81c52679936d04b6cbbfb407/src/BloomExe/Edit/EditingModel.cs#L810)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

(since you have to make a change anyway...)
This would be better without the capital R
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5419)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
