### PR TITLE
Fix BL-2887 migration code should not mess with data-page attribute

### PR DESCRIPTION
**Pull request by hatton**
Since September, every non-xmatter page was migrated and the data-page attribute was set to 'extra'. When any such book is used then as a shell those pages disappear forever.

This PR stops it from doing that, but we will require a followup commit to heal all the books that have been broken by this.

[Review on Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/858)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[src/BloomExe/Book/HtmlDom.cs, line 625 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/858#-K2w7vKyKlmaYs8K8GKQ)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a397259b933ebf8a32c0b8253b35e3d1a0e4ebd/src/BloomExe/Book/HtmlDom.cs#L625)):</sup>
The comment here looks incomplete


---

<sup>**[src/BloomTests/Book/PageMigrationTests.cs, line 349 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/858#-K2w8qzvNSUZbQVv5cEI)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a397259b933ebf8a32c0b8253b35e3d1a0e4ebd/src/BloomTests/Book/PageMigrationTests.cs#L349)):</sup>
Some version of this comment should be in the main code, I think.


---

<sup>**[src/BloomTests/Book/PageMigrationTests.cs, line 375 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/858#-K2w8TtSwZWTM-fEL23s)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a397259b933ebf8a32c0b8253b35e3d1a0e4ebd/src/BloomTests/Book/PageMigrationTests.cs#L375)):</sup>
Seems there should be another test for the case where the original (non-template) page has a NON-empty data-page (showing that it is preserved), though that may be less important.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/858)

**Comment by hatton** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[src/BloomExe/Book/HtmlDom.cs, line 625 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/858#-K2w7vKyKlmaYs8K8GKQ)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a397259b933ebf8a32c0b8253b35e3d1a0e4ebd/src/BloomExe/Book/HtmlDom.cs#L625)):</sup>
thx


---

<sup>**[src/BloomTests/Book/PageMigrationTests.cs, line 349 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/858#-K2w8qzvNSUZbQVv5cEI)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a397259b933ebf8a32c0b8253b35e3d1a0e4ebd/src/BloomTests/Book/PageMigrationTests.cs#L349)):</sup>
Not clear what the main code is, but the unfinished comment you mentioned above addresses this.  This is also addressed in the [Bloom Format documentation document](https://docs.google.com/document/d/16M8Fvt1SLYgUX5UbWy3q9s2_ab0Ni39mVumtIYzxKm4)


---

<sup>**[src/BloomTests/Book/PageMigrationTests.cs, line 375 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/858#-K2w8TtSwZWTM-fEL23s)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a397259b933ebf8a32c0b8253b35e3d1a0e4ebd/src/BloomTests/Book/PageMigrationTests.cs#L375)):</sup>
Alas, I can't think of any template books we migrate to that have such a page. If that's true, the issue can never come up.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/858)

**Comment by hatton** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[src/BloomExe/Book/HtmlDom.cs, line 625 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/858#-K2w7vKyKlmaYs8K8GKQ)** ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9a397259b933ebf8a32c0b8253b35e3d1a0e4ebd/src/BloomExe/Book/HtmlDom.cs#L625)):</sup>
I pushed a full comment for this


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/858)

**Comment by JohnThomson** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/BloomExe/Book/HtmlDom.cs, line 617 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/858#-K3Kqhd_rJeaMW3WLXPk:-K3Kqhd_rJeaMW3WLXPl:205747331) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/82934ff123a4197b5e2726318d374260980945ed/src/BloomExe/Book/HtmlDom.cs#L617)):_
It's about here that I was thinking it might be helpful to emphasize that the template data-page='extra' is something that would
normally be removed in the process of using the template to make a real page, and is therefore inappropriate to copy from
the template to the migrated page, because it will stop the page appearing in any localizations. Maybe that's overkill...maybe we
all need to review that Bloom format documentation document more often. I've been working on Bloom for about 2 years, and
had no idea that data-page-'extra' existed, much less what it signified, so it seems to me unlikely that someone reading this
will easily figure out why this one attribute should not be taken from the template.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/858)_

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/BloomExe/Book/HtmlDom.cs, line 617 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/858#-K3Kqhd_rJeaMW3WLXPk:-K3_JG4e7Jorc7JkC0yP:-37119373) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/82934ff123a4197b5e2726318d374260980945ed/src/BloomExe/Book/HtmlDom.cs#L617)):_
Yeah, and I would say that at that point, I hope the developer would say to his/her self... Hmm. Just reading this bit of code is apparently not enough. Maybe I should do a global search on this "extra" tag and see how it works. Or maybe I should make sure I have a command of the documentation before I work in this area :-) I'm just a lot less inclined to explain everything in comments, and instead more inclined than others to reduce entropy in the code wherever possible by improving architecture, structure, clarity, naming, etc.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/858)_

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/BloomExe/Book/HtmlDom.cs, line 617 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/858#-K3Kqhd_rJeaMW3WLXPk:-K3auND2VG_JOFf-CiSN:1361346627) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/82934ff123a4197b5e2726318d374260980945ed/src/BloomExe/Book/HtmlDom.cs#L617)):_
And of course the place where things really fell down is that I left this out altogether because I had no idea there was something special about the 'extra' tag. You can't comment the absence of something (except in a place where it's really obvious it might be expected).
In principle I agree with you that comments should be a last resort and other ways of improving the code are to be preferred. I can live without more comment here.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/858)_

**Pull request merged**
