### PR TITLE
BL-5393 animation control

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2047)

### CODE REVIEW

**Comment by andrew-polk** [comment]
A few notes, but looks good overall. I won't pretend I evaluated any of the math or the real guts of the new code, though.

---

Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/animationControl/animationControl.less, line 1 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2047#-L2RUMTxVHIe82mUPuz1:-L2RUMTxVHIe82mUPuz2:b-tku6id) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/58ec5321790b89cc330e79254217e0b34bbab608/src/BloomBrowserUI/bookEdit/toolbox/animationControl/animationControl.less#L1)):*
> ```Less
> @textColor: #D2D2D2;// #0C8597;
> ```

Can this make better use of the new stuff Gordon did to extract colors and name them?

---

*[src/BloomBrowserUI/bookEdit/toolbox/animationControl/animationControl.ts, line 2 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2047#-L2RUU5R7zjFFauY0bXM:-L2RUU5R7zjFFauY0bXN:b-4rd9mr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/58ec5321790b89cc330e79254217e0b34bbab608/src/BloomBrowserUI/bookEdit/toolbox/animationControl/animationControl.ts#L2)):*
> I've called in

I've called it

(If you're making changes anyway...)

---

*[src/BloomBrowserUI/bookEdit/toolbox/animationControl/animationControl.ts, line 190 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2047#-L2RVcHOsjsGPTcPtyMp:-L2RVcHOsjsGPTcPtyMq:b-r011sy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/58ec5321790b89cc330e79254217e0b34bbab608/src/BloomBrowserUI/bookEdit/toolbox/animationControl/animationControl.ts#L190)):*
> ```XML
>     private wrapperClassName = "bloom-ui-animationWrapper";
> 
>     previewAnimation() {
> ```

I guess there is no good way to share code with bloomPlayer?

---

*[src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug, line 13 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2047#-L2RW3x16prJSWpGKILt:-L2RW3x16prJSWpGKILu:bwnhhjm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/58ec5321790b89cc330e79254217e0b34bbab608/src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug#L13)):*
> ```Pug
> 			.checkbox-label(data-i18n='EditTab.Toolbox.LeveledReaderTool') Leveled Reader Tool
> 			.checkbox.clear#animationControlCheck(data-panel='animationControlTool', onclick='FrameExports.showOrHidePanel_click(this);')
> 			.checkbox-label(data-i18n='EditTab.Toolbox.AnimationControlTool') Animation Control Tool
> ```

I think this got missed when adding strings to Bloom.xlf

---

*[src/BloomExe/Book/BloomReaderFileMaker.cs, line 52 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2047#-L2RWovR0tGaiXpKbrqI:-L2RWovR0tGaiXpKbrqJ:bupt4hp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/58ec5321790b89cc330e79254217e0b34bbab608/src/BloomExe/Book/BloomReaderFileMaker.cs#L52)):*
> ```Smalltalk
> 			modifiedBook.RemoveBlankPages();
> 
> 			modifiedBook.SetAnimationDurationsFromAudioDurations();
> ```

Do we need to do this for web-published book, too? (Eventually, IMS's Story Producer app will consume raw Bloom books and will need to know this information.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2047#-:-L2RXywbxzgrcSc7D40Y:b-rjzxhf)*

**Comment by JohnThomson** [comment]
Responded to notes.
I think if any of the detailed math was wrong, it would show up pretty quickly in testing.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/animationControl/animationControl.less, line 1 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2047#-L2RUMTxVHIe82mUPuz1:-L2Wr1iwhlsOkNL8bb_y:bkfuwzz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/58ec5321790b89cc330e79254217e0b34bbab608/src/BloomBrowserUI/bookEdit/toolbox/animationControl/animationControl.less#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Can this make better use of the new stuff Gordon did to extract colors and name them?
</blockquote></details>

Done. (It was not yet merged when I worked on this)

---

*[src/BloomBrowserUI/bookEdit/toolbox/animationControl/animationControl.ts, line 2 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2047#-L2RUU5R7zjFFauY0bXM:-L2Wr8zk6QO07Ehxdukm:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/58ec5321790b89cc330e79254217e0b34bbab608/src/BloomBrowserUI/bookEdit/toolbox/animationControl/animationControl.ts#L2)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> I've called in

I've called it

(If you're making changes anyway...)
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/animationControl/animationControl.ts, line 190 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2047#-L2RVcHOsjsGPTcPtyMp:-L2WsHLpZ30K1xnB9jes:b-5ranu3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/58ec5321790b89cc330e79254217e0b34bbab608/src/BloomBrowserUI/bookEdit/toolbox/animationControl/animationControl.ts#L190)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I guess there is no good way to share code with bloomPlayer?
</blockquote></details>

I don't see one. I've added some comments calling attention to the similarity and noting some important differences.

---

*[src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug, line 13 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2047#-L2RW3x16prJSWpGKILt:-L2Wt73fHcvOs9ekk3Ey:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/58ec5321790b89cc330e79254217e0b34bbab608/src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug#L13)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this got missed when adding strings to Bloom.xlf
</blockquote></details>

Done.

---

*[src/BloomExe/Book/BloomReaderFileMaker.cs, line 52 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2047#-L2RWovR0tGaiXpKbrqI:-L2Wt9AYajSFJOe-Hlrg:bzhm6zy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/58ec5321790b89cc330e79254217e0b34bbab608/src/BloomExe/Book/BloomReaderFileMaker.cs#L52)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Do we need to do this for web-published book, too? (Eventually, IMS's Story Producer app will consume raw Bloom books and will need to know this information.)
</blockquote></details>

It's possible that we might one day want to do it when publishing to the web. However, we have a lot of books already out there that don't have it. If at some point some client needs it, we will have to choose between making that client able to figure it out itself, or adding this to our publish process AND fixing all the existing books. In fact, any book that needs this information probably needs the audio too, which we aren't currently publishing to the web, so every book that needs it needs to be republished anyway. Given that, I'm inclined to consider changing it now a case of YAGNI.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2047#-:-L2WuBnc5IlLxPG8niOe:bkwf7q0)*

**Comment by andrew-polk** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/BloomReaderFileMaker.cs, line 52 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2047#-L2RWovR0tGaiXpKbrqI:-L2X-6zSffaPskXXdC-K:bewubij) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/58ec5321790b89cc330e79254217e0b34bbab608/src/BloomExe/Book/BloomReaderFileMaker.cs#L52)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's possible that we might one day want to do it when publishing to the web. However, we have a lot of books already out there that don't have it. If at some point some client needs it, we will have to choose between making that client able to figure it out itself, or adding this to our publish process AND fixing all the existing books. In fact, any book that needs this information probably needs the audio too, which we aren't currently publishing to the web, so every book that needs it needs to be republished anyway. Given that, I'm inclined to consider changing it now a case of YAGNI.
</blockquote></details>

I'm confused by "we have a lot of books already out there that don't have it." There are no published books with animations. I'm probably missing something.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2047)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/BloomReaderFileMaker.cs, line 52 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2047#-L2RWovR0tGaiXpKbrqI:-L2X8o-P7QTTocwVIDHf:b-nkd05r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/58ec5321790b89cc330e79254217e0b34bbab608/src/BloomExe/Book/BloomReaderFileMaker.cs#L52)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm confused by "we have a lot of books already out there that don't have it." There are no published books with animations. I'm probably missing something.
</blockquote></details>

You're right. I suppose I was thinking that we have a good many books published that are marked up with durations on  audio-sentence spans but don't have them consolidated into this field that gives the duration of an animation. The main point, though, is that if we decide to start publishing books with all the information Story Producer will need, there's a lot more to add than this one field, most particularly, the actual audio. So it feels slightly premature to make a change that only meets a small part of the need. It (very marginally) slows down and complicates the web publication process without actually making the books useful to story producer. It's also not clear that Story Producer WILL need this information. It may already be capable of adding up sentence audio lengths to figure out an animation length. Or it may be smarter than Bloom Reader about allowing the user to control gaps between sentences and paragraphs, and the simple summing of the audio narrations may not give the right answer. Maybe I'm just being lazy, but it seems more appropriate to me to leave this until we actually have a scheduled task of publishing books in a form suitable for SP, and have clearly identified the requirements.
OTOH, this field is part of our spec of how the bloom file format handles animation. So maybe we really should make it part of any published version of a bloom book that has animation. If you still think it should be added, I won't argue further, but just do it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2047)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Book/BloomReaderFileMaker.cs, line 52 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2047#-L2RWovR0tGaiXpKbrqI:-L2_cCLe2maa0R2TIAlU:b34aloa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/58ec5321790b89cc330e79254217e0b34bbab608/src/BloomExe/Book/BloomReaderFileMaker.cs#L52)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

You're right. I suppose I was thinking that we have a good many books published that are marked up with durations on  audio-sentence spans but don't have them consolidated into this field that gives the duration of an animation. The main point, though, is that if we decide to start publishing books with all the information Story Producer will need, there's a lot more to add than this one field, most particularly, the actual audio. So it feels slightly premature to make a change that only meets a small part of the need. It (very marginally) slows down and complicates the web publication process without actually making the books useful to story producer. It's also not clear that Story Producer WILL need this information. It may already be capable of adding up sentence audio lengths to figure out an animation length. Or it may be smarter than Bloom Reader about allowing the user to control gaps between sentences and paragraphs, and the simple summing of the audio narrations may not give the right answer. Maybe I'm just being lazy, but it seems more appropriate to me to leave this until we actually have a scheduled task of publishing books in a form suitable for SP, and have clearly identified the requirements.
OTOH, this field is part of our spec of how the bloom file format handles animation. So maybe we really should make it part of any published version of a bloom book that has animation. If you still think it should be added, I won't argue further, but just do it.
</blockquote></details>

Let's talk about it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2047)*

**Pull request merged**
