### PR TITLE
Fix a broken test of sanitized book file/folder names (BL-12261)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5890)

### CODE REVIEW

**Review by jsubloom — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5890)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomTests/Book/BookStorageTests.cs` line 862 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5890#-NWih0Zs0FmFi3Y7zBBc:-NWih0Zs0FmFi3Y7zBBd:bo75rki) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b974f525e2fd88706031db9078c840748d4e03b7/src/BloomTests/Book/BookStorageTests.cs#L862)):*
> ```Smalltalk
> 		{
> 			using (var x = new TemporaryFolder(_folder, "foo"))
> 			using (var y = new TemporaryFolder(_folder, "fo o"))
> ```

Isn't the old test case with multiple spaces an interesting case too?  The test name is also "JunkMidFoo"

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5890)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jsubloom)

___
*[`src/BloomTests/Book/BookStorageTests.cs` line 862 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5890#-NWih0Zs0FmFi3Y7zBBc:-NWijcPK72SSg9NujdJl:b25stmn) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b974f525e2fd88706031db9078c840748d4e03b7/src/BloomTests/Book/BookStorageTests.cs#L862)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

Isn't the old test case with multiple spaces an interesting case too?  The test name is also "JunkMidFoo"
</blockquote></details>

I modified an old test which was producing and expecting a number of consecutive spaces in the new book's file/folder name.  The new behavior is to collapse multiple consecutive spaces to a single space.

**Review by jsubloom — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5890)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomTests/Book/BookStorageTests.cs` line 862 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5890#-NWih0Zs0FmFi3Y7zBBc:-NWim44L-ha2Y9Mz7FeK:b-6uik7) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b974f525e2fd88706031db9078c840748d4e03b7/src/BloomTests/Book/BookStorageTests.cs#L862)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I modified an old test which was producing and expecting a number of consecutive spaces in the new book's file/folder name.  The new behavior is to collapse multiple consecutive spaces to a single space.
</blockquote></details>

Hmm, okay I see my confusion. It looks like y is part of the setting-up the conditions for the test, but it's actually more related to the expected output. I think it should've probably had a better variable name that said something about expectedFolder or whatever, but that's okay.  All right, i think this is fine.

**Review by jsubloom — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5890#-:-NWimLS6CbvXSMXOT1Xw:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by jsubloom — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5890)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @StephenMcConnel)

**Review by jsubloom — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5890)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
