### PR TITLE
BL-11381 Book History improvements

### PR DESCRIPTION
**Pull request by gmartin7**
* added message to "ImportSpreadsheet" history event
* added Bloom version to history events
* added book history to problem report
* moved AddEvent for import into Importer where it will
   get recorded before any error reporting

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5669)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5669)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @gmartin7)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5669#-NPOatcd5rxwyMs9P0_x):*
Is that what we want? If it didn't get imported, why do we want a history event?



_Code quote:_
```
  * moved AddEvent for import into Importer where it will
     get recorded before any error reporting
```
___
*[`src/BloomExe/TeamCollection/BookHistory.cs` line 15 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5669#-NPOc-JxCEBOw_Tu-yN3:-NPOc-JxCEBOw_Tu-yN4:b-ox6usk) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0f54f2b946e451fab8484d580b4c9d8d3a092ca8/src/BloomExe/TeamCollection/BookHistory.cs#L15)):*
> ```Smalltalk
> using SQLite;
> 
> namespace Bloom.TeamCollection
> ```

In the spirit of our discussion this morning, it would improve things to move this out of the TeamCollection namespace.
___
*[`src/BloomExe/TeamCollection/BookHistory.cs` line 93 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5669#-NPOc9PW7O0HQxKrnQuX:-NPOc9PW7O0HQxKrnQuY:b-gdufzv) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0f54f2b946e451fab8484d580b4c9d8d3a092ca8/src/BloomExe/TeamCollection/BookHistory.cs#L93)):*
> ```Smalltalk
> 		}
> 
> 		public static string GetHumanReadableEventType(BookHistoryEventType type)
> ```

This deserves a comment about how we use it; specifically, why don't we care about localization.
___
*[`src/BloomExe/TeamCollection/BookHistory.cs` line 123 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5669#-NPOcXa75OcrL87Z0nJP:-NPOcXa75OcrL87Z0nJQ:b-k91o7b) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0f54f2b946e451fab8484d580b4c9d8d3a092ca8/src/BloomExe/TeamCollection/BookHistory.cs#L123)):*
> ```Smalltalk
> 					break;
> 				default:
> 					throw new ApplicationException("Unknown BookHistoryEventType");
> ```

I don't think we want to crash for this.
At least for its current use, I think `result = type.ToString()` is better.
I'm questioning whether this code is even warranted. For the current use case, having the enum values' ToString() seems sufficient.
___
*[`src/BloomExe/web/controllers/ProblemReportApi.cs` line 798 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5669#-NPOcJsOEUqR-Yz6sMnt:-NPOcJsOEUqR-Yz6sMnu:b2rmvkd) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0f54f2b946e451fab8484d580b4c9d8d3a092ca8/src/BloomExe/web/controllers/ProblemReportApi.cs#L798)):*
> ```Smalltalk
> 				}
> 			}
> 			bldr.AppendLine();
> ```

What do you think of wrapping this method in a try/catch?

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5669)* status: all files reviewed, 5 unresolved discussions (waiting on @gmartin7)

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5669)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[`-- commits` line 8 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5669#-NPOatcd5rxwyMs9P0_x):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is that what we want? If it didn't get imported, why do we want a history event?
</blockquote></details>

The import happens (at least what I've seen), but the progress dialog turns red and there is a Report button. If we put the AddEvent later in the process the Report won't even mention importing from a spreadsheet even though the import happened.
___
*[`src/BloomExe/TeamCollection/BookHistory.cs` line 15 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5669#-NPOc-JxCEBOw_Tu-yN3:-NPOvw2U7hprCmB_CTtH:bxag6cj) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0f54f2b946e451fab8484d580b4c9d8d3a092ca8/src/BloomExe/TeamCollection/BookHistory.cs#L15)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

In the spirit of our discussion this morning, it would improve things to move this out of the TeamCollection namespace.
</blockquote></details>

Will do... in a separate PR.
___
*[`src/BloomExe/TeamCollection/BookHistory.cs` line 93 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5669#-NPOc9PW7O0HQxKrnQuX:-NPOfoXU4b-aT7PsRCwe:bfxu8r4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0f54f2b946e451fab8484d580b4c9d8d3a092ca8/src/BloomExe/TeamCollection/BookHistory.cs#L93)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This deserves a comment about how we use it; specifically, why don't we care about localization.
</blockquote></details>

Done. Deleted the method per below.
___
*[`src/BloomExe/TeamCollection/BookHistory.cs` line 123 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5669#-NPOcXa75OcrL87Z0nJP:-NPOq9gD51sapklqwDxU:b-iov909) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0f54f2b946e451fab8484d580b4c9d8d3a092ca8/src/BloomExe/TeamCollection/BookHistory.cs#L123)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't think we want to crash for this.
At least for its current use, I think `result = type.ToString()` is better.
I'm questioning whether this code is even warranted. For the current use case, having the enum values' ToString() seems sufficient.
</blockquote></details>

Done. Hey Cool! I thought the `.ToString()` of an enum was just an integer! I learned something.
___
*[`src/BloomExe/web/controllers/ProblemReportApi.cs` line 798 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5669#-NPOcJsOEUqR-Yz6sMnt:-NPOrfwUB1W4luez47xa:b-hhc5cq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0f54f2b946e451fab8484d580b4c9d8d3a092ca8/src/BloomExe/web/controllers/ProblemReportApi.cs#L798)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What do you think of wrapping this method in a try/catch?
</blockquote></details>

Done. Also did JH's small format changes.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5669)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
