### PR TITLE
Enhance USB/MTP transfer with better logging (BL-4770)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1786)

### CODE REVIEW

**Comment by JohnThomson** [comment]
I think overall it would already be an improvement, but I think it can be better. Especially disconnecting the event handlers feels wrong, until we leave this publish-to-android-on-USB state altogether.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/Communication/AndroidDeviceUsbConnection.cs, line 140 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1786#-Kr6jc9CMDmWn5EzAjmb:-Kr6jc9DmyH_tVAPYoRX:bt3hmwm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/14e7ce16d9da784203230698b47ae65d660854d2/src/BloomExe/Communication/AndroidDeviceUsbConnection.cs#L140)):*
> ```Smalltalk
> 					applicableDevices.Select(d => d.Name).ToList());
> 				OneReadyDeviceNotFound?.Invoke(this, args);
> 			}
> ```

Seems we will still raise no event at all if applicableDevices.Count is zero but more than one device (or no device) is connected. Is that OK?

---

*[src/BloomExe/Publish/BloomReaderPublisher.cs, line 81 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1786#-Kr6kYkFrrO59qSDN8wK:-Kr6kYkFrrO59qSDN8wL:b-vz6ihh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/14e7ce16d9da784203230698b47ae65d660854d2/src/BloomExe/Publish/BloomReaderPublisher.cs#L81)):*
> ```Smalltalk
> 		private void OneReadyDeviceFound(object sender, EventArgs args)
> 		{
> 			_androidDeviceUsbConnection.OneReadyDeviceFound -= OneReadyDeviceFound;
> ```

Should we disconnect both handlers? Or are both still wanted in case the user wants to connect another device after transferring to this one?

---

*[src/BloomExe/Publish/BloomReaderPublisher.cs, line 95 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1786#-Kr6lkJNBrKSE0wLaRJX:-Kr6lkJNBrKSE0wLaRJY:b-9hwt4b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/14e7ce16d9da784203230698b47ae65d660854d2/src/BloomExe/Publish/BloomReaderPublisher.cs#L95)):*
> ```Smalltalk
> 
> 			// Don't report the same thing over and over
> 			if (_previousDeviceNotFoundReportType == eventArgs.ReportType)
> ```

This logic anticipates possibly receiving multiple (perhaps different) notifications as the user plugs and unplugs and perhaps installs BR, but since we disconnected this handler from the event when we got the first one, we won't.

---

*[src/BloomExe/Publish/BloomReaderPublisher.cs, line 113 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1786#-Kr6mJybnQf-ypzy8Dok:-Kr6mJybnQf-ypzy8Dol:bquyerv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/14e7ce16d9da784203230698b47ae65d660854d2/src/BloomExe/Publish/BloomReaderPublisher.cs#L113)):*
> ```Smalltalk
> 				_progress.WriteWarning(string.Format(LocalizationManager.GetString("Publish.BloomReaderPublisher.DeviceWithoutBloomReader",
> 					"The {0} device was found but does not seem to have Bloom Reader installed.", "{0} is a mobile device name"), eventArgs.DeviceNames[0]));
> 			}
> ```

Seems it would be useful here also to report "no devices appear to be connected" or "several devices are connected, but none of them appears to have BloomReader installed"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1786#-:-Kr6mxf8NfvNPoOaf1tX:bd4a6or)*

**Comment by andrew-polk** [comment]
Yikes; good thing we have code review.

---

Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/Communication/AndroidDeviceUsbConnection.cs, line 140 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1786#-Kr6jc9CMDmWn5EzAjmb:-Kr7bOYsusJhuOvW0jlP:b-vknmz1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/14e7ce16d9da784203230698b47ae65d660854d2/src/BloomExe/Communication/AndroidDeviceUsbConnection.cs#L140)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Seems we will still raise no event at all if applicableDevices.Count is zero but more than one device (or no device) is connected. Is that OK?
</blockquote></details>

Enhanced.

---

*[src/BloomExe/Publish/BloomReaderPublisher.cs, line 81 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1786#-Kr6kYkFrrO59qSDN8wK:-Kr7bbVS_iScBVMi_8un:bt2vr1b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/14e7ce16d9da784203230698b47ae65d660854d2/src/BloomExe/Publish/BloomReaderPublisher.cs#L81)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Should we disconnect both handlers? Or are both still wanted in case the user wants to connect another device after transferring to this one?
</blockquote></details>

Fixed.

---

*[src/BloomExe/Publish/BloomReaderPublisher.cs, line 95 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1786#-Kr6lkJNBrKSE0wLaRJX:-Kr7bkW8vVrbro1AQ9cK:bt2vr1b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/14e7ce16d9da784203230698b47ae65d660854d2/src/BloomExe/Publish/BloomReaderPublisher.cs#L95)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This logic anticipates possibly receiving multiple (perhaps different) notifications as the user plugs and unplugs and perhaps installs BR, but since we disconnected this handler from the event when we got the first one, we won't.
</blockquote></details>

Fixed.

---

*[src/BloomExe/Publish/BloomReaderPublisher.cs, line 113 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1786#-Kr6mJybnQf-ypzy8Dok:-Kr7bceJnuq0saIRmqfv:b-vknmz1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/14e7ce16d9da784203230698b47ae65d660854d2/src/BloomExe/Publish/BloomReaderPublisher.cs#L113)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Seems it would be useful here also to report "no devices appear to be connected" or "several devices are connected, but none of them appears to have BloomReader installed"
</blockquote></details>

Enhanced.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1786#-:-Kr7cVB1fryaiUZB2KHP:b-w6vje3)*

**Comment by JohnThomson** [comment]
:lgtm: with one remaining question.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/BloomReaderPublisher.cs, line 85 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1786#-KrBgKuWqENdpBydodbx:-KrBgKuWqENdpBydodby:b-dw5viz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32c455625dced2aec7b72b8c1cb6ea7430d53f2e/src/BloomExe/Publish/BloomReaderPublisher.cs#L85)):*
> ```Smalltalk
> 		{
> 			_androidDeviceUsbConnection.OneReadyDeviceFound -= OneReadyDeviceFound;
> 			_androidDeviceUsbConnection.OneReadyDeviceNotFound -= OneReadyDeviceNotFound;
> ```

Still not sure this is right. What is supposed to happen after the book is transferred? Will we keep looking for another device to be plugged in? If not, what is the user supposed to do if he wants to plug in another and get the book transferred? Does he need to click connect again?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1786#-:-KrBh8kiRJHVSft-4Wei:b-yfzpon)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/BloomReaderPublisher.cs, line 85 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1786#-KrBgKuWqENdpBydodbx:-KrXAFPnbIH6JmXetWZ5:bmirao9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32c455625dced2aec7b72b8c1cb6ea7430d53f2e/src/BloomExe/Publish/BloomReaderPublisher.cs#L85)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Still not sure this is right. What is supposed to happen after the book is transferred? Will we keep looking for another device to be plugged in? If not, what is the user supposed to do if he wants to plug in another and get the book transferred? Does he need to click connect again?
</blockquote></details>

Good question. I guess ideally we would notice the device was removed and update the button state. I haven't looked into how difficult that is technically. Another, less ideal, option would be to have a way to connect another device via the UI (such as changing the connect-a-device button to connect-another-device rather than just disabling it).

Currently, the button state just assumes the original device stays there. To connect a new device, the user has to exit and reenter the Android publish view.

@hatton, do you want to weigh in on the design here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1786)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/BloomReaderPublisher.cs, line 85 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1786#-KrBgKuWqENdpBydodbx:-KrXCpMAO75IRb4SR3_w:b-fmziuq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32c455625dced2aec7b72b8c1cb6ea7430d53f2e/src/BloomExe/Publish/BloomReaderPublisher.cs#L85)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Good question. I guess ideally we would notice the device was removed and update the button state. I haven't looked into how difficult that is technically. Another, less ideal, option would be to have a way to connect another device via the UI (such as changing the connect-a-device button to connect-another-device rather than just disabling it).

Currently, the button state just assumes the original device stays there. To connect a new device, the user has to exit and reenter the Android publish view.

@hatton, do you want to weigh in on the design here?
</blockquote></details>

The whole UI may change drastically.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1786)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/BloomReaderPublisher.cs, line 85 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1786#-KrBgKuWqENdpBydodbx:-KrXH3ehnBbQT4ML7qJk:bfdi0ds) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/32c455625dced2aec7b72b8c1cb6ea7430d53f2e/src/BloomExe/Publish/BloomReaderPublisher.cs#L85)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

The whole UI may change drastically.
</blockquote></details>

Ok, I'm going to merge since what I have is certainly an improvement.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1786)*

**Pull request merged**
