### PR TITLE
Implement a fast splash screen for Windows Bloom (BL-4666)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
The Linux implementation is totally different.  It will share the new splash image (src/BloomSplash.png) however.  I'll probably have to handle merge conflicts locally on whichever of these two PR's gets merged last.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1707)

### CODE REVIEW

**Comment by StephenMcConnel** [comment]
See my comment on flowdock before thinking about merging this code.  It might be better to move this functionality into Squirrel's StubExecutable (which is written in C++).  This needs some thought.

**Comment by JohnThomson** [comment]
Looks like we will modify the Squirrel launcher rather than creating this new program, so I'll wait t review that.

**Comment by StephenMcConnel** [comment]
These changes are fairly minimal, depending on the bulk of the work being done by the StubExecutable program of squirrel (which is renamed to Bloom{channel}.exe in the installer and placed in the folder about the specific version).

**Comment by JohnThomson** [comment]
:lgtm: assuming that communication with the native program works, which it seems to. But, don't you need conditionals to do something different in Linux? Seems like I saw that in the Linux PR.
How reliably does our splash screen overlay the other one? I haven't seen any code to ensure they are in the same place except that both programs try to put them in the middle of the screen.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1707#-:-KnKZ-a5xz1yV1g9XX70:b-ow7aac)*

**Comment by StephenMcConnel** [comment]
The conditional framework exists in the linux submission, but since that's a conflict that will have to be resolved after the first PR is merged and the second updated to take the other one into account, I didn't bother copying the identical to both PRs.
Both programs using the middle of the screen is all that ensures they're in the same place.  If someone has two monitors, they might end up both displaying for a second or so on the separate monitors.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1707#-:-KnKognWoZDpE6LJz24f:b1ytnvm)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1707#-:-KnKqXe0c-rVtOtk36up:bnfp4nl)*

**Pull request merged**
