### PR TITLE
[4.8] BL-8893 Better permission denied solution

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3914)

### CODE REVIEW

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3914)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomExe/ProjectContext.cs, line 452 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3914#-MGKqGG69kKt9xkm8YUn:-MGKqGG69kKt9xkm8YUo:b42rgki) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/47f4cb88cbfb1ee60a57795c41e932926fb316ea/src/BloomExe/ProjectContext.cs#L452)):*
> ```Smalltalk
> 				return Directory.GetDirectories(pathToSearch);
> 			}
> 			catch (UnauthorizedAccessException ex)
> ```

https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.getdirectories?view=netcore-3.1 says it can return ArgumentNullException, ArgumentOutOfRangeException, PathTooLongException, IOException, or DirectoryNotFoundException as well.

Should we check for any of these others as well?

IMO, DirectoryNotFound is reasonable to occur. (If the user user deletes that dir???)

The other ones seem a bit farfetched to me, but it'd be fine to check for them if we wanted. Thoughts?

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3914)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomExe/Collection/BookCollection.cs, line 126 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3914#-MGKr2zf3nKCcGLAmrkO:-MGKr2zf3nKCcGLAmrkP:bqhtmsb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/47f4cb88cbfb1ee60a57795c41e932926fb316ea/src/BloomExe/Collection/BookCollection.cs#L126)):*
> ```Smalltalk
> 			try
> 			{
> 				bookFolders = new DirectoryInfo(_path).GetDirectories();//although NTFS may already sort them, that's an implementation detail
> ```

Wonder if we could do SafeGetDirectories(_path).Select(x => new DirectoryInfo(x))?  And then not need the try/catch here?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3914)* status: all files reviewed, 3 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomExe/ProjectContext.cs, line 455 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3914#-MGKr1q17r4zS3iAuCAS:-MGKr1q17r4zS3iAuCAT:b-k9fypk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/47f4cb88cbfb1ee60a57795c41e932926fb316ea/src/BloomExe/ProjectContext.cs#L455)):*
> ```
> return new List<string>();
> ```
I'm a bit unclear of the ramifications of this. Does this mean that if a parent directory has 5 child directories and one of those 5 has permissions (or other) issues that we will get none of the 5?
If yes, can we do better than that?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3914)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomExe/ProjectContext.cs, line 452 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3914#-MGKqGG69kKt9xkm8YUn:-MGKuNABA_Js6IkekQ66:bmke7se) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/47f4cb88cbfb1ee60a57795c41e932926fb316ea/src/BloomExe/ProjectContext.cs#L452)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.getdirectories?view=netcore-3.1 says it can return ArgumentNullException, ArgumentOutOfRangeException, PathTooLongException, IOException, or DirectoryNotFoundException as well.

Should we check for any of these others as well?

IMO, DirectoryNotFound is reasonable to occur. (If the user user deletes that dir???)

The other ones seem a bit farfetched to me, but it'd be fine to check for them if we wanted. Thoughts?
</blockquote></details>

I'll add DirectoryNotFound.
___
*[src/BloomExe/ProjectContext.cs, line 455 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3914#-MGKr1q17r4zS3iAuCAS:-MGKtfLv9JQWaZ4i-Ij4:btyi3s6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/47f4cb88cbfb1ee60a57795c41e932926fb316ea/src/BloomExe/ProjectContext.cs#L455)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> return new List<string>();
> ```
I'm a bit unclear of the ramifications of this. Does this mean that if a parent directory has 5 child directories and one of those 5 has permissions (or other) issues that we will get none of the 5?
If yes, can we do better than that?
</blockquote></details>

Yes, I was worried about that. But the situation I was seeing was the folder `pathToSearch` was just one of the template folders, so we only lost that one. I couldn't figure out how to do any better. I even tried using an enumerator, but you have to do `GetDirectories()` first to GET the enumerator and that fails first.
___
*[src/BloomExe/Collection/BookCollection.cs, line 126 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3914#-MGKr2zf3nKCcGLAmrkO:-MGKvmDW6ppLeZYT7al6:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/47f4cb88cbfb1ee60a57795c41e932926fb316ea/src/BloomExe/Collection/BookCollection.cs#L126)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Wonder if we could do SafeGetDirectories(_path).Select(x => new DirectoryInfo(x))?  And then not need the try/catch here?
</blockquote></details>

Done.

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3914)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @gmartin7)

___
*[src/BloomExe/ProjectContext.cs, line 459 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3914#-MGKyk6gBtJJvUjy5NjI:-MGKyk6h1tytBYZamQAV:b-hr7kok) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/880234ab3a6ab45de20822dace0b919ea2ec807f/src/BloomExe/ProjectContext.cs#L459)):*
> ```
> nfex.Message
> ```
Should these be toString() instead of Message? Normally toString is better because it prints out the stack trace too and what not. Unless we don't want stack trace to appear here? Or if Logger.writeEvent does it automatically?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3914)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomExe/ProjectContext.cs, line 459 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3914#-MGKyk6gBtJJvUjy5NjI:-MGL0mwv4oMTCCezVSqE:bdalsxv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/880234ab3a6ab45de20822dace0b919ea2ec807f/src/BloomExe/ProjectContext.cs#L459)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> nfex.Message
> ```
Should these be toString() instead of Message? Normally toString is better because it prints out the stack trace too and what not. Unless we don't want stack trace to appear here? Or if Logger.writeEvent does it automatically?
</blockquote></details>

I think you actually want WriteError rather than WriteEvent.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3914)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

**Review by sujeffreyl — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3914)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
