### PR TITLE
Add special REACH upgrade message

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4443)

### CODE REVIEW

**Review by hatton — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4443)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Workspace/WorkspaceView.cs, line 923 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4443#-M_MlVft3Mlg-S150AoT:-M_MlVft3Mlg-S150AoU:b3phusa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d7d1329b262c93f0f667279a7fd6b105d7e1df2/src/BloomExe/Workspace/WorkspaceView.cs#L923)):*
> ```Smalltalk
> 			notifier.Image.Image = Resources.Bloom;
> 			notifier.ToastClicked += (sender, args) => Process.Start("https://bloomlibrary.org/page/reach-upgrade");
> 			notifier.Show("Click to get a better Bloom!", null, -1); // Stay up until the user clicks on it
> ```

Is L10N in French and Spanish in the cards?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4443)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/Workspace/WorkspaceView.cs, line 923 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4443#-M_MlVft3Mlg-S150AoT:-M_XP8h95p_wg-O7qj59:bp0gcyi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d7d1329b262c93f0f667279a7fd6b105d7e1df2/src/BloomExe/Workspace/WorkspaceView.cs#L923)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is L10N in French and Spanish in the cards?
</blockquote></details>

Done.
I had slim hope that we might get a Bengali translation since that is what the majority of REACH users are using. But my request from one of the translators went unanswered.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4443)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Workspace/WorkspaceView.cs, line 923 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4443#-M_MlVft3Mlg-S150AoT:-M_XUJadDj7_TQrKZ8Ek:brag6j4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d7d1329b262c93f0f667279a7fd6b105d7e1df2/src/BloomExe/Workspace/WorkspaceView.cs#L923)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Done.
I had slim hope that we might get a Bengali translation since that is what the majority of REACH users are using. But my request from one of the translators went unanswered.
</blockquote></details>

How about google translate?

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4443)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Workspace/WorkspaceView.cs, line 923 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4443#-M_MlVft3Mlg-S150AoT:-M_XUOF-54czkagMqhtI:b-cya7gr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d7d1329b262c93f0f667279a7fd6b105d7e1df2/src/BloomExe/Workspace/WorkspaceView.cs#L923)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

How about google translate?
</blockquote></details>

Or crowdin translate... whatever they call it.

**Comment by andrew-polk** [comment]
___
*[src/BloomExe/Workspace/WorkspaceView.cs, line 923 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4443#-M_MlVft3Mlg-S150AoT:-M_aYWEx-yTuslDIqaJL:bdvbtgn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d7d1329b262c93f0f667279a7fd6b105d7e1df2/src/BloomExe/Workspace/WorkspaceView.cs#L923)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Or crowdin translate... whatever they call it.
</blockquote></details>

Used Google translate. Crowdin's machine translation didn't try. DeepL doesn't have Bengali. I thought about replacing the word they translated from "Bloom" with "Bloom" but most of the existing translations in Crowdin use this word for the program name.

**Pull request merged**
