### PR TITLE
Show progress during checkins (BL-9985)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4498)

### CODE REVIEW

**Review by hatton — COMMENTED** [review]
> Reviewed 6 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4498)* status: 7 of 8 files reviewed, 6 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, line 105 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4498#-Ma_XCsQEqM0OHUN-wHF:-Ma_XCsQEqM0OHUN-wHG:b-st9dsk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0eb6783140064108cd76fb880d772c78fd903f66/src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx#L105)):*
> ```XML
>     );
> 
>     const listener = e => {
> ```

This is fine but as an option I find the following it more clear to just inline the function...
___
*[src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, line 111 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4498#-Ma_XK8A1euV4RLy9C0F:-Ma_XK8A1euV4RLy9C0G:b-295jf4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0eb6783140064108cd76fb880d772c78fd903f66/src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx#L111)):*
> ```XML
>         "checkinProgress",
>         "progress",
>         listener,
> ```

... as in just `e => setProgress(e.fraction)` instead of pre-defining `listener`
___
*[src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, line 326 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4498#-Ma_YT0H-m8v_BGRg1cs:-Ma_YT0H-m8v_BGRg1ct:b-igb7nc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0eb6783140064108cd76fb880d772c78fd903f66/src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx#L326)):*
> ```XML
>                 return (
>                     <StatusPanelCommon
>                         css={css`
> ```

This is fine but as an option I find the following more clear in these cases:

` ${busy && "cursor: progress; .checkin-button{cursor:progress;}"}`
___
*[src/BloomExe/BloomZipFile.cs, line 87 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4498#-Ma__LmiAxUGCzdsdSUx:-Ma_ZUlm74HPTWQyN4Zt:b-egz0w4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0eb6783140064108cd76fb880d772c78fd903f66/src/BloomExe/BloomZipFile.cs#L87)):*
> ```Smalltalk
> 		/// Add everything in directoryPath, including subfolders recursively, to the zip.
> 		/// The names of the zip entries are made by removing dirNameOffset from the full path
> 		/// to the file, so usually directoryPath.Length + 1 should be passed.
> ```

I'm confused about when dirNameOffset should be `directoryPath.Length + 1` and when it should be  `directoryPath.Length - rootName.Length`. I'm sure I'd figure it out if I put a debugger on existing code, though. But maybe this will prompt you to think of a way to improve the comment.
___
*[src/BloomExe/BloomZipFile.cs, line 100 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4498#-Ma_a8gmE38EeWzH5GDY:-Ma_a8gn0VVOZqpbSLiJ:bio64ay) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0eb6783140064108cd76fb880d772c78fd903f66/src/BloomExe/BloomZipFile.cs#L100)):*
> ```Smalltalk
> 			if (progressCallback != null)
> 			{
> 				count = AddDirectory(directoryPath, dirNameOffest, null, true);
> ```

Could `AddDirectory` find no files to add and then count is 0 and we have division by 0?
___
*[src/BloomExe/BloomZipFile.cs, line 113 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4498#-Ma_a203-JA4uJOp6P1J:-Ma_a203-JA4uJOp6P1K:bggl2pn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0eb6783140064108cd76fb880d772c78fd903f66/src/BloomExe/BloomZipFile.cs#L113)):*
> ```Smalltalk
> 		/// to the file, so usually directoryPath.Length + 1 should be passed.
> 		/// Files with the specified extensions will be excluded.
> 		/// Returns the number of files added.
> ```

Any reason to not use the <returns/> convention?

**Review by hatton — COMMENTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4498)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4498)* status: all files reviewed, 6 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/BloomZipFile.cs, line 113 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4498#-Ma_a203-JA4uJOp6P1J:-MaclpHaCmVZbATkuKs-:bhqzeov) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0eb6783140064108cd76fb880d772c78fd903f66/src/BloomExe/BloomZipFile.cs#L113)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Any reason to not use the <returns/> convention?
</blockquote></details>

Sorry, which convention?

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4498)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/BloomZipFile.cs, line 113 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4498#-Ma_a203-JA4uJOp6P1J:-MacmgSXBNbgc1u23ptY:b-628pk8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0eb6783140064108cd76fb880d772c78fd903f66/src/BloomExe/BloomZipFile.cs#L113)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Sorry, which convention?
</blockquote></details>

Sorry:

`/// <returns>`

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4498)* status: 6 of 8 files reviewed, 6 unresolved discussions (waiting on @hatton)

___
*[src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, line 105 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4498#-Ma_XCsQEqM0OHUN-wHF:-Macmqa3DtXEvw_eumZB:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0eb6783140064108cd76fb880d772c78fd903f66/src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx#L105)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This is fine but as an option I find the following it more clear to just inline the function...
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, line 111 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4498#-Ma_XK8A1euV4RLy9C0F:-MacmsAD0CEBcYJLWKVL:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0eb6783140064108cd76fb880d772c78fd903f66/src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx#L111)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

... as in just `e => setProgress(e.fraction)` instead of pre-defining `listener`
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, line 326 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4498#-Ma_YT0H-m8v_BGRg1cs:-Macn6P58UHn3IEhQXyZ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0eb6783140064108cd76fb880d772c78fd903f66/src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx#L326)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This is fine but as an option I find the following more clear in these cases:

` ${busy && "cursor: progress; .checkin-button{cursor:progress;}"}`
</blockquote></details>

Done.
___
*[src/BloomExe/BloomZipFile.cs, line 87 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4498#-Ma__LmiAxUGCzdsdSUx:-Macp-v02Ukv1iTxaQhm:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0eb6783140064108cd76fb880d772c78fd903f66/src/BloomExe/BloomZipFile.cs#L87)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I'm confused about when dirNameOffset should be `directoryPath.Length + 1` and when it should be  `directoryPath.Length - rootName.Length`. I'm sure I'd figure it out if I put a debugger on existing code, though. But maybe this will prompt you to think of a way to improve the comment.
</blockquote></details>

Done.
___
*[src/BloomExe/BloomZipFile.cs, line 100 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4498#-Ma_a8gmE38EeWzH5GDY:-MacpNam8Rn_UFTpGgmU:b-bttoee) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0eb6783140064108cd76fb880d772c78fd903f66/src/BloomExe/BloomZipFile.cs#L100)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Could `AddDirectory` find no files to add and then count is 0 and we have division by 0?
</blockquote></details>

Added comment
___
*[src/BloomExe/BloomZipFile.cs, line 113 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4498#-Ma_a203-JA4uJOp6P1J:-MacsH3_7eTX4uLpdQbF:b-gte777) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0eb6783140064108cd76fb880d772c78fd903f66/src/BloomExe/BloomZipFile.cs#L113)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Sorry:

`/// <returns>`
</blockquote></details>

Well, it was tricky. I find the convention seldom works well, because followed strictly, you have to explain what the function does without mentioning its arguments, which is usually difficult, and then discuss each argument in isolation, which is also often hard. In this case, the natural thing is to use at least the first argument in explaining what the function does. Then you need to describe what it returns before you can discuss how the other arguments affect that. But I found something that works reasonably well, though some linters may complain that I have param elements for some params but not all.

**Review by hatton — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4498)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @hatton)

**Pull request merged**
