### PR TITLE
BL-4856 Don't update preview when creating new book

### PR DESCRIPTION
**Pull request by JohnThomson**
(Since we immediately switch to edit view.)
Also improves urls of simulated pages to aid in identifying source of missing ones

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1787)

### CODE REVIEW

**Comment by JohnThomson** [comment]
The essence of this change is in LibraryBookView.ShowBook, which now takes an argument indicating whether the book preview should be updated, and in its OnBookSelectionChanged method, which now tells it not to update the preview if the new selection arises from creating a new book.
The rest of the changes fall into two groups:
1. Enhancing BookSelection.SelectionChanged to take a custom EventArgs so that the information that the selection is changing to a newly created book can be supplied by LibraryModel.CreateFromSourceBook().
2. Enhancing various methods so that the simulated files we make in various places have urls which indicate where in our code they were created, as an aid to debugging ones that have expired.

**Comment by andrew-polk** [comment]
A niggle. Else, :lgtm: 

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Edit/EditingModel.cs, line 21 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1787#-Kr2Q6wpqsMVr-Rfky2l:-Kr2Q6wpqsMVr-Rfky2m:b-5i00p4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9973363dc13cd910537b974ec48ec1bf6448770b/src/BloomExe/Edit/EditingModel.cs#L21)):*
> ```Smalltalk
> using Gecko;
> using L10NSharp;
> using SIL.EventsAndDelegates;
> ```

Not a big deal, but are all these added using statements necessary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1787#-:-Kr2QqGt26LlJuCaUBor:bp8v95p)*

**Comment by JohnThomson** [comment]
Review status: 10 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Edit/EditingModel.cs, line 21 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1787#-Kr2Q6wpqsMVr-Rfky2l:-Kr2SZrUwIuRkQX9kTA0:bf9znyo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9973363dc13cd910537b974ec48ec1bf6448770b/src/BloomExe/Edit/EditingModel.cs#L21)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Not a big deal, but are all these added using statements necessary?
</blockquote></details>

I think most of them were added by the system during an incorrect attempt to update the signatures of various handlers of the SelectionChanged event. I've removed them (and a few more unused ones for good measure :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1787)*

**Comment by andrew-polk** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1787)*

**Pull request merged**
