### PR TITLE
BL-998 Source collection title page had wrong languages

### PR DESCRIPTION
**Pull request by gmartin7**
* for originalAcknowledgments
* for funding
* also did some refactoring in BookData; no change of function
* change gitattributes to allow spaces in .less and .css files

### CODE REVIEW

**Comment by gmartin7** [comment]
There is one section in the bloom-xmatter-common.css file regarding the licenseandcopyright block that I did not do. Perhaps a .less change that never got synced with the .css? Let me know if it's not wanted.

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/211/
Test PASSed.

**Comment by JohnThomson** [comment]
I think the description of this commit could be improved. My first impression was that you had fixed some text that was in the wrong language. After that I looked for changes to the lang attribute of something in the html. Moreover you don't seem to have changed languages so much as added stuff. Something like, "added minimum height styles for some title page elements in national language" (if that's right, of course)

**Comment by gmartin7** [comment]
The JIRA issue title is "Wrong language selected for credits" which isn't right either. The problem is which language's text box is showing on the title page for original acknowledgments and for funding. In a Source collection, you want the first language showing (.bloom-content1). In a Vernacular collection, you want the second language showing (.bloom-contentNational1). The CSS by default doesn't display .bloom-editable DIVs, I just modified the CSS to show the right DIVs at the right time.

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/213/
Test PASSed.

**Pull request merged**
