### PR TITLE
Improve robustness replacing files (BL-12669)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6164)

### CODE REVIEW

**Review by hatton — COMMENTED** [review]
It looks like this should be done in libpalaso, on the `ReplaceFileWithUserInteractionIfNeeded`?

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6164#-:-NhTVC2DDOQUkWPY3rV3:b-5kq36d)* status: 0 of 2 files reviewed, all discussions resolved

**Review by StephenMcConnel — COMMENTED** [review]
I'm working on the libpalaso code, but thought I'd give an option for fixing in Bloom without needing to update libpalaso at this stage.  But I'd be happy(er) with the libpalaso fix getting in.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6164#-:-NhTXPt4CHuGcfOS-Aim:b5xcwdy)* status: 0 of 2 files reviewed, all discussions resolved

**Review by hatton — COMMENTED** [review]
OK great

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6164#-:-NhTY-9j-rpzX_hMgOzo:blbs1u6)* status: 0 of 2 files reviewed, all discussions resolved

**Review by hatton — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6164)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
