### PR TITLE
Open Ace by Daisy checker links in system browser (BL-9026)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3967)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3967)* status: 0 of 2 files reviewed, all discussions resolved

___
*[src/BloomBrowserUI/publish/accessibilityCheck/daisyChecks.less, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3967#-MIQlfY-EdDlwlY8djXf:-MIQlfY-EdDlwlY8djXg:b-fh6irq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e79d75e5490c168aa06b1b21136ad9c16a9cd873/src/BloomBrowserUI/publish/accessibilityCheck/daisyChecks.less#L40)):*
> ```Less
>             border-left: 0;
>             border-right: 0;
>             border-bottom: 0;
> ```

This is unrelated to the link issue but removes an ugly border causing the iframe contents to be offset.

**Comment by andrew-polk** [comment]
Making this a draft until JH approves the approach.

**Review by JohnThomson — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3967)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Publish/AccessibilityChecker/AccessibilityCheckWindow.cs, line 49 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3967#-MIUDf4F7eo5ma0Eu0fE:-MIUDf4F7eo5ma0Eu0fF:bqtxni0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e79d75e5490c168aa06b1b21136ad9c16a9cd873/src/BloomExe/Publish/AccessibilityChecker/AccessibilityCheckWindow.cs#L49)):*
> ```Smalltalk
> 					Process.SafeStart(eventArgs.Uri);
> 				};
> 			};
> ```

We already have a way to handle clicks on external links...see HtmlPublishPanel.HandleExternalLinkClick. I'm not sure whether your way is better or worse...it's certainly shorter...but it would be nice to handle the problem in a consistent way without duplication. Maybe the implementation could move to Browser, and there could be a property to control whether links should be opened in the system browser? Maybe we always want this if such links exist? Or maybe only for links outside the current page? Worth a bit of thought, anyway.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3967)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Browser.cs, line 1473 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3967#-MIV-d7i2he7vkx30HES:-MIV-d7i2he7vkx30HET:b-bbdhjq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b7f41c8ec6d5b8444734cde72f1f2347eb8138d7/src/BloomExe/Browser.cs#L1473)):*
> ```Smalltalk
> 		/// in the function this.processLinkElements.
> 		/// </remarks>
> 		public static void HandleExternalLinkClick(object sender, EventArgs e)
> ```

This is copied verbatim from the other file other than making it public static and the expanded comment.
___
*[src/BloomExe/Publish/AccessibilityChecker/AccessibilityCheckWindow.cs, line 49 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3967#-MIUDf4F7eo5ma0Eu0fE:-MIV-_w1-eh_NtH9WFNQ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e79d75e5490c168aa06b1b21136ad9c16a9cd873/src/BloomExe/Publish/AccessibilityChecker/AccessibilityCheckWindow.cs#L49)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We already have a way to handle clicks on external links...see HtmlPublishPanel.HandleExternalLinkClick. I'm not sure whether your way is better or worse...it's certainly shorter...but it would be nice to handle the problem in a consistent way without duplication. Maybe the implementation could move to Browser, and there could be a property to control whether links should be opened in the system browser? Maybe we always want this if such links exist? Or maybe only for links outside the current page? Worth a bit of thought, anyway.
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3967)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Publish/AccessibilityChecker/AccessibilityCheckWindow.cs, line 49 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3967#-MIUDf4F7eo5ma0Eu0fE:-MIV-sZQAtfUQAh5LhnB:b-se2p3e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e79d75e5490c168aa06b1b21136ad9c16a9cd873/src/BloomExe/Publish/AccessibilityChecker/AccessibilityCheckWindow.cs#L49)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Btw, my original implementation only works when we know for sure the link is trying to open in another window as it intercepts the CreateWindow event.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3967)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
