### PR TITLE
BL-9871 Add Captive Widget to Activity template

### PR DESCRIPTION
**Pull request by gmartin7**
* for Add Page dialog

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4601)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4601)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[DistFiles/localization/en/Bloom.xlf, line 1079 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4601#-Mf4dczQ9p7EUHVnZD4f:-Mf4dczQ9p7EUHVnZD4g:b58yof3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/faae2f6b32944f1e03956a7fcd57459710e8ad2e/DistFiles/localization/en/Bloom.xlf#L1079)):*
> ```XML
>         <note>ID: EditTab.AddPageDialog.LearnMore</note>
>         <note>Text of the optional link at the end of a page description.</note>
>       </trans-unit>
> ```

Let's use Common.LearnMore instead.
___
*[src/BloomBrowserUI/templates/template books/Activity/customWidgetPage.pug, line 7 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4601#-Mf4eoNt1CSb1OuvTRdE:-Mf4eoNt1CSb1OuvTRdF:bdl19ky) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/faae2f6b32944f1e03956a7fcd57459710e8ad2e/src/BloomBrowserUI/templates/template books/Activity/customWidgetPage.pug#L7)):*
> ```
> https://docs.google.com/document/d/1PNSCcxT_s0ETPSf7vLWlMm682JktBVHpdSUfhRbp7qU
> ```
I'm uncomfortable shipping a desktop app with this hardcoded because it means we can't ever move it.
We could use a Cloudflare page rule... but we only have 50 of those. 
I'll think of options...
Thoughts?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4601)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @gmartin7)

___
*[DistFiles/localization/en/Bloom.xlf, line 1079 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4601#-Mf4dczQ9p7EUHVnZD4f:-Mf4gBKmA2HA6I7apPTS:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/faae2f6b32944f1e03956a7fcd57459710e8ad2e/DistFiles/localization/en/Bloom.xlf#L1079)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's use Common.LearnMore instead.
</blockquote></details>

Done.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4601)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/templates/template books/Activity/customWidgetPage.pug, line 7 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4601#-Mf4eoNt1CSb1OuvTRdE:-Mf4gOjJ-5KG4_e9WIQr:b-tvlh0k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/faae2f6b32944f1e03956a7fcd57459710e8ad2e/src/BloomBrowserUI/templates/template books/Activity/customWidgetPage.pug#L7)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> https://docs.google.com/document/d/1PNSCcxT_s0ETPSf7vLWlMm682JktBVHpdSUfhRbp7qU
> ```
I'm uncomfortable shipping a desktop app with this hardcoded because it means we can't ever move it.
We could use a Cloudflare page rule... but we only have 50 of those. 
I'll think of options...
Thoughts?
</blockquote></details>

Yeah, I understand, but ... not sure what to do about it.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4601)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomBrowserUI/templates/template books/Activity/customWidgetPage.pug, line 7 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4601#-Mf4eoNt1CSb1OuvTRdE:-Mf4yEKKDDC8cRHJJ8xP:bpswnvx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/faae2f6b32944f1e03956a7fcd57459710e8ad2e/src/BloomBrowserUI/templates/template books/Activity/customWidgetPage.pug#L7)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Yeah, I understand, but ... not sure what to do about it.
</blockquote></details>

https://docs.bloomlibrary.org/widgets

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4601)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/templates/template books/Activity/customWidgetPage.pug, line 7 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4601#-Mf4eoNt1CSb1OuvTRdE:-Mf8iwm_7Hina5o7dew_:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/faae2f6b32944f1e03956a7fcd57459710e8ad2e/src/BloomBrowserUI/templates/template books/Activity/customWidgetPage.pug#L7)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

https://docs.bloomlibrary.org/widgets
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4601)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
