### PR TITLE
BL-5321 hotfix which should NOT be merged to 4.0

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1997)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Browser.cs, line 124 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1997#-L-DzUKjfv3BNSvVV199:-L-DzUKjfv3BNSvVV19A:b-opmryg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/031554a0851185a2d4ba6a33cd107f1f80f93635/src/BloomExe/Browser.cs#L124)):*
> ```Smalltalk
> 			// Do NOT set this to zero. Somehow that disables following hyperlinks within a document (e.g., the ReadMe
> 			// for the template starter, BL-5321).
> 			GeckoPreferences.User["browser.sessionhistory.max_entries"] = 1;
> ```

Do we know why this is set to 0? Is there something we need to test for such as the user hitting Alt-left while in Edit mode, etc.?

---

*[src/BloomExe/Book/Book.cs, line 1491 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1997#-L-E-2bjAvU0yO7XaGbK:-L-E-2bjAvU0yO7XaGbL:b-crfvgx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/031554a0851185a2d4ba6a33cd107f1f80f93635/src/BloomExe/Book/Book.cs#L1491)):*
> $" < h

Is there any significance to adding extra whitespace here? Just an IDE insertion?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1997)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Browser.cs, line 124 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1997#-L-DzUKjfv3BNSvVV199:-L-E5KlXdlgZmpE1PRab:ba3unvr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/031554a0851185a2d4ba6a33cd107f1f80f93635/src/BloomExe/Browser.cs#L124)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Do we know why this is set to 0? Is there something we need to test for such as the user hitting Alt-left while in Edit mode, etc.?
</blockquote></details>

Comments above indicate we were trying to reduce various buffer sizes to save memory. If there was any other reason, I don't recall it and someone forgot to comment.

---

*[src/BloomExe/Book/Book.cs, line 1491 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1997#-L-E-2bjAvU0yO7XaGbK:-L-E5kIblXBj3529KVmy:b1vk6o7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/031554a0851185a2d4ba6a33cd107f1f80f93635/src/BloomExe/Book/Book.cs#L1491)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> $" < h

Is there any significance to adding extra whitespace here? Just an IDE insertion?
</blockquote></details>

I don't know...not something I changed as far as I can tell...I don't think the IDE would insert white space inside a string...but IIRC the space INSIDE the tag after the bracket is illegal, so it would be good to fix. I'll make a new push.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1997)*

**Comment by JohnThomson** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/Book.cs, line 1491 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1997#-L-E-2bjAvU0yO7XaGbK:-L-E6gcHNbWfhOls1Los:br9kuwg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/031554a0851185a2d4ba6a33cd107f1f80f93635/src/BloomExe/Book/Book.cs#L1491)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't know...not something I changed as far as I can tell...I don't think the IDE would insert white space inside a string...but IIRC the space INSIDE the tag after the bracket is illegal, so it would be good to fix. I'll make a new push.
</blockquote></details>

Unfortunately that change MAY be needed upstream...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1997)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1997#-:-L-E7CDb60AtuLJIHjKb:bnfp4nl)*

**Pull request merged**
