### PR TITLE
BL-12495 Improve "show invisibles"

### PR DESCRIPTION
**Pull request by nabalone**
Instead of the emojis upon CTRL+SHIFT+SPACE, replace invisibles with symbols from the font from Victor Gaultney

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050)

### CODE REVIEW

**Comment by nabalone** [comment]
The latest release of the font from Victor does not yet use the symbols Paratext wants to use. A commit by Victor on Aug 4 says "[Changes for Paratext - prep for moving to new repo](https://github.com/silnrsi/font-bloom-show-inv/commit/d22e45c870242b5514c91da434908f00d75c6827)" and it has not yet gone into a release.

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050)* status: 0 of 10 files reviewed, 3 unresolved discussions

___
*[`src/BloomBrowserUI/bookEdit/js/bloomEditing.ts` line 248 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050#-NbWnedI23D_67Um9RUo:-NbWnedI23D_67Um9RUp:b-iomxh5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2a6b5b156717bf15555b71777267d4c48be81c2d/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L248)):*
> ```XML
> 
>     const invisibles = [
>         { name: "Zero Width Joiner", re: "&zwj;|\u200D", symbol: "\uE077" },
> ```

I left out the normal space because it caused some complications; would be more work to implement
___
*[`src/BloomBrowserUI/bookEdit/js/bloomEditing.ts` line 255 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050#-NbWnn2tB_kpIRrQmq7x:-NbWnn2tB_kpIRrQmq7y:b-tg9niy) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2a6b5b156717bf15555b71777267d4c48be81c2d/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L255)):*
> ```XML
>             symbol: "\uE079"
>         },
>         { name: "Combining Grapheme Joiner", re: "\u034F", symbol: "\uE07A" },
> ```

I was not able to test the Combining Grapheme Joiner
___
*[`src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts` line 1057 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050#-NbWo89p0Y6w-hcUq4-R:-NbWo89p0Y6w-hcUq4-S:b6wmuiv) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2a6b5b156717bf15555b71777267d4c48be81c2d/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L1057)):*
> ```XML
>         if (j === -1) {
>             // Pathological case; nbsp in attribute?
>             // (We do put &nbsp; in a data-original attribute when replacing it with a symbol as part of showing
> ```

I don't see how we can get here because you should not be able to do keyboard input with CTRL held down. But it still seems bad to be creating a "pathological case". Is it worth trying to work around?

**Review by andrew-polk — COMMENTED** [review]
Looks good. A few minor comments...

> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050#-:-Nbb2MbZElGKENnOmedb:b-qgbdnc)* status: all files reviewed, 5 unresolved discussions (waiting on @nabalone)

___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 1116 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050#-Nbb05rX0vBhIvlSg6Ko:-Nbb05rY9xVVHUddpCFM:b-dplvoh) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e0a50256fb6b4c3852df827fb36e87b38baf3360/src/BloomBrowserUI/bookEdit/css/editMode.less#L1116)):*
> ```Less
>     font-family: "BloomShowInv";
>     color: @bloom-purple;
>     font-size: calc(14px + 1.5vw);
> ```

I guess this font-size must be something JH gave you?
___
*[`src/BloomBrowserUI/bookEdit/js/bloomEditing.ts` line 266 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050#-Nbb0Xvg7hXZaqW6FeZh:-Nbb0Xvg7hXZaqW6FeZi:bg0vhk2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e0a50256fb6b4c3852df827fb36e87b38baf3360/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L266)):*
> ```XML
>             re:
>                 "&ZeroWidthSpace;|&NegativeMediumSpace;|&NegativeThickSpace;|&NegativeThinSpace;|&NegativeVeryThinSpace;|\u200B",
>             symbol: "\uE081"
> ```

Even if we give all these non-zws characters the same symbol, shouldn't we label them differently? Something like "Other space"?

Or do all these html entities really refer to the same character?
___
*[`src/BloomBrowserUI/bookEdit/js/bloomEditing.ts` line 383 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050#-Nbb1Ypl7P2-aUFwFVRd:-Nbb1Ypl7P2-aUFwFVRe:bdq71gv) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e0a50256fb6b4c3852df827fb36e87b38baf3360/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L383)):*
> ```XML
>                 });
>             }
>         });
> ```

I know you inherited this, but...
bloomEditing is already such an unsightly beast.
How feasible is it to move all this invisibles logic to a separate file?

I think you can easily move everything except the actual key handlers. But the logic inside those can be extracted, I think.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts` line 1057 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050#-NbWo89p0Y6w-hcUq4-R:-Nbb2D8iAK3n3rU0Mz75:b-l7dh9k) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2a6b5b156717bf15555b71777267d4c48be81c2d/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L1057)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

I don't see how we can get here because you should not be able to do keyboard input with CTRL held down. But it still seems bad to be creating a "pathological case". Is it worth trying to work around?
</blockquote></details>

I wouldn't worry about it unless you saw this happen. (Or think you could make it happen.)

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050)* status: 9 of 11 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/css/editMode.less` line 1116 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050#-Nbb05rX0vBhIvlSg6Ko:-NbpHg-_5sY7VH4_HG48:blv2d5v) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e0a50256fb6b4c3852df827fb36e87b38baf3360/src/BloomBrowserUI/bookEdit/css/editMode.less#L1116)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I guess this font-size must be something JH gave you?
</blockquote></details>

He said something about making it bigger but not proportional to the font size so if the font is huge the invisibles don't need to be similarly huge. What I did here is somewhat arbitrary
___
*[`src/BloomBrowserUI/bookEdit/js/bloomEditing.ts` line 266 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050#-Nbb0Xvg7hXZaqW6FeZh:-NbpIaKy8UdsM3pOWut6:b-dujrq4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e0a50256fb6b4c3852df827fb36e87b38baf3360/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L266)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Even if we give all these non-zws characters the same symbol, shouldn't we label them differently? Something like "Other space"?

Or do all these html entities really refer to the same character?
</blockquote></details>


Wikepedia: https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references

I think they refer to the same character
___
*[`src/BloomBrowserUI/bookEdit/js/bloomEditing.ts` line 383 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050#-Nbb1Ypl7P2-aUFwFVRd:-NbpfZtG3QAbELb2h5P3:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e0a50256fb6b4c3852df827fb36e87b38baf3360/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L383)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I know you inherited this, but...
bloomEditing is already such an unsightly beast.
How feasible is it to move all this invisibles logic to a separate file?

I think you can easily move everything except the actual key handlers. But the logic inside those can be extracted, I think.
</blockquote></details>

Done.

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050)* status: 9 of 11 files reviewed, 6 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/js/showInvisibles.ts` line 145 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050#-NbpxmA198N5OWIAETL6:-NbpxcH9-mcAiwnQFSo6:b-klqwwl) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/34e9134c705094817e5f1937b3907574423f1d0c/src/BloomBrowserUI/bookEdit/js/showInvisibles.ts#L145)):*
> ```XML
> }
> 
> export function hideInvisibles(e) {
> ```

Note I removed the `preventDefault` line because from a quick google it looks like it doesn't do anything on `blur` and `keyup` anyway

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050)* status: all files reviewed, 3 unresolved discussions

**Comment by nabalone** [comment]
I switched to the new SymChar font and fixed the qtip bug (please review). Waiting for JH's input regarding font size for the symbols

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 11 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050)* status: 14 of 15 files reviewed, 4 unresolved discussions (waiting on @nabalone)

___
*[`src/BloomBrowserUI/lib/jquery.qtip.js` line 14 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050#-Nc8KvUx3AYtPen-bidU:-Nc8KvUyDVywoJKuvg00:b5zyyo0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a93fc1671555cad9895730ded5ba8be73cca925a/src/BloomBrowserUI/lib/jquery.qtip.js#L14)):*
> ```JavaScript
>  */
> 
> /*jslint browser: true, onevar: true, undef: true, nomen: true, bitwise: true, regexp: true, newcap: true, immed: true, strict: true */
> ```

As we discussed, let's make prettier ignore this file.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050)* status: all files reviewed, 4 unresolved discussions (waiting on @nabalone)

___
*[`src/BloomBrowserUI/lib/jquery.qtip.js` line 19 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050#-Nc8YR998iRgDtyTbcmo:-Nc8YR998iRgDtyTbcmp:b-f5123d) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/14c966ae69cf80e11f17ce66d88b313680f69d3c/src/BloomBrowserUI/lib/jquery.qtip.js#L19)):*
> ```JavaScript
> /* hatton removed use of $browser for jquery 1.9... qtip has this fix in the pipeline but it's not out yet*/
> /* JohnT (Bloom) added code marked Adjust for zoom by transform: scale
> ```

Let's add a brief comment here stating your fix.

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050)* status: 14 of 15 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/lib/jquery.qtip.js` line 19 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050#-Nc8YR998iRgDtyTbcmo:-Nc8bcDi3ixXDM-ycKvO:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/14c966ae69cf80e11f17ce66d88b313680f69d3c/src/BloomBrowserUI/lib/jquery.qtip.js#L19)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's add a brief comment here stating your fix.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050)* status: all files reviewed, 3 unresolved discussions

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050)* status: all files reviewed, 4 unresolved discussions (waiting on @nabalone)

___
*[`src/BloomBrowserUI/lib/jquery.qtip.js` line 1236 at r7](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050#-NcSnY8PEPTkeU0pLJWs:-NcSnY8PEPTkeU0pLJWt:bnn6er8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/633db137289a6760d261d3f9470698ed188faf5f/src/BloomBrowserUI/lib/jquery.qtip.js#L1236)):*
> ```JavaScript
>                     var scaleY = bounds.height / targetElem.offsetHeight;
>                     var scaleX = bounds.width / targetElem.offsetWidth;
>                     console.log(bounds);
> ```

Let's remove this log. Then looks good.

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050)* status: 14 of 15 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/lib/jquery.qtip.js` line 1236 at r7](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050#-NcSnY8PEPTkeU0pLJWs:-NcYBrQ57DSXcBCLPHOY:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/633db137289a6760d261d3f9470698ed188faf5f/src/BloomBrowserUI/lib/jquery.qtip.js#L1236)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's remove this log. Then looks good.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6050)* status: all files reviewed, 3 unresolved discussions

**Pull request merged**
