### PR TITLE
Add ffmpeg processing for video duration metadata (BL-6022)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2465)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---

*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 84 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2465#-LEVxqLuBCskxZv3UtYK:-LEVxqLuBCskxZv3UtYL:bdm3gb2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e19e3d5cfe63ded7222c131bfee6d52b116823f/src/BloomExe/web/controllers/SignLanguageApi.cs#L84)):*
> ```Smalltalk
> 				var videoFolder = BookStorage.GetVideoDirectoryAndEnsureExistence(CurrentBook.FolderPath);
> 				var path = Path.Combine(videoFolder, fileName);
> 				var ffmpeg = "/usr/bin/ffmpeg";		// standard Linux location
> ```

We always want to be looking for ways to make code readable/maintainable by splitting things into separate methods.  This processing really wants to be its own.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2465)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 84 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2465#-LEVxqLuBCskxZv3UtYK:-LEWTMMy7PDB0b-7bB2r:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e19e3d5cfe63ded7222c131bfee6d52b116823f/src/BloomExe/web/controllers/SignLanguageApi.cs#L84)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

We always want to be looking for ways to make code readable/maintainable by splitting things into separate methods.  This processing really wants to be its own.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2465)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 140 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2465#-LEWVBjp1Tfc0itQC45I:-LEWXma67bWxnz5BQgQt:bynirde) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d6f18c19b5d44dde5306a2fbf41f705e7b1f84d/src/BloomExe/web/controllers/SignLanguageApi.cs#L140)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Wouldn't this warrant an error entry in the log? And likely it warrants a SIL.Reporting.ErrorReport.NotifyUserOfProblem()?
</blockquote></details>

The allcaps WARNING may be a bit strong.  The only things I've seen working with ffmpeg are error messages starting with either the input or output filename (which are handled by writing the raw bytes to the file), and messages about simulating threading because it wasn't compiled in to a library.  I suppose the former maybe should provoke notifying the user.  The latter maybe shouldn't even be logged, although as developer I'd like to see those messages.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2465)*

**Comment by hatton** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 140 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2465#-LEWVBjp1Tfc0itQC45I:-LEWc3oc3mIGXJTf35gZ:b-tequrh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d6f18c19b5d44dde5306a2fbf41f705e7b1f84d/src/BloomExe/web/controllers/SignLanguageApi.cs#L140)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

The allcaps WARNING may be a bit strong.  The only things I've seen working with ffmpeg are error messages starting with either the input or output filename (which are handled by writing the raw bytes to the file), and messages about simulating threading because it wasn't compiled in to a library.  I suppose the former maybe should provoke notifying the user.  The latter maybe shouldn't even be logged, although as developer I'd like to see those messages.
</blockquote></details>

How about if, say, ffmpeg went missing on linux, or was a version that we don't know how to run, or it ran out of memory, or or or

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2465)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 140 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2465#-LEWVBjp1Tfc0itQC45I:-LEWckZt9_-4VDuZPbIj:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d6f18c19b5d44dde5306a2fbf41f705e7b1f84d/src/BloomExe/web/controllers/SignLanguageApi.cs#L140)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

How about if, say, ffmpeg went missing on linux, or was a version that we don't know how to run, or it ran out of memory, or or or
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2465)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 140 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2465#-LEWVBjp1Tfc0itQC45I:-LEWcoge8DXMKVt1mb6D:bllbqbl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d6f18c19b5d44dde5306a2fbf41f705e7b1f84d/src/BloomExe/web/controllers/SignLanguageApi.cs#L140)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I actually got around to reading the man page to find out what was reported for what value of the -v command line argument, and revised things accordingly.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2465)*

**Pull request merged**
