### PR TITLE
Use RobustFile/RobustIO methods wherever possible (BL-12669)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
Also renamed one of Bloom's two RobustIO classes to reduce confusion.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6086)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 55 of 55 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6086)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/ToPalaso/RobustIO.cs` line 55 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6086#-NdbbmSu1Q-TTm6yqHW0:-NdbbmSu1Q-TTm6yqHW1:bvhg0g0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/eed84200a7da42c16f8d39885f73b2972b31814c/src/BloomExe/ToPalaso/RobustIO.cs#L55)):*
> ```Smalltalk
> 		}
> 
> 		public static FileStream OpenFile(string filePath, FileMode mode,
> ```

I think this wants to just be called `Open` as a drop-in replacement for `File.Open`.

I suppose here in this context, where the class is RobustIO rather than RobustFile, maybe it makes more sense to include the "File" part.
But I would still lean toward just `Open`.
___
*[`src/BloomExe/ToPalaso/RobustIO.cs` line 56 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6086#-NdbceFvDqHtQk9omCcs:-NdbceFvDqHtQk9omCct:b-a6jm6q) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/eed84200a7da42c16f8d39885f73b2972b31814c/src/BloomExe/ToPalaso/RobustIO.cs#L56)):*
> ```Smalltalk
> 
> 		public static FileStream OpenFile(string filePath, FileMode mode,
> 			FileAccess access = FileAccess.ReadWrite, FileShare share = FileShare.None)
> ```

The default for FileAccess is actually `(mode == FileMode.Append ? FileAccess.Write : FileAccess.ReadWrite)`.
Seems safer to use that.

(Or to just provide separate overrides.)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6086)* status: 48 of 55 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/ToPalaso/RobustIO.cs` line 56 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6086#-NdbceFvDqHtQk9omCcs:-Ndf5bO-EpJGe6av6iX_:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/eed84200a7da42c16f8d39885f73b2972b31814c/src/BloomExe/ToPalaso/RobustIO.cs#L56)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The default for FileAccess is actually `(mode == FileMode.Append ? FileAccess.Write : FileAccess.ReadWrite)`.
Seems safer to use that.

(Or to just provide separate overrides.)
</blockquote></details>

Done.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6086)* status: 53 of 55 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/ToPalaso/RobustIO.cs` line 56 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6086#-NdbceFvDqHtQk9omCcs:-NdfFz6o2BM9y4HBgq_D:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/eed84200a7da42c16f8d39885f73b2972b31814c/src/BloomExe/ToPalaso/RobustIO.cs#L56)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like you've done both provided defaults and another override.
Don't we want one or the other?

I.e. shouldn't our version with 2 params call the File.Open with 2 params?
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6086)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
