### PR TITLE
Repair loss of style with resulting loss of format cog (BL-13953)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
The repair takes two forms: fix a broken book as best we can, and prevent breakage when changing the page format.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6712)

### CODE REVIEW

**Comment by StephenMcConnel** [comment]
This could possibly be a candidate for cherry-picking to 6.0.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6712)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Book/Book.cs` line 1821 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6712#-O9kTKnj5KvQ296Mafx5:-O9kTKnj5KvQ296Mafx6:bvadinm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/677ecdec037328b08f7fbfe911ce33d6103c4fb0/src/BloomExe/Book/Book.cs#L1821)):*
> ```Smalltalk
>             RepairBrokenSmallCoverCredits(OurHtmlDom);
>             RepairCoverImageDescriptions(OurHtmlDom);
>             RepairMissingStylesAndLangZInTranslationGroups(OurHtmlDom);
> ```

I'm pretty torn over the idea of looking for this situation every time we run EnsureUpToDate.

In theory, this is the kind of thing we should be using maintenance level migrations for so we only do it once. Of course, there could, in theory, be other situations which cause this which we haven't fixed....
But I'm not sure that theoretical case warrants this check for every book.

On the other hand, using a whole maintenance level for this fix seems a bit heavy handed.

Thoughts?

Do you have an opinion, @JohnThomson?
___
*[`src/BloomExe/Book/Book.cs` line 2307 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6712#-O9kOket29Ywid1yjC8N:-O9kOket29Ywid1yjC8O:blg9xgr) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/677ecdec037328b08f7fbfe911ce33d6103c4fb0/src/BloomExe/Book/Book.cs#L2307)):*
> ```Smalltalk
>                             langZExists = true;
>                         var classList = editableDiv.GetAttribute("class").Trim().Split(' ', '\t');
>                         var style = classList.FirstOrDefault(x => x.EndsWith("-style"));
> ```

HtmlDom has a GetStyle method which looks appropriate here.
___
*[`src/BloomExe/Book/Book.cs` line 2313 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6712#-O9kOy4E8uQ9JvPUnHZf:-O9kOy4E8uQ9JvPUnHZg:bivjk7f) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/677ecdec037328b08f7fbfe911ce33d6103c4fb0/src/BloomExe/Book/Book.cs#L2313)):*
> ```Smalltalk
>                                 "class",
>                                 $"{string.Join(" ", classList)} {styleForRepair}"
>                             );
> ```

HtmlDom has an AddClass method

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6712)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6712)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @StephenMcConnel)

___
*[`src/BloomExe/Book/Book.cs` line 1821 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6712#-O9kTKnj5KvQ296Mafx5:-O9kdJEO6SZ9nU9vO48M:b-lhwjbx) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/677ecdec037328b08f7fbfe911ce33d6103c4fb0/src/BloomExe/Book/Book.cs#L1821)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm pretty torn over the idea of looking for this situation every time we run EnsureUpToDate.

In theory, this is the kind of thing we should be using maintenance level migrations for so we only do it once. Of course, there could, in theory, be other situations which cause this which we haven't fixed....
But I'm not sure that theoretical case warrants this check for every book.

On the other hand, using a whole maintenance level for this fix seems a bit heavy handed.

Thoughts?

Do you have an opinion, @JohnThomson?
</blockquote></details>

I think I would be more inclined to fix this in TranslationGroupManager.MakeElementWithLanguageForOneGroup. That could pretty easily repair an existing editable. If it has to make a new one and the prototype doesn't have a style class, it can repair the new one.
I think the cost of doing it once per editable on a page would be negligible (especially since we already found where it needs doing, so we don't even add a SelectNode), whereas the cost for doing it for a whole book might be nontrivial. And, like this solution, it will be in place if we ever again make a mistake that leaves some languages without a style class.
Of course that would not be a great solution if we actually need to fix this across the whole book (e.g., to publish a broken one).
If it's not feasible I think this is worth a maintenance level. Numbers don't cost anything, and making one more number comparison is a whole lot cheaper than searching the whole book.
___
*[`src/BloomExe/Book/Book.cs` line 2320 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6712#-O9kgCmE7CW_G-qMABgL:-O9kgCmE7CW_G-qMABgM:b-cqqy1e) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/677ecdec037328b08f7fbfe911ce33d6103c4fb0/src/BloomExe/Book/Book.cs#L2320)):*
> ```Smalltalk
>                         else
>                         {
>                             styleForRepair = style; // we expect the style to stay the same inside a translationGroup.
> ```

We should hunt for this possibility in a separate loop, unless there is reason to be quite sure that a good block that already has a style will come before any that does not.
Also, check the classes of the TG. Sometimes that has the style, too.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6712)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[`src/BloomExe/Book/Book.cs` line 1821 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6712#-O9kTKnj5KvQ296Mafx5:-O9upe5H8kJ5PpErGBht:btix9ay) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/677ecdec037328b08f7fbfe911ce33d6103c4fb0/src/BloomExe/Book/Book.cs#L1821)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think I would be more inclined to fix this in TranslationGroupManager.MakeElementWithLanguageForOneGroup. That could pretty easily repair an existing editable. If it has to make a new one and the prototype doesn't have a style class, it can repair the new one.
I think the cost of doing it once per editable on a page would be negligible (especially since we already found where it needs doing, so we don't even add a SelectNode), whereas the cost for doing it for a whole book might be nontrivial. And, like this solution, it will be in place if we ever again make a mistake that leaves some languages without a style class.
Of course that would not be a great solution if we actually need to fix this across the whole book (e.g., to publish a broken one).
If it's not feasible I think this is worth a maintenance level. Numbers don't cost anything, and making one more number comparison is a whole lot cheaper than searching the whole book.
</blockquote></details>

I've moved the repair code to TranslationGroupManager, and adjusted the unit tests accordingly.
___
*[`src/BloomExe/Book/Book.cs` line 2307 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6712#-O9kOket29Ywid1yjC8N:-O9upctW0ZeGPsLP4cgq:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/677ecdec037328b08f7fbfe911ce33d6103c4fb0/src/BloomExe/Book/Book.cs#L2307)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

HtmlDom has a GetStyle method which looks appropriate here.
</blockquote></details>

Done.
___
*[`src/BloomExe/Book/Book.cs` line 2313 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6712#-O9kOy4E8uQ9JvPUnHZf:-O9uqQMt8cdx7gBEg0Cm:b-iz5aox) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/677ecdec037328b08f7fbfe911ce33d6103c4fb0/src/BloomExe/Book/Book.cs#L2313)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

HtmlDom has an AddClass method
</blockquote></details>

The method has shifted to SafeXmlElement, but I changed to using it.
___
*[`src/BloomExe/Book/Book.cs` line 2320 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6712#-O9kgCmE7CW_G-qMABgL:-O9uuSD21LfqsJ0UB9_g:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/677ecdec037328b08f7fbfe911ce33d6103c4fb0/src/BloomExe/Book/Book.cs#L2320)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We should hunt for this possibility in a separate loop, unless there is reason to be quite sure that a good block that already has a style will come before any that does not.
Also, check the classes of the TG. Sometimes that has the style, too.
</blockquote></details>

Done.

**Review by JohnThomson — COMMENTED** [review]
LGTM. Waiting for Andrew before merging.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6712#-:-O9ymrTZAmC2cAwQVRZK:bpux9h8)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6712)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by andrew-polk — APPROVED** [review]
> Dismissed @JohnThomson from a discussion.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6712)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
