### PR TITLE
BL-11492 Color Picker tweaks

### PR DESCRIPTION
**Pull request by gmartin7**
* add Alpha percentage tooltip

- - -
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5404)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5404)* status: all files reviewed, 4 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/react_components/color-picking/bloomSketchPicker.tsx` line 15 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5404#-NCfOauZ2ukZKu0S_S6E:-NCfOauZ2ukZKu0S_S6F:b-a8xwgu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/845adbd7a1fbb7ca9538f258d1c67b4bfac7ef45/src/BloomBrowserUI/react_components/color-picking/bloomSketchPicker.tsx#L15)):*
> ```XML
> 
>     // Needed for tooltip on Alpha slider
>     currentOpacity: number;
> ```

I'm not excited about this.
My gut was telling me we should already have the info we need.

But that led to some confusion. I see we are passing in `color` which isn't even in `IBloomSketchPickerProps`.

Anyway, can't you handle the onChange from Alpha and get the opacity like we do in colorPicker and then not have to pass the opacity back in?
___
*[`src/BloomBrowserUI/react_components/color-picking/bloomSketchPicker.tsx` line 23 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5404#-NCfMk1LAXuOIaS8vwdC:-NCfMk1LAXuOIaS8vwdD:b-hip9pt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/845adbd7a1fbb7ca9538f258d1c67b4bfac7ef45/src/BloomBrowserUI/react_components/color-picking/bloomSketchPicker.tsx#L23)):*
> ```XML
>         ((1 - props.currentOpacity) * 100).toFixed(0) + "%";
> 
>     const alphaSlider = () => <CustomSliderCursor tip={transparencyString} />;
> ```

alphaSliderCursor?



_Code quote:_
```XML
alphaSlider
```
___
*[`src/BloomBrowserUI/react_components/color-picking/customCursors.tsx` line 7 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5404#-NCfNBfmAPSbHfUOwcAH:-NCfNBfmAPSbHfUOwcAI:bjxx129) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/845adbd7a1fbb7ca9538f258d1c67b4bfac7ef45/src/BloomBrowserUI/react_components/color-picking/customCursors.tsx#L7)):*
> ```XML
> 
> const CustomSliderCursor: React.FunctionComponent<{
>     tip?: string;
> ```

tooltip?



_Code quote:_
```XML
tip
```
___
*[`src/BloomBrowserUI/react_components/color-picking/customCursors.tsx` line 16 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5404#-NCfNDkmChD0OBePFVHe:-NCfNDkmChD0OBePFVHf:b2iqlmm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/845adbd7a1fbb7ca9538f258d1c67b4bfac7ef45/src/BloomBrowserUI/react_components/color-picking/customCursors.tsx#L16)):*
> ```XML
>         if (props.tip.length === 4 || props.tip[0] === "9") return "0";
>         return props.tip[0] === "1" ? "-14" : "-12";
>     };
> ```

Do these margin values still work when the display is scaled?

I think I've seen things be able to calculate the actual size of objects. Did you explore that at all? Seems like this is only approximating. (For example, you have a different value if the first number is 1 but not if the second is.) But maybe that is close enough (at least if scaling works)?

Maybe worth a comment saying while it isn't perfectly accurate, it is close enough for our purposes?

Did you look into using a tooltip library instead? I'm pretty sure we have at least one already included.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5404)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/react_components/color-picking/bloomSketchPicker.tsx` line 15 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5404#-NCfOauZ2ukZKu0S_S6E:-NCfi2Ye7TjdkFL5qkmF:bwqq31s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/845adbd7a1fbb7ca9538f258d1c67b4bfac7ef45/src/BloomBrowserUI/react_components/color-picking/bloomSketchPicker.tsx#L15)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not excited about this.
My gut was telling me we should already have the info we need.

But that led to some confusion. I see we are passing in `color` which isn't even in `IBloomSketchPickerProps`.

Anyway, can't you handle the onChange from Alpha and get the opacity like we do in colorPicker and then not have to pass the opacity back in?
</blockquote></details>

Yeah, I tried that (getting the opacity from the onChange handler). I think it was something about the way we make a HOC of BloomSketchPicker by doing

`export default CustomPicker(BloomSketchPicker);`

As a result, the handler inside of BloomSketchPicker didn't seem to have any useful information for using inside there, i.e. the color result was always empty. :(
BTW, that HOC is where the exterior color prop and the signature of the `onChange` prop come from too.
___
*[`src/BloomBrowserUI/react_components/color-picking/bloomSketchPicker.tsx` line 23 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5404#-NCfMk1LAXuOIaS8vwdC:-NCfid6064SDMsQEX7Fo:b-qqm6e8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/845adbd7a1fbb7ca9538f258d1c67b4bfac7ef45/src/BloomBrowserUI/react_components/color-picking/bloomSketchPicker.tsx#L23)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

alphaSliderCursor?
</blockquote></details>

Done. Sure.
___
*[`src/BloomBrowserUI/react_components/color-picking/customCursors.tsx` line 7 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5404#-NCfNBfmAPSbHfUOwcAH:-NCfjM202Vxytf7oIOOY:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/845adbd7a1fbb7ca9538f258d1c67b4bfac7ef45/src/BloomBrowserUI/react_components/color-picking/customCursors.tsx#L7)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

tooltip?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/react_components/color-picking/customCursors.tsx` line 16 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5404#-NCfNDkmChD0OBePFVHe:-NCg1w3B05tTvOu5PUzb:b-2ouw3p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/845adbd7a1fbb7ca9538f258d1c67b4bfac7ef45/src/BloomBrowserUI/react_components/color-picking/customCursors.tsx#L16)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Do these margin values still work when the display is scaled?

I think I've seen things be able to calculate the actual size of objects. Did you explore that at all? Seems like this is only approximating. (For example, you have a different value if the first number is 1 but not if the second is.) But maybe that is close enough (at least if scaling works)?

Maybe worth a comment saying while it isn't perfectly accurate, it is close enough for our purposes?

Did you look into using a tooltip library instead? I'm pretty sure we have at least one already included.
</blockquote></details>

Works fine when scaled with Windows display settings. Bloom scaling doesn't affect size of dialogs, oddly enough. Commented.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5404)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/react_components/color-picking/customCursors.tsx` line 16 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5404#-NCfNDkmChD0OBePFVHe:-NCgHvms5TTlZEquJie_:b6ybkrd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/845adbd7a1fbb7ca9538f258d1c67b4bfac7ef45/src/BloomBrowserUI/react_components/color-picking/customCursors.tsx#L16)):*
Thanks.

You didn't respond to 
> Did you look into using a tooltip library instead? I'm pretty sure we have at least one already included.

e.g. react-tooltip

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5404)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/react_components/color-picking/customCursors.tsx` line 16 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5404#-NCfNDkmChD0OBePFVHe:-NCgM7rBCXpLGpxrZKcZ:bm1w2hg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/845adbd7a1fbb7ca9538f258d1c67b4bfac7ef45/src/BloomBrowserUI/react_components/color-picking/customCursors.tsx#L16)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Thanks.

You didn't respond to 
> Did you look into using a tooltip library instead? I'm pretty sure we have at least one already included.

e.g. react-tooltip
</blockquote></details>

No, I haven't yet. I can look at that Monday.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5404)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/react_components/color-picking/customCursors.tsx` line 16 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5404#-NCfNDkmChD0OBePFVHe:-NCgOBh36CTJo-MtKFiq:bwyk83r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/845adbd7a1fbb7ca9538f258d1c67b4bfac7ef45/src/BloomBrowserUI/react_components/color-picking/customCursors.tsx#L16)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

No, I haven't yet. I can look at that Monday.
</blockquote></details>

Apparently we have a BloomTooltip component.
But you can also try just giving the div a title. That's what we do many places.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5404)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/react_components/color-picking/customCursors.tsx` line 16 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5404#-NCfNDkmChD0OBePFVHe:-NCun63TA3SESIdbzz8j:b-q64luu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/845adbd7a1fbb7ca9538f258d1c67b4bfac7ef45/src/BloomBrowserUI/react_components/color-picking/customCursors.tsx#L16)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Apparently we have a BloomTooltip component.
But you can also try just giving the div a title. That's what we do many places.
</blockquote></details>

The div `title` actually worked pretty well! I thought I tried it earlier and it didn't. Oh well.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5404)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
