### PR TITLE
Clarify installation of fonts on Linux

### PR DESCRIPTION
**Pull request by ermshiperete**

### CODE REVIEW

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-master-debug/340/
Test FAILed.

**Comment by ermshiperete** [comment]
retest this please

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-master-debug/341/
Test PASSed.

**Comment by StephenMcConnel** [comment]
looks good to me.

**Pull request merged**
