### PR TITLE
Improve default folder choice for SS import/export (BL-10740)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4891)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4891)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Book/BookInfo.cs, line 1514 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4891#-MrP7Lli9S9a7Knq7Slx:-MrP7Lli9S9a7Knq7Sly:b7m2n7q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/00efb8f742a0843f556d79e602674bfa10fec946/src/BloomExe/Book/BookInfo.cs#L1514)):*
> ```Smalltalk
> 		// nor useful to share between computers?
> 		[JsonProperty("spreadsheetFolder")]
> 		public string SpreadsheetFolder { get; set; }
> ```

I thought we were going to use `book.userPrefs`.
___
*[src/BloomExe/web/controllers/BookCommandsApi.cs, line 154 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4891#-MrP81Do65CqsH8ITqUo:-MrP81Do65CqsH8ITqUp:bebg2b1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/00efb8f742a0843f556d79e602674bfa10fec946/src/BloomExe/web/controllers/BookCommandsApi.cs#L154)):*
> ```Smalltalk
> 		/// we only have to change one thing if we decide to do it differently.
> 		/// </summary>
> 		/// <param name="book"></param>
> ```

These two lines are clutter, imo.



_Code quote:_
```Smalltalk
		/// <param name="book"></param>
		/// <returns></returns>
```
___
*[src/BloomExe/web/controllers/BookCommandsApi.cs, line 241 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4891#-MrP8hAo5SnJsv9ZyO5T:-MrP8hAo5SnJsv9ZyO5U:b-1z2o3j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/00efb8f742a0843f556d79e602674bfa10fec946/src/BloomExe/web/controllers/BookCommandsApi.cs#L241)):*
> ```Smalltalk
> 					{
> 						// Fall back to the last place used for ANY import or export, or if there is no such, the system Documents folder.
> 						initialFolder = !String.IsNullOrWhiteSpace(Settings.Default.ExportImportFileFolder) ? Settings.Default.ExportImportFileFolder : Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
> ```

In both cases where we call GetSpreadsheetFolderFor, we then have this same if-null logic with the same assignment. Should we fold that into the method?

Hm. I guess the complication is that in one place we need the parent and one we don't.

Well, we could pass a parameter for that. Or if that doesn't feel good, we could at least extract this fallback logic to a common method.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4891)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/web/controllers/BookCommandsApi.cs, line 154 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4891#-MrP81Do65CqsH8ITqUo:-MrSSZiZAFBNCArK5q2A:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/00efb8f742a0843f556d79e602674bfa10fec946/src/BloomExe/web/controllers/BookCommandsApi.cs#L154)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

These two lines are clutter, imo.
</blockquote></details>

Done.
___
*[src/BloomExe/web/controllers/BookCommandsApi.cs, line 241 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4891#-MrP8hAo5SnJsv9ZyO5T:-MrSSaAQ9x59sYi15Vvn:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/00efb8f742a0843f556d79e602674bfa10fec946/src/BloomExe/web/controllers/BookCommandsApi.cs#L241)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

In both cases where we call GetSpreadsheetFolderFor, we then have this same if-null logic with the same assignment. Should we fold that into the method?

Hm. I guess the complication is that in one place we need the parent and one we don't.

Well, we could pass a parameter for that. Or if that doesn't feel good, we could at least extract this fallback logic to a common method.
</blockquote></details>

Done.
___
*[src/BloomExe/Book/BookInfo.cs, line 1514 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4891#-MrP7Lli9S9a7Knq7Slx:-MrSSbQn4KFbW2Hf5V9Y:b-f3o4xh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/00efb8f742a0843f556d79e602674bfa10fec946/src/BloomExe/Book/BookInfo.cs#L1514)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I thought we were going to use `book.userPrefs`.
</blockquote></details>

Didn't get recorded, and I could not find it. Done now.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4891)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Book/UserPrefs.cs, line 110 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4891#-MrSmIuF9XmlXd9joPb-:-MrSmIuF9XmlXd9joPb0:bbsgvhb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/72d2124ae2031375be1c25dee40d889b8a4e75dc/src/BloomExe/Book/UserPrefs.cs#L110)):*
```
> Be careful...if meta.json was shared from another 
> // computer, this might be a path to a folder that does not exist. If so, it should be ignored.
```
The meta.json part is out of date. 
But I think the comment could be made more generic. Copying from elsewhere isn't the only reason the path may not exist. (User could have removed it, etc.)
So it could probably be something like
> Caller should verify the path exists.



_Code quote:_
```Smalltalk
		// Null for books where either has never happened. Be careful...if meta.json was shared from another
		// computer, this might be a path to a folder that does not exist. If so, it should be ignored.
```

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4891)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Book/UserPrefs.cs, line 110 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4891#-MrSmIuF9XmlXd9joPb-:-MrYwG_79oMB_sxTy0qx:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/72d2124ae2031375be1c25dee40d889b8a4e75dc/src/BloomExe/Book/UserPrefs.cs#L110)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

```
> Be careful...if meta.json was shared from another 
> // computer, this might be a path to a folder that does not exist. If so, it should be ignored.
```
The meta.json part is out of date. 
But I think the comment could be made more generic. Copying from elsewhere isn't the only reason the path may not exist. (User could have removed it, etc.)
So it could probably be something like
> Caller should verify the path exists.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4891)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
