### PR TITLE
Nicely report corrupt .bloom files in TC (BL-10097)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4575)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4575)* status: all files reviewed, 7 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/react_components/stringWithOptionalLink.tsx, line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4575#-MdxqqP4BM3HKTSddjSj:-MdxqqP4BM3HKTSddjSk:b-b3r037) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0eeb70a9f4c525a6c5dd74c4855c02b0030948a/src/BloomBrowserUI/react_components/stringWithOptionalLink.tsx#L13)):*
> ```
> /^(.*?)<a[^>]*?href='([^>']+)'[^>]*>(.*?)<\/a>(.*)$/
> ```
feel free to say YAGNI, but should we support double quote for the href?
___
*[src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, line 60 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4575#-MdxrGMX0xu7ZGwDhyvO:-MdxrGMX0xu7ZGwDhyvP:b-etzdka) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0eeb70a9f4c525a6c5dd74c4855c02b0030948a/src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx#L60)):*
> ```
> any
> ```
IBookTeamCollectionStatus would be preferable.

I guess that would mean you'd have to create a 
`const initialBookTeamCollectionStatus = { unfortunately list everything }`.
___
*[src/BloomExe/TeamCollection/BookStatus.cs, line 21 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4575#-MdxsElm71pv47btpW2h:-MdxsElm71pv47btpW2i:bb8bd68) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0eeb70a9f4c525a6c5dd74c4855c02b0030948a/src/BloomExe/TeamCollection/BookStatus.cs#L21)):*
> ```
> invalidRepoData
> ```
hasInvalidRepoData?
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 241 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4575#-MdxvOWE1EoWH04o3I3-:-MdxvOWE1EoWH04o3I30:bwomyg2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0eeb70a9f4c525a6c5dd74c4855c02b0030948a/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L241)):*
> ```Smalltalk
> 			
> 			var pattern = new Regex(@"\[(.*)\]");
> 			var part2 = pattern.Replace(template2, $"<a href='/bloom/api/teamCollection/reportBadZip?file={ UrlPathString.CreateFromUnencodedString(zipPath).UrlEncoded}'>$1</a>");
> ```

Do we need/want to do anything to to handle the case where the translator messed up and didn't provide square brackets?
As is, I think it will put in an empty a tag -- which might be ok?
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1645 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4575#-Mdxxp3l9KH-YbpBaFtY:-Mdxxp3mAa8e55ND5SJ3:bv9q1vy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0eeb70a9f4c525a6c5dd74c4855c02b0030948a/src/BloomExe/TeamCollection/TeamCollection.cs#L1645)):*
> ```
> Return true if there is a problem.
> ```
I was finding this unexpected when looking at the callers. It seemed the natural expectation was to return true on success.

How would you feel about reversing the logic and making it something like `TryCopyBookFromRepoToLocalAndThenReport`?
___
*[src/BloomTests/TeamCollection/FolderTeamCollectionTests2.cs, line 475 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4575#-Mdxt8cM7sLxB4jjgz9w:-Mdxt8cNE-NAAPMURPCO:bp2vhuh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0eeb70a9f4c525a6c5dd74c4855c02b0030948a/src/BloomTests/TeamCollection/FolderTeamCollectionTests2.cs#L475)):*
> ```Smalltalk
> 			{
> 				using (var repoFolder =
> 					new TemporaryFolder("ChangeToFileInOther_FromLocal_DoesNothingUnexpected"))
> ```

Both temporary folders want different names.
___
*[src/BloomTests/TeamCollection/FolderTeamCollectionTests2.cs, line 480 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4575#-MdxtQQQ4WAKMBcL8h4R:-MdxtQQQ4WAKMBcL8h4S:boz8ffz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0eeb70a9f4c525a6c5dd74c4855c02b0030948a/src/BloomTests/TeamCollection/FolderTeamCollectionTests2.cs#L480)):*
> ```
> Roses are red. Violets are blue.
> ```
A suggestion you can take or leave: you could use `Roses are red & Violets are blue.`

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4575)* status: 8 of 15 files reviewed, 6 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/react_components/stringWithOptionalLink.tsx, line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4575#-MdxqqP4BM3HKTSddjSj:-Me0clwh743hsOA52wD1:b-7ouhsw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0eeb70a9f4c525a6c5dd74c4855c02b0030948a/src/BloomBrowserUI/react_components/stringWithOptionalLink.tsx#L13)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> /^(.*?)<a[^>]*?href='([^>']+)'[^>]*>(.*?)<\/a>(.*)$/
> ```
feel free to say YAGNI, but should we support double quote for the href?
</blockquote></details>

Good question. Rather than make an already complex RE even more difficult, I decided to add a comment. Currently we're only using this in ONE place; if it proves more generally useful we can consider improving it. But these strings will typically come from C# or Javascript literals, so single quotes are much more likely to be easy to use.
___
*[src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, line 60 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4575#-MdxrGMX0xu7ZGwDhyvO:-Me0dCvk6NsFvpFD-mDE:b88pbh3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0eeb70a9f4c525a6c5dd74c4855c02b0030948a/src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx#L60)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> any
> ```
IBookTeamCollectionStatus would be preferable.

I guess that would mean you'd have to create a 
`const initialBookTeamCollectionStatus = { unfortunately list everything }`.
</blockquote></details>

Yes. Also, I'm partly borrowing this change from a change JohnH did that is on master, and the merge is already going to be a pain.
___
*[src/BloomExe/TeamCollection/BookStatus.cs, line 21 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4575#-MdxsElm71pv47btpW2h:-Me0eUzT432fGKCaSibq:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0eeb70a9f4c525a6c5dd74c4855c02b0030948a/src/BloomExe/TeamCollection/BookStatus.cs#L21)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> invalidRepoData
> ```
hasInvalidRepoData?
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 241 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4575#-MdxvOWE1EoWH04o3I3-:-Me0f0Wq3TNp3quT2V2P:b-tvk8w5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0eeb70a9f4c525a6c5dd74c4855c02b0030948a/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L241)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Do we need/want to do anything to to handle the case where the translator messed up and didn't provide square brackets?
As is, I think it will put in an empty a tag -- which might be ok?
</blockquote></details>

What I think will happen is that the regex won't match, which means the translation of "here" won't become a link. That would be somewhat unfortunate. I had a go.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1645 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4575#-Mdxxp3l9KH-YbpBaFtY:-Me0hB-CB0ab829KUvLa:b12hkxe) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0eeb70a9f4c525a6c5dd74c4855c02b0030948a/src/BloomExe/TeamCollection/TeamCollection.cs#L1645)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Return true if there is a problem.
> ```
I was finding this unexpected when looking at the callers. It seemed the natural expectation was to return true on success.

How would you feel about reversing the logic and making it something like `TryCopyBookFromRepoToLocalAndThenReport`?
</blockquote></details>

I've reversed the logic. Don't like using Try when we're not following the pattern of trying to get something through an out param.
___
*[src/BloomTests/TeamCollection/FolderTeamCollectionTests2.cs, line 475 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4575#-Mdxt8cM7sLxB4jjgz9w:-Me0inA4-t5l9QSewg6-:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0eeb70a9f4c525a6c5dd74c4855c02b0030948a/src/BloomTests/TeamCollection/FolderTeamCollectionTests2.cs#L475)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Both temporary folders want different names.
</blockquote></details>

Done.
___
*[src/BloomTests/TeamCollection/FolderTeamCollectionTests2.cs, line 480 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4575#-MdxtQQQ4WAKMBcL8h4R:-Me0ikhx0un4xGBmoI-_:bb6un1j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c0eeb70a9f4c525a6c5dd74c4855c02b0030948a/src/BloomTests/TeamCollection/FolderTeamCollectionTests2.cs#L480)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Roses are red. Violets are blue.
> ```
A suggestion you can take or leave: you could use `Roses are red & Violets are blue.`
</blockquote></details>

Done

**Review by andrew-polk — APPROVED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4575)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4575)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
