### PR TITLE
Handle changes to BloomPlayer file names

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3635)

### CODE REVIEW

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3635)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/gulpfile.js, line 70 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3635#-M1QrdT59Ui5zRUjWqCX:-M1QrdT59Ui5zRUjWqCY:b-vo1x1i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4ec47a749446de92bcf5f1bed7c43ebf46df3bbd/src/BloomBrowserUI/gulpfile.js#L70)):*
> ```JavaScript
>     ],
>     nodeFilesNeededInOutput: [
>         "./**/bloom-player/dist/bloomPlayer*.min.js",
> ```

Could you stick a comment above these pointing out the * and explaining why it is there? Then just merge, thanks.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3635)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/gulpfile.js, line 72 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3635#-M1QvxJFBCqwLaa_uV7n:-M1QvxJFBCqwLaa_uV7o:b-pppr2a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4ec47a749446de92bcf5f1bed7c43ebf46df3bbd/src/BloomBrowserUI/gulpfile.js#L72)):*
> ```JavaScript
>         "./**/bloom-player/dist/bloomPlayer*.min.js",
>         // doesn't exist currently, may be needed again later, possibly with a hash.
>         //"./**/bloom-player/dist/simpleComprehensionQuiz.js",
> ```

See my question about this in the bloom-player PR before merging.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3635)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/gulpfile.js, line 70 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3635#-M1QrdT59Ui5zRUjWqCX:-M1RrTYP3fypkqP7FheC:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4ec47a749446de92bcf5f1bed7c43ebf46df3bbd/src/BloomBrowserUI/gulpfile.js#L70)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Could you stick a comment above these pointing out the * and explaining why it is there? Then just merge, thanks.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3635)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Review by andrew-polk — APPROVED** [review]
> Dismissed @hatton from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3635)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
