### PR TITLE
Fix problems if book title contains period (BL-10520)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4844)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
You may wish to review the 2 commits separately (in GitHub)

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4844#-:-MprG-pNDtxKjuuUGLz9:b-apsmg1)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by JohnThomson — CHANGES_REQUESTED** [review]
Looks good with two minor requests

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4844#-:-MprsBd-4u_kmn1Ch_RR:bm4fnsb)* status: all files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/Book/BookStorage.cs, line 226 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4844#-MprrubJ3sRoexkRFQlS:-MprrubK8qtxzMcI2MDA:b-5j3ujq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/33e7347eb1bf792b5a479ddbd81747145aa7d137/src/BloomExe/Book/BookStorage.cs#L226)):*
> ```Smalltalk
> 			{
> 				// Path.GetFileName will return empty string if the FolderPath ends with "/"
> 				Debug.Assert(!FolderPath.EndsWith(Path.DirectorySeparatorChar.ToString()), "FolderPath is expected not to include a trailing slash, otherwise the folder's name will be determined incorrectly.");
> ```

Let's test that this doesn't fire, both when folder is automatically named by changing title to end in backslash, and when user rename command does the same.
___
*[src/BloomExe/Book/BookStorage.cs, line 230 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4844#-MprqR_954ncqRFbuTnh:-MprqR_954ncqRFbuTni:b2gmz4v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/33e7347eb1bf792b5a479ddbd81747145aa7d137/src/BloomExe/Book/BookStorage.cs#L230)):*
> ```Smalltalk
> 				// so GetFileNameWithoutExtension will return the wrong result if the folder name contains a period
> 				/// GetDirectoryName will get the parent directory (which we don't want) if the FolderPath ends with "/",
> 				/// // but would return the desired result is the FolderPath does end with "/"
> ```

Not really. It would return a full path to the parent folder. We'd need GetFileName(GetDirectoryName(FolderPath)).

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4844)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Book/BookStorage.cs, line 226 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4844#-MprrubJ3sRoexkRFQlS:-MpwZiCj-S07EAy6CYyo:bkxk7gl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/33e7347eb1bf792b5a479ddbd81747145aa7d137/src/BloomExe/Book/BookStorage.cs#L226)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Let's test that this doesn't fire, both when folder is automatically named by changing title to end in backslash, and when user rename command does the same.
</blockquote></details>

Good thought. Works fine, the upstream code detects that there's a backslash and handles the case.
___
*[src/BloomExe/Book/BookStorage.cs, line 230 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4844#-MprqR_954ncqRFbuTnh:-MpwZt8h0NmTdNZ-mFBl:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/33e7347eb1bf792b5a479ddbd81747145aa7d137/src/BloomExe/Book/BookStorage.cs#L230)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Not really. It would return a full path to the parent folder. We'd need GetFileName(GetDirectoryName(FolderPath)).
</blockquote></details>

Done.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4844)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Review by JohnThomson — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4844)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Pull request merged**
