### PR TITLE
Allow generated thumbnails to be displayed in Add Page dialog (BL-13722)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
Also fix an annoying misspelled URL parameter name.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6595)

### CODE REVIEW

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6595)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx` line 149 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6595#-O3eMk9c40yVKP4N5SMc:-O3eMk9c40yVKP4N5SMd:b7nf2xx) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9ee361a6cfd7e6ba5bfaa671aec6f37b848cdf4d/src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx#L149)):*
> ```XML
>                 // to the updated thumbnail image.
>                 if (imgSrc.startsWith(updatedThumbUrl)) {
>                     const newSrc = imgSrc + "&reload=" + internalCounter++;
> ```

so just to confirm, `imgSrc` _always_ has a `?generateThumbnailIfNecessary` so that we just want "&" here?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6595)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx` line 149 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6595#-O3eMk9c40yVKP4N5SMc:-O3hBKyN2FW56HAOcmDH:b94j17y) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9ee361a6cfd7e6ba5bfaa671aec6f37b848cdf4d/src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx#L149)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

so just to confirm, `imgSrc` _always_ has a `?generateThumbnailIfNecessary` so that we just want "&" here?
</blockquote></details>

The getTemplatePageImageSource method always tacks this onto the image source string returned.
When I was logging the strings in this method while working on this issue, the imgSrc values logged always had that at the end.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6595)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx` line 149 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6595#-O3eMk9c40yVKP4N5SMc:-O3hCBDj8habuAeDpdyq:b-9v71kl) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9ee361a6cfd7e6ba5bfaa671aec6f37b848cdf4d/src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx#L149)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

The getTemplatePageImageSource method always tacks this onto the image source string returned.
When I was logging the strings in this method while working on this issue, the imgSrc values logged always had that at the end.
</blockquote></details>

But I can restore the ? since the purpose here is to change the URL, not to extract a parameter value.

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6595)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx` line 149 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6595#-O3eMk9c40yVKP4N5SMc:-O3iaxnd6UDAoSW0jtje:b-v4gcqg) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9ee361a6cfd7e6ba5bfaa671aec6f37b848cdf4d/src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx#L149)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

But I can restore the ? since the purpose here is to change the URL, not to extract a parameter value.
</blockquote></details>

I'm confused because Reviewable isn't showing me any version that has `&` but apparently it was there, prompting my question. Sigh. Anyhow I'll approve but this does seem pretty fragile, constructing these? If there was some easy .net method that would say "here's a URL, add this parameter" then it would be robust against some other part of the code also adding a parameter?

**Pull request merged**
