### PR TITLE
Fix Error.NotifyUserOfProblem while in a locked API call (BL-9920)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4537)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4537)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/web/controllers/CommonApi.cs, line 156 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4537#-MbNwaww0vard4BVP3_j:-MbNwaww0vard4BVP3_k:b-2b9nsn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/62224ffc8e9e0a55bf454c59d11e607c9eadf147/src/BloomExe/web/controllers/CommonApi.cs#L156)):*
> ```
> requiresSync: false
> ```
This is the actual fix. The other change is just an improvement for moving forward.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4537)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/MiscUI/ReactDialog.cs, line 100 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4537#-MbhMWMV-NfbfuihjrJ8:-MbhMWMV-NfbfuihjrJ9:b-dj3uwf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/62224ffc8e9e0a55bf454c59d11e607c9eadf147/src/BloomExe/MiscUI/ReactDialog.cs#L100)):*
> ```Smalltalk
> 
> 			Application.Idle += HandleAction;
> 		}
> ```

This feels a little too generic to me. It could be called "DoOnceOnIdle" and used for any task. And the things that the other overload does will almost always be needed...why make any client that needs something more reimplement the basics too?
How about making this private, perhaps with another name, but adding to the other overload a couple of optional arguments:
Action<ReactDialog> initialize = null // done after setting width and height but before ShowDialog()
Action<DialogResult> handleResult = null // passed whatever ShowDialog returns (or whatever the close action passed, or something like that).
Then you've covered all the likely ways of customizing how the ReactDialog is used.

We're also getting to the sort of complexity of arguments where it might make sense to go to a Javascripty API, where ShowOnIdle is passed a ReactDialogParams object in which various fields can be set if you don't want the defaults. Maybe just the reactComponent has no default and must be passed separately from ReactDialogParams.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4537)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/MiscUI/ReactDialog.cs, line 100 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4537#-MbhMWMV-NfbfuihjrJ8:-Mbh_-sACTxz-0mewx-W:b-e4rvgn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/62224ffc8e9e0a55bf454c59d11e607c9eadf147/src/BloomExe/MiscUI/ReactDialog.cs#L100)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This feels a little too generic to me. It could be called "DoOnceOnIdle" and used for any task. And the things that the other overload does will almost always be needed...why make any client that needs something more reimplement the basics too?
How about making this private, perhaps with another name, but adding to the other overload a couple of optional arguments:
Action<ReactDialog> initialize = null // done after setting width and height but before ShowDialog()
Action<DialogResult> handleResult = null // passed whatever ShowDialog returns (or whatever the close action passed, or something like that).
Then you've covered all the likely ways of customizing how the ReactDialog is used.

We're also getting to the sort of complexity of arguments where it might make sense to go to a Javascripty API, where ShowOnIdle is passed a ReactDialogParams object in which various fields can be set if you don't want the defaults. Maybe just the reactComponent has no default and must be passed separately from ReactDialogParams.

</blockquote></details>

Done. Since nothing is actually using it yet, I'm not inclined to complicate things further.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4537)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Pull request merged**
