### PR TITLE
Let Autofac create just one team collection (BL-9482)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 5 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175)* status: 5 of 13 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamRepo.cs, line 74 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoHAI-2-34fqRU_hY7:-MSoHAI-2-34fqRU_hY8:b-vu82dj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomExe/TeamCollection/TeamRepo.cs#L74)):*
> ```Smalltalk
> 		}
> 
> 		public void PutAllBooks()
> ```

As a public method, this wants a significant header comment. 

Also, the name isn't quite right. It doesn't put all books, but rather, I think (?) those that need updating.

I had to read the code to figure out which direction "put" means. Would this be an accurate name? `SynchronizeBooksFromLocalToRepoFolder()`

**Review by andrew-polk — APPROVED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamRepo.cs, line 312 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoIe37-FBccN8ITFb0:-MSoIe37-FBccN8ITFb1:b-qgfh44) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomExe/TeamCollection/TeamRepo.cs#L312)):*
> ```Smalltalk
> 				PutFile(collectionStylesPath);
> 			var collectionName = Path.GetFileName(localCollectionFolder);
> 			PutFile(Path.Combine(localCollectionFolder, Path.ChangeExtension(collectionName, "bloomCollection")));
> ```

I was confused about this only partial work on BL-9487 here, but I guess since that card exists, that's fine.
___
*[src/BloomExe/TeamCollection/TeamRepo.cs, line 655 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoL2ro7n0rIVrRKjCh:-MSoL2ro7n0rIVrRKjCi:bxo5p48) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomExe/TeamCollection/TeamRepo.cs#L655)):*
> ```Smalltalk
> 			{
> 				// Todo: localize. Not adding to XLF now because we want to move to a quite different UI.
> 				MessageBox.Show("Bloom found some problems while loading changes from your team collection:"
> ```

We don't want any UI calls from this library (among other things, it makes unit testing impossible). We also don't use raw `MessageBox` calls anymore. Instead,  you want to go through the problem report layer.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamRepo.cs, line 665 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoLcasAKfVddRVVY_Q:-MSoLcasAKfVddRVVY_R:b-vy40io) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomExe/TeamCollection/TeamRepo.cs#L665)):*
> ```Smalltalk
> 	/// Methods that need data from the team collection or modify it should not be called if this is false.
> 	/// </summary>
> 	public abstract bool HasTeamCollection { get; }
> ```

We currently have an awkward name distinction  between "TeamCollection" and "TeamRepo". The existence of this property implies that you can have a TeamRepo, without having a TeamCollection.  Does that suggest a name for TeamRepo like `TeamCollectionManager`?
___
*[src/BloomTests/TeamCollection/FolderTeamRepoTests2.cs, line 16 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoMpgM3XRn8jL9W53e:-MSoMpgM3XRn8jL9W53f:bvinkrr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomTests/TeamCollection/FolderTeamRepoTests2.cs#L16)):*
> ```Smalltalk
> 	/// <summary>
> 	/// The main FolderTeamRepoTests class is mostly made up of tests that benefit from a OneTimeSetup
> 	/// function that creates a repo already connected and having some content. This class is for tests
> ```

This is a good example of where I get confused by the "repo" name, so long as it is distinct from TeamCollection. I can't tell if what one has to set up is the TC, or rather this class that itself can create TCs.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175)* status: all files reviewed, 7 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/FolderTeamRepo.cs, line 410 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoNEJa9nRQKq8j3OXd:-MSoNEJa9nRQKq8j3OXe:b-fjlx4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomExe/TeamCollection/FolderTeamRepo.cs#L410)):*
> ```Smalltalk
> 		}
> 
> 		public static void CreateTeamSettingsFile(string collectionFolder, string teamCollectionFolder) {
> ```

I think we want TeamCollectionSettings in the name and the file. There could well be other "team" settings in the future, but "TeamCollection" is what we're building here.
___
*[src/BloomExe/TeamCollection/TeamRepo.cs, line 96 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoNc0UBPPoazX2DFfb:-MSoNc0UBPPoazX2DFfc:b-q45pcw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomExe/TeamCollection/TeamRepo.cs#L96)):*
> ```Smalltalk
> 					SentrySdk.AddBreadcrumb(msg);
> 					SentrySdk.CaptureException(ex);
> 					MessageBox.Show(msg, "Copy Failed");
> ```

Let's not use raw messageboxes.
___
*[src/BloomExe/TeamCollection/TeamRepo.cs, line 655 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoL2ro7n0rIVrRKjCh:-MSoNk3137TMjlW69g6A:b-yl40cw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomExe/TeamCollection/TeamRepo.cs#L655)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

We don't want any UI calls from this library (among other things, it makes unit testing impossible). We also don't use raw `MessageBox` calls anymore. Instead,  you want to go through the problem report layer.
</blockquote></details>

Maybe once you change to  problem report call maybe unit-tests can prevent ui and check that it was raised?

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 3 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175)* status: all files reviewed, 9 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomTests/TeamCollection/FolderTeamRepoTests2.cs, line 27 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoPIpC6pvEp5v46Rhy:-MSoPIpC6pvEp5v46Rhz:bc0ala6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomTests/TeamCollection/FolderTeamRepoTests2.cs#L27)):*
> ```Smalltalk
> 				using (var sharedFolder = new TemporaryFolder("FolderTeamRepoTests2_Shared"))
> 				{
> 					var bookFolderPath = Path.Combine(collectionFolder.FolderPath, "Some book");
> ```

Is there by any chance a more centralized way of making a valid book from tests? It's painful to think of what it would mean to have to go fix a thousand tests that individually "know" what is needed to be a Bloom book.

Even in this context of TC alone, since we're going to have lots of tests, presumably a lot of this can be usefully factored out even now with only one caller, to lead those who follow down a happily factored path.
___
*[src/BloomTests/TeamCollection/FolderTeamRepoTests2.cs, line 52 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoQ2lUC7Vf1-fxqVSS:-MSoQ2lUC7Vf1-fxqVST:b-k5jsmy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomTests/TeamCollection/FolderTeamRepoTests2.cs#L52)):*
> ```Smalltalk
> 						Path.Combine(collectionFolder.FolderPath, "TeamSettings.xml");
> 					Assert.That(File.Exists(teamCollectionSettingsPath));
> 					Assert.That(RobustFile.ReadAllText(teamCollectionSettingsPath), Contains.Substring("<teamCollectionFolder>" + sharedFolder.FolderPath+"</teamCollectionFolder>"));
> ```

To my eyes camel casing looks weird on xml. In *.BloomCollection, we use PascalCasing.

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 3 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175)* status: all files reviewed, 10 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/CollectionTab/LibraryModel.cs, line 150 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoaMB6DzFfZsRE4Kok:-MSoaMB6DzFfZsRE4Kol:btz54q7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomExe/CollectionTab/LibraryModel.cs#L150)):*
> ```Smalltalk
> 			// and also using it to show any errors. But it's the latest we can do it without needing to reconcile
> 			// the changes it makes with collection data we've loaded.
> 			_repo.MergeSharedData();
> ```

We don't quite live up to "merge" ;-) How about `SynchronizeSharedAndLocalFolders()` ?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175)* status: all files reviewed, 10 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/CollectionTab/LibraryModel.cs, line 150 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoaMB6DzFfZsRE4Kok:-MSsFJOX8lnwJY5J4Nly:b-f4851b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomExe/CollectionTab/LibraryModel.cs#L150)):*
> SynchronizeSharedAndLocalFolders
Went with SynchronizeSharedAndLocal. The shared data is not necessarily always going to be a shared folder, so I've been trying not to describe it that way except in FolderTeamRepo.
___
*[src/BloomExe/TeamCollection/FolderTeamRepo.cs, line 410 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoNEJa9nRQKq8j3OXd:-MSoW94zBriPqcJRvzrN:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomExe/TeamCollection/FolderTeamRepo.cs#L410)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think we want TeamCollectionSettings in the name and the file. There could well be other "team" settings in the future, but "TeamCollection" is what we're building here.
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamRepo.cs, line 74 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoHAI-2-34fqRU_hY7:-MSoWuz8DE_Eqfs7hHEu:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomExe/TeamCollection/TeamRepo.cs#L74)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

As a public method, this wants a significant header comment. 

Also, the name isn't quite right. It doesn't put all books, but rather, I think (?) those that need updating.

I had to read the code to figure out which direction "put" means. Would this be an accurate name? `SynchronizeBooksFromLocalToRepoFolder()`
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamRepo.cs, line 96 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoNc0UBPPoazX2DFfb:-MSoXoKMANvHagEsT7Db:b-h64hv2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomExe/TeamCollection/TeamRepo.cs#L96)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Let's not use raw messageboxes.
</blockquote></details>

Changed to NonFatalProblem.Report for now. But probably we'll eventually use a progress/error reporter dialog here, too.
___
*[src/BloomExe/TeamCollection/TeamRepo.cs, line 312 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoIe37-FBccN8ITFb0:-MSoY0tHB8JOjjFhaHuv:b-yv40t6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomExe/TeamCollection/TeamRepo.cs#L312)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I was confused about this only partial work on BL-9487 here, but I guess since that card exists, that's fine.
</blockquote></details>

Yes, I was trying to focus on getting the core stuff to happen in the right places.
___
*[src/BloomExe/TeamCollection/TeamRepo.cs, line 655 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoL2ro7n0rIVrRKjCh:-MSoYNt89JcHf5q2E3cQ:b1c7k93) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomExe/TeamCollection/TeamRepo.cs#L655)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Maybe once you change to  problem report call maybe unit-tests can prevent ui and check that it was raised?
</blockquote></details>

This is deliberately a temporary fix...we have BL-9485 for how we want to do this. There are comprehensive tests that SyncAtStartup() generates the right messages.
___
*[src/BloomExe/TeamCollection/TeamRepo.cs, line 665 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoLcasAKfVddRVVY_Q:-MSoZLBw4i5jUBnlKIw8:bw4wvli) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomExe/TeamCollection/TeamRepo.cs#L665)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

We currently have an awkward name distinction  between "TeamCollection" and "TeamRepo". The existence of this property implies that you can have a TeamRepo, without having a TeamCollection.  Does that suggest a name for TeamRepo like `TeamCollectionManager`?
</blockquote></details>

I don't like it. 99% of its code is about being a Repo. 1% deals with the fact that, because we want AutoFac to create it, it has to exist even when there's no TeamCollection, and therefore it needs a way to tell clients whether there actually is.
I suppose we could have yet another class TeamCollectionManager that AutoFac creates and which has a TeamRepo only if we actually have a team collection. That would also better support the possibility of different kinds of Repos. But I'm thinking YAGNI.
___
*[src/BloomTests/TeamCollection/FolderTeamRepoTests2.cs, line 16 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoMpgM3XRn8jL9W53e:-MSoagaM3HwujclM4QxJ:b-rgtr05) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomTests/TeamCollection/FolderTeamRepoTests2.cs#L16)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This is a good example of where I get confused by the "repo" name, so long as it is distinct from TeamCollection. I can't tell if what one has to set up is the TC, or rather this class that itself can create TCs.
</blockquote></details>

I've tried to clarify the comment. But I don't think of the class as BEING the TeamCollection; that would be the folder itself. This class is the code for doing things with the TeamCollection.
___
*[src/BloomTests/TeamCollection/FolderTeamRepoTests2.cs, line 27 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoPIpC6pvEp5v46Rhy:-MSocghY9RstWyRaxHh0:brt9ri2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomTests/TeamCollection/FolderTeamRepoTests2.cs#L27)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is there by any chance a more centralized way of making a valid book from tests? It's painful to think of what it would mean to have to go fix a thousand tests that individually "know" what is needed to be a Bloom book.

Even in this context of TC alone, since we're going to have lots of tests, presumably a lot of this can be usefully factored out even now with only one caller, to lead those who follow down a happily factored path.
</blockquote></details>

Already had something like it in TeamRepo, refactored to use it.
___
*[src/BloomTests/TeamCollection/FolderTeamRepoTests2.cs, line 52 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoQ2lUC7Vf1-fxqVSS:-MSsEZEG4K8V3iD2LtJA:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomTests/TeamCollection/FolderTeamRepoTests2.cs#L52)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

To my eyes camel casing looks weird on xml. In *.BloomCollection, we use PascalCasing.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175)* status: all files reviewed, 10 unresolved discussions (waiting on @hatton)

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 2 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175)* status: all files reviewed, 5 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamRepo.cs, line 96 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoNc0UBPPoazX2DFfb:-MT0tgyZ13F5Vf6AMQfB:b5h9fue) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomExe/TeamCollection/TeamRepo.cs#L96)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Changed to NonFatalProblem.Report for now. But probably we'll eventually use a progress/error reporter dialog here, too.
</blockquote></details>

We'll need to remember to still send those sentry exceptions, and probably here, were you had them.
___
*[src/BloomExe/TeamCollection/TeamRepo.cs, line 665 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoLcasAKfVddRVVY_Q:-MT0u1jJ7muDyEn0ut4y:b2o8vcg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomExe/TeamCollection/TeamRepo.cs#L665)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't like it. 99% of its code is about being a Repo. 1% deals with the fact that, because we want AutoFac to create it, it has to exist even when there's no TeamCollection, and therefore it needs a way to tell clients whether there actually is.
I suppose we could have yet another class TeamCollectionManager that AutoFac creates and which has a TeamRepo only if we actually have a team collection. That would also better support the possibility of different kinds of Repos. But I'm thinking YAGNI.
</blockquote></details>

Let's consider the pros/cons creating, in autofac, a tiny class,`TeamCollectionRepoHolder`, that just has one of these, or doesn't. Then the repo never has to check it is is real or not. Instead, client code would have to say

`repoHolder->current?doSomething()`

Pro: very clear, vs. `repo->doSomething()` that maybe it does, maybe it doesn't.
Pro: keeps the repo class cleaner
Con: makes client code more wordy.

**Review by hatton — APPROVED** [review]
> Reviewed 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomTests/TeamCollection/FolderTeamRepoTests2.cs, line 16 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoMpgM3XRn8jL9W53e:-MT0vLOO9z_W5FwZ-Z_a:b38txcb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomTests/TeamCollection/FolderTeamRepoTests2.cs#L16)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I've tried to clarify the comment. But I don't think of the class as BEING the TeamCollection; that would be the folder itself. This class is the code for doing things with the TeamCollection.
</blockquote></details>

Hmm, that's what most OOP is, right? We have a `Book` class that isn't the folder on disk. 

But I'm not saying I am totally sure what the best plan is. I just want to simplify.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamRepo.cs, line 665 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoLcasAKfVddRVVY_Q:-MT17bha2zjgcKLhufn0:b-7vmxbw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomExe/TeamCollection/TeamRepo.cs#L665)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Let's consider the pros/cons creating, in autofac, a tiny class,`TeamCollectionRepoHolder`, that just has one of these, or doesn't. Then the repo never has to check it is is real or not. Instead, client code would have to say

`repoHolder->current?doSomething()`

Pro: very clear, vs. `repo->doSomething()` that maybe it does, maybe it doesn't.
Pro: keeps the repo class cleaner
Con: makes client code more wordy.

</blockquote></details>

If we're going to have another class, I think I like TeamCollectionManager better. In addition to CurrentRepo, which may be null or not, it can have the code that takes a collection path and creates a repo if the collection has a TeamCollection. Anything that knows it will be re-created if the CurrentRepo changes can cache it, and it's actually LESS wordy when in doubt to do manager?.DoSomething than if (repo.HasCurrentCollection) repo.DoSomething() .

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomTests/TeamCollection/FolderTeamRepoTests2.cs, line 16 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoMpgM3XRn8jL9W53e:-MT1FQjT-7trXmS6NSA0:b1upskm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomTests/TeamCollection/FolderTeamRepoTests2.cs#L16)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Hmm, that's what most OOP is, right? We have a `Book` class that isn't the folder on disk. 

But I'm not saying I am totally sure what the best plan is. I just want to simplify.
</blockquote></details>

You have a case, for sure. I'm having a hard time pinning down why I like TeamRepo better. Maybe I just like Repo because it's shorter. Maybe I'm lazy about changing it. Perhaps it has something to do with this object not JUST managing the collection folder, but also knowing about the local collection and moving things between them. But then, unlike a VCS repo, it's not maintaining any history (at least, not of file content). So you may well be right.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175)* status: 2 of 16 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomExe/TeamCollection/TeamRepo.cs, line 96 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoNc0UBPPoazX2DFfb:-MT20QhBCeF04fsp-oEk:b-hfyrzt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomExe/TeamCollection/TeamRepo.cs#L96)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

We'll need to remember to still send those sentry exceptions, and probably here, were you had them.
</blockquote></details>

Put a note in the logging issue.
___
*[src/BloomExe/TeamCollection/TeamRepo.cs, line 665 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoLcasAKfVddRVVY_Q:-MT20Tuu8Iav7HUGKA_6:b13nsvd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomExe/TeamCollection/TeamRepo.cs#L665)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

If we're going to have another class, I think I like TeamCollectionManager better. In addition to CurrentRepo, which may be null or not, it can have the code that takes a collection path and creates a repo if the collection has a TeamCollection. Anything that knows it will be re-created if the CurrentRepo changes can cache it, and it's actually LESS wordy when in doubt to do manager?.DoSomething than if (repo.HasCurrentCollection) repo.DoSomething() .
</blockquote></details>

OK, Added TCManager and renamed TeamRepo

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175)* status: 2 of 16 files reviewed, 3 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamRepo.cs, line 665 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4175#-MSoLcasAKfVddRVVY_Q:-MT2P3vc7_fx6WcgjMiA:b-yk6g7p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e25a5b1aa6780f016a3d270df622f453f3b70c/src/BloomExe/TeamCollection/TeamRepo.cs#L665)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

OK, Added TCManager and renamed TeamRepo
</blockquote></details>

Sorry! We don't have anything that is a Team (we might someday). We have only TeamCollection.  A Team like E4L will have several TeamCollections.

I'm going to merge, but go ahead and change it down the line, thanks.

**Pull request merged**
