### PR TITLE
Fix special chars in language location string (BL-9732)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4328)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4328)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomExe/Book/Book.cs, line 379 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4328#-MXY5R9_ASPpk7a9d8dw:-MXY5R9_ASPpk7a9d8dx:bfyhsx8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/74aae5a14f7f2bc701f7f9365b0a1af785debf80/src/BloomExe/Book/Book.cs#L379)):*
> ```
> .Xml
> ```
FYI, since BookData/DataSet/MultiTextBase were previously storing XML stuff in the innards, using .Xml is the directly equivalent version for any consumers of _bookData.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4328)* status: all files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/Book/BookData.cs, line 660 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4328#-MXdEro6BxeudW1g5RuM:-MXdEro708gNT-Ou9iIZ:b910mn6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/79df3c41cc5c108953467a70a034df4f4db85baf/src/BloomExe/Book/BookData.cs#L660)):*
> ```
> // TODO: Update this. Maybe.
> ```
If the comment will remain, it needs to be expanded.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4328)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/Book/BookData.cs, line 660 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4328#-MXdEro6BxeudW1g5RuM:-MXdJlCn-k7qnjOxixoQ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/79df3c41cc5c108953467a70a034df4f4db85baf/src/BloomExe/Book/BookData.cs#L660)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> // TODO: Update this. Maybe.
> ```
If the comment will remain, it needs to be expanded.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4328)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

**Review by andrew-polk — APPROVED** [review]
> Dismissed @sujeffreyl from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4328)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Pull request merged**
