### PR TITLE
Insert and play videos

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2321)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Mostly :lgtm:. A few niggles.

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/BloomBrowserUI/bookLayout/basePage.less, line 447 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2321#-L9FlioY8M6_qicCXJ24:-L9FlioY8M6_qicCXJ25:b-ftkrxq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/455225168e25e45da6a8440967ad782e93ac35aa/src/BloomBrowserUI/bookLayout/basePage.less#L447)):*
> width:100%;

Just curious why this is okay for video but not images.

---

*[src/BloomBrowserUI/bookLayout/basePage.less, line 456 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2321#-L9Fl_nF5EXWcIS29bBY:-L9Fl_nF5EXWcIS29bBZ:biayyfy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/455225168e25e45da6a8440967ad782e93ac35aa/src/BloomBrowserUI/bookLayout/basePage.less#L456)):*
> ```Less
>         // above so buttons show
>         z-index: @imageContainerZIndex;
>         // Solves BL-1033 small picture frames cycling red overflow
> ```

I see this comment was copied from .bloom-imageContainer but then you commented the overflow line.
Let's remove the comment and line if not needed.

---

*[src/BloomExe/Book/HtmlDom.cs, line 1504 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2321#-L9FmwYIE8GHZ4Uz0u77:-L9FmwYIE8GHZ4Uz0u78:b-s9de86) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/455225168e25e45da6a8440967ad782e93ac35aa/src/BloomExe/Book/HtmlDom.cs#L1504)):*
> ```Smalltalk
> 			srcElement.SetAttribute("src", url.UrlEncoded);
> 			// Hides the placeholder.
> 			videoContainer.SetAttribute("class", videoContainer.GetAttribute("class").Replace(" bloom-noVideoSelected", ""));
> ```

Is bloom-noVideoSelected guaranteed to not be the first class name? Feels a little fragile.

---

*[src/BloomExe/Edit/PageEditingModel.cs, line 34 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2321#-L9Fo_lr-Js5OFGO6_aK:-L9Fo_lr-Js5OFGO6_aL:bc8yqk8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/455225168e25e45da6a8440967ad782e93ac35aa/src/BloomExe/Edit/PageEditingModel.cs#L34)):*
> ```Smalltalk
> 			IProgress progress)
> 		{
> 			//var isSameFile = IsSameFilePath(bookFolderPath, HtmlDom.GetVideoElementUrl(videoContainer), imageInfo);
> ```

Let's remove this commented line if you're making changes.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2321#-:-L9FpvSc5p4uS3b14OFH:b-fu8fy9)*

**Comment by JohnThomson** [comment]
Review status: 15 of 18 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomBrowserUI/bookLayout/basePage.less, line 447 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2321#-L9FlioY8M6_qicCXJ24:-L9FwRa6EmJ9xZdTsDlX:b-kvm6i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/455225168e25e45da6a8440967ad782e93ac35aa/src/BloomBrowserUI/bookLayout/basePage.less#L447)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> width:100%;

Just curious why this is okay for video but not images.
</blockquote></details>

I don't know. I haven't tried it for images. Hypotheses: (1) this works in the current Gecko but not in some earlier one we were using when we worked on images; (2) apparently in some contexts images can have captions and be left-aligned; maybe this approach couldn't handle that.

---

*[src/BloomBrowserUI/bookLayout/basePage.less, line 456 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2321#-L9Fl_nF5EXWcIS29bBY:-L9FwtDx5VK_qoASAtz0:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/455225168e25e45da6a8440967ad782e93ac35aa/src/BloomBrowserUI/bookLayout/basePage.less#L456)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I see this comment was copied from .bloom-imageContainer but then you commented the overflow line.
Let's remove the comment and line if not needed.
</blockquote></details>

Done.

---

*[src/BloomExe/Book/HtmlDom.cs, line 1504 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2321#-L9FmwYIE8GHZ4Uz0u77:-L9GF1_uCygbGiWceSkd:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/455225168e25e45da6a8440967ad782e93ac35aa/src/BloomExe/Book/HtmlDom.cs#L1504)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is bloom-noVideoSelected guaranteed to not be the first class name? Feels a little fragile.
</blockquote></details>

Done.

---

*[src/BloomExe/Edit/PageEditingModel.cs, line 34 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2321#-L9Fo_lr-Js5OFGO6_aK:-L9GGrjv4qf6CFV5TiSp:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/455225168e25e45da6a8440967ad782e93ac35aa/src/BloomExe/Edit/PageEditingModel.cs#L34)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's remove this commented line if you're making changes.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2321)*

**Comment by andrew-polk** [comment]
*[src/BloomBrowserUI/bookLayout/basePage.less, line 456 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2321#-L9Fl_nF5EXWcIS29bBY:-L9GHjjE00M-p4DoHLbD:b-6xpvkr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/455225168e25e45da6a8440967ad782e93ac35aa/src/BloomBrowserUI/bookLayout/basePage.less#L456)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like this change didn't get in somehow.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2321)*

**Comment by JohnThomson** [comment]
Review status: 14 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookLayout/basePage.less, line 456 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2321#-L9Fl_nF5EXWcIS29bBY:-L9GINTn-pSRk11NikfG:b-e1psld) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/455225168e25e45da6a8440967ad782e93ac35aa/src/BloomBrowserUI/bookLayout/basePage.less#L456)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like this change didn't get in somehow.
</blockquote></details>

Done. Sorry. Hadn't saved file.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2321)*

**Comment by andrew-polk** [comment]
Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2321)*

**Pull request merged**
