### PR TITLE
BL-5389 Create Branding for CLB

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2043)

### CODE REVIEW

**Comment by hatton** [comment]
Probably we should make white there transparent so it looks ok against non-white?

**Comment by JohnThomson** [comment]
I can if you want, but my read is that the background is already transparent. You don't get a white rectangle around the pictures of books. The only white I see is what is supposed to be the ends of the book pages...and I think of that as a part of the picture that really should be white. It's not like it's a picture of hollow book covers that you'd expect to see through to what's behind them.
Then again, if you actually print this on colored paper, anything white is going to be the background color, for better or worse...so changing it will give a more realistic impression of what you're going to get...at least on paper.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2043#-:-L0tW8gCxSVcxtLURbw6:bd7tse4)*

**Comment by JohnThomson** [comment]
OK, I had a go. There's probably a few flecks of lighter colors, but the main block of near-white is now near-transparent

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2043#-:-L0tkW8tWnytwWwqYHn6:b7aperi)*

**Comment by hatton** [comment]
Now the paper parts of the book are transparent.

**Pull request closed without merging**
