### PR TITLE
Fix freeze of page selection view when changing page layout (BL-9712)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4307)

### CODE REVIEW

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4307)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Edit/EditingView.cs, line 521 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4307#-MW_Ugbj4sh4SdmGf_2X:-MW_rMVxEDwjGCNrsMmD:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b45b87781da25121f7ff67d52b92abd8570dc648/src/BloomExe/Edit/EditingView.cs#L521)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

How would you feel about moving this comment up as part of a longer comment on the method parameter describing what it does, why (with more detail), and cautions against overusing it?
</blockquote></details>

Done.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
1. I suppose you are sure that some later full reload on page switch won't cause the problem to recur?
2. I don't much like this because it seems we haven't really understood the problem and therefore may be applying a bandaid to a broken bone. WHY, when we've made only minor changes to the current page, is it fine to reload the whole browser, but if we've done something quite major like changing the layout of multiple pages, doing so somehow causes a problem? Reloading the root should be MORE like what happens when Bloom restarts than just loading the current page, not less like it. If there is one situation where it's actually unsafe to reload everything, there may be others.
Unfortunately I don't at the moment have even a hypothesis as to why the problem only occurs if the change layout is followed by a full reload.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4307#-:-MWa5DCT6ISunZGD7htn:b12shvv)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @StephenMcConnel)

___
*[src/BloomExe/Edit/EditingView.cs, line 531 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4307#-MWa4dce65gOcvl0pLUM:-MWa4dce65gOcvl0pLUN:bkcfa17) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/99e32aaf77fe01ee0480a2fd0e1324d38949d49e/src/BloomExe/Edit/EditingView.cs#L531)):*
> ```Smalltalk
> 				// navigation; otherwise, we might miss the event and never enable saving for this page.
> 				_model.NavigatingSoSuspendSaving = true;
> 				if (fastRedisplay || _model.AreToolboxAndOuterFrameCurrent() && !ShouldDoFullReload())
> ```

It's possible that it is guaranteed that fastDisplay is never passed when  _model.AreToolboxAndOuterFrameCurrent() is false. But I think the rule should be written so that the latter dominates. We absolutely can't afford to try to update things by just fixing the page iframe if something is wrong with the content of the other parts of the page and they need updating.

**Review by StephenMcConnel — COMMENTED** [review]
It's changing to a new page where we do a full reload.  Or at least when a user clicks on a page thumbnail even if it's the same page.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4307#-:-MWa8xEAEzue6AZPoBGO:b5kcbq0)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

*[a discussion](https://reviewable.io/reviews/bloombooks/bloomdesktop/4307#-MWeKcwd7A0_VrVrynBv:-MWeKcwd7A0_VrVrynBw:bkbogjh) (no related file):*
With John's help, the fix has been totally changed to elsewhere in the code.  I put an explanation there of what we think is happening and why the bug occurs and the fix works.

---
___
*[src/BloomExe/Edit/EditingView.cs, line 531 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4307#-MWa4dce65gOcvl0pLUM:-MWa8mqK8FUxgWQDyu7q:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/99e32aaf77fe01ee0480a2fd0e1324d38949d49e/src/BloomExe/Edit/EditingView.cs#L531)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's possible that it is guaranteed that fastDisplay is never passed when  _model.AreToolboxAndOuterFrameCurrent() is false. But I think the rule should be written so that the latter dominates. We absolutely can't afford to try to update things by just fixing the page iframe if something is wrong with the content of the other parts of the page and they need updating.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4307)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

**Review by JohnThomson — APPROVED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4307)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4307)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @JohnThomson)

*[a discussion](https://reviewable.io/reviews/bloombooks/bloomdesktop/4307#-MWeKcwd7A0_VrVrynBv:-MWjD8xcCnk77QRRHhsf:brnta4k) (no related file):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

With John's help, the fix has been totally changed to elsewhere in the code.  I put an explanation there of what we think is happening and why the bug occurs and the fix works.
</blockquote></details>

After discussion, the simplest fix yet is now proposed.

---

**Pull request merged**
