### PR TITLE
Add additional leveled reader limits (BL-8878)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3908)

### CODE REVIEW

**Comment by JohnThomson** [comment]
This should undergo UI review as well as code review. Assuming it passes both, there is more work to do on updating the xlf file.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3908)* status: 0 of 14 files reviewed, 1 unresolved discussion

___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerTools.ts, line 95 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3908#-MFlimOy6S-iogEYPiEU:-MFlimOy6S-iogEYPiEV:bhkmwj2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15f493a913a2300f0da9a7bcfda7639c4b0485ef/src/BloomBrowserUI/bookEdit/toolbox/readers/readerTools.ts#L95)):*
> ```XML
>             if (setupDialogWindow) {
>                 setupDialogWindow.postMessage(
>                     "ConfigureActiveTab\n" +
> ```

The changes here have no obvious connection to the PR objective. I changed the name 'window' because of the confusion with the global variable of that name, and the message we send to the dialog because reusing SetupType was leading to an infinite loop of messages, though I don't entirely understand why as it was supposed to be going to another window.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3908)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, line 1270 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3908#-MFqHfHV1YrUuk1QvE39:-MFqHfHV1YrUuk1QvE3A:b-xas4vs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15f493a913a2300f0da9a7bcfda7639c4b0485ef/src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts#L1270)):*
> ```XML
>         }
>         return Math.round(wordCount / sentenceFragmentsByPage.length);
>         //return Math.round(10 * wordCount / sentenceCount) / 10; // for one decimal place
> ```

All these single-decimal comments are incorrect (still having the values from where they were pasted from). Let's just remove them for the new functions, at least.
___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, line 1352 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3908#-MFqI6TH6Hy4GjZZNIw0:-MFqI6TH6Hy4GjZZNIw1:b-obxxyf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15f493a913a2300f0da9a7bcfda7639c4b0485ef/src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts#L1352)):*
> ```XML
>         // character as the replacement there should be no danger that the
>         // replacement will match part of another grapheme.
>         console.log("known graphemes: " + JSON.stringify(knownGraphemes));
> ```

Do we want these two console.logs here, uncommented?
___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModelSpec.ts, line 18 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3908#-MFqITjd6sSh6WEp_lX1:-MFqITjd6sSh6WEp_lX2:b-rt7yq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15f493a913a2300f0da9a7bcfda7639c4b0485ef/src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModelSpec.ts#L18)):*
> ```XML
>         expect(ReaderToolsModel.getWordLength("thro\u0301ugh")).toBe(2);
>     });
> });
> ```

Shouldn't we be adding quite a few more tests with all these new features?
___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.io.ts, line 87 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3908#-MFqE4UL7O3NNc0_iyFS:-MFqE4UL7O3NNc0_iyFT:bu2cdhq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15f493a913a2300f0da9a7bcfda7639c4b0485ef/src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.io.ts#L87)):*
> ```XML
>             (level.maxAverageGlyphsPerWord = v)
>     }
> ];
> ```

Thanks for doing all this cleanup!
___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts, line 784 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3908#-MFqJ9zl7mrlGeY0_kHb:-MFqJ9zmDL9PcZI1Of8b:b-f73kb2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7d258fb5b6660db3ca91dca12d7d99cb572ba50/src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts#L784)):*
> ```
> (<HTMLElement>document.getElementById("things-to-remember")).innerHTML =
>         '<li contenteditable="true"></li>';
> ```
Did we lose this?
Or it is no longer needed for some reason?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3908)* status: 11 of 14 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, line 1270 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3908#-MFqHfHV1YrUuk1QvE39:-MFqiw9z86peH_5bII3u:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15f493a913a2300f0da9a7bcfda7639c4b0485ef/src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts#L1270)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

All these single-decimal comments are incorrect (still having the values from where they were pasted from). Let's just remove them for the new functions, at least.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, line 1352 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3908#-MFqI6TH6Hy4GjZZNIw0:-MFqj4V0E0VKKOFVZLZP:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15f493a913a2300f0da9a7bcfda7639c4b0485ef/src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts#L1352)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Do we want these two console.logs here, uncommented?
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModelSpec.ts, line 18 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3908#-MFqITjd6sSh6WEp_lX1:-MFqtIG258FlDxjZ9LIk:b-6yiut2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/15f493a913a2300f0da9a7bcfda7639c4b0485ef/src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModelSpec.ts#L18)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Shouldn't we be adding quite a few more tests with all these new features?
</blockquote></details>

I think I've covered what seems worth testing now.
___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts, line 784 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3908#-MFqJ9zl7mrlGeY0_kHb:-MFqi_fi4e9E3C-J5VhR:bquln2m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7d258fb5b6660db3ca91dca12d7d99cb572ba50/src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts#L784)):*
> ```
> (<HTMLElement>document.getElementById("things-to-remember")).innerHTML =
>         '<li contenteditable="true"></li>';
> ```
Good catch. I'm not entirely sure why we need to do this when removing a level, but I didn't intentionally remove it.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3908)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, line 1289 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3908#-MFquyM96Up535RBMvND:-MFquyM96Up535RBMvNE:b-1whz67) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/674ea59601340f913b570aa0c128cd00525f0b06/src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts#L1289)):*
> ```XML
>             return 0;
>         }
>         console.log(`words: ${wordCount}, letters: ${glyphCount}`);
> ```

Oops. A new console log.
Then go ahead and merge.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3908)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, line 1289 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3908#-MFquyM96Up535RBMvND:-MFqydxU2gQEJIG9UjCR:b45knuv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/674ea59601340f913b570aa0c128cd00525f0b06/src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts#L1289)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Oops. A new console log.
Then go ahead and merge.
</blockquote></details>

...and we all missed that all the new tests were "fdescribe" and "fit" thus disabling all the other tests!
Done.

**Pull request merged**
