### PR TITLE
Allow user to control fixed or flowable epub mode (BL-11416)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335)* status: all files reviewed, 8 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx` line 23 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9HwkYeEDpxbkJ-y-SV:-N9HwkYeEDpxbkJ-y-SW:b-95ub39) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f038722459a0c8b7703f38aeff77bb8b93275fe5/src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx#L23)):*
> ```XML
>         l10nKey: "Publish.Epub.Fixed",
>         description:
>             "Ask ePUB reader to show pages exctly like you see them in Bloom",
> ```

exactly

(by the way, one of the things I really like about figma is you can copy/paste the text from the design)



_Code quote:_
```XML
exctly
```
___
*[`src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx` line 32 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9I-vBL9x7tRx2PRv6Z:-N9I-vBL9x7tRx2PRv6_:bkn9gdn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f038722459a0c8b7703f38aeff77bb8b93275fe5/src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx#L32)):*
> ```XML
>         description:
>             "Allow ePUB reader to lay out images and text however they want. The user is more likely to be able to increase font size. Custom page layouts will not look good. This mode is not available if your book has overlay pages (comics).",
>         descriptionL10nKey: "Publish.Epub.Flowable.Description"
> ```

I'm a bit torn about whether these should be added to the xlf now.
Starting in 5.3, we have generally been adding new strings to the xlf when we code the feature but commenting them with a comment indicating the version they are to be added in.

The advantage is we do it when we are thinking about it.
The disadvantage is we may be doing extra work if strings change. And we likely have to, when uncommenting the xlf, verify everything is still in sync anyway....
All that to say, our current process seems to be to add them now, commented. But I'm open to pushback.
___
*[`src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx` line 48 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9HxM922Z0WkEzKRkUN:-N9HxM922Z0WkEzKRkUO:bomck4i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f038722459a0c8b7703f38aeff77bb8b93275fe5/src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx#L48)):*
> ```XML
>         "fixed"
>     );
>     const [modeDropdownIsOpen, setModeDropdownIsOpen] = useState(false);
> ```

`isModeDropdownOpen`?



_Code quote:_
```XML
modeDropdownIsOpen
```
___
*[`src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx` line 92 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9Hyd79DRNI60a4V3mD:-N9Hyd7C-nl4XV7SCj2Y:b-dbwyus) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f038722459a0c8b7703f38aeff77bb8b93275fe5/src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx#L92)):*
> ```XML
>                 >
>                     ePUB mode
>                 </Div>
> ```

If I'm interpreting this and existing code/UI correctly, this will make it appear as though ePUB mode is under the accessibility heading (and indeed the code has that hierarchy), but I interpret the design that it is a sibling.
___
*[`src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx` line 115 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9HzeVN44-F6ZMvkUbR:-N9HzeVN44-F6ZMvkUbS:b-8s81av) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f038722459a0c8b7703f38aeff77bb8b93275fe5/src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx#L115)):*
> ```XML
>                         open={modeDropdownIsOpen}
>                         onOpen={() => {
>                             //setFormatPopupAnchor(null);
> ```

Any reason to keep this comment?



_Code quote:_
```XML
//setFormatPopupAnchor(null);
```
___
*[`src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx` line 143 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9Hz9pR2cJyx2ElDfPj:-N9Hz9pR2cJyx2ElDfPk:b-a7tvk4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f038722459a0c8b7703f38aeff77bb8b93275fe5/src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx#L143)):*
> ```XML
>                                     value={item.mode}
>                                     key={item.mode}
>                                     disabled={false} // todo: disable flowable if comics
> ```

I think you rather opted to disable the control and default to fixed?
So just remove this comment?

But unless I'm missing it, I think we do have a problem scenario where the user has no overlays, sets the mode to flowable, then adds overlays. Won't the mode selector be disabled with flowable selected? Or are we not persisting the setting? If not, should we be?
I think these questions may also apply to the "Use ePUB reader's text size" checkbox.



_Code quote:_
```XML
// todo: disable flowable if comics
```
___
*[`src/BloomExe/CLI/CreateArtifactsCommand.cs` line 284 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9HvgLX6QcaxIKnoyxK:-N9HvgLX6QcaxIKnoyxL:br7a3sz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f038722459a0c8b7703f38aeff77bb8b93275fe5/src/BloomExe/CLI/CreateArtifactsCommand.cs#L284)):*
> ```Smalltalk
> 
> 			maker.Book = _book;
> 			maker.Unpaginated = PublishEpubApi.EpubMode == "flowable";
> ```

I suppose this is really somewhat of a todo based on what we decide on https://issues.bloomlibrary.org/youtrack/issue/BL-11424/Make-Harvester-always-make-epubs-now, but currently this will always be false, right?

Maybe worth a brief comment for now since it looks like you're making other changes anyway.
___
*[`src/BloomExe/Publish/Epub/EpubMaker.cs` line 464 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9HvPyF-42bLS0dq1z1:-N9HvPyH50CFuBZ9chGn:bnfx1zq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f038722459a0c8b7703f38aeff77bb8b93275fe5/src/BloomExe/Publish/Epub/EpubMaker.cs#L464)):*
> ```Smalltalk
> 				book.RawDom.SafeSelectNodes(".//svg:svg[contains(@class, 'comical-generated')]", nsManager);
> 			return comicalMatches.Count > 0;
> 		}
> ```

HtmlDom already has a `HasOverlayPages()`

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335)* status: 0 of 14 files reviewed, 8 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx` line 23 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9HwkYeEDpxbkJ-y-SV:-N9IXBWJ9Nflk7S2U9xO:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f038722459a0c8b7703f38aeff77bb8b93275fe5/src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx#L23)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

exactly

(by the way, one of the things I really like about figma is you can copy/paste the text from the design)
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx` line 32 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9I-vBL9x7tRx2PRv6Z:-N9IZ3oWB9ZVRFYEkHJM:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f038722459a0c8b7703f38aeff77bb8b93275fe5/src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx#L32)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm a bit torn about whether these should be added to the xlf now.
Starting in 5.3, we have generally been adding new strings to the xlf when we code the feature but commenting them with a comment indicating the version they are to be added in.

The advantage is we do it when we are thinking about it.
The disadvantage is we may be doing extra work if strings change. And we likely have to, when uncommenting the xlf, verify everything is still in sync anyway....
All that to say, our current process seems to be to add them now, commented. But I'm open to pushback.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx` line 48 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9HxM922Z0WkEzKRkUN:-N9IWjwF5x6XTwwnefUy:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f038722459a0c8b7703f38aeff77bb8b93275fe5/src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx#L48)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

`isModeDropdownOpen`?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx` line 92 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9Hyd79DRNI60a4V3mD:-N9Icbn76SYeGipocIMx:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f038722459a0c8b7703f38aeff77bb8b93275fe5/src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx#L92)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If I'm interpreting this and existing code/UI correctly, this will make it appear as though ePUB mode is under the accessibility heading (and indeed the code has that hierarchy), but I interpret the design that it is a sibling.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx` line 115 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9HzeVN44-F6ZMvkUbR:-N9IcxnE-DGVHct5sJGi:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f038722459a0c8b7703f38aeff77bb8b93275fe5/src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx#L115)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Any reason to keep this comment?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx` line 143 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9Hz9pR2cJyx2ElDfPj:-N9IgESR-xcsqdrPGww1:b-ihzkq1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f038722459a0c8b7703f38aeff77bb8b93275fe5/src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx#L143)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think you rather opted to disable the control and default to fixed?
So just remove this comment?

But unless I'm missing it, I think we do have a problem scenario where the user has no overlays, sets the mode to flowable, then adds overlays. Won't the mode selector be disabled with flowable selected? Or are we not persisting the setting? If not, should we be?
I think these questions may also apply to the "Use ePUB reader's text size" checkbox.
</blockquote></details>

Removed comment, and added code to StageEpub to rule out invalid combinations. I'm inclined not to mess with the state of disabled controls...if they get enabled again, the user might prefer to have the previous value restored, and it's one more complication.
I added another commit for persisting ePUB mode (and a lot of associated cleanup)
___
*[`src/BloomExe/CLI/CreateArtifactsCommand.cs` line 284 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9HvgLX6QcaxIKnoyxK:-N9IhBpu1-M_zta-NsGh:b-yd4kuz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f038722459a0c8b7703f38aeff77bb8b93275fe5/src/BloomExe/CLI/CreateArtifactsCommand.cs#L284)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I suppose this is really somewhat of a todo based on what we decide on https://issues.bloomlibrary.org/youtrack/issue/BL-11424/Make-Harvester-always-make-epubs-now, but currently this will always be false, right?

Maybe worth a brief comment for now since it looks like you're making other changes anyway.
</blockquote></details>

Now that it's persisted, I made it at least use the persisted setting if any.
___
*[`src/BloomExe/Publish/Epub/EpubMaker.cs` line 464 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9HvPyF-42bLS0dq1z1:-N9Ii07O5AB_17hfuiX4:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f038722459a0c8b7703f38aeff77bb8b93275fe5/src/BloomExe/Publish/Epub/EpubMaker.cs#L464)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

HtmlDom already has a `HasOverlayPages()`
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/PublishSettings.cs` line 322 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9XOpVp7ihXJTJgabhp:-N9XOpVq8uWPRXtfbxy9:bolo3lu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/96d2f5e228e397f9e8ec87cb27b75b2535442b55/src/BloomExe/Book/PublishSettings.cs#L322)):*
> ```Smalltalk
> 		public EpubSettings()
> 		{
> 			Mode = "fixed";
> ```

It seems like elsewhere you're using `flowable` as the default. Why `fixed` here?
___
*[`src/BloomTests/Publish/ExportFixedLayoutEpubTests.cs` line 20 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9XPNY193J1pJp3huno:-N9XPNY22eKcj26BTPvT:b-mbiyr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/96d2f5e228e397f9e8ec87cb27b75b2535442b55/src/BloomTests/Publish/ExportFixedLayoutEpubTests.cs#L20)):*
> ```Smalltalk
> 		{
> 			base.OneTimeSetup();
> 			base.Setup(); // since this class represents just one test, we can do it here.
> ```

This doesn't seem to be true.



_Code quote:_
```Smalltalk
// since this class represents just one test
```

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`DistFiles/localization/en/Bloom.xlf` line 3988 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9XPY9T5gDPxkXSiBFn:-N9XPY9T5gDPxkXSiBFo:b-2ez40s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/96d2f5e228e397f9e8ec87cb27b75b2535442b55/DistFiles/localization/en/Bloom.xlf#L3988)):*
> ```XML
>             </trans-unit>
>

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`DistFiles/localization/en/Bloom.xlf` line 3988 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9XPY9T5gDPxkXSiBFn:-N9XqWGw1HwcPYRpXFvc:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/96d2f5e228e397f9e8ec87cb27b75b2535442b55/DistFiles/localization/en/Bloom.xlf#L3988)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

From this morning's conversation, let's change "Fixed" to "Fixed – ePUB 3" (I used an en dash there, though semantically it should be an em dash... just looks too big)
</blockquote></details>

Done.
___
*[`src/BloomExe/Book/PublishSettings.cs` line 322 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9XOpVp7ihXJTJgabhp:-N9Xr6wk03Grtc5SBt8U:b-d0vo8e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/96d2f5e228e397f9e8ec87cb27b75b2535442b55/src/BloomExe/Book/PublishSettings.cs#L322)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

It seems like elsewhere you're using `flowable` as the default. Why `fixed` here?
</blockquote></details>

I'm having trouble finding other places except the command-line API used by harvester. My thinking is that 'fixed' is likely to be the most useful default in situations where the user has a chance to verify and override. Where we're possibly regenerating things automatically, it seemed safer to keep the legacy behavior. But I wouldn't swear I've followed that principle faithfully.
___
*[`src/BloomTests/Publish/ExportFixedLayoutEpubTests.cs` line 20 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9XPNY193J1pJp3huno:-N9XpLEY2BjAXt_itYMA:b-9nvqyq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/96d2f5e228e397f9e8ec87cb27b75b2535442b55/src/BloomTests/Publish/ExportFixedLayoutEpubTests.cs#L20)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This doesn't seem to be true.
</blockquote></details>

Maybe the comment isn't clear enough. The tests confirm different effects of making a single epub. The base class Setup was designed for where each test does an export followed by many assertions, but I've come to prefer this style where the class represents a single export and tests can be named for the various results we want to confirm.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx` line 37 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9YT2nLBg23mnn0DLbh:-N9YT2nLBg23mnn0DLbi:b5tgguh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/456c1041611df544b4fc1c412779fb6d42972cc4/src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx#L37)):*
> ```XML
>         l10nKey: "Publish.Epub.Flowable",
>         description:
>             "Allow ePUB reader to lay out images and text however they want. The user is more likely to be able to increase font size. Custom page layouts will not look good. This mode is not available if your book has overlay pages (comics).",
> ```

Marlon pointed out that this should probably be "readers" because of "they"

Otherwise, looks good
___
*[`src/BloomExe/Book/PublishSettings.cs` line 322 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335#-N9XOpVp7ihXJTJgabhp:-N9YSi7iEZZ--fEi0x9G:bv1oiod) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/96d2f5e228e397f9e8ec87cb27b75b2535442b55/src/BloomExe/Book/PublishSettings.cs#L322)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm having trouble finding other places except the command-line API used by harvester. My thinking is that 'fixed' is likely to be the most useful default in situations where the user has a chance to verify and override. Where we're possibly regenerating things automatically, it seemed safer to keep the legacy behavior. But I wouldn't swear I've followed that principle faithfully.
</blockquote></details>

Ok sorry; I was probably just thinking of command line. I thought there was another place, but I'm sure you're right.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Review by andrew-polk — APPROVED** [review]
> Dismissed @hatton from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5335)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
