### PR TITLE
BL-10884 Fix SS Importer to update side classes

### PR DESCRIPTION
**Pull request by gmartin7**
* also removed some usings

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4944)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4944)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @gmartin7 and @hatton)

___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 197 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4944#-Muqo9Qo8V6ouHUJ0kjW:-Muqo9Qo8V6ouHUJ0kjX:b-4rvdjr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/93c84c887c6ab1a38be7e056161e8f3666386cc2/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L197)):*
> ```Smalltalk
> 		private CollectionSettings GetCollectionSettings()
> 		{
> 			var settingsFilePath = CollectionSettings.FindSettingsFileInFolder(
> ```

It seems unusual for a place wanting access to the current collection settings to get them by looking around at files and then creating a new one. Is that how we normally do it?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4944)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 197 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4944#-Muqo9Qo8V6ouHUJ0kjW:-Muqzwke6ws2o7iFtgWZ:b-b9cujp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/93c84c887c6ab1a38be7e056161e8f3666386cc2/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L197)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

It seems unusual for a place wanting access to the current collection settings to get them by looking around at files and then creating a new one. Is that how we normally do it?
</blockquote></details>

It is pretty unusual (the above method until now was only used in collection renaming), but usually we have the book or at least a bookInfo that we're dealing with, which we don't seem to in this case. OTOH, one of the classes that creates the `SpreadsheetImporter` already has the collection settings. We could modifying the `ctor` to pass in what we need, but that causes a mess in tests and CLI commands that don't have the collection readily available.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4944)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @hatton)

___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 197 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4944#-Muqo9Qo8V6ouHUJ0kjW:-MurID_PAGXK_X3LRXG1:b9ttx2e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6571ad721ef5d4afff11e2870020445fff2637cc/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L197)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

It is pretty unusual (the above method until now was only used in collection renaming), but usually we have the book or at least a bookInfo that we're dealing with, which we don't seem to in this case. OTOH, one of the classes that creates the `SpreadsheetImporter` already has the collection settings. We could modifying the `ctor` to pass in what we need, but that causes a mess in tests and CLI commands that don't have the collection readily available.
</blockquote></details>

OK, those don't seem like justifications. Sorry if I'm missing it.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
The fix looks good, but we've worked hard to make SS rather comprehensively unit tested. Can you come up with a test that would fail without this? The SpreadsheetImageAndTextImportTests does a fair bit of inserting pages, so it's likely that the DOM it produces has wrong page numbering and side classes without this fix.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4944#-:-MurcrSo2wdcQQflcCCq:b-cstiaj)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4944)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @gmartin7, @hatton, and @JohnThomson)

___
*[src/BloomExe/Spreadsheet/SpreadsheetApi.cs, line 122 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4944#-Muwj4NwCrfSz3ulIQLp:-Muwj4NwCrfSz3ulIQLq:bz9u8gf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/70aa6ec7c9fce6732ec2dc757d1a76e29eb8069e/src/BloomExe/Spreadsheet/SpreadsheetApi.cs#L122)):*
> ```Smalltalk
> 
> 				var dom = book.OurHtmlDom;
> 				var importer = new SpreadsheetImporter(_webSocketServer, dom,
> ```

Would there be a problem with simply giving the constructor the book? Why break out the properties of it?
___
*[src/BloomExe/Spreadsheet/SpreadsheetApi.cs, line 124 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4944#-MuwjKjo6uRfsGiV_e0A:-MuwjKjo6uRfsGiV_e0B:bftb2d8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/70aa6ec7c9fce6732ec2dc757d1a76e29eb8069e/src/BloomExe/Spreadsheet/SpreadsheetApi.cs#L124)):*
> ```Smalltalk
> 				var importer = new SpreadsheetImporter(_webSocketServer, dom,
> 					Path.GetDirectoryName(inputFilepath), book.FolderPath, book.CollectionSettings);
> 				importer.ImportWithProgress(inputFilepath, bookPath);
> ```

If the importer already has the path (or the target book, as suggested above), does it need to be given the `bookPath` again? I would remove that, unless I'm misunderstanding something.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4944)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4944)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/Spreadsheet/SpreadsheetApi.cs, line 122 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4944#-Muwj4NwCrfSz3ulIQLp:-Mv513qd-Mw_eCPpHMLt:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/70aa6ec7c9fce6732ec2dc757d1a76e29eb8069e/src/BloomExe/Spreadsheet/SpreadsheetApi.cs#L122)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Would there be a problem with simply giving the constructor the book? Why break out the properties of it?
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetApi.cs, line 124 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4944#-MuwjKjo6uRfsGiV_e0A:-Mv515SG4GAaJn5xtuD-:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/70aa6ec7c9fce6732ec2dc757d1a76e29eb8069e/src/BloomExe/Spreadsheet/SpreadsheetApi.cs#L124)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

If the importer already has the path (or the target book, as suggested above), does it need to be given the `bookPath` again? I would remove that, unless I'm misunderstanding something. 
</blockquote></details>

Done.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4944)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton)

**Pull request merged**
