### PR TITLE
Provide settings flag for line breaking only at spaces (BL-5761)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2311)

### CODE REVIEW

**Comment by JohnThomson** [comment]
:lgtm: with one minor question

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 499 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2311#-L8cEJtTLrjDjgQNfHJw:-L8cEJtTLrjDjgQNfHJx:bn37a6y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/929b392ee7bc6d43668927e9f514dca69ce15114/src/BloomExe/Collection/CollectionSettingsDialog.cs#L499)):*
> ```Smalltalk
> 				{
> 					_collectionSettings.SetBreakLinesOnlyAtSpaces(langNum, newBreak);
> 					ChangeThatRequiresRestart();
> ```

Does this change actually require a restart? It seems pretty localized and innocuous. But then I would have thought the same for line height...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2311#-:-L8cEgvdWoAgLSpbVcOs:brt1yk6)*

**Comment by StephenMcConnel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 499 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2311#-L8cEJtTLrjDjgQNfHJw:-L8cGjEkEjYtfQ0d_U4e:b-1ay186) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/929b392ee7bc6d43668927e9f514dca69ce15114/src/BloomExe/Collection/CollectionSettingsDialog.cs#L499)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Does this change actually require a restart? It seems pretty localized and innocuous. But then I would have thought the same for line height...
</blockquote></details>

It requires that a new settingsCollectionStyles.css file be written out.  I don't know the timing of that, but suspect that may be why it was asking for a restart.  I'll admit I was just following the pattern of the other items in the vicinity.  :-)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2311)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 499 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2311#-L8cEJtTLrjDjgQNfHJw:-L8cNfWs775joy2h_ZcF:bo44ru0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/929b392ee7bc6d43668927e9f514dca69ce15114/src/BloomExe/Collection/CollectionSettingsDialog.cs#L499)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

It requires that a new settingsCollectionStyles.css file be written out.  I don't know the timing of that, but suspect that may be why it was asking for a restart.  I'll admit I was just following the pattern of the other items in the vicinity.  :-)
</blockquote></details>

If you test and confirm that something definitely goes wrong if you don't do it,  you could have a comment stating why it is necessary. But if my guess that it's NOT necessary is right, testing would be inconclusive...all you can know is that you haven't discovered any reason to need it.
Since this is not likely to change often, maybe it's best to just leave it. You could possibly add a comment noting that you're not sure whether it is needed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2311)*

**Comment by StephenMcConnel** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 499 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2311#-L8cEJtTLrjDjgQNfHJw:-L8cduui0qxoAsQlEbxa:b-z8cs5w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/929b392ee7bc6d43668927e9f514dca69ce15114/src/BloomExe/Collection/CollectionSettingsDialog.cs#L499)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

If you test and confirm that something definitely goes wrong if you don't do it,  you could have a comment stating why it is necessary. But if my guess that it's NOT necessary is right, testing would be inconclusive...all you can know is that you haven't discovered any reason to need it.
Since this is not likely to change often, maybe it's best to just leave it. You could possibly add a comment noting that you're not sure whether it is needed.
</blockquote></details>

After checking the code and testing it, I decided that the restart wasn't needed for either the line height or line breaking settings.  The RTL setting is iffier because it may affect something other than css so I left it alone.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2311)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2311#-:-L8clNNfELIELWoqX5hj:bnfp4nl)*

**Pull request merged**
