### PR TITLE
BL-1030: Move catching of JS errors from C# to JS

### PR DESCRIPTION
**Pull request by phillip-hopper**
We were attempting to get the JS call stack when an exception occurred, but it seems it was causing worse problems. With this implementation we can get the file name and line number where the exception occurred, but not the stack trace.

### CODE REVIEW

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-master-debug/317/
Test PASSed.

**Comment by JohnThomson** [comment]
I have mixed feelings about this. Obviously we want to prevent the crash, but with this fix we will NEVER get a JS stack. As noted in Jira, we should be able to fix this when we switch to Gecko 31 or later. I suppose you've looked for other options?

**Comment by JohnThomson** [comment]
For example, could we catch the C# exception (and not any we don't want to) and just do whatever we would have done with the more complete report?

**Comment by JohnThomson** [comment]
TomH says GeckoFx33 has been in use in PT beta for a month now. So I think it's reasonable for us to push ahead with this change in the expectation of improving it soon...or possibly to hold this up until we DO make the switch to 33, and take advantage of that to enhance this PR.

**Comment by JohnThomson** [comment]
I think I'd like to wait for @hatton to give input before merging, though.

**Comment by phillip-hopper** [comment]
I don't think it would be helpful to catch the C# error, because the message, "Attempted to read or write protected memory. This is often an indication that other memory is corrupt" is not really helpful and actually gives less useful information than the javascript error message.

If the problem is fixed in GeckoFx33, and we decide to use it, then nothing in this pull request is needed.

**Comment by JohnThomson** [comment]
On the contrary, I don't have any reason to think GeckoFX 33 will fix things so that the old way of getting stack dumps works without this kind of crash. Rather, 33 will allow us to enhance what Phil has done here in that the JS error-handler can obtain a JS stack trace and pass it on.
So I think we should go ahead with this change. My only hesitation, especially since I think JH doesn't want to make the Gecko33 switch for 3.1, is whether we postpone this change until after the GeckoFx switch. It's a tradeoff: compared to this PR, the current approach gives us more information when it works, a nastier crash when it doesn't. I'm not sure how frequent these problems are, either in development or for end users, so that makes it harder to call. For development, I tend to think that an occasional green screen for JS errors is a price worth paying to get a stack trace most of the time.

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-master-debug/337/
Test PASSed.

**Pull request merged**
