### PR TITLE
Replace installing Andika New Basic with uninstalled Andika (BL-11389)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
Andika is supplied as .woff2 files in case it is not installed, and will be served up by BloomServer when Bloom is running, by Bloom Reader (which is already happening), or embedded in ePUB files.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5771)

### CODE REVIEW

**Review by andrew-polk — APPROVED** [review]
This looks good.
Let's discuss in the meeting tomorrow with the devs if anyone can think of a way to keep from having to add the font-face rules and remove them in each book.
(Like if we could get away with a more global thing to define those which isn't in each book. One downside is that opening the book in the browser won't work correctly.)

> Reviewed 41 of 41 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5771#-:-NTLjnx24oFFLiVfSA6j:bhj2t7m)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5771)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/Publish/BloomPub/BloomPubMaker.cs` line 561 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5771#-NTOsboI0yWlE5JGqF95:-NTOsboI0yWlE5JGqF96:b-1617u7) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e3ba9627255574e0b034463175727b9aa38b8892/src/BloomExe/Publish/BloomPub/BloomPubMaker.cs#L561)):*
> ```Smalltalk
> 		{
> 			const string defaultFont = "Andika"; // "Andika" already in BR, don't need to embed or make rule.
> 			fontsWanted.Remove(defaultFont);
> ```

Should we also remove "Andika New Basic" from the list of fonts wanted?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Did you experiment with adding ABeeZee to prove the system works?

> Reviewed 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5771#-:-NTQnHgz4nOH-ggCG2Fa:bf6ky9q)* status: all files reviewed, 4 unresolved discussions (waiting on @StephenMcConnel)

___
*[`DistFiles/fonts/Andika/fontinfo.json` line 1 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5771#-NTQmIIACtFokBRwtIla:-NTQmIIACtFokBRwtIlb:b-2f8b60) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6474a7cd90ab459735d757f0ee5f9945d0fbf589/DistFiles/fonts/Andika/fontinfo.json#L1)):*
> ```JSON
> {
> ```

I would prefer `font-info.json`. What do you think?
___
*[`DistFiles/fonts/Andika/fontinfo.json` line 17 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5771#-NTQm_xv6OPd0sscCtqz:-NTQm_xv6OPd0sscCtr-:bs5tzdo) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6474a7cd90ab459735d757f0ee5f9945d0fbf589/DistFiles/fonts/Andika/fontinfo.json#L17)):*
> ```JSON
>         "@font-face { font-family: \"Andika New Basic\"; font-weight: bold; font-style: normal; src: local(\"Andika New Basic Bold\"), url(\"./host/fonts/Andika New Basic Bold\"); }",
>         "@font-face { font-family: \"Andika New Basic\"; font-weight: normal; font-style: italic; src: local(\"Andika New Basic Italic\"), url(\"./host/fonts/Andika New Basic Italic\"); }",
>         "@font-face { font-family: \"Andika New Basic\"; font-weight: bold; font-style: italic; src: local(\"Andika New Basic Bold Italic\"), url(\"./host/fonts/Andika New Basic Bold Italic\") ; }"
> ```

I'm not understanding these ANB rules. 
They seem to get a locally-installed version if we have it. Do we want to? Or do we want to just always serve our Andika? Maybe a ? for JH.
If it isn't installed, they seem to ask the server for ANB. But we aren't serving ANB. (And BR isn't either, right?)


Later: Ok, now I see the code in FontsApi which essentially allows ANB requests to be served as Andika.
Feels a little too generic for every substring to serve up every superstring request.
Can't we just tell the font faces here to serve Andika for the ANB font face?
___
*[`src/BloomExe/FontProcessing/FontsApi.cs` line 21 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5771#-NTQoOti16piTcrgBH4R:-NTQoOti16piTcrgBH4S:b-gbctmt) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6474a7cd90ab459735d757f0ee5f9945d0fbf589/src/BloomExe/FontProcessing/FontsApi.cs#L21)):*
> ```Smalltalk
> 
> 		public static bool IsServingAndika;
> 		public static bool AndikaNewBasicIsAndika;
> ```

I think these are not used now.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5771)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`DistFiles/fonts/Andika/fontinfo.json` line 1 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5771#-NTQmIIACtFokBRwtIla:-NTU133W9Snt1bHKuxkJ:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6474a7cd90ab459735d757f0ee5f9945d0fbf589/DistFiles/fonts/Andika/fontinfo.json#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I would prefer `font-info.json`. What do you think?
</blockquote></details>

Done.
___
*[`DistFiles/fonts/Andika/fontinfo.json` line 17 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5771#-NTQm_xv6OPd0sscCtqz:-NTU2IvN3nLj_Kiz3ka4:b-shcd9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6474a7cd90ab459735d757f0ee5f9945d0fbf589/DistFiles/fonts/Andika/fontinfo.json#L17)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not understanding these ANB rules. 
They seem to get a locally-installed version if we have it. Do we want to? Or do we want to just always serve our Andika? Maybe a ? for JH.
If it isn't installed, they seem to ask the server for ANB. But we aren't serving ANB. (And BR isn't either, right?)


Later: Ok, now I see the code in FontsApi which essentially allows ANB requests to be served as Andika.
Feels a little too generic for every substring to serve up every superstring request.
Can't we just tell the font faces here to serve Andika for the ANB font face?
</blockquote></details>

These are modeled after the @font-face declarations in bloom-player.
Here's the /host/fonts/ handling code from BloomReader which interprets the @font-face declarations in bloom-player.  Maybe I should just adapt that in FontsApi.cs
            if (!url.contains("/host/fonts/"))
                return null;

            String fontNameRequested = IOUtilities.getFilename(url);
            fontNameRequested = URLDecoder.decode(fontNameRequested, "UTF-8");
            String fontFileName = null;
            switch (fontNameRequested) {
                case "Andika New Basic":
                case "Andika":
                    fontFileName = "Andika-Regular.ttf";
                    break;
                case "Andika New Basic Bold":
                case "Andika Bold":
                    fontFileName = "Andika-Bold.ttf";
                    break;
                case "Andika New Basic Italic":
                case "Andika Italic":
                    fontFileName = "Andika-Italic.ttf";
                    break;
                case "Andika New Basic Bold Italic":
                case "Andika Bold Italic":
                    fontFileName = "Andika-BoldItalic.ttf";
                    break;
            }
___
*[`src/BloomExe/FontProcessing/FontsApi.cs` line 21 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5771#-NTQoOti16piTcrgBH4R:-NTU1K1g83IOq4fCOZZ9:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6474a7cd90ab459735d757f0ee5f9945d0fbf589/src/BloomExe/FontProcessing/FontsApi.cs#L21)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think these are not used now.
</blockquote></details>

Done.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5771)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`DistFiles/fonts/Andika/fontinfo.json` line 17 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5771#-NTQm_xv6OPd0sscCtqz:-NTUBUbi0mM0caoB7siU:b-sb5tja) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6474a7cd90ab459735d757f0ee5f9945d0fbf589/DistFiles/fonts/Andika/fontinfo.json#L17)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

These are modeled after the @font-face declarations in bloom-player.
Here's the /host/fonts/ handling code from BloomReader which interprets the @font-face declarations in bloom-player.  Maybe I should just adapt that in FontsApi.cs
            if (!url.contains("/host/fonts/"))
                return null;

            String fontNameRequested = IOUtilities.getFilename(url);
            fontNameRequested = URLDecoder.decode(fontNameRequested, "UTF-8");
            String fontFileName = null;
            switch (fontNameRequested) {
                case "Andika New Basic":
                case "Andika":
                    fontFileName = "Andika-Regular.ttf";
                    break;
                case "Andika New Basic Bold":
                case "Andika Bold":
                    fontFileName = "Andika-Bold.ttf";
                    break;
                case "Andika New Basic Italic":
                case "Andika Italic":
                    fontFileName = "Andika-Italic.ttf";
                    break;
                case "Andika New Basic Bold Italic":
                case "Andika Bold Italic":
                    fontFileName = "Andika-BoldItalic.ttf";
                    break;
            }

</blockquote></details>

Note that BloomDesktop has to be able to serve bloom-player requests for the BloomPub preview.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5771)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

___
*[`DistFiles/fonts/Andika/fontinfo.json` line 17 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5771#-NTQm_xv6OPd0sscCtqz:-NTUPLvB5NBmm4BR5CO1:b-nqz7on) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6474a7cd90ab459735d757f0ee5f9945d0fbf589/DistFiles/fonts/Andika/fontinfo.json#L17)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Note that BloomDesktop has to be able to serve bloom-player requests for the BloomPub preview.
</blockquote></details>

That's helpful. Thanks.

I think, personally, if we're going to treat ANB->Andika as a special case in FontsApi.cs, it feels simpler to just be explicit about the mapping like we are doing in BR.
But if you think we may reuse the current logic at some point in the future, I guess that makes sense. So go ahead and merge if you like.

I had started to lean toward just being explicit here to codify the ANB->Andika mapping (even though b-p isn't currently), but then I realized that if we ever change our minds about how BloomDesktop serves ANB, we would be kinda stuck. With these font-face rules, we can, for example, change our minds to have our server use the installed version if it exists.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5771)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
