### PR TITLE
Talking-book checkbox to control showing image descriptions (BL-12194)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5854)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5854)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts` line 1928 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5854#-NVehExeCyJJhoSelAj1:-NVehExeCyJJhoSelAj2:bgt006) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/96d3d326df8012b0a14b3a8a49a57811e0d13be0/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L1928)):*
> ```XML
>     // page as well as the toolbox. Another reason is that other checkboxes in the toolbox, like
>     // Show playback order buttons, have their logic here, so it feels cleaner to keep their handling
>     //
> ```

I think you missed finishing this comment.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts` line 2587 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5854#-NVejcCA2M5wvYgfp_s8:-NVejcCA2M5wvYgfp_s9:bm0jt0d) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/96d3d326df8012b0a14b3a8a49a57811e0d13be0/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L2587)):*
> ```XML
>             showingImageDescriptions,
>             kShowImageDescriptionClickHandler
>         );
> ```

This logic is repeated and seems worth extracting to a function like `updateShowImageDescriptionCheckbox`.
```
        this.showImageDescriptionInput.checked = showingImageDescriptions;
        // This sets a class on the label (not sure we use it for this checkbox)
        this.setCheckboxLabelClass(
            showingImageDescriptions,
            kShowImageDescriptionClickHandler
        );
```
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookToolboxTool.pug` line 57 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5854#-NVehiv7CJwtNhxnn0Ib:-NVehiv7CJwtNhxnn0Ic:bunj3qa) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/96d3d326df8012b0a14b3a8a49a57811e0d13be0/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookToolboxTool.pug#L57)):*
> ```Pug
> 					#import-recording-button-container
> 					+checkboxWithHiddenClickHandler('playbackOrderControl', 'EditTab.Toolbox.TalkingBookTool.ShowPlaybackOrder','Show playback order buttons', false, 'padding-top:16px')
> 					+checkboxWithHiddenClickHandler('showImageDescription', 'EditTab.Toolbox.TalkingBookTool.ShowImageDescription','Show image description', false, 'padding-top:16px')
> ```

I think `EditTab.Toolbox.TalkingBookTool.ShowImageDescription` needs a new entry in the .xlf.
Might as well skip the `translate='no'` at this point, methinks.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5854)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts` line 1928 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5854#-NVehExeCyJJhoSelAj1:-NVey4CX-fbU9s3tuHD7:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/96d3d326df8012b0a14b3a8a49a57811e0d13be0/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L1928)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think you missed finishing this comment.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts` line 2587 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5854#-NVejcCA2M5wvYgfp_s8:-NVeymvs26G1bxJ3efAv:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/96d3d326df8012b0a14b3a8a49a57811e0d13be0/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L2587)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This logic is repeated and seems worth extracting to a function like `updateShowImageDescriptionCheckbox`.
```
        this.showImageDescriptionInput.checked = showingImageDescriptions;
        // This sets a class on the label (not sure we use it for this checkbox)
        this.setCheckboxLabelClass(
            showingImageDescriptions,
            kShowImageDescriptionClickHandler
        );
```
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookToolboxTool.pug` line 57 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5854#-NVehiv7CJwtNhxnn0Ib:-NVf0FEX9WqtvsUy6rGU:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/96d3d326df8012b0a14b3a8a49a57811e0d13be0/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookToolboxTool.pug#L57)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think `EditTab.Toolbox.TalkingBookTool.ShowImageDescription` needs a new entry in the .xlf.
Might as well skip the `translate='no'` at this point, methinks.
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5854)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5854)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
