### PR TITLE
BL-6073 Add Open File Location sign language link

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2852)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2852)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[DistFiles/localization/en/Bloom.xlf, line 1980 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2852#-LQA16Y18aLuRnpA9ai0:-LQA16Y18aLuRnpA9ai1:b-rbwzwg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1ae2bed77a63a44e8cc8afeb5c628c9544267957/DistFiles/localization/en/Bloom.xlf#L1980)):*
> ```XML
>         <note>ID: EditTab.Toolbox.SignLanguage.ImportVideo</note>
>       </trans-unit>
>       <trans-unit id="EditTab.Toolbox.SignLanguage.OpenFileLocation" sil:dynamic="true">
> ```

The upcoming BL-6664 will have this name as "Show in Folder"... if you make any other changes, might as well do that now.
___
*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 404 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2852#-LQA0HkB5Cu6z6fjqd5_:-LQA0HkB5Cu6z6fjqd5a:bpuw65s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1ae2bed77a63a44e8cc8afeb5c628c9544267957/src/BloomExe/web/controllers/SignLanguageApi.cs#L404)):*
> ```Smalltalk
> 				if (mainForm != null)
> 				{
> 					mainForm.Activated += CheckForChangedVideoOnActivate;
> ```

It seems a little iffy to say that we only notice an update if you happen to have displayed the video file using this mechanism. Personally, once I had that folder open, I probably wouldn't use this mechanism again, because it would open yet another window. So I think I would end up wondering, How come sometimes Bloom seems to notice my changes, and sometimes it doesn't?

And then, if we could just generically do the ``CheckForChangedVideoOnActivate``, this whole method could go away.  We could, if we don't already, have a generic API method that just runs ``PathUtilities.SelectFileInExplorer`` on the given path.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2852)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[DistFiles/localization/en/Bloom.xlf, line 1980 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2852#-LQA16Y18aLuRnpA9ai0:-LQB9tuJ7afu5bH6rcqi:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1ae2bed77a63a44e8cc8afeb5c628c9544267957/DistFiles/localization/en/Bloom.xlf#L1980)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

The upcoming BL-6664 will have this name as "Show in Folder"... if you make any other changes, might as well do that now.
</blockquote></details>

Done.
___
*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 404 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2852#-LQA0HkB5Cu6z6fjqd5_:-LQBHr2u70nUZYx_9kdJ:b-p1rs6y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1ae2bed77a63a44e8cc8afeb5c628c9544267957/src/BloomExe/web/controllers/SignLanguageApi.cs#L404)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

It seems a little iffy to say that we only notice an update if you happen to have displayed the video file using this mechanism. Personally, once I had that folder open, I probably wouldn't use this mechanism again, because it would open yet another window. So I think I would end up wondering, How come sometimes Bloom seems to notice my changes, and sometimes it doesn't?

And then, if we could just generically do the ``CheckForChangedVideoOnActivate``, this whole method could go away.  We could, if we don't already, have a generic API method that just runs ``PathUtilities.SelectFileInExplorer`` on the given path.
</blockquote></details>

I redid things so that we always check for changed videos when activating bloom in edit mode. That simplified this method. I didn't actually replace it with a generic open-file-in-explorer API, for reasons I've put in comments.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2852)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 379 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2852#-LQFnuae8NaJMhEnWhe2:-LQFnuae8NaJMhEnWhe3:bobr7i0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6af4fc2ef9a5daf6862c619f59b581d1aa7c9163/src/BloomExe/web/controllers/SignLanguageApi.cs#L379)):*
> ```Smalltalk
> 		// Note: we could generalize this into a request to open the folder containing any file.
> 		// But we don't yet actually need that anywhere else, and it would force us to duplicate
> 		// in JavaScript all the logic we already have in C# for figuring out the path to the
> ```

So this morning we decided actually this does belong in JS-land. This one, then can become generic.

We have multiple placed that do open folders, include one already JS-land (Sample Words:Sample Texts Folder).
___
*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 733 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2852#-LQFoxAHDZ3brRWb_rWD:-LQFoxAHDZ3brRWb_rWE:b-v6jko0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6af4fc2ef9a5daf6862c619f59b581d1aa7c9163/src/BloomExe/web/controllers/SignLanguageApi.cs#L733)):*
> ```Smalltalk
> 		public DateTime DeactivateTime { get; set; }
> 
> 		public void CheckForChangedVideoOnActivate(object sender, EventArgs eventArgs)
> ```

I fear I don't even know why we need to check that something changed. There's a lot of comments here, but they seem to assume that it's obvious that we have to do something?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2852)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 379 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2852#-LQFnuae8NaJMhEnWhe2:-LQGP6zuEEM6Mt6Uq9r6:b-lbbj2r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6af4fc2ef9a5daf6862c619f59b581d1aa7c9163/src/BloomExe/web/controllers/SignLanguageApi.cs#L379)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

So this morning we decided actually this does belong in JS-land. This one, then can become generic.

We have multiple placed that do open folders, include one already JS-land (Sample Words:Sample Texts Folder).
</blockquote></details>

Done. (I haven't actually made the Sample Words be opened like this, because it's opening a folder, not a particular file, and also it's not obvious how the JS can get hold of the path. But we're moving the right way, I hope.)
___
*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 733 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2852#-LQFoxAHDZ3brRWb_rWD:-LQGP5vT8yCveX_iWAwp:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6af4fc2ef9a5daf6862c619f59b581d1aa7c9163/src/BloomExe/web/controllers/SignLanguageApi.cs#L733)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I fear I don't even know why we need to check that something changed. There's a lot of comments here, but they seem to assume that it's obvious that we have to do something?
</blockquote></details>

Done.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2852)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 733 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2852#-LQFoxAHDZ3brRWb_rWD:-LQGQmGd2OccP_nJNF6q:bfti3vs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6af4fc2ef9a5daf6862c619f59b581d1aa7c9163/src/BloomExe/web/controllers/SignLanguageApi.cs#L733)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Maybe that points me in the right direction, but... is the reason we need to do something that otherwise the browser will play a cached version?

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2852)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 733 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2852#-LQFoxAHDZ3brRWb_rWD:-LQGRAvrAfso1J2DnrU7:b-nfvqpg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6af4fc2ef9a5daf6862c619f59b581d1aa7c9163/src/BloomExe/web/controllers/SignLanguageApi.cs#L733)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Maybe that points me in the right direction, but... is the reason we need to do something that otherwise the browser will play a cached version?
</blockquote></details>

What follows is a LOT of complexity/room for bugs, so it needs some serious justification :-)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2852)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 733 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2852#-LQFoxAHDZ3brRWb_rWD:-LQGRohA7Hw-2jpO3254:b-hundxz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6af4fc2ef9a5daf6862c619f59b581d1aa7c9163/src/BloomExe/web/controllers/SignLanguageApi.cs#L733)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

What follows is a LOT of complexity/room for bugs, so it needs some serious justification :-)
</blockquote></details>

tried again.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2852)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 733 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2852#-LQFoxAHDZ3brRWb_rWD:-LQGRt2W0fE_sm5PtTlu:bb8i3pc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6af4fc2ef9a5daf6862c619f59b581d1aa7c9163/src/BloomExe/web/controllers/SignLanguageApi.cs#L733)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

tried again.
</blockquote></details>

It will possibly get a little simpler with the elimination of "Edit outside bloom" in my current task.

**Pull request merged**
