### PR TITLE
Allow text box audio recording in xmatter

### PR DESCRIPTION
**Pull request by JohnThomson**
Includes a major change that, by default, saves attributes along with content of elements that get copied to data-div.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
My review is still in progress...

> Reviewed 6 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523#-:-Lvv6S8Y7OrbtOJbeNYf:b-zbdkat)* status: 6 of 9 files reviewed, 8 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Book/BookData.cs, line 850 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523#-Lvv22Xw5KRiVc7HM22Y:-Lvv22Xw5KRiVc7HM22Z:b-cihvoj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8376560bbac8cc89442fc14ddb7b3d761eb1c5c8/src/BloomExe/Book/BookData.cs#L850)):*
> ```Smalltalk
> 				// Junk that gets left behind by UI
> 				"tabindex", "aria-describedby", "data-book", "aria-label", "role", "spellcheck",
> 				"data-hasqtip", "data-languagetipcontent",
> ```

data-book isn't "left behind by UI", is it? 
Also, if we have data-book, we should probably have data-collection.
___
*[src/BloomExe/Book/BookStorage.cs, line 684 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523#-Lvv1QWQBHwK24eqbkVg:-Lvv1QWQBHwK24eqbkVh:b-gvg3z6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8376560bbac8cc89442fc14ddb7b3d761eb1c5c8/src/BloomExe/Book/BookStorage.cs#L684)):*
> ```Smalltalk
> 				// technically could be in back matter, but typically back matter has no recordable text,
> 				// and xmatter seems too technical a term for end users to see.
> 				FeaturePhrase = "Whole Text Box Audio in Front Matter",
> ```

Our user phrase is usually Front/Back Matter. Is that too long/unwieldy?
___
*[src/BloomTests/Book/BookDataTests.cs, line 25 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523#-Lvv3KuWA7Mdh35oSFEc:-Lvv3KuWA7Mdh35oSFEd:b-3kwaht) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8376560bbac8cc89442fc14ddb7b3d761eb1c5c8/src/BloomTests/Book/BookDataTests.cs#L25)):*
> ```Smalltalk
> 	// now copied to output elements. So be careful about using id to get an element
> 	// you want to test in the result. It may be better to use a unique attribute name.
> 	// However, any attribute on the input element will get copied to the output unless forbidden.
> ```

This makes me pretty nervous, the more I think about it. Are there not places in our production code where we look up elements by id?

I guess you said in flowdock that we are already duplicating ids for `audio-sentence`s, so that does make me feel better, but could there be other things lurking?

Sorry... I know this is questioning the whole approach after you already asked for feedback on the implementation design previously. There's something about seeing a change which makes one think about it differently.
___
*[src/BloomTests/Book/BookDataTests.cs, line 1666 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523#-Lvv5pSLCuy-NY6_oYag:-Lvv5pSLCuy-NY6_oYah:bbuynmp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8376560bbac8cc89442fc14ddb7b3d761eb1c5c8/src/BloomTests/Book/BookDataTests.cs#L1666)):*
> ```Smalltalk
> 		{
> 			// This is not very realistic. We expect that the junk attributes will NOT ever get into the bloomDataDiv. But the source for copying
> 			// in SynchronizeDataItemsThroughoutDOM is the FIRST element with a given data-book.
> ```

Sorry; I don't understand this comment regarding the FIRST element.
I also don't understand why you're talking about junk in the data div. I don't see any junk in there in your test.
___
*[src/BloomTests/Book/BookDataTests.cs, line 1676 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523#-Lvv5PNXCRyacVIfndTC:-Lvv5PNXCRyacVIfndTD:b-qid68z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8376560bbac8cc89442fc14ddb7b3d761eb1c5c8/src/BloomTests/Book/BookDataTests.cs#L1676)):*
> ```Smalltalk
> 				</body></html>");
> 			var data = new BookData(dom, _collectionSettings, null);
> 			data.SynchronizeDataItemsThroughoutDOM();
> ```

Do we need to verify that the datadiv doesn't get changed in unwanted ways? Or does the sync in that direction happen in a different method?
___
*[src/BloomTests/Book/BookDataTests.cs, line 1727 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523#-Lvv6AI11c7IPprt5t0k:-Lvv6AI11c7IPprt5t0l:bp6uryd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8376560bbac8cc89442fc14ddb7b3d761eb1c5c8/src/BloomTests/Book/BookDataTests.cs#L1727)):*
> ```
> [@findMe='foo']
> ```
Should be foo2.
___
*[src/BloomTests/Book/BookDataTests.cs, line 1731 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523#-Lvv6HMQ-GC3S1FwEXAB:-Lvv6HMQ-GC3S1FwEXAC:bkruakt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8376560bbac8cc89442fc14ddb7b3d761eb1c5c8/src/BloomTests/Book/BookDataTests.cs#L1731)):*
> ```Smalltalk
> 			Assert.That(foo.GetAttribute("data-audiorecordingendtimes"), Is.EqualTo("1.640 4.640"));
> 			// also copied to destination that previously didn't have it.
> 			Assert.That(foo.GetAttribute("data-audiorecordingendtimes"), Is.EqualTo("1.640 4.640"));
> ```

I think this is supposed to be foo2.
___
*[src/BloomTests/Book/BookDataTests.cs, line 1738 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523#-Lvv6M7wAOtNFMDn3_W2:-Lvv6M7wAOtNFMDn3_W3:b-ndwd2n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8376560bbac8cc89442fc14ddb7b3d761eb1c5c8/src/BloomTests/Book/BookDataTests.cs#L1738)):*
> ```Smalltalk
> 			Assert.That(classes, Does.Contain("bloom-postAudioSplit"));
> 			// a class that is potentially deletable, present in source but not destination, is added
> 			Assert.That(classes, Does.Contain("bloom-postAudioSplit"));
> ```

classes2

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523)* status: 4 of 9 files reviewed, 8 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/Book/BookData.cs, line 850 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523#-Lvv22Xw5KRiVc7HM22Y:-Lvvk0V87SV_nciebBeb:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8376560bbac8cc89442fc14ddb7b3d761eb1c5c8/src/BloomExe/Book/BookData.cs#L850)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

data-book isn't "left behind by UI", is it? 
Also, if we have data-book, we should probably have data-collection.
</blockquote></details>

Done.
___
*[src/BloomExe/Book/BookStorage.cs, line 684 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523#-Lvv1QWQBHwK24eqbkVg:-Lvvk7Nx35gH47AL3gAH:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8376560bbac8cc89442fc14ddb7b3d761eb1c5c8/src/BloomExe/Book/BookStorage.cs#L684)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Our user phrase is usually Front/Back Matter. Is that too long/unwieldy?
</blockquote></details>

Done.
___
*[src/BloomTests/Book/BookDataTests.cs, line 25 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523#-Lvv3KuWA7Mdh35oSFEc:-LvvkCx08T_Fcinv1GE8:b-jdoopm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8376560bbac8cc89442fc14ddb7b3d761eb1c5c8/src/BloomTests/Book/BookDataTests.cs#L25)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This makes me pretty nervous, the more I think about it. Are there not places in our production code where we look up elements by id?

I guess you said in flowdock that we are already duplicating ids for `audio-sentence`s, so that does make me feel better, but could there be other things lurking?

Sorry... I know this is questioning the whole approach after you already asked for feedback on the implementation design previously. There's something about seeing a change which makes one think about it differently.
</blockquote></details>

We make extensive use of ids in the toolbox. The problem is only elements that have data-book AND are being synchronized throughout the book AND are then being looked up by ID.
___
*[src/BloomTests/Book/BookDataTests.cs, line 1666 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523#-Lvv5pSLCuy-NY6_oYag:-LvvlK1p8s1WiiJdwDI8:b-ytr3ij) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8376560bbac8cc89442fc14ddb7b3d761eb1c5c8/src/BloomTests/Book/BookDataTests.cs#L1666)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; I don't understand this comment regarding the FIRST element.
I also don't understand why you're talking about junk in the data div. I don't see any junk in there in your test.
</blockquote></details>

I've tried to improve the comment (actually on its first occurrence; I don't think it's needed here).
___
*[src/BloomTests/Book/BookDataTests.cs, line 1676 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523#-Lvv5PNXCRyacVIfndTC:-LvvlWlM8n8hXwS1fHjb:b-o4jkxa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8376560bbac8cc89442fc14ddb7b3d761eb1c5c8/src/BloomTests/Book/BookDataTests.cs#L1676)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Do we need to verify that the datadiv doesn't get changed in unwanted ways? Or does the sync in that direction happen in a different method?
</blockquote></details>

A different method but it uses almost all the same code. There may be something it would be useful to check but I can't think what.
___
*[src/BloomTests/Book/BookDataTests.cs, line 1727 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523#-Lvv6AI11c7IPprt5t0k:-Lvvlz8C8xiJLICv3TRZ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8376560bbac8cc89442fc14ddb7b3d761eb1c5c8/src/BloomTests/Book/BookDataTests.cs#L1727)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> [@findMe='foo']
> ```
Should be foo2.
</blockquote></details>

Done.
___
*[src/BloomTests/Book/BookDataTests.cs, line 1731 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523#-Lvv6HMQ-GC3S1FwEXAB:-LvvmSc633iBel7sWiXs:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8376560bbac8cc89442fc14ddb7b3d761eb1c5c8/src/BloomTests/Book/BookDataTests.cs#L1731)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this is supposed to be foo2.
</blockquote></details>

Done.
___
*[src/BloomTests/Book/BookDataTests.cs, line 1738 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523#-Lvv6M7wAOtNFMDn3_W2:-Lvvm7l527yIKIHUR1ZQ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8376560bbac8cc89442fc14ddb7b3d761eb1c5c8/src/BloomTests/Book/BookDataTests.cs#L1738)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

classes2
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomTests/Book/BookDataTests.cs, line 1666 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523#-Lvv5pSLCuy-NY6_oYag:-LvwPrjSAjDxtk-YaOvn:byx46kp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8376560bbac8cc89442fc14ddb7b3d761eb1c5c8/src/BloomTests/Book/BookDataTests.cs#L1666)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I've tried to improve the comment (actually on its first occurrence; I don't think it's needed here).
</blockquote></details>

Looks like it is in place here but removed from the other occurrence. But I think that is correct.
___
*[src/BloomTests/Book/BookDataTests.cs, line 1731 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523#-Lvv6HMQ-GC3S1FwEXAB:-LvwPYJA2EiHKWBNOty8:brqxqbm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8376560bbac8cc89442fc14ddb7b3d761eb1c5c8/src/BloomTests/Book/BookDataTests.cs#L1731)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see this change. I think the 2 got put a few lines down on classes by mistake.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomTests/Book/BookDataTests.cs, line 1731 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523#-Lvv6HMQ-GC3S1FwEXAB:-LvzZmjrEhbQZYynWXGZ:b-j7ub7n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8376560bbac8cc89442fc14ddb7b3d761eb1c5c8/src/BloomTests/Book/BookDataTests.cs#L1731)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't see this change. I think the 2 got put a few lines down on classes by mistake.
</blockquote></details>

Both fixed. Sorry.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 1 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3523)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
