### PR TITLE
BL-5110 Embed Fonts in BloomD package

### PR DESCRIPTION
**Pull request by JohnThomson**
Also fixes bug missing font files with upper case extensions

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2239)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/BloomReaderFileMaker.cs, line 93 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2239#-L6cSwkpBLU4BkJBBILz:-L6cSwkpBLU4BkJBBIM-:b-55l3oq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a9a5469ef6edc7b57567c401fdc22a525430dc80/src/BloomExe/Book/BloomReaderFileMaker.cs#L93)):*
> ```Smalltalk
> 				{
> 					filesToEmbed.AddRange(fontFiles);
> 					progress.MessageWithoutLocalizing(string.Format(LocalizationManager.GetString("CheckFontOK",
> ```

These messages seem like things that should be localized.

---

*[src/BloomExe/Book/BloomReaderFileMaker.cs, line 121 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2239#-L6cSGTDeSCqjgs5dIdn:-L6cSGTEhQPU8-yUrQFU:b-7wefmw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a9a5469ef6edc7b57567c401fdc22a525430dc80/src/BloomExe/Book/BloomReaderFileMaker.cs#L121)):*
> ```Smalltalk
> 				RobustFile.Copy(file, dest);
> 			}
> 			var sb = new StringBuilder();
> ```

Please add a comment around here saying what fonts.css is for, what it is that will start using it, etc.. I honestly can't figure out what it could be for. This is also not mentioned in the summary statement at the beginning of this method, though it would seem to be a major output.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2239)*

**Comment by JohnThomson** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/BloomReaderFileMaker.cs, line 93 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2239#-L6cSwkpBLU4BkJBBILz:-L6ceMqSVGrzzqesd3sw:bsk5974) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a9a5469ef6edc7b57567c401fdc22a525430dc80/src/BloomExe/Book/BloomReaderFileMaker.cs#L93)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

These messages seem like things that should be localized.
</blockquote></details>

They are :-). But I guess it would be cleaner to use one of the progress methods that takes params and let it do the localizing. Unfortunately there isn't one for Error, but I guess I can add it.

---

*[src/BloomExe/Book/BloomReaderFileMaker.cs, line 121 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2239#-L6cSGTDeSCqjgs5dIdn:-L6cep-jHQuA2Zma9GM4:b-ozk5xg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a9a5469ef6edc7b57567c401fdc22a525430dc80/src/BloomExe/Book/BloomReaderFileMaker.cs#L121)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Please add a comment around here saying what fonts.css is for, what it is that will start using it, etc.. I honestly can't figure out what it could be for. This is also not mentioned in the summary statement at the beginning of this method, though it would seem to be a major output.
</blockquote></details>

Will do. (It's the magic that tells the browser to use the local file for this font family.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2239)*

**Comment by JohnThomson** [comment]
Changes made...paying more attention to localization caught some other problems, like not adding the new xlf entries.

---

Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2239#-:-L6cn7FXgV4lLBJN4uGb:bghlrwk)*

**Comment by hatton** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/BloomReaderFileMaker.cs, line 121 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2239#-L6cSGTDeSCqjgs5dIdn:-L6cr4rYSk3T1SF-8PaV:b-a997bn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a9a5469ef6edc7b57567c401fdc22a525430dc80/src/BloomExe/Book/BloomReaderFileMaker.cs#L121)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Will do. (It's the magic that tells the browser to use the local file for this font family.)
</blockquote></details>

I don't know why font.css is needed. Are the existing stylesheets still in place? Rick reported that the font fallback already worked, presumably without this file. Sorry if I'm missing something obvious.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2239)*

**Comment by JohnThomson** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/BloomReaderFileMaker.cs, line 121 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2239#-L6cSGTDeSCqjgs5dIdn:-L6csNVHq4edoz6gSJ3M:b-4ionsd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a9a5469ef6edc7b57567c401fdc22a525430dc80/src/BloomExe/Book/BloomReaderFileMaker.cs#L121)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I don't know why font.css is needed. Are the existing stylesheets still in place? Rick reported that the font fallback already worked, presumably without this file. Sorry if I'm missing something obvious.
</blockquote></details>

This is not to achieve font fallback when we can't embed the font file. It's to make the browser USE the font file for the font we really want when we DO embed it. AFAIK, when a style sheet says something like font-family: Parchment, that won't cause the browser to notice that there is a file "Parchment R.ttf" in the book folder and use it. You need a rule like
@font-face {font-family:'Parchment'; font-weight:normal; font-style:normal; src:url(Parchment R.ttf) format('opentype');}
Those rules are what go in this extra stylesheet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2239)*

**Comment by JohnThomson** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/BloomReaderFileMaker.cs, line 121 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2239#-L6cSGTDeSCqjgs5dIdn:-L6cuNxYiKeLoZE16bYi:buxnap8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a9a5469ef6edc7b57567c401fdc22a525430dc80/src/BloomExe/Book/BloomReaderFileMaker.cs#L121)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This is not to achieve font fallback when we can't embed the font file. It's to make the browser USE the font file for the font we really want when we DO embed it. AFAIK, when a style sheet says something like font-family: Parchment, that won't cause the browser to notice that there is a file "Parchment R.ttf" in the book folder and use it. You need a rule like
@font-face {font-family:'Parchment'; font-weight:normal; font-style:normal; src:url(Parchment R.ttf) format('opentype');}
Those rules are what go in this extra stylesheet.
</blockquote></details>

See https://www.w3schools.com/cssref/css3_pr_font-face_rule.asp

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2239)*

**Comment by hatton** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Book/BloomReaderFileMaker.cs, line 121 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2239#-L6cSGTDeSCqjgs5dIdn:-L6cuN_lIYk8Z_jLe6YD:b-ug5ww5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a9a5469ef6edc7b57567c401fdc22a525430dc80/src/BloomExe/Book/BloomReaderFileMaker.cs#L121)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

See https://www.w3schools.com/cssref/css3_pr_font-face_rule.asp
</blockquote></details>

OK, originally I would have thought so too, I think I must have misunderstood what what Rick meant in https://issues.bloomlibrary.org/youtrack/issue/BL-5688.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2239)*

**Pull request merged**
