### PR TITLE
BL-11954 Publish Initial screen

### PR DESCRIPTION
**Pull request by gmartin7**
* removed old PDF Options
* added Choose a PDF option initial screen
* might need better disabled Print/Save buttons

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5662)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
review still in progress...

> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5662#-:-NP-YWwq0fS9FOnjRRUo:btufcn5)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[`DistFiles/localization/en/Bloom.xlf` line 1 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5662#-NP-Xp3r2OHbNCXSqUrx:-NP-Xp3r2OHbNCXSqUry:bfnunji) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8aeee6047b1ab14481b3cea3a0a87ba7f1f0b757/DistFiles/localization/en/Bloom.xlf#L1)):*
> ```XML
> <?xml version="1.0" encoding="utf-8"?>
> ```

We need to mark all the obsolete strings as obsolete for 5.5. (Search for how we usually do that below.)
___
*[`DistFiles/localization/en/Bloom.xlf` line 4116 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5662#-NP-Xv9V2Akk7bdxpR0d:-NP-Xv9V2Akk7bdxpR0e:bfdo7ek) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8aeee6047b1ab14481b3cea3a0a87ba7f1f0b757/DistFiles/localization/en/Bloom.xlf#L4116)):*
> ```XML
>         <note>ID: PublishTab.PdfMaker.ClickToStart2</note>
>       </trans-unit
>       -->
> ```

Now that we've discovered the better way to do this, let's mark them as `translate="no"` instead of commenting them. And remove the temporarily ignore untranslated stuff.
For bonus points, you can do that for all the new pdf stuff JT added, too.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5662)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[`DistFiles/localization/en/Bloom.xlf` line 4116 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5662#-NP-Xv9V2Akk7bdxpR0d:-NP-aqU_5xVwRikI9jDA:b-720ytg) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8aeee6047b1ab14481b3cea3a0a87ba7f1f0b757/DistFiles/localization/en/Bloom.xlf#L4116)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Now that we've discovered the better way to do this, let's mark them as `translate="no"` instead of commenting them. And remove the temporarily ignore untranslated stuff.
For bonus points, you can do that for all the new pdf stuff JT added, too.
</blockquote></details>

You can see how I did that for some strings. I included a comment to make it easy to know why we want translate="no" for a particular string (added for 5.5)

**Review by andrew-polk — COMMENTED** [review]
Initial review complete.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5662#-:-NP-cmy_2ZACr9oJ_bDT:bsy7r2m)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5662)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/Bloom.xlf` line 1 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5662#-NP-Xp3r2OHbNCXSqUrx:-NP3nzL9DZij12Ici6gW:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8aeee6047b1ab14481b3cea3a0a87ba7f1f0b757/DistFiles/localization/en/Bloom.xlf#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We need to mark all the obsolete strings as obsolete for 5.5. (Search for how we usually do that below.)
</blockquote></details>

Done.
___
*[`DistFiles/localization/en/Bloom.xlf` line 4116 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5662#-NP-Xv9V2Akk7bdxpR0d:-NP3ST5B9ei5U_XF9ewV:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8aeee6047b1ab14481b3cea3a0a87ba7f1f0b757/DistFiles/localization/en/Bloom.xlf#L4116)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

You can see how I did that for some strings. I included a comment to make it easy to know why we want translate="no" for a particular string (added for 5.5)
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5662)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx` line 80 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5662#-NP4AE_tDIaxpfpedX8A:-NP4AE_uE40xSzOna65k:bz1j27c) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/577177d85cbcabd02a74b9d78dfa7e507f291e3f/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx#L80)):*
> ```XML
>         undefined,
>         undefined,
>         true
> ```

These want to have the temp disable props not set now.
Then, LGTM

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5662)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`DistFiles/localization/en/Bloom.xlf` line 4116 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5662#-NP-Xv9V2Akk7bdxpR0d:-NP4ATT4AOxsZPxquAHo:b2vf4mn) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8aeee6047b1ab14481b3cea3a0a87ba7f1f0b757/DistFiles/localization/en/Bloom.xlf#L4116)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks. You get bonus points. Now if only we knew what to do with them...

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5662)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx` line 80 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5662#-NP4AE_tDIaxpfpedX8A:-NP4HWfo8WBzBxxNsTME:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/577177d85cbcabd02a74b9d78dfa7e507f291e3f/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx#L80)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

These want to have the temp disable props not set now.
Then, LGTM
</blockquote></details>

Done.

**Pull request merged**
