### PR TITLE
BL-3148 Make Bloom Epubs pass Pagina Validation

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1133)

### CODE REVIEW

**Comment by hatton** [comment]
One question about mp3 duration, otherwise LGTM.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 385 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1133#-KMZ7w_k7SbPXS3NPBFY:-KMZ7w_k7SbPXS3NPBFZ:-1289484968) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9bfe9c5a62c987cdc1f9b6e9033750970b1fdc31/src/BloomExe/Publish/EpubMaker.cs#L385)):*
> ```Smalltalk
> 				else
> 				{
> 					// Crude estimate. In one sample, a 61K mp3 is 7s long.
> ```

I'm dubious about this, given that the bitrate can be changed and indeed can be variable within a file. We could include sox to do this, it's small enough and cross platform. HearThis uses it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1133#-:-KMZATQP0GpUZgK8EDX2:1429173224)*

**Comment by JohnThomson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 385 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1133#-KMZ7w_k7SbPXS3NPBFY:-KMZWt9t8zZFCPJpaDDB:-2017107101) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9bfe9c5a62c987cdc1f9b6e9033750970b1fdc31/src/BloomExe/Publish/EpubMaker.cs#L385)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary>
> I'm dubious about this, given that the bitrate can be changed and indeed can be variable within a file. We could include sox to do this, it's small enough and cross platform. HearThis uses it.
</details>
I'm dubious too. We could also just nuget lame, if we're sufficiently confident that the licensing people have agreed to overlook us.
It's a very low-probability case, because Bloom currently makes .wav recordings and derives the mp3 from them, so to have mp3 only someone would have to manually delete the .wav files or create the audio annotations by hand or something similar. That's one reason I was willing to make a crude estimate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1133)*

**Comment by hatton** [comment]
Can we just... make it break? I dislike these "well this is better than nothing" things... I'd rather "fail fast".

**Comment by JohnThomson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 385 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1133#-KMZ7w_k7SbPXS3NPBFY:-KN2uL_-fya7SB0QAqog:-1432056193) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9bfe9c5a62c987cdc1f9b6e9033750970b1fdc31/src/BloomExe/Publish/EpubMaker.cs#L385)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary>
> I'm dubious too. We could also just nuget lame, if we're sufficiently confident that the licensing people have agreed to overlook us.
> It's a very low-probability case, because Bloom currently makes .wav recordings and derives the mp3 from them, so to have mp3 only someone would have to manually delete the .wav files or create the audio annotations by hand or something similar. That's one reason I was willing to make a crude estimate.
</details>
I added a NonFatalProblem report. Once it's merged, could further add code to look for the data-duration attribute, if it seems worth it...though we'd only have that if we made the recording, in which case, we should have kept the wav file. But if someone just deleted them to save space...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1133)*

**Comment by JohnThomson** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 385 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1133#-KMZ7w_k7SbPXS3NPBFY:-KN2wCEiZaV9_BS7CYXC:-1935656486) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9bfe9c5a62c987cdc1f9b6e9033750970b1fdc31/src/BloomExe/Publish/EpubMaker.cs#L385)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary>
> I added a NonFatalProblem report. Once it's merged, could further add code to look for the data-duration attribute, if it seems worth it...though we'd only have that if we made the recording, in which case, we should have kept the wav file. But if someone just deleted them to save space...
</details>
Realized I CAN add the search for data-duration, even though before merge Bloom won't create them

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1133)*

**Pull request merged**
