### PR TITLE
Hide experimental tools unless requested (BL-5864)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2414)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/BloomExe/app.config, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2414#-LCoW_-c8I3zx_YVQoPh:-LCoW_-c8I3zx_YVQoPi:bwqmdsu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ec8e22c4fd7fbbc9baee0b8706c711e31a1e604d/src/BloomExe/app.config#L40)):*
> ```
>         <value />
>       </setting>
>       <setting name="ShowExperimentalFeatures" serializeAs="String">
> ```

Isn't this going to result in a false setting for every user when they upgrade to 4.3 regardless of their prior setting?

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2414)*

**Comment by StephenMcConnel** [comment]
Review status: 17 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/app.config, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2414#-LCoW_-c8I3zx_YVQoPh:-LCoancy-yVwr_xD5a5D:bihdlml) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ec8e22c4fd7fbbc9baee0b8706c711e31a1e604d/src/BloomExe/app.config#L40)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Isn't this going to result in a false setting for every user when they upgrade to 4.3 regardless of their prior setting?
</blockquote></details>

Absolutely.  I don't see any way to avoid that happening when a setting is renamed.  If you have any idea of how to do something in the .Net framework world to preserve the setting, I'd be happy to learn.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2414)*

**Comment by andrew-polk** [comment]
Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/app.config, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2414#-LCoW_-c8I3zx_YVQoPh:-LCocZ988zUJdhnzYoma:bcn7oj4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ec8e22c4fd7fbbc9baee0b8706c711e31a1e604d/src/BloomExe/app.config#L40)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Absolutely.  I don't see any way to avoid that happening when a setting is renamed.  If you have any idea of how to do something in the .Net framework world to preserve the setting, I'd be happy to learn.
</blockquote></details>

It's possible there is some way to manually migrate, but I don't know either.
Seems we should leave the setting name as it was.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2414)*

**Comment by andrew-polk** [comment]
*[src/BloomExe/app.config, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2414#-LCoW_-c8I3zx_YVQoPh:-LCod2oICMcDLEOr_Q6l:b-b66c6n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ec8e22c4fd7fbbc9baee0b8706c711e31a1e604d/src/BloomExe/app.config#L40)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

It's possible there is some way to manually migrate, but I don't know either.
Seems we should leave the setting name as it was.
</blockquote></details>

Ok, so looking at the card, I see this was asked for. But I wonder if JH realized the implications.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2414)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/BloomExe/app.config, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2414#-LCoW_-c8I3zx_YVQoPh:-LCp551r2GQpsCG8rOA9:b-8n7tfw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ec8e22c4fd7fbbc9baee0b8706c711e31a1e604d/src/BloomExe/app.config#L40)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Ok, so looking at the card, I see this was asked for. But I wonder if JH realized the implications.
</blockquote></details>

There's a block of code at line 140 in Program.cs which checks whether Settings.Default.NeedUpgrade and if so calls Settings.Default.Upgrade().  I have a vague recollection that NeedUpgrade is somehow true if the settings were written by an earlier version of Bloom...not sure how it's possible to configure what Upgrade() does, but there may be a hook there somewhere that you can use.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2414)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/BloomExe/app.config, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2414#-LCoW_-c8I3zx_YVQoPh:-LD2mfc96pCRkOQ4UCK4:bs17hcl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ec8e22c4fd7fbbc9baee0b8706c711e31a1e604d/src/BloomExe/app.config#L40)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

There's a block of code at line 140 in Program.cs which checks whether Settings.Default.NeedUpgrade and if so calls Settings.Default.Upgrade().  I have a vague recollection that NeedUpgrade is somehow true if the settings were written by an earlier version of Bloom...not sure how it's possible to configure what Upgrade() does, but there may be a hook there somewhere that you can use.
</blockquote></details>

In my opinion, it is worth seeing if we can migrate the setting. But since JH says he is okay without it, don't spend a lot of effort.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2414)*

**Comment by StephenMcConnel** [comment]
Review status: 9 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/app.config, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2414#-LCoW_-c8I3zx_YVQoPh:-LD3qc19DjPguqH0Xda6:b-pz7uei) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ec8e22c4fd7fbbc9baee0b8706c711e31a1e604d/src/BloomExe/app.config#L40)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

In my opinion, it is worth seeing if we can migrate the setting. But since JH says he is okay without it, don't spend a lot of effort.
</blockquote></details>

Nothing in the C# .Net settings design allows for preserving the value of a renamed property.  At least for Mono, the old property doesn't disappear from the settings file, but it isn't read in.  I suppose we could write code to find the settings file and load the XML and find the old value, but that's a lot of work that has some cross-platform differences to work out.  All the talk around settings is upgrading between versions where nothing has changed except the program version number.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2414)*

**Comment by StephenMcConnel** [comment]
Review status: 9 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/app.config, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2414#-LCoW_-c8I3zx_YVQoPh:-LDCWRXd7vG73a0APe8J:bby307p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ec8e22c4fd7fbbc9baee0b8706c711e31a1e604d/src/BloomExe/app.config#L40)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We are (or should be...has to be configured for each new property) using our own libpalaso settings persistence class, CrossPlatformSettingsProvider. I think Jason developed this and might be able to tell more about it. I see its Upgrade method makes reference to a RenamedSections property. Not sure whether anything useful can be done with this, but it looks promising...
</blockquote></details>

Looking at the libpalaso code, this feature applies to a "section" such as "Bloom.Properties.Settings", not to individual settings.  It might be possible to enhance the code to also handle individual renamed settings, but I'm reluctant to invest that much effort without further direction.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2414)*

**Comment by andrew-polk** [comment]
Reviewed 12 of 12 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/app.config, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2414#-LCoW_-c8I3zx_YVQoPh:-LDCcm6b4oseqF3HmzPb:b-a06f8w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ec8e22c4fd7fbbc9baee0b8706c711e31a1e604d/src/BloomExe/app.config#L40)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Looking at the libpalaso code, this feature applies to a "section" such as "Bloom.Properties.Settings", not to individual settings.  It might be possible to enhance the code to also handle individual renamed settings, but I'm reluctant to invest that much effort without further direction.
</blockquote></details>

Ok, JH says he doesn't mind if users lose the setting, so merging...

---


*Comments from [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2414)*

**Pull request merged**
