### PR TITLE
BL-12166 Dev menu to edge

### PR DESCRIPTION
**Pull request by hatton**
Open edge when asked
Drop Linux-specific stuff
Drop the "Troubleshooting info" which isn't implemented and wasn't missed.

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5813)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5813)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[`DistFiles/localization/en/Bloom.xlf` line 307 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5813#-NUXIx5j8sVXUWC0WDFg:-NUXIx5k8RXaU9c3S8w0:bsi99wy) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6280c579e6bdebfa5baadf19819b036865b2e1cc/DistFiles/localization/en/Bloom.xlf#L307)):*
> ```XML
>         <source xml:lang="en">Open Page in Firefox (which must be in the PATH environment variable)</source>
>         <note>ID: Browser.OpenPageInFirefox</note>
>       </trans-unit>
> ```

Maybe we don't care for this case, but removing this now means the translations will be lost in 5.4 when we merge in the latest from Crowdin.
Normally, we mark strings as "Obsolete as of Bloom 5.5" in a note.
___
*[`src/BloomExe/IBrowser.cs` line 459 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5813#-NUXJJRdAPCrUISvfH8h:-NUXJJRdAPCrUISvfH8i:btk0j7w) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6280c579e6bdebfa5baadf19819b036865b2e1cc/src/BloomExe/IBrowser.cs#L459)):*
> ```Smalltalk
> 
> 			adder.Add(
> 				LocalizationManager.GetString("Browser.CopyTroubleshootingInfo", "Copy Troubleshooting Information"),
> ```

Should we also mark this as obsolete in the .xlf or remove it?

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5813)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/Bloom.xlf` line 307 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5813#-NUXIx5j8sVXUWC0WDFg:-NUXKyxZ9zYTVGbqchhL:b-1n39gc) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6280c579e6bdebfa5baadf19819b036865b2e1cc/DistFiles/localization/en/Bloom.xlf#L307)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Maybe we don't care for this case, but removing this now means the translations will be lost in 5.4 when we merge in the latest from Crowdin.
Normally, we mark strings as "Obsolete as of Bloom 5.5" in a note.
</blockquote></details>

It was a bug that we ever put this in the list of things to be translated. 
___
*[`src/BloomExe/IBrowser.cs` line 459 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5813#-NUXJJRdAPCrUISvfH8h:-NUXL4IV3x0h208KoL-u:byb2tf0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6280c579e6bdebfa5baadf19819b036865b2e1cc/src/BloomExe/IBrowser.cs#L459)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should we also mark this as obsolete in the .xlf or remove it?
</blockquote></details>

I'm not clear non the context for the question, but it was a bug that we ever put this in the list of things to be translated, so long as it won't break 5.4?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5813)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @hatton)

___
*[`src/BloomExe/IBrowser.cs` line 459 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5813#-NUXJJRdAPCrUISvfH8h:-NUXMzxO-TGkesSu5njd:bfyssrh) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6280c579e6bdebfa5baadf19819b036865b2e1cc/src/BloomExe/IBrowser.cs#L459)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I'm not clear non the context for the question, but it was a bug that we ever put this in the list of things to be translated, so long as it won't break 5.4?
</blockquote></details>

I was referring to the fact that you've removed the "Browser.CopyTroubleshootingInfo" string here but not from the .xlf.
I've removed it.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5813)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hatton)

**Pull request merged**
