### PR TITLE
Make all our zip operations Robust (BL-9926)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4481)

### CODE REVIEW

**Comment by andrew-polk** [comment]
___
*[src/BloomExe/Utils/RobustZip.cs, line 158 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4481#-MaFHkBIEhgK9Q0kQAs9:-MaFHkBIEhgK9Q0kQAsA:boburd2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3041f788d6984ee0ad38a7c0b5640318f82c2df5/src/BloomExe/Utils/RobustZip.cs#L158)):*
> ```Smalltalk
> 				NonFatalProblem.Report(ModalIf.All, PassiveIf.All,
> 					"Bloom could not unpack the collection files in your Team Collection");
> 			}
> ```

I know, it is going to feel like getting penalized for doing the right thing (extracting this method), but this message and user interaction needs to go back to the calling code.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4481)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 295 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4481#-MaU0mgk543hRUUD0R_k:-MaU0mgk543hRUUD0R_l:b-d5ermd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3041f788d6984ee0ad38a7c0b5640318f82c2df5/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L295)):*
> ```Smalltalk
> 
> 		// Extract files from the given zip to the given destination folder. Delete any files in the destFolder which
> 		// are identified by filesToDeleteIfNotInZip() and which were not found in the zip file.
> ```

I think this method comment got orphaned.
___
*[src/BloomExe/Utils/RobustZip.cs, line 158 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4481#-MaFHkBIEhgK9Q0kQAs9:-MaU2Fh8Ali0KSEEqzOx:b184vr8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3041f788d6984ee0ad38a7c0b5640318f82c2df5/src/BloomExe/Utils/RobustZip.cs#L158)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I know, it is going to feel like getting penalized for doing the right thing (extracting this method), but this message and user interaction needs to go back to the calling code.
</blockquote></details>

Looks like it should be as easy as catching the exceptions, though.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4481)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4481)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 295 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4481#-MaU0mgk543hRUUD0R_k:-MaUDfP1EQKjmGkexJnj:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3041f788d6984ee0ad38a7c0b5640318f82c2df5/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L295)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this method comment got orphaned.
</blockquote></details>

Done.
___
*[src/BloomExe/Utils/RobustZip.cs, line 158 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4481#-MaFHkBIEhgK9Q0kQAs9:-MaU2J22CUSoe-WpVnPN:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3041f788d6984ee0ad38a7c0b5640318f82c2df5/src/BloomExe/Utils/RobustZip.cs#L158)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I know, it is going to feel like getting penalized for doing the right thing (extracting this method), but this message and user interaction needs to go back to the calling code.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4481)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
