### PR TITLE
[5.4] BL-11621 Move Overlay text color to editable

### PR DESCRIPTION
**Pull request by gmartin7**
* introduces the concept of a default style text color
* setting the style of a bubble w/StyleEditor can be overridden
   by setting the Overlay tool text color.

- - -
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500)

### CODE REVIEW

**Comment by andrew-polk** [comment]
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500#-NFUU4FE1Cqn96XN5VYj:-NFUU4FE1Cqn96XN5VYk:b-l0md6h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/946390624d96facbdd4bf7a1d275e4c1221f897e/DistFiles/localization/en/BloomMediumPriority.xlf#L13)):*
> ```XML
>         <note>ID: ColorPicker.DefaultForStyle</note>
>         <note>Label for the default color square in the color picker.</note>
>       </trans-unit>
> ```

This string already exists as EditTab.DirectFormatting.labelForDefaultColor in Bloom.xlf.
Let's reuse that or change the ID to share it.
Also, we don't need to comment strings for 5.4 anymore since it is on the verge of beta.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500#-NFUU4FE1Cqn96XN5VYj:-NFUcBfV8j3WCfvRZAqo:b-yqtomb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/946390624d96facbdd4bf7a1d275e4c1221f897e/DistFiles/localization/en/BloomMediumPriority.xlf#L13)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This string already exists as EditTab.DirectFormatting.labelForDefaultColor in Bloom.xlf.
Let's reuse that or change the ID to share it.
Also, we don't need to comment strings for 5.4 anymore since it is on the verge of beta.
</blockquote></details>

Done. Ah! That's the string that ckeditor uses, I suppose. I should have thought of that. I don't think there's anything bad about using the current ID.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500)* status: all files reviewed, 3 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 708 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500#-NFUYCf0Ae_ucIPtbdgB:-NFUYCf1ECJmoh_S4LI2:bwbqnbt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/946390624d96facbdd4bf7a1d275e4c1221f897e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L708)):*
My understanding from the card is we don't want do this yet.
> 5.6 Migrate any existing bubble color to editable color



_Code quote:_
```XML
clear any color on the textOverPicture div
```
___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 740 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500#-NFUaGLn9rUSJxdQsS0b:-NFUaGLn9rUSJxdQsS0c:b-62k1m0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/946390624d96facbdd4bf7a1d275e4c1221f897e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L740)):*
> ```XML
>                 const firstEditable = topBox.getElementsByClassName(
>                     "bloom-editable"
>                 )[0] as HTMLElement;
> ```

Is there not a way to get the bloom-editable directly from the activeEl?
(So that we don't have to rely on just a random (first) editable)

We'll need to do that in the future anyway when we allow for multiple languages, I think.
___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts` line 331 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500#-NFUoHDfEWUzRoXTW5sc:-NFUoHDfEWUzRoXTW5sd:b-8tfjtn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/45d87c7a8d6de730f57226fd2bbd1940a18f6de6/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L331)):*
> ```XML
>             // Now parse out the IDs.
>             const label = rules[j].substring(0, index).trim();
>             const index2 = label.lastIndexOf("-style");
> ```

I'm not excited about having this logic twice, much less having to run it twice for each rule when calling getFormattingStyleNames.
Any better ideas?

Can GetFormattingStyleRules return a map with style name and the full rule?
Then GetFormattingStyleNames could just return that result's keys?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 708 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500#-NFUYCf0Ae_ucIPtbdgB:-NFUyw58-XAiroTpAXyv:b-h9cdda) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/946390624d96facbdd4bf7a1d275e4c1221f897e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L708)):*
This comment just refers to the item before that, I believe.

> 5.4 clear out any color on the bubble and set the color on all bloom-editables.

I didn't do any system-wide migration, which is what the `5.6` line seems to indicate to me.
___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 740 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500#-NFUaGLn9rUSJxdQsS0b:-NFUzJR_3C4DdaJcXeRa:bcl3v16) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/946390624d96facbdd4bf7a1d275e4c1221f897e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L740)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is there not a way to get the bloom-editable directly from the activeEl?
(So that we don't have to rely on just a random (first) editable)

We'll need to do that in the future anyway when we allow for multiple languages, I think.
</blockquote></details>

Um... not sure. It's 2 levels down. There's a `div.bloom-translationGroup` in between. Does that affect what you're saying?
___
*[`src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts` line 331 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500#-NFUoHDfEWUzRoXTW5sc:-NFUzaXp8wlo3oe8bf8F:baiqfge) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/45d87c7a8d6de730f57226fd2bbd1940a18f6de6/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L331)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not excited about having this logic twice, much less having to run it twice for each rule when calling getFormattingStyleNames.
Any better ideas?

Can GetFormattingStyleRules return a map with style name and the full rule?
Then GetFormattingStyleNames could just return that result's keys?
</blockquote></details>

Good idea. I didn't like the duplication either, but hadn't figured out how to get around it.
Backed out this change for now, since we aren't using it yet in bubbleManager.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 740 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500#-NFUaGLn9rUSJxdQsS0b:-NFVP8gHAyo9assIwwFZ:bwjsuhp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/946390624d96facbdd4bf7a1d275e4c1221f897e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L740)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Um... not sure. It's 2 levels down. There's a `div.bloom-translationGroup` in between. Does that affect what you're saying?
</blockquote></details>

I suppose we could do `activeEl.closest(".bloom-editable")`, but it may be itself or some paragraph element, or something.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 740 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500#-NFUaGLn9rUSJxdQsS0b:-NFVQuNY09AnBrZufEKt:b-5x687) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/946390624d96facbdd4bf7a1d275e4c1221f897e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L740)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I suppose we could do `activeEl.closest(".bloom-editable")`, but it may be itself or some paragraph element, or something.
</blockquote></details>

coming soon...

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 740 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500#-NFUaGLn9rUSJxdQsS0b:-NFVSl10DsH1MhZAiD80:bp4i3v0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/946390624d96facbdd4bf7a1d275e4c1221f897e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L740)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

coming soon...
</blockquote></details>

tried using the above and it didn't work for some reason. Maybe try again when we need to have multiple languages.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 708 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500#-NFUYCf0Ae_ucIPtbdgB:-NFVSk1_8dU595edtHCZ:bqthpxu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/946390624d96facbdd4bf7a1d275e4c1221f897e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L708)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

This comment just refers to the item before that, I believe.

> 5.4 clear out any color on the bubble and set the color on all bloom-editables.

I didn't do any system-wide migration, which is what the `5.6` line seems to indicate to me.
</blockquote></details>

You're right. But now I'm not sure the design is right. I put a question in the card.
___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 740 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500#-NFUaGLn9rUSJxdQsS0b:-NFVSrDi5zbNu-7D7jMc:b-3m3tfu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/946390624d96facbdd4bf7a1d275e4c1221f897e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L740)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

coming soon...
</blockquote></details>

Decided this is ok for now.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/bookEdit/js/bubbleManager.ts` line 708 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500#-NFUYCf0Ae_ucIPtbdgB:-NFVf_pz-S3T_SXWipnA:bqzaiva) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/946390624d96facbdd4bf7a1d275e4c1221f897e/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L708)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

You're right. But now I'm not sure the design is right. I put a question in the card.
</blockquote></details>

Resolved in card.

**Pull request merged**
