### PR TITLE
Fix some less trivial compiler warnings

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
These changes will generally require more thought when reviewing than the first round of changes. Many are not trivially guaranteed to produce the same result.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892#-:-MrSysGB7eG6rIxvlQEY:b-rz36wi)* status: 0 of 28 files reviewed, 8 unresolved discussions

___
*[src/BloomExe/ElementProxy.cs, line 244 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892#-MrSySimEJwsSHAQj2r3:-MrSySimEJwsSHAQj2r4:bk8sjhf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c6e1b7cb0c4b10bdae8267a6e32ef1697efd0be/src/BloomExe/ElementProxy.cs#L244)):*
> ```Smalltalk
> 				classes.Remove(className);
> 			}
> 			SetAttribute("class", string.Join(" ", classes));
> ```

Since the old code was passing this into a library function when applies XML Encoding to it, that basically means the old SetAttribute is interpreting the 2nd parameter as an unencoded string.

That means replacing the 2nd parameter (string) with XmlString.FromUnencoded([...]) should produce the same result as before.
___
*[src/BloomExe/Book/Page.cs, line 31 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892#-MrSzCFN-EIYTI4eg2fq:-MrSzCFN-EIYTI4eg2fr:besxn7q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c6e1b7cb0c4b10bdae8267a6e32ef1697efd0be/src/BloomExe/Book/Page.cs#L31)):*
> ```Smalltalk
> 	{
> 		private readonly string _id;
> 		private readonly Func<IPage, Image> _getThumbnail;
> ```

This hasn't been used in close to 10 years.
___
*[src/BloomExe/Publish/AccessibilityChecker/AccessibilityCheckWindow.cs, line 57 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892#-MrSzScc8_BwEWY-J0U3:-MrSzScc8_BwEWY-J0U4:bngz3g0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f42b21d3c7240dfa49f2672cfe29f8fb123af581/src/BloomExe/Publish/AccessibilityChecker/AccessibilityCheckWindow.cs#L57)):*
> ```Smalltalk
> 		protected override void Dispose(bool disposing)
> 		{
> 			if (!_disposed)
> ```

Note: this obviously changes the branching logic compared to before.

Not saying I'm an expert about this, but I was trying to follow the example pattern here: https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#implement-the-dispose-pattern-for-a-derived-class
___
*[src/BloomExe/Utils/MemoryManagement.cs, line 186 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892#-MrSz_uG85138Ghp0j2N:-MrSz_uG85138Ghp0j2O:bc7w19z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c6e1b7cb0c4b10bdae8267a6e32ef1697efd0be/src/BloomExe/Utils/MemoryManagement.cs#L186)):*
> ```Smalltalk
> 	public struct MemoryInformation
> 	{
> 		[CLSCompliant(false)]
> ```

Compiler says this attribute is unnecessary because Bloom does not mark its CLSCompliance. If unmarked, the assembly defaults to CLSCompliant=false.
So, this doesn't provide any new information.

Also, all this is saying is that it returns a ULONG (not supported in CLS), so.... it's not anything super interesting that we couldn't figure out again in case we ever decided Bloom needed to be CLS Complaint.
(I have no idea why we'd need it to be CLSComplaint)
___
*[src/BloomExe/WebLibraryIntegration/BulkUploader.cs, line 38 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892#-MrT-Jk-4PewD6SdNcQs:-MrT-Jk-4PewD6SdNcQt:biiolbg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f42b21d3c7240dfa49f2672cfe29f8fb123af581/src/BloomExe/WebLibraryIntegration/BulkUploader.cs#L38)):*
> ```Smalltalk
> 		{
> 			_singleBookUploader = singleBookUploader;
> 			_thumbnailer = singleBookUploader._thumbnailer;
> ```

This is a change in behavior, technically.

Currently _thumbnailer is always null. After looking at the commit where BulkUploader was separated out from BookUpload, my conclusion was that it was unintentional that _thumbnailer is set to null.
Also, this is passed to PublishModel, which dose not expect or prepare for the possibility of _thumbnailer being null.
My conclusion is this is bug which we just thankfully haven't triggered yet.
___
*[src/BloomExe/web/WebSocketProgress.cs, line 112 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892#-MrT0cFeDIsoKogWqHcp:-MrT0cFeDIsoKogWqHcq:buichc7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c6e1b7cb0c4b10bdae8267a6e32ef1697efd0be/src/BloomExe/web/WebSocketProgress.cs#L112)):*
> ```Smalltalk
> 
> 		[Obsolete("Instead, use normal messages with an kind=Error")]
> 		public virtual void ErrorWithoutLocalizing(string message)
> ```

No more references! :)
___
*[src/BloomExe/web/WebSocketProgress.cs, line 118 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892#-MrT-x1A2m9Re8FaRfcm:-MrT-x1A2m9Re8FaRfcn:bl2xfux) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f42b21d3c7240dfa49f2672cfe29f8fb123af581/src/BloomExe/web/WebSocketProgress.cs#L118)):*
> ```Smalltalk
> 			MessageWithoutLocalizing(localizedMessage, ProgressKind.Error);
> 
> 			// NOTE: Not sure what to do about deprecating this function.
> ```

Appreciate input about this. There are 2 warnings that I did not touch because of this.
___
*[src/BloomExe/web/controllers/SignLanguageApi.cs, line 34 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892#-MrT0GRG1BAGUB-6Zu0r:-MrT0GRG1BAGUB-6Zu0s:bsx5nii) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c6e1b7cb0c4b10bdae8267a6e32ef1697efd0be/src/BloomExe/web/controllers/SignLanguageApi.cs#L34)):*
> ```Smalltalk
> 		private readonly BookSelection _bookSelection;
> 		private readonly PageSelection _pageSelection;
> 		private bool _doingEditOutsideBloom;
> ```

The function that read this value was removed in https://github.com/BloomBooks/BloomDesktop/commit/d6ae0353fdb19f78bf4e4d6db363c32de7c32a29, three years ago.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 28 of 28 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892)* status: all files reviewed, 12 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomExe/web/RequestInfo.cs, line 249 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892#-MrTkoLn5xsXjuww0rCS:-MrTkoLn5xsXjuww0rCT:b-pzcr4z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4c23dfdc3c677ac6eaab1fd47434264fcea1d3f/src/BloomExe/web/RequestInfo.cs#L249)):*
> ```Smalltalk
> #endif
> 			if (bypassCache)
> 				return false;
> ```

I'm curious...
I don't think it matters, but does this now produce a compiler warning when DEBUG is false? Something like "conditional is always false"?
___
*[src/BloomExe/web/WebSocketProgress.cs, line 118 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892#-MrT-x1A2m9Re8FaRfcm:-MrTqghzAgGRM4dhI37w:b3vylkl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f42b21d3c7240dfa49f2672cfe29f8fb123af581/src/BloomExe/web/WebSocketProgress.cs#L118)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Appreciate input about this. There are 2 warnings that I did not touch because of this.
</blockquote></details>

It seems that the purpose here was to make sure that after we logged the localized message elsewhere, we should be sure to include the unlocalized message to make sure we can read it.
But I'm not seeing that we log the localized message anywhere.

Options:
1. (Re)instate logging for errors in Message().
2. Log errors at the callers.
3. Stop logging errors.
4. ?

I would lean toward 3 unless the callers seem like particularly important places to log, in which case go with 2.
___
*[src/BloomExe/web/WebSocketProgress.cs, line 195 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892#-MrTrgXw-aAZChCzKHYc:-MrTrgXw-aAZChCzKHYd:b-b0a9f6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4c23dfdc3c677ac6eaab1fd47434264fcea1d3f/src/BloomExe/web/WebSocketProgress.cs#L195)):*
> ```Smalltalk
> 		public void Exception(Exception exception)
> 		{
> 			// ENHANCE: Maybe we should just output a single message that has exception.ToString() instead? It's usually the most informative method/property...
> ```

You sound more knowledgeable on this than me. I'm fine with switching if you think it is better.



_Code quote:_
```Smalltalk
// ENHANCE: Maybe we should just output a single message that has exception.ToString() instead? It's usually the most informative method/property...
```
___
*[src/BloomTests/ElementProxyTests.cs, line 66 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892#-MrTlvZY6iXBxBj_HHqv:-MrTlvZY6iXBxBj_HHqw:b-xgnczu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4c23dfdc3c677ac6eaab1fd47434264fcea1d3f/src/BloomTests/ElementProxyTests.cs#L66)):*
> ```Smalltalk
> 		}
> 
> 		// Disable warning for "Comparison made to same variable; did you mean to compare something else?
> ```

Missing trailing quote mark



_Code quote:_
```Smalltalk
"Comparison made to same variable; did you mean to compare something else?
```
___
*[src/BloomTests/ElementProxyTests.cs, line 101 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892#-MrTlyxjA0jK6R8o8c62:-MrTlyxjA0jK6R8o8c63:biw4ysz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4c23dfdc3c677ac6eaab1fd47434264fcea1d3f/src/BloomTests/ElementProxyTests.cs#L101)):*
> ```Smalltalk
> 		{
> 			var elementProxy = MakeElement("<div id='foo'/>");
> 			#pragma warning disable CS0253
> ```

Your other comment above detailing the warning we are disabling was very helpful. Let's add that here.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892)* status: 31 of 34 files reviewed, 11 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/web/RequestInfo.cs, line 249 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892#-MrTkoLn5xsXjuww0rCS:-MrU0xtQCxWCNQaQKZG_:bqyo7sf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4c23dfdc3c677ac6eaab1fd47434264fcea1d3f/src/BloomExe/web/RequestInfo.cs#L249)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm curious...
I don't think it matters, but does this now produce a compiler warning when DEBUG is false? Something like "conditional is always false"?
</blockquote></details>

Good question. Turns out, no it doesn't complain about it.
___
*[src/BloomExe/web/WebSocketProgress.cs, line 118 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892#-MrT-x1A2m9Re8FaRfcm:-MrU3kJo75xwUsn84YQV:brknvga) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f42b21d3c7240dfa49f2672cfe29f8fb123af581/src/BloomExe/web/WebSocketProgress.cs#L118)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

It seems that the purpose here was to make sure that after we logged the localized message elsewhere, we should be sure to include the unlocalized message to make sure we can read it.
But I'm not seeing that we log the localized message anywhere.

Options:
1. (Re)instate logging for errors in Message().
2. Log errors at the callers.
3. Stop logging errors.
4. ?

I would lean toward 3 unless the callers seem like particularly important places to log, in which case go with 2.
</blockquote></details>

I think for an unexception, the unlocalized message is actually the preferable one to have in the log than the localized one.

Well anyway, i guess the current callers already log the message anyway, so we can go with (3) and now we won't log it twice. Yay.
___
*[src/BloomExe/web/WebSocketProgress.cs, line 195 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892#-MrTrgXw-aAZChCzKHYc:-MrU25NECDj2KS5hRMts:bwsdd7u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4c23dfdc3c677ac6eaab1fd47434264fcea1d3f/src/BloomExe/web/WebSocketProgress.cs#L195)):*
Some answers here suggested using Message if you were going to show it to an end user, and ToString() if it's intended to go in a log/etc intended for developers to read.
https://stackoverflow.com/questions/2176707/exception-message-vs-exception-tostring

Well, this looks to me like it might get shown to an end user...
But since it has a stack trace, it also looks like it's intended for developers to read.
>.<

I guess I'll just change to ToString(), I think that's better than concatenating Message + StackTrace.
___
*[src/BloomTests/ElementProxyTests.cs, line 66 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892#-MrTlvZY6iXBxBj_HHqv:-MrU2pm1-0bod2Y7CpXd:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4c23dfdc3c677ac6eaab1fd47434264fcea1d3f/src/BloomTests/ElementProxyTests.cs#L66)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Missing trailing quote mark
</blockquote></details>

Done.
___
*[src/BloomTests/ElementProxyTests.cs, line 101 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892#-MrTlyxjA0jK6R8o8c62:-MrU39Bm8aXrCprd3WgZ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4c23dfdc3c677ac6eaab1fd47434264fcea1d3f/src/BloomTests/ElementProxyTests.cs#L101)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Your other comment above detailing the warning we are disabling was very helpful. Let's add that here.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892)* status: all files reviewed, 7 unresolved discussions (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4892)* status: all files reviewed, 7 unresolved discussions (waiting on @andrew-polk)

**Pull request merged**
