### PR TITLE
Fix problem with odd characters in book names (BL-5037)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
Apparently some processing have moved from javascript to C#.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1866)

### CODE REVIEW

**Comment by hatton** [comment]
Hate to do this to you, but would you be able to move the logic here into UrlPathString? So you'd probably add a new "CreateFrom____String()" method. Then the caller her would have to create one using that, and also explicity declare what kind it wants to get out. We've found that by making code use this class, it gets easier to read and harder to break because everything becomes explicit.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1866#-:-Kutg9FELI3gIMmj4KoR:b-kqb4l2)*

**Comment by StephenMcConnel** [comment]
Okay.  I've done that.  I encountered a failing test that required fixing a test class after changing the logic to use UrlPathString.  I also fixed an inconsisency in UrlPathString that was causing me trouble with my sample book name.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1866#-:-KuumWiNCPJRsE_5mc1n:b2rkagd)*

**Comment by hatton** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/UrlPathString.cs, line 81 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1866#-KuvJtKjV7xcD9KkRlwl:-KuvJtKksZl1gj3bZ5-E:b-ae4n0s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1c6a613ef657a77de97b6a60f527e939d4c69fde/src/BloomExe/UrlPathString.cs#L81)):*
> ```Smalltalk
> 		/// </summary>
> 		/// <value>The URL encoded for http path.</value>
> 		public string UrlEncodedForHttpPath
> ```

The way this class works is that we decouple the input encoding from the output encoding. To accomplish that, we have multiple factory methods, each useful for a particular incoming encoding. We then have several ouput methods, to get the output encoding you want.

This instead appears to do it backwards, so that this output method assumes a particular *input*.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1866)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/UrlPathString.cs, line 81 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1866#-KuvJtKjV7xcD9KkRlwl:-KuvNCcw6seeNkR38wpS:b-9y3ac4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1c6a613ef657a77de97b6a60f527e939d4c69fde/src/BloomExe/UrlPathString.cs#L81)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

The way this class works is that we decouple the input encoding from the output encoding. To accomplish that, we have multiple factory methods, each useful for a particular incoming encoding. We then have several ouput methods, to get the output encoding you want.

This instead appears to do it backwards, so that this output method assumes a particular *input*.
</blockquote></details>

Perhaps this property could be commented or written more clearly.  It's producing a particular output from a normal unencoded (or encoded) input.  It's similar to UrlEncoded, but with slashes and colons not encoded so that the output is more easily human (and program) readable.   The implementation uses the output of UrlEncoded as a starting point to keep things simple.  I suppose that I could have duplicated the code of UrlEncoded instead to show that it really does start with the value of _notEncoded for producing the output.

If we use UrlEncoded instead in the Bloom server code, the program would have to decode something like http%3a%2f%2flocalhost%3a8089%2fBloom%2f%2f instead of http://localhost:8089/Bloom// to strip off the leading cruft to get to the file path (which would also need to have all the %2f characters converted to get a real pathname).

Note that for Book names containing / or :, those characters would already be changed to spaces in the filename since they're invalid for filenames as such.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1866)*

**Pull request merged**
