### PR TITLE
BL-11061 Extract "content" into its own project

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5064)

### CODE REVIEW

**Comment by andrew-polk** [comment]
The added .css, .html, and .js files seem like they shouldn't be added.

**Comment by hatton** [comment]
Thanks. Found 12 files that looked to be based on source files:

image

**Comment by hatton** [comment]
Done, thx.

**Comment by hatton** [comment]
thanks

**Pull request merged**
