### PR TITLE
Cherry-pick changes that will make JS tests pass

### PR DESCRIPTION
**Pull request by ermshiperete**
On master we fixed the JS tests so that they greenbar. These changes are still missing from the Version3.0 branch so that the pre-merge builds of Version3.0 builds will always report as unstable.

### CODE REVIEW

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/263/
Test FAILed.

**Comment by ermshiperete** [comment]
retest this please

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-Version3.0-debug/1/
Test FAILed.

**Comment by ermshiperete** [comment]
retest this please

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-Version3.0-debug/2/
Test FAILed.

**Comment by ermshiperete** [comment]
retest this please

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-Version3.0-debug/3/
Test FAILed.

**Comment by ermshiperete** [comment]
retest this please

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-Version3.0-debug/4/
Test PASSed.

**Comment by JohnThomson** [comment]
I haven't reviewed these in great detail, but since I understand we've already approved them for master and they only affect unit tests it seems safe to merge.

**Pull request merged**
