### PR TITLE
BL-13326 move custom css messages to Content Pages tab in book settings

### PR DESCRIPTION
**Pull request by nabalone**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6441)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6441)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)

___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 538 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6441#-NwCAmnHBMbryhMRZV4N:-NwCAmnHBMbryhMRZV4O:b-ax4gad) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6cd2417005f79d5404de7e4e09e0eb0e65ffff00/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L538)):*
> ```XML
>                                 />
>                             </ConfigrSubgroup>
>                             {/* <ConfigrSubgroup
> ```

I dont' think we want to move these commented out ones as they seem to apply to the cover (or at least xmatter).

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6441)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 538 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6441#-NwCAmnHBMbryhMRZV4N:-NwCCIvJ4XEIXA9rYh38:b7d6298) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6cd2417005f79d5404de7e4e09e0eb0e65ffff00/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L538)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I dont' think we want to move these commented out ones as they seem to apply to the cover (or at least xmatter).
</blockquote></details>

I actually did not move these, they are still in the Cover tab, as you can see in the green "added" chunk above. The diff is kind of crazy. I essentially switched the order of two blocks of code (one with all the warnings, and one which included the end of the Cover tab and the start of the Content Pages tab) and it chose the wrong one to show as "moved" (e.g. it thinks I moved `<ConfigrGroup label={contentPagesLabel} level={1}>` below). I have highlighted the chunk that I did move here: https://github.com/BloomBooks/BloomDesktop/blob/0a0dbc26212d3104ab694a2c5afb25b96aa24503/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L443-L575

**Comment by nabalone** [comment]
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 360 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6441#-NwCEL5NBdIGSRrmvtl0:-NwCEL5NBdIGSRrmvtl1:b-e4mhn6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0a0dbc26212d3104ab694a2c5afb25b96aa24503/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L360)):*
> ```XML
>                     >
>                         <ConfigrGroup label={coverLabel} level={1}>
>                             {
> ```

This is where the custom css messages used to be. Everything it thinks I "added" below was always here in the coverLabel tab element, it just used to be underneath the custom css messages

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6441)* status: all files reviewed, 1 unresolved discussion

___
*[`src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx` line 538 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6441#-NwCAmnHBMbryhMRZV4N:-NwG0msZAgjbpWJhcVe-:bagwfvr) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6cd2417005f79d5404de7e4e09e0eb0e65ffff00/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L538)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

I actually did not move these, they are still in the Cover tab, as you can see in the green "added" chunk above. The diff is kind of crazy. I essentially switched the order of two blocks of code (one with all the warnings, and one which included the end of the Cover tab and the start of the Content Pages tab) and it chose the wrong one to show as "moved" (e.g. it thinks I moved `<ConfigrGroup label={contentPagesLabel} level={1}>` below). I have highlighted the chunk that I did move here: https://github.com/BloomBooks/BloomDesktop/blob/0a0dbc26212d3104ab694a2c5afb25b96aa24503/src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx#L443-L575
</blockquote></details>

Got it. Sorry.

**Review by andrew-polk — APPROVED** [review]
> Dismissed @nabalone from a discussion.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6441)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nabalone)

**Pull request merged**
