### PR TITLE
BL-5087 follow-up

### PR DESCRIPTION
**Pull request by gmartin7**
2 commits:
- 1st is simple refactoring and cleanup
- 2nd extracts business logic to a model class and reuses it
   for the bulk upload process

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1907)

### CODE REVIEW

**Comment by andrew-polk** [comment]
I added a couple notes.
Overall, looks okay, though it is hard to see everything (always true of refactoring).
I would like @john_thomson to take a look, also.

It might be too late now since this change is a follow-on to code which is already merged. I wish we would have explored the option of adding this feature to 4.1 instead of 4.0. This seems to be a big change right before beta. But then again, it isn't beta yet...

---

Reviewed 4 of 4 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, line 41 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-Kx9fMGYkjTwoq2sbrfV:-Kx9fMGYkjTwoq2sbrfW:bg5fuiq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ff39eadcc84246428f80fd31354e39a8168b4201/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L41)):*
> (CreativeCommonsLicense) _license

Shouldn't this be 
_license as CreativeCommonsLicense
?

---

*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 582 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-Kx9erNXgfKwouUbWUIE:-Kx9erNXgfKwouUbWUIF:b-gbfooo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ff39eadcc84246428f80fd31354e39a8168b4201/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L582)):*
> ```Smalltalk
> 		public void UploadFolder(string folder, ApplicationContainer container, bool excludeAudio = false)
> 		{
> 			if (BloomLibraryPublishModel.BloomVersionTooOldToUpload(this))
> ```

Confused. We pass in ourself (BookTransfer) so that we can call a one-line method on ourself from another class.
And this is the only call to that method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-:-Kx9ib9SdDjgimI0AZU8:b-d3g1uq)*

**Comment by gmartin7** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, line 41 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-Kx9fMGYkjTwoq2sbrfV:-Kx9sCw2Blw8t5vnMp_p:b3dkd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ff39eadcc84246428f80fd31354e39a8168b4201/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L41)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> (CreativeCommonsLicense) _license

Shouldn't this be 
_license as CreativeCommonsLicense
?
</blockquote></details>

Done. Probably safer.

---

*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 582 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-Kx9erNXgfKwouUbWUIE:-Kx9rEBvq-b1cKpINYyz:b-fyivpx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ff39eadcc84246428f80fd31354e39a8168b4201/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L582)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Confused. We pass in ourself (BookTransfer) so that we can call a one-line method on ourself from another class.
And this is the only call to that method.
</blockquote></details>

That's why we do reviews! :) I was looking around for the BookTransfer instance to feed to my method and finally realized I was IN that class... and then never looked back at the big picture to realize I had the underlying method at hand already! <facepalm>

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907)*

**Comment by JohnThomson** [comment]
I don't see anywhere the change to use the new model logic in bulk upload, which I thought was the main idea...

---

Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxJ6hN1uG0XN5OcZt4z:-KxJ6hN27V0M2ZTKbKu0:beubyxr) (no related file):*
Does having a model like this make anything unit testable that wasn't before? e.g., if you mock the BookTransfer and Book objects I think a lot of the new class could be tested. (Then again, maybe we don't have time for that right now...)

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishControl.cs, line 54 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxIlRTm80mba5lv-dMg:-KxIlRTm80mba5lv-dMh:b-xx5h2h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c0d88515cf0c0211df3924f86a4dde054cc253a/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishControl.cs#L54)):*
> ```Smalltalk
> 				_model.LogIn();
> 			}
> 			catch (Exception e)
> ```

I suppose this is what we used to do elsewhere? No reasonable way we can restrict to e.g. only network-related exceptions?

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishControl.cs, line 59 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxJ2eit0xt_Nh-2rTp1:-KxJ2eit0xt_Nh-2rTp2:b-ktpcxy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c0d88515cf0c0211df3924f86a4dde054cc253a/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishControl.cs#L59)):*
> ```Smalltalk
> 			}
> 
> 			switch (_model.LicenseType)
> ```

What would you think about moving this logic to the model, so here we would just have _usingCcControls = _model.UseCcControls etc? Feel free to respond "too much trouble for too little advantage"; what's going on here is definitely UI stuff; but generally the idea of having a model is to put as much of the complexity there as possible and keep the UI code very simple. (Of course in this case the main idea of having the model, I believe, is to isolate the logic to be shared by bulk upload...)

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishControl.cs, line 222 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxJ4J97x6fdEUdfyCl4:-KxJ4J97x6fdEUdfyCl5:bigv67l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c0d88515cf0c0211df3924f86a4dde054cc253a/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishControl.cs#L222)):*
> ```Smalltalk
> 		private void UpdateDisplay()
> 		{
> 			_uploadButton.Enabled = _model.OkToPublish && _model.LoggedIn && _okToUpload;
> ```

The relationship between _model.OkToPublish and _okToUpload is confusing. At one point _okToUpload is set from _model.OkToPublish, but now we have to check both. See my suggestion below about getting all the logic for enabling this button into one method. If that isn't possible, can any of these be better named?

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishControl.cs, line 291 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxInpCZx-NWrT-AN5EL:-KxInpCZx-NWrT-AN5EM:b-d7znpp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c0d88515cf0c0211df3924f86a4dde054cc253a/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishControl.cs#L291)):*
> ```Smalltalk
> 		}
> 
> 		private void SetUpstreamState(bool enable)
> ```

I don't get this name at all. What is the "upstream state"?

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, line 11 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxIog0kWyqh22VRxHDB:-KxIog0kWyqh22VRxHDC:bddse4e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c0d88515cf0c0211df3924f86a4dde054cc253a/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L11)):*
> ```Smalltalk
> namespace Bloom.Publish.BloomLibrary
> {
> 	public class BloomLibraryPublishModel
> ```

Needs a class comment.

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, line 105 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxJ-QYq2RpUP30oMnUu:-KxJ-QYq2RpUP30oMnUv:bkeyy3i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c0d88515cf0c0211df3924f86a4dde054cc253a/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L105)):*
> ```Smalltalk
> 		/// OkToUploadWithNoLanguages OR the user has checked a language checkbox.
> 		/// </summary>
> 		internal bool OkToPublish =>
> ```

Seems we need to improve the name. Maybe OkToPublishIfLanguageRulesPass? Or OkToPublishCore? Maybe you can think of something shorter and/or clearer, but it would be good to have some hint that this isn't the complete story of whether it can be published.
Should we also hint (at least in the comment) that it doesn't include the logged-in check? And why is that?
Another idea: it's rather weird to have a model, which is supposed to be where the business logic goes, but it only has about 2/3 of the logic for knowing whether we can go ahead and upload. What if you made the selected-languages checkboxes update some state in the model, and if necessary make the model aware of whether we're doing one book or a bulk upload, and then OkToPublish could actually give a complete answer?
For example it would be nice to be able to write something like OkToUploadOneBook => OkToPublishCore && LoggedIn && (SomeLanguageChecked ||OkToUploadWithNoLanguages) and maybe a similar method for OkToBulkUploadBook(Book book)...

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, line 118 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxJ0-wYuTZR72Vsr3G3:-KxJ0-wYuTZR72Vsr3G4:b-y5op6q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c0d88515cf0c0211df3924f86a4dde054cc253a/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L118)):*
> ```Smalltalk
> 		internal string WebUserId { get; }
> 
> 		internal bool OkToUploadWithNoLanguages => Book.BookInfo.IsSuitableForMakingShells;
> ```

According to the comment above, this might actually be "OkToUploadOneBookWithNoLanguages", that is, it doesn't apply to collections? Does that mean you can't upload a template as part of a bulk upload?

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, line 121 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxJ0KuLKr5pAZDakAWz:-KxJ0KuLKr5pAZDakAX-:by867qv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c0d88515cf0c0211df3924f86a4dde054cc253a/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L121)):*
> ```Smalltalk
> 
> 		/// <summary>
> 		/// Need a property for when we don't have a BookTransfer object available (single book upload).
> ```

Puzzling comment. Was this supposed to be a "to do" and if so did it get done? The code here seems to only be usable when we DO have a BookTransfer object.
Also, if we sometimes don't have a BookTransfer object, a lot of other methods won't work. And it doesn't really say what the property means...the name is pretty clear so maybe it doesn't even need a comment?

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, line 154 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxJ0wqp3OnYsfLqBMU8:-KxJ0wqp3OnYsfLqBMU9:b-sf1ttr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c0d88515cf0c0211df3924f86a4dde054cc253a/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L154)):*
> ```Smalltalk
> 				{
> 					// A null license and no copyright indicates they never even opened the ClearShare dialog to choose a license.
> 					return LicenseState.NeverOpened;
> ```

Have you verified this? Might be obsolete. I thought we assigned a CC license to new books by default. And I would be surprised if opening the dialog changed anything if you use Cancel. Maybe LicenseState.NeverSet? (Or other suggestions might make LicenseState obsolete.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-:-KxJ3pwz7ba2lqQjuuH4:brlv6eo)*

**Comment by andrew-polk** [comment]
@gmartin7,
Feel free to respond to any comments with "this is the way we did it before the refactor." I don't want to introduce change to existing code for improvement sake unless it is *very* simple and straightforward.

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-:-KxJ8p_ctWKHzhBpkkRr:b9yhepr)*

**Comment by gmartin7** [comment]
The new model logic is used in BookTransfer.UploadInternal around line 743 where it says:
if (languagesToUpload.Any() && blPublishModel.OkToPublish)

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-:-KxJA4VIrMcGCEPUHjjO:b-fu3372)*

**Comment by gmartin7** [comment]
Review status: 6 of 9 files reviewed at latest revision, 10 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxJ6hN1uG0XN5OcZt4z:-KxJetdPYqeJ8l33v5_V:b-g1hthx) (no related file):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Does having a model like this make anything unit testable that wasn't before? e.g., if you mock the BookTransfer and Book objects I think a lot of the new class could be tested. (Then again, maybe we don't have time for that right now...)
</blockquote></details>

Probably does... hopefully we'll have time to do that in any future work in this area.

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishControl.cs, line 54 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxIlRTm80mba5lv-dMg:-KxJET6QfbgRor-4OdjE:bh0j94q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c0d88515cf0c0211df3924f86a4dde054cc253a/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishControl.cs#L54)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I suppose this is what we used to do elsewhere? No reasonable way we can restrict to e.g. only network-related exceptions?
</blockquote></details>

Yes, I just moved this up from below. Pre-existing code.

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishControl.cs, line 59 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxJ2eit0xt_Nh-2rTp1:-KxJf6dnOZ2355E_Zdv-:bn7bzaa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c0d88515cf0c0211df3924f86a4dde054cc253a/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishControl.cs#L59)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

What would you think about moving this logic to the model, so here we would just have _usingCcControls = _model.UseCcControls etc? Feel free to respond "too much trouble for too little advantage"; what's going on here is definitely UI stuff; but generally the idea of having a model is to put as much of the complexity there as possible and keep the UI code very simple. (Of course in this case the main idea of having the model, I believe, is to isolate the logic to be shared by bulk upload...)
</blockquote></details>

Yeah. I worked hard to separate the UI stuff from the business logic. There's already stuff in the model that's not strictly needed there, but fit better as business logic. Now the Control class doesn't even know about the BookTransfer object. I'd rather leave it.

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishControl.cs, line 222 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxJ4J97x6fdEUdfyCl4:-KxJfyuuLjahyQSFslY-:b-wwym4u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c0d88515cf0c0211df3924f86a4dde054cc253a/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishControl.cs#L222)):*
> The relationship between _model.OkToPublish and _okToUpload is confusing.
Amen!
At one point I had model's OkToPublish also based on LoggedIn, but that messed up other stuff.
I've changed the model's property to MetadataIsReadyToPublish to reflect that the metadata is complete enough to publish.
The control's upload button is also based on whether the user is logged in and the right language checkboxes are checked or not.
Getting it so the right messages showed up at the right time for the right situation was very tricky.

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishControl.cs, line 291 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxInpCZx-NWrT-AN5EL:-KxJef8yCsTDWPVmuCwX:b-j4yrml) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c0d88515cf0c0211df3924f86a4dde054cc253a/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishControl.cs#L291)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't get this name at all. What is the "upstream state"?
</blockquote></details>

Changed to SetParentControlsState

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, line 11 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxIog0kWyqh22VRxHDB:-KxJiqah77a9roaeoTeG:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c0d88515cf0c0211df3924f86a4dde054cc253a/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L11)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Needs a class comment.
</blockquote></details>

Done.

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, line 105 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxJ-QYq2RpUP30oMnUu:-KxJoUCnxW_7147QcKJO:b-vos1o9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c0d88515cf0c0211df3924f86a4dde054cc253a/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L105)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Seems we need to improve the name. Maybe OkToPublishIfLanguageRulesPass? Or OkToPublishCore? Maybe you can think of something shorter and/or clearer, but it would be good to have some hint that this isn't the complete story of whether it can be published.
Should we also hint (at least in the comment) that it doesn't include the logged-in check? And why is that?
Another idea: it's rather weird to have a model, which is supposed to be where the business logic goes, but it only has about 2/3 of the logic for knowing whether we can go ahead and upload. What if you made the selected-languages checkboxes update some state in the model, and if necessary make the model aware of whether we're doing one book or a bulk upload, and then OkToPublish could actually give a complete answer?
For example it would be nice to be able to write something like OkToUploadOneBook => OkToPublishCore && LoggedIn && (SomeLanguageChecked ||OkToUploadWithNoLanguages) and maybe a similar method for OkToBulkUploadBook(Book book)...
</blockquote></details>

Name: see earlier comment.
We can write OkToUploadSingleBook and OkToBulkUploadThisBook and the model doesn't even need to know which one we're calling, but the classes that use the model will still need to know which languages to upload anyway. I tried to create the OkToBulkUpload option, but it didn't really simplify anything. :(

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, line 118 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxJ0-wYuTZR72Vsr3G3:-KxJjmjtP1oTfh_H8whV:b-zguem1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c0d88515cf0c0211df3924f86a4dde054cc253a/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L118)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

According to the comment above, this might actually be "OkToUploadOneBookWithNoLanguages", that is, it doesn't apply to collections? Does that mean you can't upload a template as part of a bulk upload?
</blockquote></details>

Bulk upload just says "If the model is okay with the metadata, and this book has any language that is 'complete', then upload is okay". I'm pretty sure that would mean a template would make it okay.

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, line 121 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxJ0KuLKr5pAZDakAWz:-KxJk9BI5i6dccsa4Rn9:bfpqd6b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c0d88515cf0c0211df3924f86a4dde054cc253a/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L121)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Puzzling comment. Was this supposed to be a "to do" and if so did it get done? The code here seems to only be usable when we DO have a BookTransfer object.
Also, if we sometimes don't have a BookTransfer object, a lot of other methods won't work. And it doesn't really say what the property means...the name is pretty clear so maybe it doesn't even need a comment?
</blockquote></details>

Comment was left over from when there was also a static version of this property for the bulk upload with a similar comment. That went away and now so has the comment here. (The idea was: we have two properties, we need this one in this case and this other one in this case.)

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, line 154 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxJ0wqp3OnYsfLqBMU8:-KxJnX0frLJqgyO1BhZE:b-1yho38) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c0d88515cf0c0211df3924f86a4dde054cc253a/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L154)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Have you verified this? Might be obsolete. I thought we assigned a CC license to new books by default. And I would be surprised if opening the dialog changed anything if you use Cancel. Maybe LicenseState.NeverSet? (Or other suggestions might make LicenseState obsolete.)
</blockquote></details>

You're right. We can't ever get into that state in Bloom. Removed this if section and the model's LicenseIsOkay property, since that was only false in this (non-possible) case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907)*

**Comment by JohnThomson** [comment]
I meant that I was expecting to see a BloomLibraryPublishModel created and used somewhere in some bulk upload code. But maybe that's another PR? I don't see any UploadInteral in this one.

---

Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishControl.cs, line 222 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxJ4J97x6fdEUdfyCl4:-KxKVc5lfc48BV9AI6fF:b28qtbv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c0d88515cf0c0211df3924f86a4dde054cc253a/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishControl.cs#L222)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

> The relationship between _model.OkToPublish and _okToUpload is confusing.
Amen!
At one point I had model's OkToPublish also based on LoggedIn, but that messed up other stuff.
I've changed the model's property to MetadataIsReadyToPublish to reflect that the metadata is complete enough to publish.
The control's upload button is also based on whether the user is logged in and the right language checkboxes are checked or not.
Getting it so the right messages showed up at the right time for the right situation was very tricky.
</blockquote></details>

Seems reasonable for now at least.

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, line 118 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxJ0-wYuTZR72Vsr3G3:-KxKUawDxQ6P5SzacwNq:bukychd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c0d88515cf0c0211df3924f86a4dde054cc253a/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L118)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Bulk upload just says "If the model is okay with the metadata, and this book has any language that is 'complete', then upload is okay". I'm pretty sure that would mean a template would make it okay.
</blockquote></details>

A template will very typically have no language that is 'complete'. The whole idea is empty pages. Very likely it has no text on any content page in any language.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-:-KxKV68bmh9jKDNk-ErF:bsthmth)*

**Comment by gmartin7** [comment]
? I thought that was what I was pointing you to. Are you opening the revision scope of the diff enough? UploadCommand.Handle() calls BookTransfer.UploadFolder(), which (through BackgroundUpload) calls BookTransfer.UploadInternal(). This PR version of UploadInternal has code that does just what you describe on lines 738 and 744

---

Review status: 6 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, line 118 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxJ0-wYuTZR72Vsr3G3:-KxO_QwgpsHwj-u0RcqW:b-x3d57m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6c0d88515cf0c0211df3924f86a4dde054cc253a/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L118)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

A template will very typically have no language that is 'complete'. The whole idea is empty pages. Very likely it has no text on any content page in any language.
</blockquote></details>

OK, thx. I guess I wasn't quite recalling the way templates work. I've added a check for model.OktoUploadWithNoLanguages to the bulk upload process that will allow templates to be uploaded.

---

*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 738 at r4](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxOZpfqKm0IGlORwGCe:-KxOZpfr0qSGcbIzPr1J:bdfr1ia) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e08921a676850b310b0c679141a505f05bb2beb3/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L738)):*
> ```Smalltalk
> 				publishModel.PageLayout = book.GetLayout();
> 				var view = new PublishView(publishModel, new SelectedTabChangedEvent(), new LocalizationChangedEvent(), this, null, null, null);
> 				var blPublishModel = new BloomLibraryPublishModel(this, book);
> ```

Creates the model.

---

*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 744 at r4](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-KxOZs7ZlSTvOovvN1r5:-KxOZs7ZlSTvOovvN1r6:b-6t4q4y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e08921a676850b310b0c679141a505f05bb2beb3/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L744)):*
> ```Smalltalk
> 				var langDict = book.AllLanguages;
> 				var languagesToUpload = langDict.Keys.Where(l => langDict[l]).ToArray();
> 				if (languagesToUpload.Any() && blPublishModel.MetadataIsReadyToPublish)
> ```

Uses the model. If 'languagesToUpload' wasn't used again a few lines farther down, I would have moved the languages stuff here to the model too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-:-KxOXgQ8JJ89VoQeWF9L:b-lqnzt9)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Review status: 6 of 9 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1907#-:-KxOuIpWoIeovEaQWsEC:bnfp4nl)*

**Pull request merged**
