### PR TITLE
Log memory use and warn user when low

### PR DESCRIPTION
**Pull request by JohnThomson**

### CODE REVIEW

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-master-debug/411/
Test FAILed.

**Comment by JohnThomson** [comment]
retest this please

**Comment by JohnThomson** [comment]
retest this please

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-master-debug/417/
Test PASSed.

**Pull request merged**
