### PR TITLE
BL-3100 Manage asnc init of Synphony properly

### PR DESCRIPTION
**Pull request by JohnThomson**
Initialization of Synphony returns a promise so we don't
do remaining init until it is ready. As a further
precaution, the model's synphony variable is not
initialized until the object is properly initialized.

---

This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/981)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/decodableReader.ts, line 7 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981#-KDUsWIxMthj_GBGuvL0:-KDUsWIxMthj_GBGuvL1:-289545555) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/252e8bf6948e5bc7a85e9fb31ff0a6d0b5016485/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/decodableReader.ts#L7)):*
I think these can be simplified by dropping the explicit result, and just returning the promise returned by then()

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981)*

**Comment by JohnThomson** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/decodableReader.ts, line 7 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981#-KDUsWIxMthj_GBGuvL0:-KDV1R8_E50jDc9VdIpP:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/252e8bf6948e5bc7a85e9fb31ff0a6d0b5016485/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/decodableReader.ts#L7)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981)*

**Comment by hatton** [comment]
Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 193 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981#-KDZAC6rbVpfWVNzUKOr:-KDZAC6soTnoFR_Abh1j:1913811399) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e7ce51e9dbbb7977b9caebd33a89ad994df6dd/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L193)):*
Shall we adopt the convention of adding "Async" to the end of any asynchronous method? If we needed to distinguish between different kinds of async (e.g. returning a promise vs. just not finishing immediately, we could also use "begin___".)

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/decodableReader.ts, line 7 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981#-KDUsWIxMthj_GBGuvL0:-KDZAgjkkYoJEbevLVj7:-1161723599) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/252e8bf6948e5bc7a85e9fb31ff0a6d0b5016485/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/decodableReader.ts#L7)):*
initializeDecodableReaderToo() is another ___Async  candidate.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 114 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981#-KDZBnDGt2jST1aZ3MUa:-KDZBnDGt2jST1aZ3MUb:-949314089) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e7ce51e9dbbb7977b9caebd33a89ad994df6dd/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L114)):*
__Async

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 116 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981#-KDZArVF2Bcx6GspVdJZ:-KDZArVF2Bcx6GspVdJ_:-905690013) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e7ce51e9dbbb7977b9caebd33a89ad994df6dd/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L116)):*
loadSynphonySettings is another ___Async  candidate.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 151 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981#-KDZBlmYLX_fTNrxOdBe:-KDZBlmYLX_fTNrxOdBf:-1757771496) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e7ce51e9dbbb7977b9caebd33a89ad994df6dd/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L151)):*
__Async()

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 152 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981#-KDZAzr41SXEj5AnuPDi:-KDZAzr41SXEj5AnuPDj:1900306665) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e7ce51e9dbbb7977b9caebd33a89ad994df6dd/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L152)):*
I'm missing the reason for the explicit result in this one.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 172 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981#-KDZBgq4a5C9to0NA03S:-KDZBgq4a5C9to0NA03T:-1757771496) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e7ce51e9dbbb7977b9caebd33a89ad994df6dd/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L172)):*
__Async()

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981)*

**Comment by hatton** [comment]
Reviewed 1 of 6 files at r1, 1 of 3 files at r2.
Review status: 2 of 6 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981)*

**Comment by JohnThomson** [comment]
Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 193 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981#-KDZAC6rbVpfWVNzUKOr:-KDZLC23P2hclSW4E_ey:1022062383) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e7ce51e9dbbb7977b9caebd33a89ad994df6dd/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L193)):*
I prefer begin, since this isn't async code in the usual threading sense. Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/decodableReader.ts, line 7 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981#-KDUsWIxMthj_GBGuvL0:-KDZLLLg7AIav2qBid7e:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/252e8bf6948e5bc7a85e9fb31ff0a6d0b5016485/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/decodableReader.ts#L7)):*
Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 114 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981#-KDZBnDGt2jST1aZ3MUa:-KDZLLy-v8f416ldRaCH:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e7ce51e9dbbb7977b9caebd33a89ad994df6dd/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L114)):*
Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 116 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981#-KDZArVF2Bcx6GspVdJZ:-KDZLMk-1klTQ3Uk5SfM:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e7ce51e9dbbb7977b9caebd33a89ad994df6dd/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L116)):*
Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 151 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981#-KDZBlmYLX_fTNrxOdBe:-KDZLNHdCWxjpoFnp6aN:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e7ce51e9dbbb7977b9caebd33a89ad994df6dd/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L151)):*
Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 152 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981#-KDZAzr41SXEj5AnuPDi:-KDZKhU_bM_CkNWPB_uk:-1969197975) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e7ce51e9dbbb7977b9caebd33a89ad994df6dd/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L152)):*
None. Fixed.

---

*[src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, line 172 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981#-KDZBgq4a5C9to0NA03S:-KDZLOJNcr2ANAazgREz:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e7ce51e9dbbb7977b9caebd33a89ad994df6dd/src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts#L172)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981)*

**Comment by hatton** [comment]
Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, line 193 \[r2\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981#-KDZAC6rbVpfWVNzUKOr:-KDZUHldHov8ueqArvCa:269611342) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44e7ce51e9dbbb7977b9caebd33a89ad994df6dd/src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts#L193)):*
"begin" is fine, but JS doesn't have threads, and yet ES7 has "async/await". So that "usual threading sense" definition of c# is not appropriate in JS, and we will need adopt async to mean things that are promised based.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/981)*

**Pull request merged**
