### PR TITLE
Reorganize files in Team Collection shared folder (BL-9538)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 79 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196#-MTflZ74CZT4bKgXNZby:-MTflZ758SUU9ggloi8X:bycjsd7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/446b7a84f0691fa0cd9b8a61c5bafc696a034b5f/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L79)):*
> ```Smalltalk
> 			else
> 			{
> 				Directory.CreateDirectory(Path.GetDirectoryName(bookPath));
> ```

It took thinking about the whole method to understand this line as doing something different than "create the directory that is holding the book".  I know, I'm dense at reading code :-)  the comment would be 

`// Make sure the repo directory that holds books exists`

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 63 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196#-MTfmyMUBlAEGgXPhQxF:-MTfmyMUBlAEGgXPhQxG:brn6vfc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/446b7a84f0691fa0cd9b8a61c5bafc696a034b5f/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L63)):*
> ```Smalltalk
> 		{
> 			var bookName = Path.GetFileName(sourceBookFolderPath);
> 			var bookPath = GetPathToBookFileInRepo(bookName);
> ```

Maybe a lack of symmetry here? We have `GetPathToBookFileInRepo()` but not `GetPathToBookFileInLostAndFound()`

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 101 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196#-MTfnjFN0_DZpr0RoJuv:-MTfnjFN0_DZpr0RoJuw:b-b6lxnq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/446b7a84f0691fa0cd9b8a61c5bafc696a034b5f/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L101)):*
> ```Smalltalk
> 		private string GetPathToBookFileInRepo(string bookName)
> 		{
> 			return Path.ChangeExtension(Path.Combine(_sharedFolderPath, "Books", bookName), ".bloom");
> ```

Since we've settled on "repo", can `sharedFolderPath` now become `repoFolderPath` ?
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 162 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196#-MTfo2Ab-shYwwvgXspI:-MTfo2Ab-shYwwvgXspJ:bin1gos) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/446b7a84f0691fa0cd9b8a61c5bafc696a034b5f/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L162)):*
> ```Smalltalk
> 		public override void PutCollectionFile(string pathName)
> 		{
> 			var destFolder = Path.Combine(_sharedFolderPath, "Other Project Files");
> ```

I'm not always a stickler for normalization, but it does seem like these subfolder strings want to be normalized somehow, either with a method `GetProjectFileFolder()` or `GetProjectFilePath()` or `kProjectFileFolder`.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 162 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196#-MTfo2Ab-shYwwvgXspI:-MTfoYFl8KA0fqvrtqkQ:b-q6d9l7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/446b7a84f0691fa0cd9b8a61c5bafc696a034b5f/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L162)):*
Edit

> I'm not always a stickler for normalization, but it does seem like these subfolder strings want to be normalized somehow, either with  `ProjectFileFolder` or `GetProjectFileFolder()` or `GetProjectFilePath(filename)` or `kProjectFileFolder`.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 442 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196#-MTfp-iL5nUrfjL9gMgA:-MTfp-iL5nUrfjL9gMgB:b-lwhm6u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/446b7a84f0691fa0cd9b8a61c5bafc696a034b5f/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L442)):*
> ```Smalltalk
> 		}
> 
> 		public static string SetupMinimumSharedCollectionFiles(string sharedFolder, string localCollectionFolder)
> ```

This is a good example were a change to `repoFolder` would remove some ambiguity. As is, one wonders if `sharedFolder` is the outer folder or the folder where collection files live in the repo.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196)* status: 0 of 5 files reviewed, 9 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 293 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196#-MTfq8J83RA6bQUygQzu:-MTfq8J83RA6bQUygQzv:b-tkncmj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/446b7a84f0691fa0cd9b8a61c5bafc696a034b5f/src/BloomExe/TeamCollection/TeamCollection.cs#L293)):*
> ```Smalltalk
> 		/// </summary>
> 		/// <param name="localCollectionFolder"></param>
> 		public void CopySharedCollectionFilesToLocal(string localCollectionFolder)
> ```

By "Shared" here... do we mean this is some subset of collection files that are shared, whereas other are not? Or do we mean those file in the Repo?  Basically every place I see "Shared" in this code, I end up with an ambiguity. I hope it goes away :-)
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 297 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196#-MTfqSIw4_pRXgHxsBGj:-MTfqSIw4_pRXgHxsBGk:b-paut7u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/446b7a84f0691fa0cd9b8a61c5bafc696a034b5f/src/BloomExe/TeamCollection/TeamCollection.cs#L297)):*
> ```Smalltalk
> 			foreach (var name in CollectionFiles())
> 			{
> 				GetCollectionFile(Path.Combine(localCollectionFolder, name));
> ```

Anything starting with "Get" is, by c# convention, an inexpensive, normally non-mutating change. But here I surmise that it must actually copying files?
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 297 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196#-MTfqd5a9bzwTP6pMFIx:-MTfqd5a9bzwTP6pMFIy:bx78hun) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/446b7a84f0691fa0cd9b8a61c5bafc696a034b5f/src/BloomExe/TeamCollection/TeamCollection.cs#L297)):*
> ```Smalltalk
> 			foreach (var name in CollectionFiles())
> 			{
> 				GetCollectionFile(Path.Combine(localCollectionFolder, name));
> ```

Ideally, the operation would be atomic (in case some files relied on changes to other files), but I suppose that's just too hard to implement.
___
*[src/BloomTests/TeamCollection/FolderTeamCollectionTests.cs, line 389 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196#-MTfp_cZ9O04DIyBK137:-MTfp_cZ9O04DIyBK138:b-1817rn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/446b7a84f0691fa0cd9b8a61c5bafc696a034b5f/src/BloomTests/TeamCollection/FolderTeamCollectionTests.cs#L389)):*
> ```Smalltalk
> 
> 		[Test]
> 		public void CopySharedCollectionFilesToLocal_RetrievesFilesPut()
> ```

Should we test when

* a file already exists, that it gets overwritten?
* a file exists in the target, but has been deleted in the source and so should be removed (or not, if that is the decision)?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196)* status: 0 of 9 files reviewed, 9 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 63 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196#-MTfmyMUBlAEGgXPhQxF:-MTfpDwx3f21iDOmHFw-:bvjaepm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/446b7a84f0691fa0cd9b8a61c5bafc696a034b5f/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L63)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Maybe a lack of symmetry here? We have `GetPathToBookFileInRepo()` but not `GetPathToBookFileInLostAndFound()`
</blockquote></details>

It's not really parallel. One is getting a single, well-defined path (and is used in multiple places). The other is finding a an available path and is only used in this one place. But I can make the method if you like.
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 79 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196#-MTflZ74CZT4bKgXNZby:-MTfnJ5j7XnblfeVVWn0:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/446b7a84f0691fa0cd9b8a61c5bafc696a034b5f/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L79)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

It took thinking about the whole method to understand this line as doing something different than "create the directory that is holding the book".  I know, I'm dense at reading code :-)  the comment would be 

`// Make sure the repo directory that holds books exists`
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 101 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196#-MTfnjFN0_DZpr0RoJuv:-MTfq8pt9VLbzmtIsDOK:bmtbf0p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/446b7a84f0691fa0cd9b8a61c5bafc696a034b5f/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L101)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Since we've settled on "repo", can `sharedFolderPath` now become `repoFolderPath` ?
</blockquote></details>

Done. Though it seems a bit beyond the scope of this PR.
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 162 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196#-MTfo2Ab-shYwwvgXspI:-MTfrNb083qTx4sGloxc:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/446b7a84f0691fa0cd9b8a61c5bafc696a034b5f/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L162)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Edit

> I'm not always a stickler for normalization, but it does seem like these subfolder strings want to be normalized somehow, either with  `ProjectFileFolder` or `GetProjectFileFolder()` or `GetProjectFilePath(filename)` or `kProjectFileFolder`.

</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 442 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196#-MTfp-iL5nUrfjL9gMgA:-MTg07KF9TMh_G10e4OC:b3osxcv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/446b7a84f0691fa0cd9b8a61c5bafc696a034b5f/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L442)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This is a good example were a change to `repoFolder` would remove some ambiguity. As is, one wonders if `sharedFolder` is the outer folder or the folder where collection files live in the repo.
</blockquote></details>

Done. I've done my best to change everywhere we use the word "shared" in the new code that makes sense.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 293 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196#-MTfq8J83RA6bQUygQzu:-MTgCWtcEUooyHK61NMb:b-kngh9g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/446b7a84f0691fa0cd9b8a61c5bafc696a034b5f/src/BloomExe/TeamCollection/TeamCollection.cs#L293)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

By "Shared" here... do we mean this is some subset of collection files that are shared, whereas other are not? Or do we mean those file in the Repo?  Basically every place I see "Shared" in this code, I end up with an ambiguity. I hope it goes away :-)
</blockquote></details>

I think I got them all.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 297 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196#-MTfqSIw4_pRXgHxsBGj:-MTg223i1uJ43xP1Uj_L:b-hw3phh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/446b7a84f0691fa0cd9b8a61c5bafc696a034b5f/src/BloomExe/TeamCollection/TeamCollection.cs#L297)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Anything starting with "Get" is, by c# convention, an inexpensive, normally non-mutating change. But here I surmise that it must actually copying files?
</blockquote></details>

I've renamed anything that is doing file copying. Most are already CopyXFromYToZ, but in a couple of cases that name is taken so I used Fetch.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 297 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196#-MTfqd5a9bzwTP6pMFIx:-MTg2MCT64_VSvNv4VOZ:b-j1j5mp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/446b7a84f0691fa0cd9b8a61c5bafc696a034b5f/src/BloomExe/TeamCollection/TeamCollection.cs#L297)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Ideally, the operation would be atomic (in case some files relied on changes to other files), but I suppose that's just too hard to implement.
</blockquote></details>

I decided to put all the collection-level files in a single zip instead of a folder. Further benefit: TC contains absolutely no .bloomCollection anyone can possibly try to open.
___
*[src/BloomTests/TeamCollection/FolderTeamCollectionTests.cs, line 389 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196#-MTfp_cZ9O04DIyBK137:-MTg3aLzAtzptds-RSj1:b-ngbx4e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/446b7a84f0691fa0cd9b8a61c5bafc696a034b5f/src/BloomTests/TeamCollection/FolderTeamCollectionTests.cs#L389)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Should we test when

* a file already exists, that it gets overwritten?
* a file exists in the target, but has been deleted in the source and so should be removed (or not, if that is the decision)? 


</blockquote></details>

Overwrite: sure. On delete: I'd prefer to tackle this as part of BL-9487. The current code only handles the two most common collection-level files, neither of which is likely to go away.

**Review by hatton — APPROVED** [review]
> Reviewed 2 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 242 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196#-MTgeclY3SWg3SyjK9L3:-MTgeclZ0iGLgVQ6Vo-S:b-9g90et) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1d2e4d10c239b5d6982f582732ce0507e07d2e59/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L242)):*
> ```Smalltalk
> 			_watcher = new FileSystemWatcher();
> 
> 			_watcher.Path = Path.Combine(_repoFolderPath, "Books");
> ```

Another unnormalized subfolder name

**Review by hatton — COMMENTED** [review]
> Reviewed 7 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4196)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Pull request merged**
