### PR TITLE
Spreadsheet Export: Add second header row w/friendly names (BL-10363)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839)* status: 0 of 16 files reviewed, 6 unresolved discussions

___
*[src/BloomExe/CLI/SpreadsheetExportCommand.cs, line 22 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-MpInrTO9AL4FAkaDnOq:-MpInrTO9AL4FAkaDnOr:b-za5sql) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a132e21b2638492ceac710d61c4f67f623efddd2/src/BloomExe/CLI/SpreadsheetExportCommand.cs#L22)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 				string bookFolder = Path.GetDirectoryName(options.BookPath);
> 				string collectionFolder = Directory.GetParent(bookFolder).FullName;
> 				string collectionName = Path.GetDirectoryName(collectionFolder);
> 				string collectionSettingsFile = Path.Combine(collectionFolder, Path.ChangeExtension(collectionName, ".bloomCollection"));
> ```
</details>


Ugh, so much work to get the path to the collectionSettings....
___
*[src/BloomExe/CLI/SpreadsheetExportCommand.cs, line 35 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-MpInwFv3XydE8FK7Iag:-MpInwFw6D2M-i2ZU5cN:b-qh45dh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a132e21b2638492ceac710d61c4f67f623efddd2/src/BloomExe/CLI/SpreadsheetExportCommand.cs#L35)):*
> ```Smalltalk
> 
> 				var bookInfo = new BookInfo(bookFolder, false);
> 				var book= new Book.Book(bookInfo, new BookStorage(bookInfo.FolderPath, locator, new BookRenamedEvent(), collectionSettings),
> ```

Ugh, so much boilerplate to get a book object...
___
*[src/BloomExe/CLI/SpreadsheetExportCommand.cs, line 38 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-MpIqny_1g-LM9edIS8A:-MpIqny_1g-LM9edIS8B:bra2nuw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2911e04b583ccea560d9904a104d990b3e0151c5/src/BloomExe/CLI/SpreadsheetExportCommand.cs#L38)):*
> ```Smalltalk
> 				null, collectionSettings, null, null, new BookRefreshEvent(), new BookSavedEvent(), new NoEditSaveContext());
> 
> 				var exporter = new SpreadsheetExporter(book.BookData);
> ```

This whole big headache is so that I can pass in a BookData which I use for mapping language codes to language display names.

Any better/easier way to do this?
___
*[src/BloomExe/Spreadsheet/InternalSpreadsheet.cs, line 144 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-MpIrey25y3OB3LhyZxN:-MpIrey25y3OB3LhyZxO:b-phfbdv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2911e04b583ccea560d9904a104d990b3e0151c5/src/BloomExe/Spreadsheet/InternalSpreadsheet.cs#L144)):*
> ```Smalltalk
> 		/// <param name="columnFriendlyName"></param>
> 		/// <returns>The index of the column (0-based)</returns>
> 		public int SetColumnForTag(string columnLabel, string columnFriendlyName)
> ```

I had a big headache because previously, it was a single function that could either Get or Set.
However, now we have a friendly name idea. This parameter is very useful (perhaps required) for Set, but not required for Get. I didn't want to add a parameter that all the Get references would need to calculate for no good reason.

So, i split the Get vs. Set scenarios.  Unfortunately, this is a behavioral change for the Get consumers.

AFAIK, there are only 2 Get scenarios in the non-test codebase. I tried to review these and update them to handle that it would not be automatically added. Hopefully I did an adequate job there.
There are numerous test scenarios that called this function, but I'm less worried about these as long as the unit tests pass.
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 206 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-MpIsQ614FVB83ZXkJwF:-MpIsQ614FVB83ZXkJwG:byautac) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2911e04b583ccea560d9904a104d990b3e0151c5/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L206)):*
> ```Smalltalk
> 				foreach (string lang in _sheet.Languages)
> 				{
> 					var columnIndex = _sheet.GetColumnForLang(lang);
> ```

This deserves careful review. GetColumnForLang does not have the same functionality as before.
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 323 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-MpIsWWd-tYwl4f39vWb:-MpIsWWd-tYwl4f39vWc:b5szcvk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2911e04b583ccea560d9904a104d990b3e0151c5/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L323)):*
> ```Smalltalk
> 			{
> 				var colIndex = _sheet.GetColumnForLang(lang);
> 				var content = colIndex >= 0 ? row.GetCell(colIndex).Content : "";
> ```

This deserves careful review too.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
Looks good...a few suggestions.

> Reviewed 12 of 15 files at r1, 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-:-MpJAxwT0WTCEpgLqWnT:bptg04m)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnThomson and @sujeffreyl)

___
*[src/BloomExe/CLI/SpreadsheetExportCommand.cs, line 38 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-MpIqny_1g-LM9edIS8A:-MpJ57SMDIRTSYMNiXNs:bgxnlwu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2911e04b583ccea560d9904a104d990b3e0151c5/src/BloomExe/CLI/SpreadsheetExportCommand.cs#L38)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

This whole big headache is so that I can pass in a BookData which I use for mapping language codes to language display names.

Any better/easier way to do this?
</blockquote></details>

It looks to me as if BookData.GetDisplayNameForLanguage (and its helper, GetLanguageNameWithScriptVariants) could usefully be moved to CollectionSettings. They are all about CollectionSettings data. They don't appear to use any private book data.
I suppose we might be sorry, if one day we allow the user to give the same language different names in different books of the same collection. But that strikes me as unlikely.
___
*[src/BloomExe/Spreadsheet/InternalSpreadsheet.cs, line 144 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-MpIrey25y3OB3LhyZxN:-MpJ735a0WMpUFK_lyxX:bjuo05r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2911e04b583ccea560d9904a104d990b3e0151c5/src/BloomExe/Spreadsheet/InternalSpreadsheet.cs#L144)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I had a big headache because previously, it was a single function that could either Get or Set.
However, now we have a friendly name idea. This parameter is very useful (perhaps required) for Set, but not required for Get. I didn't want to add a parameter that all the Get references would need to calculate for no good reason.

So, i split the Get vs. Set scenarios.  Unfortunately, this is a behavioral change for the Get consumers.

AFAIK, there are only 2 Get scenarios in the non-test codebase. I tried to review these and update them to handle that it would not be automatically added. Hopefully I did an adequate job there.
There are numerous test scenarios that called this function, but I'm less worried about these as long as the unit tests pass.
</blockquote></details>

I don't much like the name, but it's hard to come up with a name that describes well the combined task that this does. Probably my bad originally...methods that primarily return a value but sometimes modify things are problematic. The new argument (and new behavior, which isn't needed anyway AFAIK, of changing the friendly name of an existing column) make it worse.
Suggestion: instead, make a method AddColumnForTag, which only ever adds a new column (could still return its index). Then change the two 'real' callers to first call Get, then if they get -1, call Add. A fringe benefit is not having to look up the friendly name unless it's a new language.
That leaves the eight test callers. I wouldn't feel as bad about a test-only method GetExistingOrCreateColumnForTag, but you may find that it's fairly easy to determine whether each caller needs to use Get or Add.
It might be useful to make AddColumnForTag assert that there isn't already one for that tag. (If you then change any ambiguous test cases to Add, you'd quickly determine which should have been Get...unless some callers need both.)
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 206 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-MpIsQ614FVB83ZXkJwF:-MpJ9VSf4vy6-7nhYxya:b-jv1zxq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2911e04b583ccea560d9904a104d990b3e0151c5/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L206)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

This deserves careful review. GetColumnForLang does not have the same functionality as before.
</blockquote></details>

I don't think you need any of your changes here...maybe instead Assert that columnIndex >= 0. There should never be a need to add a column here, because we're iterating over the list of languages the spreadsheet already has, which comes from the existing columns.
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 323 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-MpIsWWd-tYwl4f39vWb:-MpJA6Wn0bolbWhRES9v:b-9b9dos) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2911e04b583ccea560d9904a104d990b3e0151c5/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L323)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

This deserves careful review too.
</blockquote></details>

Again I don't think there's any way you can be dealing here with a language that isn't already in the spreadsheet.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839)* status: 7 of 18 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 206 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-MpIsQ614FVB83ZXkJwF:-MpgBO921aeQgyp4i9bU:b-975gx7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2911e04b583ccea560d9904a104d990b3e0151c5/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L206)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't think you need any of your changes here...maybe instead Assert that columnIndex >= 0. There should never be a need to add a column here, because we're iterating over the list of languages the spreadsheet already has, which comes from the existing columns.
</blockquote></details>

Ok. Well, I made it throw an exception immediately instead, because seems to me the Assert would just assert and then run into an exception  next statement anyway (with a non-custom/less helpful exception message)

**Review by JohnThomson — CHANGES_REQUESTED** [review]
Nice. A few minor suggestions. Unfortunately it will need rebasing, and it will be a pain, because my change which also adds a constructor argument to SpreadsheetExporter, has been merged. We may need to talk about that, because my changes are aimed at letting autofac provide an argument. It may actually work out well, as autofac will happily provide the correct CollectionSettings without a need to make a new one for the production code, and you've already organized a mock for testing. However, I was lazy and didn't make the BookApi version use a factory for making the SpreadsheetExporter, since it already had the object it needed. That will also be a problem for your duplicate-code-removal PR. So we should make BookApi get a SpreadsheetExporter.Factory from autofac, and then we can have a common export method which always lets autofac make the exporter, complete with WebSocketServer AND CollectionSettings.

> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-:-MpsG_rp7WNxnB16c2_J:b-as9prz)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnThomson and @sujeffreyl)

___
*[src/BloomExe/Book/BookData.cs, line 1032 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-MpsE9mE0J8UbDABJ4Jt:-MpsE9mFCSewqmgjKLGL:b-k4nkok) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/72b9da6e63820d79e8bb226e785cc52e4187b2cb/src/BloomExe/Book/BookData.cs#L1032)):*
> ```Smalltalk
> 			// among the collection languages, so it means three things to check instead of four. And if by any chance
> 			// we're wanting a name of a language that is not currently in use in the book, but is known to the collection,
> 			// it's desirable to find it.
> ```

I think this comment is in the new method and not needed here?
___
*[src/BloomExe/Collection/CollectionSettings.cs, line 850 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-MpsEL_a2nznOlz7AFyL:-MpsEL_a2nznOlz7AFyM:b-tmvuxe) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/72b9da6e63820d79e8bb226e785cc52e4187b2cb/src/BloomExe/Collection/CollectionSettings.cs#L850)):*
> ```Smalltalk
> 			// among the collection languages, so it means three things to check instead of four. And if by any chance
> 			// we're wanting a name of a language that is not currently in use in the book, but is known to the collection,
> 			// it's desirable to find it.
> ```

This comment needs more thought. In the context of a collection method, using the book's languages is not really an option, so maybe the comment is obsolete?
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 206 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-MpIsQ614FVB83ZXkJwF:-MpsG0ra7bxUWys37dxD:b-fc1mp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2911e04b583ccea560d9904a104d990b3e0151c5/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L206)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Ok. Well, I made it throw an exception immediately instead, because seems to me the Assert would just assert and then run into an exception  next statement anyway (with a non-custom/less helpful exception message)
</blockquote></details>

I like what you did.
___
*[src/BloomExe/web/controllers/BookCommandsApi.cs, line 155 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-MpsGENw8Ztfgcn6-yy6:-MpsGENw8Ztfgcn6-yy7:b4zz7vi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/72b9da6e63820d79e8bb226e785cc52e4187b2cb/src/BloomExe/web/controllers/BookCommandsApi.cs#L155)):*
> ```Smalltalk
> 			try
> 			{
> 				var dom = new HtmlDom(XmlHtmlConverter.GetXmlDomFromHtmlFile(bookPath, false));				
> ```

We seem to have gotten a bunch of trailing whitespace on this line...thought we had something to prevent that?

**Review by sujeffreyl — COMMENTED** [review]
Yikes. Ok, I'll work on that.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-:-MpwjbCAEGxCHYF879HU:b2tdjdl)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Book/BookData.cs, line 1032 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-MpsE9mE0J8UbDABJ4Jt:-MpwhrpQ8kDunXwMxsf1:b-cvbbnf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/72b9da6e63820d79e8bb226e785cc52e4187b2cb/src/BloomExe/Book/BookData.cs#L1032)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think this comment is in the new method and not needed here?
</blockquote></details>

Well, the comment talks about book languages, but in the CollectionSettings class it doesn't make sense to have a discussion about whether or not to use the book languages, because obviously you won't use the book languages because the CollectionSettings has no specific book instance.
So, my line of thinking is that it made the most sense here. As an explanation of why we forward it to CollectionSettings instead of doing something with the this object's instance vars.

Does that make sense?
___
*[src/BloomExe/Collection/CollectionSettings.cs, line 850 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-MpsEL_a2nznOlz7AFyL:-MpwiJ4x8uj-LzyhaRc9:bldslzq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/72b9da6e63820d79e8bb226e785cc52e4187b2cb/src/BloomExe/Collection/CollectionSettings.cs#L850)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This comment needs more thought. In the context of a collection method, using the book's languages is not really an option, so maybe the comment is obsolete?
</blockquote></details>

Ah yeah. I was meaning to delete this.
___
*[src/BloomExe/web/controllers/BookCommandsApi.cs, line 155 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-MpsGENw8Ztfgcn6-yy6:-Mpwj3W-6RgO9kTaSff8:b-nvsk2e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/72b9da6e63820d79e8bb226e785cc52e4187b2cb/src/BloomExe/web/controllers/BookCommandsApi.cs#L155)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We seem to have gotten a bunch of trailing whitespace on this line...thought we had something to prevent that?
</blockquote></details>

Removed.
I don't know anything about... like a VS extension or something? I wrote on my TODO list to ask Andrew about that. Or is there someone else i should ask?

**Review by JohnThomson — COMMENTED** [review]
LGTM so far, but I expect conflict resolution still needs work?

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-:-Mq1BCBx-DQ6LKNWVHs6:b341iqy)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Review by sujeffreyl — COMMENTED** [review]
Rebased

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-:-MqGkIykEFNz2WT6X7oS:b9x2p3v)* status: 6 of 18 files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by JohnThomson — APPROVED** [review]
Things are re-arranged so much that this is very difficult to review, even having looked at the original changes and being familiar with the changes that forced the rebasing. However, this code is extensively unit tested and the tests haven't changed much, so it's very likely fine. I'm going to call it LGTM. @andrew-polk, looks like you commented on this issue also, so I'll give you a chance for any further thoughts.

> Reviewed 12 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-:-MqKOI1F2oaBWhj8-gpE:b-u826qd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Review by andrew-polk — COMMENTED** [review]
I don't think I commented. Merging.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839#-:-MqKQDz35fmgBOng66pP:bs34qm0)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Pull request merged**
