### PR TITLE
Improve error message when we can't lock to check out (BL-10139)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4585)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4585)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 300 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4585#-Me7-_jkAdWZK7iHbCM5:-Me7-_jl9RcRLxlbv9FY:b7zowwz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5b9d0dc68101d5909672882fdf28fe1235bd6052/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L300)):*
> ```Smalltalk
> 		{
> 			var msgId = "TeamCollection.ErrorLockingBook";
> 			var msgEnglish = "Error locking access to \"{0}\": {1}";
> ```

This seems too technical for showing the user. How about
`Bloom was not able to check out \"{0}\"`. 

And we can drop `e.Message` here?
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 309 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4585#-Me6zxie6PRNUl1pKH16:-Me6zxie6PRNUl1pKH17:b-5tyuuu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5b9d0dc68101d5909672882fdf28fe1235bd6052/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L309)):*
> ```Smalltalk
> 					param1 = cannotLockException.SyncAgent;
> 					msgEnglish =
> 						"Bloom was not able to check out \"{0}\" because some other program is busy with it. This may just be {1} synchronizing the file. Please try again later. If the problem continues, restart your computer.";
> ```

Could we factor out at least the last two sentences for l10n? That will save localizers time and also give us a bit more freedom in the future if we decide we have more to say, without completely losing the l10n we have.

Actually we can factor out the very first clause too if we go with:
1. "Bloom was not able to check out \"{0}\"."
2. "Some other program may be busy with it. This may just be {1} synchronizing the file. "
3. "Please try again later. If the problem continues, restart your computer."
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 319 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4585#-Me70jnb9xnxfLwjcwoH:-Me70jnb9xnxfLwjcwoI:bluy9yl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5b9d0dc68101d5909672882fdf28fe1235bd6052/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L319)):*
> ```Smalltalk
> 			}
> 
> 			var msg = new TeamCollectionMessage(MessageAndMilestoneType.Error, msgId, msgEnglish,
> ```

I can't see how {1} becomes "Dropbox", but it must happen somehow. Is it sufficiently non-magical and I just have missed it?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4585)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 300 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4585#-Me7-_jkAdWZK7iHbCM5:-MePuCjv91w4oVv8mBV6:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5b9d0dc68101d5909672882fdf28fe1235bd6052/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L300)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This seems too technical for showing the user. How about
`Bloom was not able to check out \"{0}\"`. 

And we can drop `e.Message` here?
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 309 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4585#-Me6zxie6PRNUl1pKH16:-MePuhKE9x0WB7EV5aFc:b5j8ior) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5b9d0dc68101d5909672882fdf28fe1235bd6052/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L309)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Could we factor out at least the last two sentences for l10n? That will save localizers time and also give us a bit more freedom in the future if we decide we have more to say, without completely losing the l10n we have.

Actually we can factor out the very first clause too if we go with:
1. "Bloom was not able to check out \"{0}\"."
2. "Some other program may be busy with it. This may just be {1} synchronizing the file. "
3. "Please try again later. If the problem continues, restart your computer."
</blockquote></details>

The message goes into an object (TeamCollectionMessage) that goes into our log. That object is set up for one EnglishMessage and one localization ID. Expanding that to a list of messages and IDs is non-trivial. We could assemble the parts and put it into the message object without an ID, but then it's different from others and that part of the log can't later be read in another language. But, that's a pretty minor consideration, so that's probably the way I'd be inclined to go if you still want to break it up.
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 319 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4585#-Me70jnb9xnxfLwjcwoH:-MePuG1g43x8WwKsBnwk:b-7qi9zc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5b9d0dc68101d5909672882fdf28fe1235bd6052/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L319)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I can't see how {1} becomes "Dropbox", but it must happen somehow. Is it sufficiently non-magical and I just have missed it?
</blockquote></details>

I added a comment and renamed a variable; that may help.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4585)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 309 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4585#-Me6zxie6PRNUl1pKH16:-Mf3rE0t434lFMn9jVKV:b-irskwh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5b9d0dc68101d5909672882fdf28fe1235bd6052/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L309)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

The message goes into an object (TeamCollectionMessage) that goes into our log. That object is set up for one EnglishMessage and one localization ID. Expanding that to a list of messages and IDs is non-trivial. We could assemble the parts and put it into the message object without an ID, but then it's different from others and that part of the log can't later be read in another language. But, that's a pretty minor consideration, so that's probably the way I'd be inclined to go if you still want to break it up.
</blockquote></details>

OK, made it three parts.

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4585)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 306 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4585#-Mf4Q_Gk2BmEyT53nIoS:-Mf4Q_Gk2BmEyT53nIoT:btmikct) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f0519ab86df7acd5723c468a7ef43b06221dd8ec/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L306)):*
> ```Smalltalk
> 				var msgCantCheckOut = string.Format(LocalizationManager.GetString("TeamCollection.CannotCheckout",
> 					"Bloom was not able to check out \"{0}\" because some other program is busy with it."), Path.GetFileName(bookFolder));
> 				var msgTryAgain = LocalizationManager.GetString("TeamCollection.TryAgainOrRestart",
> ```

This can be `Common.`
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 318 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4585#-Mf4Qe_j6JNbAOvIx6Ec:-Mf4Qe_j6JNbAOvIx6Ed:b-r3anqv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f0519ab86df7acd5723c468a7ef43b06221dd8ec/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L318)):*
> ```Smalltalk
> 				{
> 					part2 = LocalizationManager.GetString("TeamCollection.SomethingSynchronizing",
> 						"This may just be something synchronizing the file.");
> ```

By dividing like this does rather than like I suggested, doesn't `part2` lose any benefit? Might as well join with part1

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4585)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 306 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4585#-Mf4Q_Gk2BmEyT53nIoS:-Mf8K1Gw5tAfb1RgbjAY:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f0519ab86df7acd5723c468a7ef43b06221dd8ec/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L306)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This can be `Common.`
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamCollectionApi.cs, line 318 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4585#-Mf4Qe_j6JNbAOvIx6Ec:-Mf8KvosAOnKiPX2r73z:bu9w3a4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f0519ab86df7acd5723c468a7ef43b06221dd8ec/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L318)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

By dividing like this does rather than like I suggested, doesn't `part2` lose any benefit? Might as well join with part1
</blockquote></details>

Sorry. So focused on the mechanics of breaking it up I missed exactly how. Fixed.

**Review by hatton — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4585)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @hatton)

**Pull request merged**
