### PR TITLE
Modernize AutoUpdateSoftwareDialog (BL-12086)

### PR DESCRIPTION
**Pull request by andrew-polk**
Includes ensuring dialogs hosted in a WinForms frame do not have the drag cursor (BL-12038)

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5748)

### CODE REVIEW

**Review by gmartin7 — CHANGES_REQUESTED** [review]
Just one comment.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5748#-:-NSMvle2BEmym-twYiMw:b-cc91uw)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx` line 132 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5748#-NSMvQd-BGIt-egcANQQ:-NSMvQd-BGIt-egcANQR:bcd33fp) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e285196a94b029070b315144a748737d947ed8bf/src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx#L132)):*
> ```XML
> 
>         const disableDragging =
>             disableDraggingProp !== undefined
> ```

Do you really need the `!== undefined`?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5748)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx` line 132 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5748#-NSMvQd-BGIt-egcANQQ:-NSMw8X95JYymmdf7byR:bq5iipt) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e285196a94b029070b315144a748737d947ed8bf/src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx#L132)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Do you really need the `!== undefined`?
</blockquote></details>

Yep. The idea is to use that prop if it is passed in. If not, we set it based on dialogFrameProvidedExternally.

**Review by gmartin7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5748)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx` line 132 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5748#-NSMvQd-BGIt-egcANQQ:-NSN3qKiE-7Pix33Pu8U:bab63fs) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e285196a94b029070b315144a748737d947ed8bf/src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx#L132)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Yep. The idea is to use that prop if it is passed in. If not, we set it based on dialogFrameProvidedExternally.
</blockquote></details>

What happens if you just do `const disableDragging = disableDraggingProp ? disableDraggingProp :  !!dialogFrameProvidedExternally;` or `const disableDragging = !!disableDraggingProp ? disableDraggingProp : !!dialogFrameProvidedExternally;`

**Review by gmartin7 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5748)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
