### PR TITLE
BL-6354 Fix making thumbnail when screen scaled

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2741)

### CODE REVIEW

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2741)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/HtmlThumbNailer.cs, line 460 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2741#-LMJzwHD-X2FqrOcQYsH:-LMJzwHD-X2FqrOcQYsI:b8vx9o4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/64f049b68fcb2c70b0dfb5b3faf3b685dc24f699/src/BloomExe/HtmlThumbNailer.cs#L460)):*
> ```Smalltalk
> 					{
> 						Guard.AgainstNull(browser.Document.ActiveElement, "browser.Document.ActiveElement");
> 						var div = browser.Document.ActiveElement.EvaluateXPath("//div[contains(@class, 'bloom-imageContainer')]").GetNodes().FirstOrDefault() as GeckoElement;
> ```

Would this be ok if the xmatter didn't have an image on the cover?

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2741)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2741)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/HtmlThumbNailer.cs, line 460 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2741#-LMJzwHD-X2FqrOcQYsH:-LMK1Lzh42wx5wg7fbne:bxy4sfg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/64f049b68fcb2c70b0dfb5b3faf3b685dc24f699/src/BloomExe/HtmlThumbNailer.cs#L460)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Would this be ok if the xmatter didn't have an image on the cover?
</blockquote></details>

It will probably crash if there isn't even a place for an image (i.e., no bloom-imageContainer). So would the old code, I believe. I can try to figure out a way to fix it.

**Comment by andrew-polk** [comment]
___
*[src/BloomExe/HtmlThumbNailer.cs, line 460 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2741#-LMJzwHD-X2FqrOcQYsH:-LMK3VnMC2ShoiWm_mZw:b6502vo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/64f049b68fcb2c70b0dfb5b3faf3b685dc24f699/src/BloomExe/HtmlThumbNailer.cs#L460)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It will probably crash if there isn't even a place for an image (i.e., no bloom-imageContainer). So would the old code, I believe. I can try to figure out a way to fix it.
</blockquote></details>

I think the Video xmatter has no image, fwiw.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2741)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @hatton)

___
*[src/BloomExe/HtmlThumbNailer.cs, line 460 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2741#-LMJzwHD-X2FqrOcQYsH:-LMK7QOF8aqyy66klI6B:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/64f049b68fcb2c70b0dfb5b3faf3b685dc24f699/src/BloomExe/HtmlThumbNailer.cs#L460)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think the Video xmatter has no image, fwiw.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2741)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Comment by JohnThomson** [comment]
Cherry-picked to 4.3

**Pull request merged**
