### PR TITLE
Improve bulk upload stage 2 (BL-9997)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
I'm not quite clear whether the code you're modifying is common to normal and bulk upload or not. Assuming it's not, have you thought whether regular upload should generate and include the hash file? I could imagine someone who has uploaded half their books, either before they got sick of doing it one at a time and researched bulk upload, or for preliminary review etc. They might be quite glad if bulk upload would not do those books again if it's not needed.
Mostly looks good. Seems like some unit tests could be added...book transfer is fairly extensively tested, IIRC. Dry run tests, especially, would be less expensive than really sending stuff.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562#-:-McpdzCg4D35czTj1Hcb:btppuqx)* status: all files reviewed, 7 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/Program.cs, line 162 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562#-McpF-2v57o-9EtHgcf5:-McpF-2v57o-9EtHgcf6:bkqyd67) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/74ec4174bc9a8f8959158b135bf111641b515906/src/BloomExe/Program.cs#L162)):*
> ```Smalltalk
> 								if (!(error is HelpVerbRequestedError) && !(error is HelpRequestedError))
> 								{
> 									// Debug.WriteLine(error.ToString());
> ```

I don't get this part of the change. For EVERY command line way of running Bloom, we're going to discard any error messages with no attempt to pass them to the user?? I for sure wrote the Spreadsheet commands expecting the user to see any errors I generated.
___
*[src/BloomExe/CLI/UploadCommand.cs, line 104 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562#-McpGSruATPuEMhObH7l:-McpGSrv67NTBcJlu0YO:baf5i9t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/74ec4174bc9a8f8959158b135bf111641b515906/src/BloomExe/CLI/UploadCommand.cs#L104)):*
> ```Smalltalk
> 
> 	[Option('X', "excludeMusicAudio", HelpText = "Exclude music (background) audio files from upload.  (The default is to upload music files.)", Required = false)]
> 	public bool ExcludeMusicAudio { get; set; }
> ```

x and m? xn and xm? Outside of Linux, making a difference in case cause a quite different thing to happen seems dubious.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 687 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562#-Mcp_fGtB8NrprqJu3lV:-Mcp_fGu4EChKbrARj5N:bt4sdji) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/74ec4174bc9a8f8959158b135bf111641b515906/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L687)):*
> ```Smalltalk
> 		/// Folders that contain exactly one .htm file are interpreted as books and uploaded.
> 		/// Other folders are searched recursively for children that appear to be bloom books.
> 		/// The parent folder of a bloom book is searched for a .bloomContainer file and, if one is found,
> ```

bloomContainer => bloomCollection (while you're fixing comments :-)
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 706 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562#-Mcp_yPk3DVjYng6OgFl:-Mcp_yPk3DVjYng6OgFm:bg932dh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/74ec4174bc9a8f8959158b135bf111641b515906/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L706)):*
> ```Smalltalk
> 			if (!LogIn(options.UploadUser, options.UploadPassword))
> 			{
> 				SIL.Reporting.ErrorReport.NotifyUserOfProblem($"Could not log you in using user='{options.UploadUser}' and password='{options.UploadPassword}'.");
> ```

This is not new, but it seems a poor practice to display a password in clear text in a dialog or on the console.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 845 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562#-McpawI32vaOAlqYN2lN:-McpawI32vaOAlqYN2lO:b-9t41dz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/74ec4174bc9a8f8959158b135bf111641b515906/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L845)):*
> ```Smalltalk
> 					if (IsDryRun)
> 					{
> 						uploadedAlready = CheckAgainstLocalHashfile(currentHashes, uploadInfoPath);
> ```

So, if the local hash file is not the same as the one on S3, this could be inaccurate as to what will actually be uploaded? I think at least you should comment about why you don't figure it out the same way...is the idea that a dry run should not require any internet access?
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 861 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562#-McpbdpQ51cgkLU7xP5T:-McpbdpQ51cgkLU7xP5U:bd83jns) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/74ec4174bc9a8f8959158b135bf111641b515906/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L861)):*
> ```Smalltalk
> 					}
> 				}
> 				RobustFile.WriteAllText(uploadInfoPath, currentHashes);	// sync local copy of hashes file
> ```

This means, if they do two dry runs, the second one will report that this book will not be uploaded, doesn't it? That seems wrong.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 1117 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562#-McpcUcL2j4OI6TbtLyI:-McpcUcL2j4OI6TbtLyJ:b-2xran5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/74ec4174bc9a8f8959158b135bf111641b515906/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L1117)):*
> ```Smalltalk
> 		}
> 
> 		public static string HashBookFolder(string directory)
> ```

I think it would probably be good to use Book.MakeVersionCode(), which similarly generates a sha but does various things to make it less likely we will get a different code by just opening the book but without changing anything. It's possible that code is ignoring the two collection level files, in which case, you could improve it!
Should we consider whether we've been told to upload audio? If not, and if that's the only thing that changed, we don't need to. But probably it's not worth being that picky...most of the benefit is not re-uploading things that didn't change at all.

**Review by StephenMcConnel — COMMENTED** [review]
The code is mostly in the bulk upload functions at the moment.  The hash computation certainly is.  Experimenting with getting the hash for "regular" uploads revealed that the exact form of the book HTML appears to vary by a few characters between books loaded by the interactive editing/publishing and books loaded by the bulk upload process.  If it were important, we could chase down the differences and reconcile the hashing process but it doesn't seem worth it.
Book transfer has a number of unit tests, but bulk upload doesn't have any.  At a minimum, I'd have to create a folder with a .bloomCollection file and subfolders with book files for setup.  I would also need to mock the BulkUploadProgressDlg somehow to avoid GUI problems and to capture output for the test to check.  I'm not sure it's worth it, but if you insist...

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562#-:-Mcukqtq4JyTPnMBDxDn:b-hp8sck)* status: all files reviewed, 7 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Program.cs, line 162 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562#-McpF-2v57o-9EtHgcf5:-Mcu2T4L3RpLK4bQ6iCW:bohw3z7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/74ec4174bc9a8f8959158b135bf111641b515906/src/BloomExe/Program.cs#L162)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't get this part of the change. For EVERY command line way of running Bloom, we're going to discard any error messages with no attempt to pass them to the user?? I for sure wrote the Spreadsheet commands expecting the user to see any errors I generated.
</blockquote></details>

error.ToString() prints out just the class name of the error as far as I can tell.  This adds no useful information to an error message that has already been printed out by the CommandLine code.
For example,

Bloom 5.1.000.0
© SIL International 2012-2020

ERROR(S):
  Option 'p, password' has no value.
  Required option 'u, user' is missing.
  Required option 'p, password' is missing.
  A required value not bound to option name is missing.

  -x, --excludeNarrationAudio    Exclude narration audio files from upload. (The default is to upload narration files.)
...
  -d, --destination              (Default: dry-run) If preCommandLine.MissingValueOptionError
CommandLine.MissingRequiredOptionError
CommandLine.MissingRequiredOptionError
CommandLine.MissingRequiredOptionError
sent, this must be one
                                 of dry-run, dev, or production. 'dry-run' will
                                 just print out what would happen. 'dev' will
                                 upload to dev.bloomlibrary.org (you will need
                                 to use an account from there). 'production'
                                 will upload to bloomlibrary.org
...
The class names in the middle of the message add nothing of value, and will be confusing and alarming to the user.
I've added a comment to the code to explain this.
___
*[src/BloomExe/CLI/UploadCommand.cs, line 104 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562#-McpGSruATPuEMhObH7l:-Mcu4gt_E-k5Scg-ica3:bdpb9e1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/74ec4174bc9a8f8959158b135bf111641b515906/src/BloomExe/CLI/UploadCommand.cs#L104)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

x and m? xn and xm? Outside of Linux, making a difference in case cause a quite different thing to happen seems dubious.
</blockquote></details>

I changed the 'X' to 'e'.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 687 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562#-Mcp_fGtB8NrprqJu3lV:-McuIs6JAL6cI14uPi7E:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/74ec4174bc9a8f8959158b135bf111641b515906/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L687)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

bloomContainer => bloomCollection (while you're fixing comments :-)
</blockquote></details>

Done.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 706 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562#-Mcp_yPk3DVjYng6OgFl:-McuJGrQ682XTdnTuQVo:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/74ec4174bc9a8f8959158b135bf111641b515906/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L706)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This is not new, but it seems a poor practice to display a password in clear text in a dialog or on the console.
</blockquote></details>

Done.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 845 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562#-McpawI32vaOAlqYN2lN:-McuJhZy-jPXpbG5WgGy:b-5baa4j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/74ec4174bc9a8f8959158b135bf111641b515906/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L845)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

So, if the local hash file is not the same as the one on S3, this could be inaccurate as to what will actually be uploaded? I think at least you should comment about why you don't figure it out the same way...is the idea that a dry run should not require any internet access?
</blockquote></details>

Changed to check Program.RunningUnitTests since (if tests are written) we do want tests to be more deterministic.
I suppose you're right that it would a more accurate dry run to use the downloaded hash file.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 861 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562#-McpbdpQ51cgkLU7xP5T:-McuK5jD2VYTHffTftIX:b-jczl3m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/74ec4174bc9a8f8959158b135bf111641b515906/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L861)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This means, if they do two dry runs, the second one will report that this book will not be uploaded, doesn't it? That seems wrong.
</blockquote></details>

I suppose you're right.  I've changed dry run to check against the uploaded file.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 1117 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562#-McpcUcL2j4OI6TbtLyI:-McudpEQ22EueOnEUmfe:bo69jgv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/74ec4174bc9a8f8959158b135bf111641b515906/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L1117)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think it would probably be good to use Book.MakeVersionCode(), which similarly generates a sha but does various things to make it less likely we will get a different code by just opening the book but without changing anything. It's possible that code is ignoring the two collection level files, in which case, you could improve it!
Should we consider whether we've been told to upload audio? If not, and if that's the only thing that changed, we don't need to. But probably it's not worth being that picky...most of the benefit is not re-uploading things that didn't change at all.
</blockquote></details>

Done.  I didn't change anything about audio.  I added the two collection level files to the hashing, and
also put the Sha256 object into a using block to avoid yet another memory leak.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
I'm not sure, either. I'm not going to insist, if your judgement is that nothing can reasonably be done. As another option to consider, is it possible to extract any of the code that is unique to bulk upload into methods that can be tested independently? For example, it might be possible to test some of the code that generates the hashes. It's going to be more robust if we can avoid actually uploading things.
Generally looks good. Couple of minor questions.

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562#-:-Md2Pzro5xkO41mEXmGR:bqgxwkc)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/Book/Book.cs, line 3673 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562#-Md2ShRo3z0NxMuezmhD:-Md2ShRo3z0NxMuezmhE:b-z6h0q5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7585bde4484a0d51117ef1059b23962438053edb/src/BloomExe/Book/Book.cs#L3673)):*
> ```Smalltalk
> 							sha.TransformBlock(buffer, 0, buffer.Length, buffer, 0);
> 						}
> 					}
> ```

In "real life", customCollectionStyles.css is of course predictable, and the collection settings is at CollectionSettings.SettingsFilePath. However, it might be a   pain to make that work if there are any unit tests of this code involving mock books. What you have will usually work pretty well. It will pull in any other .bloomCollections, but that should be very rare. I do wonder if there might be unit tests where the book folder is a direct child of the temp folder, and scanning all the files in Temp might slow things down.
Is there a reason for the complexity of using a loop here? If so, probably deserves a comment.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Book/Book.cs, line 3673 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562#-Md2ShRo3z0NxMuezmhD:-Md3poN48nFdK_XyUoQZ:b-er215b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7585bde4484a0d51117ef1059b23962438053edb/src/BloomExe/Book/Book.cs#L3673)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

In "real life", customCollectionStyles.css is of course predictable, and the collection settings is at CollectionSettings.SettingsFilePath. However, it might be a   pain to make that work if there are any unit tests of this code involving mock books. What you have will usually work pretty well. It will pull in any other .bloomCollections, but that should be very rare. I do wonder if there might be unit tests where the book folder is a direct child of the temp folder, and scanning all the files in Temp might slow things down.
Is there a reason for the complexity of using a loop here? If so, probably deserves a comment.
</blockquote></details>

CollectionSettings is not available at this point.  I've changed the code to explicitly check the single css file, and the expected .bloomCollection file.  If it doesn't find the latter, it then will scan for *.bloomCollection.  I don't trust users not to play games with the the filename when it's not necessarily being totally controlled by our software.  I'd think that would be a greater source of error than somehow ending up with multiple .bloomCollection files.

Note that this may change all of the stored hash files since the order of the files was not guaranteed, and does make a difference!  This may be better in the long run, being more deterministic, but it could cause re-uploading 100s of Kygyzstan books.

**Review by JohnThomson — APPROVED** [review]
LGTM. But not merging myself in case there are changes that missed getting pushed.

> Reviewed 3 of 7 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562#-:-MdMgehRDKsSaP4KCOji:bfwpk19)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/Book/Book.cs, line 3673 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4562#-Md2ShRo3z0NxMuezmhD:-MdMfR8p3aYWT4XPH-F1:b-pxkjxk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7585bde4484a0d51117ef1059b23962438053edb/src/BloomExe/Book/Book.cs#L3673)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

CollectionSettings is not available at this point.  I've changed the code to explicitly check the single css file, and the expected .bloomCollection file.  If it doesn't find the latter, it then will scan for *.bloomCollection.  I don't trust users not to play games with the the filename when it's not necessarily being totally controlled by our software.  I'd think that would be a greater source of error than somehow ending up with multiple .bloomCollection files.

Note that this may change all of the stored hash files since the order of the files was not guaranteed, and does make a difference!  This may be better in the long run, being more deterministic, but it could cause re-uploading 100s of Kygyzstan books.
</blockquote></details>

I don't actually see the change. But it was a marginal preference anyway. You make a good point about why we should have the loop as a fall-back, and if we have it at all, it no longer simplifies the code to use the explicit names. With the further consideration of keeping all the parent directory files in alphabetical order (as at present) to avoid re-uploading, I'd be inclined to leave this unchanged.

**Comment by StephenMcConnel** [comment]
This has been superseded by a PR from John Hatton which incorporates this code as a starting point.

**Pull request closed without merging**
