### PR TITLE
Record video (BL-5858)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2327)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/BloomBrowserUI/bookEdit/css/editMode.less, line 189 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327#-L9ft2uf-8wU9UBnJc4i:-L9ft2ug-IvNFYENkFQk:bocr00u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44b3f7d6630db26344d9c7513a3329f176c19ccc/src/BloomBrowserUI/bookEdit/css/editMode.less#L189)):*
> ```Less
> .bloom-videoContainer {
>     &.bloom-selected {
>         border: solid 2px @bloom-yellow
> ```

Not worth a new commit just for this, but I'm surprised some linter or something didn't pick up the missing semi-colon here.

---

*[src/BloomBrowserUI/bookEdit/toolbox/videoRecorder/videoRecorder.less, line 11 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327#-L9fteK4C28ZjYlx2WA1:-L9fteK4C28ZjYlx2WA2:b-uepkhu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44b3f7d6630db26344d9c7513a3329f176c19ccc/src/BloomBrowserUI/bookEdit/toolbox/videoRecorder/videoRecorder.less#L11)):*
> ```Less
> 
> #videoToggleRecording {
>     background-image: url(audio/record_expected.svg);
> ```

With these two icons being shared, I think we want them up at a common place. See also https://issues.bloomlibrary.org/youtrack/issue/BL-5845.

---

*[src/BloomBrowserUI/bookEdit/toolbox/videoRecorder/videoTool.tsx, line 72 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327#-L9fuD6s0pipLwt4iD99:-L9fuD6s0pipLwt4iD9A:b2odgv7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44b3f7d6630db26344d9c7513a3329f176c19ccc/src/BloomBrowserUI/bookEdit/toolbox/videoRecorder/videoTool.tsx#L72)):*
> ```XML
>         const constraints = { video: true };
>         // ((navigator.mediaDevices) as any).getUserMedia(constraints, this.startMonitoring, this.errorCallback);
>         // works in FF 59 and Chrome. Not in Bloom.
> ```

This comment must go with the line above? Could be made more clear.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.pug, line 12 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327#-L9gULfODEBYgzLVSjAy:-L9gULfODEBYgzLVSjAz:bfqbkxq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44b3f7d6630db26344d9c7513a3329f176c19ccc/src/BloomBrowserUI/bookEdit/toolbox/toolbox.pug#L12)):*
> ```Pug
> 		link(rel='stylesheet', href='/bloom/bookEdit/toolbox/panAndZoom/panAndZoom.css')
> 		link(rel='stylesheet', href='/bloom/bookEdit/toolbox/music/music.css')
> 		link(rel='stylesheet', href='/bloom/bookEdit/toolbox/videoRecorder/videoRecorder.css')
> ```

Now we can use the import approach instead, because it creates more encapsulated components. See https://github.com/BloomBooks/BloomDesktop/pull/2322.

---

*[src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug, line 16 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327#-L9gUmqbEPOe-C7T3XMP:-L9gUmqd09zziBZ__N9w:brvij76) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44b3f7d6630db26344d9c7513a3329f176c19ccc/src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug#L16)):*
> ```Pug
> 			.checkbox.clear#musicCheck(data-tool='musicTool', onclick='FrameExports.showOrHideTool_click(this);')
> 			.checkbox-label(data-i18n='EditTab.Toolbox.Music.Heading') Music Tool
> 			.checkbox.clear#videoCheck(data-tool='videoTool', onclick='FrameExports.showOrHideTool_click(this);')
> ```

Too bad we still have to "register" tools in multiple places. It seems like this thing could be generated instead of being a PUG file?

---

*[src/BloomExe/Edit/EditingView.cs, line 1524 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327#-L9gVo1z2fjrSKvm8aQE:-L9gVo1z2fjrSKvm8aQF:bs7ew7b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44b3f7d6630db26344d9c7513a3329f176c19ccc/src/BloomExe/Edit/EditingView.cs#L1524)):*
> ```Smalltalk
> 		}
> 
> 		// It's slightly odd for a component which has project rather than global scope to be registered as a request
> ```

All of this seems like maybe it belongs in the model? The only "UI" here is in case of errors (which in this case is done in an kind of aberrant way, with a messagebox).

---

*[src/BloomExe/Edit/ToolboxView.cs, line 45 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327#-L9gWT2j4WxErWl8Nier:-L9gWT2j4WxErWl8Nies:b-c5lwkp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44b3f7d6630db26344d9c7513a3329f176c19ccc/src/BloomExe/Edit/ToolboxView.cs#L45)):*
> ```Smalltalk
> 	///			}
> 	///		which specifies the icon for your tool. (And create the icon in the BloomBrowserUI/images folder).
> 	/// - Usually you will add a line to GetToolboxServerDirectories() in this file
> ```

This is messed up. Yet one more place one has to "know" about to simply add a tool component. Cannot the tool's html specify where to find its icon?

---

*[src/BloomExe/web/RequestInfo.cs, line 276 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327#-L9gWw9j8effrIxaZ0Ep:-L9gWw9j8effrIxaZ0Eq:b81dr0i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44b3f7d6630db26344d9c7513a3329f176c19ccc/src/BloomExe/web/RequestInfo.cs#L276)):*
> ```Smalltalk
> 		}
> 
> 		public byte[] RawPostData
> ```

Looking at the sybling methods here... shouldn't this insted by GetRawPostData()?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327)*

**Comment by JohnThomson** [comment]
Review status: 7 of 22 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/css/editMode.less, line 189 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327#-L9ft2uf-8wU9UBnJc4i:-L9kCUaVC8did2i9xOJ8:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44b3f7d6630db26344d9c7513a3329f176c19ccc/src/BloomBrowserUI/bookEdit/css/editMode.less#L189)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Not worth a new commit just for this, but I'm surprised some linter or something didn't pick up the missing semi-colon here.
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug, line 16 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327#-L9gUmqbEPOe-C7T3XMP:-L9kDdCl15GT-KW31i28:boyg0bv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44b3f7d6630db26344d9c7513a3329f176c19ccc/src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug#L16)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Too bad we still have to "register" tools in multiple places. It seems like this thing could be generated instead of being a PUG file?
</blockquote></details>

It probably could. Doesn't feel like an appropriate change for this PR, though.

---

*[src/BloomBrowserUI/bookEdit/toolbox/videoRecorder/videoRecorder.less, line 11 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327#-L9fteK4C28ZjYlx2WA1:-L9kFOPk9_tX5W2Mpgs5:b-rn7h36) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44b3f7d6630db26344d9c7513a3329f176c19ccc/src/BloomBrowserUI/bookEdit/toolbox/videoRecorder/videoRecorder.less#L11)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

With these two icons being shared, I think we want them up at a common place. See also https://issues.bloomlibrary.org/youtrack/issue/BL-5845.
</blockquote></details>

Done (but see question in BL-5845)

---

*[src/BloomBrowserUI/bookEdit/toolbox/videoRecorder/videoTool.tsx, line 72 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327#-L9fuD6s0pipLwt4iD99:-L9kFrVp0TiikJSn-tgz:byl6f0n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44b3f7d6630db26344d9c7513a3329f176c19ccc/src/BloomBrowserUI/bookEdit/toolbox/videoRecorder/videoTool.tsx#L72)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This comment must go with the line above? Could be made more clear.
</blockquote></details>

I took it and the line above out. I think at some point I incorrectly thought the "then" version was not working in Gecko45.

---

*[src/BloomExe/Edit/EditingView.cs, line 1524 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327#-L9gVo1z2fjrSKvm8aQE:-L9kHc9P8rX7HLzpa8JO:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44b3f7d6630db26344d9c7513a3329f176c19ccc/src/BloomExe/Edit/EditingView.cs#L1524)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

All of this seems like maybe it belongs in the model? The only "UI" here is in case of errors (which in this case is done in an kind of aberrant way, with a messagebox).
</blockquote></details>

Done.

---

*[src/BloomExe/Edit/ToolboxView.cs, line 45 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327#-L9gWT2j4WxErWl8Nier:-L9kIvtuEtfx9eF87dLU:bw7lttb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44b3f7d6630db26344d9c7513a3329f176c19ccc/src/BloomExe/Edit/ToolboxView.cs#L45)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This is messed up. Yet one more place one has to "know" about to simply add a tool component. Cannot the tool's html specify where to find its icon?
</blockquote></details>

I'm not getting this. Are you complaining about the less rule a few lines up, which specifies the icon? I suppose it could be put directly in the HTML, but we more often specify images in CSS, and some of the HTML which this rule affects is, IIRC, generated by the accordion code rather than under our control. And it wouldn't reduce the list of steps here...would still need to note what to put in the HTML to hook to the icon.
Or are you thinking that we shouldn't need to add a new search directory? I'm not sure why we need that, but I don't think it's to do with finding the icon.
(I don't think this is a new requirement...each time I add a tool I seem to discover one more step we had not previously documented. Of course it would be nice to continue reducing the number of steps...)

---

*[src/BloomExe/web/RequestInfo.cs, line 276 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327#-L9gWw9j8effrIxaZ0Ep:-L9kINKF3Edhnc7Eqc9q:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44b3f7d6630db26344d9c7513a3329f176c19ccc/src/BloomExe/web/RequestInfo.cs#L276)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Looking at the sybling methods here... shouldn't this insted by GetRawPostData()?
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookEdit/toolbox/toolbox.pug, line 12 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327#-L9gULfODEBYgzLVSjAy:-L9kKKjFCNUKwdoTkIYI:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44b3f7d6630db26344d9c7513a3329f176c19ccc/src/BloomBrowserUI/bookEdit/toolbox/toolbox.pug#L12)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Now we can use the import approach instead, because it creates more encapsulated components. See https://github.com/BloomBooks/BloomDesktop/pull/2322.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327)*

**Comment by andrew-polk** [comment]
Reviewed 18 of 19 files at r2.
Review status: 21 of 22 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327)*

**Comment by hatton** [comment]
Reviewed 7 of 19 files at r1, 19 of 19 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug, line 16 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327#-L9gUmqbEPOe-C7T3XMP:-L9l8Fgt4YHc6pihSytM:blrzy7l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44b3f7d6630db26344d9c7513a3329f176c19ccc/src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug#L16)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It probably could. Doesn't feel like an appropriate change for this PR, though.
</blockquote></details>

But no PR ever is... I don't see how we ever *improve* the architecture with this approach. Whenever I point out that something is being coded in a messed up way, the answer is *always*  a variant of "I'm just doing things the way they have been done". I'm really quite at a loss of how to get everybody to want to constantly improve the system rather than just adding more features on top of things thus making it harder to change in the future. 

---

*[src/BloomExe/Edit/ToolboxView.cs, line 45 at r1](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327#-L9gWT2j4WxErWl8Nier:-L9l9HKz3RW3u6iO2dnx:b-hf4os1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/44b3f7d6630db26344d9c7513a3329f176c19ccc/src/BloomExe/Edit/ToolboxView.cs#L45)):*
> Are you complaining about the less rule a few lines up

I'm complaining about the instructions in this comment, which say to add some lines to settings.pug for each tool you want to add. I don't care if this goes in less, html, js. I care that it goes in a *component*. C O M P O N E N T.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/bloombooks/bloomdesktop/2327)*

**Pull request merged**
