### PR TITLE
Remove (rather than only display:none) certain elements before creating ePub (BL-4348)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1617)

### CODE REVIEW

**Comment by JohnThomson** [comment]
:lgtm: (But see one suggestion for solving further problems while you're in this area)

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 871 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617#-KgLDlyJDmKYdDMB9jGH:-KgLDlyJDmKYdDMB9jGI:bhej7bs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18f6ce3ac7658bb97f4e058a3d7b18dee6acab7e/src/BloomExe/Publish/EpubMaker.cs#L871)):*
> ```Smalltalk
> 					var lang = langAttr == null ? null : langAttr.Value;
> 					// normal content page. What will be displayed here is predictable enough without
> 					// the overhead of navigating a real browser to a real page.
> ```

I don't think this comment is true any more. Content pages have the same problem as xmatter: for example, a book may contain a certain translation group in V, N1, and N2, but the page settings may now specify that only N1 is displayed. My recommendation would be that we just use IsDisplayed() throughout.  If the slowdown is drastically unacceptable, we can reconsider, or try optimizations like a single JavaScript call that returns the IDs of all the display:none divs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617#-:-KgLF_IuRoeTA58sh4CK:b-4fvw2x)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 871 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617#-KgLDlyJDmKYdDMB9jGH:-KgLIsvjisl0YR088y9A:bgvfdyl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18f6ce3ac7658bb97f4e058a3d7b18dee6acab7e/src/BloomExe/Publish/EpubMaker.cs#L871)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't think this comment is true any more. Content pages have the same problem as xmatter: for example, a book may contain a certain translation group in V, N1, and N2, but the page settings may now specify that only N1 is displayed. My recommendation would be that we just use IsDisplayed() throughout.  If the slowdown is drastically unacceptable, we can reconsider, or try optimizations like a single JavaScript call that returns the IDs of all the display:none divs.
</blockquote></details>

I did try that, but it caused some errors starting up the browser with the other pages (during unit testing) and caused a unit test to fail which I couldn't seem to understand. Since there are now two of us who that it was a good idea, I will look at the problems again to see if I can make sense of them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617)*

**Comment by andrew-polk** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/Publish/EpubMaker.cs, line 871 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617#-KgLDlyJDmKYdDMB9jGH:-KgPEm8EGcrmnUhpoNmf:bkcrvj1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18f6ce3ac7658bb97f4e058a3d7b18dee6acab7e/src/BloomExe/Publish/EpubMaker.cs#L871)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I did try that, but it caused some errors starting up the browser with the other pages (during unit testing) and caused a unit test to fail which I couldn't seem to understand. Since there are now two of us who that it was a good idea, I will look at the problems again to see if I can make sense of them.
</blockquote></details>

Ok, I made all elements determine visibility from the browser. This required updating some existing tests which were invalidly passing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617)*

**Comment by JohnThomson** [comment]
I don't like that display:none and display:flex are creeping into the actual epubs. I doubt it will work properly in most/any readers. I'm pretty sure I tried it (though they may have improved since).
Worth adding a unit test for the case I wrote about in the issue?

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookLayout/basePage-sharedRules.less, line 24 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617#-KgPmcPsFVgPtKkgnxp-:-KgPmcPtShcVjj5D4jlh:b-tag42a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/abcd8165c120883b480262e36ddd0264c24a868c/src/BloomBrowserUI/bookLayout/basePage-sharedRules.less#L24)):*
> ```Less
> //Each of these is assumed to be unwanted:
> 
> //This moved to basePage-shareRules.less:
> ```

Is this because we're using the epub css to figure visibility? Because shared is supposed to be for css that will actually be included in the epub, and we shouldn't need display:none rules there.

---

*[src/BloomBrowserUI/bookLayout/basePage-sharedRules.less, line 30 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617#-KgPS6gMEnz6TeVIWSSd:-KgPS6gMEnz6TeVIWSSe:b-77qhs8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/abcd8165c120883b480262e36ddd0264c24a868c/src/BloomBrowserUI/bookLayout/basePage-sharedRules.less#L30)):*
> ```Less
> }
> .bloom-translationGroup {
>     display: flex;
> ```

I don't think we want this in epubs, do we? Doubt very much that readers will handle flex or order: correctly. I think there is code to put at least bloom:editable divs in the correct real order.
If we need the display:none rules at all and need to override them, maybe we could use a variable (value pulled from calling stylesheet?) to determine what display: should be used to override none? I don't know whether that's possible. If not I think the override rule needs to stay in the book-specific/e-pub-specific stylesheets.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617#-:-KgPnkvR7a_oQ0k3qFHU:b-ftcnuc)*

**Comment by andrew-polk** [comment]
Yes, I'll see about adding a test for the scenario you described. Thanks for pointing that out.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookLayout/basePage-sharedRules.less, line 24 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617#-KgPmcPsFVgPtKkgnxp-:-KgQUTng9vIEPYw0IrMT:b-pj4j0t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/abcd8165c120883b480262e36ddd0264c24a868c/src/BloomBrowserUI/bookLayout/basePage-sharedRules.less#L24)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is this because we're using the epub css to figure visibility? Because shared is supposed to be for css that will actually be included in the epub, and we shouldn't need display:none rules there.
</blockquote></details>

Ok, so it appears I made a very bad assumption that the css used to determine visibility was the ePub one. But it is actually the basePage one.
So, I'll need to revert this and change the unit tests... again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617#-:-KgQUmF1NADMUjip1LNQ:bmiafod)*

**Comment by andrew-polk** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookLayout/basePage-sharedRules.less, line 24 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617#-KgPmcPsFVgPtKkgnxp-:-KgQfvMhOVpucEJKZ9eA:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/abcd8165c120883b480262e36ddd0264c24a868c/src/BloomBrowserUI/bookLayout/basePage-sharedRules.less#L24)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Ok, so it appears I made a very bad assumption that the css used to determine visibility was the ePub one. But it is actually the basePage one.
So, I'll need to revert this and change the unit tests... again.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617)*

**Comment by andrew-polk** [comment]
Test added, and I verified it failed with the old code.

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617#-:-KgQg0BfDPVh5o02b1Ny:b-7s864m)*

**Comment by andrew-polk** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomBrowserUI/bookLayout/basePage-sharedRules.less, line 30 at r2](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617#-KgPS6gMEnz6TeVIWSSd:-KgQg9GZbMGC-wWkmTEf:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/abcd8165c120883b480262e36ddd0264c24a868c/src/BloomBrowserUI/bookLayout/basePage-sharedRules.less#L30)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't think we want this in epubs, do we? Doubt very much that readers will handle flex or order: correctly. I think there is code to put at least bloom:editable divs in the correct real order.
If we need the display:none rules at all and need to override them, maybe we could use a variable (value pulled from calling stylesheet?) to determine what display: should be used to override none? I don't know whether that's possible. If not I think the override rule needs to stay in the book-specific/e-pub-specific stylesheets.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617)*

**Comment by JohnThomson** [comment]
Looking much better. Now I believe the functionality is right, I've made a few picky suggestions, but I realize this has already dragged on...feel free to act on or ignore any or all of them.

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookLayout/basePage.less, line 545 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617#-KgQi5OFK-3mubmoQd5m:-KgQi5OFK-3mubmoQd5n:b-j9bfie) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4823a2ba044391314edeb61a60b36d9dad7b3c4b/src/BloomBrowserUI/bookLayout/basePage.less#L545)):*
> ```Less
> // completely since some eReaders don't handle display:none properly.
> .epub.credits {
>     .licenseAndCopyrightBlock {
> ```

Very helpful comment. I'm puzzled about one thing, though: the class .epub suggests something that is epub-specific. I would not have expected a book to contain anything epub-specific. And if it does...why? Since this rule will cause it to be invisible in regular books and removed from epubs.
Aha...found it eventually. I think it would be helpful to add one more comment here that the epub class is added to the page element when constructing the dom used for epub visibility  checking.
Another option would be to have a distinct less file that is included in the visibility-checking DOM but not regular page editing (nor in the actual epub). This would save cluttering basePage.less with rules which never apply in normal operation, and might be more intuitive. Not something I feel strongly about, only if you like the idea enough to be bothered with it.

---

*[src/BloomBrowserUI/bookLayout/basePage.less, line 564 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617#-KgQitSV2B07GFlCkNPB:-KgQitSV2B07GFlCkNPC:b-3hl934) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4823a2ba044391314edeb61a60b36d9dad7b3c4b/src/BloomBrowserUI/bookLayout/basePage.less#L564)):*
> ```Less
> //Each .bloom-editable has a lang attribute to tell us what language it is in.
> //Each of these is assumed to be unwanted:
> .bloom-editable	{
> ```

I'm surprised this whole section is new. It doesn't seem to have been removed from anywhere...didn't we already have rules (language.css IIRC?) to do this or something similar? That's what the url above describes.

---

*[src/BloomTests/Publish/ExportEpubTests.cs, line 558 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617#-KgQni1VvVdDq8nlcV1T:-KgQni1VvVdDq8nlcV1U:bp055fm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4823a2ba044391314edeb61a60b36d9dad7b3c4b/src/BloomTests/Publish/ExportEpubTests.cs#L558)):*
> ```Smalltalk
> 		public void UserSpecifiedNoVernacular_VernacularRemoved()
> 		{
> 			// We are using real stylesheet info here to determine what should be visible, so the right classes must be carefully applied.
> ```

Suggest adding, "The critical point here is that passing defaultLanguages:N1 makes N1 the value of the data-default-languages attribute of the translation group, which makes only N1 (English) visible. We want to verify that this results in only that language being even PRESENT in the epub."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617#-:-KgQoFXtf18Ql5z0bo_Q:b-jfg2nr)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/BloomBrowserUI/bookLayout/basePage.less, line 545 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617#-KgQi5OFK-3mubmoQd5m:-KgQpJPs21SRtuWJXnKs:b-yc0ybf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4823a2ba044391314edeb61a60b36d9dad7b3c4b/src/BloomBrowserUI/bookLayout/basePage.less#L545)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Very helpful comment. I'm puzzled about one thing, though: the class .epub suggests something that is epub-specific. I would not have expected a book to contain anything epub-specific. And if it does...why? Since this rule will cause it to be invisible in regular books and removed from epubs.
Aha...found it eventually. I think it would be helpful to add one more comment here that the epub class is added to the page element when constructing the dom used for epub visibility  checking.
Another option would be to have a distinct less file that is included in the visibility-checking DOM but not regular page editing (nor in the actual epub). This would save cluttering basePage.less with rules which never apply in normal operation, and might be more intuitive. Not something I feel strongly about, only if you like the idea enough to be bothered with it.
</blockquote></details>

Yeah, I do like the idea. Thought of it, too. Briefly looked into what it would take, and it quickly started to look awkward. But, as you rightly point out, this is awkward, too. I'll take another look.

---

*[src/BloomBrowserUI/bookLayout/basePage.less, line 564 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617#-KgQitSV2B07GFlCkNPB:-KgQp_1Ui5urBCpIyXpT:b-a2yiee) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4823a2ba044391314edeb61a60b36d9dad7b3c4b/src/BloomBrowserUI/bookLayout/basePage.less#L564)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm surprised this whole section is new. It doesn't seem to have been removed from anywhere...didn't we already have rules (language.css IIRC?) to do this or something similar? That's what the url above describes.
</blockquote></details>

My guess is that Reviewable had a hard time giving you a good view of the various changes I have made. I originally moved this block to the shared file. Then I moved it back here. So, this is, in the end, unchanged.

Sorry for the confusion. I did verify by looking at the change in its entirety that what I am saying is true.

---

*[src/BloomTests/Publish/ExportEpubTests.cs, line 558 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617#-KgQni1VvVdDq8nlcV1T:-KgQrmbwDZ4c-k9p0hxU:bwtxt7i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4823a2ba044391314edeb61a60b36d9dad7b3c4b/src/BloomTests/Publish/ExportEpubTests.cs#L558)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Suggest adding, "The critical point here is that passing defaultLanguages:N1 makes N1 the value of the data-default-languages attribute of the translation group, which makes only N1 (English) visible. We want to verify that this results in only that language being even PRESENT in the epub."
</blockquote></details>

Good idea. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1617#-:-KgUVFuuBfKT_l6hvYd9:bnfp4nl)*

**Pull request merged**
