### PR TITLE
BL-5075 Move page label and layout toggle

### PR DESCRIPTION
**Pull request by gmartin7**
* created space above page (but not in thumbnail)
* moved the page label and origami toggle into space

There is a small problem when zooming in. Greater than 170% starts to scroll these off the screen. Anybody have any ideas how to fix that?

We weren't thinking of doing React here, were we?!

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2008)

### CODE REVIEW

**Comment by hatton** [comment]
> We weren't thinking of doing React here, were we?!

No more jquery, but this is just html dom, which is fine.

**Comment by JohnThomson** [comment]
Looks basically good. Couple of questions and comments. Did you manage to fix the >170% zoom problem?

---

Reviewed 3 of 7 files at r1, 2 of 5 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/css/editMode.less, line 15 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2008#-L-c0WBZpgXnGgJT0YOq:-L-c0WB_aYKRtaYT3-sV:b6kbo7b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/620934fdd4bf1a12f7aa94e8cd7a5373e97d09dc/src/BloomBrowserUI/bookEdit/css/editMode.less#L15)):*
> ```Less
> #labelAndLayoutPane
> {
>     height: 45px;
> ```

Do these other numbers have meanings and relationships that could be captured in variables and expressions?

---

*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 269 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2008#-L0KliQEuq4h-9Ybouv7:-L0KliQEuq4h-9Ybouv8:b-m8evcj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d07d1913ea6815498eb2b04854fdba7903d4eb9f/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L269)):*
> ```XML
>     // This used to check for "editMode", but that has been replaced by "bookcreationtype"
>     // by the time we get here.
>     if (!body.hasAttr("bookcreationtype")) {
> ```

Is this just fixing a bug that wasn't causing problems before for some reason? I don't see any changes that would CAUSE the body to have bookcreationtype instead of editMode.

---

*[src/BloomBrowserUI/bookEdit/js/origami.ts, line 99 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2008#-L0KlMY4sA3BTM-L280N:-L0KlMY55-4nE8j40w0G:bjz1lze) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d07d1913ea6815498eb2b04854fdba7903d4eb9f/src/BloomBrowserUI/bookEdit/js/origami.ts#L99)):*
> ```XML
> function layoutToggleClickHandler() {
>     var marginBox = $(".marginBox");
>     const toggleTransitionLength = 450; // 400ms CSS toggle transition + 50ms extra to get it working.
> ```

Maybe move declaration closer to the one place it's used? (If you're redoing anything else)

---

*[src/BloomBrowserUI/bookLayout/basePage.less, line 149 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2008#-L0Kkiei9C9OHnxJNCOT:-L0Kkiei9C9OHnxJNCOU:b-9c69ux) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d07d1913ea6815498eb2b04854fdba7903d4eb9f/src/BloomBrowserUI/bookLayout/basePage.less#L149)):*
> ```Less
>     Unfortunately, it also keeps us from moving the page label and origami toggle off of the page and
> up into its own space. Fortunately, we don't center text vertically anymore, so I think we're good! */
>     //overflow: hidden;
> ```

I don't really understand how this used to help, and I wonder whether all this should just be taken out rather than leaving a mess of comments about why we used to do something and no longer do. But, we CAN still center vertically, using the box format controls in origami mode...worth checking that this change doesn't somehow mess that up?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2008#-:-L0KmRVmaBDADq3y_-ka:b-bxroh1)*

**Comment by gmartin7** [comment]
No, I wasn't able to fix the zoom problem. Any ideas on that?

---

Review status: 9 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/BloomBrowserUI/bookEdit/css/editMode.less, line 15 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2008#-L-c0WBZpgXnGgJT0YOq:-L0L3kuTPVS_vZII0eVu:b-pxtmwq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/620934fdd4bf1a12f7aa94e8cd7a5373e97d09dc/src/BloomBrowserUI/bookEdit/css/editMode.less#L15)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Do these other numbers have meanings and relationships that could be captured in variables and expressions?
</blockquote></details>

I'm just seeing "@PageLabelAndChangeLayoutPaneHeight" here. What "other" numbers? Later revisions may have erased the ones you were seeing?

---

*[src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, line 269 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2008#-L0KliQEuq4h-9Ybouv7:-L0L4609fc-kt-pPYGrG:b-wjcr3e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d07d1913ea6815498eb2b04854fdba7903d4eb9f/src/BloomBrowserUI/bookEdit/js/bloomEditing.ts#L269)):*
> Is this just fixing a bug that wasn't causing problems before for some reason?
Yeah, apparently! Any time I stepped into this area, the body already had bookcreationtype and not editMode.
* There is one place in HtmlDom that removes a editMode body attribute, but no place that adds it, and no other place that "consumed" it.
* The only C# usage of bookcreationtype is HtmlDom which adds it. This spot in bloomEditing.ts is the only place that "consumes" bookcreationtype.

---

*[src/BloomBrowserUI/bookEdit/js/origami.ts, line 99 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2008#-L0KlMY4sA3BTM-L280N:-L0L6EgCoV_zmQNesKQ0:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d07d1913ea6815498eb2b04854fdba7903d4eb9f/src/BloomBrowserUI/bookEdit/js/origami.ts#L99)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Maybe move declaration closer to the one place it's used? (If you're redoing anything else)
</blockquote></details>

Done.

---

*[src/BloomBrowserUI/bookLayout/basePage.less, line 149 at r3](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2008#-L0Kkiei9C9OHnxJNCOT:-L0L9jXgH6tys6bkyIka:b-38z3nb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d07d1913ea6815498eb2b04854fdba7903d4eb9f/src/BloomBrowserUI/bookLayout/basePage.less#L149)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't really understand how this used to help, and I wonder whether all this should just be taken out rather than leaving a mess of comments about why we used to do something and no longer do. But, we CAN still center vertically, using the box format controls in origami mode...worth checking that this change doesn't somehow mess that up?
</blockquote></details>

Comments deleted. "Just text" page and other custom ones tested in center vertically mode. Seems fine in Edit, Publish and saved pdf.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2008#-:-L0KpqNt4Acci4WpBgN9:b8yn4a1)*

**Comment by JohnThomson** [comment]
Let's merge it and maybe then I can have a go.

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomBrowserUI/bookEdit/css/editMode.less, line 15 at r1](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2008#-L-c0WBZpgXnGgJT0YOq:-L0LJb1d8cdR7hKKPbCv:bqkeqcy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/620934fdd4bf1a12f7aa94e8cd7a5373e97d09dc/src/BloomBrowserUI/bookEdit/css/editMode.less#L15)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I'm just seeing "@PageLabelAndChangeLayoutPaneHeight" here. What "other" numbers? Later revisions may have erased the ones you were seeing?
</blockquote></details>

Yes, probably left over from earlier revisions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2008#-:-L0LJY1PbahG74uDcKVL:b-l7gtkn)*

**Pull request merged**
