### PR TITLE
Reliably match UI language against localizations (BL-5298)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2002)

### CODE REVIEW

**Comment by gmartin7** [comment]
:lgtm:, especially if "reliably" is accurate! :)

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2002#-:-L-JFWBf3JjL-0eBC2hN:bjaw4ub)*

**Comment by andrew-polk** [comment]
What is the downside of having the subdirectory name match the target language tag inside the xliff file?

If I am interpreting this change correctly (which I may not be), it means what seems a regression. I.e. with the old code, a user with UI culture es-AR would get the Spanish (es) automatically whereas with the new code he will not.

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2002#-:-L-WeLxT3ixjAadgG2ro:b8ezalw)*

**Comment by StephenMcConnel** [comment]
Apart from Chinese, we've been using the plain language tag without any country embellishment to emphasize that our localizations are supposed to be generic for the language and not specific to one particular variation like en-US vs en-UK (or es-ES vs es-AR).  However, crowdin seems to add a country tag automatically.  At least that's what appears to have happened for Spanish and Portuguese (but not for French).  I'm not sure how changing the Spanish and Portuguese file and directory names now would affect crowdin.  That's not a change I tested earlier.  I'd rather leave things as they are.

The new code still matches es-AR in the operation system user interface setup with es-ES in the localization file.  The IsSameActualLanguage strips both down to "es", and the code inside the loop records localeMatchingLanguage that (for example) es-ES satisfies es-AR close enough to be usable.  I have tested this by setting UserInterfaceCulture explicitly with a temporary line of code something like

UserInterfaceCulture = CultureInfo.GetCultureInfo("es-MX");

at the beginning of GetDesiredUiLanguage.

I've beefed up the comment where localeMatchingLanguage is set to explain it a bit better.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2002#-:-L-XT-VFm4QNSr9JqOwb:b8tm1gq)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/2002)*

**Pull request merged**
