### PR TITLE
BL-12162 Upload missing L1 to web gives warning

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216)* status: all files reviewed, 6 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 58 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216#-Niur1_f2n3PwVtwsJtg:-Niur1_f2n3PwVtwsJth:b-ktoudg) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/45998f5e785c519d9cb75e1cbc7ff1a949af4266/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L58)):*
> ```XML
>     licenseRights: string;
>     isTemplate: boolean;
>     titleOKToPublish: boolean; // This will be false if there is no L1 title, unless we don't need languages.
> ```

`isTitleOKToPublish` or `isTitleOkToPublish` please
___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 173 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216#-NiurQ648sB_y9p9Q7ik:-NiurQ648sB_y9p9Q7il:b-4vx43s) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/45998f5e785c519d9cb75e1cbc7ff1a949af4266/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L173)):*
> ```XML
>             !!bookInfo?.title &&
>             !!bookInfo?.copyright &&
>             !!bookInfo?.titleOKToPublish
> ```

I'm not understanding this logic.
The comment above states titleOkToPublish is false if there is no title, unless we don't need languages.

So, if we don't need languages, won't title be empty, and this will never be true?

Should this check for title be removed?
___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 410 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216#-NiurgRo7X6ZytUPIp2U:-NiurgRo7X6ZytUPIp2V:b-wpbxzp) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/45998f5e785c519d9cb75e1cbc7ff1a949af4266/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L410)):*
> ```XML
>             return <React.Fragment />;
>         }
>         if (!bookInfo.title || !bookInfo.titleOKToPublish) {
> ```

Should this check for title be removed?
___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 443 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216#-NiuqWMM-KpsXFMvxWL6:-NiuqWMM-KpsXFMvxWL7:b68h7vo) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b293452f35a37be91c9b0b08cc31751b32989df9/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L443)):*
> bookInfo?.isTemplate ||

Did you purposely remove this check? I don't understand why.
___
*[`src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs` line 124 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216#-Niurz4yD-8fnxCcZoe1:-Niurz4yD-8fnxCcZoe2:b-nidt51) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/45998f5e785c519d9cb75e1cbc7ff1a949af4266/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L124)):*
> ```Smalltalk
> 		internal dynamic ConflictingBookInfo => _uploader.GetBookOnServer(Book.FolderPath);
> 
> 		private bool BookHasL1Title()
> ```

Does this method want to live in Book?
___
*[`src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs` line 132 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216#-NiusDUt9Br5O9bOUzDi:-NiusDUt9Br5O9bOUzDj:bj0z0xo) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/45998f5e785c519d9cb75e1cbc7ff1a949af4266/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L132)):*
> ```Smalltalk
> 		}
> 
> 		internal bool TitleIsOKToPublish => OkToUploadWithNoLanguages || BookHasL1Title();
> ```

`IsTitleOKToPublish` or `IsTitleOkToPublish` please

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 58 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216#-Niur1_f2n3PwVtwsJtg:-Niv9wOx7DDDjme2YQuV:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/45998f5e785c519d9cb75e1cbc7ff1a949af4266/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L58)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

`isTitleOKToPublish` or `isTitleOkToPublish` please
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 173 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216#-NiurQ648sB_y9p9Q7ik:-NivAinIAhwIZhAk0eem:b-flo6qd) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/45998f5e785c519d9cb75e1cbc7ff1a949af4266/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L173)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not understanding this logic.
The comment above states titleOkToPublish is false if there is no title, unless we don't need languages.

So, if we don't need languages, won't title be empty, and this will never be true?

Should this check for title be removed?
</blockquote></details>

Yeah, probably. Done.
___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 410 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216#-NiurgRo7X6ZytUPIp2U:-NivBHsG3HpT-eLQQDMK:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/45998f5e785c519d9cb75e1cbc7ff1a949af4266/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L410)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should this check for title be removed?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 443 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216#-NiuqWMM-KpsXFMvxWL6:-Niv7dGz1pItk90683W-:bkm5yl6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b293452f35a37be91c9b0b08cc31751b32989df9/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L443)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> bookInfo?.isTemplate ||

Did you purposely remove this check? I don't understand why.
</blockquote></details>

I blame a bad merge. :( Good catch!
___
*[`src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs` line 124 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216#-Niurz4yD-8fnxCcZoe1:-Niv9F_O5yY9TKEUciBZ:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/45998f5e785c519d9cb75e1cbc7ff1a949af4266/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L124)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Does this method want to live in Book?
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs` line 132 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216#-NiusDUt9Br5O9bOUzDi:-Niv9QZWD9ztfRKBsed8:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/45998f5e785c519d9cb75e1cbc7ff1a949af4266/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L132)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

`IsTitleOKToPublish` or `IsTitleOkToPublish` please
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 443 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216#-NiuqWMM-KpsXFMvxWL6:-NivH9HvB5TF2OV815vT:bypbky8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b293452f35a37be91c9b0b08cc31751b32989df9/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L443)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I blame a bad merge. :( Good catch!
</blockquote></details>

My brain isn't smart enough to know if it changed the logic, but the parentheses changed. I'd feel more comfortable putting it back how it was.
___
*[`src/BloomExe/web/controllers/LibraryPublishApi.cs` line 98 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216#-NivHRBx5aTM2UJBBkAC:-NivHRBx5aTM2UJBBkAD:b-1of5ts) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d43240f44db75465d97bdfcdcd8d94bbc9301547/src/BloomExe/web/controllers/LibraryPublishApi.cs#L98)):*
> ```Smalltalk
> 				licenseRights = Model.LicenseRights,
> 				isTemplate = Model.IsTemplate,
> 				titleOKToPublish = Model.IsTitleOKToPublish
> ```

titleOKToPublish now needs to be isTitleOKToPublish to match the tsx

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 443 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216#-NiuqWMM-KpsXFMvxWL6:-Nj8aWImCjJnpLYt_A0M:bixonp) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b293452f35a37be91c9b0b08cc31751b32989df9/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L443)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

My brain isn't smart enough to know if it changed the logic, but the parentheses changed. I'd feel more comfortable putting it back how it was.
</blockquote></details>

I don't think it changed the logic, but OTOH, it's quite reasonable to keep it the way it was, especially since this wasn't what I was meaning to be changing!

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 443 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216#-NiuqWMM-KpsXFMvxWL6:-Nj8bygtAlqxQDom5piH:b-zcjvte) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/b293452f35a37be91c9b0b08cc31751b32989df9/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L443)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I don't think it changed the logic, but OTOH, it's quite reasonable to keep it the way it was, especially since this wasn't what I was meaning to be changing!
</blockquote></details>

Thanks

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/web/controllers/LibraryPublishApi.cs` line 98 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216#-NivHRBx5aTM2UJBBkAC:-Nj8cknnB94MTAWNdvxu:b-p02sov) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d43240f44db75465d97bdfcdcd8d94bbc9301547/src/BloomExe/web/controllers/LibraryPublishApi.cs#L98)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

titleOKToPublish now needs to be isTitleOKToPublish to match the tsx
</blockquote></details>

oops, missed this one. on it.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/web/controllers/LibraryPublishApi.cs` line 98 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216#-NivHRBx5aTM2UJBBkAC:-Nj8kAZFAcMt2TYk61-0:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d43240f44db75465d97bdfcdcd8d94bbc9301547/src/BloomExe/web/controllers/LibraryPublishApi.cs#L98)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

oops, missed this one. on it.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
