### PR TITLE
BL-3560 Command-line download of books

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1137)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/CLI/DownloadBookCommand.cs, line 54 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1137#-KM_dkXPP2-9IKTNYlgK:-KM_dkXPP2-9IKTNYlgL:-665244552) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9e7ba5eb92d31c4fb7679dc71c04a6cc6a90e101/src/BloomExe/CLI/DownloadBookCommand.cs#L54)):*
> ```Smalltalk
> 				Console.WriteLine(ex.Message);
> 				Console.WriteLine(ex.StackTrace);
> 				return -1;
> ```

HydrateBookCommand returns 1 in error state.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1137)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/CLI/DownloadBookCommand.cs, line 69 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1137#-KM_eLsUM1zkkyufl3Dd:-KM_eLsVWd89bpQPfLUz:-547950420) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9e7ba5eb92d31c4fb7679dc71c04a6cc6a90e101/src/BloomExe/CLI/DownloadBookCommand.cs#L69)):*
> ```Smalltalk
> 
> 	[Option("url", HelpText = "url of folder on S3, e.g., https://s3.amazonaws.com/BloomLibraryBooks/andrew_polk@sil.org/0a2745dd-ca98-47ea-8ba4-2cabc67022e5", Required = true)]
> 	public string Url { get; set; }
> ```

does andrew want his email there?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1137)*

**Comment by hatton** [comment]
Maybe it's not feasible to have a unit test?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1137#-:-KM_e_STWh0jnlFfIseF:972805959)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/CLI/DownloadBookCommand.cs, line 69 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1137#-KM_eLsUM1zkkyufl3Dd:-KM_eatERblwso2Xzg5R:-1047866268) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9e7ba5eb92d31c4fb7679dc71c04a6cc6a90e101/src/BloomExe/CLI/DownloadBookCommand.cs#L69)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary>
> does andrew want his email there?
</details>
I didn't care enough to bring it up, but preferably no.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1137)*

**Comment by JohnThomson** [comment]
Fixed two minor issues and modified an existing unit test to exercise the new code.

---

Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/BloomExe/CLI/DownloadBookCommand.cs, line 54 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1137#-KM_dkXPP2-9IKTNYlgK:-KMjrinWR4j55FYGCOMx:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9e7ba5eb92d31c4fb7679dc71c04a6cc6a90e101/src/BloomExe/CLI/DownloadBookCommand.cs#L54)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> HydrateBookCommand returns 1 in error state.
</details>
Done.

---

*[src/BloomExe/CLI/DownloadBookCommand.cs, line 69 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1137#-KM_eLsUM1zkkyufl3Dd:-KMjrdpZzZRAuPWrvv42:-499146009) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9e7ba5eb92d31c4fb7679dc71c04a6cc6a90e101/src/BloomExe/CLI/DownloadBookCommand.cs#L69)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> I didn't care enough to bring it up, but preferably no.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1137#-:-KMju2RAez0VQyF3G380:-380989885)*

**Comment by andrew-polk** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/CLI/DownloadBookCommand.cs, line 69 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1137#-KM_eLsUM1zkkyufl3Dd:-KMju_IBlbpweKFeS-gY:1456539106) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9e7ba5eb92d31c4fb7679dc71c04a6cc6a90e101/src/BloomExe/CLI/DownloadBookCommand.cs#L69)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary>
> Done.
</details>
Looks like this was changed in the comment in BookTransfer, but not here in the usage information

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1137)*

**Comment by JohnThomson** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/BloomExe/CLI/DownloadBookCommand.cs, line 69 \[r1\]](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1137#-KM_eLsUM1zkkyufl3Dd:-KMjxmfnJqGU-uXiEJUi:-272270098) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9e7ba5eb92d31c4fb7679dc71c04a6cc6a90e101/src/BloomExe/CLI/DownloadBookCommand.cs#L69)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary>
> Looks like this was changed in the comment in BookTransfer, but not here in the usage information
</details>
Sorry. Fixed now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1137)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1137)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1137#-:-KMjyQleYe6XgUJpvAXW:1417088721)*

**Pull request merged**
