### PR TITLE
Restore hiding comic bubbles for image description tool (BL-9944)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4487)

### CODE REVIEW

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4487)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookLayout/bubble.less, line 237 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4487#-MaU-GXI70eoNhRj1cKe:-MaU-GXI70eoNhRj1cKf:btt3vlb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9ac666a609a07c8ee2d7c500fd4ed217e584304c/src/BloomBrowserUI/bookLayout/bubble.less#L237)):*
> ```Less
> 
> // Make this rule very specific because we have some quite complex rules to make certain bubbles display:flex and this needs to win.
> .bloom-showImageDescriptions.bloom-showImageDescriptions.bloom-showImageDescriptions.bloom-showImageDescriptions.bloom-showImageDescriptions {
> ```

OK, totally holding my nose here as I approve. Presumably !important didn't work?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4487)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomBrowserUI/bookLayout/bubble.less, line 237 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4487#-MaU-GXI70eoNhRj1cKe:-MaUtH1OCy2uY4JNyDRU:bsyhr22) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9ac666a609a07c8ee2d7c500fd4ed217e584304c/src/BloomBrowserUI/bookLayout/bubble.less#L237)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

OK, totally holding my nose here as I approve. Presumably !important didn't work?
</blockquote></details>

No, I just think of !important as a last resort. But quite possibly the right answer here.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4487)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/bookLayout/bubble.less, line 237 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4487#-MaU-GXI70eoNhRj1cKe:-MaUxJx18Bd-HWYAkxse:b-jplysq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9ac666a609a07c8ee2d7c500fd4ed217e584304c/src/BloomBrowserUI/bookLayout/bubble.less#L237)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

No, I just think of !important as a last resort. But quite possibly the right answer here.
</blockquote></details>

This is a definite hack (though useful!) Why wouldn't we use the *normal* approach first?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4487)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomBrowserUI/bookLayout/bubble.less, line 237 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4487#-MaU-GXI70eoNhRj1cKe:-MaV6BdP3334C_g-KquB:b-ggg1xf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9ac666a609a07c8ee2d7c500fd4ed217e584304c/src/BloomBrowserUI/bookLayout/bubble.less#L237)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This is a definite hack (though useful!) Why wouldn't we use the *normal* approach first?
</blockquote></details>

If I make a rule !important, anything that wants to override it has to be !important too, so it can spread in ugly ways. But I don't think it will here; hiding bubbles when we're showing image descriptions is surely all-or-nothing. So I was applying a coding practice in the wrong context. Sorry. Fixed.

**Pull request merged**
