### PR TITLE
Disable TC functionality when not appropriate (BL-9644)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4254)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4254)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/CollectionTab/LibraryView.cs, line 29 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4254#-MV3bc_bDQOp9_Ncar4A:-MV3bc_bDQOp9_Ncar4B:b-2eu8uz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34b65cd637d5dba5cb4e7518ad5e8a5152e45ecc/src/BloomExe/CollectionTab/LibraryView.cs#L29)):*
> ```
> BookStatusChangeEvent bookStatusChangeEvent
> ```
Probably worth cleaning this up?
___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 233 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4254#-MV3cSeD35fLx2w8gfSc:-MV3cSeD35fLx2w8gfSd:b-mhqxw6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34b65cd637d5dba5cb4e7518ad5e8a5152e45ecc/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L233)):*
> ```
> string.IsNullOrEmpty(CurrentUser)
> ```
Should we move TeamCollection.IsRegistrationSufficient() up to TeamCollectionManager and call that?
___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 236 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4254#-MV3cofm0PWLkccVqL0O:-MV3cofm0PWLkccVqL0P:b-3veaky) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34b65cd637d5dba5cb4e7518ad5e8a5152e45ecc/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L236)):*
> ```
> Most Team Collection functions are unavailable because you have not registered Bloom.
> ```
Technically they might have registered, just without an email address. But since all our messages are not solidified, not sure it is worth changing.
___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 241 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4254#-MV3d1aF7y8G14RbeKKs:-MV3d1aF7y8G14RbeKKt:bbbkhd4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34b65cd637d5dba5cb4e7518ad5e8a5152e45ecc/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L241)):*
> ```
> CurrentCollection = null; // This neatly disables almost everything
> ```
I wonder if it is worth taking out some checks for TeamCollection.IsRegistrationSufficient() elsewhere now?

Hm... as I thought about this more, I don't think we can because the user can "unregister" at any time.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4254)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4254)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/CollectionTab/LibraryView.cs, line 29 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4254#-MV3bc_bDQOp9_Ncar4A:-MVICr45BIWcJ6OH5mG2:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34b65cd637d5dba5cb4e7518ad5e8a5152e45ecc/src/BloomExe/CollectionTab/LibraryView.cs#L29)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> BookStatusChangeEvent bookStatusChangeEvent
> ```
Probably worth cleaning this up?
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 233 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4254#-MV3cSeD35fLx2w8gfSc:-MVIB26x-Qd7k65WaxV4:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34b65cd637d5dba5cb4e7518ad5e8a5152e45ecc/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L233)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> string.IsNullOrEmpty(CurrentUser)
> ```
Should we move TeamCollection.IsRegistrationSufficient() up to TeamCollectionManager and call that?
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 236 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4254#-MV3cofm0PWLkccVqL0O:-MVIB11A1XPJTm-Z3IDh:bq0hmiu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34b65cd637d5dba5cb4e7518ad5e8a5152e45ecc/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L236)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Most Team Collection functions are unavailable because you have not registered Bloom.
> ```
Technically they might have registered, just without an email address. But since all our messages are not solidified, not sure it is worth changing.
</blockquote></details>

modifeid
___
*[src/BloomExe/TeamCollection/TeamCollectionManager.cs, line 241 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4254#-MV3d1aF7y8G14RbeKKs:-MVI7nlk0joxkyLhY-3K:bhijf4z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/34b65cd637d5dba5cb4e7518ad5e8a5152e45ecc/src/BloomExe/TeamCollection/TeamCollectionManager.cs#L241)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> CurrentCollection = null; // This neatly disables almost everything
> ```
I wonder if it is worth taking out some checks for TeamCollection.IsRegistrationSufficient() elsewhere now?

Hm... as I thought about this more, I don't think we can because the user can "unregister" at any time.
</blockquote></details>

I think you're right. Though another option would be that in a TC the dialog will not allow you to change it to something unacceptable. But that would be a more drastic changes, especially as the dialog is in LibPalaso.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4254)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
