### PR TITLE
Fix TeamCollectionApi test

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5136)

### CODE REVIEW

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5136)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gmartin7 and @sujeffreyl)

___
*[`src/BloomExe/TeamCollection/TeamCollectionApi.cs` line 354 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5136#-N0lP5aTCJhb1r21J4M_:-N0lQpoY0mwQ3mzpAcRt:b-gmyl0z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8292e1b3f9cc732f1ea3d563f2c740279931d675/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L354)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I don't think we want to handle it this way. So, it seems to me that this test is testing the case where the book is null (and we're now making that okay). But, since this code throws the exception, it seems that currentBook is normally not null. (Unless there can be valid non-test situations where book is null? In that case, then the comment needs to be fixed instead).

I think we want to mock a book and have it return true.

Also, for bonus points, it seems to me like the system under test (selectedBookStatus) wants a test testing the situation where the book is not saveable.
</blockquote></details>

I think something like this in the failing unit test:


var book = new Mock<Bloom.Book.Book>();
				book.Setup(m => m.IsSaveable).Returns(true);
				var mockBookSelection = new Mock<BookSelection>();
				mockBookSelection.Setup(m => m.CurrentSelection).Returns(book.Object);
				var apiBuilder = new TeamCollectionApiBuilder().WithDefaultMocks(true).WithBookSelection(mockBookSelection.Object);

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5136)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gmartin7 and @sujeffreyl)

___
*[`src/BloomExe/TeamCollection/TeamCollectionApi.cs` line 354 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5136#-N0lP5aTCJhb1r21J4M_:-N0lR-a886f76NKVnSG3:b-gwbowc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8292e1b3f9cc732f1ea3d563f2c740279931d675/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L354)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I think something like this in the failing unit test:


var book = new Mock<Bloom.Book.Book>();
				book.Setup(m => m.IsSaveable).Returns(true);
				var mockBookSelection = new Mock<BookSelection>();
				mockBookSelection.Setup(m => m.CurrentSelection).Returns(book.Object);
				var apiBuilder = new TeamCollectionApiBuilder().WithDefaultMocks(true).WithBookSelection(mockBookSelection.Object);
</blockquote></details>

Some greater than signs got eaten in my last post.  On the 3rd line, it should be new Mock &lt;BookSelection&gt;();

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5136)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gmartin7 and @sujeffreyl)

___
*[`src/BloomExe/TeamCollection/TeamCollectionApi.cs` line 354 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5136#-N0lP5aTCJhb1r21J4M_:-N0lRGWO-6KaPEMlsehi:b-5dgb27) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8292e1b3f9cc732f1ea3d563f2c740279931d675/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L354)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Some greater than signs got eaten in my last post.  On the 3rd line, it should be new Mock &lt;BookSelection&gt;();
</blockquote></details>

variable name book -> mockBook

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5136)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[`src/BloomExe/TeamCollection/TeamCollectionApi.cs` line 354 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5136#-N0lP5aTCJhb1r21J4M_:-N0ln9pn7mk_6kqZUmBi:bdax1yb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8292e1b3f9cc732f1ea3d563f2c740279931d675/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L354)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Done. Thanks for the mock code. I wouldn't have known where to start.
</blockquote></details>

Oops. The comment still says three scenarios.

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5136)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/TeamCollection/TeamCollectionApi.cs` line 354 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5136#-N0lP5aTCJhb1r21J4M_:-N0luufoDoIWhNtYuoDL:b-3vrvpn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8292e1b3f9cc732f1ea3d563f2c740279931d675/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L354)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Oops. The comment still says three scenarios.
</blockquote></details>

Looks good other than Andrew's comment

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5136)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @sujeffreyl)

___
*[`src/BloomExe/TeamCollection/TeamCollectionApi.cs` line 354 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5136#-N0lP5aTCJhb1r21J4M_:-N0lwGU19a6GdjoJxvGy:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8292e1b3f9cc732f1ea3d563f2c740279931d675/src/BloomExe/TeamCollection/TeamCollectionApi.cs#L354)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Looks good other than Andrew's comment
</blockquote></details>

Done.

**Pull request merged**
