### PR TITLE
BL-9949 TC Book Status problem state

### PR DESCRIPTION
**Pull request by gmartin7**
* add story
* fix overflow
* submitted as draft until UI Review

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4513)

### CODE REVIEW

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4513)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomBrowserUI/bookPreview/BookPreviewPanel.less, line 7 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4513#-Maokr5b3hwBpZTWJITA:-Maokr5b3hwBpZTWJITB:b-4opbef) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4636a02c08ec231d067da33085436d870d7412b1/src/BloomBrowserUI/bookPreview/BookPreviewPanel.less#L7)):*
> ```Less
>     // We want the preview to take up the available space, limiting the Team Collection panel
>     // (if present) to what it needs.
>     flex: 4;
> ```

This is the key factor. A lower number will allow the status panel to grow > 180px tall and not scroll at all. Perhaps that is preferable? But then all the other states (besides 'problem') will use more space than they need. A higher number will tend to squish the status panel in other states to their minimum needed height (sometimes too flat?) and the 'problem' state will still scroll. I believe 4 is the right balance, but I could be persuaded otherwise.

**Comment by andrew-polk** [comment]
___
*[src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, line 99 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4513#-Mb8erxP957fsOLt9tty:-Mb8erxP957fsOLt9ttz:b9unqpo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d39a366d5a3a851b8763f9ad77f6d78a6dbb46ac/src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx#L99)):*
> ```
> don't commit this!!!
> ```
oops

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4513)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, line 99 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4513#-Mb8erxP957fsOLt9tty:-MbC5MRs9u7OxBuSeYSR:b3nux46) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d39a366d5a3a851b8763f9ad77f6d78a6dbb46ac/src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx#L99)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> don't commit this!!!
> ```
oops
</blockquote></details>

Oh Wow! thx.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4513)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @gmartin7)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4513)* status: all files reviewed, 3 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomBrowserUI/bookPreview/BookPreviewPanel.less, line 8 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4513#-MbCkrs1AZELWwY2T58a:-MbCkrs1AZELWwY2T58b:b-dg7t6f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c3275d3a5e50f8f6f565b60c11d381b3c5035b38/src/BloomBrowserUI/bookPreview/BookPreviewPanel.less#L8)):*
> ```
>     display: flex;
>     ...
>     flex-direction: column;
> ```
These two lines don't actually do anything, do they?
___
*[src/BloomBrowserUI/bookPreview/BookPreviewPanel.less, line 14 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4513#-MbCkTII5iL04adUakN2:-MbCkTII5iL04adUakN3:b-x9cqnk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c3275d3a5e50f8f6f565b60c11d381b3c5035b38/src/BloomBrowserUI/bookPreview/BookPreviewPanel.less#L14)):*
> ```
> preview-panel
> ```
I would like to clarify this somehow. Maybe something like `preview-and-status-container`? And should it be an ID rather than class?
Also, I think it would provide some clarity to put the #preview stuff inside this so it is clear that this is a container which includes that.
___
*[src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.less, line 10 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4513#-MbCjHBo0qaejcpeG2TM:-MbCjHBpABCugE2LNLsc:bj5th93) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c3275d3a5e50f8f6f565b60c11d381b3c5035b38/src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.less#L10)):*
> ```Less
>     display: flex;
>     flex-direction: column;
>     flex: 1; // less than the 4 of the preview panel, so it will limit itself to what it needs.
> ```

Doesn't this mean the bottom panel will grow proportionately to always be 20% of the available space? So I don't think the comment is accurate?

I guess you've tested with a smaller window?
Do we need a min-height? And/or do we need to set the top portion to allow shrink?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4513)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookPreview/BookPreviewPanel.less, line 8 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4513#-MbCkrs1AZELWwY2T58a:-MbDVgPW21wSvJK1Q_N9:bwdjso8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c3275d3a5e50f8f6f565b60c11d381b3c5035b38/src/BloomBrowserUI/bookPreview/BookPreviewPanel.less#L8)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
>     display: flex;
>     ...
>     flex-direction: column;
> ```
These two lines don't actually do anything, do they?
</blockquote></details>

Hmm... maybe not.
___
*[src/BloomBrowserUI/bookPreview/BookPreviewPanel.less, line 14 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4513#-MbCkTII5iL04adUakN2:-MbDWFjf-DYuAdD1PzoN:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c3275d3a5e50f8f6f565b60c11d381b3c5035b38/src/BloomBrowserUI/bookPreview/BookPreviewPanel.less#L14)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> preview-panel
> ```
I would like to clarify this somehow. Maybe something like `preview-and-status-container`? And should it be an ID rather than class?
Also, I think it would provide some clarity to put the #preview stuff inside this so it is clear that this is a container which includes that.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.less, line 10 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4513#-MbCjHBo0qaejcpeG2TM:-MbDXJQyE_7aOFiPaHbl:b-hx511c) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c3275d3a5e50f8f6f565b60c11d381b3c5035b38/src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.less#L10)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Doesn't this mean the bottom panel will grow proportionately to always be 20% of the available space? So I don't think the comment is accurate?

I guess you've tested with a smaller window?
Do we need a min-height? And/or do we need to set the top portion to allow shrink?
</blockquote></details>

My testing shows that it's more complicated than simply 20% of the available space. It's more like, if there's extra space available (beyond what's needed in the two areas already), this area is likely to receive 20% of the extra space. In practice, the comment is fairly accurate. For instance, the "problem" state version doesn't seem to change size at all. It's already had to grow some to accommodate the extra text. The other versions of the panel will grow to about 180px height, but if the window is smaller they will actually shrink some because they have extra space.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4513)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
