### PR TITLE
Improve Book-on-Blorg badge operations (BL-12404)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Why do we need all three of
1. Update status when a book is uploaded.
2. Update status when finishing a bulk upload.
3. Update status when switching from publish tab to collection tab.

?

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-:-NfIAU090oIlxdx_zJU3:b-76mc2t)* status: all files reviewed, 7 unresolved discussions (waiting on @StephenMcConnel)

___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 307 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-NfI8HEm6Kcz9cbq5ENJ:-NfI8HEm6Kcz9cbq5ENK:b-ew9xg) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/aa319972d8eec0ed8d37b3300ec6bad32955815e/DistFiles/localization/en/BloomMediumPriority.xlf#L307)):*
> ```XML
>       </trans-unit>
>       <trans-unit id="CollectionTab.OnBlorgBadge.Harvesting" sil:dynamic="true" translate="no">
>         
> ```

I know you're just following the pattern here, but I'm not seeing value added for all these "Added in 5.6" comments.
Is there one I'm not seeing?
___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 308 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-NfIBdVNBilAUYIr5_0r:-NfIBdVNBilAUYIr5_0s:borrgvs) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/aa319972d8eec0ed8d37b3300ec6bad32955815e/DistFiles/localization/en/BloomMediumPriority.xlf#L308)):*
> Harvesting in Progress

I'm unsure about this message.
I don't think we use the term "harvesting" with users so far.

Here are the relevant strings on blorg:
"We apologize for the inconvenience, but our server seems to be having problems processing newly uploaded books."
"This book has recently arrived in the Bloom Library and should be processed soon. Please check back in a few minutes."
"Our server encountered a problem while processing this book. The developers have been notified."

That would make me think of something like "Processing" or "Being processed".

@hatton What do you think the message should be on the tooltip for a book being processed?
___
*[`src/BloomExe/Book/BloomLibraryStatus.cs` line 20 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-NfICw27-PJunUdYhlah:-NfICw27-PJunUdYhlai:bub9td) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/aa319972d8eec0ed8d37b3300ec6bad32955815e/src/BloomExe/Book/BloomLibraryStatus.cs#L20)):*
> ```Smalltalk
> 	}
> 
> 	public class BloomLibraryStatus : IBloomLibraryStatus
> ```

Why do we need all the equality boilerplate and the interface?
Might warrant comments.
___
*[`src/BloomExe/Collection/BookCollection.cs` line 450 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-NfIDv9Q6YGmo9S-Hw7T:-NfIDv9Q6YGmo9S-Hw7U:btp6oy6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/aa319972d8eec0ed8d37b3300ec6bad32955815e/src/BloomExe/Collection/BookCollection.cs#L450)):*
> unless told not to

This makes me think maybe it should be called something like `skipBadgeUpdate`? 
___
*[`src/BloomExe/Collection/BookCollection.cs` line 480 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-NfIEvNd7fwJdyZvWIxI:-NfIEvNd7fwJdyZvWIxJ:bh30d1i) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/aa319972d8eec0ed8d37b3300ec6bad32955815e/src/BloomExe/Collection/BookCollection.cs#L480)):*
> ```Smalltalk
> 					}
> 					queryBldr.Clear();
> 					queryBldr.Append("{\"bookInstanceId\":{\"$in\":[\"");
> ```

How feasible is it to move the parse-specific stuff into BloomParseClient?
Probably easier to move the whole `for` loop?
___
*[`src/BloomExe/Collection/BookCollection.cs` line 514 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-NfIDVeV2EYYMP0uB08_:-NfIDVeV2EYYMP0uB08a:b-ssnnyp) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/aa319972d8eec0ed8d37b3300ec6bad32955815e/src/BloomExe/Collection/BookCollection.cs#L514)):*
> ```Smalltalk
> 		}
> 
> 		private static BloomLibraryStatus GetBloomLibraryStatusFromDynamicJson(dynamic bookState)
> ```

I think this method might be better in BloomLibraryStatus. 
Thoughts?
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 483 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-NfIGq0T1pQmerNf83aW:-NfIGq0T1pQmerNf83aX:b-zczljm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2bdbe59234e42e328275ddb9566abcf6a2b89df0/src/BloomExe/web/controllers/CollectionApi.cs#L483)):*
> ```Smalltalk
> 				apiRequest.ReplyWithJson(new
> 				{
> 					bookUrl = BloomLibraryUrls.BloomLibraryBooksWithMatchingIdListingUrl(bookId),
> ```

We seem to have lost this state which indicated that there was more than one book with the same bookInstanceId.

**Review by andrew-polk — COMMENTED** [review]
@hatton 
I think it would be value-added for you to take a look at this PR from your high-level perspective.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-:-NfINprvCoZ2UIE7V6wU:b-c08oss)* status: all files reviewed, 7 unresolved discussions (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
I suspect this update is needed mostly when switching from publish to collection tab.  But I don't think that Bloom enforces waiting for bulk upload to finish to switch tabs because bulk upload is running in a separate console window.  So signaling when bulk upload finishes may still be a good idea.  (Of course, we don't really know when bulk upload finishes, just when the user closes the console window.)

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-:-NfIZn-Z6qJZAqhALrfv:b4ssbs4)* status: all files reviewed, 7 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 307 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-NfI8HEm6Kcz9cbq5ENJ:-NfIQGLG0fzCAlp-08bd:b69dbh1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/aa319972d8eec0ed8d37b3300ec6bad32955815e/DistFiles/localization/en/BloomMediumPriority.xlf#L307)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I know you're just following the pattern here, but I'm not seeing value added for all these "Added in 5.6" comments.
Is there one I'm not seeing?
</blockquote></details>

At this point, there's probably not much value added.  I removed this comment but didn't disturb the existing ones.
___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 308 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-NfIBdVNBilAUYIr5_0r:-NfIQhnV5krT7aT-DZ7o:bqkcpmv) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/aa319972d8eec0ed8d37b3300ec6bad32955815e/DistFiles/localization/en/BloomMediumPriority.xlf#L308)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> Harvesting in Progress

I'm unsure about this message.
I don't think we use the term "harvesting" with users so far.

Here are the relevant strings on blorg:
"We apologize for the inconvenience, but our server seems to be having problems processing newly uploaded books."
"This book has recently arrived in the Bloom Library and should be processed soon. Please check back in a few minutes."
"Our server encountered a problem while processing this book. The developers have been notified."

That would make me think of something like "Processing" or "Being processed".

@hatton What do you think the message should be on the tooltip for a book being processed?
</blockquote></details>

I've provisionally changed the message to "Being processed"
___
*[`src/BloomExe/Book/BloomLibraryStatus.cs` line 20 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-NfICw27-PJunUdYhlah:-NfIR7my5tGzcmSOPsC0:b-186joq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/aa319972d8eec0ed8d37b3300ec6bad32955815e/src/BloomExe/Book/BloomLibraryStatus.cs#L20)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Why do we need all the equality boilerplate and the interface?
Might warrant comments.
</blockquote></details>

I'm happy to ditch the interface. The only reason it's there is that the issue specifically mentioned an interface.  (This particular interface seems like more trouble than it's worth since I can't conceive of a different implementation ever happening, and at least one place in the code requires casting the interface to the implementation class.)
The equality overrides are to ensure that checking for equality is value-based and not reference-based.  That is probably worth mentioning.
___
*[`src/BloomExe/Collection/BookCollection.cs` line 450 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-NfIDv9Q6YGmo9S-Hw7T:-NfIUlzV16XdKHEn6FhY:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/aa319972d8eec0ed8d37b3300ec6bad32955815e/src/BloomExe/Collection/BookCollection.cs#L450)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> unless told not to

This makes me think maybe it should be called something like `skipBadgeUpdate`?
</blockquote></details>

Done.
___
*[`src/BloomExe/Collection/BookCollection.cs` line 480 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-NfIEvNd7fwJdyZvWIxI:-NfIYCpH41ZKCyS2yAu2:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/aa319972d8eec0ed8d37b3300ec6bad32955815e/src/BloomExe/Collection/BookCollection.cs#L480)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

How feasible is it to move the parse-specific stuff into BloomParseClient?
Probably easier to move the whole `for` loop?
</blockquote></details>

Done.
___
*[`src/BloomExe/Collection/BookCollection.cs` line 514 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-NfIDVeV2EYYMP0uB08_:-NfIYc8g60JqwVSip_MI:bo3bjhg) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/aa319972d8eec0ed8d37b3300ec6bad32955815e/src/BloomExe/Collection/BookCollection.cs#L514)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this method might be better in BloomLibraryStatus. 
Thoughts?
</blockquote></details>

Done.  Either there or BloomParseServer possibly.  But probably better in BloomLibraryStatus.
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 483 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-NfIGq0T1pQmerNf83aW:-NfIa8aX90DJVyBpDEGZ:b-e28svi) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2bdbe59234e42e328275ddb9566abcf6a2b89df0/src/BloomExe/web/controllers/CollectionApi.cs#L483)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We seem to have lost this state which indicated that there was more than one book with the same bookInstanceId.
</blockquote></details>

This state actually indicated that either no book exist with this bookInstanceId or more than one book with the same bookInstanceId exist.  This state (multiple books with same bookInstanceId) needs to be handled in BloomParseClient.GetLibraryStatusForBooks().  I've fixed the code there.
No book uploaded is marked by a null for BloomLibraryStatus object.  Multiple books are marked by an empty string for the book's url, with the other values being rather meaningless.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115)* status: 9 of 15 files reviewed, 7 unresolved discussions (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 308 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-NfIBdVNBilAUYIr5_0r:-NfIl7Kj56FppoNKM0SJ:b9qfrve) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/aa319972d8eec0ed8d37b3300ec6bad32955815e/DistFiles/localization/en/BloomMediumPriority.xlf#L308)):*
"Preparing" probably would have been better, but to stay consistent,

> BloomLibrary.org is processing this book

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 483 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-NfIGq0T1pQmerNf83aW:-NfMnWW0A3Ek1GGGZ32u:b-zgm3p1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2bdbe59234e42e328275ddb9566abcf6a2b89df0/src/BloomExe/web/controllers/CollectionApi.cs#L483)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

This state actually indicated that either no book exist with this bookInstanceId or more than one book with the same bookInstanceId exist.  This state (multiple books with same bookInstanceId) needs to be handled in BloomParseClient.GetLibraryStatusForBooks().  I've fixed the code there.
No book uploaded is marked by a null for BloomLibraryStatus object.  Multiple books are marked by an empty string for the book's url, with the other values being rather meaningless.
</blockquote></details>

Sorry, something is still lost.
We no longer ever use `BloomLibraryUrls.BloomLibraryBooksWithMatchingIdListingUrl(bookId)` which is a special url useful for viewing multiple books which all have the same bookInstanceId. I'm not sure how this is going to work with the new architecture... maybe we just need a new status? Happy to discuss if that would be helpful.

**Review by StephenMcConnel — COMMENTED** [review]
I decided the update is needed only when switching to the collection tab, whether coming from publish or edit.  The refresh menu command works in the collection tab, and the refresh thumbnail menu command works for individual books.  Since updating won't actually trigger refreshes when not in the collection tab, I simplified the code to just update when changing to the collection tab.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-:-NfSnsrK8xEmElyU8NVn:b52ch8i)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 308 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-NfIBdVNBilAUYIr5_0r:-NfRMef79JyOPv7coRRd:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/aa319972d8eec0ed8d37b3300ec6bad32955815e/DistFiles/localization/en/BloomMediumPriority.xlf#L308)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

"Preparing" probably would have been better, but to stay consistent,

> BloomLibrary.org is processing this book
</blockquote></details>

Done.
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 483 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-NfIGq0T1pQmerNf83aW:-NfRSd1j5Y5PC7bwsUVB:bbw4ysz) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2bdbe59234e42e328275ddb9566abcf6a2b89df0/src/BloomExe/web/controllers/CollectionApi.cs#L483)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry, something is still lost.
We no longer ever use `BloomLibraryUrls.BloomLibraryBooksWithMatchingIdListingUrl(bookId)` which is a special url useful for viewing multiple books which all have the same bookInstanceId. I'm not sure how this is going to work with the new architecture... maybe we just need a new status? Happy to discuss if that would be helpful.
</blockquote></details>

Done.  I've added an artificial harvest state of `Multiple` and used that to trigger the "problem" badge (aka `BadgeType.OutOfCirculation`).  Multiple books with the same id now get stamped with the new harvest state and generate the proper url with `BloomLibraryUrls.BloomLibraryBooksWithMatchingIdListingUrl(bookId)`.
If the current has not been uploaded, but another book with the same instance id has been uploaded, then the badge will just look like what the other book's state indicates.  I don't think that's a regression, and I don't think there's any way to prevent it without persisting book objectIds and checking them.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r4, 1 of 16 files at r5, 15 of 15 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`build/getDependencies-windows.sh` line 1 at r6](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-Nhd01_F5v-W7qdhfwve:-Nhd01_F5v-W7qdhfwvf:b-abcu1r) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/194d7e09316e866b1888c971eca8408cad85ea25/build/getDependencies-windows.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

This is trying to pull in changes which are in master but not Version5.6.

Sorry, I probably messed you up by retargeting the PR to Version5.6.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115)* status: 18 of 19 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`build/getDependencies-windows.sh` line 1 at r6](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115#-Nhd01_F5v-W7qdhfwve:-Nhd4poTE40SdFGRSIzc:b-8l34dt) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/194d7e09316e866b1888c971eca8408cad85ea25/build/getDependencies-windows.sh#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This is trying to pull in changes which are in master but not Version5.6.

Sorry, I probably messed you up by retargeting the PR to Version5.6.
</blockquote></details>

I think I've gotten it fixed, but it's hard to tell from this view.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6115)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
