### PR TITLE
Various places we don't want to copy book.status (BL-9778)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4348)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4348)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1110 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4348#-MXn0GOz93tx09gPZ6so:-MXn0GOz93tx09gPZ6sp:b-61bl5n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2d8f91ce9ab2749f9b8c34d7deec90bde0358dd3/src/BloomExe/TeamCollection/TeamCollection.cs#L1110)):*
> ```Smalltalk
> 		}
> 
> 		public static void DeleteLocalStatus(string bookFolderPath)
> ```

I think it's worth being more abstract; other code has *no business* knowing about status. But it is reasonable to know that maybe there is something that a book should do to prepare itself for going *elsewhere*, be that S3, bloomd, bloom pack, etc.

Conceptually, the book itself or Storage, should have a method to do this. Something like `BookStorage.RemoveLocalOnlyFiles()`.  That code could then call  something like`TC.RemoveTCSpecificFiles()` ?  

Note, the code that prepares books for epub, bloompub, etc. may also need to call the book on the method?
___
*[src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, line 257 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4348#-MXn-yPL56weSW8w9L0Q:-MXn-yPL56weSW8w9L0R:b956j0s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2d8f91ce9ab2749f9b8c34d7deec90bde0358dd3/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L257)):*
> ```Smalltalk
> 				RobustFile.Delete(path);
> 			// Don't confuse anything with status belonging to source collection.
> 			TeamCollection.TeamCollection.DeleteLocalStatus(destDirName);
> ```

Good catch. 
As an aside, it *pains me* that a class clearly called "S3Client" is used to actually manipulate files in a semantic way like this.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4348)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Book/BookCompressor.cs, line 30 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4348#-MXn1hQ_3nTM5ESYnelg:-MXn1hQ_3nTM5ESYnelh:b-1qaoy3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2d8f91ce9ab2749f9b8c34d7deec90bde0358dd3/src/BloomExe/Book/BookCompressor.cs#L30)):*
> ```Smalltalk
> 
> 		// these files (if encountered) won't be included in the compressed version
> 		internal static readonly string[] ExcludedFileExtensionsLowerCase = { ".db", ".pdf", ".bloompack", ".bak", ".userprefs", ".wav", ".bloombookorder", ".map", ".status" };
> ```

This is a leakage out of TC.  See idea below.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4348)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/Book/BookCompressor.cs, line 30 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4348#-MXn1hQ_3nTM5ESYnelg:-MXqiYJE5gRUngeURfVA:bu8f5ly) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2d8f91ce9ab2749f9b8c34d7deec90bde0358dd3/src/BloomExe/Book/BookCompressor.cs#L30)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This is a leakage out of TC.  See idea below.
</blockquote></details>

It turned out a bit trickier because this is not used for deletions. I think I've done what you want as far as the status file is concerned; but I haven't tried to figure out what else might be common to all these callers and could move into the new method.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 1110 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4348#-MXn0GOz93tx09gPZ6so:-MXqjGbsAE8GwdFSsXOo:bkn74ia) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2d8f91ce9ab2749f9b8c34d7deec90bde0358dd3/src/BloomExe/TeamCollection/TeamCollection.cs#L1110)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think it's worth being more abstract; other code has *no business* knowing about status. But it is reasonable to know that maybe there is something that a book should do to prepare itself for going *elsewhere*, be that S3, bloomd, bloom pack, etc.

Conceptually, the book itself or Storage, should have a method to do this. Something like `BookStorage.RemoveLocalOnlyFiles()`.  That code could then call  something like`TC.RemoveTCSpecificFiles()` ?  

Note, the code that prepares books for epub, bloompub, etc. may also need to call the book on the method?
</blockquote></details>

I believe the epub code extracts what it wants and will just ignore the status file. One of the changed methods is part of creating Bloompubs.
___
*[src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, line 257 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4348#-MXn-yPL56weSW8w9L0Q:-MXqj9fX4rtsKeaiQ4OT:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2d8f91ce9ab2749f9b8c34d7deec90bde0358dd3/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L257)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Good catch. 
As an aside, it *pains me* that a class clearly called "S3Client" is used to actually manipulate files in a semantic way like this.

</blockquote></details>

Done.

**Review by hatton — APPROVED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4348)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, line 257 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4348#-MXn-yPL56weSW8w9L0Q:-MXqzWOv-B8fdQBzY51I:bb6mt9b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2d8f91ce9ab2749f9b8c34d7deec90bde0358dd3/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L257)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:+1:

**Pull request merged**
