### PR TITLE
Allow for long-running actions (BL-12568)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6236)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Draft because it must be merged after the azure function change (PR pending)

**Review by JohnThomson — COMMENTED** [review]
One minor suggestion.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6236#-:-NlAR4GF1rBQFhe8N3ZX:b-38b9fk)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs` line 90 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6236#-NlAMk7638vwzkDx0olt:-NlAMk7638vwzkDx0olu:bn9leda) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/38757028244828d54ad0f69135a77c507ccc9c34/src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs#L90)):*
> ```Smalltalk
> 				catch
> 				{
> 					handleError?.Invoke(response);
> ```

Could we make handleError take a message as well as a response, so that we could make the log contain not just an (at first sight) success response, but  more like "upload-start: status response did not contain valid data".
Possibly we might want to log the exception, too.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6236)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs` line 90 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6236#-NlAMk7638vwzkDx0olt:-Nlidz4x49P5hpPKP8pu:b-9w1d5f) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/38757028244828d54ad0f69135a77c507ccc9c34/src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs#L90)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Could we make handleError take a message as well as a response, so that we could make the log contain not just an (at first sight) success response, but  more like "upload-start: status response did not contain valid data".
Possibly we might want to log the exception, too.
</blockquote></details>

The logging of the response does start with 
"BloomLibraryBookApiClient call to {apiEndpoint} failed"

But it is a good point about logging specific messages and exceptions.

I switched it to the other way of doing things (letting the base method throw). It has its own ugliness, though.

Open to further improvements.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6236)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
