### PR TITLE
Mark Bloom LargeAddressAware (BL-9120)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4091)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
Thinking that before we merge this, we should discuss as a team, and plan to all...especially Colin...configure our systems for top-down memory allocation.
Have you done some smoke testing yourself with this set?

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4091#-:-MMwWPKJAhWA2AEdZRNy:b-yl4y42)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomExe/BloomExe.csproj, line 1429 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4091#-MMwVWRA6NSc-A42FMnJ:-MMwVWRA6NSc-A42FMnK:bo3uwsn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/31da9aaa9e48288e239e621098e75718bd02fe3b/src/BloomExe/BloomExe.csproj#L1429)):*
> ```XML
>     <Error Condition="!Exists('..\..\packages\LargeAddressAware.1.0.5\build\LargeAddressAware.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\LargeAddressAware.1.0.5\build\LargeAddressAware.targets'))" />
>   </Target>
>   <Import Project="..\..\packages\LargeAddressAware.1.0.5\build\LargeAddressAware.targets" Condition="Exists('..\..\packages\LargeAddressAware.1.0.5\build\LargeAddressAware.targets')" />
> ```

Guessing both of these might need to be Windows-only?

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4091)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/BloomExe.csproj, line 1429 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4091#-MMwVWRA6NSc-A42FMnJ:-MMwarp52S3xkLuEf5xT:b-w899n8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/31da9aaa9e48288e239e621098e75718bd02fe3b/src/BloomExe/BloomExe.csproj#L1429)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Guessing both of these might need to be Windows-only?
</blockquote></details>

uhm... dunno, but based on my reserach, it seems unnecessary on Linux.

**Review by sujeffreyl — COMMENTED** [review]
Yes, i smoke tested it myself

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4091#-:-MMwbC7wCWBOHB1BeChs:b-fc1mxw)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4091)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Pull request merged**
