### PR TITLE
BL-970: Some png images are not loaded correctly by Mono

### PR DESCRIPTION
**Pull request by phillip-hopper**
This will fix the problem reported by the user in https://jira.sil.org/browse/BL-970 but the underlying cause, a bug in libgdiplus, causes the same problem in the Palaso ImageToolbox which calls Image.FromFile(path).

### CODE REVIEW

**Comment by sillsdevgerrit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.lsdev.sil.org//job/GitHub-Bloom-Wrapper-debug/212/
Test PASSed.

**Comment by JohnThomson** [comment]
Did you catch the comment in flowdock where Steve caught a libgdiplus bug that Neil recently introduced related to images?

**Comment by phillip-hopper** [comment]
@JohnThomson Yes, I saw it. I looked at the libgdiplus code, but I don't know enough about image processing to be able to understand it at this time. I'll have to punt on that part of the bug.

**Comment by JohnThomson** [comment]
Yes, but assuming Neil or Steve fixes the libgdiplus bug, are you sure this fix is still desirable? Should we wait and see?

**Pull request closed without merging**
