### PR TITLE
Check font metadata consistently for upload and ePUB (BL-10389)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
Also distinguish between font license problem and font format problem.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085)* status: all files reviewed, 11 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/FontProcessing/FontMetadata.cs, line 446 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-Mzw2cTx1wZ9k8SCGOwx:-Mzw2cTx1wZ9k8SCGOwy:b-48u2bf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/FontProcessing/FontMetadata.cs#L446)):*
> ```Smalltalk
> 			extension = null;
> 			return false;
> 		}
> ```

Seems awkward to rely on the message for this.
Can we use determinedSuitability to know it is an unsupported format? (here and in tsx)
And add a new property called fileExtension?
___
*[src/BloomExe/Publish/PublishHelper.cs, line 535 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-Mzvu_Ws3AzfWx3DLHZA:-Mzvu_Ws3AzfWx3DLHZB:b6gec8y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/Publish/PublishHelper.cs#L535)):*
> ```Smalltalk
> 		/// </summary>
> 		public static void CheckFontsForEmbedding(IWebSocketProgress progress, HashSet<string> fontsWanted, IFontFinder fontFileFinder,
> 			string defaultFont, List<string> filesToEmbed, HashSet<string> badFonts)
> ```

Is there any advantage to passing in defaultFont? Both callers use "Andika New Basic" and I don't foresee ever having it be different for different formats. (here and the method below)
___
*[src/BloomExe/Publish/PublishHelper.cs, line 535 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-Mzw1mRa2E-Ydorf__Q5:-Mzw1mRa2E-Ydorf__Q6:b-qdvqc3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/Publish/PublishHelper.cs#L535)):*
> ```Smalltalk
> 		/// </summary>
> 		public static void CheckFontsForEmbedding(IWebSocketProgress progress, HashSet<string> fontsWanted, IFontFinder fontFileFinder,
> 			string defaultFont, List<string> filesToEmbed, HashSet<string> badFonts)
> ```

Do we want to make filesToEmbed and badFonts out params?
___
*[src/BloomExe/Publish/PublishHelper.cs, line 547 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-MzvssTp9lUmQEkbPak8:-MzvssTp9lUmQEkbPak9:bghjanq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/Publish/PublishHelper.cs#L547)):*
> ```Smalltalk
> 			{
> 				var fontFiles = fontFileFinder.GetFilesForFont(font);
> 				var fsTypeOK = fontFiles.Any(); // fonts eliminated by fsType don't have any files recorded
> ```

I'm probably being dense, but I'm not getting what fsType is or how its logic plays in here.



_Code quote:_
```Smalltalk
fsType
```
___
*[src/BloomExe/Publish/PublishHelper.cs, line 559 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-MzvsPBK6a00nDoDniM1:-MzvsPBK6a00nDoDniM2:b-opytj1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/Publish/PublishHelper.cs#L559)):*
> ```Smalltalk
> 							break;
> 						case "unknown":  // default setting
> 							break;
> ```

I think it would be clearer to explicitly set badLicense and missingLicense here.
And I think I would move it down to be the last case statement, perhaps also with a `default:` case.
___
*[src/BloomExe/Publish/PublishHelper.cs, line 563 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-MzvsM9p2OKCgV-KGWBU:-MzvsM9qAMUjzpfNr687:ba8uofn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/Publish/PublishHelper.cs#L563)):*
> ```Smalltalk
> 							badLicense = false;
> 							missingLicense = false;
> 							badLicense = false;
> ```

You're setting `badLicense` twice in this case.
___
*[src/BloomExe/Publish/PublishHelper.cs, line 567 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-MzvtQWBBHOH2BXOM6Gm:-MzvtQWBBHOH2BXOM6Gn:bq902nr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/Publish/PublishHelper.cs#L567)):*
> ```Smalltalk
> 					}
> 				}
> 				var extensionToCheck = fsTypeOK ? Path.GetExtension(fontFiles.First()).ToLowerInvariant() : "";
> ```

I think this would be clearer as something like
```
var badFileType = false;
if (fsTypeOK) {
  var extenToCheck = ...
  badFileType = ...
  if (!badFileType && !badLicense)
  {...
```



_Code quote:_
```Smalltalk
				var extensionToCheck = fsTypeOK ? Path.GetExtension(fontFiles.First()).ToLowerInvariant() : "";
				var badFileType = fsTypeOK && !FontMetadata.fontFileTypesBloomKnows.Contains(extensionToCheck);
				if (fsTypeOK && !badFileType && !badLicense)
				{
```
___
*[src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, line 275 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-Mzw0zLf01mGKMEORcMf:-Mzw0zLf01mGKMEORcMg:b-sszujj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L275)):*
> ```Smalltalk
> 		private static Dictionary<string, FontMetadata> _fontMetadataMap;
> 
> 		private void ReportInvalidFonts(string destDirName, IEnumerable<string> languagesToInclude, IProgress progress)
> ```

It doesn't feel like this font logic belongs in BloomS3Client.
___
*[src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, line 278 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-Mzw0vKdCKTopMDqvaeD:-Mzw0vKdCKTopMDqvaeE:b-g24sb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L278)):*
> ```Smalltalk
> 		{
> 			// For ePUB and BloomPub, we can display the book to determine exactly which fonts are
> 			// actually used.  We can't do that for uploads, so we scan css files and the styles
> ```

Technically, there's nothing stopping us, right?



_Code quote:_
```Smalltalk
We can't do that for uploads
```
___
*[src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, line 314 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-Mzw0Vzv1Gf2juRTg35E:-Mzw0Vzv1Gf2juRTg35F:b-ib33hp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L314)):*
> ```Smalltalk
> 							//break;
> 						case "unsuitable":
> 							var msgFmt1 = LocalizationManager.GetString("PublishTab.Upload.FontProblem",
> ```

I find myself thinking maybe these l10n ids are too specific. Seems likely we might want to reuse them outside the upload context.
What would you think about `PublishTab.FontProblem` or even `Publish.FontProblem`? (and similar for the others)

On the other hand, are there already messages we use for bloompub or epub which we could/should reuse?



_Code quote:_
```Smalltalk
PublishTab.Upload.FontProblem
```
___
*[src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, line 320 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-MzvzUW47mJIbadFuxka:-MzvzUW47mJIbadFuxkb:b-j2d60p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L320)):*
> ```Smalltalk
> 									"Bloom cannot publish ePUBs and BloomPubs with this font's format ({0})."), type) :
> 								LocalizationManager.GetString("PublishTab.Upload.FontProblem.License",
> 									"The metadata inside this font tells us that it may not be embedded for free in ebooks and the web.");
> ```

Technically, this isn't true for "unknown", right?
(the commented `break` means we will show these messages for "unknown" too.



_Code quote:_
```Smalltalk
The metadata inside this font tells us
```

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[DistFiles/localization/en/Bloom.xlf, line 4357 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-N--vcgU00e8BH6uRRux:-N--vcgU00e8BH6uRRuy:bwe4yj9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/27235d8645fadaf50cecbce5b87d9bbd78b10bed/DistFiles/localization/en/Bloom.xlf#L4357)):*
> ```XML
>         <source xml:lang="en">The font's file cannot be processed by Bloom and may be corrupted or not a font file.</source>
>         <note>ID: PublishTab.FontProblem.Exception</note>
>         <note>{0} is replaced by the filename extension of the font (something like ".ttc").  Do not try to translate it.</note>
> ```

Copy/paste error. This string has no param.



_Code quote:_
```XML
{0} is replaced by the filename extension of the font (something like ".ttc").  Do not try to translate it.
```

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @StephenMcConnel)

___
*[src/BloomExe/FontProcessing/FontMetadata.cs, line 446 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-Mzw2cTx1wZ9k8SCGOwx:-MzzqAAs9WVzQhZ_-_St:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/FontProcessing/FontMetadata.cs#L446)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems awkward to rely on the message for this.
Can we use determinedSuitability to know it is an unsupported format? (here and in tsx)
And add a new property called fileExtension?
</blockquote></details>

Done.
___
*[src/BloomExe/Publish/PublishHelper.cs, line 535 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-Mzvu_Ws3AzfWx3DLHZA:-MzztKfk63d4BOKvgHds:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/Publish/PublishHelper.cs#L535)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is there any advantage to passing in defaultFont? Both callers use "Andika New Basic" and I don't foresee ever having it be different for different formats. (here and the method below)
</blockquote></details>

Done.
___
*[src/BloomExe/Publish/PublishHelper.cs, line 535 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-Mzw1mRa2E-Ydorf__Q5:-MzztLyP4NMIwlcxVRcD:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/Publish/PublishHelper.cs#L535)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Do we want to make filesToEmbed and badFonts out params?
</blockquote></details>

Done.
___
*[src/BloomExe/Publish/PublishHelper.cs, line 547 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-MzvssTp9lUmQEkbPak8:-MzzwbR9CHx5s2Ul7XoB:bk8xr5d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/Publish/PublishHelper.cs#L547)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm probably being dense, but I'm not getting what fsType is or how its logic plays in here.
</blockquote></details>

I've added some comments at the beginning and renamed fsTypeOK to filesFound in an effort to make things a bit clearer.
___
*[src/BloomExe/Publish/PublishHelper.cs, line 559 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-MzvsPBK6a00nDoDniM1:-MzzxD9W4GfTs3USH3o2:b-81ipdy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/Publish/PublishHelper.cs#L559)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think it would be clearer to explicitly set badLicense and missingLicense here.
And I think I would move it down to be the last case statement, perhaps also with a `default:` case.
</blockquote></details>

Part of the trickiness here is that the variable need to be set even when _fontMetadataMap.TryGetValue() returns false, so the initial values are set to handle that case.
I've rearranged the code a bit and added some commentary.
___
*[src/BloomExe/Publish/PublishHelper.cs, line 563 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-MzvsM9p2OKCgV-KGWBU:-Mzzwo5w880YBEiSFLsd:b-qssebl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/Publish/PublishHelper.cs#L563)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

You're setting `badLicense` twice in this case.
</blockquote></details>

fixed.
___
*[src/BloomExe/Publish/PublishHelper.cs, line 567 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-MzvtQWBBHOH2BXOM6Gm:-N---SiP8Pt6ArdYcj7W:b-rv7nre) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/Publish/PublishHelper.cs#L567)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this would be clearer as something like
```
var badFileType = false;
if (fsTypeOK) {
  var extenToCheck = ...
  badFileType = ...
  if (!badFileType && !badLicense)
  {...
```
</blockquote></details>

I've rearranged things to be explicit for no metadata being found.
___
*[src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, line 275 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-Mzw0zLf01mGKMEORcMf:-Mzzwz5jA0A3l5a73s75:bpf0zcf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L275)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

It doesn't feel like this font logic belongs in BloomS3Client.
</blockquote></details>

I moved the method to PublishHelper.
___
*[src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, line 278 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-Mzw0vKdCKTopMDqvaeD:-N--2WC--p5yJIfz51U_:b-3x00rb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L278)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Technically, there's nothing stopping us, right?
</blockquote></details>

I rephrased and expanded the comment.  Now that I think about it, I'm not sure BloomPub font embedding is necessarily finding all the fonts for multi-language books.
___
*[src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, line 314 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-Mzw0Vzv1Gf2juRTg35E:-N--K1ikBi-ZDUwyx4wq:b4ezbff) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L314)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I find myself thinking maybe these l10n ids are too specific. Seems likely we might want to reuse them outside the upload context.
What would you think about `PublishTab.FontProblem` or even `Publish.FontProblem`? (and similar for the others)

On the other hand, are there already messages we use for bloompub or epub which we could/should reuse?
</blockquote></details>

I dropped the .Upload in the middle of the ids.
The flavor of the messages for ePUB and BloomPub are somewhat different as they are being displayed as progress in putting together the artifact.  These messages are warning of limitations in uploaded books.
___
*[src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, line 320 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-MzvzUW47mJIbadFuxka:-N--2nD77CYCaVBlM7DN:b-tpi00j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L320)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Technically, this isn't true for "unknown", right?
(the commented `break` means we will show these messages for "unknown" too.
</blockquote></details>

The break shouldn't have been commented.  :-)

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, line 278 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085#-Mzw0vKdCKTopMDqvaeD:-N-02U0F6H7-qQ72eYiC:be35k1z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2163144fdc426fe5ea82f1546af5b41b0e1d2a64/src/BloomExe/WebLibraryIntegration/BloomS3Client.cs#L278)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I rephrased and expanded the comment.  Now that I think about it, I'm not sure BloomPub font embedding is necessarily finding all the fonts for multi-language books.
</blockquote></details>

Thanks. Will you raise this in our meeting tomorrow, please?

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
