### PR TITLE
BL-4788 Cache language 2 and 3

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/1753)

### CODE REVIEW

**Comment by gmartin7** [comment]
:lgtm: Assuming, as you say, that this is safe because we reload everything, I like it! These, of course, represent what the Book xml contains, as opposed to what the collection settings contain, but what you're doing here seems safe enough.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1753#-:-KppefkRVWW7ArBL7DIH:bf8fxdt)*

**Comment by gmartin7** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1753)*

**Comment by andrew-polk** [comment]
I believe the goal here is to investigate BL-4823 and possibly not implement this code.

**Comment by JohnThomson** [comment]
Yes, that's the plan

**Comment by andrew-polk** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomdesktop/1753#-:-KqzUBtPf2FSQ_HMgtcJ:bnfp4nl)*

**Pull request merged**
