### PR TITLE
BL-9320 Add widget page to Activity section

### PR DESCRIPTION
**Pull request by gmartin7**
* for Add Page dialog

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4167)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4167)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomBrowserUI/templates/template books/Activity/customWidgetPage.pug, line 2 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4167#-MS_5pJw5SozWyHu1-MR:-MS_5pJw5SozWyHu1-MS:bkkew0j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3ca0240c231cb65a8f5bd89c968c13d71d5f2f87/src/BloomBrowserUI/templates/template books/Activity/customWidgetPage.pug#L2)):*
> ```Pug
> mixin customWidgetPage
> 	+page("Widget Page", "An interactive page with an independently developed javascript activity.").custom-widget-page.customPage.bloom-interactive-page.enterprise-only.numberedPage#3a705ac1-c1f2-45cd-8a7d-011c009cf406(data-page='extra' data-analyticsCategories="widget")
> ```

What would you say about

"A page where you can import an HTML5 widget that readers can interact with"  ?

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4167)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomBrowserUI/templates/template books/Activity/customWidgetPage.pug, line 2 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4167#-MS_5pJw5SozWyHu1-MR:-MScUKB62F0XFxMwAT9s:bs4grzp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3ca0240c231cb65a8f5bd89c968c13d71d5f2f87/src/BloomBrowserUI/templates/template books/Activity/customWidgetPage.pug#L2)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

What would you say about

"A page where you can import an HTML5 widget that readers can interact with"  ?
</blockquote></details>

I believe 
"A page where you can import an HTML5 widget which readers can interact with"
is technically better.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4167)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/templates/template books/Activity/customWidgetPage.pug, line 2 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4167#-MS_5pJw5SozWyHu1-MR:-MScaUzy-w8_hQ3Ovuq8:b32v57) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3ca0240c231cb65a8f5bd89c968c13d71d5f2f87/src/BloomBrowserUI/templates/template books/Activity/customWidgetPage.pug#L2)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I believe 
"A page where you can import an HTML5 widget which readers can interact with"
is technically better.
</blockquote></details>

+1

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4167)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomBrowserUI/templates/template books/Activity/customWidgetPage.pug, line 2 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4167#-MS_5pJw5SozWyHu1-MR:-MScxK4J-I8o1JhMbP0B:bo0h0wr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3ca0240c231cb65a8f5bd89c968c13d71d5f2f87/src/BloomBrowserUI/templates/template books/Activity/customWidgetPage.pug#L2)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

+1
</blockquote></details>

How about "... with which readers can interact"

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4167)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @hatton)

___
*[src/BloomBrowserUI/templates/template books/Activity/customWidgetPage.pug, line 2 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4167#-MS_5pJw5SozWyHu1-MR:-MSd0Ga246POWMXXCdkx:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3ca0240c231cb65a8f5bd89c968c13d71d5f2f87/src/BloomBrowserUI/templates/template books/Activity/customWidgetPage.pug#L2)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

How about "... with which readers can interact"
</blockquote></details>

Done.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4167)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @hatton)

___
*[src/BloomBrowserUI/templates/template books/Activity/customWidgetPage.pug, line 2 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4167#-MS_5pJw5SozWyHu1-MR:-MSd80Gu14MrA34-672Z:b-irzen7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3ca0240c231cb65a8f5bd89c968c13d71d5f2f87/src/BloomBrowserUI/templates/template books/Activity/customWidgetPage.pug#L2)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

switched to more natural, less "correct" English. :laughing:

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4167)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Pull request merged**
