### PR TITLE
BL-9844 Kyrgystan ePub back cover

### PR DESCRIPTION
**Pull request by gmartin7**
* include xmatter css in ePub (generally)
* fix BookCompressor to NOT make images transparent
   that already have transparency
* fix ePub credits page

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4394)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4394)* status: all files reviewed, 4 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less, line 437 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4394#-MZ-mq9c7v4GTPTQwtu0:-MZ-mq9d1-a-OE0McYHN:bbwlmpj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ddb29841c4343ba652b4a9a7ca50f4642740dc08/src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less#L437)):*
> ```
>     div {
>         width: unset !important; // yes! all of them!
>     }
> ```
Deserves more "why" in the comment.
___
*[src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less, line 440 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4394#-MZ-msIm24v8Ev1qJfCN:-MZ-msIm24v8Ev1qJfCO:b-zhfxel) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ddb29841c4343ba652b4a9a7ca50f4642740dc08/src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less#L440)):*
> ```
>     .marginBox {
>         width: calc(100% - 30px); // leave room for left/right arrows
>     }
> ```
I'm dubious about this.
1. It doesn't seem like we should be changing the layout/display of the page based on the reader's controls.
2. Each reader will have different controls.
___
*[src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less, line 445 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4394#-MZ-muKp31RNEAuMAbC6:-MZ-muKp31RNEAuMAbC7:bn8wslb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ddb29841c4343ba652b4a9a7ca50f4642740dc08/src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less#L445)):*
> ```
>     .ISBNContainer {
>         display: none !important;
>     }
> ```
Is there a way to do this only when there isn't content?
___
*[src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less, line 456 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4394#-MZ-mFRAAd7KJqCtH0te:-MZ-mFRAAd7KJqCtH0tf:bvra6me) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ddb29841c4343ba652b4a9a7ca50f4642740dc08/src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less#L456)):*
> ```Less
>         }
>     }
> }
> ```

Have you tested all of this on any other readers besides our preview?
The one JH has been talking about the last couple days, for example.
I know in the past, we have found that epub readers ignored things like display:none, etc.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4394)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less, line 437 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4394#-MZ-mq9c7v4GTPTQwtu0:-MZE-rmQ0WXGG6LA32Da:b3wn0z2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ddb29841c4343ba652b4a9a7ca50f4642740dc08/src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less#L437)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
>     div {
>         width: unset !important; // yes! all of them!
>     }
> ```
Deserves more "why" in the comment.
</blockquote></details>

Deleted this rule. Found a better way.
___
*[src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less, line 440 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4394#-MZ-msIm24v8Ev1qJfCN:-MZE-xU8BHrw1OblMUTi:byl1n28) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ddb29841c4343ba652b4a9a7ca50f4642740dc08/src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less#L440)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
>     .marginBox {
>         width: calc(100% - 30px); // leave room for left/right arrows
>     }
> ```
I'm dubious about this.
1. It doesn't seem like we should be changing the layout/display of the page based on the reader's controls.
2. Each reader will have different controls.
</blockquote></details>

Deleted this rule. Found a better way. ;)
___
*[src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less, line 445 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4394#-MZ-muKp31RNEAuMAbC6:-MZE7-gB1QYbmPlo5Cmb:bj8ujfa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ddb29841c4343ba652b4a9a7ca50f4642740dc08/src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less#L445)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
>     .ISBNContainer {
>         display: none !important;
>     }
> ```
Is there a way to do this only when there isn't content?
</blockquote></details>

Discovered a bug. PublishHelper.RemoveUnwantedContentInternal() is supposed to be removing these already (see `BloomBrowserUI\publish\epubVisibility.less`), but it's not working! Had to add "!important" to both rules in `epubVisibility.less`.
___
*[src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less, line 456 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4394#-MZ-mFRAAd7KJqCtH0te:-MZDwCF75dUnxzBv9pmZ:ba76zn5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ddb29841c4343ba652b4a9a7ca50f4642740dc08/src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less#L456)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Have you tested all of this on any other readers besides our preview?
The one JH has been talking about the last couple days, for example.
I know in the past, we have found that epub readers ignored things like display:none, etc.
</blockquote></details>

Tested on eKitabu on desktop and on my phone. No substantial differences from Readium.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4394)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less, line 456 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4394#-MZ-mFRAAd7KJqCtH0te:-MZEPdA03tr6MuTPgKpz:b-b3o6p2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ddb29841c4343ba652b4a9a7ca50f4642740dc08/src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less#L456)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Tested on eKitabu on desktop and on my phone. No substantial differences from Readium.
</blockquote></details>

eKitabu Acknowledgments state: "... is based on Readium R2..."

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4394)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
