### PR TITLE
Fix check for max number of sentences in a book (BL-9885)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4441)

### CODE REVIEW

**Comment by andrew-polk** [comment]
___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, line 1266 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4441#-M_84o3h-xTBElZgS5sb:-M_84o3h-xTBElZgS5sc:b-wkbu8x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/31e9f2970357c69fda1bad15b4916ea01ddfe3da/src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts#L1266)):*
> ```XML
>         this.updateActualCount(
>             ReaderToolsModel.maxSentenceLengthInBook(sentenceFragmentsByPage),
>             this.maxWordsPerSentenceOnThisPage(),
> ```

I know this isn't part of this card, but it looks like this is wrong, too?

**Comment by andrew-polk** [comment]
___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, line 1266 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4441#-M_84o3h-xTBElZgS5sb:-M_866bg5L29jyDbfJQb:b4m3v5o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/31e9f2970357c69fda1bad15b4916ea01ddfe3da/src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts#L1266)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I know this isn't part of this card, but it looks like this is wrong, too?
</blockquote></details>

I also haven't been able to convince myself that the third attribute which doesn't have a max (Word Lengths : max in book) is correct either.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4441)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, line 1266 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4441#-M_84o3h-xTBElZgS5sb:-M_LxpQrAhOrQrF3hCO9:b-dm4net) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/31e9f2970357c69fda1bad15b4916ea01ddfe3da/src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts#L1266)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I also haven't been able to convince myself that the third attribute which doesn't have a max (Word Lengths : max in book) is correct either.
</blockquote></details>

Neither the Maximum Words per Sentence nor the Maximum Letters per Word depend on the number of pages in the book.  The maximum sentence length (or word length) allowed in the book is the same as the maximum allowed in any given page.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4441)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

___
*[src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, line 1266 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4441#-M_84o3h-xTBElZgS5sb:-M_M2rZn-lPDA1d_N_HR:b-yznzck) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/31e9f2970357c69fda1bad15b4916ea01ddfe3da/src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts#L1266)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Neither the Maximum Words per Sentence nor the Maximum Letters per Word depend on the number of pages in the book.  The maximum sentence length (or word length) allowed in the book is the same as the maximum allowed in any given page.
</blockquote></details>

Well, I've overspent my budget on trying to make sense of it. I think the UI and/or some methods names could use changing. But that is all unrelated to the task, I guess.

**Pull request merged**
